### ISSUE TITLE
Review of AntConc

### ISSUE THREAD

**Issue by sieczkiewicz** [programminghistorian/jekyll#100]
This tutorial was clear, interesting and fun. It addresses an audience consistently throughout. The level of detail is appropriate. It is full of screenshots which help the reader follow along; occasionally I wanted more and noted this in the lesson. On a couple of occasions, I was confused by differences between the current version of Antconc and the version used in the screenshots. I also noted this in the lesson.

The introduction is clear, the learning outcomes are relevant (though i made one minor suggestion in the lesson). The specific skill level of the intended audience isn't made clear, but the references to Voyant and Python suggest it is intended for those with at least minimal experience using DH tools.
  
The early steps (downloading a corpus, downloading Antconc) are described in more detail than later steps (starting with *Basic Analysis*), but to me this felt like a natural shift as I got more comfortable using Antconc.

The section headings describe the sections clearly and are place at appropriate intervals. It seems like a long lesson at first, but that's because of the screenshots. I don't think it's too long. 

The conclusion suggests ways in which corpus analysis might be useful to different types of research.

**Comment by fredgibbs** [comment]
comments have been incorporated into final version 9e2ebce..c4285f9
