### ISSUE TITLE
Lesson "Getting Started with Topic Modeling and MALLET" - small bugs

### ISSUE THREAD

**Issue by hennyu** [programminghistorian/jekyll#1000]
Hi, 
while translating the lesson "Getting Started with Topic Modeling and MALLET" into Spanish, I noticed a few typos that could be corrected in the English text:
- In the section "Typing in MALLET Commands": A double hyphen (as with –help above) -> there should be two single hyphens before the parameter name "help" instead of one long one: --help
- The same typo in the section "Your first topic model" : type bin\mallet train-topics –help at the prompt. -> should be: --help
- Last sentence in the same section: In general, including –optimize-interval leads to better topics. -> should be: --optimize-interval
Best regards,
Ulrike

**Comment by ianmilligan1** [comment]
Thanks! Let me take a look at this from the English side - look forward to a pull request.
