### ISSUE TITLE
Spanish Technical Team member

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1009]
I think we need a member of the Spanish Team to take on a role as a member of the Technical Team. We relied very heavily on @arojascastro for answering questions and checking over pull requests. And now that he's on sabbatical, it's clear we have a need for someone to step into that role.

Is anyone on the current team willing to do so, maybe again on a 1 year basis like we have done with other posts. Or if not, can the search committee add this to the role they're seeking to fill?

At the minute we can't approve pull requests that have Spanish in them.

**Comment by jenniferisasi** [comment]
@acrymble, first, sorry I haven't been able to check on the pull requests with Spanish this week. 
I don't think it would be a good idea to put this role in the search for now, as getting into the flow has a learning curve and could put things in the slow for a bit. I guess I can take on the role.

**Comment by acrymble** [comment]
@jenniferisasi thanks, if you're happy with that, that would be great. Let's go with a 1-year basis for now. Then we can assess if it's ok or if we need to reconsider it.
