### ISSUE TITLE
Figure and equation numbers and references

### ISSUE THREAD

**Issue by tomduck** [programminghistorian/jekyll#101]
Re: "Sustainable Authorship in Plain Text using Pandoc and Markdown"

In case it is of interest, figure & equation numbers and references -- essential for academic writing in the sciences -- are now possible with pandoc via the [pandoc-fignos] and [pandoc-eqnos] filters.

[pandoc-fignos]: https://github.com/tomduck/pandoc-fignos
[pandoc-eqnos]: https://github.com/tomduck/pandoc-eqnos

**Comment by fredgibbs** [comment]
very glad to hear of this--thank you for the notification!

On Wed, Jun 3, 2015 at 1:38 PM, Thomas J. Duck <notifications@github.com>
wrote:

> Re: "Sustainable Authorship in Plain Text using Pandoc and Markdown"
>
> In case it is of interest, figure & equation numbers and references --
> essential for academic writing in the sciences -- are now possible with
> pandoc via the pandoc-fignos <https://github.com/tomduck/pandoc-fignos>
> and pandoc-eqnos <https://github.com/tomduck/pandoc-eqnos> filters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/101>.
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by ianmilligan1** [comment]
We could put a short note to this effect in the "Useful Resources" section, perhaps? What does @denten think?

**Comment by denten** [comment]
Hmm.. Interesting and useful! I think rather than updating this tutorial every time that pandoc advances (this filter is described as a "transitional package" for example) we should take a more modular approach. Think of this as "Pandoc Basics." At some point it would be nice to add "intermediate"  and "advanced" pandoc tutorials that go into filters. These would be much easier to keep up to date than one large master tutorial.

**Comment by ianmilligan1** [comment]
Agreed! Trick will be finding somebody to write these lessons (grins) or even then the sometimes lengthy editorial process. Worth exploring a less intensive stopgap measure?

**Comment by acrymble** [comment]
I agree with @denten on this. I don't think we can expect people to add new features (maybe fix broken stuff, but not new features) if they didn't exist when the lesson was written. That's why things have publication dates.

**Comment by fredgibbs** [comment]
ditto. i think it creates the possibility for something like
sub-lessons--kind of like mini-tutorials attached to the main, original
lessons to show how to do something that's new. that way we can cover the
new functionality in a very quick and compact way without the editorial
burden of extensively revising an existing lesson (although, if an author
wanted to do that, i wouldn't be opposed to it).

On Wed, Jun 24, 2015 at 10:22 AM, Adam Crymble <notifications@github.com>
wrote:

> I agree with @denten <https://github.com/denten> on this. I don't think
> we can expect people to add new features (maybe fix broken stuff, but not
> new features) if they didn't exist when the lesson was written. That's why
> things have publication dates.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/101#issuecomment-114930871>
> .
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>
