### ISSUE TITLE
Confused by instructions on getting-started-with-github-desktop.md

### ISSUE THREAD

**Issue by An-Old-Hand** [programminghistorian/jekyll#1012]
Hi,

I've been slowly working my way through https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/getting-started-with-github-desktop.md

I'm using Windows and I got as far as "Making changes remotely" and the part which says "We will see the sync button on 'GitHub Desktop'. I'm afraid I can't see a sync button like the one pictured. Is it a Windows/Mac thing maybe? It's at line 274

Cheers

Rachel

**Comment by acrymble** [comment]
Are you reading the live version on the website? Or the markdown file on our repository? The lesson is available here: https://programminghistorian.org/en/lessons/getting-started-with-github-desktop#making-changes-remotely

I didn't edit this lesson, but it might help if you post a screenshot of what you DO see.

**Comment by An-Old-Hand** [comment]
Using the live version on the website. Here's a screenshot of my GitHub desktop. 
![image](https://user-images.githubusercontent.com/43172655/45477521-983db580-b739-11e8-926a-b9a0671327dc.png)
No sign of a sync button (or the pull request one either but that I did find as a menu option). Hope this helps.

**Comment by mdlincoln** [comment]
Thakns for flagging this @An-Old-Hand. Since this lesson was released, GitHub has totally updated their desktop software. The [classic version of GitHub Dekstop for OS X can be downloaded here](https://central.github.com/mac/latest).

We will make a note in the lesson explaining this.

**Comment by An-Old-Hand** [comment]
Thanks for getting back to me. I'm so new to it all I was worried I was missing something.  I did get it to update OK although not sync using the new version. Will carry on with the lesson!

**Comment by arojascastro** [comment]
Unfortunately, the Spanish translation also needs this warning...

**Comment by mdlincoln** [comment]
You're right @arojascastro - I have made a note of that in the pr: https://github.com/programminghistorian/jekyll/pull/1014
