### ISSUE TITLE
Full-text search

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1018]
Based off of the Community Survey - we had several readers note that there's no easy way to search the website to find lessons. Is this possible? If so, is it hard? If not, what's the possibility of us implementing search capabilities?

On a related note - improving browsing and filtering. Some folks noted that it's not always easy to find things under specific filter headings.

**Comment by mdlincoln** [comment]
*ahem* I had a conversation with @ZoeLeBlanc at DH2018 this summer where she said she'd loooove to write a PR that would add full-text search to our site via lunr.js

**Comment by mdlincoln** [comment]
I think it'd be a great addition. There are solutions for doing it with a Jekyll site. My bandwidth would be pretty limited until after the launch of the French translations however.

**Comment by mdlincoln** [comment]
The one hiccup in implementing this would be that the index (a JSON file) is built via a plugin, which isn't supported by GitHub pages. HOWEVER, since our site builds over at Netlify as well, we might be able to point the javascript over to the netlify-generated&published JSON index even as people are still on the pages served by GitHub.

**Comment by drjwbaker** [comment]
(side note: thanks to @alsalin for opening all these issues!)

**Comment by ZoeLeBlanc** [comment]
Just saw this discussion, thanks for remembering @mdlincoln . I'm still interested in helping add a lunr search since I'm using a lot of tutorials in my teaching this semester. One question would be the layout of the search results, but maybe as a first step I could just get the lunr index generating and working with netlify. I could push a branch in the next few weeks if that's helpful, just let me know 😄

**Comment by mdlincoln** [comment]
@ZoeLeBlanc that would be quite cool! Both branch and PR builds will pop up over on https://ph-dev.netlify.com/ on the respective branch/pr subdomains that Netlify does a la https://deploy-preview-1028--ph-dev.netlify.com/ - I bet if you can get the plugin running, it could spit out json at least onto netlify's servers... and then we can go from there :)

**Comment by drjwbaker** [comment]
Re #1034, I'd say this is live but needs a development pathway to be outlined.

**Comment by ZoeLeBlanc** [comment]
I'll be working on this the next few weeks. Please let me know if anyone has any thoughts or ideas. Thanks!

**Comment by ZoeLeBlanc** [comment]
All finished 🎉

**Comment by acrymble** [comment]
I think you meant to close #1079

**Comment by drjwbaker** [comment]
If happy to be involved in this piece of work if you need a less techy person on it.

**Comment by mdlincoln** [comment]
Yes! From 2018-12-20 meeting:

We need to develop user stories to help guide our implementation:
  - what is the pathway for someone entering the site who doesn't know anything about the site and wants to e.g. see pathways, see different categories of lessons
  - what is the pathway for someone who is looking for a specific tech they know has been discussed (e.g. SPARQL) but needs to find the lesson again

other ?s
- does this search run across all lessons? should it be faceted by language?
- searching blog posts / guidelines too? (I'm thinking no, but it's worth asking)

**Comment by drjwbaker** [comment]
- What is the pathway for someone who has just finished a lesson and wants to find another (not necessarily directly related to the one they've done)?

**Comment by ZoeLeBlanc** [comment]
Updates from January meeting: 
-  I'm working with @mdlincoln on technical viability. No rush here but maybe try and have some updates for Feb/March meeting.
- Please comment on this thread if you have ideas about how the search should work. See Matt and James' comments above with some of the considerations for the search.

**Comment by drjwbaker** [comment]
Park until late-April/May to ramp up internal discussion of this. Then work on implementation in mid/late summer.

**Comment by mdlincoln** [comment]
Haven't looked deeply at it, but Ed Summers just posted about FlexSearch as an optimized alternative to lunr -  https://github.com/nextapps-de/flexsearch

**Comment by silviaegt** [comment]
In #1210 @rivaquiroga mentioned the possibility of adding R as a category. Although search options will be very useful, R is a particularly-difficult-to-find-language in full-text search so I also vouch to add it as a filter

**Comment by acrymble** [comment]
@ZoeLeBlanc I believe you said you'd be returnning to this soon. Is that so? Do you need any support?

**Comment by mdlincoln** [comment]
https://github.com/cmu-lib/dhlg/blob/master/_includes/_search-lunr.html

**Comment by ZoeLeBlanc** [comment]
Few updates from our latest call #1521 

I'm going to be trying to implement a language specific search on each of the lessons pages, which means that you'll only get search results in the language you select. 

I'm also going to be testing out @mdlincoln's approach from the DHLG https://github.com/cmu-lib/dhlg/blob/master/_includes/_search-lunr.html which generates Lunr search index without needing to use npm or rake.

Finally, I'm going to be working on integrating the search with the current filter architecture on the lessons pages, which might require some changes in the current code.

Hoping to get some code pushed up by the end of the week 😊

**Comment by mdlincoln** [comment]
@ZoeLeBlanc hello, could you put up a progress report by the end of the week? We should try and put a deadline on getting a test branch up so we can start to evaluate it.

**Comment by ZoeLeBlanc** [comment]
sure thing! I'll try to have it up by Thursday and sorry for the delay!

**Comment by ZoeLeBlanc** [comment]
Hey everyone! Really sorry but giving a talk this week + job interviews means I'm just a bit behind. Any chance I can get this in by the end of next week instead @mdlincoln ?

**Comment by mdlincoln** [comment]
@ZoeLeBlanc sure, if you think that's going to be do-able on your part. Best to figure out a deadline that makes sense rather than an arbitrary date. Let me know.

**Comment by mdlincoln** [comment]
Also flagging #1590 here as well, since the full text index generation will also impact build times - we may be able to do recover some build time by fixing the bad way we've accidentally implemented print styling for the site.

**Comment by acrymble** [comment]
@ZoeLeBlanc do you need any support on this? Is it more difficult than expected?

**Comment by mdlincoln** [comment]
We're having a call in 2 weeks to go over it one-on-one

**Comment by mdlincoln** [comment]
From 2020-03-19 call:

The big bottleneck for creating FTS is generating the textual index object. The pure "Jekyll" way of doing this is to have the user's browser create this index on the fly. However, our texts are too long and numerous - this caused our browsers to hang and crash.

We sketched out an alternative solution:

1. Generate JSON files in this repo with the unindexed full text of each lesson ([similar to this code](https://gist.github.com/mdlincoln/f325a91386ecf8944dba39e23c9b3c3c))
2. Create a small Node.js app that can pull down that JSON file from the website, create the index, and then post the generated index file (TBD where @ZoeLeBlanc ?) online.
3. Now when the user navigates to the site search page, their browser just has to download the much smaller prebuilt index, without doing any computing.

@ZoeLeBlanc will generate 1 and 2 and a mockup of 3 by the next @programminghistorian/technical-team meeting in April for initial feedback.

**Comment by mdlincoln** [comment]
For hosting the built index, perhaps we just push it to a separate GH pages site? https://docs.travis-ci.com/user/deployment/pages/

**Comment by mdlincoln** [comment]
Also suggest that we use https://docs.travis-ci.com/user/cron-jobs to periodically re-generate the index

**Comment by ZoeLeBlanc** [comment]
@mdlincoln pretty much finished 1 & 2 of the list, but ofc a few unforeseen issues that could use your input 👇 

So for 1. I need the site to actually build the search json files for en, es, fr (though code is now in branch issue-1018), but that will only happen if my PR gets merged in right?

Then for 2. Once I merge in issue-1018, then I need to update the code in the search-index repo to actually read the updated json files (though that should take two minutes to add).

Otherwise cron job is setup on travis and search-index repo is working with to deploy the search indexes 🎉  (can see the file here [https://github.com/programminghistorian/search-index/tree/master/indices](https://github.com/programminghistorian/search-index/tree/master/indices))

Thanks for your help 😊

**Comment by mdlincoln** [comment]
@ZoeLeBlanc Sure, open up a PR from the `issue-1018` branch and I'll review & merge so that you can start the search-index repo off off the live JSON.

**Comment by mdlincoln** [comment]
https://github.com/programminghistorian/jekyll/compare/issue-1018

did something odd happen to the permissions or something on your files? This comparison shows you've touched every single file! Might be better to open a fresh branch and re-do the JSON :/

**Comment by ZoeLeBlanc** [comment]
@mdlincoln super weird that happened but thanks for catching it! I just recreated the branch and files, and made a PR. Thanks!!

**Comment by ZoeLeBlanc** [comment]
so a bit of a crazy update for you @mdlincoln. I hadn't really looked into List.js at all before this (docs are here [https://listjs.com/](https://listjs.com/)) and turns out it has some search functionality already built-in. So I decided to try it out with our current structure and it seems to work 😅. I just pushed up branch search-1018 and if you pull that down, you should be able to search on each language-specific lessons page. Right now I'm searching the abstract, title, and contents of each lesson, but we could switch that up with barely any additional logic. 

Let me know what you think but this might be a lightweight enough solution to use instead of going ahead with Lunr 😄

**Comment by mdlincoln** [comment]
HUH that is... quite impressive! It's like a ctrl-F for the lesson content. Looks like the drawbacks are:

- exact search only, so searching e.g. `principles linked open data` won't return the "Principles of Linked Open Data" lesson
- can't show the keyword-in-context result

But I like that this keeps the architecture super simple and we wouldn't need to go around building indices with a separate service. It also seems to hook nicely into the existing facet buttons.

Make a PR of this so we can all give it a try?

**Comment by ZoeLeBlanc** [comment]
Link to PR  here #1720 

I wrote this in the PR note but a few things to consider/test.

1. List.js does have fuzzy searching but for some reason I get fewer hits. Might be worth it to dig into the code or have others test out fuzzySearch?
2. We could still use Lunr or write our own fuzzy search and then use List.js filtering
3. We could still do keyword-in-context, though that would involve a few more tweaks to the current lesson_describe.html

Let me know if fuzzySearch works for you and I might test writing out the Lunr example with List.js, just so we can compare 😄

**Comment by mdlincoln** [comment]
I think seeing a comparison using the Lunr code would be very useful for the tech team - would you be able to create a separate PR using Lunr instead?

**Comment by mariajoafana** [comment]
This ticket has been open for a while now, are there any pending actions here? The full-text search using listjs ticket is closed, can be close this one too?

**Comment by mdlincoln** [comment]
The active PR is #1726 this issue is very much active
