### ISSUE TITLE
Community Survey Issue: Help for Authors/Reviewers

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1019]
From the survey, it seemed as though most folks thought our guidelines were quite clear but we did receive the following comments from 3 survey participants:

- As a reviewer, it is unclear if I need to reapply after every review, or if I stay in the “pool” indefinitely. I’d like to be able to tell you that I’m available.
- Have a static, downloadable, regularly updated guidebook with a sample tutorial on how to use github that you can direct potential authors to read
- Ya lo he dicho en otra pregunta: más divulgativas, con esquemas, capturas de pantalla para ver los pasos, etc. Que incluyan algún tutorial en youtube, etc.

Are there pieces within this feedback that we could use to improve on our guidelines and instructions?

**Comment by drjwbaker** [comment]
> Have a static, downloadable, regularly updated guidebook with a sample tutorial on how to use github that you can direct potential authors to read

I think we can only do this if we can make a pdf autogenerate every time we add a new commit to the relevant page. In my opinion it is not a good use of our time to keep pdfs on this topic maintained in multiple languages each time we make a tweak to our GitHub workflow (or, indeed, each time GitHub make a tweak to their workflow).

**Comment by acrymble** [comment]
The reviewer question is tricky. I never look who is in the pool. I look for who is an internationally renowned expert in that topic. I don't care if they've signed up to review for us or not. I just send them an email. Maybe that's not clear to people who think they're in a pool. And I imagine what I do isn't consistent with what other editors do.

**Comment by mdlincoln** [comment]
Re: how to use github, I'm always in favor of pointing people to the actual GitHub documentation - we really should not be duplicating it with our own, only adding it details about our specific workflows.

**Comment by drjwbaker** [comment]
We discussed this at #1011. In particular we discussed the fact that we ask for reviewers to join our pool https://programminghistorian.org/en/contribute#join-our-team-of-reviewers but then don't seem to use them. Which means we either need to use them or stop asking for reviewers to join the pool.

**Comment by acrymble** [comment]
I propose removing the section on "join our team of reviewers", and closing this ticket. This simplifies things and removes the expectation that volunteering to do reviews will necessarily result in requests for you to do reviewing.
