### ISSUE TITLE
Community Survey Issue: Different Translation Paths

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1020]
Along the lines of the following comment:
 "It would be great, when you could provide the opportunity to translate articles or parts of articles into one’s native language, without having to commit to become a whole kind of “Special Interest Group Language X” and having to tackle the overhead coming along with this (I imagine most people don’t have the time to become a full-blown translation project within PH. Most imho, however, have the time to translate or improve upon a couple of articles)." 

Do we want to consider different routes for translation at all? We had interest in the following languages emerge from the survey: German, Portuguese, Japanese.

**Comment by drjwbaker** [comment]
Having gone down the route of having an ISSN for each translation project https://github.com/programminghistorian/jekyll/issues/788, ad-hoc translation no longer fits with our infrastructure.

**Comment by acrymble** [comment]
This is something anyone can do because our lessons are published CC-BY. We could address this with a blog post encouraging ad hoc translation.

**Comment by amsichani** [comment]
> This is something anyone can do because our lessons are published CC-BY. We could address this with a blog post encouraging ad hoc translation.

Ad hoc translation of a (part of a ) lesson is a great idea for impact- internationalisation - engagement with PH! I 'd like to contribute to such a blog post!

**Comment by drjwbaker** [comment]
Another thought on this (were ad-hoc translations to somehow fall into our infrastructure): who is responsible for keeping an ad-hoc lesson translation up to date? (that is, if the original language lesson needs to change slightly, then so does the translation, but if we don't have the language skills to make the change, who does it?)

**Comment by acrymble** [comment]
Informally, it's whomever makes the English changes is responsible for finding someone to make the other language changes. It's the same issue we have when changing the about page, for example.

**Comment by drjwbaker** [comment]
Pulled over from email conversion, there are two actions from this issue.

1. a blog post:

- encouraging ad-hoc translation (in sum: lessons are CC-BY so go ahead!) 
- underscoring the effort + commitment + policy it takes to integrate a full translation initiative as justification for why we can’t/won't take all translations in house 
- showcasing examples & uses ad-hoc translation 
- explaining the procedure

2. assess setting up a workflow / tech reqs for hosting ad-hoc translations

Assigning to @amsichani for now. Anna-Maria: it may be the case that we can close this and set-up two seperate issues for 1 and 2 above, but I'll leave that decision with you 😄

**Comment by amsichani** [comment]
closed now, as #1037 and a blog post are on their way!
