### ISSUE TITLE
Community Survey Issue: In-lesson Navigation

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1023]
A lot of folks seem to use the lessons to learn things for the first time and for reference, as such, I wonder if toying around with in-lesson navigation would be possible to help folks navigate long lessons easier? Fixed-sidebars, for example, with the TOC would be awesome. That may help folks with responses like this to our question on the ease-of-use of lessons: "I mean, mostly. Some of them require a lot of reading through before being able to start, rather than being a step by step how to to help people."

**Comment by drjwbaker** [comment]
On fixed sidebars, something like https://citation-file-format.github.io/1.0.3/specifications/ ?

**Comment by alsalin** [comment]
I like the flow of that page, though the sidebar doesn't stay fixed (maybe that might be a lot to ask)

**Comment by drjwbaker** [comment]
Yeah, fixed sidebar would be great. I'm assuming - however - that any sidebar would bork mobile (though the info you got on low mobile use may be a reason to deprioritize).

**Comment by drjwbaker** [comment]
Re #1034, perhaps we need a list of 'Would Like to Have' features for future technical development. This would take into account a) our lack of resource and b) that we don't want to forget good ideas. @mdlincoln: would this help planning of technical development?

**Comment by mdlincoln** [comment]
I think proposed technical features are already well-handed by issues.

**Comment by drjwbaker** [comment]
So what is the issue that needs to be opened here?

**Comment by mdlincoln** [comment]
I think... this _is_ the ticket for adding a nav sidebar for lessons?

**Comment by mdlincoln** [comment]
If we need a system for sorting which issues are backlogged vs. actively being worked on, we should use a [project board](https://help.github.com/articles/about-project-boards/) - I'll happily set one up.

**Comment by drjwbaker** [comment]
It *is* but it also isn't likely to be actioned soon, I suspect. So if you think a project board would be useful for parking useful ideas we don't have the capacity to action, let's set one up.

**Comment by mdlincoln** [comment]
OK, i've marked this as backlogged

**Comment by mdlincoln** [comment]
@amsichani mentions this in #1552 . Will discuss within tech team before closing out and moving to our new backlog system.

**Comment by mdlincoln** [comment]
FYI I wonder, what are we adding in addition to the generated Table of Contents for each lesson? Is it still a fixed sidebar with a ToC? 

FYI that can be a tricky thing to implement in Jekyll - the ToC gets autogenerated by the markdown parser, so we don't have fine-tuend control over how it gets rendered, unlike how we can control a lot of the rest of the site display. (sorry, I promise I am not saying no to _everything_, just trying to be honest about work involved versus the perceived benefit to the journal)

**Comment by mdlincoln** [comment]
Shifting to the "new feature" backlog, pending movement on #1552
