### ISSUE TITLE
Mathematical notation rendering in markdown

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1027]
I'm writing a tutorial that needs to properly display mathematical formulae.

I found a site that gave instructions on how to do this (http://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/) but they don't render in my lesson. Is this something we can set up somehow? The alternative is probably a few dozen figures, which is quite messy and problematic because you can't cut and paste them.

**Comment by mdlincoln** [comment]
We do enable mathjax on the site, so this should show up. Please post the markup that you're writing.

**Comment by acrymble** [comment]
I've got quite a lot of it, but here's an example line:

y = \beta_{0} + (\beta_{1}(x_{1}) + (\beta_{2}(x_{2}) + ... + (\beta_{p}(x_{p})

This needs to render properly in both code blocks (```) and in the main text. It's just rendering exactly as I type it at the minute. The file is here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/gravity-model.md

**Comment by acrymble** [comment]
It looks like the special characters might just work if I use them directly rather than the codes. That won't work for the special formatting though, like subscript, etc.

**Comment by mdlincoln** [comment]
Thanks for the example markup Let me take a look locally and see what I can do.

**Comment by mdlincoln** [comment]
When you want the markup to render in the main text,  you need to wrap it with double dollar signs

```
$$y = \beta_{0} + (\beta_{1}(x_{1}) + (\beta_{2}(x_{2}) + ... + (\beta_{p}(x_{p})$$
```

**Comment by acrymble** [comment]
Thanks @mdlincoln I can confirm that this works, but not in code blocks. Only in the running text. I'll adjust my lesson accordingly.
