### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by muggel8378** [programminghistorian/jekyll#1030]
I encountered an error when I tried to navigate to The Programming Historian using this link: [https://programminghistorian.org/lessons/en/creating-mobile-augmented-reality-experiences-in-unity]

**Comment by acrymble** [comment]
Where did you find that link?

**Comment by mdlincoln** [comment]
Thanks for sending this in - however, that's never been a valid or published URL, so I'm afraid the original source must have been in error. You'll find the actual lesson at <https://programminghistorian.org/en/lessons/creating-mobile-augmented-reality-experiences-in-unity>
