### ISSUE TITLE
October Editorial Agenda - 29 October 2018

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1034]
Date TBC - Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - French time. I (@amsichani) will be facilitating the call.

Working agenda follows. Please add by commenting or editing this comment directly.

  - #721 Current Research Projects or Submissions Pending about the Programming Historian.
  - #878 Getting a budget line for PH + progress on  #915 + #948 
  - #836 update on French Translation of infrastructure pages
  - update on recruitment sub committee searches
  - #1056 editor training idea (@acrymble)
  - #901 - Wordcat entry in Spanish (@vgayolrs)
  - Community Survey tickets - who is responsible?
- #1033 - @walshbr

**Comment by drjwbaker** [comment]
I might have the miss this one (long flight that morning). I'll keep you updated.

**Comment by walshbr** [comment]
I'll be there but might be a few minutes late - coming from another meeting w/ our AUL

**Comment by alsalin** [comment]
Mondays at 10 are our regular group meetings, so I can't make it. I'll add any questions/updates here if I have them before hand!

**Comment by jenniferisasi** [comment]
Hi everyone, 

I think we may have an issue... We didn't take into account that daylight change took place yesterday in Europe?  
![screen shot 2018-10-29 at 7 11 41 am](https://user-images.githubusercontent.com/11022533/47649040-ee2fb680-db49-11e8-8f8b-a4093a16f47d.png)

**Comment by drjwbaker** [comment]
Good spot Jennifer!
I won't be there I'm afraid. Flew overnight, not slept yet, bit wonky.
On #878 et al, I have no update since my last group email. If you want to discuss that and report back, please beo

**Comment by walshbr** [comment]
Oof - thanks @jenniferisasi. Given that James and Anna-Maria can't make it I'm going to propose we leave the time at 10:00 AM EST (so asking the European folks to adjust if possible). Looking at the doodle it looks like leaving it at that time would leave five people unchanged. I also wouldn't be able to coordinate the later time. @spapastamkou and @acrymble are the two remaining people in attendance who would be affected. I think there's no good solution on short notice, so going w/ greatest good for greatest number. Hope the two of you will still be able to make it, and I apologize!

**Comment by mariajoafana** [comment]
I’ll have to miss this one as well, I have meetings all morning.

**Comment by jenniferisasi** [comment]
@walshbr I think that's a good plan! Hope they can make it. 
I forgot to mention on my first post, that I can meet 10AM EST for the full hour or 11AM EST for about 30 min.

**Comment by walshbr** [comment]
Follow up -
#721 - @mariajoafana and @jenniferisasi are putting in an ACH abstract.
#836 - French translations are at the point where they are ready to set a time with @mdlincoln to go over next steps.
#901 - i'm going
community survey tickets - going to email the group about this.
