### ISSUE TITLE
workflow for ad-hoc translation

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1037]
The need for a clear workflow for ad-hoc translation resulted from #1020 and I am now working on drafting a text we can host (and probably translate?) on wiki. stay tuned!

**Comment by jenniferisasi** [comment]
Thanks @amsichani for writing the post! I could translate to Spanish if you think it would be useful (I think so).

**Comment by acrymble** [comment]
Is "workflow" the right word here? We aren't going to host these. I thought you were just explaining to people that they could do ad-hoc translations if they wanted to. This sounds much more official to me.

**Comment by amsichani** [comment]
Hi team, sorry for the silence. Here is a draft plan for the ad-hoc translations policy (mainly for wiki use) - blog entry on its way in separate ticket for feedback . Please go ahead with suggestions, ideas. Also, we need some existing examples , if you are aware of any plz to let me know.

In my view and proposal , ad-hoc translations are a spin-off of the PH and they are not (necessarily) need to fit to our infrastructure.  So, in terms of technical reqs @mdlincoln @ZoeLeBlanc , I think we need to explore :
-the option to have the translation as a link in the original lesson's page

-to host the ad-hoc translations (md files mainly) in a separate folder

### Ad hoc translation policy
**How to embark on an ad-hoc translation?**

- Choose a lesson you want to translate in a different language. As a starting point, you can either use the online version of the lesson or the md file from the[ github repo](https://github.com/programminghistorian/jekyll/tree/gh-pages/en/lessons) of the project.

- You can always consult our [Author](https://programminghistorian.org/en/author-guidelines) or [Editor guidelines](https://programminghistorian.org/en/editor-guidelines) to get the spirit of our lessons’ structure, wording and overall style.

- As ad-hoc translations are a spin-off of the PH and they are not (necessarily) need to fit to our infrastructure, the easiest and more obvious way to do it, is to translate it using your own infrastructure and services, in order to fit your original purposes.

1. Once you have a final version of the translated lesson and you want to share it with the project, please do send us the file (preferably if you have a md file). We then going to customize the lesson and upload it as a translation version of the original.

2. If you don’t want to share the translation with us, please do provide us with a bit of information about the translation work itself (translators, institution, publication, purpose) for our own records and do let us know if you want us to place a small note about the translation at the lesson’s page.

**Why to embark on an ad-hoc translation ?**
Here are a couple of ideas 

- As part of your class assignment 
o	students familiarise themselves with the methods- tools in question
o	translation challenges towards terminology 

- As part of an edit-a-thon organised in your country/institution – invite us or let us know!

- As an one – off contribution of a particularly interesting lesson for your local community


**and a couple of examples for ad-hoc translations** 
 @spapastamkou could you please let me know about the Ecole de chartes PH translations?

**Comment by spapastamkou** [comment]
Hey @amsichani, here's some more info that could help. The context of thesee translations is a master called Digital Technologies Applied to History organised by the Ecole nationales des chartes (Paris, France). Her's their github: @Chartes-TNAH
 
What they do: tutorials of the PH (parts or on the whole) are translated by the students from English to French as part of their class assignments for the course of English. 

This started in 2017 and the US teacher of the class contacted the PH to inform of the initiative. The translations were prepared during 2017-2018 but were not published anywhere (no FR version of the PH at the time, no infrastructure). When we were at the point of proposing a FR edition to the PH team last spring, and at the same time trying to set up a FR team, one of the FR contacts was the head of the master TNAH, Thibault Clérice. He immediately proposed to contribute to the initiative with the texts of the students and the contact was taken with the professor. They recently undertook to ask the authorization of the students to use their work for the project and we currently have some texts (finished and unfinished) to work with. Professor Meg Roussel will assign (or already has done so) parts of the unfinished texts to the class of this year and we shall probably have some more advanced texts by mid-December. For the moment, this allows us to test the FR branch and prepare the editorial process for the publications of the tutorials once the web site is on air. 

I hope that helps, if you need further info please do ask.

**Comment by acrymble** [comment]
@spapastamkou I think there is some confusion. These ad hoc translations we're talking about are for languages we don't currently support (Russian, German, Chinese). This isn't to do with French translations.

**Comment by amsichani** [comment]
hi @acrymble, I see your point - but these FR translations, for when they were initially created, they were perfect examples of ad-hoc translation (they contacted PH about their initiative although they didn't want to share them at that point). In my view, the fact that these translations are now going to form the starting point of the FR full language initiative its a welcomed development and a happy/lucky coincidence to an ad-hoc translation initiative. I think actually that an organically developed full language initiative based on ad-hoc translations is after all an interesting case study of the language diversity strategy of the PH - thoughts?
Of course, any other languages ad -hoc translations examples, more than welcome !

**Comment by acrymble** [comment]
You're right that it's a good example, but I think we're confusing things (and incidentally that's how the Spanish initiative started as well - more or less). The purpose of this post, as far as I was aware, was to tell people what to do if they want to do a partial translation in a new language which we don't support. The options are:

a) Pitch a full translation of the project (https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy)
b) Take advantage of the CC-BY license to do a lesson or two on your own and do whatever you like with it.

I don't view a) as 'ad hoc', but I do view b) as 'ad hoc'. I think we should encourage b), but I didn't think we were going to commit any resources to it. I thought that's why we were doing a blog post - to head off the expectation that we'd host these. Am I misreading?

**Comment by spapastamkou** [comment]
If this useful and if it is not already the case, perhaps it would be
interesting for @amsichani to take a look to the message sent at the time
for the FR translations and the discussions of the group that followed. It
gives an interesting insight for what was at the time a case of
spontaneaous ad hoc translations and issues it arose without an infra (and
internal human ressources) existing at the time.

**Comment by amsichani** [comment]
I 'm with you @acrymble and this is what I tried to do at this blogpost, while framing to the language diversity aspect of the project - it seems my attempt wasn't succesful enough. 
Actually the paragraph "Although we are excited that.." describes and underscores the effort of the a) and the rest of the post desrcibes and strongly encourages b). Do you want me to make it more clearer?

Also, in terms of infra, as ad-hoc translations are a spin-off of the PH and they are not need to fit to our own infrastructure and workflow, I suggested 2 options: 

1. if they want to share it with the project, they could send us the translation (preferably as md file) and then we can lightly customize it to fit our layout and upload it as a translated version of the original (with a link on the original). Tech reqs : 
-the option to have the translation as a link in the original lesson's page
-to host the ad-hoc translations (md files mainly) in a separate folder

2. If they don’t want to share the translation with us, we ask for a bit of information about the translation work itself (translators, institution, publication, purpose) for our own records and if they want us to place a small note about the translation at the lesson’s page.

From what you re saying , I am guessing we are not willing to offer the 1) at all? I am happy to amend it, if thats what the team feels.

**Comment by mdlincoln** [comment]
IMO option 1 is completely unsustainable. We aren't a personal blog. If they want to do an english, french, or spanish translation, they go through the regular editorial process.

**Comment by arojascastro** [comment]
I vote for 2 as well. People can translate and publish on different websites if they want, but we cannot commit ourselves to publish something that has not been reviewed according to our standards and mantain it in the long term. It would damage our "brand" (if we have that thing).

**Comment by drjwbaker** [comment]
@arojascastro: we do have that thing.

**Comment by amsichani** [comment]
Many thanks for your useful comments ! I do agree with your overall rationale.  I will update the ad-hoc translation policy (I guess a wiki page will be enough for this) & the blog post #1098 accordingly.

**Comment by amsichani** [comment]
Hey team, many thanks for your productive feedback on this. I 've now updated the blogpost #1098, please go ahead with suggestions. II am also happy if we feel is necessary to move this also to the wiki pages. As agreed also at the Skype meeting yesterday (29-11-2018) , I ll start a ticket/list for keeping track of ad-hoc translations.

**Comment by amsichani** [comment]
hi all, I just wanted to touch base on this - whether we are happy with the blog post text #1098 so we could publish it before holidays.

**Comment by arojascastro** [comment]
Thank you @amsichani - it looks good. Maybe in this paragraph:

> So if you are thinking about starting to translate or you have already translated a Programming Historian lesson to a language different from the ones currently supported by the project, please do let us know!

We could add that we want to keep a record of it and add the bibliographic reference (if available somewhere else online) and provide a link? 

> So if you are thinking about starting to translate or you have already translated a Programming Historian lesson to a language different from the ones currently supported by the project, please do let us know so we can keep a record and point to our readers.

Maybe... but it is up to you :)

**Comment by mdlincoln** [comment]
now published at https://programminghistorian.org/posts/ad-hoc-translation
