### ISSUE TITLE
cannot submit lessons on OS X 10.6.8

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#104]
The instructions to submit a pull request require git to be installed if you need also to upload any images or data files. The suggested git download does not work on OS X 10.6.8 (http://stackoverflow.com/questions/22892890/git-for-mac-fails-to-launch-illegal-instruction) and presents a fairly high barrier to entry for some of our potential authors.

We need to make sure our submission system is useable for everyone so we might need to rethink this.

**Comment by fredgibbs** [comment]
well, that same post shows how to fix the problem. more importantly, it's a
quite old version of OS X at this point, likely minimizing the impact on
potential authors. i agree we should keep barriers to entry low, but i
don't think we have any evidence that this particular issue presents a
significant problem.

On Wed, Jun 10, 2015 at 7:05 AM, Adam Crymble <notifications@github.com>
wrote:

> The instructions to submit a pull request require git to be installed if
> you need also to upload any images or data files. The suggested git
> download does not work on OS X 10.6.8 (
> http://stackoverflow.com/questions/22892890/git-for-mac-fails-to-launch-illegal-instruction)
> and presents a fairly high barrier to entry for some of our potential
> authors.
>
> We need to make sure our submission system is useable for everyone so we
> might need to rethink this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/104>.
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by acrymble** [comment]
Perhaps not, but it does mean anyone on a machine they don't have admin
rights for cannot make a submission.

**Comment by wcaleb** [comment]
In cases where a person can't push files from the command line, could we fall back on our original practice of having an editor do it? The lesson submission itself remains platform independent since it can be done in browser.

**Comment by ianmilligan1** [comment]
I like @wcaleb's idea - we could make that explicit in our documentation?

**Comment by fredgibbs** [comment]
resolved with f0ad9544255b01a84f75ebda0cb0cd51b2cec51f
