### ISSUE TITLE
Getting Started with Topic Modeling and MALLET: URL not up to date

### ISSUE THREAD

**Issue by t-duan** [programminghistorian/jekyll#1050]
Hi there,
the url to Scott Weingarts warnings seems not to be to date. Could you please update the link to the blog post? Thanks a lot for your engagement!
Best regards,
Tinghui

**Comment by mdlincoln** [comment]
Thanks @t-duan - what's the updated url that we should post?

**Comment by mdlincoln** [comment]
The post is accessible just fine - there's just a banner at the top of his site pointing to a new blog for more recent posts.
