### ISSUE TITLE
Adjusting workflow for Spanish Language submissions

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1051]
I bring here a discussion among the Spanish team in order to clarify the workflow for proposal submissions. Here is the step-by-step that @vgayolrs outlined:

1) editor receives lesson proposal following the template according to [#936](https://github.com/programminghistorian/jekyll/issues/936) proposal template. If the editor has doubts (almost always), sends a consultation to the editorial team via email (google-groups). 

2) once there's an agreement among the editorial team, and the editor dialogues with the author, a ticket is opened to announce that the proposal is in the making and the tentative submission date. 

3) Once the lesson is received, the editor will revise it closely and decide if it is ready for revision. Editor can consult with the editorial team if there are any doubts on the quality of the proposal. If the lesson is ready, we'll open a review issue and find reviewers.  

If members in the English team have any comments/suggestions on this step-by-step please let us know

**Comment by acrymble** [comment]
2) You might not get agreement from the editorial board. But you will likely get a sense of whether or not there's enough support to progress.

**Comment by arojascastro** [comment]
> 1. editor receives lesson proposal following the template according to #936 proposal template. If the editor has doubts (almost always), sends a consultation to the editorial team via email (google-groups).

I think there is no conditional here. The Managing editor **always** shares each proposal with the board before opening a ticket. 

I did not ask the board with proposals coming from Bogotá because I thought that that was the agreement and that these proposals were already read by people organizing the workshop.

**Comment by vgayolrs** [comment]
Precisely that exception in [this case](https://github.com/programminghistorian/ph-submissions/issues/190) and [this other](https://github.com/programminghistorian/ph-submissions/issues/185) generated this issue. The first ticket was closed awaiting an editorial decision. The second one is still open but without answers to a review that involves editorial decisions that we should have discussed via the PH email in google-groups.

**Comment by mariajoafana** [comment]
I'm going to post below the revised workflow and close de issue. It can be reopened if needed and can be searched when a new member joins the team.  

1. editor receives lesson proposal following the template according to #936 proposal template. If the editor has doubts (almost always), sends a consultation to the editorial team via email (google-groups). You might not get agreement from the editorial board. But you will likely get a sense of whether or not there's enough support to progress.

2. once there's an agreement among the editorial team, and the editor dialogues with the author, a ticket is opened to announce that the proposal is in the making and the tentative submission date.

3. Once the lesson is received, the editor will revise it closely and decide if it is ready for revision. Editor can consult with the editorial team if there are any doubts on the quality of the proposal. If the lesson is ready, we'll open a review issue and find reviewers.
