### ISSUE TITLE
Editor training idea

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1056]
We have a editorial onboarding checklist to support new editors (https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors).

I thought I'd just raise the idea of a 3-day training residency for new people, as an aspiration. Maybe we could have designated hubs that are fairly well connected (London, Virginia, Bogota, etc) where new editors could come visit one of us for a few days to get to know us and how the project works.

Is this something we'd find valuable? Obviously we'd have to find a way to pay for it, but I wonder if it might not help reduce the time it takes for new editors to really feel part of the team?

**Comment by drjwbaker** [comment]
This feels similar to Carpentries Instructor Training https://carpentries.github.io/instructor-training/

**Comment by acrymble** [comment]
It's been suggested that this could be done effectively online through a few morning skype sessions with an experienced editor.

**Comment by amsichani** [comment]
as decided at #1103 no further action at this point because of lack of financial resources. Alternatively: shadowing milestones (#1149) & a support system for new editors by assigning them a mentor / person of contact during their first editorial task.

**Comment by acrymble** [comment]
I'm closing this because it's been superceded by #1149

**Comment by mariajoafana** [comment]
I'm reopening this issue to continue the conversation about what does shadowing means and what workflows and support mechanisms we can put in place for our editors

**Comment by spapastamkou** [comment]
Technically speaking (yaml or other), is it possible for one lesson to be published under more than one editors? In case one ME, for example, would like to make an editing, in real time, express workshop (one hour or two online) for one lesson that is already in the stock of non-yet-edited lessons; through guiding 1 or 2 new editors step by step and attributing them the role of editors of the lesson. With hopefully one lesson to publish almost right after.
I think though this could be more appropriate, if possible, for translated lessons that would be simple and small.

**Comment by acrymble** [comment]
I don't think this ticket has a clear action, nor does it have a person assigned to it. I propose closing  at #2019 meeting

**Comment by spapastamkou** [comment]
Just a reminder here that #2035 is on an editorial workshop for FR new editors as an idea to avoid delays in organisation of personal shadowing for each.
