### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by VanjulBhatt** [programminghistorian/jekyll#1057]
I encountered an error when I tried to navigate to The Programming Historian using this link: https://programminghistorian.org/lessons/en/creating-mobile-augmented-reality-experiences-in-unity

**Comment by acrymble** [comment]
The link is wrong. https://programminghistorian.org/en/lessons/creating-mobile-augmented-reality-experiences-in-unity

Where did you find that link so we can fix it?

**Comment by VanjulBhatt** [comment]
It was in the AR tutorial saying "Article has been retired. You can find the latest tutorial at the link below"
There is page where i found it:
https://programminghistorian.org/en/lessons/retired/intro-to-augmented-reality-with-unity

**Comment by walshbr** [comment]
Thanks for catching this @VanjulBhatt. @acrymble - I corrected this in #1058. Merging that PR should close this.

**Comment by VanjulBhatt** [comment]
Not a problem @walshbr . Could you guide me to the correct link which might contain this supposed article . Thanks!

**Comment by walshbr** [comment]
The correct links are as follows:

Retired and archived lesson: https://programminghistorian.org/en/lessons/retired/intro-to-augmented-reality-with-unity
Current lesson: https://programminghistorian.org/en/lessons/creating-mobile-augmented-reality-experiences-in-unity

**Comment by VanjulBhatt** [comment]
Thank you @walshbr
