### ISSUE TITLE
missing code / código faltante in/en Spanish translation/traducción al español lesson/lección xml-xsl

### ISSUE THREAD

**Issue by inxochitl** [programminghistorian/jekyll#1059]
I am requiring your attention on the translated lesson / Estoy requiriendo su atención sobre la traducción de la lección

[Transforming Data for Reuse and Re-publication with XML and XSL](https://programminghistorian.org/en/lessons/transforming-xml-with-xsl)

[Transformación de datos con XML y XSL para su reutilización](https://programminghistorian.org/es/lecciones/transformacion-datos-xml-xsl)

In the published spanish version there is a code missing in the section "filtering results". I expected something like

```
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>

<xsl:template match="/">
  <xsl:for-each select="root/record">
    <xsl:if test="date/year='1815'">
      <xsl:value-of select="id"/>
      <xsl:text>&#xA;</xsl:text>
    </xsl:if>
  </xsl:for-each>
</xsl:template>

</xsl:stylesheet>
```

... but in translation is missing.

You can check between lines 347 & 360

The code is in the [translation raw version](https://github.com/programminghistorian/jekyll/blob/gh-pages/es/lecciones/transformacion-datos-xml-xsl.md) , but it is not displayed properly in the published lesson.

Thanks.

**Comment by arojascastro** [comment]
¡Gracias por avisarnos! Procederemos a corregirlo.
