### ISSUE TITLE
Submission Repo previews not updating

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1064]
I am working on a lesson on the Submission Repo and it isn't properly rendering the changes I make to the files:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/gravity-model.md

The last 2 updates have not been updating properly. Note they both have a red x next to them in the 'history', suggesting an issue. But I don't know what the problem is.

https://github.com/programminghistorian/ph-submissions/commits/gh-pages/lessons/gravity-model.md

You can see the preview here, which is 2 commits behind: 

http://programminghistorian.github.io/ph-submissions/lessons/gravity-model

**Comment by walshbr** [comment]
Thanks for pinging @acrymble - I was going to respond again to the other thread this morning. 

Is [this](https://github.com/programminghistorian/ph-submissions/commit/5bfb40d2ab6c1e2ca68241d95494c12b79fe82f7) the commit that is not showing up for you? 

I think it looks like the change there you made to make figure 8 into figure 7 is working for me but I'm not familiar enough with the lesson to know (see screenshot from the preview site). If you let me know what I should be looking for I can investigate further.

<img width="1137" alt="screen shot 2018-10-30 at 9 58 12 am" src="https://user-images.githubusercontent.com/2334220/47723299-9c129200-dc2a-11e8-9c57-3880dda62c9a.png">

If that _is_ how it's supposed to look but it's not showing up for you, I'd bet that it's a caching issue with your browser. Info for bypassing your cache [here](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) - caching issues come up a lot when working with classes making a lot of changes to GitHub and trying to see different builds. 

But if that's not the issue just let me know what to look for and I'll take a look further.

**Comment by acrymble** [comment]
@walshbr thanks for checking. That figure is supposed to be gone as part of the changes.

**Comment by acrymble** [comment]
@walshbr that might be the problem. I think I may have deleted the wrong figure, which is why I'm confused. Let me check.

**Comment by acrymble** [comment]
I'm not sure what you did @walshbr but it seems to be working now. Thanks.
