### ISSUE TITLE
Authors of "Understanding Regular Expressions" and "Cleaning OCR'd text with Regular Expressions" need bios

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#107]
We need to add a bio for Laura Turner O'Hara and Doug Knox to the `authors.yml` file. Relates to #83. All other authors at least have bios, although not sure if up to date or not.

**Comment by acrymble** [comment]
Bios get out of date when people move. I'm not sure that's a problem. It
isn't for the paper journal world.

**Comment by ianmilligan1** [comment]
Agreed - just important that we have something down there. If anything they're neat snapshots of where people were at when they contributed.

If anybody has bios for Laura and Doug handy, that would be great (or their coordinates).

**Comment by acrymble** [comment]
I've added a bio for Doug, but I don't know Laura. I believe @fredgibbs edited that lesson, so perhaps he knows.

**Comment by fredgibbs** [comment]
i sent an email to laura; i'll update the authors file when i hear back.

On Tue, Jun 16, 2015 at 1:48 PM, Adam Crymble <notifications@github.com>
wrote:

> I've added a bio for Doug, but I don't know Laura. I believe @fredgibbs
> <https://github.com/fredgibbs> edited that lesson, so perhaps he knows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/107#issuecomment-112548819>
> .
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by ianmilligan1** [comment]
Just saw that this is now all updated. Closing.
