### ISSUE TITLE
Add one or two translated French lessons

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1072]
On the `french-staging` branch, I have created a directory `fr/lecons` to hold files for translated lessons. Would you be able to add one or two of your translations to this directory? It is alright if they are not fully edited, but I do want to test that French lessons and their images are displaying properly.

**Comment by mpuren** [comment]
We will obtain some translations from the Ecole nationale des chartes. Students have translated some lessons in French for their English class, and their professor will send us soon these texts, and we can make a few tests with them.

**Comment by mpuren** [comment]
A few updates concerning the lessons already translated in French by the Ecole nationale des chartes students:  
- The Ecole des chartes has contacted their students to obtain their agreement to publish the lessons in French.
- There are 4 lessons that have been entirely translated in French: Georeferencing in QGIS 2.0, Cleaning Data with OpenRefine, Creating an Omeka Exhibit, Python Introduction and Installation. As soon we have the translators' agreement (I hope it will be soon), we'll be able to publish them (after reviewing them of course).
- There are 10 lessons that are not entirely translated: Introduction to Mobile Augmented Reality Development in Unity, Linked Open Data, Understanding Regular Expressions (the parts on "Finding structure for rows" and "The General idea of regular expressions", and the beginning of "Defining Segments"), Preserving Research Data, Editing Audio with Audacity, Up and Running with Omeka, Getting Started with Markdown, Exploring and Analyzing Network Data with Python, Web Mapping with Python and Leaflet, Installing Omeka, Python Introduction and Installation.

**Comment by mdlincoln** [comment]
@mpuren thank you for the update. Once you get the agreement, could you put those 4 lessons onto the `french-staging` branch before editing? We can replace them with the edited versions once you are done editing, but I would like to start testing out the French lesson displays as soon as possible.

**Comment by mpuren** [comment]
@mdlincoln : I think @spapastamkou will soon put a first lesson (on OpenRefine) onto the branch.

**Comment by mpuren** [comment]
#[https://github.com/programminghistorian/jekyll/commit/14b7e111b356ac4d599e10decbce68b11163d8b3](url)

**Comment by mpuren** [comment]
@mdlincoln I've put a new lesson onto the `french-staging` branch

**Comment by mpuren** [comment]
@mdlincoln And I'm working on a third lesson ("Building static sites with jekyll and Github Pages). I think I will be able to put it onto the branch next week.

**Comment by acrymble** [comment]
Are these authors willing to go through the review process?

**Comment by spapastamkou** [comment]
The facts are that they authorized the use of their translations for the PH
in FR; and they all have github accounts we can use for a review process.
Maybe before launching a review process, each editor (of us) can contact
the author in order to explain precisely what is to be done and make sure
we have the author's consent for the review. Would that be okay?

**Comment by acrymble** [comment]
I think I'm a bit confused. 

I understand that these lessons have been translated by students. I'm less clear if those students want to go through our submission process and follow through with all of the work that entails. As you can see on our submissions site (https://github.com/programminghistorian/ph-submissions/issues) that's a process that typically takes several months and several rounds of revision.

It isn't clear to me if you intend to peer review these lessons, or if you view them as 'done'. Just for reference, all sub-teams have to follow the same set of peer review guidelines to make sure we're all maintaining the same level of standards. https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy

Let me know if you need support with the peer review process. I see you haven't begun that yet, so we can definitely help explain or initiate it if you need.

**Comment by spapastamkou** [comment]
Oh no, nothing started yet, @acrymble, the question was only raised during November's meeting precisely to see how we can prepare to organize this in time, in view of the FR web site's release, and ask feedback or guidance from the rest of the team.

We have not checked all the lessons yet (some more arrived today) but at least some of them need a considerable editorial work. So I would not say we can consider them as entirely done. If @mpuren was able to check more lessons maybe she can provide further info.

What we planned to do is discuss (also) on that during the first meeting of the @programminghistorian/french-team next week ; and during yesterday's meeting we thought it would be a good idea to talk with the @programminghistorian/spanish-team in a couple of weeks (or more team members if able to). And we can definitely put the subject in the agenda of December's meeting. Perhaps better to open a separate ticket? 

Please also see #1101 for the technical aspects.

**Comment by acrymble** [comment]
ok thanks for clarifying. I'm happy to help if that help is useful.

**Comment by spapastamkou** [comment]
no way for you to escape:) thanx in advance

**Comment by mpuren** [comment]
Thanks @spapastamkou, you have said everything! Concerning the two lessons we’ve received this morning: one is complete (on Jekyll and Github Pages). I have to add the header and to check the Markdown is well defined. But soon @mdlincoln , there will be a third lesson to test the French version

**Comment by mlincoln** [comment]
@mpuren Looks like an interesting project, but I think you meant to tag @mdlincoln

**Comment by mdlincoln** [comment]
OK, thank you. I will close this issue for now since I just needed one or two example lessons to start testing.
