### ISSUE TITLE
Update French translations for team biographies

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1074]
While work was happening on #836 a few author bios have been updated. When I tried to merge these changes, we had a few conflicts, and so I need folks to please review their biographies and check that they're all in sync, and please point out if any translations need to be updated.

We need to compare the `ph_authors.yml` translations in `french-staging` to keep them updated. A few individuals I know have changed:

- @drjwbaker 
- @JMParr 
- @mariajoafana 

However I'm sure there may be a few others I did not spot.

**Comment by drjwbaker** [comment]
I think for me, just was just add 'Senior' to job title, plus https://github.com/programminghistorian/jekyll/pull/1035

**Comment by spapastamkou** [comment]
Will take care of that.

**Comment by spapastamkou** [comment]
At this stage, files should be in sync. Please note that what is not updated in either branch is @mpuren 's bio both in EN and FR and also an ES translation has then to be added. I did not touch to avoid possible conflicts before merging.

**Comment by mpuren** [comment]
Hi @jenniferisasi, could you please translate my bio in Spanish?

**Comment by jenniferisasi** [comment]
Sure @mpuren! I will translate and update the file this weekend.

**Comment by mpuren** [comment]
Thank you @jenniferisasi !

**Comment by jenniferisasi** [comment]
Updated through on pull request #1109 and awaiting review.

**Comment by spapastamkou** [comment]
#1109 has been merged so I close this ticket.
