### ISSUE TITLE
Bogota Event - final blog post

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1080]
We've now got our video recap of the event published and we need to make it more visible. I'll write a blog post once the French infrastructural pages have been published (to avoid syncing conflicts):

https://www.youtube.com/watch?v=iO5aSCZgcKw

This will include an update on the outcomes of the event.

**Comment by mdlincoln** [comment]
@acrymble don't wait for the French publish - new blog posts and new lessons don't interfere with anything.

**Comment by acrymble** [comment]
this has been posted. https://programminghistorian.org/posts/model-workshop
