### ISSUE TITLE
Worldcat entry for FR

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1083]
Post-launch need.

**Comment by spapastamkou** [comment]
I have formerly worked in a library and have contacts with librarians. I will ask if an entry can be created when it's time.

**Comment by acrymble** [comment]
@spapastamkou can you follow up on this now?

**Comment by spapastamkou** [comment]
Yes, I do actually. The answer from the FR library I asked was that the notice should normally be created by the institution that attributes the ISSN (they mentionned the National Library of France but our ISSN comes from the BL). I must contact the BL anyway once the first lessons are published to let them know the publication is on air. So I will ask the question for the notice in this occasion. That should be the case by the beginning of April. I will make un apdate by that time.

**Comment by acrymble** [comment]
Thanks for following up. Our Spanish language entry was created by the University of Virginia library, and our English one by Purdue University. So it can be done by any librarian as far as I'm aware. I just don't work in a library so I can't explain the workflow. You shouldn't have to ask the BL.

**Comment by spapastamkou** [comment]
As far as I can tell I think you are right. I thought I'd ask to the University of Lille's Library as well. But I waited to have some lessons in (even one) before anything.

**Comment by acrymble** [comment]
@walshbr since you've done this before, would you be able to help get a French one too?

**Comment by walshbr** [comment]
I can ask - sure. You just need to ask any metadata librarian, as far as I can tell. That's what I did at UVA - they put together the Spanish one.

**Comment by walshbr** [comment]
I wrote one of our metadata librarians this morning to ask about adding an OCLC record for the French publication. More soon!

**Comment by walshbr** [comment]
Here ya go - https://uva.worldcat.org/title/programming-historian-en-franais/oclc/1104391842 - let me know if anything is missing or needs to be added? Otherwise this ticket can probably be closed once the info there gets added to the contribute pages for each language.

**Comment by acrymble** [comment]
Please thank your colleague for us.

**Comment by spapastamkou** [comment]
A big thanks to both of you @acrymble and @walshbr , and to @fdlaramee for approving the PR.
