### ISSUE TITLE
ISSN for FR

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1084]
Post-launch activity

**Comment by drjwbaker** [comment]
To add, sooner we apply the better as we need this to get the DOAJ listing which takes at least 6 months (we still haven't got the ES DOAJ listing.. #897)

**Comment by mdlincoln** [comment]
@drjwbaker do you know if we actually need to have live content up in order to start the ISSN process? Or can it start ASAP?

**Comment by spapastamkou** [comment]
we could ask for more info to the British Library http://forms.bl.uk/bibliographic/index.aspx

**Comment by acrymble** [comment]
Our previous ISSN tickets outline the process: #147 #788

**Comment by mdlincoln** [comment]
Thanks for those pointers @acrymble - am I being obtuse, or do [these guidelines sound contradictory](http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/)?

>As for a print publication or a publication on CD-Rom, you can apply for an ISSN up to 3 months before a publication is released, if the information and documents you provide demonstrate that the project is sufficiently advanced.
>
>Please note that online ressources are usually not ISSN assigned ahead of publication.

Well, I suppose it would be useful for someone to start the process anyway and see if they'll mint an ISSN for us in anticipation of the publication. Who is able to take point on this?

Once we have it, please let me know so I can add it to the appropriate parts of the site.

**Comment by spapastamkou** [comment]
thank you @acrymble. I'll start the process, @mdlincoln, and keep track of the progress here.

**Comment by spapastamkou** [comment]
We got it, just e-mailed this.

**Comment by mdlincoln** [comment]
I've added this onto `french-staging`
