### ISSUE TITLE
"PH in English"?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1089]
Raised in #1088 

Should we rename _The Programming Historian_ to _The Programming Historian in English_? What are considerations for/against?

**Comment by acrymble** [comment]
We'd have to look at the repercussions for the ISSN, the Wordcat entry, and generally for brand recognition. I'd be against it because I think the advantages are outweighed by possible headaches. I understand the merit of de-anglicizing the project.

**Comment by drjwbaker** [comment]
Agree there are repercussions for listings. Though I think brand recognition would be unaffected: we'd still be PH, but with PH in E, en ES, and en FR flavours.

**Comment by vgayolrs** [comment]
Next to the considerations on the ISSN, I think it should continue calling The Programming Historian. That was the name of the original project and it was the one that attracted us to try some first translations some time ago. Certainly the sites in Spanish and French will be able to create their own lessons - I hope more and more - but they are born as versions. Titling the page as The programming Historian in english seems like a version of some other project (El historiador programador, L'historien numérique...).

**Comment by jenniferisasi** [comment]
When I mentioned that I liked the idea of adding "in English" to PH I was only thinking it in terms of the landing page, to make the 3 blocks more uniform, as it still has "The Programming Historian" unaltered in any of the versions on the top-left corner; does that make sense? 
I also think the repercussions for listings would be too big.

**Comment by arojascastro** [comment]
Yes, I agree with @vgayolrs and @jenniferisasi

**Comment by mdlincoln** [comment]
I do like the idea of making clear on the landing page that one is the PH in english, while still keeping the overall _Programming Historian_ title and not fundamentally introducing a new journal title. It sounds like we might all be in agreement on that.

This still raises a few questions:

1. Users will see a bit of a discrepancy between the apparent "title" of this journal _The Programming Historian in English_ that they click on the home page, and _The Programming Historian_ that shows up everywhere else in the English lessons.
2. When do we refer to _The Programming Historian_ in-line vs. language specific versions in places like the about pages, guideline pages, etc? Right now, for example, `/about` refers to "_The Programming Historian_" while `/apropos` refers to "_Programming Historian en français_"

One possible answer to 1) would be to have the title be something like "_The Programming Historian_ (original English version)". I'm not very sure about the term "original" as it may seem to assert primacy for the English version in a way we don't intend - on the other hand, though, it does correctly identify for users "where do I go to find the PH lessons I used three years ago?"

**Comment by drjwbaker** [comment]
Would just '(English version)' suffice? I feel as though we are at a point where a *very short* 'History of PH' could added to the About page (I often get asked and am slightly sketchy on some of the details myself..). This would help explain to readers why we have publications called PH en ES and PH en FR but don't call our EN publication PH in EN.

**Comment by spapastamkou** [comment]
does "initial English version" sound correct to you?

**Comment by amsichani** [comment]
I think a very _very_ short 'History of PH' would be a welcomed addition to the About page - I was also a bit puzzled when I needed to refer to its early days. Plus, its good now that the project is developing fast to remember our "origins" ;-)

**Comment by arojascastro** [comment]
Definitely a "History of PH" with milestones (2008: Foundation, 2011: open to public in English, 2017: Spanish edition, etc.) would clarify many things.

**Comment by drjwbaker** [comment]
Hastily assembled from http://niche-canada.org/2018/03/23/a-decade-of-programming-historians/:

> *The Programming Historian* was founded in 2008 by William J. Turkel and Alan MacEachern. It focused heavily on Python and was published open access as a *Network in Canadian History & Environment* (NiCHE) ‘Digital Infrastructure’ project. In 2012, *The Programming Historian* expanded its editorial team and launched as an open access peer reviewed scholarly journal of methodology for digital historians. In 2017 we added a Spanish Language [sub-team](https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy) to the initial English-language team and started publishing translated lessons under the title *The Programming Historian en español*. In 2018 we [hosted our first Spanish-language writing workshop](https://programminghistorian.org/posts/bogota-workshop-report), started [accepting new lessons in Spanish](https://programminghistorian.org/posts/convocatoria-de-tutoriales), and began to plan for translating lessons into English. In 2019, we will launch *The Programming Historian en français*.

@acrymble: see as you've been here the longest, does that sound about right?

**Comment by acrymble** [comment]
Yes that is a correct history

**Comment by mariajoafana** [comment]
If I recall correctly the Spanish team was formed in 2016 and we launched the Spanish website in 2017

**Comment by mdlincoln** [comment]
In 2018-11-29 meeting, decided to try out putting a subtitle on the homepage only for the english version saying "initial English version" that will appear in slightly smaller font under the title. This won't be a full title change for the journal, just a useful text cue on the homepage. I'll add this to #1088 

@drjwbaker will open up a new ticket for a proposed "history of PH" copy on the about page

**Comment by arojascastro** [comment]
"In 2018 we hosted our first Spanish-language writing workshop, started accepting new lessons in Spanish,"... well, we have always from the beginning accepted originals, but we got only a few ones until now, that were rejected... but I guess it is not a big issue how it is worded.

**Comment by drjwbaker** [comment]
@arojascastro Does the edit here https://github.com/programminghistorian/jekyll/issues/1102#issue-385799569 work?

**Comment by arojascastro** [comment]
@drjwbaker thanks! it's better. one more question: "Python and was published open access as a Network in Canadian History & Environment (NiCHE)" - I always thought that that (let's say) *iteration* was a closed publication, not open access. Can @acrymble confirm?

**Comment by acrymble** [comment]
You can still download it for free and openly. That's open access.

**Comment by arojascastro** [comment]
cool, good to know
