### ISSUE TITLE
about suggestion (remove the number of tutorials)

### ISSUE THREAD

**Issue by denten** [programminghistorian/jekyll#109]
> The Programming Historian is an online, open access, peer reviewed suite of about 30 tutorials that help humanists (though slanted towards historians) learn a wide range of digital tools, techniques, and workflows to facilitate their research. 

Suggest to rewrite to:

> The Programming Historian is an online, open access, peer reviewed suite of ~~about 30~~ tutorials that help humanists (though slanted towards historians) learn a wide range of digital tools, techniques, and workflows to facilitate their research. 

The number would have to be changed as the site grows in any case.

**Comment by acrymble** [comment]
Agreed.

**Comment by ianmilligan1** [comment]
Agreed as well. Users will see the breadth when they check out the index of lessons. If there is rough consensus, I can make change.
