### ISSUE TITLE
Improvements for "Reshaping JSON with jq"

### ISSUE THREAD

**Issue by efung** [programminghistorian/jekyll#1091]
- The full title of the lesson: `Reshaping JSON with jq`
- The system you are using: `Mac`

# Core jq filters
- Since there are references to the filename `jq_rkm.json` elsewhere, and the target of the link is to a file named `jq_rkm.json`, it might be clearer to have the anchor text be `jq_rkm.json` also.

# The Pipe: `|`
- In first paragraph, typo: `.artOjbects[]` should be `.artObjects[]`
- `every value at the key id within the artObjects array`: might be clearer to say `artObjects array ` _`elements`_ here

# Create new JSON: [] and {}
- Might be clearer to demonstrate creating a new object with _different_ keys, e.g. ` {painting_id: .id, painting_title: .title}`. Otherwise, the existing example can be simplified to just specifying the field names directly, like this: `.artObjects[] | {id, title}`

# JSON vs JSON Lines
- There is a website describing this defacto format: http://jsonlines.org/

# One row per tweet
- In the final example demonstrating how to separate hashtags with semicolons, it mentions "There are ways to get the same results using an even shorter query". Perhaps an example, such as this, could be given, for further study:

```
[.id, ([.entities.hashtags[].text] | join(";"))] | @csv
```

# Extracting user data
- Typo: `numers` should be `numbers
- Typo: `deliminters` should be `delimiters`

**Comment by mdlincoln** [comment]
Thanks very much @efung for finding these typos and suggesting some additions.

I'm going to fix the typos, as they are obviously incorrect!

For the time being, though, I'm probably not going to implement the additional improvements. While they're all well-taken, we'd need to do a fair bit of rewriting and testing to incorporate them all - something we generally try to avoid with _Programming Historian_ lessons unless its a fundamentally breaking problem like typos, broken links, or out of date software. We try to limit editorial content changes to the open review phase of the article, which has passed already. If a major version change of jq comes in the future that breaks most of this lesson, we may solicit a full rewrite of the lesson which could incorporate these suggestions.
