### ISSUE TITLE
Add 'History of The Programming Historian' to the About page.

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1102]
Building on #1089. Proposed wording at https://github.com/programminghistorian/jekyll/issues/1089#issuecomment-442761221

> *The Programming Historian* was founded in 2008 by William J. Turkel and Alan MacEachern. It focused heavily on Python and was published open access as a *Network in Canadian History & Environment* (NiCHE) ‘Digital Infrastructure’ project. In 2012, *The Programming Historian* expanded its editorial team and launched as an open access peer reviewed scholarly journal of methodology for digital historians. In 2016 we added a Spanish Language [sub-team](https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy) to the initial English-language team and in 2017 started publishing translated lessons under the title *The Programming Historian en español*. In 2018 we [hosted our first Spanish-language writing workshop](https://programminghistorian.org/posts/bogota-workshop-report), issued a call for [new lessons in Spanish](https://programminghistorian.org/posts/convocatoria-de-tutoriales), and began to plan for translating lessons into English. In 2019, we will launch *The Programming Historian en français*.

Do we agree on this?

**Comment by drjwbaker** [comment]
Replying to @arojascastro https://github.com/programminghistorian/jekyll/issues/1089#issuecomment-442890887 that confused me as well, but I took it from this line at http://niche-canada.org/2018/03/23/a-decade-of-programming-historians/:

> Two years later in 2008, the ‘Easy Pieces’ series had evolved into the co-written Programming Historian, focusing heavily on Python and was published open access by NiCHE’s ‘Digital Infrastructure’ project.

**Comment by arojascastro** [comment]
Interesting...

**Comment by spapastamkou** [comment]
The comment is for the last phrase. 
In the place of: "In 2019, we will launch _The Programming Historian en français_." would it be ok to consider smth like: "In the same year we also added a French language sub-team in order to launch  _The Programming Historian en français_ in 2019"?
Only if this is useful to show some continuity as to the addition of language sub-teams; and maybe avoid to have to update "will launch" in some time.

**Comment by drjwbaker** [comment]
Good idea @spapastamkou, so can we agree to:

> *The Programming Historian* was founded in 2008 by William J. Turkel and Alan MacEachern. It focused heavily on Python and was published open access as a *Network in Canadian History & Environment* (NiCHE) ‘Digital Infrastructure’ project. In 2012, *The Programming Historian* expanded its editorial team and launched as an open access peer reviewed scholarly journal of methodology for digital historians. In 2016 we added a Spanish Language [sub-team](https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy) to the initial English-language team and in 2017 started publishing translated lessons under the title *The Programming Historian en español*. In 2018 we [hosted our first Spanish-language writing workshop](https://programminghistorian.org/posts/bogota-workshop-report), issued a call for [new lessons in Spanish](https://programminghistorian.org/posts/convocatoria-de-tutoriales), and began to plan for translating lessons into English. In the same year we added a French language sub-team and will launch *The Programming Historian en français* in 2019.

**Comment by drjwbaker** [comment]
Close with https://github.com/programminghistorian/jekyll/pull/1135

**Comment by jenniferisasi** [comment]
The Programming Historian fue fundado en 2008 por William J. Turkel y Alan MacEachern. Se centró principalmente en Python y se publicó en acceso abierto como un proyecto de "Infraestructura digital" en la Red de Historia y Medio Ambiente de Canada (Network in Canadian History & Environment (NiCHE)). En 2012, The Programming Historian expandió su equipo editorial y se presentó como una revista académica de metodología para historiadores digitales, de revisión por pares y de acceso abierto. En 2016 añadimos un equipo en español al equipo inicial en inglés y en 2017 empezamos a publicar lecciones traducidas bajo el título The Programming Historian en español. En 2018 organizamos nuestro primer taller de escritura en español, abrimos una convocatoria para lecciones en español y comenzamos el plan para traducir lecciones al inglés. En ese mismo año añadimos un equipo en francés que lanzará The Programming Historian en français en 2019.

**Comment by spapastamkou** [comment]
"The Programming Historian a été fondé en 2008 par William J. Turkel et Alan MacEachern. Il s'est focalisé principalement sur Python et il a été publié en libre accès, en tant que projet d'infrastructure numérique de NiCHE (Network in Canadian History & Environment / Nouvelle initiative canadienne en histoire de l’environnement). En 2012, The Programming Historian a élargi son équipe éditoriale pour être lancé en tant que revue académique évaluée par les pairs, en libre accès, spécialisée aux questions méthodologiques pour des historiens et historiennes numériques. En 2016, nous avons ajouté une équipe hispanophone à l'équipe anglophone initiale puis, en 2017, nous avons commencé à publier des leçons traduites sous le titre The Programming Historian en español. En 2018, nous avons organisé notre premier atelier d'écriture hispanophone, lancé un appel à contributions pour de nouvelles leçons en espagnol et prévu de les traduire en anglais. Dans la même année, nous avons ajouté une équipe francophone et nous lancerons The Programming Historian en français en 2019."
@fdlaramee, could you please confirm if only "Nouvelle initiative canadienne en histoire de l’environnement (NiCHE)" is ok or whether in Canada you rather use both EN and FR as "Network in Canadian History and Environment/Nouvelle initiative canadienne en histoire de l’environnement (NiCHE)"? And if further comments on the rest, please go on directly in the text.

**Comment by drjwbaker** [comment]
Thanks @spapastamkou & @jenniferisasi. When we have confirmation re NiCHE from @fdlaramee, I'll add these changes to the FR staging branch (as per @mdlincoln's instructions at https://github.com/programminghistorian/jekyll/pull/1135#issuecomment-452138198)

**Comment by fdlaramee** [comment]
Hi everyone,

I am not super-familiar with NiCHE, but I have always seen it as (usually) just the acronym or (rarely) as the whole bilingual name: "NiCHE: Network in Canadian History & Environment / Nouvelle initiative canadienne en histoire de l’environnement".

**Comment by spapastamkou** [comment]
Thank you very much @fdlaramee. I edited and updated the text in the previous comment, so @drjwbaker you can use this updated version.

**Comment by drjwbaker** [comment]
Done at https://github.com/programminghistorian/jekyll/commits/french-staging (10 Jan)
