### ISSUE TITLE
Reviewers list auto-update on project team page?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#111]
We've got a list of 'community participants' on the Project team page (http://programminghistorian.org/project-team). This is currently manually updated and is quite out of date. Can we pull directly from the YAML file to populate this with people who aren't otherwise listed as editors or something else?

**Comment by wcaleb** [comment]
That's theoretically possible. Perhaps we should also roll the "emeritus" members into that list?

**Comment by acrymble** [comment]
Is it a pain to do?
I'm not so sure about the emeritus members. Someone might have a considerable contribution over time and need that record to get a further job.

**Comment by wcaleb** [comment]
Not a huge pain, but enough of a hassle that it's probably a back-burner 
issue. We would have to add an additional field to each record in the 
YAML directory to indicate that someone is not already listed in the 
other categories.

**Comment by acrymble** [comment]
like a 'role'?

On Mon, Jun 22, 2015 at 3:14 PM, W. Caleb McDaniel <notifications@github.com

**Comment by wcaleb** [comment]
Yes, though it might be easier for this purpose to have a Boolean value for general community member or not.

**Comment by wcaleb** [comment]
@smargh Does this look like a project you might be able to take on? Basically we would need to add a field to every author record in this file `_data/authors.yml`. Something like `editorteam: false`. For anyone who is a Fellow or on the Editorial Team, the value would be true, for everyone else it would be false. We would then need to write a little Jekyll loop to auto-generate a list of all the `false` records on the Project Team page. If you want to fork this repo and work on this a little bit, I'd be happy to offer feedback over at your repo as you work on it. I think you said you've done some Jekyll blogs recently, but let me know if not.
