### ISSUE TITLE
strict liquid filtering

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1116]
I'm going to explore enabling [strict liquid filtering](https://jekyllrb.com/docs/configuration/liquid/) which will cause our checks to throw errors when any YAML fields are empty that the site expects to be filled. Our dependence on YAML is very high now, so it probably makes sense to use this, even though it will mean that the Travis checks become even more onerous.

**Comment by mdlincoln** [comment]
Set `strict_variables: true`

**Comment by mdlincoln** [comment]
This option is only available in jekyll 3.8.0, however github-pages 3.9.3 pins jekyll 3.7.4 instead - we'll need to wait for them to increment their own jekyll.

**Comment by drjwbaker** [comment]
In the meantime what can we do to minimise time spent looking for why a build has failed? (which - I'm hoping - strict filtering has enough verbosity to help us with)

**Comment by mdlincoln** [comment]
well, this switch would be to make builds fail more often. Right now problems like #1115 are because jekyll tends to silently ignore when a metadata variable is missing - it just fills it in as a blank string and keeps processing. So it's not that builds are failing, but that they're _working_ and then publishing incorrect content.

**Comment by mdlincoln** [comment]
This is a result of us sort of pushing jekyll to its limits. Normally this kind of tight interconnection of different bits of metadata would be handled by a an ORM hooked up to a database that would constantly validate things for us. Jekyll is generally meant to be a lot more lightweight than how we're using it. It's possible to build out the custom lesson metadata checks to also validate the author bios, but that'd be another toolchain to have to maintain and update every time we think up a new feature.

**Comment by drjwbaker** [comment]
Okay. So this then is a case of "please read the docs and get the formatting right"?

**Comment by mdlincoln** [comment]
Yeah, kind of :( And also for us to be a bit more eagle-eyed during the PR review process. For example, I didn't realize his bio was showing up out of alphabetical order, and I approved it anyway! So.

**Comment by mdlincoln** [comment]
A complicating factor in using this is that, currently, `strict_variables` throws an error _even when you are checking to see if a variable exists!_ Luckily some others agree this is odd behavior, and there's an open ticket: https://github.com/Shopify/liquid/issues/1034#issuecomment-444323003

**Comment by mdlincoln** [comment]
also fwiw, even if github-pages hasn't yet adopted jekyll 3.8.0, we can use jekyll 3.8.0 in our build checks with Travis, so that isn't a blocker.

**Comment by walshbr** [comment]
Are we just leaving this open until github-pages increments their version of jekyll?

**Comment by mdlincoln** [comment]
@walshbr yes, I'd like to keep it open while tracking updates to liquid

**Comment by mdlincoln** [comment]
Closing out and adding to https://github.com/programminghistorian/jekyll/wiki/Technical-Team/
