### ISSUE TITLE
Institutional Support correct?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#112]
Current text reads:

Programming Historian remains grateful to the Network in Canadian History & Environment (NiCHE), ScholarsLab at the University of Virginia, The Center for Digital Humanities at UCLA, as well as to the Roy Rozensweig Centre for History & New Media (CHNM) for generous hosting services and technical support.

---
Is this representative? NiCHE and CHNM both contributed money or in kind contributions of the sort that one could account for. The other two really just supplied bodies on the original project team, so this seems arbitrary now. Should we limit this to tangible contributions of cash or kind rather than just a list of institutions where the project team happen to work? I believe that would take us down to NiCHE as a historic contributor, and CHNM as a current in-kind supplier of our server space and domain name. Yes?

**Comment by acrymble** [comment]
I've moved this to the about page, and reduced it as above. Discuss here if you think other institutions need to be added to the list. Probably a conversation for an editorial board call.

**Comment by ianmilligan1** [comment]
Although a relative newcomer, I think this makes sense. I think we should generously value in-kind contributions, however, including if people receive leave from duties etc. to do this sort of work. But if it's just a place where one of us happens to work, it shouldn't be there (i.e. UW shouldn't appear).

**Comment by fredgibbs** [comment]
to be a bit more specific: CHNM provided hosting space initially when were
on wordpress, and of course was essential early on. they don't provide
server space anymore--github hosts everything--but they do renew our domain
name for us, which i think they initially set up--which is pretty
important. so we need to keep them in the credits, but might want to revise
their contribution to be something more like a generic hosting support.

On Mon, Jun 22, 2015 at 8:14 AM, Ian Milligan <notifications@github.com>
wrote:

> Although a relative newcomer, I think this makes sense. I think we should
> generously value in-kind contributions, however, including if people
> receive leave from duties etc. to do this sort of work. But if it's just a
> place where one of us happens to work, it shouldn't be there (i.e. UW
> shouldn't appear).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/112#issuecomment-114121940>
> .
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by acrymble** [comment]
Thanks, that's helpful Fred.
