### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SchaeG1** [programminghistorian/jekyll#1122]
I encountered an error when I tried to navigate to The Programming Historian using this link: [https://programminghistorian.org/en/lessons/exploring-and-analyzing-networkdata-with-python]

**Comment by mdlincoln** [comment]
Thanks for the report! We've never published anything under that url, but we do have a lesson at https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python

**Comment by acrymble** [comment]
Where did you find that broken link @SchaeG1 ?

**Comment by SchaeG1** [comment]
It was posted as a tutorial for one of my Computer Science courses. It worked awhile ago, but it stopped working not too long ago.

On Dec 6, 2018, at 12:38 AM, Adam Crymble <notifications@github.com<mailto:notifications@github.com>> wrote:


Where did you find that broken link @SchaeG1<https://github.com/SchaeG1> ?

**Comment by acrymble** [comment]
Thanks. I think it's just a matter of a typo by your lecturer. That's not something we can fix since it isn't on our own website. But thanks for letting us know.
