### ISSUE TITLE
Welcome blog post for FD Laramée

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1123]
I prepared a blog post to announce @fdlaramee 's joining the PH team (cf. #1096). We checked already together, as I asked for bio info. Any remarks welcome especially for short intro and final part.

**Comment by spapastamkou** [comment]
@mdlincoln : I opened an issue instead of a pull request. Please let me know if you prefer that I do the latter

**Comment by acrymble** [comment]
You might just outline briefly what he will be working on for the French edition, to give people a sense. Otherwise I think it's fine.

Thanks.

**Comment by drjwbaker** [comment]
Added to which, it might be worth using the blogpost to *briefly* make note of how much work has gone into PH-FR so far (FR team understanding how PH works, **lots** of non-lesson page translation, getting the technical and social infrastructure working, first batch of translated lessons coming together) and how close you are to launch.

**Comment by mdlincoln** [comment]
yes @spapastamkou you can open a pull request from the branch you created. let me know if you need any help doing that
