### ISSUE TITLE
make sure to push to french-infrastructure

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1127]
@spapastamkou I noticed that you pushed a commit a few days ago to a branch you called `french-infrastructre` - please make sure that you put commits for the French pages onto the `french-staging` branch instead, otherwise they won't get published when we eventually merge the pages.

**Comment by spapastamkou** [comment]
I did so, it was a mistake while choosing the branch to commit. Actually, right afterwards, I did the commit onto the right branch (but without the ticket number), it this one here: https://github.com/programminghistorian/jekyll/commit/c684b346053aef91ed51ddd282e2fe2dcd4c604b  
Sorry for the confusion!

**Comment by mdlincoln** [comment]
oh ok, good! As long as the change made it on to the `french-staging` branch that is fine :)
