### ISSUE TITLE
Translation Editorial Process - Meeting 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1136]
I'm opening this issue to set up a time in January to run the French team on the editorial process of reviewing and publishing translations. 
I will also mentor and "oversee" the first translation edition of the French team.

**Comment by fdlaramee** [comment]
I should be available at any time Tuesday through Thursday starting Jan 8. Some Fridays may work as well.

**Comment by spapastamkou** [comment]
Perhaps we can choose a date by voting here: https://framadate.org/5mKEjDvP1sBRofBB

**Comment by fdlaramee** [comment]
My votes are in.

**Comment by spapastamkou** [comment]
I propose we retain Tuesday, January 15, do you think you can follow, @mpuren ?

**Comment by mpuren** [comment]
Hi, I can join you tomorrow.

**Comment by jenniferisasi** [comment]
It was great to talk to you! 
Here are my go-to resources for translations of technical terms/contexts : 
- European Union Terminology [https://iate.europa.eu/home](https://iate.europa.eu/home) 
- Term Bank [https://termbank.com/en/spanish-english](https://termbank.com/en/spanish-english)
- Linguee [https://www.linguee.es](https://www.linguee.es)

**Comment by spapastamkou** [comment]
A big thanks for everything, @jenniferisasi!

**Comment by arojascastro** [comment]
> It was great to talk to you!
> Here are my go-to resources for translations of technical terms/contexts :
> 
>     * European Union Terminology https://iate.europa.eu/home
> 
>     * Term Bank https://termbank.com/en/spanish-english
> 
>     * Linguee https://www.linguee.es

I did not know Term Bank, maybe we could add some of these resources on our website for translators... there are also Memory tools like Omega or [this](https://github.com/programminghistorian/ph-submissions/issues/197) that help to segment and align translations.

**Comment by acrymble** [comment]
I think this meeting was held. Can we close this @jenniferisasi ?

**Comment by jenniferisasi** [comment]
You are right, @acrymble we can close as the meeting took place.
