### ISSUE TITLE
Update Editorial Guidelines for Managing Director Publishing

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1137]
I think I'm the first one to push out a lesson since we decided that managing director would be coordinating pull requests for the publishing process. Accordingly, I've noticed some kinks in the editorial guidelines (holdovers from the old system) that would cause confusion if you're strictly following the text step by step. Also caught a couple errors in the metadata guidelines from when we condensed them. 

Changes to "Acceptance and Publication - Editorial Checklist"
- [x] Step 1 asks you to update the ph_authors.yml file. That's alright in theory, except in practice no one has been updating the ph-submissions version of that file for a long time (it's about half the length) of the one on the jekyll repo. So if we updated the ph-submissions file and copied it over we'd lose a lot of data. I'm going to clarify which one we should be editing to be the ph-submissions file, and I'll update the ph-submissions file to be up-to-date. Update - we'll just remove this file from ph-submissions and clarify this in the guidelines.  
- [x] Under step 3, the metadata guidelines. The example given for a slug isn't meaningful, as it needs to be a lower-cased and hyphenated path to the lesson. The old text was helpful and should be added - "**slug** should have the path to the lesson on the public PH site, which means the hyphenated text following programminghistorian.org/lessons/ (e.g. building-static-sites-with-jekyll-github-pages)"
- [x] Under step 3, the metadata guidelines. The date of the lesson should be updated to the date it was moved to the jekyll repo. That information dropped off, so there's no indication that the date should be changed during the publishing process. 
- [x] Step 4 wants you to find an image and upload it to the gallery folder. But this folder doesn't actually exist anywhere on the ph-submissions repo - it's a folder that exists purely on the jekyll repo. So if you are going to add it to the gallery folder you'd need to preemptively make a pull request before asking the ME to make a pull request, which doesn't make a lot of sense. So it sounds like we'll need to make a folder on the ph-submissions repo to fold new gallery photos that mirrors the structure of the Jekyll site. 
- [ ] Steps 5 and 6 should be switched. It doesn't make sense to incorporate it into the Twitter bot spreadsheet before publishing with the ME. You'll need a link to be able to do so, which should only be generated after publishing it. Also, there is always the off chance that the lesson could come up in the bot if there is a lag in the process before it's actually live. 

With those changes it should be a little more straightforward and clear about what is happening and what the managing editor's role will be. The lesson editor prepares everything on the ph-submissions repo, which is what I think we intended anyway. 
Do those changes sound alright @mdlincoln (particularly the ones that entail me making changes to the structure of ph-submissions)? If so I'll open a PR to change them.
@alsalin - when we're both back in the office after the break let's chat on slack when going through the final steps of the process to make sure we didn't miss anything.

**Comment by drjwbaker** [comment]
Good catch (and I'd missed that we'd made this decision about the MD taking on final publication duties - good call!)

**Comment by walshbr** [comment]
@mdlincoln - wanted to ping you again on this. I need to confirm that I can make these changes so as to start finish a lesson on the ph submissions repo. These are the two technical changes - I'm happy to just go forth and break things if you want. 

- [ ] Update the ph_authors.yml file on ph-submissions with the most recent production version of that file from the main repo. 
- [ ] Add a gallery folder to the ph-submissions repo for holding lesson avatars that has the same structure as the production site. 

That will allow me to make the requisite changes to the guidelines now that the publishing process involves handing everything finished off to the managing editor.

**Comment by mdlincoln** [comment]
oof, sorry I've been remiss in looking at this.

1. no, definitely not. In fixing up all of the design problems for #967, I just totally removed the preview lesson header - it was redundant given that the real thing that was needed for the submissions was the line numbers. As a result, there's no reason to even have ph_authors.yml on ph-submissions anymore 🤦‍♂️ I ought to have accounted for that and checked our guidelines. It would be better for the guideline to only stipulate that the lesson editor needs to give the managing editor the data they need to update ph_authors.yml on programminghistorian/jekyll only
2. yes, good correction for the slug gudielines
3. yes to the date changes
4. yes, go ahead and make this folder on ph-submissions
5. yeah makes sense about the twitter bot

**Comment by mdlincoln** [comment]
So maybe you can just... delete ph_authors.yml on programminghistorian/ph-submissions 🙃

**Comment by walshbr** [comment]
Sounds good - I'll make these changes and update the guidelines accordingly. Then ping @alsalin when I'm good to go with publishing the thing. I'll close this ticket by the pull request that will update the guidelines.
