### ISSUE TITLE
Mentioning "future lessons" in lessons to be published - sustainability question

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1143]
Working with a lesson that's about to be published: should we encourage authors to not directly mention their proposed "future lessons" since we don't know when or if those lessons will be published? Can we give guidelines for how to phrase "next steps" work without mentioning that the author intends to publish subsequent lessons?

**Comment by walshbr** [comment]
My inclination is to have them not mention it in the current lesson under review - only reference what exists. It's easy enough to add one or two sentences to an old lesson as part of a pull request that adds a new one. So when and if a future lesson gets published the two can be bound together more tightly by adding some language at that time.

**Comment by mdlincoln** [comment]
I agree with you both! Even in spite of good intentions all around, we've had a few hoped-for series that never materialized past the first lesson - definitely understandable given the work involved. So I think erring on the side of caution about future lessons is right.

**Comment by alsalin** [comment]
Thanks to you both!
