### ISSUE TITLE
Bogotá Acknowledgement

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1147]
@acrymble and @mariajoafana - just wanted to make you aware of this. The new lesson we just pushed live, I believe, was the first Bogotá lesson 🎉. Dave put together a short little acknowledgement of how the lesson was made possible through the Bogotá workshop, but could the two of you take a look to make sure that you don't have required changes to the language? Since this will theoretically be the first of several under that rubric I thought it would be good to have a template. 

https://programminghistorian.org/en/lessons/introduction-to-ffmpeg#open-source-av-analysis-tools-using-ffmpeg

**Comment by acrymble** [comment]
Looks perfect. Thanks @walshbr and glad to see the first of many coming through!
