### ISSUE TITLE
Wget Installation Instructions Need Updating

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#1151]
The `wget` lesson that I wrote needs to be updated to reflect new installation instructions. 

From an e-mail I received:

You have:

```
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
```

Not only did that not work, but the Homebrew site (https://brew.sh) now suggests this:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

I will explore this when I find a chance either today or early next week, and can stage a PR for the PH team's review.

**Comment by mdlincoln** [comment]
closed by #1152
