### ISSUE TITLE
Assistant Managing editor for April -June

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1153]
As @alsalin will be on maternity leave from April until June, it would be good to have an Assistant Managing Editor in place for these months. Please consider to nominate yourself!

**Comment by alsalin** [comment]
Thanks in advance all!

**Comment by acrymble** [comment]
I can cover this for the 3 months. I won't be doing any other editing though.

**Comment by acrymble** [comment]
@alsalin Can you make sure the Managing Editor Handover takes place when you're ready, and just let me know so I can clock on? https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover

**Comment by alsalin** [comment]
@acrymble certainly! I'll touch base in general by mid-April on this

**Comment by acrymble** [comment]
Ok I will close this since we've agreed on a path.
