### ISSUE TITLE
Our next great intervention

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1155]
We're getting close to launching our French project. What's next for us?

Please share ideas for how we can substantially and productively expand the project into new areas (but not too far from our remit).

**Comment by acrymble** [comment]
Just a few possible ideas:

- Following up on Bogotá event to pursue greater 'Global South' participation in DH
- Pursuing our connections to India
- Another translation team
- Further workshops like Bogotá around the world (maybe one in London or multiple cities at the same time?)
- Raising money to give fellowships so people can pursue methods research

Other ideas?

**Comment by drjwbaker** [comment]
I'd still like to think we ca get ourselves to financial stability.. Of the above I'd vote for more writing workshops. A francophone or English in global south (perhaps with our South African connects?) one would be ace.

**Comment by acrymble** [comment]
We've got a number of new ideas out there now, so i think this ticket has served its purpose.
