### ISSUE TITLE
layout issue on lesson under review 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1159]
Hey all,  
there is an annoying layout issue on a lesson I am currently reviewing and its now on its final stages (Gravity Models of Migration https://github.com/programminghistorian/ph-submissions/issues/204)- any help, esp from @mdlincoln, would be much appreciated.

Here is the lesson preview
http://programminghistorian.github.io/ph-submissions/lessons/gravity-model

* Table 3 does not fit horizontally on the page and is cut off. This is confusing for the reader. I suspect it is a CSS issue
* wide formulas that use the double-dollar-sign formatting codes are cut off horizontally. I suspect it is a CSS issue. See paras 125, 130, 131

I suspect both issues might be solved with small amendments on CSS table margins/borders.  I 'd be hesitant though to make changes on the main CSS file as this would affect other lessons too. So probably we should find a way to amend the markdown locally - is this an option? thanks ;-)

**Comment by mdlincoln** [comment]
@amsichani it's possible that I may be able to make some adjustments to the CSS so that the particularly large tables can at least scroll horizontally. I can look at this once you move this lesson onto a PR on this main repo.

**Comment by amsichani** [comment]
fab @mdlincoln - many thanks ! I 'll keep you posted!

**Comment by amsichani** [comment]
Hi @mdlincoln , could you please have a look on this again. @acrymble managed to fix most of it -he reduced the width on Table 3 but it still is JUST too wide. Probably it needs a bit of your CSS magic ;-)

**Comment by mdlincoln** [comment]
>I can look at this once you move this lesson onto a PR on this main repo.

**Comment by amsichani** [comment]
fab - @mariajoafana will be the managing editor for this one so she will update when she is ready.

**Comment by mdlincoln** [comment]
We've resolved the formatting issues.
