### ISSUE TITLE
length issue on lesson under review

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1160]
Hey all,

a lesson I am currently reviewing and its now on its final stages (Gravity Models of Migration [programminghistorian/ph-submissions#204](https://github.com/programminghistorian/ph-submissions/issues/204) it exceeds the 8.000 word limit of our tutorials. I am wondering whether I should suggest to the author to try and make it more compact. 

A couple of necessary remarks, though: I think this is one of our more complex tutorials , with specialised mathematical procedures and formulas and an interesting historical case study. The lesson is beautifully written, well structured, and it succeeds in making its readers  (even the non specialised ones!) able to follow  and understand it. I think this is happening precisely because the author is generous in his words - he is creating a story behind the lesson, he dedicates entire sections to explain the tech reqs, the mathematic logic behind the model used etc, the methodology and then a beautiful deployment in three steps of the model+the historical interpretation. 

From a (non-specialist) reader perspective: although it is a difficult lesson, I found it easy to follow and by no means its length was an obstacle to my reading experience.

Any thoughts?

**Comment by drjwbaker** [comment]
For reference see #779, where it was agreed that 8k is a guide rather than hard limit. However, long essays make translation more difficult and have in the past been divided up. If the latter isn't possible here, we need to consider the impact on internationalization: long lessons are opposed to that ideal because of the additional work required to translate them.

**Comment by acrymble** [comment]
I declare a conflict of interest in this matter as it is my lesson. I'm happy to adhere to any decisions made by the board.

**Comment by amsichani** [comment]
Thanks for your thoughts . Given the complexity and the difficulty of this tutorial, I 'd suggest we ll take here this word limit as suggestion and not as a hard limit and accept this as it stands. As for the translation issue, although I am generally sharing the rationale 'short tutorials =easier translation', especially for this tutorial I d find  difficult to get it translated given the 1) language-specific dataset and 2) the math terminology, which I (personally) found especially difficult to follow in English, not even imagine to have to translate it ;-)

**Comment by mdlincoln** [comment]
I'm closing this for now since it sounds like this is resolved as well as it's going to be?
