### ISSUE TITLE
'Support Us' missing from menu bar

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1162]
Now the Big FR PR has been pushed (🎉 🎉 🎉 🎉 🎉 🎉 🎉 ), I've noticed that the 'Support Us' `https://programminghistorian.org/support-us` (which was bundled into the Big FR PR) has some problems:

1. It is not in the EN menu bar
2. It has no ES/FR translation

On 1., I think `https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/menu.html` is the page I need to edit, though I'm not entirely sure how it works: for example `a class="dropdown-item" href="{{site.baseurl}}{{site.data.snippets.menu-contribute-edit[page.lang].link}}">{{site.data.snippets.menu-contribute-edit[page.lang].title}}</a>` refers to the page `editor-guidelines.md` which suggests there is an intermediary page that needs editing that I can't find. If someone can tell me where to go, I can make the edits.

On 2., what is our current process for getting a page in a translation workflow?

**Comment by mdlincoln** [comment]
Oh, thanks for noticing that @drjwbaker. To add a menu item you need to make two changes:

1. Go to `_data/snippets.yml` and create a new entry in the section with the comment `# top nav bar` following the pattern of items like `menu-about-overview`. For example, you may name it `menu-about-support`, with sub-entries for each language with both the display `title` as well as the proper `link`.

2. As you found already, in `_includes.menu.html` you add an `<a href...` link to the desired submenu, using the variable name you chose to add to `snippets.yml`. In this case, it'd read something like `<a class="dropdown-item" href="{{site.baseurl}}{{site.data.snippets.menu-about-support[page.lang].link}}">{{site.data.snippets.menu-about-support[page.lang].title}}</a>`

I'm going to add comments to `_includes.menu.html` that document this procedure better. Go ahead and add the snippets in a new PR, and once that PR is open @programminghistorian/french-team and @programminghistorian/spanish-team can add the required translation pages and add to the `snippets.yml`

**Comment by drjwbaker** [comment]
Thanks @mdlincoln. Worked for me. Go ahead and merge the PR when you are ready.
