### ISSUE TITLE
Twitter Bot and New Languages

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1167]
Popping in from sabbatical with this bit I thought of last night and wanted to get down before I forgot. The twitter bot currently tweets out four times a week - 

English tweet, Spanish tweet, English ICYMI, Spanish ICYMI.

It's pretty hardcoded for the two languages, and I'll have to do similar work as @mdlincoln did to make it more easily able to add multiple languages in the future. Also worth noting that there is probably a translation threshold under which we might not want it to be tweeting? In other words, if we started running it for the French project but the French project only had three lessons translated it would cycle through the lessons in three weeks (probably too quickly)? 

- [ ] Decide the threshold at which we will start having it feed in new languages
- [ ] Add French to the spreadsheet and instructions
- [ ] Make sure heroku can accommodate as many free deploys as this would require (I seem to remember five per week being the limit for how I set it up).
- [ ] Accommodate more languages in the future.

I won't have time to take a look at this until after this semester is over, but I could take a swing at it this summer.

**Comment by spapastamkou** [comment]
I've been giving this some thought as the first publications of FR lessons are imminent. Perhaps the simplest thing for us to do, when the FR lessons are on air, would be to manually tweet from the PH Twitter account? What do you think? 
For info, 4 translations are currently under review. One of them should be ready for publication in the coming days. (And 2 more could go under review soon.)

**Comment by walshbr** [comment]
Oop - I forgot I made this ticket! Thanks for pinging here. 

I think you're right - makes sense to stick to manual tweeting for the first beginning bits. I can put together the infrastructure for the French bot this summer when I'll have more time, and then we can slot the translations into the spreadsheet as for the other languages. I think once you're at six lessons then you probably have enough to start going to the bot. The only reason you might want to wait is that the bot does a lesson a week. So it's a question of how quickly you want the cycle to repeat. Six weeks might not feel like much time, but it's a pretty significant accomplishment to release these. I think it makes sense to promote them heavily for a bit. But open to your thoughts.

**Comment by spapastamkou** [comment]
Thank you. Let's target 6 published lessons then before we start use the Twitter bot for the FR version. It makes definitely sense.

**Comment by mdlincoln** [comment]
Just sticking a note here @walshbr that, maybe in a few months when you have room and others have been brought up to speed, this could be a great project to pair-program with one of the newer members of our technical team.

**Comment by mdlincoln** [comment]
Moving this to the new feature backlog for now - we can assess during our next tech team call.
