### ISSUE TITLE
Trying to update my bio

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1168]
I've tried to start a pull request to update my bio info but for some reason the Commit button appears unactive. I want to edit my bio and affiliation like this. Can someone try for me: 

 affiliation:
    en: |
        University of los Andes, Colombia.
    es: |
        Universidad de los Andes, Colombia.
    fr: |
        Universidad de los Andes, Colombia.
  bio:
    en: |
        Maria José Afanador-Llach is an assistant professor of Digital Humanities and History at the Universidad de los Andes, Bogotá (Colombia).
    es: |
        Maria José Afanador-Llach es profesora asistente de humanidades digitales e historia en la Universidad de los Andes, Bogotá (Colombia).
    fr: |
        Maria José Afanador-Llach est maître de conférences en Humanités numériques et histoire à l'Université de los Andes, (Bogota, Colombie).

**Comment by drjwbaker** [comment]
It might have been inactive as your were trying to push to the main branch? Anyway, I've opened a branch, made a PR, just needs approval to be merged. https://github.com/programminghistorian/jekyll/pull/1170
