### ISSUE TITLE
Intro to the Zotero API /  No module named 'exceptions'

### ISSUE THREAD

**Issue by silviaegt** [programminghistorian/jekyll#117]
1] CONTEXT I am a Ubuntu user [v. 15.04] and I use python 3.4 in the anaconda environment through the PyCharm code editor.
2] ATTEMPT I tried to create a Zotero library object called zlib in the exact same way as the example you [provided in your Tutorial] (http://programminghistorian.org/lessons/intro-to-the-zotero-api):
```python
from libZotero import zotero
zlib = zotero.Library('group','155975','<null>','9GLmvmZ1K1qGAz9QWcdlyf6L')
items = zlib.fetchItemsTop({'limit': 5, 'content': 'json,bib,coins'})
print(items)
```
​3] RESULT​

Traceback (most recent call last):
  File "/home/.../nltk-experiment-spanish.py", line 2, in <module>
    from libZotero import zotero
  File "/home/.../anaconda3/lib/python3.4/site-packages/libZotero/zotero.py", line 1, in <module>
    from exceptions import *
ImportError: No module named 'exceptions'

I have tried changing my interpreter to python 2 and to python 3.4 (without anaconda) but it still doesn’t work , also if I comment zotero.py's first line out the ImportError says that the next library doesn't exist and so on. 

​I appreciate any assistance you can provide​ and congratulations for your great work at the PH!

**Comment by wcaleb** [comment]
When running the script on the command line, did you do it like this: `python scriptname.py`?

**Comment by wcaleb** [comment]
@silviaegt Were you able to solve this problem?

**Comment by silviaegt** [comment]
@wcaleb I wasn't! But that might be due my close-to-0 knowledge on running scripts on the command line :( however I was able to follow-adapt the tutorials' objectives [using pyzotero](https://github.com/silviaegt/dh-toolbox/blob/master/zoterohtml2text.py#L121).
Anyway, thank you so much for trying to help me!

**Comment by wcaleb** [comment]
Glad you were able to find some resolution! Closing this for now.
