### ISSUE TITLE
Roy Rosenzweig Prize ($4k) - application

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1179]
I believe we should be putting together an application for the Roy Rosenzweig prize: https://www.historians.org/awards-and-grants/awards-and-prizes/roy-rosenzweig-prize

The deadline is May 15, 2019, and is for $4,000 in funding to help achieve the project's goals. The Spanish Edition is elligible because it is only 2 years old (the English version is too old). I would welcome suggestions for how the Spanish initiative might productively spend $4,000 so we can decide if it's worth putting in an application. This should be an impactful idea that benefits the project (not just the people implementing it).

**Comment by drjwbaker** [comment]
Some ideas. To pay for:

- the commissioning of a report on language interoperability in common DH tools/approaches (using ES as a test language).
- time to research and publish new versions of existing lessons based on emerging ES language data/sources.
- another writing workshop.
- a speaking/engagement tour.

**Comment by acrymble** [comment]
Worth noting that nearly all of their past prizes go to digital archives, so framing it in a "new media" focused way would be a good idea.

**Comment by mariajoafana** [comment]
Great idea. A combination between the second and third options seems to me like a good idea. A workshop to produce data sets and/or do some research digital archives' in Spanish, and then writing time to create new versions of existing lessons

**Comment by vgayolrs** [comment]
I agree with @drjwbaker  and @mariajoafana  . But I think it's important to consult the rest of the team. One important thing is that we have not developed a particular objective from the PH-es perspective. Simply as we have embedded ourselves in a previously determined structure, which is not bad, but it invites us to reflect. There is an example: the reflections we took over last year for the HD2018 conference. There were several things discussed, such as the digital divide. If we can achieve an agreement of our goals as PH-es beyond being a mere reflection of a predetermined structure, it would be fantastic.
And it implies to think what were the goals we have when creating PH-es? It is not a mere translation of a given thing, it is a dialogue with the cultures and the possibilities of the digital between the north and the south (to put it quickly).
Let's make a collective reflection for space in one or two weeks. See what happens. @arojascastro @jenniferisasi @jamotilla 
ok, lets take things like:
* the commissioning of a report on language interoperability in common DH tools/approaches (using ES as a test language).
* time to research and publish new versions of existing lessons based on emerging ES language data/sources.
* another writing workshop.
* a speaking/engagement tour.
But asking why?

**Comment by arojascastro** [comment]
Hi, thank you @vgayolrs for pinning me - otherwise I would not have seen this. I agree with Víctor that we need to discuss collectively and internally what we have achieved and what we want to achieve, our experience and how we see our future as a group of people working on the same project. I guess we should have a meeting and talk about - I cannot remember the last time we all could make it to the monthly meeting.

Said this, I would like to reflect on the idea of "version" that @drjwbaker pointed to: "time to research and publish new versions of existing lessons based on emerging ES language data/sources". In my opinion, we are already doing that: any translation is a version... because translating is always adapting to the target language and context. It is not simply a matter of language transfer, we are constantly changing the source text in order to meet our audience's expectations. Some translations require small changes, others require adding more instructions, others to change the whole data, others a lot of annotation to make the content clear for a Hispanic audience, etc. 

In any case, let's submit proposals for conferences and apply for funding that allow everybody in the project to engage with it. So, again, let's talk firstly and reflect on our experience and future.

**Comment by drjwbaker** [comment]
Glad this is leading to a discussion of purpose around the goals of PH-ES :smiley: 

And yes, @arojascastro, I agree that translation is versioning. So I misspoke/typed. I guess I was envisaging more radical rewriting (which we might never do without funding), as that would - I expect - reveal in interesting ways how different datasets fundamentally change the premise of a lesson on using a particular tool to do digital history.

**Comment by acrymble** [comment]
Thanks for the comments everyone. To keep things organized and on topic, I've created a new ticket to discuss the Spanish team's direction and objectives for this year (#1182). That will let us keep this ticket clear for discussing an application once those objectives have been decided.

**Comment by drjwbaker** [comment]
Does anyone want to pick this up and lead on whether or not we go for it?

**Comment by acrymble** [comment]
I'll take the lead on this, because I think it's important that we apply for this.

I've drafted some text about the project, but I haven't yet included the actual idea. I think we can reasonably build upon the Bogota workshop and possibly host another one somewhere in the Western hemisphere, but the $4,000 isn't nearly as big as the £17,000 we spent on the previous one, so it would have to be organized very differently.

@jamotilla we talked about something in Mexico. Any ideas?

[Rosenzweig Prize.docx](https://github.com/programminghistorian/jekyll/files/2907426/Rosenzweig.Prize.docx)

**Comment by jamotilla** [comment]
Hi @acrymble i think Mexico can be a good idea. What do you think @vgayolrs? Maybe in Mexico City, in San Luis Potosí or in Zamora. I can help leading this.

**Comment by drjwbaker** [comment]
Can we hook into / partner with some of the local organising committee for DH2018? I know they must be still exhausted and are more pan-DH than us, but it seemed like they had a good network. Perhaps Silvia (who came to the Bogota workshop, right?)

**Comment by jamotilla** [comment]
It´s a good idea @drjwbaker i think we can work together with the Red de Humanidades Digitales (MX), i´m sure they will be interested.

**Comment by acrymble** [comment]
My alternate idea for this is to hire someone to help us create the Spanish equivalent of #1194 Copyediting stylesheet. We have a lot of examples now of specific suggestions for word changes in Spanish tutorials, as well as a discussion about adopting inclusive language #958.

Why not consolidate that into a shareable document that is useful for both translators, reviewers, and anyone writing about DH in Spanish?

**Comment by drjwbaker** [comment]
During #1196  @acrymble proposed we close in next 5 days if no-one wants to own this. @programminghistorian/spanish-team @programminghistorian/french-team: the EN edition is more than 2 years old so is not eligible, so this will need a ES or FR lead if we go for it.

**Comment by spapastamkou** [comment]
After reading carefully this time, I have the impression the call is open for funding a workshop (and @drjwbaker mentions this in a previous comment). I exchanged with my contact in Senegal several days ago and they are still interested in a FR-speaking PH workshop, if we have the occasion. The EN-speaking alternative was not excluded but they are clearly more interested in the 1st. If you think we'd go for it, the deadline lets me the possibility to work on it in a no stressful way in April. What would be the best way to exchange on this, e-mail or ticket?

**Comment by acrymble** [comment]
@spapastamkou I think that's a very positive idea. I would encourage you to pursue it.

You should frame it as an initiative of the Programming Historian's internationalization push (which is now 2 years old), since you won't be able to show the impact of the French project yet.

You can point to the impact of our Bogota workshop (first tutorials being published now, plus @rivaquiroga joining the team). I'm happy to help as much or as little as you'd like with the writing. I'd also love to join you if you're doing a North African event.

**Comment by spapastamkou** [comment]
Great! Thanks for the ideas, @acrymble, and of course I will take all the help you can give. I'll take a closer look to it in the coming days and will come back to you for more.

**Comment by acrymble** [comment]
@spapastamkou have you had a chance to think more? I just want want to leave this too late!

**Comment by spapastamkou** [comment]
I had definitive confirmation from the VU of Senegal they are interested for a workshop following this call, 2 days ago. I started making a list with technical questions to ask you @acrymble, you will have it by next week. If we target smth like 15 April to have it sent, does that fit you?

**Comment by acrymble** [comment]
Sure that's fine. Do you want to submit it through your institution, or do you want me to submit it through mine? I ask because there are internal approval processes if you want me to do it, and they take some time. But it means I would have to deal with booking and money here, which quite frankly would save time for you.

**Comment by spapastamkou** [comment]
This is precisely one of these questions:-) Just let me check them quickly in the weekend (most probably tomorrow) and send them all at once to you, @crymble. But already yes, if your institution can take this up, why not.

**Comment by acrymble** [comment]
A note to the team. @spapastamkou and I have put together a bid for an initiative in West Africa. It is currently going through some internal approval and checking processes at my university.

**Comment by drjwbaker** [comment]
If you want someone to give it a read before submission, I'm more than happy to. Sounds awesome thus far.

**Comment by acrymble** [comment]
Thank you for submitting a nomination. Awardees will be announced on the AHA website in October and will be recognized during a ceremony at the January 2020 AHA annual meeting in New York City. For questions please contact awards@historians.org

**Comment by drjwbaker** [comment]
Great job @acrymble & @spapastamkou. Even if we don't get it, let's look to find ways to do the work anyway: you've made a really strong case for doing practical work in Francophone Africa.
