### ISSUE TITLE
Image for antconc concordance tutorial

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#118]
I don't know if you've been put on the case already, @ahegel but there's a new lesson up by Heather Froelich and it uses the same image on the lessons page as another lesson.

**Comment by fredgibbs** [comment]
the duplication is definitely my fault: i wasn't sure what the process is
for creating images for new lessons and didn't want to further delay
publishing the lesson. even as @ahegel continues to make us look good with
these, we should probably add some directions to the wiki so others (like
me) don't start messing things up. <nudge>

On Fri, Jul 3, 2015 at 9:05 AM, Adam Crymble <notifications@github.com>
wrote:

> I don't know if you've been put on the case already, @ahegel
> <https://github.com/ahegel> but there's a new lesson up by Heather
> Froelich and it uses the same image on the lessons page as another lesson.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/118>.
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by ahegel** [comment]
I updated the lesson with a new image. What kind of writeup would be helpful? A step-by-step outline of how we pick and format lesson images, or more of a "contact Allison to get an image for your lesson"?

**Comment by acrymble** [comment]
I think the latter is the process at the moment, isn't it? If you want
editors to contact you once a tutorial hits a certain stage (eg, final
review, copy editing) so that you have time to find something appropriate,
then just let us know and write it up.

**Comment by fredgibbs** [comment]
i had in mind the step-by-step outline so that when you're swamped when a
new lesson is ready or after you stop doing images altogether, we can pick
up where you left off without having to figure out what the best process is.

On Fri, Jul 3, 2015 at 3:39 PM, Allison Hegel <notifications@github.com>
wrote:

> I updated the lesson with a new image. What kind of writeup would be
> helpful? A step-by-step outline of how we pick and format lesson images, or
> more of a "contact Allison to get an image for your lesson"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/118#issuecomment-118429205>
> .
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by ahegel** [comment]
I added a [step-by-step outline](https://github.com/programminghistorian/jekyll/wiki/Lesson-Images) to the wiki, as well as a reference to image selection in the [New Lesson Workflow for Editors](https://github.com/programminghistorian/jekyll/wiki/New-Lesson-Workflow-for-Editors). Is this what you had in mind, @fredgibbs?

**Comment by fredgibbs** [comment]
this is perfect! i hope we can keep updating this page with suggested
places to find images as we discover more. but this is exactly what i was
hoping for. thanks @ahegel!

On Sat, Jul 11, 2015 at 3:54 PM, Allison Hegel notifications@github.com
wrote:

> I added a step-by-step outline
> https://github.com/programminghistorian/jekyll/wiki/Lesson-Images to
> the wiki, as well as a reference to image selection in the New Lesson
> Workflow for Editors
> https://github.com/programminghistorian/jekyll/wiki/New-Lesson-Workflow-for-Editors.
> Is this what you had in mind, @fredgibbs https://github.com/fredgibbs?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/118#issuecomment-120664042
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs
