### ISSUE TITLE
Google Summer of Code 2020?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1180]
Hi Team, some of you might be familiar with the "Google Summer of Code" programme. It pairs up computer science students with organizations working on open source projects. We've missed the February deadline this year, but is sthis something we might be interested in for next year?

https://summerofcode.withgoogle.com/

It requires a physical premises to work in, and a dedicated supervisor. My thoughts are that this would be best supplied by either @mdlincoln or our colleagues at the Scholar's Lab, since you do our technical work.

If not of interest, just say so and we can close. Otherwise we can start thinking about what we might like to be working on.

**Comment by acrymble** [comment]
Ok I'm going to close this. It's been open a week and no body has expressed any interest. That's absolutely fine. If anyone changes their mind, feel free to re-open it.

**Comment by mdlincoln** [comment]
Sorry I didn't respond earlier, but I agree it's fine to close. GSC projects tend to focus on much more computationally-intensive things like optimizing machine learning. They've had a few projects with wikimedia however those were definitely aimed at large-scale interface and editing workflows with high impact - probably something beyond our scope.
