### ISSUE TITLE
Restructure as a "Publisher" & "Publications"

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1183]
In light of our expansion into French and an acknowledgment that the Spanish team might want to work towards a unique strategy #1182 that is different from the English team priorities, I wonder if it isn't time that we discuss restructuring the project into two different initiatives:

1) A "Publisher" of open access peer reviewed methodology journals run by a board that makes decisions about things like governance, new publications, website services, etc. (possible name: "Method Press")

2) A series of "Publications" that are ultimately responsible to the publisher - in the sense that the agree to follow the "rules", but that are otherwise given a greater degree of autonomy.

The advantages of this approach might be that people could choose a level of engagement that better suits their interest, and that we could develop structures for expansion that are a bit more flexible to the needs of our different activities.

Thoughts on this?

**Comment by drjwbaker** [comment]
Thanks for raising this Adam. Builds on discussion we had last spring https://github.com/programminghistorian/jekyll/issues/788#issuecomment-380176694 I think this is where we have drifted since then and agree that it would be sensible to look at formalising roles based on 'Publisher' and 'Publications' (so, we in effect end up with 4 teams). My instinct, would be that we are by default attached to a 'publication' (probably along language lines) and then - if we want - take terms in a 'publisher' role that relinquishes and/or removes 'publication' responsibilities for a fixed period of time (until we step down, are ousted, et cetera).

**Comment by drjwbaker** [comment]
This impacts acutely on some policy:

- quorum https://github.com/programminghistorian/jekyll/issues/789
- sub-teams policy https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy
- diversity https://programminghistorian.org/en/about#diversity-policy

**Comment by drjwbaker** [comment]
- [ ] @ all put in this ticket things we think are impacted by this proposed change. 
- [ ] In response to our comments, @acrymble to write a document that outlines in more detail (but not too much!) the new proposed structure so that we can all comment on it.

**Comment by acrymble** [comment]
This proposal might also allow us to start to recruit specialists that have skills that could benefit us as a publisher but who might not be interested in our individual publications. Eg, people interested or skilled in financing projects, open access or sustainability experts, librarians and metadata experts, etc.

**Comment by acrymble** [comment]
Can I ask everyone on the editorial board to express which team(s) they feel they would most like to be part of if we were to make this split?

Choices being: Publisher, English, Spanish, and French publications.

@mariajoafana @ZoeLeBlanc @mdlincoln @jamotilla  

Responses:

**Publisher:**

- @acrymble
- @drjwbaker 
- @spapastamkou 
- @vgayolrs 
- @amsichani
- @arojascastro 

**English**

- @JMParr
- @walshbr 

**French**

- @fdlaramee
- @spapastamkou 
- @mpuren
 

**Spanish**

- @arojascastro 
- @jenniferisasi 
- @vgayolrs 

**On Sabbatical**

- @alsalin

**Comment by fdlaramee** [comment]
For me: French publications. I do not believe that I have any special skills that would be particularly useful on the Publisher side but I could contribute grunt work there as needed. And in the unlikely event that we ever run out of native English speakers, I could fill in there as well.

**Comment by spapastamkou** [comment]
We have one or more choices?

**Comment by drjwbaker** [comment]
I think I've been more 'Publisher' than 'English' since I joined, but happy to slot in wherever I'm needed.

**Comment by arojascastro** [comment]
I'm not sure... I like both.

**Comment by acrymble** [comment]
@spapastamkou what ever you feel makes sense to you. You can be on more than one for our purposes here. But I suspect not everyone is interested in being on more than one.

**Comment by acrymble** [comment]
For comment. My idea for how this might look in practice. Not fully formed:


**Publisher (working title: “Method Press” or "Invisible College Press")**

- Provides technical infrastructure for peer review and publishing for its publications.
- “owns” the publications and their titles but also “serves” the boards of each as a service provider.
- makes decisions about new publication titles.
- has oversight over “policy” discussions that affect all titles.
- responsible for the continued growth of the project into relevant markets and in line with the principles of the project and its component parts.
- takes a lead in seeking funding and income to support relevant activities, including research and outreach.
-	Structure:
o	Various (specific) Roles held via election on 1 or 2 year terms. (Communication Manager; Onboarding Manager; Meeting Coordinator; Finance Manager)
o	Technical Team – responsible for all technical aspects of the project
o	Managing Editor – all managing editors automatically have a spot on the Publisher team during their one-year tenure.





**Publication: The Programming Historian: English, Spanish, French.**
-	Each respective team is responsible for peer review and editorial of all lessons submitted to their language-specific publication.
-	Complete editorial freedom to accept or reject lessons without the interference of the publisher or boards of other publications.
-	Complete freedom to add new members as they see fit. Not to be interfered with by the “Publisher” unless the team looks as though it will not be able to continue otherwise, or is failing to maintain the standards of the press.
-	Must adhere to the standards and practices established by the “Publisher” (eg, open access, sustainability guidelines, ethical practices, etc)
-	Has a right to feed into the “Publisher’s” agenda and to feed back on proposed changes and policies.
-	Structure:
o	Managing Editor – one year elected term (September – September). Responsible for “publishing” finished lessons, and acting as the point of contact for all lesson proposals.
o	Editors – all other team members sit as editors and facilitate the editorial processes of individual lessons

**Comment by walshbr** [comment]
Just a note to say that I'm not ignoring the pings. I don't think that I know the context for this enough to be able to weigh in constructively (since I've been sabbatical'ing). And without more information I don't know that I'll be able to say which part of a split I'd want to be a part of. So I'll be following the discussion and might comment more when I feel like I have enough of a sense to do so. And also totally understand that these are still thoughts in process. All that being said, these are the questions this makes me think about - 

- How is this functionally different from what we've been doing? Does it primarily empower certain power to take on explicit roles and not others, and so less work? That's a totally fine and valid thing, and is worth doing. People should be able to do the work they feel qualified and interested in doing. And it might enable more retention of folks if we can demarcate more clearly what people can focus on so they're not spread so thin. I'm just trying to think through logistically what would change. Or is the primary goal to empower the editorial decisions of the language imprints? Because I don't know that the processes here would clarify things to me, but if it works for the language groups then that seems great. Who cares about me, in that case :)
- If we have elected roles what are they? Can we list them all out? Because I was just thinking that if a number of people are taken out of editorial responsibilities for the English team we'd need more people to do that work. That's probably where Adam was heading with his roll call, and I'd want to know what kind of labor would be going where and what would be needed.
- My main thought is that this sort of split might make more sense to me if our editorial policies were more stable. Since I've been on the board, it feels like we haven't had a month (or a week?) go by when there wasn't a major editorial or technical discussion taking place. And many have them have lead to significant changes in process, technical and editorial. That's great - the publication is alive and grappling with a lot of important things relevant to open publishing. The discussion are all good ones, and I think it's great that they represent all the new voices that are coming onboard. Manipulating the structure of the team like this might help things in light of that - it also might make it difficult for the language imprints to engage with that ongoing discussion or (more what I was thinking) act on them. I guess I'd just need to hear more about it.

But really - I haven't been a part of this discussion. Some of those might have already been addressed. So I'm going to take a backseat and follow along for now.

**Comment by mdlincoln** [comment]
> Since I've been on the board, it feels like we haven't had a month (or a week?) go by when there wasn't a major editorial or technical discussion taking place.

This would be a concern of mine as well. IT has been a massive struggle for our different teams to keep up with the constant changes to editorial and production instructions. I think those changes have been for the better - we're constantly clarifying and making implicit things more explicit - but it does suggest that we're still in a relative state of flux.

**Comment by acrymble** [comment]
@mdlincoln I think that might be a separate issue. My sense is that the systems in place for "publications" are actually quite robust and can be replicated in any language (more or less). We know how the proposal, peer review, and publication systems all work. These don't actually change much, though it can be a lot of work training new people to use these systems.

Where we tend to "innovate" is on aspects that are more akin to an umbrella service provider (a "publisher"). These are issues that are generally independent of individual language team concerns.

@walshbr you ask how this will change things, I think it will streamline everything. At present we pretend that everyone will contribute to every decision, but we know in practice that some people just aren't interested (or choose not to participate). That's fine, but I think we could be more efficient if we started making more formal roles that more accurately defined the level of contribution various people want to make. That way we aren't waiting for people to chime in who won't, and they don't even necessarily need to get the alerts for issues they just don't care about.

For example, the Spanish team is really working hard on doing lots of translating, but generally speaking that team is less engaged in the wider discussions. Maybe that's a language barrier. Maybe those people are just happy with the really impressive successes they're having with the Spanish project. If it's the latter, then let's just make it clear that we don't expect anything else from them.

**Comment by mpuren** [comment]
Sorry for my late answer, I was in Slovenia last week for a big work meeting and after that in Lyon.

I've carefully read the discussion - thank you @acrymble for opening the issue, I find it very interesting for the project. For me, like @fdlaramee : French publications. It would suit me well.

**Comment by walshbr** [comment]
As far as I understand this I would probably shift to only the English section and not the Publisher.

**Comment by amsichani** [comment]
hi, thanks @acrymble for opening up this . Instinctively I 'd go for the 'Publisher' role - but I d like both. I can see a potential efficiency in our procedures by formalising roles, expectations and tasks but , as any other big change, it requires some (extra) risk management.

I 'd like to quickly raise a couple of issues:

- In terms of decision making, we need to make very clear the areas/ issues that each 'Role' will deal with,  eg. while the Publications will deal more with the content of the tutorials , this will certainly have some implications to the technical side of things. Which will be the relation between these two roles/areas in terms of decision-making? 

- diversity: I am guessing that the 'Publisher' role will be very American-English populated (in terms of language/ nationality) and this might be an unexpected battle for our diversity and internationalisation fronts. We need to secure that even if Publications teams are by default language specific , we somehow keep (language & national) diversity within the Publisher team as well. I think we need to revisit again our diversity algorithm here ....or even be more creative on establishing a new diversity rule/pattern.
The same (a bit more complicated I guess) goes with gender diversity. 

- recruitment processes:  as for now, we are recruiting sub-teams based on language (French, Spanish), or generally for Editorial team (=English team). With the Publisher team in place, we ll need to decide on necessary skillsets we want and then advertise the specific role/ or approach the candidate with a proposal.

- power dynamics : it is important to ensure that any restructuring will not change the power dynamics of the team as a whole. All and each of us has a unique contribution to the project, and any change should respect and support this, without prioritising specific roles or decisions over others.

**Comment by drjwbaker** [comment]
> diversity: I am guessing that the 'Publisher' role will be very American-English populated (in terms of language/ nationality)

https://github.com/programminghistorian/jekyll/issues/1183#issuecomment-466748259 suggests maybe not, but I agree this is something we should look at carefully, especially we regard to the power dynamic you raise.

**Comment by acrymble** [comment]
@mariajoafana @vgayolrs @jenniferisasi @ZoeLeBlanc @mdlincoln @jamotilla @spapastamkou @JMParr @amsichani @alsalin @walshbr I'm still hoping to hear back from you on whether you see yourself as part of a publication team (English, Spanish, French) or as part of a 'Publisher' team.

**Comment by spapastamkou** [comment]
Had put my name in the list under both « publisher » and « French team »

**Comment by walshbr** [comment]
Sorry I mentioned earlier that I would probably be interested in only English and not publisher. But it looks like we would need to do a significant amount of recruiting to make up for all the people switching over to publisher.

**Comment by vgayolrs** [comment]
Returning from my "sabbatical" on March 29, but I want to get involved in this discussion, but I put my name on both.

**Comment by jenniferisasi** [comment]
After reading all the differentiation of the two roles (thank you @acrymble for writing them), I put my name in the Publication for Spanish as I don't have enough formal knowledge, at least at the moment, on OA policies, seeking funding, etc. and I know I can and want to keep contributing on our lessons.

**Comment by arojascastro** [comment]
I am a little a conflicted about this change. I definitely want to have a voice in the direction of our project and I also can do maintenance tasks, but if I have to choose - considering that I have little time - I would stick to "Publication" in Spanish. I am also wondering how this will affect our "roles" (editorial board, editorial team, etc.). I guess *publication* means *editorial team* while *publisher* fits more in the *editorial board* category, but I still want to be part of the board... 🤔

**Comment by acrymble** [comment]
Thanks for raising your concerns @arojascastro. We will have to work out how to make sure people still have voices in areas where they feel they have vested interests. 

But I think we need to start acknowledging that many people just want to be involved in a particular publication rather than wider discussions. Our model of wanting to make sure everyone has a chance to participate in discussions means that tickets linger open for months. We miss opportunities like funding because the deadlines are short but our conversations are long. So giving some people specific remits and letting them get on with those remits will make us more efficient. We'll have to have mechanisms for keeping those people accountable, but I don't think we've got anyone nasty or power hungry on the team.

We're also already seeing publication groups forming in the non-English groups. Just yesterday you suggested a separate Skype call of the Spanish team (the English team has never done that, and I suspect might raise resentment if we did). I think you should have that call, because I think those people are the ones that best understand the needs of the Spanish publication, and people like me should be cut out of it because you all clearly know what you're doing.

I'm also becoming concerned that no one actually wants to run the English publication. And if that's the case, we need to know so that we can reruit a team that does.

**Comment by arojascastro** [comment]
Sure, you are right about long discussions, open tickets, slow participations, etc. I agree it is annoying sometimes, but it is hard for me to separate our editorial work from our publisher work. For instance, let's say that someone, who is part of the publisher team and hasn't edited any lesson for a long time, wants to submit a paper for a conference about the project, and the editors do not have time or cannot make it to the conference. I am wondering how credit is going to be distributed? Maybe is a bad example, but I am wondering if this change will make our flat structure into a more hierarchical one, where publishers control what editors do. I know there is no bad intention, but we should be cautious. On the other hand, just for the record, I suggested that separate meeting to discuss that specific issue, but I do not mean to have separate skype meetings on a regular basis at all.

**Comment by acrymble** [comment]
Thanks for that example @arojascastro. I'll add concerns about credit to the list of issues to tackle.

**Comment by walshbr** [comment]
I have the same concern @acrymble re: the English publication. There are a few people left to weigh in, but if we have to onboard more than 50% of a new board for English it would concern me.

**Comment by JMParr** [comment]
I would be "English publication."

**Comment by acrymble** [comment]
Just to add a big bonus of this shift, I thin it would allow our three publications to drift apart somewhat. That means no more waiting for translations of every little change we want to make. And that should save a lot of people time and mental energy.

**Comment by drjwbaker** [comment]
Agree with @arojascastro that this change will create hierarchies and we need to figure out how to manage those. Those is kinda why I envisaged each language publication having fixed term representatives of the 'editorial' team: to share credit and reduce the risk of top down action *on* each publication.

**Comment by drjwbaker** [comment]
Discussed at https://github.com/programminghistorian/jekyll/issues/1196 from now, please try to propose **edits** to text of the proposed restructure (which is at https://github.com/programminghistorian/jekyll/issues/1183#issuecomment-466997467), either by suggestions for changes to individual lines or new lines, rather than write comment. We can then periodically revise the proposal until we are all happy

**Comment by drjwbaker** [comment]
Edit:
> - has oversight over “policy” discussions that affect all titles. Takes decisions based on '[Lazy Consensus](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance)' among members of the Publisher Team. Where "policy" changes are considered by the Publisher Team to be substantial, they will seek 'Lazy Consensus' from all Publication Teams.

**Comment by acrymble** [comment]
I'm not sure there's been enough enthusiasm for this idea to really take it forward at present.

I wonder if we can approach it another way? What if we start looking at the tasks we do, and the tasks we'd like to do, and work towards assigning people to more specific roles that they do on behalf of the project. @jenniferisasi 's new position as Communication Manager being a prime example of that. We can turn to her for strategic direction or problem solving on issues related to our outward communication. And we know that she'll get the job done.

There are a number of other roles we might like to fill. Just to brainstorm:

- Onboarding Manager - to give new members a clear pathway into integrating with the team
- Educational Manager - someone to improve the educational potential of our project (eg #1022)
- Research Impact Manager - someone to improve the impact our project has on research and to document that impact.
- Regional Outreach Managers - people with remits to build bridges with certain regions (Asia, Africa, Latin America, etc)

That way we have multiple pathways for people to contribute, and there's a clear line between people who just want to edit or translate from time to time, and people with more strategic roles to help grow the project.

Does this sound like a more appealing approach?

**Comment by jenniferisasi** [comment]
Yes, I actually like this idea better, @acrymble!

**Comment by arojascastro** [comment]
Yes, maybe this proposal is clearer, but are these additional roles to the role of `editor`? Or can someone be `Onboarding Manager` and stop editing lessons? And should we keep the editorial board? Should we give for granted that everybody is part of the editorial board if we implement this change? I have no view on this...

Just for the record, at the moment we have the following roles:


    Editorial Board: A fully-fledged member of the project team, involved in directing the project's future
    Editorial Team (English): Responsible for editorial work resulting in the review and publication of English-language lessons
    Editorial Team (Spanish): Responsible for editorial work resulting in the review and publication of Spanish-language lessons
    Editorial Team (French): Responsible for editorial work resulting in the review and publication of French-language lessons
    Community Engagement: Responsible for project outreach and impact
    Managing Editor: First point of contact for authors with lesson ideas
    Ombudsperson: A person that authors and reviewers can turn to if they have queries or concerns about any part of the peer review and publication process
    Technical Team: Responsible for the technical features that bring the content and peer review to our community
    Archivist: Responsible for archiving the project
    Treasurer: Responsible for project finances
    Sponsorship Coordinator: Responsible for managing relationships with our sponsors

**Comment by drjwbaker** [comment]
@arojascastro Agreed that we if take forward this proposal (for which, thanks @acrymble) we need to define what a member of the 'Editorial Board' does or remove it.

**Comment by acrymble** [comment]
Building upon this, how about this for a new structure moving forward?:

- Managing Editor (English)
- Managing Editor (Spanish)
- Managing Editor (French)
- Ombudsperson
- Technical Manager (has strategic oversight) @mdlincoln
- Technical Team (reports to technical manager)
        - @jenniferisasi  
- Archivist @drjwbaker 
	- Manages regular deposits to Zenodo of Programming Historian project and publications. Co-ordinates keeping Directory of Open Access Journals listing up to date.
- Finance Manager (formerly treasurer + sponsorship) @drjwbaker 
	- Looks after donations and sponsorship, including reimbursements and payment when money is spent. Point of contact for potential and existing sponsors.
- Communication Manager @jenniferisasi  
- Team Development Manager (onboarding manager)
- Education Manager
- Research Impact Manager
- Head of PH Global
- Regional Manager - Africa (or change title to 'PH Global - Africa'?)
- Regional Manager - Europe
- Regional Manager - Asia / Pacific
- Regional Manager - North America
- Regional Manager - Latin America
- Editor (English) @drjwbaker 
- Editor (Spanish)
- Editor (French)

That way all tasks have someone in charge of them, outsiders including employers know exactly how we contribute, and we can signal to each other our level of commitment. This would replace the proposal to restructure as a publisher/publications, but would have a similar effect in many ways.

**Comment by drjwbaker** [comment]
Thanks @acrymble. This will also help recruitment, as we can be clearer on what we need.

On which - and thinking of https://github.com/programminghistorian/jekyll/issues/1249#issuecomment-480190726 - do we want to a) define specific translations roles within 'Editor (LANG)' or b) make it part of the 'Managing Editor (LANG)' role to recruit a mix of LANG-only editors and those who can translate between publications?

I'm on the side of b), though I'm thinking of a few specific things here:

- EN needs editors who can translate from ES and FR.
- ES and FR should be able to recruit editors who do not translate to EN (or indeed, FR and ES).

We should capture that as we define Editor and Managing Editor roles.

**Comment by acrymble** [comment]
I don't see any dissenting votes on this. So we can discuss it one final time at the April 2019 meeting and if no one raises issues I will start implementing it, taking @drjwbaker 's points into consideration.

**Comment by drjwbaker** [comment]
We should include in roles the meetings that people in certain roles are expected to attend.

**Comment by mdlincoln** [comment]
I will take on the "Technical Manager" role

**Comment by acrymble** [comment]
we have agreed to implement the new "roles" system. I will open a new ticket.
