### ISSUE TITLE
British Academy Network grant £25k

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1185]
I hope you all don't mind me continuing to post relevant funding calls, but the British Academy has a call at the minute for partnerships between the UK and developing countries. It strikes me as something we could use to build partnerships with either India or people in Africa:

https://www.thebritishacademy.ac.uk/programmes/gcrf-networking-grants?utm_source=newsletter&utm_medium=email&utm_campaign=fundingcall%20%7C%20gcrf-networking%20%7C%20%20%7C%20International&utm_content=International&utm_term=20190222

**Comment by drjwbaker** [comment]
Related to https://github.com/programminghistorian/jekyll/issues/1155#issuecomment-460206261

**Comment by acrymble** [comment]
I'm going to close this ticket because nobody has jumped on the idea, and I don't think we need to keep lots of tickets open.

**Comment by spapastamkou** [comment]
I was precisely looking for this ticket:) I have just a question: do we have a UK-based researcher who would be interested in applying?

**Comment by acrymble** [comment]
Sorry @spapastamkou please feel free to re-open it.

I haven't had a chance to go through the bid requirements in detail, but if you're interested in applying I'm sure either James or I could put the bid in with you in a collaborative way.

**Comment by spapastamkou** [comment]
I sent an e-mail and if there is a reason to re-open, then I will:)

>
