### ISSUE TITLE
Potential collaboration with Pelagios Commons

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#1186]
I would like to report about a potential collaboration between the PH and [Pelagios Commons](http://commons.pelagios.org/) and its suite of tools [Recogito](https://recogito.pelagios.org/) and [Peripleo](http://commons.pelagios.org/forums/topic/ten-days-left-to-apply-for-a-pelagios-small-grant/). 

Pelagios Commons is a platform that aims to provide resources like gazetteers to link places: 1. Recogito is a tool that helps users to add coordinates to places found in texts and maps; 2. Peripleo is a search service that allows you to find community-curated content related to specific place. The project is funded by the Andrew W. Mellon Foundation and is well-known amongst digital humanities practitioners.  

Rebecca Khan contacted us and suggested a potential collaboration between the PH and Pelagios. For the last 3 years, they've run a [small grants programme](http://commons.pelagios.org/resource-development/), which supports members of their community to develop resources and tools. Usually 6-8 projects are funded, and they produce different materials, including gazetteers, digital methods, and tools. As a condition of the grant, they have to document their work, produce a series of blog posts, and share the final results under open licences. 

They would like in the future to propose the creation of tutorials as part of their annual grant reviewed and hosted by the PH. Here is an example of a call for [Pelagios Small Grants](http://commons.pelagios.org/forums/topic/ten-days-left-to-apply-for-a-pelagios-small-grant/).

After some email exchanges, we reached some consensus about a potential collaboration.

- peer review process is maintained and respected
- tutorials should be original and targeted outputs for the PH
- they would mention the PH in the grant call
- they usually give 6 - 8 grants per year, but they only expect around 4-6 tutorials annually

We acknowledge that mapping tutorials are relevant for the PH as it is shown by the fact that we have already published several lessons on that topic.

However, this collaboration arises a few things to consider by the Editorial Board:

- workload implications and copy-editing costs  
- submissions and multilingualism
- peer review process and rejection
- duration?
- are tools stable enough? 
- originality?

Any more ideas?

**Comment by arojascastro** [comment]
We discussed this issue in our monthly meeting, and we reached a kind of agreement: we welcome any proposal from Pelagios, and we will treat it as any other proposal - that is, in order to succeed lessons will have to be compliant with our current guidelines and pass our peer reviewing process. I'll try to draft an answer for Pelagios as soon as possible.

**Comment by drjwbaker** [comment]
Plus we want to see how they proposal to word the call (at least the bit that mentions us) before they put out the call.

**Comment by arojascastro** [comment]
Right! Thank you for the reminder

**Comment by arojascastro** [comment]
I contacted Pelagios and shared our position. They answered with a positive reply. I am closing this since we are having email exchanges and no discussion is needed any longer. Thank you all.
