### ISSUE TITLE
update FR guidelines with explicit mentions to translations

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1189]
The FR pages with guidelines for editors, authors, and reviewers were translated from EN. As a result, there is not a lot of stuff on translations, whereas this exists in the ES pages. 

I found the following parts: 
https://programminghistorian.org/es/guia-editor#nota-sobre-la-revisi%C3%B3n-de-traducciones 
https://programminghistorian.org/es/guia-para-revisores#traducciones
https://programminghistorian.org/es/guia-para-autores (some phrases in parts 1 and 3)

I think it would be good to update to be in lines with the ES version, especially since we want to attract reviewers of translations and translators. Maybe we could just adapt corresponding parts in the FR pages to our needs instead of trying a translation (I do not speak Spanish, as far as I am concerned). Any thoughts on that? This concerns @programminghistorian/french-team but all views are welcome.

**Comment by arojascastro** [comment]
Maybe this is a great opportunity to discuss if we should split the guidelines for authors and for translators and if the English edition should include information about translations as well (since we are publishing original tutorials in Spanish soon). @programminghistorian/english-team @programminghistorian/spanish-team

**Comment by jenniferisasi** [comment]
I agree with @arojascastro, it could be a good way to have a conversation about splitting the guidelines. In particular, I'm thinking it would be beneficial to have "how-to" guide for translations, as I am sharing a series of "tips" with the French team. For instance: 
- If the software cannot be changed into the target language, keep the original term in the instructions and provide a translation or explanation in parenthesis. Same goes for functions in programming languages. 
- If the software cannot be changed into the target language, you can reuse the images from the original lesson.
Etc. 

This probably has to go on another issue? We have these things somehow indicated in the reviewers guidelines for translations but not on the translators guidelines, where it's more open ended with the Global Audience text. 

In the meantime, do we have anyone on board who is fluent in French and Spanish?

**Comment by spapastamkou** [comment]
It would be more clean to split the guidelines and have translators specific ones. So I favour the idea and will be glad to work on that. Perhaps we could write a general text for the web site and keep the specific details for the wiki? 
If we are to go further with this, perhaps it would not be necessary to update the FR pages in the meantime as proposed.

**Comment by fdlaramee** [comment]
Splitting the guidelines for authors from those for translators seems like a good plan. Something to add to the agenda for next month's conference call? 

I agree with @spapastamkou that making changes to the existing FR pages may not be necessary if we pursue this plan, especially since we are still working within our small group for the time being. As long as we make a decision soon enough that we can produce the translation guidelines before we recruit a larger pool of translators.

**Comment by mpuren** [comment]
I agree : we should split the guidelines. As @jenniferisasi said earlier, she gave us some very interesting tips that should be available for every translator. Moreover, concerning French translations, we also have these guidelines on "l'écriture inclusive" (gender-inclusive writing). I think Spanish-speaking translators - and future versions of PH in other languages - could find useful to have access to this kind of guidelines as well.

**Comment by vgayolrs** [comment]
Thanks to @mpuren for mentioning gender inclusive writing. In fact, we have that task pending in the Spanish team: #958

**Comment by spapastamkou** [comment]
In #1196 it was suggested we go for the separate translator guidelines. Activity on this will now be in #1199. Therefore, I close this ticket.
