### ISSUE TITLE
French ombudsperson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1193]
I just noticed that Amanda Visconti is being listed as the Ombudsperson on the French submission tickets. Really it would be better for someone on the French team to take on this role for French submissions so that everyone can operate in French.

This role is not a lot of work. We have only ever ONCE called upon the ombudsperson. But it's important to have them in place.

**Comment by mpuren** [comment]
@fdlaramee Do you voulunteer for the role?

@acrymble Can we have two ombudspersons, or is it too much?

**Comment by acrymble** [comment]
@mpuren you can do whatever you like. As I said, only once has this ever been used.

**Comment by mpuren** [comment]
Thank you @acrymble 

@fdlaramee what do you think ? We can put our 2 names, or only yours.

**Comment by fdlaramee** [comment]
@mpuren If you want the role, it is yours. If you don't want it and @spapastamkou doesn't either, I'll take it. You two were here first and built this thing, so it is only fair that you would get priority of assignments. (I assume this means that @spapastamkou is going to be Managing Editor?)

**Comment by mpuren** [comment]
Thumbs up for @spapastamkou as Managing Editor

@fdlaramee I propose to put our 2 names as ombudsperson, it is simpler to decide this way :-).

**Comment by fdlaramee** [comment]
@mpuren As you wish. (As long as @spapastamkou is okay with being Managing Editor!)

**Comment by spapastamkou** [comment]
ok, I can do this for this year, thanks for trusting me :) We can leave the ticket open, the time to make a PR out of it to update the relevant web site pages.

**Comment by spapastamkou** [comment]
I created PR #1219 to update the FR pages with the new team roles. Once @mpuren and @fdlaramee will have replaced Amanda Visconti's name with theirs as ombuds and the branch is merged, we can close this ticket.

**Comment by spapastamkou** [comment]
Note that for the lesson I am editing, I left Amanda's name as ombudsperson, as both Marie and François Dominic are reviewers. Remarks welcome, if any.
