### ISSUE TITLE
Copyediting stylesheet (funded *fingers crossed*)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1194]
There is a small pot of internal funding I can apply for (very short deadline). I am thinking of applying to have someone in the publishing business help us create a stylesheet for copyediting lessons. By copyediting, I mean the stage after the lesson is "done" and before it is "Published".

At the moment this burden falls on editors (https://programminghistorian.org/en/editor-guidelines) and the tasks are quite extensive. I'd envisage the stylesheet as step one, giving us a set of rules on things like accepted dictionaries / formatting of tables, code blocks, reserved words, etc.

Then ideally step two would be to convert that into a script that new lessons could be run through, identifying where a lesson doesn't meet the rules so editors can quickly fix them.

I'm proposing asking for money to hire someone to help us develop that stylesheet. I might be able to get that expertise internally at the University of Hertfordshire Press. So it might be quite straightforward if they agree to fund it.

I don't need comments on this stage on specifics (will we use US or UK spelling for English) but generally I'd welcome comments on this idea more broadly. It won't require work for anyone who doesn't want to be involved, but I'm happy to work with whomever feels invested in this. In the first instance it would probably involve an English stylesheet, in consultation with some of our non-English teams to make sure it's something that's useful for other languages too.

My deadline is next week, so please comment fast.

**Comment by acrymble** [comment]
I should say, this is meant to be a time saver in the long term, specifically for editors. As well as a way to catch mistakes so we don't have to fix them later down the line.

**Comment by mdlincoln** [comment]
What would be particularly useful from this is a stylesheet specifically for code-heavy writing, as our lessons are. Guidelines on when to use `inline code` (for variable, function, or filenames) spans versus

```
fenced code blocks
```

and the use of subheads, bulleted/numbered lists in particular would be great. These are small things that, when done consistently, have a nice cumulative impact on the readability of code-rich tutorials.

**Comment by alsalin** [comment]
I agree with @mdlincoln and would like to add that we'd need to decide on the level of copyediting and the issue of voice. Our lessons vary greatly in terms of formality and voice and, as opposed to technical writing where you want to have one voice across publications, the voice of authors in this case should be preserved - but to what level. Do we want to include style guidelines for author voice/formality in writing? What about formality of grammar? Is there a style guide we'd like to follow for that (CMS, MLA, etc).

**Comment by acrymble** [comment]
Maybe we should just steal / borrow the O'Reilly styleguide then? http://oreillymedia.github.io/production-resources/styleguide/

I agree about the importance of literary and technical style here.

**Comment by drjwbaker** [comment]
Thanks for pursuing this Adam. I'd like to see a stylesheet guide authors on how to spot when they are drifting between tenses and offer some tips on how to write in the second person plural (you) form. On the latter and taking @alsalin's point, I actually don't want to enforce either 'next you should enter' or 'next we enter', rather I want authors to be consistent across a single lesson, with an acknowledgement that the 'you' form - which many authors choose to use - is actually quite to tricky to get right.

**Comment by acrymble** [comment]
@drjwbaker that sounds like you're asking for an increase in the quality of the writing more generally. Can we realastically hope to achieve that through a stylesheet?

**Comment by drjwbaker** [comment]
Isn't that in part the purpose of a stylesheet?

**Comment by acrymble** [comment]
Touchée.

**Comment by acrymble** [comment]
I've made contact with the University of Hertfordshire Press for some initial ideas. They're going to ask around and get back to me.

**Comment by acrymble** [comment]
The possible "approved suppliers" I can use if the university is paying are:

http://www.twocopywriters.co.uk/
www.proseworks.co.uk
http://www.prominentpr.co.uk/

I will try to contact them asap to get a quote.

**Comment by acrymble** [comment]
I've received feedback from a journalism lecturer, which has been very helpful. I'll incorporate that into my internal bid.

**Comment by drjwbaker** [comment]
Need someone (me?) to read a draft before you put it in?

**Comment by acrymble** [comment]
I've sent James a draft for comment. It contains sensitive details so I can't post it here.

**Comment by acrymble** [comment]
just a note that I've had some quotes and some feedback from @drjwbaker and I'm going to be putting this internal bid forward for consideration. Hopefully they will decide to support it.

**Comment by acrymble** [comment]
This has been submitted. I'll update everyone when we know the outcome.

**Comment by acrymble** [comment]
I'm pleased to report that this has been approved and will be supported by the History Group at the University of Hertfordshire. Thanks for the input everyone.

**Comment by drjwbaker** [comment]
Congrats @acrymble. We should recognise this in our 'Supporters' section https://programminghistorian.org/en/support-us#supporters
