### ISSUE TITLE
CfP IV Congreso Internacional HDH

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#1195]
La llamada de propuestas del congreso de la asociación HDH - en Toledo (España), del 23 al 25 de octubre - se publicó hace poco: https://eventos.uclm.es/24964/detail/iv-congreso-internacional-de-la-asociacion-de-humanidades-digitales-hispanicas.html

La fecha límite para presentar propuestas, aunque no lo ponga en esa página, es el 31 de marzo.

Me gustaría enviar una propuesta para presentar resultados y avances en relación con las traducciones y originales. Podemos reutilizar algunas ideas ya presentadas en otros congresos y presentar una comunicación larga (20 min) o corta (10 min) o incluso un póster. 

¿Alguien está interesado en escribir algo? @vgayolrs @mariajoafana @jenniferisasi @jamotilla

**Comment by jenniferisasi** [comment]
@arojascastro sería genial presentar en ese congreso! Para ese momento tendremos varios originales publicados y más traducciones y, desde luego, podemos reutilizar el trabajo que hicimos para la presentación en Irlanda y la que haremos (aunque está pendiente de confirmación) aquí en EEUU. Me apunto a trabajar pero, como sabes, no sé si podré viajar hasta Toledo (ojo, si confirman con suficiente antelación volar a Madrid no sería tan difícil).

**Comment by jamotilla** [comment]
Genial @arojascastro y @jenniferisasi Cuenten conmigo!

**Comment by arojascastro** [comment]
Ok, crearé un Google doc en donde podemos compartir ideas.

**Comment by arojascastro** [comment]
Jennifer y yo hemos estado trabajando en el resumen; han ampliado la fecha de envío, pero creo que es buena idea no dilatarlo más. Así que si alguien más está interesado en participar, es hora de revisar la propuesta y aportar más ideas. Durante la escritura de la propuesta, nos dimos cuenta de que podríamos hacer una encuesta a nuestros autores, traductores y revisores para saber qué partes del flujo de trabajo son más difíciles y cuáles son sus motivaciones; también queremos preguntar a los asistentes del taller de Bogotá qué piensan del proceso de escritura de tutoriales y qué retos ven.

**Comment by acrymble** [comment]
@arojascastro if you are going to be studying "human participants" - including surveying people for the purpose of generating research publications, then you will need to have ethical approval from your institution(s).

**Comment by arojascastro** [comment]
@mariajoafana did a similar survey in the beginning and I have seen another survey designed by @vgayolrs on Twitter - I think that requirement is only applicable in the UK... What others think?

**Comment by acrymble** [comment]
It's not about thinking. It's about checking with your university.

**Comment by arojascastro** [comment]
Sure, I'll check do not worry.

**Comment by arojascastro** [comment]
We somehow have already written the abstract, and we are ready to submit. If you do not say anything soon, we'll assume that you agree with it.

**Comment by arojascastro** [comment]
Resumen enviado el 12 de abril; cierro aquí.
