### ISSUE TITLE
Broken link in lesson on topic modeling and MALLET

### ISSUE THREAD

**Issue by tapar001** [programminghistorian/jekyll#120]
Here goes my first stab at opening an issue...hope I'm doing this right! 

The editor's note in the opening to the "Getting Started with Topic Modeling and MALLET" links to the Scholars' Lab Command Line Bootcamp tutorial, but the link is broken. 

Just curious: Why does the editor's note link to the Scholars' Lab tutorial, and not the PH tutorial on the Bash command line?

**Comment by ianmilligan1** [comment]
You did it perfectly! Great catch, and an excellent selection. I've made the changes as suggested. Thanks @tapar001!
