### ISSUE TITLE
small correction on the Bogota blogspot 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1206]
Again our Insight reviewer pointed that in our [blogpost ](https://programminghistorian.org/posts/bogota-workshop-report) we are saying 'Spanish to follow' while there is actually the Spanish version if you scroll down. Perhaps delete /or rephrase it @acrymble @mariajoafana ?
Thanks!

**Comment by acrymble** [comment]
"to follow" means "below". Or at least it is meant to. It's just a signal that there is a Spanish version of the text, even if you can't see it at the top of the page.

You can change it if you like.

Why is your reviewer looking at our website? Shouldn't they be reviewing your text? Or is this something else?

**Comment by amsichani** [comment]
thanks @acrymble . I am not a native speaker , so I wasn't sure about this -  tbh for me also it was clear that 'to follow' = 'see below'.
We have a link in the article to this blogpost , so I guess she just had a quick look .
