### ISSUE TITLE
broken link in lesson on OpenRefine 

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#1207]
I committed a change in this [pull request](https://github.com/programminghistorian/jekyll/pull/1204) and Travis alerted us that there is a broken link in our lesson on OpenRefine. I checked the published version on line in English and Spanish and the link is  in

> The RDF Refine extension transforms plaintext keywords into URLs. 

EN: https://programminghistorian.org/en/lessons/cleaning-data-with-openrefine#building-on-top-of-your-cleaned-data

> La extensión RDF Refine transforma las palabras clave de texto sin formato en URLs. 

ES: https://programminghistorian.org/en/lessons/cleaning-data-with-openrefine#building-on-top-of-your-cleaned-data

I couldn't find the right link. I think we just delete that sentence? Or do you want to ask authors?

**Comment by spapastamkou** [comment]
Thanks @arojascastro, this is a problem for the FR version as well (currently [under review](https://github.com/programminghistorian/ph-submissions/issues/223)). 
I found this extension that is built on the previous one: https://github.com/sparkica/rdf-extension 
I am not sure we can delete the sentence without prior consent of the authors. Could we just ask for their help to update?

**Comment by mdlincoln** [comment]
Because this sentence in ancillary to the main tutorial, it is not necessary to contact the author. What we usually will do on supplementary links like this is change it to point to the Wayback Machine's version of the link: http://web.archive.org/web/20180113121435/http://refine.deri.ie/docs

possibly add a phrase like "formerly available at" before the linkj

**Comment by acrymble** [comment]
I'm the editor for this lesson, but my internet service provider blocks access to the internet archive (I know, right?) so I can't actually verify the link. Could someone else make the update please?

**Comment by arojascastro** [comment]
Changes made for en and es. I opened a pull request here https://github.com/programminghistorian/jekyll/pull/1218

**Comment by acrymble** [comment]
this has been fixed

**Comment by spapastamkou** [comment]
ok for the FR version as well (currently under review)
