### ISSUE TITLE
ORCID for contributors

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1208]
Branching this off from #1205

**Comment by mdlincoln** [comment]
ORCID can be integrated into a publishing system at several points, from the authentication of authors for a back-end editorial system, to the display of their profiles, to metadata and logos/tags on article pages.

Because we use GitHub as our publishing platform , we wouldn't be able to integrate ORCID for user logins. This means that we couldn't authenticate the IDs in the conventional way that ORCID strongly recommends. 

What we could use it for, however, is adding metadata and ORCID badges to article pages - however ORCID doesn't seem keen on static systems like ours just pasting in ORCID ids: https://orcid.org/blog/2017/02/20/whats-so-special-about-signing

That said, they do seem to have guidelines for displaying non-authenticated ORCID ids: https://orcid.org/content/journal-display-guidelines

I'll reach out to them for some guidance - it may be possible to store some kind of auth key in the author yaml and then use a bit of javascript to get and render the ID in a way that ORCID likes, but idk how that would necessarily work yet.

**Comment by drjwbaker** [comment]
Thanks Matt. I feel there is value in the integration we'd get from ORCID, but would be keen to avoid it becoming a time consuming dependency.

**Comment by mdlincoln** [comment]
After asking around, it seems like although the authentication thing is a preferred practice, it's an acceptable fallback to just store and display the IDs via the straightforward method if all you're doing is linking to ORCID and not doing more complicated things like harvesting author info, updating records etc. I'll put together a PR adding these to lesson headers and the author bio bits.

**Comment by acrymble** [comment]
@mdlincoln I read the links you posted above, and they seemed to suggest that author control is really a key part of ORCID philosophy. Are we going to be asking consent from authors to add these in?

**Comment by mdlincoln** [comment]
@acrymble good question - yes, to clarify, I'll only add the code for displaying an ID. I think adding authors' IDs to our `ph_authors.yml` should be part of the future editorial workflow. We should NOT add IDs for past authors.
