### ISSUE TITLE
English language style decisions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1209]
Related to #1194 - Style and copy editing guide (awaiting funding decision at present).

We'll need to make some decisions about our English language lessons and the style we'll expect authors to adhere to moving forward. I suspect most people won't have strong feelings about this, but I thought I'd list some things we'll need to ultimately decide, as well as some things we've already decided:

**Already decided** :

* Chicago Manual of Style for endnotes.
* ISO 8601:2004 for dates and times

**Need to decide**:

* Which version(s) of English we publish in (UK, US, Canadian, Australian, etc).
* what authors should call their tutorials in prose (lesson, article, tutorial, etc).
* How to format "reserved" words in code (eg, "For Loop").
* Guidance for variable naming (eg, no "x" variables).
* Guidance on code line maximum length.
* Guidance on comments in code.
* Guidance on linking to Wikipedia (eg, first instance of any technical term).
* Guidance on using "you" and "we" style of writing (eg, we will now...).
* What do we italicize? (eg, "Instagram", "American Historical Association"?)
* probably lots of other things. let me know...

**Comment by mdlincoln** [comment]
from 2019-04-29 meeting: clarified that the contractor will be primarily focusing on consistent prose style (e.g. formality/informality), and once they deliver that then @mdlincoln will be able to add guidelines on code formatting, consistency in referring to variables, filenames, math.

**Comment by acrymble** [comment]
Just an update that this has finally been processed internally so I'll be able to start working with the copy editors soon.

**Comment by acrymble** [comment]
For technical guidance, I've just come across the "Zend Framework" which gives stylistic rules for PHP code writing: https://framework.zend.com/manual/2.4/en/ref/coding.standard.html. 

I'm sure there are others. If anyone has expertise in this area please make it known.

**Comment by acrymble** [comment]
From an accessibility perspective, there are rules and guidelines covering website accessibility. I dont' think we've ever tackled this directly, but we should make sure our style guidelines help us to achieve this. Relevant documents include:

https://www.w3.org/standards/webdesign/accessibility
http://www.section508.gov/
http://www.section508.gov/test/web-software
http://ec.europa.eu/ipg/standards/accessibility/index_en.htm

I'm sure there are others. If anyone has expertise in this area please make it known.

**Comment by acrymble** [comment]
I would suggest that ideally we accept any recognized form of English, but that we insist that spelling is internally consistent with that choice. It would be nice if we could spell check in the author's chosen form of English. It would also be nice if we could get a list of terms that are dialect specific to flag them up to prospective authors and encourage the use of a more neutral and more widely recognized word where appropriate.

Apparently some of the more common forms of English and their internet codes are:



| -- | -- | 
| en-AU | English - Australia |
| en-BZ | English - Belize |
| en-CA | English - Canada |
| en-CB | English - Caribbean |  
| en-IE | English - Ireland |
| en-JM | English - Jamaica |
| en-NZ | English - New Zealand |
| en-PH | English - Philippines |  
| en-ZA | English - South Africa |
| en-TT | English - Trinidad and Tobago |
| en-GB | English - United Kingdom |
| en-US | English - United States |
| en-ZW | English - Zimbabwe |

**Comment by acrymble** [comment]
I've had an initial call and they are working on the first draft of our new English styleguide.

**Comment by acrymble** [comment]
Our first draft has arrived from the copyeditors and I've circulated it to the team via email.

We need to include information on reserved words, variable naming, and comments in code.
The text is very England-centric at the moment, but we can work on these things.

**Comment by acrymble** [comment]
Do we have programming languges other than Python, Javascript and R?

Reserved words taken from the Internet:

Python 2:

and       del       from      not       while
as        elif      global    or        with
assert    else      if        pass      yield
break     except    import    print
class     exec      in        raise
continue  finally   is        return
def       for       lambda    try

Python 3:

False      class      finally    is         return
None       continue   for        lambda     try
True       def        from       nonlocal   while
and        del        global     not        with
as         elif       if         or         yield
assert     else       import     pass
break      except     in         raise

R:

if else repeat while function for in next break

TRUE FALSE NULL Inf NaN NA NA_integer_ NA_real_ NA_complex_ NA_character_ 

JavaScript:

abstract | arguments | await | boolean
-- | -- | -- | --
break | byte | case | catch
char | class | const | continue
debugger | default | delete | do
double | else | enum | eval
export | extends | false | final
finally | float | for | function
goto | if | implements | import
in | instanceof | int | interface
let | long | native | new
null | package | private | protected
public | return | short | static
super | switch | synchronized | this
throw | throws | transient | true
try | typeof | var | void
volatile | while | with | yield

**Comment by acrymble** [comment]
@mdlincoln do you have opinions on variable naming conventions?

Should we encourage a certain convention? what about multi-word multi_word multiWord variables?

I presume there are standards, but I am not versed in them.

**Comment by acrymble** [comment]
Formatting styles of specific types of words, as per O'Reilly style guide. Do we like these?:


Type of element | Final result
-- | --
Filenames, file extensions (such as .jpeg), directory paths, commands in Unix, Oracle, SQL, and Linux books | Body font italic
URLs, URIs, email addresses | Body font italic
Emphasized words (shouting!).Please use italics rather than bold for emphasis. | Body font italic
First instance of a technical term | Body font italic
Code blocks **we do this differently, but automatically** | Constant width
Registry keys | Constant width
Language and script elements: class names, types, namespaces,  attributes, methods, variables, keywords, functions, modules, commands,  properties, parameters, values, objects, events, XML and HTML tags, and  similar elements. Some examples include: System.Web.UI, a while loop, the Socket class, and the Obsolete attribute. Exception: commands in Unix, Oracle, SQL, and Linux book, which are regular italics. | Constant width
Replaceable items (placeholder items in syntax); “username” in the following example is a placeholder:  login: username | Constant width italic
Commands or text to be typed by the user | Constant width bold
Line annotations | Body font italic (but smaller)
Placeholders in paths, directories, GUI items, URLs, or other text that would be italic anyway | http://www.<yourname>.com
Keyboard accelerators (Ctrl, Shift, etc.), menu titles, menu options, menu buttons | Body text

**Comment by acrymble** [comment]
This has been sent back for some further work.

**Comment by acrymble** [comment]
To close this ticket I need information from the Technical Team on the following:

- [ ] variable naming conventions for authors.

**Comment by mdlincoln** [comment]
Because there are differing formatting conventions across languages when it comes to variable casing (`snake_case` vs `CamelCase`) we should be agnostic on that.

For the content of the names, though, I think [R's Tidyverse guide](https://style.tidyverse.org/syntax.html#object-names) gives good advice:

>Generally, variable names should be nouns and function names should be verbs. Strive for names that are concise and meaningful. Where possible, avoid re-using names of common functions and variables.

**Comment by acrymble** [comment]
I've  passed this on to the copy editors who are amending the document. I expect a second draft in a few days.
