### ISSUE TITLE
Adding new category for filtering lessons 

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1210]
Hi!
What do you think about adding `R` as a category for filtering lessons? Currently is possible to filter the ones that use Python, but not the ones that use R (there are around 7).

**Comment by acrymble** [comment]
Thanks for the suggestion. It raises a bigger question of whether or not our categories are fit for purpose anymore. In the past we talked about possibly adopting an established taxonomy, though it was also raised that maybe our full text search (once implemented) will supercede the value of these tags. See issues #931 and #1018. What do you think?

**Comment by rivaquiroga** [comment]
Totally agree that this raises a bigger question, and has to do with what is currently being discussed in #1018 (specially, thinking about possible pathways for users). I'm closing this issue to keep all the discussion there.
