### ISSUE TITLE
Add RSS feed link to footer

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1224]
A suggestion from one of our readers:

"There is no way to know about new articles. I would suggest to have
at leas one of the following channels to inform readers about new
articles:
- RSS for the page https://programminghistorian.org/en/lessons/
- possibility to subscribe for a (periodic monthly) email newsletter"

Thoughts?

**Comment by walshbr** [comment]
FWIW, we have an RSS feed at https://programminghistorian.org/feed.xml. It covers blog posts, Spanish translations, and new English lessons I believe. I'm not sure if it's advertised anywhere on the site though…

**Comment by vgayolrs** [comment]
There is the twitter acount to...

**Comment by mdlincoln** [comment]
We do have a unified RSS feed already, but it's true that it's not advertised prominently. Any thoughts where that could go?

I think doing an email blast is really not necessary given the existing channels we have though.

**Comment by vgayolrs** [comment]
I do not know, Matt (you're the one who knows most about this), but maybe a link to the `xml` with the `.rss` [logo](https://upload.wikimedia.org/wikipedia/commons/4/43/Feed-icon.svg) in the right corner of the header or footer of the main page.

**Comment by acrymble** [comment]
There might be free services that would "email" new RSS updates to people who wanted that.

**Comment by acrymble** [comment]
This should be the remit of our new Communication Manager #1215

**Comment by acrymble** [comment]
I've assigned this to @jenniferisasi in her new role as Communication Manager.

**Comment by amsichani** [comment]
Hi @jenniferisasi do we have any progress/ ideas on this?

**Comment by jenniferisasi** [comment]
@amsichani thanks for reminding me of this ticket. Currently, I have established the 3-month trilingual newsletter (in blog-post form) that covers all the lessons that have been published within that time frame and regardless of them being original or translations + other info. This is also posted on Twitter. 

In order for more people to get a note about the newsletter, we could make the RSS link accessible in the footer (I don't know how this functions though), but then they will be getting updates for each lesson - which we already publish on Twitter - plus the blog posts (it could be many one week and none for...a month or more).

**Comment by walshbr** [comment]
Let me know if you need implementing an RSS link in the footer @jenniferisasi.

**Comment by jenniferisasi** [comment]
I'm starting to work on this. I have already identified how to add the RSS link to the footer, the rss xml file to link to.

**Comment by mdlincoln** [comment]
Closed by #1565
