### ISSUE TITLE
Optimize lessons for printing

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#1225]
Another suggestion from a reader: To optimize our lessons for printing. 

Some initial suggestions include: fixing the header and footer to display properly when printed, check code blocks to ensure they print properly and don't run off the page.

**Comment by vgayolrs** [comment]
Hi @alsalin , Once (2017/04) there was a discussion to create PDF of the lessons with the idea of making a version-of-record –that can be used as friendly printable version– #417

**Comment by mdlincoln** [comment]
Yes, for most of the reasons pointed out in #417 due to the frequency of small updates to our lessons, we're NOT going to produce PDFs. But it's true that some components on the printed versions of the webpage don't render ideally - I'll flag it as a task to look at. @ZoeLeBlanc maybe you have some more experience with `@media print` than I...

**Comment by drjwbaker** [comment]
Agreed. We're not doing pdfs.

**Comment by acrymble** [comment]
Just for the record, can someone explain why we dont' like PDFs? Is this just practical as @mdlincoln described, or is it philosophical?

**Comment by drjwbaker** [comment]
Practical for me. Our site is too fluid.

**Comment by acrymble** [comment]
I've saved a random lesson of mine as a PDF and attached it here. It's not great, but it's fairly usable. The issues I see are mostly with the headers bleeding into the text.


[Using Gazetteers to Extract Sets of Keywords from Free-Flowing Texts | Programming Historian.pdf](https://github.com/programminghistorian/jekyll/files/2974157/Using.Gazetteers.to.Extract.Sets.of.Keywords.from.Free-Flowing.Texts.Programming.Historian.pdf)

**Comment by jenniferisasi** [comment]
Adam how did you save the lesson? I did both **export as PDF** and **print-save as PDF** in Safari, the same lesson, and it didn't capture the headers. The output is different (no page number, date, url in the footer) and the margins are very small (but this can be "fixed" if you are printing by scaling it), but ... might it be a matter of browsers and/or how people export the lessons into PDF? 

[Using Gazetteers to Extract Sets of Keywords from Free-Flowing Texts | Programming Historian.pdf](https://github.com/programminghistorian/jekyll/files/2974166/Using.Gazetteers.to.Extract.Sets.of.Keywords.from.Free-Flowing.Texts.Programming.Historian.pdf)

**Comment by acrymble** [comment]
@jenniferisasi mine was saved as a pdf on a mac using firefox's "save" features.

Do you have some energy that you could put into a bit of reading as to how we might optimize things without much effort?

**Comment by acrymble** [comment]
Or maybe the best solution is just to say "it seems to work well in Safari"?

**Comment by jenniferisasi** [comment]
Sorry I didn’t respond to you question @acrymble. But, yes, I looked a bit around and, at least for now, in some type of guideline (against a blogpost in this case cos it gets “lost”) we can explain that they can save or export it and the best browsers to do it. i can run a test in Chrome and check for other browsers. 

Update: The headers don't show up on "Print" from Chrome. 

Do the rest agree with this idea for the time being?

**Comment by arojascastro** [comment]
All our lessons are accessible as markdown on github and markdown files are very easy to transform (in theory) to pdf with pandoc for instance. We could also give the link to github and mention that people can get the files directly and transform them themselves into any other format (word, html, pdf, etc.).

**Comment by mdlincoln** [comment]
Hi, to repeat what I said above:

>it's true that some components on the printed versions of the webpage don't render ideally - I'll flag it as a task to look at.

**Comment by ZoeLeBlanc** [comment]
So finally got a chance to look into this. According to bootstrap, our 'headers', which are just nav component, gets hidden in print because most ppl don't want random nav links on their pdfs 😅. I don't think we necessarily want the links but some form of header/footer would be nice. I'm happy to start a branch playing around with optimizing for print/pdf. Would be helpful to know what ppl would like though?

**Comment by ZoeLeBlanc** [comment]
https://getbootstrap.com/docs/4.0/components/navbar/#how-it-works 
"Navbars are hidden by default when printing. Force them to be printed by adding .d-print to the .navbar. See the display utility class."

**Comment by ZoeLeBlanc** [comment]
Started a branch with an optimized print version. We now have a header that could be further styled and it would be fairly trivial to add a foot [https://github.com/programminghistorian/jekyll/tree/issue-1225](https://github.com/programminghistorian/jekyll/tree/issue-1225) . You can inspect the changes by either printing from a browser or just using the chrome inspect dev tools to render the print version [https://stackoverflow.com/questions/9540990/using-chromes-element-inspector-in-print-preview-mode](https://stackoverflow.com/questions/9540990/using-chromes-element-inspector-in-print-preview-mode) . Looking forward to hearing feedback 😊

**Comment by mdlincoln** [comment]
Thanks @ZoeLeBlanc - want to go ahead and turn that into a (draft) pull request?
