### ISSUE TITLE
Update data in authors bios?

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#1226]
Hello everyone! I am about to correct the translation of the author bio of Nabeel Sidiqui as someone translated it and treated "him" as he was "her".

So, since I am going to do the editing, I would like to ask if we should also update the data. At the time of writing the lesson, Sidiqui was a PhD candidate, but now that we have published the translation, he is already a PhD. All this because the original lessons and the translations have different publication dates. Thoughts?

**Comment by mdlincoln** [comment]
Thanks for fixing that mistake @vgayolrs. 

As for updating the bios during translations, I don't think we have a policy on that right now. In my opinion, it's nice to reach out to the original author to let them know about the translation and ask if they'd like the chance to update their bio. But I think I would only update it if the author confirms the update they want - I would not make the change based on just googling what I think their current status is.

Also, given our current infrastructure, there's only one bio per author, and it will display on any lesson they're associated with. So if you update their bio now, the original lesson will display this new bio.

**Comment by vgayolrs** [comment]
You welcome @mdlincoln 

Well, I was thinking only of the relevance of doing the data update in the translations and leaving the original Bio untouched.

**Comment by mdlincoln** [comment]
Sorry, the way that jekyll is set up right now, we can't have different bios for different lessons.

**Comment by vgayolrs** [comment]
Ok! Thanks for the clarification Matt! I think I could close this.
