### ISSUE TITLE
create Solicitudes de lecciones

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1232]
The "Solicitudes de lecciones" link under the "Contribuciones" menu on the Spanish site just points to the main page. On the English site this is the "Lesson Requests" page.

This should be removed from the Spanish site menu because it doesn't look like that team has a lessons request active.

The English page is also out of date, from what I can tell. But that's a separate issue.

@mdlincoln what file do I need to amend to remove the link?

**Comment by jenniferisasi** [comment]
Before we delete it, I want to ask if we the @programminghistorian/spanish-team want to create our own request for lessons? I guess we could adapt the blogpost we originally had (and that might be now lost after a few other posts) into that page. What do you think?

**Comment by arojascastro** [comment]
Yes, I think we can translate/adapt the English request or write our own one based on that post. I can help you Jennifer in the following days.

**Comment by acrymble** [comment]
I think it would be better for you to come up with your own, as we're discussing changing the English one, and I don't think these need to stay in sync.

**Comment by mdlincoln** [comment]
@programminghistorian/spanish-team when you create the new page, you can add its link to the _snippets.yml under the `menu-lesson-requests` category

**Comment by jenniferisasi** [comment]
Thanks for the tip, @mdlincoln!

**Comment by vgayolrs** [comment]
I think this is related to #1182

**Comment by spapastamkou** [comment]
FYI @programminghistorian/french-team

**Comment by acrymble** [comment]
This is published I believe, so I'm closing.
