### ISSUE TITLE
Can you apply for / be listed on grant applications?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1236]
I would like to get an understanding of our fundraising capabilities on the team. Can all editors please answer the following questions:

1) Are you able and willing to apply for grants related to PH activity in your current role?
2) Are you able and willing to have some of your time paid for (and therefore you would DO things related to the grant) by any current or future grant applications related to PH?
3) Are you actively hoping to have some of your time paid for by grants related to PH activities?

This will help us to understand who is looking to be involved in grant-funded activity, and who is not. If I don't hear from you I will assume "no" to all 3 questions.

Thanks @mariajoafana @ZoeLeBlanc @mdlincoln @jamotilla @spapastamkou @rivaquiroga

**Comment by JMParr** [comment]
1.) I am able and willing. 
2.) I am willing. We just passed a new faculty policy manual this past week, and I would need to verify what is possible for NTT faculty.
3.) Not currently, but possibly in the future.

**Comment by fdlaramee** [comment]
I will submit my thesis at the end of April and the odds that I will be remaining in academia to any significant extent after my defense are somewhat less than 50%. Therefore, a definite no to question 1 and "I have no idea" to questions 2 and 3.

**Comment by mpuren** [comment]
Currently I work for a European research project ; legally all my (paid) time has to be devoted to this project. So for the moment, I have to answer no to the 3 questions.

**Comment by walshbr** [comment]
1) It's complicated given red tape at UVA around staff/faculty status at UVA, but the short answer should be yes.
2) Yes, and that's generally the preferred approach for our lab re: grant writing. 
3) Not for this calendar year, but I have an idea or two that might fit in the future.

**Comment by drjwbaker** [comment]
1. Yes.
2. Yes.
3. It would keep my employer happy.

**Comment by amsichani** [comment]
1. yes
2. yes in theory - not sure how it 'd work in practice as I am on project-based contract
3. no idea for the moment - positive though

**Comment by jenniferisasi** [comment]
1. Yes. 
2. I am willing; I don't know for sure if I could for two reasons: I am currently on a scholarship, and I am currently an alien on a visitor visa in the USA. 
3. Not right now, but always open to study possible activities

**Comment by JoshuaGOB** [comment]
1. No as far as I understand it. Grad status generally prevents me from applying to most. 

2. Yes. Right now the grant that pays for my position involves developing teaching material that I’m trying to turn into PH lessons. 

3. Yes.

**Comment by arojascastro** [comment]
1. yes
2. yes in theory 
3. yes, but take into account that I normally work full time

**Comment by vgayolrs** [comment]
I believe that I can not legally receive financial support (grants) for issues other than my research work in my institution. I'm going to ask.

**Comment by acrymble** [comment]
So from what I see here so far:

1. @acrymble, @arojascastro, @jenniferisasi, @amsichani, @drjwbaker and @JMParr 
2. @acrymble, @arojascastro, @amsichani, @drjwbaker, @JMParr, @JoshuaGOB, @walshbr 
3. @acrymble, @arojascastro, @drjwbaker, @JoshuaGOB

All others are "no".

Thanks for filling this in everyone. That really helps me get an understanding of our growth capacity.

**Comment by acrymble** [comment]
I've added this as a page to the wiki. Please update it as and when required. I hope this proves useful.

https://github.com/programminghistorian/jekyll/wiki/Team-Funding-Capabilities

**Comment by drjwbaker** [comment]
Thanks for asking the question Adam.
