### ISSUE TITLE
Premios HDH 2018 for PH in Spanish

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1237]
Hi everyone, 

The [Humanidades Digitales Hispánicas](http://humanidadesdigitaleshispanicas.es) (Hispanic Digital Humanities) association has put forth an announcement for their first HDH Prize. One of their categories to opt to the prize is best tool, resource, infrastructure (2. Mejor herramienta, recurso, infraestructura) and of course I thought of us all. 

We would need to put a nomination together, under 1000 words, and fill out a form with two of us nominating the project, before April 12. 

Do we go for it? 

http://humanidadesdigitaleshispanicas.es/premios-hdh-2018/

**Comment by acrymble** [comment]
absolutely. I think it's a great way to generate publicity. Do you need help?

**Comment by mariajoafana** [comment]
Yes, lets go for it. I can work with you to write the nomination

**Comment by rivaquiroga** [comment]
Me too!

**Comment by arojascastro** [comment]
Puedo ayudar también si es necesario

**Comment by jenniferisasi** [comment]
Great! I've started a google doc to share with you all. 

https://docs.google.com/document/d/1XeTjDcXgW1Zy1yRx-TBpNHDGcfJCqv0HObGIYJEGn-E/edit?usp=sharing

**Comment by arojascastro** [comment]
Genial. Podemos reutilizar algo del texto del resumen de HDH, creo.

**Comment by arojascastro** [comment]
Hola, la fecha límite para esto es el próximo viernes; Jennifer y yo hemos estado trabajando en un borrador... ¿alguien más está interesado en revisarlo?

**Comment by arojascastro** [comment]
Hola, creo que estaría bien enviarlo mañana 11 a más tardar... con vuestro permiso.

**Comment by rivaquiroga** [comment]
¡Está muy bueno!

**Comment by jenniferisasi** [comment]
Enviémoslo ya. ¿Ponemos nuestros dos nombres al ser también los que queremos presentar en la conferencia?

**Comment by acrymble** [comment]
Good luck!

**Comment by arojascastro** [comment]
Enviado el formulario y texto por email con copia a Jennifer el 11 de abril. Merci.
