### ISSUE TITLE
Translation training for English team

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1249]
We've got exciting news today that our first ever Spanish-first tutorial has been published: https://programminghistorian.org/es/lecciones/corpus-paralelo-lfaligner

That means that we on the English team don't have a full suite of tutorials for the first time ever.

Can we get some input from the Spanish team on how we can set up a Spanish-to-English translation system so that we can get back in sync with what you've achieved?

**Comment by jenniferisasi** [comment]
@acrymble, and for the whole team, my first question here would be: 
Is the @programminghistorian/spanish-team going to be in charge of the Spanish to English translations or is the @programminghistorian/english-team (and the @programminghistorian/french-team by extension into the future) securing translators/editors to translate, revise and edit the translations? Usually the translators translate into their first language. 

In general, I think once we get to work on  #1199 Translators Guidelines, it would set a nice workflow for any language translation.

**Comment by acrymble** [comment]
I can't speak for everyone, but I think it makes the most sense for each language publication to be responsible for any translations they publish. That way a single managing editor has oversight over the whole publication.

**Comment by jenniferisasi** [comment]
That is what I was hoping for but I needed to ask :) 

A few things that I can think of right now are to start the process while we work on #1199: 
- promote the new "need" to your audience: translation opportunity besides the original authorship
- promote the "need" for reviewers with a minimum of experience on translation work 
- start building a database of volunteers for both roles
- create additional folder for translations in ph-submissions 
- explore the tickets on our translations to get a sense of the review/edition process

**Comment by acrymble** [comment]
Do we have anyone who is a native English speaker who can read Spanish well enough to translate this lesson?

**Comment by drjwbaker** [comment]
Agreed. I think the EN publication needs to recruit people who can translate from ES and FR. I'm useless in this regard, I'm afraid.

**Comment by amsichani** [comment]
I have two people in mind with this profile if we need to recruit.

**Comment by arojascastro** [comment]
I agree with @jenniferisasi suggestions. I think you could start by promoting translation activities in your page and launch a public call to reach reviewers with interlingual skills and translators es-en. In the meantime we can work together on our guidelines for translators.

**Comment by acrymble** [comment]
I think we need guidance in place before we seek a translator. How long do we expect #1199 to be in development?

And does anyone on our English editorial team want to act as a liason on our behalf in the development of those guidelines? @drjwbaker @amsichani @mdlincoln @ZoeLeBlanc ?

**Comment by drjwbaker** [comment]
Love to, but overwhelmed right now.

**Comment by acrymble** [comment]
Thanks for the feedback. I'm going to close this and we will wait for the translation guidelines and use that as our method forward.
