### ISSUE TITLE
image for 'authors' 'reviewers' 'readers'

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#125]
@ahegel could you please find me some images i can use to represent these three types of users? They'll probably appear right next to one another.

Thanks as always.

**Comment by ahegel** [comment]
Here are some options I found:

Authors: [Man 1](https://www.flickr.com/photos/internetarchivebookimages/14584579208/), [Man 2](https://www.flickr.com/photos/internetarchivebookimages/14803471143/), [Man 3](https://www.flickr.com/photos/internetarchivebookimages/14582989438/), [Woman 1](https://www.flickr.com/photos/internetarchivebookimages/14596715977/), [Woman 2](https://www.flickr.com/photos/internetarchivebookimages/14584747337/)

Reviewers: [Duo 1](https://www.flickr.com/photos/britishlibrary/11286539426/), [Duo 2](https://www.flickr.com/photos/britishlibrary/11279635344/), [Man 1](https://www.flickr.com/photos/britishlibrary/11282759755/), [Man 2](https://www.flickr.com/photos/britishlibrary/11300023496/), [Man 3](https://www.flickr.com/photos/britishlibrary/11090519684/), [Woman 1](https://www.flickr.com/photos/britishlibrary/11301810973/)

Readers: [Man 1](https://www.flickr.com/photos/internetarchivebookimages/14595909668/), [Man 2](https://www.flickr.com/photos/britishlibrary/11192877745/) (cropped), [Man 3](https://www.flickr.com/photos/britishlibrary/11245594616/), [Woman 1](https://www.flickr.com/photos/britishlibrary/11291392343/), [Duo 1](https://www.flickr.com/photos/internetarchivebookimages/14803011343/), [Duo 2](https://www.flickr.com/photos/britishlibrary/11285583405/)

Let me know which ones you like best, and I'll upload them into the gallery when I get home tonight.
