### ISSUE TITLE
British Academy funding notice on lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1250]
We need a funding note on this lesson saying that it was supported by the British Academy as part of the Bogota event: https://programminghistorian.org/es/lecciones/corpus-paralelo-lfaligner

We used the following text on Dave Rodriguez's article: 

This tutorial was made possible with the support of the British Academy and written during the Programming Historian Workshop at La Universidad de Los Andes in Bogotá, Colombia, 31 July - 3 August, 2018.

**Comment by mdlincoln** [comment]
@mariajoafana since you're the editor for that lesson, would you please open a PR adding that text? Thank you!

**Comment by acrymble** [comment]
@jenniferisasi this also applies to https://programminghistorian.org/es/lecciones/analisis-voyant-tools

**Comment by acrymble** [comment]
Both fixed.
