### ISSUE TITLE
Lesson Index translations+original 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1251]
Just got to our main page to check our new and first original lesson and found a technical issue:
- If organized by the default new to old, it shows the original at the end (!!)
- If switched from old to new, it shows the original then translations oldest to newest. 

As we move forward with translations from Spanish to English, and potentially future original lessons in French, the 3 sites need a way to display both originals and translations in order (I don't think separating them will be good, but it'd depend on the technical solution) 

I'm afraid I need to ping @mdlincoln and @ZoeLeBlanc, and ask, is there a way to "merge" the yaml fields for translation and publication? 

- We also now need to change the words in this tab:
<img width="374" alt="Screen Shot 2019-04-04 at 2 47 10 PM" src="https://user-images.githubusercontent.com/11022533/55583875-89741b80-56e8-11e9-8295-f931e97589bb.png">

**Comment by mdlincoln** [comment]
Thanks for opening this, I've been meaning to revisit the sorting here.

I agree that it would make the most sense to sort by "appearance date", which would mean the translation date or the publication date, whichever is later. I can probably set that up in the templates - let me take a look at it.
