### ISSUE TITLE
cleaning data with openrefine lesson: dead link

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1265]
To all: in the "Cleaning Data with Openrefine" lesson, the following link: 
`[website]: http://www.powerhousemuseum.com/collection/database/download.php "website"`
redirects to a broken link: http://api.powerhousemuseum.com/

There is an archived version of this last link here: https://web.archive.org/web/20190114204425/http://api.powerhousemuseum.com/login/?next=/

The link was supposed to send to the API where the dataset for the exercice of the lesson can be downloaded. The dataset is also provided by the PH, so there is no problem for the lesson. But we should perhaps add a note in each version and provide the Internet Archive link? The Powerhouse Museum has changed its website and I was not able to find the dataset. I believe the change is very recent: the capture I provide is from December 2018. I myself had previously access to the dataset through the website when I prepared the translated lesson for the reviewing process (some time before February 25). 

This ticket concerns all PH, the lesson is in all three languages.

**Comment by mdlincoln** [comment]
Their API has been combined with their sister museums here: https://api.maas.museum/docs

I'd point to that link, and just note in parentheses that the data sample for this lesson was downloaded in 2013 and may not represent the data available now.

**Comment by spapastamkou** [comment]
I like this option, @mdlincoln, I just pointed this in the translation review ticket and wait a while to gather comments, if any.
