### ISSUE TITLE
Editors guidelines in FR: add a FR library

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1266]
I refer to the part of the editors guidelines that corresponds to that in EN: https://programminghistorian.org/en/editor-guidelines#4-find-an-image-to-represent-the-lesson
In the respective part of the FR editors guidelines it would be good, I think, to add [Gallica](https://gallica.bnf.fr/accueil/fr/content/accueil-fr?mode=desktop), the digital FR library, a a potential source of images. 
Would that be ok to have this additional resource only in the FR guidelines? What do the @programminghistorian/english-team and @programminghistorian/spanish-team think? cc @programminghistorian/french-team  
Thank you.

**Comment by arojascastro** [comment]
Sure, whatever makes sense for the French edition. Do you know if Gallica provides objects to Europeana?

**Comment by spapastamkou** [comment]
It does, yes. 

Envoyé de mon iPhone

**Comment by spapastamkou** [comment]
I added Europeana as well, thanks for the idea @arojascastro (with PR #1267)
