### ISSUE TITLE
markdown error in author instructions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#127]
I've tried to move the markdown instructions from the Wiki to the main site (as per our discussion), but the code for adding an image

{% include figure.html src="../images/filename" caption="Caption to image" %}

Is rendering instead as full HTML, which makes it awkward, because then readers can't actually see what the code looks like.

See here under 'Figures'. http://programminghistorian.org/new-lesson-workflow

Is there a solution? @wcaleb

**Comment by wcaleb** [comment]
I'll take a look later. At first glance, though, this doesn't look like the most updated version of the wiki instructions. It doesn't include my step by step pull request instructions for instance.
