### ISSUE TITLE
Update and Translate PH Wikipedia entry 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1272]
Our [wikipedia entry for PH](https://en.wikipedia.org/wiki/Programming_Historian ) needs to be updated to reflect on the French publication. It will also be worth to translate the entry into Spanish and French and link it to this one to have more online presence. 

I will take care of updating the entry and translating it into Spanish in the following days.

**Comment by jenniferisasi** [comment]
I have minimally updated the Wikipedia entry in English and translated the page to Spanish. I have kept the original one for now. I recommend the @programminghistorian/french-team they translated and publish the page in French (took me about 15 min) as I can't do it myself.

**Comment by spapastamkou** [comment]
Seen and noted, @jenniferisasi. I myself cannot do it at least immediately but perhaps the rest of @programminghistorian/french-team have the possibility. Otherwise please keep the ticket open until one of us can. Thank you.

**Comment by acrymble** [comment]
I think you have to apply for a new page, no?

**Comment by fdlaramee** [comment]
I'll take this one. I have never edited Wikipedia and I figure it's about time I got started! 😀

**Comment by fdlaramee** [comment]
The translation is online at https://fr.wikipedia.org/wiki/Programming_Historian 

Please do not hesitate to point out any deficiencies @spapastamkou @mpuren and anyone else who reads French!

**Comment by spapastamkou** [comment]
thank you so much!

**Comment by jenniferisasi** [comment]
Merci @fdlaramee! 
This issue is now ready to be closed!
