### ISSUE TITLE
DH2019 Utrecht

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#1274]
Some people showed their interest in submitting a workshop late proposal for DH2019 taking place in Utrecht on Monday 8th July. It is a half day workshop as part of "Accelerating DH". The deadline for submission is Monday 6th May. Is anyone planning to attend the conference? I think @amsichani and @mariajoafana intended to do so. Can we recap here? 

More information:

Date: 2019-03-27 16:40:25+00:00
        From: Elli Bleeker 
        Subject: DH2019 workshops - Call for participation workshop "Accelerating DH Education" 

Dear list,

We are pleased to invite submissions for lightning talk presentations (5
minutes) at the half-day workshop "Accelerating DH Education" taking place
*Monday 8th July from 9am to 1pm* at DH2019 in Utrecht.

The workshop offers an exceptional platform for communication between DH
practitioners, specialists in educational sciences and digital innovation
strategists. Among its organisers are people connected to several Dutch
universities and research institutions alongside nationwide initiatives SURF
(the collaborative ICT organisation for Dutch education and research) and the
VSNU (the Dutch Association of Universities) that together in 2018 initiated the
national "Acceleration plan educational innovation with ICT". This combination
of DH experts and educational specialists presents a unique opportunity to
consider a shared strategic agenda for innovation in DH education.

The workshop is organised primarily around two strands of discussion:
(1) *Open Education*. Open Education can be defined in multiple ways, we will
zoom in on the aspects that could be of relevance to Digital Humanities
education, and to map and imagine its implications for accessible, inclusive and
sustainable approaches to its delivery.

(2) *Shared educational agendas and initiatives*. How can we move towards more
cooperative and evidence-based approaches to teaching and training in DH across
the community? What are the key desiderata for educational innovation in DH?
This strand will feature both national agendas and international initiatives
including the #dariahTeach platform.

We welcome 200-300 word proposals from anyone involved or interested in the
creation and usage of educational resources in DH.

Submissions can be sent via the online submission form
https://docs.google.com/forms/d/e/1FAIpQLSehm6IWZ3LoXbc6ZLhlAGxq-0C84sSahOXIod5khexuF4dWxg/viewform?usp=s
f_link. 
The deadline for submission is *Monday 6th May* at midnight (CET).
Applicants will be notified of acceptance by the end of May.

Please note that the Early Bird Registration for the ADHO
conference (https://dh2019.adho.org/registration/)
is valid until the 29th of March.

Looking forward to seeing you in Utrecht this year!

Best,

Elli Bleeker, Royal Netherlands Academy of Arts Sciences
Johanna de Groot, SURF
Aodhan Kelly, Open University, Netherlands
Martine Schophuizen, Open University, Netherlands
Sally Wyatt, Maastricht University

**Comment by spapastamkou** [comment]
Organize a 5 min presentation on the basis of the 2 main ideas of the workshop (open education - shared initiatives)? 
1. Principles of openness of the PH: open access, open source, open peer review
2. The internationalisation of the PH: though for my part I find better to frame around the notion of trans-national rather than inter-national

**Comment by amsichani** [comment]
Should we draft a small proposal using Gdocs?

**Comment by arojascastro** [comment]
For the record, I shared a google drive doc with Anna Maria and Sofia. Let us know if anyone else needs access.

**Comment by mariajoafana** [comment]
Right now it seems that I won't be able to attend DH2019. If anything changes I'll let you know

**Comment by arojascastro** [comment]
In addition to the workshop, yesterday 25 April Anna-Maria, Sofia and myself sent an abstract for a late breaking poster titled *Designing Multilingual Digital Pedagogy Initiatives: The Programming Historian for English, Spanish, and French speaking DH Communities*. We are planning to work on the abstract for the workshop in the following days.

**Comment by arojascastro** [comment]
Our poster was accepted! We are still waiting for the participation at the workshop. Kudos!

**Comment by drjwbaker** [comment]
Yes! Are you planning to publish it via Zenodo is similar? Would be great to have this to refer to when talking about our multi-lingual approach.

**Comment by arojascastro** [comment]
> Yes! Are you planning to publish it via Zenodo is similar? Would be great to have this to refer to when talking about our multi-lingual approach.

We can!

**Comment by acrymble** [comment]
@amsichani I sent some stickers to you via Tim Hitchcock.

**Comment by acrymble** [comment]
@arojascastro can we close this now?
