### ISSUE TITLE
New Lesson: Análisis de corpus con Voyant Tools

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1276]
Preparing to publish a new original lesson in Spanish by Silvia Gutiérrez.

**Comment by mdlincoln** [comment]
I see this lesson was already merged. But the published lesson has a heading for footnotes... but no footnotes? Please proofread the lesson to make sure everything is looking ok

https://programminghistorian.org/es/lecciones/analisis-voyant-tools#notas-al-pie

**Comment by mdlincoln** [comment]
Specifically, these lines: https://github.com/programminghistorian/jekyll/blame/gh-pages/es/lecciones/analisis-voyant-tools.md#L412-L413

you need to have a corresponding `[^1]` and `[^2]` in the body of the text where you want the note number to appear. Only then will the note text get rendered at the bottom of the page

**Comment by jenniferisasi** [comment]
Oh, sorry Matt, and good catch! I added the connector to the footnotes dismissing it in the text, but I will fix it now. Thanks!
