### ISSUE TITLE
Replacement Spanish Managing Editor

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1280]
As @mariajoafana is going on Sabbatical in July, we need to replace her as managing editor. This would have to be one of our Spanish team members:

@vgayolrs @jenniferisasi @jamotilla @JoshuaGOB @rivaquiroga @arojascastro 

Since the position is normally from September to September, this would be until September 2020.

**Comment by arojascastro** [comment]
Since I was managing editor before, I won't take this role very soon again. I encourage others to nominate themselves.

**Comment by acrymble** [comment]
For those who are unsure what the role includes, here is a summary:

- The first point of contact for all questions from prospective authors
- Responsible for checking over and publishing all lessons
- May be called upon by other members of the team to act as a point of contact for the "Spanish" team.

**Comment by vgayolrs** [comment]
Since I have to finish a book in the following months and, plus, have been appointed as a member of the AHDO Awards Committee for this year (and that's a lot of work), I think I can't take the assignment.

**Comment by walshbr** [comment]
Just a note from the May editorial meeting that it sounds like @rivaquiroga and @jenniferisasi will discuss this further.

**Comment by mariajoafana** [comment]
I can push my sabbatical until September and complete one year as managing editor

**Comment by acrymble** [comment]
@rivaquiroga has agreed to take on this role. @mariajoafana is going to skype with her to start training for the hand over.
