### ISSUE TITLE
ACH 2019 in Pittsburgh (stickers?)

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1283]
Anyone who will be at ACH 2019 in Pittsburgh, let us know in this ticket so we can maybe meet up and say hi!

Also - we would like to order a block of new stickers (en, es, and now fr!) - @drjwbaker can you let us know what service you used to order these last time?

I'm glad to volunteer to put in an order and can then meet up to find people to hand out.

**Comment by mdlincoln** [comment]
https://www.stickermule.com

**Comment by drjwbaker** [comment]
I used stickermule. Just shared with you (@mdlincoln) the link to reorder if you want to use the same. I can't get a link out to reorder, but I have shared with the group email as well.

**Comment by mariajoafana** [comment]
I'll be there with @jenniferisasi talking about PH en español!

**Comment by amsichani** [comment]
We need some stickers to be delivered also somewhere in Europe (London/ where @arojascastro will be/ FR-ladies) for EU-based events (DH2019).

**Comment by arojascastro** [comment]
I'll be in Barcelona until June and then probably in Berlin (if everything goes well, if not in a parallel dimension).

**Comment by acrymble** [comment]
I think I still have some Spanish ones. I'll check. (turns out I dont' have any).

**Comment by walshbr** [comment]
I'll be there

**Comment by arojascastro** [comment]
I just found out I still have stickers with the Spanish logo. I'll bring some to Utrecht.

**Comment by rivaquiroga** [comment]
Hi! Just for today, a deal from StickerMule to print 3" × 3" stickers ($19 for 50): https://www.stickermule.com/deals

**Comment by mdlincoln** [comment]
I've ordered sets of ES and FR stickers for ACH - if someone wants to grab some EN ones as well that'd be great :)

**Comment by acrymble** [comment]
I have some English ones. Can one of you send me your postal address and I'll mail them? Ideally someone with a reliable postal service.

**Comment by mdlincoln** [comment]
@acrymble I'll email you, thank you!

**Comment by amsichani** [comment]
hey @acrymble we want some EN  stickers for DH2019 in Utrecht this July.

**Comment by acrymble** [comment]
Can I give them to Tim Hitchcock to pass to you @amsichani?

**Comment by acrymble** [comment]
@mdlincoln can we close this?

**Comment by amsichani** [comment]
> Can I give them to Tim Hitchcock to pass to you @amsichani?
sure thing !
