### ISSUE TITLE
Technical Team call &| comms channel

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1284]
Came up during the 2019-04-29 call that it'd be useful to maybe have a sub-team call with @mdlincoln @amsichani @ZoeLeBlanc @jenniferisasi (others?) where I can do a high-level overview of the Jekyll architecture and we can figure out some good to-do tasks that team members can begin to collaborate on.

I can send out a scheduling poll later this week if we want? 

Also would people be interested in a slack channel on e.g. the DH Slack (if we're all on there?) fwiw I have already set up a proghist monitoring channel that shows me all the commits, PRS, and comments on my own personal slack team and we could use that as well :)

**Comment by drjwbaker** [comment]
As Archivist, I'd be grateful if you could try not to turn PH Slack into a place where all PH tech discussions happen because a) content there expires unless you have a £$€ plan and b) doing so would go against our 'hey, we do almost all our work in public!' ethos. Otherwise, I'm happy :)

**Comment by amsichani** [comment]
I share @drjwbaker 's sustainability&openesss concerns. imho we could have a slack channel for actual day2day communication and dev work and report back in technical Github tickets.
It might be wise to have someone also from the @programminghistorian/french-team at the technical team.
yes to a scheduling poll and chat later this week -

**Comment by spapastamkou** [comment]
Have you met already??

**Comment by jenniferisasi** [comment]
@spapastamkou no, we haven’t met yet :)

**Comment by mdlincoln** [comment]
Can members/potential members of the technical team please see if any of these days would work for a technical call at the usual editorial call time of 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time

https://doodle.com/poll/ipg4wu4ydri6ueqi


For this first call, I'll aim to:

1. Do a walkthrough of our setup
        1. How Jekyll works with GitHub pages
        2. How we integrate with Netlify to get page previews
        3. How we use Travis-CI to run the metadata checking plugin and htmlproofer
2. Overview of the template architecture that gives us translated versions of pages
3. Figure out next steps for future coordination (automated notifications channel for tech team? documentation sprint? new feature brainstorming?)

**Comment by drjwbaker** [comment]
I'm not planning to join the tech team, but if I can make this call, I'd like to. I'd find the walkthrough useful.

**Comment by arojascastro** [comment]
same as @drjwbaker - i would like to know more but not joining the team

**Comment by mdlincoln** [comment]
The time with the most responses was Tuesday May 14th - see you all then!

**Comment by ZoeLeBlanc** [comment]
Sadly I need to bow out for a bit until my dissertation defense in August. Looking forward to joining this team in the fall :)

**Comment by mdlincoln** [comment]
Good luck with the defense!

**Comment by mdlincoln** [comment]
Discussed on the call:

- Went over the basic concept of _layouts and _includes and how they copy&paste from metadata
- looked at the basic Travis & Netlify connection
- next steps:
    - We will try monthly calls for the next few months. Goal is to get each person on the team comfortable enough to do a first pass at a new feature and give feedback to their teammates by 2020.
    - Over the next few months, we'll aim to get everyone able to build the site on their own local machines and each of us try building out a practice feature (eg. adding a "lesson keywords" metadata to a lesson and displaying it)
    - will schedule next call for about a month from now https://github.com/programminghistorian/jekyll/issues/1298
