### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by Pio82** [programminghistorian/jekyll#1287]
Do you publish a newsletter?  If not, perhaps you should.  Programming Historian is a great source of ideas and knowledge for us programmers.

**Comment by acrymble** [comment]
This sounds like a matter for our new communication manager! Thanks for raising the idea @Pio82

**Comment by spapastamkou** [comment]
Please note that one of our recent volunteers for the FR edition asked the same thing.

**Comment by jenniferisasi** [comment]
Thanks @Pio82 for reaching out to us! 
We currently don't have a newsletter as such. However, I am working on establishing a periodical blog-post that will very much resemble a newsletter as it will include notes on all the new lessons, updates on work-in-progress, etc. These will be published in our blog, to which you can subscribe via a [RSS feed](https://programminghistorian.org/feed.xml).

**Comment by acrymble** [comment]
Closing this because @jenniferisasi has initiated #1288 in response. Thanks @Pio82 for the suggestion.
