### ISSUE TITLE
Communication: Blogpost/Newsletter for June 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1288]
I am going to write a half-year newsletter/blogpost to be published in June (then every 3 months), to highlight that in the first half of 2019 we did: 
- Launch of PH in French (+ blogpost)
- First original lessons in Spanish 
- X number of new lessons
- X number of translations into Spanish and French (if ready)
- X number of visitors (+ Adam's blogpost)
- New members 
- Upcoming presentations in conferences (to let people know we will be there)
- Spanish-language browsers now account for 20% of our website traffic in the last year. Up for 9% the year before, and almost 0 the year before that.
- more?

**Comment by arojascastro** [comment]
Great idea! I strongly support this initiative and share more messages on DH lists in addition to dissemination on Twitter and FB.

**Comment by drjwbaker** [comment]
Great idea. Nothing to add. But when we get to the end of year one, we should align with the annual Zenodo deposit (2018: https://zenodo.org/record/1477854#.XNEsBaZ7mb8)

**Comment by rivaquiroga** [comment]
Looks great! Is it going to be published just in English? Or in the three languages?

**Comment by jenniferisasi** [comment]
@rivaquiroga that's a very good question...ideal: trilingual, of course! But, for one, I cannot translate the whole thing, and it could become too long a document. But as I am thinking about it, what do you think about highlighting each teams achievements in their language and then having a small version of it in the other two languages? Some type of mix instead of 3 big chunks of text, but that would need be a PDF and not a markdown blog post...

@drjwbaker does the Zenodo deposit ask for a specific type of format? (It's down right now so I can't check our files)

**Comment by jenniferisasi** [comment]
@drjwbaker I checked Zenodo now that it is back and running, and I see that it's a copy of the whole repository as is. Will you do the upload/review again in November?

**Comment by drjwbaker** [comment]
@jenniferisasi Yes, I do the deposit each November (https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#zenodo). So the latest deposit can go in the December newsletter.

**Comment by jenniferisasi** [comment]
Please apologize for the late posting; a huge commitment + trip came up at work for the first part of June and then I had my trip home for vacation. I'm finalizing and publishing this by the end of the week so that it is still within June.

**Comment by amsichani** [comment]
no worries @jenniferisasi - if you need an extra pair of eyes don't hesitate!
