### ISSUE TITLE
MALLET lesson screenshots out of date

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#129]
screenshots of output in the lesson do not match latest version of MALLET output.

**Comment by ianmilligan1** [comment]
Is this on OS X or Windows? My output on Mallet 2.0.7 on OS X looks similar to what we've got in the lesson, and 2.0 is still the current "development release" according to [their page here](http://mallet.cs.umass.edu/download.php). @shawngraham

**Comment by shawngraham** [comment]
What are you seeing on your end Fred?

**Comment by fredgibbs** [comment]
sadly, i haven't had a chance to try to replicate the report; i just wanted
to post the issue before i forgot about it. i'm hoping to look into it more
this week. my sense is that we should leave it alone until the next release
and double check then once there is less confusion about what version to
use. not sure what issue tag makes the most sense for that case.

On Fri, Jul 17, 2015 at 4:12 PM, Shawn Graham notifications@github.com
wrote:

> What are you seeing on your end Fred?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/129#issuecomment-122431642
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by shawngraham** [comment]
No problems. We'll just sit tight!

**Comment by ianmilligan1** [comment]
We've seen in this in another e-mail thread – I think we need to tweak the lesson to make sure they download the right version. That said, the MALLET site is down. Will revisit soon.
