### ISSUE TITLE
June PH Technical Team Call

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1298]
The votes are in - we will call on Thursday, June 27th. Time for the call is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

Team homework:
- [ ] Read [PH's Jekyll lesson](https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages) 
- [ ] make sure you are able to install and run jekyll on your own computer.
- [ ] Pick one lesson and one infrastructure page (e.g. https://programminghistorian.org/en/research) and compare the HTML source for those pages to the original markdown files. See if you can trace which _layout and _template files are used to render that page, and which template tags (`{{ }}`) are used to create the HTML

**Comment by amsichani** [comment]
This might sound silly but I need to say it: I m glad our tech team (following our main team's ethos) manages to respect gender balance and to support women representation in technical/programming roles - fighting this good fight (together with the DH community in general) against the "brogrammer" stereotype and culture.

**Comment by acrymble** [comment]
@mdlincoln can we get confirmation of who is on this team?

**Comment by spapastamkou** [comment]
I will follow this, @acrymble.

**Comment by mdlincoln** [comment]
team members as best I understand it (and anyone, please correct me if I'm wrong!)

- myself
- @amsichani 
- @spapastamkou 
- @ZoeLeBlanc 
- @mariajoafana 
- @jenniferisasi 
- @arojascastro 
- @walshbr 

Others who have asked not to be on the formal team but wanted to sit in on this first call
- @drjwbaker

**Comment by amsichani** [comment]
how about @jenniferisasi ?

**Comment by jenniferisasi** [comment]
> how about @jenniferisasi ?

He forgot about me :'(  (no worries @mdlincoln) I have technically been in the team a few months already and I have tried to make 'technical' changes whenever I was able to or troubleshoot Travis when possible. I think though @mariajoafana won't be part of the team because she's planning on taking a sabbatical in July #1279 

If you have some extra time, I recommend building your own jekyll site too - I am building my personal website that way and it is helping me a lot in learning how everything works together (did a little bit of html and css and even Ruby in the past but not much)

**Comment by arojascastro** [comment]
I'd like to be part of the technical team as well if possible :)

**Comment by amsichani** [comment]
Thanks for the HW @mdlincoln ;-)
may I add a couple of things we are expecting from your part:
- [ ] add us to the Slack channel for PH notifications 
- [ ] create a new Slack channel for PH tech team day2day comms
- [ ] create a GitHub tech team handle

**Comment by walshbr** [comment]
I can see myself contributing here if it's useful @mdlincoln. I didn't immediately sign up for it b/c the meeting time had been set by the time I got off sabbatical. Also just trying to be mindful of how much stuff I'm signing up for. But I've helped out with troubleshooting some of the travis PRs in the past, so seems to make sense. If you'll loop me in and have me as a latecomer, that is.

**Comment by drjwbaker** [comment]
Did you set a date/time for a June call?

**Comment by jenniferisasi** [comment]
@drjwbaker we didn't

**Comment by mdlincoln** [comment]
The votes are in - we will call on Thursday, June 27th. Time for the call is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

**Comment by walshbr** [comment]
Sounds good - I'll be there.

**Comment by arojascastro** [comment]
Sorry I just moved to Berlin, and I am still getting adapted and looking for a flat. I think I'll drop my name from the technical team. I can join you in the future perhaps. Thank you.

**Comment by drjwbaker** [comment]
Sorry, not going to be able to make this. I'll do my homework though 😁

**Comment by mdlincoln** [comment]
Hi @programminghistorian/technical-team, just a reminder to please do your homework tasks ahead of our call this Thursday!

**Comment by drjwbaker** [comment]
Did my homework. Still not sure I like GH Desktop though..

**Comment by mdlincoln** [comment]
@drjwbaker I mean, I always recommend the command line 🤣

**Comment by amsichani** [comment]
HW done - me too still struggling with the GH desktop (it might be just a matter of time though )

**Comment by spapastamkou** [comment]
I did not do my homework (sorry!), but I am ok with GH desktop. Can I follow silently?

**Comment by acrymble** [comment]
It would be nice to know what you did. I see a lot of pull requests!
