### ISSUE TITLE
Look into setting up as a legal entity in the UK

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1301]
Further to https://github.com/programminghistorian/jekyll/issues/878#issuecomment-492379337, a walkthrough of what I found at https://www.gov.uk/setting-up-charity

1. (a) Check if Setting up a Charity is Right for You.

Possibly. We may be better suited in the first instance to becoming an 'Unincorporated Association' https://www.gov.uk/unincorporated-associations There is advice on this at https://www.resourcecentre.org.uk/information/legal-structures-for-community-and-voluntary-groups/#uia (a charity that supports community groups in setting up)

1. (b) Check if you are eligible

Based on https://www.gov.uk/government/publications/what-makes-a-charity-cc4/what-makes-a-charity-cc4 we are. Summary:

- we fit one of the 13 purposes of the Charity Act ("(b)the advancement of education")
- we are for public benefit

2. Trustees

See https://www.gov.uk/guidance/trustee-board-people-and-skills?step-by-step-nav=3dd66b86-ce29-4f31-bfa2-a5a18b877f11 and https://www.gov.uk/government/publications/finding-new-trustees-cc30?step-by-step-nav=3dd66b86-ce29-4f31-bfa2-a5a18b877f11. This would involve some work.

3. Structure

Based on https://www.gov.uk/guidance/charity-types-how-to-choose-a-structure, we won't have a wide membership (e.g. who can vote at AGMs) and we probably don't want a corporate structure (as we'd have to send annual accounts to the Charity Commission), so this points again to an 'Unincorporated Association' 

4. Creating a governing document

Based on https://www.gov.uk/guidance/how-to-write-your-charitys-governing-document, I'm again erring towards an 'Unincorporated Association' because it requires a constitution only in the first instance, which I think we are better placed to write, but the work that goes into that looks like it can be converted into a full charity at a later date is needed.

**Comment by drjwbaker** [comment]
# More info on being an 'Unincorporated Association' in the UK

- annual income cannot exceed £5,000 https://www.resourcecentre.org.uk/hidden-information/routemap26a/ We can't make a profit
- we'd need a constitution https://www.resourcecentre.org.uk/information/constitutions/
- Individual members are personally responsible for any debts and contractual obligations. https://www.gov.uk/unincorporated-associations "An unincorporated organisation is, in legal terms, a collection of individuals. Any debts or obligations are the responsibility of the trustees or management committee themselves. Although this might sound scary, many small organisations actually have very few financial obligations. For example, most community groups do not employ staff or run premises, and there is little money involved in running the group’s activities. This means the risk is often very low." https://www.resourcecentre.org.uk/information/legal-structures-for-community-and-voluntary-groups/#incorporation
- we'd need voting members (i.e. us) https://www.resourcecentre.org.uk/information/legal-structures-for-community-and-voluntary-groups/#uia
- we can open a bank account https://www.resourcecentre.org.uk/information/bank-accounts-for-community-and-voluntary-organisations/ (needs three uk-based signatories, which is an implication for team membership)

From https://www.resourcecentre.org.uk/information/legal-structures-for-community-and-voluntary-groups/#uia

> An unincorporated association is a membership organisation. It can be whatever its members want it to be, and carry out whatever activity the members choose. It is the easiest, quickest and cheapest way for a group to set itself up. It is ideal for many small groups, especially those without staff or premises. A large number of groups fall into this category (sometimes without knowing it). To set up an unincorporated association, your group simply needs to draw up a constitution, setting out the rules under which it will be run.

> An unincorporated association can be a charity, but it does not have to be. Many unincorporated associations primarily benefit their own members, and are therefore not considered to be charitable and are not regulated by charity law. For an unincorporated organisation to be a charity it must have charitable aims and be run for the public benefit. If your group is not charitable you do not need to register with or report to anyone. If your group is charitable, you will need to register with the Charity Commission if your annual income is over £5,000 per year.

> An unincorporated association is not incorporated, so it cannot enter into contracts or own property in its own right.

> To set up an unincorporated association, all you need to do is write and agree a constitution in your group. If you do not plan to become a charity, your constitution should lay out whatever aims you want for your group. If you wish to be a charity, it is best to base your constitution on the model constitution on the Charity Commission website.

**Comment by acrymble** [comment]
Thanks @drjwbaker . This sounds like a good possible path forward, and more reliable than through a university. Let's put it on the agenda for the next meeting.

**Comment by drjwbaker** [comment]
Thanks @acrymble. I'm looking into whether a UK-based Unincorporated Association (because if we go for this it will be as the bank account will be in the UK) can have non-UK based voting members. I'll report back when I hear more.

**Comment by amsichani** [comment]
Great , thanks @drjwbaker . I won't be at the next meeting but I m keen to keep an eye and contribute to further investigate this path.

**Comment by drjwbaker** [comment]
Thanks @amsichani. If we go for this, the bank account will need three UK-based signatories, so we might need you on that.

**Comment by drjwbaker** [comment]
> Thanks @acrymble. I'm looking into whether a UK-based Unincorporated Association (because if we go for this it will be as the bank account will be in the UK) can have non-UK based voting members. I'll report back when I hear more.

I've been advised that I should seek legal advice on this. I'm looking into if Sussex has expertise than can answer the question. More soon.

**Comment by acrymble** [comment]
Let me know if I can help.

**Comment by drjwbaker** [comment]
@acrymble Will do. Would be useful to chat about it. Are you coming to [my talk Tuesday](https://ihrdighist.blogs.sas.ac.uk/2018/08/james-baker-decolonial-futures-for-colonial-metadata-1838-present/) per chance?

**Comment by acrymble** [comment]
If I can get back from exam board I will.

**Comment by drjwbaker** [comment]
Okay. If you don't, lets try to have a brief call later in the week.

**Comment by drjwbaker** [comment]
Update. Sussex doesn't appear to have this expertise. I've drafted an internal case for funds (matching that provided by University of Hertfordshire https://github.com/programminghistorian/jekyll/issues/1194) to instruct a lawyer to advise us. Deadline 31 May. Money has to be spent by 31 July. So hopefully we can move fast on this.

**Comment by drjwbaker** [comment]
Update. I have [a solicitor](https://www.girlings.com/our-people/caroline-armitage) interested. They are willing to provide an initial consultation and written follow up advice on structuring (note, initial thoughts are that becoming an 'Unincorporated Association' isn't the best idea and, as expected, "the overseas aspects do need to be handled carefully"). I've submitted a bid for internal Sussex funds to pay for this and some support with subsequent work that is needed (paperwork, opening bank accounts, et cetera). I'll know by mid-June. Thanks to @acrymble for comments on a draft bid. If I don't get it, let's re-evaluate. If I do, I'll take the lead but might need some rapid support from @programminghistorian/project-team with things we might then need to do like draft a constitution, start picking trustees, agreeing to be co-signatories on a bank account.

**Comment by drjwbaker** [comment]
I had a meeting today with the [head of a learned society](https://www.regionalstudies.org/) based on campus (they wanted to quiz me about OA, I wanted to quiz them about charitable status, so it was a fair exchange). A few notes of interest:

- Becoming a charity in the UK creates an admin overhead: e.g. we'd need trustees, an annual meeting, to submit annual returns the Charity Commission and HMRC.
- But becoming a charity is pretty straightforward, and most charities follow a template structure.
- Becoming an Incorporated Charity would protect us from liability if, say, we published an article that contained plagiarism and we were sued.
- Charities have to have a clear charitable mission. If we can define things in our mission that people might wish to pay for (services we are experts in), that can be a good way of generating revenue for PH.

**Comment by drjwbaker** [comment]
Note from https://github.com/programminghistorian/jekyll/issues/1286 on Board of Trustees: think about whether we want to use this tactically to engage senior folks with us, or whether we can perform those roles.

**Comment by drjwbaker** [comment]
Two updates:

- a took a meeting this with a colleague from Sussex in charge of [an externally-funded impact acceleration account](http://www.sussex.ac.uk/broadcast/read/47595). Two pieces of advice came out of this: setting up as a [not-for-profit social enterprise could be a good option](https://www.gov.uk/set-up-a-social-enterprise); once we are a legal entity, I'd be eligible to get financial support from this Sussex fund 'impact' related activity. This might include, for example, paying for a person to project manage targetted internationalization work (they were *very* interested in the India stats).
- Further to https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-495652875 Sussex have agreed to fund a solicitor to take an opinion.

**Comment by drjwbaker** [comment]
Two updates:

I took a meeting earlier this week with [someone from the Sussex Innovation Centre](https://www.sinc.co.uk/meet-the-team). Two things to note from this:

- First, they provide services such as accountancy (which we'll need) on a fee basis or via funds I can apply to at Sussex.
- Second, they have a lot of expertise in market research, and one thing we discussed is getting evidence of how our readers/audiences would feel about us transitioning from our current model of access/labour to a model that might include some kind of subscription/membership that provided additional benefits. To be clear, I'm not suggesting we ever stop being OA, just that if we become a legal entity it gives us an opportunity to look at revenue streams to reinvest in the work we do - we may as well think big rather than just make enough to pay the costs (accounting) of being a legal entity.

I took a meeting today with [the Learned Societies Liaison Officer at the Foundation for Science and Technology](http://foundation.org.uk/About/Default.aspx). Highlights:

- If we incorporate (e.g. as Charitable Incorporated Organization, or CIO) a number of things happen:
	- The CIO would be legal separated from its members (us), in that it has rights and duties
	- Members (us) cease to all be equally liable (as we are now) if we, say, publish a plagiarized article
	- The duties of members (us) become more formalized if we incorporate: e.g., the Technical Team would be responsible for ensuring that we reused software in fair and legal ways; or the Manager Editor would be responsible for ensuring that a lesson we published was not plagiarized. Now if we all volunteer our time to these tasks, the CIO would be unlikely to win a case to cover costs from the individual responsible for doing something illegal. But if any of us were paid to work for the CIO (and here we'd have to be careful re how @mdlincoln's time working for PH is described..), the CIO would have a better chance of recovering costs. In short, the duty of care is higher for paid workers than volunteers.
	- Trustees of a CIO don't have be in the UK.
	- The CIO would need a UK postal address.
	- There is a model constitution for CIOs. 
	- If we go down a CIO route, [the Learned Societies Liaison Officer at the Foundation for Science and Technology](http://foundation.org.uk/About/Default.aspx) has agreed to offer advice on the constitution we draft and to guide us through the online application process, without us having to join the the Foundation for Science and Technology (which was a very generous offer).

**Comment by drjwbaker** [comment]
To sum up for #1337:

- I'm taking meetings.
- It looks like a Charitable Incorporated Organization or a Social Enterprise are our two best options.
- Sussex has given us some money for a solicitor to take an opinion. I'll ask them to evaluate these two options.
- The Sussex money has to be spent by end of June, so hopefully I'll have a proposal for you all to consider by the end of summer.
- At present though, my recommendation is that we do become a legal entity so that a) we can grow sustainably and b) we protect ourselves as individuals from unlikely, but still potential, liabilities.

**Comment by drjwbaker** [comment]
Update: I'm meeting nominated solicitor on Monday for an initial consultation. I'll update on next steps after the meeting.

**Comment by drjwbaker** [comment]
Update. I met the [Caroline from Girlings](https://www.girlings.com/our-people/caroline-armitage) today for a consultation. It went very well. Timetable is as follows:

- by 19 July: Girlings will produce written advice on how to structure as a not-for-profit Company Limited by Guarantee called 'The Programming Historian'. This will include a draft constitution and proposed structure, as well as a rationale paper (ergo, why this type of structure in UK law works for us) and a guide to next steps (picking Directors, registering at Companies House, getting a bank account, et al).
- by 23 July: We have a chance to comment on these documents (I will circulate privately to you all)
- on 23 July: @drjwbaker to return comments to Girlings.
- by 26 July: Girlings will return document to us so that we as a team can make a decision on whether or not we go down this route.

Can I emphasis that this is a **super significant decision**.

My recommendation - based on conversations with Caroline and others - is that we do it, both for all the positive benefits we get (ability to accept and spend money to grow) and for all the risk mitigation it brings (we are personally liable for so much right now it is a little alarming..). But once the opinion is in, we need to make some time to talk this through properly.

**Comment by JMParr** [comment]
Thank you James, for your work on this!

**Comment by drjwbaker** [comment]
Thanks @JMParr. Exciting times!

**Comment by drjwbaker** [comment]
Update. @acrymble and I (under the auspices of the Project Development Team) met today to work through the documents prepared by Girlings (sorry @amsichani: all came together quick and we *think* you are away!)

We have responded to Girlings who will produce a final recommendation and articles of incorporation by 26 July (per https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-509266916)

We agree with their recommendation that the Editorial Board establish a Company Limited by Guarantee (not for profit) based in the UK.

This gives us everything we need: the ability to spend/collect money, the ability to enter into contracts, a reduction of our individual liabilities.

It also means that we will need to appoint company directors (no more than 7, no fewer than 2) to administer the business of the company: hold an AGM (to which all members, ergo in the first instance the Editorial Board will be invited and have voting power), check that accounts have been signed off correctly, be responsible for ensuring that the project is in compliance with the law (e.g. publishing copyrighted material) and if not that steps are taken to limit the damage.

We propose that the Directors in the first instance will be the Project Development Team (@drjwbaker @acrymble @amsichani) and the Managing Editors (@acrymble @mariajoafana @spapastamkou). Each Director will be appointed for a term of 3 years. If we chose to revise or expand the Directors within that period we can.

This is not a substantial shift in our ethos. The Directorial roles are not powerful roles. They do not supersede the authority of the Editorial Board. In fact the project and the company are separate entities. Instead, the roles are required to manage the company, which we can think of the admin layer of what we do.

In order to ensure there is no confusion that the company and the project are separate, Adam and I propose that we create a name for the company that is similar but distinct from The Programming Historian. We need a name that isn't already listed at [Companies House](https://beta.companieshouse.gov.uk/). I suggest **ProgHist Limited**. Though I'm open to ideas.

Next steps are for Girlings to give us the final documents, at which point I will post them here and email round the team for comment. The idea is to discuss this at our next Editorial Meeting (https://github.com/programminghistorian/jekyll/issues/1362) and if we agree to proceed, incorporate in September.

After that, our main task will be establishing routes for donations, membership models (as a more sustainable source of income), and areas to focus expenditure once the money starts trickling in!

**Comment by JMParr** [comment]
Hi, James-
Thank you for all of your hard work on this. I have no objection to either
the proposed composition of the Board of Directors or to the proposed name.
I look forward to seeing the documents when they're ready. - Jess

**Comment by drjwbaker** [comment]
Thanks @JMParr. I really appreciate your vote of confidence!

**Comment by amsichani** [comment]
Hi @drjwbaker and @acrymble - thanks for all your hard work on this (I wasn't able to join you physically, thats true). 
Company Limited by Guarantee sounds like a good idea to me. As a newbie to the company world, I searched for some extra information on the nature of the company and obligations of Directors/ members:
 https://www.companylawclub.co.uk/companies-limited-by-guarantee#why (feel free to add resources).

 First thoughts, at this stage

- what about shares?  "there may be different classes of shares, it is possible to have different classes of members in a guarantee company" or we are all gonna keep the minimum liability/shares for all of us - this needs to be declared at the company's articles  " liability is limited to the amount of the guarantee set out in the company's articles, which is typically just £1."

- The name sounds good to me - although I am not sure in what extent we want/need to keep the firm distinction between the project and the company , also at the name level. btw, we can avoid having the Ltd if we wish at the name (A not for profit company limited by guarantee can be exempted from having the word 'Limited' (or 'Ltd') at the end of its name if it is set up for certain objects. These are the promotion of commerce, art, science, education, religion, charity or any profession) . I feel that this might be a source of misunderstanding about the nature of the company and its relationship with PH, a volunteer led project.

Do keep us updated on the progress, drop me a line if you need any help and again 🎉🎉🎉

**Comment by drjwbaker** [comment]
@amsichani Thanks for the comments. In turn:

- There won't be shares. That is a different type of company ("Company Limited by Shares"). We will be a "Company Limited by Guarantee", which is common for non-profits. In this strucutre the members are guarantors. See the differences on [gov.uk](https://www.gov.uk/limited-company-formation).

- On the name, we will have a clear explainer page on this (simple facts, list of Directors, links to AGM minutes, et cetera). I feel we should keep the 'Limited' because it will be a limited company, just one without shares and that is not for profit. In addition to an explainer page, I can imagine footer text that says something like: "The Programming Historian is a volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is based in the UK, Company Number X"

**Comment by arojascastro** [comment]
Thank you a lot James for this work. It must be difficult to deal with this kind of tasks, so appreciate and I thank you for your efforts. Just one silly question: do we need to say that we are based in the UK?

**Comment by drjwbaker** [comment]
Thanks @arojascastro. I'm learning a lot of new things, so I don't mind putting in the effort.

We don't have to say we are based on the UK, but legally a company has to be registered in a country, and in this case - for reasons of clarity, precision, and transparency - we probably should say where the company based. Perhaps we could adjust the footer text (which I'm just making a suggestion at for now) to something like:

> The Programming Historian is an international volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is registered in the UK, Company Number X

**Comment by arojascastro** [comment]
cool! yes, that little change is much more accurate :)

**Comment by drjwbaker** [comment]
Agreed. 'Based in' wasn't the right phrase. Thanks for the correction.

**Comment by spapastamkou** [comment]
Thank you for your work, @drjwbaker and @acrymble. If I can be useful, please let me know.

**Comment by drjwbaker** [comment]
Thanks @spapastamkou. If we all agree to go ahead, we'll be sure to fully explain what being a director will entail.

**Comment by drjwbaker** [comment]
Short update. Documents will be with us from Girlings soon. In the meantime, note that we'll be looking to take out Charity Directors’ and Officers Indemnity Insurance once we incorporate. For why, see https://www.adviceuk.org.uk/products-and-services/insurance-financial/trustees-directors-and-officers-insurance/. Basically, without the cover, [a director’s personal assets could be at risk if a claim was to be made that contested a decision they made on behalf of the organisation](https://www.zurich.co.uk/en/charity-insurance/our-products/protecting-your-trustees).

**Comment by drjwbaker** [comment]
# Opinion and Articles

All. [Caroline Armitage at Girlings](https://www.girlings.com/our-people/caroline-armitage) has delivered an opinion and draft articles on the matter of setting up as a legal entity in the UK. The opinion is consistent with my note at https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-512845046. I attach the documents for your attention below.

@acrymble and I agree that this matter demands swift resolution. So in a slight adaptation of our [Lazy Consensus](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance) model, we propose that we aim to discuss and agree a position on this at [our next Editorial Meeting on 28 August](https://github.com/programminghistorian/jekyll/issues/1362). For the sake of simplicity, **we will decide at that meeting whether or not to proceed to incorporate a non-profit in the UK** for the purposes of administering the legal and financial aspects of our work. If we agree to proceed, we will work on the details (e.g., as discussed on this ticket, what to call the company or how to display this on the site) on a ticket by ticket basis.

So please read (or at least flick through) the attached before 28 August, and if you have any questions please post them to the ticket. If you can't make the meeting and would like to offer your support or reservations, again the ticket is the place to do it.

I'd like to take this opportunity to thanks Caroline for her swift and insightful work. And the [School of History, Art History and Philosophy at the University of Sussex](http://www.sussex.ac.uk/hahp/) for providing the funds to instruct Caroline via our Higher Education Innovation Fund, as well as for admin support with invoices and the like (especially my colleague Paige Thompson!)

- [Structure Report v2 (clean).pdf](https://github.com/programminghistorian/jekyll/files/3418352/Structure.Report.v2.clean.pdf)
- [Articles of Association v3 (clean).pdf](https://github.com/programminghistorian/jekyll/files/3418349/Articles.of.Association.v3.clean.pdf)
- [Table C Articles.pdf](https://github.com/programminghistorian/jekyll/files/3418354/Table.C.Articles.pdf) {note: don't worry too much about this document, it contains standard legal articles}

**Comment by acrymble** [comment]
Thanks @drjwbaker I have no questions at this time. Thanks for your work.

**Comment by drjwbaker** [comment]
We agreed at https://github.com/programminghistorian/jekyll/issues/1362#issuecomment-525825607 to take forward the proposal to incorporate at https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-513861381. Thanks to everyone who has contributed to this piece of work. It has been a long road since we originally started looking into ways in which we could legally receive and spend money! (see https://github.com/programminghistorian/jekyll/issues/878#issuecomment-492379337).

Closing this issue now. Note the following issues relate to decisions taken before registering as a company:

- objects and powers https://github.com/programminghistorian/jekyll/issues/1401
- incorporated name https://github.com/programminghistorian/jekyll/issues/1392
