### ISSUE TITLE
Github Sponsors

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1313]
@drjwbaker I just saw this on Github. Is this worth considering for us to crowdfund some money? https://help.github.com/en/articles/about-github-sponsors

**Comment by drjwbaker** [comment]
The GitHub match looks good. Still have to sort out our own taxes though.

**Comment by acrymble** [comment]
I've moved this to the Team Funding Capabilities page on the wiki, as this isn't something we can action at present. https://github.com/programminghistorian/jekyll/wiki/Team-Funding-Capabilities
