### ISSUE TITLE
erroneous information in jekyll lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1316]
I have been reading the Intro to Jekyll lesson by @amandavisconti. The introduction contains two pieces of information that are inconsistent.

> Difficulty level: Intermediate (this lesson includes use of the command line and git, but walks you through anything needed to complete this lesson). Forthcoming lessons in the basics of git/GitHub and GitHub Pages will be linked here when available, and provide a good background for anyone wishing for deeper understanding of the technology used in this lesson.
> 
> Up to date?: This lesson was last updated on May 2, 2017 to fix issues caused by Jekyll version 3.2.

The lesson is "beginner" according to the metadata, but says "intermediate" here in the text. This needs to be consistent.

The lesson also contains "last updated" information within the text, which is not consistent with the metadata, which automatically updates this information.

@amandavisconti can we remove these two bits?

**Comment by acrymble** [comment]
Sorry I forgot the full URL is https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages

**Comment by amandavisconti** [comment]
Will do!
