### ISSUE TITLE
Proposed revisions to lesson workflow documentation

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1318]
Based on recent experience, there is a feeling among @programminghistorian/project-team that we need to tighten up the language used in the [Editor](https://programminghistorian.org/en/editor-guidelines) and [Reviewer](https://programminghistorian.org/en/reviewer-guidelines) Guidelines to reflect the following:

- The Editor is not expected to an expert in the lesson content. This is the role of the Reviewers.
- At the end of the editorial process, the Editor recommends publication to the Managing Editor. The Managing Editor can suggest further edits.

Given the potential impacts on @programminghistorian/french-team & @programminghistorian/spanish-team we need to keep these changes short and have agreement so as to avoiding have to make further edits. Proposals:

-------

### First

In the '[Open Peer Review](https://programminghistorian.org/en/editor-guidelines#open-peer-review)' part of the Editorial Guidelines, edit:

> Before soliciting external reviews, the editor should read and try the tutorial and use their experience with the _Programming Historian_ to help the author make initial improvements (if required). The editor should complete an initial sustainability overview...

to:

> Before soliciting external reviews, the editor should read and try the tutorial and use their experience with the _Programming Historian_ to help the author make initial improvements (if required). The editor is not expected to be a expert in content of the lesson, this is the role of the [reviewers](https://programminghistorian.org/en/reviewer-guidelines).

> The editor should complete an initial sustainability overview...

Rationale: it needs to be clear that assignment of editors is based on interest and capacity, rather than expertise.

### Second

In the '[Review Philosophy](https://programminghistorian.org/en/reviewer-guidelines#review-philosophy)' part of the Reviewer Guidelines, suggest edit:

> We do not solicit reviews to judge whether a tutorial is “good enough” to be published. Rather, we consider the review process an integral component of a collaborative, productive, and sustainable effort for scholars to create useful technical resources for each other. Once a tutorial enters our editorial workflow, we work closely with the author and reviewers to maximize its potential and publish it within a reasonable amount of time.

to:

> We consider the review process an integral component of a collaborative, productive, and sustainable effort for scholars to create useful technical resources for each other. Once a tutorial enters our editorial workflow, we work closely with the author and reviewers to maximize its potential and publish it within a reasonable amount of time.

Rationale: we've already accepted the proposal. There is no judging for the editor to do at this stage. Rather, they work with the author and reviewers to produce an acceptable outcome.

### Third

In the '[Constructive Criticism](https://programminghistorian.org/en/reviewer-guidelines#constructive-criticism)' part of the Reviewer Guidelines, suggest edit:

> To review a tutorial is not simply to assess its merits and flaws (though it is important to do these as well), or judge whether it’s appropriate for the _Programming Historian_, but to help improve the tutorial by virtue of an outside perspective. We ask that reviewers provide fair and constructive criticism (and of course praise) that will improve the tutorial for a wide range of readers. We don’t send anything out for review that isn’t within a reasonable distance of publishable quality.

to:

> To review a tutorial is not simply to assess its merits and flaws (though it is important to do these as well), but to help improve the tutorial by virtue of an outside perspective. We ask that reviewers provide fair and constructive criticism (and of course praise) that will improve the tutorial for a wide range of readers.

Rationale: see 2. Also, 'reasonable distance' is too fuzzy and assumes the editor has expertise. The role of the editor is to send out to review a lesson that is well-written, sustainable, considers international audiences, et cetera, not to be an expert who can pre-judge how close the lesson is to publication.

-------

@acrymble: can you please add a suggestion regarding the role of the Managing Editor in all this.

**Comment by arojascastro** [comment]
I agree with the spirit of these changes if they make our workflow clearer and avoid problems. However, if I’m not wrong, the editor has to do a first review suggestions changes before asking two external reviewers. As it is put after those changes, it seems that the editor has not to do anything but look for reviewers. I think still editors need to know our guidelines and have some expertise on the topic necessarily. Am I wrong?

**Comment by acrymble** [comment]
/editor-guidelines.md

**Fourth:**

In the opening paragraph:

> We always encourage prospective authors to pitch their ideas before they start writing. We do not act as gatekeepers in the same way as a traditional journal. 

to:

> We always encourage prospective authors to pitch their ideas before they start writing.

The existing phrasing again takes authority away from the reviewers to be experts.

**Fifth**

> Once an author has revised the tutorial to the satisfaction of the editor, it is the editor’s job to invite two formal external peer reviews. It is entirely up to the editor who these reviewers are, however in the interest of our commitment to diversity, we encourage editors to ask themselves if they have made a sufficient effort to draw from reviewers who are distinct from themselves either by gender, nationality, race, age, or academic background. Please try not to find two people who are very like you.

to:

> Once an author has revised the tutorial to the satisfaction of the editor, it is the editor’s job to invite two formal external peer reviews. In the interest of our commitment to diversity, we encourage editors to ask themselves if they have made a sufficient effort to draw from reviewers who are distinct from themselves either by gender, nationality, race, age, or academic background. Please try not to find two people who are very like you.

It is important that we solicit expert reviews. Particularly on "analysis" articles or articles that are intermediate or advanced. Suggesting anyone can be a reviewer is problematic.

**Sixth**

> To coordinate our requests for reviewers, please use the “Programming Historian - Reviewer Tracking” Google Spreadsheet. (Contact the managing editor or Jeri Wieringa if you need help accessing the spreadsheet.) 

Jeri Wieringa is no longer part of the project.

**Seventh**

> Acceptance and Publication - Editorial Checklist

to:

> Recommend Publication - Editorial Checklist

Change of language gives the Managing Editor a clearer role in quality control

**Eight**

> Once you and the author are happy with a tutorial, the next step is to begin the publication process. This involves checking the files and adding some additional metadata:

to 

> Once you and the author are happy with a tutorial, the next step is to recommend publication to the managing editor. This involves checking the files and adding some additional metadata before contacting him or her:

This clarifies the role of the managing editor.

**Ninth**

> 5) Inform the Managing Editor to Publish

to:

> 5) Inform the Managing Editor of your Recommendation to Publish

Same as above.

**Tenth**

> The Managing Editor will publish the lesson by moving the files to the main website and check everything over. 

to:

> The Managing Editor will read and carefully check over the lesson, ensuring that it adheres to our sustainability, internationalization, and style guidelines. If in the Managing Editor's discretion, the lesson fails to meet any of those thresholds of quality, it may be returned to the author for revision. If it passes these final quality control checks, the Managing Editor will publish the lesson by moving the files to the main website and check everything over. 

This gives the Managing Editor a clear and important role in the quality control process, and will ensure greater consistency across lessons.

**Eleventh**

> The Managing Editor is responsible for moving the files to the main website via a pull request. This is also a chance for the managing editor to familiarize him/herself with the new lesson, and to quickly check that everything looks ok.

to:

> The Managing Editor is responsible for carefully checking the lesson to make sure it adheres to all of our policies and requirements. If the lesson does not meet these requirements it should be referred back to the editor for further revision. This is a crucial part of the editorial workflow. Once the Managing Editor is satisfied that the lesson meets our standards, it is his/her role to move the files to the main website via a pull request.

This clarifies the Managing Editor Role.

**Twelfth**

> 1) Look over the submission preview
> Check the submission preview for any obvious errors such as broken images or strange formatting. Inform the editor of any mistakes, which they are responsible for getting fixed.

to:

> 1) Carefully check the submission preview
> Check the submission preview for any errors or failures to meet our publication guidelines. Refer any issues back to the editor.

Same as above.

**Comment by drjwbaker** [comment]
> I agree with the spirit of these changes if they make our workflow clearer and avoid problems. However, if I’m not wrong, the editor has to do a first review suggestions changes before asking two external reviewers. As it is put after those changes, it seems that the editor has not to do anything but look for reviewers. I think still editors need to know our guidelines and have some expertise on the topic necessarily. Am I wrong?

I think the editor still has lots of work to do before sending to review. From https://programminghistorian.org/en/editor-guidelines#open-peer-review:

- read it
- test that it works
- suggest initial improvements based on their expereince
- initial sustainability review
- clarify the intended audience
- remove jargon

I've edited what I wrote at 'First' for clarity. I hope that helps @arojascastro.

**Comment by drjwbaker** [comment]
Thanks @acrymble. Except for the Managing Editor bits which required new text, I think we've managed to do most of this by removing, which should assist translation. According to our own policy https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance we need to set a formal deadline for feedback.

@acrymble: would be easier to review as a PR than a ticket?

**Comment by arojascastro** [comment]
> > I agree with the spirit of these changes if they make our workflow clearer and avoid problems. However, if I’m not wrong, the editor has to do a first review suggestions changes before asking two external reviewers. As it is put after those changes, it seems that the editor has not to do anything but look for reviewers. I think still editors need to know our guidelines and have some expertise on the topic necessarily. Am I wrong?
> 
> I think the editor still has lots of work to do before sending to review. From https://programminghistorian.org/en/editor-guidelines#open-peer-review:
> 
>     * read it
> 
>     * test that it works
> 
>     * suggest initial improvements based on their expereince
> 
>     * initial sustainability review
> 
>     * clarify the intended audience
> 
>     * remove jargon
> 
> 
> I've edited what I wrote at 'First' for clarity. I hope that helps @arojascastro.

I would add that bullet list and add a note on writing for a global audience. Being explicit about expected tasks is specially useful for new editors.

**Comment by arojascastro** [comment]
> Thanks @acrymble. Except for the Managing Editor bits which required new text, I think we've managed to do most of this by removing, which should assist translation. According to our own policy https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance we need to set a formal deadline for feedback.
> 
> @acrymble: would be easier to review as a PR than a ticket?

There are other members of the team who live on other parts of the Earth who have not even got u yet... please give people a chance to contribute :)

**Comment by drjwbaker** [comment]
Agreed. I was just thinking, given the volume of little changes proposed, that commenting on a PR (where you can see the diffs) might be easier than commenting on a ticket.

**Comment by walshbr** [comment]
This all seems fine to me. I've generally thought of my role as editor as being to ensure that a lesson is enough in the ballpark of the genre and quality of writing that we're looking for in order to proceed to the review phase. That often hasn't required me to comment from a position of expertise in a particular tool or method - more just as an expert in what the Programming Historian does. So I might just offer this change.  

From

> The editor is not expected to be a expert in content of the lesson, this is the role of the reviewers.

To

> The editor is not expected to be an expert in content of the lesson, this is the role of the reviewers. But the editor is expected to be an expert in the Programming Historian - they may suggest substantial edits to a submitted first draft in order to prepare it for reviewers, who may have more specific expertise in the content of the lesson. 

Or something to that effect. This is more just a gloss on "initial improvements (if required)", which to me perhaps undersells the level of work some people are in for even after we've accepted them.

**Comment by drjwbaker** [comment]
@walshbr Thanks for this. My qualm with your wording - and why I thought this might be easier to see as a PR - is that the Editorial Guidelines are aimed at editors not reviewers or authors, and this seems to stray into aiming at someone other than an editor. To keep it simple, what about:

> Before soliciting external reviews, the editor should read and try the tutorial and use their experience and expertise with the _Programming Historian_ to help the author make initial improvements (if required). The editor is not expected to be a expert in content of the lesson, this is the role of the reviewers.

**Comment by drjwbaker** [comment]
I'll get to this and make a PR for comment when I've finished marking :)

**Comment by drjwbaker** [comment]
I've opened a PR to make it easier for us to see these changes in context (via diff). I recommend that we suggest changes on the PR. If any larger/philosophical questions arise, comment here https://github.com/programminghistorian/jekyll/pull/1336/files

**Comment by acrymble** [comment]
This has been merged.
