### ISSUE TITLE
Privacy Policy required

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1321]
I note that we haven't got a Privacy Policy. This is now required if we are putting cookies on the computers of our readers, which we do by virtue of using Google Analytics.

I'm going to look into what text this needs to include.

**Comment by mdlincoln** [comment]
Different functionality is covered here, but we had to work one up for an online journal here at CMU: https://lps.library.cmu.edu/site/privacy/

**Comment by acrymble** [comment]
A couple of other examples from sites I'm familiar with:

https://www.rct.uk/about/policies/cookies
https://www.british-history.ac.uk/privacy

**Comment by drjwbaker** [comment]
@acrymble are you saying we need a ~'do you accept cookie' pop-up tag thing? If so, we'd need to multi-lingual that, right?

**Comment by acrymble** [comment]
Here is a first draft that cobbles together the three pages above:

---

#Privacy Policy

##Publishing Data 

As an open access publisher committed to openness, *Programming Historian* collects a number of pieces of information about authors, translators, editors, and reviewers. This information is publicly displayed in the following file: https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml, and is also used to populate various pages of our website with relevant information (eg, an author's name and bio).

Depending on one's role, the data collected may include:

* Name
* Personal or Professional website address
* Twitter handle
* Github username
* Year of joining the editorial board
* Year of leaving the editorial board
* Editorial board roles, if any
* Institutional affiliation
* A short biography, usually supplied by the author/editor
* An ORCID

In keeping with our open ethos, and to express our gratitude to authors, translators reviewers, and editors, we publicly acknowledge the names of all individuals who participate in one of these activities on the published lesson, and on our Project Team page (and its translations).

If you wish to contact us to discuss any data we may have about you, you can email our managing editor. You have the right to withdraw your consent to our use of this data, however, it should be noted that Right to Erasure may not apply to authors of a submitted article as we have a legitimate interest in keeping your data to identify you as the author of a published and indexed text.

---

##Google Analytics Data

The *Programming Historian* also collects web traffic data. We use this data to identify the needs of our visitors, to identify types of lessons that are in high demand in certain geographic regions, to promote the success of the project with potential funders, partners, and outside bodies through summary statistics, and to conduct and publish research about digital humanities and teaching and learning.

None of the data collected by Google Analytics allows us to identify individuals.

Google Analytics sets a number of "cookies" on your computer when you visit the website. These may include:

_ga, _gat 

You can block this using the "Do Not Track" settings in your browser

_utmv

This cookie is used by Google Analytics to determine the type of visitor that visits our website. The cookie determines the user's preferences based on which webpages they visit, so that we may use this data to understand which are the most popular webpages and why people visit the website.

__utmz

This cookie is used by Google Analytics to determine the type of referral used by each visitor to arrive at our website. The cookie determines if the user has come directly to our website or via a search engine, e-mail or e-mail campaign. We use this data to understand how our users arrive at our website.

__utma

This cookie is used to identify unique visitors to our website. The results are sent to our Google Analytics account, so that we can see how many unique visitors come to the site over a period of time.

__utmb

This cookie is used by Google Analytics to determine the visitor session times on our website. Each time you visit a new webpage on the website, the cookie is set to expire within 30 minutes. If it does not find an existing cookie, a new one is created.

__utmc

This cookie is used by Google Analytics in conjunction with __utmb to determine visitor sessions. Unlike __utmb, this cookie does not have an expiry date. It determines whether a new session should be created based on whether you have previously closed your browser, re-opened it and come back to the website.

**Comment by acrymble** [comment]
I dont' think we actually need to translate this @drjwbaker. But I'm not a lawyer.

**Comment by acrymble** [comment]
If anyone has experience with this can you please suggest any revisions needed?

**Comment by drjwbaker** [comment]
I don't have any expertise, but this looks reasonable.

**Comment by acrymble** [comment]
@mdlincoln I believe you were going to check this over and implement it if you were happy. I've had an approval of my ethics application on the basis of us being compliant. If this could get in place in the coming days or weeks, that would be great for that (as well as the wider need).
