### ISSUE TITLE
alt-text descriptions for lesson galley images

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1324]
re: #1315 

Technically, we can set this up to as new variables in the lesson metadata, aka

```yaml
avatar_alt: "A compass rose"
```

We will need to write all those descriptions, though! Perhaps if we can split up the work across a few volunteers so that we each write 10-20 descriptions? I'm happy to take on a set of english descriptions.

**Comment by walshbr** [comment]
I'm happy to help with this.

**Comment by mdlincoln** [comment]
We may walk through this on the technical call on Thursday and then can have a template in place for ppl to start adding alt texts
