### ISSUE TITLE
Communications team setup

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1327]
Opening this ticket as a branch off of #1285 for discussion about setting up the communications team. @jenniferisasi @walshbr @amsichani seem to be the ones associated with the team as of now. We had discussed staggering set up of all these new teams, and I had ballparked June as a time for us to think about setting this up.

**Comment by acrymble** [comment]
I had originally suggested that this team have the following positions (but that is entirely up for discussion):


 *  Communication Manager (Twitter, blog, etc (leadership)) @jenniferisasi
 *  Twitter Bot developer @walshbr
 *  Education Manager (responsible for the overall education aspect of the project (leadership)) @amsichani
 *  Research Impact Manager (supports and enhances research impacts cases for all contributors & outputs / coordinates users' analytics production and use (leadership))

Do we want to have each team led by one person who everyone else reports/communicates through? This one has 3 "leadership" roles. Just thinking about the logistics.

**Comment by walshbr** [comment]
I had the same thought. FWIW, the twitter bot is basically a dormant thing that I don't look at for months at a time these days. It required sustained attention at first and for a few weeks after the Spanish tweets started. But now it should be sorted. I think it would make sense to formalize one of these three as the "leader" for reporting purposes.

**Comment by acrymble** [comment]
@jenniferisasi and @amsichani I know you had to miss the last meeting, but we're hoping to have this team fully set up and operational by the end of June. I would suggest you have a conversation between the three of you about who will be the "leader" of this team in terms of being the contact with the rest of the group over communication issues. It would also help if you started to add a little bit more information to the wiki page (https://github.com/programminghistorian/jekyll/wiki/Communication-Team) about the other roles.

Does the Skype coordinator (maybe we should call it meeting coordinator?) need to be added to this team?

**Comment by amsichani** [comment]
I d prefer to stick to one role if possible on this team , preferably the Education one ;-) @walshbr are you interested to the research impact one? I see those roles often interrelated, esp when it comes to initiatives, outreach events etc

**Comment by walshbr** [comment]
I'm not really qualified for or interested in the research impact role. And I don't want to step on your toes if you're interested in the education piece. Maybe the impact one is a role that we could recruit for?

**Comment by acrymble** [comment]
We'd like to close this ticket in a few days and know that you all feel confident in your new roles. Can you let us know if you want any extra support in that?

**Comment by amsichani** [comment]
I d like us to have a Research Impact manager role in this team , I think is important for the project itself as well as for our own career progression through this. Anyone interested?
skype coordinator : I am happy to take this role for another year, if the team agrees. I d say lets list it as a separate role within the comms team , although the duties are quite limited.
@jenniferisasi I am extremely happy for you to lead the team!

**Comment by walshbr** [comment]
@amsichani that sounds good re: skype call coordinator for another cycle to me. It feels like it's a role that benefits from having done it before - I think you and I both have systems in place that make it an easier lift for us than for others to step into it. I'm happy to sub in when you need and to take over for a rotation when you're done with that one.

**Comment by amsichani** [comment]
> @amsichani that sounds good re: skype call coordinator for another cycle to me. It feels like it's a role that benefits from having done it before - I think you and I both have systems in place that make it an easier lift for us than for others to step into it. I'm happy to sub in when you need and to take over for a rotation when you're done with that one.

fantastic @walshbr ! lets keep it that way!

**Comment by acrymble** [comment]
To close this issue, can your team please make sure the following tasks are complete:

- [x] Assign someone the "lead" role in this team who will be the key contact for all communication matters for the rest of the editorial board
- [x] Update teamroles.yml with new roles and descriptions for the new roles
- [x] Update ph_authors.yml so that team members are associated with the new roles
- [x] Update the wiki to more fully explain the scope of this team: https://github.com/programminghistorian/jekyll/wiki/Communication-Team

It would be nice to close this ticket this month, to keep with our wider timeframe for integrating new teams one month at a time.

**Comment by jenniferisasi** [comment]
Just a note: I am awaiting to decide on #1280 to take on the lead role here or not (it would be too much for me to have both during the next school year as I will be teaching and on the job market). 
On the Wiki, my part is done, and I ask that @amsichani and @walshbr write their positions as they see fit with their interest and time.

**Comment by jenniferisasi** [comment]
Note from meeting:
- [x] @jenniferisasi is the lead
- [x] @walshbr will create the PR to update profiles/roles
- [x]  we need to add Education manager and Twitter Bot manager roles on the Wiki @amsichani 
- [x] we can recruit the research impact manager in the future
- [ ]  close ticket this month

**Comment by jenniferisasi** [comment]
I have edited our Wiki site a bit to include names and roles, but I would like each of you to describe your roles as I did with mine (Manager) to have some control of what you envision and can do.

**Comment by walshbr** [comment]
Just a note that I used the stub descriptions of the roles for adding them to the project team page (preview from the PR here) - https://deploy-preview-1354--ph-dev.netlify.com/en/project-team. So if they change substantially we will need to update that pull request. I restructured the page just slightly to make the sections clearer and added the description of the Twitter Developer role.

**Comment by amsichani** [comment]
hi @jenniferisasi @walshbr I was about to update the comms wiki and I ve discovered our team's content is lost - any ideas?Am I missing smth???

**Comment by acrymble** [comment]
I think someone renamed it to pluralize communication: https://github.com/programminghistorian/jekyll/wiki/Communications-Team

**Comment by jenniferisasi** [comment]
> I think someone renamed it to pluralize communication: https://github.com/programminghistorian/jekyll/wiki/Communications-Team

Mea culpa! I changed it because I noticed the title of this issue. Then I forgot I needed to add the -s- on the list for the menu. What is the best option for English? Once we settle to one I'll make all changes so that everything

**Comment by walshbr** [comment]
Either one seems fine to me!

**Comment by amsichani** [comment]
Education Manager role updated on the wiki !

**Comment by jenniferisasi** [comment]
Thank @amsichani and @walshbr! 
To close this ticket we only need to get the French version of our roles in PR #1354
