### ISSUE TITLE
Editorial Team setup

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1328]
Opening this ticket as a branch off of #1285 for discussion about setting up the new structure of the editorial team. This difficult appears to affect most everyone, frankly. We had discussed staggering set up of all these new teams, and I had ballparked July as a time for us to think about setting this up. But open to thoughts! Also not sure exactly what it would mean to "set up" this team, since it largely seems like it depends on the rest of the other teams being restructured as well. But I've also been out of the loop.

**Comment by acrymble** [comment]
Thinking ahead, is anyone interested in taking on the managing editor role in English next year? This should be someone who isn't already holding another leadership role. @alsalin could also continue in the role if she's happy to do so.

The handover date would be September and it would normally be for one year.

**Comment by acrymble** [comment]
Given @alsalin's current leave, which extends to July, I propose moving this team setup to August instead, to give her time to get back.

**Comment by acrymble** [comment]
In order to close this ticket we need to do the following:

- [ ] Team leader nominated
- [ ] English Managing Editor confirmed (2019-2020)
- [x] Spanish Managing Editor confirmed (2019-2020)
- [x] French Managing Editor confirmed (2019-2020)
- [ ] Update ph_authors.yml so that team members are associated with the new roles
- [x] Update the wiki to more fully explain the scope of this team

**Comment by drjwbaker** [comment]
I can't do managing editor right now do to commitments at #1330 and #1301. They are my focus until I know the scale of the work involved.

**Comment by acrymble** [comment]
I've added descriptions on the Wiki. https://github.com/programminghistorian/jekyll/wiki

Can @rivaquiroga @spapastamkou and @alsalin please review it and make changes if needed?

**Comment by rivaquiroga** [comment]
I've just read the descriptions. They seem clear to me.

**Comment by spapastamkou** [comment]
I added some links here: https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover 
Otherwise, I found a dead link here the 1st one about the graphics for the stickers): https://github.com/programminghistorian/jekyll/wiki/Things-we-pay-for-%28and-need-budget-for%29

**Comment by acrymble** [comment]
@alsalin has informed me that she plans to step down from the role of Managing Editor. The English language Programming Historian therefore needs a new Managing Editor

**Comment by acrymble** [comment]
This is awaiting the outcome of our advertised post for a new English ME.

**Comment by acrymble** [comment]
We're currently arranging interviews/discussions with the applicants.

**Comment by acrymble** [comment]
We have now appointed to this role.
