### ISSUE TITLE
Global team setup

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1329]
Opening this ticket as a branch off of #1285 for discussion about setting up the global team. 

Note from #1286 - we thought it might make sense to wrangle a team of 3-5 folks committed to being on the global team to carry the conversation further and make decisions. In other words, rather than waiting until we have a decision on global divisions to decide what the team will look like we thought it best to assemble the team and have this decision be their first task. #1285 lists these folks as interested in the global team - @amsichani @JMParr @acrymble @spapastamkou @rivaquiroga and @arojascastro (though recognizing Antonio that you said you were still thinking about it)! 

Also note that the discussion in #1296 feeds into this.

**Comment by acrymble** [comment]
I'm happy to let @JMParr take the leadership role on developing this team if she's still interested.

**Comment by quinnanya** [comment]
If there's anything I can do to help out with this (while recognizing that you probably don't need another US-based person here), let me know! The new Global Outlook::DH exec board is interested in helping connect folks where we can for projects like this.

**Comment by acrymble** [comment]
@quinnanya can you tell us more?

**Comment by quinnanya** [comment]
@acrymble GO::DH has been quiet for the last couple years, but after the recent board election, we’ve got a group of people who are very interested in it becoming more active again. Historically, it’s played a role (at least within ADHO) of raising the visibility of DH as it’s practiced outside of the US / western Europe, with a particular focus on the Global South. We’re working on putting together a call for translators to collaborate on any or all of our projects (GO::DH website overhaul, a cluster of journal articles, a refresh of “Around DH in 80 Days”, etc.) We’re also aiming to get in touch with some of the local/regional DH groups worldwide that aren’t part of another larger DH organization, to see what we can do about getting their needs and interests represented in the international scene.

It’s really early days for all of this, and it’s hard to say what part(s) will work out yet, but it seemed worth mentioning here, if only to put it on your radar. If there’s something we can do to work together with PH Global, I think we’d be interested!

**Comment by JMParr** [comment]
> I'm happy to let @JMParr take the leadership role on developing this team if she's still interested.

Sure. I can take this on.

**Comment by acrymble** [comment]
@JMParr maybe it would be a good idea to set up a Skype call with the team members?

**Comment by acrymble** [comment]
We have had our first meeting. To close this ticket we need to do the following:

- [ ] Update teamroles.yml with new roles and descriptions for the new roles @rivaquiroga 
- [ ] Update ph_authors.yml so that team members are associated with the new role @rivaquiroga
- [ ] Update the wiki to more fully explain the scope of this team @JMParr 

Riva, roles should be 'Global Lead'  and 'Global Team'.

Updating those two files will put the new roles on the Project Team page:  https://programminghistorian.org/en/project-team

You should be able to follow the model of what you see in those files, but let me know if you need help.

**Comment by acrymble** [comment]
@rivaquiroga could you let me know if you need help with this? We are ready to close this now once the above is complete.

**Comment by acrymble** [comment]
This is now complete.
