### ISSUE TITLE
add main editor to YAML data

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#133]
we should do this as we add difficulty levels to each lesson.

**Comment by jerielizabeth** [comment]
Found this while looking for details on the difficulty levels to add to the editor guidelines. Should we add instructions for adding the editor information? Add the editor as a reviewer?

**Comment by wcaleb** [comment]
It definitely shouldn't be as reviewer---put it in a new field as "editor" and we can figure out later how to display it. We can always display the editor with the reviewers if that's what we choose, but putting the editor in his/her own field preserves the option to display it separately.

**Comment by jerielizabeth** [comment]
@wcaleb that makes good sense to me! Are there formatting things we should keep in mind so that the editor name corresponds with the information in the author.yml file?

**Comment by wcaleb** [comment]
Probably first name and last name is fine. We won't need to pull in 
other information from the authors.yml file to display the editor's 
name, probably.
