### ISSUE TITLE
Dead links in "Introduction to Populating a Website with API Data"

### ISSUE THREAD

**Issue by GO5IT** [programminghistorian/jekyll#1348]
- The full title of the lesson
Introduction to Populating a Website with API Data

- The system you are using (Mac, Linux, Windows)
Windows, but OS does not matter

- Version numbers of the relevant software you are using
Firefox 67,0,03, but does not matter

- The exact steps you took that caused the problem
1) Go to https://programminghistorian.org/en/lessons/introduction-to-populating-a-website-with-api-data

2) Click 3 links of "See a full tutorial here" in 3 OS. (Line 168, 174, 181 in this code: https://github.com/programminghistorian/ph-submissions/edit/BranchWithoutExtraInfo/lessons/published/use-api-almost-without-coding-php.md)

Windows
    Double-click the downloaded file (exe) to start the installation process
    By default, XAMPP should be installed at: C:\xampp
    See a full tutorial here
Mac OSX
    Double-click the downloaded file (dmg) to start the installation process
    By default, XAMPP should be installed at: /Applications/XAMPP
    See a full tutorial here
Linux
    Change permission (chmod 755 xampp-linux-*-installer.run)
    Run installer (sudo ./xampp-linux-*-installer.run)
    By default, XAMPP should be installed at: /opt/lampp folder
    See a full tutorial here

**Comment by mdlincoln** [comment]
@GO5IT are you able to create a pull request updating these links to the ones you prefer?

**Comment by GO5IT** [comment]
@mdlincoln 
It seems I cannot click anything after selecting create "a new branch..."
![image](https://user-images.githubusercontent.com/28560661/60183096-df5aea00-9825-11e9-845e-aea7984b6749.png)
As said above, personally I prefer to remove the links completely. Please tell me exactly what to do. Thank you!

**Comment by GO5IT** [comment]
Just a note. I can modify texts in the box, but cannot activate "Propose file change", so I can only cancel.

**Comment by GO5IT** [comment]
Same for "Commit directly to the BranchWithoutExtraInfo branch"
