### ISSUE TITLE
Soliciting Scholarly Reviews

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#135]
I have contacted the following journals suggesting a review of the PH:
1) Matthew K Gold, Journal of Interactive Technology and Pedagogy (14 August 2015) [made positive noises]
2) Danny Millum, Reviews in History (14 August 2015)
3) Donna Peterson, American Historical Review (14 August 2015)
4) Jeffrey McClurken, Journal of American History (14 August 2015)

Any other suggestions?

**Comment by fredgibbs** [comment]
awesome! also maybe
http://www.journalofamericanhistory.org/submit/websitereviews.html

On Fri, Aug 14, 2015 at 12:51 PM, Adam Crymble notifications@github.com
wrote:

> I have contacted the following journals suggesting a review of the PH:
> 1) Matthew K Gold, Journal of Interactive Technology and Pedagogy (14
> August 2015) [made positive noises]
> 2) Danny Millum, Reviews in History (14 August 2015)
> 3) Donna Peterson, American Historical Review (14 August 2015)
> 
> Any other suggestions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/135.

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by acrymble** [comment]
Done, Fred.
