### ISSUE TITLE
PH Technical team call - Friday, August 30th

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1358]
Friday August 30th. Time for the call is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time.

@mdlincoln will:
- [x] put some git/github software tool suggestions on the wiki
- [x] links to liquid template docs
- [x] trial Slack team for PH Tech team to monitor issues/PRs/commits and pair program

We will continue to think through adding alt texts to lesson avatar images. Any other tasks that @programminghistorian/technical-team want to consider before our next meeting?

**Comment by walshbr** [comment]
Not necessarily for next time, and maybe you already did this on the call I couldn't make? But I think eventually it'd be good to take Jekyll and artificially introduce the four or five common things that cause travis / jekyll to break. And just do a session on reading error messages on travis and in the terminal. But that assumes people have jekyll and the site running on their computer.

**Comment by mdlincoln** [comment]
Slack team for @programminghistorian/technical-team set up at https://programminghistorian.slack.com - I think I sent invites to the relevant folks but lmk if you didn't get one.

**Comment by mdlincoln** [comment]
@programminghistorian/technical-team please vote for the meeting day here: https://doodle.com/poll/49fkiicyfgavtz5y

**Comment by mdlincoln** [comment]
I have only heard from @jenniferisasi and @walshbr so far; @programminghistorian/technical-team I'm going to edit this poll to push until September to give another chance for team members to respond. If you are UNABLE to make this, but still wish to be part of the team, please respond anyway as unavailable for all dates. I need to know who is interested in working on tech parts of the site but unable to attend this one, vs. those who no longer wish to be on the technical team.

https://doodle.com/poll/49fkiicyfgavtz5y

**Comment by mdlincoln** [comment]
@jenniferisasi @walshbr if you're still a go for this Thursday August 29 let's do it - but if next week is a better option, you'll note that there are new options on the poll.

**Comment by walshbr** [comment]
Ah sorry - filled out the other poll so long ago that my schedule has changed since then. I'm not around this Thursday, but I filled out the other dates I could do!

**Comment by mdlincoln** [comment]
Thanks! And no worries, I was the one being a bit tardy on hunting down the rest of the team to get them to respond

**Comment by ZoeLeBlanc** [comment]
I'm back from dissertating so I'm happy to join the call too. I could do this week or next one. Just let me know 😊

**Comment by mdlincoln** [comment]
@ZoeLeBlanc you can let US know by filling out that doodle poll ✅

**Comment by mdlincoln** [comment]
OK, Friday the 30th it is!

**Comment by amsichani** [comment]
hi, I m currently on holidays until 9th Sept- not able to join this time. Sorry for missing this one!

**Comment by drjwbaker** [comment]
Sadly I can't make this. In line with something @acrymble said yesterday, much as I really want to know about our technical infrastructure, I think I'm going to have to concede that I don't have the capacity right now. So can you remove me from tech team comms please, and ensure I don't get any credit for being part of your awesome team :)

**Comment by mdlincoln** [comment]
@drjwbaker that's alright James! Will make sure you're not spammed - and we'll be here when you have capacity again :)

**Comment by drjwbaker** [comment]
@mdlincoln Ta. Will do.
