### ISSUE TITLE
French translation of privacy policy

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1359]
During the 2019-06-26 meeting, we thought that because this would be a significant translation task, we published the English version first (since it is most pressing).

https://programminghistorian.org/en/privacy-policy

@programminghistorian/french-team when you have the capacity, this page will need a translation.

**Comment by spapastamkou** [comment]
@mpuren @fdlaramee how about this? I have several editions running right now and unfortunately cannot take this up.

**Comment by fdlaramee** [comment]
I am returning from post-thesis defence vacation tomorrow night. I will review the various pending translation requests on Wednesday and assign some to myself at that time. You can assume that this one will be among them.

--
François Dominic Laramée
Doctorant en histoire (numérique), Université de Montréal
Email: fdl@francoisdominiclaramee.com
Web: www.francoisdominiclaramee.com 
Twitter: @fdlaramee
ORCID ID: http://orcid.org/0000-0001-5542-3754

**Comment by mpuren** [comment]
I can translate that in French, but after the DH2019 conference. Would it be ok?

**Comment by jenniferisasi** [comment]
That’s fine! We decided that it was important to publish the English version ASAP but our versions could wait. Also, I translated it quite fast into Spanish as it is not very tricky.

**Comment by mpuren** [comment]
Ok, perfect. I do that in two weeks (or so) then

**Comment by fdlaramee** [comment]
@mpuren I have some bandwidth this week and could take care of it if you want, probably as early as tomorrow. Just let me know what's best for you.

@jenniferisasi However, I do not know how to change the site's menus in my pull request to point to the new French page instead of the English version (if we're even supposed to do it ourselves and not let the technical team do it themselves.) Any advice?

**Comment by fdlaramee** [comment]
Never mind my proposal to take this one on right away (which I just deleted); an urgent assignment from a client has filled my available bandwidth for the next week.

**Comment by mpuren** [comment]
@fdlaramee No problem, I will take care of this next week

**Comment by acrymble** [comment]
@fdlaramee @spapastamkou this ticket was assigned to Marie, but she has now left the project. Are either ofy ou willing ot take this on? Or should I close the ticket?

**Comment by fdlaramee** [comment]
@acrymble @spapastamkou I’ll take care of it, no problem.

**Comment by acrymble** [comment]
Thank you @fdlaramee

**Comment by spapastamkou** [comment]
thank you very much, @fdlaramee

**Comment by spapastamkou** [comment]
This is ok (see PR #1452) and the page has been published.
