### ISSUE TITLE
Spanish translation of privacy policy

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1360]
During the 2019-06-26 meeting, we thought that because this would be a significant translation task, we published the English version first (since it is most pressing).

https://programminghistorian.org/en/privacy-policy

@programminghistorian/spanish-team  when you have the capacity, this page will need a translation.

**Comment by jenniferisasi** [comment]
I'll take on this one.

**Comment by acrymble** [comment]
Closing this as it's been merged.
