### ISSUE TITLE
Translation of code snippets in French

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1365]
The lesson Working with Text Files in Python has been translated in FR and is ready to be published. Snippets of code in python with the simple phrase "hello world" were not translated. [Translator and one reviewer do not find this necessary](https://github.com/programminghistorian/ph-submissions/issues/232) as it is widely used in FR as well and the phrase is quite simple. I think so as well. 
However, I would like us to have consensus on this. Must say the ES translation did translate the same snippets in ES. I plan to make the PR in the coming days, so to settle this quickly I will ask there for reviews from the rest of the @programminghistorian/french-team , the @programminghistorian/spanish-team and the @programminghistorian/english-team.

**Comment by fdlaramee** [comment]
FWIW, not once in my undergrad days studying computer science in a French Canadian university did I ever see Hello World translated. I would leave it as is.

--
François Dominic Laramée
Doctorant en histoire (numérique), Université de Montréal
Email: fdl@francoisdominiclaramee.com
Web: www.francoisdominiclaramee.com 
Twitter: @fdlaramee
ORCID ID: http://orcid.org/0000-0001-5542-3754

**Comment by mpuren** [comment]
I agree with @fdlaramee. You don't have to traslate with kind of code snippets in French

**Comment by spapastamkou** [comment]
Ok, there is general agreement on this:) I'll make things simple and close this ticket with a PR, once I am done with another PR. Thanks.
