### ISSUE TITLE
English Style Guide draft

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1367]
I've got a second draft of the English language style guide. We need to revise this very quickly because the invoice has to be paid by the end of July 2019 which means we only have a few days.

[PROGRAMMING HISTORIAN style guide v2-ac.docx](https://github.com/programminghistorian/jekyll/files/3361907/PROGRAMMING.HISTORIAN.style.guide.v2-ac.docx)

Is there a member of the Team who is a native English speaker and one who is not, who would be willing to look through and let me know if there are any areas that need revising?

**Comment by drjwbaker** [comment]
Okay. Had a stab. Some more questions in there. And a few things need revising to take into account that we use markdown. Thanks for making this happen @acrymble.

**Comment by drjwbaker** [comment]
[2019-07-05_JB-edit_PROGRAMMING.HISTORIAN.style.guide.v2-ac.docx](https://github.com/programminghistorian/jekyll/files/3362818/2019-07-05_JB-edit_PROGRAMMING.HISTORIAN.style.guide.v2-ac.docx)

**Comment by acrymble** [comment]
Thanks @drjwbaker these look like fairly minor things that we can integrate. Is anyone else able to look and comment on the draft? I need to submit the invoice ASAP.

**Comment by jenniferisasi** [comment]
@acrymble This looks great! I have taken a look at the guide as the non-native English speaker you requested. I wrote a few comments where I was confused or where I though further clarification might be needed for our authors. 

Do you recall if talked about having this translated and adapted later on?

**Comment by acrymble** [comment]
@jenniferisasi where are your comments? Can you send it to me?

We only have funding for an English version. I would suggest that the needs of each publication are different and that this might prove a useful model but shouldn't be translated. Rather, each publication should create their own with their own language needs at the fore.

**Comment by jenniferisasi** [comment]
Oh, I made the changes over James' document...I downloaded the file, here: 
[2019-07-05_JB-edit_PROGRAMMING.HISTORIAN.style.guide.v2-ac-2.docx](https://github.com/programminghistorian/jekyll/files/3368115/2019-07-05_JB-edit_PROGRAMMING.HISTORIAN.style.guide.v2-ac-2.docx) or here the [link](https://drive.google.com/file/d/1x6L8m-Wgo6gGSWF4EVMHNZbN0zPGvx9F/view?usp=sharing).

**Comment by acrymble** [comment]
Thanks @jenniferisasi. These are good comments and like @drjwbaker they are fairly minor changes. With that being the case, I'm going to pay the invoice and set the copyeditors free. We can do any minor amendments ourselves.

**Comment by acrymble** [comment]
I have now reformatted this to fit our author's guidelines page. I will convert it to markdown and do a pull request to make it live.
