### ISSUE TITLE
Mobile Usability Issues

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1371]
I got an email from Google warning us that we have some mobile usability issues on the site. Full details are available in this report: https://search.google.com/search-console/mobile-usability?resource_id=https://programminghistorian.org/&utm_source=wnc_10030322&utm_medium=gamma&utm_campaign=wnc_10030322&utm_content=msg_100058679&hl=en

They are all technical matters.

**Comment by mdlincoln** [comment]
I'm unable to view this report, even when signed in under the PH email:

![Screen Shot 2019-08-20 at 9 43 53 AM](https://user-images.githubusercontent.com/4392604/63352509-3d401580-c32f-11e9-8813-9f3665375b16.png)

**Comment by mdlincoln** [comment]
Can't proceed without more info.
