### ISSUE TITLE
Global Team Meeting Agenda 23 July

### ISSUE THREAD

**Issue by JMParr** [programminghistorian/jekyll#1377]
Opening this ticket as a follow-up to issue [#1329](url). 

Call time is 23 July, 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET time. Below, I've added some agenda items, but other members of the team should feel free to add suggested items for discussion.

- [x] Defining team member's roles.
- [x] Set team goals for the next six months.
- [x] Discuss recruitment of lessons from under-represented areas.
- [x] Discuss strategies for improved cultural and linguistic diversity.
- [x] Funding applications in submission
- [x] British Academy Writing Workshop (funding open again: https://www.thebritishacademy.ac.uk/programmes/writing-workshops-2020)
- [x] GO:DH webinar, 2 August

**Comment by acrymble** [comment]
I can report on relevant funding proposals in submission.

**Comment by JMParr** [comment]
Great. Let’s add it

**Comment by acrymble** [comment]
The following institutions are working globally in DH and we should be aware of them or working with them where appropriate:

- GO:DH http://www.globaloutlookdh.org/
- EIFL https://www.eifl.net

**Comment by JMParr** [comment]
**Six Month Goals** 

- Re-apply for British Academy funds for two (smaller) workshops. A follow-up in South or Latin America, and one in Africa. 
- Possibility of fundraising for a travel bursar to support ECR in underdeveloped culture.
- See if we can improve our connections in India. (Have tried without success in the past.)
- Figure out other players working on Global DH, and create a list

**Recruitment of lessons from under-represented areas**

- Are there strategies other than workshops? Give remote mentoring program one more shot.
- Identify other players working on global DH, and create a list on the Wiki, and reach out to them.

**Strategies for improving linguistic diversity.**

- Developing language-specific initiatives: for instance, having a French-speaking team presence at Franco-speaking language group. 
- Grow French-speaking team by a few more people. Reach out to Belgium, Switzerland, etc. Sofia will create a ticket.
-Spanish team wants to see more lessons that originate in Spanish - more of the Bogota workshop tutorials, for example.
- We have created a thread [https://github.com/programminghistorian/jekyll/issues/1393](url) to discuss inter-team communications issues, to make sure that we're not stepping on other team's toes.

**Technical issues**

- Jess will create a Wiki
- Add team labels to the PH page - will need to be translate to French and Spanish as well. 

Meetings will be quarterly. So, next meeting will be in October. We'll need to keep good minutes.

**Comment by arojascastro** [comment]
I would also like to share this resource - Principles for Digital Development: https://digitalprinciples.org/

**Comment by JMParr** [comment]
Thank you, both!

**Comment by walshbr** [comment]
Closing as this meeting already happened. We can reopen if necessary.
