### ISSUE TITLE
Need suggested citation for whole project

### ISSUE THREAD

**Issue by williamjturkel** [programminghistorian/jekyll#138]
On the main landing page, we should have a suggested way of citing the Programming Historian project as a whole. My vote would be for a form that doesn't include any of our names, but I am amenable to being outvoted on that.

**Comment by acrymble** [comment]
Good point. I think we should go the other way though, and include all active members of the editorial board as 'editors' on the project. People will cite it as they like. But this is the metadata age, after all. That will let semi-automated and automated aggricators like Google Scholar make sense of what we're doing.

**Comment by ianmilligan1** [comment]
I tend to agree with @acrymble – probably an edited collection is the closest model we've got to emulate? I think that gives it more gravitas than a simple website citation format. This is not a strong preference, however, so am happy to defer to others.

**Comment by ianmilligan1** [comment]
One example that I generated from Zotero (can you tell I'm procrastinating on my writing?):

Crymble, Adam, Fred Gibbs, Allison Hegel, Caleb McDaniel, Ian Milligan, Miriam Posner, and William J. Turkel, eds. _The Programming Historian_. 2nd ed., 2015. http://programminghistorian.org/.

**Comment by wcaleb** [comment]
That looks good to me, @ianmilligan1. 

P. S. I think the correct term for what you are doing is [structured procrastination](http://www.structuredprocrastination.com/).

**Comment by williamjturkel** [comment]
I'm OK with Ian's suggestion if everyone else is.

**Comment by acrymble** [comment]
I agree.

**Comment by ianmilligan1** [comment]
Ok cool - if there's consensus, I am happy to incorporate it into the landing page.
