### ISSUE TITLE
New Lesson Template ToC Error

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1382]
Unless I'm missing something, the template for new lessons has an error in it - https://programminghistorian.org/en/author-guidelines. 

It lists this as the first entries in the contents of a lesson - 

```
# Contents

## Contents
{:.no_toc}

* TOC
{:toc}
```

But I think we actually want to replace all those lines with this piece from the editor's guidelines, correct?

```
{% include toc.html %}
```

I think the rest of the template is more clearly meant to be edited, but I think (based on the lesson I'm looking at) it's not immediately clear to authors that the ToC portions aren't meant to be kept. 

If someone from the @programminghistorian/technical-team can confirm I can PR this.

**Comment by acrymble** [comment]
I've found a few errors on that page as I'm working on the styleguide. I will take this issue on and integrate this fix into the new details. Thanks for pointing it out.

**Comment by walshbr** [comment]
Thanks @acrymble
