### ISSUE TITLE
Author formally giving publishing permission

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1383]
We will need to log that authors have given us permission to publish with us under CC-BY, and will need to find a mechanism for recording this. This is a legal requirement moving forward.

**Comment by acrymble** [comment]
I think this could be as simple as requiring them to post a set statement to their review ticket at the point of publication.

**Comment by drjwbaker** [comment]
Agree.

**Comment by walshbr** [comment]
That sounds like a fine solution.

**Comment by amsichani** [comment]
sounds reasonable.

**Comment by spapastamkou** [comment]
I agree as well. Are translators expected to do likewise?

**Comment by rivaquiroga** [comment]
Agree. 
I think it would be a good idea to record translators permission too.

**Comment by drjwbaker** [comment]
Okay. I've adapted from agreements I have signed. Something like:

`I the author|translator hereby grant a non-exclusive license to ProgHist Limited {FIXME: link to explainer page on the company} to allow The Programming Historian English|en français|en español to publish the tutorial in this ticket (including abstract, tables, figures, data, and supplemental material) under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.`

**Comment by mdlincoln** [comment]
OK @drjwbaker - is this something to go in the author or editor guidelines for the submission process?

**Comment by drjwbaker** [comment]
Can we put it in the template text when a new submission issue is opened on the submission repo?

**Comment by mdlincoln** [comment]
Go for it - although it's the editor who posts that issue, so some language will be needed about needing the _author_ to copy and paste that text into a comment they post.

**Comment by drjwbaker** [comment]
Okay. I'll try to find some time this week.

**Comment by drjwbaker** [comment]
Okay, suggest change..

> [EDITORS: Please adapt the below templates as needed when posting the initial comment on a proposed or submitted lesson. Delete this template if this issue does not concern a new lesson.]
> 
> ---
> [**Proposal Template**]
> 
> The Programming Historian has received the following proposal for a lesson on 'PROVISIONAL LESSON TITLE' by AUTHOR(S) NAME(S). The proposed learning outcomes of the lesson are:
>      
> - key learning outcome 1
> - key learning outcome 2
> - key learning outcome 3 (add as needed)
>  	
> In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than [90 DAYS BY DEFAULT BY LONGER IF AGREED WITH EDITOR]. The author(s) agree to contact the editor in advance if they need to revise the deadline.
>  
> If the lesson is not submitted by [THE AGREED DATE], the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
>  
> The main editorial contact for this lesson is [EDITOR USERNAME]. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.
> 
> ---
> 
> [**Submission Template**]
> 
> The Programming Historian has received the following tutorial on 'Editing Audio with Audacity' by INSERT GITHUB HANDLE OF AUTHOR HERE. This lesson is now under review and can be read at:
> 
> http://programminghistorian.github.io/ph-submissions/lessons/LESSON-SLUG-HERE
> 
> Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.
> 
> I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.
> 
> Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.
> 
> I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.
> 
> ## Anti-Harassment Policy
> 
> This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.
> 
> > The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our Ombudsperson (@amandavisconti). Thank you for helping us to create a safe space.

..to:


> [EDITORS: Please adapt the below templates as needed when posting the initial comment on a proposed or submitted lesson. Delete this template if this issue does not concern a new lesson.]
> 
> ---
> [**Proposal Template**]
> 
> The Programming Historian has received the following proposal for a lesson on 'PROVISIONAL LESSON TITLE' by AUTHOR(S) NAME(S). The proposed learning outcomes of the lesson are:
>      
> - key learning outcome 1
> - key learning outcome 2
> - key learning outcome 3 (add as needed)
>  	
> In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than [90 DAYS BY DEFAULT BY LONGER IF AGREED WITH EDITOR]. The author(s) agree to contact the editor in advance if they need to revise the deadline.
>  
> If the lesson is not submitted by [THE AGREED DATE], the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
>  
> The main editorial contact for this lesson is [EDITOR USERNAME]. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.
> 
> ---
> 
> [**Submission Template**]
> 
> The Programming Historian has received the following tutorial on 'Editing Audio with Audacity' by INSERT GITHUB HANDLE OF AUTHOR HERE. This lesson is now under review and can be read at:
> 
> http://programminghistorian.github.io/ph-submissions/lessons/LESSON-SLUG-HERE
> 
> Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.
> 
> I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.
> 
> Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.
> 
> I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.
> 
> ## Anti-Harassment Policy
> 
> This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.
> 
> > The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our Ombudsperson (@amandavisconti). Thank you for helping us to create a safe space.

> ---
> 
> [**Permission to Publish**]
> 
> The edit must also ensure that the author or translator post the following statement to the Submission ticket.
> 
> > I the author|translator hereby grant a non-exclusive license to ProgHist Ltd to allow The Programming Historian English|en français|en español to publish the tutorial in this ticket (including abstract, tables, figures, data, and supplemental material) under a [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en) license.

**Comment by drjwbaker** [comment]
@programminghistorian/technical-team Where is the setting in Github for amending the default text in a new issue? It doesn't appear to be a template so I can a bit confused..

**Comment by walshbr** [comment]
@drjwbaker - should be under settings - https://help.github.com/en/articles/creating-issue-templates-for-your-repository.

But I think you have to be an admin/owner on the repository in order to see it. I'm not one, so it might be something that @mdlincoln has to do?

**Comment by drjwbaker** [comment]
@walshbr That is what I looked at, but I was confused when clicking through that I was being asked to setup a template when I thought one was already setup.

**Comment by mdlincoln** [comment]
Thanks very much for your patience. You can edit this file: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/.github/ISSUE_TEMPLATE

**Comment by drjwbaker** [comment]
Raised a PR. Closing this to discuss in PR.
