### ISSUE TITLE
Error in Introduction to stylometry with Python lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1388]
This bug report has been made on the Submissions site so I have moved it here:

The lesson specifies that the user should be in the "data" directory as the working directory (see "The Dataset"); however, the f-string construct statement assumes that the working directory is one level up:
`with open(f'data/federalist_{filename}.txt') as f:`

suggestion: either change suggested working directory to one level up or change line to read:
`with open(f'federalist_{filename}.txt') as f:`

@fdlaramee can you look at these points?

**Comment by fdlaramee** [comment]
Thanks @acrymble -- I have fixed the issue in PR #1391.
