### ISSUE TITLE
Translator Guidelines in French

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1389]
I open this ticket following the #1385 issue because we work principally with translations right now and have the translator guidelines in French would greatly facilitate this work. 
I propose a 1-month time schedule to achieve this work so that we have them ready for use after the summer vacation. Ideally this ticket should be closed by the end of August in view of the PH team's August meeting. 
@fdlaramee and @mpuren, if we can all take bits to translate, this would advance easily and with no much work charge for each. I will open a pull request named after the issue so that we can work on it.

**Comment by fdlaramee** [comment]
@spapastamkou @mpuren I can take care of this translation this week. The text isn't that long so it isn't necessary to split it between the three of us.

**Comment by spapastamkou** [comment]
Thank you, @fdlaramee, let me know if I can be useful to something. There is a branch `issue-1389` and I opened a pull request #1390. If you prefer, I can make the pull request for you to share tasks.

**Comment by spapastamkou** [comment]
The #1390 has been merged, I can close this ticket.
