### ISSUE TITLE
Incorporated name

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1392]
We need a name for the company we're registering as per #1301 - setting up as a legal entity.

We've had a couple of suggestions so far:

- Method Press
- ProgHist Ltd

Please suggest names you think we should go for. My personal view is that I'd like us to think long-term and not try to be too trendy. If you have ideas, please share them.

(postscript: this assumes of course that we go ahead with #1301 and I don't mean to pre-empt the decision of the board on that with this ticket).

**Comment by drjwbaker** [comment]
Note, it can't be a name already in use in the UK https://beta.companieshouse.gov.uk/search/companies

**Comment by arojascastro** [comment]
Something that sounds well in English, Spanish and French and it is not proper English? Method Press is English; ProgHist Ltd I think works for all our three languages...

**Comment by drjwbaker** [comment]
I like that idea @arojascastro

**Comment by amsichani** [comment]
I like ProgHist Ltd mainly for the reason Antonio raised, but also because it has a direct link with the project.

**Comment by acrymble** [comment]
I like @arojascastro 's suggestion for something that makes sense across languages.

I've found a site with English-Spanish cognates : https://www.realfastspanish.com/vocabulary/spanish-cognates which might be helpful.

I admit not personally liking the ProgHist name because it's a bit too hipster techy for my liking, and it may be adventageous to look more traditional. Not quite 'Royal Historical Society', but closer to that than the other end of the spectrum.

**Comment by acrymble** [comment]
I'm trying to brainstorm a relevant play on words. The word "red" in Spanish means network and a colour in English that might make for some clever branding opportunities.  Doesn't mean anything in French. But just as another suggestion:

- Digital Red Learning
- Digital Red Societé

etc

**Comment by mdlincoln** [comment]
I agree with @arojascastro @drjwbaker @amsichani - this corporation is solely dedicated to the publication of the Programming Historian, and it's a known name so there's no risk of diluting our well-liked brand. I don't find any of the alternates provided to be compelling.

**Comment by drjwbaker** [comment]
I also think we could use ProgHist Ltd to do non-PH publication things that are within the scope of the company, if we wanted to (e.g. absorbing another methods journal is not our of scope of the objects of the company). So, my feeling is, the name won't inhibit our long term ambitions whatever we call it, and ProgHist Ltd makes sense.

**Comment by acrymble** [comment]
It looks like ProgHist Ltd has the support of the majority of those who've expressed an opinion. Let's move ahead on that basis.
