### ISSUE TITLE
Managing inter-team communications / team scopes

### ISSUE THREAD

**Issue by JMParr** [programminghistorian/jekyll#1393]
During our Global Team Meeting Call, we had a discussion about team scopes, and particularly how to make sure that the teams aren't stepping on each other's toes. How do we make sure we define who does what?

**Comment by mdlincoln** [comment]
This seems to be somewhat documented in the wiki pages, for example: https://github.com/programminghistorian/jekyll/wiki/Editorial-Team

Do you think these descriptions can be enhanced further? Or can we close this ticket?

**Comment by acrymble** [comment]
Let's close this for now and reopen if we end up with an issue that looks like there's a cross-team conflict of interest / powers overlapping.
