### ISSUE TITLE
FR team enlargement

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1394]
I open this ticket following the #1377 meeting where adding new members in the FR team was discussed among strategies for improving linguistic diversity in the PH. This coincides with real needs as we have already received various translations we have not been able to edit yet - we had evoked these needs within the @programminghistorian/french-team. Finally, this could enable the team to start producing original lessons as well. I start an agenda so that we are able to exchange here in view of the August meeting, please feel free to add items and discuss ideas. 

- [x] Number of members to recruit 
- [x] Geographical diversity 
- [x] How to recruit (call for new members, invitation...)
- [ ] Consider privileges and responsibilities of editors as per #1387  
- [ ] Consider existence of new teams (global, communication, technical etc) 
- [ ] Set a time schedule for recruitment

**Comment by spapastamkou** [comment]
Here are some ideas/thoughts of mine: 
I think we should consider to recruit at least two new members. 
As for geographical diversity, it would be natural to favour members from francophone countries that are not represented yet in the team. A question we might (or might not!) come up with could be mobilities (French living in other francophone or the opposite). 
For the way of recruitment, I like the idea of an open call. 
For the question of privileges/responsibilities of editors, I think it would help if we can precisely present the state of the finished and unfinished translations we already have (mainly from the Ecole des chartes): I can make sure they will all be in the repository by the time we'll start looking. 
For the new teams, it would be nice to let people know but I am not sure if this is something to highlight while looking for new members or after recruiting.     
Time schedule: be done with the recruitments by the end of the year latest?

**Comment by acrymble** [comment]
Just a suggestion. The new "roles" we have make it easier to specify exactly what we're recruiting for. I think you probably need someone right now who wants to focus on editing tasks only. So maybe tailor  your advert specifically for that?

I'm not sure you need to wait until the end of the year. Once the French team knows what it's looking for, I think it would be reasonable to start finding that person.

**Comment by acrymble** [comment]
Sorry, another suggestion (thinking as the new Team Development Manager who will help onboard this person). Why not suggest that you're looking for someone to translate a lesson so that they get used to the process, and thereafter become an editor? That way they get to see what the process is like from an author's perspective, and you get a translation at the same time?

**Comment by fdlaramee** [comment]
I like @acrymble's proposal of onboarding new editors by having them work on a translation first. That's pretty much what I did (or what I would have done had I already taken an editor's role on something, I should say) and it has at least helped me get somewhat comfortable with GitHub.

As for who and how many to recruit, I guess the first thing to think about is: what are the bottlenecks right now? Do we lack "pure" editors, or should we look for people who will translate and review on a regular basis in addition to running projects? It seems to me that translation reviewers have been hard to wrangle and that doing more of that work in-house, so to speak, might speed up our overall process.

(On a personal note: it seems that my professional situation will stabilize fairly soon and that, against all odds, I will stay in academia for another couple of years. At which point I will be more active, in whatever role the team sees fit.)

**Comment by jenniferisasi** [comment]
As we did with the translation review process, I am happy to talk to you three about the process of recruiting new editors for the journal, lessons learned, and things to improve (and failures, why not). A few notes on your steps: 
- Number of members to recruit: according to needs, two is a good number. 
-  Geographical diversity: the more, the better. Mobility (if I understood you correctly) is also good as long as you don't end up with people of the same nationality living in different places (for example, Antonio and I are from Spain so we wouldn't get another Spaniard on board right now even if we don't live in the country) or, people of different francophone countries all working in the same country. 
-  How to recruit (call for new members, invitation...): we've done calls for new members every time (first time by the English team, then twice ourselves). They are posted on the blog if you want to take a look. 
-  Consider privileges and responsibilities of editors as per #1387
-  Consider existence of new teams (global, communication, technical etc): Yes, consider some empty room we have in those teams and try to make it part of the new people's roles if at all possible. 
- Set a time schedule for recruitment

Congrats @fdlaramee on what seems a job you got!

**Comment by spapastamkou** [comment]
A quick summary following the #1362 meeting and the existing comments: 

Number of members to recruit: 2 
Geographical diversity: make clear that we privilege candidates from outside France albeit not excluding this country. 
How to recruit (call for new members, invitation...): combine invitation and open call (associated task: prepare a blog post). 
Consider privileges and responsibilities of editors as per #1387: Yes (facilitates explaining tasks and assuring a minimum engagement).
Consider existence of new teams (global, communication, technical etc): explain that we are looking principally for people who could do editorial/translation work; and leave open their participation to other teams. 
Set a time schedule for recruitment: I propose 13 September as deadline to publish the blog post. 

Comments/ideas are still welcome! I will close this ticket once I open a new one for the blog post.

**Comment by jenniferisasi** [comment]
@spapastamkou I've gotten a number of names to contact, mostly based in the US (mainland) but doing work on the Caribbean, so at the same time they will know people based in the region.

**Comment by spapastamkou** [comment]
thank you @jenniferisasi !
