### ISSUE TITLE
Mexico +  South African workshop grant application

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1395]
This is an initiative of the Global Team, and was discussed at our first meeting  #1377 .

The British Academy Workshops Grants are open again (deadline November 2019). We are planning on putting in an application with the hope of hosting two workshops based on our Bogota model, in mid-2020.

At present we are exploring the feasibility of hosting one in South Africa, and on in Mexico.

@acrymble will be the PI, and @rivaquiroga is going to be CoI. @jamotilla is currently making enquiries with colleagues in Mexico and may participate but has not yet committed to attending.

I am currently drafting this and will be liasing primarily with @rivaquiroga offline as we work on that proposal. Anyone with views is welcome to share them with us.

**Comment by jamotilla** [comment]
i´m in @acrymble i can help you and @rivaquiroga  with the draft

**Comment by acrymble** [comment]
Update that I've received  feedback form @rivaquiroga .  Working on that now.

**Comment by acrymble** [comment]
Due to circumstances beyond our control, we're going to pursue this through the University of Sussex with @drjwbaker

**Comment by drjwbaker** [comment]
Quick update: this is 95% done with local hosts in South Africa and Mexico. Thanks to @acrymble for getting this into such fine shape. I think we have a great chance.

**Comment by acrymble** [comment]
@drjwbaker just checking in, anything else you need from me?

**Comment by drjwbaker** [comment]
@acrymble Thanks for asking. My internal approvals at Sussex are nearly complete. On the bid, I'm just waiting on two of the Co-Applicants to complete their bit of the form, then I'll print the whole thing out for a final read. If you are willing and able to help with the latter, let me know.

**Comment by acrymble** [comment]
Sure. Always happy to help.

**Comment by drjwbaker** [comment]
This has now been submitted to the British Academy. I've added a copy of the bid to our archive. Thanks to @acrymble @rivaquiroga @asmartinez @silviaegt @zjsteyn & @anelda for their input, hard work, and desire to get involved. It is a great bid.

**Comment by silviaegt** [comment]
Yay! Congrats!
