### ISSUE TITLE
Incorporated Entity: objects and powers

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1401]
Further to #1301, we need to agree on our objects (article 2) and powers (article 3) **before** we incorporate (if we choose to do so). These are currently:

2. Object

> The object for which the Company is established is to advance the education of the public in the humanities in particular in the use of digital tools and techniques and to promote research for the public benefit in all aspects of that subject and to publish the useful results.

3. Powers (note I've only included a-b here, c-p are standard text for a non-profit limited by guarantee)

> (a) To initiate and carry out and publish comprehensive and systematic programmes of peer-reviewed tutorials that help students of the humanities learn a wide range of digital tools, techniques, and workflows to facilitate research and teaching in the United Kingdom and internationally. 
> (b) To arrange meetings, lectures, exhibitions, and visits between people and organisations involved in the use of digital tools and techniques in research and study.

**Comment by acrymble** [comment]
If I'm not mistaken, these are the ONLY things we can do, is that right? If so, everyone needs to speak up if there's something else they think we should be doing.

**Comment by drjwbaker** [comment]
Yes. The objects and powers limit our activities, that is why they are kept broad. We can broaden them further for now, but if we to were to become a charity they need to be around the current level of breadth. Any more and we'd be rejected by the Charity Commission. So, in short, it is useful to hit the right tone here.

Note that we don't need Objects at this stage (it is not a requirement of becoming a company limited by guarantee) but Caroline at Girlings recommended we have them to signal our non-profit status. And drafted them to help us understand the level of breadth we'd need.

**Comment by mdlincoln** [comment]
Does funding promotional materials or even funding some conference expenses for members of ProgHist to promote the project fall under these stipulated powers? I think those are feasible activities.

**Comment by drjwbaker** [comment]
Yes, Caroline wrote them to be legally vague, so we are only restricted by what we think is ethical (and obvious illegal things like embezzlement or false accounting/claims).

**Comment by acrymble** [comment]
In keeping with vague, I'd change this:

> (a) To initiate and carry out and publish comprehensive and systematic programmes of peer-reviewed tutorials that help students of the humanities learn a wide range of digital tools, techniques, and workflows to facilitate research and teaching in the United Kingdom and internationally.

to

> (a) To initiate and carry out and publish comprehensive and systematic programmes of peer-reviewed materials that help students of the humanities learn a wide range of digital tools, techniques, and workflows to facilitate or share research and teaching in the United Kingdom and internationally.

**Comment by drjwbaker** [comment]
Unless there are any options, I am going to proceed with @acrymble's suggested edit at https://github.com/programminghistorian/jekyll/issues/1401#issuecomment-525226474. I hope to have a revised Articles of Association done by the weekend.

**Comment by drjwbaker** [comment]
These suggestions were merged and submitted as part of the incorporation application https://github.com/programminghistorian/jekyll/issues/1437
