### ISSUE TITLE
Incorporated entity: register of members

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1402]
Further to #1301, **after** we incorporate (if we choose to do so) we will need a Register of Members of the Company.

**Comment by mdlincoln** [comment]
Is there a specific format or location that this register needs to be published? e.g. does it go onto a public HTML page? A sheet of paper mailed to some authority? etc.

**Comment by drjwbaker** [comment]
No. We just need to keep a register of members in a form that is legal in the UK (that is, in a way that doesn't controvene the 2018 Data Protection Act). I recommend it is the responsibility of one of the team members to maintain this offline, or in a private repo (they are now free on GitHub..)

**Comment by acrymble** [comment]
Maybe we should move ProgHist Ltd to a new github board?

That would declutter this one for those who aren't interested.

**Comment by drjwbaker** [comment]
Good idea. But can we hold off until we get approval from the Editorial Board? We might choose/want to manage that differently.

**Comment by walshbr** [comment]
FWIW, I think the ability to mute conversations (it unmutes automatically if you get pinned) and the elaborate tagging system we've set up makes it pretty easy to shuffle the GitHub issues based on the sub-teams you're on. So I'm not sure a separate board is necessary, but that's just me. But I agree with @drjwbaker - it will probably just depend on the volume of conversation and tickets you're imagining.

**Comment by drjwbaker** [comment]
This is now done [2019-10_ProgHistLtd_Register-of-Members.pdf](https://github.com/programminghistorian/jekyll/files/3723678/2019-10_ProgHistLtd_Register-of-Members.pdf) and added to the offline archive. I will update this monthly in line with my responsibilities as secretary of ProgHist Ltd https://github.com/programminghistorian/jekyll/issues/1404
