### ISSUE TITLE
Incorporated entity: Chairperson for Board of Directors

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1403]
Further to #1301, **after** we incorporate (if we choose to do so) we will need a Chairperson for the Board of Directors.

**Comment by acrymble** [comment]
I'd like to volunteer for this in the first instance.

**Comment by drjwbaker** [comment]
Thanks Adam. The Chairperson should be elected at the first meeting of the Board of Directors. Note the articles on the chair in the articles of association:

> 10.1	If the numbers of votes for and against a proposal at a meeting of directors are equal, the chair or other director chairing the meeting has a casting vote. [that is, the chair does not typically vote except to break a tie among the BoD]

> 10.2	Article 10.1 shall not apply in respect of a particular meeting (or part of a meeting) if, in accordance with the Articles, the chairman or other director is not an Eligible Director for the purposes of that meeting (or part of a meeting). [that is, if the chair has a conflict of interest, the chair does not vote]

**Comment by acrymble** [comment]
Adam Crymble has been appointed to this position by the Board of Directors of ProgHist Ltd.
