### ISSUE TITLE
Incorporated entity: Secretary

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1404]
Further to #1301, **after** we incorporate (if we choose to do so) we will need a Secretary for meetings of the Board of Directors.

**Comment by acrymble** [comment]
This person will need some basic training in minute taking.

**Comment by acrymble** [comment]
James Baker has been appointed to this position of ProgHist Ltd.
This is for ProgHist Ltd activities only. Not Editorial Board meetings.
