### ISSUE TITLE
Incorporated entity: membership

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1405]
Further to #1301, **after** we incorporate (if we choose to do so) we will need to create establish criteria for membership and classes of membership.

For example, the Editorial Board will all be members with the class of membership 'Editorial Board' the criteria for joining being to be selected by the existing Editorial Board.

We may then chose to create other classes of membership, for example by paying an annual subscriptions. Note that all members regardless of their class of membership will be eligible to vote (in person or electronically) if they choose to attend Annual General Meetings (see Article 22 for the powers of members). In short, if we create tiers of membership they will outweigh the votes of the Editorial Board.

**Comment by acrymble** [comment]
We could opt for "friends" instead of paid memberships, which wouldn't automatically come with voting rights.

**Comment by drjwbaker** [comment]
Correct. Article 19 gives us flex here:

> 19.4	The directors may establish different classes of Members and set out the different rights and obligations for each class, with such rights and obligations recorded in the Register of Members.

**Comment by drjwbaker** [comment]
Note that one way of doing this would be via Patreon https://github.com/programminghistorian/jekyll/issues/916, with a tier that brings membership. They'd get a cut but it could reduce our/my admin headache of - for example - getting to grips with how people might pay us a direct debit or standing order.

**Comment by drjwbaker** [comment]
Following https://github.com/programminghistorian/jekyll/issues/1439 we have established the membership class **‘Member (Editorial Board)’.** This is defined as follows and will be recorded by me in https://github.com/programminghistorian/jekyll/issues/1402:

> In addition to the rights and obligations defined in Articles 19-24 of the Articles of Association, the ‘Member (Editorial Board)’ membership class is the following: individual must be a member of the Programming Historian Editorial Board, the criteria for membership of which is an invitation form the Programming Historian Editorial Board; the annual cost is £0; the member will be sent a copy of each Board of Directors Meeting Minutes; per Article 20 this class of membership is non-transferable, meaning that resignation from the Programming Historian Editorial Board will result in removal from the ProgHist Ltd Register of Members.

@acrymble to invite the Editorial Board.

**Comment by drjwbaker** [comment]
Building on https://github.com/programminghistorian/jekyll/issues/1461#issuecomment-537938787 I propose we look at further membership classes **for people who are not members of the Editorial Board** (in response to concerns at https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-539398973, it is worth reiterating the the Editorial Board will not pay membership fees https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

I propose two in the first instance.

1. **Member (Supporter A)** For individuals (assumed to be humanities academics or  those in associated roles/disciplines - e.g. library staff) from non-[ODA eligible countries](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm) and with a proper job, who pay an annual/monthly subscription (£$€ to be determined). In return they get a vote at the AGM, a few stickers, and a clear sense of what their £$€ is contributing to (basically, what is at https://programminghistorian.org/en/support-us + reports from AGM setting out strategic directions + **Member (Supporter B)**).
2. **Member (Supporter B)** For individuals (assumed to be humanities academics or  those in associated roles/disciplines - e.g. library staff) from [ODA eligible countries](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm) or who can't afford to support us (PhD, precarious academic) that have the same rights/perks as above but pay £0 annual membership. We will monitor them and ask if they are able to move to **Member (Supporter A)** after each AGM.

Now, the £$€ is key here. Personally, I support a number of charities/orgs using this model at around £5 per month, and think that is a reasonable ask. But maybe I'm just weird. What I suggest for **Member (Supporter A)** is that we set a standard amount (say, £5 per month / £60 per year) and give an option to pay more if they are feeling generous (a podcast I support does this, and it seems to work well for them) with no extra benefits attached.

Thoughts?

**Comment by drjwbaker** [comment]
(note: stickers cost us ~50p each, so with postage the first month of a £5 membership would be cost us ~£5, so we'd need a minimum commitment of at least 3 months to make it worthwhile)

**Comment by amsichani** [comment]
initial comments to the proposed membership classes:
- although is totally pragmatic, the "from non-ODA eligible countries and **with a proper job**" as opposed to "from ODA eligible countries or who can't afford to support us (PhD, precarious academic)" is v problematic as regards to our inclusivity strategy. Furthermore, by saying this we somehow presume that people with precarious job positions aren't able or eligible to apply for the Supporter A status. In other words, it's not your professional or financial status which is going to define your membership class but all memberships classes should be agnostic of these values and open to anyone who wishes to join one of them. 

- I feel we need to work on what we give in return to members, esp when it comes to actual involvement at the AGM (lets also have in mind the paperwork /documentation we ll need to produce after each AGM - minutes for ‘Member (Editorial Board)’ and reports with strategic decisions for Member (Supporter A) ?). This also reminds me a bit what one usually gets from supporting charities or Gofund campaigns, that is a list of /special mention of members-supporters probably with the amount of contribution they offer etc.

**Comment by drjwbaker** [comment]
- on **Supporter A** I should have said that this wasn't my proposed final wording. I was merely trying to express a membership class that was about 'you can probably afford it' without asking people what they earn (like, say, a union does). For example, a political party that I am a member of asks members to self-define which type of membership they want but all members get the same rights: so when I was a PhD I paid the precarious person amount, then when I got a job I contacted them and said I think I should be paying more, but all the while I've been voting for leaders, deputies, et cetera.
- on what we give back, agreed, we could give more. But I wonder what this could be without compromising our editorial principles. I also - re your first point - am loath to propose that we create classes of members, where those who pay more get more control (e.g. to have a lesson on a topic of their choice, or get a guaranteed thing to be voted on at the AGM). That doesn't seem right to me.

**Comment by acrymble** [comment]
Just to be clear, we are not proposing any membership fee for Editorial Board members. That is and continues to be free. There has been some confusion.

**Comment by acrymble** [comment]
I'm really uncomfortable about offering any voting rights at this stage. There is a real risk that a competitor could effectively take over ProgHist by putting enough votes on right before the AGM to take it all a way from us.

**Comment by drjwbaker** [comment]
@acrymble Okay. That is a valid (if conspiratorial!) reason to proceed with caution. I'm happy to back this position.

**Comment by drjwbaker** [comment]
@acrymble So, is what you are proposing then to ditch membership classes and instead use the #916 tiers for managing ongoing supporters?

**Comment by acrymble** [comment]
for now, that is my suggestion. Yes.

**Comment by drjwbaker** [comment]
In which case, let's close this for now and move your Patreon suggestion to policy https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance
