### ISSUE TITLE
Managing Editor Description

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1407]
related to #1406 

Is the role of the managing editor documented anywhere? I see on the wiki that we have a page on the handover, but that just lists the pages where the managing editor exists. And the [editor guidelines](https://programminghistorian.org/en/editor-guidelines) lists the role of the managing editor as it pertains to the technical process. And the editorial team wiki describes it in the abstract. But the only real description of what this person actually _does_ was in an email from Jeri. We should add that to the wiki, unless I'm missing something, because it's changed a couple times since I've been on the board so I don't have a good sense of what a couple pieces of the job entail. 

These are the responsibilities as I see it and as adapted from Jeri's email - 

1. receive emails with lesson pitch.
2. correspond with author to clarify or get more details as necessary. Once there is enough of an idea, email the group for feedback and interest. Exchange any feedback with the author
3. make a submission ticket if it is accepted
4. if the lesson is going directly to an editor, make the necessary email introductions.
5. If the proposal is “green-lighted,” email the author with any suggested modifications from the team, send the author guidelines, and set a date of 90 days for the submitted draft. Note status on the Github issue. Serve as point person for questions during that drafting.
6. once a draft is ready for submission, connect author with editor who will offer suggestions on draft, and then guide lesson through review and publication.
7. do the final publishing as per the editorial guidelines.

Are there other things I'm missing @acrymble @JMParr or @alsalin?

**Comment by alsalin** [comment]
Somewhere between steps 5 and 6, I've done initial feedback rounds with authors (just did one today!). It's not just answering questions but actually doing the very initial review before it gets to the editor.

Also, I've been setting up the folders in the repository for my lessons since I'm the initial contact - I think that may have gotten straightened out as I went on leave with the new editorial guidelines, but it seems to make sense for the ME to do it since they are setting up the lesson to pass it on to the editor.

**Comment by acrymble** [comment]
The description of the role on the Wiki is:

Managing Editor

The managing editor is a leadership role which comes with it the ultimate authority for their respective publication. All editors report directly to the managing editor, who has the executive power to accept or reject any paper, and to intervene as they see appropriate in the peer review of any lesson under their remit.

They should be a strong voice and a spokesperson for their publication.

They are responsible for quality, and for managing expectations of editors, authors, and reviewers, as well as ensuring that all rules, policies, and relevant laws are followed by members of their team.

**Comment by acrymble** [comment]
This is now  managed by  a pending blog post re #1406
