### ISSUE TITLE
QGIS lessons upgrade?

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1408]
We are grappling in the Spanish team with the translations of the QGIS lessons. Our reviewers and translator have suggested that is necessary to introduce some "upgrades" related to some relevant changes made to the interface through versions 2.0.1 to 2.18.16. According to one of our reviewers, those changes don't make significant modifications to the lesson itself but only to software interaction. Our reviewer thinks it could be easier for readers to work with upgraded versions (v. 2.0 is from 2013!). Our other reviewer asked if an update process been planned. He states that for this specific case, the lesson is done on QGIS 2.0. However, in QGIS 3.4 (the current one) some menus change and automate some of the steps, so you might think how necessary a tutorial update process would be (whether it is convenient or not).

 This was suggested for this lesson: - [ ] 163 -  Georeferenciar con QGIS - programminghistorian/ph-submissions#163

A similar issue was raised by @jamotilla who is translating another QGIS lesson. He is working on the translation of the "Installing QGIS2.0" lesson and has found the difficulty that the current version (3.8) is very different from the 2.0 working tutorial. I translated his words here: "Although in other spaces it has been commented on the pertinence of maintaining the translation of the old versions of the programs, I believe that in this case we are facing a greater difficulty, since for example the installation instructions, some aspects of the interface, among others, are very different, so more than a "literal" translation, this lesson would need an adaptation." 
See: - [ ] 173 - Instalando QGIS 2.0 a instalando capas - programminghistorian/ph-submissions/issues/173

@jenniferisasi suggested discussing with the whole team if the original lesson itself has become obsolete, especially because version 2.0 she thinks is not in the history of the download site http://www.kyngchaos.com/category/software/ (normally we would change the link to the new place of 2.0 and already, but it is not there)

@JoshuaGOB let us know that he had no trouble finding the original files to make the lesson as it is. But from there to installing everything is another matter. Especially considering that for OS X, the top of 2.0 is 10.9. Then we would have to verify, both in Windows and OS X, which systems would be compatible and it seems to me that this is not worth it unless the original lesson is still quite popular.

So we need to discuss the pertinence of updating the lesson or keeping it with the 2.0 version given the possible version problems that this can cause with newer operating systems. Let me know your thoughts, also shall we contact the authors to discuss this further?

**Comment by mdlincoln** [comment]
From a technical standpoint, I'd strongly suggest using the 2.0 version instead of trying to do a translation on the outdated version.

However, I think it's up to the Spanish team to discuss whether this modifications are so complete that the lesson is no longer a "translation" as such. If you decided to go the route of "adaptation" then I would include a note about the translated lesson, but not mark the lesson as a direct translation with an `original:` entry in YAML, etc...

**Comment by acrymble** [comment]
I think you'll have to decide as a Spanish publication if a lesson using an old version of software serves the needs of your audience.

**Comment by acrymble** [comment]
@mariajoafana do you need further views on this or can we close it?

**Comment by mariajoafana** [comment]
Thanks for the advice, we can close this
