### ISSUE TITLE
add reviewers to contributors page

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#141]
As a way of foregrounding the work of our reviewers, who of course are essential to our success, I think it would be nice to give them a brief bio blurb (and twitter pic or similar) on the contributors page rather than provide a long (and growing) list of names. Presumably this could be handled as we do authors data and we could get in the habit of asking reviewers for a 1-2 sentence blurb.

**Comment by acrymble** [comment]
This is another old topic. I am going to suggest we drop this idea as it hasn't found a champion. I suspect this will start to look unwieldly as the list of reviewers continues to grow, but I agree that the large paragraph of names isn't perhaps the nicest format.

**Comment by acrymble** [comment]
I think this should be dealt with through #303 instead, which @fredgibbs is currently working on. Am closing this, but the spirit of keeping reviewer's contributions prominent will endure. Reopen if you need it.
