### ISSUE TITLE
Escaping Quotation Marks in Figure Captions

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1416]
Our author guidelines for figures - https://programminghistorian.org/en/author-guidelines#figures-and-images - do not mention escaping quotation marks. In other words, 

`{% include figure.html filename="special-paste-values.png" caption="Choose "Values" in the "Paste Special" menu." %}`

Will cause a jekyll build error, because it will assume the first quotation mark after Choose closes the caption. To have internal quotation marks in a parameter like this you have to escape them like so - 

`{% include figure.html filename="special-paste-values.png" caption="Choose \"Values\" in the \"Paste Special\" menu." %}`

Anyway, this is something we should address. Three times now we've had authors/editors confused because their lessons appeared to be breaking when the couldn't find any errors. In each case, the problem was with actually older lessons with issues like these that only subtly get flagged in the github web interface (they're a lot more obvious when working on the command line). We should also mention that punctuation marks _have_ to be inside the closing quotation mark.

I can take care of this - it would just entail adding two sentences or so to the author guidelines that will need to get translated.

**Comment by mdlincoln** [comment]
Thanks @walshbr - yeah, in this case, they definitely DO need to escape the quote marks. Another possibility is to use single quote marks for the `caption=''` declaration, and then they can use double quotes with impunity and without escaping inside the caption.

**Comment by walshbr** [comment]
Then we have the problem of apostrophes :) I'm good with either single or double quotes, though it does seem like we should mention escaping either way in the documentation. If you let me know what you'd prefer tech boss I can implement it @mdlincoln.

**Comment by mdlincoln** [comment]
haha, true enough. OK, to keep it consistent, let's say `caption="Use \"escaped\" quotes."`

**Comment by walshbr** [comment]
Kk - I'll PR it when I get a chance.
