### ISSUE TITLE
button to report a broken lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#142]
We're bound to have lessons break over time, but it's probably fair to say most people won't make a ticket. If we had a 1-click way of letting someone say they think a lesson is broken, it might alert us to problems more efficiently.

Obviously we'd have to experiment with how many clicks from unique useres suggested a real problem rather than some idiot causing trouble.

Thoughts? Is this difficult?

**Comment by wcaleb** [comment]
To be honest, I'm not sure I see the need. I think we want people who are reporting something is broken to create an issue, so that we know what's broken about it. Just reporting that it's broken will create more work for us because then we'll have to do the whole lesson ourselves to see what doesn't work. It might create more alerts, but wouldn't necessarily make our process any more efficient.

**Comment by fredgibbs** [comment]
i agree with caleb here. additionally, users can always send an email (i've
gotten a few that i've created tickets for) if they are confused about
creating tickets. without proper info about the bug and contact info to
follow up, a notification of a potential problem isn't that helpful.

before we implement a new system to solve a problem that maybe doesn't
exist, we might first review our directions for creating a ticket to make
sure they are as clear as possible--and really encourage people to get in
touch if they get confused, which would give us a better sense how much of
a barrier the ticket is. most tutorials are sufficiently difficult that
there's a decent chance that people spending time working through them
carefully enough to find a bug are not going to be intimidated by github
tickets.

On Fri, Oct 9, 2015 at 9:56 AM, W. Caleb McDaniel notifications@github.com
wrote:

> To be honest, I'm not sure I see the need. I think we want people who are
> reporting something is broken to create an issue, so that we know what's
> broken about it. Just reporting that it's broken will create more work for
> us because then we'll have to do the whole lesson ourselves to see what
> doesn't work. It might create more alerts, but wouldn't necessarily make
> our process any more efficient.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/142#issuecomment-146910241
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by acrymble** [comment]
I think you have both eloquently rebutted this suggestion
