### ISSUE TITLE
Dead links in 2016 blogpost and Travis build fails

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1421]
In a 2016 blogpost under the title [#ColorOurCollections: Promoting Digital Archives](https://programminghistorian.org/posts/promoting-digital-archives) there are several dead links that cause fails in the Travis builds of current pull requests (I made the experience with PRs #1390 and #1411).
There are not Internet archive links for all to replace them (here is a non-archived one: https://digital.houstonlibrary.org/cdm/singleitem/collection/curriculum-project/id/17/rec/2). What to do in this case?

**Comment by acrymble** [comment]
@mdlincoln can we remove the blog from these checks? It seems to be one of the most common sources of this type of problem because blog posts don't follow the same rigorous sustainability processes.

**Comment by mdlincoln** [comment]
No, I'd go back and remove the links from the blog post and mark them as (now gone) or something in the text.

Many of the errors on blog posts have been authors incorrectly linking even to internal blog pages or not linking to images correctly, so the link checks serve a pretty vital proofreading purpose beyond just notifying us when formerly-good links have gone bad.
