### ISSUE TITLE
Diversity Policy and UK law

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1423]
So, when we incorporate #1301 all our activities are not bound by UK law but we should assume we need to be careful to not do anything obviously contravening. As Adam mentioned in the Summer call https://github.com/programminghistorian/jekyll/issues/1362 this  is an example.

In the UK positive discrimination (quota based hiring, what in the US is known as 'affirmative action') is illegal but positive action (encouraging curtain people to apply or when two candidates are equally good picking the one that makes your organisation staffed by people who are more representative of wider society, or the communities you work with, or some other criteria) is not. See https://en.wikipedia.org/wiki/United_Kingdom_employment_equality_law#Positive_action (I know Wikipedia isn't a legal option but the gist of it is there).

So in lieu of having a lawyer on the team (maybe we should get one on the Board of Trustees... https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-497728288) I suggest we adjust the wording at https://programminghistorian.org/en/about#diversity-policy from..

> The Programming Historian team is committed to diversity, and we insist on a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or technical experience. Our commitment to diversity extends to our Editorial Board, which has adopted a diversity policy to ensure that members from any one gender or any one nationality do not comprise more than 50% + 1 of the members on the team. This is to ensure that the project continues to benefit from diverse viewpoints. This policy is under perpetual review and we welcome suggestions on it from the community.

.. to something like (changes in bold):

> The Programming Historian team is committed to diversity, and we insist on a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or technical experience. Our commitment to diversity extends to our Editorial Board, which has adopted a diversity policy **whereby we aim to ensure** that members from any one gender or any one nationality do not comprise more than 50% + 1 of the members on the team. **We achieve this in two ways: when seeking new members of the Editorial Board, by encouraging individuals from groups that are under-represented on our Editorial Board to apply; when two equally qualified candidates apply for a role on the Editorial Board, by selecting the candidate from groups that are under-represented on our Editorial Board.** This policy is designed to ensure that the project continues to benefit from diverse viewpoints. This policy is under perpetual review and we welcome suggestions on it from the community.

This shouldn't affect our business too much as a) we are moving to advertising rather than just asking people anyway, b) this is kinda what we do already anyway, and c) we've never really adhered to our own 'no more than 50% + 1' rule anyway.

**Comment by acrymble** [comment]
Thanks @drjwbaker. Can I suggest a slightly different approach to your a mendments?:

The Programming Historian team is committed to diversity, and we insist on a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age, religion, or technical experience. Our commitment to diversity extends to our Editorial Board, which has adopted a diversity policy **whereby we aim to ensure** that members from any one gender or any one nationality do not comprise more than 50% + 1 of the members on the team. **We encourage individuals from under-represented groups to apply to our Editorial Board when positions are advertised, and we commit to considering and discussing a candidate's potential to offer different perspectives to those already on the team when deciding between two equally qualified candidates.** This policy is designed to ensure that the project continues to benefit from diverse viewpoints. This policy is under perpetual review and we welcome suggestions on it from the community.

**Comment by drjwbaker** [comment]
Much more elegant than my suggestion.

**Comment by drjwbaker** [comment]
Any further comments on this? (if the Incorporation https://github.com/programminghistorian/jekyll/issues/1437 goes as planned, we'd ideally have this in place for when we begin operation on 1 October)

**Comment by drjwbaker** [comment]
So we go ahead with this then?

**Comment by amsichani** [comment]
Sounds good to me!

**Comment by drjwbaker** [comment]
Opened PR. Move discussion to there.
