### ISSUE TITLE
Guía para Traductores + Wiki

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1424]
Tal como se discutió en https://github.com/programminghistorian/jekyll/issues/1196, https://github.com/programminghistorian/jekyll/issues/1199 y https://github.com/programminghistorian/jekyll/issues/1385, la idea es tener la guía para autores y traductores en páginas separadas + un documento con orientaciones terminológicas para la traducción como Wiki. Tengo un primer borrador de lo segundo y a inicios de la próxima semana dejaré una primera versión de la traducción de la Guía para Traductores para que el resto del equipo pueda revisarla. 

Respecto a la página Wiki con las orientaciones terminológicas, me gustaría su opinión respecto de dónde dejarla. Actualmente el Wiki que está en este repositorio está descrito así: "_This wiki contains instructions about best practices for developing the backend of The Programming Historian, as well as pages concerning policies agreed by the Editorial Board, and generally of use only to the project team. These documents are currently only available in English._". Considerando que el foco de esa documentación es más de uso interno del equipo, ¿les parece si el Wiki con las sugerencias para la traducción va en el repositorio `ph-submissions`? Ese es el repositorio en el que se involucran autores, traductores y revisores.

**Comment by jenniferisasi** [comment]
Gracias por encargarte de la traducción @rivaquiroga. Lleva varias semanas en mi radar pero no logro sacar el tiempo y, bueno, lo escribí en inglés ya. Haré la revisión cuando esté lista la traducción. 

Respecto a la página de Wiki, concuerdo con que la deberíamos tener en el repositorio de `ph-submissions` para que los autores y revisores puedan acceder a ella. No le veo ninguna pega, la verdad, salvo que no veo que tengamos la pestaña para la Wiki ya preparada (será cuestión de crear una).

**Comment by arojascastro** [comment]
Sí, me parece lógica la división... but let's make sure our English and French colleagues are aware of this @acrymble @spapastamkou

**Comment by rivaquiroga** [comment]
I'll open another ticket for that. I think in the long run having that kind of guide for translating between the three languages would be helpful.

**Comment by acrymble** [comment]
Is this still in progress? Is there an action here that needs doing?

**Comment by rivaquiroga** [comment]
We can close it as it overlaps with the Copy Editing guidelines thay is being discussed as part of #1635
