### ISSUE TITLE
Open Publishing Awards?

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1425]
[Open Publishing Awards](https://openpublishingawards.org/) accepts self-nominations. The application form has four items:

* _Please describe the project in your own words._
* _Why does this project stands out to you?_
* _Please describe the value and impact of this work._
* _What role does 'open' play in making this project special?_

If you think that applying is a good idea, I can work on this next week. Deadline is on mid September.

**Comment by acrymble** [comment]
That would be amazing. Thank you so much

**Comment by rivaquiroga** [comment]
Do we have application forms from previous nominations to other awards? It would be very useful to have them, specially regarding data about the impact of the project.

**Comment by drjwbaker** [comment]
I saw that too, so thanks @rivaquiroga for taking this on. The best data in bids we've made. There is some text at https://github.com/programminghistorian/jekyll/issues/1179#issuecomment-467603354. @acrymble & @spapastamkou recently submitted something relating to West Africa but I can't find.

So I think we need a bid library. Perhaps we can create a private repo for that? I'll open a new ticket rather than clog this one up.

**Comment by arojascastro** [comment]
@jenniferisasi and i wrote something in spanish for the Asociación HDH... is it helpful?

**Comment by acrymble** [comment]
The British Academy grant I sent you has some useful phrases in it.

**Comment by drjwbaker** [comment]
@rivaquiroga: thanks for taking this on our behalf. If you want someone to take a look at the nomination text after you've drafted it, I'm happy to. Deadline is 19 September, right?

**Comment by rivaquiroga** [comment]
Thanks @drjwbaker! That would be great. Yes, deadline is on September 19. My plan is to have the first draft by this Thursday.

@arojascastro, it would be great if you can send me that document :rocket:

**Comment by arojascastro** [comment]
Done via email!

**Comment by acrymble** [comment]
This is due in 3 days @rivaquiroga. Is everything progressing?

**Comment by drjwbaker** [comment]
@rivaquiroga confirmed via email that they will submit today.

**Comment by rivaquiroga** [comment]
Ready! :crossed_fingers: 

![open_publishing_award](https://user-images.githubusercontent.com/31421616/65269478-9e563700-daef-11e9-92c3-a73ac4b48e20.png)
