### ISSUE TITLE
Private Repo

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1426]
So, we need a place to put documents we send to - say - funding councils but don't want to put on our public repo. So I think we need a private repo for things like a bid library (see https://github.com/programminghistorian/jekyll/issues/1425).

@programminghistorian/technical-team: before I open a private repo for this purpose, are there any objections? Alternatively, do you have potential uses for a private repo, in which case I'll keep the naming of it generic ('Admin')

**Comment by drjwbaker** [comment]
Note this may also be a place we keep documents associated with ProgHist Ltd, but note that per UK law copies of the records will be kept at the company's registered office address https://www.gov.uk/running-a-limited-company/company-and-accounting-records?step-by-step-nav=37e4c035-b25c-4289-b85c-c6d36d11a763 (which will probably be my office at work).

**Comment by mdlincoln** [comment]
go for it

**Comment by acrymble** [comment]
Can we try to plan a bit of a structure for it so we stay organized?  Maybe by teams +  a space for grants or research details?

**Comment by drjwbaker** [comment]
What about in the first instance:

- REPO PER TEAM
- Bids-Awards
- ProgHistLtd

Then, within each repo encourage teams to organise documents by year, and to give directory names logical names (e.g. `2019_BA-bid`).

**Comment by rivaquiroga** [comment]
Are we using the free Github plan? Private repos have a maximum number of three collaborators for personal users free accounts. Not sure how it works in the case of organizations

**Comment by drjwbaker** [comment]
> Are we using the free Github plan? Private repos have a maximum number of three collaborators for personal users free accounts. Not sure how it works in the case of organizations

Ah. Didn't realise the free private repos change came with a collaborators limit. I'll have a play and report back.

**Comment by drjwbaker** [comment]
Reporting back. We can't have a shared private repo because of the size of our team. Thanks to @rivaquiroga for flagging this. So, question now is: what are our alternatives? If requirements are:

- a secure space to put private documents
- access (read/write) by all members of the Editorial Board
- ideally free, or a small fee
- not tied to one of our employers (e.g. I could make a shared space on our institutional Box that you all had access to, but that relies on me staying with my employer).

An option, is that I (as Archivist) manage these documents in a secure off-line space (as I'll probably be doing for PROGHIST LTD anyway), then keep a list of files as a .txt file on our public PH repo so that we all know what I have and I can share documents via email as appropriate.

Another option is that we share less sensitive documents (e.g. a bid library) on a shared Google Drive directory.

**Comment by amsichani** [comment]
thanks @drjwbaker for the research and the suggestions on this. I d prefer you, as archivist , keeping all the documents in an offline space, with a publicly accessible registry of all the files, and then providing access to them upon request via email. The same goes with any physical paperwork we need to keep for the Ltd.
I can't think of a better alternative -I am open to ideas.

**Comment by drjwbaker** [comment]
In which case, I'll need to periodically make sure things like bids are passed to me to keep a version of record, should we then need it for reference later. I'm happy with that. I'll bring up at the September meet and close for now.
