### ISSUE TITLE
blogpost for call for a new member in the FR team (in French)

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1428]
I put below a text project in French for the blogpost to publish by mid-September. Please @programminghistorian/french-team integrate directly modifications/additions, if you wish. 

### Le Programming Historian en français s'élargit! Appel à candidatures pour de nouveaux membres 

Le Programming Historian publie en libre accès des tutoriels ouvertement évalués par des pairs qui permettent l'initiation à et l'apprentissage d'un large éventail d'outils numériques, de techniques et de flux de travail pour faciliter la recherche et l'enseignement en sciences humaines et sociales. Le projet repose intégralement sur le travail de volontaires. 

Récemment lancé, le Programming Historian en français cherche à agrandir et à diversifier son équipe éditoriale (cf. notre [politique de diversité](https://programminghistorian.org/fr/apropos)). Le projet compte actuellement cinq traductions de leçons publiées, d'autres sont en attente de finalisation, de relecture et/ou de suivi. Par ailleurs, notre objectif est de produire prochainement des leçons originales en français. Nous recherchons des personnes motivées, actives dans le domaine de l'histoire numérique et/ou des humanités numériques, qui peuvent consacrer du temps au projet selon [les privilèges et les responsabilités définies pour les membres de l'ensemble de l'équipe](/jekyll/wiki/Privileges-and-Responsibilities-of-Membership). Merci de noter qu'il s'agit d'un travail volontaire non rémunéré. Il s'agira de remplir [le rôle de rédacteur ou de rédactrice assurant le travail éditorial pour l'évaluation et la publication de tutoriels en français](/fr/consignes-redacteurs). Concrètement, cela signifie de :

- contribuer à achever des traductions dont l'équipe disposé déjà, seul(e) ou en collaboration avec les autres membres de l'équipe (fichiers en markdown); 
- rechercher des traducteurs et des traductrices pour prendre en charge l'adaptation de tutoriels originaux de l'anglais ou de l'espagnol au français;
- assurer le suivi d'une traduction avant publication, ce qui implique: rechercher des relecteurs / relectrices pour faire évaluer une traduction, lancer et suivre la procédure de la relecture sur Github en guidant les personnes chargées de la traduction et de la relecture, préparer la version finale du tutoriel avant publication; 
- contribuer aux activités de mise à jour du projet qui peuvent nécessiter des opérations ponctuelles de traduction sur les pages du site web et/ou du blog (via une veille des tickets ouverts par l'équipe);
- faciliter le travail de communication autour du projet, en participant par exemple à la traduction en français des postes du blog du site web (en particulier lors de la préparation des bulletins d'information);   
- participer et contribuer dans la mesure du possible aux discussions et aux activité collectives autour du projet;
- participer aux réunions mensuelles de l'équipe par Skype. 

Les membres de l'équipe éditoriale du Programming Historian peuvent en outre intégrer des équipes de tâches spécifiques selon leurs souhaits, domaines d'intérêt et compétences: équipe [technique](/jekyll/wiki/Technical-Team), de [développement du projet](/jekyll/wiki/Project-Development-Team), de [communication](/jekyll/wiki/Communication-Team), [globale](/jekyll/wiki/Global-Team).
  
Idéalement, nous souhaitons recueillir des candidatures de tout l'espace francophone. La connaissance de l'anglais est indispensable, celle de l'espagnol sera particulièrement appréciée. Le projet étant hébergé sur Github, une formation sera assurée en cas de besoin. 

Merci d'envoyer un bref CV et un texte d'environ 200 mots expliquant les raisons pour lesquelles vous souhaitez rejoindre le projet à <a href="mailto:sofia.papastamkou@gmail.com">Sofia Papastamkou</a> jusqu'au 10 octobre.

**Comment by spapastamkou** [comment]
Note on missing elements in the text: contact, deadline, CV+letter

**Comment by fdlaramee** [comment]
@spapastamkou That works for me!

**Comment by acrymble** [comment]
If you're happy, we're happy. Make sure you're clear that it isn't a paid role.

**Comment by acrymble** [comment]
I think you should post this soon @spapastamkou

**Comment by spapastamkou** [comment]
I just updated the text: 
- does no longer specify number of members to recruit;
- does not give specific details on composition of the present team;
- asks for candidatures from all francophone space;
- gives contact info and sets deadline for 10 October.  

We can make changes (for example date?) in the PR, if we need to.

**Comment by spapastamkou** [comment]
Please @programminghistorian/english-team and @programminghistorian/spanish-team, provide info on how you organised in similar cases. For example, what to do with the incoming candidatures? Forward emails to the rest of the FR team? Keep the the tdm informed @acrymble ? Other?

**Comment by acrymble** [comment]
Collect any applications, and wait until the deadline. Then organise interviews with a team including at least two other colleagues. Then propose a candidate to the full team for comment.  Then invite them, assuming no problems.

Make sure you are clear on what applicants should send (eg 1 page cv and 200 word statement)

**Comment by spapastamkou** [comment]
created PR #1447.

**Comment by spapastamkou** [comment]
thanks @acrymble.
