### ISSUE TITLE
Wednesday October 9th - Technical Team Call

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1430]
Wednesday October 9th, Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET.  @mdlincoln will be facilitating the call

- Check-in on the status of #1324 
- Add RSS links to footer/elsewhere? #1224

**Comment by mdlincoln** [comment]
Hey @programminghistorian/technical-team FYI the winning option on our doodle poll was Monday, September 30th.

**Comment by spapastamkou** [comment]
There might be an overlap with the monthly all PH meeting, where the 30th is the most popular option as well.

**Comment by mdlincoln** [comment]
Ahhh I made a foolish misreading of my Doodle polls 🙃 Here's a poll for early October: https://doodle.com/poll/9zhf88q6yiww6ca4 @programminghistorian/technical-team please fill it out!

**Comment by walshbr** [comment]
AM changed the general call to the 26th, so the 30th is still open if you wanted @mdlincoln

**Comment by mdlincoln** [comment]
Eh, at this point I wouldn't mind the extra week buffer.

**Comment by walshbr** [comment]
Cool! Already deleting it from my calendar.

**Comment by ZoeLeBlanc** [comment]
Hey everyone! unfortunately I can't do any of the times on the doodle poll. I could do October 4th if that could be added, but otherwise I need to request a different week in October. Alternatively I could do the search stuff in the November technical call. Let me know what is easiest and thanks for organizing Matt!

**Comment by mdlincoln** [comment]
@ZoeLeBlanc I'm afraid it's the opposite for me, I won't be able to make the week after! Let's have you present in November then? And those able to make the October call, we can look at some small technical things like #1224

Let's schedule (for real this time! 😳) Wednesday October 9th.

**Comment by spapastamkou** [comment]
I am afraid I'll miss the October meeting: I will be at another one in Paris.

**Comment by mdlincoln** [comment]
Hey @programminghistorian/technical-team, I'm sorry to say that I've had to schedule a pretty urgent doctor's appointment tomorrow morning, and it could probably end up intersecting with our scheduled call...

Would you all like to meet anyway in my absence and take a look at the two tickets mentioned here? Or reschedule for another time?

**Comment by jenniferisasi** [comment]
Oh no, I hope everything goes well @mdlincoln. 

I think only @walshbr and I are left? I am more than happy to meet to try to add the RSS in the footer but also to take that time to complete all the alt-images in the ES side of the house as I am afraid no one else is going to do more.

**Comment by walshbr** [comment]
If you wanted @jenniferisasi i can do the same. The two of us can just take the time to work through tech tickets and be on slack if anything comes up.

**Comment by jenniferisasi** [comment]
> If you wanted @jenniferisasi i can do the same. The two of us can just take the time to work through tech tickets and be on slack if anything comes up.

Let's do that.

**Comment by amsichani** [comment]
cou cou! I 'm here too!  I ll help working on a couple of tech tickets. I ll be slacking too. see you shortly! hope everything goes smoothly @mdlincoln !

**Comment by mdlincoln** [comment]
Thanks so much everyone. I'll try to check in later today to see how things are going.

**Comment by amsichani** [comment]
@mdlincoln should we close this ticket and schedule our next @programminghistorian/technical-team meeting ?
