### ISSUE TITLE
Lesson requests FR page

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1431]
During #1358 meeting of August 30 we worked on the lesson requests EN and ES pages. This is a good occasion to start planning the creation of the FR page, so I open this ticket to start the discussion about setting a timeline for its publication and deciding on the type of original lessons the @programminghistorian/french-team wishes to call for.  

EN and ES pages can be found here: 
https://programminghistorian.org/en/lesson-requests 
https://programminghistorian.org/es/solicitud-lecciones

**Comment by spapastamkou** [comment]
Some first ideas for a time schedule: 
- decide on the content and create the page by the beginning of October could be a reasonable target, what do you think @programminghistorian/french-team ?
- at a later stage, we could propose a writing workshop for May 2020 during the first francophone DH conference that will take place in Bordeaux (the CFP should come out shortly). 
Thoughts and ideas are welcome!

**Comment by fdlaramee** [comment]
@spapastamkou Sounds good. The Bordeaux workshop would look something like the one the @programminghistorian/spanish-team did in Colombia (I think) a while ago?

**Comment by spapastamkou** [comment]
@fdlaramee we could be inspired from this workshop, but we also have to organize something rather costless:-)

**Comment by spapastamkou** [comment]
I just copy below the list of lessons from the Lesson Requests page of the PH EN so that there is a basis to make a selection, additions etc. 

- [ ] How do you conduct spatial clustering of geographic data?
- [ ] When do you know your network analysis is meaningful?
- [ ] How to Publish Digital Scholarly Editions using a Native XML Database
- [ ] How to Analyse Audio Artefacts
- [ ] How to Choose a Metadata Schema
- [ ] How to Apply Multidimensional Scaling
- [ ] How to establish a podcast (edit, host, distribute, and build an audience) 

I add (to discuss):   
- [ ] Text analysis (I am thinking of textometry and lexicometry here]
- [ ] Use of ontologies for historical data

**Comment by spapastamkou** [comment]
Je viens d'ajouter comme sujet possible de leçon l'utilisation d'ontologies pour des données historiques. Je commencerai à travailler doucement sur une version de la page et nous pouvons discuter si besoin sur ce qu'on retient ou pas, lorsque nous aurons une version de travail.

**Comment by spapastamkou** [comment]
La discussion sur la forme finale de cette page peut maintenant se faire dans le cadre du pull request #1551.
