### ISSUE TITLE
Meeting Report Template

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1432]
As we move towards a "team based" reporting style for our group meetings, I thought it might be helpful to have a simple template that could be used by team leaders to disseminate reports before each meeting. I have drafted a template for comment. Does this meet the needs of our team leaders?

---

# General Meeting Report Template

Team Name  (delete as appropriate): Editorial, Technical, Project Development, Communication, Global

By:
Date:

---

Actions Completed Since Previous Report:

Actions Remaining Open Since Previous Report:

---

Queries for the Team:

---

6-month focus:

12+ month focus:

Further Comments:

**Comment by drjwbaker** [comment]
Just so we keep are nomenclature tight, I think this should read "Queries for the Editorial Board" because our all team monthly meetings are technically Editorial Board meetings.

**Comment by drjwbaker** [comment]
Oh, and whoever is responsible for our monthly meetings (@walshbr or @amsichani?) can you please @ in the meeting issue those who need to complete this report advance of each meeting.

**Comment by walshbr** [comment]
Seems like that will just be the same five people every time, but sure. We can just tag that list.

**Comment by drjwbaker** [comment]
Ta. I like a targeted @ notification :)

**Comment by acrymble** [comment]
I will add this to the wiki. Thanks for the feedback

**Comment by acrymble** [comment]
Added: https://github.com/programminghistorian/jekyll/wiki/Meeting-Report-Template
