### ISSUE TITLE
Annual General Meeting month

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1438]
Now we have incorporated https://github.com/programminghistorian/jekyll/issues/1437 we need an AGM at which Members (for now, the Editorial Board) vote on matters brought by them and/or the Board of Directors.

Action for now is for Board of Directors to agree a month for this, which we will use for subsequent AGMs.

**Comment by acrymble** [comment]
Is there a mental advantage to  doing it in January so that the "year" maps onto the calendar year?  I don't have a strong preference, but thought I'd raise the idea.

**Comment by drjwbaker** [comment]
Perhaps. I was thinking making this mid-way through our operating year (we start in October) might make sense as well.

**Comment by acrymble** [comment]
Let's go with May then. That's after teaching for most people too, so it's doable.

**Comment by drjwbaker** [comment]
Okay. We still have to formally agree this at https://github.com/programminghistorian/jekyll/issues/1439 and document our decision.

**Comment by acrymble** [comment]
We've set the date of the AGM of ProgHist Ltd as 28 May 2020 at 3pm London time (Skype).
