### ISSUE TITLE
Board of Directors Meeting 10/19

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1439]
@acrymble @amsichani: now we have incorporated https://github.com/programminghistorian/jekyll/issues/1437 we need to arrange a Board of Directors meeting for shortly after we begin operating (1 Oct 2019).

This can be remote. I suggest anytime 2-4 October.

Initial business is:

- Nominate a Chair of the Board of Directors (proposal: @acrymble)  https://github.com/programminghistorian/jekyll/issues/1403
- Elect further Directors to a maximum of 7 (proposal per https://github.com/programminghistorian/jekyll/issues/1301: add the EN/ES/FR Managing Directors). Details of the these Directors will need to be submitted to Companies House.
- Nominate a Company Secretary to record votes/resolutions at Board of Directors Meetings and manage Company documentation (proposal: me). See [gov.uk](https://www.gov.uk/running-a-limited-company/company-and-accounting-records?step-by-step-nav=37e4c035-b25c-4289-b85c-c6d36d11a763) for what we need to keep https://github.com/programminghistorian/jekyll/issues/1404
- Decide a month for the Annual General Meeting (proposal: May) https://github.com/programminghistorian/jekyll/issues/1438 
- Confirm initial terms of membership (proposal: restricted to Editorial Board) and list of members (proposal: all on the Editorial Board) https://github.com/programminghistorian/jekyll/issues/1405
- Registering for VAT in the UK (proposal: we don't need to, see email from gov.uk 09:57 6 Sept 2019)

**Comment by acrymble** [comment]
Can we get this in the diary? I can do anytime on the 3rd of October.  @amsichani ?

**Comment by drjwbaker** [comment]
I'll block 3 Oct until we fix a time.

**Comment by acrymble** [comment]
3pm? Our normal meeting time?

**Comment by arojascastro** [comment]
Is it really really really necessary to call these people "directors"... I may have missed something - I haven't paid attention lately to tickets and I have not attended some of our latest skype meetings- but suddenly I feel like we are not longer a flat structure.

**Comment by acrymble** [comment]
It's a legal term for those who are legally responsible for a company, so we can't change the name.

I believe we remain quite flat. Everyone was invited to put themselves forward to whatever roles they wanted, and people were given the option of taking on more or less responsibility, depending on their circumstances. What we don't have any more, is all the same title, regardless of activity. But I think that helps us better explain and reflect our contributions to the project.

**Comment by arojascastro** [comment]
Fingers crossed!

**Comment by drjwbaker** [comment]
@arojascastro Sorry this surprised you. To add to @acrymble's point, the Board of Directors is only for ProgHist Ltd https://beta.companieshouse.gov.uk/company/12192946, and we've structured the Articles of Association https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-513861381 in such a way that:

a) the Board of Directors only really have oversight over the financial and legal side of what the Programming Historian does
b) Members of ProgHist Ltd (that is in the first instance, the Editorial Board) outvote the Board of Directors (because there are more of them!) in the Annual General Meeting https://github.com/programminghistorian/jekyll/issues/1438

I hope that helps clarify matters.

**Comment by drjwbaker** [comment]
Going back through our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for this meeting today:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))
- we don't have to have a secretary (Article 17)

**Comment by acrymble** [comment]
The minutes of this meeting have been distributed to the Editorial Board on 4 October 2019
