### ISSUE TITLE
deprecated lessons not clear that they're so

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#144]
@fredgibbs and I just got an email about a problem with a deprecated lesson. Other than the URL there's nothing there to suggest that it's now deprecated. I don't think we should REMOVE these lessons in case someone has a syllabus that relies upon it. But maybe we need to think about a flag that makes it obvious to people that we won't be updating them any longer? If indeed that will be our policy.

**Comment by ianmilligan1** [comment]
I agree - maybe a separate section of the _Programming Historian_ for archived lessons? And perhaps a persistent banner along the top, noting that the lesson is depreciated and may not work on your system.

**Comment by fredgibbs** [comment]
i concur. although it seems like in this case the emailer was simply web
trolling for a particular link to offer a competing resource to any webpage
that had it. i don't think many of our deprecated URLs are really used
anymore (they obviously didn't have deprecated in the URL to begin with).
but in case anyone stumbles on one (btw, are these in our robots.txt
file?), we should be clearer they are likely to be broken in many ways.

On Sat, Oct 17, 2015 at 8:17 PM, Ian Milligan notifications@github.com
wrote:

> I agree - maybe a separate section of the _Programming Historian_ for
> archived lessons? And perhaps a persistent banner along the top, noting
> that the lesson is depreciated and may not work on your system.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/144#issuecomment-148970767
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs

**Comment by wcaleb** [comment]
I added a banner. Looking more closely at the lessons in the `deprecated` folder, all but [one of them](http://programminghistorian.org/lessons/deprecated/getting-started) is basically just a stub, and I can't imagine anyone still linking to the one that isn't. Perhaps we should just consider deleting them all. @fredgibbs I'm not sure there's a way to have a GitHub Pages `robots.txt` file. We don't currently have one, as far as I know.

**Comment by acrymble** [comment]
The Getting Started one is decent, so I wouldn't like to see it deleted. It
just doesn't fit the way we have our lessons going these days. But if the
others aren't anything, then I suppose you're right.

On Mon, Oct 19, 2015 at 4:25 PM, W. Caleb McDaniel <notifications@github.com
