### ISSUE TITLE
Bank account for ProgHist Ltd

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1440]
Now we've incorporated https://github.com/programminghistorian/jekyll/issues/1437, note that I've started looking into this. Ideally, we need it open for once ProgHist Ltd starts operating (1 October 2019).

**Comment by drjwbaker** [comment]
@acrymble @amsichani Note that I have you both in mind as co-signatories to the bank account. The company bookkeeper (I have someone in mind) will also be a signatory. I'll keep you updated via email.

**Comment by drjwbaker** [comment]
An application is in. I'll update when I know more.

**Comment by drjwbaker** [comment]
We now have a bank account. @acrymble @amsichani: have either of you received an email with login details to internet banking? I haven't, but I think they will attach it to my existing banking login.

**Comment by drjwbaker** [comment]
nb: our shared gmail is the place where we get notification from the bank. I'll monitor this.

**Comment by acrymble** [comment]
Not yet.

**Comment by drjwbaker** [comment]
Okay. If/when you do, please let me know so I can chase if needed.

**Comment by amsichani** [comment]
not yet .

**Comment by acrymble** [comment]
I believe these have now arrived.
