### ISSUE TITLE
Communication on behalf of ProgHist Ltd

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1441]
Directors of ProgHist Ltd https://github.com/programminghistorian/jekyll/issues/1437 should ensure that when communicating in the capacity of a Director they include the Incorporated Name and Company Number (see [gov.uk](https://www.gov.uk/running-a-limited-company/signs-stationery-and-promotional-material)).

I suggest we put the following text in our email signature:

> Director, ProgHist Ltd. ProgHist Ltd is a Not for Profit Company Limited by Guarantee, Registered in England, Company Number 12192946 https://programminghistorian.org/

**Comment by acrymble** [comment]
Confirming I have done this.

**Comment by acrymble** [comment]
I've added this instruction to the Wiki.  https://github.com/programminghistorian/jekyll/wiki/Board-of-Directors-Responsibilities
