### ISSUE TITLE
Explainers re relationship between the Programming Historian and ProgHist Ltd

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1442]
We need some text on the site (translated @programminghistorian/spanish-team @programminghistorian/french-team) that describe the relationship between the Programming Historian and ProgHist Ltd. @arojascastro suggested https://github.com/programminghistorian/jekyll/issues/1301#issuecomment-513144094:

> The Programming Historian is an international volunteer-driven project whose financial activities are administered by [ProgHist Limited](https://beta.companieshouse.gov.uk/company/12192946), a Not for Profit Company Limited by Guarantee that is registered in England, Company Number 12192946

I think this should go in the site footer, though I appreciate - pinging @programminghistorian/technical-team - that there is already quite a bit in there. Advice?

We also need role labels for Directors on the project team pages https://programminghistorian.org/en/project-team. I suggest 'ProgHist Ltd Director' as a role label. @acrymble, as TDM, does this work for you?

**Comment by acrymble** [comment]
I'd suggest we don't add labels for Director. The directorship may be different from the Project Team. It's possible that in future the company will own activities that do not include the projects we currently advertise on that site. I think it should be kept separate. The list of roles is also already quite long and complex.

**Comment by drjwbaker** [comment]
Okay. I guess my suggested link in the footer blurb will direct readers to the Directors anyway.

Any thoughts on the text and @programminghistorian/technical-team how we might best implement?

**Comment by walshbr** [comment]
If it's going to live in the footer, I'd add it as new text to this line "The Programming Historian (ISSN: 2397-2068) is released under a CC-BY license."

**Comment by drjwbaker** [comment]
@walshbr Okay. Where can I find the EN footer text? (can't find it in the build.....)

**Comment by drjwbaker** [comment]
@walshbr Ignore me. Found it https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/snippets.yml

**Comment by walshbr** [comment]
Ha I was just looking at it. When you have the language that you want ping me on the PR - the way that we have it set up looks like it might want a little bit of refactoring since that category is called "license" but we'd be putting more than just the license in there.

**Comment by drjwbaker** [comment]
Closing to move discussion/refinement to PR https://github.com/programminghistorian/jekyll/pull/1444
