### ISSUE TITLE
Ombudsperson (Spanish)

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1443]
With María José on Sabbatical, we need someone to take the Ombudsperson role in the Spanish team. @programminghistorian/spanish-team, anyone interested?

**Comment by jenniferisasi** [comment]
I cannot take on another role for the time being, sorry.

**Comment by acrymble** [comment]
I would suggest getting someone to do this who is not an editor. Their job is to be objective and neutral. I don't know that an author would trust an editor to be neutral in a dispute with another editor.

**Comment by arojascastro** [comment]
I could take it... we have never had any problem to the date and thus it does not mean actual work. But if we do not accept an editor, then we need to find someone else... but who?

**Comment by rivaquiroga** [comment]
That's a good point, @acrymble. As everyone in the Spanish Team is currently an editor, we need someone to join the team in that role (unless someone in the team doesn't want to be an editor anymore; which I think is not the case). 
I have a possible candidate. Should we discuss that here or through email?

**Comment by acrymble** [comment]
Email

**Comment by spapastamkou** [comment]
if all teams should go along similar lines, perhaps I can ask whether Marie is interested continue to assume the role?

**Comment by amsichani** [comment]
@spapastamkou could you please open a ticket for Ombudsperson (French) and inform it accordingly? Its important to have this role in place for all of our publications.

**Comment by spapastamkou** [comment]
There is already @fdlaramee who fills the role. Should we look for someone outside the team?

**Comment by amsichani** [comment]
I also thought that it is better to be someone outside the editorial board. We can raise this at the next meeting.

**Comment by acrymble** [comment]
@rivaquiroga I think this needs a new plan, yes?

**Comment by rivaquiroga** [comment]
Yes! We now need to find someone outside the team.

**Comment by acrymble** [comment]
would you like to approach people, or invite outside people to express interest?

**Comment by acrymble** [comment]
@rivaquiroga this seems stuck.

**Comment by jenniferisasi** [comment]
@acrymble, quick note to say that we are discussing it via email.

**Comment by rivaquiroga** [comment]
@acrymble, Silvia Gutiérrez will be the ombudsperson of the Spanish team. I'll close this ticket once I've add her to the project team page.

**Comment by acrymble** [comment]
@rivaquiroga can we finish this off?

**Comment by rivaquiroga** [comment]
I'll upload during this weekend the info + picture she sent me this week

**Comment by acrymble** [comment]
This was merged. So closing. Thanks @rivaquiroga
