### ISSUE TITLE
Issue creation w web form

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#145]
https://github.com/benbalter/problem_child

Pointed out by @drjwbaker . Useful to lower barrier to entry for comments?

**Comment by wcaleb** [comment]
I can look into it, though I don't have any experience with Ruby. It seems like the problem with this solution would be that we would have to run the web form on a separate website that one of us (or one of our institutions) would have to provide and maintain. For the time being, it looks like @fredgibbs has revised the "email us" option for reporting issues in 7944c4e03c1827cbc7f46649c27b71945e1d70fb.

**Comment by fredgibbs** [comment]
even if we could get it working quickly (which seems unlikely anyway), it
seems like a non-trivial maintenance issue over time. but if we start to
hear that the normal github issue creation process is too difficult for
users, we should look into this solution more--it does seem to make it
super easy for users.

On Sun, Oct 18, 2015 at 10:59 PM, W. Caleb McDaniel <
notifications@github.com> wrote:

> I can look into it, though I don't have any experience with Ruby. It seems
> like the problem with this solution would be that we would have to run the
> web form on a separate website that one of us (or one of our institutions)
> would have to provide and maintain. For the time being, it looks like
> @fredgibbs https://github.com/fredgibbs has revised the "email us"
> option for reporting issues in 7944c4e
> https://github.com/programminghistorian/jekyll/commit/7944c4e03c1827cbc7f46649c27b71945e1d70fb
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/145#issuecomment-149098803
> .

## 

frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
http://www.twitter.com/fredgibbs
