### ISSUE TITLE
PubSweet as publishing platform?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1451]
Just noticed that the team behind the Open Publishing Awards produce a platform designed for online publishing. We've made github work, but it's not the most user friendly. Does anyone know anything about their PubSweet platform? http://pubsweet.coko.foundation/

**Comment by walshbr** [comment]
Looking at the technical documentation, migration questions aside (and that would be a lot of work), my sense is that this is far more technically complex and would require dramatically more of the technical team than Jekyll/GitHub does.

**Comment by mdlincoln** [comment]
Yes, I agree with @walshbr's assessment. A switchover to this would be a massive and unjustifiable increase in complexity.

There are some options for layering a CMS over a jekyll site such as https://www.netlifycms.org/, however I don't see that it's really the need to format YAML that is causing workflow issues, but instead the challenges around coordinating the reviewing of each other's work, which will exist on any platform.
