### ISSUE TITLE
Communication: Blogpost/Newsletter for September

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1456]
Issue created to post the second newsletter to be published at the end of the month. So far, I have these accomplishments on my notes: 

- new member in the French team (@spapastamkou no formal blogpost yet, do you want to wait or can I mention it here briefly?)
- French team looking for new editorial members
- PH at DH and ACH in the summer (@mdlincoln can you please send me the pic you take at ACH? thanks!) 
- PH in Spanish received the HDH Premio 2018 in July 
- new publications: 3 translations into French
- ProgHist Ltd (@drjwbaker we haven't announced this yet, so should I mention it or wait till all is in place and we write a formal blogpost?)

Upcoming events: 
- HDH in Toledo in October 
- ??

Questions for the team: 
- Do we want to announce the lessons that are under review as "lessons in the making" or similar? On the one hand, journals don't issue an announcement of the articles they are going to publish; on the other hand, since we don't have fixed publishing dates , I thought it would be a nice way of saying, hey we are working on new lessons.   
- Do we add a note of people leaving the project?  

Please, let me know if I'm forgetting something and, specially, if there is something coming up that I am not aware about.

**Comment by drjwbaker** [comment]
On https://github.com/programminghistorian/jekyll/issues/1437, ProgHist Ltd is operational from 1 October, so I'm happy for it to go up this month, and use the next newsletter to talk more about the specific purposes of the company. It can be a short note, so something like:

> Last year [we announced](https://programminghistorian.org/en/support-us) our intention to seek financial support for the _Programming Historian_ in order to grow, improve, and sustain our work. We are therefore delighted to announce that from 1 October 2019 ProgHist Ltd will be operational, a Not for Profit Company Limited by Guarantee (registered in England, Company Number [12192946](https://beta.companieshouse.gov.uk/company/12192946)), the purpose of which is to administer our financial activities. We believe that having a legal and financial footing will enable us to:

>> - Maintain our infrastructure.
>> - Bring in professional services that enhance the quality of our publications.
>> - Improve our community outreach and internationalisation.
>> - Protect The Programming Historian from changes to service agreements of those ‘free’ services upon which we rely.

> In the coming months, we will to announce the mechanisms by which the community can financially support our work.

**Comment by drjwbaker** [comment]
On people leaving the project, yes I believe we should use the newsletter to thanks people for their contributions.

**Comment by spapastamkou** [comment]
@jenniferisasi Please, do mention that there is a new member in the team. In addition, there is a first draft for a blogpost that is ready. Some updates are on the way but it can be published this week (around Wednesday), and so you can have a link for the newsletter. 

Otherwise, yes, it would be nice to have a thought for people who leave the project, thank them for their contribution and wish them luck. Let me know if I can help further. 

And of course we can continue to advertise that the FR team is looking for new members. 
Thanks!

**Comment by spapastamkou** [comment]
Just merged the PR #1468 so there will be a blog post for Martin, if you need a link @jenniferisasi

**Comment by jenniferisasi** [comment]
Perfect @spapastamkou! That is exactly what I needed :) 

@drjwbaker since my intention is to publish the newsletter around that time, or a few days later, this will work. Thanks for your help with that!

**Comment by mdlincoln** [comment]
![IMG_20190725_104736](https://user-images.githubusercontent.com/4392604/65819199-b745a300-e1e7-11e9-80cb-c579ef61d91c.jpg)


![IMG_20190725_105010](https://user-images.githubusercontent.com/4392604/65819207-bb71c080-e1e7-11e9-80a1-17ffe088f1d5.jpg)
