### ISSUE TITLE
Donation mechanisms

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1457]
Now that we are on our way to having a bank account https://github.com/programminghistorian/jekyll/issues/1440 I want to revive the discussion of mechanisms for donation. I'm minded as follows:

- We should keep it simple in the first instance. **Proposal: accept Paypal https://github.com/programminghistorian/jekyll/issues/917, cheque, bank transfer, and cash**. Anything I'm missing?
	- On Paypal pinging @programminghistorian/technical-team: does our infrastructure support putting badges for this somewhere visible (but not in a begging way!) if we choose to do so?
- We should look into Patreon again https://github.com/programminghistorian/jekyll/issues/916 as a way for getting regular donations, because if we can get a regular stream of dependable small contributions that will help financial planning.
- We should revive the discussion of recognition https://github.com/programminghistorian/jekyll/issues/918 because we probably don't want to clutter our '[Supporters](https://programminghistorian.org/en/support-us#supporters)' section with the name of every person who has ever given us money, but we should put that information somewhere visible. **Proposal: page on the GitHub repo with this info**
- We should consider if we want a membership stream https://github.com/programminghistorian/jekyll/issues/1405

I'd be grateful for thoughts and input on this.

**Comment by acrymble** [comment]
We've got to have a plan for this. If you ask for a one-off donation, that person isn't going to then sign up for a monthly giving plan. We've also got to have messaging that will appeal to potential donors, brand guidelines for keeping that messaging consistent, and an idea of how much we need to achieve our goals (which are not yet decided). So  all to  say  I think we need address a 2-5-10  year plan #1461 ASAP so we can start building this messaging and strategy.

**Comment by drjwbaker** [comment]
A good chunk of the messaging on what we want money for is at https://programminghistorian.org/en/support-us I'd love to be able to say what we need, but we don't know yet. So based on what we say we want money for, some sums:

1) "Maintain our infrastructure" can be interpreted as a social thing, so let's take it to be a hire to run the project. Ideally for a full-time skilled person, £50,000 per year. But realistically, doing this now would be super hard without a dedicated grant/sponsor for the post (like the [IMLS Laura Bush fund supported Library Carpentry](https://www.imls.gov/grants/awarded/re-85-17-0121-17))
2) Copyediting. Last year we published 10 new lessons. So a baseline is £2,000 per year (based on https://github.com/programminghistorian/jekyll/issues/1381).
3) Outreach. Basic: £250 for marketing materials (stickers). Advanced: £5,000 per year to run an annual workshop in an [ODA Country](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm).
4) Project us again changes to free services. If we wanted Pro GitHub, $2,000 per year.

So we can aim for £10k in the first year if you want?

On mechanisms..

> If you ask for a one-off donation, that person isn't going to then sign up for a monthly giving plan.

.. I agree, though this is another case of baby steps vs big bang. I think we need to learn how to quietly accept and process small amounts as a means of learning how to set up an infrastructure for getting regular donations (like membership, or supporters programme, or whatever).

**Comment by acrymble** [comment]
We've got £24,000 in grants in preparation or submission at the moment, so I think £10,000 is too low. I'd say £250,000 of which very little is likely to be donations. I also think vision needs to come first. We can continue to do what we do for £10,000 per year. But we have more potential than that.

**Comment by drjwbaker** [comment]
And none of those grants are coming to the company. I'm all for ambition. But I'm also not confident we have the expertise to manage a £250k business so soon.

**Comment by drjwbaker** [comment]
For context, for example, once we get above £85k turnover we hit a VAT threshold that'll require administration and expertise. Both of which cost money.

**Comment by drjwbaker** [comment]
@acrymble Further to your recent work on business models and sustainable revenue streams, let's keep this ticket for setting up the practical mechanisms for payment (putting our bank details on the site, setting up Paypal, et cetera) and - when it comes to it - open a separate ticket for everything else.

**Comment by acrymble** [comment]
Let's remember #1313 Github Sponsors is still offering match funding for donations up to $5000 in the first year.

**Comment by drjwbaker** [comment]
This? https://github.com/sponsors Shall we join the waiting list?

**Comment by acrymble** [comment]
I don't see a downside. It doesn't have to be the only tool we use.

**Comment by acrymble** [comment]
Overview of GoFundMe Platform
- Fee of 2.9% plus £0.25 per donation
- possible to work as a team with other colleagues who sign up for free accounts. Gives dashboard to make life easier.
- money is managed by Paypal
- Cannot fundraise on behalf of a limited company. Only charities or individuals, so would have to fundraise as one of us...bit awkward for messaging, but could be overcome.
- Was easy to set up a test page.
- set up for a single campaign. Not ongoing giving.

**Comment by acrymble** [comment]
Overview of Patreon Platform #916 Patreon discussion
- aimed at creatives, and good for reaching growth objectives
- set up for long-term giving and monthly donation
- expectation of rewards for giving (tiered rewards)
- definitely 'cooler' than gofundme
- Launch with special offers to draw people in
- fees 2.9% plus 30 cents per successful pledge for pledges over $3, and 5% plus 10 cents per successful pledge for pledges of $3 or less. PayPal payments from non-US patrons have an additional 1% fee. in addition they charge a platform fee (5-12% depending on service package you choose).

**Comment by acrymble** [comment]
Based on what I've just seen, I suggest we reopen #916 and go with Patreon. I suggest we agree on messaging in another discussion. @drjwbaker do you want me to look over what you've got on Patreon or otherwise help with this?

**Comment by drjwbaker** [comment]
>     * Cannot fundraise on behalf of a limited company. Only charities or individuals, so would have to fundraise as one of us...bit awkward for messaging, but could be overcome.

Bit worried by the legalities of that should the money be subsequently donated to PH Ltd.

**Comment by drjwbaker** [comment]
@acrymble Sorry for the delay. Other things to deal with. Do go ahead with Patroen. Login details at https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#patreon I've made a fair start to the profile page, but nothing on banking integration.

**Comment by drjwbaker** [comment]
Reopening the Paypal ticket to support this https://github.com/programminghistorian/jekyll/issues/917

**Comment by drjwbaker** [comment]
@acrymble Can we close this and open a specific ticket on implementation of our opening donations drive? (that is, agreeing Patreon tiers and how to display the drive on the site)

**Comment by acrymble** [comment]
Of course. And I didn't mean to shut down paypal. I just wasnt clear what you were thinking for it.  You're right, patreon doesn't have a one-off donation option.

**Comment by drjwbaker** [comment]
Okay. So we agree that Paypal should be our default one-off option and more onto implementation on the site.

**Comment by drjwbaker** [comment]
(opening a new ticket on this now)
