### ISSUE TITLE
Pandoc sample file causes errors

### ISSUE THREAD

**Issue by ersanchez** [programminghistorian/jekyll#146]
## Brief Description

The sample markdown file in the Markdown & Pandoc tutorial causes errors when following the bibliography example code.
## Details

I used the sample [main.md](https://raw.githubusercontent.com/dhcolumbia/pandoc-workflow/master/sample.md) file to use in practicing commands. I copied the text of the example file into a file that I used on my computer.

The fenced codeblock backticks (```) in the example file caused errors for me. Specifically, when invoking the following command:

`$ pandoc -S -o main.docx --filter pandoc-citeproc main.md`

I received the following error:

`pandoc-citeproc: reference`_`author_title_date`_`not found`

Removing the backticks from the sample file allowed this command to run without errors.
## Recommended Fix

Remove the fenced codeblock backticks from the example file. 

I suspect that the fenced codeblock backtics are preventing pandoc-citeproc from reading the metadata  section.

**Comment by wcaleb** [comment]
You're right. This looks to be an error in the file hosted in a different repository. I've proposed a [pull request](https://github.com/dhcolumbia/pandoc-workflow/pull/4) to fix it. But I also wonder if we should just host the example file in our own assets directory. @denten would you be okay with that?

**Comment by denten** [comment]
Sounds good.
