### ISSUE TITLE
2-5-10 year plan

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1461]
I think it's time we start building a longer-term strategy to help us reach our project's potential.

I'm going to suggest a "2-5-10" model, whereby we set a vision for 2 years which include changes, to help us achieve our 5 year vision that includes activities that will help us reach a 10 year purpose.

Before going into any more detail, I open this for discussion.

**Comment by acrymble** [comment]
I've found a couple of business plan templates for charities or not-for-profits that might be helpful starting points. Please comment on this idea so I know if we're on the right track.

[business-plan-template-non-profits-charities-and-volunteer-organizations.docx](https://github.com/programminghistorian/jekyll/files/3672726/business-plan-template-non-profits-charities-and-volunteer-organizations.docx)
[business-plan-template-proforma.docx](https://github.com/programminghistorian/jekyll/files/3672729/business-plan-template-proforma.docx)

**Comment by acrymble** [comment]
Rather than wait for lazy concensus, I'd like to put together a group who will work collaboratively to draft a business plan proposal to put to the team for comment. This will involve collaborative writing on Google Drive, and possibly a few Skype calls.

The timeline will be from now until Christmas 2019. If you are a member of the team and would like to be involved, please make yourself known on this thread.

**Comment by drjwbaker** [comment]
I'd love to but I don't have any time to give right now.

**Comment by acrymble** [comment]
Just a note to say that this is voluntary. There will be a consultation opportunity for everyone once we have a draft. I have some time now I can devote to this, which is why I'm moving forward and taking advantage of that time. I recognize not everyone is in the same  position.

**Comment by amsichani** [comment]
I 'd love to be involved ; I don't have enough time at the moment so I can't promise massive amount of commitment on this, but I am happy to contribute on (one or more)' business plans'.

**Comment by jenniferisasi** [comment]
Same here, I would like to help but I have enough on my plate from now to the winter holidays as to commit to writing a long document. I will happily review it once it is written, though. 

I have one question about this, @acrymble is this plan going to be overarching for PH in a way that there is "no need" from individual language-team to write in here their vision for 2-5-10?

**Comment by acrymble** [comment]
This is going to require a lot of steps. So I'm going to start adding material here to this thread to keep track. Starting with a list of ideas for income streams for ProgHist Ltd, for future comment.

[Possible income and business models.docx](https://github.com/programminghistorian/jekyll/files/3686156/Possible.income.and.business.models.docx)

**Comment by mdlincoln** [comment]
Is this going anywhere @acrymble ?

**Comment by acrymble** [comment]
Yes. We had a discussion about business models we're happy with. I'm using that feedback to build a business plan for further comment.

**Comment by acrymble** [comment]
I have sent a draft of the business plan to team leaders and managing editors for feedback, with a deadline of 30 November 2019. The whole team will have a future opportunity to comment once I've incorporated these ideas.

**Comment by acrymble** [comment]
@drjwbaker @mdlincoln @jenniferisasi @svmelton @rivaquiroga @spapastamkou @JMParr just a reminder that I've sent you this business plan for comment.

**Comment by acrymble** [comment]
Based upon the feedback I've received, I'm revising this and will sent it to the team for comment.

**Comment by acrymble** [comment]
I'm working with @jenniferisasi on a section about communication strategy.

**Comment by acrymble** [comment]
This business plan has been sent to all team members for comment.

I'd like to add it to the January Project Team meeting.

**Comment by acrymble** [comment]
This plan has been submitted to @drjwbaker to archive. Everyone on the team was sent a draft the other day. We're committed to revising this (within the Team Development team) once a quarter. So this is a living document rather than one set in stone.
