### ISSUE TITLE
problem with creating a new branch on jekyll

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1465]
Hey, I just tried to create a new branch for publishing a blogpost and I do not seem to have sufficient rights to do this. I can only switch between existing branches. I have this problem only on jekyll, and it is the 1st time. On ph-submissions everything works fine. Could you check this @programminghistorian/technical-team please?

**Comment by spapastamkou** [comment]
ok, the problem is probably related to #1462, I just saw that. I'll close the ticket after confirmation.

**Comment by walshbr** [comment]
If this is a permissions thing then @mdlincoln (I think) is the only one with permissions to actually change permissions for other people.

**Comment by spapastamkou** [comment]
Yes, this is it, thanks @walshbr. 
@mdlincoln I've been working locally, nothing in rush about this ticket.

**Comment by mdlincoln** [comment]
@spapastamkou I'm sorry, it wasn't directly related to #1462 but I _did_ modify one of the repo settings and that may have broken permissions. Can you please try again and see if you can open a PR now?

**Comment by spapastamkou** [comment]
all ok now @mdlincoln, thank you. I close the ticket.
