### ISSUE TITLE
Lesson references a version of GitHub Desktop that is no longer maintained

### ISSUE THREAD

**Issue by billygriffin** [programminghistorian/jekyll#1466]
Lesson: [An Introduction to Programming Using GitHub Desktop](https://programminghistorian.org/en/lessons/getting-started-with-github-desktop)
OS: Mac and Windows, latest versions

👋 Hi folks! I'm the product manager for GitHub Desktop, and I wanted to let y'all know that the version of GitHub Desktop introduced in this lesson is no longer maintained and we definitely do not recommend that people download it. Additionally, very soon it's likely that users will not be able to authenticate with the classic apps. We recently released version 2.0 of the latest version of the app, and it has been generally well received especially by folks learning, so hopefully y'all would now be comfortable swapping the references to classic to the new application.

I'm happy to help with some of the legwork to switch over the English translation of this lesson at the very least, if that would be helpful, but I wanted to find out if you're open to that and what concerns, if any, you might have.

Thanks!

**Comment by drjwbaker** [comment]
Thanks @billygriffin for reaching out. Really nice to know that GitHub staff have our backs on this one. We've got a workflow of submitting changes via pull request (https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions) which I believe anyone can already do. Do you think the work updating the lesson will be more substantial than a few pull requests? If so, and you think we need to start afresh, we also have a lesson retirement policy to cover this https://programminghistorian.org/en/lesson-retirement-policy Note: we're currently going through a similar process updating our lessons that using Python 2, so migrating lessons from depreciated tech is something we are actively working on :)

**Comment by mdlincoln** [comment]
The interface for the new GH desktop app is significantly different from the old one, so I'd say this is a retire&rewrite/re-review situation @drjwbaker. Does @programminghistorian/english-team have any thoughts on this before we proceed?

**Comment by billygriffin** [comment]
Thanks @drjwbaker! I'm in agreement with @mdlincoln after going through the entirety of the course that the content and screenshots are too divergent to realistically update, other than just using it as guardrails and an outline once it gets into specifics of the GitHub Desktop portion. The overall portions about version control more generally do still seem reasonable to bring over to a new page.

I would be more than happy to review any pull requests or provide some help in reviewing and updating content, but usually content like this works a bit better coming not from GitHub's voice. We did recently release a guide that walks through many of these steps to help folks get set up more quickly using Desktop (https://help.github.com/en/desktop/getting-started-with-github-desktop/creating-your-first-repository-using-github-desktop) that does contain screenshots and helpful guidance, but it's certainly not specific to the use case y'all are driving toward.

One upside I noticed going forward is that the same app now works on Mac *and* Windows, thought still not supported on Linux. Looks like the current version only references the previous Mac app, so this will hopefully be a positive for people on Windows as well.

More generally, I really appreciate the quick responses, and please let me know how I can be helpful!

**Comment by mdlincoln** [comment]
Documenting from the call on #1449 - I'd expressed the opinion that writing a whole tutorial for a generalized piece of software like GH desktop doesn't fall within our purview because it doesn't go significantly beyond the documentation supplied by the developer. If it's not really a tutorial for historians/humanists, then why can't we just defer to the official developer documentation? Another option is to have git-dependent lessons point to well-maintained beginner tutorials like http://swcarpentry.github.io/git-novice/

**Comment by jenniferisasi** [comment]
> Documenting from the call on #1449 - I'd expressed the opinion that writing a whole tutorial for a generalized piece of software like GH desktop doesn't fall within our purview because it doesn't go significantly beyond the documentation supplied by the developer. If it's not really a tutorial for historians/humanists, then why can't we just defer to the official developer documentation? Another option is to have git-dependent lessons point to well-maintained beginner tutorials like http://swcarpentry.github.io/git-novice/

For reference, I just found that the lesson you suggest is also available in Spanish (https://swcarpentry.github.io/git-novice-es/) - our version of the lesson has been visited 9.802 times this year - and it is not available in French, at least for now.

**Comment by drjwbaker** [comment]
I'll all for us not duplicating the great work of the Carpentries. Looking through our lesson, there is not a huge amount that is history/humanities specific. Perhaps if we retire our lesson, we can also point to the SWC material in some way at the same time. On FR, I haven't heard of any plans for SWC to translate into languages other than ES. But we could ask.

**Comment by svmelton** [comment]
I concur that this is more firmly in the court of SWC and should be retired. If we decide to retire it, is there anything that needs to be done on the ME's end, or is it a technical team workflow? I'm reading through the [retirement policy](https://programminghistorian.org/en/lesson-retirement-policy) and just want to make sure I understand the process and expectations.

**Comment by mdlincoln** [comment]
Thanks for weighing in @svmelton. Given that we haven't heard any votes against retiring, I think we can begin the process. I'll put the pull request together so you can see what the changes look like, and I'll ask you to review and accept the changes so we can use this as a good walkthrough of the general PR process as well.

**Comment by acrymble** [comment]
It would be good to disciss this with the author.

**Comment by mdlincoln** [comment]
We may inform them, but we structured our policy so that it's in the hands of the editorial board - that's why we have it.
