### ISSUE TITLE
Minor grammatical error

### ISSUE THREAD

**Issue by DanielBrett** [programminghistorian/jekyll#1467]
Hi there!

I noticed a small grammatical error in the Basic Text Processing in R tutorial.  The very last sentence in the Analyzing Barack Obama's 2016 State of the Union Address Exploratory Analysis section hast the words "seem to suggest" repeated twice.

Hope this helps!

Daniel Brett
Brock University Digital Scholarship Lab Technical Support

**Comment by jenniferisasi** [comment]
@DanielBrett thank you warning us about this typo! It has now been fixed.
