### ISSUE TITLE
PH-FR 3M Planning

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1469]
@fdlaramee, @grandjeanmartin and me established a basic 3 month planning of our activities. This ticket is our reminder. 

### Translations
- [x] Analyzing Documents with TF-IDF: François-Dominic
- [ ] From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources: Martin
- [x] Getting Started with Markdown: Sofia

### Translation editions  
- [x] Préserver ses données de recherche: François-Dominic 
- [x] Comprendre les expressions régulières: Sofia 
- [ ] Introduction aux bots Twitter avec Tracery: Sofia (E checks after reviews)

### Translation reviews
- [x] Préserver ses données de recherche: Martin, Sofia 
- [x] Comprendre les expressions régulières: François Dominic 

### Other 
- [x] Document the FR translation guidelines or a dedicated page in the wiki with the references we used for making our choices about the translation of basic terms and inclusive writing: Sofia 
- [x] Finish with the lessons request FR page and publish it: all (#1431 + PR #1551) 
- [x] FR Kanban board (#1546 + #1491) Sofia + @svmelton 

If I forget something, please @fdlaramee and @grandjeanmartin complete.

**Comment by acrymble** [comment]
should we all have plans like this? It seems like a good way to keep everyone focused.

**Comment by rivaquiroga** [comment]
This is a great idea!

**Comment by spapastamkou** [comment]
@fdlaramee @grandjeanmartin Je viens de créer une page wiki qui s'intitule French Translation Documentation et dont le contenu est en français.  https://github.com/programminghistorian/jekyll/wiki/French-Translation-Documentation
Elle explicite les choix faits au début du projet; elle a vocation à s'améliorer et à évoluer si besoin. Si vous voyez des choses qui manquent à votre avis, merci de les ajouter directement ou les signaler. Merci!

**Comment by spapastamkou** [comment]
I note here that Translation editions / Comprendre les expressions régulières should either pass to the next 3M plan or will delay closing this ticket, as the translator let me know that she will be able to deliver the revised (and final version) of the text, following the reviews, in January.

**Comment by spapastamkou** [comment]
Habemus [FR kanban](https://github.com/programminghistorian/jekyll/projects/5) as per #1546

**Comment by grandjeanmartin** [comment]
👍 Comment est-ce qu'on l'utilise et est-ce que ça se met à jour en fonction des issues, etc. ou est-ce que ça doit être actualisé ?

**Comment by spapastamkou** [comment]
Je suis en train d'explorer; pour l'instant j'ai activé l'automatisation seulement pour la colonne "Done" où tout ticket fermé (proposition et relecture) dans l'avenir ira dedans (sauf pour ceux qui étaient déjà fermés et que j'ai mis manuellement car peu nombreux encore). Mais jouez aussi avec @fdlaramee, si vous voulez, et si vous avez des idées, on peut revoir l'organisation ou l'automatisation.

**Comment by spapastamkou** [comment]
@grandjeanmartin As-tu pu avancer avec la traduction ou on la reporte au prochain ticket? Je fais le ménage pour préparer le prochain ticket d'ici à la fin du mois:-)

**Comment by spapastamkou** [comment]
2 unfinished tasks from this ticket were reported to #1642.
