### ISSUE TITLE
ISSN for 'ongoing integrating resource'

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#147]
As far as I can tell, we are elligible for an ISSN number as an 'ongoing integrating resource':

http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/

This is free, and I think would be useful for increasing findability in communities used to working with these types of numbers (eg, libraries). I'm happy to pursue this if no one objects. It also adds an element of confidence that we intend to be here indefinitely.

The only change this would require is that we display the number on the website. Probably in the footer.

**Comment by ianmilligan1** [comment]
This is an excellent idea, Adam - I think we should go for it! Happy to help if you want a hand. Looks pretty straigthforward. Should we get an ISSN through the UK agency?

**Comment by acrymble** [comment]
That's a worthwhile point to raise. We have to choose one country to claim as the location of publication. It seems the world has not quite caught up with the 21st century. We have a claim to UK, Canada, and American publication locales. Does anyone want to put forth a particular nationalist case? If I fill in the form, I'll have to put my own address, which is in the UK.

**Comment by fredgibbs** [comment]
it might need to be wherever GitHub is hosted, but i can't claim to know
anything about international copyright law.

**Comment by acrymble** [comment]
It's the location of the 'publisher', not the physical storage devices. As a non-legal entity we don't really fit into this world of lawsuits and profits.

**Comment by acrymble** [comment]
For the sake of simplicity, I propose that I just do this via the Uk system. I don't think we need to make a big deal about location. Any objections?

**Comment by ianmilligan1** [comment]
I think that sounds like a good idea, @acrymble. Happy to see it registered via UK.

**Comment by acrymble** [comment]
This requires us to have a visible indicator of our last update. Either through a volume/version number, or a 'last updated on x date' somewhere on the site. Can we add that to the footer and tie it in from some metadata generated on github? or is that complicated?

**Comment by ianmilligan1** [comment]
A quick perusal of StackOverflow seems to indicate that while there are ways to programmatically query the last update of the repo, it's beyond my personal ability to pipe that into our Jekyll pages.

Could we do quarterly or bi-annual 'issues'? 

In some ways, maybe doing a quarterly announce could tie into #119, our issue around announcing new lessons. i.e. each quarter, we update the number and do a reminder note out to the usual list-serv suspects?

**Comment by acrymble** [comment]
We had a discussion about that in issue #64. I'm happy to reopen that idea because it makes things easier in this instance.

**Comment by ianmilligan1** [comment]
Perfect - it's all coming together... maybe. I'd be happy to take leadership of the quarterly release cycle if folks want to do this. Maybe on the next call (which I unfortunately can't make) we can make a decision and figure out how the cycle should work?

**Comment by mdlincoln** [comment]
At the risk of butting in, I believe the [Jekyll variable](http://jekyllrb.com/docs/variables/) `{{site.time}}` ought to reflect the last timestamp that github regenerated the site, which it does on each change to the `gh-pages` branch.

**Comment by ianmilligan1** [comment]
Not butting in at all, @mdlincoln, that's fantastic to learn about!

**Comment by acrymble** [comment]
@ianmilligan1 I think we can get away with an annual volume instead. I released our code on Zenodo in September, after we discussed and rejected volume numbers.

https://zenodo.org/record/30935#.VkHqfqKjTQg

Maybe we can just shift that into this new need, as it addresses some of the concerns from our conversations on gender and making the site look more like the genre of academic publications that people understand (#152).

We started publishing in 2012. But do we back-number, or just say we're on Volume 2 as of September? I'd say the latter. Once that's in place I can apply for an ISSN.

**Comment by acrymble** [comment]
Thanks to @mdlincoln. I tweaked that to {{ site.time | date_to_long_string }} to get it to look prettier.

I have requested an ISSN. Will report back when I hear outcome.

**Comment by acrymble** [comment]
Dear Dr Crymble,

INTERNATIONAL STANDARD SERIAL NUMBER (ISSN)

Thank you for your recent enquiry.  We have assigned the following ISSN:

The programming historian      ISSN 2397-2068

We would be grateful if the ISSN could be printed in all issues of the serial, preferably on the top right-hand corner of the front cover or title screen in the form given above, i.e. preceded by the letters ISSN with a hyphen separating the two halves of the number.  If the serial is available in more than one physical format, a separate number is assigned to each version and all the ISSN should be quoted on each version available, with an appropriate qualifier in brackets, eg:

ISSN 0000-0000 (Print)
ISSN 0000-0000 (Online)
ISSN 0000-0000 (CD-ROM)

The same ISSN is printed on successive issues of the serial, providing the title does not change.  Please notify us in advance of any change in title, however slight, as this may necessitate the assigning of a new number. The ISSN should also be quoted in all promotional and descriptive material concerning the serial.

The ISSN UK Centre requires only the first issue of a publication. For details of the current and future arrangements for legal deposit of websites and electronic publications, please see the information provided at:

http://www.bl.uk/aboutus/legaldeposit/websites/index.html

**Comment by drjwbaker** [comment]
Nice assumption there that journals are printed.

**Comment by ianmilligan1** [comment]
:+1: Great stuff, @acrymble. Thanks for getting this up and running! (and yeah, love that @drjwbaker)
