### ISSUE TITLE
Lesson Transliterating Non-ASCII Characters needs to be reworked for Python 3

### ISSUE THREAD

**Issue by frederik-elwert** [programminghistorian/jekyll#1471]
The lesson [Transliterating non-ASCII characters with Python](https://programminghistorian.org/en/lessons/transliterating) needs to be updated to Python 3, see #1460. The lesson heavily deals with unicode and Python strings, where Py3 and Py2 have major differences. Thus, the lesson has to be re-written in parts.

**Comment by frederik-elwert** [comment]
I started working on the lesson. I think I cannot assign it to myself, I probably don’t have the required rights?

**Comment by acrymble** [comment]
I've added our managing editors to this thread, as this is really an editorial issue.
