### ISSUE TITLE
Establishing formal meeting minutes

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1476]
It was requested out of our internal team survey that we establish formal minutes to meetings. These should be kept in a central repository for future access. I think in the first instance  this most affects @amsichani who hosts our group meetings. Can we get feedback from her on  this?

**Comment by drjwbaker** [comment]
Given that we have the reports, can we just have lists of 'Decisions' and 'Actions'? It is way way easier, and provides 95% of what people coming back to them will need (for context, my department now only records decisions and actions and we are a large academic unit responsible for lots of staff, students, cash, and with statutory responsibilities..)

**Comment by acrymble** [comment]
I've attached a possible minutes template for discussion. It's fairly basic, I think. @drjwbaker is this similar to what your department produces? We'd need to store these permanently somewhere accessible.

[PH Minutes Template.docx](https://github.com/programminghistorian/jekyll/files/3674849/PH.Minutes.Template.docx)

**Comment by drjwbaker** [comment]
That'll work. I'd suggest not reproducing the reports (to avoid duplication of effort) but just linking to the report in the relevant ticket.
On storage, unless we consider anything here privileged, we may as well just make a folder on the repo.

**Comment by amsichani** [comment]
Hi @acrymble @drjwbaker thanks for the idea- I ve started writing down the minutes in the existing ticket but I am happy to explore also this option. So, in order to be clear, for our Skype meetings we are going to produce 

**before the Skype meeting**

- [ ] a doodle via email to secure a date
- [ ] a dedicated ticket for the meeting 
- [ ] an agenda for the meeting 
- [ ] team reports (before the meeting)

 **after the meeting**  
- [ ] brief minutes in the ticket
- [ ] minutes in doc format - stored by the Archivist

I understand the necessity of keeping things in track and in a sustainable format (also for the Ltd) but I feel that we need to document decisions /tasks also in the ticket itself because its an accessible and straightforward way to this info.
Thoughts?

**Comment by acrymble** [comment]
Thanks for highlighting the labour @amsichani 

I think the dedicated ticket can continue to be the agenda, so 2 & 3 above can be combined. Team reports contribute to that same ticket.

The minutes can also be in .md (maybe that's better give our approach). So the only new thing is recording the minutes and uploading them to jekyll. It's just a clear time-stamped set of actions and decisions that we hope is easier to keep track of for anyone missing a meeting or needing to refer back to one (many  people comment that our current system is difficult for this right now)

**Comment by amsichani** [comment]
I am not sure I understand the suggested procedure @acrymble : I am going to upload the minutes in the ticket or no? And then, a md file of these it should be uploaded in a dedicated jekyll folder as such?

**Comment by acrymble** [comment]
The minutes are a new file (let's say it's .md). It's pre-populated with the Agenda items for the meeting. You then record decisions and actions in that .md file, and when complete it's uploaded to a new folder we'll create. At the beginning of each meeting (as is common) we approve or amend the minutes from the previous meeting. It then acts as an agreed record of what took place.

For example:

3. Establishing formal meeting minutes
Documents:  
- Ticket #1476

Reports (none)
Decision: Team agreed to adopt formal meetings for minutes
Actions: AM to complete and upload formal meeting minutes to /minutes folder henceforth asp art of role as Project Manager at Large

**Comment by acrymble** [comment]
If you think it's too much to chair and be secretary of meetings @amsichani maybe we need a secretary?

**Comment by amsichani** [comment]
TBH the last couple of times and esp with the new team structure is really hard to keep track of everything: monitoring the call, participate and record all the discussions, keeping minutes, then trying to formalise them , linking with tickets , upload them, etc. It might be just the new developments or just me be very tired/perfectionist. I think two person team will be a good idea to explore.

**Comment by amsichani** [comment]
I am still not sure how you suggest us to proceed with the structure of the minutes. Do you want me to create a new .md file for the minutes besides the existing ticket (.md) opened for the meeting? Sorry for this.

**Comment by acrymble** [comment]
Fair. Let's do that. I'll try next time to do a test run of the minutes at our next meeting. And we can revise it to meet our needs.

**Comment by acrymble** [comment]
You can just do the same as always. I'll act as secretary while we work on this workflow.

**Comment by amsichani** [comment]
thanks @acrymble

**Comment by acrymble** [comment]
I've added the template to the wiki and I will fill it in at our next editorial board meeting.  We can assess it's effectiveness then. Thank you to whomever anonymously suggested we pursue this via  our team survey.
