### ISSUE TITLE
Personal Project Plans

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1477]
Our team survey suggested it might be valuable to help people devise plans for their project involvement on an ongoing basis. I'd like to suggest that we first trial this on a voluntary basis before rolling it out to the whole team. This would involve having an informal meeting with me to discuss and then record your project goals for the next 3, 6, and 12 months.

Whether these are public or private, I think we need to consider as a team.

If you're willing to try this out, please respond here so I can get in touch with you about a call. If you have any ideas or concerns, please share them here too, since this is supposed to be a helpful process.

**Comment by acrymble** [comment]
I'll do one for me first, to show what that might look like:

---

Teams: Team Development, Global

3 Months:
- submit British Academy workshop grant for workshop in Mexico/South Africa (£20,000)
- asssist @drjwbaker and @amsichani in the immediate task of getting ProgHist Ltd operational
- assist in the onboarding of new team members
- complete a draft (with the whole team) of a 2, 5, and 10 year plan for the project.

6 months:
- apply for some core funding to support our growth and the development of a sustainable infrastructure (£250,000)
- re-assess new team structure and help teams adjust as needed

12 months:
- help implement a sustainable business model that ensures we can grow into the following year.

**Comment by acrymble** [comment]
I'll close this in a couple of days if I don't hear from anyone, as it doesn't seem like this is something people want.

**Comment by arojascastro** [comment]
Teams: Spanish Team (as far as I know)

3 Months:
- I do not have any lesson to edit or proofread
- do this task https://github.com/programminghistorian/jekyll/pull/1357
 
6 months:
- translate a new lesson (probably this https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages)

12 months:
- organize a PH workshop in La Habana, Cuba

**Comment by jenniferisasi** [comment]
Teams: Communications Team, Technical Team, Spanish Team

3 Months:
- Write end of the year Newsletter in three languages 
- Edit lesson [#254](https://github.com/programminghistorian/ph-submissions/issues/254) 
- Submit lesson for publication
- Continue learning technical skills 

6 months:
- Edit lesson after peer-review
- Write two trimestral Newsletters in three languages
- Continue learning technical skills 
- Assist further in technical issues 

12 months:
- Organize/help organize a PH workshop in Spanish
- Help implement a sustainable business model 

PS: I am looking for a job and my status will change by August 2020, if not earlier, so 6 and 12 month plans could change drastically

**Comment by acrymble** [comment]
@arojascastro interesting plan. Did you need help raising money for the Cuban workshop?

**Comment by arojascastro** [comment]
@acrymble for organizing the event itself no, because we are planning to do this workshop in the context of a bigger conference. But it would be cool to offer PH small grants to fund people from developing countries to travel to Cuba... if possible.

**Comment by drjwbaker** [comment]
Which feeds into https://github.com/programminghistorian/jekyll/issues/1487: if we have a continuous donation drive banner/comms strategy (pinging @jenniferisasi as Comms manager), we can easily switch from continuous donation drives to donation drives that point out specific things we could/would do with that money, like paying bursaries to enable people from [ODA countries](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm) to go to a PH workshop in Cuba.

**Comment by acrymble** [comment]
I don't think t here's been enough interest in this idea across the team to pursue it further at this time.
