### ISSUE TITLE
Funded Impact Manager Post

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1489]
Following an application I made to the [University of Sussex's ESRC Impact Accelerator Account Fast Track Engagement Fund](http://www.sussex.ac.uk/staff/research/rqi/rqi_information_and_support/rqi_impact_funding/if-esrciaa/), we've won £3k for an short term (2 months) fractional (0.4 FTE) Impact Manager.

The main focus of the role will be to leverage our existing partnerships to:

- Publish a report on expanding Programming Historian’s outreach and impact activities with a focus on non-historian communities in the Global South.
- Deliver a business plan outlining the resources required to make the role of Impact Manager sustainable and potential pathways for funding.

I'm currently working on all the internal paperwork/processes that a new post creates. I'm aiming for a November start, but that may be optimistic if we need to go through a full recruitment process. I hope to have an update soon.

**Comment by drjwbaker** [comment]
Quick update. There is a possibility this may end up in internal redeployment, if not, the job will go up this week. Once it is up, applicants will have two weeks to apply. I'll alert all team members by email.

**Comment by drjwbaker** [comment]
This job has now been advertised https://www.sussex.ac.uk/about/jobs/research-assistant-impact-manager-prog-hist-2753

**Comment by acrymble** [comment]
Great work @drjwbaker. I know this took a lot of effort on your part.

**Comment by jenniferisasi** [comment]
This is great news @drjwbaker. I subscribe to Adam’s message of gratitude for you working on this one. I am looking forward to see where this research and roadmap takes us

**Comment by drjwbaker** [comment]
Just so you know, I'm getting interest in the post, which is encouraging.

**Comment by acrymble** [comment]
@drjwbaker if you want help with this process at all, just let us know.

**Comment by drjwbaker** [comment]
Ah, I'd been meaning to say: applications are in, an internal panel will shortlist in Wednesday (@amsichani, me, and a neutral colleague from Sussex library), and then we hope to interview before Christmas.

**Comment by drjwbaker** [comment]
And we have some excellent applicants.

**Comment by acrymble** [comment]
Can't wait to work with them.

**Comment by jenniferisasi** [comment]
Thanks @drjwbaker for keeping us posted, and @amandavisconti for participating in the search committee/panel. Looking forward to the next update.

**Comment by drjwbaker** [comment]
Update: we've shortlisted and will interview on Thursday 19 December. So with luck, we'll have someone in place early next year.

**Comment by drjwbaker** [comment]
Now the paperwork is complete, I'm delighted to confirm that [Penny Andrews](https://orcid.org/0000-0002-4530-0862) will be joining Sussex on 3 Feb to take on this role (2 months, 2 days per week). Penny has a strong background in open access, qualitative research, report writing, and business planning. I'm confident they will be a valuable asset.

Penny and I will be meeting on 3 Feb to discuss the work plan and deliverables. As and when, one or both of us will be in touch with some of you to pick your brains on PH, who we work with, and our aspirations.

More soon!

**Comment by acrymble** [comment]
what wonderful news. I hope to get the chance to meet Penny. Thanks @drjwbaker for so much effort on this.

**Comment by jenniferisasi** [comment]
This is great news! Thank you @drjwbaker for this, and I am looking forward to meeting Penny.

**Comment by acrymble** [comment]
Closing this as the post has been appointed.

**Comment by drjwbaker** [comment]
@JMParr This is what I was referring to. Main outputs are..

- Publish a report on expanding Programming Historian’s outreach and impact activities with a focus on non-historian communities in the Global South.
- Deliver (to the Programming Historian Board of Trustees) a business plan outlining the resources required to make the role of Impact Manager sustainable and potential pathways for funding.

..which I think we be made all the better by finding out more about all the excellent outreach work you've been doing :)

**Comment by JMParr** [comment]
Thanks! Yes. It's exactly what the Global Team has been up to. I think some of the bigger things she can maybe help with is working on making this sustainable. In our Skype chat earlier in January, Quinn D highlighted groups in So. Korea, Thailand, Hong Kong, Taiwan, etc, doing some great work. There's also robust DH communities in India and the Middle East. So, aside from the language issues inherent in tech's English-centeredness, we need to develop a sustainable outreach strategy.

**Comment by drjwbaker** [comment]
**Update**. This work is progressing nicely (Covid-19 notwithstanding). I also managed to repurpose an underspend into 2 more weeks of Penny's time. This means we can add an extra feedback loop into the report writing, specifically time for the wider PH team to comment on the report and Penny action/respond to those comments before we move to publication. I think this is a win. I'll be in touch soon with the report text for comment.

**Comment by drjwbaker** [comment]
**Update** Report has now been sent to the Project Team for comment, with the aim to publish 7 May.

**Comment by JMParr** [comment]
Excellent. Thanks for the update, James.

**Comment by drjwbaker** [comment]
Report now published:

> Andrews, Penny, & The Programming Historian. (2020, May 19). The Programming Historian: developing and sustaining impact in the Global South (Version 1.0). Zenodo. http://doi.org/10.5281/zenodo.3813763
