### ISSUE TITLE
Proposal for donation implementation

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1503]
Following work on donation mechanisms https://github.com/programminghistorian/jekyll/issues/1457, membership https://github.com/programminghistorian/jekyll/issues/1405, and business models https://github.com/programminghistorian/jekyll/issues/1487 we propose to use this ticket to agree on implementing of donations to support our work. There are a number of strands to this work, so this is my attempt - on behalf of the Project Development Team - to pull together an actionable proposal.

1) We propose Patreon as the primary mechanism for ongoing donation, the benefit of which being that it provides a sustainable income. We propose to implement the Patreon tiers listed at https://github.com/programminghistorian/jekyll/issues/916#issuecomment-541396704. Once agreed **these are hard to change** (adjusting the tiers means cancelling ongoing donations), so we need to get this right. *This is all setup and ready to go.*
2) We propose Paypal as the primary mechanism for one off donations, the benefit of which is that Paypal is a widely used checkout mechanism. We will also accept bank transfer, cheque, and cash. *This is all setup and ready to go.*
3) We propose that parts of the site be updated to generate donations. These include:
	a) Update to https://programminghistorian.org/en/support-us listing all possible donation routes. *This is ready to go in English https://github.com/programminghistorian/jekyll/pull/1504 and will move to translation if/when agreed.*
	b) Paypal and Patreon buttons in the site footer. *This has been tested https://github.com/programminghistorian/jekyll/pull/1502*
	c) Some kind of banner, perhaps as a call out on all our lesson pages, where we can display donation info and our latest campaign. *This is currently the least specified part of the proposal.* We'd be grateful for input from @jenniferisasi on this, and how this might fit with comms (e.g. the twitter bot)

**Under our [Lazy Consensus model](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance) I move that we discuss this at our next Editorial Board meeting https://github.com/programminghistorian/jekyll/issues/1483 with a view to receiving all feedback no later than 4 November 2019**.

Note, I think this affects everyone in some way, so please take a look. For example:

- @jenniferisasi: this feeds into the comms strategy
- @programminghistorian/technical-team: scoping design of *3c* above will involve technical time.
- @programminghistorian/french-team @programminghistorian/spanish-team @programminghistorian/english-team: editorial impacts here include workflows for copyediting https://github.com/programminghistorian/jekyll/issues/1381 using funds generated and translation labour.
- @JMParr: impact on global team relating to capacity funds will hopefully create to spend money on activities that support audiences in the global south.

**Comment by drjwbaker** [comment]
- [x] Agree Patreon tiers https://github.com/programminghistorian/jekyll/issues/916#issuecomment-541396704
- [x] Agree Paypal use.
- [ ] Update 'support us' page.
- [ ] Add links to site.
- [ ] Look into campaign banner.

**Comment by jenniferisasi** [comment]
Thanks for taking care of placing mechanism for the project to get some funds on a regular basis.
On 3c above I have a few ideas, in order of my preference: 
1. At the end of the lesson, a sentence with links along the lines of: If you liked this lesson please consider supporting the project for us to continue to publish similar work. 
2. At the beginning of each lesson, similar to 1, but it will conflict (at least for me) with the banner on an available translation. 
On the twitter bot: Just add messages requesting donations or patronage in the spreadsheet and let it do the work? @walshbr I'm wondering if the more tweets we add for the bot, it will space them out too much in time? That would be my only concern on using the bot for this purpose (though we don't want to ask for money every other day either)

**Comment by drjwbaker** [comment]
Thanks for the input @jenniferisasi. I agree that more things at the top of lessons gets in the way on existing text. But I'm also keen not to bury our donation drives at the bottom. I'm wondering if it can go to the right of the peer review tick and license. We have some space there.
![Screenshot 2019-10-24 at 11 04 44](https://user-images.githubusercontent.com/4965300/67475443-1ca57c00-f64e-11e9-9787-f78e8a9fadb7.png)

**Comment by walshbr** [comment]
@jenniferisasi - that sort of use of the bot has come up before. It's really not meant for such things - it works through randomization of the content in the spreadsheet. There's no feed or anything - if we wanted to regularly schedule things we should just use Tweetdeck to schedule a tweet every few months or something like that. 

I think the screenshot you shared seems like a good way to do it @drjwbaker. From a web design standpoint, I think we should avoid putting more information in the footer (it's already crowded down there).

**Comment by JMParr** [comment]
Hi, All - In general, I am in support of all of James' suggestions. Not to
overly complicate things, but I wondered if there was a way to also allow
donors to use Venmo? The reasons I ask is that there's growing push back
against PayPal here in the US for political reasons, and I know a number of
people who are boycotting the platform.

**Comment by svmelton** [comment]
Hi all,

I do love Venmo, but it's probably worth noting that they're owned by
PayPal, as well. That said, if it's an easy add, it can't hurt to have
multiple options.

Sarah

**Comment by drjwbaker** [comment]
I believe Venmo is only available to those who bank in the US.

**Comment by jenniferisasi** [comment]
@drjwbaker I like the example you placed on the screenshot! I was thinking about putting it below but of course it makes much more sense there. 

@walshbr right, that is why I was asking...I'll look into scheduling tweets through Tweetdeck (thanks for the tip!) once we approve the mechanisms. 

And yes, as per [Venmo's requirements](https://help.venmo.com/hc/en-us/articles/209690188-Requirements), it is only available to US users.

**Comment by drjwbaker** [comment]
@walshbr Where can I find the file I need to edit to test putting some donate text after the CC-BY notice? (somewhere in here https://github.com/programminghistorian/jekyll/blob/gh-pages/_layouts/lesson.html maybe?)

**Comment by acrymble** [comment]
alternative possibility. 
![new-ribbon-labels-corner-banner-new-tag-label-vector-23575386](https://user-images.githubusercontent.com/646647/67560990-ec281580-f713-11e9-9143-e6e5e1f3585b.jpg)

**Comment by drjwbaker** [comment]
You mean overhanging clickable banners?

**Comment by acrymble** [comment]
yea. On our icons at the top. More visual.

**Comment by drjwbaker** [comment]
We'd need input from @programminghistorian/technical-team on what is possible within our current architecture and achievable with the resources they have.

**Comment by JMParr** [comment]
Oops. I hadn't realized!

**Comment by walshbr** [comment]
Yeah that looks correct @drjwbaker - a new div between lines 57 and 58. Any of these solutions are going to need CSS styling, though. The banner solutions would probably just take slightly more work.

**Comment by amsichani** [comment]
thanks @drjwbaker for this. I like the idea of placing it in the header of the lesson and not in the footer .
On Paypal, where I can see the political aspect of its use, it is an easy way for money transfer - bank transfer is always a safe alternative.
I am not sure I get /like the visual clickable banners with donation on it @acrymble -- it looks like we 'll suddenly become an eBay store with brand new offers.

**Comment by drjwbaker** [comment]
Okay so I had a go https://github.com/programminghistorian/jekyll/pull/1520 See https://deploy-preview-1520--ph-dev.netlify.com/en/lessons/introduction-to-populating-a-website-with-api-data Note, I don't know how to make text text tab to the right a bit, or align vertically, or start with a nice money image, or make the text font correct, but apart from that this is what it could look like :)

**Comment by acrymble** [comment]
It's a bit ambiguous who's being supported. The author?

**Comment by walshbr** [comment]
How about "Support the Programming Historian"? I like the idea of the currency, but leaving it text probably makes it more internationalizable (the denominations listed are all Eurocentric right now, and I'm sure we wouldn't want to keep adding things!). I can help style it once you have the text and location settled, though I might come with further suggestions as to how the text could better accommodate the styling :) 

Or even just "Support us" or "Support the PH" would be easier to style (text length more in keeping with the other columns there).

**Comment by drjwbaker** [comment]
Yeah. I wasn't concentrating on the text, just getting the placing right, but I changed it to "Support the Programming Historian" 5 minutes ago and am now waiting on Netlify.

And `£$€` was meant as a placeholder for a much more international graphic, so please suggest something. All styling support gratefully received :)

**Comment by drjwbaker** [comment]
Agreed at https://github.com/programminghistorian/jekyll/issues/1483 to press ahead. Thanks all for your input.

**Comment by walshbr** [comment]
Just a note @drjwbaker - we use font awesome for our icons, and they have a lot of options for representing money that aren't denomination specific. Might pick one of those? You can find them at this link - https://fontawesome.com/icons?d=gallery&q=money

**Comment by drjwbaker** [comment]
The credit card one?

**Comment by walshbr** [comment]
Cool - I'll implement that on your PR after lunch and ping you.

**Comment by walshbr** [comment]
Ah @jenniferisasi also had an idea here - https://github.com/programminghistorian/jekyll/pull/1520#issuecomment-548843273

**Comment by drjwbaker** [comment]
fab. On the graphic, I'll defer to our comms chief @jenniferisasi.

**Comment by drjwbaker** [comment]
PR raised https://github.com/programminghistorian/jekyll/pull/1504 to add donation mechanism info to https://programminghistorian.org/en/support-us (and ES/FR equivalents).

**Comment by acrymble** [comment]
@drjwbaker is this ready to close?

**Comment by drjwbaker** [comment]
yes
