### ISSUE TITLE
Lesson not on lessons page

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#151]
The following lesson doesn't appear on our lessons page:
http://programminghistorian.org/lessons/installing-python-modules-pip

I'm not sure why.

**Comment by ianmilligan1** [comment]
It's actually [hidden there](http://programminghistorian.org/lessons/) under "Getting Ready to Program," but not with a separate lesson icon like the others.

Maybe we could have standard pictures/icons for the two lessons listed in that section?

**Comment by acrymble** [comment]
Sounds good to me. Allison, any ideas?

Adam

**Comment by acrymble** [comment]
Sorry I should have used @ahegel.

**Comment by ahegel** [comment]
I agree - I'll add some icons this weekend!

**Comment by ahegel** [comment]
I updated the "Getting Ready to Program" section with a new image for the pip lesson - the other link is to an external site so I didn't give that an image. Look good to you guys, @acrymble and @ianmilligan1?

**Comment by acrymble** [comment]
Great. Thanks.

**Comment by ianmilligan1** [comment]
Looks awesome @ahegel!
