### ISSUE TITLE
Progress reporting for Lesson Sequences

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1525]
A suggestion today from a workshop I was hosting.
For lessons that are part of a sequence, provide visual indicators of how far along you are in the series. For example (lesson 2 of 4).

This mostly relates to the Python and Geospatial series.

Assigning to @amsichani as Education manager

**Comment by mdlincoln** [comment]
This has two technical components if you want to go through with it:

1. Design a data scheme for ordering series lessons in YAML / some kind of text block that editors will need to format and keep updated across lessons
2. Implement a display

@amsichani what are your thoughts on the payoff for this vs. the time needed to implement it?

**Comment by acrymble** [comment]
An alternative to additional infrastructure is just to add a bit of text at the top and bottom of relevant lessons.

**Comment by mdlincoln** [comment]
that's what i mean by some kind of text block

**Comment by amsichani** [comment]
The idea of lessons' sequence is mainly concerning the Python and Geospatial series, as for now, but any decision will also be implemented to other future series. As a user and as Education Manager I think this is a useful addition to these lessons that will help users and facilitate the learning curve of these series.
I am a big fan of visuals, although I suspect a text block of the "(lesson 2 of 4)" type would be more easy and straightforward to be implemented in the YAML file . It could appear near the 'difficulty level' and the 'estimated duration' #1526 or closer to the title perhaps. 
 
a couple of remarks/ tasks on the actual implementation : 
- establish a clear sequence (is there any? in a list format of the lessons in question (separate ticket). I am suspecting this is also related to #1022
- decide with the  @programminghistorian/technical-team on a common implementation approach of the lessons' sequence and #1526 
- @amsichani as Education manager write a blogpost on these two new changes from a enhancement of users' experience point of view

**Comment by acrymble** [comment]
@amsichani there is an order to both of those series, yes. You can find it via the "next" and "previous" links at the bottom of those lessons. Let me know if you get stuck.

**Comment by amsichani** [comment]
Thanks for this @acrymble - I ve noticed the previous and next links , however I d recommend to make a clear list of lessons (based on these links and perhaps and enhance it) so we can more clearly do the maths (lesson 2 of 5 ) etc.

- we also need to notice how this change might affect/be implemented in the ES translation of the series.

**Comment by mdlincoln** [comment]
one way you could do this @amsichani is to manually add a bit of markdown to each lesson like this:

```md
{% include alert.html text="
This lesson is part of a series:

1. [lesson one](url)
2. [lesson two](url)
3. **lesson three** (you are here now)
4. [lesson four](url)
"%}
```

Then it would show up as one of the yellow alert boxes. This would need to be added and customized correctly for each lesson in the series.

If you wanted to get fancy, you could turn this instead into YAML in the headers of lessons:

```yaml
series:
  label: intro-to-python
  sequence: 3
```

and then we figure out a way to compute everything using liquid markup, like

```html
{% if page.series %}
{% assign series_lessons = site.lessons | where: "series.label", page.series.label | sort: "series.sequence" %}
<ol>
{% for lesson in series_lessons %}
<li>
  <a href="{{ lesson.url }}">
    {{ lesson.title }}
    {% if lesson.url == page.url %} (current lesson){% endif %}
  </a>
</li>
{% endfor %}
</ul>
{% endif %}
```
I'm not %100 sure if that code would work, it's just a guess. Since lesson series are fairly uncommon, I don't know if it really makes sense to generate this programmatically - manual markdown might be the most straightforward. But you have options.

**Comment by amsichani** [comment]
many thanks @mdlincoln for these options! I am keen to explore inserting the manual markdown to each of these lessons, as it is indeed needed just in two instances /series so far, so I don't see the point of changing the YAML with all the consequences it might have for the not-relevant lessons. I am now going to update this ticket with a set of tasks in order to further follow this option - and I will take it from there, if thats OK. I will ask again for feedback - cheers!

**Comment by acrymble** [comment]
Some of the new apps for learning languages such as Duolingo have fairly simple and intuitive ways of representing this progress. You might want to take a quick look at some of that competition. Things like 8/10, or a progress bar graphic.

**Comment by amsichani** [comment]
many thanks to all for your comments and ideas so far. I am planning to work on this and #1526 in the next couple of days and I will update the relevant tickets.

**Comment by mdlincoln** [comment]
2020-04-13 meeting discussed:

- replacing the previous/next banners with a single "sequence" banner
- condensing all translation link listings into one banner in order to conserve space (tbd in #1738)

**Comment by mariajoafana** [comment]
Passing by to see what is the status of this and if you need any support to complete this task

**Comment by amsichani** [comment]
I am now working on this ticket and below is a list of tasks for me to do the next couple of days: 

- [x] define the lessons' sequences -- currently two series of lessons , Python (15 EN lessons, 5 ES lessons, 2 FR lessons), GIS (4 EN lessons)
- [ ] manually add a bit of markdown to each lesson to mark the sequence: 
-the initial proposed solution 
```md
{% include alert.html text="
This lesson is part of a series:

1. [lesson one](url)
2. [lesson two](url)
3. **lesson three** (you are here now)
4. [lesson four](url)
"%}
```
 is not feasible for large lessons' series, as the Python one, as it will end up to a huge list inside the banner .
Alternatively we might have: 

```
This lesson is part of a series of 15 lessons - you are on lesson 3 | Go Back | Go Forward 
```

I am happy to explore other options, more visually attractive, but I can't find any hints. If anyone from @programminghistorian/technical-team has any ideas or links, please share them !

- [ ] include the markdown on the lesson sequence inside a banner structure after the https://github.com/programminghistorian/jekyll/issues/1767 banner.

- [ ] it will be part of the Education Manager 's role to ensure that any new lessons within these series or new series will follow this structure & to get in touch also with the @programminghistorian/technical-team .

**Comment by walshbr** [comment]
The piece you propose after "alternatively we might have" seems like a good solution to me!

**Comment by jenniferisasi** [comment]
I agree with @walshbr!

**Comment by mdlincoln** [comment]
I'm glad you have come to a solution for the formatting. I would like you to submit a PR for this before our mid-June tech team meeting. If you need help to meet that deadline, please ask for it frankly.

**Comment by acrymble** [comment]
I've closed Anna Maria's sabbatical ticket on the assumption that this ticket is being reassigned. Making a note here just in case that gets missed.

**Comment by mariajoafana** [comment]
Hi @ZoeLeBlanc, what is the status of this? Let us know if you need some support

**Comment by ZoeLeBlanc** [comment]
Thanks! @mariajoafana I'm taking this issue over and will be looking over the previous code this week.

**Comment by ZoeLeBlanc** [comment]
Just want to make a note of thanks to @amsichani for all her hard work on this issue! I was able to get her code quickly sorted into the existing code base with very few tweaks. Great work 🎉 !
