### ISSUE TITLE
2019 Zenodo deposit

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1530]
I've made the 2019 Zenodo deposit today (using the process outlined on our wiki https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#zenodo). This will involve light editing our our 'About' pages (EN/ES/FR).

Process same as 2018 deposit https://github.com/programminghistorian/jekyll/issues/1067

**Comment by mdlincoln** [comment]
This seems to have been finished by #1531 

Reminder, when you open a PR, if you write `Closes #ISSUE-NUMBER` in the description when you create it on GitHub, merging the PR will auto-close the issue.
