### ISSUE TITLE
Managing Patreon rewards

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1532]
As part of the Patron #916 setup we have promised to:

- thank 'Subscriber' tier supporters on Twitter.
- thank 'Sponsor' tier supporters on Twitter and in our newsletter, and give them a chance to suggest a lesson topic.
- thank 'Patron' tier supporters on Twitter and in our newsletter, give them a chance to suggest a lesson topic, and list their names on our website as a valued sponsor.
- thank 'Lasting Legacy Member' tier supporters on Twitter and in our newsletter, give them a chance to suggest a lesson topic, list their names prominently our website as a valued sponsor, write them a hand-written thank you letter.
- to recognize the first person to join a tier on our sponsorship page.

As Sponsorship Coordinator I'm happy to coordinate and delegating tasks relating to this. 

Specifically I am thinking that:

- @jenniferisasi: thanking people on Twitter and via the newsletter falls within in the purview of the Communications Team. Are you happy to take this and distribute tasks to your team? If so, I will feed you (or someone you delegate) a weekly list - exported direct from Patreon - of people that need thanking.
- @amsichani: giving 'Patrons' and above a chance to suggest a lesson falls within the purview of the Education Manager. In the past, we've done semi-annual blogs on lessons we'd like to see (e.g. https://programminghistorian.org/posts/lessons-we-would-like-to-see). Perhaps to fulfill our promise we could make this an annual thing, and in preparation for it you could contact 'Patrons' and above for suggestions? (I can give you a list when you need it)
- @acrymble: as Director of ProgHist Ltd perhaps drafting a letter to 'Lasting Legacy Members' falls to you?
- finally, I will list 'Patron' and above on the website, as well as the first in each tier.

Does that sound a reasonable division of labour? If so, I'll close the ticket and leave teams to get on distribute the tasks as they see fit.

**Comment by acrymble** [comment]
I would like to suggest that having someone entirely responsible for Patreon increases  someone's  ownership, simplifies the workflow, and makes it easy to make sure all tasks are completed in a consistent manner.

**Comment by amsichani** [comment]
I second @acrymble 's point with a small twist - the person responsible for Patreon will provide with information and ask individuals with certain roles , as mentioned in @drjwbaker initial comment, to perform  necessary actions (eg provide @jenniferisasi with information for tweets &newsleeter / provide @amsichani a list of names to contact on lessons' suggestions etc) . (S)he will have the overview of Patreon workflow and collaborate with dedicated teams/leaders to perform adequate tasks.

**Comment by drjwbaker** [comment]
Thanks both. I was basically advocating for the Sponsorship Coordinator (me) to be 'entirely responsible' (@acrymble's phrase) for Patreon and the tasks that emerge from it, but that the Sponsorship Coordinator shouldn't undertake all the tasks that come out of Patreon, because some are not in the purview of the Sponsorship Coordinator. So @amsichani has more or less captured what I had in mind. Are we happy with that?

**Comment by drjwbaker** [comment]
E.g. It is up to @jenniferisasi as Comms Manager to determine how to do comms. If we want to trust each other to take responsibility for the work our roles entail (as discussed at https://github.com/programminghistorian/jekyll/issues/1483), delegating to the person in the role to deliver a given piece of work is a key part of that.

**Comment by jenniferisasi** [comment]
I agree with this type of coordination and I suggest the following workflow for comms: 

**For tweets:** 
1. @drjwbaker emails me, @jenniferisasi a list of supporters every Monday morning London time
2. @jenniferisasi tweets the list Monday morning US central time 

**For newsletter:** 

1. @drjwbaker curates a list of supporters and shares it with @jenniferisasi on the ticket for the newsletters.
2. @jenniferisasi creates a dedicated section on the newsletter for supporters

My question is, do we anticipate we will have new sponsors every week to thank them?

**Comment by drjwbaker** [comment]
Fab. Thanks for the suggestion @jenniferisasi. On the weekly thing, we'll see, but it won't take me a minute to check and either send a list or send a note saying no additions.

**Comment by acrymble** [comment]
I think this is resolved, @drjwbaker ?

**Comment by drjwbaker** [comment]
I need to document this in Service Integrations first. Then we can close.

**Comment by drjwbaker** [comment]
I've added this to the Service Integrations https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#patreon

@amsichani: can you confirm you are happy with your piece as Ed Manager? Then I can close.

**Comment by amsichani** [comment]
fine by me.thanks!

**Comment by drjwbaker** [comment]
Fab.
