### ISSUE TITLE
Managing Copyediting Hiring

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1537]
## Copyediting Work

The Programming Historian Development Team puts forward its plan for the fair and efficient management of professional copyediting of original lessons to Programming Historian publications (English, Spanish, French).

We welcome comment from the Members and Directors of ProgHist Ltd until the end of November 2019.

---

1 - That until such time as our finances can fully and reliably cover the cost of copyediting, ProgHist ltd funds will only be used for  copyediting, and professional fees / services needed to fulfill our legal requirements as a company.

2 - That copyeditors will be hired as sole traders for individual pieces of work, and will not be employees of ProgHist ltd.

3 - That the Development Team will produce and maintain a list of approved copyeditors that Managing  Editors  can use to choose and engage a copyeditor for original lessons (translations are currently   handled through a peer review process instead). ProgHist Directors and Members are encouraged to put themselves forward for inclusion on this list if they posess the relevant skills.

4 - That rates for copyeditors must be agreed by the Finance Manager or their assignee in advance of agreeing to any work, and will need to be based on availability of funds. That this should not vary substantially from agreed rates set by the Society for Editors and Proofreaders (https://www.sfep.org.uk/resources/suggested-minimum-rates/). Local cost of living should be considered when setting rates, with an aim towards fairness.

5 - That the contact for the copyeditor will be the Managing Editor or their assignee.

6 - That invoices are sent to the Finance Manager or their assignee.

7 - That this policy be revisited once per year, or once item 1 above has been satisfied.

**Comment by arojascastro** [comment]
Thanks! As usual, some questions:

1. copyediting in what language and for which edition? 
2. Rates vary a lot from countries... this has to be contextualized.
3. I thought editors had to proofread and copy edit lessons... is there a real need for this?

**Comment by drjwbaker** [comment]
On 3., one of the initial aims of creating a funding stream was to remove that burden from editors. We have increasingly complex and specalised copy editing needs https://github.com/programminghistorian/jekyll/issues/1381 that would benefit from expert input.

On 2., of course. I guess by referencing https://www.sfep.org.uk/resources/suggested-minimum-rates/ we are expressing a keeness not to undercut UK based copy editors (given that ProgHist Ltd is a company registered in England). If there are similar guidance documents produced by professional copy editing organisations in other countries we work in, I'd be keen that we follow those.

On 1.:

> The Programming Historian Development Team puts forward its plan for the fair and efficient management of professional copyediting of **original lessons to Programming Historian publications (English, Spanish, French)**.

**Comment by acrymble** [comment]
@arojascastro On 3. yes, ideally editors could do this. But it isn't everyone's strength, and it can be incredibly time consuming work. We're using this as a means of improving the consistency and quality of lesson prose.  It's part of an investment in long-term sustainability as well, as hopefully lessons we need less frequent updating after being carefully copyedited.

**Comment by acrymble** [comment]
Thank you for feedback. I have moved this to the Wiki: https://github.com/programminghistorian/jekyll/wiki/Copyeditors
