### ISSUE TITLE
Multi-lingual Patreon

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1539]
Building on https://github.com/programminghistorian/jekyll/issues/916, we'd now like to look at making our Patreon https://www.patreon.com/theprogramminghistorian multi-lingual. Suggestions include:

- separate Patreon pages for ES and FR. *Would require three Patreon accounts, so this is possibly too admin heavy*
- translating the text and running them in parallel.
- multi-lingual videos.

@jenniferisasi : what is your preference here?

**Comment by acrymble** [comment]
I've done very limited research and there may be more culturally appropriate platforms for Spanish and French. Patreon is very US-focused.

**Comment by jenniferisasi** [comment]
> I've done very limited research and there may be more culturally appropriate platforms for Spanish and French. Patreon is very US-focused.

Let me check on this to see if they would make it significantly easier to Spanish and French-speakers. If not, for the time being and taking into account our availability, I would go for: 

- translating the text and running them in parallel.

Having videos would be great but we would need to record, edit, and close-caption at the least.

**Comment by drjwbaker** [comment]
@jenniferisasi Okay. Let me know what you find and I'm happy to help implement. Alternatively, should you want the Patreon login, details here https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#patreon (email me for password).

**Comment by arojascastro** [comment]
I know some people/writers in Spain that are using Patreon: https://www.patreon.com/evacidm

I can ask on Twitter...

**Comment by jenniferisasi** [comment]
I have looked into a specific platform, https://www.goteo.org, which has a multilingual interface yet the content is in the preferred language of the campaign. It is too late now to switch platforms (as we already have some patreons) and I don't think running different platforms is efficient in the long run. So again I advocate for trilingual content in Patreon.

**Comment by arojascastro** [comment]
agreed with @jenniferisasi - i checked ko-fi and others and are only available in English. I think Patreon is quite used in Spain at least.

**Comment by drjwbaker** [comment]
Okay. Thanks for your input. We'll move to translation then.

@spapastamkou @programminghistorian/french-team @rivaquiroga @programminghistorian/spanish-team. We have a translation task please. We'd like the 4 tiers and the 2 goals at https://www.patreon.com/theprogramminghistorian translated please. I'm less sure about the 'About' text though, as that may be overkill. Thoughts @jenniferisasi?

When you are done, please post here and I'll implement on Patreon.

**Comment by fdlaramee** [comment]
For the four tiers:

Abonné (1$ par mois): Merci! Nous vous remercierons publiquement en tant que nouvel abonné dans un message à nos milliers de lecteurs sur Twitter.

Parrain/Marraine (5$ par mois): Merci! Tous les avantages des niveaux précédents, plus un message de remerciement personnalisé dans notre bulletin trimestriel et la possibilité de suggérer un thème de leçon à d'éventuels auteurs (à l'intérieur des cadres de nos publications) sur notre site Web.

Mécène (15$ par mois): Merci! Tous les avantages des niveaux précédents, plus l'affichage de votre nom en tant que commanditaire important sur notre site Web.

Membre "Héritage durable" (200$ par mois): Merci! Tous les avantages des niveaux précédents, plus une note de remerciement manuscrite de la part de notre équipe et une place de choix pour votre nom ou celui de votre organisation sur nos pages de partenariat pendant toute la durée de votre soutien."

Goal #1: "500$ par mois permettront à l'un de nos rédacteurs ou à l'une de nos rédactrices de mettre (et de conserver) à jour nos quelque 130 leçons et de travailler de plus près avec nos auteurs pour assurer que chaque nouvelle leçon sera rédigée de façon claire et accessible."

Goal #2: "1000$ par mois nous permettront d'assurer la traduction de toutes nos leçons en français, en espagnol et en anglais."

**Comment by jenniferisasi** [comment]
Subscriptor ($1 al mes): ¡Gracias! Agradeceremos tu suscripción con un anuncio a nuestros miles de seguidores en Twitter.  
Sponsor ($5 al mes): ¡Gracias! Tendrás los beneficios del nivel anterior junto con un agradecimiento a tu aportación en nuestro boletín informativo trimestral. Además, podrás sugerir un tema para una lección en nuestra página para futuros autores/as (dentro del ámbito de nuestra publicación)  
Mecenas ($15 al mes): ¡Gracias! Tendrás los beneficios de los niveles anteriores junto con tu nombre como patrocinador/a en nuestra página web.
Miembro de legado duradero ($200 al mes): ¡Gracias! Tendrás todos los beneficios de los niveles anteriores junto con una carta de agradecimiento escrita por nuestro equipo así como una mención destacada de tu nombre u organización en nuestra página de patrocinadores por el tiempo que dure tu apoyo. 

Goal 1: Tener 500 dólares al mes nos permite la actualización y mantenimiento de más de 130 lecciones así como trabajar más estrechamente con nuestros/as autores/as para asegurar que cada lección está escrita de forma clara y accessible. 

Goal 2: Con 1.000 dólares al mes podríamos financiar la traducción de todas las lecciones entre inglés, español y francés. 


I would appreciate if @JoshuaGOB could take a look and edit this translation if necessary before adding it to Patreon.

**Comment by JoshuaGOB** [comment]
I'd say it's good to go now.

**Comment by drjwbaker** [comment]
Fab. @acrymble: have you discussed your plans outlined here https://github.com/programminghistorian/jekyll/issues/1554 with the ES and FR teams? (in short: staggered integration of multi-lingual Patreon)

**Comment by acrymble** [comment]
No, but I welcome input as it will require a team effort. Please post thoughts on #1554 if you have any

**Comment by drjwbaker** [comment]
Okay. I ask as it impacts on when we use the descriptions kindly provided above. And I'd be keen that we don't change the English by the time the renewed plan kicks in (when we asked for translation the assumption was that we'd add the ES and FR immediately, but this changed when you suggested the plan at #1554 whilst the translation was ongoing)

**Comment by acrymble** [comment]
You can add them now if you want @drjwbaker. The point of #1554 is to have a plan to drive eyeballs to the page.  Patreon gets effectively zero views without us actively pushing people to it.

**Comment by acrymble** [comment]
I have added the French text to the page https://www.patreon.com/theprogramminghistorian

Some of the fields have character length limits, which means we cannot keep adding additional languages. We need to re-think our strategy.

**Comment by jenniferisasi** [comment]
> Some of the fields have character length limits

Oh, we didn't know this so thanks for pointing it out @acrymble. I would say create another patreon account for additional languages (to keep it in the same platform)?

**Comment by acrymble** [comment]
Additionally, some of the French content I added is hidden under a 'show more' link on the default view.
<img width="1146" alt="Screenshot 2019-12-02 at 18 45 10" src="https://user-images.githubusercontent.com/646647/69985897-0edbf400-1534-11ea-8583-fef71d136e11.png">

I think from a user experience perspective we need separate accounts. Maybe we could experiment and do Spanish in Github Sponsor to see how we like each platform?

**Comment by rivaquiroga** [comment]
Github Sponsors currently has a waiting list. Maybe is better, as @jenniferisasi said, to keep it in the same platform.

**Comment by arojascastro** [comment]
Yes, agreed with Riva and Jennifer! Sorry for jumping so late but this should be a priority since donations are already coming. I would like to donate some money monthly but I do not know yet if the donations are going to be separated by language or distributed equally between three... Is there any place where you have already discussed this?

**Comment by acrymble** [comment]
@arojascastro At present donations go into an unrestricted fund. This means we aren't legally bound to spend the money in a particular way (beyond a moral obligation to do what we say we'll do on Patreon).

We agreed at the last meeting that until we've got more stable income, we'll only spend this  money on copyediting, with the aim of expanding that once we have that covered. @rivaquiroga @spapastamkou and I are currently discussing how we can get Spanish and French copyediting style guidelines produced, so that this can benefit all publications equally. I hope that clarifies our plan at the moment. As always, we welcome feedback.

**Comment by drjwbaker** [comment]
> > Some of the fields have character length limits
> 
> Oh, we didn't know this so thanks for pointing it out @acrymble. I would say create another patreon account for additional languages (to keep it in the same platform)?

I worry that having multiple Patreon accounts (which would be required for this) would be admin heavy.

**Comment by acrymble** [comment]
We could contact them and ask them if we can have 3 pages linking to the same account. Maybe  nobody has ever asked before. It's mostly solo artists that use this site.

**Comment by drjwbaker** [comment]
Do you want to ask?

**Comment by drjwbaker** [comment]
Note, their FAQ suggests they've been asked about this and default people to setting up multiple accounts https://support.patreon.com/hc/en-us/articles/360028555212-Can-I-have-multiple-accounts-

**Comment by acrymble** [comment]
We can use the blog feature to create a non-ideal workaround that mimics the front page as much as possible and direct linguistic groups of readers appropriately to the relevant blog post. It's not perfect but it should be a workaround

<img width="1180" alt="Screenshot 2019-12-07 at 14 58 49" src="https://user-images.githubusercontent.com/646647/70376590-3222ec80-1902-11ea-87ce-06379980ee0a.png">

**Comment by drjwbaker** [comment]
Huh. Good hack idea.

**Comment by acrymble** [comment]
I will try this (and publish it) with the Spanish data. And we can look and decide if we're happy. If so we can close this until a better solution is available.

**Comment by acrymble** [comment]
It isn't as pretty, but here it is: https://www.patreon.com/posts/tiers-en-espanol-32213677
