### ISSUE TITLE
Create generic email address

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#154]
In working on #153, I'm noticing lots of places on the site where @fredgibbs's email is listed as the person to contact, which may run at cross-purposes with what we want to communicate about our collaborative editorial style. Should we consider making a generic email address for PH on Gmail or some such service, which can then be forwarded to all of us or to one of us on a rotating basis?

**Comment by acrymble** [comment]
Sounds fine. I think a rota system is the best approach, otherwise you might get multiple responses that go against one another. That's how H-Net does things. Usually 6 months at a time.

**Comment by ianmilligan1** [comment]
I'm game, and my availability gets pretty decent when I'm back into my regular routine come Jan 2016.

**Comment by fredgibbs** [comment]
I'm happy to rotate off as contact person, as there are other site improvements I'd love to have more time for. @ianmilligan1, if you want next (starting 2016 or earlier if you can manage it), you got it! (if others agree, of course.)

I strongly disagree that we should use a generic email address. I understand that there are good reasons for doing so (if we're trying to distribute email inquiries among us, for instance), but I don't think that transparency and friendliness are among them, and those are two values central to our mission and workflow. Instead, I think we should emphasize our collaborative editorial processes, and perhaps be even more clear that whomever is listed as the point person is truly that (or at least more administrative than editorial), and that the entire team routinely discusses potential, ongoing, and future lessons as well as other inquiries. I agree with the sentiment behind @wcaleb's suggestion, but I think emailing a real person is better ( = less intimidating, more personal, etc) than a generic organization address.

**Comment by wcaleb** [comment]
Those are good points, Fred. I'm not wedded to a generic email address, but do think it might be valuable to make clear that there are multiple potential points of contact. Maybe link to the editorial board contact list whenever we mention the current point person. I also like your idea of making clear how we work collaboratively as an editorial board: I don't think that's really said anywhere on the site. Will close this comment for now and perhaps we can discuss at next Skype call.
