### ISSUE TITLE
Communication: End of the year Newsletter

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1540]
Issue created to post the third newsletter to be published at the end of the year 2019. This will be a 3-month newsletter + year wrap-up of our biggest accomplishments, including:

- all new members in PH
- retirements of PH: Anandi and Marie
- ProgHist Ltd 
- HDH prize for PHes (I have a "diploma" and pic of me) 
- summary of visits to the site, by regions and languages 
- list of all lessons
-- Python lessons update
- a big thanks to all our collaborators including list of patreon names
- Presentation of the PH during the "Teaching digital history" workshop at the Center for Digital History Aarhus (23 October 2019) 
Upcoming events:
- ?

I would appreciate anyone editing this very same comment to add anything they would want to highlight in the end of the year newsletter.

**Comment by drjwbaker** [comment]
>     * all new members in PH

By which you mean Patreon subscribers?

I have no PH related events coming up.

**Comment by acrymble** [comment]
Announcing the updating of our Python lessons to Python3?

**Comment by jenniferisasi** [comment]
> > ```
> > * all new members in PH
> > ```
> 
> 
> By which you mean Patreon subscribers?
> 
> 
> I have no PH related events coming up.

@drjwbaker I meant new editors, not patreons, but I can certainly include a paragraph with all their names.

**Comment by drjwbaker** [comment]
Ah. Yes, new editors are important to mention! :)

**Comment by spapastamkou** [comment]
Added a presentation made during a dhist workshop at the Aarhus University, Denmark. Will send further details by e-mail to @jenniferisasi

**Comment by acrymble** [comment]
I think this is done?
