### ISSUE TITLE
Edit governance doc to better fit sub-team structure/powers

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1543]
Spinning out from https://github.com/programminghistorian/jekyll/issues/1491 a proposal for editing the [Governance](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance#venues-for-discussion) document:

1. add 'Sub-team calls' to our list of 'Venues for Discussion'.
2. edit 'Monthly Skype calls' to 'Monthly Skype calls **(including sub-team reports)**'
3. edit:

> Members who have a specific interest in an issue (whether in approval or in dissent) are expected to make their voice heard on one of these venues. If any team members object to a course of action, we will not move forward without addressing those objections.

to:

> Members who have a specific interest in an issue (whether in approval or in dissent) are expected to make their voice heard on one of these venues. **[Sub-teams](https://github.com/programminghistorian/jekyll/wiki#project-structure) are empowered to make decisions on behalf of the project (with the exception of `policy` level changes, see below), but must do so in a sufficiently transparent way that if** any team members object to a course of action, we will not move forward without addressing those objections."

Pinging team leads: @mdlincoln @svmelton @rivaquiroga @spapastamkou @jenniferisasi @JMParr for comment.

**Comment by acrymble** [comment]
I support this. I suspect there are situations though where someone  may object but we may have a legal obligation or an extremely compelling practical reason for moving ahead anyway. Maybe j ust  say attempting to address those objections?

**Comment by drjwbaker** [comment]
> Members who have a specific interest in an issue (whether in approval or in dissent) are expected to make their voice heard on one of these venues. **[Sub-teams](https://github.com/programminghistorian/jekyll/wiki#project-structure) are empowered to make decisions on behalf of the project (with the exception of `policy` level changes, see below), but must do so in a sufficiently transparent way that if** any team members object to a course of action, we will not move forward without seeking to address those objections.

Better?

**Comment by drjwbaker** [comment]
@acrymble did this not get discussed at https://github.com/programminghistorian/jekyll/issues/1538?

**Comment by acrymble** [comment]
Sorry @drjwbaker it looks like we missed it somehow.

**Comment by svmelton** [comment]
No objections here!

**Comment by jenniferisasi** [comment]
No objections.

**Comment by amsichani** [comment]
no objections - thanks for this!

**Comment by drjwbaker** [comment]
I've made the edit to the [Governance Document](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance) adding the text above about sub-teams. Happy to reopen if anyone has an objection.
