### ISSUE TITLE
Anandi Retirement admin

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1545]
@alsalin has informed the team that she'll be retiring from the project. We wish her the very best and thank her for her contributions to the project. 

Once @svmelton has added herself as the Managing Editor (https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover) and we close #1473 we can begin working on our team member stepping down checklist.
 
https://github.com/programminghistorian/jekyll/wiki/Admin-when-team-members-step-down

**Comment by drjwbaker** [comment]
Thanks for your hard work @alsalin!

I confirm that there is no action to take wrt the ProgHist Ltd register of members.

**Comment by acrymble** [comment]
- [x] Remove Google Groups access (@acrymble)
- [x] Remove Google Analytics access (@acrymble)
- [x] Remove Github Jekyll access (@mdlincoln)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Change team: true to team: false, and add team_end: YYYY to the _data/ph_authors.yml file to remove the person from the Project Team page (@acrymble)
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@acrymble).
- [x] Remove Twitter access (@jenniferisasi)

**Comment by jenniferisasi** [comment]
@acrymble checking your list, a new item occurred to me that I need to take care of: Remove Twitter access, right?

**Comment by acrymble** [comment]
Yes.
