### ISSUE TITLE
New kanban board for managing editorial workflows

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1546]
I've put together a [kanban board](https://github.com/programminghistorian/jekyll/projects/3) for managing editorial workflows. Right now it's only for the English site, but I'd be happy to expand it to the other publications.

I'm posting it here for any general feedback. Are there any steps or checklists that should be added?

**Comment by mdlincoln** [comment]
I really like this! 👍 

Since this populated with the current English team pipeline, you might want to rename it so that it's clear it's just the EN PH kanban. I suspect - unless ppl think otherwise - that if the ES or FR teams want to also set up a kanban, then they should make separate boards so that things don't get too cluttered.

**Comment by jenniferisasi** [comment]
I really like this system @svmelton, thanks for adding it! 

And @mdlincoln you are right, of course, probably better to keep them separate. If Riva at some point wants to create one of this, shall she create a new project? I understand that "PH Submission & Publication Tracking" is your `project` and you have a `card` per task (grey box) then subtasks are a `column`?

**Comment by acrymble** [comment]
I suspect every team could  benefit from something similar. It might also help internal communication by giving each team a clear sense of what to pay attention to. #1491

**Comment by walshbr** [comment]
Love it! One question - is this something that you'll be updating and tracking as managing editor? That certainly seems the most likely to keep it up to date, but it does ask a lot more work of you @svmelton. The alternative would be asking people to check in and update as their card changes, but that seems more prone to letting it slide. I'm good with whatever you think makes sense and will support whatever you need.

**Comment by svmelton** [comment]
@walshbr Ideally editors should check in and update as their card changes, but ultimately I think it falls to the ME to make sure that things are moving through. I'll plan on reminding people for awhile until we're all used to it.

**Comment by rivaquiroga** [comment]
I really like this! It will definitely help with @programminghistorian/spanish-team internal communication to have one.

**Comment by spapastamkou** [comment]
All teams have now a kanban board each, so I think we are okay with this ticket.
