### ISSUE TITLE
October 2019 Board Actions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1549]
The following is a list of agreed actions arising out of the 2019 October board meeting. Please tick off your actions once completed. All actions should be complete or reportable by the next board meeting.

- [x] Who triages and discusses the needs to come up with solutions, and how do we prioritize to be most effective as a whole unit? 
Technical team to discuss and report next meeting. @amsichani @walshbr @mdlincoln 
- [ ] Working on next quarterly newsletter. @jenniferisasi 
- [ ] new research development manager plan. @jenniferisasi @drjwbaker 
- [x] Education manager plan @jenniferisasi @amsichani 
- [ ] Plan to work through stuck issues / old issues in the next month @svmelton 
- [x] French: 3 candidates applied to join the team, to be interviewed Nov 2019 -  @spapastamkou 
- [x] RQ in Chile during unrest, may need extra support. @jenniferisasi @JoshuaGOB contact @rivaquiroga 
- [x] Spanish team capacity query. A lot of long-term missing people. @acrymble to liase with @rivaquiroga 
- [x] Team leaders to decide together how to deal with internal communication to ensure their team memers are aware of relevant tickets. @mdlincoln @JMParr @drjwbaker @svmelton @spapastamkou @rivaquiroga @jenniferisasi

**Comment by walshbr** [comment]
Edited to add @mdlincoln to the conversation about the technical team.
