### ISSUE TITLE
Education Manager role | 1-6m plan

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1552]
Here is a draft plan for @amsichani as an Educational Manager - agreed with @jenniferisasi as Head of Communications Team.

**1-3 months**

- enhance users' experience 

_actions_ :
- [ ] address issues raised regarding lessons' duration #1526 and sequence (series) #1525 (December 2019)
- [ ] audience and Learning Paths  #1022 (December 2019)

**3-6 months**

- enhance & document the integration of its lessons into existing curricula 

_actions:_ 
- [ ] document & assess existing integrations (2018-) (March 2020)
- [ ] blogpost - invitation for integrations & ad-hoc translations (March 2020)

-  explore PH workshops as a service (aka as a potential funding stream / business model ) (April-June 2020). For this, I 'd ask ProgHist LTD directors @acrymble and @drjwbaker as well as @jenniferisasi as comms head to contribute in due course.

**Comment by acrymble** [comment]
Thanks for putting this together @amsichani . Do you have a place to store it while you work through it?

**Comment by amsichani** [comment]
I can close the ticket if needed and re-open it when necessary. I 've recorded my task also through private comm with @jenniferisasi (email).

**Comment by jenniferisasi** [comment]
Let's close this issue @amsichani since you are working on your tasks already in individual tickets.
