### ISSUE TITLE
Suggestion for printing in EN only

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1555]
I realized that the suggestion we added for a better printing at the end of the lessons is only available in English. The banner is in the `lesson.html` file. 

Do we need to create another {{ site.data.snippet.suggested-printing [page.lang] }} tag?

**Comment by mdlincoln** [comment]
I'm marking that I will be glad to take on the "support" role for this ticket. We're confirming now which @programminghistorian/technical-team member will take lead on writing the PR and will update with a timeline.

**Comment by mdlincoln** [comment]
Hey, I'm going to close this because the latest printing update now removes the suggested printing comment!
