### ISSUE TITLE
sudo pip install in intro to beautiful soup

### ISSUE THREAD

**Issue by IsaacVerm** [programminghistorian/jekyll#1557]
If you are reporting a problem with a lesson, please try to provide us with the following information:

- The full title of the lesson: [Intro to Beautiful Soup](https://programminghistorian.org/en/lessons/intro-to-beautiful-soup)
- The system you are using: not relevant
- Version numbers of the relevant software you are using: not relevant
- The exact steps you took that caused the problem: open the post

The issue I'm having is it seems quite dangerous to encourage running `pip install` as [sudo](https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice). It opens a can of worms of security risks.

**Comment by svmelton** [comment]
Pinging anyone from @programminghistorian/technical-team who may have thoughts here.

**Comment by walshbr** [comment]
Yep - this is a good point. @mdlincoln or @ZoeLeBlanc might have suggestions involving pipenv or something instead?

**Comment by ZoeLeBlanc** [comment]
Ya using sudo isn't great, but honestly we might want to include guidance on package management just because of the need to update dependencies. 

We could set up some guidelines that are lesson agnostic for package management. Maybe something about using conda, pipenv, or virtualenv for python, yarn and npm for node/js, and then something for R?

**Comment by acrymble** [comment]
I believe this is in other lessons too.

I admit not understanding why this is a bad idea in this specific context.

**Comment by walshbr** [comment]
The top comment here I think addresses it - https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice.

**Comment by svmelton** [comment]
Are there other thoughts on @ZoeLeBlanc's suggestion to set up guidelines for package management? It seems like a good suggestion to me. Is there anyone who could take this on?

**Comment by walshbr** [comment]
I think it's a good idea, but I don't have the expertise to do it. I mostly just know that the way I manage my Python installation is not a good practice. 😄

**Comment by svmelton** [comment]
The proposed solution brought forward during #1589 was to flag sudo if authors use it in future lessons, and encouraging users to open a ticket with PH if they have questions about using sudo.

**Comment by mdlincoln** [comment]
@svmelton anything need to change in our reviewer guidelines for this? Or can we close it?

**Comment by svmelton** [comment]
I think we can close this!
