### ISSUE TITLE
Resolving Decision-making workflow

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1558]
There seems to still be some different ideas about how decision-making should or does take place on the project. I thought we resolved this last meeting with the decision in the minutes:

> 10. Internal Communications #1491 * Agreed: Teams are empowered to get on with decisions within their remit, and raise issues for the group when they feel issues are substantive enough to need team input. 

It's important that we all have the same understanding of what this means.

My reading of this is that each team (English, Spanish, French, Tech, Development, Global, Communication) has areas of responsibility (eg the blog) where they are free to do their job without consulting the wider team, unless decisions may substantially affect the workings of other teams.  Other people may be consulted,  but there is no obligation to do so for minor things.

I will leave this space open for discussion of alternative interpretations of that agreement, so that we can move forward efficiently with project team work.

**Comment by drjwbaker** [comment]
@acrymble I opened a ticket on this https://github.com/programminghistorian/jekyll/issues/1543
