### ISSUE TITLE
Add "Support Us" banners/alerts across site

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1563]
Breaking this specific task out from #1554 since it needs to be tracked by @programminghistorian/technical-team 

To move forward, we'll first need a list of locations were we'd like the banner to appear. Getting a complete list first before we start coding it would be very useful, since it may affect how we structure template/includes inheritance - and it may also affect the exact length/wording of the messages the development team settles on so that they display nicely. Once we have a decision on locations, the tech team can draft a PR for review while the development team finalizes and translates wording.

Current proposals:

1. Support Us alert box at the bottom of each lesson page, above the "about the authors" info
2. An alert box on the landing pages https://programminghistorian.org/en/
3. (possible?) Sitewide banner underneath the navigation bar?

Another decision we need to move forward: FYI we could configure any one of these options to be connected to a "switch" that we could flip on and off - for example, the sitewide banner might be something we turn on periodically, whereas we might _always_ have alert boxes showing up on the lessons.

**Comment by mdlincoln** [comment]
Reminder to @programminghistorian/project-team to please make a decision on locations so that tech team can start work.

**Comment by acrymble** [comment]
I would go for 1 and 3 with the switch for 3 if possible.

**Comment by mdlincoln** [comment]
@acrymble What's the code we need to embed the Patron button?

**Comment by acrymble** [comment]
<a href="https://www.patreon.com/bePatron?u=11816614" data-patreon-widget-type="become-patron-button">Become a Patron!</a><script async src="https://c6.patreon.com/becomePatronButton.bundle.js"></script>

**Comment by mdlincoln** [comment]
hmm. I'm very unhappy with the amount of javascript they want to inject into our site - it's truly enormous, and will slow down load times for folks on slow connections, and perhaps also add a lot of tracking cookies to our visitors' computers.

I can't access their technical documentation without having an account, but if they have an option for displaying a simple image without using their javascript, I would much prefer that. If not, I'd advise that we just use simple links to the Patreon page(s) that we run.

**Comment by acrymble** [comment]
we can just screenshot and trim the button and add it ourselves.
