### ISSUE TITLE
November 2019 Project Team Meeting Actions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1564]
The following is a list of agreed actions arising out of the 2019 November project board meeting. Please tick off your actions once completed. All actions should be complete or reportable within  30 days.

Carried forward from October 2019:

- [x]  Plan to work through stuck issues / old EN team issues in the next month @svmelton

New: 
- [x] ALL: find out if your institution could offer us free DOIs and report to @mdlincoln .
- [x] liase w. technical team on education manager plan. @amsichani 
- [x] produce plan for promoting PH at conferences. @jenniferisasi 
- [x] liase w @drjwbaker  and @acrymble  re patreon multilingual integration. @jenniferisasi 
- [x] follow up with Amical, GLobal DH, and RED_HD  @JMParr 
- [x] follow up with potential Portuguese partners. @JMParr @svmelton 
- [ ] EN team to decide on sudo in lessons issue #1557 @svmelton 
- [x] EN team to decide on how to decide on lesson proposals when consensus not reached. @svmelton 
- [x] EN team decide who is responsible for unsolicited lesson updates. @svmelton 
- [x] open onboarding process for new team members.  @spapastamkou 
- [x] liase w. @mariajoafana  about reintegrating after sabbatical @rivaquiroga 
- [x] follow up with Bogota lessons @rivaquiroga 
- [x] follow up with VG re ombudsperson role. @acrymble

**Comment by acrymble** [comment]
A reminder to @amsichani @jenniferisasi @JMParr @svmelton @spapastamkou and @rivaquiroga that you have pending actions still on this ticket before the next meeting in a few weeks

**Comment by JMParr** [comment]
Hi, @acrymble - I will take care of these things before our next meeting. Thanks for the reminder.

**Comment by acrymble** [comment]
@svmelton has referred to the only outstanding action in her report for this month, which she intends to carry forward. Therefore, I will close this ticket as all actions have been completed. Thanks everyone.
