### ISSUE TITLE
Twitter bot advertising a retired lesson

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/jekyll#1569]
Sorry if this is not the appropriate forum to raise this issue, but I just noticed that the Twitter bot has advertised @mdlincoln's "Learn to use SPARQL to work with Linked Open Data" lesson, which is marked as retired in the text.

Is this an issue for the technical team or the communications team? @jenniferisasi ?

**Comment by mdlincoln** [comment]
I saw that, deleted the tweet, and then deleted the record in the Twitter bot google sheet that was causing it to still be advertised. Removing that row from the sheet was a step in the lesson retirement protocol that we overlooked.
