### ISSUE TITLE
Large Assets and GitHub

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1570]
I was emailing with @svmelton and @mdlincoln about an editorial issue on the English team, and it seemed like something to raise to the group here for comment. An upcoming lesson in the pipeline has an asset - a CSV file - that is necessary for the analysis, but the asset is large. It's about 130 megabytes, and GitHub is complaining when they try to upload it. The question is what to do with such things. 

@mdlincoln had good thoughts - that the best solution would be to make sure that datasets or assets like this go into a scholarly repository so they have a persistent link. He suggested using Zenodo, since we already use that for archiving the project. Either the author or the lesson editor could upload to it, and then we link to the DOI that is generated. Posting here for thoughts.

**Comment by jenniferisasi** [comment]
I'm pinning @JoshuaGOB as the lesson he has submitted for ImagePlot use also has this issue.

**Comment by JoshuaGOB** [comment]
I was considering doing the same with the institutional repository here and now I've been asked to do so by the person in charge of the collection. I'm not very informed on the licenses but the CC0 they have by default is apparently the least restrictive possible. They also provide a DOI. 

Just thinking out loud: would we want to upload to multiple repos when there's an institutional requirement to deposit into a particular one and should there be a standard or list of acceptable licenses for those datasets/assets?

**Comment by mdlincoln** [comment]
If the data are already in (or will be deposited) into an author's institutional repository, then I think we should be happy to link to that, provided that the data can be freely downloaded without needing to log in or have a certain IP location, and that there's a reasonable guarantee that the repository is stable.

For any datasets that are being created expressly for the Programming Historian lesson and that aren't otherwise in a repository, I'd suggest we point authors towards Zenodo by default, since it's a known entity.

**Comment by acrymble** [comment]
I wouldn't trust institutions to indefinitely keep items for former students or employees.  For sustainability reasons I would suggest zenodo. It's a similar principle to why we ask for everything to be put on our servers. I've had many items of my own deleted from former employers when it no longer served their active needs, and they never asked me about it.

**Comment by walshbr** [comment]
@mdlincoln would it make sense to ask author's to copy their datasets into Zenodo even if those datasets are already in an institutional repository? For redundancy/sustainability?

**Comment by mdlincoln** [comment]
Note that we're talking about institutional repositories, not university/department/faculty websites. IRs do have an expectation of permanence, the others do not.

Having it all in Zenodo certainly helps keep it standardized on our end.

**Comment by walshbr** [comment]
In that case, how about the following as a policy for the wiki?

> Occasionally, large assets used by particular lessons might be too large to be stored in our GitHub repository. If this is the case, we recommend that authors upload their asset to Zenodo for archiving and then provide the lesson editor with the DOI generated by Zenodo for linking from within the lesson. In the event that such datasets might already exist in an institutional repository, we still recommend uploading the version of the dataset used in The Programming Historian to Zenodo for the purposes of consistent use across all of our lessons.

I'm inclined to say that a larger conversation about licensing for assets might be worth another ticket discussion if it comes up enough rather than trying to solve that topic here. But, for what it's worth, in keeping with our general philosophy of open culture work I'd be inclined to lean more towards least restrictive.

**Comment by mdlincoln** [comment]
I like that text!

**Comment by amsichani** [comment]
Zenodo also came up as a solution on the [Working with batches of PDF files](https://github.com/programminghistorian/ph-submissions/issues/258) lesson  - its worth keeping an eye there.

**Comment by JoshuaGOB** [comment]
﻿
I really like that text and the strategy to have redundancy in Zenodo. My IR runs as part of the entire system of state universities but we were just informed that due to funding issues they are exploring subscription and third-party hosting solutions. It’s not clear what the effects of that will be in the long run. 

I’m also curious, @rivaquiroga, if our team should be contributing to repos like CLACSO.

**Comment by mdlincoln** [comment]
@walshbr is this a thing for the wiki, or for the editor guidelines? I'm thinking the latter, since it's about lesson production... could you start a PR for that?

**Comment by drjwbaker** [comment]
I agree.

**Comment by walshbr** [comment]
I was trying to give it until today so that folks could render alternative opinions if they had thoughts. Seeing none, sure thing. I had thought wiki but since you're the tech boss I can do a PR for the lesson guidelines. Will add it to my task list.

**Comment by drjwbaker** [comment]
Note: if we ever hit the 2GB file size limit on Zenodo, let me know - my Lab is willing to support hosting large files if we need it.

**Comment by mdlincoln** [comment]
Good to note, however I'd say if a lesson required a 2GB download (or even a 100MB download!) that should raise lots of eyebrows during the review phase, not least of which from an accessibility standpoint (internet bandwidth, storage, processing power it'd demand from readers)

**Comment by drjwbaker** [comment]
Agreed. But if we get a lesson with lots of large audio-visual assets, it might happen :)
