### ISSUE TITLE
Broken EN-ES-FR link on "Reviewer Guidelines"

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1573]
I found an error in the three languages link in "reviewer guidelines", EN to ES and back it works, but the FR link is not connected to them. 
https://programminghistorian.org/en/reviewer-guidelines
https://programminghistorian.org/fr/consignes-evaluateurs

Will look into it, probably something spelled wrong on snippets or the liquid (?) build tags

**Comment by mdlincoln** [comment]
I'm not at my computer to check it, but see if the `original` YAML value is correct on the FR page?

**Comment by jenniferisasi** [comment]
No it is not, actually no `original` value there. Thanks Matt! Will do the change now.

**Comment by jenniferisasi** [comment]
Fixed.
