### ISSUE TITLE
Content addition proposal

### ISSUE THREAD

**Issue by Bundi-py** [programminghistorian/jekyll#1575]
Greetings,
I just finished reading the lesson
**[Working with Text Files in Python]**
"https://programminghistorian.org/en/lessons/working-with-text-files"
which is a nice intro for non-technical people like me. Thank you for posting that, But I also have a proposal to expand a little bit the content of the lesson.  by adding example of appending a text file to a pre-existing text file and not only a string. Practically merging two files, which is more real scenario than adding just a string to the file,

Good luck with your project!

**Comment by svmelton** [comment]
Thanks for this note!

Since @acrymble worked on this lesson, I'll let him weigh in on any potential expansion. (And if he has the capacity to work on it!)

**Comment by acrymble** [comment]
The lesson does provide these skills, if not that specific example. You can save the content of one file to a string, and then append it to another file. All of the bits of that workflow are already in the lesson.

**Comment by svmelton** [comment]
Thanks, @acrymble. I'm going to close this issue for now.
