### ISSUE TITLE
Victor Retirement and Offboarding

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1576]
This is the checklist for offboarding members of the  project who are stepping down. In  this  case, @vgayolrs :

- [x] Remove Google Groups access (@acrymble)
- [ ] Remove Google Analytics access (@acrymble)
- [ ] Remove Github Jekyll access (@mdlincoln)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker) (not applicable)
- [ ] Remove Twitter access (@jenniferisasi)
- [ ] Change team: true to team: false, and add team_end: YYYY to the _data/ph_authors.yml file to remove the person from the Project Team page (@acrymble)
- [ ] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@acrymble).
- [ ] If they hold any other team roles, inform @acrymble that a replacement is needed.

**Comment by vgayolrs** [comment]
???

**Comment by rivaquiroga** [comment]
@vgayolrs, @acrymble has been trying to contact you in his role as Team Development Manager. Did you manage to check his emails? We haven't heard from you in a while.

**Comment by acrymble** [comment]
Yes @vgayolrs please get in touch if you think there's been miscommunication. We tried to contact you many times through private channels.

**Comment by acrymble** [comment]
Let's put this process on pause for a week while we wait to hear from @vgayolrs. As it seems he may not have been receiving emails.

**Comment by jenniferisasi** [comment]
Oh, if @mdlincoln did the 
> Remove Github Jekyll access (@mdlincoln)

Would @vgayolrs receive your comment from three days ago @acrymble?

**Comment by acrymble** [comment]
If he has his alerts set up, it shouldn't make a difference. If he isn't checking his email, then no.

**Comment by jenniferisasi** [comment]
Ok! Wanted to make sure it works that way. I'm sending you an email too @acrymble

**Comment by acrymble** [comment]
We've got confirmation of an email problem, so we're awaiting to hear from Victor as he works to fix this.

**Comment by vgayolrs** [comment]
Hi. I've email @rivaquiroga and she assigned me https://github.com/programminghistorian/ph-submissions/issues/163 to complete the translation edition. However, I do not have permission to modify the translation. can you help, @mdlincoln ?

**Comment by rivaquiroga** [comment]
@mdlincoln, can you add again @vgayolrs to the team? He is back :rocket: He was trying to work in one of the tickets, but he can no longer edit the repositories.

**Comment by jenniferisasi** [comment]
@rivaquiroga @mdlincoln I just invited @vgayolrs back to the ph-submissions repo.

**Comment by mdlincoln** [comment]
done! sorry for the delay. Are there any other tasks that need to be done before we can close this?

**Comment by acrymble** [comment]
Yes I just need @vgayolrs to send me his current Google email so I can add it to the google group.

**Comment by acrymble** [comment]
I've heard from @vgayolrs and he's sent me his email address. This is now closed. Thanks everyone.
