### ISSUE TITLE
Project Team page - foregrounding 'work' vs 'volunteer' labour

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1581]
This is a suggestion for discussion.

We have a number of team members who are paid through their employer and given some time to work on Programming Historian. We also have a number who do not have this arrangement in place. In order to A) encourage employers to do this, and B) to highlight the different pressures the team face, I propose adding a snippet on the Project Pages recognising this "work" when it is sponsored.

For example: James Baker is a Senior Lecturer in Digital History and Archives at the University of Sussex and a historian of interactions between people and things. James receives time from the University of Sussex to contribute to Programming Historian, for which we are grateful.

Are there any unforseen consequences of this openness?

**Comment by drjwbaker** [comment]
Thanks for starting this conversation Adam. I'm broadly supportive of acknowledging in-kind where we think it exists. But I also think we need to be subtle here and not create either/or binaries. In my case, I have some freedom over my work programme and I choose to spend 'work' time on PH and this is broadly supported, but it isn't in my official work allocation (like it may be for some of the team), and a change in management/leadership/direction/workload could derail my ability to be involved. At the moment I think my employer would see it as a good thing that their contribution was recognised in some way, but I can envisage a situation in which anything too formal would be questioned. Does that make sense?

**Comment by acrymble** [comment]
Alternative suggestion: A tag (not sure what, paid, work, something) that uses the 'role' system to highlight who is paid either directly, or has the flexibility in their job to work on PH activities?

**Comment by drjwbaker** [comment]
I prefere that. Though also not sure what to call it. Also reduces translation burden.

**Comment by acrymble** [comment]
Maybe:

Supported - This member's time on the project is either directly or indirectly supported by their employer.
Voluntary - This member's time on the project is wholly voluntary.

?

**Comment by drjwbaker** [comment]
I like 'Supported'. Vague enough to fit with my status.

**Comment by mdlincoln** [comment]
I'll second @drjwbaker - while CMU is happy for me to spend time on the project, it's from my ~20% time allocated to research projects of my choosing, so work on PH happens in place of other projects I could be interested in working on. Very different relationship than if PH were a paying client that was contracting my services.

**Comment by mdlincoln** [comment]
I'd go so far as to make the label "institutionally supported"

**Comment by walshbr** [comment]
Same - PH is drawing time from my 20% R&D time that I can use for research of my choosing at UVA. So the suggestions from @mdlincoln and @drjwbaker also fit my situation.

**Comment by drjwbaker** [comment]
> I'd go so far as to make the label "institutionally supported"

That would work for me. I have, after all, been able to draw on internal funds, even if my time commitment is not fixed/allocated.

**Comment by jenniferisasi** [comment]
> I'd go so far as to make the label "institutionally supported"

I like the wording too. I have been using part of my 20% research time provided by default by my postdoctoral fellowship and I would like to recognize that support. It will change within the next few months, but I am going to try my best to negotiate time for PH in my next position.

**Comment by acrymble** [comment]
I'll move forward with this, including collecting the relevant information from all current team members.

**Comment by acrymble** [comment]
Members by category (Institutionally Supported & Volunteer)

Please help me fill this in.

- @mariajoafana 
- @drjwbaker - Institutionally supported 
- @acrymble - volunteer
- @vgayolrs - volunteer
- @grandjeanmartin 
- @jenniferisasi - Institutionally supported 
- @fdlaramee - Institutionally supported
- @ZoeLeBlanc
- @mdlincoln  - Institutionally supported 
- @svmelton - volunteer
- @jamotilla 
- @JoshuaGOB - volunteer
- @spapastamkou - volunteer 
- @JMParr - volunteer
- @rivaquiroga - volunteer
- @arojascastro 
- @amsichani 
- @walshbr - Institutionally supported

**Comment by JMParr** [comment]
I'd be a volunteer

**Comment by acrymble** [comment]
Proposed Language:

EN

Institutionally Supported - This member's time on the project is either directly or indirectly supported by their employer.
Voluntary - This member's time on the project is wholly voluntary.

---
ES: [@jenniferisasi 's edits]

Patrocinado por su institución - El tiempo que este miembro dedica al proyecto está directa o indirectamente patrocinado por su institución
Voluntario - El tiempo que este miembro dedica al proyecto es voluntario

--

FR: 

PLEASE HELP @spapastamkou @grandjeanmartin or @fdlaramee

**Comment by jenniferisasi** [comment]
I am not entirely happy with "Patrocinado por su institución" so @arojascastro @JoshuaGOB @rivaquiroga do you like it or prefer "Apoyado por su institución" o "Apoyado institucionalmente"?

**Comment by fdlaramee** [comment]
FR:

Soutenu institutionnellement - Le temps que ce membre consacre au projet est directement ou indirectement financé par son employeur.
Bénévole - Ce membre contribue son temps sur une base entièrement bénévole.

**Comment by arojascastro** [comment]
*Apoyado* sounds better in Spanish... *patrocinado* is a little too commercial or sounds business to me.

**Comment by acrymble** [comment]
Once I hear from the following people I can finish the pull request:

@arojascastro - volunteer
@amsichani - volunteer
@jamotilla - volunteer
@ZoeLeBlanc
@mariajoafana

**Comment by arojascastro** [comment]
volunteer! Thanks.

**Comment by amsichani** [comment]
volunteer - thanks!

**Comment by acrymble** [comment]
I will wait until the end of the week to hear from @jamotilla @ZoeLeBlanc and @mariajoafana and then I will post this as is.

**Comment by jamotilla** [comment]
Hi, volunteer 

thanks
