### ISSUE TITLE
Wrong link in SPARQL lesson?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#159]
@mdlincoln we've just had a correction that the Paul Mellon Center for British Art listed in your lesson should be the Yale Center for British Art. Can you double check that for me?

**Comment by mdlincoln** [comment]
Oh dear, yes: the link is correct, but the link text ought to read the "Yale Center for British Art"

**Comment by fredgibbs** [comment]
closed by eb3af1101cea9ee824dd2bef81143279ad629d9f
