### ISSUE TITLE
ProgHist Ltd Board of Directors Meeting 13 February 2020 

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1594]
## ProgHist Ltd Board of Directors Meeting 13 February 2020

**Time: 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET**

Chair: @acrymble
Secretary: @drjwbaker 
Members: @amsichani @spapastamkou @drjwbaker @svmelton @rivaquiroga 
Minutes of the last meeting: these are not posted publicly. Please see your email from @drjwbaker 12 December 2019.

### Agenda

1. Apologies  
2. Approval of Minutes from last meeting & actions status   
3. ProgHist Directors administration (e.g changes of address)
4. Finance update @drjwbaker
5. Institutional Partner Programme #1625 @drjwbaker 
6. Approval of Business Plan
7. Any Other Business 
8. Agree date of next meeting

**PLEASE SUGGEST AGENDA ITEMS IN THE TICKET FOR INCLUSION**
Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))

**Comment by drjwbaker** [comment]
@acrymble @amsichani @spapastamkou @drjwbaker @svmelton @rivaquiroga: I polite reminder about this meeting on 13 Feb. Managing Editors: you are unable to make it, please consider nominating a representative from your team.

**Comment by amsichani** [comment]
I am afraid I can't make it tomorrow - an urgent family commitment. Looking forward to the minutes. Sorry for any inconvenience.

**Comment by drjwbaker** [comment]
@acrymble @spapastamkou @drjwbaker @svmelton @rivaquiroga: who is coming? We need 3 to make quorum.

**Comment by acrymble** [comment]
I will be. Best wishes @amsichani

**Comment by rivaquiroga** [comment]
I'll be there. 
@amsichani, hope everything is fine

**Comment by svmelton** [comment]
I’ll be there, as well.

**Comment by drjwbaker** [comment]
Fab. We have quorum. Speak tomorrow.

**Comment by drjwbaker** [comment]
Minutes circulated

**Comment by drjwbaker** [comment]
Closed as minutes sent to Members.
