### ISSUE TITLE
Research Leave (Feb-June 2020) and proposal to step down as EN Editor

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1598]
All. I have Research Leave coming up (1 Feb - 30 June 2020) which will impact on my work for the Programming Historian. Whilst I won't be disappearing into archives and deleting all email (I still have funded research projects to run and contribute to, so 'leave' isn't really going to happen in my case!), research leave does mean I am required by my Department to scale back on my admin roles in order to complete the tasks I said I would complete during this period (starting a book, hopefully..).

That said, I don't wish to take a full Sabbatical https://github.com/programminghistorian/jekyll/wiki/Checklist-for-Sabbaticals as there are exciting things in the works that I want to continue to develop, contribute to, and manage (e.g. https://github.com/programminghistorian/jekyll/issues/1489)

With that in mind, I propose that I resign - rather than take sabbatical - from being on the English Editorial Team (but stay as Archivist, Finance and Sponsorship Manager, and on the Editorial Board, as well as Directorship of the Ltd). In reality, I haven't recently been stepping up for this anyway as most of my PH time has been dedicated to the Team Dev part of my role, so I guess this is recognition that I'd like this to be formalised. @svmelton: I think this directly affects you the most as it reduces editorial capacity and potentially means we need to look for new EN editors. @acrymble: with your Team Dev Lead hat on, any thoughts on this proposal?

**Comment by svmelton** [comment]
Hi @drjwbaker—thanks for bringing this up, and congrats on the research leave! I'm in strong support of recruiting new EN editors; we're in need of some more editorial capacity.

**Comment by acrymble** [comment]
@svmelton let's set a meeting to discuss recruitment for EN. Email me when you're back and we can set a date.

**Comment by drjwbaker** [comment]
Thanks for your kindness folks.

**Comment by acrymble** [comment]
Thanks @drjwbaker I've been in touch with @svmelton so we will take this forward.
