### ISSUE TITLE
New PR template to help out editors?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1600]
Right now we have a [PR template](https://github.com/programminghistorian/jekyll/blob/gh-pages/.github/PULL_REQUEST_TEMPLATE.md) that is addressed to external users who occasionally try to submit PRs directly for our lessons. It's the text that is automatically put into any new pull request.

I'm wondering if it would be more useful to rewrite this template so that it's useful for _us team members_, and provides a checklist that every PR (whether for a new lesson or a blog post or a small content change) should pass before it's ready to submit. 

The template could include a spot at the top to describe the change, and then include a footer section with a generic checklist that could include reminders:

- on how to open up the Travis check results
- to check how the page looks on the Netlify preview
- to assign at least one reviewer (either individual or team)
    - if changing a page with translations, reminder to add all appropriate language teams as reivewers
- to assign self as "assignee" responsible for the PR
- to add an appropriate label

Do we think this makes sense? Are there any other tasks we need?

**Comment by jenniferisasi** [comment]
I think it makes sense and could be really useful. I would maybe add a note at the end of who to contact in case you get stuck with errors?

**Comment by drjwbaker** [comment]
Great idea @mdlincoln. I suggest that we should point to the note on the wiki about how to request translation https://github.com/programminghistorian/jekyll/wiki/Requesting-Translation-Guidelines (agreed at #1458)

**Comment by mdlincoln** [comment]
Agreed @drjwbaker I've added that to the PR. I have also updated the wiki to include a few pointers on certain Travis errors that have hard-to-understand error messages (they're ones written by Jekyll so I don't have control over what they say).
