### ISSUE TITLE
Copyediting Trial

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1610]
I have an experienced copyeditor who can copyedit the next English lesson, and also to provide feedback on the styleguide, and our copyediting workflows, to make sure it's sufficient and efficient. @svmelton can you let me know when we've got a lesson that we can put through copyediting?

**Comment by svmelton** [comment]
Hi @acrymble—we've actually got a lesson that could be put through copyediting now: https://github.com/programminghistorian/ph-submissions/issues/258

**Comment by acrymble** [comment]
Great. I'll get a quote and speak to @drjwbaker for approval for the test.

**Comment by drjwbaker** [comment]
If by 'approval' you mean financial, it is within scope of what we'd said we'd do with the funds, so no problem there. The question is if we have the funds. Email me.

**Comment by acrymble** [comment]
@svmelton can you please manage the expectations of the authors while we set this up? I will let you know a timeline asap

**Comment by acrymble** [comment]
Timeline update. I've been in contact and I've sent the quote to @drjwbaker to make sure we can afford to proceed. It's the weekend so I don't expect to hear from him today, but I wanted to keep @svmelton up to date.

**Comment by acrymble** [comment]
This is now with the copyeditor.

**Comment by acrymble** [comment]
Our first copyediting trial has now been conducted. The editor made a couple of comments on our process which are useful for us to consider.

1) That it would be a good idea to use repeat copyeditors who can become familiar with our publication, audience, and style. This has $ savings implications in the longterm, but also quality implications for the work
2) That our markdown format isn't really conducive to copyediting. She made a PDF and added comments to it instead, which I actually think works fine.

If anyone who has been involved (@amsichani or @svmelton) wants to comment, please do. I hope the process has felt smooth.

**Comment by drjwbaker** [comment]
@acrymble Small note on process: can you make sure we are billed via the shared gmail box (rather than my person email). I monitor that, so I will be sure to pick it up.

**Comment by acrymble** [comment]
@drjwbaker added that to the wiki. Thanks.

**Comment by svmelton** [comment]
From my perspective, it ran pretty smoothly! The point about our markdown is one that I've heard before, but I think it's fine for copyediting to happen outside of GH.

If we plan to keep copyediting (and I hope we can!) we should add a bit about the process to our editorial documentation.

**Comment by acrymble** [comment]
Thanks. I'm going to close this now that both have commented (here and on the ticket)
