### ISSUE TITLE
paginate blog

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1616]
Our blog page has never had pagination. It just lists every post for all time in one big page. This didn't matter much when we had a dozen posts but it's perhaps reaching an unweildy size right now, particularly because it asks users to load quite a lot of images in one request.

Jekyll has built-in pagination, I believe this should be a minor configuration change. Will set aside some time to assess with @programminghistorian/technical-team

**Comment by jenniferisasi** [comment]
This would be perfect @mdlincoln, I was starting to worry about it.
