### ISSUE TITLE
Patreon suggested new topics

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1619]
Patreon supporters pledging $5+ per month have the option of suggesting a new lesson topic they'd like to see, which we'll post on the website. I wanted to open this ticket to make sure we follow through with that. I believe @drjwbaker agreed to do this, but if I'm remembering wrong let me know.

**Comment by drjwbaker** [comment]
@amsichani Agreed to do this as Education Lead (though I can't find the ticket in which we agreed this right now..)

**Comment by acrymble** [comment]
@amsichani can you let us know if you're still happy to take this on? Otherwise we'll have to redistribute the task to someone with some more time.

**Comment by acrymble** [comment]
@amsichani shall I get someone else to take this on?

**Comment by acrymble** [comment]
@amsichani I'm going to take your silence as a sign that you're too busy for this. I will take on this task for existing sponsors and @drjwbaker and I will have to discuss who should do it moving forward. @amsichani can you please confirm you're still receiving notifications to Github?

**Comment by drjwbaker** [comment]
@acrymble Happy to help until we find someone to take it on.

**Comment by acrymble** [comment]
It looks like we can set this up in Patreon to send emails automatically to eligible people. Looking into it now @drjwbaker

**Comment by drjwbaker** [comment]
Okay. My question is whether we want to ask for ideas only when a $5+ person joins, or whether we want to ask all $5+ people every 6/12 months. The latter is probably better for longer term community engagement.

**Comment by acrymble** [comment]
Good question. I've sent out an initial email to the eligible people through Patreon. Let's see what the response rate is to decide if we want to ask more than once. I'll close this for now, and will report to you when I hear more @drjwbaker

**Comment by drjwbaker** [comment]
Thanks Adam. There is a note about this on the wiki https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#patreon that might need updating.

**Comment by acrymble** [comment]
@drjwbaker done, thanks
