### ISSUE TITLE
Reordering Project Team page

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1621]
I'm happy to take on this task, but I wanted to get feedback first.

The project team page is a very long list. Thinking about how people might want to use this, I suspect it makes more sense to order it by publication, with a separate section for the non-editorial people. So four sections instead of one.

Eg:

English Publication
- person
- person
- person

Spanish Publication 
- person
- person

French Publication
- person
- person

ProgHist Ltd
- person 
- person

With everything else, such as tags and descriptions, as they currently are.

I think this makes it easier both internally and externally for people to understand our structure and who they might need to contact for various activities. I won't make this change unless it has support. So let me know.

**Comment by mdlincoln** [comment]
Yeah, the team page could do with a bit of reordering. I'm not sure the language subdivisions make total sense though - there are PH Ltd people who are still in the language teams, yes? And I've stepped down really from the English editorial board, so where do I go?

Another feature to consider might be adding a small table of contents to the top of the page so folks know what they'll find if they scroll down.

**Comment by acrymble** [comment]
@mdlincoln yes some people may appear more than once in what I've proposed. I think that's ok. I see what we've become as a publisher that publishes 3 publications. I think that's how an outsider would understand us. I'm not sure everyone on the team sees it that way though. The groupings under what I've proposed would look like this (I think):

English
- Sarah Melton
- Zoe LeBlanc
- Anna Maria Sichani
- Brandon Walsh

Spanish
- Riva Quiroga
- Maria José Afanador Llach
- Victor Gayol
- Jennifer Isasi
- José Antonio Motilla
- Joshua G Ortiz Baco
- Antonio Rojas Castro

French
- Sofia Papastamkou
- Martin Grandjean
- François Dominic Laramée 
- Marie Christine Boucher
- Maëlle Amand

ProgHist Ltd
- Matt Lincoln
- Jennifer Isasi
- Sofia Papastamkou
- Anna-Maria Sichani
- Brandon Walsh
- Jessica Parr
- Adam Crymble
- Riva Quiroga
- James Baker

**Comment by jenniferisasi** [comment]
Might be out of scope - and, please @mdlincoln feel free to ignore my suggestion if it involves more than a few easy changes that the junior technical members of the techteam could help you with - but how about using the `teamrole` tag to filter "teams" like we do with `topics` for the lessons? So we leave the list of the editorial board as is, but above it we have all the `teamrole` tags clickable to filter out who is on the Spanish editorial team or who is Institutionally supported. 
Is that too crazy? Again, if so, please ignore.

**Comment by mdlincoln** [comment]
That filtering involves a bunch of custom javascript written just for the lesson pages - you can take a look but I'm not sure how easy it'd be to revise to work for this.

**Comment by jenniferisasi** [comment]
> That filtering involves a bunch of custom javascript written just for the lesson pages - you can take a look but I'm not sure how easy it'd be to revise to work for this.

**javascript**! that is why I couldn't find the code in the first place... I can't read .js yet. 
Ignore my idea.

**Comment by acrymble** [comment]
I managed to create a preview:

https://deploy-preview-1637--ph-preview.netlify.com/en/project-team
https://deploy-preview-1637--ph-preview.netlify.com/es/equipo-de-proyecto
https://deploy-preview-1637--ph-preview.netlify.com/fr/equipe-projet

I think it could use some css styling to visually differentiate the different groupings a bit, but I think it's useful. Other views?

**Comment by jenniferisasi** [comment]
Can we add a simple "table of contents" of shorts above? I feel that at this point this page is so long that the user deserves a way to jump directly to a group if they want to. Would it be too much?

**Comment by acrymble** [comment]
This has been merged. Thanks everyone.
