### ISSUE TITLE
Advertising trial (consentual only)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1622]
I know advertising isn't popular, but I wanted to raise it again as something I think we should test in a limited way. In particular, on lessons that receive more than 100,000 visitors per year, and for which we have the explicit permission of authors.

I think this has value for a couple of reason. Firstly, those few lessons (there are only 7) are obviously being used widely and not just by historians/humanists. But those users are extremely unlikely to donate to us via Patreon. Advertising could help us bring in a little bit of money to cover the cost of future development. It's obvious now that donations won't be enough to let us grow in the ways we envision.

Secondly, I've written a couple of these, as they're in the original Python series. So I can give permission.

I've also looked briefly into Google alternatives, and there's a tech-focused one that claims to have high ethical standards called CodeFund, which is designed to help people like us support our development work: https://codefund.io/

I'd like permission from the team to try this on an English-language lesson I've written, for a period of 3-6 months, and then report back to decide if we want to pursue it further.

**Comment by mdlincoln** [comment]
I'd actually be ok with ads as long as:

1. you do get the permission of the authors
2. we integrate them with our strategy for getting donations. Display the ads along with donation banners etc.
    - FYI we don't have a way to hide ads for those users who are patreon donors, because we're just a static site
3. The ad providers are not planting tracking cookies. I see codefund has some vague promises to this on their homepage but I couldn't actually find a document on there that really spelled out what they meant by that committment?
4. Even if these start on English lessons, please research if they have advertisers who publish in other languages
5. Most important - who are their advertisers? It would take just one advertisement for e.g. Palantir showing up on our pages to (correctly) kill the trust of our audiences. I think this may be the most difficult one to get a guarantee on.

**Comment by acrymble** [comment]
Thanks for those. I didn't think of 4. I will look into it and the other issues you raise.

**Comment by acrymble** [comment]
I have an old Google Adsense account with $65 sitting in it. It's never reached the minimum $100 payment threshold so I've never seen any of the money. I'm happy to donate it to the project if we use that account to reach $100 and then close it down and use another service. But @mdlincoln that may be a non-starter if you're worried about privacy and cookies. Let me know.

**Comment by acrymble** [comment]
I don't have the time to do further research on this right now so will close (and may reopen in future).
