### ISSUE TITLE
Institutional Partner Programme

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1625]
Further to me recent email to the group, and building on the work on donation mechanisms https://github.com/programminghistorian/jekyll/issues/1457 it has come to the attention of the @programminghistorian/development-team that we need some clear messaging and pricing for institutions (especially libraries) who would like to financially support our work. In short, there is interest in paying us an annual amount if we have a scheme for such a thing.

@acrymble & I propose therefore adding to the "[Support Us](https://programminghistorian.org/en/support-us)" page a section on something we are calling an *Institutional Partner Programme*. This is modelled on similar initiatives run by similar projects (e.g. [OLH](https://www.openlibhums.org/plugins/supporters/signup/), [DOAJ](https://doaj.org/membership), and [DOAB](https://www.doabooks.org/doab?func=loadTemplate&template=supportDOAB&uiLanguage=en)).

We invite comment. We propose (based on the sub-team powers detailed at https://github.com/programminghistorian/jekyll/issues/1543#issuecomment-555384006) to discuss this with the Editorial Board at https://github.com/programminghistorian/jekyll/issues/1589 and implement shortly thereafter.

Proposed text below.

-----

The Programming Historian Institutional Partner Programme enables your library, university, or research centre to support the growth, development, and sustainability of our award winning open access publishing platform.

By joining the Institutional Partner Programme you will receive the following benefits:

- An invitation to our ProgHist Ltd Annual General Meeting as an Advisory Member (one individual per Library Partner).
- An annual breakdown of ProgHist Ltd expenditure.
- Acknowledgement of your contribution on our 'Supporters' page.
- The right to use Programming Historian Library Partner Programme membership in marketing activities.
- For library partners: a list of articles published by all Programming Historian journals (on request).

Partnership rates for 2020 are set at £1,000 GBP ($1,300 USD / €1,100 EUR) and £150 ($195 USD / €165 EUR) for partners in [ODA eligible countries](http://www.oecd.org/dac/financing-sustainable-development/development-finance-standards/daclist.htm). Rates are due annually from the date of first payment. Rates are published in January each year.

To become a Institutional Partner, please email James Baker at programminghistorian@gmail.com with "Institutional Partners Programme" in the subject line. Your email should include the following information:

- Your Name.
- Your Institution.
- Your Preferred Method of Payment (bank transfer, cheque, invoice, Paypal).
- Your Preferred Currency (if this is not listed, please ask).

Note that upon email with the subject line "Institutional Partners Programme" you agree to the following conditions:

1. You are authorized to commit to expenditure of the institution whose name you use.
2. Once a method of payment is agreed and funds requested you will enter a legally binding agreement for the amounts specified.
3. The Programming Historian Editorial Board reserves the right to reject funds from any organization or individual for any reason.
4. The Programming Historian is an international volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is registered in England, Company Number 12192946.
5. The purpose of the Programming Historian is to advance the education of the public in the humanities in particular in the use of digital tools and techniques and to promote research for the public benefit in all aspects of that subject and to publish the useful results.

**Comment by acrymble** [comment]
Should this replace our $200 tier on Patreon? Maybe we should lower that to something more like 25, and direct institutions to this messaging instead?

**Comment by drjwbaker** [comment]
Yeah, I had something like that in mind.

**Comment by drjwbaker** [comment]
Seems from https://github.com/programminghistorian/jekyll/issues/1589 what we are happy to think of ourselves as the kind of group that can/should have this kind of relationship with institutions. I'll start setting it up.
