### ISSUE TITLE
Zoe - please contact

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1628]
@ZoeLeBlanc I'm trying to contact you via email about ProgHist ltd. I suspect my messages are going to your junk box. Can you please email me?

**Comment by acrymble** [comment]
If anyone has @ZoeLeBlanc 's email, please contact her and let her know I need her to touch base. I've tried every venue I have.

**Comment by ZoeLeBlanc** [comment]
@acrymble just replied via email. Sorry for the delays, it's been a crazy few weeks and your email slipped through the cracks! Thanks for following up though 😊
