### ISSUE TITLE
Plan for promoting PH at conferences

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1629]
This ticket will serve as a sharing point on the plan to promote PH at conferences before moving the guidelines to the Wiki. I anticipate that the procedure could be different by location and/or discipline so I'd appreciate any input.   

If one or several PH editorial board members are going to assist a conference or event that is tied to digital scholarship in any way, please, do the following: 
1. Contact the Communications Manager to inform our audience about your attendance on: 
- Twitter 
- Newsletter 

2. With the communications manager organize to: 
A. Contact conference organizing committee about "permission" to have a **designated space** to promote PH during a few hours (dependent on how many PH members are at the conference)
B. Organize a working session about PH by hosting an **informal PH meetup** at some coffee place. Keep receipts for reimbursement. 
> "Come hear about our current development, opportunities for collaboration, and general info at 3PM at XYZ Coffee Shop. Beverage is on us." 

The Communications Manager will contact the financial team to be advised on the budget for conference promotion. 

For the development and communication team: 
- Ensure PH conference attendants have stickers or other merch to hand out. 
- Track how many people approach the PH member or attend the meeting/workshop

**Comment by drjwbaker** [comment]
A couple of thoughts as Finance Manager:

> B. Organize a working session about PH by hosting an informal PH meetup at some coffee place

Keep receipts and we should be able to reimburse this.

> Ensure PH conference attendants have stickers or other merch to hand out.

We should be in a position to pay for a batch of stickers each time someone needs them.

Re both these items, I suggest @jenniferisasi that when someone informs you that they'll be going to a conference and are able to do a little comms, you alert me so I can look at our finances and advise what we can spend (this should get easier over time, but is a little tight right now as https://github.com/programminghistorian/jekyll/issues/1537 is our spending priority.

**Comment by jenniferisasi** [comment]
> you alert me so I can look at our finances and advise what we can spend

Noted @drjwbaker, thanks!

**Comment by jenniferisasi** [comment]
@drjwbaker two people have already sent me an email with plans to attend conferences. How would you prefer me to inform you of funds necessary/available for stickers and the like? 

I am going to start a record where I take note of who is attending what to be able to promote it, maybe a spreadsheet, would it help if it's a shared one?

**Comment by drjwbaker** [comment]
Spreadsheet works. And ping me each time there is a new addition.

Our problem at the moment is that stickers aren't cheap. So until we get a big uptick in funds, we can only really do a batch every 2 months based on our current Patreon.

**Comment by drjwbaker** [comment]
Clarification: stickers are cheaper the more you by. E.g. with my preferred supplier, 50 is £45, 100 is £53, 200 is £68, 500 is £103, 1000 is £153. So it may be better for me or you to buy a bulk amount, and then post them to people.

**Comment by jenniferisasi** [comment]
We also should take into account the shipping cost, right?. The company we have been using here in the US has similar prices, 50 for $56, 100 for $67, 200 for $85, etc. (looks a bit cheaper today as per conversion) and then shipping a bunch within the US is super cheap.

**Comment by acrymble** [comment]
Can I suggest we look into eco friendly stickers? I'd hate us to be part of a plastic problem if we can avoid it.

**Comment by drjwbaker** [comment]
Fine idea. I'll investigate. Found these so far https://stickerit.co/custom-stickers/biodegradable-stickers.html

**Comment by acrymble** [comment]
@jenniferisasi is there an action waiting for something here? Can we press ahead?

**Comment by jenniferisasi** [comment]
Thanks for being on top of everything @acrymble! I need to wrap up all the ideas after talking to a couple more people, created a spreadsheet, etc. so give me about a week to finalize and publish on the wiki. 
(Flying today to my new location, if all goes according to plan I should be more than able to complete this)

**Comment by acrymble** [comment]
@jenniferisasi I'm not sure how many conferences there will be this year. Maybe this energy should be shifted into other areas?

**Comment by drjwbaker** [comment]
I've avoided ordering stickers for this precise reason.

**Comment by jenniferisasi** [comment]
Right, basically all conferences are either cancelled or postponed so I can certainly close the ticket and reopen once we can start going to conferences again.

**Comment by jenniferisasi** [comment]
Will re-open this issue whenever conferences start happening again.
