### ISSUE TITLE
data files wrong in Python intro lessons

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#163]
In the migration the .zip files used for syncing the obo library have been lost for the lessons including and after: http://programminghistorian.org/lessons/output-data-as-html-file

I will have to rebuild these and upload the right files, as you can't follow through at the moment.

**Comment by wcaleb** [comment]
Is [this](http://programminghistorian.org/assets/programming-historian3.zip) not the right one?

**Comment by acrymble** [comment]
No it's wrong. I'm going to have to remake it. Each lesson should
effectively have a different zip file, because it builds upon the previous
one each time. Not sure where it went wrong, but I suspect it was a while
ago.

**Comment by acrymble** [comment]
this was fixed some time ago

**Comment by ianmilligan1** [comment]
:tada:
