### ISSUE TITLE
Say thanks to FR volunteer translators and reviewers

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1631]
All: the @programminghistorian/french-team will soon be done with the translation editions we had started this fall and so the FR lessons will be integrated in the Twitter bot and will be diffused regularly from the PH twitter account. 

In this occasion, I thought it would be nice to make a blog post (or at least tweet) to thank all volunteers who spontaneously took contact with us and translated lessons from English, as well as the master of the Ecole des chartes (two of these translations come from their students and at least three more are ready for us to edit in the coming months). It is always nice to say thanks but there we were happily surprised of people spontaneously contacting us and I (want to) see it as a community in the making thing that could further encourage people to engage. 

What do you think? The blog post could go out some time in February once these three new lessons are published. All views and ideas welcome, and I ping @jenniferisasi as Communication Manager and @programminghistorian/french-team in particular.

**Comment by jenniferisasi** [comment]
@spapastamkou and team, of course, this is the perfect example of community building in the project and credit has to be given. Let's do a blogpost + tweet about it :) 

The blogpost can be a thank you note + an account of the status of the French project on your way to celebrating a year

**Comment by walshbr** [comment]
Sounds good - just ping me when you're ready for the Twitter bot to get going. You'll need to load tweet messages and the URLs onto the spreadsheet. I have the Fr tab already on the spreadsheet for you ready to go.

**Comment by mariechristineb** [comment]
@spapastamkou I also agree about doing a blogpost on the topic - all the more so if it can encourage other people to reach out and contribute :)

**Comment by spapastamkou** [comment]
@programminghistorian/french-team cf. PR #1689
