### ISSUE TITLE
COINS metadata should only appear on lesson pages

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1632]
Very minor issue, but the COins metadata that makes our lessons easily importable by reference managers like Zotero is currently added on ALL pages, so Zotero could try to import e.g. our homepage as if it is an article. I need to add a logic flag or change where the metadata is added so that it's only happening on lesson pages.

**Comment by drjwbaker** [comment]
Good catch @mdlincoln!
