### ISSUE TITLE
Anna-Maria's Software Sustainability Institute fellowship - collaboration with PH

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1633]
I 've been awarded a Software Sustainability Institute Fellowship for 2020  🍾🍾🍾
https://software.ac.uk/blog/2020-01-10-announcing-2020-software-sustainability-institute-fellows 

As part of my fellowship, I am planning to organise later this year "an edit-a-thon somewhere in the UK (probably London or Sussex) in order to run health checks in terms of sustainability for PH lessons", also in collaboration with @drjwbaker and @acrymble . The content of this event is in purpose relatively vague and I am still exploring what might be a good set up for this event .

As I am still thinking about the content and the logistics of this event, I am open to ideas or proposals on what might be a useful event/ task for the project itself, mainly from a technical point of view. Any ideas, more than welcome!

I am willing to leave this ticket open and I will update it once I have more information on it.

**Comment by mdlincoln** [comment]
This is very cool. 

I want to make sure we keep it connected with the forthcoming DOIs, and the far stricter policies we'll need to think up re: what edits we make to lessons post-publication, versus what kinds of changes trigger a whole new lesson. We are, after all, NOT a wiki, but a peer reviewed journal.

**Comment by jenniferisasi** [comment]
Nothing to add for now, but wanted to say: congratulations!! 🍾

**Comment by acrymble** [comment]
Congratulations @amsichani. That's really impressive.

If you're looking for a free venue, the Royal Historical Society in London will let us use their council room on days they don't need it. It can accommodate about a dozen, but isn't great for plugs.

**Comment by drjwbaker** [comment]
> This is very cool.
> 
> I want to make sure we keep it connected with the forthcoming DOIs, and the far stricter policies we'll need to think up re: what edits we make to lessons post-publication, versus what kinds of changes trigger a whole new lesson. We are, after all, NOT a wiki, but a peer reviewed journal.

Good shout. Seconded. Strikes me that getting a librarian or two in the room would give us a strong take on this. This is the relevant ticket @amsichani #1370

**Comment by drjwbaker** [comment]
I'd like to have noted in this ticket that is the THIRD award from the SSI (@shoaibsufi et al) for a PH team member and/or that has had a direct impact on PH work. They are strong and kind allies.

**Comment by svmelton** [comment]
Congrats! This is great news.

**Comment by rivaquiroga** [comment]
Congratulations! :rocket:

**Comment by acrymble** [comment]
@amsichani can you let us know if you need anything from anyone on the team to support this? I'm not sure what your timelines are.

**Comment by amsichani** [comment]
Hi @acrymble , I ve started thinking (also with @drjwbaker as my SSI mentor) and planning this event for early autumn 2020. We ve recently been informed that our SSI inaugural period will be extended by 9 months, so this gives me a bit of extra room to plan for the event. The situation is quite insecure in the UK universities for the time being in terms of the next term and event planning , and given the current circumstances, I am happy to organise it sometime in late Nov-Dec 2020. I will keep you updated.

**Comment by mariajoafana** [comment]
Yes please, keep us posted

**Comment by acrymble** [comment]
@amsichani this doesn't look to me like a ticket with an active 'to do' task associated with it. Instead it looks like a (very positive) announcement. Can we close the ticket?

**Comment by acrymble** [comment]
I haven't heard any more so I'm going to close this on the assumption that there is no action required for any PH team member. @amsichani you can reopen this if you need it, but please make sure the ticket has an action.
