### ISSUE TITLE
Spanish Copyediting Setup

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1635]
Now that we have conducted a trial of copyediting in English (https://github.com/programminghistorian/jekyll/issues/1381), I'd like to work with the Spanish team to do the same for them. Especially because some of our Patreon sponsorship comes from Spanish colleagues!

At the moment, a Styleguide is only available in English and it was externally funded: https://programminghistorian.org/en/author-guidelines.

Rather than translate this directly, I believe it is best for someone with advanced Spanish grammar knowledge to use it as a guide, but to create something appropriate for the Spanish publication. I believe this should be paid work, and would benefit from someone internal to the team doing the work. However, I will leave it up to the Spanish Team to decide what is best.

@rivaquiroga can you please discuss with your team how we might best proceed? I will then work with you to find the money or persons to conduct this work, and ensure that we integrate it effectively with our editorial processes. We will not be able to do Spanish copyediting until we have this styleguide finished and approved.

**Comment by jenniferisasi** [comment]
Quick note to say that we are discussing via email.

**Comment by acrymble** [comment]
Just for information purposes, I have contacted the public relations firm that created our English styleguide to see if they can work also in Spanish, and to ask what the cost of doing this work for us would be. I will report back when I know. There is no obligation to proceed, but I think it's important for us to know the options.

**Comment by rivaquiroga** [comment]
Thanks. We are curently discussing the details. We want one of the team members to be leading this task.

**Comment by acrymble** [comment]
The quote to get this work done professionally is £1350. @rivaquiroga tell me what you think in terms of whether or not you a) want me to get another quote. b) think this quote is reasonable. or c) want to do this yourselves?

**Comment by rivaquiroga** [comment]
I'll discuss this with the Spanish team and reach you back

**Comment by jenniferisasi** [comment]
> The quote to get this work done professionally is £1350. 

Out of curiosity @acrymble was that the price for the work in English?

**Comment by acrymble** [comment]
No it was £1800

**Comment by acrymble** [comment]
@rivaquiroga it would also help me to know what timeline you would like to try to achieve for having this in place so that we can copyedit new Spanish lessons. Are you hoping to have this ready soon? By mid-year? End-of-year? Then I can help coordinate to your schedule.

**Comment by rivaquiroga** [comment]
@acrymble, by mid-year.

**Comment by acrymble** [comment]
Just an update that @rivaquiroga and I have had some conversations about this and the Spanish team is still finalizing their plan, but it seems like they will build a styleguide themselves.

**Comment by mariajoafana** [comment]
Shall we continue planning this here? @jenniferisasi @rivaquiroga @arojascastro @JoshuaGOB @vgayolrs @jamotilla

**Comment by acrymble** [comment]
@rivaquiroga can you update me on the timeline here? I'd really like it if this system could be in place before our AGM on 28 May if possible.

**Comment by acrymble** [comment]
A recently published lesson had a link in it to a personal website of the author that's broken within a few weeks of publication. The result can be seen in the following ticket: https://github.com/programminghistorian/jekyll/pull/1734#issuecomment-612046199

I'd suggest making sure the styleguide provides advice for avoiding this type of problem in future.

**Comment by mariajoafana** [comment]
Revisiting this abandoned ticket. I contacted Riva to rethink the path to follow on this. Following @acrymble advise to the French Team [here](https://github.com/programminghistorian/jekyll/issues/1636#issuecomment-621674930) we could break the work into the three sections and assign different people to translate and adapt, and then have two people review and publish the whole thing. These are the sections: 

A. Style and Audience
B. Specific Writing Guidelines
C. Formatting Guidelines

**Comment by mariajoafana** [comment]
I just started the translation and adaptation file in progress [here](https://github.com/programminghistorian/jekyll/pull/1771)

**Comment by acrymble** [comment]
It looks like this is now in a pull request, which is great news. Thanks @mariajoafana. I'm happy to work with @programminghistorian/spanish-team once this has been published to set up a trial on the next lesson, since I've gone through that process with the English team. Can someone message me once the pull request is complete and we can more to the next stage?

**Comment by rivaquiroga** [comment]
Sure! I’ll let you know when we are done.

**Comment by acrymble** [comment]
@rivaquiroga @mariajoafana just a reminder that this was an action agreed at the last meeting #1868.

If you haven't been able to make progress on this, I propose we close this ticket and mark Copyediting as 'Declined' for the Spanish publication on the list of services (with the right to revisit that decision in future) - https://github.com/programminghistorian/jekyll/wiki/ProgHist-services-to-Publications

This lets us adjust our ProgHist budgets accordingly and plan for the future, and means the action doesn't have to continue to take up time at meetings.

**Comment by rivaquiroga** [comment]
@acrymble, the Style Guide is ready. The team had until today to make any comments, so in the next few days we will be merging the open PR (#1771).
