### ISSUE TITLE
French Copyediting Setup

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1636]
Now that we have conducted a trial of copyediting in English (#1381), I'd like to work with the French team to do the same for them. 

At the moment, a Styleguide is only available in English and it was externally funded: https://programminghistorian.org/en/author-guidelines.

Rather than translate this directly, I believe it is best for someone with advanced French grammar knowledge to use it as a guide, but to create something appropriate for the French publication. I believe this should be paid work, and would benefit from someone internal to the team doing the work. However, I will leave it up to the French Team to decide what is best.

@spapastamkou  can you please discuss with your team how we might best proceed? If I remember correctly you were already seeking funding to support this. Once I know your plan I will  work with you to find the money or persons to conduct this work, and ensure that we integrate it effectively with our editorial processes. We will not be able to do French copyediting until we have this styleguide finished and approved.

**Comment by spapastamkou** [comment]
I can start working on adapting the copyediting chart into French and verify with members of the team who wish to do it. I am quite familiar with normalized fr forms because I needed to use them now and then so I can put the bases of this work. I see this as part of my volunteer work for the PH. I will either start a translation edition I am in charge of late this trimestre or I will extend a bit the deadlines so that I can combine both activities smoothly. 
I will email separately about seeking funding in the coming days.

**Comment by acrymble** [comment]
@spapastamkou can you clarify the dates so I can keep track? When is the end of the trimestre for you?

Thanks for responding.

**Comment by spapastamkou** [comment]
Yes, sorry: the current trimestre (for the 3M FR planning) runs from February to April as we established it only days ago. 
We can set the end of March as deadline for the copy-editing in FR, would that be ok with what you had in mind? Please let let me know and I can note the date in #1642. Thank you!

**Comment by acrymble** [comment]
Just for information purposes, I have contacted the public relations firm that created our English styleguide to see if they can work also in French, and to ask what the cost of doing this work for us would be. I will report back when I know. There is no obligation to proceed, but I think it's important for us to know the options.

**Comment by acrymble** [comment]
The quote to get this work done professionally is £1350. @spapastamkou tell me what you think in terms of whether or not you a) want me to get another quote. b) think this quote is reasonable. or c) want to do this yourselves?

**Comment by spapastamkou** [comment]
Thank you for this @acrymble. For b, I do not know bcz I was not able to find an estimation here yet; for c not particularly, but will if have to. For a let me come back in a few days: I'll try and see how this can fit in the grant proposal and if the rest of the @programminghistorian/french-team has ideas on it.

**Comment by fdlaramee** [comment]
My two cents: Judging by the rates that usually apply on the translation market here (Quebec), by the amount of adaptation that is likely to be required in addition to said translation, and by my rough estimate of the difference in cost of living between the UK and Canada, I would say that the quote that the current vendor provided to @acrymble is a tad high but well within reasonable parameters.

**Comment by acrymble** [comment]
@spapastamkou can you update me on the timeline here? I'd really like it if this system could be in place before our AGM on 28 May if possible.

**Comment by spapastamkou** [comment]
@acrymble We consider working on the chart in June. Would this be ok?

**Comment by acrymble** [comment]
I'm wondering if this ticket is stuck because it seems like a bigger task than it actually is. In order to try to make it more manageable, we can break it down into sections that need to be developed (or translated from the English document). There are 3 sections:

A. Style and Audience 
 - Language and Style (5 lines)
 - Open Source, Open Access (1 paragraph)
 - Write for a Global Audience (8 bullet points)
 - Sustainable writing (5 bullet points)

B. Specific Writing Guidelines
 - Dates and Times (6 bullet points)
 - Numbers (7 bullet points)
 - Headings (2 sentences)
 - Lists (3 bullet points)
 - Punctuation (12 bullet points)
 - Capitalisation (4 large bullet points)
 - References (8 bullet points)
 - Challenging Words Explained (4 bullet points)

C. Formatting Guidelines
 - Write in Markdown (3 paragraphs)
 - Bold, Italics, and Underline (3 bullet points)
 - Alerts and Warnings (1 paragraph)
 - Figures & Images (4 paragraphs)
 - Code Exampes (about a page)


Maybe @spapastamkou we could assign sections to different members of the team, with you then able to bring it all together?

**Comment by spapastamkou** [comment]
According to current disponibilities, some members of the @programminghistorian/french-team could work on this: if have to, in June / July; more easily towards August.

**Comment by acrymble** [comment]
@spapastamkou thanks for the update. It looks like this is not a key priority for the French team (perhaps because you are not yet writing French lessons). Would it be more helpful to have this as a service we could offer your publication, but not one you are obliged to take up right now?

You could then open a ticket to start this process when your team is actually ready for it?

**Comment by spapastamkou** [comment]
I think it could be simpler to agree that it is a team responsibility, rather than externalize so that we fix a timeline. At least 2 members (me and @fdlaramee) can work on it this summer, so if we schedule to have it ready by August, we can open a ticket after my sabbatical? Or directly a pull request based on this ticket (reopened for the purpose).

**Comment by acrymble** [comment]
Sure @spapastamkou I will make a note for the ProgHist board that the French Team will contact us if and when they have something ready. Should we close the ticket in the meantime? It might relieve some mental pressure to take this off the agenda if it can't be worked on now.

**Comment by acrymble** [comment]
Just a note that I've recorded this on the Wiki on a new page for keeping track of these types of services. So we won't forget about it. https://github.com/programminghistorian/jekyll/wiki/ProgHist-services-to-Publications

**Comment by drjwbaker** [comment]
This is a useful summary Adam. Without sidetracking this issue, note that we'll need to think about the distinction between this wiki page and the [Service Integrations](https://github.com/programminghistorian/jekyll/wiki/Service-Integrations) page. E.g., the fact that the Ltd pays for use of Netlify beyond the free plan (as a Service to the Publications) is currently listed on the latter page, and may need to move.

**Comment by drjwbaker** [comment]
Aiming for after the summer (per @spapastamkou comment at https://github.com/programminghistorian/jekyll/issues/1729)

**Comment by acrymble** [comment]
I am closing this while @spapastamkou takes her sabbatical. It can be reopened later in the summer when it is under active development.
