### ISSUE TITLE
 Retired lessons in Spanish PH

### ISSUE THREAD

**Issue by KlausIllmayer** [programminghistorian/jekyll#1638]
I'm doing currently some metadata harvesting of the PH GitHub repo. I found an issue, that may be a bug. It is about retired lessons in the Spanish PH. Whereas in the English PH the lessons in the [retired-folder](https://github.com/programminghistorian/jekyll/tree/gh-pages/en/lessons/retired) do not show up in the English [Lesson Index](https://programminghistorian.org/en/lessons/) (and I think this is in accordance with the [Lesson Retirement Policy](https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lesson-retirement-policy.md)), the ones in the [retirada-folder](https://github.com/programminghistorian/jekyll/tree/gh-pages/es/lecciones/retirada) do show up in the Spanish [Índice](https://programminghistorian.org/es/lecciones/) (and they are also counted on the [main page](https://programminghistorian.org/)).
Two lessons are involved:
* https://programminghistorian.org/es/lecciones/retirada/introduccion-control-versiones-github-desktop
* https://programminghistorian.org/es/lecciones/retirada/sparql-datos-abiertos-enlazados

Could be connected to #706

**Comment by mdlincoln** [comment]
Thank you for noting this @KlausIllmayer  - I'll follow up on it 👀

**Comment by rivaquiroga** [comment]
@mdlincoln, I just read #706 and it seems that your suggestion about storing the ES retired lessons in the same `/retired` folder as the English ones was not take into account :( They are currently in `es/retiradas`. 
Do you want me to move them?

**Comment by mdlincoln** [comment]
No, they should stay there so the URL remains the same. I need to edit our configuration file so that files stored in `es/retiradas` will be processed appropriately. Will do a PR shortly.
