### ISSUE TITLE
Suggested update to "Analyzing Documents with TF-IDF"

### ISSUE THREAD

**Issue by mjlavin80** [programminghistorian/jekyll#1645]
@ZoeLeBlanc I'm wondering if it would be possible to add a small detail to my lesson on TF-IDF. In my mention of Karen Sparck Jones, originator of the algorithm, I would love to add that Jones was actually part of the New York Times's ["Overlooked" obituary series](https://www.nytimes.com/2019/01/02/obituaries/karen-sparck-jones-overlooked.html). She was included in January 2019, which is about when I was finishing the lesson, but it was not something I was aware of until just now (thanks, Peter Organisciak!).

**Comment by spapastamkou** [comment]
as @fdlaramee just finished the translation of this lesson into French; and I will edit it somewhere in March, please keep us in copy if changes are brought to the original, to keep the FR version updated. Thank you!

**Comment by acrymble** [comment]
I'm not the editor here, but (while I understand that this would be a nice gesture), I'm not clear that it increases the sustainability, learning outcomes, or clarity of the lesson. The implications of making small updates like this are potentially quite burdensome as we now publish in 3 languages. Is this an important enough change for a learner that it warrants 3 people's time?

**Comment by mjlavin80** [comment]
I respect @acrymble 's concern about the precedent, and the question of folks' time. For me, the best reason to do this is to call a little more attention to people like Karen Sparck Jones, and maybe inspire people to look for others who have been ignored or insufficiently credited for their work. Calling attention to the politics of who is memorialized was always an intended learning goal for me.

**Comment by ZoeLeBlanc** [comment]
I understand @acrymble's hesitation as well but considering this lesson is on Sparck Jones' algorithm and the NY Times obituaries datasets, it seems like an important enough update to the lesson. Would you be willing to contribute a pull request with the changes so we could review them with the French editorial team @mjlavin80 ?

**Comment by mjlavin80** [comment]
Will do. Thanks, everyone!

**Comment by acrymble** [comment]
@ZoeLeBlanc just a reminder that as we bring in DOIs soon, this type of change won't really be viable. So if you do intend to make it, please make sure it happens before DOIs are implemented, and then close the ticket.

**Comment by drjwbaker** [comment]
> @ZoeLeBlanc just a reminder that as we bring in DOIs soon, this type of change won't really be viable. So if you do intend to make it, please make sure it happens before DOIs are implemented, and then close the ticket.

@ZoeLeBlanc See https://github.com/programminghistorian/jekyll/issues/1682#issuecomment-605084365 (tl;dr: viable, but discouraged)

**Comment by ZoeLeBlanc** [comment]
Duly noted @drjwbaker & @acrymble . Think this PR was merged in some time ago, so going to close this issue ticket.
