### ISSUE TITLE
French tweets in the Twitter bot

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1648]
@walshbr There are two PR in progress for 2 FR translations which means that we are ready (once merged) for the Twitter bot. 
At the moment, there are 2 tweets ready for each of these lessons; and for the five lessons that are already published there is one tweet for each (I kept the texts) which means I shall have to prepare 5 second tweets for these lessons. 

My question is: I should put all tweets at once on the FR sheet or is it possible to put the ones that are ready now and the rest let's say tomorrow? I ask only to see how I organise myself. Thank you!

**Comment by walshbr** [comment]
Either one! It doesn't matter at the moment, because the bot currently isn't looking at the French tab. So you're free to add stuff to it as you'd like. Once we turn it on we will want to be careful about putting materials there when they are ready to be tweeted. But for now it's all the same. I'll get to working on adding the French piece to the bot!

**Comment by spapastamkou** [comment]
Ok, thank you very much! I'll start adding then.

**Comment by walshbr** [comment]
Just to reiterate what I said on the call - I believe I have the code ready to go for the French tweet. I just need to flip the switch on Heroku. So let me know when you've got tweets there - I'll test it once or twice before automating it.

**Comment by spapastamkou** [comment]
I am done @walshbr, all tweets are there. Please note that the last 2 rows correpond to lessons that are under pull request; I'll let you know when they are out.

**Comment by walshbr** [comment]
KK - the script I have set up for the bot will tweet at random anything in the spreadsheet, so in the future it'd be best only to put rows in the spreadsheet for lessons that are active (otherwise we'll be tweeting out dead links). So I'll hold tight until those last two lessons are ready to go! Just ping me when they're both merged. Looking forward to getting the word out!

**Comment by spapastamkou** [comment]
@walshbr The 6th lesson is now published. I left in the bot the tweets for the 6 active lessons, so you can test your code. Once the next lesson is merged as well, I will add again its tweets. Is this ok for you ?

**Comment by walshbr** [comment]
Yep! I'll get testing. One question for you - what days and times do you want it to run to best reach your audience? Currently we have the thing sending out tweets on this schedule:

Monday: English tweet; 4:00 PM UTC
Tuesday: Spanish tweet; 4:30PM UTC
Wednesday: Spanish tweet; 2:00 PM UTC
Thursday: English follow-up tweet; 1:30 PM UTC

Back when there were just two languages I was trying to keep them all on separate days, but I don't think we should push anyone to the weekends. What about a French follow-up tweet on Friday with the initial tweet on one of the first four days? At a time that makes sense to you?

**Comment by spapastamkou** [comment]
I propose:
Tuesday: 3 pm UTC
Friday: 10 am UTC
Thanks!


Envoyé de mon iPhone

**Comment by walshbr** [comment]
Sounds good! I'll get working and let you know if I have any further questions or if I run into any issues.

**Comment by walshbr** [comment]
It's alive! https://twitter.com/ProgHist/status/1225069416406188032?s=20

It's definitely tweeting, but I'll leave this issue open for a week or so while I keep an eye on the scheduler aspect of things. Let me know if anything seems amiss in the meantime.

**Comment by walshbr** [comment]
Just a note to say that I was watching today, and caught an error on the Heroku scheduler that made the French tweet today hang up. Corrected that, and will keep an eye on next week's tweets. Will close when they're running.

**Comment by spapastamkou** [comment]
Thanks, Brandon!

>

**Comment by spapastamkou** [comment]
For info: one new lesson in FR is out (https://programminghistorian.org/fr/lecons/comprendre-les-expressions-regulieres) and I added the tweets in the bot. 

I am not very clear about one thing that is of interest for @jenniferisasi so I ping her: now that the FR tweets go into the bot, do I continue (as ME) to send a tweet to Jennifer, so that she can alert for the lesson via twitter? Do I alert only for the lesson coming out? Other?

**Comment by jenniferisasi** [comment]
Congrats on publishing another lesson, @spapastamkou! I am very much in favor of a one-time tweet about a new lesson, with a slightly different text than the one you put in the bot. Something like: Our FR team has been working hard and we have a new lesson in French! XYZ has translated comprendre-les-expressions-regulieres by XYZ

(so, something that announces the *newness* of a lesson vs. the "learn about..." of the regular/bot tweets)

**Comment by walshbr** [comment]
Yes I think in the past we've usually had people do their own, regular tweets when a new lesson comes out to announce that. The bot only works at random, so it might be a while before a new lesson pops up in the pipeline.

**Comment by acrymble** [comment]
This is live, no? can we close?

**Comment by walshbr** [comment]
All working yes.
