### ISSUE TITLE
Hand over of Project Manager at Large role

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#1650]
I am having the Skype facilitator role for 18 months now (wow!) and I am willing to hand it over to the next one , in order to focus more on my Education manager & Tech roles as well as my PML and ProgHist Ltd duties.
Anyone interested? I am happy to facilitate the February call and hand over after this, if that sounds easier.

**Comment by acrymble** [comment]
I've renamed this to Project Manager at Large, as that's the role within our team structure that you're looking to hand over.

**Comment by acrymble** [comment]
The role description for this position is here:

### Project Manager at Large

The role of the Project Manager at Large is to keep the team focused on achieving its goals. In practical terms this involves running the bi-monthly Skype calls of the project team, and ensuring open tickets are actioned efficiently and in a reasonable time span. Their job includes identifying a need for extra support or assigning unassigned tickets to someone on the team for actioning. This vital role ensures that we continue to meet our objectives and work efficiently as a team. This is a monthly task.

---

This will involve being a part of the Team Development team, led by @drjwbaker.

Is there anyone on the project team that would be willing to take on this role?

**Comment by mariajoafana** [comment]
I'm rejoining the team after my sabbatical and I'll be glad to take on the Project Manager at Large role after the February call

**Comment by acrymble** [comment]
Thanks @mariajoafana. Maybe you and @amsichani can have a conversation about what it entails and what changes you might like to bring to the role?

Once we've done the handover, I will update the project team page.

**Comment by amsichani** [comment]
Fantastic news @mariajoafana ! Lets talk through email on the transition process.

**Comment by amsichani** [comment]
@mariajoafana I am trying to send you an email at your usually used address but something isn't right...any idea?

**Comment by amsichani** [comment]
I have contacted @mariajoafana almost a week ago with no response so far. I hope she is happy  to facilitate also the [March call ](https://github.com/programminghistorian/jekyll/issues/1661#issuecomment-585094563
). I ll keep you and the relevant tickets updated.

**Comment by acrymble** [comment]
I've sent an email to you both in case you didn't have the most recent email @amsichani

**Comment by mariajoafana** [comment]
I'm closing this issue since we already discussed this
