### ISSUE TITLE
Consistency of Team Role labeling

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1652]
The new Team Role labels on the Project Team page are not consistent.

The 'Communication Team' and 'Technical Team' labels refer to a team, whereas most refer to specific roles. I think these should be consistently referring to roles.

The Managing Editor label for English also doesn't mention the language, whereas the others do. For consistency sake, this too should say (English).

Unless I hear otherwise, I'll assume I'm ok to make these changes by the end of February 2020.

**Comment by drjwbaker** [comment]
Good spot.

**Comment by acrymble** [comment]
@walshbr can we fold your Twitter bot work into your technical role? I'm trying to shorten our list of roles, and this one seems like a fairly straightforward maintenance task now that the hard work of setting it up is done. I'm not sure it needs to be flagged permanently in this way. Does that sound ok?

**Comment by walshbr** [comment]
Yeah that's probably fine @acrymble.

**Comment by acrymble** [comment]
@drjwbaker you've got a number of roles with similar descriptions:

Finance Manager: Responsible for project finances and fundraising
Treasurer: Responsible for project finances
Sponsorship Coordinator: Responsible for managing relationships with our sponsors

Can we fold all 3 into 'finance manager'?

**Comment by drjwbaker** [comment]
Go for it.
