### ISSUE TITLE
Patreon Goals - Re-thinking

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1653]
Our Patreon income at the time of writing is $99 per month. Our three goal levels (a built in part of Patreon to encourage sponsors to join) are at $100, $500, and $1000.

Over the past three months we've increased our monthly donations by about $20 per month. That means the gap between $100 and $500 is perhaps too big. In order to help us reach the next goal faster and have something to celebrate with the community, I would like to re-assign the values at $100, $250, and $500. Any objections?

**Comment by drjwbaker** [comment]
None from me.

**Comment by drjwbaker** [comment]
Just so I know who is doing what, are you expecting me to make the changes on Patreon? I only ask as you've been taking this on recently (for which I am grateful) but it had previously fallen under my remit. I don't mind who does it though!

**Comment by acrymble** [comment]
Right. I've done it this time. But I can leave all Patreon things to you in future if you'd like. You just let me know.

**Comment by drjwbaker** [comment]
My point is I think I'm 'supposed ' to do them, but I don't care about *my* turf. We both have a vested interest this, so perhaps we can share the load: if you want to run an idea by me and implement it, just say; equally, if you want to run an idea by me *and* have me do it, just say as well.
