### ISSUE TITLE
Maximum Number of Roles per person

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1668]
I'd like to propose that we adopt a (perhaps informal / soft cap) policy on the number of roles a person will take on within the project at any one time. I propose we cap this at 3, with the understanding that 1 or 2 is probably best for most people.

The reason for this suggestion is to ensure that no one is expected to do too much, that everyone can focus on doing all of their roles to the best of their ability, and to reinforce our commitment to the wellbeing of our team. I don't think we need anyone to reduce their workload if they currently exceed this limit, but I'm proposing we take it into consideration for future allocation of roles. 
This proposal would not affect paid roles, should we move towards that in future.

And for clarity, I would suggest that @spapastamkou (who has 6 tags on the project team page)

>  Managing Editor, Editor (French), ProgHist Ltd, Technical Team, Global Team, Volunteer 

Actually only has 3 roles (Managing Editor, Technical Team, Global Team).

Please share thoughts. Will this help manage expectations and wellbeing?

**Comment by jenniferisasi** [comment]
I strongly support members having a limited amount of roles. 

Following Sofia's example, @acrymble are you suggesting we get rid of the volunteer/supported tags as well? I found these very important to indicate our labor and would like to keep them. Since they are different from roles though, I wonder if changing their color to differentiate them from the roles could be a solution.

**Comment by acrymble** [comment]
Yes I think we should keep those @jenniferisasi. I will try to change the colour.

**Comment by spapastamkou** [comment]
This makes sense @acrymble and @jenniferisasi , and things can look more "clean" this way on the team page. 
Personally speaking, I am not sure I can stick to 3 roles, at least not as long as I am ME. I'll clarify this in the coming days.

**Comment by rivaquiroga** [comment]
I support this. And the color tag is a great idea :art:

**Comment by acrymble** [comment]
Ok I will leave this open for comment for another week and then action this if no one opposes

**Comment by acrymble** [comment]
Ok I think we can say this has been approved informally (and it's informal anyway). No one currently exceeds this so the only action is for me:

- [ ] change the colour of the volunteer / institutionally supported buttons on the project team page

**Comment by acrymble** [comment]
@mdlincoln do you have a view on the colour for this icon? I don't want to mess with the colour scheme of the whole site by going rogue with my own preferences.

**Comment by acrymble** [comment]
Note for myself: the css class used for setting the colour is in an external stylesheet: view-source:https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css so I guess I can either choose one of the other "badge" classes (the current one is using badge-primary) or I can add a new css class to our style.css sheet. I'll also have to add some logic to add a class to the HTML for volunteer / supported labels.

**Comment by mdlincoln** [comment]
If you can, please stick to the Bootstrap "badge" classes.

**Comment by acrymble** [comment]
The file where these tags are applied is: https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/contact-info.html

**Comment by acrymble** [comment]
I think this may require moving "volunteer" and "institutionally supported" in ph_authors.yml to a new metadata category in order to tag them separately with a different HTML tag. Are we fine with that @mdlincoln ?

**Comment by mdlincoln** [comment]
Sure. Make a PR and let's see what it looks like.
