### ISSUE TITLE
 Additional step suggested for Mac users of "Building Static Sites with Jekyll"

### ISSUE THREAD

**Issue by spswanz** [programminghistorian/jekyll#1669]
In the installing Ruby Gems and Jekyll phase, my Mac users have received an error that they don't have write permissions to the ruby gems directory. 

This is the suggested fix in the instructions:
> If you get a permissions error at this point, entering usr/local/bin/gem install rubygems-update instead of the command above may help.

That did not working for us, but the following did:

Typing this command:
`echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.bash_profile`
Then this command:
`source ~/.bash_profile`

That fix derived from here:https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma

**Comment by svmelton** [comment]
Thanks, @spswanz! I'll take a look at it.

**Comment by acrymble** [comment]
@mariechristineb is going to test this for us as part of a 'bug testing' trial #1817 . She will make a recommendation to @svmelton about how we should proceed.

**Comment by spswanz** [comment]
fwiw, I'm not sure this is long term fix with Mac switching from bash to zsh in Catalina OS, but I'm afraid I don't have more insight.

**Comment by jenniferisasi** [comment]
Will have to keep an eye on this together with @JoshuaGOB because we have a group of DHers in Argentina translating that lesson.

**Comment by acrymble** [comment]
@jenniferisasi in general it would be helpful for translating teams to inform us when lessons with bugs are being translated. That's an efficient way for us to address these problems. How can we make sure that information gets where it's needed?

**Comment by jenniferisasi** [comment]
We were informed about the translation of this particular lesson long ago ([Jan 21](https://github.com/programminghistorian/ph-submissions/commit/af9779634408dfdb14d649f21edcc8e2363f4502#diff-4c3049e1135f65166558a4a02c537276) for March 30 but then covid19 happened); so the translation proposal arrived earlier than the bug notification... that to say we need to have a system to inform both ways (bug reported before translation started & translation in process while bug is reported). 

The teams have their [project tracking system](https://github.com/programminghistorian/jekyll/projects/4), could we use them to report also about bugs and cross-reference them?

**Comment by mariajoafana** [comment]
I think that is good idea @jenniferisasi
