### ISSUE TITLE
Possible problem with whitespace in Getting Started with Markdown

### ISSUE THREAD

**Issue by miriamposner** [programminghistorian/jekyll#167]
See @c-forster's tweets [here](https://twitter.com/cforster/status/674255168905617408). Tagging @ssimpkin.

**Comment by ianmilligan1** [comment]
I don't fully see the issue here, but I am daft. Can it be laid out a wee bit clearer? Thanks!

**Comment by ianmilligan1** [comment]
Think I figured out what was wrong - can folks take a look? Thanks.

**Comment by ghost** [comment]
Looks like @ianmilligan1's fix corrected it. Learning so much about Jekyll!

**Comment by wcaleb** [comment]
@ssimpkin This is tangential, but what would you think about putting the rendered text in each example between two horizontal rules, or in a special `div`, just to more clearly set the examples apart from the main lesson text?

**Comment by ianmilligan1** [comment]
@ssimpkin I'm learning a lot too! :+1:
