### ISSUE TITLE
Possible bug in Georeferencing in QGIS 2.0

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1672]
[Georeferencing in QGIS 2.0](https://programminghistorian.org/en/lessons/georeferencing-qgis) is currently [being translated to Spanish](https://github.com/programminghistorian/ph-submissions/issues/163).

One of the reviewers identified a possible bug. Here is the paragraph for context:

> To offer some examples of georeferenced historical maps, we prepared some National Topographic Series maps hosted on the University of Toronto Map Library website courtesy of Marcel Fortin, and we overlaid them on a Google web map. Viewers can adjust the transparency with the slider bar on the top right, view the historical map as an overlay on terrain or satellite images, or click ‘Earth’ to switch into Google Earth mode and see 3D elevation and modern buildings (in Halifax and Dartmouth). Note: these historical images are large and will appear on the screen slowly, especially as you zoom into the Google map.
> 
> [National Topographic System Maps](http://maps.library.utoronto.ca/datapub/digital/3400s_63_1929/maptile/Halifax/googlemaps.html) – Halifax, 1920s
> [National Topographic System Maps](http://maps.library.utoronto.ca/datapub/PEI/NTS/west/) – Western PEI, 1939-1944
> [National Topographic System Maps](http://maps.library.utoronto.ca/datapub/PEI/NTS/east/) – Eastern PEI 1939-1944

Here is a screenshot of what you get when following the links:

![lesson-bug](https://user-images.githubusercontent.com/31421616/74549027-aa72e300-4f2d-11ea-86c9-969ca971cefd.png)

- A window pops-up warning that the page cannot load Google Maps correctly
- There is no slider bar on the top right to adjust transparency
- There is no 'Earth' button to switch into Google Earth mode and see it in 3D

@acrymble, as the original editor of the lesson, can you take a look on this?

**Comment by acrymble** [comment]
@svmelton I will have to pass this off to your team.

**Comment by svmelton** [comment]
Thanks @acrymble—we'll talk about this on our call on Tuesday.

**Comment by rivaquiroga** [comment]
Thanks! This is the only thing preventing us for publishing the translated lesson, so as soon as you have news on this please let us know.

**Comment by svmelton** [comment]
The EN team didn't feel like we could address this issue, so I've reached out to the authors to see if they can take a look.

**Comment by mariajoafana** [comment]
Hi @svmelton any updates on this?

**Comment by svmelton** [comment]
Hi @mariajoafana—sorry for the delay. Still no word from the authors. Does anyone have a relationship with the lesson authors? You might have better luck than I did.

I'm not sure what to do here. We didn't create or host the maps, so I don't know how else we can troubleshoot this.

**Comment by walshbr** [comment]
If we don’t have access to the maps and the authors can’t be reached then we will have to retire it I think.

**Comment by acrymble** [comment]
Was the lesson tried before it was translated? If not, that should probably become standard practice moving forward.

**Comment by rivaquiroga** [comment]
@acrymble, not sure if it was tried before. Definitely should be standard practice > be a step in the Translator Guidelines. 
@walshbr, the maps are referred on the lesson goals section, as an example of georeferenced historical maps. Maybe we can just remove the paragraph :scissors:. They are before the "Getting Started" section, so they are not really part of the actions involved in the lesson.

**Comment by walshbr** [comment]
Oh totally - that seems like it'd be a really sensible edit to me @rivaquiroga.

**Comment by svmelton** [comment]
That would certainly be preferable to retiring the lesson completely!

**Comment by rivaquiroga** [comment]
Great! I'm going to ask to the translator to remove the paragraph then. 
I'll be closing the ticket as soon as you confirm me it was also remove from the original lesson.

**Comment by mariajoafana** [comment]
Following up on this, @svmelton have you had a chance of removing the paragraph from the English-language lesson?
