### ISSUE TITLE
Retiring lessons and Twitter bot

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1674]
The bot just tweeted out a lesson that was retired. 

Reminder that when you retire a lesson you should also move that lesson to the retired spreadsheet tab on the google spreadsheet. 

I'll include more explicit instructions for how to do so by opening a pull request for updating the instructions here - https://programminghistorian.org/en/lesson-retirement-policy. Right now it just mentions that the lesson will be removed from the twitter stream, but it doesn't really explain how to do so in great detail.

**Comment by mdlincoln** [comment]
You'd also mentioned developing either better error reporting or better data validation on the google sheet during #1613 - can you please open up a second issue giving a bit more detail on that?

**Comment by walshbr** [comment]
Yep it's on my list of things to do @mdlincoln!
