### ISSUE TITLE
Data validation on twitter bot spreadsheet

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1677]
As discussed on #1613, the main issues with the Twitter Bot are twofold

1. People forget to update the spreadsheet when a lesson is retired.
2. People incorrectly update the spreadsheet.

So they're largely social issues, but we can try to account for them. Number one is going to be addressed by text in a PR or on the wiki giving clearer reminders and instructions for doing so. As for number two, @mdlincoln suggested opening this ticket with examples so that we could work on data validation on the spreadsheet as a first pass solution.

- [ ] A row is left blank - the gspread library will return a list of the spreadsheet contents, and if there is the odd empty value in the middle of the contents it will error if it tries to tweet out nothing. This is typically caused by someone deprecating a lesson and clearing the row out but not deleting it. 
- [ ] - A value other than X, XY, or nothing appearing in the tweet_log column. X notes a tweet has been used this cycle for the bot, and XY notes that the tweet is the current week's tweet (used for the ICYMI tweets). Really this should never happen, so long as the bot is the only person/robot interacting with that column.
- [ ] - XY appearing nowhere in the tweet_log column. If the bot tries to run an ICYMI tweet and can't find a particular tweet marked as of the current week it will error. This gets caused if an error occurs during a week before it can tweet for the first time. In other words, if it tries to tweet and fails, when it tweets a second time that week it won't have anything to hook onto for an ICYMI tweet. 

@mdlincoln suggested we might be able to solve some of this with data validation settings on google spreadsheet. It seems like the first two should be doable from the google spreadsheet side of things. FWIW, it doesn't error too often, as we don't publish that many lessons and people are generally pretty good about interacting with the spreadsheet. I think i notice something messing up once every six months or so.

**Comment by mdlincoln** [comment]
@walshbr I think google sheets validation should help us out here. I'll edit the english sheet to show how it might work - enforcing set values in `tweet_log`. IDK how sensitive your code is to data validation rules (or if the validation is just warnings that'll pop up for humans). So if it starts to go wonky after I add the rules, I'll revert it!

**Comment by mdlincoln** [comment]
hrm, well, I don't see (after a few minutes of googling) anyway to enforce a `NOT NULL` constraint on columns. But I did protect the `tweet_log` column and enforced values for it

**Comment by mdlincoln** [comment]
@walshbr any bot issues since I added data validation? LMK - if not, then I'll add it to es and fr sheets and then we can close

**Comment by mdlincoln** [comment]
Doing strict validation on sheets causes the bot to bug out, so we've remove it.
