### ISSUE TITLE
Portuguese Team Shadowing practice

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1681]
@svmelton our prospective Portuguese team all speak and read English well, and as part of their training to get up to speed with our practices, I'd like to ask that you pair each of them with an English language lesson going through peer review, if that's ok.

I realise this may take a few months. Can you let me know if you foresee any problems? I will put you in touch with them on email if you're ok with this.

**Comment by jenniferisasi** [comment]
@acrymble I don't want to step on your toes, but have you considered having them (or at least two of three) shadow translations peer-review processes? If I remember correctly, the PT team will be first doing translations as they have some grant to do so, and I had to help (happily) the FR team understand this particular process as it is slightly different to original lessons.

For communication purposes, I think @rivaquiroga and @spapastamkou could agree with us to make an exception for shadowing and do the next peer-reviews for translations in English to help them. Does any of them read Spanish by any chance?

**Comment by acrymble** [comment]
@jenniferisasi that would be great, but none of them said they knew Spanish.

**Comment by walshbr** [comment]
To @jenniferisasi's point - I'm never quite clear on the exact distinctions between translation workflows and the process for EN original lessons. This means that when I had ES folks shadowing me I give a lot of caveats about how what I'm telling them might be entirely different for their translation workflow. When I've done shadowing I usually do a skype call to describe the editorial process. I wonder if it would address @jenniferisasi's point to have an experienced ES person on that call as well? That way they could provide context for the general translation workflow and how it maps onto what they're seeing, but then the actual shadowing of the lesson could happen along in English.

**Comment by svmelton** [comment]
I'm happy to have the Portuguese team shadow lessons, though I think @walshbr's idea of having an ES team member join an editorial process call would be useful. 

The EN team is also planning on recruiting 1-2 new editors, so it's possible that a lesson may have multiple people shadowing. I don't think that should be an issue, but I wanted to mention it.

**Comment by walshbr** [comment]
When I did shadowing for the ES team last, I had two folks shadowing me at once. @rivaquiroga @JoshuaGOB could speak to how it worked for them, but to me it didn't really seem to cause any problems. It's always a little more difficult to schedule calls with one more person, but we only needed one call. The rest was by email.

**Comment by acrymble** [comment]
@svmelton are there any lessons coming up soon that we can start someone on?

**Comment by svmelton** [comment]
@acrymble We have a draft that's supposed to come in on March 1, so that could be a possibility!

**Comment by acrymble** [comment]
Thanks @svmelton I will find out who is available first and introduce you via email.

**Comment by rivaquiroga** [comment]
I agree with @jenniferisasi. Although the workflow is very similar in terms of the general steps, the focus of the editorial and reviewing process is different. In translations the focus is not the aims, contents, or structure of the lesson, but how to communicate them in the new language for a global audience. In many cases that involves adapting examples and/or datasets.
Proposal: we just received the Spanish translation that an author made of his lesson originally written in English. As Spanish is his heritage language, he and the collegue that helped him with the translation probably prefer to go through the editorial process in English. Maybe someone from the PT team can shadow this lesson.

**Comment by rivaquiroga** [comment]
Two of us shadowing @walshbr worked perfect!

**Comment by acrymble** [comment]
Thanks @rivaquiroga  I will find a second PT person to shadow your new lesson. We have 4 people so this will let us get two people trained quicker.

Would it be helpful to have videos of someone talking through each process? That might reduce the future burden of training?

**Comment by walshbr** [comment]
Potentially, but it also didn't feel like a huge burden on me. Others might feel differently. Videos might help standardize things if nothing else - I also had a lot of caveats like "this is what I do / look for; others are probably different at this stage in the process." Perhaps inevitable though since we are all different people.

**Comment by mariajoafana** [comment]
Passing by to ask about the status of this, @acrymble have you found a second PT person? Can I support you in this?
@rivaquiroga I couldn't find the translation ticket, is it Dave's lesson on audiovisual transcoding?

**Comment by acrymble** [comment]
Thanks for following up @mariajoafana. I have a zoom meeting with the Portuguese people today.

**Comment by acrymble** [comment]
I've had a meeting with the Portuguese team. They weren't clear what this would involve, but now understand and will be sending me a couple of names soon.

**Comment by acrymble** [comment]
The following people from the new Portuguese team (being assembled) would like to start shadowing lessons in either English or Spanish as the opportunity arises:

Joana Vieira Paulino
Taciana Sene Lucio
Rômulo Predes Monteiro da Cunha

@rivaquiroga and @svmelton can you please assign them to shadowing the next time a lesson appears for peer review? I can give you their contact info.

**Comment by JoshuaGOB** [comment]
Hi @acrymble I’m sorry to hear that this has been mainly on you #1718 I’m still more than willing to be of help in this. I’m going to be taking on at least one of the new members for a lesson translation that should come in soon. I’ve also contacted the members of the Spanish team to have a sense of where their lessons are to see if they can take part. Obviously talking into consideration the current obstacles we are all facing. 

I definitely agree with the process being discussed by the technical team and at project team meetings. I thought that had happened already for the PT team. Please feel free to include me in the meetings or communications you may have so I can take some of that work off your plate.

**Comment by acrymble** [comment]
Thanks @JoshuaGOB did you get my email about this last week?

**Comment by acrymble** [comment]
@JoshuaGOB has this gone ahead? Do you need any guidance?

**Comment by JoshuaGOB** [comment]
﻿
Hi @acrymble, got in touch with the PT team to reassess how they’re doing and what their current capacity is with regards to the on boarding tasks. As soon as I receive word from them I’ll update here as well.

**Comment by JoshuaGOB** [comment]
Hello, I've put @amsichani and the three PT editors in touch to work on the OCR and Machine Translation lesson. They expressed a preference for lessons in English so if there are any more coming soon I'd like to offer them the chance of shadowing on those as well if the editors are willing.

**Comment by acrymble** [comment]
I've created some new videos to support new (and existing) editors to build their skills. https://github.com/programminghistorian/jekyll/wiki/Training-and-Support-for-Editorial-Work

@JoshuaGOB can you let the Portuguese team know about these?

**Comment by JoshuaGOB** [comment]
﻿
Done. I have to look through since I still have a ton to learn. Thank you, this look like amazing work @acrymble

On Jun 6, 2020, at 01:41, Adam Crymble <notifications@github.com> wrote:

﻿
I've created some new videos to support new (and existing) editors to build their skills. https://github.com/programminghistorian/jekyll/wiki/Training-and-Support-for-Editorial-Work

@JoshuaGOB can you let the Portuguese team know about these?

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> I've created some new videos to support new (and existing) editors to build their skills. https://github.com/programminghistorian/jekyll/wiki/Training-and-Support-for-Editorial-Work
> 
> @JoshuaGOB can you let the Portuguese team know about these?

Thanks for this @acrymble I will send the link to the PT editors. Just looked at the first one. Very helpfull

**Comment by mariajoafana** [comment]
Just passing by to ask how shadowing practice is coming along and if anyone needs any support

**Comment by acrymble** [comment]
@JoshuaGOB I don't think you're using this ticket are you? Can we close it?
