### ISSUE TITLE
Include DOIs in lessons

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1684]
Once we have established a DOI registration workflow #1683 we need to edit the Jekyll layouts to have a field for DOI in the YAML header and to display the DOI on the lesson page & citation.

**Comment by mdlincoln** [comment]
The first part of this work is to produce crossref XML files for each fo the journals. I've started that branch now.

One question for @programminghistorian/spanish-team @programminghistorian/english-team @programminghistorian/french-team : [crossref allows us to set the following contributor roles](http://data.crossref.org/reports/help/schema_doc/4.4.2/NO_NAMESPACE.html#contributor.atts_contributor_role):

```xsd
<xsd:attribute name="contributor_role" use="required">
  <xsd:simpleType>
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="author"/>
      <xsd:enumeration value="editor"/>
      <xsd:enumeration value="chair"/>
      <xsd:enumeration value="reviewer"/>
      <xsd:enumeration value="review-assistant"/>
      <xsd:enumeration value="stats-reviewer"/>
      <xsd:enumeration value="reviewer-external"/>
      <xsd:enumeration value="reader"/>
      <xsd:enumeration value="translator"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:attribute>
```

I trust it's acceptable that both the original reviewers as well as the translation reviewers both get the role `reviewer`, and the editor and translation editors both get the role `editor`?

**Comment by arojascastro** [comment]
yup! 

(such a beautiful piece of xml :)

**Comment by mdlincoln** [comment]
I've submitted a first draft of the XML back to Sussex along with a few technical questions for their review.

**Comment by drjwbaker** [comment]
Woo! Great job @mdlincoln. Feels like we are making real progress.

**Comment by mariajoafana** [comment]
Have you heard from them @mdlincoln ?

**Comment by mdlincoln** [comment]
on May 3 2020:

>Hi Matthew,
Annette is chasing up with Crossref as we are still waiting for the new DOI range. Once received we will first need to create DOIs for the journals followed by a test run before adding DOIs to the 3 journal article xml files... will keep you posted
>
>Best,
>Tim

**Comment by drjwbaker** [comment]
To add, with no slight on my colleagues at Sussex, I don't expect this will come together super quick. They have a lot on, I suspect this isn't top priority, and CrossREF is a large infrastructure that - we can assume - is working below capacity right now.

**Comment by mdlincoln** [comment]
We've gotten _reserved_ DOIs back from Sussex (they're reserved but not yet active). I'm going to add them into our lesson files and set the doi to display with the citation info.

Will update once we hear back on whether CrossRef happily accepted our data

**Comment by mdlincoln** [comment]
🎺 

Our DOIs are now live!

They're listed in the suggested citation section of lessons at the bottom of e.g. https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files

And you'll see that DOI now resolves back to PH! We'll be double checking the linked metadata as it propagates out from crossref, but the back catalog should be uploaded now.

I'll follow up with Sussex for our first "new lesson" DOI for #1769 workflow tomorrow once they're awake.

**Comment by jenniferisasi** [comment]
Sorry to be informal but this deserves this gif right here: 

![msy](https://user-images.githubusercontent.com/11022533/81864559-cd1b9480-953a-11ea-9227-db6172c34bed.gif)

**Comment by arojascastro** [comment]
Thank you @mdlincoln and great job!

**Comment by drjwbaker** [comment]
@walshbr (you still run the Twitter bot, right?): just a thought, should we move the bot to using DOIs? e.g. https://doi.org/10.46430/phen0088 rather than https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files. If we want to, we should open a fresh ticket.

**Comment by walshbr** [comment]
Yay! This is exciting.

And oof at the thought of editing all those spreadsheet rows 😄.  I opened a ticket - that is a thing we should do.

**Comment by mdlincoln** [comment]
I have written up the workflow for managing editors to request new DOIs from Sussex, complete with email templates: https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI

@rivaquiroga will be testing this out and we'll update it as we try out this first pass

**Comment by mdlincoln** [comment]
I have also written a blog post draft at #1775 announcing this new partnership - @programminghistorian/communication-team please take a look :)

**Comment by spapastamkou** [comment]
@mdlincoln @rivaquiroga @svmelton We should probably update the editor guidelines (and the Managing Editors list) to add this info on the workflow and insert a link to the wiki

**Comment by drjwbaker** [comment]
> @mdlincoln @rivaquiroga @svmelton We should probably update the editor guidelines (and the Managing Editors list) to add this info on the workflow and insert a link to the wiki

@spapastamkou @rivaquiroga @svmelton And this relates to https://github.com/programminghistorian/jekyll/issues/1682#issuecomment-628003633 (in short, policy on updating articles in light of them having DOIs). I suspect the two issues need to be dealt with together.

**Comment by jenniferisasi** [comment]
> @mdlincoln @rivaquiroga @svmelton We should probably update the editor guidelines (and the Managing Editors list) to add this info on the workflow and insert a link to the wiki

As we agreed not to do further changes to those pages while de PT team is translating the core pages and, at the same time, this is a change that needs to be made pointing to [this wiki](https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI), I suggest you communicate with @JoshuaGOB on where the PT teams stands and maybe wait.

**Comment by acrymble** [comment]
@jenniferisasi just to be clear, we haven't agreed not to do further changes to pages while the PT team is translating them. We've asked the PT to do the following:

> While you are translating this material, we will pause any edits on it in the wider project to make sure that your pages stay syncronised with the other languages. To do that efficiently, we would appreciate a list of which pages you are currently working on at any moment, and a deadline (ideally no more than 1 month) for completion of those pages. This can be done in stages. For example, you might choose to translate certain pages in month one, and additional pages in month two. Once I know which pages you are working on I will announce a freeze to the team to ensure no changes are made.

This was sent to them in late March 2020 and I haven't heard any more, so from our perspective (unless @JoshuaGOB can tell us otherwise) there are no freezes currently in place.

**Comment by rivaquiroga** [comment]
:heavy_check_mark: workflow tested

The new lesson has it's DOI: https://doi.org/10.46430/phes0046
@mdlincoln instructions are super clear, and the process is faster than I expected.

**Comment by mdlincoln** [comment]
Excellent! I think the worst problems will just be any time difference between UK and the requesting editor :) This is great.

**Comment by jenniferisasi** [comment]
Thanks for clarifying the actual plan/wording @acrymble. It makes more sense that way that what I had in mind for sure.
