### ISSUE TITLE
Priority Pages for new publication translations

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1688]
At present we require ALL non-less pages to be translated for a new publication to get up and running. I'd like to suggest this is a big burden, and that we could instead reduce this to some key core pages, while providing a window of time for translating the rest. I'd suggest the following would make a good priority list:

- [ ] about
- [ ] project team
- [ ] privacy policy
- [ ] reviewer guidelines (tailored to language/community nuances)
- [ ] author guidelines (tailored to language/community nuances)
- [ ] translator guidelines (tailored to language/community nuances)
- [ ] editor guidelines (tailored to language/community nuances)

And that the following could be lower priority:

- [ ] research
- [ ] feedback
- [ ] lesson requests
- [ ] lesson retirement policy
- [ ] support us
- [ ] technical contributions

(I'm sure there are other non-public-facing files we need to include too). @JMParr, is this a global conversation? Can I ask for your feedback on this? I'd like to make sure our new teams are able to get going efficiently.

**Comment by JMParr** [comment]
I agree that it's important to be mindful about the workload we're asking of new language teams, and it makes sense to prioritize certain pages - particularly those that involve the public-facing pages that allow new lessons to move forward.

But, certainly this, is a multi-team conversation. I would like some feedback from our existing language teams. @spapastamkou @rivaquiroga can you run this by the French and Spanish teams and see what they think?

I'd also be interested in hearing from the technical team how (if at all) this proposed workflow might impact them. @mdlincoln @jenniferisasi @walshbr - any thoughts?

**Comment by spapastamkou** [comment]
If I may, I'd like also to give some personal thoughts as I am currently almost the only one in the FR team that was involved since the beginning in this (please correct me if I am wrong, @fdlaramee, I can't recall at which stage you walked in). 

The high priority pages as set by @acrymble in this ticket are the most demanding in time and energy to translate. Once they are ready, the lower priority pages are quite easy to prepare and, remember, the technical contributions are not translated either in ES or in FR, we all send to the EN version on the wiki. So I am note sure they can save considerable time and effort to the new teams. 

On the contrary, I am afraid that letting them out could create confusion and disorder in the infrastructure files of the new linguistic versions. 

I think that this distribution can set a guide for the translations but IMHO it is better to be done with the infrastructure in the beginning rather than come back to it in different times, as this might be confusing for the new members as well.

**Comment by mdlincoln** [comment]
Chiming in on the technical front to say this would be fine, but teams would need to be mindful of how they would want to set up the [menu links](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/snippets.yml#L6-L205) if some pages would be missing for the first few weeks/months.

**Comment by JMParr** [comment]
Thank you, @spapastamkou - it's very helpful feedback. 

And thanks to @mdlincoln too.

**Comment by jenniferisasi** [comment]
I strongly agree that translation does slow things down on some pressing texts/updates that need to be there sometimes. So thanks @acrymble for opening up the conversation. 

I want to express some concerns/ideas to add to the conversation, taking into account that you are suggesting to always translate the most relevant pages:

1. How can we keep a 'pipeline/workflow' to know that X page is not going to be translated asap but does need work later. This resonates with @spapastamkou's fear of confusion. When we do changes to a page, Github marks the changes in red/green, but we don't have that to keep track of a paragraph added in EN is missing in ES... 

2. Note that these updates usually happen in EN first to then do ES|FR|?, so it will leave some of our audience "uncommunicated" [I acknowledge we don't always need to communicate with everyone so in that case, it is fine with me]. 

3. On the lower priority list, the **lesson request** page only matches in EN|ES|FR *if we want to*. This is, the desire of the EN team for a lesson might not match what the ES team is looking for at a particular moment. I think **lesson retirement policy** needs to be clear in every language cos is communicating something important. Honestly, the research page is too easy to update...

4. Finally, in thinking about the team that is going to join (+future, this is more of a general issue in this case than this particular suggestion): how do we ensure that new add-ons to pages are included in new team/project without driving them crazy? [Say they already translated the 'about' page and tomorrow we decide to add another paragraph].

**Comment by acrymble** [comment]
So my sense is that this idea is not one we want to take forward. That's ok. Thanks for the feedback @jenniferisasi and @spapastamkou
