### ISSUE TITLE
Short 1-2 sentence abstracts on lessons page?

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#169]
@cblevins' review of the _Programming Historian_ in _The Journal of Interactive Technology and Pedagogy_ has lots of food for thought! It is great to have somebody spend such engaged time with the project.

One point suggests our landing page might be alienating.

> But I always try to point them towards a specific tutorial that will fit a discrete need. Otherwise, they run the risk of getting lost in a forest of intimidating trees. Jumping into The Programming Historian landing page armed with little more than “I have a bunch of photos from the archive – what do I do now?” is a recipe for alienation. Lesson titles such as Transliterating non-ASCII Characters with Python, Supervised Classification with a Naive Bayesian, or even the tutorial I followed for this review, Sustainable Authorship in Plain Text Using Pandoc and Markdown, assume an existing familiarity with what all those words mean and how they might help you. ASCII, Python, Bayesian, Pandoc, Markdown: these are part of an insider vocabulary.

Should we consider re-jigging things? Would our layout support a sentence or two per lesson, to give a sense to readers what might be within? Or another idea to help lower the intimidation factor.

**Comment by acrymble** [comment]
Thanks Ian. Good point.

I think our plan to address this is via the new blog, which will act as
guides for people in that situation of 'I have a bunch of photos...'. No?

**Comment by wcaleb** [comment]
That passage recalled to mind a discussion we've had before about 
whether to create more welcoming "tracks" through the lessons. Something 
on the order of "So you want to ... ?" together with a chained walk 
through related lessons. Could be something for blog posts to do, as 
well.

**Comment by ianmilligan1** [comment]
I think the blog posts are a great idea, but still think somehow putting more description onto our home page is good. "Sustainable Authorship in Plain Text Using Pandoc and Markdown" is one of my favourite lessons, and was actually pretty foundational for moving me into Markdown, but if you have no clue what Pandoc or Markdown you might not know to click through.

**Comment by acrymble** [comment]
Sounds reasonable to me. Can you mock it up for us to circulate?

**Comment by fredgibbs** [comment]
i've been thinking about a new lessons page for some time; i'd be happy to do a mock up with intro sentences (which i'm happy to create) and continue with that project--esp since @ianmilligan1 will be taking over as general contact person in a few weeks. (right?)

**Comment by ianmilligan1** [comment]
Sure that sounds good to me, @fredgibbs. I can't remember when we had the handover scheduled. We can time it for the first week of January if you want?

**Comment by acrymble** [comment]
Closing this as these issues are covered by #193 and #134.
