### ISSUE TITLE
Respond to UKRI Open Access Consultation

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1690]
Further to https://github.com/programminghistorian/jekyll/issues/1370#issuecomment-591574780 I suggest we make a short and targeted (e.g. responding only to specific questions) response to the UKRI Open Access Consultation, wrt our specific (small, OA, agile, innovative publisher) concerns/hopes/dreams around Plan S.

Deadline is 17 April.

**Comment by drjwbaker** [comment]
Link https://www.ukri.org/funding/information-for-award-holders/open-access/open-access-review/

**Comment by acrymble** [comment]
The deadline for this has been pushed back to 29 May.

**Comment by acrymble** [comment]
@drjwbaker are there specific areas you'd like us to respond to? I'm happy to work up some text with you, but if there are points you're passionate about, let's go with those.

We can also obviously not comment if you're feeling overstretched at the moment.

**Comment by drjwbaker** [comment]
Sorry. This fell off my radar as the crisis hit.

Looking briefly at the questions (attached), I think we should respond to:

> Q5. Should UKRI’s OA policy require a version of all in-scope research articles to be deposited in a repository, irrespective of whether the version of record is made OA via a journal or publishing platform? Yes / No / Don’t know / No opinion. 

Because this would be hard for an author submitting to an infrastructure like ours (and we think UKRI should encourage innovation like ours).

> Q13. Regarding research articles in-scope of UKRI’s OA policy, to what extent do you agree or disagree with each of the seven proposed technical standard requirements for journals and OA publishing platforms? 

Because innovative publishers like us would need funding to fully comply.

> Q19. Do you think the proposals outlined in Section A will have any financial cost implications for you or your organisation? Yes / No / Don’t Know / No opinion.

Because they will. To comply we need investment/support.

> Q27. There are many business models that can support OA. A common model for journals is based on APCs, but there are also other models (such as membership models and subscribe to open). Are there changes or alternatives to the present UKRI funding mechanisms that might help support a diversity of OA models? Yes / No / Don’t know / No opinion.

Because I suspect there are that could help people like us (not that I can think of them right now)

> Q29. Are there any existing or new infrastructure services that you think UKRI should fund the maintenance and/or development of, to support the implementation of its OA policy for research articles? Yes / No / Don’t know / No opinion. 

This is chance to say that we want things, if we want things.

[Full List of Consultation Questions.docx](https://github.com/programminghistorian/jekyll/files/4456100/Full.List.of.Consultation.Questions.docx)

**Comment by acrymble** [comment]
Some proposed response text draftings:

> Q5. Should UKRI’s OA policy require a version of all in-scope research articles to be deposited in a repository, irrespective of whether the version of record is made OA via a journal or publishing platform? Yes / No / Don’t know / No opinion.

Response: Not all publications take the format of a single file. This is especially the case for publications that include appendices or associated datasets and more innovative forms of publication will continue to evolve. Requiring all content to be deposited in a repository may stifle this innovation in publishing format. For publications that do not yet have a downloadable copy of the version of record, there is a cost to changing their infrastructure that will have to be paid for by someone. Unless funding is made available to meet this requirement, we caution against it.

> Q13. Regarding research articles in-scope of UKRI’s OA policy, to what extent do you agree or disagree with each of the seven proposed technical standard requirements for journals and OA publishing platforms?

Response: A number of these technical requirements have costs that will not easily be met by truly open publications that have opted not to charge for their content or services. CLOCKSS is expensive, as are DOIs. Your metadata requirements assume a scale of operation that would allow an expert to be hired to implement this policy, and which is not possible for small independent open access publications. Our publication attempted to contact SHERPA RoMEO many months ago about complying with this technical requirement, but we were ignored. Unless the infrastructure can support the demand, no requirements should be attached to it.

> Do you think the proposals outlined in Section A will have any financial cost implications for you or your organisation? Yes / No / Don’t Know / No opinion.

Response: The proposals in Section A will have a direct and substantial cost to our small not-for-profit scholarly publisher. In fact, they are amongst the only costs we have. We have managed to publish open access for free for a decade. To comply with your requirements will mean developing a business model in order to charge for what we know can be done for free. As a small publisher with a history of providing free scholarly content, we expect universities will be unwilling to use their block grants to support newly ascribed APCs. This will leave us unable to operate.

> There are many business models that can support OA. A common model for journals is based on APCs, but there are also other models (such as membership models and subscribe to open). Are there changes or alternatives to the present UKRI funding mechanisms that might help support a diversity of OA models? Yes / No / Don’t know / No opinion.

Response: small independent publishers have been forgotten by these proposals. Direct access to funding is needed to comply with these new requirements. This should be on going. Innovation in publishing like in research, often comes from small players who need support.

> Are there any existing or new infrastructure services that you think UKRI should fund the maintenance and/or development of, to support the implementation of its OA policy for research articles? Yes / No / Don’t know / No opinion.

Response: There are a number of areas UKRI could or should support. These might include free consultation for small publishers seeking to implement these requirements, access to developer time, grants to support new on going costs that arise from the requirements, and a general awareness and training programme to make your staff more aware of the contexts of small academic publishers.

---

Happy for any of this to be revised, but hopefully a useful starting point.

**Comment by drjwbaker** [comment]
Sorry. Slow getting to this. Thank you so much for making such a detailed and comprehensive start. Suggested revisions in bold:

> Q5. Should UKRI’s OA policy require a version of all in-scope research articles to be deposited in a repository, irrespective of whether the version of record is made OA via a journal or publishing platform? Yes / No / Don’t know / No opinion. (100 words max)

Response: Not all publications take the format of a single file. This is especially the case for publications that include appendices or associated datasets and more innovative forms of publication will continue to evolve. Requiring all content to be deposited in a repository may stifle this innovation in publishing format. For publications that do not yet have a downloadable copy of the version of record, there is a cost to changing their infrastructure that will have to be paid for by someone. Unless funding is made available to meet this requirement, we caution against it.

> Q13. Regarding research articles in-scope of UKRI’s OA policy, to what extent do you agree or disagree with each of the seven proposed technical standard requirements for journals and OA publishing platforms? (100 words max)

Response: A number of these technical requirements have costs that will not easily be met by truly open publications that have opted not to charge for their content or services. CLOCKSS is expensive, as are DOIs. Your metadata requirements assume a scale of operation that would allow an expert to be hired to implement this policy, and which is not possible for small independent open access publications. Our publication attempted to contact SHERPA RoMEO many months ago about complying with this technical requirement, but we were ignored. Unless the infrastructure can support the demand, no requirements should be attached to it.

> Q19. Do you think the proposals outlined in Section A will have any financial cost implications for you or your organisation? Yes / No / Don’t Know / No opinion. (300 words max)

Response: The proposals in Section A will have a direct and substantial cost to our small not-for-profit scholarly publisher. In fact, they are amongst the only costs we have. We have managed to publish open access for free for a decade. To comply with your requirements will mean developing a business model in order to charge for what we know can be done for free, **or else partner with existing publishers or organisations in such a way that will undermine our independent ethos and load dependencies onto our operation**. As a small publisher with a history of providing free **at the point of access** scholarly content, we expect universities will be unwilling to use their block grants to support newly ascribed APCs. **Without investment in infrastructure, the proposals in Section A** will leave us unable to operate **in our current form, diminishing the international impact of an innovative UK-based publisher for the sake of complying with UK specific open access mandates**.

> Q27. There are many business models that can support OA. A common model for journals is based on APCs, but there are also other models (such as membership models and subscribe to open). Are there changes or alternatives to the present UKRI funding mechanisms that might help support a diversity of OA models? Yes / No / Don’t know / No opinion. (400 words max)

Response: small independent publishers have been forgotten by these proposals. Direct access to funding is needed to comply with these new requirements. This should be on going. Innovation in publishing like in research, often comes from small players who need support.

> Q29. Are there any existing or new infrastructure services that you think UKRI should fund the maintenance and/or development of, to support the implementation of its OA policy for research articles? Yes / No / Don’t know / No opinion. (400 words max)

Response: There are a number of areas UKRI could or should support. These might include free consultation for small publishers seeking to implement these requirements, access to developer time, **low or no cost access to key publishing infrastructures (e.g. DOI minting services)**, grants to support new on going costs that arise from the requirements, and a general awareness and training programme to make your staff more aware of the contexts of small academic publishers.

---

Once we've agreed on this, are you happy to make the submission?

**Comment by drjwbaker** [comment]
@acrymble: I think the response to Q19 needs the most work because in your admirable desire to get to the point, you've slightly mis-characterised what we do. E.g. on 'free', we probably can and should dis-aggregate fiscal costs - where we have until recently operated for free - from labour costs - where we rely on time that comes from people having the leisure/privilege/support to give it. That is, I don't think it helps us case to respond the consultation by saying ~Academics can just do this for free!~, because that libertarian end of open source values fails to shine a light on hidden labour, the inequalities of open culture, et cetera. This is perhaps the area on which we most disagree (I should add Penny's report - v0.1 coming this week - is very much framed by the problems of egalitarian, open source thinking).

**Comment by acrymble** [comment]
Ok. What would you like to change? Keeping in mind the purpose of the consultation response is to get a favourable outcome for organizations like us.

**Comment by drjwbaker** [comment]
See above in bold, that is my stab at shifting our position slightly.

**Comment by acrymble** [comment]
Ah ok, I think all your suggestions are great. Thanks for making them. Anyone else want to comment?

**Comment by acrymble** [comment]
I haven't heard anyone else on this, so @drjwbaker I will submit this in the next couple of days, on our behalf.

Thanks for your input.

**Comment by drjwbaker** [comment]
The reassign implies that you will do the submission? If so, thanks.

**Comment by drjwbaker** [comment]
(if not, let me know!)

**Comment by acrymble** [comment]
Yes, sorry I thought you asked me to. I'll submit it.

**Comment by drjwbaker** [comment]
I did. Just double checking that you don't mind :)

**Comment by acrymble** [comment]
This has been submitted. Thanks for the input.
