### ISSUE TITLE
Andrew Mellon Foundation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1691]
I've done some digging and the Open Library of the Humanities got funding from the Andrew Mellon Foundation to support their sustainable financial development. I think we should look into this as an option for building our own sustainable base. 

Their Scholarly Communication Stream seems the most appropriate for us: https://mellon.org/programs/scholarly-communications/

It would be worth talking to Martin Eve who set up OLH, to see if he has any advice.

**Comment by acrymble** [comment]
Note this is liked to our Programme 3 goal from the business plan: To apply for core funding for 1.5FTE posts to project manage ProgHist ltd by August 2020, with the roles to focus on sustainability and project growth

**Comment by drjwbaker** [comment]
@acrymble Note the OLH grant went through Birkbeck https://mellon.org/grants/grants-database/grants/birkbeck-college/21500709/ not direct to OLH the charity (though it might be worth a conversation with Martin re how the finances broke down in reality). If we need to run this through a HEI, we need to think about *who* can/should/is able to lead the grant and then start bringing their Research Office on board to help prepare (my understanding of Mellon is that getting a grant from them is more an iterative process than a research council yes/no).

**Comment by drjwbaker** [comment]
For example, I suspect Sussex would be up for it and I could be PI. But I have next to zero grant writing capacity right now, so if we did that we might need to someone else from the team to write the grant on my behalf, and that person shouldn't be expected to do that for free.

**Comment by mdlincoln** [comment]
So it's true that Mellon has been investing heavily into scholarly publishing _platforms_ as of late, such as OLH's _Janeway_ project, _Manfiold_, and a few others. But the emphasis is on platforms that could support a wide array of publications in the field, not individual publications like ours: https://mellon.org/programs/scholarly-communications/electronic-publishing/

I'm not saying PH is an impossible fit, just that we're focused on our particular publications, and aren't necessarily building out a reusable technical platform like OLH is. Maybe there's a case to be made around designing a good translation workflow, but you'd need to really drill down and identify what PH would be bringing to the larger community.

**Comment by svmelton** [comment]
I concur with @mdlincoln—Mellon did a big round of funding scholarly publishing platforms in the past 3-5 years, but if we were to try to apply for something, we would really need to demonstrate how PH provides a model that is usable across lots of different types of publications. I don't think we're at that point yet. 

But I do think that continuing to partner with libraries, we may find some ways that we can build out this model a bit. (@mdlincoln, I think you're going to be at the Library Publishing Forum in May, right? I'll be there as well—perhaps we could think about how/if we want to talk about PH to some of the institutions that will be there.)

**Comment by mdlincoln** [comment]
@svmelton  I won't be in person - I think I'm just named on a paper - but a few of my colleagues will be there, I can try to put you all in touch!

**Comment by acrymble** [comment]
Thanks for the feedback @svmelton and @mdlincoln.

Can we position ourselves as creating a model for tech self-learning that's linguistically global? We're small now, but the idea is scalable.

**Comment by drjwbaker** [comment]
If we did that, what publishing infrastructure would the Mellon ultimately fund?

- A toolkit (a document https://themuseumsai.network/toolkit/) that provides a plug-and-play orginsational and documentation structure for multi-lingual open access publication?
- Generalisable technical infrastructure (based on https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Translation-Links)?
- A forkable github repo?

**Comment by acrymble** [comment]
My understanding of the Open Library of the Humanities is that Mellon funded a team to build a sustainable business model so that they could offer a service indefinitely. They aren't funding tech. They're funding startups.

**Comment by drjwbaker** [comment]
https://mellon.org/grants/grants-database/grants/birkbeck-college/21500709/

> to support the further development of a platform and editorial framework for open access journal article publication in the humanities

The money was to fund the model. My comment above was about that. What model would Mellon be funding by funding us?

**Comment by acrymble** [comment]
I think we're talking past each other.

We have a platform and an editorial framework for open access journal article publication in the humanities that relies heavily on sporadic and voluntary labour. We need support to transform that model into one that is sustainable and self-supporting like OLH is (thanks to the support of Mellon). I really don't see a difference.

**Comment by acrymble** [comment]
@drjwbaker none of this is necessary of course if you think the IPP can sustainably support a Project Manager (which is part of the business plan, and core to sustainability).

**Comment by drjwbaker** [comment]
> @drjwbaker none of this is necessary of course if you think the IPP can sustainably support a Project Manager (which is part of the business plan, and core to sustainability).

I don't think the can rely on IPP (though we have news, see the shared inbox!)

> I think we're talking past each other.
> 
> We have a platform and an editorial framework for open access journal article publication in the humanities that relies heavily on sporadic and voluntary labour. We need support to transform that model into one that is sustainable and self-supporting like OLH is (thanks to the support of Mellon). I really don't see a difference.

And I think what me @mdlincoln and @svmelton are querying is if what you seem to be proposing is what Mellon funds.

For clarity, I suspect the OLH bid was not ~"please help us make OLH sustainable" but "please help us make OLH sustainable + enable us to make OLH a model for sustainable model for OA in the humanities". I go back to the summary of the OLH grant..

> to support the further development of a platform and editorial framework for open access journal article publication in the humanities

..which reads - to me - as about supporting the development of generlisable platforms/frameworks, not just about supporting the development of OLH, hence why I asked what infrastructure beyond PH that we'd be asking Mellon - ultimately - to fund https://github.com/programminghistorian/jekyll/issues/1691#issuecomment-595731632.

Are we on the same page?

**Comment by acrymble** [comment]
Thanks for clarifying @drjwbaker. My understanding of what Mellon seeks to fund was different, so thanks for putting us on the same page. I think it would be worth one of us (I can volunteer because I know you're busy) reaching out to OLH for information on what was funded and what they might be willing to teach us. Are you happy for me to pursue that?

**Comment by drjwbaker** [comment]
I should clarify. I might be wrong. But that it my reading of what they fund.

**Comment by drjwbaker** [comment]
And yes, do pursue. I can't imagine that Martin would be unhelpful.

**Comment by amsichani** [comment]
Hi, this is an interesting idea to pursue and it would be great if we could reach OLH to learn what their bid was initially for.

**Comment by acrymble** [comment]
Just an update that I've reached out to Martin Eve for advice. He's not obliged to give it of course, so I'll report if I hear anything.

**Comment by acrymble** [comment]
I've heard back from Martin Eve who sent me his grant and an article he's written relevant to our search for fiscal sustainability. He's also suggested we contact JISC about having them offer our IPPs to libraries. I have some contacts there so I'm happy to do that (or to leave it to @drjwbaker when he gets back). @rivaquiroga and @jenniferisasi I think that's also relevant to #1658 so I will let you instruct me to either run with that idea or leave it for someone else already active in that area.

In terms of the Mellon grant, it's a bit of supporting technical bits and bobs, but it's mostly about making their "super journal" economically sustainable. They offered a much smaller startup grant before the big pot of money, so I do think it's a viable avenue for us.

Update: Sorry I made assumptions about JISC knowledge. It's a UK-based organisation that (among other things) manages library subscriptions and bulk-buy options for UK universities. They're like a store for digital content for libraries.

**Comment by drjwbaker** [comment]
> In terms of the Mellon grant, it's a bit of supporting technical bits and bobs, but it's mostly about making their "super journal" economically sustainable. They offered a much smaller startup grant before the big pot of money, so I do think it's a viable avenue for us.

I think it is a great idea. Realistically, who can take a lead on this? I can't right now. Sorry.

**Comment by amsichani** [comment]
I think too it's a great idea and I am happy to help in writing the bid - difficult for me to lead at this point.

**Comment by acrymble** [comment]
Just an update that I'm going to put this on hold until after I've been able to read and consider Penny Andrews' report for us. I think that should inform any funding bid directions. So I haven't forgotten. Just pausing.

**Comment by drjwbaker** [comment]
And to add: Penny's report is slightly delayed, partly due to Covid, partly because I managed to get their contract extended https://github.com/programminghistorian/jekyll/issues/1489#issuecomment-607254675

**Comment by acrymble** [comment]
I've shifted this to the wiki under funding opportunities (https://github.com/programminghistorian/jekyll/wiki/Funding-Opportunities). I may be able to return to it in future, but I don't think we're currently in a place where I can do this or that we're ready for it, in the next few months.
