### ISSUE TITLE
ProgHist Ltd Annual General Meeting 28 May 2020

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1694]
## ProgHist Ltd Annual General Meeting 28 May 2020

**Time: 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET**

**The AGM should last no longer than 2 hours**

### People

Chair: @acrymble

Secretary: @drjwbaker 

Voting attendees: all ProgHist Ltd Directors (@acrymble @drjwbaker @amsichani @svmelton @spapastamkou @rivaquiroga) and all who are ‘Member (Editorial Board)’ of ProgHist Ltd (@walshbr @mdlincoln @arojascastro @grandjeanmartin @jenniferisasi @fdlaramee @JoshuaGOB @JMParr @mariajoafana @vgayolrs @jamotilla @ZoeLeBlanc @mariechristineb)

Advisory attendees: one individual invited from each member of the [Institutional Partner Programme](https://programminghistorian.org/en/support-us#institutional-partner-programme) (@drjwbaker to invite)
- Laura Mesotten, KU Leuven Libraries
- Matthew Shaw, IHR Wohl Library

### Agenda

1. Apologies  
2. Chair's report @acrymble 
3. Treasurer's report @drjwbaker
4. Financial Planning Summary @drjwbaker
5. Managing Editors (MEs) & Directorship - should all MEs be directors? (for reference, 10/19 Directors meeting added MEs as Directors https://github.com/programminghistorian/jekyll/issues/1439#issue-490337849)
5. Actions arising from Funded Impact Manager Post #1489 report @drjwbaker 
	 - Andrews, Penny, & The Programming Historian. (2020, May 19). The Programming Historian: developing and sustaining impact in the Global South (Version 1.0). Zenodo. http://doi.org/10.5281/zenodo.3813763)
6. Any Other Business 
7. Agree date of next meeting

**PLEASE SUGGEST AGENDA ITEMS IN THE TICKET FOR INCLUSION**
Note, the remit of the Annual General Meeting is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- no quorum is required.
- motions should to be proposed and seconded before put to a vote.
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- every Member who is present in person (or by proxy) shall on a show of hands have one vote (Article 22)
	- we interpret 'in person' as being on the call, and we interpret 'show of hands' as any show of agreement or disagreement at the time of voting (the Chair as responsibility for making the mechanism for voting clear to members)
- if a motion is proposed (that is, something for the attendees to vote on), the Chair (@acrymble) has responsibility for making sure that said motion is appropriate. This should be done before the start of the AGM.
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))

**Comment by drjwbaker** [comment]
@rivaquiroga @spapastamkou @acrymble @amsichani @svmelton: we have external folks coming to this (IPP representatives), so we can't use of old familiar Skype channel for this meeting. Any objections to me setting this up as a Zoom call? (Sussex have an institutional subscription, so we don't need to worry about timeouts)

**Comment by svmelton** [comment]
Zoom works for me!

**Comment by rivaquiroga** [comment]
I'm sorry, but I can't make it this time.

**Comment by spapastamkou** [comment]
Zoom is ok.
Sofia

Le lun. 18 mai 2020 à 17:24, Riva Quiroga <notifications@github.com> a
écrit :

**Comment by acrymble** [comment]
Here is a copy of the Chair's Report, which I'll speak to in the meeting.
[ProgHist Ltd Chairs Report 2020.pdf](https://github.com/programminghistorian/jekyll/files/4671539/ProgHist.Ltd.Chairs.Report.2020.pdf)

**Comment by arojascastro** [comment]
Thank you, Adam! This report is very useful and has allowed me to understand some recent changes.

**Comment by drjwbaker** [comment]
Details of the Zoom call have been sent to all attendees. If you don't have the email, please let me know.

**Comment by drjwbaker** [comment]
On item 4., find attached my Financial Planning summary: [2020-05_ProgHistLTD-financial-planning.pdf](https://github.com/programminghistorian/jekyll/files/4695532/2020-05_ProgHistLTD-financial-planning.pdf)

Note: this document was updated 28/05/2020

**Comment by JMParr** [comment]
I am planning to be on the call, but will likely have to be without video/mainly listening in because another member of the household is going to be on a call.

**Comment by drjwbaker** [comment]
On item 3., I will attach the Treasurer's report to the call chat at the start of the meeting.

**Comment by JMParr** [comment]
Sorry, all. Having trouble with my connect. I'll read the minutes when
they're posted.

**Comment by acrymble** [comment]
The previous meeting minutes are in the Business repo for those of you with access and need to approve them: https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2020/02-2020/2020-02_ProgHistLtd-BoD.docx

**Comment by amsichani** [comment]
Hi all, I was waiting for a Skype call and I just realised that this meeting happened in zoom - sorry for any inconvenience caused. Waiting for the minutes now.

**Comment by drjwbaker** [comment]
> Hi all, I was waiting for a Skype call and I just realised that this meeting happened in zoom - sorry for any inconvenience caused. Waiting for the minutes now.

Not to worry. I keep expecting a Teams call, only to realise it was Zoom, or WhatsApp, or BlueJeans, or Skype, or something else. Oh, the complexity of pandemic working :)

**Comment by acrymble** [comment]
So sorry @amsichani. We will revert to Skype for future meetings (except maybe next year's AGM). We will try to send out a reminder email the day of next time to avoid the confusion.

**Comment by drjwbaker** [comment]
[ProgHist Ltd 2020 AGM minutes](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/AGMs/2020/2020_ProgHistLtd-AGM-minutes.pdf) are up. Please direct any corrections to me. The minutes and papers will be sent to IPP members for their records. Thanks all for attending!

**Comment by drjwbaker** [comment]
[2020_ProgHistLtd-AGM-minutes.pdf](https://github.com/user-attachments/files/29328251/2020_ProgHistLtd-AGM-minutes.pdf)
