### ISSUE TITLE
Spanish team combined authors & translation guide page

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1695]
Hey @programminghistorian/spanish-team I wanted to raise a question for you all that came up during #1673 :

There is no separate ES "translation guide" page. Instead there's the combined ["Guía para autores y traductores" page](https://programminghistorian.org/es/guia-para-autores). 

You may want to consider if you want to separate out your author & translator guide - it would be nice from the technical standpoint because it's the only exception to the patterns we have set up across the rest of the core pages. **It's not urgent**, but it is an exception to the regular pattern in PH technical infrastructure. Also you may want to have separate pages if you are intending to solicit more original es lessons in addition to translations.

**Comment by acrymble** [comment]
@mdlincoln the Spanish team is currently re-writing this as we implement styleguides. @rivaquiroga can we save Matt work here and separate these files?

**Comment by mdlincoln** [comment]
for future @programminghistorian/technical-team - will need to remove the if-logic around the menu once these pages are split out

**Comment by spapastamkou** [comment]
@jenniferisasi just commented on this in the PR #1673: https://github.com/programminghistorian/jekyll/pull/1673#issuecomment-593649644

To provide some context: the initial issue for creating translator guidelines, separating them from the author guidelines, was #1385. We then created separate tickets for the FR and ES guidelines. In the latter case, as Adam said, the ES translator guidelines overlapped with the ES copy-editing issue.

**Comment by jenniferisasi** [comment]
> @jenniferisasi just commented on this in the PR #1673: [#1673 (comment)](https://github.com/programminghistorian/jekyll/pull/1673#issuecomment-593649644)
> 
> To provide some context: the initial issue for creating translator guidelines, separating them from the author guidelines, was #1385. We then created separate tickets for the FR and ES guidelines. In the latter case, as Adam said, the ES translator guidelines overlapped with the ES copy-editing issue.

haha I deleted that comment cos I saw this issue 3 minutes later. Yes, I remember why we did it, and I believe if FR and EN already have it separate and eventually PT will have it, then we need it the same.

**Comment by rivaquiroga** [comment]
Sure. I don’t see any reason why not to separate them

**Comment by mariajoafana** [comment]
Hi, just making sure that someone in the Spanish team is taking over the task of separating the author and translator guidelines, anyone? I'm happy to take work on this with someone else

**Comment by jamotilla** [comment]
I can work with you @mariajoafana

**Comment by rivaquiroga** [comment]
@mariajoafana & @jamotilla, it would be great if you can work on this.

**Comment by jamotilla** [comment]
Of course @rivaquiroga I'll do it

**Comment by mariajoafana** [comment]
Voy a crear un pull request separado para crear la guía para traductores, ahí haré una primera versión de la guía para traductores para que @jamotilla la revise

**Comment by jamotilla** [comment]
Perfecto @mariajoafana !

**Comment by mariajoafana** [comment]
@jamotilla incorporé las correcciones que mencionaste y queda pendiente añadir la parte de puntuación y mayúsculas de la RAE

**Comment by rivaquiroga** [comment]
> for future @programminghistorian/technical-team - will need to remove the if-logic around the menu once these pages are split out

@programminghistorian/technical-team, the pages are already split in https://github.com/programminghistorian/jekyll/pull/1771.
