### ISSUE TITLE
Link to Reg Ex lesson from Applied Archival Downloading

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#17]
The section on downloading Bligh's diary could probably revised with a link to the Regular Expressions lesson so that readers can capture pages that contain letters as well as numbers in the script.

**Comment by acrymble** [comment]
can one of our Summer Fellows help us with that? That's a fairly good task.

**Comment by ianmilligan1** [comment]
I added a link to the lesson. A more substantial edit would be a great task for a fellow or somebody else, just to note a potential implementation. But in meantime, the link should get our readers thinking..
