### ISSUE TITLE
extracting-keywords.md

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#170]
You may wish to note that on opening `The Dataset - Alumni Oxonienses - Jas1.csv` with your favourite spreadsheet package that separators need to be set to comma and text delimiter field needs to be set to `"` (at least that is the case for LibreOffice). I only note this as you have a .csv file with commas that are not delimiters, which can be tricky to resolve.

**Comment by acrymble** [comment]
Thansk @drjwbaker I will take a look at this.

**Comment by acrymble** [comment]
updated. Thanks @drjwbaker
