### ISSUE TITLE
App/platform for shared storage of financial/business/team documentation

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1700]
All - we have a bus factor in that I hold on our financial/business documentation for PH Ltd but that we can't quite figure out a *secure* (and GDPR compliant) place to keep this all in a shareable form.

Does anyone have any thoughts, experience, suggestions in this area?

One option is to pay for Box https://www.box.com/en-gb/pricing because it is cheap(ish), GDPR compliant, and trusted as secure (our university use it as an enterprise service, so it must be, you'd hope.....)

Alternatively @programminghistorian/technical-team if you could get some use out of private repos for other purposes, we could move to paying for GitHub https://github.com/pricing for storing these docs (because as we found out at https://github.com/programminghistorian/jekyll/issues/1426#issuecomment-527171411, we need to pay to get more than 3 collaborators on a private account).

**Comment by drjwbaker** [comment]
Also relates to https://github.com/programminghistorian/jekyll/issues/1482: we could do with reducing the bus factor on the offline archive of PH documentation.

**Comment by walshbr** [comment]
UVA also has a box subscription, and I could certainly toss things up there. Our file storage limit is obscene. But it sounds like you're after a purely ProgHist hosted solution, right?

Alternatively (and if you haven't already looked into it) we might think about applying for a GitHub education discount, which I think comes with free repositories. I think we'd qualify, and IIRC the process isn't too difficult.

**Comment by drjwbaker** [comment]
Yeah, I'd rather not rely on one of the services our universities subscribe to as those are - ultimately - personal accounts linked to individuals.

If @programminghistorian/technical-team could use private repos for other things, an edu discount could be worth pursuing.

**Comment by acrymble** [comment]
I think we should directly ask Github to give us an in-kind private subscription so we can run our journals on it. I suspect we're one of the only such examples in the world and something they may well want to support.

**Comment by drjwbaker** [comment]
Ambitious thinking. Do you want to ask?

**Comment by walshbr** [comment]
Just to be clear: it's been some time since I specifically signed up for a GitHub education plan, but I remember it being very, very easy. And it does what I think you're asking @acrymble. I remember it being a form that you fill out, and it took fifteen minutes. I could do it, but I think it might be need to be @mdlincoln, as I suspect he is listed as the owner/administrator of our GitHub organization.

**Comment by acrymble** [comment]
@walshbr can you find the link for us?

**Comment by walshbr** [comment]
Looks like it cares more about institutional affiliation than I remembered, but since we have many institutional affiliations it might be alright for one of you to apply for yourself and upgrade the team by association - 

https://help.github.com/en/github/teaching-and-learning-with-github-education/applying-for-an-educator-or-researcher-discount

**Comment by drjwbaker** [comment]
Private repos for unlimited users is now free https://help.github.com/en/github/getting-started-with-github/faq-about-changes-to-githubs-plans. And Github has GDPR compliance https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/entering-a-data-protection-agreement-with-github-for-gdpr-compliance. Which means that I can move the offline archive to a private repo, both for the Project and for the Ltd.

Unless I hear any objections, I'll make a plan to migrate this material. Specifically:

- [x] open a private repo ('Project and Business Archive')
- [x] migrate the offline archive to the private repo
- [x] delete the offline archive listing from the public repo (PR raised https://github.com/programminghistorian/jekyll/pull/1750)
- [x] plan to make regular (at least weekly) commits with listing of remaining private repo (financial details)
- [x] update the service integrations description

**Comment by drjwbaker** [comment]
I should add, at a reduced $4 per month it may still be worth getting Pro anyway. Or investing the edu account, as @walshbr suggested.

**Comment by drjwbaker** [comment]
Right. This is now done. A private repo is at https://github.com/programminghistorian/project-and-business-archive. A couple of notes on process: 

- Seen as I manage this archive, I'm proposing to just push docs to the repo, rather than open pull requests.
- I'm keeping some docs offline, mostly finance related docs that contain private and sensitive info (bank account numbers).

Are we happy with this? If so, I'll close the issue.

**Comment by acrymble** [comment]
Is it documented and bus-factor proof? If so, yes.

**Comment by drjwbaker** [comment]
Documentation is on the service integrations page.

Bus-factor, nearly. Finance docs with private/sensitive info are only listed, not on the repo. Still struggling with an ideal solution to that (unless it is something like a Dropbox/Box folder that only Ltd Directors have access to).

**Comment by acrymble** [comment]
Why don't we bite the bullet and just keep 3 physical copies and use the Royal Mail ever 3 months? One for me, you and Anna Maria kept in hard copy until we get a better idea?

**Comment by drjwbaker** [comment]
I don't have access to a printer.

**Comment by acrymble** [comment]
I do (and presumably you will eventually when you get back to the office). Is the volume high? Would it be feasible for me to print and disseminate it in hard copy?

**Comment by drjwbaker** [comment]
Volume isn't high. See the listing at https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Finances. We are talking: the accounts + invoices received/issued.

**Comment by amsichani** [comment]
I don't have a printer either. It might be clever to keep hard copies , but I don't know if this would be a sustainable option.

**Comment by acrymble** [comment]
Should we do a trial and then decide based on that?

**Comment by drjwbaker** [comment]
Sure. @acrymble: if I email you the docs in question can you print circulate this quarter?

**Comment by acrymble** [comment]
Sounds good.
