### ISSUE TITLE
Portuguese Core Pages Plan

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1708]
I had a meeting with the Portuguese team about translating core pages, and have helped them set up a plan for doing this efficiently. They will be translating from English to Portuguese. I've asked them to inform us in one-month blocks of which pages they will be translating at any given time. This will allow us to freeze any changes while they are working, without requiring us to stop work all together.

I will begin collecting pages and helping them learn how to upload them as content comes in.

We have a few tickets open at the moment that could result in changes to current pages. I suggest we aim to resolve those open tickets soon so that the Portuguese team can move forward. They are:

* Spanish/French Copyediting Setup #1635 #1336 (affects author-guidelines.md)
* DOIs and lesson retirement / updating policy #1682 (affects retirement-policy.md, contribue.md, feedback.md)
* Identity - Journal vs Website #1682 (possibly affects index.md, about.md, contribute.md, author-guidelines.md, support-us.md)

**Comment by JMParr** [comment]
Hi, @acrymble - this seems more like it's in the Tech Team's domain than Global's.

**Comment by acrymble** [comment]
@JMParr that's worth raising at the next meeting. Whose job is it to follow through with a new publication team? It was pursued by Global, and I don't think there are many tech implications. It's important we all agree who is doing the work.

**Comment by JMParr** [comment]
We can also delegate some of this to other members of the Global Team. @rivaquiroga or @spapastamkou , do either of you have the bandwidth to take tracking these ticket on?

**Comment by acrymble** [comment]
The latest update is that they are formulating a plan and will communicate it when they are able.

**Comment by rivaquiroga** [comment]
@acrymble, I can support on this, but after this week.

**Comment by acrymble** [comment]
I don't think this ticket is actually being used to keep track of what the Portuguese team is working on. I am going to close it and @JoshuaGOB and @DanielAlvesLABDH can open new tickets as appropriate to keep track of their progress.
