### ISSUE TITLE
Jessica Parr sabbatical

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1715]
Due to other pressures and commitments related to the current virus, @JMParr is going to take a 1-month sabbatical until 15 April 2020 (in the first instance). @JMParr if you're able, could you list any tickets or reviews you're working on so we can find cover?

We look forward to your return.

**Comment by acrymble** [comment]
I've had a chance to go through tickets. The following include either Jess or the Global Team (which she leads):

- #1681 Portuguese Team Shadowing Practice (being managed by @acrymble - with support)
- #1704 Service Agreement between ProgHist Ltd and Publications (this can wait as it will be a longer conversation)
- #1708 Portuguese Core Pages Plan (being managed by @acrymble - with support)
- #1710 Portuguese Title Checklist (being managed by @acrymble - with support)

**Comment by acrymble** [comment]
Jess is also an editor on one lesson in production: https://github.com/programminghistorian/ph-submissions/issues/278. I've left a note on the ticket that she'll be unavailable. @svmelton please can you make sure everyone is kept informed and supported on that one?

**Comment by drjwbaker** [comment]
Who will be the contact for the Global Team during this sabbatical?

**Comment by acrymble** [comment]
We'll have to leave anything new until she gets back, I think. If you need to, I can step in for anything on going, but times may be longer than normal.

**Comment by drjwbaker** [comment]
Okay. Thanks for clarification.

**Comment by acrymble** [comment]
@JMParr Can you update us on timelines when you're able, just so we can plan?

Thanks and hope you're well.

**Comment by acrymble** [comment]
@JMParr can you check in please? I haven't heard from you so I don't know what your situation is currently.

**Comment by JMParr** [comment]
Hi, @acrymble I'd mentioned my return in a separate email, but forgot to post on the Github. I will be back off sabbatical this coming Monday.

**Comment by acrymble** [comment]
Sorry @JMParr I must have missed the email. It will be great to have you back. I'll close this ticket and we'll look forward to having you next Monday.
