### ISSUE TITLE
April Technical team meeting: Monday April 13

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1722]
Monday, 13 April 2020, Time is 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET

@JoshuaGOB would like to join us as well to discuss Portuguese team onboarding

Agenda:

- [x] Portuguese team onboarding @JoshuaGOB 
- [x] demo of full-text search options #1720 and #1726 @ZoeLeBlanc 
- [x] (time-permitting) update on DOI discussion @mdlincoln

**Comment by mdlincoln** [comment]
Thanks everyone for submitting availability. The final date is Monday, April 13

**Comment by jenniferisasi** [comment]
Fantastic job @ZoeLeBlanc! I like how #1726 highlights the words it finds. 

Small note: the search bar words are now in English, will have to translate if possible once we decide which one keep.

**Comment by ZoeLeBlanc** [comment]
Thanks @jenniferisasi! Definitely will need to translate search bar words and search button (also let me know if you have other ideas for those... wasn't quite sure what to put 😅). 

Let me know if there's any bugs you find when searching, whether with results or not refreshing the html. Thanks for testing it out 😊

**Comment by amsichani** [comment]
(time-permitting) I 'd like to give you a quick update on my thoughts- future actions on https://github.com/programminghistorian/jekyll/issues/1525  and https://github.com/programminghistorian/jekyll/issues/1526

**Comment by mdlincoln** [comment]
@rivaquiroga we're on at https://join.skype.com/T6ex4gQnxOuc

**Comment by mdlincoln** [comment]
Decisions:

- Portuguese translation
    - @walshbr will the be @programminghistorian/technical-team first responder for questions from the Portuguese editorial team. (Not that he will resolve every single qeusiton, but will at least field initial problems)
    - @mdlincoln will create a branch with a copy of files for portuguese team to begin translation of core pages
    - General documentation on how to create new translation branches on wiki #1737
- @amsichani will close #1526 
- @amsichani will continue work on #1525 
- FTS
    - Will go forward with #1726 solution
    - @programminghistorian/technical-team will usertest and report all issues on PR comments NO LATER THAN 2020-04-20, after which @ZoeLeBlanc will assess and input final changes
    - We'll want to do a blog post and wii documentation voerview of howt he code works at a high-level too

**Comment by walshbr** [comment]
@mdlincoln - should those questions/concerns about the Portuguese translations come in through the PR thread on the branch you set up? or through email?

**Comment by mdlincoln** [comment]
Let's try to keep the process in the GitHub PR (once I make it) as much as possible.

**Comment by mdlincoln** [comment]
@JoshuaGOB when will the PT team be ready to start work? We'll need to generally lock the editing of our core pages so they can finish teh translations without the content constantly changing under them.

**Comment by mdlincoln** [comment]
Should have closed this one a long time back...
