### ISSUE TITLE
Institutional Partner Programme in a time of crisis

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1732]
This ticket is breaking off from a discussion on a gdoc @jenniferisasi kindly put together that will form the basis of our comms to libraries/institutions 'advertising' our IPP.

@walshbr & @svmelton are of the opinion that we give a little more back in return than what we currently have listed at https://programminghistorian.org/en/support-us#institutional-partner-programme

We previously (though I can't find the tickets) avoided making too many promises in return for Patreon or IPP £, but given this time of crisis, I suspect we might revisit that.

One option which I like, to borrow/adapt from @walshbr, is to have some kind of regular community calls (either themed or as no agenda 'office hours') where one of our team offers support to IPP members: e.g. tips on how to adapt our materials to develop a workshop, advise on OA publishing, gather ideas about articles people need, et cetera.

I suspect there is a way of doing that that is:

- low effort.
- gives something tangible back to IPP members.
- helps us learn from our community.
- develops our offer.
- is creative, enjoyable, and fun without us straying too far into things we don't really want to do right now (troubleshooting articles, giving out loads of free advice, becoming a training provider)

Thoughts?

**Comment by acrymble** [comment]
I support this idea. Thanks @walshbr. I think this should be paid for activity.

**Comment by drjwbaker** [comment]
> I think this should be paid for activity.

To clarify this comment, you mean it should be the sort of thing we offer to IPP members at no extra cost?

**Comment by acrymble** [comment]
I mean I think whomever does this work for us (which is essentially a fundraising activity) should be paid to do it. Like copyeditors are. (Update: it's really a suggestion that any new tasks we create from here on in should be - in my view - budgeted and paid for)

**Comment by drjwbaker** [comment]
> I mean I think whomever does this work for us (which is essentially a fundraising activity) should be paid to do it. Like copyeditors are.

Oh. Okay.

**Comment by walshbr** [comment]
I agree - I'd think of it as a fundraising activity that a person is compensated slightly for, even though the vast majority of the funds go to PH. To go off what @acrymble suggested, it might be worth thinking about what a reasonable rate of compensation would be for the people hosting the sessions. And what the content would be -  seems like there have been several types of workshops related to PH that we've run over the years.

I do like the idea of holding community workshops, which is a better model than tying IPP . This is sort of a model borrowed from music kickstarters, patreon, etc., when a group offers a house concert in return for a certain level of support. Those concerts don't generate money from nothing, but can really be thought of as trying to create a vehicle to encourage further work in a way you want to take on. So in this case, we'd essentially be encouraging IPP partners to commit to funding a PH session for their community, with the vast majority of the proceeds going back to PH. It's extra work, but if we're able to modestly compensate the team member taking it on they might be more inclined to do it.

**Comment by acrymble** [comment]
@walshbr you mean in-person events that we send someone to? That sounds expensive.

**Comment by walshbr** [comment]
No - I was thinking about online community events like the sort of thing that you both were describing. Could be worth thinking about in-person events as a separate tier, if you really wanted to include stretch goals. But I like the model @drjwbaker was describing above.

**Comment by acrymble** [comment]
This will also have to take into consideration who will manage this process, and how much time that will take (plus chasing around to get someone to commit to hosting it and making sure they show up).

**Comment by drjwbaker** [comment]
So, I like the ideas here as things to grow into, but I was thinking of something quite simple in the first instance: a monthly virtual call/workshop run by us and available to IPP members only as 'added value' for their IPP membership.

I like the idea of doing something that brings in wider communities, but I don't think we have the capacity for that right now.

Are we roughly on the same page here?

**Comment by walshbr** [comment]
Yes I think so.

**Comment by acrymble** [comment]
I don't work in a library. Are they likely to show up for a call we schedule? (Update - sorry I think that was too brief to get my question across: I thought the original suggestion was to offer a consultation with them at their convenience? I suspect, but don't know, that would have a higher take-up).

**Comment by svmelton** [comment]
A scheduled consultation would have more uptake, but I do know that lots of people in libraries are interested in virtual professional development opportunities. Or even community gatherings—several professional orgs I'm in have had calls in that vein that have been well-attended. 

...With the caveat that right now, schedules may be a bit more flexible if we were to just schedule a call, but that may not be true going forward.

**Comment by drjwbaker** [comment]
Okay. I appreciate the input. Compromise. Monthly community calls on request. So, we don't have a scheduled a monthly call. Rather, if an IPP member wants to consult with us, we schedule a call on a date that works for them (around our usual 3pm GMT, 11am EST time), and invite all other IPP members (I guess we could make them open calls if the IPP member who made the request is happy?). To manage our effort, we commit to a maximum of 12 calls per annum. And to ensure that this isn't an empty offer, we prod IPP members periodically (quarterly?) to remind that this exists. Does that work for people? If so, we can get some rough text to @jenniferisasi for the IPP mailout, and then work on the specifics.

**Comment by acrymble** [comment]
If that's how you want to promote the IPP that's fine with me. Who will host the calls?

**Comment by drjwbaker** [comment]
> Who will host the calls?

In the first instance, I can do this seen as I've been working on the IPP and have good overall sense of how we operate.

**Comment by acrymble** [comment]
Ok thanks. Can you be careful not to bind us long-term to this, in case either it proves something we don't want to continue, or you decide you can't do it and we haven't got a replacement?

**Comment by drjwbaker** [comment]
Sure. I'll propose some vague wording for the IPP email.

**Comment by drjwbaker** [comment]
Done. See gdoc. @svmelton: I couldn't work out your gmail so as to tag you properly.

**Comment by drjwbaker** [comment]
Next action (for me) is to add some wording on this to our IPP pages, and document as a service integration.
