### ISSUE TITLE
List of Holidays / Religious Days

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1739]
I'd like to put together a list of days during the calendar year that we should avoid holding meetings on, on the basis that they are either a religious or a civic holiday for one or more of our team members. Can I ask that everyone on the @programminghistorian/project-team help me put together this list, as this varies widely by country and none of us should expect everyone else to know.

Let's be practical and only include ones that are pertinent to us. Otherwise I'm sure we'd find something significant about every day.

I can start:

- 1 January (New Years Day)
- Mid-January variable (Martin Luther King's Birthday/Civil Rights Day - USA) added by @JMParr 
- Mid-February (Washington's Birthday - usually falls around the 15th - USA) added by @JMParr 
- variable (Easter - good Friday & Easter Monday)
- 1 May (Labour Day - most EU countries)
- 8 May (Bank Holiday - UK)
- 25 May (Bank Holiday - UK)
-  Last Monday of May (Memorial Day - US) added by @JMParr 
- 24 June (Fête Nationale du Québec) added by @fdlaramee 
- 1 July (Canada Day) added by @fdlaramee 
-  4 July (Independence Day - US / celebrated on the Monday if the date is a weekend) added by @JMParr 
- 31 August (Bank Holiday - UK)
- First Monday of September (Labour Day - Canada and USA) added by @fdlaramee
- Early October - variable (Indigenous Peoples Day/Columbus Day - USA) added by @JMParr 
- 11 November (Veterans Day - USA) added by @JMParr 
- Third Thursday of November (Thanksgiving - USA / Most people are off on the Friday as well) added by @JMParr 
- 25 December (Christmas - UK & USA)
- 26 December (Boxing Day - UK) (Note from @JMParr - most USA colleges/universities are closed from around 23 Dec - 2/3 of January).

**Comment by drjwbaker** [comment]
Early May, Spring, and Summer bank holidays move around in the UK (and we get extra ones if Christmas, Boxing Day or NYD fall on a wekend. Best source of info is https://www.gov.uk/bank-holidays.

**Comment by JMParr** [comment]
I'll add religious holidays here, since this could affect both team members as well as authors and collaborators(all variable dates):

- Jewish:https://pjcc.org/jewish-life/jewish-holidays-explained/
- Muslim: https://www.birminghammail.co.uk/whats-on/whats-on-news/islamic-calendar-2020-muslim-holidays-14109325
- Hindu: https://www.learnreligions.com/hindu-festivals-calendar-1770190
- Buddhist: https://agsci.psu.edu/diversity/events/diversity-calendar/buddhism

**Comment by amsichani** [comment]
That s a great initiative/start in line also with our inclusive/internationisatioon strategy. Just to make it clear: are we going to list the various religious/cultural/national celebrations for our @programminghistorian/project-team or also our users?

**Comment by JMParr** [comment]
> Early May, Spring, and Summer bank holidays move around in the UK (and we get extra ones if Christmas, Boxing Day or NYD fall on a wekend. Best source of info is https://www.gov.uk/bank-holidays.

We've got a couple of those here in the USA - if the dates for Washington's Birthday, the 4th of July, or Indigenous People's Day/Columbus Day falls on a weekend, it's often observed on the Monday.

**Comment by JMParr** [comment]
> That s a great initiative/start in line also with our inclusive/internationisatioon strategy. Just to make it clear: are we going to list the various religious/cultural/national celebrations for our @programminghistorian/project-team or also our users?

@amsichani I just added some links to religious holidays for major global religions.

**Comment by acrymble** [comment]
The purpose right now is to avoid our own meetings on these dates @amsichani. So it should be the shortest possible list of dates that affect our members only.

**Comment by drjwbaker** [comment]
Given that many of these days change each year, and we aren't the only org to have to navigate these challenges, is there not an API (or multiple) we can plug into to generate a page (rather than us manually update a page) we can refer to when booking meetings? Gov.uk have a public holidays API that will cover the UK side https://www.gov.uk/bank-holidays.json

**Comment by acrymble** [comment]
Thanks for the suggestion @drjwbaker. I asked on Twitter and Ulrich Tiedau has suggested the calendars on Google Calendar (for anyone that uses those). I've just added (I think) the regional holidays for every country one of our members live in. I think it also includes minor holidays (like St George's Day in England), but it's a start.

I think we only have a handful of people who set meetings. Would everyone who does be willing to use that feature to try to avoid special days for people when setting up doodle polls or scheduling meetings? I'm thinking of @mariajoafana @drjwbaker @svmelton @rivaquiroga @spapastamkou @JMParr @jenniferisasi Me, and @mdlincoln in particular?

**Comment by JMParr** [comment]
Yes, I'd be happy to use that feature.

**Comment by svmelton** [comment]
I'd also be happy to use it!

**Comment by rivaquiroga** [comment]
Yes!

**Comment by drjwbaker** [comment]
Okay.

**Comment by acrymble** [comment]
If you need to know how to do this, you have to add other calendars (on the left pane on my version). You can then 'browse calendars of interest' and choose the 'regional calendars' for the relevant countries. I added the UK, Canada, US, France, Mexico, Colombia, Chile, Germany, Switzerland, Brazil, and Portugal. Did I miss any?

**Comment by drjwbaker** [comment]
@acrymble I've added all these to the programminghistorian@gmail.com calendar, which we can keep updated as a resource. My concern is that - just looking at the UK days - not all listed on there are actual holidays: e.g. 23 April is St George's Day but that is not a holiday. I don't know if that same is true for 'Day of Trees' in Colombia, or 'Ascension Day' in Germany. If so, this won't be that useful for planning meetings.

**Comment by acrymble** [comment]
@drjwbaker agreed. Not perfect. But easier than creating from scratch, as you suggested.

**Comment by mariajoafana** [comment]
During Easter week, in Colombia, and I guess in all Latin America, we observe not only good Friday but also Thursday, they are "jueves y viernes santo"

**Comment by acrymble** [comment]
I don't want this to be a huge chore out of this. But can we use this as a starting point when setting a doodle poll? Consider who you're inviting to the meeting and have a quick check of the calendars to see if those people might be affected by holidays?

And if anyone finds a meeting scheduled on a holiday for you, please just let the meeting organizer know. We won't always be able to avoid everything, but we can all make an effort to be more globally aware.
