### ISSUE TITLE
PH in Google Scholar

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1742]
I was wondering why not all our lessons appear in Google Scholar: https://scholar.google.com/scholar?start=0&q=source:Programming+source:Historian

Is there anything we can do to fix this? 

I found an old issue about the same subject: https://github.com/programminghistorian/jekyll/issues/190

**Comment by mdlincoln** [comment]
They will once we are indexed by crossref with the doi process.
