### ISSUE TITLE
Content and interface accessibility

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1743]
Question related with #1659 but of more general interest. Does the PH have / is interested in defining a policy or think on accessibility issues?  

I can think of two cases, but there are surely other ideas to come. 
- [ ] Limited Internet connections and speed (this is openly asked in the document of the grant I've been working on recently). Having a static website is an advantage from this point of view, but would something like proposing an open export format like epub be helpful form this point of view (if technically possible)? @programminghistorian/global-team @programminghistorian/technical-team 
- [ ] Accessibility issues for people with disabilities. @programminghistorian/technical-team

**Comment by drjwbaker** [comment]
Note, I suspect accessibility will come up in Penny's report #1489

**Comment by acrymble** [comment]
I just remembered we did some work on this last year. #1315 There may be something useful there.

**Comment by JMParr** [comment]
Hi, All -
Sofia, thank you for raising this. And, Adam, thank you for posting that
ticket. I'd missed that conversation last May, because it was right after
my surgery. Do you know if the issues with machine readability that you
were working on addressing were resolved?

**Comment by spapastamkou** [comment]
I am not sure this can go further than that for the moment. If someone thinks otherwise, please reopen this ticket.
