### ISSUE TITLE
Policy on scientific integrity issues

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1744]
Question related with #1659 but of more general interest. 
Are we interested in adding a small section in the About page on integrity issues such as plagiarism and data fabrication? 

I think that commitment to openness and community minimizes any such risk but yet, does the team think that this is something important that would worth some kind of mention there?

**Comment by acrymble** [comment]
I don't know that this is an issue with our type of publication. We aren't publishing scientific results. We're publishing method. So data fabrication isn't going to undermine the value of a work in the same way. Not that we'd want to encourage it.

**Comment by spapastamkou** [comment]
I think we've nothing more here, so we are ok.
