### ISSUE TITLE
Furloughed Staff query

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1746]
I have no idea the implications of this, or if it's a good idea or not. But in the UK there are currently thousands of people who have been 'furloughed' in a government scheme whereby 80% of their salary is paid by the state temporarily, to keep people employed rather than putting them on unemployment benefits.

Since many cultural heritage organisations such as libraries have had to close, I suspect there are some furloughed people with expertise that we lack, who might like to volunteer with a not-for-profit press like us. I'm thinking people who might be able to help us develop library-focused strategies such as getting our journals into libraries, adopting appropriate metadata standards, or otherwise understanding the needs of libraries.

Does anyone have a view on this? Would we be wise, foolish or otherwise to suggest we would like some targeted help from someone who may or may not be furloughed at this stage? Am I not considering something?

**Comment by mdlincoln** [comment]
Nice idea. But this generates a lot more organizational tasks for our project team to figure out. That's a considerable consequence, given how many of our tickets in the past year are still dealing with creating new work for ourselves.

Instead of trying to channel volunteer energy towards brand new work and new workflows, why not channel it towards our core competency of publishing new lessons? We don't have to figure out brand new workflows for that. Could be a good time to try and solicit experts to submit to us.

**Comment by drjwbaker** [comment]
> Could be a good time to try and solicit experts to submit to us.

**If** their expertise in a given area does not cross a line into the very thing that is being furloughed. In short, I don't want to be seen to encourage people to break furlough. In the UK, at least, it seems kinda strict what counts as not acceptable during furlough. Either way, I support the idea of driving engagement, interest, effort if people are bored, sufficiently well (mentally and physically), and so feel the desire to contribute something to us.

**Comment by acrymble** [comment]
Thanks for the important workload implication reminder @mdlincoln .

I like your idea, but I wouldn't want to pursue it without the permission of @svmelton @rivaquiroga @spapastamkou because that might push them beyond their own capacity. Do any of our MEs think they could handle a bit of a push on submissions at the moment?

@mdlincoln I wonder also if we might just go a simple route of asking for advice on or help on some of our stuck tickets. Things like the Plan S one that involve a lot of components with specialist knowledge behind them? #1370. Or maybe see if someone is available to help us with a draft of the French Styleguide #1636 or things like that?

**Comment by mdlincoln** [comment]
What's stuck on plan S?

**Comment by svmelton** [comment]
Speaking for the EN team, we've received at least 5 pre-proposals or proposals over the last two weeks. I'm not sure our team has the capacity (or if it would be wise!) for us to recruit more submissions right now, but we *are* almost ready to send out an announcement to recruit more editors.

**Comment by drjwbaker** [comment]
> Speaking for the EN team, we've received at least 5 pre-proposals or proposals over the last two weeks. I'm not sure our team has the capacity (or if it would be wise!) for us to recruit more submissions right now, but we _are_ almost ready to send out an announcement to recruit more editors.

In the spirit of this ticket (and I'm not involved in editing so please feel free to ignore me), would we be willing to take on temporary editors who have capacity now (because furlough) but wouldn't later (because full time job)?

**Comment by acrymble** [comment]
@mdlincoln I'm a bit confused by that question. It looks to me like the whole ticket is stuck. It's been open for almost a year. It's one of a number of very old tickets, which could mean lots of things.

Maybe we lack capacity. Maybe some people don't feel empowered to close or take the lead on tasks. Maybe some people are overly optimistic about what they can contribute. Maybe some people are being assigned tasks they aren't interested in. I'm not sure which (or what else) may be the case for those tickets.

I just wondered if there might not be some expertise and people with time out there right now to help us clear the decks a little.

**Comment by rivaquiroga** [comment]
If there are people willing to submit in Spanish, we can handle editing a couple of lessons.

**Comment by acrymble** [comment]
@drjwbaker maybe there's also someone out there who could help us upskill on the mechanics of running a not-for-profit? Things like gov't paperwork, payments, the annual cycle, etc? I think you're on research leave, but if there are knowledge gaps we have, maybe I could see if anyone out there can help me learn them so I can pass the knowledge on when you've got more time?

**Comment by drjwbaker** [comment]
Thanks for the suggestion @acrymble: any voluntary support I could get from experts in HR, non-profit admin, business finance would be enormously gratefully received, especially in setting us up to run more efficiently. I'm far from drowning, but I can see the limits of my expertise and capacity coming in the next 12-18 months.

**Comment by drjwbaker** [comment]
(happy to work on a call for voluntary expertise, though, as you say, I am on research leave..)

**Comment by svmelton** [comment]
> In the spirit of this ticket (and I'm not involved in editing so please feel free to ignore me), would we be willing to take on temporary editors who have capacity now (because furlough) but wouldn't later (because full time job)?

I know it's impossible to say how long furloughs will last, but my hesitation here is that it usually takes us at least 2 months to go from a proposal to a submission. I'm not sure that we would have submissions coming in by the time people might be back to work.

That said, if there are people willing to step in for a short time, we could likely find something for them to do. But I'm not sure the timing would quite work out.

**Comment by drjwbaker** [comment]
> but my hesitation here is that it usually takes us at least 2 months to go from a proposal to a submission.

Fair point.

**Comment by spapastamkou** [comment]
To answer the question on our (=FR) capacity to take up new submissions: up until now, we haven't said no to anyone who voluntarily offered translations. We do however have a limited capacity of editing and a pile of translations that are waiting for. We are going to exchange soon in the FR team to see how we can remedy to this.

**Comment by acrymble** [comment]
Ok. I think the message I'm taking from this (and thanks everyone for feedback) is that there aren't many things we can bring someone in on easily because everything requires training.

But there are a few areas where people might be able to contribute expertise or knowledge, and that we can pursue that through social media requests. I'll liaise with @jenniferisasi about how we might tweet that out effectively.

Thanks all.

**Comment by drjwbaker** [comment]
Thanks @acrymble: expertise needed in HR, non-profit/charity admin, finance/tax please :)

**Comment by amsichani** [comment]
If I can add, it might be clever to also adopt a new strategy for our peer reviewers' recruitment: as we are probably going to have multiple EN lessons' submissions in the next couple of weeks/months , we might be able to ask for specific expertise for reviewers (computer vision, image processing etc) . Perhaps @svmelton might help on this.

**Comment by acrymble** [comment]
I'm going to collate the ideas here and take them forward in new tickets, since this particular idea (coopting a new temporary team member) doesn't seem viable:

- Tweets about new Spanish lesson proposals sought
- training for editors on finding peer reviewers
- training for @drjwbaker on HR, not-profit/charity admin, and UK finance & tax regulations.

**Comment by acrymble** [comment]
With thanks to everyone for their contributions (and warnings). I'm going to close this idea now and we'll take the other ones forward.
