### ISSUE TITLE
New translations workflows: Spanish > EN, FR / French > ES, EN

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#1747]
Until now, the only translations we have done are from English to Spanish, and from English to French. As Programming Historian en Español has three original lessons already published and a couple more on their way, it seems a good idea to start planning how we are going to manage this new translation workflow from Spanish to EN and FR. 

Currently, our model involves having editors proficient in English for editing the translations from EN to ES and FR. This model has worked: we have around 50 translations published between ES and FR teams. So recruiting editors that also speak Spanish seems to be the best way to handle this. When the FR Team starts publishing original lessons, the rest of the teams should consider recruiting French speaking editors as well.

As the English team hasn't make any translations yet, for the shadowing process new team members could be paired with a Spanish editor to get involved with the translation workflow. 

It would be great to read the thoughts of EN and FR teams about this.

**Comment by svmelton** [comment]
This makes sense to me! I'll also note that in our call for new editors, we're putting Spanish and/or French as a desired skill.

**Comment by spapastamkou** [comment]
All the ideas expressed here make perfectly sense @rivaquiroga. 
Just for info, in our previous call for editors for the FR team we had already designated knowledge of Spanish as a particularly appreciated skill and we will of course do it again in the future. The person who had this skill was unfortunately not able to join us in the end. I hope we will eventually find someone in the future.

**Comment by acrymble** [comment]
@rivaquiroga It looks like the action here has been agreed, yes? That the English and French teams will make efforts in future recruitment to bring on some bilingual team members and the other teams will help train in translation tasks? Can we close this then?

**Comment by rivaquiroga** [comment]
Sure!
