### ISSUE TITLE
ProgHist Ltd Board of Directors Meeting 17 June 2020

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1748]
## ProgHist Ltd Board of Directors Meeting 17 June 2020

**Time: 9:00 AM - Mexico time; 10:00 AM - EST; 3:00 PM - British time; 4:00 PM - CET**

Chair: @acrymble
Secretary: @drjwbaker 
Members: @amsichani @spapastamkou @drjwbaker @svmelton @rivaquiroga 
Minutes of the last meeting: these are not posted publicly. Please see your email from @drjwbaker 13 February 2020.

### Agenda

1. Apologies  
2. Approval of Minutes from last meeting & actions status   
3. ProgHist Directors administration (e.g changes of address)
4. Finance update @drjwbaker
5. Institutional Partner Programme update @drjwbaker 
6. Actions arising from AGM https://github.com/programminghistorian/jekyll/issues/1694 @acrymble 
7. Business administration @drjwbaker 
8. Preparing to become a charity in the UK https://github.com/programminghistorian/jekyll/issues/1671 @drjwbaker 
8. Any Other Business 
9. Agree date of next meeting

**PLEASE SUGGEST AGENDA ITEMS IN THE TICKET FOR INCLUSION**
Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))

**Comment by acrymble** [comment]
This planned meeting falls during a period when 2 of our directors will be on sabbatical.

As there is no urgent business requiring a meeting to take forward, I'd like to propose to @drjwbaker @rivaquiroga @amsichani @spapastamkou @svmelton that we reschedule this for August 2020. Can you all let me know if you have any objections to that?

**Comment by drjwbaker** [comment]
No objections.

**Comment by amsichani** [comment]
I am on sabbatical from July-October, butI m happy to take part in one or two BoD meetings during that period. One issue I want to discuss is the SLA - do we have a deadline for this, how are we going to actually 'sign' it and how /for which reasons are we planning to use it?

**Comment by rivaquiroga** [comment]
No objections

**Comment by spapastamkou** [comment]
Ok for me.
Sofia

Envoyé de mon iPhone

**Comment by svmelton** [comment]
No objections!

**Comment by acrymble** [comment]
@amsichani do you mean the service agreement in #1704 ?

If so, this has shifted to a Programming Historian Project Team thing of which we are a part. I can make sure we circulate it to each of you for comment before anyone on our team signs it.

I will send along a Doodle poll to re-schedule this for August. Anyone who needs to call an unscheduled meeting is still able to do so in the normal way. I will paste this agenda into the new meeting ticket once that's been agreed.
