### ISSUE TITLE
Tweets encouraging Spanish original submissions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1752]
As per #1746 one of the suggestions was encouraging Spanish original submissions. This can be a simple series of scheduled tweets.

I might suggest text along the following (in Spanish of course) tweeted on a schedule over the next 10 days or so:

* Have a digital skill you could share with other humanists? The @proghist en espanol wants to hear from prospective authors of Spanish-language digital skills tutorials. [LINK to submission guidelines]

* Share your digital knowledge relevant to library and archive professionals. The @proghist en espanol is accepting Spanish-language lesson proposals [LINK to submission guidelines]

* Help your colleagues around the world adjust to new digital ways of working. Share your knowledge of digital skills via @proghist en espanol, now seeking new Spanish-language lesson proposals [LINK to submission guidelines]

**Comment by acrymble** [comment]
Attempts at translations of the above tweets:

* ¿Tienes una habilidad digital que podrías compartir con otros humanistas? @Proghist en español quiere saber de posibles autores de tutoriales en español. 

* Comparta su conocimiento digital relevante para profesionales de bibliotecas y archivos. @Proghist en español está aceptando propuestas de tutoriales en español 

* Ayude a sus colegas de todo el mundo a adaptarse a las nuevas formas digitales de trabajo. Comparta su conocimiento de habilidades digitales a través de @proghist en español, ahora buscando nuevas propuestas de lecciones en español

@jenniferisasi can you comment?

**Comment by jenniferisasi** [comment]
Ok, I'll tweet these starting on Monday, May 4. Thanks

**Comment by acrymble** [comment]
Thanks @jenniferisasi I will close this. Feel free to adapt or change any of the tweets, as they are just suggestions.
