### ISSUE TITLE
Admin training for James

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1754]
Coming out of #1746 @drjwbaker has suggested he needs additional training in the following areas:

Human Resources, not-profit/charity admin, and UK finance & tax regulations.

@drjwbaker can you outline briefly what this might look like? Do you want us to try to pair you with a mentor? To work together in a small group to find and learn from existing resources? An online course? Something else?

**Comment by acrymble** [comment]
I've had a little look around the web for possible options for training:

* There are some London-based in-person charity training workshops (currently postponed obviously) on a range of topics and in the £450 range: https://www.dsc.org.uk/training/
* Coursera has some business management coursess (offered by American universities so possibly a little different), which maybe we could work on in a small group to stay motivated?
* Open University has a business fundamentals MOOC. I'm not sure of the cost.
* You can buy used copies of "for dummies" type books for a few pounds, which I've used in the past for building confidence about vocabulary and processes, etc. So maybe a good starting point.

Anyone else have suggestions for these types of learning needs?

**Comment by drjwbaker** [comment]
Thanks for investigating Adam. I appreciate it. I guess what I'm looking for is a grounding in what I can feasibly do, and what I'd need help to do. 'For Dummies' might be a start. But I think I really need to shadow someone who does small charity HR and/or books to real get a feel for it. Because I think I'm doing okay, but don't have a clear reference point.

I should add: on running the books, I have already been leaning on a family member who is a book-keeper for advice support. I this is charity/non-profit specific stuff I worry I'm missing. And I don't feel confident to scale what I can do to running HR (aside from paying sole traders for their labour).

**Comment by acrymble** [comment]
I presume HMRC is a good starting point then? https://www.gov.uk/running-payroll

Or online step-by-step guides: https://startups.co.uk/how-to-pay-employees/

We should have a discussion about who will do this type of work if we do actually hire someone as has been recommended to us. A manager can do their own paperwork, depending on who you hire.

**Comment by acrymble** [comment]
A few resources on business mentoring that might be helpful:

https://www.theguardian.com/small-business-network/2015/jan/16/five-steps-finding-perfect-business-mentor-startups

http://www.mentorsme.co.uk/

https://www.charitymentors.co.uk/

**Comment by drjwbaker** [comment]
Thanks @acrymble. I rely on HMRC a lot. On the hire, I'd say if we want someone good for the project and seek to avoid the 'hire does everything' pitfall Penny identifies, they perhaps shouldn't be doing this, but arranging for support (e.g. things like https://www.blueumbrella.co.uk/#welcome or https://www.missmps.co.uk/virtual-assistant-kent)

**Comment by acrymble** [comment]
Once we have had our AGM and decided if we're going to action that advice of Penny's, lets shift towards a conversation about the tasks that person might do. Then we'll have a better idea of what you'll be continuing to do as well. But I'd like people to have a chance to think about the report.

**Comment by acrymble** [comment]
@drjwbaker I think it's going to be a much longer conversation before we end up with anything like a manager. Are there any training elements here (or elsewhere) that you'd like to move forward on? Even if it's just setting up a monthly call with a few of us to learn together online?

**Comment by drjwbaker** [comment]
I like the idea of a regular call. Thanks for suggesting it.

One option would be to work through materials at https://www.resourcecentre.org.uk/information-category/managing-money/looking-after-your-groups-money/ for hour every 3/4 weeks. Resource Centre is a charity aimed at supporting groups like ours, especially those on the smaller end like ours. Going through the info here might be useful sanity check that we are running the Ltd appropriately and haven't missed anything obvious (which I don't think we have, but as it isn't my sole focus I do worry from time to time!)

**Comment by acrymble** [comment]
Ok. I'm happy to participate in that with you. Do any of our other directors want to build their knowledge in this area? @svmelton @rivaquiroga @amsichani @spapastamkou ? (Keeping in mind the advice will be UK-centric).

If so, can you drop me an email? And @drjwbaker let's shift this into practice by connecting on email about when we might like to start and where to focus.

**Comment by drjwbaker** [comment]
I suspect it would make more sense for UK-based folks to join, but only if they are willing and able. Even if it is just me and you @acrymble, doing it as a working call would be good for focusing my mind.

**Comment by acrymble** [comment]
Ok I will close this, and anyone interested in joining can email us.
