### ISSUE TITLE
PH-FR Planning 2020/2 (May-July)

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1762]
### Translations
- [x] Sustainable Authorship in Plain Text using Pandoc and Markdown (Marie-Christine) (remaining from #1642) 
- [ ] Downloading Multiple Records Using Query Strings (Sofia)
- [ ] Code Reuse and Modularity in Python (FDL)
- [x] Counting Word Frequencies with Python (FDL)
- [x] Downloading Web Pages with Python (FDL) 

### Translation editions
- [ ] ~~Analyse de documents avec TF-IDF (Sofia)~~
- [ ] Introduction to Jupyter Notebooks (Sofia)
- [x] Introduction à Python et installation (FDL) (publication pending)
- [x] Installation de Python sous Windows (FDL) (published)
- [ ] Construire un site web statique avec Jekyll et GitHub Pages OU Générer un ensemble de données ordonnées à partir d'un fichier texte (Marie-Christine)

### Translation Reviews 

- [ ] Construire un site web statique avec Jekyll et Github Pages (FDL) *__if the lesson is edited__*
- [ ] Introduction à l'emploi de Google Maps et Google Earth (FDL) *__if the lesson is edited__*
- [ ] Générer un ensemble de données ordonnées à partir d'un fichier texte (FDL) *__if the lesson is edited__*
- [x] Introduction à Python et installation (Sofia)
- [x] Installation de Python sous Windows (Marie-Christine)
 
### Original Lessons 
- [ ] Gérer et mettre en ligne une base de données avec Heurist (in progress)

**Comment by spapastamkou** [comment]
Je m'assigne un seul suivi de traduction pour cette période, cela est plus réaliste selon mes disponibilités.

**Comment by spapastamkou** [comment]
@mariechristineb J'ai ajouté à ton nom un suivi de traduction au choix selon tes choix dans le Gdoc, pour avoir un repère, mais sens-toi libre de modifier comme tu le veux.

**Comment by spapastamkou** [comment]
@fdlaramee ce n'est pas un peu beaucoup? :-)

**Comment by fdlaramee** [comment]
@spapastamkou bof, ce n’est pas comme si j’avais beaucoup d’alternatives pour occuper mes loisirs par les temps qui courent... mais bon, s’il y a quelques tâches qui débordent sur août ça ne fera pas mal.

**Comment by fdlaramee** [comment]
@mariechristineb @grandjeanmartin Bonjour à vous deux Martin et Marie-Christine; pensez-vous être en mesure d'assurer une relecture de "Installation de Python sous Windows", traduite par @spapastamkou, pendant le trimestre en cours? Histoire de savoir si je dois recruter à l'externe pour cette tâche. Merci!

**Comment by mariechristineb** [comment]
@fdlaramee pas de problème de mon côté

**Comment by mariechristineb** [comment]
Bonsoir @grandjeanmartin @fdlaramee - pensez-vous être disponibles pour faire la relecture de "Construire un site web statique avec Jekyll et GitHub Pages" dans un avenir plus ou moins rapproché? Je crois qu'on avait parlé de faire la plupart du travail d'édition à l'interne pour ce trimestre, n'est-ce pas? Merci :)

**Comment by fdlaramee** [comment]
Bonjour @mariechristineb -- Oui, je pourrai le faire d'ici les prochaines semaines. Désolé de ne pas avoir répondu plus rapidement, il semble que je ne reçoive plus beaucoup de notifications de GitHub depuis le mois dernier. 😬

**Comment by acrymble** [comment]
@spapastamkou I believe this checklist can be closed now, as the time has passed?

**Comment by spapastamkou** [comment]
yes!
