### ISSUE TITLE
Ombudsperson (FR)

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1763]
During recent exchanges in the @programminghistorian/french-team several names were submitted for discussion to assign an external ombudsperson. The discussion is open by email.

**Comment by spapastamkou** [comment]
This ticket will close through a pull request once we have a new ombudsperson.

**Comment by spapastamkou** [comment]
1st e-mail sent.

**Comment by spapastamkou** [comment]
e-mail resent.

**Comment by acrymble** [comment]
If you have to resend the email that might be a sign that the person won’t be responsive enough when you need them. Keep in mind the purpose of the role is to diffuse tension.

**Comment by spapastamkou** [comment]
Not much lack here after contacting a 2nd possible candidate.

**Comment by acrymble** [comment]
Happy to say Hélène Huet at the University of Florida has agreed to take on this role. Thank you @spapastamkou for suggesting her. I will add a pull request to close this issue.

(Update: just waiting for an avatar from Hélène and then I can do pull request).

**Comment by spapastamkou** [comment]
Thanks to you @acrymble for moving this forward and taking in charge the contacts for the @programminghistorian/french-team! Please don't hesitate to assign us the PR or ask for review.
