### ISSUE TITLE
UK Gov't support available

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1766]
As ProgHist Ltd is based in England (legally), we're eligible for some of the UK's support schemes related to covid19. There is a very easy questionnaire available on https://www.gov.uk/business-coronavirus-support-finder that helps you determine what schemes your business is eligible for.

In our case, we are eligible for the government backed loans of up to £100k. I open this as information, principally for the ProgHist Ltd board members, but also for anyone who wants to keep informed or express views on this topic.

If there is no discussion on it within a couple of weeks, I will close the ticket.

**Comment by drjwbaker** [comment]
Thanks for raising this @acrymble. I'm very nervous about taking out a loan without a clear purpose (and plan to pay it back!)

**Comment by acrymble** [comment]
I hope everyone has had a chance to see this now, so I will close it. And I fully agree with @drjwbaker .
