### ISSUE TITLE
Update Twitter bot to use DOIs for lessons

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1773]
^^

**Comment by walshbr** [comment]
While working on this, @jenniferisasi I noticed that there is a tweet on the ES spreadsheet for the twitter bot to a blog post - https://programminghistorian.org/posts/convocatoria-de-tutoriales. Row 15 of that tab. My Spanish is very rusty, but to my reading it looks like you might want to move that to the new communications tab?

**Comment by walshbr** [comment]
The spreadsheet is all updated. So @jenniferisasi once you respond to / act on that question above this can be closed.

**Comment by drjwbaker** [comment]
Heroic effort getting that done so quick @walshbr!

**Comment by jenniferisasi** [comment]
Done! We can close.
