### ISSUE TITLE
Python lesson sequence and accessing files as binary

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1777]
I received a note from a reader who is having problems with this lesson and is using Windows. It appears to be the same error referenced in #1768. @walshbr would you be able to take a look at this, or would you rather I tag someone else in? 
![screenshot](https://user-images.githubusercontent.com/7232545/82235160-5c8cc300-9900-11ea-9a75-1f5c9bc74585.png)

**Comment by walshbr** [comment]
Same error message as the other one, but a different context. I don't immediately know how to troubleshoot errors like these, and I don't have access to a Windows machine to help facilitate it. Could you check with someone else? Sorry!

**Comment by svmelton** [comment]
Would someone from @programminghistorian/technical-team be able to take a look at this?

**Comment by jenniferisasi** [comment]
I am afraid I don't know Python nor do I have a Windows machine with me.

**Comment by acrymble** [comment]
Sorry we obviously made mistakes when doing to 2 to 3 migration #1460. @JoshuaGOB helped with the Windows files. Maybe he can advise?

**Comment by JoshuaGOB** [comment]
I think it's a matter of eliminating the binary option in open but I don't have a Windows computer to check this on right now. Will try to get access soon but if someone does try: 
`f = open('helloworld.html','w')`

**Comment by walshbr** [comment]
FWIW - https://github.com/programminghistorian/jekyll/issues/1611 - the wb component was specifically added to address an error on Windows machines. So definitely would want to double check instances of it to make sure that taking it out doesn't re-introduce the other error.

**Comment by walshbr** [comment]
Just a note that I've renamed this ticket to reflect the particular bug that was initially reported. It overlaps with #1777 as part of larger debugging needed for the python lesson sequence.

**Comment by mariajoafana** [comment]
Lets bring this up in the next Project Team meeting

**Comment by rivaquiroga** [comment]
Hi everyone!
@jairomelo, one of our bug assessors, confirmed that @JoshuaGOB proposal is the one that can fix the problem. He also checked the solution on Windows. Changes in the English and Spanish version are ready to merge: https://github.com/programminghistorian/jekyll/pull/1997. 

@spapastamkou and @DanielAlvesLABDH: if this lesson ("Creating and Viewing HTML files with Python") is under translation, please take into account these changes.

**Comment by DanielAlvesLABDH** [comment]
@daniellesanchesDH por favor veja se a lição indicada pela Riva é uma das que está a ser traduzida. Se for avise os colegas para estarem atentos a estas alterações
