### ISSUE TITLE
Commit direct to repo in error

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1779]
@programminghistorian/technical-team Can someone please revert this commit? https://github.com/programminghistorian/jekyll/commits/gh-pages/en/research.md Nothing wrong with it. I just hit the wrong button in error. And would rather do the process properly as it requires translation. Sorry!!

**Comment by walshbr** [comment]
FWIW @drjwbaker I actually don't think I can commit directly to the repository to revert this…I'd have to commit a pull request
