### ISSUE TITLE
Actions Arising from May 2020 Project Team Meeting

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1789]
The following actions have arisen from the May 2020 Project Team Meeting

- [x] @mdlincoln to report to @acrymble in June 2020 who the Tech Lead (or equivalent) will be.
- [x] @acrymble to speak to colleagues with more than 2 roles about reducing workload
- [x] @mariajoafana  to follow up with owners of older tickets to identify avenues of support, and to follow up on the Wiki idea for saving tickets for future, or to identify any tickets that don't have a clear 'team' behind them.
- [x] @mariajoafana  & @acrymble to discuss implications for Global Team makeup with @JMParr & @JoshuaGOB  and make sure they have the resources and support they need.
- [x] @acrymble to discuss Proghist/Development team structure overlap with @drjwbaker .
- [x] @acrymble open ticket for suggested new services
- [x] @svmelton SM and English team to select new editors from applicants.
- [x] @programminghistorian/project-team to suggest ombudspersons to @svmelton

**Comment by drjwbaker** [comment]
Note, I also said I'd do this https://github.com/programminghistorian/jekyll/issues/1729#issuecomment-634085380 which I have done https://github.com/programminghistorian/jekyll/issues/1791

**Comment by acrymble** [comment]
We only have one outstanding action here, which is about appointing new English editors. Since our meeting is in a couple of days, I'm going to roll this over to the next agenda (#1788)

Thanks everyone for completing your actions.
