### ISSUE TITLE
Suggested ProgHist Ltd services for publications

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1790]
Arising from May 2020 Project Team Meeting:

Please use this ticket to share ideas on new services that ProgHist ltd could offer (particularly to publications) to make the team member's lives easier, increase the quality of work, and or help them better meet their mandate.

**Comment by walshbr** [comment]
+1 for paying someone to help field bug reports that necessitate upgrades to lessons as technology changes. We've typically looped in the authors and then the editors of the lessons as they are the most familiar with the codebase (and then I think managing editors are next in line), so it would be slower for someone else to do that work. But it would be welcome relief for a problem that will only increase over time.

**Comment by drjwbaker** [comment]
> +1 for paying someone to help field bug reports that necessitate upgrades to lessons as technology changes. We've typically looped in the authors and then the editors of the lessons as they are the most familiar with the codebase (and then I think managing editors are next in line), so it would be slower for someone else to do that work. But it would be welcome relief for a problem that will only increase over time.

We are thinking here of a specialist upgrades editor, right?

**Comment by walshbr** [comment]
Not sure what we'd call it, but that seems fine enough to me. Probably would still need work on our end to vet whether or not it's something quick vs something we'd want to send out for outside help.

**Comment by drjwbaker** [comment]
@walshbr Okay. Can you take this to a @programminghistorian/technical-team meet to discuss?

**Comment by acrymble** [comment]
@walshbr I think he means bug fixing, which is editorial, not technical.

**Comment by drjwbaker** [comment]
> our end

sorry, I read that as tech for some reason. my bad.

**Comment by svmelton** [comment]
Definitely +1 for big fixing and upgrades. One of the challenges is that our lessons cover so much ground (different programming languages, methodologies, etc.) that it can be difficult to find help within PH.

**Comment by mdlincoln** [comment]
I know I beat this drum constantly, but I'm going to keep doing it while I still work here. 

Our retirement policy was very well thought out and is really meant for these occasions where we do not have the capacity to fix a lesson that is no longer usable. We should not hesitate to invoke it. It is not "unpublishing" or "retracting" a lesson - it is humbly acknowledging that technology changes and our labor has limits.

**Comment by acrymble** [comment]
@mdlincoln this suggested 'bug fixer' could also be a 'bug accessor' who helps editorial teams make decisions on those. I think when a bug comes in it's still a burden for editors, so I can see why having someone to take that off their plate is helpful.

Other suggestions still welcome here. If we have lots to choose from that's a good thing.

**Comment by acrymble** [comment]
Thanks everyone for your views. It looks like we have a one good idea so far. But it does strike me as an idea that benefits the English team most (for now). Do the @programminghistorian/spanish-team @programminghistorian/french-team or @DanielAlvesLABDH (on behalf of the Portuguese team) have any ideas on what we might support to make your jobs as editors easier?

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Thanks everyone for your views. It looks like we have a one good idea so far. But it does strike me as an idea that benefits the English team most (for now). Do the @programminghistorian/spanish-team @programminghistorian/french-team or @DanielAlvesLABDH (on behalf of the Portuguese team) have any ideas on what we might support to make your jobs as editors easier?

As I understand, this "bug fixer" would be paid, correct? He/she will be working with all the teams? From my knowledge the majority of the lessons are in English, and the other teams have translated a good part and only a few are original from the FR, ES (hopefully from PT in the future) teams. This balance could probably change in the future, so the person in charge of this will have to deal with "bugs" in 4 languages. Unless the bugs are more technical, I find this task rather difficult. But do let me know if I'm missing something here...

**Comment by acrymble** [comment]
This is a good question @DanielAlvesLABDH. We would have to discuss it, but for copyediting (which we also pay for), we would hire a copyeditor who was fluent in the language. We pay copyeditors for each lesson as and when we need them. So they aren't a member of permanent staff.

I guess a bug fixer could do the same (hired individually and as needed for their skill in a given language).

**Comment by DanielAlvesLABDH** [comment]
Ok, more clear now! Thanks

**Comment by jenniferisasi** [comment]
@acrymble @DanielAlvesLABDH I also see this as a paid position outside PH like the copyeditors. 

A bug could arise on monolingual or crosslanguage situations*.  In the case of monolingual, I wanted to add that some translated lesson have edited/different/additional codes to be able to work in say, Spanish, so the bug could arise on a translated version and not in the original (this is unlikely, but it could happen at some point). 

*monolingual: only happens in one lesson
cross language: happens in the lessons that are translated (ie. python update)

**Comment by acrymble** [comment]
We're going to test the idea of a bug tester #1790 .

As no other suggestions have come in, I will close this ticket and we can open others in future as capacity allows. Thank you everyone.
