### ISSUE TITLE
Working on the Programming Historian without being a "full" editor

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1791]
Yesterday in https://github.com/programminghistorian/jekyll/issues/1729 @spapastamkou asked ~"if language teams should/can have members that aren't 'full' editors, e.g. they only work on translation" https://github.com/programminghistorian/jekyll/issues/1729#issuecomment-634085380 

This chimes with a theme of [Penny's research-led report](http://doi.org/10.5281/zenodo.3813763) on our work/structure/practices, specifically in the 'should have' actions (p9):

> Editing an article should not be a rite of passage for everyone who we want to work on the project. Create a structure that allows people to join the team at a lower-barrier, more granular level with one or two modest responsibilities (e.g. running the Twitter account, managed by the Communications Lead) to build confidence and skills. Not everyone can be or wants to be an editor and it leads to single points of failure when the one keen person who take on a particular task gets ill or moves on.

I recall that there was a little disquiet about this when I circulated the draft report, so I wanted to open a proper discussion here. 

As far as I can see there are four things we need to discuss:

1) Are we in principle for or against the idea of having members of the Project Team who are **not "full" editors**? (e.g. they are only [onboarded](https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors) as far as their role demands).

2) If we are happy with 1), are we happy for sub-team to come up with their own models for **not "full" editors**? Note, doing so would fit the spirit of our [Governance document](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance), specifically the line: 

> Sub-teams are empowered to make decisions on behalf of the project .. but must do so in a sufficiently transparent way that if any team members object to a course of action, we will not move forward without addressing those objections.

3) If we are happy with 1), and more or less happy with 2), do we want to set some boundaries for what a **not "full" editor** can or can't be?

4) If we are happy with any or all of the above, how do we want to refer to *not "full" editors*, because my phrasing is terrible :)

Any and all comments are welcome. I propose to leave this ticket open until **throughout June** with a view to bringing a proposal to our [July Project Team call](https://github.com/programminghistorian/jekyll/issues/1788).

**Comment by acrymble** [comment]
This seems to be a query that only affects people working on Publications, no? We already have people who don't edit lessons anymore.

I don't see why our current 'editor' role can't already cover this. It's perfectly reasonable for a Managing Editor to assign one of their editors only translation work. I'm not sure that needs to be in writing, but I may be missing a use-case.

You're right that the onboarding instructions need to be made a bit more flexible. I can work on that. (update: I've done this)

**Comment by drjwbaker** [comment]
My sense is that it is more about onboarding than anything else. By default we onboard someone as a "full" Editor, then over time people - like me, for instance - move away from editing. The recommendation from Penny is that we have a clearer route for toe-in-the-water involvement (e.g. someone with web analytics skills whose only "job" is to report monthly on our web traffic), that might then lead to being a "full" Editor in time if they want to, but doesn't straight away come with all the overheads that brings (e.g. does every role demand GitHub onboarding, or being on the mailing list, or becoming a member of the Ltd, etc).

**Comment by acrymble** [comment]
What you suggest is fine with me. It's in line with our ProgHist AGM yesterday where I suggested the board might benefit from people with expertise not in the team (eg fundraising) but who might not be interested in the editing side of the project.

**Comment by drjwbaker** [comment]
Agreed (just not as Directors for now per https://github.com/programminghistorian/jekyll/issues/1694#issuecomment-635511587). And that is the tenor of Penny's report. Hence the ticket.

**Comment by acrymble** [comment]
@drjwbaker does the update to the onboarding checklist resolve this? Can we close?

**Comment by drjwbaker** [comment]
> I recall that there was a little disquiet about this when I circulated the draft report, so I wanted to open a proper discussion here.

Why the rush to close? Looking at https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors it seems, despite the caveat, to heavily lean towards editors-by-default.

I for one would love to know more about the appetite from sub-team leads for toe-in-the-water roles, and - more generally - if we accept the principle (which, per my quote above, there was some dissent about when I shared the draft report).

**Comment by drjwbaker** [comment]
> I recall that there was a little disquiet about this when I circulated the draft report, so I wanted to open a proper discussion here.

- @JMParr: you had some qualms about the idea of lower-barrier entry roles when I first circulated the report. Any thoughts on the above?
- @spapastamkou: before you go on sabbatical, is there anything you like to add around what how the FR team is currently thinking about not "full" editor roles?

**Comment by acrymble** [comment]
@drjwbaker it's been a few weeks and we haven't seen any additional comments. Based on the lazy consensus, I think you can assume you have approval here.

**Comment by drjwbaker** [comment]
I had this in my diary to look at today. Agreed @acrymble. Closing noting lazy consensus that **we are happy** for people to work on PH without being a full editor, being that we can in the future partially onboard individuals to take on specific roles. Penny's line kinds sums up the tenor of this:

> Editing an article should not be a rite of passage for everyone who we want to work on the project

**Comment by drjwbaker** [comment]
Note from https://github.com/programminghistorian/jekyll/issues/1788 that there are 22 members of the PT team, and I'm assuming they are not all will be 'full' editors, so it looks like we are comfortable with this.

This links to https://github.com/programminghistorian/jekyll/issues/1818
