### ISSUE TITLE
Sherpa/Romeo registration

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1794]
Offshoot of the Plan S implimentation #1370 

    Registering the self-archiving policy of the venue in SHERPA/RoMEO. [We tried to reach out to this organization in October 2019 but were ignored -ac]

The EN edition is on the old Sherpa/Romeo via our DOAJ listing http://sherpa.ac.uk/romeo/search.php I suspect the email how caught in the shift of Sherpa/Romeo to a Jisc infrastructure (in beta, launches in July) https://v2.sherpa.ac.uk/romeo/search.html We have friends at Jisc, so can we try resending the request to help@jisc.ac.uk to get us listed (ideally, EN/FR/ES and PO) on the new service?

**Comment by amsichani** [comment]
Good to keep an eye on it. Thanks for the update @acrymble . It 'd be great if we manage to get the rest PH publications listed too.

**Comment by acrymble** [comment]
I've sent the request on 31 May 2020. Awaiting response.

**Comment by acrymble** [comment]
In response to our blog post about Plan S I've now had a response to our approach and will follow up accordingly.

**Comment by acrymble** [comment]
I've re-submitted our information and asked them to confirm receipt and give an estimated timeline.

**Comment by acrymble** [comment]
I'm pleased to say that this has been approved and added to their database: https://v2.sherpa.ac.uk/id/publisher/62625

I have added this to the Wiki under service integrations https://github.com/programminghistorian/jekyll/wiki/Service-Integrations

@JoshuaGOB @drjwbaker I'm not sure where this falls in terms of remit. Is this a new publications or an archivist thing moving forward? We'll have to update the entry to include the Portuguese team at some point (#1802).

**Comment by drjwbaker** [comment]
Great work @acrymble. As archivist, I probably should be in charge of periodically checking that the info is up to date.
