### ISSUE TITLE
Process for closing a line of spending

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1796]
Action from the #1694: as suggested by @mdlincoln, we need a process for closing a line of spending, to complement our process for spending requests https://github.com/programminghistorian/jekyll/wiki/Spending-Requests

My suggestion for wording (to be added to an amended ttps://github.com/programminghistorian/jekyll/wiki/Spending-Requests( is as follows:

> In the event that the Treasurer deems it necessary to reduce spending, the Treasurer first brings the matter to the attention of the ProgHist Ltd Directors (via email). After discussion among the Directors, they will then make a recommendation to the Members via a ticket.

Comments/suggestions welcome. I'll aim to update the wiki **mid-June**.

**Comment by acrymble** [comment]
I don't think you want to paint yourself into a corner here. You may find a need to very quickly halt spending and may not have time to consult widely. For example, a banking problem makes our money disappear and you actually can't pay bills.

There should be a 'spirit of' this principle that doesn't bind you to act in fulfilling your legal requirements. I'd suggest instead an approach that says the sunsetting of services will be first raised with the project team with enough time for people to consider the implications, as will conversations about needing to reduce spending or find cheaper alternatives (switching from Netlify to X technology because it's better/cheaper).

**Comment by drjwbaker** [comment]
So something like:



> The Treasurer has the authority to unilaterally halt all spending (for example, in the event of unexpected collapse in cash flow). However, this is a last resort. In most cases, if the Treasurer deems it necessary to plan for reduced spending (for example, our surplus is steadily being reduced or we are notified that a key income stream will be coming to an end), the Treasurer will bring the need to gradually reduce costs to the attention of the ProgHist Ltd Directors (via email). After discussion among the Directors and directly impacted Team Leaders, they will then make a recommendation to the Members via a ticket.

**Comment by acrymble** [comment]
I'm of the view that this is already what would have been required based on our agreed processes. So I don't think this needs to be put into writing. The more rules we have the harder it is to operate and the harder it is to keep track of the rules.

>> Sub-teams are empowered to make decisions on behalf of the project .. but must do so in a sufficiently transparent way that if any team members object to a course of action, we will not move forward without addressing those objections.

**Comment by amsichani** [comment]
I am also not if favour of having too many rules , as this might impede us from operating more flexible and quickly in the near future. I think that as of spending, it 'd be wise to set up a straightforward framework: to have a first information from the Treasurer and an initial discussion among directors & impacted team leaders via email, perhaps a quick voting ,and if needed we can open a ticket for the entire team to comment.  So imho the lighter the written rule are, the better - that doesn't mean our procedures are not legit .

**Comment by drjwbaker** [comment]
Okay, I get the desire to reduce the number of processes/rules. I am also mindful that at the AGM https://github.com/programminghistorian/jekyll/issues/1694 this issue was raised by a ProgHist Ltd Member and we have a duty to respond.

I also think although we have the sub-team policy, it is useful to remind ourselves sometimes of its implications (e.g. that the Global Team could until https://github.com/programminghistorian/jekyll/issues/1729 unilaterally add a new publication, or that the Treasurer can just stop all spending if they wish) and outline steps to reassure those impacted.

How about:

> The Treasurer has the authority to unilaterally halt all spending (for example, in the event of unexpected collapse in cash flow). However, this is a last resort. In most cases, if the Treasurer deems it necessary to plan for reduced spending (for example, our surplus is steadily being reduced or we are notified that a key income stream will be coming to an end), the Treasurer will bring a recommendation to the attention of the ProgHist Ltd Directors and directly impacted Team Leaders.

**Comment by acrymble** [comment]
@mdlincoln is there something specific here that you think isn't covered by the agreement to act transparently and to work with other teams as issues arise that affect them? I'm mindful you've also warned us not to make the project more work for its members than needed, so I'd like the leanest possible solution here, because anything new has time implications for volunteers.

**Comment by mdlincoln** [comment]
I think the language @drjwbaker puts is fine. The treasurer DOES need unilateral authority to act, but we would need to be well into a financial emergency by that point, and I think it is important to codify that the treasurer needs to inform and consult with the project team when deciding how to respond to such an emergency.  That kind of oversight is not the "makework" that I am concerned about, @acrymble.

**Comment by acrymble** [comment]
Ok. @drjwbaker I don't have any objection to what you're proposing. I think it's just common sense. But where are you going to keep this? Running this organization is becoming exhaustingly complex, and most of that complexity is socially constructed.

**Comment by drjwbaker** [comment]
I can just edit this https://github.com/programminghistorian/jekyll/wiki/Spending-Requests

**Comment by drjwbaker** [comment]
> Running this organization is becoming exhaustingly complex, and most of that complexity is socially constructed.

@acrymble: you don't need to be on top of everything :)

**Comment by acrymble** [comment]
Thanks @drjwbaker can you do that and close this out? I don't think it's controversial enough to need a long discussion.

**Comment by drjwbaker** [comment]
Done.

If anyone would like to reopen this (now or at a later date) please do.
