### ISSUE TITLE
ProgHist Ltd Annual General Meeting May 2021

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1797]
Further to #1694, ticket to start the process of setting a date for the 2021 ProgHist Ltd Annual General Meeting.

But before we set a date, I propose a slightly different format, specifically:

- now we've had our first ProgHist Ltd AGM, the following AGMs should be quite light (Chair's report, Treasurer's Report) because the remit of the Ltd is relatively limited.
- so, what we could do instead is have a Programming Historian AGM, to celebrate all our achievements, check everyone is happy with their roles, and set a focus for the following year, and within that tuck the ProgHist Ltd AGM buisness (which is a legal requirement).
- the upside of this is that a Programming Historian AGM might be more interesting and interactive for our IPP representatives, and giver a fuller picture of what we are up to as a group.

As ever, thoughts/comments welcome.

**Comment by acrymble** [comment]
This sounds like a great idea. Can we agree to just make it happen? I think it only affects @mariajoafana 's workflow.

**Comment by drjwbaker** [comment]
If there are no objections, sure.

**Comment by mariajoafana** [comment]
I agree, yes

**Comment by drjwbaker** [comment]
@mariajoafana In which case, can we close this ticket and agree to start work in - say - February 2021 on a joint PH & ProgHist Ltd AGM for May 2021?

**Comment by mariajoafana** [comment]
yes, sounds right, I'll post this on my calendar to remember
