### ISSUE TITLE
directory of open access journals listing

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#180]
Anyone object to me submitting an application to be listed amongst open access journals on the site? https://doaj.org/publishers
I know the term 'journal' isn't a perfect fit, but I think this will be helpful for increasing findability, and also giving us ideas on metadata we might include to make linking/slurping into catalogues easier.

Let me know any thoughts or concerns.

**Comment by fredgibbs** [comment]
sounds like a good idea!

**Comment by ianmilligan1** [comment]
Agreed - great idea, @acrymble!

**Comment by acrymble** [comment]
ok i'll initiate it.

**Comment by acrymble** [comment]
I have submitted this application. I suspect we will be told we need to do the following:

1) Provide 'permanent identifiers' at article level
2) Send them regular 'article level metadata' (maybe we can do this via rss?)
3) Answer this question: Which deposit policy directory does the journal have a registered deposit policy?

We'll know in about 6 months if we qualify. If not we can re apply. No cost.

**Comment by acrymble** [comment]
We have been added to the DOAJ repository, which is good because it makes it easier for institutions like libraries to index us. We've been asked to add the following however:

1) An annual publications page in addition to our /lessons directory. I suspect this should be quite easy to do?

2) To make the most of it we have to upload the files to DOAJ using their custom XML template (https://doaj.org/publisher/uploadfile). The template is fairly straight forward. Is it easy enough to pipe our content into it and provide that as a download option?

**Comment by acrymble** [comment]
FYI: https://doaj.org/toc/2397-2068 this is us.

**Comment by acrymble** [comment]
Related, @amandavisconti has convinced the University of Purdue to produce a catalogue entry for PH (http://purdue-primo-prod.hosted.exlibrisgroup.com/primo_library/libweb/action/dlDisplay.do?vid=PURDUE&search_scope=everything&docId=PURDUE_ALMA51671812890001081&fn=permalink) as well as a WorldCat entry: http://www.worldcat.org/title/programming-historian/oclc/951537099

Many thanks for that!

**Comment by acrymble** [comment]
I've updated this with all of our new entries this year. Closing this ticket because there's nothing actionable here that we're working on. I'll just try to keep updating this once a year.
