### ISSUE TITLE
PT technical onboarding

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1802]
This is a tracking ticket for [technical tasks related to starting the PT team](https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Setting-Up-a-New-Language).

- [x] Create new defaults in _config.yml 
- [x] Add new language line to all snippets
- [x] Copy core pages to the new language directory
- [x] Push core pages to gh-pages branch so language team can begin translation
- [x] Create language logo and set theme color (#1822)
- [x] Add the new language to the RSS feed XML
- [x] Enable full text search stemming support
- [x] Add the new team to [this](https://github.com/programminghistorian/jekyll/blob/15f818d6d11d9cee17f17e1689655b294d69397d/_includes/project-team-loop.html#L28) loop once editors have been added to the team's data files.
- [x] Make pages public

**Comment by acrymble** [comment]
In case it helps the brand guidelines on the wiki give the logo fonts (https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines). I believe I used a colour-palatte generater in the past to get colours that worked well together, but I can't remember which one.

**Comment by amsichani** [comment]
Thanks for this @mdlincoln! I think its handy to have the technical tasks related to start a new language publication as a distinct wiki page -- we will link to this tutorial from the main wiki page .

**Comment by JoshuaGOB** [comment]
Thank you @mdlincoln I really needed to see this and the technical tutorial to get a sense of what was going on behind the scenes.

**Comment by jenniferisasi** [comment]
@ZoeLeBlanc I think Matt missed a step in this guide. We have to manually add the chunk about the editorial team in Portuguese in this loop right? https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/project-team-loop.html

**Comment by acrymble** [comment]
Yes @jenniferisasi that can just be cut and pasted and amended in place.

**Comment by walshbr** [comment]
I added that to the wiki template for this issue @jenniferisasi and updated Matt's checklist above.

**Comment by acrymble** [comment]
@ZoeLeBlanc I most recently worked on the /project-team page so I think I can do the changes to add the Portuguese team without screwing anything up. Would you like me to do that or will that get in the way of your processes? We already have Daniel in there so there is content that would and should appear.

**Comment by ZoeLeBlanc** [comment]
Go ahead and make the changes to project-team page @acrymble and I'll take a look at what's left to be done once you do your PR. Thanks!

Seems like it's just the full-text and making pages public though according to the to-do list, which should be easy.

**Comment by drjwbaker** [comment]
Per https://github.com/programminghistorian/project-and-business-archive/blob/master/project/2020/2020-04_Sussex-DOI-MOU/2020-05-18_ProgHist%20MOU%20w%20University%20of%20Sussex.docx we need to ask our DOI provider if they are happy to provide DOIs for a new publication, in this case the PT edition.

Has this happened? If not, two actions:

- @programminghistorian/technical-team please update https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Setting-Up-a-New-Language to include this task as part of the technical process for creating a new language publication.
- @JoshuaGOB @acrymble @DanielAlvesLABDH I'm out of the loop in the status of the PT work (I think you are the main people involved), but - when you are ready - someone needs to ask me to ask Sussex re providing DOIs for the PT publication.

**Comment by DanielAlvesLABDH** [comment]
@drjwbaker we are still in the process of translating the platform to Portuguese. I guess the DOI will apply only to the lessons, correct?

**Comment by walshbr** [comment]
@drjwbaker I can add that to the Wiki checklist, but I don't exactly know what the language would entail. As far as I know that hasn't happened. Something like…

"Get @drjwbaker to check with the DOI provider that they are happy provide DOIs for a new publication." Or is that meant to be @ZoeLeBlanc as technical lead? And what happens if they say no? Could you offer some language for what that checklist item should be? I haven't been involved with the DOI process so I wouldn't know what needs to happen at that stage.

**Comment by drjwbaker** [comment]
That is fine. I have at the relationship. Though technically, I'm working on behalf of the Ltd (DOIs is a service the Ltd provides to the publications https://github.com/programminghistorian/jekyll/wiki/ProgHist-services-to-Publications#services-provided-in-kind)

If they say no, the new publication runs without DOIs until the Ltd finds a solution.

**Comment by walshbr** [comment]
Cool. Added it to the wiki @drjwbaker

**Comment by drjwbaker** [comment]
> @drjwbaker we are still in the process of translating the platform to Portuguese. I guess the DOI will apply only to the lessons, correct?

@DanielAlvesLABDH Correct. Perhaps once we have an ISSN for the PT publication (https://github.com/programminghistorian/jekyll/commit/8a7b7fe2381c8adf7cf1591ff1e1de79b7369197#commitcomment-42033910) contact me and I will speak to our DOI provider?

**Comment by DanielAlvesLABDH** [comment]
Will do that @drjwbaker

**Comment by ZoeLeBlanc** [comment]
Full text search stemming is now live. Nothing to see until we make the pages public, which I think is waiting on more translations and merging of ph_authors.yml

**Comment by JoshuaGOB** [comment]
> > @drjwbaker we are still in the process of translating the platform to Portuguese. I guess the DOI will apply only to the lessons, correct?
> 
> @DanielAlvesLABDH Correct. Perhaps once we have an ISSN for the PT publication ([8a7b7fe#commitcomment-42033910](https://github.com/programminghistorian/jekyll/commit/8a7b7fe2381c8adf7cf1591ff1e1de79b7369197#commitcomment-42033910)) contact me and I will speak to our DOI provider?

Hi @drjwbaker This has come up again and I think the question is about when the DOI request should happen. Would this be once we have a firm deadline for publication or after a set of lessons are in review? Are there any other factors?

**Comment by drjwbaker** [comment]
I think there are 2 parts to this:

1) I need to ask our DOI provider if they are happy to supply a new set of DOIs
2) If yes, we need to create a new xml template for the PT publication https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI and ensure that part of the process (as well as https://github.com/programminghistorian/jekyll/wiki/The-Programming-Historian-Digital-Object-Identifier-Policy-%28April-2020%29) is understood by the PT team

I can do 1) before we have a PT ISSN, or I can wait until that is completed. Either way, I don't think we can start minting DOIs until we have the PT ISSN.

So do you want me to do 1) now, or wait for the ISSN?

**Comment by drjwbaker** [comment]
Update: our DOI provider is happy to support the PT publication and have been in correspondence over practicalities. Particular thanks to our alumni tech lead @mdlincoln for chipping in when cc'd by our DOI provider (not realising he had moved on). This is now with @ZoeLeBlanc to implement.

**Comment by DanielAlvesLABDH** [comment]
This is great. Many thanks!

**Comment by drjwbaker** [comment]
(note, I've archived the correspondence and added it to the DOI folder on the private repo https://github.com/programminghistorian/project-and-business-archive/tree/master/project/2020/2020-04_Sussex-DOI-MOU)

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Update: our DOI provider is happy to support the PT publication and have been in correspondence over practicalities. Particular thanks to our alumni tech lead @mdlincoln for chipping in when cc'd by our DOI provider (not realising he had moved on). This is now with @ZoeLeBlanc to implement.

Hi @drjwbaker and @JoshuaGOB , wishing you a Great New Year! Getting back to this issue since we are closing our first lesson (translated) during this week, and we are ready to put the PT version online. Also catching up from the email "ISSN form for PT team". Do you need any information from our side? Do I need to do anything? Thanks in advance!

**Comment by drjwbaker** [comment]
Happy new year to you as well. I've replied to the email thread on the ISSN. I think it is ready to go with the changes I suggested 17 December.

**Comment by drjwbaker** [comment]
Then @ZoeLeBlanc needs to work on the mechanism for the PT team to request DOIs.

**Comment by drjwbaker** [comment]
> Then @ZoeLeBlanc needs to work on the mechanism for the PT team to request DOIs.

Is anyone on @programminghistorian/technical-team working on this?

**Comment by ZoeLeBlanc** [comment]
I'll tackle it this weekend @drjwbaker just had a few deadlines the last few weeks that had to take priority!

**Comment by drjwbaker** [comment]
Thanks for letting us know @ZoeLeBlanc. I just wasn't sure if it had been picked up. And please don't work over the weekend for my benefit! (though I do appreciate that the team work on PH things at times that suit them).

**Comment by ZoeLeBlanc** [comment]
Just heard from Tim at Sussex and he wants that crossref.xml to be live on the site prior to requesting DOIs. He writes that the workflow is after having that xml file:
```
So in terms of the workflow, when you have a new lesson that requires a DOI, let me know at t.haillay@sussex.ac.uk, ccing library.cataloguing@sussex.ac.uk and a.moore@sussex.ac.uk

I will then let you know the new DOI number - you complete the XML process as outlined above - let me know when the lesson is live - I register the DOI with CrossRef - I let you know when live
```
So reading this it seems like we need the PT lesson to be live before I can request a DOI.

**Comment by walshbr** [comment]
If that's the case we'll need to update the guidelines and wiki I think @ZoeLeBlanc.

**Comment by ZoeLeBlanc** [comment]
So I spoke too soon about going live... looking at the build fail for PR #1991 and it looks like there's a lot of small syntax issues that is breaking the PT site. 

Should I go ahead and fix those or should it be something the PT team handles? Happy to go ahead and do it since it's a lot of small errors but will definitely want their review to make sure I don't add any spelling errors

**Comment by rivaquiroga** [comment]
The workflow Tim describes is the one we've been using, and is the one described here: https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI. The DOI is registered after the crossref.xml is live, but the first thing is to make the request. 
So I'm not sure if we need to update the guidelines/wiki. We've been using them in the past few months without any issue.

**Comment by walshbr** [comment]
I was supposed to be the one dealing with PT @ZoeLeBlanc, and I'm happy to do that unless you wanted to take them. Lmk what you think. We can also split them up if there are a ton.

**Comment by walshbr** [comment]
Complete! New tickets are open for the odds and ends.
