### ISSUE TITLE
Newsletter: 2nd trimester and mid 2020

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1804]
Time flies and the end of June will be here before we realize. As usual, I will create a list of accomplishments here and ask that you please add anything I am forgetting for mid-year newsletter:

- [x] search functionality 
- [x] DOI in lessons
- [x] New 1 IPP and Patreon subscribers
- [x] Adam's three workshops
- [x] new lessons and translations
- [x] Matt's retirement note to honor his great work (possibly add a crying gif) https://matthewlincoln.net/2020/06/18/leaving-programming-historian.html
- [x] Daniel joined. Do we have a preliminary date for launching PH em portugues??
- [x] translate

**Comment by acrymble** [comment]
3 workshops hosted at Edinburgh (@acrymble and @JMParr). 

- Adam Crymble, ‘Documenting Your Digital Methods’, University of Edinburgh, United Kingdom (27 May 2020).
- Adam Crymble & Jessica Parr, ‘Programming Historian Silent Disco’, University of Edinburgh, United Kingdom (18 May 2020).
- Adam Crymble, ‘Do You Need to Learn Programming?’, University of Edinburgh, United Kingdom (14 May 2020).

**Comment by jenniferisasi** [comment]
@acrymble just thought about it: Did they record your workshops and are they available? It would be nice to share them if so.

**Comment by acrymble** [comment]
No I'm afraid they weren't that type of workshop.
