### ISSUE TITLE
managing editor loop

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1807]
I just noticed that in the team's page of every linguistic version (EN example: https://programminghistorian.org/en/project-team) the name of the Managing Editor is followed by a pair of parentheses for no particular reason. I can see it is related to `managing-editor-loop.html` and the include. Can someone of the @programminghistorian/technical-team help me to fix this? Thank you.

**Comment by spapastamkou** [comment]
There is a screenshot:
 
![project-team](https://user-images.githubusercontent.com/27706167/84561774-8d211a80-ad4f-11ea-8608-865a0a4f5126.jpg)

**Comment by acrymble** [comment]
That should have the corresponding language in it if I remember correctly (English, Spanish, French).

**Comment by mdlincoln** [comment]
Ah, when @amsichani worked up the PR for #1798 we removed some snippets used for the banners - and I'd forgotten that the `language-name` snippet was used on other parts of the site.

**Comment by spapastamkou** [comment]
thanks!
