### ISSUE TITLE
Establish a regular internal tech documentation/service integration review process

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#1814]
Coming out of #1787 

>In response to @drjwbaker, we probably should have at least an annual review of the service integrations. We also are sensitive to how we might change our technical documentation regarding how to do PRs, reviews etc. since GitHub changes its interface incrementally over time. We discussed ways to change our docs so that we point as often as possible to GitHub's own maintained documentation rather than taking lots of screenshots, so that we don't end up duplicating it (and duplicating that labor). Instead, we make sure that our docs come from the perspective of our workflow, and point more actively to github's documentation instead.

**Comment by walshbr** [comment]
I'll think more about what this should look like, what pieces it should have, and how we might divide up the labor for a first pass.

**Comment by ZoeLeBlanc** [comment]
Thanks @walshbr ! Let me know if I can help at all.

**Comment by walshbr** [comment]
The next couple weeks are pretty busy for me but I'll try to look at this when I can.

**Comment by acrymble** [comment]
Just noticing this morning that Matt appears a lot still on our service integrations page. https://github.com/programminghistorian/jekyll/wiki/Service-Integrations

So very much welcome this suggestion. Thanks everyone.

**Comment by walshbr** [comment]
Going through this now. In terms of service integrations, I think reviewing of those in an abstract sense is already happening whenever someone leaves the team. But I updated our wiki to make that an official part of the retirement process.

**Comment by walshbr** [comment]
The most likely changes to affect our day-to-day work, I would think, would be changes to the user interface on places where we have screenshots. I went through the wiki, and these are the four pages where things are most likely to change:

https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions
https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Search
https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Setting-Up-a-New-Language
https://github.com/programminghistorian/jekyll/wiki/Technical-Tutorial-on-Translation-Links

But of those, only the Technical Contributions page, I think is likely to really matter. If we change something in the site infrastructure likely to affect the search, setting up a new language, or how the underlying translation links together it's likely that the person making those changes is just going to be a member of the technical team and know enough to modify the wiki when they make those changes. This ticket was more meant to capture a concern that changes might come from _outside the team_ and affect our work. 

So I'd like to consider the "making technical contributions" something we check periodically. In terms of reviewing it now, I think it can be broken into two pieces:

- [ ] "Editing the site using GitHub through responding to a review"
- [ ] "developing this site locally" through the end

Given the changes that were just made to the GitHub interface, I took this as an opportunity to just quickly page through it all and made some changes to things based on some general principles:

1. Aesthetic changes in the screenshots can probably be ignored. GitHub switched to rounded corners, for example, but that is unlikely going to throw people off on its own.
2. Any icon changes or more minor changes to the interface should be noted in the running text.
3. Any substantial changes to the interface probably require a new screenshot. I didn't notice anything like this while reading this time.

**Comment by walshbr** [comment]
I reviewed our technical documentation and screenshots for the "making technical contributions" wiki and documented the process here - https://github.com/programminghistorian/jekyll/wiki/Process-for-Reviewing-Internal-Technical-Documentation. I mostly just copied over relevant text from the above comment, noted when I last reviewed them, and made a note that this should probably be done once annually.

**Comment by drjwbaker** [comment]
@walshbr Thanks for setting this up.

Bit late the conversation (sorry!), but does anyone have knowledge of https://github.com/programminghistorian/jekyll/blob/gh-pages/_layouts/crossref.xml & https://github.com/programminghistorian/jekyll/wiki/How-to-Request-a-new-DOI sufficient to make a change to the former if step 6 of the latter (validation errors) were to occur?

If not, perhaps it can go on https://github.com/programminghistorian/jekyll/wiki/Process-for-Reviewing-Internal-Technical-Documentation?

**Comment by walshbr** [comment]
I think the tech team could figure that out @drjwbaker. I added it to the technical documentation review as something for us to keep track of though.

**Comment by drjwbaker** [comment]
Thanks @walshbr. I kinda assumed we'd have enough knowledge in the group to generate some standardised .xml, but didn't want to assume it was in hand. I appreciate @programminghistorian/technical-team documenting this and keeping an eye on it.
