### ISSUE TITLE
Discrepancy between code and text in "Downloading Web Pages with Python"

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/jekyll#1819]
As I was translating "Downloading Web Pages with Python" into French, I noticed two slight discrepancies between the code that was recently upgraded to Python 3 and the surrounding text, which was not changed accordingly:

* Module urllib2 from Python 2 has been renamed urllib in Python 3.
* A link to the module's official documentation on the Python web site still points to the deprecated Python 2 library.

I will fix the issue in the English text; I am also pinging the Spanish team in case their translation needs to be updated accordingly.

**Comment by drjwbaker** [comment]
@fdlaramee Just in case you hadn't noticed, please run through https://github.com/programminghistorian/jekyll/wiki/The-Programming-Historian-Digital-Object-Identifier-Policy-%28April-2020%29 before making changes to this article. MEs are aware of this, but I'm just reminding folks occasionally do that we don't annoy our DOI partner!

**Comment by drjwbaker** [comment]
(in this case, it sounds like a minor edit, so no issue re DOIs)

**Comment by rivaquiroga** [comment]
Thanks @fdlaramee. Just checked, and it also needs to be updated in the Spanish translation.
@drjwbaker, yes, it is a minor edit. Just removing one character + changing a link.
