### ISSUE TITLE
Portuguese logo options

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1822]
The Portuguese team will need a logo (mentioned in #1802). I thought I'd help by putting together a small selection.

To make sure the colours match our current logo colour scheme and our brand guidelines (which specify the HTML colour codes: https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines) I've come up with two options available here. I came up with the colours using our existing colours as the basis for a palette using http://colormind.io/. Anyone can play around and come up with other colours if we don't like these ones.

@DanielAlvesLABDH can you discuss with your team if you have a favourite?
![phlogo-magenta](https://user-images.githubusercontent.com/646647/85895804-402d5180-b7ef-11ea-8294-a51260556325.jpg)
![phlogo-mustard2](https://user-images.githubusercontent.com/646647/85895808-415e7e80-b7ef-11ea-8f11-f514d0ec7a10.jpg)

**Comment by walshbr** [comment]
Thanks for this. I wonder @acrymble - is there a Portuguese appropriate diacritical marking that might be used, in the same way that we did for the French and Spanish teams? Of course, we'll probably eventually run out of such markings if we keep using them for each new language. But I always thought that was a nice touch. You'd know better than I would if it wasn't appropriate or possible though.

**Comment by arojascastro** [comment]
"Portuguese makes use of five diacritics: the cedilla (ç), acute accent (á, é, í, ó, ú), circumflex accent (â, ê, ô), tilde (ã, õ), and grave accent (à, and rarely è, ì, ò, and ù)". : https://en.wikipedia.org/wiki/Portuguese_orthography

**Comment by acrymble** [comment]
I tried a cedilla previously and it looked terrible. I think it would have been best for French anyway given its presence in 'français'.

**Comment by JoshuaGOB** [comment]
Thanks for the options @acrymble and the website for creating the colors. I Was looking for something like that last week and couldn’t find it. 

I mentioned the circumflex to @jenniferisasi as the communications expert and she agrees that shipped has sailed for the Portuguese team since stickers and promos for the French have already been out for a while. I wonder if @DanielAlvesLABDH has discussed this with the team. Diacritics feel like an important part of the logo not just thinking of branding but also for the visually impaired. Hopefully someone more creative than me can come up with other options.

**Comment by acrymble** [comment]
Another possibility
![phpt](https://user-images.githubusercontent.com/646647/85943734-d2d20b80-b929-11ea-89e4-f80738150bd4.jpg)

**Comment by arojascastro** [comment]
some ideas... 

![IMG_8469](https://user-images.githubusercontent.com/7340111/85943812-c0a89b00-b932-11ea-8256-af9383105b07.JPG)

**Comment by JoshuaGOB** [comment]
Hi all, I got some really cool options for the logo from @cloudyfemme Let me know what you all think. 
https://ibb.co/B2QtpNg https://ibb.co/0FVWJ35 https://ibb.co/Rvnxbxh https://ibb.co/cYvfjq8 https://ibb.co/KrVz1Mt https://ibb.co/zHNt2Jp https://ibb.co/cYvfjq8 
This one is my favorite so far: 
![WhatsApp Image 2020-07-02 at 13 33 52 (1)](https://user-images.githubusercontent.com/36772647/87050071-ccfee480-c1cb-11ea-88e9-1bb28ce1daf2.jpeg)

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Another possibility
> ![phpt](https://user-images.githubusercontent.com/646647/85943734-d2d20b80-b929-11ea-89e4-f80738150bd4.jpg)

Dear all, we had today the meeting of the Portuguese team and among other subjects we already decide about the logo. This option presented by Adam with the little "t" near de "P" is the favorite, but the choice was for the mustard color scheme, if possible with the square brackets in white also. The choice was achieved by voting, so democracy rules...

**Comment by acrymble** [comment]
@DanielAlvesLABDH I've created them. As long as you like it all we need to do is convert these to .svg files and upload them here https://github.com/programminghistorian/jekyll/tree/gh-pages/images/logos . I don't have any software that can convert to svg. Can anyone help? I have Tif files but I can't post them here but I can email them to you.

![Screen Shot 2020-07-09 at 17 19 43](https://user-images.githubusercontent.com/646647/87065031-68ae4600-c208-11ea-864b-a6798fbb053e.png)

**Comment by DanielAlvesLABDH** [comment]
Thanks @acrymble . I don't have that type of software either.

**Comment by aracele** [comment]
Hi @acrymble if you email them to me I can try to convert it to svg format.

**Comment by acrymble** [comment]
Thanks @aracele I've emailed them to you.
