### ISSUE TITLE
DOAJ listing for ES and FR publications

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1827]
@acrymble's recent blog https://programminghistorian.org/posts/plan-s has resulted in the Directory of Open Access Journals reaching out with regards to getting our ES and FR journals listed. It looks like we'll have to go through the application process again, which isn't too onerous and I am happy to do.

We have, however, been asked a question that I'd like input on from MEs (@mariechristineb & @rivaquiroga) so I can provide a full answer. Specifically:

> it would be helpful if you could provide an estimate now as to how much original research the journal publishes. 

It strikes me that there are two things we need to provide here:

1. The % of ES and FR publications that are original submissions as opposed to translations.
2. A qualitative account of the originality that is inherent to article translation (that is, a light push back against the idea that translated articles are unoriginal).

**Comment by rivaquiroga** [comment]
@drjwbaker, I'll have an answer by tomorrow

**Comment by drjwbaker** [comment]
Thanks @rivaquiroga. Don't feel like you need to write too much on this.

**Comment by mariechristineb** [comment]
@drjwbaker here are some thoughts on my side:
1. If I am not mistaken, we have one original lesson published at the moment (out of 10), and have received two proposals for original lessons. Our objective is to publish more original content in the future.
2. Our translations often contain additional resources in French, on top of the resources in the original, so there's extra research done on the side of the translators there.

**Comment by drjwbaker** [comment]
Thanks @mariechristineb. I think capturing some of 2. is vital, so this is really helpful. We know translation isn't trivial, but sometimes it can be treated as such.

**Comment by acrymble** [comment]
if we're going to push against this we have to be clear that "research" and "work/effort" are not the same thing in the context in which we operate. We have to be really clear and open that we (generally speaking) are not publishing research findings. In the humanities that usually means an argument-driven, evidence-based answer to a research question.

That may apply to some of our articles that focus on methodology. But not all of our lessons do. And I think we have to sort out a clear argument as to why translation (even intensive and good translation) is research. I'm not placed to do that.

**Comment by drjwbaker** [comment]
@acrymble The context of..

> it would be helpful if you could provide an estimate now as to how much original research the journal publishes.

..really was about the ES and FR publications, so I very much read 'original research' as 'original papers', as opposed to being a comment about research. But I can clarify.

**Comment by acrymble** [comment]
No it's a general comment about a culture clash that I find a lot in DH projects which try to claim everything they do is 'research' without recognizing or necessarily understanding why all of their colleagues don't agree. We use the word in different ways, and in this case, the definition of the word I suspect DOAJ uses will be very different from the DH one. So if we're going to talk to them productively it helps to use their language.

**Comment by drjwbaker** [comment]
Okay. Notes. For the purposes of this ticket can we agree that the request for info on `original research the journal [ES/FR] publishes` equals in PH-land `original papers the journal publishes`.

**Comment by acrymble** [comment]
This is why they rejected the journal originally:

> We consider that this publication is not a scientific journal but a compilation of resources, lessons and tutorials. For this reason we cannot index your website.

Original ticket for rejection: #897

So unless you address that specifically and persuasively, I don't think it will go our way. They aren't asking how much original content we produce. They want to see we produce original research.

**Comment by drjwbaker** [comment]
No, they've clarified that the ES publication was actually rejected because it didn't have an ISSN (even though it did!), so we are good on that count.

Edit: which was a surprise to me, as originally I read the rejection the same you did @acrymble!

**Comment by rivaquiroga** [comment]
1. We currently have 45 lessons published; 4 of them are original lessons. It is important to note that since the first original lesson was published (May 2019), the ratio between this kind of lessons and translations has been 2 to 1. 
2. Regarding translations, as Marie Christine says, the process involves suggesting additional resources in Spanish. When possible, it also involves adapting the examples to the intended audience.

**Comment by drjwbaker** [comment]
@rivaquiroga This is very helpful. Thanks. Especially..

> the ratio between this kind of lessons and translations has been 2 to 1

..which the ES team should also be super proud of.

If DOAJ get fussy, I'll make a point of that fact that the EN edition will "soon" contains lessons translated **from** ES/FR to EN, so if they want to no accept ES/FR on the grounds of unoriginality, they should consider kicking our the EN edition.

In short, my view is that we have all our publications in DOAJ, or none of our publications in DOAJ. We are working to remove hierarchies between our publications, and our interactions with infrastructure should reflect that.

Rant over :)

**Comment by jenniferisasi** [comment]
Just stopping by to say 

> we have all our publications in DOAJ, or none of our publications in DOAJ.

I appreciate this solidarity.

**Comment by acrymble** [comment]
I'd like us to slow down on this ~~and put it on the agenda for our meeting~~. I've read their response to us in the Programming Historian Gmail and I don't agree with @drjwbaker 's reading of it. I also appreciate the offer of solidarity, but I don't think we should hastily move towards removing ourselves from key parts of the scholarly infrastructure (this came up a year ago too in #897). If we pull out of DOAJ we need to have someone spending a lot of effort replicating the way it helps us get into library catalogues, and I don't think that's a good use of time.

They haven't said they will accept us without scrutiny. They have asked us to reapply and said that a new assessment will be made based on their criteria which includes:

> Content: at least a third of the content should consist of peer reviewed original research and/or review papers. All content should be available in full text on the site without embargo. See our policy for journals that publish case reports.

As I've said before, 'research' ≠ 'useful', 'interesting', 'difficult', 'a lot of effort', 'valuable'.

I believe our new application will be rejected if we take this approach. I'd rather avoid that.

**Comment by drjwbaker** [comment]
Okay. Perhaps I got a tad enthusiastic on throwing toys out of the pram. But I still an unenthusiastic about only having our EN publication listed in DOAJ.

> They have asked us to reapply

Also note that the email thread also asks us to hold off from reapplying until we receive further instruction.

On `peer reviewed original research and/or review papers` I still believe that `research` is probably not the big issue you think it is Adam. Originality is I believe the key criteria. But we can agree to disagree for now and see how this pans out. We are, after all, an odd case. 

As 'Archivist' I'm happy to stay on top of this, and will of course not to anything reckless without consultation, and seek input at the text meeting.

**Comment by acrymble** [comment]
I've done some reading and I think the AHA "Guidelines for the Professional Evaluation of Digital Scholarship by Historians" (2015) may provide us with a clear response IF we are again challenged on the research content of our journals as we were last time.

It states that the AHA definition of digital history is 'scholarship that is either produced using computational tools and methods or presented using digital technologies'. It goes on to say 'Digital history in various forms often represents a commitment to expanding what history is, and can do, as a field, as well as the audiences that it addresses'.

I think we can very clearly make an argument that based on that AHA definition we publish DH digital methodology and praxis, which is digital humanities scholarship as defined by one of the key professional organizations within our field.

I'm sure most people find this boring, but I'd rather have a good answer ready if we have problems getting it through.

[Guidelines Dig. Scholarship 9.30.2015(0)-1.pdf](https://github.com/programminghistorian/jekyll/files/4875332/Guidelines.Dig.Scholarship.9.30.2015.0.-1.pdf)

**Comment by drjwbaker** [comment]
@acrymble. Very kind of you to spend time digging into this. I don't find this boring at all.

**Comment by arojascastro** [comment]
Sorry for jumping here but as Riva suggested I would argue that our translation are not literal, they are most of the time adaptations for a new audience or a remix. Translating is a creative task.

**Comment by drjwbaker** [comment]
Right. Finally making progress. I've been informed me the Editor-in-Chief of DOAJ to submit for all our publications, and "that these will be fast tracked for review". I can do this when I get a minute. @JoshuaGOB @DanielAlvesLABDH does the PT edition have an ISSN yet?

**Comment by DanielAlvesLABDH** [comment]
Hi @drjwbaker , we don't have an ISSN yet. Is up to the PT team to ask for it? If so I could start doing that. Regarding the general discussion (and sorry for not being involved earlier), my guess is that they will refuse again unless we can demonstrate that the lessons are research articles of some kind. And that is difficult because we don't do research in Humanities in our lessons, and we don't do research in Computer Science also. That is the general problem with the Digital History / Digital Humanities for decades now. On top of this we are presenting also translations, and although we can agree that they comprehend a lot of new work, new intellectual work, in the baseline they are translations. Sorry for not presenting solutions...

**Comment by drjwbaker** [comment]
On the ISSN, @acrymble: this is a publisher responsibility https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Service-Agreement/ProgHist%20Service%20Agreement%20w%20Existing%20Publications.docx Who within the Ltd team should take this?

On DOAJ, I'm more hopeful @DanielAlvesLABDH. We've had a long conversation with DOAJ over this, and I think they understand our case, are a willing to work with us to list all PH publications in a way that doesn't undermine the integrity of DOAJ.

**Comment by JoshuaGOB** [comment]
I’ve been reviewing the Brazilian center for ISSN and I can’t find any restrictions related to the journal being research oriented. https://bit.ly/2Wk1oRA I think we can provide the screenshots they’re requesting from what we have now. Would this work @DanielAlvesLABDH ?

**Comment by drjwbaker** [comment]
I'm pretty sure getting an ISSN won't be a problem: EN/FR/ES all have them.

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> On the ISSN, @acrymble: this is a publisher responsibility https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Service-Agreement/ProgHist%20Service%20Agreement%20w%20Existing%20Publications.docx Who within the Ltd team should take this?
> 
> On DOAJ, I'm more hopeful @DanielAlvesLABDH. We've had a long conversation with DOAJ over this, and I think they understand our case, are a willing to work with us to list all PH publications in a way that doesn't undermine the integrity of DOAJ.

Yes, my approach was not so positive. Thanks for all your work on this @drjwbaker and all the team

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> I’ve been reviewing the Brazilian center for ISSN and I can’t find any restrictions related to the journal being research oriented. https://bit.ly/2Wk1oRA I think we can provide the screenshots they’re requesting from what we have now. Would this work @DanielAlvesLABDH ?

Thanks @JoshuaGOB! Taking into consideration what they are requesting I think we can't ask for the ISSN before we publish our first lessons and the PT version is online. We are trying to complete the first ones, but maybe only in January it will be possible.

**Comment by JoshuaGOB** [comment]
Hi @DanielAlvesLABDH Looking over the existing publication agreement, it suggests using the British Library for the ISSN and this center has less requirements. I’m preparing the form they request and I will forward it to you as complete as I can for your review.

**Comment by walshbr** [comment]
@JoshuaGOB - were you able to get the ISSN for Pt? We're at the stage where we need that in order to finalize things with Sussex for DOIs.

**Comment by DanielAlvesLABDH** [comment]
@walshbr Joshua send me the form to ask for the ISSN, but from what I understood we can only ask that after we have our first lesson online. I have the form ready and will send the request by email as soon we go live

**Comment by JoshuaGOB** [comment]
Hi @DanielAlvesLABDH I think we are good to go. I already included the address for the “semi-live” version and double checked the info just now.

**Comment by drjwbaker** [comment]
Update: this got lost in some 'politics'. I need to find the time to make these applications. Maybe next week.

**Comment by drjwbaker** [comment]
Update: DOAJ request made for ES an FR today. And I've prodded DOAJ to remind them of why and in what context (them rejecting and no answering our emails of protest which they later agreed were well-founded) we are resubmitting ES. I'll do PT when we have a little more in there.

**Comment by drjwbaker** [comment]
Update: DOAJ rejected us, this time on different grounds ("This application is not for a scientific journal, but for a blog of lessons and tutorials"). I've written to tell them the backstory (and cc in all the DOAJ people who know the backstory) and to thoroughly reject their characterization of our work, including @acrymble's comment above. I tried not to be too grumpy in the email, but I am grumpy about this!

**Comment by acrymble** [comment]
This is frustrating. But it looks to me like they've rejected it on exactly the same grounds as the original application:

> We consider that this publication is not a scientific journal but a compilation of resources, lessons and tutorials. For this reason we cannot index your website.

I don't think we should spend more time on this application. We don't have any evidence that it increases our audience, funding, or mission. It's more of a trophy of acceptance.

**Comment by drjwbaker** [comment]
@acrymble Last time we were rejected for not having an ISSN. DOAJ have just replied saying that we were rejected by an automated process. I'm willing to persist with this as a matter of principle: we can't have the EN publication in DOAJ but not the ES/FR/PT. It isn't right. Either they accept our other publications, or they remove the EN publication.

**Comment by drjwbaker** [comment]
DOAJ have accepted both the ES and FR publications. I will now work through getting the backlog of articles on there, and when doing March/September updates do so for all three publications (per https://github.com/programminghistorian/jekyll/wiki/Service-Integrations#directory-of-open-access-journals-doaj)

At some point we'll need to add the PT edition as well, but I suspect we should wait until there is a little extra PT content

**Comment by acrymble** [comment]
Well done @drjwbaker

**Comment by jenniferisasi** [comment]
Thank you for fighting this fight, @drjwbaker!

**Comment by rivaquiroga** [comment]
This is great news! Thank you, @drjwbaker!

**Comment by DanielAlvesLABDH** [comment]
Thanks for the good news and the hard work @drjwbaker !

**Comment by drjwbaker** [comment]
Just noting here that I've added all the historic ES/FR journal data to DOAJ: ES https://doaj.org/toc/2517-5769 FR https://doaj.org/toc/2631-9462 (hit the articles tab to see the listings)
