### ISSUE TITLE
Onboarding for Aracele Torres

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1829]
This is an onboarding checklist for @aracele.

## Purpose of this checklist

This checklist is a GUIDELINES for use by anyone responsible for welcoming a new team member onto the project. It was originally written with lesson editors in mind. It therefore may need to be adjusted for people entering non-editing roles to ensure they have the training and support they need to become effective team members. Please use this in the spirit in which it was created rather than viewing it as a rigid set of rules.

---

## Welcome

Welcome to the Programming Historian Project Team. We're very pleased to have you on our team. We know that joining a new project and getting up to speed can be a challenge. So we've put together this information to help you get up to speed. It includes details of what we will do and a checklist of tasks you should complete, to make sure you know how to perform key tasks. We hope it won't take you very long and that this process will enable you to contribute your ideas and energy to their fullest.

## What we will do

Within 2 weeks of your joining, our current team will ensure that you have been granted access to the following services used by the Project Team:

- [x] Our Google Group email so you can communicate with other editors (@jenniferisasi)
- [x] Our Google Analytics account for monitoring web traffic (@acrymble)
- [x] Our Twitter team (@jenniferisasi)
- [x] Our Github Repository so you can upload materials to the site (@ZoeLeBlanc)
- [x] Our Skype group so that you can participate in our monthly calls (@mariajoafana)
- [x] partner you with an existing editor to develop a 3 month plan so that you can acclimatise to the project.
- [x] invite you to become a 'member' of ProgHist Ltd, our not-for-profit company that administers the business end of the project.

## What you should do

There are a few tasks you will need to perform to make sure you know how to use our system, and also to make sure your details appear on the Project Team page. All of these tasks are encouraged, but some may be optional:

### communication

- [x] set up a GitHub account and inform @ZoeLeBlanc of your username (mandatory)
- [x] set up a twitter account (optional)
- [x] set up a Skype account and inform @mariajoafana (mandatory)
- [x] inform @acrymble and @jenniferisasi of your Google-activated email (mandatory)
- [x] write an email to the other editors using the Google group (say hello!) (mandatory)

### technical

We rely heavily on Github for communicating and conducting our editorial processes. You will need to get familiar with it and the way we use it. We recognise that this can take time, so if you would like one-on-one training, please let someone know and this will be arranged. To make sure you can do all required tasks, try the following activities on our Github /jekyll website.

- [x] contribute to one open ticket on our github repository (mandatory)
- [x] create and assign to yourself a new ticket on the github repository to ensure you know how to do this. Add a relevant label. (mandatory)
- [x] make a technical contribution on your own. This will normally be adding your bio to the /data/ph_authors.yml file, and uploading a square black and white avatar (.png) of yourself to /avatars). You will then submit a pull request for approval so that this bio information can be added to the Project Team page (mandatory)
- [x] Read all sections of the /contribute pages of the website, including author, reviewer, and editor guidelines
- [x] Bookmark the /jekyll (https://github.com/programminghistorian/jekyll) and /submissions (https://github.com/programminghistorian/ph-submissions) github sites so you can find them easily
- [x] Read the 'Making Technical Contributions' wiki page: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions

### The Culture of the Project

We have invited you to join the team because we value your opinions. We encourage all of our editors to contribute to discussions on github or via email, and to civilly express their views, even if they disagree with any or all other members. This right to express one's opinions is central to our project. Please take this to heart.

**Comment by acrymble** [comment]
Hi @aracele if you want to email me (adam.crymble@gmail.com) with your Google-enabled email address I can add you to Google Analytics so you can see our traffic stats.

**Comment by aracele** [comment]
Done! @acrymble Thank you!

**Comment by aracele** [comment]
Hi @mariajoafana, my skype account is **araceletorres** and my twitter username is @araceletorres

**Comment by DanielAlvesLABDH** [comment]
Hi @aracele, since you already contribute to one open issue (about the logo) you can check the first technical task on the list. Maybe the second and third tasks can be related to the upload of the translation of one platform file as we talked about in our meeting. Um abraço e bom fim-de-semana!

**Comment by mariajoafana** [comment]
Welcome @aracele ! I just invited to our Skype group. Here is the info of our next meeting: #1788
The call is mainly for team leaders and optional for the rest of the team, but please let me know whether you will attend or not.

**Comment by JoshuaGOB** [comment]
Hello @aracele 
@DanielAlvesLABDH and I will be in touch soon about setting up your shadowing plan.

**Comment by aracele** [comment]
> Welcome @aracele ! I just invited to our Skype group. Here is the info of our next meeting: #1788
> The call is mainly for team leaders and optional for the rest of the team, but please let me know whether you will attend or not.

Hi @mariajoafana  Thank you! I've already accepted the invitation. Well, considering it's not mandatory, I prefer not participate since I'll be busy next week. :)

**Comment by JoshuaGOB** [comment]
Shadowing assigned which closes this ticket.
