### ISSUE TITLE
/Lessons page UX questions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1835]
I've been spending some time with the /lessons page and there are a few things I wanted to raise about user experience that I'd suggest the tech team consider. They're largely little things about building in standards widely used on the web now (some of which are newer than our site).

- The 'Start Searching' box doesn't look like a search box to me. If you add the magnifying glass icon I think it would be more obvious. (https://www.google.com/search?client=firefox-b-d&q=search+icon)
- When you click on the 'sort by difficulty', it works fine but there's no visual indicator of where "hard" becomes "medium". You have to click through to look at the metadata. In its current form it also looks like each lesson is ranked on difficulty from hardest to easiest. That's misleading. Suggest just exposing the metadata in the search (maybe by default if that's the least work).
- For a number of my ProgHist reports I have to find all lessons published in certain date ranges (eg, this year). At present that's not visible without clicking through and reading the metadata. Is it possible to expose this in the /lessons view? I think it's also useful for users to know if a lesson is 10 years old, for example.

I hope those are useful comments. I don't think any are difficult. I can try a patch if the @programminghistorian/technical-team is too busy. @ZoeLeBlanc can you let me know?

Update: @arojascastro suggested we add the DOI to the header metadata on individual lessons. Putting here so we can keep track as it's a similar type of suggestion.

**Comment by acrymble** [comment]
@ZoeLeBlanc @programminghistorian/technical-team I haven't heard anything here, and I'm not sure what your new workflows are, so I'm not sure how to proceed. If you can let me know that would be very helpful.

**Comment by walshbr** [comment]
Thanks for these good suggestions! As per https://github.com/programminghistorian/jekyll/wiki/Technical-Team, we generally to take on one feature request every four months if we can. We haven't had a tech team meeting since Matt left recently, so we could discuss then. I feel like the current priority, for me at least, is to support the PT team coming on.

But, in general, I think the workflow would be to run it by the tech lead for first response and then we'll talk about it at a meeting as we try to suss out what would be involved.

**Comment by acrymble** [comment]
Thanks for responding @walshbr. Since I haven't asked for the tech team to do the work (I said I could try myself), does that make this a communication issue instead of a tech one?

**Comment by walshbr** [comment]
Yeah that would probably make sense! Can always help troubleshoot if you or the comms team run into issues.

**Comment by acrymble** [comment]
I'm going to take this internally to the Comms team for consideration more broadly. So I will close the ticket and maybe the results will re-appear in our #1837 2020-2021 goals agenda.
