### ISSUE TITLE
Project to track copyedited lessons

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1841]
All new original lessons will be copyedited. All lessons that have undergone major updates (eg bug fixes) will also be copyedited. It is likely that in the future it will be difficult to keep track of which lessons have already been copyedited and which have not. To ensure we don't waste money we need a clear way of tracking this.

I think the easiest way would be to add a metadata field "Copyedited: True" added only when copyediting has taken place. Is this a reasonable solution? @programminghistorian/technical-team 

This affects the /editor-guidelines page in each language and this is currently frozen as the Portuguese team works on translations. So any change has to wait until at least August 2020.

**Comment by walshbr** [comment]
Are you intending this to be displayed on the site somewhere @acrymble or otherwise use it somewhere in the site infrastructure? That would be a reason to track it on the lesson's metadata. Otherwise I think I would probably not use the metadata as a project management tool like this - it's sort of clunky, and it won't be easy to see at a glance what it is still left to do. Might make sense to just have copyediting be a project that is tracked on on a project board like this - https://github.com/programminghistorian/jekyll/projects. Seems like a tool that is more fit to purpose, but @svmelton might have thoughts since she is managing the English team very well.

**Comment by acrymble** [comment]
@walshbr thanks. No it would not be displayed. As you say it's just for project management purposes.

I think the work associated with keeping this up to date would fall with either MEs or with @drjwbaker when we pay the bill for copyeditors. @drjwbaker maybe we should just keep track as part of our accounting processes? I think ME's jobs are already quite taxing.

**Comment by drjwbaker** [comment]
> Might make sense to just have copyediting be a project that is tracked on on a project board like this - https://github.com/programminghistorian/jekyll/projects.

That I like. We mostly need a place to refer to when articles come up for copyediting (e.g. when we make a major change per https://github.com/programminghistorian/jekyll/wiki/The-Programming-Historian-Digital-Object-Identifier-Policy-%28April-2020%29). I don't want us to accidentally pay twice to copyedit a lesson.

**Comment by rivaquiroga** [comment]
I like the idea of a project board!

**Comment by svmelton** [comment]
I think a project board makes a lot of sense, unless there's a specific
reason to track it in the metadata!

**Comment by acrymble** [comment]
Thank you everyone for the suggestions. I will create a project board for this and we can see how that goes. Will be in touch if I need anyone.

**Comment by acrymble** [comment]
@drjwbaker I don't think I have a copy of the invoices because I think they're offline or a way to identify which lessons they were attached to. Can you point me to the info so I can add them to the project cards?

**Comment by drjwbaker** [comment]
The invoices don't say which articles were copyedited. But I know only three have been copyedited.

**Comment by acrymble** [comment]
Which three?

**Comment by drjwbaker** [comment]
I don't know @acrymble as I don't really get involved in editing. I'd expect that relevant ME would know.

**Comment by acrymble** [comment]
@svmelton can you let us know which lessons have already been copyedited?

@drjwbaker in future can you send back invoices that don't have the lesson title on them?

I've updated the copyeditors wiki page to reflect the need to include this information in invoices. https://github.com/programminghistorian/jekyll/wiki/Copyeditors

**Comment by svmelton** [comment]
Yup, here are the 3:

- [Running a Collaborative Research Website and Blog with Jekyll and GitHub](https://github.com/programminghistorian/ph-submissions/issues/278)

- [Understanding and Using Common Similarity Measures for Text Analysis](https://programminghistorian.org/en/lessons/common-similarity-measures) 

- [Working with batches of PDF files](https://programminghistorian.org/en/lessons/working-with-batches-of-pdf-files)

**Comment by acrymble** [comment]
Thanks @svmelton . For now I can volunteer to administer this to keep another task off your plate (maybe we can think of a more automated option in future). So I can do that can you just make sure to CC me in when lesson copyediting requests go to @drjwbaker so I know to add a card?

Open to alternative suggestions.
