### ISSUE TITLE
English Ombudsperson

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1842]
As raised at the recent editorial meeting, we need a new English ombudsperson. We'll need to:

- [x] Select a person
- [x] Add them to the project team page and other pages on the site
- [x] Update the associated templates on the ph-submissions page.

**Comment by svmelton** [comment]
Just a quick update that I've made some inquiries and will hopefully have more news soon!

**Comment by acrymble** [comment]
Sorry I can't figure out where the templates are on the ph-submissions repo. Can anyone on @programminghistorian/technical-team remind me please?

**Comment by walshbr** [comment]
I think here @acrymble -https://github.com/programminghistorian/ph-submissions/blob/gh-pages/.github/ISSUE_TEMPLATE

**Comment by acrymble** [comment]
Thanks @walshbr got it.

@svmelton I have now (I think) added @ianmilligan1 to all templates, pages, etc. So he should now be fully able to take up his post!

It would be a great idea for you to introduce your team to Ian so they understand his role and understand that they too can approach him if they ever feel the need.
