### ISSUE TITLE
Annual statistics on submissions, reviews, approval rate, time from submission to publication

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1849]
Notwithstanding @acrymble's forthright blog, I have - as promised https://github.com/programminghistorian/jekyll/issues/1370#issuecomment-652260114 - gone through the Plan S implementation ticket #1370 and believe that we currently meet all of the **mandatory** conditions with the exception of one, and at that a sub-clause. Specifically we do not comply with:

> The journal/platform must provide, on its website, [..] at least basic statistics must be published annually [by the journal/platform], covering in particular the number of submissions, the number of reviews requested, the number of reviews received, the approval rate, and the average time between submission and publication.

The question is, given that this is the **only** mandatory condition we miss, if we want to pursue it.

If we did the tasks that would need attention are:

- [ ] make somewhere to put the stats
- [ ] annual collation of the stats. This *could* involve:
	- [ ] "number of submissions": search https://github.com/programminghistorian/ph-submissions/issues with variants of `created:2020 label:proposal label:French` for each journal. Register the counts.
	- [ ] "number of reviews requested": search https://github.com/programminghistorian/ph-submissions/issues with variants of `created:2020 label:submission label:English` for each journal. Look at issue. Register number of reviewers requested.
	- [ ] "number of reviews received": search https://github.com/programminghistorian/ph-submissions/issues with variants of `created:2020 label:submission label:English` for each journal. Look at issue. Register number of reviews received.
	- [ ] "the approval rate": this is trickier for our workflow, but one approach would be compare to search https://github.com/programminghistorian/ph-submissions/issues with variants of `created:2020 label:submission label:English` for each journal, and then simple compare the number of issues with the number that end up published. Alternatively, we could ask each ME for the number of email submissions they've had via the proposal form https://programminghistorian.org/en/author-guidelines#step-1-proposing-a-new-lesson that have been published vs though that haven't (minus those still in process), and calculate from there.
	- [ ] "the average time between submission and publication": for each lesson published that year in each journal, compare publication date on published version with corresponding `label:proposal` at https://github.com/programminghistorian/ph-submissions/issues

My view on this is:

1) **positive** These are useful mostly stats for us to have, because they tell us something about our work that we don't know but are sometimes asked by readers/authors.
2) **negative** There is a risk in generating these stats that we end up somehow driven/shamed/pressured by the stats, so if we choose to generate these stats we'd have to be clear that we are not stats driven and do not intend to be.
3) **negative** This takes time and energy and would need to be assigned to someone.
4) **positive** If we did this we could say we were Plan S compliant, which is something we could be proud of.
5) **neutral** We could use the Ltd to pay for this as an annual task we contract out (or to a team member who wants the paid work).

**Comment by drjwbaker** [comment]
I note @jenniferisasi that you've added this to the Comms Team report for #1788. I should make it clear that by tagging this as 'Communication' I'm not assuming I'll be handling this to you. I'm happy to work on this if we collectively want to work on this.

**Comment by acrymble** [comment]
@drjwbaker if your reading is right and this makes us plan S compliant, I'm concerned that takes away the leverage to get the planS organizers to actually engage with and acknowledge the burden they've put on publishers like us. I'm of the view that we shouldn't do this until they show meaningful willingness to engage with small publishers.

**Comment by drjwbaker** [comment]
We'd be compliant but not still missing three of the strongly recommended, so you can still make your point.

And you may get your wishes anyway, because It is within the scope of this ticket:

- to figure out how much work fulfilling this requirement would take;
- to cost it;
- to decide if that is sustainable;
- and if not, to decide how we approach demonstrating how plan S is bad for innovation in open access publishing, and campaigning for change. I saw re both replied to https://twitter.com/martin_eve/status/1287740666999701504 so we are aligned on the fact that the policy transition to OA is creating large amounts of work for small publishers.

**Comment by acrymble** [comment]
This issue is now very old and we haven't had any movement on it. @drjwbaker is this something you want to action, or should we close it at #2019 ?
