### ISSUE TITLE
Change to kramdown Markdown processor

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#185]
Apparently GitHub Pages is soon going to disallow `redcarpet` as a Markdown processor and is [requiring that GitHub Pages use `kramdown`](https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/). I need to work on this to see how this will affect us; it likely will change some things such as the way we were styling codeblocks.

**Comment by wcaleb** [comment]
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by wcaleb** [comment]
Does anyone know of a lesson that has a "table" in it? I'm looking for one to see how the switch to kramdown will affect table syntax.

**Comment by acrymble** [comment]
Introduction to the Bash Command Line

On Tue, Feb 23, 2016 at 4:42 PM, W. Caleb McDaniel <notifications@github.com

**Comment by wcaleb** [comment]
Thanks. Here's a rundown of how the change will affect us, as far as I can tell.

With redcarpet, we were using the `with_toc_data` extension; kramdown provides same functionality by default without an extension.

With redcarpet, we were using the `smart` extension to render smart quotes properly; it looks as though kramdown also does this by default.

With redcarpet, we were using the `superscript` extension so that we could do some rough footnote styling in the Pandoc lesson. But [kramdown supports footnotes](http://kramdown.gettalong.org/quickref.html#footnotes) as part of its feature set. We'll need to bring any footnotes in lessons into conformity with that syntax. I think we will lose the ability to do superscript, but since the only reason we really needed it was footnotes, that may not be a problem.

I think the main reason we were using redcarpet in the first place was to provide fenced code blocks. (See #2.) But the kramdown that GitHub Pages is now using by default now appears to offer that functionality by default.

**Comment by wcaleb** [comment]
I've done rough testing of the above changes on the [sample lesson](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/sample-lesson.md) at our submissions repo.
