### ISSUE TITLE
Improve onboarding efficiency by empowering Joshua more

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1855]
It's become clear that our onboarding process for new members is too distributed and thus very inefficient (and possibly frustrating for new members).

To improve that we're going to make @JoshuaGOB an administrator on more of the services that people need to be registered with so that they can liase with him directly to get everything set up. This should reduce how long onboarding takes and means fewer people need to be involved or paying attention to tickets.

@JoshuaGOB now has admin access to the following:

- Google Groups 
- Google Analytics
- I'll also suggest he collect skype details and pass them on to the Project Manager at Large, just to cut out a step for the new person.

This only leaves Twitter and Github permissions in the hands of someone else. @JoshuaGOB can you confirm this is all ok? I hope it makes it faster and less frustrating for new members in future. Let me know if you need any training on how to add people to these services.

I've updated the wiki to reflect the changes.

https://github.com/programminghistorian/jekyll/wiki/Onboarding-Checklist-for-New-Editors
https://github.com/programminghistorian/jekyll/wiki/Service-Integrations

**Comment by walshbr** [comment]
@acrymble did you want to give @JoshuaGOB GitHub admin rights as well? As I mentioned by email, I think that'd be fine. But @ZoeLeBlanc can weigh in on whether or not she is alright with loosening our security slightly. @ZoeLeBlanc - Josh would just be adding people to the repo.

**Comment by acrymble** [comment]
Would be great if we could.

**Comment by JoshuaGOB** [comment]
All of these are useful and I'd only be using them in the event of onboarding an editor. Thanks @acrymble for suggesting this.

**Comment by acrymble** [comment]
Great. I'll close the ticket. Maybe @walshbr you can raise that wider query about access to Github admin at your next tech team meeting and we can proceed accordingly.

**Comment by walshbr** [comment]
Will do @acrymble
