### ISSUE TITLE
Job Description for potential future paid role

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1856]
As per our recommendations from Penny Andrews and the ProgHist ltd business plan, the ProgHist team is currently working on a suggested (very) part time job within the team that will take on a range of tasks currently undertaken by volunteers. What those tasks are and exactly how this will work will be a matter of discussion across a range of teams. For transparency we will attempt this in the following manner:

- [x] @acrymble drafts a proposal for the role and circulates it for comment with ProgHist Ltd directors 
- [x] Proghist Ltd directors discuss and eventually approve it in principle at a ProgHist Ltd meeting
- [x] @acrymble takes proposal to Team Leaders of Tech, Comms, Global team for further comment and approval, and who will have the chance to share it with their teams and otherwise amend it.
- [x] depending on the extent of suggested changes, we either recirculate it or move ahead.
- [ ] Assuming no problems, post is advertised internally and if someone is found, the person takes up the role as soon as we're able to approve everything above.

We hope to have this in place by October 2020 but that depends on a lot of factors, so we will be flexible if required. If anyone has any questions, I'm happy to field them either here or confidentially via email.

**Comment by acrymble** [comment]
Update 1 Oct 2020 - this has shifted back to the ProgHist ltd team to do some budgeting.

**Comment by acrymble** [comment]
This has hit a bit of a legal snag with regards to UK employment law. But I'm still working on alternative solutions.
We're also still fundraising at this stage so we aren't yet in a position to move ahead yet anyway.

**Comment by jenniferisasi** [comment]
> This has hit a bit of a legal snag with regards to UK employment law. But I'm still working on alternative solutions.
> We're also still fundraising at this stage so we aren't yet in a position to move ahead yet anyway.

Thanks for the update Adam, and too bad there are a few stones in the way.

**Comment by acrymble** [comment]
A plan for this has been submitted to the ProgHist ltd board for (hopefully) final approval.

**Comment by acrymble** [comment]
Happy to report that ProgHist's board has approved the plan, which I'll be sharing soon with the rest of the Programming Historian team. Thanks to everyone for your input over this long process!

**Comment by acrymble** [comment]
I've circulated this to the full team so I'm closing this ticket.
