### ISSUE TITLE
Wiki page for saving tickets for the future 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1857]
In the last Project Team meeting, we discussed the follow up of older tickets to identify avenues of support. It was also suggested that we created a Wiki idea for saving tickets for the future or to identify any tickets that don't have a clear 'team' behind them. 

Once someone proposes an enhancement to the project it is often the case that no one can take the lead to make it happen, but they are valuable ideas to follow up in the future when time and resources become available. Right now those ideas seem to get lost once we close tickets.

I'm starting this issue to collect some ideas on what this section on the Wiki page should be called, and how should we reference the tickets here.

**Comment by walshbr** [comment]
We have a version of this on the bottom of the technical team wiki - https://github.com/programminghistorian/jekyll/wiki/Technical-Team. Does make sense to keep track for the project as a whole.

**Comment by acrymble** [comment]
This hasn't been implemented, and no one has taken a lead on it. So I propose closing it at #2019
