### ISSUE TITLE
Add new IPP partner to /sponsor page

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1879]
Need to add Western University to our list of sponsoring institution. Need to wait to hear from @programminghistorian/portuguese-team on the #1818 progress as pages are frozen while being translated.

**Comment by DanielAlvesLABDH** [comment]
@josircg could you coordinate with Adam the inclusion of this new reference in our apoie-nos.md? Thanks!

**Comment by acrymble** [comment]
@josircg this just needs an additional entry added to the list of Institutional Partnership Programme organizations on the /support-us page:

Our Institutional Partner Programme members:

    KU Leuven Libraries [2020-Present]
    Institute of Historical Research Wohl Library [2020-Present]
    University of Sussex Library [2020-Present]
    Centre for Data, Culture and Society, University of Edinburgh [2020-Present]

---

Add to the bottom:

- Western University [2020-Present] (link: https://www.uwo.ca/)

**Comment by jenniferisasi** [comment]
Will keep an eye on this to announce it

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> @josircg this just needs an additional entry added to the list of Institutional Partnership Programme organizations on the /support-us page:
> 
> Our Institutional Partner Programme members:
> 
> ```
> KU Leuven Libraries [2020-Present]
> Institute of Historical Research Wohl Library [2020-Present]
> University of Sussex Library [2020-Present]
> Centre for Data, Culture and Society, University of Edinburgh [2020-Present]
> ```
> 
> Add to the bottom:
> 
>     * Western University [2020-Present] (link: https://www.uwo.ca/)

Included https://github.com/programminghistorian/jekyll/blob/issue-1818/pt/apoie-nos.md

**Comment by acrymble** [comment]
Thanks @DanielAlvesLABDH I will assume I can update the other pages then, and that your translation will reflect the change.
