### ISSUE TITLE
creating-apis-with-python-and-flask no table is created

### ISSUE THREAD

**Issue by JoshCLWren** [programminghistorian/jekyll#1881]
there's a problme with the api_final code published at : https://programminghistorian.org/en/lessons/creating-apis-with-python-and-flask

First of all there's no command to create the table or any logic to not do that if the table already exists. Also, when I've added such a command the links that should be displaying content from the books.db file don't actually produce anything but an empty array in the browser. Mind you I've placed the books.db into the api directory where the api_final.py code resides as well. I've added a line in the api_all method:
    cur.execute("CREATE TABLE books (id ID, published INTEGER, author VARCHAR, title VARCHAR, first_sentence VARCHAR);")
This creates the table but the rest of the code still doesn't work to display the contents of the db.

**Comment by walshbr** [comment]
I've pinged the author.

**Comment by smythp** [comment]
Is it possible you missed the paragraph where you download a small example data set for the final section? I copy it below with the surrounding context, the second paragraph is the one with the link:

> This last example of our Distant Reading Archive API pulls in data from a database, implements error handling, and can filter books by publication date. The database used is SQLite, a lightweight database engine that is supported in Python by default. SQLite files typically end with the .db file extension.

> Before we modify our code, [first download the example database from this location](https://programminghistorian.org/assets/creating-apis-with-python-and-flask/books.db) and copy the file to your api folder using your graphical user interface. The final version of our API will query this database when returning results to users.

> Copy the below code into your text editor. As before, we’ll examine the code more closely once you have it running.

It makes sense that the final code will return an empty list if the database is empty. Please let me know if you have other questions, and thanks @walshbr for bringing this to my attention.

**Comment by smythp** [comment]
I'll also note that, after downloading the database file, moving it to the folder, and checking that the name is correct (it's possible to wind up with "books.db (1)" or similar if you already have a file with that name in your downloads folder), you'll want to remove the code you added before running, as you may wind up overwriting the file, getting a duplicate table error, etc.

**Comment by walshbr** [comment]
Closing this as it appears to be an issue not with the lesson itself. But feel free to reopen and continue the conversation!
