### ISSUE TITLE
Potential Bug in Introduction to Stylometry in Python

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1883]
A reader sent me a note about some difficulties she encountered when working through the lesson:

"While replicating we came across a few errors(?) in the code mentioned on the website; the outputs for Kilgariff's Chi-Squared Method and John Burrows' Delta Method do not match what has been stated.

We figured a probable error as to what was wrong with the Chi-Squared Method, but couldn't understand the bug in Delta Method."

![image(2)](https://user-images.githubusercontent.com/7232545/91737161-b433ff00-eb7c-11ea-89a9-f63f22b51274.png)

She tried this to solve the issue:
![image(3)](https://user-images.githubusercontent.com/7232545/91737226-cd3cb000-eb7c-11ea-950e-366b58400f39.png)

Tagging @fdlaramee to take a look.

**Comment by fdlaramee** [comment]
@svmelton -- Noted. Will take a look as soon as I can, which may take a week or more.

**Comment by fdlaramee** [comment]
Hi @svmelton -- I have looked at the lesson and the code, and I get the original (correct) results. The only thing I can think of to explain the reader's results is that they did not run all of the tests in sequence. Some of the preprocessing done for Mendenhall's is reused for the others; if Mendenhall isn't run first, all bets are off.

We could always rewrite the code to make each test independent of the others but that wasn't the original intent.

Thanks,
FDL

**Comment by acrymble** [comment]
@fdlaramee maybe just add a warning box to the lesson saying just that? In case someone else has the same problem?

**Comment by fdlaramee** [comment]
Thanks @acrymble -- Sorry, I noticed that I haven't responded to your suggestion. Yes, that would be a good way to prevent confusion in the future. I'll do it as soon as I can.

**Comment by svmelton** [comment]
Thank you @fdlaramee! Let me know if you need anything else from me.
