### ISSUE TITLE
Python programming sequence not fully updated for Python 3

### ISSUE THREAD

**Issue by aschock1** [programminghistorian/jekyll#1885]
At least several lessons in the Python sequence aren't updated for Python 3. I'm trying to assign this sequence to a class (did so successfully in 2014 and 2016, so I really appreciate it!), but am starting a class this semester, and found that much of the sequence doesn't work with Python 3.

Lesson: Working with Text Files
OS: Mac
Version: 10.5.5
Python version: 3.8

Lesson calls to use the following text:
`# file-output.py
f = open('helloworld.txt','wb')
f.write('hello world')
f.close()`

After trouble-shooting, I found that while this worked in Python 2.7, in which 'wb' writes bytes, in 3.0, the proper command is 'w'.

More serious is the issue with Downloading Pages with Python. Same system. In this case, the open-page.py doesn't work (and it's necessary for most of the further lessons in the sequence).

Here's the PH code

`# open-webpage.py

import urllib.request, urllib.error, urllib.parse

url = 'http://www.oldbaileyonline.org/browse.jsp?id=t17800628-33&div=t17800628-33'

response = urllib.request.urlopen(url)
webContent = response.read()

print(webContent[0:300])`

After trying various ways to get this to work, I contacted one of the authors, Bill Turkel, who found that the urllib module has been deprecated: [https://stackoverflow.com/questions/36781105/import-urllib-request-importerror-no-module-named-request?rq=1]

Other updates that would be good for these lessons:

- Textwranger is now BB Edit
- For Komodo edit, users need to right-click on the "Run" to get it to run (at least on Macs, double-click doesn't work)
- oldbaileyonline.org might require http**s** protocol for requests

Thanks!

**Comment by walshbr** [comment]
Thanks @aschock1! We're aware of the issues, but this level of granularity is much appreciated. 

Just a note for us - this issue has a lot of overlap with #1777, though it also raises a few other Python3 updates that could be useful.

**Comment by aschock1** [comment]
Thanks, @walshbr! I appreciate it. Now looking back through some of the threads, I can see that some of this (urllib) appears to have been on the radar. Thanks to you and all the team for all your work on PH; it's such a service to students, faculty, and the whole community.

**Comment by acrymble** [comment]
There are some relevant previous tickets:

wb vs w: #407 #1611
is the user running python3? #1810

**Comment by rivaquiroga** [comment]
Hi everyone!
Just want to let you know that all the Python lessons will go through an assessment process by our bug assessor @jairomelo. He will check that all of them are correctly updated to Python 3 and fuctional in all OS.

**Comment by walshbr** [comment]
Oh thanks @rivaquiroga I just commented on #407, but you might have just answered it. I was just noting that the issue appears elsewhere as well. My only suggestion, then, is to make sure that the .zip files get updated as well - the code in there is just meant to collect the code for each lesson, so it has the "wb" issues. Thank you for doing this!

**Comment by walshbr** [comment]
might be worth just updating the zip files for the specific lessons @Jairomelo is working on as they go, so that you can merge in the complete fixes for particular lessons when they're done (as opposed to waiting and doing all zips at the end).

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga and @jairomelo. Do you have any updates on this fix? (Are you also working on #2187? That is another Lesson Maintenance Issue that focusses on Python 3)

Let me know if there's anything I can do to support the next steps.

**Comment by rivaquiroga** [comment]
@anisa-hawes, this lesson was updated. It looks like we forgot to close the ticket. Regarding #2187 we will post the fix this week.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! That's excellent news. I'll close this now.
