### ISSUE TITLE
Create Issue and Pull Request templates

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#189]
A new feature that could be useful for us: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by ianmilligan1** [comment]
This would be great. One idea could be on the pull request template to note, once we move over to our new submissions move w/ `ph-submissions`, to provide a link to our instructions for that. Just to avoid people using our old system once we migrate.

**Comment by wcaleb** [comment]
Good idea, @ianmilligan1.

**Comment by ianmilligan1** [comment]
We talked about this during #242. Extremely brief summary: Contributing guidelines re: anti-harassment, etc. will be put into both ones, and more technical issue details (i.e. operating system, platform, etc.) on the main repo as well. It could lower the barrier to people creating tickets? 

On ph-submissions, issue boilerplate would be the review ticket that editors have been doing – so we can edit it accordingly.

Also as we move towards the new submission system, let's put text in the pull requests on the main repo directing people to ph-submissions.

**Comment by wcaleb** [comment]
In our March 29 call, we agreed to add several things:
- A `CONTRIBUTING.md` file on both repos that contains our anti-harrassment policy (see #229).
- A template for issues on the jekyll repo that gives people guidance on what information to provide about bugs (system they are using, etc.)
- A template for pull requests on the jekyll repo telling people not to submit lessons by pull request.
- A template for issues in the submissions repo with the boilerplate that we create when new lessons are received.

Anything I missed?
