### ISSUE TITLE
Translation of the .yml files of the PH platform to Portuguese

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#1891]
Starting the translation of the .yml files of the PH platform to Portuguese: Activities.yml; ph_authors.yml; snippets.yml; teamroles.yml and topics.yml

**Comment by acrymble** [comment]
Thanks @DanielAlvesLABDH can we have a week before you start on ph_authors.yml? We are currently trying to onboard some English language editors who will need to edit this file to add themselves to the project team. Is that ok?

**Comment by DanielAlvesLABDH** [comment]
@josircg e @aracele eu já actualizei os ficheiros Activities.yml; snippets.yml; teamroles.yml e topics.yml (https://github.com/programminghistorian/jekyll/tree/gh-pages/_data). Podem, por favor, dar uma olhada para ver se não me enganei ou esqueci de algo. Obrigado. O ficheiro ph_authors.yml só pode ser alterado depois de termos luz verde do Adam.

**Comment by aracele** [comment]
Oi @DanielAlvesLABDH,parece tudo ok pra mim. Apenas consertei um erro de digitação no arquivo _snippets_, e gostaria de sugerir uma alteração no _topics_. Acho que o início da linha 35, onde se lê "Dedica muito esforço à pesquisa", poderia ser traduzida como "Você dedica muito esforço à sua pesquisa" , "Você se esforçou muito em sua pesquisa" ou "Pesquisar exige muito esforço". O que acha?

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @aracele , já corrigi, optei pela última sugestão.

**Comment by acrymble** [comment]
@DanielAlvesLABDH I just want to check that the timeline is on track. I've frozen any new additions to the authors.yml file so that your team can translate it, but we do have people who want to add themselves to the project team page so can you confirm that your team are working on this? I ask because I see your pull request to add Danielle has been sitting approved and waiting to be merged for a few weeks #1894

**Comment by DanielAlvesLABDH** [comment]
@acrymble during this week I hope to finish all the .yml files

**Comment by DanielAlvesLABDH** [comment]
@acrymble merge of #1894 is done. Until the end of this week we will finish the reaming files of the Portuguese Team platform: authors.yml (@joanacvp), lessons-requests.md (@daniellesanchesDH), translator-guidelines.md (me), lesson-retirement-policy.md (me) and author-guidelines.md (@aracele and @josircg)

**Comment by JoshuaGOB** [comment]
I believe this is done. Can we close this ticket @DanielAlvesLABDH?

**Comment by DanielAlvesLABDH** [comment]
Yes @JoshuaGOB it's done
