### ISSUE TITLE
Google Scholar indexing guidelines

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#190]
Google scholar seems to struggle to get our tutorials right. They can't make out the authors from the reviewers, and don't get the difference between the whole site and individual tutorials. We might want to consider digging into their guidelines for metadata and indexing to raise the potential impact and findability of our tutorials:  https://scholar.google.co.uk/intl/en/scholar/inclusion.html#overview

**Comment by ianmilligan1** [comment]
Google has indexing guidelines [here](https://scholar.google.ca/intl/en/scholar/inclusion.html#indexing). Example:

```
<meta name="citation_title" content="The testis isoform of the phosphorylase kinase catalytic subunit (PhK-T) plays a critical role in regulation of glycogen mobilization in developing lung">
<meta name="citation_author" content="Liu, Li">
<meta name="citation_author" content="Rannels, Stephen R.">
<meta name="citation_author" content="Falconieri, Mary">
<meta name="citation_author" content="Phillips, Karen S.">
<meta name="citation_author" content="Wolpert, Ellen B.">
<meta name="citation_author" content="Weaver, Timothy E.">
<meta name="citation_publication_date" content="1996/05/17">
<meta name="citation_journal_title" content="Journal of Biological Chemistry">
<meta name="citation_volume" content="271">
<meta name="citation_issue" content="20">
<meta name="citation_firstpage" content="11761">
<meta name="citation_lastpage" content="11766">
<meta name="citation_pdf_url" content="http://www.example.com/content/271/20/11761.full.pdf">
```

A bit time consuming, but if we did so slow we could try to implement title, author, journal_title throughout each lesson? (and build into submissions)

**Comment by wcaleb** [comment]
Not time-consuming at all: I can build this into the Jekyll template so it gets generated automatically.

**Comment by ianmilligan1** [comment]
:+1:

**Comment by wcaleb** [comment]
Actually, @mdlincoln already did this in [metadata include](https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/metadata.html). So I'm not really sure why it's not working.

**Comment by ianmilligan1** [comment]
Weird. Always ahead of the curve, @mdlincoln!The only difference I see between our headers like:

```
<meta name="citation_author" content="Amanda Morton" />
<meta name="citation_publication_date" content="2013-04-01" />
<meta name="citation_journal_title" content="Programming Historian" />
<meta name="citation_public_url" content="http://programminghistorian.org/lessons/intro-to-the-zotero-api" />
```

And above is the closing slash at `/>`.

**Comment by wcaleb** [comment]
The fact that the meta tags were previously in the `body` of the lesson instead of the `head` could make a difference, but we'll have to wait a while to see if Google's spiders pick up the change. I don't think the closing slash should make a difference.

**Comment by wcaleb** [comment]
Closing this for now because I don't think there's anything else we can do but wait to see if these changes make a difference.

**Comment by acrymble** [comment]
I suspect #193 and the addition of more metadata to the lessons page will help too. They're using algorithms that look for things that are structured like journals, so we'll have to adopt bits and pieces of the genre's design.

**Comment by acrymble** [comment]
I put in a request for a crawl.
