### ISSUE TITLE
Newsletter: 3rd trimester of 2020

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1903]
As usual, I will create a list of accomplishments here and ask that you please add anything I am forgetting for the end of September (hopefully) newsletter:

- [x] First year anniversary of ProgHist Limited
- [x] New PH members
- [x] New IPP and Patreon subscribers
- [x] Note of PT edition almost ready 
- [x] FR publication looking for new editors
- [x] New lessons and translations
- [x] translate to ES
- [x] translate to FR

**Comment by spapastamkou** [comment]
We shall have published a call for FR editors by then, I will add the link soon here.

**Comment by jenniferisasi** [comment]
@acrymble are you the facilitator in this event by any chance? https://www.cdcs.ed.ac.uk/events/silent-disco-fetching-and-parsing-data-web-openrefine

**Comment by acrymble** [comment]
@jenniferisasi no I ran the first one they did along with @JMParr but it looks like they're going forward with the idea on their own. Some good impact.

**Comment by jenniferisasi** [comment]
> @jenniferisasi no I ran the first one they did along with @JMParr but it looks like they're going forward with the idea on their own. Some good impact.

Yes, it is! Saw it and was wondering to put it in newsletter. Thanks for your quick response!
