### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Khushee-Upadhyay** [programminghistorian/jekyll#1905]
I encountered an error when I tried to navigate to The Programming Historian using this link: https://programminghistorian.org/mapping-with-python-leaflet#geocoding-with-python

**Comment by walshbr** [comment]
Thanks! Where did you find that link? I found one instance of it on our site and just fixed it (the changes should appear shortly) but more details about where you found it could confirm.  For what it's worth, the link should be this (just needs the language information in the URL) - https://programminghistorian.org/en/lessons/mapping-with-python-leaflet#geocoding-with-python

**Comment by Khushee-Upadhyay** [comment]
I found this link in this article: [Visualizing Data with Bokeh and Pandas](https://programminghistorian.org/en/lessons/visualizing-with-bokeh) but it works now. Thanks!
