### ISSUE TITLE
Update `feedback` page 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1908]
Rework the wording on all _feedback_ pages to make it clear what type of bugs can be reported (and fixed) and what type we cannot attend to. 

https://programminghistorian.org/en/feedback

**Comment by drjwbaker** [comment]
I wonder how much the revision to https://programminghistorian.org/en/feedback could push readers to https://programminghistorian.org/en/author-guidelines, because we might encourage readers to see the "not bugs" mentioned by @acrymble @svmelton at https://github.com/programminghistorian/jekyll/issues/1871 as kernels of new articles. Just a thought. Happy to be ignored if MEs don't want it :)

**Comment by jenniferisasi** [comment]
No, @drjwbaker, thanks for bringing that idea up because it is a good one.

**Comment by acrymble** [comment]
I'd like to suggest that if we do continue to solicit feedback / suggested changes, that we be explicit that people need to reference changes they assert are incorrect. We often get people tell us something needs changed, and then it falls upon one of us to actually check if they're right. That research time is costly, so if we can cut down on it a bit it would be helpful. It also separates the "I think" from "I know" suggestions.

**Comment by walshbr** [comment]
Just a reminder that there is a little bit of stub text when you create a new issue - 

===

If you are reporting a problem with a lesson, please try to provide us with the following information:

- The full title of the lesson
- The system you are using (Mac, Linux, Windows)
- Version numbers of the relevant software you are using
- The exact steps you took that caused the problem

If you'd like, you can delete this template text before posting your issue.

===

But it could definitely stand to be made more robust. I agree. This would help a lot.

**Comment by jenniferisasi** [comment]
It has taken me a bit but here is my suggestion and I'll do the appropriate changes in the actual files once we comment:

**[We Appreciate Your Feedback](https://programminghistorian.org/en/feedback)**

Have you followed the instructions in a lesson meticulously and still run into an error? 
Does a command or concept need a clearer explanation? 
Thank you for taking the time to report a problem with one of our lessons. Your assistance is crucial for helping us maintain the best possible lessons! 

Note: We cannot attend to errors caused by the user editing the code or changing materials (datasets, input files, etc.)

`Get rid of Option 1 [radical, I know]`

**Option 1: Open an Issue on GitHub** 
...
If your issue has not been reported, create a new issue with a descriptive title and follow the prompt you will find with as much information about the problem as you can give.

Is anyone using **option 3 and 4** ever?

**Comment by svmelton** [comment]
We do get people making PRs on occasion, but never option 3.

**Comment by jenniferisasi** [comment]
Per @svmelton comment:

I'll do the appropriate changes in the actual files once we comment. It occurred to me that @spapastamkou @rivaquiroga and @DanielAlvesLABDH should also weight in on this. 

**[We Appreciate Your Feedback](https://programminghistorian.org/en/feedback)**

Have you followed the instructions in a lesson meticulously and still run into an error? 
Does a command or concept need a clearer explanation? 
Thank you for taking the time to report a problem with one of our lessons. Your assistance is crucial for helping us maintain the best possible lessons! 

Note: We cannot attend to errors caused by the user editing the code or changing materials (datasets, input files, etc.)

`Get rid of Option 1 [radical, I know]`

**Option 1: Open an Issue on GitHub** 
...
If your issue has not been reported, create a new issue with a descriptive title and follow the prompt you will find with as much information about the problem as you can give.

`Get rid of Option 3 `

Option 4 becomes Option 2

**Option 2: Make a Pull Request**

**Comment by spapastamkou** [comment]
I am ok with the proposed changes. I just think we should keep the channel of directly e-mailing a ME open: I think mostly about beginners or anyone who for whatever reason could be uneasy with Github.

**Comment by DanielAlvesLABDH** [comment]
I agree with @spapastamkou that we should keep the email option.

**Comment by acrymble** [comment]
I suggest changing this to 'report a bug' and then have a definition of what we consider a 'bug', because I think that's where the confusion lies.

We have 'contact' information elsewhere.

**Comment by walshbr** [comment]
It might be worth linking to the bug tag in the issue tracker rather than just the issues in general, and then also encouraging people to look for related language in the bugs (though tbh that list might be expecting too much).

**Comment by jenniferisasi** [comment]
Ok, I am going to try to refine this again:

**[Report a bug](https://programminghistorian.org/en/feedback)** /change title and url

Have you followed the instructions in a lesson meticulously and still run into an error? Thank you for taking the time to report a problem with one of our lessons. Your assistance is crucial for helping us maintain the best possible lessons! 

We define bugs as: "An error in a computer program that produces and unexpected result or that behaves different from the lesson." [please, edit] 

First, we ask that you [check on our issue tracker](https://github.com/programminghistorian/jekyll/issues?q=is%3Aissue+is%3Aopen+label%3Abug) if someone has already flagged the problem; if your issue has not been reported, follow one of these options:  

**Option 1: Open an Issue on GitHub** 
...
Create a new issue with a descriptive title and follow the prompt you will find with as much information about the problem as you can give. [+ current instructions] 

**Option 2: Make a Pull Request**
[+ current instructions] 

**Option 3: contact MEs**
If you are not familiarized at all with GitHub, you can also send an email to the corresponding managing editor of the journal in which you are consulting the lesson [link to project team?]

[In one of those yellow banners:]
Note that cannot attend to errors caused by the user editing the code or changing materials (datasets, input files, etc.)

**Comment by walshbr** [comment]
I think that's about as good as we'll be able to do! Thanks for this @jenniferisasi

**Comment by jenniferisasi** [comment]
I want to reflect here for future reference that on the version in Spanish of this page, I added a note that the users can email us if they don't know English due to our GitHub repo (and hence issue tracker) only being available in English. I suggested FR and PT do the same.

**Comment by jenniferisasi** [comment]
Done!
