### ISSUE TITLE
Optimize the use of GitHib tickets 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#1909]
As we discussed in the meeting, we open several tickets in GitHub and they are not always as effective. The question is: which types of issues require always opening a ticket and which one can be discussed via email/slack?

**Comment by jenniferisasi** [comment]
Two that we agreed on: 
- Anything that leads to an action 
- Anything that is later a pull request 
(some actions do not need a pull request, but all PR should go through a ticket)
- Onboarding for new members to keep track of the process 
- Bugs reported / in process of fixing

**Comment by acrymble** [comment]
Suggest all tickets adopt "SMART" project management criteria:

    Specific – target a specific area for improvement.
    Measurable – quantify or at least suggest an indicator of progress.
    Assignable – specify who will do it.
    Realistic – state what results can realistically be achieved, given available resources.
    Time-related – specify when the result(s) can be achieved.

**Comment by ZoeLeBlanc** [comment]
from discussion during #1917 going to see if @programminghistorian/technical-team  can help with producing analytics like this one which shows how long an issue is open on the Jekyll Repository (this one was created by me).
![chart](https://user-images.githubusercontent.com/8355129/99978205-a654db00-2d73-11eb-953d-b9361d5066fe.png)

**Comment by acrymble** [comment]
I don't think this ticket has a clear action. I propose closing at #2019 meeting
