### ISSUE TITLE
PH-FR Planning October-December 2020

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1921]
Apologies for the late creation of this ticket. 

### Call for FR editors 
End of call: 30/10/2020

### French Copy-editing
Expected in December - 1- day team workshop with date to be defined

### Original Lesson Proposals 
- [ ] Gérer et mettre en ligne une base de données avec Heurist (expected in December 2020) - editor: Sofia
- [x] Calibrer des datations obtenues par le radiocarbone avec R - editor: Sofia

### Translations Under Review 
- [x] Introduction aux carnets Jupyter Notebooks - FDL (translator); Marie-Christine (reviewer); Sofia (editor)
- [x] Rédaction durable avec Pandoc et Markdown - Marie-Christine (trnaslator); Sofia (editor)
*both published - update: 19 November 2020*

### Translation Proposals in Progress
- [ ] Downloading Multiple Records Using Query Strings - Sofia (translator)
- [x] Installer un environnement de développement pour Python (Linux) - external translator

### 5 Translations ready to review - editor wanted!!
- [ ] Analyse de documents avec TF-IDF
- [ ] Generating an order dataset from an OCR text file
- [x] Installing Python Modules with pip
- [ ] Téléchargement de pages Web avec Python
- [ ] Décomptes de fréquences de mots en Python

**Comment by mariechristineb** [comment]
@grandjeanmartin @spapastamkou si un.e d'entre vous veut se charger de l'édition, je peux faire la relecture d'une des traductions de leçon Python de @fdlaramee (ou vice-versa, je peux aussi me charger de l'édition)

**Comment by spapastamkou** [comment]
@programminghistorian/french-team @mariechristineb Il m'est actuellement impossible de prendre en charge un suivi éditorial de plus, sachant que je suis en train de finir celui d'une traduction et j'attaque par la suite la première leçon originale qui a été déposée cette semaine. Je peux vous aider de le mettre en place si toi et @grandjeanmartin vous répartissez les rôles entre vous (ou aider à rechercher un relecteur/une relectrice).

**Comment by mariechristineb** [comment]
Ça m'irait de partager les tâches avec @grandjeanmartin pour celle-ci, puisqu'on y va avec une seule relecture, n'est-ce pas? Sinon je peux essayer de trouver des relecteurs, mais dans ce cas, je repousserais à janvier (et je te reviendrais à ce moment-là @spapastamkou pour des suggestions de contacts)
