### ISSUE TITLE
Broken link in lesson: Applied Archival Downloading with Wget

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1923]
There is a broken link in the lesson entitled ["Applied Archival Downloading with Wget"](https://programminghistorian.org/en/lessons/applied-archival-downloading-with-wget). 

Here follows the link, apparently result of a search in the db of the Canadian Archives: 
[No. 14 Canadian General Hospital]: http://collectionscanada.gc.ca/pam_archives/index.php?fuseaction=genitem.displayItem&lang=eng&rec_nbr=2005110&rec_nbr_list=3366167,3203123,2005097,2005100,2005101,2005099,2005096,2005110,2005108,2005106

I tried to do the search in the db but there are several results and I can't figure out which one corresponds to the one used in the lesson. 
The broken link impeded at first the build in PR #1922 but eventually the build was succesful (after fixing three other broken links in three different pages). Not sure how to fix this, I report it however in case the problem reappears in another build.

**Comment by spapastamkou** [comment]
![broken_link](https://user-images.githubusercontent.com/27706167/97907654-e3feaf00-1d45-11eb-8c1a-7b290df4f885.png)

**Comment by walshbr** [comment]
@spapastamkou that seems like a question for the author of the lesson.

**Comment by spapastamkou** [comment]
Right, I ping @ianmilligan1 in case he can help us find the author (Kellen Kurschinski)

**Comment by ianmilligan1** [comment]
Ah, they've launched a new collection search. I can put a PR in to update the URL.

**Comment by spapastamkou** [comment]
it's ok now, thanks again @ianmilligan1.
