### ISSUE TITLE
2020 Programming Historian Deposit release

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1925]
I've just done this: https://zenodo.org/record/4244655

The next step is to update the 'Open Source' section of the 'About' page https://programminghistorian.org/en/about#open-source. Can someone please let me know if we are still holding back PRs for main pages? Or can I go ahead and update the EN/ES/FR pages? (I'm behind on the PT integration project, hence the question). Thanks!

**Comment by acrymble** [comment]
Yes you can do it. Just do it to the PT page too.

**Comment by drjwbaker** [comment]
Thanks for confirming Adam.
