### ISSUE TITLE
Correcting a detail of the preamble of the "Project Scholarship" 

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/jekyll#1930]
Hello, following the on-board! The preamble to the "Project Scholarship" page reads like this:

"The project team and members of the wider community are involved in a number of scholarly initiatives related to our work here at The Programming Historian. These include events, journal articles, reviews (of us by the community), and posters. If you are conducting academic research using this project please Sarah Melton."

It says "please Sarah Melton." but it would be better if it were "If you are conducting academic research using this project please contact Sarah Melton.".

NOTE: This is part of a test issue/pull-request sequence to support project documentation.

**Comment by DanielAlvesLABDH** [comment]
Welcome @JimmyMedeiros82 ! I think your proposal is fine. I agree with the correction to be made.

**Comment by JoshuaGOB** [comment]
Hi @JimmyMedeiros82 Please create a pull requests making the correction in the appropriate file. Se você precisar de ajuda com o processo específico para isso, você pode fazer perguntas no Github ou por e-mail.

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82! O @JoshuaGOB ou eu podemos ajudar na conclusão desta questão. Estamos quase a lançar o site, era bom ter este processo completo. Abraço

**Comment by JimmyMedeiros82** [comment]
Processo finalizado, correto? Posso fechar, @DanielAlvesLABDH ?

**Comment by DanielAlvesLABDH** [comment]
Não sei. Você chegou a fazer a alteração no ficheiro e a abrir o pull request?

**Comment by JimmyMedeiros82** [comment]
I made the pull request now. 
I thought I did that a few months ago
