### ISSUE TITLE
Better onboarding documentation

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#1932]
Per my conversation with @walshbr & @hawc2, I'm opening a ticket to discuss better onboarding documentation for new editors.

**Comment by drjwbaker** [comment]
A relevant historical discussion on shadowing https://github.com/programminghistorian/jekyll/issues/1149

And a second on a training 'event' https://github.com/programminghistorian/jekyll/issues/1056

**Comment by drjwbaker** [comment]
Discussion at https://github.com/programminghistorian/jekyll/issues/1917#issuecomment-731914136 seemingly drifted towards a one-time community/training event for new(ish) people on editing an article.

**Comment by ZoeLeBlanc** [comment]
Also maybe could add to this documentation when and how to contact tech team if you have small questions or want a an external review to make sure everything looks ok on the technical side (also coming from discussion in #1917 )?

**Comment by walshbr** [comment]
In #1906 we discussed also expanding the technical contributions section to include things like…

- how to contact the technical team
- frequently asked questions
- basic troubleshooting advice
- common errors and how to approach them
- link to the tech team slack 

Sounds like @ZoeLeBlanc will take a first pass at that portion.

**Comment by walshbr** [comment]
For the English team portion of this ticket, @svmelton how about we take the notes from the recent onboarding call, give the new editors a couple months of working on their lessons to see if they have any notes to add, add those notes, and then add them to the Wiki? Then we can reframe this ticket as being specifically about tech documentation as we close out our portion for the English team.

**Comment by walshbr** [comment]
I worked more on the onboarding docs today that came out of the collective experience of working with the three new English editors and sent them to @svmelton to check out just now. More soon.

**Comment by acrymble** [comment]
@walshbr Can you provide an update? Is this a task with specific actions?

**Comment by walshbr** [comment]
I sent a draft of the documentation to @svmelton to review, but we still need meet to discuss any changes that might be needed to it before I leave the team. @hawc2 has also given some helpful feedback on it.

**Comment by anisa-hawes** [comment]
Hello there @svmelton and @walshbr. I have joined the team today! Adam has asked me to contribute to your review of the Onboarding Documentation, as I will soon be supporting new editors at this stage. Looking forward to meeting with you both, and learning how I can be part of this process.

**Comment by walshbr** [comment]
@Anisa-ProgHist Thanks! This is sitting with @svmelton for review, but I'll send an email to you with the link for you to check out.

**Comment by acrymble** [comment]
I've had a conversation with @Anisa-ProgHist to help her understand the various bits of onboarding / training material. To help keep track of it here are some relevant pages:

* https://programminghistorian.org/en/editor-guidelines
* https://programminghistorian.org/en/translator-guidelines
* https://programminghistorian.org/en/reviewer-guidelines
* https://programminghistorian.org/en/author-guidelines
* https://github.com/programminghistorian/jekyll/wiki/Onboarding-Process-for-New-Editors
* https://github.com/programminghistorian/jekyll/wiki/Leading-a-Shadowing-process

**Comment by anisa-hawes** [comment]
Thank you, @walshbr! My role will include providing training for new editors, so I'm really keen to contribute to the development of these documents and this thinking. May I ask if you could clarify which of the materials Adam has linked above, your document is intended to supersede?

**Comment by walshbr** [comment]
@hawc2 might be able to best advise, since he was recently part of the cohort that felt the documents we had weren't adequate for the onboarding process and helped put together that document. I was just trying to answer questions and compile what seemed to be left out. But I think my sense was that the document I worked on just tried to fill in all of the social elements and implicit knowledge that might be conveyed through a shadowing process but in one place written down. @hawc2 is the stuff we put together in the google doc the sort of thing that could be added as a pull request to one of those public guidelines pages? I think it's probably the case that such a thing could be done.

**Comment by anisa-hawes** [comment]
Thank you, @walshbr! @hawc2 and I can take this forward.

**Comment by hawc2** [comment]
Hi @Anisa-ProgHist, happy to work with you on this. 

It definitely makes sense to me to use the Google Doc we created to update existing webpages. I'm not sure if we need a separate page, or if there are other ways this might lead us to consolidate the number of separate links.

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I'll start to look through the various pages on the live site + the existing WikiPages, alongside the Google Doc. I'll collate some feedback, and we can work on this together from there.

**Comment by anisa-hawes** [comment]
Alex and I have arranged to meet and discuss this next Friday 23rd July.

**Comment by walshbr** [comment]
Removing myself from assignment on this as I'm leaving the group and the two of you seem to have it from here!

**Comment by acrymble** [comment]
Update from conversation with @Anisa-ProgHist the goal for this test is to have 1 document where editors can go to both learn the process / best practices of editing, and to refresh their memory as needed.

This should be in 1 place only and not spread across multiple pages / websites / wikis

**Comment by acrymble** [comment]
Suggestions for simplifying editorial work and therefore making it easier to learn (from a conversation w @Anisa-ProgHist ):

- Stop having separate proposal/submission tickets. Just do the whole thing on one ticket only. Easier for authors and editors.
- Help editors understand the chronology of editing a lesson. This then this then this...
- Don't assume editors have experience with peer review process. Many are early in their career. It needs to be more explicit what to look for and how to do it well / productively.
- Add in explanation of the copyeditor and their role (which is newer than the guidelines)
- Make timelines clearer. How long should something take. What if it takes longer?
- can we simplify more steps or shift them to someone else (eg. checking the YAML to copyeditor?) (can @Anisa-ProgHist do the promotion of published lesson to cut out a step for editor?) (perma.cc to copyeditor?)
- a little bit of upskilling. A little bit of simplifying.
- less focus on the technical. More focus on the editorial.
- flow charts to show the processes.
- shift away from "shadowing" to having a mentor who acts as the "shadow" of the new editor.
- reintroduce the time limits on phases of the review process if they've been lost.

We will reconnect to discuss draft on 16 Sept 2021 to see if we can bring @svmelton in to discuss recruitment

**Comment by anisa-hawes** [comment]
As my second draft of our editorial guidelines are now with the English team, I am closing this Issue. 

The revised documentation is going to be tested in a pilot study for new English editors. When their onboarding is complete, I will collate feedback and open a new Issue for consultation.
