### ISSUE TITLE
Revisão de "Proposta de tradução: Instalação e Introdução ao Python"

### ISSUE THREAD

**Issue by daniellesanchesDH** [programminghistorian/jekyll#1933]
O Programming Historian em português recebeu a proposta sobre '**Instalação e Introdução ao Python**' do autor **@aracele** . Esta lição está agora em revisão por **@rsouza** e @bgmartins e pode ser lida em:

[](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/introducao-e-instalacao.md)

Eu (@daniellesanchesDH ) serei a editora no processo de revisão. O meu papel é solicitar duas revisões da comunidade e gerir as discussões, que devem ser realizadas aqui neste fórum. Eu já li a lição e forneci feedback, ao qual o autor respondeu.

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso ombudsperson Luís Ferla se achar necessário.

-

Política anti-assédio

Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso ombudsperson Luís Ferla. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by daniellesanchesDH** [comment]
Revisão das Labels.

**Comment by drjwbaker** [comment]
@daniellesanchesDH @DanielAlvesLABDH  @JoshuaGOB Is this a ticket for the first PT article translation? If so, is this the right time for me to request that our DOI partner support the PT publication? (see discussion from https://github.com/programminghistorian/jekyll/issues/1802#issuecomment-687074997)

**Comment by JoshuaGOB** [comment]
Hi @drjwbaker This is a good question that I'm following up in #1802 since I think this lesson should be in the ph-submissions repository instead of this one.
 
@daniellesanchesDH can you close this ticket and reopen it here https://github.com/programminghistorian/ph-submissions/issues

**Comment by DanielAlvesLABDH** [comment]
Hi @drjwbaker I think this is the right time to that request yes, although we have several lessons being translated so I can't say which will be the first. Is that important?

**Comment by drjwbaker** [comment]
> Hi @drjwbaker I think this is the right time to that request yes, although we have several lessons being translated so I can't say which will be the first. Is that important?

No. Which will be first isn't important. This is about the principle that our DOI provider will support the PT publication. I shall write to them.

**Comment by daniellesanchesDH** [comment]
@JoshuaGOB It is done. Thanks for that.
