### ISSUE TITLE
 ProgHist Ltd Board of Directors Meeting 11 February 2021

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#1946]
## ProgHist Ltd Board of Directors Meeting 11 February 2021

Time is 9:00 AM - Mexico, Colombia, Ottawa, Philadelphia, Boston; 11:00 AM Chile and Brasil (GMT-3); 2:00 PM - London; 3:00 PM - Paris and Berlin. @drjwbaker will be facilitating the call.

Chair: @acrymble
Secretary: @drjwbaker 
Members: @drjwbaker @svmelton @spapastamkou @amsichani @rivaquiroga 
Minutes of the last meeting: [2020-11_ProgHistLtd-BoD.docx](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2020/11-2020/2020-11_ProgHistLtd-BoD.docx).
Papers: on the [private repo](https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Board-of-Directors-Meetings/2021/02-2021).
Minutes: on the [private repo](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/02-2021/2021-02_ProgHistLtd-BoD.docx)

### Agenda

1. Apologies  
2. Approval of Minutes from last meeting & actions status.
3. ProgHist Directors administration (e.g changes of address)
4. Finance update @drjwbaker
5. Business administration @drjwbaker 
6. Goal: End of volunteering on services @amsichani 
7. Goal: Bug Reporting @rivaquiroga 
8. Goal: 40 IPP members @acrymble (including #1988 - new band pricing)
9. Goal: Job description @acrymble
10. Goal: Register as a charity @drjwbaker https://github.com/programminghistorian/jekyll/issues/1671#issuecomment-745360060
11. 2021 AGM (including invites to IPP members) - TBC May @drjwbaker  
12. Any Other Business
13. Agree date of next meeting

**PLEASE SUGGEST AGENDA ITEMS IN THE TICKET FOR INCLUSION**
Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by drjwbaker** [comment]
@acrymble Can you add the 'Goals' as agenda points please, and send me the last version of the business plan for adding to the archive. Thanks!

**Comment by drjwbaker** [comment]
Zoom invite sent to directors.

**Comment by drjwbaker** [comment]
Actions arising from meeting today:

- [x] @drjwbaker  to circulate draft minutes to Directors
- [x] @drjwbaker  to circulate minutes to Members
- [x] @drjwbaker to contact @acrymble re Register of Members
- [x] @rivaquiroga @drjwbaker to open ticket to look at bug workflow, with view to transitioning to article maintenance.
- [x] @acrymble to contact PH Team regarding approval of paid role by Directors and next steps.
- [x] @acrymble to liaise with @mariajoafana re hosting of Programming Historian AGM in May.
- [x] @drjwbaker to circulate poll to Directors + @mariajoafana for Programming Historian AGM https://github.com/programminghistorian/jekyll/issues/1797
	- [x] Fix date.
	- [x] Notify team.
	- [x] Invite IPPs
- [x] @drjwbaker to add Deputy Chair / Deputy Finance as standing item for next Directors meeting https://github.com/programminghistorian/jekyll/issues/2036
- [x] @drjwbaker to poll Directors in late-Feb on April Directors Meeting.

**Comment by drjwbaker** [comment]
@rivaquiroga: re the above..

> @rivaquiroga @drjwbaker to open ticket to look at bug workflow, with view to transitioning to article maintenance.

.. do you need help to get this started?

**Comment by rivaquiroga** [comment]
@drjwbaker, I'm working on this. I'll open the ticket on Friday with the first draft of a proposal :memo:

**Comment by drjwbaker** [comment]
Note the item 10 is now in progress.
