### ISSUE TITLE
Last Newsletter of 2020 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#1947]
We are less than a month away from leaving this infamous, longest year ever 2020 behind and hoping 2021 will be better to us, so it is time for me to collect information about what we've accomplished despite the circumstances and publish it in newsletter form. I want to do it a celebration of the entire year instead of only the three last months, a recap, with some data and vizs. 

In this issue I will begin to collect the information and, as usual, I ask that anyone that stops by and sees I'm forgetting something please add it on the ticket **before Dec 15th** (so I can write, edit, translate). 

Data: 
- [x] visitors in GAnalytics
- [x] IPP members
- [x] Patreon subscribers + money 
- [x] lessons published + under review

Information: 
- [x] publications 
-- [ ] review on [_Tidskrift För ABM_](https://www.diva-portal.org/smash/record.jsf?pid=diva2%3A1508542&dswid=8334) 
- [x] retirements: Matt Lincoln, Antonio Rojas Castro, Víctor Gayol, François Dominic Laramée 
- [x] Curso: "Taller de Introducción a las Humanidades Digitales - The Programming Historian en español" por Víctor Gayol,  15 al 21 de septiembre de 2020 (20 horas), El Colegio de Michoacán, México.

**Comment by DanielAlvesLABDH** [comment]
Hi @jenniferisasi maybe you could include this information:
Round table to present and discuss the impact of the "Programming Historian in Portuguese" in the online event "I JORNADA NACIONAL DE HUMANIDADES DIGITAIS", organized by IBICT, Brazil (October 13th) - Available here: https://www.youtube.com/watch?v=bt-OaMW2Fr4

**Comment by walshbr** [comment]
In case you wanted to include it, I'm giving a presentation for MLA 2020 on a panel called "Perspectives on Digital Publishing" with the Manifold, Fembot Collective, Debates in DH, and USLDH folks. My talk is "The Programming Historian and Editorial Process in Digital Publishing."

**Comment by acrymble** [comment]
@walshbr @DanielAlvesLABDH can you please add any talks to the /research pages? We need to keep a record for future reference.

**Comment by walshbr** [comment]
Ah good call @acrymble. Will make a note to do that. I might blog the talk, so I'll wait to to add the information to the research page until I have that material online.

**Comment by spapastamkou** [comment]
@jenniferisasi 
1) I prepared some words in French for the departure of François Dominic. Please adapt as you like and we can fix together for the final version.  
"François Dominic Laramée quitte l'équipe du Programming Historian pour se consacrer à ses activités en journalisme technologique et politique, en science des données, en traduction et en enseignement. François Dominic a été un formidable collaborateur avec une énorme contribution au lancement du Programming Historian en français et à l'offre de ses leçons sur Python. Ses compétences, son ethos et sa bonne humeur vont nous manquer, et nous souhaitons bonne chance à notre ami pour la suite de ses aventures."  

2) If possible, can we put a word that the PH en français started preparing its first original lessons? There are two of them: 
https://github.com/programminghistorian/ph-submissions/issues/329
https://github.com/programminghistorian/ph-submissions/issues/300
Please let me know and if it is the case, I can send further info. 
Thanks!
