### ISSUE TITLE
Error in command in Python pip tutorial

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1948]
[Reviewing the FR translation](https://github.com/programminghistorian/ph-submissions/issues/320) of the lesson [Installing Python Modules with pip](https://programminghistorian.org/en/lessons/installing-python-modules-pip) established that the command provided in the[ Windows instructions part](https://programminghistorian.org/en/lessons/installing-python-modules-pip#windows-instructions) of the EN original has an error. 
In the original EN lesson, the command reads currently as follows: ```python get-pip.py to install pip```  but the ```to install pip``` part must have slipped in the code by mistake as it does not correspond to a known command but it rather apparently continues the text (phrase) provided before the code. 
We'll soon be done with the translation review and can fix the error in the EN and ES versions of the lesson once I make the pull request - ~~@ssimpkin~~ @svmelton and @rivaquiroga I will ask for your reviews and perhaps you'll need to intervene to reajust the phrase. Thanks a lot to @fdlaramee for his vigilance. 
I will close this issue with the pull request that will publish the lesson in some days from now.

**Comment by spapastamkou** [comment]
I also ping @DanielAlvesLABDH to be aware in case a PT translation is in progress.

**Comment by DanielAlvesLABDH** [comment]
Thank you @spapastamkou! Will inform @daniellesanchesDH and @josircg of this small correction to be incorporated in the PT version...
