### ISSUE TITLE
FDL, Victor and Antonio leaving the team technical details

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#1967]
This issue is now modified to organize @fdlaramee, @arojascastro and @vgayolrs 's departure from the team. 

- [x] Remove Google Groups access (@jenniferisasi)  
- [x] Remove Google Analytics access (@acrymble)
- [x] Remove Github Jekyll access (@ZoeLeBlanc)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@jenniferisasi)
- [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@spapastamkou )
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@spapastamkou ).
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts ~(@mariajoafana)~ extraordinarily reviewed by @spapastamkou . 

~~Please edit if I forget something. 
@rivaquiroga Please let me know if you want me to update at the same time ph_authors.yml for Antonio as well.~~

**Comment by acrymble** [comment]
The checklist is on the wiki: https://github.com/programminghistorian/jekyll/wiki/Admin-when-team-members-step-down

**Comment by spapastamkou** [comment]
Thank you @acrymble. I pasted the correct list now - I can take up to update the files and check the open issues, unless you prefer otherwise (I put both our names in the task list). 
All- to be clear, this is the checklist for @fdlaramee stepping down from the team; in case we use this issue for @arojascastro, I will add his name in the title and we'll make a PR for both. Thank you.

**Comment by rivaquiroga** [comment]
@spapastamkou, sounds a good idea to add both @arojascastro and @vgayolrs to this PR.

**Comment by jenniferisasi** [comment]
I removed the 3 of them from Twitter and Google Groups.

**Comment by spapastamkou** [comment]
@rivaquiroga I checked in both repositories and did not find any assigned issues to Antonio and Victor so it seems ok to me. 
@acrymble Is it possible to remove also Antonio and Victor from G Analytics if it is not already the case? Sorry for the confusion.

**Comment by drjwbaker** [comment]
Done my bit.

**Comment by spapastamkou** [comment]
I created a branch for the issue and did the changes on the file there; once we are done here, I'll raise the PR.

**Comment by acrymble** [comment]
I didn't hear that @vgayolrs was leaving. It would be great if this can be made known when people are stepping down. This isn't a nice way to hear about it.

**Comment by rivaquiroga** [comment]
@spapastamkou, that’s correct. No tasks assigned. 
@acrymble, Victor announced his retirement to the Spanish team just a couple of weeks ago. I think we might expect his farewell email in the next couple of days. I agree that this is not the best way to hear about this kind of news.

**Comment by spapastamkou** [comment]
@ZoeLeBlanc @mariajoafana I assigned you as reviewers for the PR so that I do not forget any task here:)

**Comment by spapastamkou** [comment]
@mariajoafana I need some help here to make sure all tasks are finished and close this ticket (under your Project manager at large role). Thanks!

**Comment by spapastamkou** [comment]
It seems to me @vgayolrs and @fdlaramee have not been removed from Github Jekyll yet, can you please confirm @programminghistorian/technical-team ? Thanks a lot!

**Comment by ZoeLeBlanc** [comment]
Sorry for the delay and may have just screwed up a little bit. I removed both their organization access but should've I just made them outside collaborators? I didn't see a remove option specific to Jekyll so if someone on @programminghistorian/technical-team knows, I can either reinvent them back as outside collaborators or go ahead with removing organization access.

Thanks and sorry for the confusion!

**Comment by walshbr** [comment]
"go ahead with removing organization access" - I think that is probably what the wiki had in mind FWIW

**Comment by ZoeLeBlanc** [comment]
Going to clarify this policy in the Wiki but as of now we're good to go with removing organizational access @spapastamkou

**Comment by spapastamkou** [comment]
Thanks @ZoeLeBlanc and @walshbr !
