### ISSUE TITLE
Update submission guidelines to reflect reorganization of ph-submissions folder

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1968]
Breaking off part of #1795. The ph-submissions repo was a bit of a mess, with each team using their own pattern of organizing submitted lessons. I've emailed the managing directors of each language (should have just been a ticket from the go but alas) and gotten approval for this system going forward - 

/fr/lecons/
/es/lecciones/
/en/lessons/
/pt/licoes/

Though the teams are free to make their own subdirectories within their own language folders moving forward, of course. This makes things more consistent. I've already set this up on the ph-submissions side, so we just need to update the URLs in the docs to reflect where new things will be placed.

Note that the fix will apply things for future lessons only - we'll let the old lessons uploaded in weird places under the old system finish and close out rather than trying to move a ton of stuff around. So it should be the case that this will clean up the future and then past will quietly move along until it's up to date as well.

**Comment by spapastamkou** [comment]
If I get it right, it is rather /fr/lecons/ that ought to be in the list above to harmonize with the rest (/fr/traductions/ is for translations)

**Comment by walshbr** [comment]
I wonder if it might be easiest just to say some version of "New lesson submissions should be placed in the appropriate subdirectory (original lessons or translations) within their corresponding language folder in the root of the ph-submissions repository."
