### ISSUE TITLE
Feedback from student(s) of digital history in Umeå

### ISSUE THREAD

**Issue by patrikpersson** [programminghistorian/jekyll#197]
I think _The Programming Historian_ is beyond awesome. I really think more historians could find use for advanced computer tools and (basic-to-intermediate) programming skills, and your site seems to be the best there is in this regard. Congratulations on making a real contribution here.

This is a brief report from students taking [a course on Digital History](http://digitalhistorian.net/umedh2016/) at Umeå University. We used the tutorial ”Getting Started with Topic Modeling and MALLET” as part of it, and I’ve collected a few observations from our experience. Students in the course are primarily trained in history, and have widely varying backgrounds with respect to computers. The technical hurdles easily get in the way of understanding what MALLET actually does, and not all of us got everything to work. I’m a student of this Digital History course, but teach computer science at another university, and still wasn’t sure about some of the details.

Below, I’ve attempted to collect my and my fellow students’ ideas on how the tutorial could be made clearer. We hope this is useful to you.

(Apologies for dumping all of this as a single issue. Let me know if you want me to break it up into smaller parts.)
## Understanding MALLET commands

The tutorial is built up around a number of MALLET commands, but it is not always quite clear to the reader when to enter text verbatim, and when to figure out the details yourself. Of course, to use MALLET, the reader will need to figure out some of those details, but I think the tutorial could teach them in a different way.

For example, under the heading ”Importing data,” the following command is suggested:

`bin\mallet import-dir --input pathway\to\the\directory\with\the\files --output tutorial.mallet --keep-sequence --remove-stopwords`

The input file reference, ”pathway\to\the\directory\with\the\files”, needs some figuring out. I (and several others taking the course) had to spend some time on this. One way of addressing this is to make the instructions more precise, say,

`bin\mallet import-dir --input sample-data\web\en --output tutorial.mallet --keep-sequence --remove-stopwords`

Now that the reader has something that works, you could provide hints on how to change it. Point out that there is another directory of data, ”de”, and that this data can be imported using the command line

`bin\mallet import-dir --input sample-data\web\de --output tutorial.mallet --keep-sequence --remove-stopwords`

Similarly, the file path ”sample-data\web\de” can be replaced by something else to use another set of files.
## Understanding files

To help the reader to specify paths, it is probably useful to see how the command prompt relates to the (more familiar) Windows file explorer (or Mac Finder). It may be worthwhile to propose the command (in Windows)

`explorer .`

or (on Mac)

`open .`

to view the MALLET directory from the file browser. Browsing the files this way gives a much clearer understanding the paths discussed above.
## Mac & Windows

Perhaps it would be worthwhile to have separate tutorials for Windows & Mac? Translating the Windows instructions to the Mac is an additional hurdle for the reader, even though instructions are given on how to do it. The Windows-specific parts (on entering environment variables) add to this confusion.
## MALLET versions

Finally, some of us mistakenly downloaded and ran the slightly newer MALLET version 2.0.8RC3, as the download site says ”2.0.8RC3 is much more stable than 2.0.7.” In this case, the output appears to be structured slightly differently. Of course, you point clearly to the 2.0.7 release in the tutorial, but I thought this was worth mentioning anyway.

Also, when I run 2.0.7 (on a Mac) I still do not get the same results for the ”optimize-interval 20” example. The word ”xi” instead occurs in this output line:

`1 0,05106 hindi actress naa earned crossed xi premier owner boyfriend stage online bbc accomplishments kabhi portrayal romance commercial biggest mil`

**Comment by ianmilligan1** [comment]
Thanks so much for this, @patrikpersson! I think all on one issue is perfect. As one of the authors, once I have some free cycles (might be a bit of time) I really look forward to improving our lesson with this feedback in hand.

**Comment by ianmilligan1** [comment]
So when I said "might be a bit of time," I wasn't joking. But thanks again for this!
