### ISSUE TITLE
Translation Concordance Page Bugs

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1972]
While working on my MLA presentation for ProgHist I noticed that there are some issues with the translation concordance page - https://programminghistorian.org/translation-concordance. There are a bunch of blank rows, some pages are showing up in Spanish under the English column, and we'll want to make sure PT shows up there after that site launches. I've assigned myself for now, but if any other @programminghistorian/technical-team person has time and wants to take a look go for it. This is a screenshot of the bottom of the page - 
<img width="804" alt="Screen Shot 2021-01-08 at 2 38 01 PM" src="https://user-images.githubusercontent.com/2334220/104056848-2073de80-51bf-11eb-8cff-4561b493ec5b.png">

**Comment by walshbr** [comment]
I haven't actually looked at the code, but if someone else got to it first I would look at how the loop is determining which pages under the miscellaneous pages section to look at.

**Comment by jenniferisasi** [comment]
https://github.com/programminghistorian/jekyll/pull/1705#issuecomment-624320807

**Comment by walshbr** [comment]
I opened a PR - #1974 - for this. I think that it's actually an issue outside of what you and ML were talking about there, but let me know if I am wrong.
