### ISSUE TITLE
Add Brandon's MLA talk to the research page

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#1983]
Just a note to myself to add my MLA talk, which I just blogged to our research page - http://walshbr.com/blog/the-programming-historian-and-editorial-process-in-digital-publishing/. 

I also noticed just now that we don't have ML's blog post on how we do translation in Jekyll on the research page - https://matthewlincoln.net/2020/03/01/multilingual-jekyll.html. @acrymble - can I go ahead and add that in the same PR? I assume it was just forgotten as opposed to, say, not wanting to mention blog posts. Because it's definitely something folks would be interested in.

**Comment by jenniferisasi** [comment]
Don't want to step on @acrymble toes, but I think it is OK to add both items in the same PR; maybe just use a generic title or put both your last names in the title and then a note in the description.

**Comment by acrymble** [comment]
Yes it's fine with me. I think the ML one looks like it best fits in the Media & Media Contributions section?

**Comment by walshbr** [comment]
Can do!
