### ISSUE TITLE
Creating Mobile Augmented Reality Experiences in Unity/Windows 10/2018 unity

### ISSUE THREAD

**Issue by ghost** [programminghistorian/jekyll#1985]
Creating Mobile Augmented Reality Experiences in Unity/Windows 10/2018 unity

I FOLLOWED THE STEPS IN THE INSTRUCTIONS BUT WHEN I GO TO TEST MY SCENE THE IMAGE THAT IS SUPPOSED TO APPEAR AFTER YOU Scan the image target is already there behind it.
![Screenshot (1)](https://user-images.githubusercontent.com/77302007/104860130-d940c880-58f7-11eb-83b2-885b2ba9561c.png)
CN THE IMAGE target is already there.

**Comment by hawc2** [comment]
@ledds21 to make sure we debug this correctly, can you provide more information before we investigate? Where exactly in the tutorial is this error occurring? 

When you say you're 'testing' the scene, do you mean at the stage of using it on a mobile device? In which case, which mobile device are you using?

**Comment by anisa-hawes** [comment]
Hello @hawc2 and @nabsiddiqui. I've noticed that this report was submitted by a user whose account is now deleted. I'm not familiar with Unity, but if you think this is a genuine Lesson Maintenance issue, I would be happy to set aside time to install the software and test this lesson. Please let me know how you'd like to move forwards.

**Comment by hawc2** [comment]
The problem for me was I didn't understand the nature of the error
message/how to replicate it. If we have someone available to do a full test
of the session, it's not a bad idea, but I don't think we should take too
seriously bug reports like this with no follow up.

Generally I'd say, in cases like this, close the issue, and put on the
docket for testing at a later point. Sustaining a Unity lesson like this is
going to be a pain, so it should be on the docket for a refresh or
retirement at some point in the future.

**Comment by nabsiddiqui** [comment]
@anisa-hawes I agree with @hawc2 . This was a bug that was posted a while ago, and I believe we tried to do a follow up but did not get a response. These types of errors are too specific for us to troubleshoot. I'm going to go ahead and close it.

**Comment by anisa-hawes** [comment]
Understood. Thank you @hawc2 and @nabsiddiqui! We are getting through the Lesson Maintenance backlog now 🙂   so I will soon be able to start working through our older lessons, doing preventative maintenance instead of rescue. I'll prioritise our oldest lessons and those which are frequently accessed according to our site traffic data.
