### ISSUE TITLE
Team Leader - Terms & Selection Process

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1986]
I'd like to add this to discussion by the Project Team.

I propose that all 'Team Leader' roles on the 'Publisher' side of the project (Comms Lead, Tech Lead, Global Lead, ProgHist Chair) be term-limited roles with defined, but staggered terms (probably 3 years). And that the selection of new team leads be the remit of the Project Team.

This is in line with common practice in voluntary organizations like us, and it means team leaders have a period in which to make their mark and implement their vision. It also clarifies who Team Leaders are responsible to (the Project Team).

**Comment by drjwbaker** [comment]
(but we can't force someone to hold to a 3 year commitment)

**Comment by drjwbaker** [comment]
We also need to frame this positively, that is ~"we think it takes time to get used to a role, so 3 years feels about right"

**Comment by drjwbaker** [comment]
From @acrymble in https://github.com/programminghistorian/jekyll/issues/1941: last job of a team leader in their term is handover the role or decide if the team needs to continue.

**Comment by acrymble** [comment]
@spapastamkou has suggested a pre-agreed term should also apply to Managing Editors. I'd suggest also for the Project Manager at Large role @mariajoafana holds.

**Comment by spapastamkou** [comment]
@acrymble I think it should at least be noted it should be given a thought and a team may discuss this, 3 years passed, and decide whether someone is prolonged, if the person desires so, or else. 
However, there is also the case that someone precisely joins the team for the role (I think it is @svmelton 's case), and it would not be fair to decide otherwise _a posteriori_ if the person has come in a more permanent base in this role.

**Comment by jenniferisasi** [comment]
Something to consider: how will sabbaticals or leaves affect this "timeline"?

**Comment by svmelton** [comment]
That's a good point @jenniferisasi—I could very well see life events arising in the span of 3 years that would necessitate a sabbatical of a couple months or more.

**Comment by spapastamkou** [comment]
For MEs: @acrymble had once the idea that a ME can be assisted by another team member (smth like assistant ME). This is a good idea, as there would be someone familiar with the tasks who could possibly substitute a ME if needed.

**Comment by acrymble** [comment]
For MEs, I believe our service agreement means that individual publications have the authority to choose their ME. So we can come up with transition guidelines, but I think the project team has to be careful not to interfere directly in who the ME is.

For parental leave, I think we want to be adopting best practices for this. Does anyone know what the advice is? I'd think the leave would be part of the term, for simplicity of planning purposes within the wider project. But I don't know the repercussions of that suggestion.

**Comment by acrymble** [comment]
I think this issue may need to be broken into stages to be fully resolved.

1. We agree that the following roles are appointed (in future) by the Project Team: Global Lead, Comms Lead, Proghist Chair, Tech Lead, Project Manager at Large.
2. If we agree 1 above, each of the people holding those roles talk to their team about an appropriate and reasonable timeframe for the role, with 3 years the suggested starting point for discussion. They report this to the Project Team.
3. A group of 3 people come up with a plan for how this all works in practice, taking into account issues such as sabbaticals, family leave, illness, if more than one person wants a role, if no one wants a role, if we want to change/remove a role, etc.
4. We have a separate conversation about MEs (as ME selection is not the remit of the Project Team, except in dire circumstances)

**Comment by acrymble** [comment]
We've agreed that we will take this forward at our Project Team meeting #2019 and we will move to step 2 above.

**Comment by acrymble** [comment]
People with roles affected by this (I'm guessing a bit on times roles began):

@acrymble - ProgHist Chair - began role c. May 2020
@ZoeLeBlanc  - Technical Lead - began role c. June 2020
@mariajoafana  - Project Manager at Large - began role c. May 2020
@jenniferisasi - Comms Lead - began role c. June 2019? - stepping down December 2021
@JMParr - Global Lead - began role c. June 2019?

---

Can I get 2 people from @programminghistorian/project-team to volunteer to join me to do step 3: A group of 3 people come up with a plan for how this all works in practice, taking into account issues such as sabbaticals, family leave, illness, if more than one person wants a role, if no one wants a role, if we want to change/remove a role, etc.

**Comment by acrymble** [comment]
I haven't had any volunteers. @nabsiddiqui @JMParr are you available to join a working group on how to appoint these roles in future? It will involve a few zoom calls and a google doc, most likely.

**Comment by nabsiddiqui** [comment]
@acrymble Yes, I can but it will have to be after this month (even May 1st is fine).

**Comment by acrymble** [comment]
3. A group of 3 people come up with a plan for how this all works in practice, taking into account issues such as sabbaticals, family leave, illness, if more than one person wants a role, if no one wants a role, if we want to change/remove a role, etc.

## Proposed solution (that I hope takes into ideas expressed above):

- As the affected roles are currently occupied by people on undefined terms, we continue as normal. If and when those individuals want to step down from those roles, they inform the Project Team at a Project Team meeting and it is noted in the meeting minutes. We would appreciate notice of at least 6 months if possible.
- Project Team then assigns a sub-team of 2-3 people to investigate and make recommendations on the continued / altered need for said role and brings them to the next Project Team meeting for discussion. Outcome may be: no need to replace (role ends), replace as-is (new candidate), replace with amendments (new but closely related role).
- If a new candidate is needed, a role description and ideal term length is written & approved and circulated internally to all Members for expressions of interest. Candidates submit roughly 250 word vision for the role for consideration by membership. If more than one candidate, then a private ballot determines the winner. If no candidates come forward, we proceed with an external advertisement.
- All roles will be 3 year terms unless agreed otherwise. Role holders are encouraged to take up to 12 month leaves / sabbaticals as needed, in line with our [sabbatical policy](https://github.com/programminghistorian/jekyll/wiki/Checklist-for-Sabbaticals), in which case an interim person may be appointed using a similar method.
- This task of chairing and administering the replacement process will be agreed between current team leaders (my suggestion is Project Manager at Large, but I don't want to impose that on anyone without asking), and will be folded into someone's official role in future when an appropriate vacancy arises.

@nabsiddiqui can you take a look at this and let me know if I'm overlooking something or otherwise making a poor suggestion?

**Comment by nabsiddiqui** [comment]
@acrymble This looks largely good to me. In terms of the sabbatical policy, it should be noted that not all places provide a 12 month sabbatical. I am assuming that the affiliation of the role does not make a difference to the length provided by Programming Historian, but I would make this explicit. In addition, I think that we should frame our suggestions in more positive terms. Research shows that people will often continue to work despite having the ability to take parental leave, etc. I would like framing that says that we encourage, although do not require, such breaks during family illnesses, births, sickness, etc.

**Comment by acrymble** [comment]
Thanks @nabsiddiqui I think these suggestions maybe need to go into our sabbatical policy text to clarify that policy:  https://github.com/programminghistorian/jekyll/wiki/Checklist-for-Sabbaticals.

I'll amend the above as well.

**Comment by acrymble** [comment]
@Anisa-ProgHist it was agreed today at the Project Team meeting that I'd add this to the wiki and close the ticket. Do you have a suggestion for where this should go on the wiki?

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. I feel it would fit best within the Human Resources section, e.g., following the pages detailing Privileges-and-Responsibilities-of-Membership and Admin-when-team-members-step-down. 

Would you like me to create a new page? 

I notice that the Human Resources section doesn't appear on the Wiki's Home page, neither the heading nor contents. Does this need adjusting too?

**Comment by JMParr** [comment]
Agree with Anisa's suggestions.

**Comment by acrymble** [comment]
Thanks everyone. Added it and fixed the Wiki.
