### ISSUE TITLE
Middle IPP band criteria

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#1988]
Having spoken to @rivaquiroga she's suggested we adopt a middle cost band for IPP to bridge the gap between the current £150 and £1000 costs. This may open up the option for more middle income countries to join. We're discussing an appropriate price point, but I also wanted to discuss appropriate criteria. At present we have ODA-eligible (countries eligible for foreign aid) and everyone else.

There doesn't seem to be a great set of criteria for 'wealthy' vs 'middle income'. The World Bank keeps a list, but it may be problematic. I'm going to put forth a fairly simple suggestion of countries listed with a GDP per capita of greater than $30,000 in the top price band. Those who are ODA-eligible to stay in the band they have, and everyone else eligible for the middle category. 

There's a pretty clear list on WIkipedia that we can use for our purposes: https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28PPP%29_per_capita

Can anyone raise potential implications I haven't thought of?

**Comment by drjwbaker** [comment]
My only thing is do team members want me to enforce this? E.g. if we have a middle band and a research group at a - say - Spanish institution wants to join as IPP but pleads poverty and want to join in middle ban (Spanish HE isn't as rich as UK HE, or that is my understanding) shall I just accept this?

I guess that I'm saying is, can we find a way to describe the middle band as a "we'd love to help but can't afford full IPP" band?

**Comment by acrymble** [comment]
@drjwbaker I think we have to take each one on as a conversation. Especially because in many parts of the world prices are always seen as negotiable. These are really just conversation starters. But the sentiment of what you describe in the 'we'd love to help' is really why we have suggested another level, since that's the feedback we got.

**Comment by drjwbaker** [comment]
Okay. Let's call it something like "Middle Income Countries" band and we can monitor the responses we get.

**Comment by jenniferisasi** [comment]
For the sake of acknowledgement of different economic realties, can we say "middle income countries and/or institutions with limited resources"? Maybe not in the chart title but somewhere? I am thinking of institutions that would like to contribute but cannot pay the partnership fee even if they are in one of the richest countries; I think it could also be a way of starting the conversation @acrymble?

**Comment by acrymble** [comment]
We'll set this at £400 and I'll do a pull request as soon as I've got the french pages live.
