### ISSUE TITLE
downloading pip - broken link

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#199]
@fredgibbs I think the 'which you can download here' link in your pip lesson is outdated: https://raw.githubusercontent.com/pypa/pip/master/contrib/get-pip.py

The link points to a new address: https://bootstrap.pypa.io/get-pip.py

Are you happy that this is in fact the correct new link?

**Comment by fredgibbs** [comment]
yes, as far as i can tell, the bootstrap link is the best one and replicates the functionality of the previous link.

**Comment by ianmilligan1** [comment]
OK swapped the link out (just trying to get these issues under control with a spare cycle).
