### ISSUE TITLE
How should we highlight code blocks?

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#2]
@fredgibbs I'm preparing to use Pandoc to do a massive bulk conversion of all existing lessons into Markdown. Before doing so, I've been doing some thinking about how code blocks should be handled in the new site.

In the lessons you've already converted, you used Jekyll's preferred highlighting feature. But the problem with this method is that when you view the markdown files in Github, the Github browser itself doesn't recognize those highlighting codes, and instead interprets things that should be commented lines in a code block as level-1 headers.

I'm wondering if it might be better (and would make us less dependent on Jekyll in the long run) to instead use raw HTML tags like `pre` for code blocks, and then use CSS styling to handle the language-specific highlighting. That way they would look readable either on the site or on Github.

Thoughts on this issue? Here are a couple of (oldish) sites that outline some of the different possibilities:
- https://gist.github.com/zakkain/3203448
- http://demisx.github.io/jekyll/2014/01/13/improve-code-highlighting-in-jekyll.html

**Comment by nivaca** [comment]
I suppose this is a related issue. I was wondering why syntax highlighting in markdown code blocks, which normally looks great in GitHub, is ignored here.

For instance, this code:
```XML
<text>
  <body>
    <div type="recto">
      <!-- aquí iría la cara frontal -->
    </div>
    <div type="verso">
      <!-- aquí iría la cara de atrás -->
    </div>
  </body>
</text>
```
which as you can see looks great here (rendered by GitHub), looks like so in PH:

![image](https://user-images.githubusercontent.com/2309005/134827999-034bee88-fc6c-4ee1-baf4-a85e433e9c38.png)

I don't know if this a bug or a feature (as some people prefer no syntax highlighting at all).

**Comment by acrymble** [comment]
@anisa-hawes can you investigate if there's a required action here?

**Comment by hawc2** [comment]
@acrymble seems like this issue can be closed and the broader question raised here can be added to a list of features under consideration for website redesign or enhancement at a later point. Unless I'm mistaken there's not a current problem with PH's code rendering that needs to be resolved here . . .

**Comment by anisa-hawes** [comment]
I've added this Issue to [a Project board](https://github.com/orgs/programminghistorian/projects/2/views/1) where I am keeping note of ideas for enhancements to improve users' experience of our website and its contents.
