### ISSUE TITLE
Outdated version of Git Bash in to Bash lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#200]
Link at 'the mysgit featured downloads list' (https://github.com/msysgit/msysgit/releases/) warns:

PLEASE NOTE: Git for Windows 1.x is deprecated, superseded by Git for Windows 2.x.

This is in big bold letters so MUST ber serious!

Line 33: https://github.com/programminghistorian/jekyll/edit/gh-pages/lessons/intro-to-bash.md

**Comment by acrymble** [comment]
@drjwbaker and @ianmilligan1 is this important?

**Comment by drjwbaker** [comment]
@acrymble  I don't think it makes a difference. Just that you need to click through all the alarming warnings to this https://git-for-windows.github.io/ (which I appreciate for a beginner may be off-putting).
For info, I ran a doctoral training workshop where I pointed the attendees at the lesson to find the right software to install for learning Bash. They found it fine in spite of all the warnings (which I noticed at the time and forgot to inform you of. Sorry...)

**Comment by ianmilligan1** [comment]
Hmm, should we change the link so it's a direct one to https://git-for-windows.github.io/?

**Comment by drjwbaker** [comment]
Probably.

**Comment by drjwbaker** [comment]
(though given that the Git page flags the depreciation and redirect it _may_ prove more sustainable than https://git-for-windows.github.io/)

**Comment by ianmilligan1** [comment]
I figure for now we're on top of this stuff, so let's change it to the URL that won't freak out our already brave readers..
