### ISSUE TITLE
Blogpost for PT launch

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2000]
Opening this issue for the announcement of the launch of PH in Portuguese. 

@DanielAlvesLABDH and team is working on a blogpost, this issue is to record the process before opening a PR with the text. 

Once I receive the blogpost, I will add and/or translate a couple of sentences at the end in English, Spanish and French to make it a little more accessible.

**Comment by drjwbaker** [comment]
If there is going to be a list of thank yous, can we please include a general thank you to our IPPs for their support (because they give us the confidence to grow), and especially to Sussex for extending their DOI support to the PT journal.

**Comment by mdlincoln** [comment]
omg @ZoeLeBlanc just told me the news. 🍾🍾🍾🍾🍾  congrats all!

**Comment by rivaquiroga** [comment]
@drjwbaker, your lesson is now the first one to be translated in all four languages!

![four-languages](https://user-images.githubusercontent.com/31421616/106300431-42e49f00-6235-11eb-93d6-b630a7c0260b.png)

**Comment by DanielAlvesLABDH** [comment]
Here is the Portuguese version of the blog post:

![Portugal](https://user-images.githubusercontent.com/62759376/106333141-f3779080-627f-11eb-9691-434dd0bb2f7d.png)
É com uma enorme alegria que anunciamos hoje a publicação do _The Programming Historian em português_! São quatro as línguas agora disponíveis no projecto, reforçando a sua internacionalização, diversidade e alcance global. A versão em português, disponível em [https://programminghistorian.org/pt/](https://programminghistorian.org/pt/), resulta de um esforço colectivo de uma ampla equipa de voluntários de Portugal e do Brasil. A equipe inicial, que preparou a tradução da plataforma e vai assegurar as primeiras lições, conta com o contributo de colegas da Universidade Nova de Lisboa (Portugal), da Fundação Getúlio Vargas (Brasil), do Instituto Brasileiro de Informação em Ciência e Tecnologia (Brasil), do Instituto Superior Técnico (Portugal) e da Universidade Federal de São Paulo (Brasil). Mas é uma equipe que está aberta a novas colaborações com outras comunidades académicas e outras áreas geográficas de língua portuguesa, nomeadamente na África e na Ásia. Teremos muito gosto em contar com o [contributo](https://programminghistorian.org/pt/contribua) de todos, num ambiente inclusivo e de ampla diversidade!
O nosso objectivo é poder contribuir para expandir as competências digitais da comunidade de historiadores e humanistas em geral que falam português. Nesse sentido, vamos oferecer tutoriais de métodos digitais variados que poderão ser úteis para o ensino, investigação e publicação. Nos primeiros tempos, daremos prioridade à tradução de algumas das lições já existentes nas outras três línguas do _Programming Historian_, o [inglês](https://programminghistorian.org/en/), o [espanhol](https://programminghistorian.org/es/) e o [francês](https://programminghistorian.org/fr/). Neste esforço de [tradução](https://programminghistorian.org/pt/directrizes-tradutor) todos os interessados poderão participar, mas gostaríamos muito de também [receber tutoriais originais](https://programminghistorian.org/pt/directrizes-autor) sobre ferramentas e métodos digitais ainda não disponibilizados pelo projecto. Estamos prontos para colaborar convosco!
Concretizar o projecto do _The Programming Historian em português_ foi um trabalho de equipe, colaborativo, intenso, dialogante, e que ficou a dever profundos agradecimentos a todos os voluntários que acreditaram na iniciativa logo desde o início. Mas é também devedor a todas as equipes do _Programming Historian_, sejam a equipa técnica e de comunicação, a equipe global ou as equipes específicas das versões inglesa, espanhola e francesa. Todos foram inexcedíveis na simpatia, paciência e competência com que nos receberam e na partilha de conhecimento e experiência que possibilitaram concluirmos com êxito este primeiro passo! A todos o nosso muito obrigado!
Uma última palavra de agradecimento a todos os participantes no nosso [Programa de Parceiros Institucionais](https://programminghistorian.org/pt/apoie-nos#programa-de-parceiros-institucionais), pelo seu apoio que nos dá confiança para crescer, bem como à [Universidade de Sussex](https://www.sussex.ac.uk/) por estender ao _The Programming Historian em português_ o apoio à obtenção dos DOI das lições.

_Imagem: Captura de ecrã da “[«Home Page» de Portugal / Portugal Home Page](https://arquivo.pt/wayback/19961013145852/http:/s700.uminho.pt/homepage-pt.html)”, 1996. Página mais antiga da Internet portuguesa com referência a Portugal preservada no Arquivo da Web Portuguesa – [Arquivo.PT](https://arquivo.pt/)._

**Comment by DanielAlvesLABDH** [comment]
What is the usual process for announcing the new language version? Should I wait for the blog post to go live or can I start sharing the "PH em português" on our own social networks? Once again thanks for all your help! Obrigado!

**Comment by jenniferisasi** [comment]
Obrigada @DanielAlvesLABDH! I am going to prepare the document right away and will open a PR with it for your revision. Shouldn't take me too long. 

I would wait for us to publish the blogpost to announce it officially so that you have "something" to send along the website. That is why I haven't posted it on Twitter yet either, so that our users can also read about how _The Programming Historian em português_ came to be :)

**Comment by DanielAlvesLABDH** [comment]
Thank you! If you need any help with the translation @jenniferisasi, just let me know
