### ISSUE TITLE
Translation Concordance Bug - Pt Lesson Template

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#2002]
Take a  look at why that file appears twice, under English and Pt. 

<img width="958" alt="Screen Shot 2021-01-28 at 8 01 14 PM" src="https://user-images.githubusercontent.com/2334220/106217677-c190fc00-61a3-11eb-8c5f-a565ec227519.png">

**Comment by jenniferisasi** [comment]
1) they appear twice because the PT team has copied but not translated that file in pt/licoes-modelo.md or maybe it was misplaced. 

2) the EN, ES and PT are not in the same row because those files are missing the YAML that will connect them with an "original" field.

**Comment by jenniferisasi** [comment]
To begin the process here, 
1) I want to ask @DanielAlvesLABDH if the PT team has or is planning on translating to Portuguese the page https://programminghistorian.org/pt/licoes-modelo.md  

2) I will add YAML to the lesson-template files and go from there (see if additional changes are needed)

3) I realized in checking the author guidelines in ES doesn't match/direct to the same page when clicking on EN/FR/PT that can also be seen in the translation concordance. Will look into that. 
![Screen Shot 2021-02-02 at 10 28 31 AM](https://user-images.githubusercontent.com/11022533/106622254-68c5b880-6541-11eb-86a1-6209e9929c83.png)

**Comment by DanielAlvesLABDH** [comment]
Hi @jenniferisasi! We are planning to translate that file. Next week we will have a team meeting to decide that and other things

**Comment by jenniferisasi** [comment]
> Hi @jenniferisasi! We are planning to translate that file. Next week we will have a team meeting to decide that and other things

Thanks @DanielAlvesLABDH, maybe let me know when you make a decision and we take it from there; maybe it is better for us to wait for you to translate the file so we don't do too many changes almost at the same time.

**Comment by DanielAlvesLABDH** [comment]
Hi @jenniferisasi, the team decided to translate the file. @joanacvp volunteered to the task.
