### ISSUE TITLE
Add PT to Twitter Bot

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#2006]
@DanielAlvesLABDH - this is a placeholder ticket to document our need to add the Pt publication to the Twitter bot. We typically wait until the new language publication has ~7 lessons before doing so. It just works from a spreadsheet and tweets things randomly from it. So if you only have, say, two lessons, it would just cycle those lessons every few days forever. So we want some low threshold at which we'll start incorporating it. Ping me here when you have that handful merged and live?

**Comment by DanielAlvesLABDH** [comment]
Right! Will keep an eye on this and let you know. The plan is to have 6 lessons in the next 3 to 6 months. Let's see if we can deliver

**Comment by jenniferisasi** [comment]
And until you have enough lessons for the bot, what we do is tweet about them manually: 1) when you publish the lesson (the editor always tweets about it because the bot can take a while), and 2) any random day you want you can tweet or you can tell me to tweet.

**Comment by DanielAlvesLABDH** [comment]
Hi @walshbr , we now have 7 lessons live! Maybe it is time to include things on the Twitter bot. Let me know about the next steps. Do we have documentation about that?

**Comment by walshbr** [comment]
Yep! @DanielAlvesLABDH It's in the Author Guidelines - https://programminghistorian.org/en/editor-guidelines#6-incorporate-your-lesson-into-our-twitter-bot. I just added you to the spreadsheet - let me know if it didn't go through. I made a tab for Portuguese. The first step is for you to fill in the first three columns on that tab. You can look at the tabs for the other lessons for guidance, but I'm happy to answer questions. Once you have the rows filled out there tag me here, and I'll try to get things going.

**Comment by DanielAlvesLABDH** [comment]
Thank you @walshbr. I already asked @joanacvp and @daniellesanchesDH to take a look and add the info in the spreadsheet.

**Comment by acrymble** [comment]
Is this now ready to go live @DanielAlvesLABDH ?

**Comment by DanielAlvesLABDH** [comment]
@acrymble this is ready. Just confirmed with Joana and Danielle.

**Comment by walshbr** [comment]
@DanielAlvesLABDH there are only four lesson tweets in the spreadsheet - were you going to add others there or did you want me to go ahead and finish it up?

**Comment by DanielAlvesLABDH** [comment]
Hi @walshbr, the info is now corrected and we have 7 lesson tweets. By mistake, some of the tweets were introduced in the English table ;-)

**Comment by walshbr** [comment]
Ha! Ah good. I'll work on this as I'm able. Just wanted to note here that I think I did everything correctly and updated some of the documentation, but ran into a couple errors while testing that I'll need to troubleshoot.

**Comment by walshbr** [comment]
I think I got this set up @DanielAlvesLABDH. It successfully tweeted out from my terminal, but the final step is always making sure that the scheduler worked correctly. So keep an eye out July 1st at 1:30PM UTC for the first one. And then let's circle back in a week to make sure it worked right and we can close this out. When I added French I accidentally made it tweet in French every ten minutes forever at first so it's good to check haha.

**Comment by DanielAlvesLABDH** [comment]
Thanks a lot @walshbr! I will take a look. It was literally a "French revolution"! ;-)

**Comment by walshbr** [comment]
Oh actually the way it schedules is a bit confusing - I have to give it days of the week as numbers 1-7, and it starts over on Mondays. So I _think_ the first tweet should come out on Monday.

I wrote about this on the documentation for the bot earlier, but in case you're interested -

The bot actually runs a series of terminal commands every day at particular times. And each of those commands has logic in it to check what day it is. If it's not the right day for that type of tweet it just shuts off. So the PT command will start running everyday tomorrow, but it will get ignored until Monday.

**Comment by DanielAlvesLABDH** [comment]
Thank you @walshbr! Just to let you know that the fist tweet is out!

**Comment by walshbr** [comment]
That first tweet yesterday was me testing it manually :) Let's give it a week before closing this to make sure it runs on its own, but fingers crossed!

**Comment by anisa-hawes** [comment]
Hello @walshbr, Have you already re-assigned the management of our Twitter Bot, or is this something I can take on for you?

**Comment by walshbr** [comment]
We have not! I think it probably makes sense for @ZoeLeBlanc to take over the management of it in her capacity as technical lead given the technical weirdness of how I set the thing up, but if you feel comfortable you totally can. Day to say the thing doesn't require much management beyond adding to the spreadsheet. But adding a new language involves adding about 15 lines of Python to a script (I tried to document pretty clearly where and what to add), a series of terminal commands, and then adding some lines to our heroku account. We don't add languages to the bot very often. If you want, you could check out the instructions here - https://github.com/programminghistorian/proghistbot - to see if you'd be comfortable. Also to let me know what things need to be added -  I have a feeling that I'll need to resurface whenever the next language gets added and someone tries to walk through the documentation there.

**Comment by acrymble** [comment]
@walshbr sounds great to have it with @ZoeLeBlanc . Can we please update the https://github.com/programminghistorian/jekyll/wiki/Service-Integrations to reflect that new ownership? I believe it needs a new token for it to work in your absence.

**Comment by walshbr** [comment]
I'll need to share the credentials json file with her by email. We could also rotate the credentials and re-generate them if she really wanted to practice good security hygiene, but that would also require updating things in the Heroku account as well. Updated the wiki.

**Comment by walshbr** [comment]
I noticed this was not working correctly, and I think I caught the syntax error that was causing the PT bot to fail. Will keep an eye over the next week to make sure that it works correctly and then close if it does!

**Comment by DanielAlvesLABDH** [comment]
Thanks for keeping an eye on this @walshbr

**Comment by walshbr** [comment]
Seems to be working @DanielAlvesLABDH. So I'll close this.
