### ISSUE TITLE
Mac M1 Big Sur issues for "Building a static website with Jekyll and GitHub Pages"

### ISSUE THREAD

**Issue by johnpilbeam** [programminghistorian/jekyll#2028]
Same as @quinnanya this is a great tutorial, but it is not working for me on my current machine (Mac/M1/Big Sur). Everything is fine up to the Homebrew install, this is different on M1 based Macs ([https://docs.brew.sh/Installation#macos-requirements](https://docs.brew.sh/Installation#macos-requirements)). 
I could not install Ruby & Ruby Gems/Jekyll according to the instructions, in fact ended up breaking my system Ruby and had to reinstall (my fault, not the tutorial's, but without the right instructions, it is surprisingly easy to trash Ruby). 
This might be an edge case as I had setup the M1 Mac via Migration Assistant from an Intel machine with Homebrew and Ruby installed. However, I do think that Ruby installation on the Mac is fraught with problems which is not helped by the semi-deprecated/out-of-date system Ruby and the Apple Silicon transition, and the guide doesn't take this into account. One alternative route might be recommending a script (e.g. [https://github.com/monfresh/install-ruby-on-macos](https://github.com/monfresh/install-ruby-on-macos)) - I'm sure there are other laptop scripts available too) which standardises and takes some of the pain out of installing Ruby on a new Mac.

_Originally posted by @johnpilbeam in https://github.com/programminghistorian/jekyll/issues/1955#issuecomment-773189924_

**Comment by walshbr** [comment]
Thanks for the information! We are working on this.

**Comment by acrymble** [comment]
@Anisa-ProgHist I think this is the same problem as #1955. Maybe you can close both at the same time?
