### ISSUE TITLE
Broken Link in regex lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#203]
404 error link to http://www.pythonregex.com/

in http://programminghistorian.org/lessons/cleaning-ocrd-text-with-regular-expressions

**Comment by ianmilligan1** [comment]
Right now, I'm going to delete the sentence:

"For PC users (or people who don’t want to pay or download software), I also found another tester tool that was fairly transparent" which contains the broken link.

I checked out the Wayback Machine and the link is dead. This is semi-equivalent: http://www.pyregex.com/. Would the author endorse this as a replacement, maybe?

**Comment by ianmilligan1** [comment]
@fredgibbs are you in touch with the author? Or do you think this is an acceptable solution. Let me know if we should close or keep open.

**Comment by fredgibbs** [comment]
We could email the author, but I think in this case, as well in similar ones where we can make a basic change that more or less replaces no-longer-extant functionality of the original lesson, we should go ahead and do so. Let's close and be done.
