### ISSUE TITLE
Naive Bayesian warning message

### ISSUE THREAD

**Issue by sharonhoward** [programminghistorian/jekyll#2031]
I've just noticed that the Naive Bayesian lesson still has a "technical issues with the Old Bailey Online" warning message. I've been using the OB API in the last few days (in fact I was visiting the lesson to "borrow" some of the code) and as far as I know it was fully restored and works exactly as it did before the technical problems occurred. So the lesson *shouldn't* need any changes, though I'm sure you'll want to test that out for yourselves.

**Comment by svmelton** [comment]
Thanks, Sharon—we've had a couple of people reach out in the last two weeks via email about the lesson, so I think we should keep the warning by now. I'm hoping we can eventually remove the warning!

**Comment by sharonhoward** [comment]
No problem. If you want to pass on any details of technical issues the email is oldbailey@sheffield.ac.uk.
