### ISSUE TITLE
ProgHist Ltd Board of Directors Meeting 7 April 2021 

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2036]
## ProgHist Ltd Board of Directors Meeting 7 April 2021 

Time is [13:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210407T1300). @drjwbaker will be facilitating the call.

Chair: @acrymble
Secretary: @drjwbaker 
Members: @drjwbaker @svmelton @spapastamkou @amsichani @rivaquiroga 
Minutes of the last meeting: [2021-02_ProgHistLtd-BoD.docx](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/02-2021/2021-02_ProgHistLtd-BoD.docx).
Papers: on the [private repo](https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Board-of-Directors-Meetings/2021/04-2021).

### Agenda

1. Apologies  
2. Approval of Minutes from last meeting & actions status.
3. ProgHist Directors administration (e.g changes of address)
4. Finance update @drjwbaker
5. Business administration @drjwbaker 
6. Goal: Register as a charity @drjwbaker 
	- paperwork to West & Berry (deadline 17 April)
	- link to paperwork in [meeting papers](https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Board-of-Directors-Meetings/2021/04-2021)
7. Chair term length & trustee term lengths
8. Goal: Bug Reporting @rivaquiroga 
9. Goal: 40 IPP members @acrymble
10. Goal: Job posting @acrymble
11. Deputy Chair / Deputy Finance Officer
12. Any Other Business
13. Agree date of next meeting

**PLEASE SUGGEST AGENDA ITEMS IN THE TICKET FOR INCLUSION**
Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by rivaquiroga** [comment]
@drjwbaker, did you send the poll to define the date of this meeting? I'm not sure if it haven't been sent or if I managed to miss the email.

**Comment by drjwbaker** [comment]
- [x] date set
- [x] zoom circulated

**Comment by acrymble** [comment]
Correction for the previous minutes (to save time):

Agenda item 9. I'd like this to say that the board voted and approved in principle that we will be hiring when we have the money to do so. There was a vote and we need to minute that.

**Comment by drjwbaker** [comment]
Actions arising from the meeting today:

- [x] @drjwbaker to circulate minutes to members.
- [x] @drjwbaker to email Directors re charity registration documents.
- [ ] @rivaquiroga to update wiki and editorial guidelines on bug fixing in line with new process.
	- @rivaquiroga: I'm happy to work on this with you if you want help [says @drjwbaker!]
- [x] @acrymble to ask PT team about clear structure of institutional support and how best to recognise this.
- [x] @acrymble to give @spapastamkou access to the IPP sales doc.
- [x] @acrymble @rivaquiroga to discuss interview questions for DH Publishing Assistant job and to circulate to members for comment.
- [x] @drjwbaker to send Doodle to Directors in early-May re July meeting.

**Comment by acrymble** [comment]
@rivaquiroga @drjwbaker did that last action get done? I know sometimes these lists are forgotten.

**Comment by drjwbaker** [comment]
not sure on the maintenance workflow

**Comment by rivaquiroga** [comment]
@acrymble, I have a raw draft for both. 
It looks like a better idea to wait until we hire the Publishing Assistant to move forward with this. Lesson maintenance will be part of their tasks, so working together in updating the guidelines and wiki might help them to get involved/familiar with the process.
