### ISSUE TITLE
Translation of "Programming Historian English Language Lesson Template"

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/jekyll#2037]
@DanielAlvesLABDH and @jenniferisasi I will start translating the page "Programming Historian English Language Lesson Template" into Portuguese. Once I am finished with that task I will let you know.

**Comment by joanacvp** [comment]
The translation is finished and @aracele already reviewed it.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela tradução @joanacvp e pela revisão @aracele e @rivaquiroga. Joana, pode fechar isto!
@jenniferisasi the translation is finished!
