### ISSUE TITLE
IPP page duplication problem (incorrect info)

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2041]
I've noticed that both https://programminghistorian.org/en/support-us#institutional-partner-programme and https://programminghistorian.org/en/supporters list IPPs and supporters, with the former page out of date. I presume the details of this on the former can be removed? Or is - @jenniferisasi @acrymble - there something related to the roll out of IPP pages across languages that means the former still needs to be there?

**Comment by acrymble** [comment]
Yes these need to be forwarded to the new page to prevent 404s. I forgot. Thanks for catching.

**Comment by drjwbaker** [comment]
Is there an action for me here?

**Comment by acrymble** [comment]
You can action it to that other ticket and I'll do it in the next update.

**Comment by drjwbaker** [comment]
Which ticket?

**Comment by acrymble** [comment]
#1943 I have to add some changes soon.
