### ISSUE TITLE
FR Author Guidelines revision 

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2042]
As per (now closed) #1636; the fact that we started receiving and preparing original lessons without yet having an editorial chart; and the previously expressed will to integrate at least parts of our [French Translation Documentation](https://github.com/programminghistorian/jekyll/wiki/French-Translation-Documentation), I open a ticket to help us (FR team) organize the revision of the [French page of the Author Guidelines](https://programminghistorian.org/fr/consignes-auteurs). Based on this ticket, we will open a branch so that members who can work on the page revision are able to work collectively. I expect this to last some weeks from now, as parts of the page can be taken up from different FR members, the new ones included (as part of their 3M plan). I set May 31 as a desired deadline to have finished with this. I will create the branch in the coming days and expect future comments to be mostly in French to provide detailed context and instructions, and facilitate exchanges between us.

**Comment by spapastamkou** [comment]
I will progressively assign this ticket to all FR members who wil participate in this (or please assign it yourselves as you come in).

**Comment by spapastamkou** [comment]
Nous allons travailler à partir de la branche [```consignes-auteurs-revision```](https://github.com/programminghistorian/jekyll/tree/consignes-auteurs-revision)

**Comment by spapastamkou** [comment]
Il y a quelques mois, la page [Author Guidelines](https://programminghistorian.org/en/author-guidelines) en EN a été révisée pour intégrer une charte éditoriale plus élaborée que par le passé. L'idée est de travailler maintenant sur la pages des [Consignes aux auteur(e)s](https://programminghistorian.org/fr/consignes-auteurs) en FR pour (1) l'harmoniser dans la mesure du possible avec celle en EN dans sa structure; et (2) l'adapter aux réalités francophones, notamment pour la partie 2 qui comprend une charte éditoriale.  
Les parties 1 (proposer une nouvelle leçon) et 3 (soumettre une nouvelle leçon) doivent être surtout vérifiées et peut-être légèrement modifiées. La partie 2 (écrire et formatter une nouvelle leçon) doit être adaptée, ce qui peut impliquer quelques recherches et modifications (par ex. on écrit différemment les chiffes en français, on capitalise de manière différente: il va falloir modifier cela en conformité avec les usages normalisés en français). 

Nous pouvons nous repartir les parties suivantes (un membre sur chaque): 

- [x] [Etape 1](https://programminghistorian.org/fr/consignes-auteurs#proposer-une-nouvelle-le%C3%A7on) - [Step 1](https://programminghistorian.org/en/author-guidelines#step-1-proposing-a-new-lesson)  
- [ ] Etape 2/A: traduire/adapter selon [Step 2/A
](https://programminghistorian.org/en/author-guidelines#a-style-and-audience) _- attention! dans langue, les variations du français sont sans doute à discuter en équipe, de même que la sous partie Write for A Global Audience._  
- [ ] Etape 2/B: adapter selon l'organisation [Step 2/B](https://programminghistorian.org/en/author-guidelines#b-specific-writing-guidelines) mais le contenu sera différent - _c'est sans doute la partie avec le plus de travail, possible de la repartir entre 2 personnes_   
    - [x]  "Dates and Time", "Headings", "Lists" "Capitalisation": @InesSalome 
    - [ ] "Numbers", "Punctuation", "References", "Challenging Words Explained": @spapastamkou 
- [ ] Etape 2/C: vérifier et adapter si besoin selon [Step 2/C](https://programminghistorian.org/en/author-guidelines#c-formatting-guidelines)  
- [ ] [Etape 3](https://programminghistorian.org/fr/consignes-auteurs#soumettre-une-nouvelle-le%C3%A7on) - [Step 3](https://programminghistorian.org/en/author-guidelines#step-3-submitting-a-new-lesson)

**Comment by InesSalome** [comment]
Je trouve la partie sur l'adaptation de la charte éditoriale au contexte français particulièrement intéressante. Je suis partante pour travailler avec quelqu'un d'autre sur l'Etape 2/B si ça va à tout le monde !

**Comment by spapastamkou** [comment]
@InesSalome Tu peux choisir la ou les sous-parties qui t'intéressent le plus et je prends le reste moi-même (je n'ai pas de préférence particulière).

**Comment by InesSalome** [comment]
@spapastamkou Il y a 8 sous-parties en tout, on en prend 4 chacune ? De mon côté je peux me charger de "Dates and Time", "Headings", "Lists" et "Capitalisation" si cela te convient.

**Comment by spapastamkou** [comment]
@mariechristineb Je crois que ce ticket répond à la question 2 posée dans le [ticket d'évaluation](https://github.com/programminghistorian/ph-submissions/issues/364). Si tu as la possibilité, tu serais la personne idéale pour faire un premier jet pour la partie 2/A qui porte sur les variétés linguistiques. On pourrait peut-être aussi dialoguer avec l'équipe PT qui font face à de telles problématiques.
De mon côté, je compte me mettre à travailler sur ce ticket après le 21 avril, mais nous prévoyons large de toute manière (idéalement pour juin, si je ne me trompe pas).

**Comment by mariechristineb** [comment]
@spapastamkou Effectivement, c'est de ça dont je parlais. Je pense qu'il sera important d'avoir une politique claire à ce sujet. Il y a aussi la question de l'écriture inclusive qui mériterait notre attenion - ça ne s'applique pas trop à l'anglais, mais la version espagnole a une section dont on pourrait sûrement s'inspirer.

**Comment by spapastamkou** [comment]
C'est notre équipe qui a initié l'écriture inclusive, en fait:-) Les principes sont dans le wiki: https://github.com/programminghistorian/jekyll/wiki/French-Translation-Documentation#%C3%89criture-inclusive et bien sûr le but est aussi de les intégrer aux consignes, maintenant que nous les reprenons.

**Comment by InesSalome** [comment]
J'ai commencé à compléter mes parties sur le fichier [consignes-auteurs.md](https://github.com/programminghistorian/jekyll/pull/2114/commits/b2ce23b5c4eebd6be4e486355ed25b74e8a61921) ("Dates et heures", "En-têtes" et "Listes"). J'ai parfois laissé plusieurs possibilités (notamment pour la question de l'écriture des décennies ou des heures), mais dites-moi si vous préférez restreindre. Je ne suis pas sûre d'avoir bien traduit la mention "inline code font" dans la première phrase pour les [en-têtes](https://programminghistorian.org/en/author-guidelines#headings), donc n'hésitez pas à me corriger !

**Comment by mariechristineb** [comment]
@spapastamkou ah voilà! J'avais bien vu cette page sur le wiki dans le passé, mais je ne l'avais plus du tout en tête quand j'ai jeté un coup d'oeil aux consignes aux auteurs :)

**Comment by spapastamkou** [comment]
Merci à toutes les deux. 
@InesSalome On va partir sur la base qu'on fait chacun(e) confiance à l'autre pour les parties respectivement en charge, et on peut bien sûr discuter de tout ce qui nous pose problème (voire demander l'avis de toute l'équipe). Je pose ici les liens de la documentation officielle que j'utilise souvent et qui, en la mobilisant, peut répondre à la plupart des questions qui se posent: 
- [Lexique des règles typographiques de l'Imprimerie nationale](https://www.circaete.net/eric/Lexique%20des%20r%C3%A8gles%20typographiques%20en%20usage%20%C3%A0%20l%27Imprimerie%20nationale.pdf) (France) 
- [La banque de dépannage linguistique](http://bdl.oqlf.gouv.qc.ca/bdl/) de l'Office québécois de la langue française (il y a aussi des index disponibles au menu à gauche)
- TERMIUM Plus® (banque linguistique du gvt du Canada), [ici ](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/clefsfp/index-eng.html?lang=eng&lettr=indx_catlog_h&page=9Ix3w11_n52g.html#:~:text=Dans%20les%20textes%20g%C3%A9n%C3%A9raux%20ou,symboles%20h%20%2C%20min%20et%20s.)pour les heures

**Comment by spapastamkou** [comment]
@InesSalome Pour "inline code font", je crois qu'il s'agit d'éviter des balises de mise en forme imbriquées dans h, du coup ta traduction m'a l'air pertinente, si elle te va.

**Comment by InesSalome** [comment]
@spapastamkou Merci pour les références, je prendrai le temps de regarder par rapport à ce que j'ai trouvé. Ok pour "inline code font", on peut laisser la traduction telle quelle alors :)

**Comment by InesSalome** [comment]
Je pense avoir fait le tour pour mes parties ("Dates and Time", "Headings", "Lists" "Capitalisation"). N'hésitez pas si vous pensez qu'il y a des choses à modifier/améliorer :)
@spapastamkou, veux-tu que je rédige une courte en-tête introductive entre le titre **Règles typographiques** et la section **Dates et heures** ?

**Comment by spapastamkou** [comment]
@InesSalome Merci beaucoup pour ton travail! Si tu souhaites introduire des parties qui facilitent la lecture, aucun souci:) 
De mon côté, je ferai en sorte que l'on dispose d'une première version pour l'ensemble d'ici à la fin du mois.

**Comment by acrymble** [comment]
@anisa-hawes this ticket is related to the setup of French copyediting, which still needs to finalise the copyediting guidelines. This is a ProgHist goal for this year, and it needs some project management support. Can you please liaise with the people involved about completing this task?

**Comment by datalogism** [comment]
TO DO (resumption of remarks of #2312) : 
* Being more precise concerning how to underline the name of file / variables / and functions (taking a look on english guidelines)
* taking a concrete position on the translation issue of the codes content

**Comment by spapastamkou** [comment]
@datalogism En fait, j'ai ouvert à nouveau ce ticket car les consignes aux auteurs n'ont pas été mergés et cela sert de rappel:) 
Pour les questions que tu évoques, nous pouvons les discuter au sein de l'équipe et, s'il en ressort des propositions concrètes, soit les appliquer aux traductions fr, soit, si elles concernent plus largement les autres équipes langagières, discuter ces propositions avec elles dans un nouveau ticket. Cela te convient-il?

**Comment by datalogism** [comment]
Sans soucis @spapastamkou  !

**Comment by spapastamkou** [comment]
Les consignes révisées devraient être mises en ligne vie l'issue #2411 et le PR #2412.
