### ISSUE TITLE
Homepage - Portuguese, French and Spanish translations of "Enter the Programming Historian" 

### ISSUE THREAD

**Issue by matgille** [programminghistorian/jekyll#2048]
I've been looking for a similar issue in the repository, without success. I hope I'm posting this message in the right place. 

The French and Spanish translations of "Enter the Programming historian" do not sound very natural to me. 

In French I would expect the preposition "dans" (`Entrez dans *The Programming Historian en français*`), as it is used in the online thesaurus "Trésor Informatisé de la Langue Française" (TILF: http://atilf.atilf.fr/).  In Spanish, I would expect the preposition "en" (`Entrar en *The Programming...*`). The preposition "a" is also used in America, although I think it is less common (https://www.rae.es/dpd/entrar). 

Another possibility would be to use the verb "Accéder" (`Accédez à *The PH en français*`) in French or in Spanish the noun "Acceso" (`Acceso al *Programming historian* en español`) as we can find it in the "Corpus Diacrónico del Español" (CORDE) homepage (https://www.rae.es/banco-de-datos/corde).

What would you think of:
- Spanish: `Acceso a *The Programming Historian en español*` | `Entrar en *The Programming Historian en español*` ?
- French: `Accéder à *The Programming Historian en français*` | `Entrez dans *The Programming Historian en français*` ?

I don't know if this is relevant in Portuguese !

**Comment by spapastamkou** [comment]
Both suggestions for the FR are fine with me. Let's cc the @programminghistorian/technical-team in case this involves them (or them guiding us) and @programminghistorian/spanish-team and @programminghistorian/portuguese-team and the rest of the @programminghistorian/french-team to see what they think.

**Comment by DanielAlvesLABDH** [comment]
If those changes are approved to fr and es, in the pt case would be "Entrar no The Programming..."

**Comment by mariechristineb** [comment]
@matgille good catch, I never noticed that before! I would vote for 'accéder à'

**Comment by rivaquiroga** [comment]
"acceder/entrar a" sounds good to me in Spanish. At least in my Spanish variety, "entrar en" + proper noun is not common.
I'm not sure about "acceso", because is a noun and in all the other languages we will be using a verb.

**Comment by matgille** [comment]
So maybe: 
- "Entrar no *The Programming Historian em português*"
- "Accéder à *The Programming Historian en français*"
- @rivaquiroga  "Acceder a *The Programming Historian en español*" as there are different uses for "entrar" depending on the variety ?

The file that contains the texts of the homepage is  `_data/snippets.yml` . Am I correct ?

**Comment by DanielAlvesLABDH** [comment]
@matgille in the case of the PT version it could also be "Aceder ao The Programming Historian em português". Please use this instead. Thanks!

**Comment by matgille** [comment]
Yes, of course, sorry !

**Comment by matgille** [comment]
Ok !

**Comment by spapastamkou** [comment]
@matgille you got the good file, yes

**Comment by josircg** [comment]
> @matgille in the case of the PT version it could also be "Aceder ao The Programming Historian em português". Please use this instead. Thanks!

Hi Daniel, "Aceder" is not a frequent word in Brazil. It's much better "Entrar no" ou "Entrar em"

**Comment by DanielAlvesLABDH** [comment]
Obrigado @josircg. In this case the Portuguese version will stay "Entrar no The Programming Historian em português"

**Comment by matgille** [comment]
Thanks @josircg and @DanielAlvesLABDH. So, to sum up, we would have : 
- "Entrar no *The Programming Historian em português*" @DanielAlvesLABDH 
- "Accéder à *The Programming Historian en français*" @spapastamkou
- "Acceder a *The Programming Historian en español*" @rivaquiroga 

I will create a new branch and submit a PR when I have your agreement. 

Matthias

**Comment by DanielAlvesLABDH** [comment]
Thanks @matgille that's correct for Portuguese

**Comment by spapastamkou** [comment]
This is fine, sure.

**Comment by rivaquiroga** [comment]
Thanks, @matgille! 
I'm just wondering if we should drop the article on the name, following the [Brand Guidelines](https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines#project-title). At least in Spanish, "Acceder a Programming Historian en español" sounds good.

**Comment by mariechristineb** [comment]
@rivaquiroga thanks for pointing to the brand guidelines, this is something I had been wondering about, as we otherwise do drop the article in other pages of the website.

**Comment by matgille** [comment]
@rivaquiroga @mariechristineb Thanks for your answers !  If we drop the article in Spanish, should we do the same in the other languages ?

**Comment by DanielAlvesLABDH** [comment]
Hi all! I think we should keep the article in this case. "The Programming Historian" is the brand, although we could use the shorter version in other occasions, in the main page it would be better to keep the "The"

**Comment by acrymble** [comment]
@DanielAlvesLABDH the brand guidelines @rivaquiroga pointed to say the opposite:

> The title of the project is "Programming Historian". It was formerly known as "The Programming Historian 2". You can use the article "the" when the sentence makes better sense when it is included, but it should not be included as part of the project name.
> 
> The title of the Spanish project is "Programming Historian en espanol".
> 
> The title of the French project is "Programming Historian en français".

If this doesn't make sense, then we should update the brand guidelines, but we should be consistent.

**Comment by DanielAlvesLABDH** [comment]
OK @acrymble I have missed that. "The Programming Historian" is a personal preference. Then, if the article drops in ES, FR and EN there's no point in keeping it in PT

**Comment by mariechristineb** [comment]
@matgille yes, considering that the brand guidelines do point in that direction, I would go for "Accéder au _Programming Historian en français_" (it also flows better without the article)

**Comment by matgille** [comment]
So we would change the english version too ? 

- "Entrar no *Programming Historian em português*" @DanielAlvesLABDH 
- "Accéder au *Programming Historian en français*" @spapastamkou @mariechristineb (actually the article is still here, but it has been translated !)
- "Acceder a *Programming Historian en español*" @rivaquiroga 
- "Enter *Programming Historian*" @acrymble 



Matthias

**Comment by spapastamkou** [comment]
Are we going forward with this?

**Comment by matgille** [comment]
@spapastamkou should I start with the PR ?

**Comment by spapastamkou** [comment]
@matgille Sure! I think all is ok, but in any case EN, ES and PT teams can review the PR and ask changes if needed. Thanks!

**Comment by matgille** [comment]
Ok, thanks !
I've just created PR  #2144. I hope the changes I made won't have unattended side effects.
