### ISSUE TITLE
Programming Historian Annual General Meeting 25 May 2021

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2049]
May 25 2021, Time is [3:00 PM London](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210525T1400). @mariajoafana will be facilitating the call. Joint meeting with our Project Team Meeting: #2103 

Zoom invitation:
https://universityofsussex.zoom.us/j/93462421184

This AGM is an annual celebration of the Programming Historian. It also contains the ProgHist Ltd AGM, as required by the articles of association of our Not-For-Profit Company. *Members are invited to use this ticket submit agenda points for either part of the AGM*

**The AGM should last no longer than 2 hours**

### People

Chair: @mariajoafana 
Secretary: @drjwbaker 
Minutes of last meeting: [on the private repo](https://github.com/programminghistorian/project-and-business-archive/tree/master/business/AGMs/2021) (guests: please contact me to get a copy).

For ProgHist Ltd business, voting attendees: all ProgHist Ltd Directors (@acrymble @drjwbaker @amsichani @svmelton @spapastamkou @rivaquiroga) and all who are ‘Member (Editorial Board)’ of ProgHist Ltd (see https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Register-of-Members/2021)

Advisory attendees: one individual invited from each member of the [Institutional Partner Programme](https://programminghistorian.org/en/ipp) (@drjwbaker to invite)

- UCL DH (Julianne Nyhan)
- C2DH, University of Luxembourg (Sean Takats)
- Edinburgh Centre for Data, Culture and Society (Lisa Otty, Lucia Michielin)
- KU Leuven Libraries (Laura Mesotten?)
- READ-COOP (Melissa Terras)
- University of Sussex (Annette Moore)
- University of Waterloo (Jane Forgay)
- CESTA, Stanford (Daniel Bush, Alix Keener)

### Agenda

**Programming Historian AGM**

1. Welcome @mariajoafana 
2. Apologies @drjwbaker 
3. Approve Minutes 2020 AGM (@acrymble)
4. Programming Historian Annual report @acrymble @drjwbaker to present (Paper A ProgrammingHistorian2020-21report.pdf)

**ProgHist Ltd AGM**

5. ProgHist Treasurer's report @drjwbaker
6. ProgHist Business Plan 2021 @acrymble - including new goal proposal by @spapastamkou on legal matters (Paper B ProgHist Business Plan 2021 AGM.pdf)
7. ProgHist Service Agreement Terms 2021 @acrymble (https://github.com/programminghistorian/jekyll/wiki/Service-Agreement-Publisher-and-Publications)
8. Open Discussion with members and IPPs about the coming year @mariajoafana
9. AOB

**Comment by drjwbaker** [comment]
@mariajoafana I'll set up a Zoom for this now and circulate via email. I think the time zone details are correct, but I'd appreciate you double-checking. On the agenda of the non-Ltd bits, this was @acrymble's idea, so maybe you could liaise?

**Comment by drjwbaker** [comment]
@acrymble This is probably also a good opportunity to check if the register of members https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Register-of-Members/2021 is up to date.

**Comment by DanielAlvesLABDH** [comment]
Just a small correction, Lisbon is in the same time zone as London, not Paris 🙃

**Comment by drjwbaker** [comment]
Yeah, @DanielAlvesLABDH I thought that. Took time zones from https://github.com/programminghistorian/jekyll/issues/2019 which must also be wrong, right?

**Comment by mariajoafana** [comment]
> @mariajoafana I'll set up a Zoom for this now and circulate via email. I think the time zone details are correct, but I'd appreciate you double-checking. On the agenda of the non-Ltd bits, this was @acrymble's idea, so maybe you could liaise?

Yes, the time zone details are correct.

**Comment by acrymble** [comment]
Confirming that the service agreement has been re-agreed for this year. Point 7 on the above agenda.

**Comment by drjwbaker** [comment]
[2021_ProgHistLtd-AGM-minutes.docx](https://github.com/user-attachments/files/29328258/2021_ProgHistLtd-AGM-minutes.docx)
