### ISSUE TITLE
Network Analysis - broken link

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#205]
Link to author's own thesis description (on his own website no less!) has broken:

http://programminghistorian.org/lessons/creating-network-diagrams-from-historical-sources

Link goes to:
http://martenduering.com/covert-support-networks-phd

@mduering is this somewhere else now? Can we get a fix?

**Comment by mduering** [comment]
Hi Adam,

thanks for letting me know. Fixed it,

Best,

Marten
