### ISSUE TITLE
1st Newsletter of 2021

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2054]
Opening this ticket to start to keep track of everything we are doing this first 3-months of 2021: 

- [x] New editors in _PH en français_ (in French)
> - Antoine Henry, 
> - Gwenaëlle Patat
> - Matthias Gille Levenson
- [x] New editors in _PH em português_ (in Portuguese): 
> - Ricardo Pimenta
- [x] Open call for editors in _PH en español_ (in Spanish) https://programminghistorian.org/posts/convocatoria-editores-2021
- [x] Night mode now available (in English)

**Public outreach:** 
- [x] PH en español: Open Data Day. March 6 (in Spanish)
- [x] "Riva Quiroga: Multilingual Digital Humanities" _Digital Humanities Long View Seminar_ (UCLDH / CESTA) March 10 (in English) 
> - Link to recording ?
> - Link to recording + Stanford Newspaper clip
- [x] "Challenges for Digital Literacy in the Humanities: The Open, Community-Based and Multilinguistic Approach of The Programming Historian" (Sofia Papastamkou, Jessica Parr and Riva Quiroga) at NewsEye’s international conference (in English) https://www.newseye.eu/wpip21/save-the-date/, March 17 
> - Link to recording ?
- [x] "Programming Historian: Un proyecto colaborativo para poner la programación al alcance de los humanistas" Jenn and Riva for Intele (Spain), March 25 (in Spanish)

Upcoming: 
- [ ] Blogpost by Zoe on Github actions 
- [x] PH at Global DH at MSU April 12 (in English)
- [x] "Teach Digital History Well" with Adam Thurs. 29 April https://t.co/XBN5m0c2qO?amp=1  (in English)

**Supporters**
- [x] New IPP supporters
> - [Software Sustainability Institute](https://www.software.ac.uk/), United Kingdom
> - [Université du Luxembourg](https://www.c2dh.uni.lu/), Luxembourg
> - [Princeton University](https://www.princeton.edu/), United States
>  - [Roy Rosenzweig Center for History and New Media, George Mason University](https://rrchnm.org/), United States
>  - [Transkribus - READ COOP](https://readcoop.eu/), Austria
>  - [RStudio](https://rstudio.com/), PBC, United States

**Awards:**
- [x] Matt's blogpost on multilingual Jekyll is in DH Awards 2020/ Best Blog Post category: http://dhawards.org/dhawards2020/voting/

**Comment by spapastamkou** [comment]
For info, Matt's blogpost on multilingual Jekyll is in DH Awards 2020/ Best Blog Post category: http://dhawards.org/dhawards2020/voting/

**Comment by rivaquiroga** [comment]
➕ _PH en español_: [Open Data Day](http://programminghistorian-datosabiertos2021.eventbrite.com/). March 6

**Comment by acrymble** [comment]
I'm currently working with some of our IPP members to build knowledge about how they are using PH in teaching settings, so that we can share that with the wider IPP community. They are Edinburgh, UCL, and Los Andes.

**Comment by jenniferisasi** [comment]
> I'm currently working with some of our IPP members to build knowledge about how they are using PH in teaching settings, so that we can share that with the wider IPP community. They are Edinburgh, UCL, and Los Andes.

Thanks @acrymble! How about I word it as a "collaboration"?
