### ISSUE TITLE
Proposal of ajustments for the lesson "Building a static website with Jekyll and GitHub Pages"

### ISSUE THREAD

**Issue by InesSalome** [programminghistorian/jekyll#2059]
As a recent member, I installed Jekyll with the application Github Desktop thanks to the lesson "Building a static website with Jekyll and GitHub Pages", which is very clear. Nevertheless, using a Mac, I encountered a few problems to install correctly Jekyll when following strictly the lesson, and I am maybe not the only one. I would like to add to the lesson the solutions I found to make it functional.

The part concerned is "Setting up Jekyll" :

- The folder created by installing the application "Github Desktop" is well located in Libray/Application\ Support and is named "Github Desktop" (it can seem evident to precise it but I myself loose a bit of time to search the folder "Github" and not "Github Desktop"). 
- When we don't have write permissions in the folder "Library", the command line to force it is "sudo gem install jekyll bundler" (just precise that adding "sudo" in the command line can help if it doesn't function correctly).

I propose to add these small modifications if it suits you !

**Comment by walshbr** [comment]
Thanks @InesSalome! I know this one is in the bug assessor pipeline, but I appreciate the suggestion for solutions. Point one seems fine to me. @ZoeLeBlanc - do you have thoughts on point two? My sense is that we want to avoid installing things with sudo bc the installation would raise security issues for the person's machine, right? Personally, more and more I think we should not explicitly tell people instructions for installing things like this and, instead, link to the docs for the tech directly in the lesson - https://jekyllrb.com/docs/installation/macos/. Jekyll has a pretty good guide for installing things. It might be a little more difficult for people, but it's the only real way we can make these sustainable and not have to update the lessons every time a significant new version is released.

**Comment by InesSalome** [comment]
Ok, thanks for your opinion @walshbr. I understand the choice to avoid the use of sudo. The link to the docs seems to me a good solution.

**Comment by InesSalome** [comment]
Would you like me to limit my contribution to point one in the pull request, and then close the issue ?

**Comment by acrymble** [comment]
@InesSalome is this a bug in the original lesson? We have a workflow for handling that and managing editors must be involved in the conversation: https://github.com/programminghistorian/jekyll/wiki/Bug-Assessment

**Comment by InesSalome** [comment]
Thank you for the precisions @acrymble. @walshbr informed me of the existence of an issue about the bug (Mac Catalina bug for "Building a static website with Jekyll and GitHub Pages" #1955), that's why I think this issue is actually not relevant. What do you think @spapastamkou ?

**Comment by spapastamkou** [comment]
@InesSalome as long as you 've seen with @walshbr for point 1, all that's left is to have @svmelton 's review in the pull request, right? 
We @programminghistorian/french-team just need to somehow keep track of this change and also the ones integrated in the ES translation because we have this lesson in the pipeline of translated lessons to edit.

**Comment by InesSalome** [comment]
Ok @spapastamkou, I've just suppressed the addition of point 2 in my pull request (the use of sudo in the command line) and kept point 1.

**Comment by svmelton** [comment]
Thanks @InesSalome! I'll do my review now.

**Comment by InesSalome** [comment]
Thank you @svmelton :)
