### ISSUE TITLE
Repository for storing events/outreach activities materials

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2064]
As part of the grant scheme for our Open Data Day event, we are required to make all materials and outputs of the session available. To this end, I would like to create a new repository on our GitHub account. 
What do you think of having a repository called something like “outreach-activities” or “ph-events” where we can store this kind of materials?
(This looks like a communication issue, so I'll tag that team)

**Comment by acrymble** [comment]
We did this for the Bogota workshop using the blog and Zenodo, which meant we didn't have to maintain the resources long term. I would suggest that was an effective choice you may like to follow: https://programminghistorian.org/posts/model-workshop

**Comment by drjwbaker** [comment]
A github repo can also be versioned and deposited on Zenodo. Works really well. And captures the process of working on the materials https://guides.github.com/activities/citable-code/

**Comment by drjwbaker** [comment]
(that is, the dev can happen openly on GH then Zenodo can be used for the preservation)

**Comment by jenniferisasi** [comment]
I concur with @drjwbaker, work on GitHub then archive on Zenodo to make it citable :)

**Comment by rivaquiroga** [comment]
GitHub+Zenodo looks like the best option in this case. 
Thanks, everyone!
