### ISSUE TITLE
Tutorial by Jonathan Reeve not in Lessons directory

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#207]
This is linked in @miriamposner Omeka lesson, but doesn't appear elsewhere:

http://programminghistorian.org/lessons/installing-omeka.html

@wcaleb you are listed in the history. Is this supposed to be live?

**Comment by wcaleb** [comment]
Egads! I actually don't know; it looks like all I did was fix a syntax problem that was probably interfering with page build. But it certainly _seems_ like it should be live and listed!

**Comment by acrymble** [comment]
Who was the editor? There are no reviewers listed.

On Fri, Feb 26, 2016 at 7:29 PM, W. Caleb McDaniel <notifications@github.com

**Comment by JonathanReeve** [comment]
[Here is the original PR](https://github.com/programminghistorian/jekyll/pull/106). Fred had a suggestion for reorganizing it that I never got around to fixing. I'll revisit this today and add it to the PR.

**Comment by JonathanReeve** [comment]
^ I just opened #230 with some revisions. I also went ahead and updated it for the latest Omeka version. If it all looks good, it'd be great to see it make the list of lessons! Also, if it needs any further edits, let me know, too, and I'll be happy to fix it up.

**Comment by JonathanReeve** [comment]
I also just submitted #231 which adds the lesson to the lesson index, complete with an old-timey etching.

**Comment by acrymble** [comment]
Closing this as it's now back in the pipeline for @fredgibbs . Thanks for helping us sort it out @JonathanReeve
