### ISSUE TITLE
New Portuguese Support-Us pages

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2074]
Building on #1943 - Translate Support us

We need 3 new pages in Portuguese for our various fundraising pages to bring them in line with the other languages. These are

    /pt/ppi.md
    /pt/doacoes.md
    /pt/apoiadores.md

We also need to add a Middle Band price for middle income countries, set at £400 - see #1988.

We currently have no Portuguese IPP members, and I think it is far more important that the @programminghistorian/portuguese-team publish more lessons. So I will leave this here and will revisit it with @DanielAlvesLABDH once there are 6 PT lessons published.

**Comment by DanielAlvesLABDH** [comment]
@acrymble I noticed that the menu "Apoie-nos" in the PT version is no longer correct. There is only one sub-menu "Apoiadores" that directs to that specific section of our "Apoie-nos" page. Should we start to translate the pages? Should we make changes in the snippets.yml file to fix this?

**Comment by acrymble** [comment]
@DanielAlvesLABDH thank you for pointing this out. I've made a pull request that I think fixes this.

**Comment by acrymble** [comment]
@DanielAlvesLABDH you had a very busy day today! I see you now have 7 published lessons. Is there someone on the @programminghistorian/portuguese-team you would like me to work with on updating these support pages so that they are the same as the other language teams?

**Comment by DanielAlvesLABDH** [comment]
Hi @acrymble , once you mention this a couple of moths ago, @JimmyMedeiros82 offer to help in the translation of those pages. Jimmy, a oferta ainda está de pé? Abraço

**Comment by JimmyMedeiros82** [comment]
A oferta segue de pé, @DanielAlvesLABDH

**Comment by DanielAlvesLABDH** [comment]
Obrigado @JimmyMedeiros82. Hi @acrymble, Jimmy has agreed to collaborate in this. If you need any help from me please let me know.

**Comment by acrymble** [comment]
Thank you @JimmyMedeiros82 I will be in touch after our AGM on 25 May to discuss this. I hope it will be easy.

**Comment by JimmyMedeiros82** [comment]
All right @acrymble . I await your contact.

**Comment by acrymble** [comment]
@JimmyMedeiros82 thank you for your patience and for your help.

As it says above, we made changes to the Support Us pages in each language. These are now in 3 different pages. For Portuguese they will be:

/pt/ppi.md
/pt/doacoes.md
/pt/apoiadores.md

They have been designed so that a non-Portuguese speaker should be able to update them in future.

Some of the text is the same as is currently on https://programminghistorian.org/pt/apoie-nos and some of it is new.

The finished pages should look like :

https://programminghistorian.org/en/ipp
https://programminghistorian.org/en/individual
https://programminghistorian.org/en/supporters

Do you want to have a meeting to discuss? You may already know everything you need to hear, but I'm happy to speak to you at a convenient time. I'm happy either for you to make the pages in markdown, or to send me the text as translation and I can put it into markdown for you.

**Comment by acrymble** [comment]
@JimmyMedeiros82 I think we should also include currency options in Brazilian Real for the PT pages.

**Comment by JimmyMedeiros82** [comment]
Hi @acrymble , sorry for the delay. 
Do you have a value suggestion in Brazilian Real? Is it a simple conversion of current values ​​from GBP/USD/EUR to Real at today's rate?

I did the translation of /pt/doacoes.md
Can I create a pull request for this first step?

**Comment by acrymble** [comment]
@JimmyMedeiros82 thanks. Let's go with 7,000 Real for the full price.

If you have a pull request ready go ahead and we can check it.

**Comment by acrymble** [comment]
@JimmyMedeiros82 is this ready to check?
