### ISSUE TITLE
TweetSets changes and updates to Beginner's Guide to Twitter Data

### ISSUE THREAD

**Issue by lwrubel** [programminghistorian/jekyll#2087]
I'm part of the team that maintains [TweetSets](https://tweetsets.library.gwu.edu), which is featured heavily in the lesson "[Beginner's Guide to Twitter Data](https://programminghistorian.org/en/lessons/beginners-guide-to-twitter-data)". (Thank you for including it! We appreciate it's been useful to researchers.)

Last week, we deployed a new release of TweetSets which has several UI and export functionality changes. While the release improves overall accessibility and usability, some export options are not available for the time being. The mentions edges CSV file, in particular, was causing TweetSets to take weeks to complete some dataset exports and we wanted people to be able to get the most-often used data extracts more promptly. (It may be possible to bring this back in the future and in the meantime we now make the top 1000 users/mentions/urls automatically available as downloadable CSV files in the statistics tab.)

We'd like to submit a PR with updated screenshots and wording. However, the current lesson uses the edges extract file as a way to teach VLOOKUP. I haven't been able to identify a comparable alternative way to teach VLOOKUP with the files now available, especially one that leads toward creating a social network visualization. I am wondering if this is important to this lesson's learning objectives? 

I'd like to create a PR, but I think we would regretfully need to remove the discussion on VLOOKUP. However, I may just not be seeing a way that would work and would also welcome ideas on how to adjust it.

**Comment by spapastamkou** [comment]
Hi @lwrubel, thanks for your ticket. @svmelton is the EN team's Managing Editor and would be your main contact in the team. Sarah, we edited the lesson with @drjwbaker if this can help, please let us know in case you need contact details of the authors of the lesson.

**Comment by anisa-hawes** [comment]
Hello @svmelton. 

I've been having a look at this lesson, and reading its [Review Issue](https://github.com/programminghistorian/ph-submissions/issues/248). If I understand the comment above correctly, one of the options available at that time was to export  a data file representing 'edges' – which in this context was two columns of Twitter user IDs, representing pairs of users: one who posts a tweet, and another who is mentioned within that tweet. 

TweetSets doesn't any longer/at the moment offer the option to export this type of dataset. Moreover, the datasets available to export now, aren't suitable material for handling in the section of the lesson which teaches VLOOKUP and guides the creation a social network graph.

Do you think an adjustment can reasonably be made without compromising the lesson's original objectives?
It sounds like the revision being proposed by the OP and their colleagues at GWU could help us to bring the lesson up to date, and if you think it's suitable, this revision could be made in collaboration with the original authors.

Alternatively, we could consider adding an information alert box to that step, simply explaining that edges datasets aren't available to export from TweetSets anymore. This lesson was published relatively recently (end of 2019) and so I expect that you would be very reluctant to suggest retiring it altogether. 

Please let me know what you think, and how I could support the next steps.

**Comment by lwrubel** [comment]
I wanted to add that we're about to release an update to TweetSets that will bring back mentions nodes/edge files for full datasets. I can update you when datasets will begin to have that content again, and which datasets will have those files generated and available first. It will be accessible in a slightly different way and not (yet) for custom datasets where there have been filters applied to the data. So, this is just to say that I would continue to be willing to update the lesson (or work with someone to do that) and that those updates may be less drastic than I initially described.

**Comment by anisa-hawes** [comment]
Oh! Amazing news, @lwrubel! Thank you for your incredibly swift and generous response! I would certainly be keen to learn more. I know Justin Littman from when he was working on Social Feed Manager at GWU, and have also collaborated with Ed Summers (one of the reviewers of this lesson) on past projects, so this subject is very interesting to me.

**Comment by svmelton** [comment]
Perfect, thanks @lwrubel!

**Comment by anisa-hawes** [comment]
Hello @lwrubel and @svmelton. 

I've added the On Hold label to this Issue, to reflect that we will be returning to update this lesson in the future but a solution isn't available right away. 

In the meantime, I would like to suggest that we add an info/warning box to the live site, to let readers know that the export options available for Tweet Sets are limited in the current release, and that we'll be updating the lesson soon. What do you think?

Could you perhaps suggest some wording to best reflect the current availability of nodes/edge files @lwrubel?

**Comment by lwrubel** [comment]
Hi @anisa-hawes,

I've almost got a PR ready with suggested revisions to the lesson, sorry for the delay! I think an info box is a good idea. It could say something like:

"TweetSets export options have changed since this lesson's last update. Users should select one dataset at a time to export. Nodes and edges files for mentions are available for selected full datasets and more will be available over time."

**Comment by anisa-hawes** [comment]
Thank you, @lwrubel. This is much appreciated. I've prepared a PR to add the info-alert box. 

I'd also be happy to take care of the PR for revisions to the lesson. If you would like to suggest the changes here in the Issue, then I can implement them.

No need at all to apologise for any delay. Whenever you're ready, there is no rush.

**Comment by lwrubel** [comment]
I've submitted a PR with suggested revisions and new screenshots: https://github.com/programminghistorian/jekyll/pull/2397

Happy to make any further edits or answer questions.

**Comment by anisa-hawes** [comment]
Enormous thanks, @lwrubel! I have just been reading through the adjustments you've suggested. Your changes to the text are written very clearly – thank you. I'm running the build workflow now, so that I can check everything looks right in the Netlify Preview (new screenshots, adjusted captions, etc.). After that, I'll ask @svmelton to review, and confirm we're okay to merge the PR.

Thank you again, for your willingness to collaborate on this! Your support is much appreciated.
