### ISSUE TITLE
Deleting Lesson Request pages

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2089]
I propose deleting the various Lesson Request pages.

https://programminghistorian.org/en/lesson-requests
https://programminghistorian.org/es/solicitud-lecciones
https://programminghistorian.org/fr/appel-contributions
https://programminghistorian.org/pt/licoes-pedidos

This was started years ago when contributions were less forthcoming. It doesn't look like it works very well in terms of actually getting lessons on those topics, and it's not clear that someone has taken ownership of all of these pages to the same degree. Removing them also declutters the menus a little bit.

**Comment by jenniferisasi** [comment]
Stopping by to say if we move ahead with this, we would need to delete a few tweets from the bot. 

per meeting: if we do blog posts, then we can link switch the page-links on tweets to the blogpost-links

**Comment by acrymble** [comment]
Agreed at the meeting #2019.

I will take this forward.

**Comment by acrymble** [comment]
@jenniferisasi thanks. I've removed them from twitterbot.
