### ISSUE TITLE
Change menu bar from static top to fixed top

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2100]
We would like us to fix the menu bar to avoid endless scrolling up and down to navigate pages. 

Things to make sure of before changing it: 

- [ ] It doesn't interfere with accessibility (screen readers; maybe it helps?)
- [ ] It doesn't interfere with the PDF printing layout (that gets rid of the menu) 

Some instructions [https://getbootstrap.com/docs/3.4/components/#navbar-fixed-top](https://getbootstrap.com/docs/3.4/components/#navbar-fixed-top). 

I am opening the ticket but I will need the help and input of the @programminghistorian/technical-team

**Comment by walshbr** [comment]
It shouldn't affect screen readers, but it would pose general issues for someone using a screen magnifier - https://a11y.colorado.edu/node/303. It also shouldn't interfere with the PDF printing layout unless it overrides the print sheet css.

**Comment by jenniferisasi** [comment]
Thanks @walshbr! I/we'll take that into account. It looks like it is problematic when behaving in a certain way, so I'll try to figure if it is possible to fix it. And we might need to think about the 'donate' banner since having 2 poses issues (as per that link)

**Comment by walshbr** [comment]
Yep! Totally. Also happy to brainstorm with you on this.

**Comment by jenniferisasi** [comment]
At the August Tech Team meeting we decided to let this go for now, since we are planning on either changing our framework/service or improving the current one to go back to faster build times. I'm closing this ticket.
