### ISSUE TITLE
Broken link found in getting-started-with-markdown

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2102]
Our build system found a broken 404 link in "Getting Started with Markdown". 

[https://stackedit.io/editor](https://stackedit.io/editor) no longer exists, and it looks like it has been replaced with [https://stackedit.io/app#](https://stackedit.io/app#)

I was going to do the simple edit, but upon reading the instructions that go with the link, I found that they no longer match with the app in question: 

> click on the # in the upper left corner for a menu. Choose Import from URL, then paste the following URL to display the “Intro to Bash” lesson in the editor

I clicked on the # and only these options are now available for import: 

<img width="279" alt="Screen Shot 2021-03-30 at 6 16 25 PM" src="https://user-images.githubusercontent.com/11022533/113063903-0c1efc80-9184-11eb-8e07-0b7b729825b1.png">

Looks like we could remove that step easily and proceed, but the lesson is available in all languages, so the edit needs to be in sync.

**Comment by spapastamkou** [comment]
For the FR version, only the link has to change, I believe. I (as translator of the lesson) had updated the instructions to fit v.5 and they are in the separate block here: https://programminghistorian.org/fr/lecons/debuter-avec-markdown#la-syntaxe-markdown 
The link was kept bcz v.4 was still live although no longer maintained and with a message sending to the app (this helped keep the link with the original lesson too). Of course, we'll change now.

**Comment by DanielAlvesLABDH** [comment]
I will ask @joanacvp to contact the colleague that is translating this lesson to Portuguese so that he can incorporate that fix.

**Comment by joanacvp** [comment]
> I will ask @joanacvp to contact the colleague that is translating this lesson to Portuguese so that he can incorporate that fix.

I already contacted the author and asked him to incorporate that fix. Thank you for the attention

**Comment by jenniferisasi** [comment]
> For the FR version, only the link has to change, I believe. I (as translator of the lesson) had updated the instructions to fit v.5 and they are in the separate block here: https://programminghistorian.org/fr/lecons/debuter-avec-markdown#la-syntaxe-markdown
> The link was kept bcz v.4 was still live although no longer maintained and with a message sending to the app (this helped keep the link with the original lesson too). Of course, we'll change now.

Merci @spapastamkou. I'm wondering how to edit everything, cos there is no need maybe for the instructions in version 4, just go with the new way. I see that in Spanish the url is the new one but the instructions don't match. All of us should change to something like: download this document and upload it to the editor with "Import Markdown"?

**Comment by rivaquiroga** [comment]
Thanks, @jenniferisasi!
Maybe we can put the link to the raw version of the .md file and ask people to copy paste the content into Stack Edit. I'm not sure if everyone will know how to download a file from GitHub.

**Comment by spapastamkou** [comment]
@jenniferisasi Ok, I see what you mean, I just checked better. The instructions for v.4 are indeed in the text because the version was still functionning although obsolete and with a message in the interface saying there was v. 5 available. So we should delete these instructions, yes. And for the FR version we can move the instructions that are now in the block in the main text. 

@rivaquiroga The URL to the raw version is provided because v.4 imported directly from URLs. In the instructions I had provided for v. 5 I offer two options: one is to copy paste from the raw version to the v.5 interface; and the other is to copy paste into a file of a text editor, save the file as .md and then import to StackEditor.

**Comment by spapastamkou** [comment]
There is also a broken link in this post: https://programminghistorian.org/posts/promoting-digital-archives.html The [link](https://www.bodleian.ox.ac.uk/__data/assets/$1) has not been archived anywhere from what I see, I propose we only keep the generic link of the Bodleian.
