### ISSUE TITLE
link checker to ignore blog

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2106]
Can we please have our link checking service that activates on pull requests just ignore broken links in the blog? They aren't really core maintenance priorities and they really slow down simple updates. Asking @programminghistorian/technical-team if this is easy to do?

**Comment by walshbr** [comment]
I think that should be possible. Does that make sense for you @ZoeLeBlanc?

**Comment by acrymble** [comment]
I think this is becoming a larger issue that needs re-thinking. We've now got problems of retired lessons also being checked, and the burden of fixing these is unequally falling on some people.

It's contributing to a long backlog of pull requests not getting actioned, and it's really part of our lesson maintenance commitment, not our day-to-day updating the website with simple changes workflow.

Can we think about changing this to a monthly task or similar - specifically with regards to broken links, which are 90% of these problems. @programminghistorian/technical-team

**Comment by drjwbaker** [comment]
@acrymble See also https://github.com/programminghistorian/jekyll/issues/2030 There are related issues here.

**Comment by ZoeLeBlanc** [comment]
We can have the link checker ignore the blog though we should probably add some documentation somewhere that those links may or may not work. It's also turning out that there's some issues into how we formatted the link checker so trying to fix it now and hopefully that will solve some of this backlog.
