### ISSUE TITLE
Datafiles and Links for Google Maps lesson broken

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#211]
This was kept in Drop box (bad idea) and is no longer downloadable: https://www.dropbox.com/s/7xv11vd7dz2afud/UK%20Global%20Fat%20Supply%201894-1896%20-%20Sheet1.csv

I think we may need to deprecate this unless it can be fixed by the authors.

Affects: http://programminghistorian.org/lessons/googlemaps-googleearth

**Comment by acrymble** [comment]
Affects: http://programminghistorian.org/lessons/googlemaps-googleearth

(You can also download and explore Dan Macfarlane’s Seaway map for this part of the exercise).

Link refers to 'Seaway map'.

https://www.google.com/maps/d/kml?mid=zLGDOilNtMgo.kTGA5fuMJTds&ie=UTF8&hl=en&t=h&source=embed&authuser=0&msa=0&output=kml

#212 brought over here, as these are the same type of issue.

**Comment by acrymble** [comment]
Related: Link to 'Mobile Mapping an dHistorical GIS in the Field' is also broken.

**Comment by ianmilligan1** [comment]
Also pinging poor @jburnford here.

**Comment by jburnford** [comment]
[UK Global Fat Supply 1894-1896 - Sheet1.csv.zip](https://github.com/programminghistorian/jekyll/files/148984/UK.Global.Fat.Supply.1894-1896.-.Sheet1.csv.zip)

**Comment by jburnford** [comment]
[seaway.zip](https://github.com/programminghistorian/jekyll/files/148993/seaway.zip)

**Comment by jburnford** [comment]
It does still work, but we need to change the opening, as you just use Google Maps instead of Map Engine Lite. Do I have access to the Markdown version?

**Comment by ianmilligan1** [comment]
@jburnford Yep, you could do a pull request, Jim, or you could shoot me a short note with the suggested opening text and I'm happy to make the change on your behalf.

**Comment by jburnford** [comment]
Here is the correct link to mobile mapping 
http://niche-canada.org/2011/12/14/mobile-mapping-and-historical-gis-in-the-field/
