### ISSUE TITLE
Recognising former IPPs

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2119]
One of our IPPs (Institute of Historical Research) is no longer able to support us. I'm wondering how best to recognise their support whilst also ensuring our ongoing IPPs are most prominent.

So, looking at https://programminghistorian.org/en/supporters, I suggest moving Institute of Historical Research to the bottom of the list, and adding `[2020-2021]` like we do for grants on the same page.

@jenniferisasi @acrymble What do you think?

**Comment by jenniferisasi** [comment]
That sounds good to me @drjwbaker. And to avoid too many brackets and numbers, I suggest we still don't add the [year-Present] to the others (in case you thought about doing it). In the future, as the lists grows both on adds-on and drops, we can create a "past members" inside Institutional Partners section.

**Comment by drjwbaker** [comment]
I thought to just add the dates to the *previous* IPPs. I guess the question is if we want a 'past members' section now, or just to move past members to the bottom (hopefully we won't accumulate too many past members!)

**Comment by jenniferisasi** [comment]
Yes, that's exactly what I meant :)

Dates only on _previous_ IPPs and "past members" only if the list grows (hopefully not!)

**Comment by acrymble** [comment]
can we ask Martin Eve what they do for OLH?

**Comment by drjwbaker** [comment]
Looking at https://www.openlibhums.org/plugins/supporters/ OLH have either never had a supporter leave or just scrub them when they do. @MartinPaulEve (with apologies for the cheeky direct ping), right?

**Comment by MartinPaulEve** [comment]
Hi all,

We only list "active" supporters. Perhaps ungracious...(!)

Best wishes,

Martin

**Comment by drjwbaker** [comment]
Okay. We'll use this..

> Dates only on previous IPPs and "past members" only if the list grows (hopefully not!)

..approach in the future, and move to the "ungracious" :) approach if it becomes unwieldy.
