### ISSUE TITLE
Update research + Add article by Alves to Research 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2120]
I just read @DanielAlvesLABDH's "Ensinar Humanidades Digitais sem as Humanidades Digitais: um olhar a partir das licenciaturas em História" and it includes a section on Programming Historian, so I think it should go on our research page.

**Comment by DanielAlvesLABDH** [comment]
Thanks @jenniferisasi

**Comment by jenniferisasi** [comment]
In updating the 'research' page to include the article by Daniel Alves, I realized we haven't updated it in a while with our multiple presentations in 2021. Although the branch name has Alves in it, I will use it do to a PR with everything I can collect.

**Comment by acrymble** [comment]
@jenniferisasi did this happen already?

**Comment by jenniferisasi** [comment]
Yes! Sorry, I had forgotten that I opened this one.
