### ISSUE TITLE
ProgHist Ltd Board of Directors Meeting 22 July 2021

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2123]
## ProgHist Ltd Board of Directors Meeting 22 July 2021 

Time is [13:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210407T1300). @drjwbaker will be facilitating the call.

Chair: @acrymble
Secretary: @Anisa-ProgHist 
Members: @drjwbaker @svmelton @spapastamkou @amsichani @rivaquiroga @drjwbaker 
Minutes of the last meeting: [2021-04_ProgHistLtd-BoD.docx](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/04-2021/2021-04_ProgHistLtd-BoD.docx).
Papers: on the [private repo](https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Board-of-Directors-Meetings/2021).

### Agenda

1. Apologies  
2. Approval of Minutes from last meeting & actions status.
3. ProgHist Directors administration (e.g changes of address)
4. New Digital Humanities Publishing Assistant @acrymble
5. Finance update & Business administration @drjwbaker 
6. Goal: Register as a charity @drjwbaker 
7. Goal: £300 p.a. budget for publication outreach activities (@acrymble) *input required from MEs*
8. Goal: Lesson Maintenance Reporting @rivaquiroga 
9. Goal: 40 IPP members @acrymble
10. Actions arising from AGM
11. Approval of publication budgets for 2021/22 - input required from MEs
12. Proposal to become a member of the [Foundation for Science and Technology](https://www.foundation.org.uk/About/Subscription-to-FST) @drjwbaker 
	- in recognition of their support in us establishing as an Ltd (I can explain further in the meeting)
13. Any Other Business - People development Plan (See Business Plan)
14. Agree date of next meeting

**PLEASE SUGGEST AGENDA ITEMS IN THE TICKET FOR INCLUSION**
Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by acrymble** [comment]
@drjwbaker can we check if it's possible to re-schedule this to a Wednesday, Thursday, or Friday so that our new publishing assistant can join?

**Comment by drjwbaker** [comment]
Afraid not according to the poll, unless @rivaquiroga has become free on 22 July. 
![Screenshot from 2021-06-14 09-14-46](https://user-images.githubusercontent.com/4965300/121860694-03ed4c80-ccf1-11eb-8fb8-ca25c40eba42.png)

**Comment by rivaquiroga** [comment]
I'm not sure yet.
I'm presenting at the ACH Conference (21-23 July), but the schedule hasn't been published.

**Comment by drjwbaker** [comment]
Thanks for letting us know @rivaquiroga. @acrymble: what would be the purpose of moving so that that new publishing assistant can attend? Just to say hi, or something more?

**Comment by acrymble** [comment]
To act as secretary so you don't have to do it anymore.

**Comment by drjwbaker** [comment]
@acrymble and I just spoke and I think we agreed not to move this meeting, but to schedule future meetings for days the publishing assistant can make so that they can take minutes.

**Comment by rivaquiroga** [comment]
Hi! The schedule was published and I'm presenting on the afternoon of the 22. So I'm available at 13:00 UTC that Thursday if you still want to re-schedule the meeting.

**Comment by drjwbaker** [comment]
@rivaquiroga Belatedly, thanks. @acrymble: would you still prefer we move this?

**Comment by acrymble** [comment]
It would be my preference but I don't want to cause problems by it.

**Comment by drjwbaker** [comment]
Meeting moved per discussion via email.

**Comment by drjwbaker** [comment]
@svmelton @rivaquiroga @spapastamkou @DanielAlvesLABDH Further to our email correspondence and an update to the [Spending Requests](https://github.com/programminghistorian/jekyll/wiki/Spending-Requests) process, I've added an agenda item here: "11 - Approval of publication budgets for 2021/22 - *input required from MEs*"

I'd be grateful if in advance of 22 July, you could each give me an estimate on expected copyediting for 2021/22 (starting 1 October). The current estimates are:

- EN copyediting: 8 times @ £125 (max for longest articles) per annum.
- ES copyediting: 5 times @ £125 (max for longest articles) per annum.
- FR copyediting: 5 times @ £125 (max for longest articles) per annum.
- PT copyediting: 3 times @ £125 (max for longest articles) per annum.

Don't worry too much about the £ value, I'm more interested in how many copyedits you expect per year. At present we only copyedit original articles, but I know @acrymble recently raised the possibility of copyediting translation, which we may also wish to include.

I can then present these for approval at the meeting.

Note that in addition to this, we also estimate at present for bugfixing costs of 8 times @ £125 per annum. I expect we'll work on this estimate once the Publishing Assistant starts https://github.com/programminghistorian/jekyll/issues/2058#issuecomment-861555665

**Comment by DanielAlvesLABDH** [comment]
Dear James, I would say 3 times for the PT team, thinking essentially in new articles, since for now we are more focused on translations and for now we can still manage the copyediting of those.

**Comment by spapastamkou** [comment]
@drjwbaker I edited the estimates to add 5 times of expected copyediting for the FR edition next year (on the basis that we had 9 publications in 2020). Includes originals and (long) translations.

**Comment by svmelton** [comment]
Thanks @drjwbaker! We can keep it at 8 for EN, since we may start including translations as well.

**Comment by svmelton** [comment]
Apologies, all—I've had a meeting scheduled to onboard someone at work from when we first filled out the poll, and I won't be able to make the new date. Also @drjwbaker my calendar invite was still for today, but that may just be something weird with my calendar?

**Comment by drjwbaker** [comment]
Apologies @svmelton. Digging through my email, I realise that I resent the call details with the new date but failed to resend the calendar invite.
