### ISSUE TITLE
Deprecation method needed

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#214]
We need a way to flag up lessons that are currently broken (or perhaps permanently broken). I think it's important that we keep lessons available forever (whatever that means) because we don't want to break links and the good will that comes with it. But some way of letting readers know is important too.

Maybe a standard boilerplate warning at the top of the lesson, and tinting the icon red on the lessons' page?

**Comment by wcaleb** [comment]
We have such a method implemented already. Add `deprecated: true` to the YAML metadata on a lesson, and a red banner at the top reads "This is an old lesson that is no longer being actively maintained." Right now all of the lessons of this kind are in a separate folder called `deprecated` in the lessons directory, but that's not required for it to work.

**Comment by acrymble** [comment]
Thanks. I've added the flag to http://programminghistorian.org/lessons/googlemaps-googleearth

Until we can get a chance to fix it.

**Comment by acrymble** [comment]
Hasn't shown up yet with a banner, but maybe needs to wait for cache to clear. No need to panic yet :)
