### ISSUE TITLE
Just a typo in a es/lesson translate

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#2142]
Hi everybody!

In es/lesson translate [Introducción a los datos abiertos enlazados](http://programminghistorian.org/es/lecciones/introduccion-datos-abiertos-enlazados), there is a typo on line 166

It says: “Ongology”
Should say; “Ontology”

Best for all!
vg

**Comment by rivaquiroga** [comment]
Thanks, @vgayolrs!

**Comment by acrymble** [comment]
@Anisa-ProgHist I know this one is in Spanish but it's a really quick and easy fix, so I'm tagging you when you have time.
