### ISSUE TITLE
programminghistorian.org email

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2148]
We'll have to set up an email address for our new Digital Humanities Publishing Assistant soon.

I'd like to suggest we try to use the @programminghistorian.org URL for the email address moving forward. I'll look into what this means in practical terms, since RRCHNM pays for our URL, but I know this can be integrated into Gmail somehow.

**Comment by drjwbaker** [comment]
Thanks Adam.

**Comment by acrymble** [comment]
To do this via Gmail costs $6/month. https://workspace.google.com/intl/en/products/gmail/?utm_medium=et&utm_source=gmail-en-ui&utm_campaign=FY19-Q2-global-xsell-referralgoogle-ft-Gmail_settings_G_Suite&utm_content=var1

It also comes with other things they think businesses would like to use, like large Google Hangout capacity, storage, etc.

**Comment by drjwbaker** [comment]
I wonder if it is UK business (e.g. GDPR compliant)?

**Comment by acrymble** [comment]
I've emailed CHNM about the domain as well to let them know about the new needs to see what they think.

@drjwbaker good question.

**Comment by acrymble** [comment]
I've emailed again, this time to our contact at CHNM

**Comment by acrymble** [comment]
I've had contact with them and they're looking into the best options.

**Comment by acrymble** [comment]
They're going to help us set up using Google Mail.

GDPR details about Google are available here for those concerned: https://cloud.google.com/security/gdpr/

**Comment by acrymble** [comment]
@drjwbaker are you happy for me to get us going with a Google account? It costs $6/mo

**Comment by drjwbaker** [comment]
Yes. What is the payment method?

**Comment by acrymble** [comment]
@drjwbaker I will have to put it on my credit card.

**Comment by drjwbaker** [comment]
billed annually or monthly? Ideally we'd do the former (because that is less paperwork for me)

**Comment by acrymble** [comment]
Actually we can do paypal or direct debit. Preference?

**Comment by drjwbaker** [comment]
Paypal is slightly easier to process.

**Comment by acrymble** [comment]
Ok we have an account with Google. I just need to wait for our partners to verify that we can use the domain (I've sent an email). Then we should be able to set this up and close the ticket.

**Comment by amsichani** [comment]
I propose to use this email or at least cc it in every ltd-related process/comm/project email.

**Comment by drjwbaker** [comment]
I prefer not. We have the shared gmail for that. This is just for Anisa to do their job. And there are many Ltd related things that it isn't right for Anisa to see (e.g. our interactions with payroll, HMRC, etc)

**Comment by amsichani** [comment]
Do we need then to set up an ltd email as well?

**Comment by acrymble** [comment]
Its possible. It's £4 per email address per month. We can definitely discuss @amsichani

**Comment by josircg** [comment]
Hi folks, you can try Google for Nonprofits!

https://www.google.com/nonprofits/

You definitely are eligible.

Josir.

Em qui., 22 de jul. de 2021 às 09:51, Adam Crymble ***@***.***>
escreveu:

**Comment by drjwbaker** [comment]
> Do we need then to set up an ltd email as well?

So many systems are plugged into the shared gmail the idea makes me **really** nervous (unless we can do some clever forwarding to a new @programminghistorian.org email address).

**Comment by josircg** [comment]
It's easy to do as well. I do it all the time for my customers.
The most "dangerous" part is to change the DNS settings for the domain.
Josir.

Em qui., 22 de jul. de 2021 às 11:14, James Baker ***@***.***>
escreveu:

**Comment by drjwbaker** [comment]
@josircg When we chose to do this, would you be willing to help?

**Comment by josircg** [comment]
Sure! Count on me.
We can make a "Anydesk" or GRD connection and do it together.

Em sex., 23 de jul. de 2021 às 05:24, James Baker ***@***.***>
escreveu:

**Comment by acrymble** [comment]
I've spoken to the RRCHMN web administrator and he says he's unable to help us set up our Google email because they only pay for the domain and have no access to our hosting.

There are 3 ways I can verify our domain and get the email working:

1) Log in to our cloudflare.com account (possible if we have sign in access to the domain host) 
2) create a TXT record (only possible if we can edit the domain records)
3) create a CNAME record (only possible if we can edit the domain records)

I think option 1 is the easiest if someone has the login details. @programminghistorian/technical-team can you let me know please which approach is best and who I can contact about it?

Thank you.

**Comment by josircg** [comment]
Hi Adam, in fact there are more steps to take. But the first on is access the registar. Probably www.domain.com

https://whoisnote.com/whois/programminghistorian.org

And here are the generic steps:

https://support.google.com/a/answer/140034

**Comment by ZoeLeBlanc** [comment]
@acrymble I can log into our cloudflare account but I need to transfer over the DNS to our account for any of those options to be viable (at least I think that's true, maybe @josircg can weigh in?). Currently I thought the DNS records were through GMU but maybe they are still under Matt Lincoln's account 🤔 ?

**Comment by josircg** [comment]
Hi Zoe. In theory, you don't need to transfer accounts or other dangerous actions. The process is:

1) log in the registar.
2) add the MX records supplied by Google.

and never touch the www configuration. kkk...

See an live example:

![mxrecords](https://user-images.githubusercontent.com/634507/127201313-32403481-d296-4123-8846-b180677c1825.png)

**Comment by acrymble** [comment]
@ZoeLeBlanc if you email me the login details I can try to follow the steps for option 1. If it doesn't work, I promise not to mess with any other details. Otherwise, I can give you the Google Workspace login details and you can try instead?

**Comment by ZoeLeBlanc** [comment]
Happy to email you the login details @acrymble! Thanks for taking the lead on this 👍🏽

**Comment by acrymble** [comment]
@ZoeLeBlanc I'm not able to do this because our account isn't authorized to make changes. So this is currently stuck.
![Screen Shot 2021-07-28 at 14 42 25](https://user-images.githubusercontent.com/646647/127332720-0286a981-c3f6-418a-aeb4-f1bdd01c37eb.png)

**Comment by ZoeLeBlanc** [comment]
Sorry for not following back up on this @acrymble ! I don't really know what to do with the cloudflare issue so wondering if we could set up a meeting with @josircg maybe? I feel like this might go quicker via video chat than github issue, so let me know if that makes sense and I can start an email chain. Thanks!

**Comment by anisa-hawes** [comment]
Hello @josircg! Do you think you might have capacity to help us to move forward with this & Issue #1981? 
I'm working on Thursday and Friday next week – let me know if you have time to connect! 
Thank you ✨

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/technical-team 👋🏼  Just following up: Have we got hold of the information we need to transfer the DNS to our own server?

I'm cross-referencing related Issue #1981 for context.

**Comment by acrymble** [comment]
We've now got this set up. Thanks @josircg for telling us about the Google nonprofit option.
