### ISSUE TITLE
Broken link to GIS data

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#216]
Affects: http://programminghistorian.org/lessons/georeferencing-qgis

Links to 
'National Topographic System Maps – Western PEI, 1939-1944'
and
'National Topographic System Maps – Eastern PEI 1939-1944'

http://maps.library.utoronto.ca/datapub/PEI/NTS/west/
http://maps.library.utoronto.ca/datapub/PEI/NTS/east/

both give 403 forbidden errors.

**Comment by ianmilligan1** [comment]
Entire `datapub` site seems down. Simple search of the site doesn't turn it out. Any thoughts, @jburnford? (picking on you because I don't know if Josh or Dan have GitHub accounts, but feel free to forward to them)

**Comment by ianmilligan1** [comment]
Links are again working. Hazzah!
