### ISSUE TITLE
Visual Accessibility & Editorial Practices

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2174]
We have commissioned a report on visual accessibility, by Dr Amy Kavenagh, which has given our technical team a number of suggestions #2072 (Accessibility Audit). Thanks also to our summer placement student, Yifan Wang, who has helped us identify other issues related to colour vision deficiency.

Editorial-relevant issues include:

- [x] lessons should consider moving to a template for early sections, to make sure goals, scope, etc, are very clear up front. "This lesson will...etc" Especially for users with cognitive disabilities or those using screen readers. Some 'good' example lessons were pointed out, and some that could use more work in this area.
- [x] making sure screenshots are well and consistently described with low vision users in mind. This is currently varied from lesson-to-lesson. Not all lessons are following the style guides on Figure captions. This includes avoiding phrases that assume vision, such as 'as you can see' or 'it should look like this'. Editors can and should send back screenshots and visualisations that are not accessible or that are not strictly necessary.
- [x] avoiding red/green for data visualisation. With thanks to @drjwbaker there are accessible libraries for R & Python for choosing colours in data vis: "most standard languages have colour vision deficient friendly libraries, e.g. R https://cran.r-project.org/web/packages/colorBlindness/index.html https://cran.r-project.org/web/packages/colorBlindness/vignettes/colorBlindness.html and Python https://pypi.org/project/colorblind/" and editors should be aware of this and insist on their use.
- [x] screenshots of code should not be used. Instead code needs to be cut-and-pasteable.
- [x] being aware of the implication of choices of data / examples / case studies / software on users with visual impairments. For example, clean 20th century font vs medieval French manuscripts.

Dr Kavanagh also suggested curated lists of lessons targeted at users with visually impaired users. But I don't think that is an editorial matter.

Some of this can be taken care of during copyediting to avoid making more work for editors. But I think some of it comes down to editor training or continuing professional development.

Can editors and MEs provide some feedback on these initial ideas? Do you feel you could benefit from training on accessibility and editing? Does this feel like a copyediting task? Should we add it to the editorial guidelines along with the sections on sustainability / internationalisation?

@svmelton @rivaquiroga @spapastamkou @DanielAlvesLABDH

**Comment by rivaquiroga** [comment]
Thanks, @acrymble. This doesn’t feel to me like a copyediting task. Looks more like something we as editors should take into account. So yes, training on accessibility and editing would be great. 
We should definitely add these points to the editorial guidelines. Regarding item number two, I find very useful these suggestions for writing alt text for  data visualizations: https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81

**Comment by walshbr** [comment]
I'd also add them to the author guidelines - that's really where the work should take place for a number of these things. And the editorial load would just be to double check.

**Comment by DanielAlvesLABDH** [comment]
Thanks for this @acrymble! I totally agree we should include a closer look at these issues, and we should try to implement those suggestions and specifications. I agree with @walshbr that author guidelines is the first place we should look. But we should also be aware that it's not feasible to promise a full compliance.

**Comment by acrymble** [comment]
@anisa-hawes I know you're working on improving editor training. Is this something we can fold into that? #1932

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. I have integrated these into my current re-draft of the Editorial Guidelines. I've also added the resources @drjwbaker collated on colour vision deficiency to [the Accessibility page of our Wiki](https://github.com/programminghistorian/jekyll/wiki/Accessibility).
