### ISSUE TITLE
Newsletter: June/Mid-Year 2021 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2175]
This time of the year once again :) I am going to be collect here the things I need to write about on the newsletter for the time period between April 1st and June 30th give or take. As usual, I ask that if anyone sees anything missing, please edit or comment. Thanks!!

- [ ] New lessons: 

> - Detecting Text Reuse with Passim
> - Crowdsourced-Data Normalization with Python and Pandas
> - Télécharger des pages web avec Python
> - Noções básicas de páginas web e HTML 
> - Trabalhando com ficheiros de texto em Python
> - Introdução e instalação do Python
> - Configurar um ambiente de desenvolvimento integrado para Python (Windows)
> - Configurar um ambiente de desenvolvimento integrado para Python (Mac)
> - Configurar um ambiente de desenvolvimento integrado para Python (Linux)
> - Visualización y animación de tablas históricas con R

- [ ] New supporters: 
> - Universidad de los Andes, Colombia
> - Royal Danish Library / Copenhagen University Library, Denmark
> - Aarhus University Library, Denmark
> - Roskilde University Library, Denmark

- [ ] Additional Supporters: 

> - UCL, Faculty of Arts & Humanities, United Kingdom [2021].
> - Escola de Ciências Sociais FGV CPDOC, “Literacia digital: modelando competências digitais para humanistas e cientistas sociais”, Brazil [2021-2022].
> - The Open Knowledge Foundation Open Data Day mini-grant scheme, United Kingdom [2021].

- [ ] New members:
- I think no one this time? or @acrymble are we ready to announce?

- [ ] Events:
Any?

**Comment by rivaquiroga** [comment]
I added to the list the ES original lesson we published today. 
With this one we hit the 50 lessons milestone :tada: :rocket: :avocado: 

![Captura de pantalla de 2021-06-28 18-34-14](https://user-images.githubusercontent.com/31421616/123712268-fc28be80-d83f-11eb-8e61-21b700837772.png)

**Comment by acrymble** [comment]
@jenniferisasi yes you can announce but she wont start until 7 July so if you want to talk to her about it first for details, it depends on when you plan to publish the newsletter.

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi. I've joined the team today and I'd like to be able to help with this! Let me know if you have scope to connect sometime soon.
