### ISSUE TITLE
Broken link in 'Georeferencing in QGIS 2.0' tutorial

### ISSUE THREAD

**Issue by patrikpersson** [programminghistorian/jekyll#218]
In [the tutorial](http://programminghistorian.org/lessons/georeferencing-qgis), under the heading _Open the Necessary GIS Layers_, there is a link for downloading `lot_township_polygon`.

The link has a backslash that seems to break it. It is `http://www.gov.pe.ca/gis/license_agreement.php3?name=lot\_town&file_format=SHP`.

I think it should be `http://www.gov.pe.ca/gis/license_agreement.php3?name=lot_town&file_format=SHP`.

With the backslash, I end up on a page where I accept the license, but don't get anything to download. Without the backslash, it works as expected.

**Comment by ianmilligan1** [comment]
Thanks @patrikpersson!
