### ISSUE TITLE
Removing New Publication Manager Role

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2183]
A huge thank you to @JoshuaGOB for supporting the new PT publication this past year and a half and for helping all teams with onboarding support.

I've corresponded with @JoshuaGOB and he's agreed that we're going to transfer this role into the work of our new Publication Assistant who is starting next week. Therefore I'll remove this role from the Project Team page.

@JoshuaGOB is still staying with us in his editorial role.

I will be in touch with MEs about how the Publishing Assistant can support this work moving forward.

**Comment by DanielAlvesLABDH** [comment]
Many thanks for all your help Joshua! Um abraço!
