### ISSUE TITLE
Need to update EN lesson/FR translation for Python 3

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2187]
During review of the French  translation of lesson [Generating an Ordered Data Set from a Text File](https://programminghistorian.org/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file), see issue [362](https://github.com/programminghistorian/ph-submissions/issues/362) on ```ph-submissions```, we noticed that the original lesson proposes code in Python v.2.  The review of the translation is practically finished but before publishing we need to address this problem; the original lesson should also be updated at the same occasion. 
@rivaquiroga, am I right tagging you to see how to proceed?

**Comment by spapastamkou** [comment]
@InesSalome is the editor of the FR translation, I tag her to follow progress. Not sure who should be assigned this ticket yet:)

**Comment by spapastamkou** [comment]
update: @datalogism + @matgille will check with @InesSalome 
FYI @svmelton @programminghistorian/english-team as it concerns also the original in EN.

**Comment by rivaquiroga** [comment]
@spapastamkou, this one is on the list the bug assesor is currently checking

**Comment by spapastamkou** [comment]
Thank you @rivaquiroga  for this information. Of course we would not want to obstruct the assessor's work or have @matgille  and @datalogism  working on the same lesson. 
Would it be possible to have information about expected ~~delays~~ timeline to estimate the translated lesson's publication? More importantly, is it possible to have the list of the lessons under check? There were further ideas to update at least one lesson so it would be very useful. Thank you!

**Comment by datalogism** [comment]
After a first look i understood that the tutorial is based on OCR output data example. But for testing the code we will need to test it on a concrete dataset. Is https://programminghistorian.org/assets/Roman_to_Arabic.txt the only file linked to the tutorial ?

**Comment by InesSalome** [comment]
In fact, the code is based on the OCR version of _The Cartolare di Giovanni Scriba_ : if you want to test the code, you can find the dataset on the digital library of  Biblioteca europea di informazione e cultura : https://www.beic.it/it/articoli/biblioteca-digitale (typing "Giovanni Scriba" in the search bar).

**Comment by spapastamkou** [comment]
@InesSalome @datalogism thank you very much, however we need to freeze this for the moment since un assessment is already in progress

**Comment by rivaquiroga** [comment]
Hi, everyone!
Here are @jairomelo's suggestions to update this lesson to Python 3. 
@anisa-hawes, it looks like this is a case where we you and @svmelton should decide if these are major changes that will require a [DOI update](https://github.com/programminghistorian/jekyll/wiki/The-Programming-Historian-Digital-Object-Identifier-Policy-%28April-2020%29).


## Generating an Ordered Data Set from an OCR Text File

slug: 'generating-an-ordered-data-set-from-an-OCR-text-file.md'

- [x] ### line 100

replace url to `[python dictionary](https://docs.python.org/3.7/tutorial/datastructures.html#dictionaries)`

- [x] ### lines 162 to 182

`lev()` function raise an issue related with line 168 (cannot use the operator + between range and list)
I wasn't able to find a good solution modifying this function. The better solution I could find is to use this script, wrote in Python3. It uses `numpy` and I just modify it a bit to reduce the return to just the distance between two strings.

```python
'''
Code ripped from https://www.datacamp.com/community/tutorials/fuzzy-string-python
'''
def lev(seq1, seq2):
    """ levenshtein_ratio_and_distance:
        For all i and j, distance[i,j] will contain the Levenshtein
        distance between the first i characters of s and the
        first j characters of t
    """
    # Initialize matrix of zeros
    rows = len(seq1)+1
    cols = len(seq2)+1
    distance = np.zeros((rows,cols),dtype = int)

    # Populate matrix of zeros with the indeces of each character of both strings
    for i in range(1, rows):
        for k in range(1,cols):
            distance[i][0] = i
            distance[0][k] = k

    # Iterate over the matrix to compute the cost of deletions,insertions and/or substitutions    
    for col in range(1, cols):
        for row in range(1, rows):
            if seq1[row-1] == seq2[col-1]:
                cost = 0 # If the characters are the same in the two strings in a given position [i,j] then the cost is 0
            else:
                # In order to align the results with those of the Python Levenshtein package, if we choose to calculate the ratio
                # the cost of a substitution is 2. If we calculate just distance, then the cost of a substitution is 1.
                cost = 1
            distance[row][col] = min(distance[row-1][col] + 1,      # Cost of deletions
                                 distance[row][col-1] + 1,          # Cost of insertions
                                 distance[row-1][col-1] + cost)     # Cost of substitutions

    return distance[row][col]
```

The above code was tested against following scripts and its results seems accurate.

- [x] ### line 209

update of '/assets/Roman_to_Arabic.txt' to Py3

```python
### This script is entirely self-contained. Change the filename suffix to .py
### and you can run it at the command line like this:
### python Roman_to_Arabic.py

def rom2ar(rom):
    """ From the Python tutor mailing list:
    János Juhász janos.juhasz at VELUX.com
    returns arabic equivalent of a Roman numeral
    
    This is really a bit of brilliance, so I sprinkled it with
    print statements to demonstrate why it works.
    """
    roman_codec = {'M':1000, 'D':500, 'C':100, 'L':50, 'X':10, 'V':5, 'I':1}
    roman = rom.upper()
    roman = list(roman)
    roman.reverse()
    decimal = [roman_codec[ch] for ch in roman]
    result = 0
    print(f"For Roman Numeral: {rom.upper()}\nlist of roman characters translated to arabic equvalents,\nthen reversed: {decimal}\n")
    while len(decimal):
        act = decimal.pop()
        print(f"decimal.pop() yields: {act}")
        if len(decimal) and act < max(decimal):
            act = -act
            print(f"current result: {result} + {act} = {result + act}\nnegative because {abs(act)} is less than the maximum value in the list which is: {max(decimal)}")
        else:
            print(f"current result: {result} + {act} = {result + act}")
        print(f"our decimal list is now: {decimal}\n\n")
        result += act
        print("LOOP!")

    return result
    

print(rom2ar("mmcdlxxxix"))
print("Brilliant, huh?")
```

- [x] ### line 222

update link: `[collections](https://pymotw.com/3/collections/index.html)`

- [x] ### line 231

update link: `[.finditer()](https://docs.python.org/3.7/library/re.html#re.finditer)`

- [x] ### line 242

update to Python 3

- [x] ### lines 294 to 330

replace with:

```python
# At the top, do the importing you need and define the lev() function as described above, and then:

fin = open("our_base_OCR_result.txt", 'r') # read our OCR output text
fout = open("out1.txt", 'w') # create a new textfile to write to when we're ready
GScriba = fin.readlines() # turn our input file into a list of lines

for line in GScriba:
    # get a Levenshtein distance score for each line in the text
    recto_lev_score = lev(line, 'IL CARTOLARE DI GIOVANNI SCRIBA')
    verso_lev_score = lev(line, 'MARIO CHIAUDANO - MATTIA MORESCO')

    # you want to use a score that's as high as possible,
    # but still finds only potential page header texts.
    if recto_lev_score < 26 :

        # If we increment a variable 'n' to count the number of headers we've found,
        # then the value of that variable should be our page number.
        n += 1
        print(f"recto: {recto_lev_score} {line}")

        # Once we've figured out our optimal 'lev' score, we can 'uncomment'
        # all these `fout.write()` lines to write out our new text file,
        # replacing each header with an easy-to-find string that contains
        # the page number: our variable 'n'.

        #fout.write("~~~~~ PAGE %d ~~~~~\n\n" % n)
    elif verso_lev_score < 26 :
        n += 1
        print(f"verso: {verso_lev_score} {line}")
        #fout.write("~~~~~ PAGE %d ~~~~~\n\n" % n)
    else:
        #fout.write(line)
        pass

print(n)
```

- [x] ### line 383 to 406

replace with the following code:

```python
# At the top, do the importing you need, then define rom2ar() as described above, and then:
n = 0
romstr = re.compile("\s*[IVXLCDM]{2,}")
fin = open("out1.txt", 'r')
fout = open("out2.txt", 'w')
GScriba = fin.readlines()

for line in GScriba:
    if romstr.match(line):
        rnum = line.strip().strip('.')
        # each time we find a roman numeral by itself on a line we increment n:
        # that's our charter number.
        n += 1
        try:
            # translate the roman to the arabic and it should be equal to n.
            if n != rom2ar(rnum):
                # if it's not, then alert us
                print(f"{n}, there's a charter roman numeral missing?, because line number {GScriba.index(line)} reads: {line}")
                # then set 'n' to the right number
                n = rom2ar(rnum)
        except KeyError:
            print(f"{n}, KeyError, line number {GScriba.index(line)} reads: {line}")
```

- [x] ### line 431

replace with
`fout.write(f"[~~~~ GScriba_{rnum} :::: {num} ~~~~]\n")`

- [x] ### line 522

replace with:
`print(f"problem in charter: {(n + 1)}") #NB: this will miss consecutive problems.` 

- [x] ### line 527

replace with:
`print(f"number of italian summaries: {num_firstlines}")`

- [x] ### line 562

replace with: `if 1 in c.values(): print(pgno, pgfnlist)`

- [x] ### line 581

replace with: `>>> print(c)`

- [x] ### line 590

replace with: `>>> print(c.values())`

- [x] ### line 726

replace with: `print(f"charter: {ch}\ntext, line 1: {line1}\ntext, line 2: {line2}")`

- [x] ### line 728

replace with: `print(ch, "oops") # to pass the charters from the missing page 214` 

- [x] ### line 744

replace with: `print(f"missing charter {ch}")`

- [x] ### line 802

replace with: `print("printer's error? ", "pgno:", pgno, line)`

- [x] ### line 829

replace with: `print(f"chno. {d['chno']} fix the month {dt.group(2)}")`

- [x] ### line 831

replace with: `print(d['chno'], "The usual suspects ", sys.exc_info()[:2])`

- [x] ### line 833

update url with: [sys](https://pymotw.com/3/sys/index.html)

- [x] ### line 837

update url with: [PyMOTW](https://pymotw.com/3/datetime/index.html)

- [x] ### line 883

replace with: `print(f"chno: {charters[ch]['chno']}, date: {dt}")`

- [x] ### line 890

change for:

```markdown
```terminal
```

- [x] ### line 944

update following urls

[`Pickle`](https://docs.python.org/3.7/library/pickle.html)

[`json`](https://docs.python.org/3.7/library/json.html#module-json)

- [x] ### line 1009

broken link.

**Comment by svmelton** [comment]
Thanks @rivaquiroga! Yeah, this seems significant enough to warrant a new DOI in my view. @anisa-hawes the [DOI policy](https://github.com/programminghistorian/jekyll/wiki/The-Programming-Historian-Digital-Object-Identifier-Policy-%28April-2020%29) indicates that lessons published before 2020 should go through copyediting. I can make a copy of the lesson for you to copyedit, if that works for you.

**Comment by drjwbaker** [comment]
@svmelton: is this the first time we've had to go through the 'major changes' part of our workflow? If so, @anisa-hawes, I'm happy to be looped in as I'm curious how it work in reality (for context: we kinda made it up during DOI implementation so it hasn't really been tested).

**Comment by svmelton** [comment]
@drjwbaker It is! We're about to have a similar situation with a [lesson that needs to be retired](https://github.com/programminghistorian/jekyll/issues/2290), as well.

**Comment by drjwbaker** [comment]
> @drjwbaker It is! 

Excellent!

> We're about to have a similar situation with a [lesson that needs to be retired](https://github.com/programminghistorian/jekyll/issues/2290), as well.

But that shouldn't necesitate a new DOI, right?

**Comment by rivaquiroga** [comment]
#2301 might involve a new DOI too

**Comment by svmelton** [comment]
@drjwbaker No, it shouldn't need a new DOI. I'm wondering if we need to notify Sussex if we retire lessons (the URL technically changes even though the user won't notice it.) I might be overthinking it—did this come up at all in our convos about getting DOIs?

**Comment by drjwbaker** [comment]
> @drjwbaker No, it shouldn't need a new DOI. I'm wondering if we need to notify Sussex if we retire lessons (the URL technically changes even though the user won't notice it.) I might be overthinking it—did this come up at all in our convos about getting DOIs?

Hmm. If the object is the same but the URL changes, then - technically - that shouldn't affect the DOI, because the DI is for the O, rather than the I for the DO (if that makes sense). But, you are right, I don't think we checked that scenario. Best check with Sussex what they'd prefer.

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. Thank you for co-ordinating this!
Hello @jairomelo. Thank you for your amazing work!

I have made the updates you've suggested in [a new branch #2187](https://github.com/programminghistorian/jekyll/tree/Issue-2187). You can review the [changes to the lesson](https://github.com/programminghistorian/jekyll/commit/03f9eaf235e45332705ae7023bb358e8e3cedc8c) and the associated [.txt asset](https://github.com/programminghistorian/jekyll/commit/89b52f482053a8f8470f86023ec880b531e9acd0) in the commit history.

I have two questions:

1. Do you wish me to keep or delete the first two lines of code in [/assets/Roman_to_Arabic.txt](https://github.com/programminghistorian/jekyll/blob/gh-pages/assets/Roman_to_Arabic.txt) ?
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
```

2. At line 1009, I have removed the broken link you've identified http://www.diveintopython.net/html_processing/dictionary_based_string_formatting.html. I'd like to 
suggest https://docs.python.org/3/tutorial/inputoutput.html#the-string-format-method as a replacement resource, what do you think?

**Comment by jairomelo** [comment]
Hi @anisa-hawes :)

About your questions:

1) Those two lines are deprecated in Py3. You can delete them without any fear.
2) Excelent! I think is a great source of information :)

**Comment by anisa-hawes** [comment]
Thank you for your reply, @jairomelo! And thank you so much for all the energy you have given to this. 
I'll make that small additional change to the Roman_to_Arabic.txt asset now.

**Comment by anisa-hawes** [comment]
Hello @svmelton. The updates are now complete in the branch named [Issue-2187](https://github.com/programminghistorian/jekyll/tree/Issue-2187). How would you like me to go forwards with copyediting? Shall I merge this branch first, so that the lesson is usable in the meantime?

**Comment by spapastamkou** [comment]
And just to be clear for the workflow about the modifications to make on the French translation: the suggested changes should rather be made in the `ph-submissions` repository (where the translation review of the python 2 version has been achieved); or would it be preferable to create a new branch on Jekyll, push the existing translation, then add the changes on this jekyll branch and finally publish?  cc @InesSalome

**Comment by anisa-hawes** [comment]
Sorry, @svmelton. I meant to say in my previous comment that I would be interested to learn more about the process of requesting a new DOI, if you'd be happy to share that workflow with me.

**Comment by svmelton** [comment]
> Hello @svmelton. The updates are now complete in the branch named [Issue-2187](https://github.com/programminghistorian/jekyll/tree/Issue-2187). How would you like me to go forwards with copyediting? Shall I merge this branch first, so that the lesson is usable in the meantime?

Yes, please go ahead with copyediting! I think it's ok to merge the branch in the meantime. As I mentioned, it's just a matter of requesting a new DOI from Sussex, as far as I know (since we haven't actually run into this before!) I can get that started if we're ready, and I can cc you on the email if you'd like.

**Comment by anisa-hawes** [comment]
Thank you, @svmelton! The branch representing the update to Python3 is now ready to merge. I've requested your review on the PR. I'll work on the copyedits separately, and let you know when the revised text is ready so we can connect with Sussex re: the new DOI.

@InesSalome and @spapastamkou – as soon as PR #2338 is merged, you will be able to use the live EN version of the lesson to update the code in your FR translation.

**Comment by spapastamkou** [comment]
@anisa-hawes thanks!
