### ISSUE TITLE
Investigate options for installing a VM running Windows on my Mac. 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2195]
I'm going to investigate the options for installing a VM running Windows on my Mac to support my lesson maintenance activities.

**Comment by anisa-hawes** [comment]
Some additional thoughts: 

a virtual machine running Windows and macOS / or separate testing laptops which can be repeatedly cleaned to factory settings could be important to establishing safer and more effective lesson testing and lesson maintenance practice. 

Performing lesson maintenance on VMs/testing laptops would help us to understand how lessons work beyond specific dependancies of the authors' and initial testers' computers, software they already have installed, etc.

**Comment by anisa-hawes** [comment]
Virtual Box is an open source option: https://www.virtualbox.org/

Alternatively, Fusion could be a good solution: https://www.vmware.com/uk/products/fusion/fusion-evaluation.html 
https://store-uk.vmware.com/vmware-fusion-12-pro-5434554600.html
but the cost of a licence is £199.00

Using either, I believe I could install virtual Windows and MacOS environments on my computer, for use specifically as safe testing environments.

**Comment by anisa-hawes** [comment]
N.B. An OEM license would be required to install an instance of Windows on the VM

**Comment by anisa-hawes** [comment]
Snapshots in Virtual Box: https://www.virtualbox.org/manual/ch01.html#snapshots
Snapshots in Fusion: https://docs.vmware.com/en/VMware-Fusion/12/com.vmware.fusion.using.doc/GUID-4C90933D-A31F-4A56-B5CA-58D3AE6E93CF.html

The snapshots feature would be ideal for Lesson Maintenance activities. It allows a user to take 'snapshot' copy of a VM's current state, and later restore to that state.

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc. Having worked on this over a couple of sessions, I'm still struggling to get set up. Last night, I even enlisted the help of a friend – but actually that didn't help because suddenly, the workflow was out of my hands. I'm clear that I need to understand the methodology I'm using. I want to be able to re-produce my steps and install further VMs later. 

Someone definitely needs to write a PH lesson on VirtualBox! I'm using their manual, combined with instructions adapted from various online sources... but no luck yet. I would really appreciate some support with this, if any one on the @programminghistorian/technical-team has scope. I can (of course) be flexible and connect at a time which fits your schedules. Thank you!

**Comment by josircg** [comment]
Hi @Anisa-ProgHist I have a lot of experience on VirtualBox and, on my opinion, VirtualBox is *much* better than Fusion. My suggestion is to focus on it.

I can help you with that because I had some Win7 and Win10 appliances available. With that, you don't need to install windows from scratch. We can go on here or we can continue on email josircg at gmail dot com.

**Comment by josircg** [comment]
Important question: how many RAM do you have on your MAC?

**Comment by anisa-hawes** [comment]
Thank you so much, @josircg! It sounds like I could learn a lot with your support! 

I have 8GB of RAM. Do you think this will be sufficient? My hope is to install two VMs within VirtualBox to start with, one running macOS Catalina, and one running Windows. I will email you, and perhaps we can organise a time to connect.

**Comment by acrymble** [comment]
@Anisa-ProgHist this looks stuck. Would it be faster for us to see if we can find you a used Windows machine? Our goal is lesson maintenance, not VMs, after all.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. This has certainly been more challenging than I envisaged, but with with @josircg's kind 
help (and great patience) I have now got Windows 10 and Ubuntu running on Virtual Box. In the end, I organised use of an alternative MacBook (secondhand, via a friend) with greater RAM than my own computer. The VM still feels a little slow, but I will test it on a Windows-based Lesson Maintenance task today, and close this issue if it works efficiently enough. 

However, despite our best efforts we haven't been able to get a macOS installed – Apple do not make this easy. Possibly a problem with the .iso file, we're not certain. I downloaded mac-osx-catalina-iso via the Internet Archive after much searching. Unless anyone else on the team has a mac appliance/.iso ready to go ? I think I probably need to give up on the idea of running Catalina / Big Sur via a VM for now.

**Comment by anisa-hawes** [comment]
I am closing this Issue as I've now got Windows 10 and Ubuntu running on Virtual Box on a (borrowed) laptop, + macOS running on my own machine. This will suffice for now, but in conversation with @acrymble we agree that the Lesson Maintenance tasks I undertake for Windows-based Issues could be more efficient if I acquire a secondhand Windows computer.
