### ISSUE TITLE
update submissions page with editor interests and contact info. 

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#220]
this follows on #171.

**Comment by ianmilligan1** [comment]
We're going to update our [Project Team page](http://programminghistorian.org/project-team) with the [editorial roles listed here](https://github.com/programminghistorian/jekyll/wiki/Editorial-Roles). We'll have to [edit this file](https://github.com/programminghistorian/jekyll/blob/188d98d251554679b630d0902464b4ba61d9c495/_data/authors.yml). Ticket will remain open until we do that update.

**Comment by acrymble** [comment]
I've updated myself.

**Comment by ianmilligan1** [comment]
We realized that the bio updates that @acrymble and I did updated our author bios in the lessons too (duh, right?).

I think we'll make our Project Team page a static page. How does that sound @wcaleb?

**Comment by wcaleb** [comment]
@ianmilligan1 @acrymble I would recommend instead breaking out "interests" into a separate field in the YAML data, as I've done in the above commits. The advantage here is that sometimes you may need to change the bio (e.g., when you're promoted!), and you want that change to be reflected across the site on both the Project Team page and the lesson author bylines. This preserves the ability to change it in just one place, whereas going to a static page for Project Team would require fixing it in two places.

**Comment by acrymble** [comment]
@fredgibbs @ahegel @tapar001 @jerielizabeth @wcaleb this is still waiting on a 1 sentence contribution from you. If you don't think this is worthwhile (I'm now less convinced) then please say so. At the moment we've got a half-implemented solution, which is not good practice.

**Comment by acrymble** [comment]
Related to my above comment, I think it's more relevant for a potential reader/contributor to know that @ianmilligan1 is actively involved in editorial work and that @tapar001 is not than the approach we've done so far. We've gone with a model that showcases a flat structure, but that's not really useful for our readers who want to know who to contact.

**Comment by acrymble** [comment]
I think this is complete for our lesson-editing-editors. Reopen if needed.
