### ISSUE TITLE
Correção de link e verificar utilização do Komodo Edit nas lições de Python

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/jekyll#2200]
A lição https://programminghistorian.org/pt/licoes/instalacao-windows tem um erro no link do Komodo Edit e o software aparentemente já não se encontra disponível, apenas a versão IDE (https://www.activestate.com/products/komodo-ide/download-ide/). Peço ao @josircg que faça uma verificação no link quando possível (https://github.com/programminghistorian/jekyll/blob/gh-pages/pt/licoes/instalacao-windows.md) e um teste ao Komodo IDE para perceber se temos de actualizar a lição. Obrigado e abraço

**Comment by josircg** [comment]
Na verdade, a única vez que eu vi esse Komodo foi aqui no Programming Historian. Não sei em portugal mas aqui no Brasil, não conheço uma viva alma que utiliza ele! Mas não sei te temos abertura para sugerir outro editor pois ficaria muito diferente das outras versões. 

O link correto deve ser: https://www.activestate.com/products/komodo-ide/downloads/edit/

Mas eu vou testar a instalação em uma máquina com Windows com essa nova versão do editor para rever o passo a passo do tutorial.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @josircg! Acho que nós falámos nisso na altura da tradução, mas temos todas as outras lições de Python a falar desse editor, acho, pelo que a questão pode ser mais complexa. Por mim não há problema em mudar, mas isso teria de ser consistente em todas as lições. Talvez seja de agora fazermos apenas esta correção e depois com tempo, com mais lições de Python publicadas fazermos uma edição global.
