### ISSUE TITLE
Cleaning Data with OpenRefine - Windows, OpenRefine 34.1

### ISSUE THREAD

**Issue by tebain** [programminghistorian/jekyll#2201]
I seem to be having a problem with the Cleaning Data with OpenRefine lesson and was wondering if anyone else had this same error. I followed all the steps and up until the very end of the article, I had everything correct.
 However, on the last step of ad-hoc transformations (before I am instructed to export the clean data) it says "You will notice that 33,008 cells are affected" but every time I try it I only get 33,006 cells.
  Could someone respond when you get a chance and let me know if I'm doing something wrong or if the number in the article is a misprint?
  Thank you so much for your help!
  Tara B

**Comment by anisa-hawes** [comment]
I have tested this, and I can confirm that when I ran the final GREL function, `value.split('|').uniques().join('|')` I had transformed **33008** cells in column Categories, as indicated in the lesson.
