### ISSUE TITLE
Expenses form

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2205]
At the request of our finance manager @drjwbaker we are going to need to get an expenses procedure, including paperwork trail, in place in the coming few months, to accommodate new types of spending.

We'll try to find the least bureaucratic process we can.

**Comment by acrymble** [comment]
I've sent a draft to @drjwbaker for comment.

**Comment by acrymble** [comment]
Ok @drjwbaker is happy. We've updated the Wiki to reflect the simple change of making a spending request. If there are further things that need clarifying they will be fixed when they're noticed. But for now I am closing this.

https://github.com/programminghistorian/jekyll/wiki/Spending-Requests

**Comment by drjwbaker** [comment]
Fab. Thanks @acrymble. I've edited the contact point to me at the PH gmail.
