### ISSUE TITLE
Updating fr/consignes-auteurs.md and pt/directrizes-autor.md

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2210]
In dialogue with Riva, I have updated `en/author-guidelines.md` to reflect recent revisions to the Lesson Maintenance workflow. I have proposed a new paragraph (see below). Within #2077, Riva has provided an ES translation. This update requires translation into FR and PT so that it can also be added to `fr/consignes-auteurs.md` and `pt/directrizes-autor` as well.

--

Hello @programminghistorian/french-team and @programminghistorian/portuguese-team,

Please could you help to translate the following paragraph into French and Portuguese?:

`en/author-guidelines.md`

###What happens after your lesson is published?

Occasionally, we receive feedback from users who have encountered an error while completing one of our lessons. If this happens, our Publishing Assistant will open an Issue on GitHub, then carry out an assessment to confirm whether the error reported represents a problem caused by the user (editing the lesson's code or changing its dataset, for example) or a problem within the lesson itself. If the latter, our Publishing Assistant will re-test the relevant part(s) of the lesson and undertake research to identify a fix. As part of this Lesson Maintenance process, we may contact you alongside other members of the Programming Historian team to ask for advice. In the case that no fix can be found, we will propose adding a warning to the lesson explaining that some users may encounter an error. Where possible, the warning should include links to further reading, empowering users to identify a solution themselves.

With many thanks, Anisa

**Comment by rivaquiroga** [comment]
In #2077 we also updated the author guidelines regarding software citation and computational resources, ans the editor guidelines regarding the use of formulas: https://github.com/programminghistorian/jekyll/pull/2077/files#diff-dbb0ad10d5e3662eaa385051ddad999b946d167c497e5745bea6a3c3ddfc0498

**Comment by anisa-hawes** [comment]
Apologies, @rivaquiroga! I should have noted these updates within this Issue!
