### ISSUE TITLE
New £300 budget for publications (outreach)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2213]
This is an action arising from 22 July 2021 ProgHist meeting #2123:

ProgHist has been able to approve an additional budget of £300 per journal per year for outreach and community activity. This was originally suggested by @arojascastro (thank you). This ticket is a space for deciding what guidance and limits should be offered that ensure it is used appropriately and to good effect.

# It has been agreed that:

- the budget is to be spent at the discretion of MEs, in line with the Spending Request policy: https://github.com/programminghistorian/jekyll/wiki/Spending-Requests-and-Reimbursement.
- that the whole publication team should be consulted by the ME about the plan in advance
- the money must "advance the education of the public in the humanities, in particular in the use of digital tools and techniques and to promote research for the public benefit in all aspects of that subject and to publish the useful results" in some way.
- the money should promote one publication or one of our language communities directly.

# Queries for the whole Programming Historian team:

- Are there any activities would we NOT want this money to be used for? For example, travel costs, food/hospitality costs, any activity that doesn't involve members of the public, paying for conference fees, purchase of equipment, an activity in which the ME is the only participant/beneficiary, fees to speakers with full time salaries (just thinking aloud here to get the conversation started)?
- Do we want to encourage certain types of spending in particular? (e.g., free virtual events with paid speakers / facilitators?)
- Anything else?

Once we're all happy we can formally start using this money to promote our publications.

**Comment by drjwbaker** [comment]
Just to two notes from a process/finance perspective:

- this is in addition to ongoing spending (e.g. on copyediting)
- I'd be grateful if spending was for 1 or 2 purchases rather than lots of little receipts (because lots of little receipts take a lot more time for us to process!)

**Comment by acrymble** [comment]
@programminghistorian/english-team @programminghistorian/spanish-team @programminghistorian/portuguese-team @programminghistorian/french-team can I ask that each team discuss this internally and post to this ticket before the next Project Team meeting.

I presume we all agree that MEs should not use this money to buy themselves cigarettes and alcohol. What I'd like us to agree is the more realistic boundaries of use we want to set for this spending. I really want to avoid someone getting upset about their team's budget being used in a particular way. So I really would like feedback on this proposal.

**Comment by DanielAlvesLABDH** [comment]
Hi @acrymble and all. I already had the opportunity to talk with the PT team and the idea was to organize a workshop around one or two lessons / methods of the PH and use the money to pay for the speaker and to expand the outreach on social media. Do you think that is feasible / acceptable? What is the timetable for this? Thanks in advance

**Comment by drjwbaker** [comment]
Short note on timescales, the budget is available from the start of the new financial year (1 October)

**Comment by acrymble** [comment]
This hasn't received any real suggestions for practical limits. I want to be able to approve and close this at the team meeting #2223.

So I will suggest:

- the budget is to be spent at the discretion of MEs, in line with the Spending Request policy: https://github.com/programminghistorian/jekyll/wiki/Spending-Requests-and-Reimbursement.
- that the whole publication team should be consulted by the ME about the plan in advance, and should clearly promote the publication or its language community
- the money must "advance the education of the public in the humanities, in particular in the use of digital tools and techniques and to promote research for the public benefit in all aspects of that subject and to publish the useful results".
- the following are ineligible expenses: food & drink, travel costs, items for individual consumption / use, unless agreed by the Project Team.
- money cannot be carried forward year-upon-year. The year-end is 30 September.

**Comment by drjwbaker** [comment]
> the following are ineligible expenses: food & drink, travel costs, items for individual consumption / use, unless agreed by the Project Team.

Any reason? These may be reasonable expenses for outreach work.

**Comment by DanielAlvesLABDH** [comment]
I think travel costs can be justified for outreach work, we could invite someone for a conference or a workshop and some help to pay the travel expenses could be useful

**Comment by spapastamkou** [comment]
Most popular idea in the FR team: use this budget for workshops.

**Comment by acrymble** [comment]
This was agreed at the September 2021 project team meeting #2266.


- the budget is to be spent at the discretion of MEs, in line with the Spending Request policy: https://github.com/programminghistorian/jekyll/wiki/Spending-Requests-and-Reimbursement.
-  that the whole publication team should be consulted by the ME about the plan in advance, and should clearly promote the publication or its language community
-  the money must "advance the education of the public in the humanities, in particular in the use of digital tools and techniques and to promote research for the public benefit in all aspects of that subject and to publish the useful results".
-  that physical travel can only be supported by reimbursement and that if this is a financial strain then @drjwbaker should be alerted well in advance. Anyone traveling should ensure they have full travel & health insurance in place either personally or through their employer as this cannot be provided by ProgHist ltd.
-  money cannot be carried forward year-upon-year. The year-end is 30 September.
- Details on spending and reimbursing are available: https://github.com/programminghistorian/jekyll/wiki/Spending-Requests-and-Reimbursement

[Anything wrong, please correct @drjwbaker / @anisa-hawes]

Happy outreaching everyone!

**Comment by anisa-hawes** [comment]
Do you think it would be useful to set up a new Project Board for MEs to track their outreach spending, @drjwbaker?

**Comment by drjwbaker** [comment]
Thanks for the idea. However, I'm hoping MEs submit spend in chunks, so I'm hopeful we won't need to track it in too much detail.

**Comment by anisa-hawes** [comment]
Okay, that makes good sense. With these agreements in place, I'll close this Issue. But let me know if you feel anything further is needed.
