### ISSUE TITLE
Brandon Walsh Retirement 😭 

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2214]
Sadly our beloved @walshbr is retiring at the end of the Summer!

As far as I can tell the only remaining open ticket assigned to you is #2072 which we'll discuss at our Summer meeting (hopefully next week).

A few other remaining things that I'm sure you're already on top of Brandon is making sure we hand over any of your remaining duties, remove you from any documentation so that you don't get unnecessarily pinged, and then I wonder if we should do some type of exit interview 🤔 (just a thought though!) .

Regardless just wanted to start this ticket off to make sure that we kept track of anything related to your retirement ❤️ .

**Comment by walshbr** [comment]
Happy to do an exit interview if ya want - @svmelton had talked about it as well, and we could do the two together if you want. This is the full checklist:

- [x] Remove Google Groups access (@jenniferisasi)
- [x] Remove Google Analytics access (@acrymble)
- [x] Remove Github Jekyll access (@ZoeLeBlanc)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@jenniferisasi)
- [x] Change team: true to team: false, and add team_end: YYYY to the _data/ph_authors.yml file to remove the person from the Project Team page (@acrymble)
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (team leader).
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts (@mariajofana).
- [x] If they hold any other team roles, inform @mariajofana that a replacement is needed.
- [X] Finalize Twine Lesson publication
- [x] Discuss #2072 with tech team
- [x] debrief with @ZoeLeBlanc and @svmelton 

I do have one lingering lesson editing that's still in the pipeline, so I think we might not want to actually take steps on these until, say, the third or fourth week of August? I'm not sure the lesson will be done by then, but I think I should be able to carry out those duties after the summer's end (might be slightly easier if I still have push access though).

**Comment by drjwbaker** [comment]
@walshbr I note you are an admin on the repo https://github.com/orgs/programminghistorian/teams/administrators Do we need to nominate someone to take over this or are 4 people enough?

**Comment by walshbr** [comment]
That'd be up to @ZoeLeBlanc I think. I believe ML (when he was technical lead) wanted to have fewer folks as admins, and I was only added later for whatever particular work I was doing at that time.

**Comment by drjwbaker** [comment]
ML did. Happy to @ZoeLeBlanc to make the call if having a second @programminghistorian/technical-team person as repo admin is useful.

**Comment by walshbr** [comment]
@svmelton I just moved the last lesson I'm editing along to copyediting. So I think we should be good for going ahead with the rest of these now that that piece is moving through the finale stages and we have a tech call scheduled to discuss the last open ticket on my plate.

**Comment by svmelton** [comment]
Thank you @walshbr!! We're going to miss you :(

**Comment by walshbr** [comment]
@jenniferisasi @acrymble @ZoeLeBlanc @drjwbaker just a note to start checking off these items. I'm meeting with the tech team tomorrow to discuss the last things I'd been working on with them, so might be good to wait until after that to remove my push access to the repository. But other than that I'm sailing away.

**Comment by walshbr** [comment]
DM'd @svmelton and @ZoeLeBlanc about a debrief if they wanted it. We've got one scheduled.

**Comment by walshbr** [comment]
Opened #2233 to remove me from the project team page (no need to make @acrymble do it for me).

**Comment by ZoeLeBlanc** [comment]
Closing this since @walshbr is officially retired 😭 ! We miss you Brandon ❤️
