### ISSUE TITLE
Onboarding Alex to Tech Team

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2215]
This is a pretty redundant ticket but wanted to make sure that we had officially both welcomed @hawc2 to the Tech Team and also made sure to add him to any official documentation, as well as answer any questions about our processes (or lack thereof 😅 )

**Comment by hawc2** [comment]
Thanks for the formal welcome! I do need to update the profile page in a few ways. 

Not to make this ticket complicated or anything, but just to say the work I've been doing with @walshbr and @Anisa-ProgHist updating the docs for Onboarding new Editors has been fruitful, and if there's anything I can do to help formalize onboarding process for the tech team, let me know!

**Comment by acrymble** [comment]
@ZoeLeBlanc is this complete?

**Comment by ZoeLeBlanc** [comment]
Pretty much! Final thing I wanted to check was with @hawc2 and if he had SSH (or HTTPS) for this repo setup locally? I'm assuming you do but since Jenn didn't I want to double check. Thanks!

**Comment by hawc2** [comment]
Yep should be all set!
