### ISSUE TITLE
August Tech Team Meeting: August 24 2021

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2216]
Hiya @programminghistorian/technical-team here's our agenda for our Summer Tech Team Meeting.

We're tentatively scheduled for August 3 2021 from 10-11:30am EST (pending my move) and I've already emailed the Zoom link.

Our agenda is pretty thick so hopefully we can get through everything and if I've missed anything below please feel free to add it.

-  Deal with initial metadata ticket #1995
- @walshbr update us on #2072 and plan next steps
- @hawc2 update us on #2030 and plan next steps
- @jenniferisasi update us on #2100 and plan next steps
- Zoe update us on #2020 and plan next steps
- Discussing  #2195 and whether @Anisa-ProgHist needs any help with this ticket
- Zoe finally dealing with #1981
- Discuss #2214 @walshbr retiring this summer 😢  
- Also onboard @hawc2 officially to the Tech Team 🎉 with #2215

**Comment by acrymble** [comment]
I raised this in the Project Team meeting @ZoeLeBlanc but I think it would be worth the tech team assessing https://janeway.systems/ as a possible platform solution. It's developed by the DH team behind the Open Library of the Humanities.

**Comment by ZoeLeBlanc** [comment]
Also adding to our agenda #2227 to discuss both git workshops for editors and overall processes

**Comment by acrymble** [comment]
@ZoeLeBlanc when you are able can you please update me on the status of the Cloudflare account? I can't set up Anisa with an email address until that's complete, and I can't do it myself.

**Comment by ZoeLeBlanc** [comment]
Closing this issue since most of these issues have been closed now.
