### ISSUE TITLE
Adding the PT project in EN, FR and ES About pages 

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2217]
I noticed that the About / A propos / Acerca pages do not list the PH in PT in the History of the project part (see here for the EN page: https://programminghistorian.org/en/about#history-of-the-project). We should add a phrase that in 2021 we added a Portuguese version just like in the [PT page](https://programminghistorian.org/pt/sobre#hist%C3%B3ria-do-projeto).

**Comment by jenniferisasi** [comment]
Oh, good catch @spapastamkou we totally forgot about that little but important part 😳😅 

How does this sound? EN and ES
- A year later, we were joined by a Portuguese-speaking team and launched [Programming Historian em português](https://programminghistorian.org/pt/) in early 2021. 
- Un año después, un equipo de habla portuguesa se unió a nosotros e inauguramos [Programming Historian em português](https://programminghistorian.org/pt/) a principios de 2021.

FR attempt: 
- Un an plus tard, nous avons été rejoints par une équipe lusophone et avons lancé [Programming Historian em português](https://programminghistorian.org/pt/) début 2021.

**Comment by spapastamkou** [comment]
Cool, thanks @jenniferisasi, let's keep this pattern. I will open a pull request shortly. It will be a good occasion to also clean these pages from all the "The" of Programming Historian (there are plenty everywhere) :-)

**Comment by jenniferisasi** [comment]
You can ping me to do the review and approve and anything else if needed :)

**Comment by DanielAlvesLABDH** [comment]
Obrigado! 😉
