### ISSUE TITLE
User notes on Installing Python Modules with pip

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#222]
Lesson user Hypothesis annotations:
https://hypothes.is/a/AVK35MmZvTW_3w8Lyxdz What to try if using Windows
https://hypothes.is/a/AVKOOE8evTW_3w8Lylxj Adding pip flag to make command successful
https://hypothes.is/a/AVLBSrICvTW_3w8LyzEQ Only necessary if on Mac/Linux

**Comment by fredgibbs** [comment]
add a note about updating pip (and dependencies)?

**Comment by acrymble** [comment]
Sorry, I'm unclear. Was this changed, or no?
