### ISSUE TITLE
Technical Onboarding of Tiago

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2220]
This is a checklist of items that @drjwbaker needs to work through with our new Digital Humanities Publishing Assistant (in support of the Jisc and TNA funded project ‘Programming Historian publications: developing computational skills for digital collections’), @tiagosousagarcia (from 9 August 2021).

- [x] add to Github
- [x] work station assessment
- [x] dedicated email?
- [x] introduce to Project documentation on website
- [x] introduce to Wiki
- [x] introduce to Github tickets
- [x] add to project team page & confirm happy with pull requests
- [x] share funded project specific documentation
- [x] establish welcome meetings with project team members (over the coming weeks)

**Comment by drjwbaker** [comment]
@tiagosousagarcia Please ignore any notifications from me and/or this repo until next week :)

**Comment by drjwbaker** [comment]
@acrymble Could you please make @tiagosousagarcia a member of https://github.com/orgs/programminghistorian/people. I don't appear to have those admin rights.

**Comment by acrymble** [comment]
@drjwbaker it says he isn't a github member, so I can't add him.

**Comment by drjwbaker** [comment]
That is weird @acrymble. I checked with one of my non-PH organisations/repos, and I can invite @tiagosousagarcia.

**Comment by acrymble** [comment]
got it. Sorry. You don't include the @ symbol :P

**Comment by drjwbaker** [comment]
>  establish welcome meetings with project team members (over the coming weeks)

@acrymble: would you be willing to talk to @tiagosousagarcia briefly about the project structure? E.g. anything they needs to know in addition to that which is on the wiki https://github.com/programminghistorian/jekyll/wiki (note: Tiago works on Monday only)

**Comment by drjwbaker** [comment]
>  dedicated email?

Note to discuss with @peterwebster via email about setting up a dedicated email for this project that he and @tiagosousagarcia can access (e.g. for cfp submissions). Note that this may not be possible as a programminghistorian.org email as that ticket is a little stuck https://github.com/programminghistorian/jekyll/issues/2148 (correct @acrymble?)

**Comment by acrymble** [comment]
@drjwbaker I'm just about to go on leave, so I don't think I'll be able to reach @tiagosousagarcia in time. I can reconnect in September though if it's still useful at that stage.

**Comment by drjwbaker** [comment]
> @drjwbaker I'm just about to go on leave, so I don't think I'll be able to reach @tiagosousagarcia in time. I can reconnect in September though if it's still useful at that stage.

Thanks @acrymble. September is still useful.

**Comment by amsichani** [comment]
do let me know if I can be of help on the email front in the meantime -

**Comment by tiagosousagarcia** [comment]
Hi @drjwbaker, @acrymble and @amsichani! Very excited to join the team! Rather embarrassingly, my first contribution here is to ask for help -- I seem not to have permissions to create a branch (so that I can add myself to the project team) -- anything anyone can do on that front, or am I just missing something really obvious?

**Comment by drjwbaker** [comment]
Ack. I think you might need to be added to the Project Team https://github.com/orgs/programminghistorian/teams/project-team/members?query= @acrymble @walshbr @JoshuaGOB @ZoeLeBlanc: as maintainers of this team, am I right?

**Comment by acrymble** [comment]
@tiagosousagarcia you should have received an invite. Can you check your github or spam to see if one is waiting?

**Comment by drjwbaker** [comment]
@tiagosousagarcia If this doesn't get fixed by the end of today, hopefully we can ensure you are ready to go next Monday!

**Comment by tiagosousagarcia** [comment]
@acrymble I received an invite to join the organisation, but I'm guessing I need a different permission to work in this repo -- nothing in spam/github boxes, I'm afraid

**Comment by tiagosousagarcia** [comment]
@acrymble @drjwbaker I'm guessing that someone might have done something, because I can now do it! Thanks!

**Comment by drjwbaker** [comment]
Ah the mysteries of github.

**Comment by amsichani** [comment]
Fantastic @tiagosousagarcia ! Please go ahead and add yourself on the project team page, so we can tick (almost) all the boxes of this ticket. As @acrymble and @drjwbaker are soon going on holidays, happy to answer any questions (today or next Monday) here or via email/zoom ( I am off from 23rd Aug).

**Comment by tiagosousagarcia** [comment]
Thanks @amsichani!
