### ISSUE TITLE
Newsletter: September 2021

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2221]
Hello all,

I am opening this Issue to collate content for our September Newsletter. I'll be collaborating with @jenniferisasi to produce this one, and will be taking it forward as part of my role. 

Please let me know if you have ideas for inclusion under the headings I've sketched out below, or if you'd like to suggest a another section. Edits and comments are very welcome!

Thank you! 

Anisa

1. **Recent research activities**: Have you contributed to articles or events that you'd like me to share?

- @drjwbaker and @amsichani I will summarise the new [partnership between Jisc, the Programming Historian and The National Archives (TNA)](https://research.jiscinvolve.org/wp/2021/07/23/boost-your-skills-in-working-with-digital-collections/) and can include a link to the [Call for Papers](https://programminghistorian.org/posts/cfp-jisc-ph)

- @acrymble and @mariajoafana I will include the publication of [‘The Globally Unequal Promise of Digital Tools for History: UK and Colombia Case Study’ in Adele Nye (ed.) Teaching History for the Contemporary World (Springer, 2021), 85-98.](https://www.springer.com/gp/book/9789811602467).

- @DanielAlvesLABDH I will include the publication of [‘Ensinar Humanidades Digitais sem as Humanidades Digitais: um olhar a partir das licenciaturas em História’, Revista EducaOnline, v. 15, n. 2 (2021)](https://novaresearch.unl.pt/files/32228034/Ensinar_Humanidades_Digitais.pdf).

2. **New Lessons**: Original lessons or translations published since our mid-year newsletter

- [Reutilizar colecciones digitales: GLAM Labs](https://programminghistorian.org/es/lecciones/reutilizando-colecciones-digitales-glam-labs) de Gustavo Candela, María Dolores Sáez, María Pilar Escobar y Manuel Marco Such, muestra cómo reutilizar colecciones digitales publicadas por instituciones de patrimonio cultural.

- [Introducción a la codificación de textos en TEI (parte 1)](https://programminghistorian.org/es/lecciones/introduccion-a-tei-1_) de Nicolás Vaughan te enseña los rudimentos de TEI-XML para codificar textos.

- [Introdução ao Omeka.net](https://programminghistorian.org/pt/licoes/introducao-omeka-net) por Miriam Posner e traduzido por Gabriela Kucuruza você aprenderá a criar sites na web para mostrar coleções de itens com o Omeka.net.

- 

3. **New Supporters and Partnerships**: Individual or Institutional support and partnership announcements  

- [Cambridge Digital Humanities](https://www.cdh.cam.ac.uk/) 

-

-

4. **Team News**: A space to welcome new members, and say thank you to people who are retiring

- This September we bid farewell to our brilliant colleague Brandon Walsh from the University of Virginia, who is retiring. He has worked as part of our editorial and technical teams since 2017. Thank you, Brandon, for your energy and tireless commitment to this project!

- Nos alegra presentarles a nuestros tres nuevos compañeros Isabelle Gribomont, Nicolás Linares, y Nicolás Vaughan quién se unen al equipo de Programming Historian en español. ¡bienvenidos! Reúnete con ellos  [en nuestro blog](https://programminghistorian.org/posts/llano-gribomont-vaughan).

- joining of Tiago Sousa Garcia

- Four students from [Universidade NOVA de Lisboa](https://www.unl.pt/) are joining the Portuguese team this September. As part of their fellowships awarded by [Instituto de História Contemporânea](https://ihc.fcsh.unl.pt/), they will be working with us on new translations of lessons, covering themes as varied as GIS, digital archives and platforms, data management and Python. These fellowships are generously supported by the [Fundação para a Ciência e Tecnologia](https://www.fct.pt/fct.phtml.en)'s special [Verão com Ciência 2021](https://www.fct.pt/apoios/veraocomciencia/index.phtml.pt) initiative.

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/english-team @programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team Please let me know if you have news to share within the September Newsletter!

**Comment by DanielAlvesLABDH** [comment]
>     * @DanielAlvesLABDH Would you like me to include the publication of [‘Ensinar Humanidades Digitais sem as Humanidades Digitais: um olhar a partir das licenciaturas em História’, Revista EducaOnline, v. 15, n. 2 (2021)](https://novaresearch.unl.pt/files/32228034/Ensinar_Humanidades_Digitais.pdf)?

Sorry for the late reply Anisa. Yes, do include this, please. Thanks

**Comment by mariajoafana** [comment]
Hi @Anisa-ProgHist Yes, please include the "Globally Unequal Promise..." publication

**Comment by joanacvp** [comment]
Hello @Anisa-ProgHist !

In the Portuguese Team, during September, we are having 4 students with fellowships working with us in the translation of lessons regarding GIS, digital archives and platforms, data managment and python. Those fellowships were awarded to the Institute of Contemporary History from NOVA FCSH and are funded by the Portuguese Foundation for Science and Technolgy, through the special support  "Verão com Ciência 2021" [Summer with Science 2021] (total amount: 1 784,48€).

**Comment by jenniferisasi** [comment]
> Hello @Anisa-ProgHist !
> 
> In the Portuguese Team, during September, we are having 4 students with fellowships working with us in the translation of lessons regarding GIS, digital archives and platforms, data managment and python. Those fellowships were awarded to the Institute of Contemporary History from NOVA FCSH and are funded by the Portuguese Foundation for Science and Technolgy, through the special support "Verão com Ciência 2021" [Summer with Science 2021] (total amount: 1 784,48€).

@joanacvp that is fantastic! Maybe when you have a minute you could write something similar to what @acrymble and his students wrote in June? https://programminghistorian.org/posts/ucl-placement-2021 That way we have a brief announcement of the support in the newsletter and then we also have a more extended record of their collaboration.

**Comment by anisa-hawes** [comment]
Hello there @tiagosousagarcia! Could you tell me a little bit about the projects you are contributing to at *Programming Historian*? I'd like to write a few lines about what you are working on in our September Newsletter.

**Comment by joanacvp** [comment]
> > Hello @Anisa-ProgHist !
> > In the Portuguese Team, during September, we are having 4 students with fellowships working with us in the translation of lessons regarding GIS, digital archives and platforms, data managment and python. Those fellowships were awarded to the Institute of Contemporary History from NOVA FCSH and are funded by the Portuguese Foundation for Science and Technolgy, through the special support "Verão com Ciência 2021" [Summer with Science 2021] (total amount: 1 784,48€).
> 
> @joanacvp that is fantastic! Maybe when you have a minute you could write something similar to what @acrymble and his students wrote in June? https://programminghistorian.org/posts/ucl-placement-2021 That way we have a brief announcement of the support in the newsletter and then we also have a more extended record of their collaboration.

@jenniferisasi that should be great! We should definitely do it

**Comment by drjwbaker** [comment]
> Hello there @tiagosousagarcia! Could you tell me a little bit about the projects you are contributing to at _Programming Historian_? I'd like to write a few lines about what you are working on in our September Newsletter.

@tiagosousagarcia works Monday/Tuesday so I'll chip in with a little info now that he can add to later:

- he is working in support of the Jisc/TNA/PH partnership, in particular articles selected as part of the [cfp](https://programminghistorian.org/posts/cfp-jisc-ph).
- at the moment he is getting to grips with our publication workflows by doing some work with the PT team.
- when not working for us, he works for [Newcastle University Research Software Engineering](https://rse.ncldata.dev/)

**Comment by anisa-hawes** [comment]
Super, thank you @drjwbaker! I'll wait to hear from @tiagosousagarcia if he'd like me to add anything else!

**Comment by tiagosousagarcia** [comment]
Hi @anisa-hawes! @drjwbaker already gave you the gist of it, I'll just add a few more lines of background (if at all relevant):

- I've been using and following *PH* for years, and I'm incredibly excited to be part of the team;
- Supporting the Jisc/TNA/PH partnership is a particularly well-suited task for me, as I have long been interested in how to use big data methods with humanistic datasets;
- Before joining the Newcastle RSE, I was an RA for the [ATNU project](https://research.ncl.ac.uk/atnu/);
- I'm, otherwise, an early modernist, specialising in early modern translations into English from vernaculars, and I have a past in Computer Engineering.

Anything else you need just let me know, I'll promise to reply quicker!

**Comment by amsichani** [comment]
hi @anisa-hawes , a bit of outreach news from my part to be included @ the newsletter if you feel that it fits: my opening keynote @ [DH Benelux](https://2021.dhbenelux.org/schedule/) on 2nd June was entitled "Sustaining communities in Digital Humanities: diversity, collaboration, and capacity building in digital scholarship and pedagogy" where I showcased our PH work.

**Comment by acrymble** [comment]
> my opening keynote @ [DH Benelux](https://2021.dhbenelux.org/schedule/) on 2nd June was entitled "Sustaining communities in Digital Humanities: diversity, collaboration, and capacity building in digital scholarship and pedagogy" where I showcased our PH work.

@amsichani you should put this on https://programminghistorian.org/en/research

**Comment by nabsiddiqui** [comment]
A bunch of us presented at the Global Digital Humanities Symposium: https://msuglobaldh.org/abstracts/#programming-historian.

I gave a talk entitled "Programming Historian and the Challenges of Globally Distributed Learning" at  Seshadripuram Evening Degree College in Bengaluru, India. @JMParr and I will be giving a talk called "The Programming Historian as Pedagogical Tool" at the Center for Urban History at Lviv, Ukraine.

**Comment by jenniferisasi** [comment]
> A bunch of us presented at the Global Digital Humanities Symposium: https://msuglobaldh.org/abstracts/#programming-historian.
> 
> I gave a talk entitled "Programming Historian and the Challenges of Globally Distributed Learning" at Seshadripuram Evening Degree College in Bengaluru, India. @JMParr and I will be giving a talk called "The Programming Historian as Pedagogical Tool" at the Center for Urban History at Lviv, Ukraine.

We included the Global DH Symposium presentation on the newsletter in April. 

@nabsiddiqui can you tell us the dates for your talk in Bengaluru and the one with Jessica? thanks

**Comment by JMParr** [comment]
@Jennifer Isasi ***@***.***> Our talk is 29 September. Have we
also covered the NewsEye conference that a big group of us presented at
this past March. I also gave a presentation to the University of Cambridge
Data School on 30 March.

**Comment by spapastamkou** [comment]
@anisa-hawes Some info about the NewsEye conference where we presented with Jess and Riva: 
[programme ](https://www.newseye.eu/international-conference/conference-programme/day-2-17-march-2021/)(see session 4)
[slides](https://www.newseye.eu/fileadmin/user_upload/Challenges_for__Digital_Literacy_in_the_Humanities.pdf) and abstract in the[ book of abstracts](https://zenodo.org/record/5167375) of the conference

**Comment by jenniferisasi** [comment]
@JMParr and @spapastamkou yes, the NewsEye conference information was also included in the first newsletter of the year.

**Comment by nabsiddiqui** [comment]
@jenniferisasi The one I gave in India was on June 29th, 2021

**Comment by anisa-hawes** [comment]
Super! Thank you, all! 

It feels that through the process of gathering content for this Newsletter, we have learned a lot about each other's recent work and activities. 

I have added the question of how we might be able to adapt and improve our external Communications strategies to the [agenda for our next Project Team Meeting](https://github.com/programminghistorian/jekyll/issues/2223), but I am wondering if an internal catch up to share recent research and project news might be useful too? Perhaps on a quarterly basis? It's so interesting to hear what each of you are involved in.

In the meantime, I'd be happy to facilitate updates to the research/investigacion/recherche/pesquisa pages. Send me a message anytime if there's something you'd like to add!

**Comment by jenniferisasi** [comment]
Hi @anisa-hawes looks like we have a lot to share on this newsletter! Do you want me to wrap it up and you review, or viceversa?

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi! I am just finishing writing this up! When I'm done, I'll create a new Branch with my draft and connect with you so that you can review it for me. I really appreciate your support 🙂

**Comment by jenniferisasi** [comment]
> Thank you, @jenniferisasi! I am just finishing writing this up! When I'm done, I'll create a new Branch with my draft and connect with you so that you can review it for me. I really appreciate your support 🙂

Fantastic! Thanks @anisa-hawes
