### ISSUE TITLE
Lost copy of Daniel's research

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2226]
We've lost the live link to a paper @DanielAlvesLABDH  wrote 

Daniel Alves, ‘Ensinar Humanidades Digitais sem as Humanidades Digitais: um olhar a partir das licenciaturas em História’, Revista EducaOnline, v. 15, n. 2 (2021).

This was possibly due to a fire. In order to continue merging pull requests we have to remove the link: http://www.latec.ufrj.br/revistas/index.php?journal=educaonline&page=article&op=view&path[]=1176

But once vacation is over it would be nice if we can ask @DanielAlvesLABDH if he has a copy that we can host so that the work is not lost.

**Comment by DanielAlvesLABDH** [comment]
New copy found... https://github.com/programminghistorian/jekyll/pull/2218#issuecomment-897804819
