### ISSUE TITLE
Offboarding Sylvia Fernández

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2232]
- [x] Remove Google Groups access (@jenniferisasi)
- [x] Remove Google Analytics access (@acrymble)
- [x] Remove Github Jekyll access (@ZoeLeBlanc)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@jenniferisasi)
- [x] Change team: true to team: false, and add team_end: YYYY to the _data/ph_authors.yml file to remove the person from the Project Team page (@acrymble)
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@svmelton).
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts (@mariajofana).
- [x] If they hold any other team roles, inform @mariajofana that a replacement is needed.

**Comment by svmelton** [comment]
@sferna109 currently has one lesson in the workflow, which we're working on reassigning to another editor.

**Comment by jenniferisasi** [comment]
I will keep @sferna109 in the google groups until the end of the off-boarding process so she can receive goodbye emails

**Comment by acrymble** [comment]
@jenniferisasi the google group is the last outstanding item here.

**Comment by jenniferisasi** [comment]
Ok, done!
