### ISSUE TITLE
Clean up PH-Submissions repo

### ISSUE THREAD

**Issue by hawc2** [programminghistorian/jekyll#2235]
The [PH-Submissions repo](https://github.com/programminghistorian/ph-submissions) has been renovated over the last couple years to make it look more like the Jekyll repo's directory structure. However, a legacy [lessons folder](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/lessons) still exists, and it has caused confusion for new editors on the English and Portugues team, who both have lessons in revision currently stored there. 

@Anisa-ProgHist and I have discussed with the tech team (@ZoeLeBlanc @jenniferisasi) the need to clean up the repo and clarify guidelines for future lessons.  It appears the French and Spanish teams have stopped using this directory, so it will only require PT and EN editors to adjust slightly. 

Once the Lessons are moved from this folder into their corresponding "en," "fr," "es," or "pt," folders, for any lessons currently under review, we will need to update the live preview links on the corresponding issue tracking the revision process. 

For lessons that are already published, we have discussed putting those lessons in an archive folder in the PH-submission repo just so we preserve the history of their revision process. If necessary, we could update all old preview links for closed issues, but that seems unnecessary since the final versions are viewable on the Jekyll site. 

Once we receive approval to move forward on this from @programminghistorian/english-team and @programminghistorian/portuguese-team , @Anisa-ProgHist and I can do the cleaning up of the repo, migration of lessons and the updating of any links. We can also notify relevant editors and authors of any changes to the file structure for ongoing lessons.

**Comment by DanielAlvesLABDH** [comment]
Hi @hawc2, I have started to move the files of the lessons to the "pt" folder before the vacation, but there is still two files that are under revision right now. If the links in the tickets can be updated, for me those files can move to the "pt" folder and the old one can be deleted. Thanks for this

**Comment by ZoeLeBlanc** [comment]
This all sounds fantastic @hawc2 and @Anisa-ProgHist! Let me know if there's anything else I can do to help. Should I open a separate issue for updating our ph-submissions repo documentation? Mostly wondering if we should fold #1995 into a larger overall ticket for ph-submissions workflows. Lmk what you think. Thanks!

**Comment by hawc2** [comment]
Opening a separate repo for ph-submissions docs makes sense to me. Once
ticket #1995 is finished it'll be easier to update docs accordingly

**Comment by anisa-hawes** [comment]
As a general step towards tidying up the Submissions Repo (and keeping it organised going forwards) it might be worth us updating the README.md for `ph-submissions`.

We need to clarify which file directory location editors should put lesson .md files. The current instruction is not correct.

--

The URLs for lessons in the Submissions Repository should be:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/lessons/lesson-file-name-here.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/lesson-file-name-here.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/lecons/lesson-file-name-here.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/lesson-file-name-here.md

The URLs for translations in the Submissions Repository should be:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/translations/lesson-file-name-here.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/lesson-file-name-here.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/lesson-file-name-here.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/traducoes/lesson-file-name-here.md 


*N.B. At the moment, the PT team use a slightly different directory structure. Their folder of ‘traducoes’ is inside the ‘licoes’, so the URLs are currently structured*:
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/lesson-file-name-here.md 

--

If lesson .md files are in the correct location, then URLs for live previews in the Submissions Repository will be:

http://programminghistorian.github.io/ph-submissions/en/lessons/lesson-file-name-here
http://programminghistorian.github.io/ph-submissions/es/lecciones/lesson-file-name-here
http://programminghistorian.github.io/ph-submissions/fr/lecons/lesson-file-name-here
http://programminghistorian.github.io/ph-submissions/pt/licoes/lesson-file-name-here

http://github.com/programminghistorian/ph-submissions/blob/gh-pages/en/translations/lesson-file-name-here
http://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/lesson-file-name-here
http://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/lesson-file-name-here
http://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/traducoes/lesson-file-name-here

**Note**
URLs for live previews have two important features:
- http without ‘s’ 
- file name without .md suffix

**Comment by DanielAlvesLABDH** [comment]
> _N.B. At the moment, the PT team use a slightly different directory structure. Their folder of ‘traducoes’ is inside the ‘licoes’, so the URLs are currently structured_:
> https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/lesson-file-name-here.md

I can change the folder structure for the PT team if needed. The logic was to differentiate between original lessons pt/licoes/originais ; translations pt/licoes/traducoes ; and published lessons pt/licoes/publicadas

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH. 

I think your system of having a sub-folder for published lessons is a really good idea. I've noticed that the @programminghistorian/french-team do this too. @hawc2 and I were chatting recently about an 'archive' folder to which lessons can be moved once they have been published. Your published folder achieves this aim, and makes a lot of sense to me. 

It might be good to adjust the directory structures though, so that the folders are not nested and we can give consistent instructions across all 4 languages. 

e.g.,

ph-submissions/pt/licoes
ph-submissions/pt/originais
ph-submissions/pt/traducoes
ph-submissions/pt/publicadas

As Alex mentions above, we are aware that making adjustments, may cause links to previews of lessons still under review to break. So we will approach this 'tidying up' task by moving only published lessons for now if that sounds okay to you?

**Comment by DanielAlvesLABDH** [comment]
That sounds great. Thanks!

**Comment by hawc2** [comment]
@anisa-hawes and I have set up a branch for cleaning up the PH-submisions repo and standardizing the organization of the language directories: https://github.com/programminghistorian/ph-submissions/tree/ReorgDirectory

Preview images, etc. are working fine in my local build. @anisa-hawes is still in the process of moving each lesson to its proper directory.

We've currently settled on a directory structure for each language as follows:

en/documentation
en/drafts/originals
en/drafts/translations
en/published/originals
en/published/translations

@programminghistorian/english-team @programminghistorian/french-team @programminghistorian/spanish-team @programminghistorian/portuguese-team, can you each review these changes for your language and let us know of any concerns or corrections that should be made? 

Next steps:
- [ ] @anisa-hawes completes moving all lessons into their proper directories
- [ ] editorial teams give feedback on any final changes
- [ ] @jenniferisasi @ZoeLeBlanc resolve/sign off on any potential technical issues (clean up ruby dependencies etc.)
- [ ] @hawc2 finalizes and pushes changes to merge with main
- [ ] @anisa-hawes @hawc2 work with editors to improve editorial onboarding documentation and improve the documentation available on the PH-submissions site for each journal

**Comment by DanielAlvesLABDH** [comment]
Dear @hawc2, thank you!
Here is my suggestion:
pt/documentacao
pt/propostas/originais
pt/propostas/traducoes
pt/publicadas/originais
pt/publicadas/traducoes

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH. What do you think about "esboços" instead of "propostas", to indicate that the proposal has been approved and the lesson is in progress?

**Comment by DanielAlvesLABDH** [comment]
@anisa-hawes I agree, I understand the meaning

**Comment by svmelton** [comment]
This is so exciting—thank you so much @anisa-hawes and @hawc2! The structure makes a lot of sense to me, I just want to flag that we'll need to update the [editor guidelines](https://programminghistorian.org/en/editor-guidelines) (I know you're also working on those!), particularly the managing editor piece on [moving the files](https://programminghistorian.org/en/editor-guidelines#3-move-the-files).

(The managing editor instructions in general are kind of a mess. @anisa-hawes let me know if you want to talk about possible edits as you're reviewing our documentation!)

**Comment by spapastamkou** [comment]
Thanks for your work @hawc2 and @anisa-hawes. For the FR repo, if current proposed naming is maintained, there are some slight changes to make to be in accordance with "leçons" (plural, feminin): `brouillon` => `brouillons` and `publie` => `publiees`
I wonder if something like `en-cours` (in progress) would fit better instead of `brouillons` but I invite the @programminghistorian/french-team to give feedback on this (maybe @datalogism if the others are too taken by more pressing tasks ??) and in general.

**Comment by anisa-hawes** [comment]
Thank you for these thoughts, @spapastamkou. I'd be happy use whichever terminology you feel is most appropriate and natural.

**Comment by InesSalome** [comment]
I agree with you @spapastamkou, `en-cours` seems more appropriate than `brouillon`.

**Comment by InesSalome** [comment]
Thanks for all this work @hawc2 and @anisa-hawes ! It's a very clear organization :)

**Comment by anisa-hawes** [comment]
Thank you for your feedback, @InesSalome! I will make this change.

**Comment by spapastamkou** [comment]
thank you @InesSalome for the feedback.

**Comment by spapastamkou** [comment]
@anisa-hawes @hawc2 I drop here that once these changes are live, we should update the links we provide in Authors guidelines for the ph-submissions repo (even check all guidelines just in case). Maybe this is noted somewhere, but it is no harm to remind so that we do not forget. cc @svmelton @DanielAlvesLABDH @rivaquiroga

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou. I hadn't realised that links within the ES, FR and PT Author Guidelines directed to specific directories within Submissions. I will make sure to update those when this work is complete.

**Comment by anisa-hawes** [comment]
Apologies for my delay in following up on this Issue.

Many of you will have noticed that [I recently re-organised](https://github.com/programminghistorian/ph-submissions/pull/453) the EN file directories within ph-submissions in collaboration with @svmelton and @hawc2.

As discussed above, we knew these changes would break links to live Lesson Previews, so my first task after merging was to
update all Preview links for lessons under active review and let all active editors, authors + reviewers know that the file directory structure has changed for EN. This all worked smoothly!

Just to outline what has changed –

There are now two sub-folders within the directory /en:

en/drafts
en/published

Nested within those, I have created:

en/drafts/originals
en/drafts/translations

en/published/originals
en/published/translations

If this is something @programminghistorian/spanish-team @programminghistorian/french-team and @programminghistorian/portuguese-team feel they would find useful, please let me know and I will proceed with preparing the changes one journal at a time via the Submissions Repo.

**Comment by anisa-hawes** [comment]
This Issue is on the agenda for our forthcoming Managing Editors' Meeting #2497. We will discuss if the changes recently implemented for EN are welcome / felt to be useful to ES, FR and PT teams. If so, I will open new Issues in Submissions to implement these changes one journal at a time. (There is no pressure for teams to standardise practices if they do not find the suggestion useful).

**Comment by anisa-hawes** [comment]
Following agreement at the Managing Editors' Meeting #2497, I have continued this work in our Submissions repo. I have started by re-organising the ES directory: see [#471](https://github.com/programminghistorian/ph-submissions/issues/471).

**Comment by anisa-hawes** [comment]
Update: I've now re-organised the FR directory too: see [#474](https://github.com/programminghistorian/ph-submissions/issues/474)

**Comment by hawc2** [comment]
@anisa-hawes just checking in on this project - there are still a couple stray folders/files from the old organization in ph-submissions repo, are we going to finalize moving everything over to the new structure? I ask because I think the next step is going to be some discussion of standardization as the English team works to improve its translation workflows based on the other language journals
