### ISSUE TITLE
User notes on Intro to Bash Commands

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#224]
https://hypothes.is/a/AVLRMKV9vTW_3w8Ly4mc Suggestion to avoid space in directory names for problem avoidance
https://hypothes.is/a/AVLRKEnQvTW_3w8Ly4k7 Clarification and how to customize a command

**Comment by ianmilligan1** [comment]
Thanks @amandavisconti - this is a fantastic workflow! Already tweaked lesson in response to these.
