### ISSUE TITLE
Blogpost to announce 3 new editors in the Spanish-speaking team 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2240]
I am opening this ticket to keep track of the blogpost I need to prepare to welcome and announce our three new editors: @nllano @isag91 and @nivaca. We are asking them to provide a short paragraph of themselves and I will take pictures from their ph_authors update or from their professional profiles online. 

@Anisa-ProgHist I am tagging you here, but the blogpost will be primarily in Spanish. We can then link it to the #2221 if it published in time (I think so), in English and Spanish. 

@rivaquiroga adding you too so you are aware on our progress on this front too, but you probably don't need to do anything other than maybe approve the last PR to publish the post.

**Comment by acrymble** [comment]
@jenniferisasi I just wanted to note that this isn't something we do consistently for all new editors. A number of editors never got a blog post. So I wonder if we should cease this practice moving forward to create consistency and reduce extra tasks?

**Comment by jenniferisasi** [comment]
🤔 we add a note of new (and retiring) editors in the newsletter so I guess we could do away with an individual blogpost. We have been doing it in FR and Es regularly, and to some extend organically, as the main editor takes it as their role to write a short note on new editors; but you are right that I haven't received those note for publication from everyone.
