### ISSUE TITLE
Updating ProgHist membership list

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2246]
We have a number of changes we need to add/remove:

Removals:

- Sylvia & Brandon & Ricardo Pimenta

Additions (to be invited by @acrymble):

- Nicolas Llano
- Isabelle Gribomont
- Nicolas Vaughan

To be complete by end of October 2021.

**Comment by nivaca** [comment]
@acrymble Hi, I think in both cases is "Nicolas" without an "h". Thanks.

**Comment by drjwbaker** [comment]
I'll edit the register of members

**Comment by drjwbaker** [comment]
Done https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Register-of-Members/2021
