### ISSUE TITLE
Translation required for (one sentence of) the Call for Papers for the JISC/TNA project

### ISSUE THREAD

**Issue by peterwebster** [programminghistorian/jekyll#2249]
We could use FR/ES/PT translations of the following text:

"The Programming Historian invites proposals of new tutorials dealing with computational analysis of large-scale digital collections, as a part of a special series developed in partnership with the National Archives and Jisc."

Could @drjwbaker assign some folk to help?

**Comment by DanielAlvesLABDH** [comment]
If it helps, here is the translation for Portuguese: "O Programming Historian convida à apresentação de novos tutoriais relacionados com a análise computacional de coleções digitais em grande escala, como parte de uma série especial desenvolvida em parceria com os National Archives e o Jisc."

**Comment by jenniferisasi** [comment]
Here it is in Spanish: 

"Programming Historian los invita a presentar propuestas para lecciones nuevas relacionadas con el análisis computacional de colecciones digitales a gran escala, como parte de la serie especial desarrollada en colaboración con los National Archives y Jisc."

**Comment by drjwbaker** [comment]
Thanks all. Looks like @spapastamkou has seen it but tagging @programminghistorian/french-team for completeness.

**Comment by drjwbaker** [comment]
For context, the call is coming out in English but it felt sensible to have at least the opening line translated into ES/FR/PT. If colleagues feel strongly that the whole call should be translated and are willing and able to do that, please say.

**Comment by jenniferisasi** [comment]
So @spapastamkou or anyone else only needs to edit: 

"Le Programming Historian lance un appel à contributions pour de nouveaux tutoriels qui traitent de l'analyse computationnelle de grands corpus de collections numériques, dans le cadre d'une série spéciale développée en partenariat avec les Archives nationales du Rayaume-Uni (The National Archives) et l'organisation Jisc."

**Comment by jenniferisasi** [comment]
@drjwbaker once @peterwebster sends me the call to add it to our blog I can have a better sense (well, and everyone else) if we need to translate it in full :)

**Comment by drjwbaker** [comment]
@peterwebster Note that the submission form is already translated at https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms (at least the sections we are using for CFP responses)

**Comment by spapastamkou** [comment]
Thanks @jenniferisasi! I edited slightly. You can copy the French text from Jennifer's comment directly, @peterwebster

**Comment by drjwbaker** [comment]
https://github.com/programminghistorian/jekyll/pull/2262
