### ISSUE TITLE
Regular ME meetings

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2255]
In a couple of recent conversations with members of the English and tech teams, I'd like to suggest that we set up standalone Managing Editor meetings, maybe on a quarterly basis. The full team meetings are useful for updates, but I think we might benefit from time to talk specifically about editorial matters. Curious to know how others feel!

**Comment by rivaquiroga** [comment]
Sounds great!

**Comment by spapastamkou** [comment]
I'm in

**Comment by svmelton** [comment]
Thanks, @spapastamkou and @rivaquiroga! @DanielAlvesLABDH if that sounds good to you, I can set up a poll for a first meeting.

**Comment by DanielAlvesLABDH** [comment]
Sorry for the late reply. I agree with the idea

**Comment by anisa-hawes** [comment]
Thank you, @svmelton. Please let me know if there's any way you'd like me to support these meetings, either by sitting in and co-ordinating minutes or by sharing a general summary of your collected notes with the broader team.

**Comment by svmelton** [comment]
@spapastamkou @rivaquiroga and I met today and decided that it would be useful for MEs to meet the week before the full project team meetings. @anisa-hawes would you be able to help us coordinate these?

We also discussed ways to improve our current editor guidelines (#2312)

**Comment by anisa-hawes** [comment]
Yes, absolutely. I'll add this task to my calendar for the months ahead.

**Comment by anisa-hawes** [comment]
As our Project Team Meetings take place every two months in late-January, late-March, late-May, late-July, late-September and late-November, I have set myself a reminder to coordinate your ME meetings for mid-January, mid-March, mid-May, mid-July, mid-September and mid-November. I'll circulate a Doodle Poll to agree the date 2 weeks ahead of each meeting.
