### ISSUE TITLE
Using PH in teaching event on November 18th - UK targeted virtual

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2256]
We've won some funding from the Institute of Historical Research in London to put on a virtual workshop for how to use PH lessons in teaching settings.

I will be the host. 

The date is not yet set, but I've spoken to @anisa-hawes and will wait until more of our lesson maintenance backlog has been closed to increase choices for educators. Aiming for something in either October or November 2021.

**Comment by jenniferisasi** [comment]
Fantastic news, @acrymble! 

Just fyi, Brandon and I are going to be using some lessons for what we've called "PH Bookclub" for ACH, we will work on a lesson together on Zoom, so it's more showing people how to learn from it, also in Oct and Nov.

**Comment by acrymble** [comment]
Plan tentatively is to host this late morning on 18 November.

**Comment by amsichani** [comment]
@acrymble @anisa-hawes more than happy to support/attend if needed!

**Comment by acrymble** [comment]
Will launch the sign up 1 month in advance (so 18th October). 

I will be looking for a @programminghistorian/spanish-team member to help translate the materials (we can pay for this). So if any Spanish speaking team members are interested please let me know (@rivaquiroga I don't think it can be you because of your trustee role).

**Comment by jenniferisasi** [comment]
@acrymble I could do it if no one else is available.

**Comment by jenniferisasi** [comment]
Hi @acrymble any update on this? Wondering if you still need translation since October 18th is coming up pretty fast 😬

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi! The signup launches on October 18th, but the event itself is not until November 18th!

**Comment by jenniferisasi** [comment]
Ah, @anisa-hawes thanks! I thought translation was also needed for the registration period, so no problem :) more time then.
