### ISSUE TITLE
Portuguese version not mentioned in 'Contribute' pages in French, Spanish and English

### ISSUE THREAD

**Issue by isag91** [programminghistorian/jekyll#2258]
I was reading the [/contribuciones](https://programminghistorian.org/es/contribuciones)  page of the Spanish site as part of my onboarding and noticed that it does not mention Portuguese alongside French and English.
The Portuguese version is also omitted from the [French](https://programminghistorian.org/fr/contribuer) and [English](https://programminghistorian.org/en/contribute) equivalent pages.
I'm happy  to make the changes, but wanted to check first if there might be a reason to wait or something I'm not aware of (since I'm brand-new to the PH team).

**Comment by DanielAlvesLABDH** [comment]
@isag91 I believe this was mentioned in another ticket a couple of weeks ago, but not sure if it was @jenniferisasi to mentioned it or othwr colleague

**Comment by rivaquiroga** [comment]
Thanks, @isag91! @spapastamkou identified the same problem on the About page ([#2217](https://github.com/programminghistorian/jekyll/issues/2217)). But it seems we missed the mention on Contributions!
It would be great if you can make the changes 🚀
