### ISSUE TITLE
ProgHist Ltd Board of Trustees Meeting: Thursday 21st October 2021

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2266]
## ProgHist Ltd Board of Trustees Meeting October 2021 **Date TBC**

Date: Thursday 21st October 2021. Thank you for confirming your availability via this [Doodle Poll](https://doodle.com/poll/hsmkh8fs4fagrud6?utm_source=poll&utm_medium=link)
Time: [13:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20210407T1300)

@acrymble  will initiate our call.
Meeting link: https://ucl.zoom.us/j/93457432968

Chair: @acrymble
Secretary: @anisa-hawes  
Members: @drjwbaker @svmelton @spapastamkou @amsichani @rivaquiroga
Minutes of the last meeting: [2021-07_ProgHistLtd-BoD.docx](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/07-2021/2021-07_ProgHistLtd-BoD.docx).
Papers: [A) Goal 3 Update - IPPs](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/10-2021/Programme3-update-10-2021.pdf), [B) Business Plan 10-2021](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/10-2021/ProgHist%20Business%20Plan%202021-10.docx), [C) Cashflow Dashboard](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Finances/cashflow/2020-21/2021-10_ProgHist_CashFlowDashboard.xlsx)

Board of Trustees Meeting: Thursday 21st October 2021, Time: 13:00 UTC

---

Hello all,

**I'm creating this issue so that we can begin to draft our agenda for October's BoT meeting.**
Please feel free to edit this agenda, and add further Items for discussion below

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf),  I'd like to ask that new agenda Items are added **no later than Thursday 7th October** so that all attendees have sufficient  time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions on the 21st.  

### Agenda

1. Apologies  
2. Approval of Minutes from last meeting & actions status.
3. ProgHist Directors administration (e.g., changes of address)
4. Finance update & Business administration @drjwbaker 
4b. Adding another signatory to the bank account. Are any of the existing Directors willing/able to do this? @drjwbaker 
5. Goal 1 - phased end to volunteering @amsichani 
6. Expanded Risk Register - project wide @acrymble / @anisa-hawes  
7. 'need for a "technical editor"'  https://github.com/programminghistorian/jekyll/issues/2223#issuecomment-930558204 @svmelton 
8. Goal X - implications of becoming a charity in the UK https://github.com/programminghistorian/jekyll/issues/2276
9. Any Other Business
10. Agree date of next meeting

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by drjwbaker** [comment]
Note I no longer have a institutional Zoom account. So if I set up the call it'll be on Soton Teams. Or we can use something easy and broswer based like [jitsi](https://meet.jit.si/).

**Comment by anisa-hawes** [comment]
Ah! Sorry, @drjwbaker! Jitsi is usually good, and I would be happy to initiate this if my Google mail account is set up by then (to schedule a Jisti meet in advance, I believe it is necessary to integrate with either a Gmail or Outlook calendar). Alternatively, perhaps @acrymble could initiate our call?

**Comment by acrymble** [comment]
I can set up a zoom @Anisa-ProgHist if you confirm the date when you know more.

**Comment by drjwbaker** [comment]
@anisa-hawes per https://github.com/programminghistorian/jekyll/issues/2276 this is now a trustees meeting, so I've changed the header and need to change some of the blurb above that refer to our articles of association.

I've also created a template for board of trustees meetings here, to be used from now on https://github.com/programminghistorian/project-and-business-archive/tree/master/charity/Board-of-Trustees-Meetings/2021

Any questions, please ask.

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker! I've saved the template and can work from this going forwards. Maria José and I decided to minute  the Project Team meetings in Markdown, rather than in Word. Maybe we could chat about the best approach for the BoT meetings, but I'm happy to do either.

**Comment by acrymble** [comment]
@rivaquiroga @svmelton @spapastamkou @amsichani @drjwbaker @anisa-hawes 

I have uploaded the three papers for the meeting under "Papers" in the agenda above. I've done this 2 weeks before the meeting so that you have time to review them in advance. We won't necessarily be going through each one page by page, but they all contain information you should be familiar with as trustees.

**Comment by anisa-hawes** [comment]
Dear all,

I have added the minutes of our October Board of Trustees Meeting to our Project and Business repository. You can review them here: https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Board-of-Directors-Meetings/2021/10-2021/BoT_minutes.md. These minutes are formatted in Markdown for your convenience. 

As before, please write me a note if you feel I have missed any key points or mis-represented something you said. I'm more than happy to make an adjustment. I'll create a watermarked PDF when the minutes have been approved by you all. 

Thank you.

Anisa

**Comment by drjwbaker** [comment]
@anisa-hawes for info, I've moved these docs to the `Charity` directory where BoT minutes/papers should go from now on https://github.com/programminghistorian/project-and-business-archive/tree/master/charity/Board-of-Trustees-Meetings/2021/10-2021

**Comment by anisa-hawes** [comment]
A PDF of the Approved minutes from this meeting have been uploaded to the Charity sub-directory of our Project and Business Archive. You can find it here: <https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2021/10-2021/BoT-21.10.22.pdf>

**Comment by anisa-hawes** [comment]
A PDF of the Approved minutes from this meeting have been uploaded to the Charity sub-directory of our Project and Business Archive. You can find it here: [https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2021/10-2021/BoT-21.10.21.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2021/10-2021/BoT-21.10.21.pdf)

**Comment by drjwbaker** [comment]
I'm getting a 404 error.

**Comment by drjwbaker** [comment]
this works https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2021/10-2021/BoT-21.10.21.pdf

**Comment by drjwbaker** [comment]
(which is weird as they are the same link?!)

**Comment by anisa-hawes** [comment]
Apologies, @drjwbaker. I deleted my original comment because I mistakenly named the file with the year 2022! 
So I think the links are the same, and both correct.

I've updated the name of the PDF and re-uploaded it.
