### ISSUE TITLE
User notes on using SPARQL to access...

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#227]
https://hypothes.is/a/AVLH7aAMvTW_3w8Ly19w User notes on how to customize command
https://hypothes.is/a/AVK7W2hnvTW_3w8Lyx3i Suggested clarification of syntax

**Comment by mdlincoln** [comment]
Neat feedback ideas! I'll be able to take a look at these next week.

**Comment by mdlincoln** [comment]
I think this can be closed based off of #233
