### ISSUE TITLE
PT -- Review of author guidelines

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/jekyll#2274]
Olá a todos,

A pedido de @drjwbaker e @DanielAlvesLABDH, estou a rever as [Directrizes para Autores](https://programminghistorian.org/pt/directrizes-autor#b-directrizes-espec%C3%ADficas-de-estilo) do PH em Português, com vista a consolidá-las e corrigi-las quando necessário. Entretanto, deixo esta *issue* aberta para identificar as mudanças mais relevantes, ou discutir algumas questões em particular.

Se houver algum aspecto que achem que deva fazer parte das directrizes em Português (em particular, alguma coisa que diga respeito ao contexto linguístico), deixem um comentário aqui -- tentarei incluir as sugestões na minha revisão.

Um abraço a todos,
Tiago.

***

*Issue summary in English*
I'm reviewing the Portuguese author guidelines and leaving this issue open for the moment to note and discuss any major changes; I'm also asking the community for improvement suggestions.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela ajuda Tiago. Qualquer dúvida, estou disponível! Abraço

**Comment by tiagosousagarcia** [comment]
Depois da primeira ronda de revisões, algumas questões que merecem discussão (mais ou menos na ordem em que as encontrei):
- [ ] code -> código ou código-fonte?
    Talvez seja só eu, mas 'código' por si só soa-me mal (quando diz respeito a código computacional, claro)
- [ ] referências culturais -> localizadas aos contextos lusófonos? (i.e., Beatles, Kleenex)
    Valerá a pena substituir os exemplos por outros que sejam mais problemáticos em Portugal ou no Brasil? (ao contrário dos Beatles que colocam todos os países lusófonos em pé de igualdade) -- por exemplo, Caetano Veloso, Amália Rodrigues ou Cesária Évora, que podem ser reconhecidos por parte da comunidade de língua portuguesa, mas não necessariamente por todos;
- [ ] vocabulário PT/BR
    O exemplo que ilustra o uso de marcas comerciais lembrou-me que talvez seja necessário fazer uma nota específica acerca das diferenças de vocabulário entre Português Europeu e Brasileiro: por exemplo, o uso de 'Kleenex' é mais claro para mim do que 'lencinho' (ou, provavelmente, do que 'lenço de papel' para outros). Algo simplesmente indicando aos autores que será bom ter em conta (e estar atento a potenciais problemas) as diferenças de vocabulário;
- [x] Definição de *titlecase* em Português
    A definição que temos actualmente pareceu-me um pouco incerta: 'usar maiúsculas para iniciar as palavras' -- as definições em Inglês não são muito melhores, geralmente baseando-se em 'major words'. O que propus peca talvez por ser demasiado restrito: '**Em títulos**: cabeçalhos e títulos de livros devem usar maiúsculas para iniciar nomes, pronomes, verbos, advérbios e adjetivos, mas não artigos e preposições';
- [ ] títulos de organizações internacionais
    Talvez valha a pena indicar quando (ou quando não) usar nomes e siglas de organizações internacionais em Português -- por exemplo NATO vs OTAN. Talvez quando a organização tenha um nome oficial em Português? Por exemplo, a União Europeia tem, claro, mas a FIFA não (ou, caso ainda mais complicado, quando a sigla é diferente do nome oficial em Português).
- [ ] Acordo ortográfico
   Já estou fora de Portugal há algum tempo, por isso não faço idea se mencionar o uso do acordo ortográfico ainda é relevante; ainda menos ideia noutros contextos.
- [x] Regularização de alguns termos (equipe/equipa | o URL / a URL, uso da segunda pessoa)
    Tenho regularizado alguns usos que aparecem mistos (como equipa e equipe -> equipe ou **o** URL e **a** URL -> **o** URL), e o uso da segunda pessoa, de acordo com as regras de estilo que propomos (por exemplo 'Escrever para alguém ...' -> 'Escreva para alguém ...'

**Comment by tiagosousagarcia** [comment]
Pull request #2286 adiciona as correções sugeridas no ultimo ponto acima

**Comment by DanielAlvesLABDH** [comment]
> 
> 
> Depois da primeira ronda de revisões, algumas questões que merecem discussão (mais ou menos na ordem em que as encontrei):
> 
>     * [ ]  code -> código ou código-fonte?
>       Talvez seja só eu, mas 'código' por si só soa-me mal (quando diz respeito a código computacional, claro)
Acho que chegámos a falar sobre isso e a equipe acabou por decidir manter código, mas talvez o @josircg tenha outra ideia
> 
>     * [ ]  referências culturais -> localizadas aos contextos lusófonos? (i.e., Beatles, Kleenex)
>       Valerá a pena substituir os exemplos por outros que sejam mais problemáticos em Portugal ou no Brasil? (ao contrário dos Beatles que colocam todos os países lusófonos em pé de igualdade) -- por exemplo, Caetano Veloso, Amália Rodrigues ou Cesária Évora, que podem ser reconhecidos por parte da comunidade de língua portuguesa, mas não necessariamente por todos;
Concordo com a ideia e a opção por Beatles. Já Kleenex, em PT é apenas uma marca de lenços de papel. Nesse caso tem valores diferentes em PT e em BR
> 
>     * [ ]  vocabulário PT/BR
>       O exemplo que ilustra o uso de marcas comerciais lembrou-me que talvez seja necessário fazer uma nota específica acerca das diferenças de vocabulário entre Português Europeu e Brasileiro: por exemplo, o uso de 'Kleenex' é mais claro para mim do que 'lencinho' (ou, provavelmente, do que 'lenço de papel' para outros). Algo simplesmente indicando aos autores que será bom ter em conta (e estar atento a potenciais problemas) as diferenças de vocabulário;
Não sei se a resposta que dei acima ajuda aqui?
> 
>     * [ ]  Definição de _titlecase_ em Português
>       A definição que temos actualmente pareceu-me um pouco incerta: 'usar maiúsculas para iniciar as palavras' -- as definições em Inglês não são muito melhores, geralmente baseando-se em 'major words'. O que propus peca talvez por ser demasiado restrito: '**Em títulos**: cabeçalhos e títulos de livros devem usar maiúsculas para iniciar nomes, pronomes, verbos, advérbios e adjetivos, mas não artigos e preposições';
Concordo
> 
>     * [ ]  títulos de organizações internacionais
>       Talvez valha a pena indicar quando (ou quando não) usar nomes e siglas de organizações internacionais em Português -- por exemplo NATO vs OTAN. Talvez quando a organização tenha um nome oficial em Português? Por exemplo, a União Europeia tem, claro, mas a FIFA não (ou, caso ainda mais complicado, quando a sigla é diferente do nome oficial em Português).
Poderíamos dar alguns exemplos, mas isso vai variar muito e teríamos sempre de deixar em aberto para que os autores analizarem o contexto, acho
> 
>     * [ ]  Acordo ortográfico
>       Já estou fora de Portugal há algum tempo, por isso não faço idea se mencionar o uso do acordo ortográfico ainda é relevante; ainda menos ideia noutros contextos.
Aqui é algo que realmente não tenho a certeza ou talvez não queira dar uma opinião definitiva. Eu não uso o Acordo Ortográfico, mas há colegas PT que usam. No BR não usam, acho. @programminghistorian/portuguese-team o que acham?
> 
>     * [x]  Regularização de alguns termos (equipe/equipa | o URL / a URL, uso da segunda pessoa)
Alguns termos foram acordados entre as equipes PT e BR. Vou enviar um mini-glossário que fizemos para esse efeito.
>       Tenho regularizado alguns usos que aparecem mistos (como equipa e equipe -> equipe ou **o** URL e **a** URL -> **o** URL), e o uso da segunda pessoa, de acordo com as regras de estilo que propomos (por exemplo 'Escrever para alguém ...' -> 'Escreva para alguém ...'
Ver resposta anterior

Caro @tiagosousagarcia este trabalho de revisão está excelente. Muito obrigado!

**Comment by DanielAlvesLABDH** [comment]
Reparei agora que não tenho o teu email @tiagosousagarcia

**Comment by tiagosousagarcia** [comment]
> Reparei agora que não tenho o teu email @tiagosousagarcia

É o mesmo username que no GitHub [at]gmail.com :)

**Comment by acrymble** [comment]
@tiagosousagarcia sorry my Portuguese is rusty. The ProgHist team is aiming to get copyediting set up in Portuguese soon, and I think, but I'm not sure, that's what you're helping to do here by establishing the expanded author guidelines as we did in other languages. Is that right? I ask so I can report to the Proghist team at our upcoming meeting.

**Comment by tiagosousagarcia** [comment]
@acrymble yes, I believe so -- essentially, I've been reviewing the author guidelines in order to make them more pertinent to a Portuguese-speaking context (as well as some minor copyediting for typos and regularisations).

**Comment by DanielAlvesLABDH** [comment]
Caros amigos/as da @programminghistorian/portuguese-team vanos avançar com estas alterações nas directrizes para autores. Alguém mais quer contribuir, em especial nas dúvidas levantadas por mim no comentário [aqui](https://github.com/programminghistorian/jekyll/issues/2274#issuecomment-923295307)?

**Comment by josircg** [comment]
Olá Daniel, fiz uma revisão geral e só tenho 2 pequenos comentários a fazer: 

1) eu prefiro "código-fonte". Inclusive, meus amigos de Portugal confirmaram que o termo usado é esse. 

2) eu procuro sempre usar o acordo ortográfico - acho que poderíamos colocar que deve ser utilizado preferencialmente mas não obrigatório.

**Comment by ericbrasiln** [comment]
@DanielAlvesLABDH Como parte das análises que realizei para a pesquisa no Lab, eu tenho algumas contribuições a fazer. Na próxima semana vou me dedicar a isso, e incluo aqui. 

E concordo com os comentários do @josircg

**Comment by DanielAlvesLABDH** [comment]
Obrigado a ambos! Sendo assim, vamos aguardar os contributos do @ericbrasiln e depois avançar.

**Comment by joanacvp** [comment]
Olá a todos,
Em conversa com a Anisa esta sugeriu que criássemos uma Wiki para disponibilizar o glossário. Podemos ir alimentando e poderá ser uma forma de centralizar as questões linguísticas e de terminologia do PT-BR (e de não perdermos a informação). 
Acho também que devíamos acrescentar que, por exemplo, no caso de softwares que não têm versão PT, costumamos colocar entre parênteses o que significa o local onde o usuário deve clicar em português para lhe ser mais familiar.

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for your energy to take this Issue forwards. I've created [a Wiki page](https://github.com/programminghistorian/jekyll/wiki/Achieving-Sustainability-Agreed-terminology-PH-em-portugu%C3%AAs), where you can start to rebuild your shared glossary. Thank you for this suggestion, @joanacvp!

With something like the use of brackets to clarify technical terms in English (for example, elements of an interface) I think this could be added directly to Directrizes para Autores. The French Team have included something similar in their guidelines.

**Comment by joanacvp** [comment]
Hello everyone. I have just filled the Wiki page with our glossary and other notes. We can add new terms anytime. It is a work in progress.
@ericbrasiln will add it to the Author Guidelines. Thank you @ericbrasiln!

**Comment by DanielAlvesLABDH** [comment]
@joanacvp and @ericbrasiln many thanks for this. Do you think it could also be useful to include a reference in the "Directrizes para Tradutores" page?

**Comment by ericbrasiln** [comment]
Hi @DanielAlvesLABDH 
I think it's a good idea.
I have added the links on both pages. The PR is #2823 

But there was an error when github actions was checking for deploy. The error was in an external link in the file [`es/investigacion.md`](https://github.com/programminghistorian/jekyll/blob/gh-pages/es/investigacion.md):

```
/_site/es/investigacion.html
  *  External link http://researchprofiles.herts.ac.uk/portal/files/10476604/Blip_2016_Autumn_2016_Final_Autumn_2016.pdf failed: 404 No error
```
The link is in:

```
* Adam Crymble, ['Identifying and Removing Gender Barriers in Open Learning Communities: The Programming Historian'](http://researchprofiles.herts.ac.uk/portal/files/10476604/Blip_2016_Autumn_2016_Final_Autumn_2016.pdf), _Blended Learning in Practice_, (2016), 49-60. [[pre-print pdf](/researchpapers/openLearningCommunities2016.pdf)]
```

If we click in the [link](https://researchprofiles.herts.ac.uk/portal/files/10476604/Blip_2016_Autumn_2016_Final_Autumn_2016.pdf) the page is not found. The problem is repeated in all other languages.

@anisa-hawes or @GeeAlmeida could you take a look?

**Comment by DanielAlvesLABDH** [comment]
Hi @ericbrasiln, I noticed the error after my revision. I think the correct link for that file is https://www.herts.ac.uk/__data/assets/pdf_file/0016/138013/Blip-2016-Autumn-2016-Final-Autumn-2016.pdf

**Comment by ericbrasiln** [comment]
Hi everyone,
@anisa-hawes fixed the links and the PR has already been merged.
The information about the wiki page is online.
Thanks @anisa-hawes !!  😉

**Comment by anisa-hawes** [comment]
Hello @ericbrasiln and @joanacvp, 

Have all the recommendations within this Issue now been actioned? If so, we can close it 🙂

**Comment by anisa-hawes** [comment]
These updates to PT Author Guidelines are complete, and [a Wiki page setting out Agreed terminology for _PH em português_](https://github.com/programminghistorian/jekyll/wiki/PH-em-portugu%C3%AAs) is in place. This page represents part of a series of guideline documents we are developing to support editors and copyeditors in their work.
