### ISSUE TITLE
Implications of becoming a Charity in the UK

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2276]
In prepartion for becoming a Charity (which is going well, see https://github.com/programminghistorian/jekyll/issues/1671#issuecomment-919862049), @acrymble @rivaquiroga and I read through document produced by the Charity Commission (UK) to better understand the roles of the ProgHist Ltd Directors as this role morphs into being Charity Trustees (side note, the Ltd will still exist simulateously, so we will be both Directors and Trustees, but it is convention to refer to role for both as 'Trustee' once we are a charity in the UK).

The document in called called 'The essential trustee': available [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf) with a visual summary [here](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/544220/Jigsaw.pdf). We identified a number of points that need attention, which are listed below.

- [x] "A registered charity with an income over £10,000 in its last financial year must state that it’s a registered charity on any fundraising documents and on many of its financial documents, including cheques, invoices and receipts. This includes electronic documents such as emails and websites. You don’t have to state the charity’s registration number, but it’s good practice to do so."
    - [x] @drjwbaker to share email footer with trustees, and edit footer on shared gmail.
    - [x] @drjwbaker to update invoicing docs
    - [x] @drjwbaker to send @anisa-hawes revised footer text for Board of Trustees meeting agendas/minutes.
    - [x] @drjwbaker to propose changes to website text: footer, [funding and ownership](https://programminghistorian.org/en/about#funding--ownership), [ipp](https://programminghistorian.org/en/ipp)
- [x] "As someone responsible for governing a charity, you [..] should give enough time, thought and energy to your role, for example by preparing for, attending and actively participating in all trustees’ meetings". This means we need to ensure prep time for meetings, such that documents that need attention in Trustees meetings are prepared sufficiently in advance.
    - @anisa-hawes: can this be solved by having a deadline for new agenda items for Trustees meetings (what are currently Directors meetings https://github.com/programminghistorian/jekyll/issues/2266)?
- [x] Trustees must "avoid putting yourself in a position where your duty to your charity conflicts with your personal 
interests or loyalty to any other person or body". This means that we need to ensure MEs who are Trustees don't act as or feel representatives of their publications when performing the role of Trustee.
    - @rivaquiroga: I saw that the MEs plan to meeting from time to time. Can you have a discussion about this point at that meeting?
 - [x] Section 5 talks about how to 'Comply with your charity’s governing document and the law'. We agreed that Trustees should read the document - currenty [here](https://github.com/programminghistorian/project-and-business-archive/tree/master/charity/application/2021_ongoing) but I'll move once the charitable application status is complete.
     - @anisa-hawes: I think this needs to somehow appear on the agenda for Trustees meetings so that we remember to do it annually, starting once we become a charity. Agree?
 - [x] We currently have one class of member - 'Member (Editorial Board)' - details of which are listed on the latest [Register of Members](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Register-of-Members/2021/2021-08_ProgHistLtd_Register-of-Members.docx).
     - @drjwbaker takes an action here to clarify what changes with membership once a charity.
 - [x] We should consider ensuring that our fundraising complies with the [Fundraising Regulator](https://www.fundraisingregulator.org.uk/).
     - (updated 21/10/2021) @acrymble notes that we comply, but no need becoming a member.
- [x] A charity cannot pay trustees (except for expenses incurred being a trustee), so once we are a charity the trustees cannot do any paid work for the project (e.g. copyediting).
     - @drjwbaker: add an action to https://github.com/programminghistorian/jekyll/issues/2266 to ensure Trustees are aware.
- [ ] Section 7.7 includes a series of points on staff and volunteers, and how they differ, e.g. "You must ensure that [..] volunteers are clearly distinct from employees in terms of responsibilities and rights; for example by not requiring volunteers to work set hours, nor paying them more than expenses they actually incur". It also details how we must ensure that volunteers work safely, know who to report to, and have role descriptors.
     - We need a brief role descriptor for our volunteers, that is clear on what voluntary work is and is not for PH. For example, is a volunteer is going to a conference and giving a talk about their work on PH, this would ideally as part of their work for their employer, otherwise PH is responsible for their safety (insurnace et al) at and travelling to/from that conference. @acrymble: you mentioned this may be connected to something @mariajoafana & @anisa-hawes are working on, but I can't locate the issue in question (or maybe I've misremembered!)

**Comment by rivaquiroga** [comment]
@drjwbaker, sure. We will discuss it at that meeting.

**Comment by acrymble** [comment]
@drjwbaker On 7.7, it was just the "Longer Term Objectives" google doc conversation on #2223, which may affect the structure of the "Project Team" moving forward

**Comment by drjwbaker** [comment]
Thats the one. Thanks.

**Comment by drjwbaker** [comment]
Now we are a charity (!!!) I've added to this list the following:

> @drjwbaker to propose changes to website text: footer, funding and ownership, history of the project

If there are other parts of the website I need to propose changes to, do please say.

**Comment by drjwbaker** [comment]
> 
> 
> Now we are a charity (!!!) I've added to this list the following:
> 
> > @drjwbaker to propose changes to website text: footer, funding and ownership, history of the project
> 
> If there are other parts of the website I need to propose changes to, do please say.

Realised the IPP page needs attention.

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker! 

- In terms of a deadline for adding new items to our Trustee meetings agenda, do you think 14 days ahead would be sufficient?

- I'm happy to make a note that each September, we re-share Section 5 of the Essential Trustee Guidance document and add an item to that month's BoT agenda for a discussion about any adjustments that we may need to make to our working practices.

**Comment by drjwbaker** [comment]
Yes. And many thanks.

**Comment by acrymble** [comment]
>> We should consider ensuring that our fundraising complies with the Fundraising Regulator.

I have read their guidance. We are already compliant in most areas. I will send a separate email to those with relevant fundraising responsibilities on the specifics. But nothing major needs to change.

**Comment by anisa-hawes** [comment]
Hello @drjwbaker. You mentioned in the BoT meeting that very little has changed in terms of what it means to be a Member of the Editorial Board. Is there anything you'd like me to add to the Minutes to clarify this? 

I've also added a note in the Minutes to reflect a comment you made about how we distinguish the roles/our expectations of volunteers vs employees. Is there further action to take here? Let me know if I can help you to complete these tasks.

**Comment by drjwbaker** [comment]
> Hello @drjwbaker. You mentioned in the BoT meeting that very little has changed in terms of what it means to be a Member of the Editorial Board. Is there anything you'd like me to add to the Minutes to clarify this?

A bit of background. We agreed some time back to have one class of membership when we became an Ltd: "Member (Editorial Board)". This is what you see in the list of members. The action now is to move this membership over to the charity, though I just haven't found the time to properly go back to the relevant bit of '[The Essential Trustee](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf)' and figure it out.

> I've also added a note in the Minutes to reflect a comment you made about how we distinguish the roles/our expectations of volunteers vs employees. Is there further action to take here? Let me know if I can help you to complete these tasks.

This refers to section 7.7 of the Essential Trustee, also described above https://github.com/programminghistorian/jekyll/issues/2276#issue-996899862 In short, I think we need a *brief* generic role description for voluntary work (what it is, what it is not). I wondered if this could align with the Project Team structure work you've been doing.

**Comment by acrymble** [comment]
I don't believe the charity has any volunteers. It only has trustees and staff (though it did have some summer students back in June, briefly).

The volunteers are volunteers of the Project Team.

**Comment by drjwbaker** [comment]
Blurred lines.

Are team members using Charity money to run outreach https://github.com/programminghistorian/jekyll/issues/2213 not volunteering for the Charity?

As we get used to being a charity I'd lean towards at least defining the distinction between paid and voluntary labour as set out by the guidance (e.g. generic: volunteers do not have set hours, are assumed to be responsible for their own equipment use; specific to us: for insurance purposes, speaking about PH assumed to be for their employer / in personal capacity not for PH)

**Comment by acrymble** [comment]
I don't agree, just like me spending IHR money doesn't make me a volunteer of the IHR.

We need to be careful here. A volunteer is someone operating under the direction and with the permission of someone within the charity. We don't direct the global lead, for example, so she isn't our volunteer.

**Comment by anisa-hawes** [comment]
Thank you @drjwbaker. I am meeting with Maria José next week and will raise these questions. 

Some thoughts: It sounds as though we could usefully integrate the descriptions of voluntary work and staff work into the [Privileges-and-Responsibilities-of-Membership](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership) page of the Wiki. Reviewing this, I think we also need to update some of the other Wiki pages to reflect our change of status. For example: https://github.com/programminghistorian/jekyll/wiki/Service-Agreement-Publisher-and-Publications. 

I'm happy to take a look at the Essential Trustee document with you.

**Comment by drjwbaker** [comment]
> 
> 
> I don't agree, just like me spending IHR money doesn't make me a volunteer of the IHR.
> 
> We need to be careful here. A volunteer is someone operating under the direction and with the permission of someone within the charity. We don't direct the global lead, for example, so she isn't our volunteer.

Okay. But we are a publisher. We provide loads of guidance for editors https://github.com/programminghistorian/jekyll/wiki And we call people volunteers https://programminghistorian.org/en/project-team When - say Alex - is working with Anisa on implementing permacc, is he working for himself, the project, or the Ltd?

I appreciate that the Ltd was designed to administer the legal and financial aspects of our work. We've paid attention to that line and it as worked well. And I don't want the Ltd to colonise our community of practice. But some of this is about optics. And I'm pretty sure from the outside it would be assumed that people doing things for PH for zero remuneration are volunteers doing voluntary work for a charity. Any other answer feels like an outsourcing legal technicality.

**Comment by acrymble** [comment]
I agree our structure at the moment makes this very problematic. That's why I've been pushing for ProgHist ltd to replace the Project Team as the administrator of day-to-day publishing activities in their entirety. That clarifies these legal issues, but hasn't been popular so far.

**Comment by drjwbaker** [comment]
This has been a really helpful to and fro. I suggest we a) keep an eye on where work is happening and b) draw up a *brief* doc to say what we think a volunteer for the Charity is (which excludes editorial work).

**Comment by drjwbaker** [comment]
> > Hello @drjwbaker. You mentioned in the BoT meeting that very little has changed in terms of what it means to be a Member of the Editorial Board. Is there anything you'd like me to add to the Minutes to clarify this?
> 
> A bit of background. We agreed some time back to have one class of membership when we became an Ltd: "Member (Editorial Board)". This is what you see in the list of members. The action now is to move this membership over to the charity, though I just haven't found the time to properly go back to the relevant bit of '[The Essential Trustee](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf)' and figure it out.

I had a chance to look at this, and this is now resolved: see https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Register-of-Members/2021 (in short, updated Register of Members template, changed article references, checked membership type fits [our articles](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/application/2021_complete/pro101%20articles.doc), which it does.

**Comment by anisa-hawes** [comment]
Hello @drjwbaker. I've drafted a brief text, which I think might provide a good start towards fulfilling Section 7.7. I have adapted this from the [Privileges and Responsibilities of Membership](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership) page of the Wiki. Let me know what you think. 

-- 

What does being a volunteer for _Programming Historian_ mean?

Most of our Members participate in the project on a voluntarily basis. As a volunteer, it’s very important that you are not asked to take on more than you have time or energy to commit to. 

We ask that you: 

- contribute a minimum average of one half-day per month to the project (and let us know if you need to [step away from the project for a defined period](https://github.com/programminghistorian/jekyll/wiki/Checklist-for-Sabbaticals))
- engage actively in any roles that you hold
- join us at our Project Team Meetings (occurring once every two months) regularly, or send us apologies in advance
- speak up: ask questions, express any concerns by contacting [one of our Managing Editors](https://programminghistorian.org/en/project-team) or our [ombudsperson Dr Ian Milligan](mailto:i2milligan@uwaterloo.ca)
- respect our shared code of ethics (defined in our [Anti-Harassment Policy](https://programminghistorian.org/en/editor-guidelines#anti-harassment-policy) and our [commitment to Safe Spaces](https://programminghistorian.org/posts/PH-commitment-to-diversity))
- do your best for the project at all times

In return, we:

- invite you to participate in all decisions made by the Project Team, through Github or Project Team Meetings
- offer you the privilege of publicly declaring yourself a member of the Project Team, and using that association in any job applications, grant applications, social media, public facing profiles, etc., as long as it is not done in a manner that puts the reputation of our project at risk, or that we have specifically requested you cease
- give you the right to [step away from the project for a defined period](https://github.com/programminghistorian/jekyll/wiki/Checklist-for-Sabbaticals) if you need to
- will protect your right to be treated fairly and with respect in all matters related to the project

--

I realise that you may want to add some specific exclusions/inclusions. We could add a set of further bullets to clarify, e.g.,

We are unable to offer:

- any payment beyond [reimbursement of specific, agreed expenses](https://github.com/programminghistorian/jekyll/wiki/Spending-Requests-and-Reimbursement)
- any travel or health insurance

**Comment by drjwbaker** [comment]
Many thanks for drafting @anisa-hawes. I think that does the trick. @acrymble: would having wording like this that we could point to as a 'description of our voluntary roles' ease the concerns you've expressed above?

**Comment by acrymble** [comment]
If someone fails to meet those standards, who has to have the conversation with them about moving on? If that's me, then no I don't agree to this because it's thankless and emotionally exhausting. If it's someone in the Project Team, then I don't think it matters what I think.

Editors aren't ProgHist volunteers. They're our members. We're responsible to them, not the other way around.
Project team leads aren't our volunteers. They're volunteers of the Project Team. They're our colleagues, not our volunteers.
If those team leads ave volunteers then they're their volunteers.
Trustees aren't volunteers in a legal sense.

So who are the volunteers this refers to?

**Comment by anisa-hawes** [comment]
Let's chat, Adam. I think I have mis-understood the distinction between volunteers of the Project Team and volunteers of the Editorial Board. 

I'm also happy to draft a further section about the procedures for how we remove members who don't meet those requirements/fulfil their responsibilities.

**Comment by drjwbaker** [comment]
> If someone fails to meet those standards, who has to have the conversation with them about moving on? If that's me, then no I don't agree to this because it's thankless and emotionally exhausting. If it's someone in the Project Team, then I don't think it matters what I think.

I don't think this was intended as a job for you. A community of practice should maintain its own community standards. This isn't a requirement. It is a polite ask.

> Editors aren't ProgHist volunteers. They're our members. We're responsible to them, not the other way around.
> Project team leads aren't our volunteers. They're volunteers of the Project Team. They're our colleagues, not our volunteers.
> If those team leads ave volunteers then they're their volunteers.
> Trustees aren't volunteers in a legal sense.
> So who are the volunteers this refers to?

I refer back to my point at https://github.com/programminghistorian/jekyll/issues/2276#issuecomment-953712508.

First, we call people volunteers on our [About page](https://programminghistorian.org/en/project-team). Second, in terms of optics, I'm pretty sure from the outside it would be assumed that people doing things for PH - whatever part of it - for zero remuneration are volunteers doing voluntary work for a charity (with the exlucusion of Trustees as that is legally seperate).

All I'm trying to do here is meet our legal requirements..

> "You must ensure that [..] volunteers are clearly distinct from employees in terms of responsibilities and rights; for example by not requiring volunteers to work set hours, nor paying them more than expenses they actually incur" [Section 7.7 of Essential Trustee](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf)

..and I think @anisa-hawes's helpful suggestion to massage some existing text on rights and responsibilities helps us towards that.

It is imperfect, but I don't think it is as big an issue as you perhaps think it is.

**Comment by acrymble** [comment]
It's a big issue for me because if something goes wrong, it will be up to me to spend the time and energy to handle it. I'm not willing to be responsible everyone on the project. Our project structure is very clear and disseminated in our business plan among other places. ProgHist's remit is not for the entire project, so everyone who engages with PH is not a ProgHist volunteer.

Under our current structure everyone is responsible to the Project Team of the Programming Historian, and @mariajoafana is the chair of that (under the title Project Manager at Large).

If we want to change our structure, that conversation has to start with the Project Team, whose volunteers make up Programming Historian.

**Comment by drjwbaker** [comment]
Adam. I think we are speaking past each other. I am not proposing changing the project structure. I am acknowledging the reality of being a charity in the UK and that Charity Commission asks us to make clear the difference between paid work and voluntary work. We already basically have this text https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership. What @anisa-hawes has done is integrate some useful additional clarifications, e.g. around insurance. On my read, this will enable us to continue our slight fudge position that everyone who engages with PH is not a volunteer for the charity.

And I'm not sure why you assume that it is up to you to put time and energy into every problem. We aren't your enemies.
