### ISSUE TITLE
broken link (markdown)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#228]
Line 44 is not displaying properly in Extracting Keywords. Not sure what's wrong. It looks fine to me.

https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/extracting-keywords.md

**Comment by wcaleb** [comment]
It was interpreting the underscores as markers of emphasis. You can "escape" reserved characters with a backslash so that it takes those underscores literally, as per the [kramdown syntax](http://kramdown.gettalong.org/syntax.html#automatic-and-manual-escaping).

**Comment by acrymble** [comment]
thanks.
