### ISSUE TITLE
Updating Research Pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2282]
I am updating the following pages:

en/research
es/investigacion
fr/recherche
pt/pesquisa

1. add a link to abstracts of the _Global Digital Humanities Symposium_
2. add Nabeel Siddiqui's talk at Seshadripuram Evening Degree College (29 June 2021)
3. add Jessica Parr's talk at the University of Cambridge (30 March 2021)

**Comment by anisa-hawes** [comment]
Hello @nabsiddiqui and @JMParr. Just to let you both know that I've added your recent talks to our research pages. I'll set myself a reminder to update again after 29th September to add your next talk in Ukraine.

**Comment by nabsiddiqui** [comment]
Thank you @anisa-hawes. Let me know if there is anything I can do on my end to help.

**Comment by anisa-hawes** [comment]
All done, @nabsiddiqui!
