### ISSUE TITLE
Bug in Intro to BeautifulSoup Lesson

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2290]
If you are reporting a problem with a lesson, please try to provide us with the following information:

- The full title of the lesson
Intro to Beautiful Soup https://programminghistorian.org/en/lessons/intro-to-beautiful-soup

- The system you are using (Mac, Linux, Windows)
Mac, running Python locally and in Google colab notebooks

- Version numbers of the relevant software you are using
- The exact steps you took that caused the problem

The underlying website [https://bioguide.congress.gov/search](https://bioguide.congress.gov/search) for Intro to BeautifulSoup seems to have changed it's underlying code where when you now save a copy of the website you no longer get the same HTML as listed in the lesson and in fact the saved HTML isn't even the same as what's actually served on the webpage (thinking they are now running a web app that limits how much you can download).

Few solutions exist in my opinion though also want to see if @jerielizabeth wants to weigh in since it's her lesson.

1) Do we have a saved copy of the earlier webpage? Does it exist in the web archive? We could just use one of these and just update the lesson to indicate this change.

2) Do we want to update the lesson to work with the new HTML structure and specifically how to work around scrapping from web apps, which usually involves a bit more fancy footwork?

3) Do we want to retire this lesson as-is and then either have @jerielizabeth or someone else produce a new BeautifulSoup tutorial?

Again just some initial thoughts but wanted to flag since I wasn't able to use this lesson as-is this semester. In case it's helpful this is my web scraping lesson in a Jupyter notebook that I adapted from Jeri's code using the Humanist listserv as a dataset, available [here ](https://colab.research.google.com/drive/1Vv_vtjoq7BCJ4RB_O9PsT-iwuwd91KmF?usp=sharing).

**Comment by jerielizabeth** [comment]
I think we could find an archived version of the old site so that the tutorial still makes some sense, but I think it is time to retire the lesson as is and produce a new one that uses Python 3.

**Comment by jerielizabeth** [comment]
Hey! The bioguide now has a download option :) Maybe they got tired of everyone practicing web scraping.

**Comment by spapastamkou** [comment]
Hi @ZoeLeBlanc (and @jerielizabeth). A French translation of this lesson was submitted earlier this year and is currently [under review](https://github.com/programminghistorian/ph-submissions/issues/400). I drop this here so that we are able to track progress of this ticket and act accordingly cc @InesSalome

**Comment by anisa-hawes** [comment]
Hello @jerielizabeth and @ZoeLeBlanc. I found [an archived version of this webpage via the Wayback Machine](https://web.archive.org/web/20121225235545/http://bioguide.congress.gov/biosearch/biosearch.asp) that is contemporaneous to the lesson's publication, but (as I suspected) it isn't possible to perform a search enquiry here – so a researcher wouldn't be able to retrieve the data, download and continue the lesson. 
![Screenshot 2021-09-24 at 12 28 19](https://user-images.githubusercontent.com/87070441/134667535-0f0513c8-5466-4437-9770-15e129ca9920.png)
![Screenshot 2021-09-24 at 12 28 29](https://user-images.githubusercontent.com/87070441/134667541-e590fb1b-7341-4af3-ad44-3de60f4f5509.png)

How do you feel about retiring this lesson @svmelton? Do you think there is an alternative option?

**Comment by svmelton** [comment]
I think it's time to retire the lesson, sadly. We would love a new version if you're interested at some point, @jerielizabeth!

**Comment by svmelton** [comment]
Just created the PR to retire the lesson. After it's retired, I'll [update the list here](https://programminghistorian.org/en/lesson-retirement-policy) and [remove it from the Twitter bot](https://github.com/programminghistorian/jekyll/wiki/Retiring-a-Lesson-from-the-Twitter-Bot).
