### ISSUE TITLE
Potential FAQs derived from PH/JISC/TNA author event

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/jekyll#2294]
Hello everyone,

Following our very successful author event, I came up with a list of possible FAQs to add to the [CfP/Blog post](https://programminghistorian.org/posts/cfp-jisc-ph). These are (in no particular order right now, though I will organise them thematically):

- Can I still publish my lesson in *The Programming Historian* even if it hasn't been selected for this call?
- How will I know you have received my application?
- Will I need to translate (or arrange for the translation) of the lesson myself?
- When will I hear if my lesson has been accepted?
- Can I appeal the decision?
- Do I need a GitHub account or learn Markdown?
- Why is the peer review process open?
- Where can I find guidance for writing my lesson?
- Why does the CfP focuses on large-scale data?
- Who makes up the selection panel?
- What is the selection criteria?
- Does my lesson need to make use of JISC/TNA datasets?
- What should I do if I have more than one idea I would like to submit?
- What should I do if my dataset is too big?
- Can I make use of cloud services for data processing in my lesson?
- Are you able to take personal circumstances into account? (e.g. parental leave)

Some of these issues are already addressed in the CfP (though are also the kinds of things people tend to misunderstand, skim, or need confirmation about), others came from the author event, others still just things I was thinking about.

I'm drafting and making a pull request for this now (we can correct specific wordings there) but, in the meantime, anything you think should not be a part of this list / should be added?

P.S.: I can't seem to find Peter's username -- if he's not here, I can send them a link to the FAQs once they've been published and add any of his corrections/suggestions later, to avoid multiplying channels of conversation

**Comment by anisa-hawes** [comment]
Hello @tiagosousagarcia. I think it is @peterwebster.

**Comment by tiagosousagarcia** [comment]
Thanks @anisa-hawes -- I don't think @peterwebster is assignable for some reason (though I think he will be notified now), and in the process ended up getting rid of James and Anna-Maria by mistake! Not very graceful today, am I?

**Comment by anisa-hawes** [comment]
Ah! I see! I'm not sure why that isn't possible.... but I think @drjwbaker will be able to help 🤞🏼

**Comment by drjwbaker** [comment]
Thanks @tiagosousagarcia. I think that is an excellent summary. Maybe add a general one about 'are you able to take personal circumstanes into account? (e.g. parental leave)', the answer to which - I think - if we will try to and do so on a case by case basis.

**Comment by tiagosousagarcia** [comment]
Thanks @drjwbaker -- added to the list above
