### ISSUE TITLE
New Activities to add to website

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2296]
Collecting here for future pull request. Please add others if we've not kept up to date.

Brandon Walsh has written a blog post. When Matt Lincoln did something similar we added it to the /research pages under Media Contribution. https://walshbr.com/blog/lessons-from-the-programming-historian/

**Comment by jenniferisasi** [comment]
You are faster than me! I was going to add Brandon's post today :) 


I don't know of any other contribution that's already out there, latest is on #2221  

We have 2 articles coming up, I'm involved in both, so I will update as soon as I see them published (one at least not until December)

**Comment by anisa-hawes** [comment]
And I have set myself a reminder to add this next week:

Jessica Parr & Nabeel Siddiqui, '_Programming Historian_ and the Challenges of Globally Distributed Learning', [Sharing Digitally: Seminar on Digital Tools and Infrastructures](https://www.lvivcenter.org/en/conferences/sharing-digitally-2/), Center for Urban History at Lviv, Ukraine, 29 September 2021.

**Comment by anisa-hawes** [comment]
Am I right that we are thinking specifically about the Research pages here? I have added a few items recently, and noted some inconsistencies with typesetting on that page which I would be happy to set myself as a task to tidy up. 

I have also noticed that this is a place of frequent link breakage. Perhaps this page is a good candidate for a perma.cc overhaul.
