### ISSUE TITLE
FR/PT translation needed: changes related to becoming a charity in England and Wales

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2297]
Further to https://github.com/programminghistorian/jekyll/issues/2276 and https://github.com/programminghistorian/jekyll/pull/2292 I merged the pull request with EN and ES text only in three places because the PR contained a broken URL that was stopping builds.

The pages where translation is needed are:

> https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/snippets.yml
>> old `This project is administered by ProgHist Limited, Company Number [12192946](https://beta.companieshouse.gov.uk/company/12192946).`
>> 
>> new `This project is administered by ProgHist Ltd, Charity Number [1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview) and Company Number [12192946](https://find-and-update.company-information.service.gov.uk/company/12192946).`

> https://github.com/programminghistorian/jekyll/blob/gh-pages/en/about.md
>> old `The Programming Historian is an international volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is registered in England, Company Number [12192946](https://beta.companieshouse.gov.uk/company/12192946).`
>> 
>> new `The Programming Historian is an international volunteer-driven project whose financial activities are administered by ProgHist Ltd, a charity registered in England and Wales ([1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview)) and incorporated in England and Wales as a company limited by guarantee ([12192946](https://find-and-update.company-information.service.gov.uk/company/12192946)).`

> https://github.com/programminghistorian/jekyll/blob/gh-pages/en/ipp.md
>> old `The *Programming Historian* is an international volunteer-driven project whose financial activities are administered by ProgHist Limited, a Not for Profit Company Limited by Guarantee that is registered in England, Company Number 12192946.`
>> 
>> new `The *Programming Historian* is an international volunteer-driven project whose financial activities are administered by ProgHist Ltd, a charity registered in England and Wales ([1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview)) and incorporated in England and Wales as a company limited by guarantee ([12192946](https://find-and-update.company-information.service.gov.uk/company/12192946)).`

So you'll see that the changes are small and tend to repeat themselves.

@programminghistorian/french-team @programminghistorian/portuguese-team: could someone take a look at this please?

**Comment by DanielAlvesLABDH** [comment]
Hi @drjwbaker! The change in the PT files are here: https://github.com/programminghistorian/jekyll/pull/2300

**Comment by spapastamkou** [comment]
@mariechristineb do you believe you can lend a hand here for the translation? Your (Canadian) ear must be more used to these terms and their equivalent in French (I have not the slightest idea how "charity" is translated in this context). Thanks!

**Comment by mariechristineb** [comment]
@spapastamkou I've added the translations to #2305
