### ISSUE TITLE
Add button to select all text in a code block 

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#23]
There is currently a [javascript in our repo](https://github.com/programminghistorian/jekyll/blob/gh-pages/js/codeblocks.js) that, if enabled, will place a small button beside each code block. When the button is clicked, all the text in the code block will be selected so that the user can easily copy it to his/her clipboard.

Currently, the button is floated to the right of the code block outside the main container, sort of like the sidebar comment icons on a site like Medium. The button is grayed out, as in the first example pictured, until the mouse hovers over the code block or clicks on the button, as in the second example pictured.

![select_button](https://cloud.githubusercontent.com/assets/1126864/3866857/4adef8ac-1fe5-11e4-94e7-d6db37f9ffd4.png)

Before enabling this across the site, a couple of issues need to be decided:

- should we use the current icon, or pick a different one (preferably from [Font Awesome](http://fortawesome.github.io/Font-Awesome/icons/) for the sake of design consistency?
- should the button be placed elsewhere, i.e. above or below the code block? (placing it within the code block doesn't work well because text will run over it)?
- should we just hide the button entirely until someone hovers over the code block, at which point it is revealed?

**Comment by dmoskovsov** [comment]
+1

**Comment by wcaleb** [comment]
Would we be more comfortable with restoring this feature if the icon was totally invisible until you hover over a codeblock? Sort of like the hover links for headers work now?

**Comment by acrymble** [comment]
What if it was just a 'select code' text link? Not international enough?

**Comment by ianmilligan1** [comment]
I think a little 'select code' link would work well, making it easy to quickly locate?

**Comment by wcaleb** [comment]
I'll experiment with this. My initial move towards the icon was an aesthetic one---on some lessons we have lots of short little codeblocks, and a text link with each one could begin to clutter the page considerably. But perhaps I can hide the text until user hovers over the codeblock, or something like that.

**Comment by acrymble** [comment]
We should have a 1 year time limit on tickets :)

**Comment by amandavisconti** [comment]
Coming from [here](https://github.com/programminghistorian/ph-submissions/issues/3#issuecomment-202426152): I'd vote for placing the link visibly directly above (like, top-left) the code block.
