### ISSUE TITLE
Updating editor guidelines

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2312]
At our most recent managing editor meeting (#2255), @spapastamkou @rivaquiroga and I discussed some ways to improve our current editor guidelines. Specifically, we identified these items:

- Ensuring that editors know to change absolute to relative links when reviewing lessons
- Creating a checklist for editors, as the current text is quite long and difficult to read through

Are there other items that would be useful to revise?

**Comment by rivaquiroga** [comment]
@isag91, @nivaca & @nllano, your views as new editors will be extreamly valuable in this discussion.

**Comment by DanielAlvesLABDH** [comment]
Thanks for this. Sorry for not being able to attend the meeting. One thing I think we need is a clearer separation between the task of the Editor and the ME. Probably in different pages

**Comment by rivaquiroga** [comment]
We should add more specific guidelines on how editors can fix errors on the build of the ph-submissions repo. Most of the time they are due to unescaped quotes within the caption or alt text.

**Comment by spapastamkou** [comment]
In addition to what @svmelton and @DanielAlvesLABDH say: 
- specifically for translations, remind to check the translation of the anchors, meaning that if the authors use an anchor as a link to send to another part of the lesson, in most cases the translator does not realize this link has to change since they mostly work on the text; the editor should check and change the link in this case. 
- in current guidelined, there is an overlap between the final checks on the editors list and the beginning of the ME's.

**Comment by spapastamkou** [comment]
@InesSalome @datalogism @matgille @icolab If during your current or recent editorial work you found the editors guidelines were not clear on something, please let everyone know here so that we can make them better.

**Comment by anisa-hawes** [comment]
Editor Guidelines
- [x] include a note to explain relative links, asking editors to check them at initial and final stages
- [ ] create a checklist
- [x] a clearer separation between the tasks of the Editor and the ME
- [x] notes on fixing build errors, including how to use escaped quotes within captions and alt text

Editor of Translations
- [ ] reminder about translation of section anchors, and updates to section anchor links

**Comment by datalogism** [comment]
The only contribution that I can give you on at the view of my tiny experience concerns how to underline the name of file / variables / and functions. In the guidelines, we only talk about file names, and as we often have to speak about these objects it could be an idea to "normalize" how to write each kind of thing (to discriminate cognitively easily these). That is not a big contribution but I ask myself the question a lot of time and in the tutorial, it seems to be randomly underlined. I just submit my questioning, it may be also a bad idea to formalize too much this kind of detail...

**Comment by anisa-hawes** [comment]
Thank you, for your contribution @datalogism! I think it is possible to use html \<u> tags to underline text, but Markdown syntax doesn't include an underline option, and our Author Guidelines advise against using underlines in lessons. 

In terms of standardising the way we write variables and functions, our Author Guidelines ask that variable names should be nouns (for example, “counter”) and function names should be verbs (for example, “createFile”). The section I am referring to can be found in the English guidelines, here: https://programminghistorian.org/en/author-guidelines#code-examples. Do these notes help you? Please let me know if you have questions, and I'll do my best to find the answer. 

I notice that the French Author Guidelines are structured slightly differently, and do not appear to cover this specific section. But the FR Author Guidelines are under review at the moment, so it will certainly be very useful for the @programminghistorian/french-team to hear your feedback.

**Comment by InesSalome** [comment]
My short experience in editorial work concerns mainly translations, and I notice it may be useful to clarify when we must translate or not code terms and examples, because the translator guidelines indicate "translating code terms and examples, if possible", but what does "if possible" actually mean ? Does it mean only that the translation must not break the code ? Are any other limits suggested ? 

Otherwise, I share the comments mentioned before !

**Comment by datalogism** [comment]
I join @InesSalome  on this suggestion, i also worked on an original 15 lessons of PH, and i really doubtful about this recommendation. Do the translation the well known "hello world" print exemple giving more literacy ? Is it really strategic to translate every variable names while the current standard is to naming even in France variable with english names ? Wouldn't it be a better option to add detailed in language comments ?

**Comment by anisa-hawes** [comment]
Thank you for all your insights and ideas, which have been invaluable in guiding this work. 

As my second draft of our editorial guidelines are now with the English team, I am closing this Issue. 

The revised documentation is going to be tested in a pilot study for new English editors. When their onboarding is complete, I will collate feedback and open a new Issue for consultation.
