### ISSUE TITLE
Broken link in /es/retroalimentacion.html

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2314]
There's a 404 for [this link](https://docs.github.com/es/github/getting-started-with-github/quickstart). I found [an alternative](https://docs.github.com/es/get-started) but it doesn't appear to actually be translated into Spanish. Tagging the @programminghistorian/spanish-team to see if there's a different resource or if we should remove it entirely.

**Comment by rivaquiroga** [comment]
@svmelton, from which lesson is the link?

**Comment by svmelton** [comment]
@rivaquiroga It's from the /es/retroalimentacion.html page

**Comment by rivaquiroga** [comment]
Sorry!!! Was on the ticket title 😳 
I'll look for a better option tomorrow. I can't do it today, so if you need to merge something, feel free to change it for the english version until I have a solution.

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. Just to let you know that we've updated the link at paragraph 42 of `/es/retroalimentacion.html` with this: https://docs.github.com/es/get-started/quickstart. Sarah and I think it is a reasonable temporary fix. It seems that the Spanish translation of GitHub's Quickstart Guide is incomplete, but 'in progress'!
