### ISSUE TITLE
Gemfile removed?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#232]
I noticed in commit e7cbd30406bca98de75165d550c0243956788d1e by @wcaleb that the `Gemfile` was removed. Was this file interfering with the Heroku preview? I usually relied on the `Gemfile` to enable local build & preview using `bundle exec jekyll serve`.

**Comment by wcaleb** [comment]
I had only put it in for Heroku preview, which we've discontinued using. But I can put it back---hadn't occurred to me that it would affect local build.

**Comment by wcaleb** [comment]
Reverted with 004acc4b90346956db554f51d13cc0131a0338b7.
