### ISSUE TITLE
IPPs pack - renewal

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2321]
As part of the annual renewal process for existing IPPs, we are preparing a brief update on our activities during the past year. Our objective is to say 'thank you', and show them that we value their contribution. 

@programminghistorian/english-team @programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team Please let us know if you have suggestions for key achievements to include.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes , from the PT team I think the number of lessons published in 9 months of the project (12) is something to mention. Also the fact that we manage to get four scholarships from the Portuguese Science and Technology Foundation to have four students to work with us during September (they translated 8 more lessons; to be reviewed). Finally, we are implementing the project "Literacia Digital..." with the support of Fundação Getúlio Vargas, Brazil (see: https://programminghistorian.org/en/supporters#additional-supporters).

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH! These achievements are exactly the kinds I think we will want to highlight.

**Comment by amsichani** [comment]
We 'd like to ask for some highlights from the @programminghistorian/french-team to be included to this update . Thanks !

**Comment by amsichani** [comment]
many thanks to all of you for contributing on this esp @anisa-hawes ! I ll close this as the final text is now with @drjwbaker
