### ISSUE TITLE
Troubleshoot search building 

### ISSUE THREAD

**Issue by ZoeLeBlanc** [programminghistorian/jekyll#2324]
After discussing the search with @anisa-hawes she pointed out that for some reason the Gravity Models isn't returned in the search.

I need to do some testing to understand what's going on but please let me know if you've had other search-related issues.

**Comment by anisa-hawes** [comment]
Just noted that I don't retrieve [Exploring and Analyzing Network Data with Python](https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python) when I filter by [Topic Python](https://programminghistorian.org/en/lessons/?topic=python)....
