### ISSUE TITLE
Editor recruitment process documentation

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#2329]
Related to our [forthcoming recruitment process for EN editors](https://programminghistorian.org/posts/call-for-editors-en), it might worth documenting our processes and criteria for future reference. This might be an ongoing, collaborative output - reference document of all publications  @programminghistorian/french-team @programminghistorian/english-team @programminghistorian/spanish-team @programminghistorian/portuguese-team (as part of our wiki training documentation perhaps?), ensuring our processes are transparent, accessible and inclusive.

**Comment by acrymble** [comment]
Maybe we could start storing all advertisements for new editors in a central place on our business repository? Then anyone who needs to advertise has something to reference?

Althought I think they're all already on the blog.

**Comment by jenniferisasi** [comment]
> Maybe we could start storing all advertisements for new editors in a central place on our business repository? Then anyone who needs to advertise has something to reference?
> 
> Althought I think they're all already on the blog.

Correct, @acrymble. The last calls for editors at least going 3-4 years back are published in the blog. We could copy them in the business repository (and leave them up or take them down from the blog)

**Comment by acrymble** [comment]
@amsichani can you clarify what needs to happen to close this ticket?

**Comment by hawc2** [comment]
I can sit down with @svmelton and document what our last round of recruitment involved for English editors. Is there a fitting place on the wiki or elsewhere that we should put any relevant information?

The current task of identifying a Managing Editor for the French team would be another opportunity to document how PH handles these processes. Each language journal handles these things differently, and we're all still figuring out the ideal/most practical way to handle recruitment and rotation of editors, so this sort of documentation is probably going to be a little sketchy for now

**Comment by acrymble** [comment]
@hawc2 A wiki page is probably the best we can use for now. I would think this can be quite high-level though:

- Identify a need & discuss it with your team, including timelines
- Adapt an old advert from the blog to meet new needs
- Post and disseminate
- Select from suitable candidates (maybe do a call with them?)
- Invite them on an agreed term (I always think 3 years is the best)
- Send to Anisa for training
- Set up meetings with ME for additional training and team building

**Comment by hawc2** [comment]
I drafted a new wikipage for documenting [Editorial Recruitment](https://github.com/programminghistorian/jekyll/wiki/Editorial-Recruitment). This covers most of what was requested in this thread, but older editor calls could still be added, and others should feel free to update this as it gets translated into other languages.

**Comment by acrymble** [comment]
@hawc2 do you think we can close this and amend it as needed over time?

**Comment by hawc2** [comment]
yep works for me
