### ISSUE TITLE
Mark JISC/TNA CfP as closed

### ISSUE THREAD

**Issue by peterwebster** [programminghistorian/jekyll#2331]
I suggest that, now that the deadline has passed, the text be left there as an aid to those who have applied, but a prominent note be added to state that the deadline has passed.
https://programminghistorian.org/posts/cfp-jisc-ph

One for @tiagosousagarcia ?

**Comment by drjwbaker** [comment]
Good idea. @tiagosousagarcia: no hurry on this, just pick it up on your next working day please.

**Comment by tiagosousagarcia** [comment]
I'll do that :)
