### ISSUE TITLE
Adding tested-date: to two lessons

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2341]
I am adding a `tested-date:` field to the yaml headers of basic-text-processing-in-r and cleaning-data-with-openrefine, which I have worked through recently.

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi. Please let me know if you'd like me to add in the date you tested es/lecciones/procesamiento-basico-de-textos-en-r (you mentioned that the corpus and commands differed in this case).

**Comment by jenniferisasi** [comment]
@anisa-hawes I just checked, and everything still also works on the lesson in Spanish. Only part of it is different and the main functions are not altered.

**Comment by anisa-hawes** [comment]
Thank you so much, @jenniferisasi ! I have added the `tested_date` metadata to the ES lesson too.

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc and @jenniferisasi. Let me know how you feel we should move forwards to make `_layout/lesson.html` and `_data/snippets.yml` consistent? When we've made a decision, I can add the correct "tested date" metadata to these and the other lessons which Jenn identified, so that this shows on our website in all cases.

sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
up-and-running-with-omeka.md
creating-an-omeka-exhibit.md

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc. What are your thoughts about how we should make `_layout/lesson.html` and `_data/snippets.yml` consistent? Another lesson has just been tested and I'd like to add a tested date there too!
