### ISSUE TITLE
Re-test Introducción a Map Warper

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2344]
A [recent thread on Twitter ](https://twitter.com/NYPLMaps/status/1452668555992965122?s=20) indicates that the NYPL Maps Division are closing their MapWarper project. It would be good to re-test our ES tutorial https://programminghistorian.org/es/lecciones/introduccion-map-warper, and see what the implications are/check that the lesson still works. 

I can have a go at this, guided by the screenshots, but I would appreciate it if someone from the @programminghistorian/spanish-team could support this too. 

If the lesson still works now, we could consider applying an information alert box to indicate that the project is changing and set ourselves a reminder to check again in a few months' time.

**Comment by anisa-hawes** [comment]
![Screenshot 2021-10-27 at 11 19 28](https://user-images.githubusercontent.com/87070441/139048860-29bd91a8-dc7f-4c05-948c-6ba0eae8a39c.png)

**Comment by nllano** [comment]
Hi @anisa-hawes! Thanks for the heads up. I can help you re-test it and see if the lesson still works properly.

**Comment by anisa-hawes** [comment]
Ah! thank you, @nllano! Much appreciated!

**Comment by nllano** [comment]
Hi, @anisa-hawes! The lesson is still running smoothly, aside from a couple of specific functionalities of Mapwarper's system. Here is a rundown of the key elements of the lesson. 

- _Registro_: I was able to create an account on Mapwarper (using my email).
- _Cargar Mapa_: I sucessfully uploaded and deleted a map. I also was able to download the .csv file (no relation to Mapwarper’s system).
- _Metadatos_: Sucessfully edited (added and deleted) metadata.
- _Georrectificación — Add Custom Basemap_: **I couldn’t add any custom basemaps.**
- _Control points — Recitfy_: Manage to add control points and rectify the map.
- _Control points_ and _.csv export_: Working properly. 
- _Upload of .csv file with control points_: Done successfully. 
- _Crop tool_: Working properly.
- **Some of their _Export formats (Map Services)_ are not working**: Tiles / Bibliographic Links / Bibliographic.
- _Activity_ :Working properly.

Maybe we should include a note or footnote updating the current status of the tool/program (archived): 

[_As of April 2021, Mapwarper will no longer be updated by NYPL and has been archived. This means all embedded views utilizing Mapwarper will no longer work once the site is archived. However, all contributions  and data have been retained by the Library for future use and research._](https://www.nypl.org/digital-research/projects/map-warper)

**Comment by nllano** [comment]
Let me know if I can help you with something else! :)

**Comment by anisa-hawes** [comment]
Thank you for your thorough work @nllano! This is an enormous effort and is much appreciated. 

Is there any chance you have time to translate this note into Spanish?

1. "As of April 2021, Mapwarper will no longer be updated by NYPL and has been archived. This means all embedded views utilizing Mapwarper will no longer work once the site is archived. However, all contributions and data have been retained by the Library for future use and research". 

I can see that the lesson already uses Markdown's blockquotes to create grey boxes containing notes/hints, but for this I think I will create a blue "alert information" box at the very beginning of the lesson, to let users know that some utilities have changed. We can also include the link to the status update: https://www.nypl.org/digital-research/projects/map-warper

It might also be useful to add yellow "warning alert" boxes in those sections (_Georrectificación_ and _Exportar_ where specific things are not working. 

So, if you could translate: 

2. _Georrectificación_ "Since Mapwarper was archived by NYPL, it is no longer possible to Add Custom Basemaps". 
3. _Exportar_ "Since Mapwarper was archived by NYPL, the following Export formats are no longer available: Tiles, Bibliographic Links, Bibliographic".

**Comment by anisa-hawes** [comment]
I'm happy to create the new branch & implement these changes, but I do need a hand to get the Spanish right! 🙂

**Comment by nllano** [comment]
Happy to help! Sure, I can work on the translations, no problem.
I like the idea of the blue "alert information" box, and the yellow "warning alert" on those two sections that are not working properly.

**Comment by anisa-hawes** [comment]
Wonderful, thank you @nllano!

**Comment by nllano** [comment]
**NYPL Note:** "A partir de abril de 2021, la NYPL dejará de actualizar Mapwarper, y este quedará archivado. Esto significa que todas las vistas incorporadas (_embedded_) que utilicen Mapwarper dejarán de funcionar una vez que la página sea archivada. Sin embargo, todas las contribuciones y datos han sido guardadas por la Biblioteca para usos e investigaciones futuras.”

**Georreferenciación** "Desde que Mapwarper fue archivado por la NYPL, ya no es posible añadir un mapa base.”

**Exportar** "Desde que Mapwarper fue archivado por la NYPL, los siguientes formatos de exportación ya no están disponibles: Tiles, Bibliographic Links, Bibliographic.”

**Comment by anisa-hawes** [comment]
Thank you so much, @nllano! I have run out of time today, but I will update the lesson file next week ✨

**Comment by nllano** [comment]
Great. You're welcome, @anisa-hawes!
