### ISSUE TITLE
Martin Grandjean offboarding

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2349]
- [x] Remove Google Groups access (@anisa-hawes or @jenniferisasi?)
- [x] Remove Google Analytics access (@acrymble) - only applicable to longer-serving members
- [x] Remove Github Jekyll access (@anisa-hawes or @ZoeLeBlanc?)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@anisa-hawes)
- [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@anisa-hawes)
- [x] Check that they have no open issues assigned to them on either the Jekyll repository or the Submissions Repository (@spapastamkou ).
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts (@anisa-hawes). 
- [x] If they hold any other team roles, inform @mariajofana that a replacement is needed.

**Comment by spapastamkou** [comment]
@anisa-hawes I followed the latest instructions available on the wiki and see you are assigned most of the tasks. I put interrogations where I believe you do not have access yet (and I think @jenniferisasi contributed already - thanks!). Please let me know if the ticket seems ok and feel free to ask me if you want me to do something here. Thanks!

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou. I have initiated a PR to update `ph_authors.yml` and @acrymble has kindly removed Martin's Jekyll access.

Hello @ZoeLeBlanc, I don't currently have "owner" credentials to our repositories, so I'm unable to add/remove members or change their roles in our Teams. Let me know if you want to review this so I can help take care of these tasks in the future.

**Comment by anisa-hawes** [comment]
Just a note to say that I've checked the most recent [Register of Members](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Register-of-Members/2021/2021-11_ProgHistLtd_Register-of-Members.docx) and Martin's name has already been removed.

**Comment by drjwbaker** [comment]
> 
> 
> Just a note to say that I've checked the most recent [Register of Members](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/Register-of-Members/2021/2021-11_ProgHistLtd_Register-of-Members.docx) and Martin's name has already been removed.

Indeed. I was in there sorting out https://github.com/programminghistorian/jekyll/issues/2276#issuecomment-958890016 so thought I may as well remove Martin at the same time.

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker 🙂
