### ISSUE TITLE
Edits required to Georeferencing in QGIS 2.0 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2356]
In the process of translating the EN and ES lesson into PT @joanacvp and @Angelaimp have noted the following issues:

--

See: Submissions [#409](https://github.com/programminghistorian/ph-submissions/issues/409)

Good morning @anisa-hawes. Hope everything is ok with you. When translating this lesson @Angelaimp spotted some incorrections in the english version (she used QGIS 3.0):

 
- [x] In "Open the Necessary GIS Layers/Download lot_township_polygon", in the link available, there is no longer the need to read and accept the licence and they don't ask for our name and email (http://www.gov.pe.ca/gis/license_agreement.php3?name=lot_town&file_format=SHP)
- [x] In "Open the Georeferencer Tool /Add your historical map" the link to the online repository Island Imagined is not correctly positioned. 
- [x] The same as the later in "Adding control points - Some tips for choosing control point", since in the last point the link in Atlantic Canada is not correctly positioned. 
- [x] In "Determine the transformation settings" the link are incorrect.
- [x] In "world file" the link is incorrect.
- [x] In "Tif" the link is incorrect.
- [x] In "Island Imagined" the link is incorrect and there is no image of a lower resolution map.
- [x] In "Creating New Vector Layers in QGIS" the link is incorrectly positioned.
- [x] In "Geospatial Historian" the link is incorrectly positioned.

**Comment by anisa-hawes** [comment]
Dear @joanacvp and @angelaimp,

I have re-positioned the links and the corrected Markdown syntax at the following lines:

line 47 [Intro to Google Maps and Google Earth](/lessons/googlemaps-googleearth)
line 59 [rubber-sheeting](http://en.wikipedia.org/wiki/Rubbersheeting)
line 80 [Coordinate Reference System](http://en.wikipedia.org/wiki/Spatial_reference_system)
line 81 [Installing QGIS 2.0 and adding Layers](/lessons/qgis-layers)
line 85 [Installing QGIS 2.0 and adding Layers](/lessons/qgis-layers)
line 125 [Installing QGIS 2.0 and adding Layers](/lessons/qgis-layers)
line 146 [can be downloaded here](http://geospatialhistorian.files.wordpress.com/2013/02/pei_lakemap1863.jpg)
line 147 [Island Imagined](https://islandimagined.ca/islandora/object/imagined:208687)
line 183 [in Atlantic Canada](http://books.google.ca/books?id=TqCNZYXWXAUC&dq=tilting&source=gbs_navlinks_s)
line 251 [world file](http://en.wikipedia.org/wiki/World_file)
line 256 [Island Imagined](https://islandimagined.ca/islandora/object/imagined:208687)
line 258 [Tif](http://en.wikipedia.org/wiki/Tagged_Image_File_Format)
line 311 [Creating New Vector Layers in QGIS](/lessons/vector-layers-qgis)
line 327 [Geospatial Historian](http://geospatialhistorian.wordpress.com/)

line 102: removed ", read/accept the license agreement, and then download the following (they will ask for your name and email before you can"

I think the lower resolution file refers to the file that you can drag and drop from this page: https://islandimagined.ca/islandora/object/imagined:208687

The higher resolution .jpg is here: http://geospatialhistorian.files.wordpress.com/2013/02/pei_lakemap1863.jpg

**Comment by anisa-hawes** [comment]
P.S. I've removed the 'Spanish' label, because these issues do not appear in in that version of the lesson.

**Comment by joanacvp** [comment]
Thank you very much for your support @anisa-hawes
