### ISSUE TITLE
Possibility to a Code of Conduct (to take advantage of new GitHub feature)

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2362]
In the same way that a `license.md` file is highlighted on the right side of a repo page, GitHub [now highights](https://twitter.com/github/status/1456635470339788803) `code_of_conduct.md`.

We have a few CoC-like docs scattered around - e.g. https://github.com/programminghistorian/jekyll/wiki#social-guidance and https://programminghistorian.org/en/author-guidelines#holding-us-to-account - so I wondered if we had the will to highlight them in a central CoC md file.

If there is no will - of suggestions otherwise - I will happily close the ticket.

**Comment by rivaquiroga** [comment]
Yes! That would be great.

**Comment by drjwbaker** [comment]
@rivaquiroga: how about something like this? https://github.com/programminghistorian/jekyll/pull/2363

**Comment by rivaquiroga** [comment]
Great! We can add a section in that same file for the other three languages.

**Comment by drjwbaker** [comment]
I kept the text minimal for that reason (and the opening block of text is largely copied from https://programminghistorian.org/en/editor-guidelines#anti-harassment-policy)
