### ISSUE TITLE
Newsletter: December 2021

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2364]
Dear all, I am opening this Issue to collate content for our December Newsletter. Please let me know if you have ideas for inclusion under the headings I've set out below, or if you'd like to suggest something else. Edits and comments are very welcome!

Thank you!

Anisa 

Newsletter: December 2021
---

1. **Recent research activities**: Have you contributed to articles or events that you'd like me to share?

- [Training the Teacher: Giving your first Digital History Workshop](https://www.history.ac.uk/our-century/centenary-events/training-teacher-giving-your-first-digital-history-workshop) with IHR. 18th November @acrymble and @anisa-hawes 

- ~~Fundação para a Ciência e Tecnologia, através do apoio especial ‘Verão com Ciência 2021’, Portugal~~. This was included in the September Newsletter

- [Open Publishing Fest: _Programming Historian_: A Multilingual Open Access Publication](https://openpublishingfest.org/calendar.html#event-69/). 17th November
@svmelton, @rivaquiroga, @joanacvp, @nabsiddiqui 

- Jennifer Isasi and Antonio Rojas Castro. “Sin equivalencia: Una reflexión sobre la traducción al español de recursos educativos abiertos.” Hispania 104.4 (2021): pp. 613-24.

- Torre de Babel: Humanidades Digitales multilingües (roundtable discussion) at the Association of History Literature Science and Technology (AHLiST)'s International Interdisciplinary Conference 19th November 2021 in Madrid, Spain @jenniferisasi @arojascastro with Alex Gil, organized by Daniel Carrillo

2. **New Lessons**: Original lessons or translations published since our September newsletter

- EN [Clustering with Scikit-Learn in Python](https://programminghistorian.org/en/lessons/clustering-with-scikit-learn-in-python)
- EN [Interactive Fiction in the Humanities Classroom: How to Create Interactive Text Games Using Twine](https://programminghistorian.org/en/lessons/interactive-text-games-using-twine)

- ES [Introducción a la codificación de textos en TEI (parte 2)](https://programminghistorian.org/es/lecciones/introduccion-a-tei-2)
- ES [Introducción a la publicación web de archivos TEI con CETEIcean](https://programminghistorian.org/es/lecciones/publicar-archivos-tei-ceteicean)

- FR [Installer un environnement de développement intégré pour Python (Linux)](https://programminghistorian.org/fr/lecons/installer-ide-python-linux)
- FR [Détecter la réutilisation de texte avec Passim](https://programminghistorian.org/fr/lecons/detecter-la-reutilisation-de-texte-avec-passim)
- FR [Générer un jeu de données structuré à partir d’un texte océrisé](https://programminghistorian.org/fr/lecons/generer-jeu-donnees-texte-ocr)

- PT [Noções básicas de R com dados tabulares](https://programminghistorian.org/pt/licoes/nocoes-basicas-R-dados-tabulares)
- PT [Processamento Básico de Texto em R](https://programminghistorian.org/pt/licoes/processamento-basico-texto-r)
- PT [Manipular strings com Python](https://programminghistorian.org/pt/licoes/manipular-strings-python)

3. **New Supporters and Partnerships**: Individual or Institutional support and partnership announcements  

Institutional

- Georg-August-Universität Göttingen 

- Purdue University

- MIT Libraries

- University of Nebraska-Lincoln

- [Beijing Normal University at Zhuhai]* wait until January to announce

Individual

- Monica Berti (Educator)

- Mike Bess

- Ajit Balakrishnan

4. **Team News**: A space to welcome new members, and say thank you to people who are retiring

- Eric Brasil @ericbrasiln (Portuguese Team)

- Martin Grandjean retired from the FR team

5.  **News** 

- We are one of the three recipients of the Open Publishing Award 2021 on the Open Content category, by Coko https://openpublishingawards.org/results/2021/index.html

**Comment by acrymble** [comment]
There are some new IPPs that may or may not be complete. @drjwbaker can let you know the ones that are ready to announce closer to the date.

**Comment by drjwbaker** [comment]
If everyone pays on time, by then we'll have added:

- Georg-August-Universität Göttingen (just paid!)
- MIT Libraries
- Purdue University
- University of Nebraska-Lincoln

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. The PT team has published two new lessons since September: Noções básicas de R com dados tabulares (https://programminghistorian.org/pt/licoes/nocoes-basicas-R-dados-tabulares) and Processamento Básico de Texto em R (https://programminghistorian.org/pt/licoes/processamento-basico-texto-r)
We also finished the programme "Fundação para a Ciência e Tecnologia, através do apoio especial ‘Verão com Ciência 2021’, Portugal [Setembro 2021]" with the translation of 8 new lessons to be revised and published in the next months.

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH!

Apologies! I did a quick check of Noções básicas de R and Processamento Básico de Texto em R but noted that the translation dates were 2021-08-28 and 2021-07-13 so I was thinking they were older, but can see now that they have been modified more recently! I'll add them to my notes for the Newsletter.

**Comment by DanielAlvesLABDH** [comment]
That is probably my fault. I usually use the date the translators send the file to us as the date of translation, but in reality the publication of that translation is a couple of weeks or moths later, after peer review.

**Comment by anisa-hawes** [comment]
Understood, but don't worry! 

I checked the Mid-year Newsletter and didn't see them there, so I could have guessed that they weren't yet published!

**Comment by spapastamkou** [comment]
@anisa-hawes We may have a new FR translation published until then, I'll let you know when/if this is the case. 
Update, 22 Nov: added

**Comment by rivaquiroga** [comment]
@anisa-hawes, we will publish a new lesson this week. I'll let you know when it's done.

**Comment by jenniferisasi** [comment]
> If everyone pays on time, by then we'll have added:
> 
> * Georg-August-Universität Göttingen (just paid!)
> * MIT Libraries
> * Purdue University
> * University of Nebraska-Lincoln

I just edited the name of UNL as it was Lincoln first, then Nebraska. As their alumn, it was easy to spot :)

**Comment by svmelton** [comment]
We'll be publishing a new lesson, as well. You could also add our presentation on this Wednesday Nov. 17 at the [Open Publishing Fest](https://openpublishingfest.org/calendar.html#event-69/).

**Comment by anisa-hawes** [comment]
> We'll be publishing a new lesson, as well. You could also add our presentation on this Wednesday Nov. 17 at the [Open Publishing Fest](https://openpublishingfest.org/calendar.html#event-69/).

Thank you, @svmelton! I'll add this to the Research pages of our website too.

**Comment by rivaquiroga** [comment]
The new ES lesson is now published: http://dx.doi.org/10.46430/phes0055 🎉

**Comment by anisa-hawes** [comment]
Hooray! Thank you, @rivaquiroga! Our December Newsletter is going to be filled with wonderful new lessons!

**Comment by DanielAlvesLABDH** [comment]
We have a new one, also! https://doi.org/10.46430/phpt0016

**Comment by drjwbaker** [comment]
@anisa-hawes Purdue University have joined, if you have some time to celebrate that on twitter!

**Comment by jenniferisasi** [comment]
@anisa-hawes something else to add :) We are one of the three recipients of the Open Publishing Award 2021 on the Open Content category, by Coko https://openpublishingawards.org/results/2021/index.html

**Comment by svmelton** [comment]
New EN lesson! https://doi.org/10.46430/phen0095

**Comment by rivaquiroga** [comment]
@anisa-hawes, we will publishing a new ES lesson this week 🥑🎉

**Comment by anisa-hawes** [comment]
Excellent! I'll keep an eye out for it!
