### ISSUE TITLE
Translation of our Code of Conduct.

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2366]
@drjwbaker has created a Code of Conduct for us! See #2362. Thank you, James!

With PR #2363 we've merged the EN text into Jekyll, but translations into ES, FR and PT would be welcome! 

The text is [here](https://github.com/programminghistorian/jekyll/blob/gh-pages/CODE_OF_CONDUCT.md) if anyone in the @programminghistorian/spanish-team, @programminghistorian/french-team and @programminghistorian/portuguese-team has an interest / time to translate this.

Thank you, @rivaquiroga for your enthusiasm already!

**Comment by joanacvp** [comment]
Hi @anisa-hawes! Here follows the PT translation. 
@DanielAlvesLABDH do you agree with everything? Also, do we have the first linked document translated?




# Código de Conduta do Programming Historian

O *Programming Historian* não tem um código de conduta único, mas sim um conjunto de documentos que representam a nossa dedicação em providenciar um ambiente aberto que ofereça à comunidade de participantes a liberdade para discutir ideias, colocar questões, fazer sugestões ou apresentar pedidos de clarificação. Também dispõe de um espaço anti-assédio para todos os contribuidores do projeto, não obstante o seu género, identidade de género e expressão, orientação sexual, incapacidade, aspecto físico, tamanho corporal, raça, idade, religião ou experiência técnica. Não toleramos assédio ou ataques *ad hominem* de qualquer forma dos participantes da comunidade. Aqueles  que violem estas regras podem ser expulsos da comunidade mediante a decisão do conselho editorial.

Este documento reúne vários documentos num único espaço de forma a facilitar o acesso. 
- Para membros da Equipe do Projeto: [Privilégios e Responsabilidades da Filiação](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership) (em Inglês)
- Para autores: a secção [‘Responsabilidade da equipe’](https://programminghistorian.org/pt/directrizes-autor#etapa-3-submeter-uma-nova-lição) das Diretrizes para Autores
- Para revisores: a secção [‘Filosofia da Revisão’]( https://programminghistorian.org/pt/directrizes-revisor#filosofia-da-revisão) das Diretrizes para Revisores
- Para editores: as secções [‘Espaços seguros’]( https://programminghistorian.org/pt/directrizes-editor#espaços-seguros) e [‘Política anti-assédio’]( https://programminghistorian.org/pt/directrizes-editor#pol%C3%ADtica-anti-assédio) das Diretrizes para Editores

**Comment by anisa-hawes** [comment]
Thank you, @joanacvp! The Wiki is only available in English at the moment, so maybe for that link we can add a note to say _(em Inglês)_?

**Comment by jenniferisasi** [comment]
_Programming Historian_ no tiene un único código de conducta. Más bien, tenemos varios documentos que presentan nuestra dedicación a proporcionar un entorno académico abierto que ofrece a sus participantes la libertad de analizar a fondo ideas, de hacer preguntas, de hacer sugerencias o de solicitar aclaraciones, pero siempre desde un espacio libre de acoso para quienes contribuyan al proyecto, independientemente de su género, identidad y expresión de género, orientación sexual, discapacidad, apariencia física, tamaño corporal, raza, edad o religión, o experiencia técnica. No toleramos el acoso o los ataques ad hominem de los participantes de la comunidad de ninguna forma. Quienes violen estas reglas pueden ser expulsados ​​de la comunidad a discreción del consejo editorial.

Este documento reúne los documentos en un solo lugar para facilitar su acceso y localización. 

Para miembros del equipo del proyecto: [Privileges and Responsibilities of Membership](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership) (en inglés)
Para autores: [Haznos responsables](https://programminghistorian.org/es/guia-para-autores#haznos-responsables)
Para revisores: [Nuestra filosofía](https://programminghistorian.org/es/guia-para-revisores#nuestra-filosof%C3%ADa) 
Para editores: Las secciones de [Espacio seguro](https://programminghistorian.org/es/guia-editor#espacios-seguros) y de la [Política contra el acoso](https://programminghistorian.org/es/guia-editor#pol%C3%ADtica-contra-el-acoso)

**Comment by joanacvp** [comment]
> Thank you, @joanacvp! The Wiki is only available in English at the moment, so maybe for that link we can add a note to say _(em Inglês)_?

Yes @anisa-hawes, we can add the note "(em inglês)". It will be better. Thank you :)

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi!

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/french-team. Let me know if anyone has time to offer a translation into French? If so, I can create a new branch and make all the additions in a single pull request. Thank you

**Comment by matgille** [comment]
Hi @anisa-hawes @programminghistorian/french-team, I can submit a translation if you want ! Just let me a day or two, if possible.

**Comment by anisa-hawes** [comment]
Excellent! Thank you, @matgille! Next week is fine -- whenever you have time! The paragraph is [here](https://github.com/programminghistorian/jekyll/blob/676cb0d947581580eb209f544dd1ceab1a6377ac/CODE_OF_CONDUCT.md) in English.

**Comment by matgille** [comment]
Thanks ! I have a question not related to this issue (I want to know if it's worth opening a new issue): I was searching for the Code of Conduct page in the website and couldn't find it; is there a search bar available ? I see a search bar for lessons, but no tool to search the entire website... I think it could be useful for editors and / or translators-reviewers. 

Matthias

**Comment by anisa-hawes** [comment]
Oh! I asked the same question! Actually the Code of Conduct isn't a page on our website, but rather within our Jekyll repository. If you navigate to the Code tab, you will find it in the right-hand column. It is in the About section, underneath the Readme.

![Screenshot 2021-11-11 at 16 44 50](https://user-images.githubusercontent.com/87070441/141336591-b3022c5f-c4b2-4ece-8d51-724518c54190.png)

**Comment by anisa-hawes** [comment]
There is also [an Issue](https://github.com/programminghistorian/jekyll/issues/2324) open about troubleshooting/improving the Search facility, which you could maybe add this idea to @matgille.

**Comment by matgille** [comment]
Thanks @anisa-hawes, I'll do it = )

**Comment by DanielAlvesLABDH** [comment]
> Hi @anisa-hawes! Here follows the PT translation. @DanielAlvesLABDH do you agree with everything? Also, do we have the first linked document translated?
Obrigado pela tradução Joana e obrigado todos por mais este documento.

**Comment by matgille** [comment]
Hi @anisa-hawes, here comes the french translation: 

---

Programming Historian n'a pas de code de conduite proprement dit. Nous proposons plutôt un ensemble de documents qui présentent notre engagement à promouvoir un environnement académique ouvert qui puisse offrir à ses participants et participantes la possibilité d'analyser finement des idées, de poser des questions, de faire des suggestions, demander des précisions ou des éclaircissements, et qui offre aussi à ses contributeurs et contributrices un espace sans harcèlement, dénué de préjugés sur le genre, son identité ou son expression, l'orientation sexuelle, le handicap, l'apparence physique, la corpulence, l'origine ethnique, l'âge, la religion ou l'expérience technique. Nous ne tolérons aucune forme de harcèlement ni aucune attaque *ad hominem*. Les participant(e)s qui ne respecteraient pas ces règles encourent le risque de se voir exclu(e)s de la communauté à la discrétion du comité éditorial. 

À ce propos, nous renvoyons vers un ensemble de documents: 
	- Pour les membres de l'équipe de PH: [Privileges and Responsibilities of Membership](https://github.com/programminghistorian/jekyll/wiki/Privileges-and-Responsibilities-of-Membership) (en anglais)
	- Pour les auteur(e)s: [nous interpeller](https://programminghistorian.org/fr/consignes-auteurs#nous-interpeller)
	- Pour les évaluateur(trice)s: [notre philosophie](https://programminghistorian.org/fr/consignes-evaluateurs#notre-philosophie)
	- Pour les  rédacteur(trice)s: [un espace d’échange sûr](https://programminghistorian.org/fr/consignes-redacteurs#un-espace-d%C3%A9change-s%C3%BBr) et [Politique contre le harcèlement](https://programminghistorian.org/fr/consignes-redacteurs#politique-contre-le-harcèlement)

---

@programminghistorian/french-team anyone to review the translation ? 

Matthias

**Comment by spapastamkou** [comment]
thank you very much, @matgille! it is perfect. I edited directly (to save you time) to make the following changes:  

contributeur(ices)s => contributeurs et contributrices _(pour être en harmonie avec participants et participantes qui précède)_
aucun attaque => aucune attaque _(e oublié)_ 

And in the end of the text these forms only because we have them already like this in the various guidelines.
auteur(ices) => auteur(e)s
évaluateur(ices) => évaluateur(trice)s
rédacteur(ices) => rédacteur(trice)s 
Is that ok with you?

thanks for your work @drjwbaker and  @anisa-hawes!

**Comment by matgille** [comment]
@spapastamkou Thanks ! That's perfect.

**Comment by rivaquiroga** [comment]
@jenniferisasi, I made a small change: "no tiene un código de conducta" -> "no tiene un único código de conducta"
