### ISSUE TITLE
draft of new lesson workflow page

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#237]
I have published a draft of a new lesson workflow page (http://programminghistorian.org/new-lesson-workflow-draft), which is a pretty major overhaul from the previous version that reflects our new submission process. Please edit or flag any potential issues!

There are some other open issues related to images and editorial roles, but I'll address those in future updates. I wanted to get the workflow description settled first.

**Comment by acrymble** [comment]
Thanks Fred. Can we get a few people who hate github to try it for us? Best way to find sticking points, I'd say.

**Comment by acrymble** [comment]
what's the URL for the actual new lessons site?

**Comment by acrymble** [comment]
http://programminghistorian.github.io/ph-submissions/lessons/sample-lesson

**Comment by acrymble** [comment]
Just a couple of comments on the format more than what you have written. I think we should be doing more to make our site visually more recognizeable as a scholarly publication that accepts submissions. There are a lot of stylistic cues that are common to academic journals that we just eschew.

For example:
- http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291468-2281/homepage/ForAuthors.html
- http://www.tandfonline.com/action/authorSubmission?journalCode=rshi20&page=instructions#.VuPTjRhhPa8

These are both run by different companies but they immediately say: this is an academic publication, and you can contribute to it like this. The language and tone too are part of a genre of writing that we don't adopt.

To name a few: They use the horizontal space for menus. Have clearer heading levels (ours are visually quite similar). Make it possible to link to sections by using a sub-menu at the top of the page. Take a professional tone. Clearly separate the 'instructions for authors' from the 'submit' section, etc.

I think we could learn from those if we took a look.

**Comment by fredgibbs** [comment]
Definitely a good point to bring up at the next meeting. I think as the page has grown, it's gotten complex enough that we need better index menus near the top, and need to improve the visual clarity. I deliberately didn't address these in the revision, preferring to wait until we can agree on the content change (and thus know how to structure the menus). Personally, I don't have much desire to emulate the language of Wiley and T&F; I quite like that we haven't. But that's obviously a good topic for our next call.

**Comment by acrymble** [comment]
@fredgibbs do you mind if I get 2 anonymous (I mean arms length) reviewers to look at it as we would with tutorials?

**Comment by fredgibbs** [comment]
I think external reviewers are a great idea. But I think we should talk about it on the next call before we reach out to external readers.
