### ISSUE TITLE
Activities to add to the research / investigacion / recherche / pesquisa pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2385]
Hello all,

I will soon be updating the research / investigacion / recherche / pesquisa pages of our website with some recent activities:

- [Training the Teacher: Giving your first Digital History Workshop](https://www.history.ac.uk/our-century/centenary-events/training-teacher-giving-your-first-digital-history-workshop) with IHR. 18th November 2021 @acrymble and @anisa-hawes 

- [Open Publishing Fest: _Programming Historian_: A Multilingual Open Access Publication](https://openpublishingfest.org/calendar.html#event-69/). 17th November 2021
@svmelton, @rivaquiroga, @joanacvp, @nabsiddiqui 

- Adam Crymble, 'Digital Humanities for the Visually Impaired: Programming Historian's Journey to Accessibility' (UCL, 17 November 2021).

- @jenniferisasi and Brandon Walsh, [_Programming Historian_ Book Club](https://ach.org/blog/2021/09/13/fall-2021-programming-historian-book-club/) The Association for Computers and the Humanities  21st October, 18th November 2021

- Fundação para a Ciência e Tecnologia, através do apoio especial ‘Verão com Ciência 2021’, Portugal. September @programminghistorian/portuguese-team 

- Torre de Babel: Humanidades Digitales multilingües (roundtable discussion) at the [Association of History Literature Science and Technology (AHLiST)'s International Interdisciplinary Conference](http://ahlist.org/wp-content/uploads/2021/11/AHLIST-2021-PROGRAM_Virtual_FINAL.pdf) 19th November 2021 @jenniferisasi @arojascastro

Please let me know if there's anything else you'd like me to add?
@programminghistorian/english-team @programminghistorian/french-team @programminghistorian/spanish-team @programminghistorian/portuguese-team

**Comment by jenniferisasi** [comment]
I'm not sure when in December it will come out, so it depends when you do the updates; but we will soon have an article on _Hispania_ that is an analysis of the translations with do in Spanish. Unless anything changes on their end, this would be the citation: 

Jennifer Isasi and Antonio Rojas Castro. “Sin equivalencia: Una reflexión sobre la traducción al español de recursos educativos abiertos.” _Hispania_ 104.4 (2021): pp. 613-24.

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi. Just a quick note to say that I've added your & @arojascastro's article to my notes for the Newsletter, as issue 104.4 of _Hispania_ doesn't seem to have been published yet.

**Comment by jenniferisasi** [comment]
> Hello @jenniferisasi. Just a quick note to say that I've added your & @arojascastro's article to my notes for the Newsletter, as issue 104.4 of _Hispania_ doesn't seem to have been published yet.

Fab. I think it will come out around the 15th (checking on previous Dec volumes of theirs). I will also open a PR to add it to the research pages once I am notified that it is published.
