### ISSUE TITLE
Team role to maintain and update old lessons

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#239]
Related to @mdlincoln 's #238. It's a big job to keep lessons updated, and often authors just don't have the time or the will to do it. I've noted lots of little errors and broken links when I went through the lessons recently, which suggests we need someone doing a careful sweep of all the lessons, probably once a year.

A 'last updated' alongside the 'date published' would probably be a good idea.

I would suggest that a member of the team brought in to focus on this area would be a good idea, and I propose we discuss that at an editorial meeting.

**Comment by ianmilligan1** [comment]
We discussed this during #242. 

Idea was that the `last updated` entry needs to be a bit more visible and accurate for the lesson. Suggestion to put it at the top of the lesson to give an immediate sense of when it was last maintained, etc. We also now have `deprecated = true` to make clear that a lesson is no longer actively maintained.

**Comment by acrymble** [comment]
Related to last updated might be the idea of adding a version number that auto-generates. That's helpful for citing with confidence, but I don't know if that's easy to do with our setup.

**Comment by acrymble** [comment]
Not going to pursue as this job sucks too  much and no one will want to do it.
