### ISSUE TITLE
Little imprecision in documentation of lev's fonction (Lesson "Generating an Ordered Data Set from an OCR Text File")

### ISSUE THREAD

**Issue by InesSalome** [programminghistorian/jekyll#2396]
As mentioned in a [comment](https://github.com/programminghistorian/ph-submissions/issues/362#issuecomment-972935952) from the issue #362 _in_ ph-submissions repository, I noticed during my work of editor for lesson's translation _[Generating an Ordered Data Set from an OCR Text File](https://programminghistorian.org/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file)_ e little imprecision in the documentation of lev's fonction in the part about [Levenshtein distance](https://programminghistorian.org/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file#levenshtein-distance). Actually, fonction's parameters in the lesson are `seq1` and `seq2`, but the parameters mentioned in the documentation are those of the tutorial from which the [code](https://www.datacamp.com/community/tutorials/fuzzy-string-python) is ripped (`s` and `t`). 

It's not urgent but maybe it would be more precised to replace `s` and `t` by the parameters used in the lesson's code `seq1` and `seq2` ? 

I can do this if you want @programminghistorian/english-team.

**Comment by anisa-hawes** [comment]
Thank you for noting this, @InesSalome. I can take care of making the change!

**Comment by anisa-hawes** [comment]
Apologies for the delay, @InesSalome! I made a mistake within the previous PR, so have closed it and created a fresh one. 
Thank you again for spotting this error!

**Comment by InesSalome** [comment]
No problem !

**Comment by anisa-hawes** [comment]
Hmmm... Although I used the phrase "Closes #2396" in [PR 2420](https://github.com/programminghistorian/jekyll/pull/2420) this Issue hasn't closed. So I am closing it now.
