### ISSUE TITLE
trouble adding new author to new repo

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#240]
I'm trying to add @mhbeals to our new repo, but I get a message that she doesn't exist.
![unnamed](https://cloud.githubusercontent.com/assets/646647/13722581/3d7a93f2-e842-11e5-9b14-718cba7b90a5.png)

Any advice @wcaleb ?

**Comment by fredgibbs** [comment]
I've always found it easier to search via username; so I just added @mhbeals.
