### ISSUE TITLE
Improving communication with our IPPs

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2402]
We've recently received some feedback from one of our new IPPs, relating to how our Communications with them could be improved. 

One idea proposed is that we could send a "Welcome" email upon their joining, including general information about the AGM and how/when memberships are renewed. This could be something we create once, as a template to re-use.

Another idea is that we create an IPP mailing list, via which we circulate a semi-regular Newsletter including information about upcoming events or activities. 

My sense is that these Communications could be woven into the writing of our quarterly Newsletter/Blog* and updates to the Research pages of our website.

*the continuation of its precise format will be reviewed in the New Year.

Please let me know what you think, and if you have any ideas you'd like to share @programminghistorian/english-team @programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team.

**Comment by jenniferisasi** [comment]
@anisa-hawes for one thing, creating a pretty PDF out of the markdown file that we use to create the newsletters is super easy

**Comment by anisa-hawes** [comment]
A few ideas which have come out of a conversation with Adam:

The Issue is really about "community building" and so it may be worth bringing our Patreon supporters into this circle of people who we would like to keep better informed.

Perhaps the revised newsletter format should become something aimed at the Team + IPP contacts + Patreon members + potential supporters? Rather than an update aimed at users and educators more generally. 

With these thoughts in mind, I'm going to link this Issue to #2257. I'm not certain if we have any volunteers to take on the responsibility for Patreon leadership? But maybe I could do it (or at least share it?)

**Comment by drjwbaker** [comment]
> I'm not certain if we have any volunteers to take on the responsibility for Patreon leadership? But maybe I could do it (or at least share it?)

I'm concerned about your workload. Do you really have capacity?

**Comment by anisa-hawes** [comment]
Thank you, James. I'm not sure... I would certainly need to better understand what Patreon leadership requires. But if it was writing and circulating a Newsletter (a version of which I am writing anyway, for the moment) I think I could do (at least this share of) it.

**Comment by drjwbaker** [comment]
I guess it depends if we want to maintain what we have on Patreon (a group of patrons who got us going, but are losing numbers as people's bank details become out of date), or grow that part. I'd assume the former, seen as IPPs are more fundamental to our economic sustainability.

**Comment by anisa-hawes** [comment]
I think this is something we could discuss within our forthcoming Project Team Meeting. As we agree which goals we want to focus on in the coming year, we will be able to clarify which areas we want to dedicate our energy and resources to.

**Comment by anisa-hawes** [comment]
This is a small thing: but it would help me to know which Twitter handle(s) to mention when I post our "welcome" Tweet. 

Earlier this week, I used the University of Nebraska-Lincoln handle https://twitter.com/UNLincoln but realise now that I should have used https://twitter.com/CDRH_UNL to connect directly with The Center for Digital Research in the Humanities.

**Comment by anisa-hawes** [comment]
Happy news: our Patreon community continues to grow! Yesterday we welcomed our second new Apprentice-level supporter this year.

I noticed that two others' subscriptions expire at the beginning of next month, and I'd like to ask if we have written to Patreons in the past to encourage them to renew in the same way as we do for IPPs? I could adjust the email we sent to several organisations recently, and send a note?

**Comment by jenniferisasi** [comment]
Great news!

Although all this is more of @acrymble’s purview, I think it’s a good idea to reach out to them via email.

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi! I'll chat with Adam about the specifics, and prepare an email. 

Update: Now we welcome our *third* new Patreon member!

**Comment by anisa-hawes** [comment]
We are progressing with the recruitment process to appoint an Education and Community Lead, whose responsibilities will include: building relationships with current and potential supporters, as well as developing a programme of activities to support our Patreons and Institutional Partners.
