### ISSUE TITLE
Programming Historian - Reviewer Tracking sheet

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#2405]
I've just noticed that @jerielizabeth is the owner of this sheet. Should we move ownership onto the shared gmail?

**Comment by anisa-hawes** [comment]
Good idea, @drjwbaker. Shall we also do this for these two Google Sheets: 

- Twitter Bot 
- Lesson Concordance (are you the owner at the moment, @jenniferisasi?)

**Comment by drjwbaker** [comment]
I guess the priority are docs not currently owned by a member of the team. But as good practice, yes, the shared gmail should own all critical documents.

**Comment by jerielizabeth** [comment]
Hi all - sorry for the delay. End of term. 

What is the shared gmail? I am happy to transfer ownership of the document.

**Comment by anisa-hawes** [comment]
Thank you, @jerielizabeth. Our shared Gmail address is <programminghistorian@gmail.com>

**Comment by jerielizabeth** [comment]
Ownership transfer initiated on my end.

**Comment by drjwbaker** [comment]
Got it. Thanks @jerielizabeth.

**Comment by anisa-hawes** [comment]
Just to confirm: the shared Gmail is now the owner of both the Twitter Bot & Lesson Concordance Google Sheets as well as the Reviewer Tracker. Thanks all!
