### ISSUE TITLE
Adding new Patreon to en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2417]
I am adding Mike Bess to our lists en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores

**Comment by drjwbaker** [comment]
Is he a Patron or Educator level supporter? (if so, apologies for missing that)

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker! I have spoken with Adam, who explained that Apprentice level supporters aren't added to the website. I've closed this Issue. Apologies for the misunderstanding!

**Comment by drjwbaker** [comment]
I did wonder. It says here https://programminghistorian.org/en/supporters which 'levels' we recognise on the site. No worries, we have complicated ways of doing things!
