### ISSUE TITLE
Editorial Meeting agenda 29/03/16

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#242]
Hi fellow editors. I'm chairing the meeting today, so as per usual please nominate any issues from the github list that you think we should focus on for our upcoming meeting on Tuesday.

**Comment by ianmilligan1** [comment]
I think we should talk about #239; #237; #229; #220; #189; and #172. We should also chat about #143 - I think we struck a subcommittee but it hasn't met yet.

**Comment by acrymble** [comment]
Thanks @ianmilligan1. Did I get any actions out of this? Sorry I missed the meeting.

**Comment by ianmilligan1** [comment]
No actions for you, other than to keep on doing what you're doing! :smile:
