### ISSUE TITLE
Create banner on "Report a bug" page

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2423]
After several users creating PRs (from forks in their repo) directly to make changes to our materials, @anisa-hawes and I have decided to add a banner on the "Report a bug" site explicitly telling users NOT to do PRs. It might not be followed by all, but it doesn't cost us to add a banner and also gives Anisa a place to direct PR creators and say "it is a rule".

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. Things would certainly be much simpler for me to manage if we could discourage this.

I'd like to suggest that we also remove these sentences:

"If you believe you know how to fix the problem in the lesson, you may wish to consider forking our repository and making a pull request.

For more information about pull requests, see the GitHub Guide on Forking Projects or Rich Jones’s tutorial on How to GitHub."
