### ISSUE TITLE
New section to display awards in About page 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2442]
Programming Historian was the recipient of an Open Content category award in the Open Publishing Award 2021 https://openpublishingawards.org/results/2021/index.html 

This has prompted a conversation about displaying our awards somewhere in our website. The simple addition can happen in the About page in a new section that we can create; if we want to display logos for each award I believe it will work best if we place them at the end of the page. But open to other suggestions.

**Comment by drjwbaker** [comment]
Thanks for opening this. One option could be to make a version of https://github.com/programminghistorian/jekyll/blob/gh-pages/images/about.png that contains logos. But that might get messy. Or noting also what OLH does https://www.openlibhums.org/site/about/ something on the about page, but between sections rather than at the bottom, perhaps around the 'open' section.

**Comment by anisa-hawes** [comment]
Yes, I think that sounds good. And agree that, in this case, it would fit well with the Open Source and Gold Open Access sections. But considering previous (and future) awards that may not be specific to "openness" a dedicated section headed "Awards" might be preferred. Perhaps at the very top of the About page, we could add a general introductory section to say what _Programming Historian_ is, and then summarise our awards/achievements?

**Comment by acrymble** [comment]
If you're updating the page it might be worth switching "Gold" to "Diamond" in our publishing model, as Gold implies that you pay to make it open. Diamond is open by default. That may be on other pages too

**Comment by drjwbaker** [comment]
So annoying that 'Gold' as been tainted by association with APCs. Anyway, we should cite this diagram as explanation https://doi.org/10.6084/m9.figshare.6900566.v1

**Comment by anisa-hawes** [comment]
Do we already have list of the awards _Programming Historian_ has won in the past?

I know of the following:

**2021**
- [Coko Foundation's Open Publishing Award](https://openpublishingawards.org/results/2021/index.html) (Open Content category)

**2020**
- [Canadian Social Knowledge Institute's Open Scholarship Award](https://etcl.uvic.ca/events-activities/open-scholarship-awards/)

**2018**
- ‘[The Programming Historian en español](https://programminghistorian.org/es/)’, Winner of "Mejor iniciativa formativa desarrollada durante el año 2018", [Humanidades Digitales Hispánicas Association](http://humanidadesdigitaleshispanicas.es/)

**2017**
- ‘[The Programming Historian en español](https://programminghistorian.org/es/)’, Winner of Digital Humanities Award (Best Series of Posts category)

**2016**  
- ‘[The Programming Historian in English](https://programminghistorian.org/en/)', Winner of Digital Humanities Award (Best Series of Posts category)

Could others help me to fill in the gaps?

**Comment by drjwbaker** [comment]
‘[The Programming Historian en español](https://programminghistorian.org/es/)’, Winner of "Mejor iniciativa formativa desarrollada durante el año 2018", [Humanidades Digitales Hispánicas Association](http://humanidadesdigitaleshispanicas.es/).

**Comment by acrymble** [comment]
2021, Open Publishing Award, Coko Foundation
2020, Open Scholarship Award, Canadian Social Knowledge Institute

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi. I've created [a new branch](https://github.com/programminghistorian/jekyll/tree/Issue-2489-and-2442) containing a draft Awards section within en/about.md.

Do you have time to review the wording and check you're happy with this approach?

You'll see that I've also made the following changes:
- replaced "Gold" with "Diamond" in relation to our publishing model 
- adapted the History of the Project section to integrate a link to Turkel's blog (see also #2489)

When we've agreed that this is a good way to move forwards, we can ask our FR and PT colleagues for their assistance with translations. Thank you.
