### ISSUE TITLE
Happy Holidays / Merry Christmas / Feliz Navidad / Joyeux Noël /  Feliz Natal

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2449]
Tomorrow will be my last working day of 2021 and I wanted to take this opportunity to thank you all for making me feel so welcome at _Programming Historian_. I am enormously grateful for your generosity and patience as I have found my way these past six months.  

Wishing you all a restful break, whatever traditions or celebrations you may share. 

Thank you for the very generous Book Token gift. It will be such a treat to choose some new reading! 

I have been making 'cards' for my family and friends, and would like to send this digital one to you all: 

![01](https://user-images.githubusercontent.com/87070441/146940833-8dc542c9-8f94-45a6-ba94-6b64eb256c2a.JPG)
![02](https://user-images.githubusercontent.com/87070441/146940836-f203b189-b9ee-4f41-bed9-d9c72fd7ceba.JPG)
![03](https://user-images.githubusercontent.com/87070441/146940844-a7a4ee5f-fb1b-44d3-b634-e4301d1fa2c7.JPG)

**Comment by spapastamkou** [comment]
Merry Xmas to you too, @anisa-hawes! A huge thanks for all you have accomplished here.

**Comment by mariajoafana** [comment]
Merry Christmas @anisa-hawes ! Best wishes and thanks for all your hard work

**Comment by jenniferisasi** [comment]
¡Feliz Navidad, @anisa-hawes! Lovely 3D 'card' in 2D photographs 😃 My best wishes for a restful break after so much hard work all these months 🙏

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes , many thanks for the message, for the wishes and for all your wonderful work with us. Boas Festas e Feliz Ano Novo!

**Comment by rivaquiroga** [comment]
¡Feliz navidad y próspero año nuevo! Thank you for all your hard work.
