### ISSUE TITLE
Alternative reference link in en/introduction-to-ffmpeg es/lecciones/introduccion-a-ffmpeg?

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2451]
A reader has got in touch to suggest introducing an alternative reference link in:

EN Introduction to Audiovisual Transcoding, Editing, and Color Analysis with FFmpeg
ES Introducción a la transcodificación, edición y visualización de datos audiovisuales con FFmpeg

The section [Graphing Color Data](https://programminghistorian.org/en/lessons/introduction-to-ffmpeg#graphing-color-data) / [Visualizando datos de color](https://programminghistorian.org/es/lecciones/introduccion-a-ffmpeg#visualizando-datos-de-color)  includes a link to [a WikiHow tutorial](https://www.wikihow.com/Create-a-Graph-in-Excel). Our reader is suggesting that we either replace or supplement this with [this alternative](https://computeexpert.com/english-blog/excel-tips-and-trick/how-to-make-a-chart-in-excel) from their own website. 

I wonder what you think? My view is that the WikiHow page is much 'lighter' in terms of its resource, with fewer advertisements and sponsored links. My instinct would be that we keep this as is, but I would be pleased to hear if you have a view on this @svmelton and @rivaquiroga. 

Meanwhile, he thanks us for this lesson, which he says "gives much knowledge and insight about FFmpeg" adding that "it seems to get all the basic things that we should learn related to FFmpeg".

**Comment by jenniferisasi** [comment]
It is great to hear about how our readers find lessons useful! 

Regarding that personal website, it opens other promotional websites for me within 10 seconds of landing. So it is not secure and will not be sustainable in the long term. My 2 cents

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. Yes, I do feel it's best to leave it as is (WikiHow) to avoid those advertisements and sponsored links. Just thought I should ask for others' thoughts before replying to explain that choice.

**Comment by rivaquiroga** [comment]
I agree. Better to keep it as is.

**Comment by anisa-hawes** [comment]
I have replied to the reader, explaining our decision to leave the WikiHow link unchanged. Thank you both!
