### ISSUE TITLE
User reported issues: Intro to Google Maps and Google Earth

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2456]
A reader has got in touch to let us know about two issues they encountered within our lesson 'Intro to Google Maps and Google Earth'

en/lessons/googlemaps-googleearth
es/lecciones/intro-a-google-maps-y-google-earth

1. In the Google Earth section, the reader suggests that we replace this link <http://www.google.com/earth/index.html> to the browser-based version of GE with this <https://www.google.com/intl/eng/earth/versions/#earth-pro> to the Desktop version.

2. The reader notes that in the version of GE they used (7.3.4.8248 (64-bit)) the seaway routes in the provided KML-file do not appear.

This reader is working on a PC running Windows 10.

**Comment by DanielAlvesLABDH** [comment]
@joanacvp this issue is similar to the one reported by Angela on the translation to pt isn't?

**Comment by joanacvp** [comment]
yes it is @DanielAlvesLABDH.
I will send it to Angela

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH and @joanacvp. I'll update you both here when I have tested this so you can pass on the information to your translator Angela. Which Issue is her report detailed in?

**Comment by anisa-hawes** [comment]
Okay. I have tested this twice now (on Windows 10 and on my macOS Big Sur v.11.5.2), and I am encountering the same issue as our reader. 

I'm able to successfully load the KML file into Google Earth Pro desktop (7.3.4.8248 (64-bit)) but I don't see the old canals or current Seaway routes that were traced in different line colours and widths onto Dan’s Seaway map. Is this what your colleague Angela encountered, @joanacvp? 

Here's a screenshot of the location on Windows 10. (Note: no pre-traced lines or routes)

<img width="985" alt="Screenshot 2022-01-14 at 14 36 24" src="https://user-images.githubusercontent.com/87070441/149534049-d687ef43-67a2-4f1b-a052-638b02f3ad0e.png">

Pop-up information box for the map indicates that a "blue line indicates the seaway navigation channel, running from Montreal to Lake Erie. Locks, dams, and other points of interest are marked, including pictures. The green line indicates the longer Great Lakes-St. Lawrence water route that the seaway made possible. Pre-seaway canals are marked in pink". but none of these lines or annotations are visible.

**Comment by joanacvp** [comment]
Hello @anisa-hawes . Sorry for the late reply. In the PT version Angela tried to explain how to get to the desktop version to solve that problem. I already contacted Angela to see if she can help us with this.

**Comment by anisa-hawes** [comment]
No problem, @joanacvp. I know how busy you all are! 

I used the desktop version (Google Earth Pro desktop v.7.3.4.8248 (64-bit)) but was unable to see any of the pre-traced lines or routes. 

I would be really interested to hear about Angela's proposed solution when she has time.

**Comment by Angelaimp** [comment]
Hello @anisa-hawes. Also sorry for the late reply. Yes, those were the same issues I identified. I could not see any of the details that should be featured in the the KML-file. Regarding the link for the GE Desktop version, in the translation I made I used the link provided in the lesson (in its portuguese version) and explained how to get to this version. (But I gess a direct link to it is easier, so I'll make that adjustment in the translation file).

**Comment by Angelaimp** [comment]
About a solution for the KML-file issue, in the translation we kept it the same (and used the images from the original lesson), and were also going to do a report about it once it was really finished.

**Comment by anisa-hawes** [comment]
Thank you, @Angelaimp. Okay. 

In this case, perhaps it would be worth us connecting with the original authors to see if they could re-issue/update the KML file.

This is a popular entry-level lesson, which I know has been used by colleagues at Edinburgh University in their undergraduate teaching programme. I think it would be good to try to resolve this problem if we can.

How would you feel about me contacting the authors @svmelton?

**Comment by svmelton** [comment]
Thanks for raising this @anisa-hawes! Yes, please go ahead and contact the authors.

**Comment by anisa-hawes** [comment]
Thank you, @svmelton. I will put it on my list for next week! 

I'll keep you updated too, @Angelaimp!

**Comment by Angelaimp** [comment]
Thank you so much @anisa-hawes ! 
We will finish the translation and adapt it if necessary

**Comment by anisa-hawes** [comment]
Hello @Angelaimp. Just a quick update: I've written to the authors today and will let you as soon as I hear back from them.

**Comment by anisa-hawes** [comment]
Update: I've followed up with the authors today, to ask if updating the KML file is practicable + suggest an interim option is to apply an alert/information box to the lesson, that lets readers know lines and routes displayed on the map aren’t quite as described due to subsequent updates.

**Comment by Angelaimp** [comment]
Thanks @anisa-hawes! I'll add that suggestion to the translation file.

**Comment by anisa-hawes** [comment]
I'm adding an alert information box to this lesson, which includes a link to this Issue:

> <div class="alert alert-info">
Updates to Google Earth since the publication of this lesson in 2013, mean that some users of Google Earth Pro Desktop v.7.3.4.8248 (64-bit) may find that they are unable to view the Seaway routes that should be featured in the the KML-file. <a href="https://github.com/programminghistorian/jekyll/issues/2456">We are investigating this issue</a>. (March 2022)
</div>

In the same PR, I'll update the Install link to https://www.google.com/intl/eng/earth/versions/#earth-pro as suggested.

I will open a future Issue to update the KML asset if the authors advise that this could solve the problem.

**Comment by Angelaimp** [comment]
Thanks for this solution @anisa-hawes! I have now translated and incorporated the information box in the shared lesson translation file (with the pt-br translation team), maintaining the link to this issue.

While integrating the pt-pt and pt-br versions I also noticed that there was an extra link that did not appear in the original English version, related to the map of Aultsville, in the "Adding Scanned Historical Maps" section in the final part of the lesson: https://digital.library.mcgill.ca/countyatlas/showtown2.php?TownID=Aultsville

**Comment by Angelaimp** [comment]
I don´t know if this is the place to ask this (and sorry if it isn´t!), but also due to the different Portuguese versions of the softwares (pt-pt and pt-br) we were wondering if it was possible to incorporate a link in the end of the lesson to a repository of images (another file in GitHub) with the pt-br version of the software?... 
Thank you very much, @anisa-hawes, for your input and assistance!
