### ISSUE TITLE
Update PayPal link on Twitter Bot Google Sheet

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2458]
We [recently Tweeted](https://twitter.com/ProgHist/status/1475391142065848323?s=20) a link to our PayPal donations page, and received [a reply](https://twitter.com/11enbeinturm/status/1475402559422615554?s=20) to let us know that the link was broken! 

[I've replied](https://twitter.com/ProgHist/status/1478788336869384199?s=20) to share the correct link, but would like to update our Twitter Bot Google Sheet so that we don't make this mistake again! 

We need to update the Tweets in cells C10, C11, and C12 on the Communications tab of the sheet.

The correct link is: https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=7BGHUZRVS4LYL&source=url
I've shortened it using bit.ly: https://bit.ly/3eTCqSt

**Comment by jenniferisasi** [comment]
I made the change that same day @anisa-hawes, apologies because I forgot to open a ticket about it though.

**Comment by anisa-hawes** [comment]
Ah! Thank you, @jenniferisasi! You are steps ahead!
