### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#246]
This start of a Spanish translation was brougth to my attention via Twitter: http://cibercliografia.org/manuales/introduccion-a-python/

I wonder if this is something we can support more actively?

**Comment by juancobo** [comment]
Hello! Some colleagues and I run a non-profit in Colombia devoted to digitising the holdings of endangered archives and libraries and promoting the digital humanities in the country more broadly (www.neogranadina.org). I came across your tutorials a few years ago and found them extremely useful, and I've used them more recently to train our student interns. My colleagues and I have spoken about approaching you to discuss offering to help with translations, but I hadn't seen this open issue until now. We'd love for these materials to be more accessible to Spanish speakers. How can we help?

**Comment by acrymble** [comment]
Thanks @juancobo for getting in touch. I for one think this would be a great way for the project to branch out. All of the lessons are already licensed CC-BY so anyone could in practice translate and post whatever they want. But I wonder if this isn't something we could integrate more closely with the rest of the site if we had enough interest to start translating (or even writing in Spanish and translating to English)? @wcaleb is this easy to integrate multiple instances of lessons into the navigation?

Problems of keeping lessons in sync as minor tweaks are made is something we'd have to figure out, but I am supportive of ideas to reach new communities.

**Comment by acrymble** [comment]
We've had someone come forth offering to translate @mdlincoln 's SPARQL tutorial intot Spanish. They'd like to incorporate the translation into the site. I think we've now got evidence that we've got a market for Spanish translation as a start.

My suggestion is that the editorial board moves on this quickly to keep this momentum. I'd like to suggest we seek a dedicated Spanish editor to lead this task for us in an ongoing capacity and to work with us to integrate the material into our existing site. Let's discuss this at the editorial meeting.

**Comment by ianmilligan1** [comment]
Sounds good, @acrymble.

**Comment by jerielizabeth** [comment]
Sounds good to me!!

## 

Jeri E. Wieringa
Digital Publishing Production Lead, George Mason University Libraries
PhD Candidate, Department of History and Art History
George Mason University
www.jeriwieringa.com

**Comment by wcaleb** [comment]
Things to discuss at #261:
- [x] recruiting of an editor
- [x] how/whether to actually integrate under our site, or different URL/fork 

Could potentially use [CSS selectors](http://stackoverflow.com/a/4718706), but this would make our lesson files very long and bulky. Another option could be to treat translations as `_includes`.

**Comment by ianmilligan1** [comment]
We discussed this on our call:
- recruiting of an editor, if we have an open call we could put this in a bullet point list of things we're interested in;
- if it's just one or two lessons at this point, we'll incorporate with links on the lesson homepage as well as the lessons itself to Spanish (or other language options).

**Comment by acrymble** [comment]
Should I hold off drafting a recruitment text till next meeting? Sorry just about to board plane. But they had wifi :)

**Comment by wcaleb** [comment]
If you want to draft something, that would be fine---our thought was to write a blog post listing some of the editorial needs that we currently have (translation, ombudsperson, social media, Software Carpentry) in a bullet-type list. In addition to publishing that, we also discussed a few specific people that we could specifically send the list of needs to, inviting them to join us as editor either in one of those specific roles or not. @jerielizabeth and @wcaleb agreed to draft those emails.

**Comment by acrymble** [comment]
We are currently actively recruiting for this role. Please see full details: http://programminghistorian.org/posts/spanish-editor

**Comment by ajspadial** [comment]
@ivetteaddington 's blog (http://ivetteaddington.com/post1/) includes some ideas for making a multilingual Jekyll.

**Comment by IvetteAddington** [comment]
Thanks @ajspadial for the blog post shout out!
If anyone has any question about the code or if there is anything I can do to contribute to making the site bilingual, please let me know.

**Comment by versae** [comment]
Well, I always liked the Programming Historian idea, and even tried to get one story published once, and I think I can help with the Spanish version, maybe even under `http://es.programminghistorian.org`, ala Wikipedia, defaulting to English.

**Comment by acrymble** [comment]
Just a point of clarification because I've had a few queries and misunderstandings.

This is not a job posting. It's a posting for an academic service position. You don't need to have a PhD to apply.

We're also not expecting the person to sit down and translate everything for us. We'd like the material to start shifting into Spanish over time, but we're looking for someone to be active participants in our project, with a focus on the Spanish-speaking world. In other words, we're after an enthusiastic and safe pair of hands to take a lead on a new initiative.

If anyone has specific questions you can email me at adam.crymble@gmail.com

And thanks to those of you for your technical suggestions. They look like good conversations to have.

**Comment by vgayolrs** [comment]
Hi, I'm one of the Cibercliografia's editors who began, few months ago, the translation of the programming historian. I stopped it, among other things, because I had lot of academic workload (I was teaching Spring 2016, finishing a book, etc...), and because I saw that it has appeared the printed version (PDF), with some changes. I will be very interested in continue working with the spanish translation, but in coordination with a team to upgrade the information. I have some drafts of lessons we didn't published in Cibercliografía yet, that could help. We need those lessons in spanish (and further collaboration in digital history), so here I am.

**Comment by acrymble** [comment]
Thanks @vgayolrs. Is that an official expression of interest?

**Comment by acrymble** [comment]
The DH+LIB group are looking into translation of DH materials. Worth keeping them in mind and reaching out when we can: http://acrl.ala.org/dh/2016/06/22/building-a-dhlib-community-with-a-global-outlook/

**Comment by vgayolrs** [comment]
You're wellcome @acrymble . Yes, it is. I can star by reviewing the materials I've translated. By the other hand, I'm in touch with two postgraduate students, very fluent in Spanish and English (and interested in DH), with whom we can work in coordination. Translate to Spanish The Programming Historian (or anything that refers to Digital History),  also means adapting it to the Spanish-speakin scholars reality, and discuss some problems (for example, there is not a digital repository of historical records in Spanish with the characteristics of The Old Bailey On Line and so on...). All in all, translation is the first steep. We can continue with the Cibercliografía's project, but it's better to combine efforts.

**Comment by acrymble** [comment]
Thanks @vgayolrs we've still got the nomination process open until the end of July, but we'll be in touch shortly thereafter.

**Comment by acrymble** [comment]
Thanks to everyone who has applied. We'll be in touch with you shortly. This issue is now closed.
