### ISSUE TITLE
Rescale oversized gallery images

### ISSUE THREAD

**Issue by bmschmidt** [programminghistorian/jekyll#2463]
Most lesson thumbnails in the gallery are about 50K and an appropriate size (like 128x128 or something).

But three are much larger, and should be rescaled in `/gallery` to save everyone storage and bandwidth costs.

```
-rw-r--r--@   1 bschmidt  staff   512K Dec 31 13:39 detecting-text-reuse-with-passim.png
-rw-r--r--@   1 bschmidt  staff   212K Dec 31 13:39 working-with-batches-of-pdf-files.png
-rw-r--r--@   1 bschmidt  staff   180K Dec 31 13:39 gravity-model.png
```

**Comment by anisa-hawes** [comment]
Hello @bmschmidt. Thank you for noticing this. Yes, we aim to resize our Gallery images so that their dimensions are ~200x200 pixels. Perhaps that step has been missed in these cases. I'll take care of resizing them to put it right.
