### ISSUE TITLE
Don't accidentally bundle lessons in content.

### ISSUE THREAD

**Issue by bmschmidt** [programminghistorian/jekyll#2465]
The single HTML file (not images, not js, etc) at `https://programminghistorian.org/en/lessons/index.html` is about 869K, which is much larger than it should be. Viewing the source, it appears to include the full text of all English language lessons inside of it as comments that no one will ever see.

I believe the problem should be solved [here](https://github.com/programminghistorian/jekyll/pull/2464)

The issue seems to be this HTML comment below. I think that Jekyll is running the last block and including full text for all lessons. I don't know what `list.js` is or whether there's anything in this comment that should be documented elsewhere.

```html
  <!-- Uncomment if you want to include lesson content for List.JS -->
  <!-- <span id="{{lesson.url}}-content" class="content"
    style="display: none;">{{ lesson.content | markdownify | strip_html }}</span> -->
```

Associated code:

https://github.com/programminghistorian/jekyll/blob/ab91b960c1876738808db3cc9d136d1e223abd10/_includes/lesson_describe.html#L36-L38

**Comment by ZoeLeBlanc** [comment]
Thanks for finding this @bmschmidt ! Definite mea culpa since I was the one that added that comment. Just waiting for the build to finish and then we'll merge this in and close the issue 👍🏽
