### ISSUE TITLE
How does suggestion citiation work on the site?

### ISSUE THREAD

**Issue by vidhyav656** [programminghistorian/jekyll#2466]
The need is exact steps to take the implementation.

**Comment by acrymble** [comment]
Hi @vidhyav656 the suggested citation is based on the format in the Chicago Manual of Style, which is a fairly common format used by historians who publish in English (I don't know about in other languages).

**Comment by vidhyav656** [comment]
How is the implementation is done on the site? I want to use the same. I am looking for some wiki or docs to implement.

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/technical-team. Is anyone able to advise @vidhyav656 about how our citations are implemented? Thank you!

**Comment by acrymble** [comment]
It's built up from metadata we collect. On our site you can find the code here:

https://github.com/programminghistorian/jekyll/blob/gh-pages/_layouts/lesson.html

on lines 282-291. But our site is custom, so it's unlikely that you could just cut and paste the code.

**Comment by vidhyav656** [comment]
@acrymble @anisa-hawes Thank you so much.
