### ISSUE TITLE
QGIS and OS X

### ISSUE THREAD

**Issue by Anterotesis** [programminghistorian/jekyll#247]
The lesson Installing QGis
http://programminghistorian.org/lessons/qgis-layers
states:
"(this works with Lion, Mountain Lion, and Snow Leopard – no word yet on using it with the forthcoming Mavericks)"
I can confirm that QGis works with the latest OS X 'El Capitan' 10.11.4.
The text can be updated to reflect this.

**Comment by ianmilligan1** [comment]
Great, I will update the text. Thanks @Anterotesis!
