### ISSUE TITLE
Add info box about new version of AntConc

### ISSUE THREAD

**Issue by svmelton** [programminghistorian/jekyll#2477]
Heather Froehlich, the author of [Corpus Analysis with Antconc](https://programminghistorian.org/en/lessons/corpus-analysis-with-antconc), wrote to let us know that there has been a significant update to the software. She asked if we could include an info box letting readers know that this tutorial is still functional but relies on an older version of the software that may not look like the most recent version. I have created a PR for this issue (#2476).

**Comment by acrymble** [comment]
@svmelton you could assign this to @anisa-hawes as it's a lesson maintenance task.

**Comment by anisa-hawes** [comment]
Closed by PR #2476.
Closing phrase did not close this issue.
