### ISSUE TITLE
Board of Trustees Meeting: 18 February 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2478]
Board of Trustees Meeting: 18 February 2022

Date: **18 February 2022** Thank you for filling in your availability in our [this Doodle Poll](https://doodle.com/poll/m3axbagxerhvcrhg)
Time: **14:00 UTC**

Zoom link: https://ucl.zoom.us/j/96056624496

Chair: @acrymble
Secretary: @anisa-hawes
Members: @drjwbaker @svmelton @spapastamkou @amsichani @rivaquiroga
Minutes of the last meeting: [10-2021/BoT_minutes.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2021/10-2021/BoT_minutes.md)

---

Hello all,

**I'm creating this issue so that we can begin to draft our agenda for February's BoT meeting.**
Please feel free to edit this agenda, and add further Items for discussion below

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf),  I'd like to ask that new agenda Items are added **in advance of the meeting** so that all attendees have sufficient time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions.  

### Agenda

- Apologies  
- Approval of Minutes from last meeting & actions status.
- ProgHist Directors administration (e.g., changes of address)
- Staffing @drjwbaker
- Structure @acrymble 
- Our forthcoming AGM
- [Mat/Paternity Leave](https://knowhow.ncvo.org.uk/your-team/hr/managing-annual-parental-and-compassionate-dependants-leave/parental-leave) @drjwbaker @amsichani 
- Any Other Business
- Agree date of next meeting

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by spapastamkou** [comment]
@drjwbaker You 'll be on paternity leave! Congrats!

**Comment by drjwbaker** [comment]
Not me @spapastamkou!
We just need to talk about our policy on this.

**Comment by anisa-hawes** [comment]
Hello all,

I have uploaded the minutes of our February Board of Trustees Meeting to the Charity sub-directory of our Project and Business repository. 

You can review them here: https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/02-2022/BoT-18-02-2022.md in Markdown format.

Please let me know if I've missed any key points or mis-represented something you said. I'm more than happy to make adjustments. I'll create a watermarked PDF when the minutes have been approved by you all. 

With thanks,
Anisa

**Comment by drjwbaker** [comment]
Thanks Anisa. Key points looks good.
