### ISSUE TITLE
Typo in "Intro to Bash"

### ISSUE THREAD

**Issue by briancroxall** [programminghistorian/jekyll#2484]
There is currently a typo in the [Intro to Bash](https://programminghistorian.org/en/lessons/intro-to-bash) lesson. Under `Interacting with Files`, the second paragraph begins as follows:

> Here’s a few basic ways to do interact with files.

It should probably be changed to 

> Here's a few basic ways to ~~do~~ interact with files.

**Comment by anisa-hawes** [comment]
Thank you for letting us know, @briancroxall! I'll take care of correcting this.
