### ISSUE TITLE
Project Team Meeting: Friday 11th March 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2486]
Minutes of our December meeting are available [here](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2021/12_2021_ProjectTeamMeeting.md).

Date: Friday 11th March
Thank you for filling in your availability via the [Doodle Poll](https://doodle.com/poll/ufn9aykpchvk9w9m?utm_source=poll&utm_medium=link)

Time: [08:00 COT / 13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220311T130000&p1=41&p2=1440)

Maria José @mariajoafana will initiate our call.
Zoom link: https://uniandes-edu-co.zoom.us/j/81805587005

--

Team Leaders: please add a brief update of your Team's key activities before we meet.

@programminghistorian/english-team
@programminghistorian/spanish-team
@programminghistorian/french-team
@programminghistorian/portuguese-team 

All members who would like to join us are welcome.

Project Team Meeting
---

This meeting will take the form of a group discussion, zooming in on some of our Shared Goals for 2022.

**1. Drive and anticipate the future needs of our field** 
Actively setting the skills agenda in Digital Humanities

**2. Expand our educational outreach programme** 
Collaborating with universities, libraries and educators to promote and improve our lessons

**Comment by anisa-hawes** [comment]
Sincere apologies for any confusion I have caused with the timing of this meeting.

I didn't notice that the Doodle system had located my time-zone incorrectly. Having spoken with colleagues, I realise that the Poll options given were one hour earlier than I'd advertised in this Issue. 

So, to be consistent with the Poll options which _I believe you saw_: will meet at [**08:00 Columbia Time**](https://www.timeanddate.com/worldclock/converter.html?iso=20220311T130000&p1=41)

**Comment by jenniferisasi** [comment]
@anisa-hawes I don't think anyone has ever set-up these meetings without mistaking time-zones (+ daylight savings different changes) at least once haha so no worries. 

For this particular meeting, set at 8AM Colombia, I can certainly be there 8AM too and maybe everyone in the US East Coast can... but it would be asking some others to be on Zoom at 7AM (ie Zoe) to 5AM (ie Scott). Maybe it's OK this time and no need to change, they may skip the meeting.

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. [Going forwards](https://github.com/programminghistorian/jekyll/issues/2494), I have proposed that all our Project Team Meetings start at 15:00 UTC, but I would be happy to re-think this if we collectively feel a later slot is more convenient for a greater proportion of our members. 

I can re-schedule this particular meeting if there are people who are particularly keen to join but are now unable to. Please let me know here in the comments.

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for filling in your availability via the [Doodle Poll](https://doodle.com/poll/ufn9aykpchvk9w9m?utm_source=poll&utm_medium=link)

We'll meet on **Friday 11th March [at 08:00 COT / 13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220311T130000&p1=41&p2=1440)**

**Comment by anisa-hawes** [comment]
Hello all,

For tomorrow's Project Team Meeting, I would like to lead a discussion that zooms in on one (or two, if there's time!) of our shared goals for 2022. My hope is that by moving in on the detail, we can begin to distill our creative dialogues into a clear action plan towards success. Following the meeting, we will be able to open a sequence of Issues that correspond to the distinct tasks which will help us achieve each of our goals.

I'd like to suggest we structure the conversation by considering two questions underneath each goal:
- _What will success look like?_
- _How will we achieve success?_

I've gathered some ideas, and devised some discussion points to start us off.

**Shared Goals 2022**
--

**1. Drive and anticipate the future needs of our field**
--
**Actively setting the skills agenda in Digital Humanities**

 **Ideas**

_What will success look like?_
- Managing Editors as curators of their publications with the agency to shape their journals' voices

_How shall we achieve success?_
- Managing Editors seek new lessons; actively invite new contributors to write lessons teaching particular methods

--

_What will success look like?_
- Editorial team members as co-curators of their publications

_How shall we achieve success?_
- Editors contribute and develop their specialist knowledge through editorial work; have the opportunity to share insights into methods that most are relevant to them, their peers, their students and feed into their journal's agenda

--

_What will success look like?_
- A forward-facing plan for new tutorials

_How shall we achieve success?_
- Make time for creative discussions in Managing Editors' Meetings and Project Team Meetings, where we brainstorm/share/devise our plans
- Develop thematic programmes of CFPs or honoraria to compliment our open submission programme

--

Discussion points:
- What are the subjects/methods/technologies missing from our offer?
- What are our communities' learning goals? (and how do our different teams find out -- at the moment? in the future?)
- What are the subjects/methods/technologies we are focused on this quarter? (what are the 'trends' we observe in our current submissions)
- What are the subjects/methods/technologies we would like to focus on next quarter? (considering the knowledge/voices/perspectives of our contributing editors, and considering external Digital Humanities practitioners we'd like to collaborate with)

Follow up:
- What are the infrastructural/technical challenges we might need to surmount to publish on particular methods/technologies, this quarter and next?

--

**2. Expand our educational outreach programme**
--
**Collaborating with universities, libraries and educators to promote and improve our lessons**

**Ideas**

_What will success look like?_
- Well-established partnerships between PH and Project Team Members' institutions

_How shall we achieve success?_
- Initiate collaborative workshops, i.e., funded with annual Outreach Budgets
- Invite departmental colleagues to submit lesson proposals/contribute to Peer Review
- Invite Members' institutions to join [our network of Partners](https://programminghistorian.org/en/ipp) and involve them in decisions and forward planning

--

_What will success look like?_
- Increased use within university curriculum

_How shall we achieve success?_
- Gather data about where our lessons are used in curriculum, and where our lessons aren't being used but could be
- Creating opportunities for constructive feedback sessions, where we hear educators' and students' experiences of our lessons
- Learning to respond to that feedback so that our content better suits the needs of educators and students
- Periodic Lesson Maintenance, to support trust and confidence in our lessons
- New "lectureships" that facilitate educator training

--

_What will success look like?_
- Broader and swifter circulation of our materials in university libraries

_How shall we achieve success?_
- Integration with subscription management services (such as the partnership with JISC, UK). What are the international equivalents?

--

Discussion points

- What data can we gather about which of our lessons are used in syllabuses at the moment?
- What data can we gather about which syllabuses our lessons aren't used in, but could be?
- How well do we understand what educators are seeking? What kinds of training do they wish we offered?
- How can we better collate feedback from workshop participants/facilitators, to learn from experiences and integrate their ideas?
- What other kinds of feedback have you heard at educator workshops, reader discussions groups etc.? Can we initiate some clearer routes for logging and responding to this?
- How would we like to shape a lectureship programme? Who would be involved?
- How else could we facilitate the circulation of our materials in university libraries? What routes do other Digital Humanities journals use? What can we learn from others' experiences?

--

**Comment by anisa-hawes** [comment]
I've also drafted some table-format action plan templates. I think these might help us to break down each goal into tasks (I welcome your feedback/suggestions for adjustments/improvements)

|  What will success look like? | What = evidence we can use to measure our progress |
| ----------- | ----------- |
| Sign of success   | Evidence measure:|
| Sign of success   | Evidence measure:|

|  How shall we achieve success? | How = defining a clear Action Plan towards success|
| ----------- | ----------- |
| Action 1  | Plan:
**What?** (task = Issue#)
**Who?** (assignees, contributors)
**When?** (time scale)    |
| Action 2  | Plan:
**What?** (task = Issue#)
**Who?** (assignees, contributors)
**When?** (time scale)    |

**Comment by drjwbaker** [comment]
Can I just reiterate here, that if funding dataset creation would help some publications better reach their communities, we could and should look into that.

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for the energy and ideas you contributed to our Project Team Meeting on Friday.

The minutes are in our private repository [here](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Project-Team-Meetings/03_2022_ProjectTeamMeeting.md). 

Please let me know if I've missed any important points, or mis-represented something you said. I will be happy to adjust.

Very best,
Anisa.
