### ISSUE TITLE
Suggestion on Creating Web APIs with Python and Flask

### ISSUE THREAD

**Issue by JoergRuebesamen** [programminghistorian/jekyll#2496]
If you are reporting a problem with a lesson, please try to provide us with the following information:

- The full title of the lesson: 
https://programminghistorian.org/en/lessons/creating-apis-with-python-and-flask
- The system you are using (Mac, Linux, Windows): Windows - but that does not matter
- Version numbers of the relevant software you are using - Python 3.10 - but that does not matter, eighter
- The exact steps you took that caused the problem:

First of all, I enjoyed the session and maybe understood most of it. But there may be an enhancements I'd suggest for the last part including the database access. 

The sample database provided does not include entries for the attribute ID; they are all NULL.
But there is already sample code included for selecting if the ID is known in your example.
But this method deals with an ID provided as character string. 
In the preceding examples there is a method that created an integer representation from the given character string.
I reccon that it is at least confusing to a beginner. 
I wrote a little update script to update the sample database with unique integer serial ID values, so I ran into exactly that error.
I've tried to update the database with character IDs. Seemed to work with the code provided by your webpage. 
I did not expect the database not to care for the data type.
But maybe it would be better to add an int() expression to the selecting method of the example as in the previous examples. I don't know. Maybe you can discuss that on the webpage or at least provide me with your experienced insights.

**Comment by JoergRuebesamen** [comment]
I took the time to jump even a little deeper into the code and think that the factory method is not needed or used but called, tough. At least I removed the invocation and did not notice a difference.
I took the explanation from the text, that dictonaries get better jsonized than lists, but in this case it seems to work quite well. Anyway, I'll keept that in mind for later, but omitting that method and the invocation may make the source even more impressing because it gets lighter and even more easy to understand. But maybe I've missed something.
Please don't get me wrong, you helped me a lot getting a bit into the subject. Thank you.

**Comment by anisa-hawes** [comment]
Thank you for sharing your thoughts, @JoergRuebesamen. I will take a look at this lesson, and see if any further clarifications or changes are needed. Very best wishes, Anisa

**Comment by hawc2** [comment]
@anisa-hawes as far as I can tell there are not actionable edits we're going to make at this time, as it's not clear to me this is a lesson-breaking bug, so I'd suggest we close this issue. We could separately send a note to the author about this comment and related updates that might be necessary with this lesson, and leave it to them to update it if they are interested and able

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I agree.
