### ISSUE TITLE
Meeting of MEs: Wednesday 16th March 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2497]
Hello @DanielAlvesLABDH, @rivaquiroga @svmelton and @spapastamkou.

As proposed in #2494, I am opening this Issue to agree an agenda for the forthcoming meeting of MEs.

**Wednesday 16th March at [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220317T140000&p1=1440&p2=43&p3=232&p4=195&p5=133)**.
10:00 Boston / 11:00 Santiago / 14:00 Lisbon / 15:00 Paris

The link to join our Zoom is: https://us05web.zoom.us/j/87506702460?pwd=eEtHQTlseStsYm53VmNLblg0MVMwQT09

Meeting ID: 875 0670 2460
Passcode: jj64ev

Meeting of MEs
---

Please add items you'd like to put on the agenda for discussion

- Copyediting across all four publications. @anisa-hawes 
This is one of the Goals on our Business Plan. I'd like to ask what support is needed to establish these services, and how can I help. 
- Re-organisation of directories in Submissions Repository. @anisa-hawes 
I'd like to ask if changes discussed in #2235 and implemented for EN are welcome / felt to be useful to ES, FR and PT teams (There is no pressure to standardise practices if you do not find the suggestion useful)
-
-
-

**Comment by rivaquiroga** [comment]
I'm sorry, but I'll not be able to attend :(
In my case, Thursday is not a good day for having meetings because I'm teaching most of the day.

**Comment by DanielAlvesLABDH** [comment]
For me, 18th at the same time works fine also

**Comment by spapastamkou** [comment]
In this case 17th works for me but 18th might probably not. But otherwise, in general, if Fridays work better for the other MEs and you Anisa, we can try and go for it.

**Comment by anisa-hawes** [comment]
Thank you @rivaquiroga, @DanielAlvesLABDH and @spapastamkou for letting me know your availability/conflicts. 

How would **Wednesday 16th March** at [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220316T140000&p1=1440&p2=43&p3=232&p4=195&p5=133) suit you on this occasion? 

Please indicate: 
- [x] Riva?
- [x] Daniel?
- [x] Sofia?
- [x] Sarah?

Going forwards through the year, we could instead try alternating Wednesdays and Fridays as follows:

**March**
Wednesday 16th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220316T140000&p1=1440&p2=43&p3=232&p4=195&p5=133)

**June**
Friday 17th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220617T140000&p1=1440&p2=43&p3=232&p4=195&p5=133)

**September**
Wednesday 14th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220914T140000&p1=1440&p2=43&p3=232&p4=195&p5=133)

**December**
Friday 16th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20221216T140000&p1=1440&p2=43&p3=232&p4=195&p5=133)

If this sounds reasonable, I can update the proposal outlined in [Issue 2494](https://github.com/programminghistorian/jekyll/issues/2494). Of course, it's understandable that you may not be able to attend every meeting scheduled. But my hope is to make it possible!

**Comment by spapastamkou** [comment]
I could be a bit late but make it on 16/03. Same for 14/09.

**Comment by anisa-hawes** [comment]
Dear @DanielAlvesLABDH @svmelton, @spapastamkou and @rivaquiroga, 

Thank you for your time last Wednesday. 

I've uploaded the Minutes to our Project and Business Archive. You can review them [here](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Managing-Editors-Meetings/03_2022_ManagingEditorsMeeting.md) in Markdown format.

Do let me know if you feel I've missed any important points, or if you would like me to make any adjustments.

Very best,
Anisa
