### ISSUE TITLE
Categorize each lesson with tags

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#25]
Per Skype call on August 15:

- @fredgibbs is going to reorganize the lessons directory under non-alphabetic categories (like "Getting Started," "Tools," etc.)
- @wcaleb is going to tag each lesson with categories; the categories will include, at a minimum, the topics under which the lessons are *currently* listed on the category page, so that the [Lessons Directory](https://github.com/programminghistorian/jekyll/blob/11b191f21c9067ecb44da697eb68bc8312dc9f1d/lessons/index.md) can be automatically generated.

**Comment by acrymble** [comment]
I really think we've nailed the lesson's page. Do we still want to do this? It's almost a year ago that this discussion started. Close?

**Comment by ianmilligan1** [comment]
Agreed w/ @acrymble - I think the lesson page is great as is.
