### ISSUE TITLE
Error message in 'Temporal Network Analysis with R' on R v. 4.x

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2502]
My students were working on the Alex Bray, 'Temporal Network Analysis with R' lesson, which was written suggesting versions of R above 3.x

Students working in R 3.6.x were ok.
Students working with newer versions (R 4.1.x) got an error message:

> Error in plot(thenetwork) : object 'thenetwork' not found

When executing the code in the line following 'Now that we’ve got our basic data into R, we can take a look at the network:'.

The error happened with students on both a mac and pc, so that's why the version of R was queried.

**Comment by anisa-hawes** [comment]
Thank you @acrymble! I'll take a look at this.

**Comment by drjwbaker** [comment]
I happened to be in R doing something, so looked at this.

The error before the one reported - which is `Error: `multiple` is `FALSE`, but `x` contains parallel edges. The following rows in `x` are duplicated:` - is the important error. So, this works:

```r
# Make and visualize our static network
thenetwork <- network(
  PHStaticEdges,
  vertex.attr = PHVertexAttributes,
  vertex.attrnames = c("vertex.id", "name", "region"),
  directed = FALSE,
  bipartite = FALSE,
  multiple = TRUE
)
plot(thenetwork)
```

**Comment by drjwbaker** [comment]
(sorry if you'd already got there @anisa-hawes!)

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker! I tested this in RStudio (2021.09.0 Build 351) yesterday and I think the solution you've suggested works well. 

Upon entering the code as given, I found that two errors were produced:
1.
```
Error: `multiple` is `FALSE`, but `x` contains parallel edges.
```
2. 
```
Error in plot(thenetwork) : object 'thenetwork' not found
```

![Screenshot 2022-03-02 at 19 33 35](https://user-images.githubusercontent.com/87070441/156437332-4957ca24-2139-47cd-b802-2094814fd06a.png)

Upon trying again, I added in the line you suggested `multiple = TRUE` I've been able to produce the plot as shown here:

![Screenshot 2022-03-02 at 19 36 34](https://user-images.githubusercontent.com/87070441/156437367-06088ac0-fb19-4d55-b336-9fe9d1dc489f.png)

**Comment by anisa-hawes** [comment]
Just re-tested in R Console (R 4.1.1 ) and can confirm that this works here too:
![Screenshot 2022-03-03 at 12 18 33](https://user-images.githubusercontent.com/87070441/156563517-c5f2c958-4f1b-498f-99db-776fcb92232b.png)

![Screenshot 2022-03-03 at 12 18 39](https://user-images.githubusercontent.com/87070441/156563501-fa2a9ac4-4a34-44ed-b8b7-24377937210c.png)

I'll add `multiple = TRUE` to /en/lessons/temporal-network-analysis-with-r
/es/lecciones/analisis-temporal-red
