### ISSUE TITLE
Wiki on Project & Business archive

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2505]
@drjwbaker I believe we agreed you're the only one able to add this feature to the https://github.com/programminghistorian/project-and-business-archive. Opening a ticket to get that on the to-do list so that we can move our service integrations and other charity-related documentation to that repository.

**Comment by drjwbaker** [comment]
No. We need to upgrade to get a wiki on a private repo (https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis). @anisa-hawes and I feel a markdown doc in the private repo with this info should suffice.

**Comment by drjwbaker** [comment]
(or we can pay to upgrade, but I suspect we don't need all the features that brings just yet)

**Comment by anisa-hawes** [comment]
I've moved the Service Integrations Wiki page to our [Private Repo](https://github.com/programminghistorian/project-and-business-archive/blob/master/service-integrations/ProgHist-Service-Integrations.md) where I've created an .md document.

I've left a note + link for Members in its old location in case anyone looks for it there.

**Comment by drjwbaker** [comment]
Perfect. Thanks @anisa-hawes
