### ISSUE TITLE
Reformatting the blog page

### ISSUE THREAD

**Issue by tapar001** [programminghistorian/jekyll#251]
The PH [blog](http://programminghistorian.org/blog) is looking a bit old school with the list of links and no previews of individual posts. Thoughts on updating it to a more 2016 blog format?

**Comment by wcaleb** [comment]
Yes, I agree. What do you want it to look like? Let me know and I can work on the formatting.

**Comment by tapar001** [comment]
I was thinking we might do away with the bullet points, and instead lead with the title of each post, followed by the date, and beneath it a preview (maybe a few sentences) of the post itself. 

Another quick question while we're on the topic of formatting--right now the blog posts have the same margins as the lessons. I'm wondering if we might bump the margins out a little wider for blog posts? It's a little narrow for my preferences--but if it's just me then no worries, let's leave it as is!

**Comment by acrymble** [comment]
@tapar001 I suspect it would help this along if you could mock something up.

**Comment by wcaleb** [comment]
@tapar001 I've made some preliminary changes to the layout. Let me know what you think.

**Comment by acrymble** [comment]
I like it. note problem with break falling in the middle of a link (post on Edinburgh). But I like it.

**Comment by tapar001** [comment]
This looks fantastic, Caleb! Exactly what I was thinking of. Thank you!

As the blog populates I wonder if it'd make sense to add a max number of
posts to display per page so readers aren't scrolling down the page for too
long.

On Mon, Jun 27, 2016 at 10:51 AM, Adam Crymble notifications@github.com
wrote:

> I like it. note problem with break falling in the middle of a link (post
> on Edinburgh). But I like it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/programminghistorian/jekyll/issues/251#issuecomment-228787872,
> or mute the thread
> https://github.com/notifications/unsubscribe/AMjtsUTt-IOd3wr98NJSKIayP5yqBgKrks5qP_GAgaJpZM4IQJWb
> .

## 

Evan Taparata
Immigration History Fellow, PRI.org
http://www.pri.org/people/evan-taparata
Ph.D. Candidate, History Department
University of Minnesota
1100 Heller Hall
271 19th Ave S
Minneapolis, MN 55455

**Comment by wcaleb** [comment]
There is a way to limit number of posts displayed, but I'll have to think about how to do that while also allowing users to see all posts if they want to---perhaps a separate "Archives" page with a complete listing that looks more like the old one.
