### ISSUE TITLE
Ombudsperson to replace Miriam

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#252]
As Miriam has stepped down, we need to replace her as one of our ombudspersons. Anyone from the Editorial board willing to step into this?

**Comment by ianmilligan1** [comment]
As the other ombudsperson, it would be great to work with one of you. 👋

**Comment by jerielizabeth** [comment]
I cannot take on more right now (barely keeping up with editorial responsibilities). This could be a great way to bring someone else onto the team (per Miriam's suggestion).

**Comment by acrymble** [comment]
I think we're going to need to look outside the editorial board for this.

**Comment by ianmilligan1** [comment]
We discussed this at our call.
