### ISSUE TITLE
Organising our Annual General Meeting: 23rd May 2022 15:00 UTC

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2520]
I am opening this Issue as a space to organise our AGM. These are the steps I think are needed. 
Please add in any steps/notes you feel I've missed. 

- [x] Decide on a date **The event will take place on Monday 23rd May at [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220523T150000&p1=1440)**

**POLL CLOSED**

[![](https://api.gh-polls.com/poll/01FXTEJ14ZJA7WNZTV3539P2KA/Monday%2023rd%20May%2015:00%20UTC)](https://api.gh-polls.com/poll/01FXTEJ14ZJA7WNZTV3539P2KA/Monday%2023rd%20May%2015:00%20UTC/vote)
[![](https://api.gh-polls.com/poll/01FXTEJ14ZJA7WNZTV3539P2KA/Tuesday%2024th%20May%2015:00%20UTC)](https://api.gh-polls.com/poll/01FXTEJ14ZJA7WNZTV3539P2KA/Tuesday%2024th%20May%2015:00%20UTC/vote)

**POLL CLOSED**

- [x] Prepare invitations 

- [x] Circulate invitations - send to IPPs, our Patreon community, and the Project Team
- - [x] direct emails to IPP representatives
- - [x] direct emails to Patreons
- - [x] via our Google Groups
- - [x] via our General Slack channel

- [x] Promote event:
- - [x] a Patreon post
 
- [x] Planning meeting to agree the AGM's shape and content
- [x] Finalise agenda
- [x] Treasurer's Report @drjwbaker 
- [x] Prepare slide presentation

**Comment by anisa-hawes** [comment]
Hello all, 

This is just a reminder to anyone in the @programminghistorian/english-team, @programminghistorian/spanish-team,  @programminghistorian/french-team, @programminghistorian/portuguese-team who would like to indicate their preference of the two proposed dates for our Annual General Meeting. 

Very best,
Anisa

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for indicating your preference of dates for our forthcoming AGM. 

I'd like to confirm that the event will take place on Monday 23rd May at [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220523T150000&p1=1440).

All best,
Anisa

**Comment by drjwbaker** [comment]
@anisa-hawes To help you with this, I'm going to add a 'contact details' column to the IPP tab for the next month end cashflow statement (those at https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Finances/cashflow/2021-22). I'm going to do this tomorrow (because it'll help me with renewals anyway), so if there is any other info you'd find useful to have there about IPPs, let me know.

**Comment by drjwbaker** [comment]
Have the invites to IPPs gone out?

**Comment by anisa-hawes** [comment]
Not yet – preparing to do this next week. Thank you for creating the Contact column in the Dashboard document @drjwbaker.

**Comment by drjwbaker** [comment]
Okay! Ping me if you need a hand.

**Comment by drjwbaker** [comment]
I've started a folder here for papers, including my report https://github.com/programminghistorian/project-and-business-archive/tree/master/charity/AGMs/2022

**Comment by anisa-hawes** [comment]
I am closing this Issue following a successful AGM! 

Thank you all.
