### ISSUE TITLE
Add "R" as a topic 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2523]
As we are receiving more and more lessons that use R as the language to do some research, and after a couple of conversations about it here and there (for example, it is hard to find R with the search option only), the tech-team is going to add "R" as a topic for lessons. 

This includes adding a new `type` in the `_data/topics.yml` file and then adding R as a topic to existing and new lessons. I am going to start with the lessons in Spanish to make sure the change works.

**Comment by anisa-hawes** [comment]
This Issue has been resolved by PR #2524 so I am closing it now.
