### ISSUE TITLE
Update our articles in the Directory of Open Access Journals (DOAJ)

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2528]
This afternoon, I updated the [Directory of Open Access Journals (DOAJ)](https://doaj.org/about/) so that our most recently published articles in EN, ES and FR are listed. If you follow the links below and click on 'Articles', you can see how the listings are structured.

_Programming Historian en Español_ <https://doaj.org/toc/2517-5769>
_Programming Historian en Français_ <https://doaj.org/toc/2631-9462>
_Programming Historian_ <https://doaj.org/toc/2397-2068>

The DOAJ provides an index of open access articles. Contributing to it makes the content we publish searchable via library catalogues. 

This morning, I submitted an application to add _Programming Historian em português_ to our publisher dashboard. 
@DanielAlvesLABDH and @programminghistorian/portuguese-team – I'll let you know when this has been set up! When it's ready, I'll add article metadata for everything you've published so far.

Thank you to @drjwbaker for showing me how this service works 🌟

Going forwards, I'll be maintaining our entries on the DOAJ. I'll update the listings twice yearly, in March and September.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes many thanks for this. If you need any help or additional information from us just let us know.

**Comment by anisa-hawes** [comment]
I’m delighted to confirm that our recent application to add _Programming Historian em português_ to the DOAJ has been successful!

I’ve added article metadata for all PT lessons published to date, and will update again in September (when I will also update EN, ES and FR). 

For now, three cheers for the Portuguese team @programminghistorian/portuguese-team! 

You can view the Journal’s DOAJ dashboard [here](https://doaj.org/toc/2753-9296?source=%7B%22query%22%3A%7B%22bool%22%3A%7B%22must%22%3A%5B%7B%22terms%22%3A%7B%22index.issn.exact%22%3A%5B%222753-9296%22%5D%7D%7D%5D%7D%7D%2C%22size%22%3A100%2C%22sort%22%3A%5B%7B%22created_date%22%3A%7B%22order%22%3A%22desc%22%7D%7D%5D%2C%22_source%22%3A%7B%7D%2C%22track_total_hits%22%3Atrue%7D)

And you can browse the individual article metadata by navigating from the  'About' tab, to the 'Articles' tab.

(& sincere thanks to @drjwbaker for helping me to co-ordinate this)
