### ISSUE TITLE
Remove non-paying IPPs

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2529]
I am removing the following IPPs from our list of Institutional Partners on en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores.

- [UCL Centre for Digital Humanities](https://www.ucl.ac.uk/digital-humanities/), United Kingdom
- [Roy Rosenzweig Center for History and New Media, George Mason University](https://rrchnm.org/), United States

These institutions are past-year partners, but they have not yet renewed their memberships. I am moving them to the 'Additional Supporters' section instead.

**Comment by drjwbaker** [comment]
Thanks Anisa. There are a couple more who I suspect aren't renewing, but I'll confirm later this month.

**Comment by anisa-hawes** [comment]
Thank you, James. I see now, the Additional Supporters section includes the dates between which each institution has supported us. When non-renewals are confirmed, may I ask if you could also include the year they signed up?

**Comment by drjwbaker** [comment]
These https://github.com/programminghistorian/project-and-business-archive/tree/master/business/Finances/cashflow/2021-22 should give you a good sense (the IPP tab should be up to date most of the time)
