### ISSUE TITLE
Collating activities to add to the research / investigacion / recherche / pesquisa pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2533]
Hello all,

Are there any recent publications / workshops / events / reports you've been involved in which you'd like me to add to the research / investigacion / recherche / pesquisa pages of our website? 

I'm aware of this, which is coming up soon:

- Jennifer Isasi & Brandon Walsh with Gabi Kirilloff, ‘[Programming Historian Workshop on Twine in the Classroom](https://ach.org/blog/2022/02/15/ach-programming-historian-workshop-on-twine-in-the-classroom/)’, Association for Computers and the Humanities, United States (13 April 2022).

- I'd also like to add in Dr Amy Kavenagh's report on visual accessibility & editorial practices. How would it be best to cite this?

Please let me know if there's anything else you'd like me to add?
@programminghistorian/english-team, @programminghistorian/spanish-team, @programminghistorian/french-team and @programminghistorian/portuguese-team

**Comment by jenniferisasi** [comment]
I was invited to talk about our editorial workflow at a class in Spain, by our former colleague Antonio Rojas Castro. Not sure if we include shorter invited talks, but it so Jennifer Isasi, "El flujo editorial en _Programming Historian en español_" en Edición Digital de Textos, Máster Universitario en Humanidades Digitales, Universidad Internacional de La Rioja, 2021-2022.

**Comment by anisa-hawes** [comment]
We would love to include this. Thank you, @jenniferisasi!

**Comment by DanielAlvesLABDH** [comment]
Me and @joanacvp gave a small workshop this week. Daniel Alves e Joana Vieira Paulino, “O Programming Historian em português e o ensino das Humanidades Digitais”, 2.º Seminário CEComp-HD, Centro de Estudos Comparatistas da Faculdade de Letras, Universidade de Lisboa, Lisboa, 23 de Março de 2022.

**Comment by spapastamkou** [comment]
We have a forthcoming workshop as part of the forthcoming Humanistica 2022 conference in May and one oral presentation in DHnord 2022 conference in June. But both programmes are not yet under elaboration currently. When we know more we'll update.

**Comment by acrymble** [comment]
I gave a paper:

Adam Crymble, 'Trans-Atlantic Digital History and the Spatial Turn of Practice (as viewed from London)' IHR Digital History Seminar, London (29 March 2022).

**Comment by ericbrasiln** [comment]
In May I will give a webinar at the School of Social Sciences (FGV/CPDOC), coordinated by @JimmyMedeiros82:

Eric Brasil, "Criação, manutenção e divulgação de projetos de História em meios digitais: git, GitHub e o Programming Historian" . Webinar at the School of Social Sciences (FGV/CPDOC). 16 May 2022.

**Comment by spapastamkou** [comment]
Sofia Papastamkou, Hugues Pecout, Sébastien Rey-Coyrehourcq, Timothée Giraud, Gwenaëlle Patat, "Programming Historian en français et Rzine: faire communauté pour le partage de ressources éducatives libres en méthodes numériques/quantitatives en
sciences humaines et sociales francophones", _Humanistica 2022_, Séance de groupe de travail, 18 mai 2022
The programme has not yet been published, so no link for the moment. 

There will be another conference in June but everything is in the making, I think it will be for the next time you collect this kind of information, Anisa - or I'll add it directly then. 

UPDATE 12 May 2022: This workshop has slightly changed name as we merged with another one with similar content. It is now as follows: 
Sofia Papastamkou, Hugues Pecout, Sébastien Rey-Coyrehourcq, Timothée Giraud, Gwenaëlle Patat, Margot Mellet, Servanne Monjour, Nicolas Sauret: "Programming Historian en français, Rzine, ... & Tutos : Faire communauté autour des dispositifs et des formats alternatifs du savoir", _Humanistica 2022_, 18 May 2022. Link to programme: https://humanistica2022.sciencesconf.org/program

**Comment by spapastamkou** [comment]
I wonder if we can agree that each time some of us participate to conferences, give workshops etc, we systematically upload a basic description and abstract to Zenodo (or another open archive?) so that we can have a clue on our activities and provide a bit more that a list of titles on the website.

**Comment by jenniferisasi** [comment]
> Eric Brasil, "Criação, manutenção e divulgação de projetos de História em meios digitais: git, GitHub e o Programming Historian" . Webinar at the School of Social Sciences (FGV/CPDOC). 16 May 2022.

@ericbrasiln will this be recorded? or any chance you'll have written notes/pptx to share? I'd love to watch/read it, but also @ZoeLeBlanc is working on a paper that sounds similar :)

**Comment by ericbrasiln** [comment]
Yes, the webinar will be available on FGV's YouTube channel. And I will prepare an online presentation hosted on GH Pages.
I share with you in early May. 😄

**Comment by acrymble** [comment]
I gave a paper:

Adam Crymble, 'Building Methods with the Global South' Research Methodology Conference, Coventry (20 April 2022).

**Comment by spapastamkou** [comment]
upcoming: 
- Sofia Papastamkou, "Penser la pédagogie aux méthodes numériques au prisme de la reproductibilité: le cas du Programming Historian", _Journées annuelles du réseau MATE-SHS_: Recherche reproductible: regards croisés en sciences humaines et sociales, 16-17 mai 2022, Campus Condorcet Paris-Aubervilliers, 16-17 mai 2022. Link to programme: https://ja-mate2022.sciencesconf.org/resource/page/id/1  
- Matthias Gille Levenson, Sofia Papastamkou et Célian Ringwald, "Programming Historian: un lieu de collaborations et d'interactions multiples", _DHNord 2022: Travailler en humanités numériques : collaborations, complémentarités et tensions_, Lille, France, 22 June 2022. Link to programme: https://www.meshs.fr/page/dhnord2022.5

**Comment by anisa-hawes** [comment]
Thanks to all who have shared their recent research activities here!

I’ve prepared a PR to update our en/research, es/investigacion, fr/recherche, pt/pesquisa pages of our website today. 

N.B. I have set myself a reminder to add @matgille, @spapastamkou and @datalogism (Célian)’s forthcoming presentation at _DHNord_ in June.

**Comment by matgille** [comment]
Dear Anisa, with Gwenaëlle @InesSalome  we've presented Progamming Historian at Humanistica 2022 congress, two or three weeks ago: 

Matthias Gille Levenson, Gwenaëlle Patat. Programming Historian en français : Faire communauté pour le partage de ressources éducatives libres sur les méthodes numériques en sciences humaines et sociales francophones. Colloque Humanistica 2022, May 2022, Montréal, Canada. [⟨hal-03672420⟩](https://hal.archives-ouvertes.fr/hal-03672420)

Many thanks !

Gwenaëlle and Matthias

**Comment by acrymble** [comment]
giving a talk today:

Adam Crymble, 'Local Needs for Global Digital Scholarship', _Quo Vadis_, 9 June 2022, (UCL, London)
