### ISSUE TITLE
Investigating U.S.-based Subscription Management organisations

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2535]
Following the success of our partnership with JISC in the U.K., we have begun to investigate U.S.-based Subscription Management organisations who we may wish to contact about the services they offer to U.S. academic libraries.

Our hope is that we can make it simpler for academic libraries in the United States to join us as IPPs via a subscription integration system.

I am opening this Issue to signal the beginning of this investigation, and to invite ideas from the Project Team (particularly those based in the U.S.) about organisations that could be useful to contact. Thanks to @jenniferisasi and @svmelton who have helped me to build this initial list:

- EBSCO <https://www.ebsco.com/academic-libraries>
- Lyrasis <https://www.lyrasis.org/Pages/Main.aspx>
- CRL <https://www.crl.edu/>
- SPARC <https://sparcopen.org/>
- JSTOR <https://www.jstor.org/>

N.B. This task may eventually be passed onwards to a new member of staff (who we hope to recruit later in 2022) with responsibilities for community management.

**Comment by GeeAlmeida** [comment]
I have emailed EBSCO to ask if they provide this service.

**Comment by GeeAlmeida** [comment]
I have not received a reply from EBSCO...

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. Another library subscription management service which I think would be worth investigating a link with is [ProQuest](https://about.proquest.com/en/about/who-we-are/). (I thought they were Canadian, but actually they are U.S.-based)

There's information about their selection policy here: https://about.proquest.com/en/company/proquest-open-access/
And a link to Contact them here: https://about.proquest.com/en/publishers/

**Comment by GeeAlmeida** [comment]
Thank you Anisa! I contacted ProQuest today.

**Comment by GeeAlmeida** [comment]
I have moved the content of this issue to [#2682](https://github.com/programminghistorian/jekyll/issues/2682) .
