### ISSUE TITLE
Clarifying our policies on authorial copyright and publishing rights

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2536]
In the process of applying to add _Programming Historian em português_ to the [Directory of Open Access Journals (DOAJ)](https://doaj.org/about/) (see #2528) we have been asked to clarify our policies on authorial copyright and publishing rights.

My understanding is that this links to some conversations you have already been having within the Project Team (initiated by @spapastamkou) about how we can keep a more formal record of the permissions authors have granted, as well as clarifying their (and our) rights. @acrymble and I have been talking about setting up a workflow for forward- and retrospective documentation of these agreements. An idea is establishing a form that authors can complete for our (and their) records, which offers a clearer explanation of terms than the short statement we currently ask them to paste into Issues in our Submissions Repo.

The DOAJ's suggestion is that we add the following two statements to our website:

**Authors' copyrights:**

EN: "Authors retain copyright and grant the journal the right of first publication, with the work simultaneously licensed under the Creative Commons - Attribution 4.0 International CC BY 4.0 License."

PT: "Os autores mantêm os direitos autorais e concedem à revista o direito de primeira publicação, com o trabalho simultaneamente licenciado sob a Licença Creative Commons - Atribuição 4.0 Internacional CC BY 4.0."

**Authors' publishing rights:**

EN: "Authors have permission to publish and distribute their work online in institutional / disciplinary repositories or on their personal homepage."

PT: "Os autores têm permissão de publicar e distribuir o seu trabalho online em repositórios institucionais / disciplinares ou na sua página pessoal."

I'd like to ask the Managing Editors @DanielAlvesLABDH @svmelton @spapastamkou and @rivaquiroga for their thoughts on this?

I see this Issue as comprising two key tasks:

- [x] adding the statements on authors' copyrights and publishing rights PR #2555 
- [x] gathering ideas about developing a Rights Agreement form, to help us document our agreements with authors, clarifying their rights as authors and our rights as publisher.

**Comment by drjwbaker** [comment]
Thanks so much @anisa-hawes for tieing this together with ongoing work: your ability to see things across the project is so valuable!

I think one of the drivers here is the OA community trying to encourage authors to assert copyright over the submitted/accepted version of their work, so as to better faciliate Green OA. We are Diamond, so this may seem slightly less relevant, but from DOAJs perspective I can see why they'd encourage DOAJ listed journals to embody best practice. I'm sympathatic to that aim, so hopefully we can make this change without too much effort.

**Comment by anisa-hawes** [comment]
Thank you, James – this is useful context. 

I think there are two particular things we would be able to consider weaving into a Rights Agreement form:

- the possibility that post-publication updates may be required (lesson maintenance)
- our remit to translate the author's work and re-publish it within one of our other journals

**Comment by jenniferisasi** [comment]
If I may, @anisa-hawes for your last bullet-point: translate, **potentially remix/alter** and republish (best example [lesson on MALLET]( https://programminghistorian.org/es/lecciones/topic-modeling-y-mallet)). 

Don't know if we need to go into that detail, but I thought I'd share.

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. Yes, I agree that clarification is important. We can find a way to clarify that our translation process may include the alteration of case studies and/or substitution of sample data, and explain that this is to ensure the lesson will remain relevant, engaging and practicable for each journal's community.

**Comment by drjwbaker** [comment]
> I think there are two particular things we would be able to consider weaving into a Rights Agreement form:
> 
>     * the possibility that post-publication updates may be required (lesson maintenance)
> 
>     * our remit to translate the author's work and re-publish it within one of our other journals

Agree, but when the work is licensed CC BY then all of this is possible irrespective of the author retaining (c).

**Comment by anisa-hawes** [comment]
Yes, and I note that we do include this link <https://creativecommons.org/licenses/by/4.0/> in our Submissions Issue template. We can explicate these terms as they pertain to our specific case in an agreement form, also adding <https://creativecommons.org/licenses/by/4.0/deed.es>, <https://creativecommons.org/licenses/by/4.0/deed.fr> and <https://creativecommons.org/licenses/by/4.0/deed.pt>.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes thanks for moving this forward. I agree with the idea of formalizing the information sharing between authors and the publications. Although we are clear about that in the several places in the platform, to keep a record of this rights agreement would be good police. I agree with James that probably we do not need to go in too much details since the type of license we already use open the possibility for changes and republication. 
Regarding the statemnents on the website, here are the revised translations to Portuguese:
PT: "Os autores mantêm os direitos autorais e concedem à revista o direito de primeira publicação, com o trabalho simultaneamente licenciado sob a Licença Creative Commons - Atribuição 4.0 Internacional CC BY 4.0."
PT: "Os autores têm permissão de publicar e distribuir o seu trabalho online em repositórios institucionais / disciplinares ou na sua página pessoal".
Do you need anything more from our side?

**Comment by svmelton** [comment]
Thanks @anisa-hawes. I think @drjwbaker is right about the context here, and I'm fine with moving this forward as proposed!

**Comment by rivaquiroga** [comment]
Thanks @anisa-hawes, I also agree with moving this forward

**Comment by spapastamkou** [comment]
I would suggest, if need to reiterate the commitment to OA principles, already preserved by CC BY license we use, to borrow vocabulary from the [Declaration of Budapest](https://www.budapestopenaccessinitiative.org/read/) on OA, which would correspond with what Jennifer proposes. I mean mainly this part (and especially the verbs): 
"By “open access” to this literature, we mean its free availability on the public internet, permitting any users to read, download, copy, distribute, print, search, or link to the full texts of these articles, crawl them for indexing, pass them as data to software, or use them for any other lawful purpose, without financial, legal, or technical barriers other than those inseparable from gaining access to the internet itself. "  

I also attach a file with a translation in EN of the contracts the National Fund for Open Science (France) proposes to OA journals in [this web page](https://www.ouvrirlascience.fr/des-contrats-pour-la-science-ouverte/) (model A1, if you scroll down to the page). In case it may be useful to get inspired. 
[A1_agreement_Journal_Author_no-exclu.odt](https://github.com/programminghistorian/jekyll/files/8430656/A1_agreement_Journal_Author_no-exclu.odt)

**Comment by anisa-hawes** [comment]
> Dear @anisa-hawes thanks for moving this forward. I agree with the idea of formalizing the information sharing between authors and the publications. Although we are clear about that in the several places in the platform, to keep a record of this rights agreement would be good police. I agree with James that probably we do not need to go in too much details since the type of license we already use open the possibility for changes and republication. Regarding the statemnents on the website, here are the revised translations to Portuguese: PT: "Os autores mantêm os direitos autorais e concedem à revista o direito de primeira publicação, com o trabalho simultaneamente licenciado sob a Licença Creative Commons - Atribuição 4.0 Internacional CC BY 4.0." PT: "Os autores têm permissão de publicar e distribuir o seu trabalho online em repositórios institucionais / disciplinares ou na sua página pessoal". Do you need anything more from our side?

Thank you for the revised translations, @DanielAlvesLABDH! I've noted these, and edited [my initial comment](https://github.com/programminghistorian/jekyll/issues/2536#issue-1187903062).

The relevant section of our Author Guidelines is the section headed [Open Source, Open Access](https://programminghistorian.org/en/author-guidelines#open-source-open-access)/[Código aberto, Acesso aberto](https://programminghistorian.org/pt/directrizes-autor#c%C3%B3digo-aberto-acesso-aberto).

At the moment, they read: 

EN: _Programming Historian_ is committed to open source values. All lessons must use open source programming languages and software whenever possible. This policy is meant to minimize costs for all parties, and to allow the greatest possible level of participation.

Upon acceptance, you agree to publish your lesson under a Creative Commons “CC-BY” license.

PT: O _Programming Historian em português_ está comprometido com os valores de código aberto. Todas as lições devem usar linguagens de programação e softwares livres sempre que possível. O objetivo é minimizar os custos e permitir aumentar a participação o máximo possível.

Depois da lição ser aceite, o autor deve concordar com a sua publicação sob uma licença Creative Commons “[CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en)”.

I think we can replace this final sentence the statements agreed above that clarify authors' (and our) rights: 

**EN: _Programming Historian_ is committed to open source values. All lessons must use open source programming languages and software whenever possible. This policy is meant to minimize costs for all parties, and to allow the greatest possible level of participation.**

**Authors retain copyright and grant the journal the right of first publication, with the work simultaneously licensed under the Creative Commons - Attribution 4.0 International [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en) License.**

**Authors have permission to publish and distribute their work online in institutional / disciplinary repositories or on their personal homepage.**

**PT: O _Programming Historian em português_ está comprometido com os valores de código aberto. Todas as lições devem usar linguagens de programação e softwares livres sempre que possível. O objetivo é minimizar os custos e permitir aumentar a participação o máximo possível.**

**Os autores mantêm os direitos autorais e concedem à revista o direito de primeira publicação, com o trabalho simultaneamente licenciado sob a Licença Creative Commons - Atribuição 4.0 Internacional [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.pt).**

**Os autores têm permissão de publicar e distribuir o seu trabalho online em repositórios institucionais / disciplinares ou na sua página pessoal.**


May I ask if someone from the @programminghistorian/spanish-team and @programminghistorian/french-team have time to provide the two new sentences? I can add them to [Código abierto, acceso abierto](https://programminghistorian.org/es/guia-para-autores#c%C3%B3digo-abierto-acceso-abierto) and [Open source, libre accès](https://programminghistorian.org/fr/consignes-auteurs#open-source-libre-acc%C3%A8s).

> Authors retain copyright and grant the journal the right of first publication, with the work simultaneously licensed under the Creative Commons - Attribution 4.0 International [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en) License.

> Authors have permission to publish and distribute their work online in institutional / disciplinary repositories or on their personal homepage.

**Comment by anisa-hawes** [comment]
> I would suggest, if need to reiterate the commitment to OA principles, already preserved by CC BY license we use, to borrow vocabulary from the [Declaration of Budapest](https://www.budapestopenaccessinitiative.org/read/) on OA, which would correspond with what Jennifer proposes. I mean mainly this part (and especially the verbs): "By “open access” to this literature, we mean its free availability on the public internet, permitting any users to read, download, copy, distribute, print, search, or link to the full texts of these articles, crawl them for indexing, pass them as data to software, or use them for any other lawful purpose, without financial, legal, or technical barriers other than those inseparable from gaining access to the internet itself. "
> 
> I also attach a file with a translation in EN of the contracts the National Fund for Open Science (France) proposes to OA journals in [this web page](https://www.ouvrirlascience.fr/des-contrats-pour-la-science-ouverte/) (model A1, if you scroll down to the page). In case it may be useful to get inspired. [A1_agreement_Journal_Author_no-exclu.odt](https://github.com/programminghistorian/jekyll/files/8430656/A1_agreement_Journal_Author_no-exclu.odt)

Thank you for sharing these links and ideas, @spapastamkou! These will be very helpful to me as I draft a Rights Agreement form to meet the second objective of this Issue.

**Comment by spapastamkou** [comment]
Here is the FR translation of the two phrases: 

Les auteur(e)s détiennent les droits de propriété intellectuelle et cèdent à la revue le droit de première publication, l'œuvre étant simultanément placée sous licence Creative Commons - Attribution 4.0 International (CC-BY 4.0). 

Les auteur(e)s ont le droit de publier et de mettre à disposition leur œuvre par voie numérique au travers de dépôts institutionnels / disciplinaires ou de leur propre page web.

**Comment by jenniferisasi** [comment]
1.[stays as is]

2. Los autores conservan los derechos de autor y otorgan a la revista el derecho de primera publicación y, simultáneamente, la obra tendrá la licencia Creative Commons - Atribución 4.0 Internacional [CC-BY 4.0].

3. Los autores tienen permiso para publicar y distribuir su trabajo en línea en repositorios institucionales/disciplinarios o en su cuenta personal.

@rivaquiroga what do you think?

**Comment by rivaquiroga** [comment]
Thanks, @jenniferisasi. Might be better to have all the verbs in present tense on number 2.  
_y, simultáneamente, la obra tendrá la licencia Creative Commons_ could be _, quedando la obra simultáneamente bajo la licencia Creative Commons_ o _, licenciando simultáneamente la obra bajo Creative Commons_
What do you think?

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for your collaboration! I've updated our Author Guidelines as agreed, so task 1 is complete. This fulfils what is needed for the DOAJ and our application to add _Programming Historian em português_ to their listings - see #2528.

Task 2: I'll now start work on drafting a Rights Agreement form as a document for collecting authors' permissions more formally than we do in our currently workflow.

**Comment by drjwbaker** [comment]
@anisa-hawes Will you reply to DOAJ, or would you like me to?

**Comment by anisa-hawes** [comment]
> @anisa-hawes Will you reply to DOAJ, or would you like me to?

Thank you, @drjwbaker. I'm happy to write to them. I'll put this on my list for Wednesday.

**Comment by drjwbaker** [comment]
thanks @anisa-hawes

**Comment by anisa-hawes** [comment]
Just a note to say that we've received a positive reply from the DOAJ, who say that the copyright information we've added to our website is "clear and complete". They've updated our application form, and I'll let you all know here when we hear further news.

**Comment by anisa-hawes** [comment]
Dear all,

I've drafted a rights agreement form that I think could support authors to understand what the CC-BY license means, and help us to keep clearer long-term records of the permissions authors have granted us. Please let me know if you think this will meet our needs?

[Authorial-copyright-and-publishing-rights - Google Docs.pdf](https://github.com/programminghistorian/jekyll/files/8642578/Authorial-copyright-and-publishing-rights.-.Google.Docs.pdf)

![Screenshot 2022-05-06 at 18 51 40](https://user-images.githubusercontent.com/87070441/167189622-ca46aac4-288f-403b-95c0-368a3ce61927.png)

**Comment by anisa-hawes** [comment]
Hello @programminghistorian/english-team  @programminghistorian/spanish-team  @programminghistorian/french-team @programminghistorian/portuguese-team.
I’d love to hear your feedback on [the rights agreement form I have drafted](https://user-images.githubusercontent.com/87070441/167189622-ca46aac4-288f-403b-95c0-368a3ce61927.png). 

Do you think this will serve our needs?
Is there anything you think needs to be changed/clarified/expressed differently?

When we have agreed on the wording, I propose that:

1. We consider dedicating some resource to translating this form, so that it is accessible to all our authors
2. We agree which file format to make this form available in. Do you think PDF format would be suitable? (I understand that PDFs can also be opened and edited in LibreOffice).
3. We then upload it to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) and add a download link from the Open Source, Open Access/Código abierto, acceso abierto/Open source, libre accès/Código aberto, Acesso aberto sections of our /en/author-guidelines, /es/guia-para-autores, /fr/consignes-auteurs, pt/directrizes-autor.

Some further considerations/next steps: 

1. Our responsibilities to hold authors’ information securely and in accordance with [General Data Protection Regulation (GDPR)](https://gdpr-info.eu/)
2. Integrating the rights agreement form into our editorial workflow and Editorial Guidelines

**Comment by acrymble** [comment]
@anisa-hawes thanks for drafting the agreement. Can we add a sentence along the lines of 'Programming Historian is published by ProgHist Ltd (charity number...). Just to clarify why ProgHist is getting the rights.

Do we need to get translators to sign this also? And should add a managing editor's signature or something else just to avoid any ambiguity (maybe that's not necessary)?

Also I don't mean to be pedantic, but I don't think Diamond Open Access means those things, but those things are also things we do in the spirit of our Diamond open access model.

I'd be happy for us to start using the form. I can retroactively sign if for lessons I wrote.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. This feedback is very welcome, pedantry included! 

1. How do you think I could clarify that phrasing?
Would this better:

"Our publishing model is Diamond Open Access, _and in that spirit_: 
- Authors retain copyright
- Authors never pay any fees to publish with us
- Content is peer-reviewed
- Content is always free for readers to access"

2. Another good point you made (in our conversation yesterday) was about 'future-proofing' the document so that it refers to "any future translations in any _Programming Historian_ journals", rather than specifying the languages we currently publish in. 

3. Additionally, I can amend the sentence "Agreement between..." to read "Agreement between ProgHist Ltd and the author/translator: …."

4. Add will the sentence "_Programming Historian_ is published by ProgHist Ltd (Charity Number [1195875](https://register-of-charities.charitycommission.gov.uk/charity-search/-/charity-details/5181272/charity-overview) and Company Number [12192946](https://find-and-update.company-information.service.gov.uk/company/12192946)."

**Comment by acrymble** [comment]
sounds great. thanks.

**Comment by anisa-hawes** [comment]
This is done. 

[Authorial-copyright-and-publishing-rights.pdf](https://github.com/programminghistorian/jekyll/files/8879406/Authorial-copyright-and-publishing-rights.pdf)

![Screenshot 2022-06-10 at 14 47 50](https://user-images.githubusercontent.com/87070441/173079746-5a98eaa1-6f8e-4ec2-b712-0833051d0f75.png)

I'll upload it as a PDF to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) and add a download link from the Open Source, Open Access/Código abierto, acceso abierto/Open source, libre accès/Código aberto, Acesso aberto sections of our /en/author-guidelines, /es/guia-para-autores, /fr/consignes-auteurs, pt/directrizes-autor.

Next, I'd like to edit the Issue Template in ph-submissions to remove our Permission to Publish statement, and replace it with a link to the form. I have found instructions for how to edit an existing Issue Template [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository), but I don't have **Set up templates** button. Can anyone help?

**Comment by acrymble** [comment]
I haven't got it either. Maybe only the owner of the repository has it?

Edit: To make sure this is done consistently, maybe this is something you should do for all lessons, and not leave it to editors at all?

**Comment by jenniferisasi** [comment]
@anisa-hawes Let me check... negative, I don't have the button either :/

**Comment by jenniferisasi** [comment]
By the way, do we have to translate this form?

**Comment by ericbrasiln** [comment]
@anisa-hawes 
You can edit the `ISSUE_TEMPLATE` file directly in [`ph-submissions/.github` directory](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/.github/ISSUE_TEMPLATE).

If you want you can add some information in the front matter as well, like this:
```
---
name: title of the template
about: about
labels: ''
assignees: ''
---
```

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln! This is great! I will do that. I noticed a spelling mistake on our Jekyll PR template months ago, and so now I know how to update this too :-)

And thank you @jenniferisasi + @acrymble for checking things from your side. 

Adam, I think that is a great idea. I'd be happy to co-ordinate this, and can also organise a new directory to save the completed forms in our private repository.

Hello @drjwbaker. May I ask for your thoughts about whether we could dedicate some resource to translating this document?

**Comment by drjwbaker** [comment]
> Hello @drjwbaker. May I ask for your thoughts about whether we could dedicate some resource to translating this document?

We don't have to translate the form. But it would be a courtesy to authors who prefer to submit in FR/ES/PT, so I suspect we should, and can happily commit from £ resource to it.

**Comment by anisa-hawes** [comment]
Update: 

- [x] Trial use of the Authorial copyright forms is underway - permission forms received for first two EN lessons
- [x] ES translation is complete (thank you @jenniferisasi!)

Next steps to close this Issue:

- [x] upload EN and ES PDFs to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) 
- [x] add Form download links from the Open Source, Open Access/Código abierto, acceso abierto/ sections of /en/author-guidelines, /es/guia-para-autores
- [x] PT translation is complete
- [x] FR translation is complete
- [x] upload PT PDF to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) 
- [x] upload FR PDF to [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) 
- [x] add Form download link from the Código aberto, Acesso aberto section of our pt/directrizes-autor
- [x] add Form download link from the Open source, libre accès section of our /fr/consignes-auteurs

**Comment by rivaquiroga** [comment]
Hi @anisa-hawes! Thank you for all your work on this. :sparkles:  
We are about to start the edition of a new original lesson in Spanish, and I would like to test the use of the form  (thanks, @jenniferisasi, for translating it :heart:). 
I have a couple of questions:
- Are you going to wait until the FR and PT translations are done to open the PR to update the guidelines? (I just want to know if I can point authors to the updated version of the them in the near future, or if we better explain the process and what the form is via email).
- How is the process going to be? @acrymble suggested that you be in charge, not the editors. That sounds like a good idea. 
What do you think might work best?
  1. Editor (or ME) tells the author to download the form from the guidelines and send the signed version of the form to you. 
  2. Editor (or ME) sends you the contact info of the author and you write them to request the form. We can have a template for that message that we can translate to the other three languages. 
  Or maybe you have a better idea!

Regardless of what we decide, we should describe that process in the Editor Guidelines.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! 

I'm happy to prepare the first of two PRs to upload the EN and ES forms, then add one sentence + a download download link to our author guidelines. (I can prepare a second PR when the FR and PT forms are ready). 

In terms of the workflow, I'm happy to do it either way. As we incorporate our other sustainability practices into the workflow (typesetting and perma.cc for all lessons), each lesson will arrive on my desk ahead of the ME's final steps. This feels like a natural place in the workflow to ask authors/translators to complete the form, so I think Adam's idea of me handling it makes good sense. 

Perhaps upon receiving recommendation for publication from an Editor, MEs could post a comment explaining the next steps:
- Typesetting - Publishing Assistant will review the YAML and Markdown to check the lesson’s layout and structure
- Generating archival hyperlinks - Publishing Assistant will replace all external links included in the lesson with archival perma.cc hyperlinks
- Copyright - Author/translator to complete declaration form [we'll share the download link here], acknowledging their copyright and granting us permission to publish the lesson. We'll ask them to email their form to: admin [at] programminghistorian.org. 

As you say, we'll need to outline these steps in the Editor Guidelines so that everyone knows what to expect.

**Comment by rivaquiroga** [comment]
> Perhaps upon receiving recommendation for publication from an Editor, MEs could post a comment explaining the next steps

I like this idea!

**Comment by anisa-hawes** [comment]
Update: this Issue is almost ready to close. I've prepared a PR #2685 to roll out use of our Authorial Copyright and Publishing Rights declaration forms to PT and FR. 

- [x] Just awaiting a few final tweaks to the FR translation (thank you @spapastamkou)
- [x] Then, I'll replace the PDF in [Forms](https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/forms) and move the PR forwards 
- [x] I'll upload a new copy to our private repo too
