### ISSUE TITLE
Megan R Brett missing author bio.

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#255]
Megan R. Brett is now listed as an author on the Omeka Exhibit lesson. But she has no bio at the bottom of the page. http://programminghistorian.org/lessons/creating-an-omeka-exhibit

Anyone recall when this happened and who initiated so we can chase this up?

**Comment by wcaleb** [comment]
@mebrett did all of the updating to the lesson in #234. Megan, can you add yourself to the author directory so that your bio appears at the bottom?

**Comment by acrymble** [comment]
This was fixed by a pull request. She's also been added to the lessons.md page.
