### ISSUE TITLE
Google Analytics upgrade needed

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2551]
Apparently Google Analytics may need some tweaking in order to keep working after July 2022

![Screen Shot 2022-04-18 at 10 28 49](https://user-images.githubusercontent.com/646647/163788471-a990d5fb-6bfa-453d-82cf-06dca2e25509.png)

**Comment by jenniferisasi** [comment]
"After that, you’ll be able to access your previously processed data in Universal Analytics for at least six months." [panics] We have to download all the data!! Which I guess could make for a nice new repo here in GitHub.

**Comment by anisa-hawes** [comment]
Does anyone in the @programminghistorian/english-team, @programminghistorian/spanish-team, @programminghistorian/french-team, or @programminghistorian/portuguese-team have experience to support us with moving over to Google Analytics 4?

**Comment by rivaquiroga** [comment]
@anisa-hawes, I while ago I started reading the documentation for dowloading our Google Analytics data, so I got some familiarity with the platform. I can help with the task if needed, but not before August. (BTW, the deadline is July 2023, not 2022, so we have more than a year to solve this issue).

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! That would be wonderful! I'll set myself a reminder to contact you in September so we can organise a time to collaborate on this. I shall mark this Issue as On Hold for now.

**Comment by jenniferisasi** [comment]
re I have downloaded data for the newsletter and presentations/papers in multiple occasions so I'm familiar with navigating; not so much about transfer and migration of platforms but if available I can help to at least set some pipeline to extract and preserve data

**Comment by spapastamkou** [comment]
And I am in contact on this subject with the infrastructure guys of the center I work for for the data of the project I am currently in charge of. I have no particular experience and it will take some time before we attack this as a result of different availabilities. But if I have useful news by the time you work on this, I'll let you know or lend a hand.

**Comment by hawc2** [comment]
@anisa-hawes what remains to be done with this ticket? We can discuss it at next tech meeting but it sounds like data has been archived, and some customization of Google Analytics still neds to be done?

**Comment by acrymble** [comment]
I got an email about this today actually. Apparently it's just a few clicks to upgrade. I can assign myself to this as I'm an administrator on it.
