### ISSUE TITLE
Incorrect screenshot in creating-an-omeka-exhibit and criar-exposicao-omeka

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2556]
A reader has written to us, having noticed that the first figure/screenshot in _Creating an Omeka Exhibit_ is incorrect, and is a duplicate of the second.

I can see that the same error has been reproduced in the PT translation _Criar uma Exposição Omeka_ (meanwhile the ES version is correct)

I have located the correct figure (createoexhibit1.png) for EN within the Images folder on Jekyll, here: https://github.com/programminghistorian/jekyll/blob/gh-pages/images/creating-an-omeka-exhibit/createoexhibit1.png and can update the Markdown so that it displays as it should.

Meanwhile, for PT, I note that the figure that shows "Criar uma página de exposição" is missing from the folder. I'd like to ask if anyone on the @programminghistorian/portuguese-team who has access to Omeka could help by creating the screenshot image?

N.B. The PT screenshots numbered 1, 2 and 3 [in this folder](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/creating-an-omeka-exhibit), correspond to the EN 2, 3, 4.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes just created a PR to correct this on the PT lesson. https://github.com/programminghistorian/jekyll/pull/2557

**Comment by anisa-hawes** [comment]
Super! Thank you, @DanielAlvesLABDH! I've updated the filename for figure 1 in the EN lesson on your branch.
