### ISSUE TITLE
Fixing a batch of broken links

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2568]
I am opening this Issue to fix a batch of broken links, highlighted in #2567

In the most recent build, the problem appears to be with http://www.juxtasoftware.org/ -> which requires sign in to access? (linked from /es/lecciones/corpus-paralelo-lfaligner.html)

But I noted that the build report before this one, flagged some others too:

./_site/es/lecciones/corpus-paralelo-lfaligner.html

1. External link http://www.juxtasoftware.org/ failed: 401 No error
2. External link https://www.ecured.cu/ISO_639-3 failed: 404 No error

./_site/es/lecciones/introduccion-a-tei-1.html

3. External link https://www.ecured.cu/Texto_plano failed: 404 No error

./_site/es/lecciones/sitios-estaticos-con-jekyll-y-github-pages

4. External link https://github.com/monfresh/install-ruby-on-macos failed: 404 No error

Number 4. means we'll also need to fix it on: /en/lessons/building-static-sites-with-jekyll-github-pages

I've re-checked all the links above and I am hitting 404 errors in each case.

**Comment by jenniferisasi** [comment]
@anisa-hawes I think it is a safe bet to replace the link on TEI part 1 with this Wikipedia article: https://es.wikipedia.org/wiki/Archivo_de_texto

**Comment by anisa-hawes** [comment]
Yes! My thoughts exactly! I was just searching around for an alternative to this, https://github.com/monfresh/install-ruby-on-macos, which is in a warning/alert box that I created a few months ago... but I can't find anything useful. I think the best option is to remove that sentence. The warning/alert is clear enough without it, I think. (And macOS has already moved beyond Big Sur, so maybe there are new problems!)

For http://www.juxtasoftware.org/ I think perhaps we should remove that link -- it is one of two examples given for programs that can be used to align different versions of a text in the same language, when performing relational analysis.

At the moment, it reads, (rough translation) [...] there are other tools that perform this task better, such as Collatex or Juxta. so I can change that to >> hay otras iniciativas que cumplen mejor con esta tarea como Collatex // there are other tools that perform this task better, such as Collatex.

To replace https://www.ecured.cu/ISO_639-3 I suggest >> https://es.wikipedia.org/wiki/ISO_639-3
