### ISSUE TITLE
Pip lesson -O flag

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#257]
Via John Simpson on Twitter:

http://programminghistorian.org/lessons/installing-python-modules-pip

There's a small error in the lesson on installing pip. curle needs a -O flag or it just puts url content to the screen.

I haven't had a chance to try this yet but I wanted to capture.

**Comment by ianmilligan1** [comment]
Tested – and yes, does need the `-O` flag. I'll make the change.
