### ISSUE TITLE
Board of Trustees Meeting: 19 May 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2570]
Board of Trustees Meeting: 19 May 2022
--

Date: 19 May 2022 Thank you for replying to my calendar invitation 
Time: [14:00 UTC](https://www.google.com/url?q=https://www.timeanddate.com/worldclock/converter.html?iso%3D20220519T140000%26p1%3D1440&sa=D&source=calendar&ust=1652626295599869&usg=AOvVaw2Ge7afUZ_nLe4S0X9z_96f)
Jitsi link: https://meet.jit.si/MaximumAttributesChairObviously
Chair: @acrymble 
Secretary: @anisa-hawes 
Members: @amsichani @drjwbaker @rivaquiroga @svmelton @spapastamkou  @ZoeLeBlanc 
Minutes of the last meeting: [BoT-18-02-2022.md
 ](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/02-2022/BoT-18-02-2022.md)

---

Hello all,

**I'm creating this issue so that we can begin to draft our agenda for May's BoT meeting.**
Please feel free to edit this agenda, and add further Items for discussion below

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf),  I'd like to ask that new agenda Items are added **in advance of the meeting** so that all attendees have sufficient time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions.  

### Agenda

- 1. Apologies  
- 2. Approval of Minutes from last meeting & actions status.
- 3. ProgHist Directors administration (e.g., changes of address)
- 4. Approval of 2020/21 accounts (and letter of representation) for ProgHist Ltd @drjwbaker (docs [here](https://github.com/programminghistorian/project-and-business-archive/tree/master/charity/Annual-Return)) (@drjwbaker)
- 5. AGM Planning (@acrymble)
- 6. New Director conversation (@acrymble)
- 7. Update on Job Posting (@acrymble)
- 8. Any Other Business
-  9. discuss potential collaboration with TNA and other stakeholders on [this call](https://www.ukri.org/opportunity/embed-digital-skills-in-arts-and-humanities-research/) (@amsichani)

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by svmelton** [comment]
My apologies, I'll be traveling for work and will not be able to attend this meeting.

**Comment by anisa-hawes** [comment]
Dear all,

I've uploaded the Minutes of our recent Board of Trustees Meeting. You can review them here: [https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/05-2022/BoT-19-05-2022.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/05-2022/BoT-19-05-2022.md) in Markdown format. 

As always, let me know if I've missed anything or if you'd like to suggest any amendments.

Thank you, 
Anisa
