### ISSUE TITLE
Programming Historian's Annual General Meeting : 23 May 2022 : 15:00 UTC

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2571]
![AGM-invite-Project-Team-image](https://user-images.githubusercontent.com/87070441/168073928-3bb5cb10-07f6-46d7-9981-7b3a0ca6a962.png)

---

Date: 23 May 2022
Time: [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220523T150000&p1=1440)
Zoom link: https://ucl.zoom.us/j/4161789524
Chair of the Trustees: @acrymble 
Treasurer: @drjwbaker 
Secretary: @anisa-hawes  
Minutes of the last meeting: [2021_ProgHistLtd-AGM-minutes.docx
 ](https://github.com/programminghistorian/project-and-business-archive/blob/master/business/AGMs/2021/2021_ProgHistLtd-AGM-minutes.docx)

---

Dear all,

**I'm creating this Issue so that we can set our agenda for May's Annual General Meeting.**
Please feel free to add Items for discussion. 

### Agenda

- Welcome @anisa-hawes
- Apologies @anisa-hawes
- Approve Minutes 2021 AGM (@acrymble)
- Programming Historian Annual report & treasurers report @acrymble @drjwbaker
- Open Discussion about the coming year @acrymble
- AOB

**Comment by anisa-hawes** [comment]
Dear all,

I have now uploaded the minutes of Monday's meeting to our Project and Business Archive. 

Project Team Members can review them in Markdown format here: [2022_ProgHistLtd-AGM-minutes.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2022/2022_ProgHistLtd-AGM-minutes.md).

Please let me know if you'd like to suggest any revisions, before I circulate among the Advisory Members who joined us.

Thank you.

Very best,
Anisa

**Comment by drjwbaker** [comment]
Excellent minutes. Thanks so much @anisa-hawes!

**Comment by anisa-hawes** [comment]
Dear all,

I have circulated a PDF copy of our 2022 Annual General Meeting minutes via our Google Group. 

We are grateful to those of you who were able to join us in May, and would also like to share this summary of the discussions with those who were unable to attend this time.

You can review the [minutes in Markdown format](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2022/2022_ProgHistLtd-AGM-minutes.md) within our Project and Business Archive, where you will also find Adam's [Director's Report](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2022/PHDirectorsReportAGM2022.pdf) and James's [Treasurer's Report](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2022/ProgHist.Ltd.Treasurers.Report.2022.docx) alongside our [Business Plan](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2022/ProgHist%20Business%20Plan%202022%20AGM.docx).

Best, 
Anisa

**Comment by drjwbaker** [comment]
[2022_ProgHistLtd-AGM-minutes.md](https://github.com/user-attachments/files/29328266/2022_ProgHistLtd-AGM-minutes.md)
