### ISSUE TITLE
Update ph_authors.yml

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2590]
I am making a further change to `ph_authors.yml` to update @amsichani's institutional affiliation.

**Comment by jenniferisasi** [comment]
@JoshuaGOB should be changing his too :) https://faculty.utk.edu/Joshua.Ortiz.Baco

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. I've made the changes for both Anna-Maria and @JoshuaGOB's affiliations + bios in a branch named Issue-2590. 

If I generate a PR, might you or Joshua have time to review it (including my translations)?
