### ISSUE TITLE
Adding a new element (Twitter icon + link) to our site footer 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2592]
I am adding a new element (Twitter icon + link) to our site footer.

**Comment by anisa-hawes** [comment]
I am closing this Issue and associated PR #2593, but adding the idea to a list of enhancements/user needs to address as part of a future project.

**Comment by GeeAlmeida** [comment]
We now have a Mastodon account. Just flagging this up in case we want to add a link to it in the website footer.
