### ISSUE TITLE
Collating activities to add to the research / investigacion / recherche / pesquisa pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2600]
Hello all,

I've made a couple of updates to the research / investigacion / recherche / pesquisa pages of our website this morning.
 
Are there any other recent or forthcoming publications / workshops / events / reports you've been involved in which you'd like me to add?

@programminghistorian/portuguese-team, @programminghistorian/spanish-team, @programminghistorian/french-team, @programminghistorian/english-team? 

I have noted this, which is forthcoming:

- Matthias Gille Levenson, Sofia Papastamkou & Célian Ringwald, '_Programming Historian_: un lieu de collaborations et d'interactions multiples', [DHNord 2022](https://www.meshs.fr/page/dhnord2022.5): Travailler en humanités numériques : collaborations, complémentarités et tensions, Lille, France, (22 June 2022).

**Comment by InesSalome** [comment]
Thanks for the updates @anisa-hawes ! :)

**Comment by ericbrasiln** [comment]
Hi, @anisa-hawes 
I made two presentations in May (the first one is already on the PH page, but I updated the date and the links).

Eric Brasil. “Criação, manutenção e divulgação de projetos de história em meios digitais: git, github e o programming historian”. May 20, 2022. [DOI](https://doi.org/10.5281/zenodo.6566754). Presentation [slides](https://ericbrasiln.github.io/hdfgv/) and [video](https://youtu.be/aJvjkSBETBw).

Eric Brasil. “Hemeroteca digital brasileira e a pesquisa histórica: reflexões sobre teoria e prática”. May 17, 2022. [DOI](https://doi.org/10.5281/zenodo.6568346).  Presentation [slides](https://ericbrasiln.github.io/hdufrn/) and [video](https://youtu.be/Uu3I9_a2knc).

**Comment by anisa-hawes** [comment]
Ah! Excellent! Thank you, @ericbrasiln! I'll make those changes + add the new entry!

**Comment by acrymble** [comment]
New article came out today: 

Matthew Lincoln, Sarah Melton, Jennifer Isasi, François Dominic Laramée, 'Relocating Complexity: The Programming Historian and Multilingual Static Site Generation', _Digital Humanities Quarterly_ 16, 2 (2022): http://www.digitalhumanities.org/dhq/vol/16/2/000585/000585.html
