### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by migadepan93** [programminghistorian/jekyll#2603]
I encountered an error when I tried to navigate to The Programming Historian using this link: [[PASTE URL HERE](https://programminghistorian.org/assets/basic-text-processing-in-r)]

**Comment by anisa-hawes** [comment]
Thank you, @migadepan93! I can see that the link to the assets directory has been written incorrectly as <https://programminghistorian.org/assets/basic-text-processing-in-r>. The correct full link is: <https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/basic-text-processing-in-r>. 

I am going to update this across /en/lessons/basic-text-processing-in-r, /es/lecciones/procesamiento-basico-de-textos-en-r, and /pt/licoes/processamento-basico-texto-r.
