### ISSUE TITLE
Tweetdeck retiring

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2610]
I believe we use Tweetdeck for our twitter management. This is no longer going to be supported from July 2022 so we need to make sure we can switch (probably only affects @anisa-hawes).

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. I'll look into alternatives.... At the moment, we're using Tweet Deck to set new members up as Contributors or Admins, as well as to Manage Teams and Team Roles.

**Comment by acrymble** [comment]
it turns out it's just the app they've discontinued. I think it's going to still exist as a website https://tweetdeck.twitter.com/

So this may be a non-issue.

**Comment by anisa-hawes** [comment]
Ah, you are right. We'll be able to continue accessing TweetDeck on the web.
