### ISSUE TITLE
Copyediting is not mentioned in the Editor Guidelines

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2619]
The copyediting process is only described [in the wiki](https://github.com/programminghistorian/jekyll/wiki/Copyeditors), and with a focus on what the Managing Editors should do. We are missing an explanation of the process in the Editor Guidelines (basically, when and how editors should request copyediting). 
@anisa-hawes, maybe you can describe the process for English, and then the other teams update our guidelines according to our version of the process. What do you think?

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. You are right, and overhauling our Wiki is one of the important projects on my list!

I have updated the Wiki this morning. I've changed the title of the Copyediting page, to reflect that this is one of a suite of support steps we are introducing to improve the sustainability of our lessons. I've called it [Achieving Sustainability: Copyediting, Typesetting, Archival Links, Copyright Agreements](https://github.com/programminghistorian/jekyll/wiki/Achieving-Sustainability%3A-Copyediting%2C-Typesetting%2C-Archival-Links%2C-Copyright-Agreements).

I have used that page to outline the steps involved:

1. Copyediting (original lessons only)
2. Typesetting
3. Generating archival hyperlinks
4. Documenting authorial copyright/permission to publish

The text is adapted from the guidelines I've written for myself during the past 6 months or so, as I've taken on these tasks within the EN team. We can work together to adapt/localise them for ES, FR and PT. For example, within FR we may want to include specific instructions about typographical conventions for special characters &laquo; =`&laquo;` and `&raquo;`= &raquo; and non-breaking spaces `&nbsp;` (in html) `&#x202F;` (Unicode). These are some of the specific things I've needed to learn as I've started to support step 2. for the FR team.

**Comment by spapastamkou** [comment]
> [...] For example, within FR we may want to include specific instructions about typographical conventions for special characters « =`&laquo;` and `&raquo;`= » and non-breaking spaces `&nbsp;` (in html) `&#x202F;` (Unicode). These are some of the specific things I've needed to learn as I've started to support step 2. for the FR team.

These elements are already in the French author guidelines since the last revision so if need to refer to language specificities they can be copied from there (or send to this part of the author guidelines via a link).

**Comment by hawc2** [comment]
@rivaquiroga we're you referring to the English version of the [Editorial Guidelines on the website](https://programminghistorian.org/en/editor-guidelines)? I agree it would make sense to have more about the copyediting stage there, as it's not currently mentioned. It's helpful for editors to know how copyediting fits into the process, and what standards the copyeditors help ensure before publication.

@anisa-hawes, there's also a more up to date pdf version of the English-language Editor guidelines in circulation, right? Between the website, the pdf, and the wiki, it can be hard to keep track, but ideally each step of the process would be represented in our most public facing [document](https://programminghistorian.org/en/editor-guidelines) and linked out from there to the wiki for more detailed info

**Comment by spapastamkou** [comment]
I've been thinking about this and we should definitely add it in the checklist of the ME, along with the typesetting control that is done afterwards. This way it would be clear both for the editors and the MEs (+ assistant MEs).

**Comment by rivaquiroga** [comment]
@hawc2, I am referring to the Editor Guidelines in all four languages. Copyediting, typesetting, and link archival are not mentioned there.

**Comment by anisa-hawes** [comment]
As noted in #2760, proposals for an overall revision to our Editorial Workflows remain under-discussion while we test and refine the processes, but are available (imperfect!) [to review](https://github.com/programminghistorian/ph-submissions/wiki#editorial-guidelines).

This workflow sets out the sequence of Phases in our workflow, and clarifies who is responsible for which processes at each step. 

A key difference in this proposed workflow, is that I/my team will take care of Phase 6 Sustainability + Accessibility. This will include: coordinating copyediting (original lessons only), typesetting (all lessons), generation of perma.cc archival links, collection of copyright declaration forms + request of DOI.
