### ISSUE TITLE
difficulty level needed SPARQL lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#262]
@mdlincoln your lesson has no difficulty rating! Oversight, but as I didn't edit this I don't know what value to put in. There may be other lessons that have the same problem but I don't know a quick way to check.

http://programminghistorian.org/lessons/graph-databases-and-SPARQL

**Comment by mdlincoln** [comment]
Probably a 2 or a 3, I'd guess. @fredgibbs edited it; he may have an opinion.

**Comment by fredgibbs** [comment]
my vote is for 2. it's a very clearly written lesson, but the conceptual (if not technical) difficulty is sufficiently advanced that, in comparison to many other lessons, i think a 1 would be misleading.
