### ISSUE TITLE
Onboarding Gisele Almeida, our new Education & Community Lead

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2625]
Welcome, Gisele Almeida (@GeeAlmeida)!
---
This is a checklist of tasks and conversations which @anisa-hawes is working through with our new Education & Community Lead, Gisele Almeida.

**Overview of the project:**
- [x] Introduce the About pages, including PH history
- [x] Introduce the Project Team pages and organisational structure chart
- [x] Introduce the Research pages
- [x] Introduce the Lesson Index pages, including conversation about the ways users find and filter resources to meet their learning objectives

**Internal communications:**
- [x] Set up Gmail address (community [at] programminghistorian.org)
- [x] Invite to our Google Groups
- [x] Invite to Slack
- [x] Organise welcome meetings with team members (over the coming weeks)

**External communications:** 
- [x] Introduce the PH Blog
- [x] Initiate conversation about how we could re-activate our blog to improve engagement and reach our multi-lingual communities. Qs: Rethink the platform we use? Adjust the format/tone of voice/content themes/kind of messaging?
- [x] Share examples of other newsletter/blog formats, which could provide inspiration 
- [x] Introduce our Twitter profile, including Twitter Bot Google Sheet
- [x] Add as 'contributor' on Tweet Deck
- [x] Introduce our Institutional Partner Programme (N.B. At the moment, where we ask [Want to Discuss?](https://programminghistorian.org/en/ipp#want-to-discuss) we provide a link to mailto: the PH Gmail. Q: Shall we update this to the community@ email address for initial enquiries?)
- [x] Introduce Patreon
- [ ] ~~Confirm set up of two-factor authentication for Patreon~~ (see comments below)
- [x] Initiate conversation about how we can improve communication with our Patreons and Partners, and better support/grow these communities. Ideas: Develop a 'Welcome Pack'? What 'package of benefits' come with partnerships? (a special hosted masterclass? a dedicated small-team event/training session? priority access to content?)
- [x] Introduce our YouTube Channel (N.B. At the moment, the PH Gmail is set as admin for YouTube. Q: Shall we reset this so that community@ is the administrator?) >> Notes about how to relink the YouTube account to the  community@ email, are here: https://support.google.com/youtube/answer/3056283?hl=en-GB#. Steps 1-12 under the heading Move your Brand Account to a different Google Account are the ones we need. See #2298.
- [x] Initiate conversation about how we could use YouTube/Vimeo as a platform to livestream events or host recordings of past events 

**Workflows + best practice:**
- [x] Set up GitHub Account
- [x] Invite to join Jekyll - I've granted @GeeAlmeida Write access to Jekyll
- [x] Invite @GeeAlmeida to join our organisation on GitHub [N.B. Only the owners of our repository can do this].
- [x] Introduce Jekyll Issues
- [x] Introduce the Pull Request system
- [x] Add Gisele's profile + portrait to the Project Team page
- [x] Publish a blog post to introduce Gisele
- [x] Introduce the project Wiki
- [x] Introduce Zenodo
- [x] Initiate conversation about whether Zenodo could be a good space host/store workshop materials, see [an example of our 2018 workshop in Bogotá](https://zenodo.org/record/1473414)

**Workspace + tools:**
- [x] Workspace assessment
- [x] Initiate conversation about the infrastructure that might be needed to facilitate this work, e.g., professional Zoom account to host events?, Mailchimp for Newsletters?, professional Eventbrite for ticketing?
- [x] Set up Zoom Pro account (linked to admin@ email address)
- [x] Introduce Google Analytics (N.B. 1. At the moment, the PH Gmail is set as admin for Analytics. Q: Shall we reset this so that admin@ is the administrator? 2. An upgrade to Analytics 4 will be needed this time next year July 2023, see #2551)
- [x] Gisele to work through Sarah Simpkin's lesson [Getting Started with Markdown](https://programminghistorian.org/en/lessons/getting-started-with-markdown).

**Next Steps:**
- Gisele & Anisa will co-lead a discussion at our next Project Team Meeting (Friday 9th September 15:00 UTC) about how we can expand our educational outreach programme

**Comment by acrymble** [comment]
I've sent @GeeAlmeida an invitation to the Jekyll team on github. Hopefully that works.

**Comment by acrymble** [comment]
Looks like you two are making great progress!

**Comment by anisa-hawes** [comment]
@GeeAlmeida, did you manage to solve the issue with Two Factor Authentication for Patreon? If not, this is something to chat with James about when you connect. Then we can tick off the last task and close this Issue!

**Comment by GeeAlmeida** [comment]
I can access Patreon, but have not been able to set up the two factor authentication. I'll speak to James about this.

**Comment by drjwbaker** [comment]
Hmm. I just tried to log into Patreon and I don't have 2FA setup for Patreon on my mobile.

**Comment by drjwbaker** [comment]
(for context, I haven't logged into Patreon in a long time - maybe Adam has?)

**Comment by anisa-hawes** [comment]
Oh.... I have 2FA for Patreon so I thought it might be worth Gisele setting up too. There may a limit to the number of devices from which we can log on to this service? In which case, I could disable 2FA on my side.

**Comment by drjwbaker** [comment]
Ack. Yeah. Sometimes 2FA can only connect to one device unless we can create profiles within the login (this is what Xero allows, so I can get in there but so can our accountants, should something happen to me!)

**Comment by anisa-hawes** [comment]
Okay. I'll connect with Gisele to disable 2FA on my side, and enable it on her side. (If we agree it is necessary to have 2FA?)
Then I'll close this Issue.

**Comment by drjwbaker** [comment]
Re 2FA, I guess the calculation is what do we gain/lose from it.

With 2FA off, if someone hacked our account, we'd have a valuable - if not not vital - source of income source of income stolen, possibly suffer some spamming, and lose some pride.

With 2FA on, if, for whatever reason, we lose the ability to access our 2FA, we lose the whole account (unless Patreon has a way to recover it).

So it *may* be worth turning off 2FA for this.

**Comment by acrymble** [comment]
@anisa-hawes can we just turn this off and then we can close this issue.

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. Did you already switch off the 2FA? 

I'm no longer able to log in at all from my side. I think perhaps there is a limit to the number of devices we can access our Patreon account from.

**Comment by acrymble** [comment]
No I don't have access anymore either.
