### ISSUE TITLE
Updated Link in Basic Text Processing in R 

### ISSUE THREAD

**Issue by taylor-arnold** [programminghistorian/jekyll#2629]
I recieved an email yesterday about an issue running the R code from @nolauren and my lesson "Basic Text Processing in R" It seems that everything still runs as expected, which is great given all the underlying changes to the packages we used 5+ years ago. There is however, an issue with the definition of the `base_url`variable used in the lesson. I believe it should be the following:

```
base_url <- "https://raw.githubusercontent.com/programminghistorian/jekyll/gh-pages/assets/basic-text-processing-in-r/"
```

I think this may be due to a change in which files GH shows as-is and which it provides a display for. Using `raw.githubusercontent.com` should force it to display the raw files regardless.

**Comment by anisa-hawes** [comment]
Thank you, @statsmaths! I'll update the link!

**Comment by anisa-hawes** [comment]
Hello again, @statsmaths. Just finding time to take a closer look at this. 

The link you suggest <`https://raw.githubusercontent.com/programminghistorian/jekyll/gh-pages/assets/basic-text-processing-in-r/`> doesn't work for me... It generates a 400: Invalid request. The link provided <`https://github.com/programminghistorian/jekyll/tree/gh-pages/assets/basic-text-processing-in-r`> directs me to the folder containing all the lesson's assets. 

Did you intend it to direct to a specific sub-folder or individual file within this? Which file(s) would you like to display as raw?

**Comment by taylor-arnold** [comment]
Hi @anisa-hawes, thanks for testing this out. Yes, you're correct about the behavior of actually trying to navigate to the `base_url`. However, in the lesson one is never supposed to (or instructed to) go to the base url link directly. Rather, we download files with specific filenames attached. The one I provided won't allow you to display a directory (that's why it gives 400, BAD REQUEST response), but it will allow you to get individual files within the directory. For example, here are the two different ways to see the metadata.csv file:

- [current link](https://github.com/programminghistorian/jekyll/blob/gh-pages/assets/basic-text-processing-in-r/metadata.csv)
- [proposed link](https://raw.githubusercontent.com/programminghistorian/jekyll/gh-pages/assets/basic-text-processing-in-r/metadata.csv)

The first one is nice and human readable, but it's actually an complicated HTML file that renders all of the GH information around the data itself. If you try to run the code in the lesson in R, it won't work. The second one is just a CSV file, and that's what's need to read into R. You'll get the same page by clicking on the « Raw » button that appears on the currently available link.

**Comment by anisa-hawes** [comment]
Thank you for explaining @statsmaths. I'm going to try updating the link as you've suggested, but I suspect that our Jekyll build will fail because of the 400 error it generates.

**Comment by anisa-hawes** [comment]
Dear @statsmaths, just a quick note to say that this update is complete. Thank you for getting in touch, and for explaining the fix. Very best wishes, Anisa
