### ISSUE TITLE
High-res logos

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2630]
Hello everyone - my fist issue, yay!

Last week Anisa and I were in the IHR for an event. I tried to find high-res logos on Jekyll, and only found what is [available here](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/logos). 

I then tried to recreate the logos, following the brand guidelines [found here](https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines) to create bookmarks: 
but that did not go perfectly - you can see the result in the image. Some of the shapes of the accent characters in Spanish and French are not quite as in the original.

<img width="164" alt="bookmark PH" src="https://user-images.githubusercontent.com/109232661/180435311-9c6ea5db-a6d4-4888-928c-863a0bc2e616.png">

I am opening this issue because I would like to use high-res logos to create materials for use in our communications. Does anybody have these files?

**Comment by acrymble** [comment]
Hi @GeeAlmeida the files we have are vector files, which means they can be scaled up to absolutely any size. It may be a matter of making sure you have software that can work with them effectively.

**Comment by rivaquiroga** [comment]
Hi @GeeAlmeida! [Inkscape](https://inkscape.org/) and [Gimp](https://www.gimp.org/) are open source software that can be used to work with svg files.

**Comment by GeeAlmeida** [comment]
OK, this has been helpful, I can now see that the files are vectors. It's not a format that I am used to.

I downloaded one of the files and tried to make it smaller, and it became pixelated! I am using Photopea`https://www.photopea.com/`, which is pretty much the same as GIMP, but better in my opinion. Vector files should work on this page.

Any further thoughts on this?
<img width="212" alt="example" src="https://user-images.githubusercontent.com/109232661/181588672-e2c55dc4-2a2c-485e-8f03-b6ef6a5874d6.png">

**Comment by GeeAlmeida** [comment]
<img width="212" alt="example" src="https://user-images.githubusercontent.com/109232661/181584576-d41f18ee-64f0-4f46-b9a3-73b306e6f9e1.png">

**Comment by GeeAlmeida** [comment]
Thanks everyone for your help with this issue. I have now managed to obtain the logo images I required. I have created a step-by-step guide of the process, which I have added to the [Brand Guidelines](https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines).

**Comment by acrymble** [comment]
@GeeAlmeida thank you very much for documenting it as well.
