### ISSUE TITLE
Agreeing consistent use of the date: and translation_date: fields in lesson YAML

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2642]
I am opening this Issue in response to [a conversation](https://github.com/programminghistorian/jekyll/pull/2606#issuecomment-1197981924) @DanielAlvesLABDH and I had earlier this week.

I noted that the most recently published Portuguese lesson doesn't appear at the top of the list shown in [Índice de Lições](https://programminghistorian.org/pt/licoes/) when the list is ordered by date.

Clicking into the file, I could see why. The YAML header specifies:

```
date: 2018-05-03
translation_date: 2021-12-18
```

Daniel explained that the `translation_date:` he entered represents the date the review Issue was opened in ph-submissions. 

I wondered if it would be preferable to adjust the `translation_date:` so that it reflects the date the translation has been published (rather than when the revision and peer review processes began). My understanding is that this would bring the system for dating translations into line with our system for dating original lessons, where the `date:` field, represents the date of publication.

I am not sure if this is something the MEs and editorial teams have already discussed? But I'd like to agree on a consistent use so that editors of translations across all teams use this field in the same way. 

@rivaquiroga shared that the Spanish team's practice is to enter the date a translation is published in the `translation_date:` field.

What are your thoughts? 

I'd be particularly keen to hear views from @spapastamkou (about the @programminghistorian/french-team's practice) as well as from @svmelton and @hawc2 who are preparing to publish their first translations into English over the coming months.

I think this metadata is important because it affects which volume of our journal the lesson forms part. In this case, the translation is dated in the previous calendar year, so the lesson falls into Vol.1 of _Programming Historian em português_ rather than Vol.2 (which will represent all PT lessons published in 2022). I use these dates when I add our articles to the Directory of Open Access Journals, for instance.

**Comment by rivaquiroga** [comment]
We use for both original lessons and translations the date it was published.

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga! It's really useful to understand your practice here.

**Comment by spapastamkou** [comment]
I usually modify the date to fit the last edits/final control of the Managing Editor - most of the times this corresponds to the date the pull request is raised (or is not too far from this date), so this should be the date when the file lesson is moved to jekyll. So this is close to the ES practice and actually was established with Matt Lincoln at the time (to have the lessons appear at the top of the list once published).

**Comment by anisa-hawes** [comment]
Thank you for clarifying how you date FR lessons, @spapastamkou.

**Comment by spapastamkou** [comment]
Maybe some sort of note on this should be added to the editor guidelines for the part that regards the ME's tasks.

**Comment by DanielAlvesLABDH** [comment]
Hello all. Since it seems that the best solution is to use the date of the publication or the PR that start the publication process, I agree that we should use that solution. @anisa-hawes should I open a PR to fix the translation dates to all of our lessons or are you going to do that?

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH. I think it may be best to leave the dates as they are for lessons published in the past because they may have been cited, and in some cases changing the date will change the volume number (year of publication).  

What do you think? 

But we can agree on this practice going forwards.

**Comment by DanielAlvesLABDH** [comment]
I agree @anisa-hawes and will implement that in future publications
