### ISSUE TITLE
Change IPP name (RStudio, PBC -> posit, PBC)

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2643]
If I don't write this down now I will forget it. But this is an issue for October, so I already put the "On Hold" label.
RStudio, PBC is [changing its name](https://www.rstudio.com/blog/rstudio-is-becoming-posit/) to posit, PBC. After their re-launch in October, we should change their name and website in the “Our supporters” page.

**Comment by GeeAlmeida** [comment]
Thanks for this Riva, I'll set myself a reminder to amend the info we have for them in Oct.

**Comment by rivaquiroga** [comment]
Hi, @GeeAlmeida! Since yesterday "RStudio, PBC" is "posit, PBC". Their new website is https://posit.co/

**Comment by GeeAlmeida** [comment]
Thanks for the reminder! I'll update our website with this information.
