### ISSUE TITLE
Update Wikipedia

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2653]
I came across our [Wikipedia entry](https://en.wikipedia.org/wiki/Programming_Historian) today. It looks good, but needs updating. Adding Spanish, Portuguese and French versions would be great.

The current entry does not mention Portuguese or that we are a Diamond Open Access publication.

**Comment by anisa-hawes** [comment]
Thank you, @GeeAlmeida! There is a dedicated PT Wiki page on _Programming Historian_ [here](https://pt.wikipedia.org/wiki/Programming_Historian), but I agree it would be good to update the EN version so that it reflects all our journals. 

There is also an [FR Wiki page](https://fr.wikipedia.org/wiki/Programming_Historian) and an [ES page here](https://es.wikipedia.org/wiki/Programming_Historian).

**Comment by acrymble** [comment]
@GeeAlmeida is this updated now?

**Comment by GeeAlmeida** [comment]
Not yet!

**Comment by GeeAlmeida** [comment]
I have updated the English version of our Wikipedia entry. It now mentions awards received up until 2021 and gives a bit more detail on the open access aspect of the project.

**Comment by GeeAlmeida** [comment]
I can create a Portuguese page and propose a Spanish version for a native speaker to look over. (@programminghistorian/spanish-team) --- https://es.wikipedia.org/wiki/Programming_Historian

We will need someone from the @programminghistorian/french-team to do the edits in the French version. Any volunteers?

**Comment by GeeAlmeida** [comment]
Programming Historian es una revista académica revisada por pares de humanidades digitales y metodología de la historia digital [1]. Este proyecto emblemático para los métodos de investigación de las humanidades digitales publica lecciones que ayudan a los estudiosos de las humanidades a aprender una amplia gama de herramientas digitales, técnicas y flujos de trabajo para facilitar la investigación y la enseñanza[2]. El proyecto original se basó en una serie de lecciones escritas por William J. Turkel y Alan MacEachern de la Universidad de Western Ontario en 2008.[3] El proyecto se lanzó como una revista académica durante la conferencia de Humanidades Digitales de 2012 en Hamburgo[4].
Además de la revista original en inglés, la publicación está disponible en español, francés y portugués. La apertura es um aspecto fundamental de este proyecto de Acceso Abierto Diamante: Programming Historian es de código abierto, tiene un modelo de revisión por pares abierto y una ética abierta para la planificación del proyecto. Todo el contenido es de acceso abierto y se publica bajo una licencia Creative Commons CC-BY, sin coste alguno para los autores o lectores. Esto hace que Programming Historian esté disponible en todo el mundo, incluso para lectores ubicados en el Sur Global.

El proyecto ha ganado el premio "Digital Humanities Award" dos veces. En 2016 ganó el premio a "Mejor serie de publicaciones" por su contenido en inglês. [5] En 2017 ganó el premio a "Mejor serie de publicaciones" por su contenido en español. [6] También ganó el Premio de Becas Abiertas 2020 del Canadian Social Knowledge Institute [7] y en 2021 recibió el Premio de Publicación Abierta de la Fundación Coko[8] en la categoría de Contenido Abierto. El proyecto también ha estado involucrado en temas sociales en humanidades digitales, realizando una auto-reflexión y una encuesta sobre los sesgos de género en el proyecto en 2015, en un intento por alentar una mayor participación de autores y revisores femeninos. [9][10].

La publicación está indexada en el [Directorio de Revistas de Acceso Abierto](https://es.wikipedia.org/wiki/Directory_of_Open_Access_Journals) . [8](https://es.wikipedia.org/wiki/Programming_Historian#cite_note-Directory_of_Open_Access_Journals-8) También está incluida en las bases de datos propietarias y otros recursos electrónicos en la Biblioteca de la Universidad de Harvard. [9](https://es.wikipedia.org/wiki/Programming_Historian#cite_note-9)

**Comment by GeeAlmeida** [comment]
Se alguém quiser repassar o PT:
https://pt.wikipedia.org/wiki/Programming_Historian
@programminghistorian/portuguese-team

**Comment by GeeAlmeida** [comment]
The steps needed to close this issue are:

- [x] someone to revise the Spanish text https://es.wikipedia.org/wiki/Programming_Historian
- [ ] someone to edit the french text in the French Wikipedia https://fr.wikipedia.org/wiki/Programming_Historian

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @GeeAlmeida, ficou óptimo. Sugiro apenas trocar "Diamond Open Access" por "Acesso Aberto Diamante", bem como colocar sempre em itálico "Programming Historian".

**Comment by jenniferisasi** [comment]
Hi @GeeAlmeida, thanks for working on this! I will review the text in Spanish during the day (hopefully) but on a quick, I see an award for the ES team is missing, here from the project page: "En 2018, la [Asociación de Humanidades Digitales Hispánicas](http://humanidadesdigitaleshispanicas.es/) otorgó el premio de ‘Mejor iniciativa formativa desarrollada durante el año 2018’ a Programming Historian en español."

Back to it later.

**Comment by GeeAlmeida** [comment]
> Hi @GeeAlmeida, thanks for working on this! I will review the text in Spanish during the day (hopefully) but on a quick, I see an award for the ES team is missing, here from the project page: "En 2018, la [Asociación de Humanidades Digitales Hispánicas](http://humanidadesdigitaleshispanicas.es/) otorgó el premio de ‘Mejor iniciativa formativa desarrollada durante el año 2018’ a Programming Historian en español."
> 
> Back to it later.

Well spotted, thank you.

**Comment by jenniferisasi** [comment]
Hi @GeeAlmeida, here is my review (sorry I can't edit directly on Wikipedia today but wanted to do the work anyway): 

Programming Historian es una revista académica revisada por pares de humanidades digitales y metodología de historia digital.1​ Este proyecto emblemático sobre métodos de investigación de humanidades digitales publica lecciones que ayudan a los humanistas a aprender una amplia gama de herramientas digitales, técnicas y flujos de trabajo para facilitar la investigación y la enseñanza.2​ El proyecto original está basado en una serie de lecciones escritas por William J. Turkel y Alan MacEachern de la Universidad de Ontario Occidental en 2008.3​ El proyecto se lanzó como una revista académica durante la conferencia de Humanidades Digitales de 2012 en Hamburgo.4​

Además de la revista original en inglés, la publicación está disponible en español, francés y portugués. La apertura es un aspecto fundamental de este proyecto de Acceso Abierto Diamante: Programming Historian es de código abierto, tiene un modelo de revisión por pares abierto y una ética abierta para la planificación del proyecto. Todo el contenido es de acceso abierto y se publica bajo una licencia Creative Commons CC-BY, sin coste alguno para autores o lectores. Esto hace que Programming Historian esté disponible en todo el mundo, incluso para lectores ubicados en el Sur Global.

El proyecto ha ganado el "Premio de Humanidades Digitales" dos veces. En 2016 ganó el premio a "Mejor serie de publicaciones" por su contenido en inglês.5​ En 2017 ganó el premio a "Mejor serie de publicaciones" por su contenido en español.6​ En 2018, la Asociación de Humanidades Digitales Hispánicas otorgó el premio de ‘Mejor iniciativa formativa desarrollada durante el año 2018’ a Programming Historian en español. También ganó el Premio de Becas Abiertas 2020 del Canadian Social Knowledge Institute7​ y en 2021 recibió el Premio de Publicación Abierta de la Fundación Coko8​ en la categoría de Contenido Abierto. El proyecto también ha estado involucrado en temas sociales en humanidades digitales, realizando una auto-reflexión y una encuesta sobre los sesgos de género en el proyecto en 2015, en un intento por alentar una mayor participación de autoras y revisoras.9​10​

La publicación está indexada en el Directorio de Revistas de Acceso Abierto.11​ También está incluida en las bases de datos propietarias y otros recursos electrónicos en la Biblioteca de la Universidad de Harvard

**Comment by GeeAlmeida** [comment]
Thanks @jenniferisasi - that is done!

**Comment by anisa-hawes** [comment]
cc. @marie-flesch

Hello Matthais @matgille and Célian @datalogism,

I hope you are both well?

Gisele has been working on updating the Wikipedia entries for each of our journals, and we'd like to ask if you might have time to help us with the FR translation?

There are just a few changes, and I have drafted the following in French for you to review (many sentences are collated from the existing FR wiki and /fr/apropos but please let me know any errors!) :

Le Programming Historian en français est une revue universitaire évaluée par les pairs portant sur les humanités numériques et la méthodologie de l'histoire numérique. La revue publie des leçons qui aident les humanistes à maîtriser un large éventail d’outils numériques, de techniques et de méthodes de travail qui facilitent la recherche et l’enseignement. Une première version du projet, qui consistait en une série de leçons écrites par William J. Turkel et Alan MacEachern de l'Université Western Ontario au Canada, est parue en 2008. Le lancement de la revue sous sa forme actuelle a eu lieu lors de la conférence Digital Humanities 2012 à Hambourg.

La revue publie des leçons en anglais, en espagnol et en français. Elle fonctionne sous un modèle d'évaluation ouverte par les pairs et tout dépôt fait sur le Programming Historian en français est publié sous licence Creative Commons ‘CC-BY’ selon le modèle de publication en libre accès de la ‘voie diamant’ sans frais pour les auteurs ou les lecteurs. Cela permet à Programming Historian d'être disponible dans le monde entier, y compris pour les lecteurs des pays du Sud.

Le projet a remporté un prix "Digital Humanities Award" à deux reprises. En 2016, il a remporté le prix de la "Meilleure série d'articles" ("Best Series of Posts") pour son contenu en anglais. En 2017, il a remporté le prix de la "Meilleure série d'articles" pour son contenu en espagnol.  En 2018, Programming Historian en espagnol était le vainqueur de ‘Mejor iniciativa formativa desarrollada durante el año 2018’, Humanidades Digitales Hispánicas Association. Nous avons remporté le Canadian Social Knowledge Institute’s Open Scholarship Award en 2020 et en 2021 nous avons été récompensés d’un Coko Foundation’s Open Publishing Award dans la catégorie Contenu Ouvert. Le projet a également été impliqué dans les questions sociales liées aux humanités numériques, notamment en procédant à une auto-réflexion et à une enquête sur les biais de genres dans le projet en 2015, dans le but d'encourager une plus grande participation des femmes à titre d'auteures et d'évaluatrices.

La revue est indexée par le Directory of Open Access Journals. Elle est également répertoriée parmi les bases de données propriétaires et autres ressources électroniques par la bibliothèque de l'Université Harvard.

On the [EN Wiki page the wording is as follows](https://en.wikipedia.org/wiki/Programming_Historian):

> The Programming Historian is a [peer-reviewed](https://en.wikipedia.org/wiki/Peer-reviewed) [academic journal](https://en.wikipedia.org/wiki/Academic_journal) of [digital humanities](https://en.wikipedia.org/wiki/Digital_humanities) and [digital history](https://en.wikipedia.org/wiki/Digital_history) methodology.[[1]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-1) This flagship resource for digital humanities research methods publishes tutorials that help humanities scholars learn a wide range of digital tools, techniques, and workflows to facilitate research and teaching.[[2]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-2) The original project was based upon a series of lessons written by William J. Turkel and Alan MacEachern of the [University of Western Ontario](https://en.wikipedia.org/wiki/University_of_Western_Ontario) in 2008.[[3]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-3) The project launched as an academic journal during the Digital Humanities 2012 conference in [Hamburg](https://en.wikipedia.org/wiki/Hamburg).[[4]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-Digital_Humanities_2012:_The_Programming_Historian_2-4)

> The journal publishes in [English](https://en.wikipedia.org/wiki/English_language), [Spanish](https://en.wikipedia.org/wiki/Spanish_language), [French](https://en.wikipedia.org/wiki/French_language), and [Portuguese](https://en.wikipedia.org/wiki/Portuguese_language). Openness is the cornerstone of this Diamond [Open Access](https://en.wikipedia.org/wiki/Open_access) project: it is open source, has an open peer review model, and an open ethos to project planning. All content is open access and released under a [Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons) CC-BY license, with no cost to authors or readers. This makes Programming Historian available around the world, including to readers in the Global South.

> The project has twice won a "Digital Humanities Award". In 2016 it won "Best Series of Posts" for its English-language content.[[5]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-Digital_Humanities_Awards_2016-5) In 2017 it won "Best Series of Posts" for its Spanish-language content.[[6]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-Digital_Humanities_Awards_2017-6) In 2018, The Programming Historian en español, was the winner of ‘Mejor iniciativa formativa desarrollada durante el año 2018’, [Humanidades Digitales Hispánicas Association](https://humanidadesdigitaleshispanicas.es/). It also won the Canadian Social Knowledge Institute’s Open Scholarship Award 2020[[7]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-7) and in 2021 it was awarded the Coko Foundation’s Open Publishing Award[[8]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-8) in the Open Content category. Programming Historian has also been involved in social issues in digital humanities, conducting a self-reflection and survey into gender biases in the project in 2015 in an attempt to encourage more participation from female authors and reviewers.[[9]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-9)[[10]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-10)

> Programming Historian is indexed by the [Directory of Open Access Journals](https://en.wikipedia.org/wiki/Directory_of_Open_Access_Journals).[[11]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-Directory_of_Open_Access_Journals-11) It is also listed among proprietary databases and other e-resources at Harvard University Library.[[12]](https://en.wikipedia.org/wiki/Programming_Historian#cite_note-12)

**Comment by anisa-hawes** [comment]
When it comes to applying these updates in the New Year, we can also update the name of the French Managing Editor: from Sofia Papastamkou to Marie Flesch.

**Comment by GeeAlmeida** [comment]
I have changed the name of the French Editor on Wikipedia on Wed. I have also added the logos of the French, Spanish and Portuguese journals to their respective entries.

**Comment by marie-flesch** [comment]
Hello @matgille et @datalogism, est-ce que l'un de vous a le temps de regarder ça ? Sinon, je m'en occupe :) Dites moi !

**Comment by datalogism** [comment]
Hello ! je peux m'en occuper fin de semaine ! I could take a moment at the end of the week !

**Comment by marie-flesch** [comment]
Super, merci Célian !

**Comment by matgille** [comment]
Salut ! Je n'ai pas vu la notification, il faut que je revoie mes paramètres. Après relecture rapide: 
- premier paragraphe RAS

> La revue publie des leçons en anglais, en espagnol et en français. Elle fonctionne sous un modèle d'évaluation ouverte par les pairs et tout dépôt fait sur le Programming Historian en français est publié sous licence Creative Commons ‘CC-BY’ selon le modèle de publication en libre accès de la ‘voie diamant’ sans frais pour les auteurs ou les lecteurs. Cela permet à Programming Historian d'être disponible dans le monde entier, y compris pour les lecteurs des pays du Sud.

Elle fonctionne **selon un modèle**; et tout dépôt: ajouter une virgule avant. **voie diamant**: ajouter le lien plus précis vers la section wiki (https://fr.wikipedia.org/wiki/Libre_acc%C3%A8s_(%C3%A9dition_scientifique)#La_voie_diamant%C3%A9e)

> Le projet a remporté un prix "Digital Humanities Award" à deux reprises. En 2016, il a remporté le prix de la "Meilleure série d'articles" ("Best Series of Posts") pour son contenu en anglais. En 2017, il a remporté le prix de la "Meilleure série d'articles" pour son contenu en espagnol. En 2018, Programming Historian en espagnol était le vainqueur de ‘Mejor iniciativa formativa desarrollada durante el año 2018’, Humanidades Digitales Hispánicas Association. Nous avons remporté le Canadian Social Knowledge Institute’s Open Scholarship Award en 2020 et en 2021 nous avons été récompensés d’un Coko Foundation’s Open Publishing Award dans la catégorie Contenu Ouvert. Le projet a également été impliqué dans les questions sociales liées aux humanités numériques, notamment en procédant à une auto-réflexion et à une enquête sur les biais de genres dans le projet en 2015, dans le but d'encourager une plus grande participation des femmes à titre d'auteures et d'évaluatrices.

Là il faudrait pouvoir préciser qui attribue ces différents prix (c'est un problème de la version anglaise en fait). **était le vainqueur de**: remporte le prix de. **Humanidades Digitales Hispánicas Association**: asociación de Humanidades Digitales Hispánicas (HDH); le passage à la première personne du pluriel ne va pas pour du contenu encyclopédique. Il faut garder la 3e personne du singulier (nous > l'initiative a remporté, etc)

Bonne semaine !


Matthias

**Comment by datalogism** [comment]
Finalement pas plus à redire que @matgille  !

**Comment by marie-flesch** [comment]
Merci @matgille et @datalogism ! Je vais finaliser le texte ; je pense qu'il faut aussi modifier les guillemets pour respecter les conventions typographiques de Wikipédia.

**Comment by marie-flesch** [comment]
Hi @GeeAlmeida, I've finalized the text. Do you want me to put it up on Wikipedia?


Le Programming Historian en français est une revue universitaire [évaluée par les pairs](https://fr.wikipedia.org/wiki/%C3%89valu%C3%A9e_par_les_pairs) portant sur les [humanités numériques](https://fr.wikipedia.org/wiki/Humanit%C3%A9s_num%C3%A9riques) et à méthodologie de l'[histoire numérique](https://github.com/programminghistorian/jekyll/issues/v). La revue publie des leçons qui aident les humanistes à maîtriser un large éventail d’outils numériques, de techniques et de méthodes de travail qui facilitent la recherche et l’enseignement. Une première version du projet, qui consistait en une série de leçons écrites par William J. Turkel et Alan MacEachern de l'[Université Western Ontario](https://fr.wikipedia.org/wiki/Universit%C3%A9_de_Western_Ontario) au Canada, est parue en 2008. Le lancement de la revue sous sa forme actuelle a eu lieu lors de la [conférence Digital Humanities](https://fr.wikipedia.org/wiki/Digital_Humanities_conference) 2012 à Hambourg.
La revue publie des leçons en [anglais](https://fr.wikipedia.org/wiki/Anglais), en [espagnol](https://fr.wikipedia.org/wiki/Espagnol) et en [français](https://fr.wikipedia.org/wiki/Fran%C3%A7ais). Elle fonctionne selon un modèle d'évaluation ouverte par les pairs, et tout dépôt fait sur le Programming Historian en français est publié sous [licence Creative Commons](https://fr.wikipedia.org/wiki/Creative_Commons) « CC-BY » selon le modèle de publication en libre accès de la « voie diamant » sans frais pour les auteurs ou les lecteurs. Cela permet au Programming Historian d'être disponible dans le monde entier, y compris pour les lecteurs des pays du Sud.
Le projet a remporté un prix « Digital Humanities Awards » à deux reprises. En 2016, il a remporté le prix de la « Meilleure série d'articles » (« Best Series of Posts ») pour son contenu en anglais. En 2017, il a remporté le prix de la « Meilleure série d'articles » pour son contenu en espagnol. En 2018, le Programming Historian en espagnol s’est vu décerner le prix de « Mejor iniciativa formativa desarrollada durante el año 2018 » de l’Humanidades Digitales Hispánicas Association. Le Programming Historian a remporté le Canadian Social Knowledge Institute’s Open Scholarship Award en 2020, et a été récompensé d’un Coko Foundation’s Open Publishing Award dans la catégorie « Open content » (« contenu ouvert ») en 2021. La revue est également impliquée dans les questions sociales liées aux humanités numériques, notamment en procédant à une auto-réflexion et à une enquête sur les biais de genre dans le projet en 2015, dans le but d'encourager une plus grande participation des femmes à titre d'auteures et d'évaluatrices.
La revue est indexée par le [Directory of Open Access Journals](https://fr.wikipedia.org/wiki/Directory_of_Open_Access_Journals). Elle est aussi répertoriée parmi les bases de données propriétaires et autres ressources électroniques par la bibliothèque de l'Université Harvard.

**Comment by GeeAlmeida** [comment]
Thanks for this @marie-flesch ! I'll try to put it up on the French Wikipedia. I'll let you know if I need help.

**Comment by GeeAlmeida** [comment]
All 4 languages have been completed :)
https://fr.wikipedia.org/wiki/Programming_Historian
https://en.wikipedia.org/wiki/Programming_Historian
https://es.wikipedia.org/wiki/Programming_Historian
https://pt.wikipedia.org/wiki/Programming_Historian
