### ISSUE TITLE
Twitter Hashtags

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2654]
Hello everyone

I want to tap into our collective intelligence to improve PH communications. This is the first of other issues that will seek to get your input to amplify our voice online.

As the title gives away, I want to compile a list of hashtags to be used in our tweets, so more people see our content and also so we can start to engage with discussions related to topics we care about. So far I only have the following:

#twitterstorians

#DigitalHumanities

#HumanidadesDigitais

#HumanitésNumériques

If you know of any other hashtags I can use or should keep an eye on (in English, Spanish, Portuguese or French), please let me know.

**Comment by drjwbaker** [comment]
#dhist

**Comment by rivaquiroga** [comment]
#HumanidadesDigitales

There are some hashtags related to more specific topics, such us #computationalliterarystudies or #corpuslinguistics. And some for specific tools, like #rstats for things related to the R programming language, or #python and #python_es

**Comment by spapastamkou** [comment]
#histnum (<= histoire numérique)

S

Le mer. 10 août 2022 à 15:03, Riva Quiroga ***@***.***> a
écrit :

**Comment by GeeAlmeida** [comment]
Great stuff everyone, thanks a lot!

**Comment by DanielAlvesLABDH** [comment]
Sorry for the late reply @GeeAlmeida. #humanidadesdigitais and #historiadigital are two commom hastags

**Comment by GeeAlmeida** [comment]
Obrigada Daniel :)

**Comment by GeeAlmeida** [comment]
Thanks to everyone who contributed, I have made a note of the suggested hashtags and will be adding them to PH tweets!
