### ISSUE TITLE
Project Team Meeting: Friday 23 September 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2659]
Project Team Meeting: Friday 23 September 2022
--

Date: Friday 23 September 2022
Time: [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20220923T150000&p1=1440)
Zoom link: https://zoom.us/j/5959205456
Minutes of the last meeting: [03_2022_ProjectTeamMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Project-Team-Meetings/03_2022_ProjectTeamMeeting.md)

---

**All members who are available to join us are encouraged and welcome.**

Our September Project Team Meeting will be a first opportunity for the whole Project Team to meet our new Education & Community Lead, Gisele Almeida @GeeAlmeida. 

The meeting will take the form of an open group discussion about developing our educational outreach and events programme. It will be an opportunity to collaborate and shape plans for community-facing activities to support our communities.

Gisele and I will add an agenda/discussion framework to this Issue early next month.

_Please note that we've needed to adjust the [previously advertised date](https://github.com/programminghistorian/jekyll/issues/2494) of this meeting, due to staff availability. We hope that many of you will still be able to join us._

**Comment by GeeAlmeida** [comment]
@programminghistorian/project-team 
Here are three files we want to share with you ahead of our meeting:

**1. Breakdown of PH's audience:**

<img width="1337" alt="PH Audiences" src="https://user-images.githubusercontent.com/109232661/188200157-2376bde3-cea5-4b21-82ca-f8c924b2dc28.png">

**2. Ideas of events for the different groups:**

<img width="1435" alt="PH Events" src="https://user-images.githubusercontent.com/109232661/188200162-ea7122a6-cf05-4e7e-aa9e-ad79b9d3439a.png">

**3. The mindmap that led to the above:** (click to enlarge)

<img width="1678" alt="Mindmap" src="https://user-images.githubusercontent.com/109232661/188200947-02ba2eb3-9a7e-4c6f-bee9-cdc551a7a6c2.png">

**Comment by drjwbaker** [comment]
Hey @GeeAlmeida, just want to say that I love the audience model: really should help us think through how and what to do in an eduation space.

**Comment by GeeAlmeida** [comment]
@programminghistorian/project-team 
This is another gentle reminder of our meeting next Friday! I have just emailed everyone about it. See you then!

**Comment by spapastamkou** [comment]
Please note I am currently with Covid, and might be unable to assist although I'll do my best. cc @programminghistorian/french-team 
Thank you.

**Comment by rivaquiroga** [comment]
I teach in that time slot, so I won't be able to join :broken_heart:

**Comment by JMParr** [comment]
J'espère que tu te sens mieux, Sofia!

**Comment by anisa-hawes** [comment]
Dear all,

Thank you for the energy and ideas you contributed to our Project Team Meeting in September.

The minutes are in our private repository [09_2022_ProjectTeamMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Project-Team-Meetings/09_2022_ProjectTeamMeeting.md).

As always, please let me know if I've missed any important points, or mis-represented something you said. I'm happy to make adjustments.

Very best,
Anisa.
