### ISSUE TITLE
Corpus Analysis lesson needs figure syntax

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#266]
It looks like all the images for the Corpus Analysis lesson by @heatherfro are currently hosted on the author's Wordpress site. It looks like we have all the images in a [subdirectory in our repo](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/froehlich), but several things still need to be done:
- [ ] That subdirectory needs to be renamed to `corpus-analysis-with-antconc`
- [ ] Within the lesson itself, all the image codes need to be changed to our [special figure syntax](http://programminghistorian.org/new-lesson-workflow#figures). I would do this myself, but someone with more familiarity with the lesson should probably choose the captions for each image

**Comment by fredgibbs** [comment]
fixed with 76621e3
