### ISSUE TITLE
Rethinking the platforms we use for internal communications

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2660]
I am opening this Issue to resurface [a conversation we had](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Project-Team-Meetings/03_2022_ProjectTeamMeeting.md) at our Project Team Meeting in March.

During that meeting, Maria José observed that GitHub has become a natural archive of our decision-making. Meanwhile, important conversations were/and are increasingly happening on Slack. In the minutes, I recall typing out her question: _who will be responsible for archiving those conversations as part of the history of the project?_

That question has come back into my thoughts in the last couple of weeks.

Any members of the team who regularly use Slack will have noticed a pop up banner which has recently appeared on the platform, alerting us to the fact that from 1st September, messages and files older than 90 days will be "hidden". Slack describe this as a "visibility limit", and explain that "members can continue to send messages, but older messages will be archived. If you [upgrade your workspace to a paid subscription](https://my.slack.com/plans), all archived messages will become available again". You can read more [here](https://slack.com/intl/en-gb/blog/news/pricing-and-plan-updates) and [here](https://slack.com/intl/en-gb/help/articles/115002422943-Message-file-and-app-limits-on-the-free-version-of-Slack).

![Screenshot 2022-08-12 at 22 31 39](https://user-images.githubusercontent.com/87070441/184447624-aec39cd1-946c-4595-8467-9a766a8c56ac.png)

So, September seems like a good time for us to have another conversation about how we want to communicate, how we want to chat, and how/if we want to archive those interactions as part of the history of this project.

**Comment by rivaquiroga** [comment]
What about moving to Discord? It has voice/video channels for quick meetings. And the app doesn't consume as much RAM as Slack, so it works perfectly on older devices.

**Comment by drjwbaker** [comment]
Thanks for starting this @anisa-hawes. Getting away from Slack seems sensible. I understand that Discord could work well, but have zero experience.

**Comment by ericbrasiln** [comment]
> What about moving to Discord? It has voice/video channels for quick meetings. And the app doesn't consume as much RAM as Slack, so it works perfectly on older devices.

I've been using Discord in undergraduate/graduate courses and to supervise student researches and I think it works well, particularly voice/video channels, screen sharing, and bots to creating polls and automatic answers.
I know there are bots and apps to download messages from Discord servers, but I don't know of an official Discord feature for that. However, from what I've read, old messages on Discord are not deleted or hidden from users.

**Comment by hawc2** [comment]
Are we sure these upcoming changes to Slack affect us? Don't we have the nonprofit pro plan? My understanding is that we are eligible for that through TechSoup and that the nonprofit plan for Slack isn't being affected by these changes. 

Personally, I would not be in favor of changing the platform away from Slack to Discord, but if a majority of people on the team would be more likely to use Discord and engage in discussion, then let's go for it. That's a big change, though, so let's not make the leap too quickly.

If our main concern is being able to archive our messages, what does Discord offer that Slack doesn't?

**Comment by spapastamkou** [comment]
I would suggest considering to continue to use Slack for quick exchanges and when a given exchange leads to more extensive discussion to then open an issue on Github where more members can theoretically participate and in any case the issue will be archived as usual. This said, I do not use Discord and am no familiar with its possible advantages - it seems to me though that it could be more difficult to archive.

**Comment by anisa-hawes** [comment]
I've been investigating @hawc2's suggestion of applying for a Slack for Charities Pro Subscription (which is free :slightly_smiling_face:) but I have found that I can’t because I’m not the owner/administrator of our organisational channel. Who is? 

I'd like to take the next step/find out what's new for Pro users and discover whether or how we would be able to archive our chats if we took that option forwards.

**Comment by rivaquiroga** [comment]
With Ctrl+shift+E you can search people by role on Slack. It looks like @walshbr is the owner, and  @ZoeLeBlanc is the administrator.

**Comment by ZoeLeBlanc** [comment]
Happy to help with this @anisa-hawes but also want to add my vote towards moving to Discord. Also previously I've used existing tools to download Discord messages when I need to calculate student participation. But generally just want to support us using either of these platforms more often over google groups or emails since they are difficult for these types of conversations.

**Comment by walshbr** [comment]
FWIW I think you can have multiple owners, @ZoeLeBlanc is also an owner according to the dashboard. It looks I can't self-remove myself as owner but feel free to do so, Zoe :)

**Comment by ZoeLeBlanc** [comment]
Just made you member @walshbr and you owner @anisa-hawes (wasn't sure if owner or admin was better but went with owner for now)

**Comment by anisa-hawes** [comment]
Thank you, @ZoeLeBlanc! I will investigate our options for Slack for Charities Pro Subscription and am also researching how easy/difficult it is to set up a Discord server. If anyone has knowledge to share on this, let me know.

**Comment by ZoeLeBlanc** [comment]
Thanks @anisa-hawes 🙏🏽 ! Everything I learned about Discord came from @rccordell Ryan Cordell's post https://ryancordell.org/teaching/classroom-discord/

**Comment by anisa-hawes** [comment]
A thought: with either option, it would be good to make our admin or owner admin [@] programminghistorian.org. This would help us to future-proof our access to any communication platforms we use going forwards.

My personal email appears to be locked when I click into my profile in Slack's settings...

**Comment by anisa-hawes** [comment]
Dear all, I apologise for leaving this Issue hanging. 

I have been thinking about this, and how I can help to create a space for informal, internal dialogue. 

- [x] I've read some documentation, plus various forums and blog posts to learn more about Discord
- [x] I've created an account associated with my admin@ email address
- [ ] I got stuck on a verification step, which prompts me to associate my account with a phone number. My hope was to create a 'neutral' admin account for our organisation, rather than link it to any individual. Might not be possible?

**Comment by spapastamkou** [comment]
I have a Discord account without any phone number associated, so this should be possible?

**Comment by anisa-hawes** [comment]
Okay. Maybe I'll go through that step and then see if I can remove my telephone number. I also had to give them a date of birth, and decided to give one which isn't mine (!) but is easy to remember for anyone in the future. Now I think about it, that might be what caused the problem...

**Comment by hawc2** [comment]
@anisa-hawes could we still pursue getting the Non-Profit discount for Slack Pro? Is it just that you don't have admin access to the organizational account? 

Even if we're going to migrate to Discord, it would be nice in the meantime to get free access to Pro so we can see our chat histories in Slack.

**Comment by anisa-hawes** [comment]
Thank you for raising this again, @hawc2.

Updates:

- [x] I have resolved the Issue I encountered which locked my personal email address to my profile in our Slack organisation, so _admin[@]programminghistorian.org_ is now the registered owner of our Slack space. 

- [x] I submitted an application to the Slack Nonprofits programme, which has been approved. Thank you for the suggestion, Alex! ✨  We now have a Complimentary Pro plan, which is available for up to 250 active users. The key benefits of this plan include: full access to our organisation’s message history, and the option to use audio and video conversations for up to 15 participants.

- I notice that the majority of people who actively use our Slack channels are on the English Team, with the addition of a few from the Spanish Team. It may be that others are not currently Slack users or are not interested in joining?

- [x] Meanwhile, I’ve also set up a Programming Historian Discord Server community 🎉  as requested by several people in this Issue thread. I have set up 'webhooks' so that notifications from our Jekyll and ph-submissions repos will automatically arrive in two named channels, (as they do at the moment in Slack). 

At risk of inundating you with all emails via the Google Group today, I will set myself a reminder to send out joining links for those two platforms next Wednesday. I would like to make this an opportunity to extend an invitation to all current members of the @programminghistorian/project-team to join us on Slack or Discord or both !

I will be very interested to learn which of these discussion spaces appeals to you, and which provides us with the most useful place for informal chat and direct messages between teams.

**Comment by hawc2** [comment]
That's great @anisa-hawes !

Intersting to know who on PH team uses Slack. Sounds like I should use email to reach the whole team rather than Slack #general channel

**Comment by anisa-hawes** [comment]
- We now have complimentary Pro access as part of Slack's Nonprofit Programme. If you are new to Slack, there’s a [Quick Start Guide](https://slack.com/intl/en-gb/help/articles/360059928654-How-to-use-Slack--your-quick-start-guide) and a range of [Slack tutorials](https://slack.com/intl/en-gb/help/categories/360000049063) available.

- We now have a Discord Server for our community. If you are new to the platform, there’s [a guide to Getting Started](https://support.discord.com/hc/en-us/categories/115000217151-Getting-Started) which includes a [Beginner's Guide to Discord](https://support.discord.com/hc/en-us/articles/360045138571).

@programminghistorian/project-team Please contact me if you'd like me to send you a fresh invitation link to join either platform ✨
