### ISSUE TITLE
Jekyll lesson needs figure syntax

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#267]
The images in our Jekyll lesson by @amandavisconti need to be updated with the [syntax for figures](http://programminghistorian.org/new-lesson-workflow#figures): I could do this myself, but it might be good for author or editor to go through and give each image a descriptive caption. (The caption also becomes the `alt` text under the hood, so calling them all "screenshot" makes them less accessible.)

**Comment by amandavisconti** [comment]
I can do this.

**Comment by amandavisconti** [comment]
[Fixed](https://github.com/programminghistorian/jekyll/commit/0f31c35df1cc1c0bd6d75abb36796774c00e57b9).
