### ISSUE TITLE
Proposition to create kanban-style project for managing portuguese editorial workflow

### ISSUE THREAD

**Issue by ericbrasiln** [programminghistorian/jekyll#2670]
Hello @programminghistorian/portuguese-team 

I would like to suggest the creation of a kanban-style project titled **PT PH Submissions & Publication Track** following the model of those that already exist for the [English](https://github.com/programminghistorian/jekyll/projects/3), [French](https://github.com/programminghistorian/jekyll/projects/5) and [Spanish](https://github.com/programminghistorian/jekyll/projects/4) teams.

The aim is to maintain an organized board of the entire editorial workflow of the Portuguese team. I believe it'll help a lot in organizing, visualizing and managing our workflow.

The column model existing in the other projects can serve as a basis for the Portuguese version.

What do you think? It is necessary?

Perhaps the @programminghistorian/french-team and @programminghistorian/spanish-team can give us their thoughts on the advantages/disadvantages of using these boards in workflow management.

If the portuguese team finds it useful and possible to be implemented, I can help in the organization of the board, columns, etc, as I have already used this structure in other researches.

**Comment by rivaquiroga** [comment]
@ericbrasiln, using the board has been very useful! I don't see any disadvantage.
With @anisa-hawes we've been talking about using the new version of GitHub projects, which allows you to connect the board to current open issues. We still have to test all the new features.

**Comment by ericbrasiln** [comment]
Yes @rivaquiroga! I totally agree with you. And i'm already using the new version of Projects and it's great! You can create table or board views for the  project's items, generate charts, and the integration with issues is really nice.

**Comment by nllano** [comment]
I completely agree with you two, Riva and Eric. This is my first experience with Projects, but I am really enjoying how easy and clean the whole process looks this way.

**Comment by acrymble** [comment]
Great to see efforts to improve the workflow. I had a look at the English Kanban and the one thing it seems to be missing is a sense of how long something has been stuck at a particular point in the publication cycle. I know other publishing workflow tools tend to have clear automated warnings, either stoplight colours or a prominently listed number of days, to help MEs know when something needs prodding.

I'm not sure we have that, and from looking at the submissions board it looks like it's a problem our project is facing, as several have been in submission a really long time with little movement.

**Comment by ericbrasiln** [comment]
That's a good point, @acrymble. I think one way to handle this in GitHub Projects (Classic) is to add labels on late issues.

We could create a workflow on GitHub Actions to automatically label issues that are in a given project column for a specific period of time. But of course this would require some research and testing before implementing it. Therefore, it may be a solution that will consume too much time and effort.

On the other hand, the new GitHub Projects has more options for visualizing the workflow, such as Tables where you can group issues by labels, milestones, reviewers, assignees, pull requests.
Perhaps this will be a better option in the future. In fact I suggest that the @programminghistorian/portuguese-team version uses this new Projects.

**Comment by rivaquiroga** [comment]
Just a note: we've been discussing with @anisa-hawes about using the new GitHub Projects. The possibility of grouping issues by labels, milestones, reviewers, etc., allows us to have one board for all the four publications. 
Regarding @acrymble comment, as @ericbrasiln mentions we can create a GitHub action that add a specific label or post a message when a ticket has been open for X number of days. The idea of moving all the boards to a new GitHub Project is to start using this kind of features.

**Comment by ericbrasiln** [comment]
> Just a note: we've been discussing with @anisa-hawes about using the new GitHub Projects. The possibility of grouping issues by labels, milestones, reviewers, etc., allows us to have one board for all the four publications. Regarding @acrymble comment, as @ericbrasiln mentions we can create a GitHub action that add a specific label or post a message when a ticket has been open for X number of days. The idea of moving all the boards to a new GitHub Project is to start using this kind of features.

That would be amazing! If you need any help, you can count on me.  😄 

@rivaquiroga @anisa-hawes Do you suggest to leave the Portuguese Kanban on hold, while the idea of moving all boards to a new GitHub Project is under discussion?

**Comment by DanielAlvesLABDH** [comment]
Dear all, sorry for the long silence on this. It was my decision in the beginning of the Portuguese project not to use this feature. I had so many other things to learn about GitHub at the time and so many other things to do that I didn't realize the benefits of this. Talking to Eric today we both agree that implementing this to manage our work would be better now, since we have too many issues, translations and other workflows open at the moment. If the other teams decide to move on with the idea of having only one project to manage all four teams we also agree. Many thanks and sorry again for being late in this discussion.

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln for opening this Issue and to all who have contributed so far. 

Thank you @DanielAlvesLABDH for your support, too.

Eric and I are going to connect next Friday 9th September to chat about GitHub Projects Beta, and think about how we can collaborate 🙂

**Comment by anisa-hawes** [comment]
I have been working with MEs to create a Project Board that serves across all four journals. 

Managing Editors and editors now have the choice to access an overview (of all active lessons) in [Board format](https://github.com/orgs/programminghistorian/projects/5/views/1) or [Chart format](https://github.com/orgs/programminghistorian/projects/5/views/2) or indeed, simply to access an Overview of active lessons in each journal if preferred: 
[English](https://github.com/orgs/programminghistorian/projects/5/views/6)
[Español](https://github.com/orgs/programminghistorian/projects/5/views/5)
[Français](https://github.com/orgs/programminghistorian/projects/5/views/4)
[Português](https://github.com/orgs/programminghistorian/projects/5/views/7)

Additionally, I've created an Overview of active lessons in our special series:
[2021/22-JiscTNA](https://github.com/orgs/programminghistorian/projects/5/views/8)

--

With thanks to @ericbrasiln + @rivaquiroga for initial brainstorming and testing, and to all the MEs for their willingness to trial a different way of working.

**Comment by ericbrasiln** [comment]
Hi @anisa-hawes 

The Project Board looks amazing! It will make our job much simpler!
