### ISSUE TITLE
Marie-Christine Boucher stepping down

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2672]
Related to #2277. @mariechristineb is stepping down for the FR team. Here is a list of what we have to do at the team level: 

- [x] Remove Google Groups access (@anisa-hawes)
- [x] Remove Google Analytics access (@acrymble) ?
- [x] Remove Github Jekyll access (@ZoeLeBlanc)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@anisa-hawes)
- [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@anisa-hawes) OR @spapastamkou 
- [x] There are no open issues assigned to MCB - checked by @spapastamkou 
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts (@anisa-hawes).

**Comment by spapastamkou** [comment]
@anisa-hawes MC was mentionned somewhere in the wiki as the person to contact for the FR team for bug resolution. I do not seem to find this page but I will check again. I drop this here to not forget.

**Comment by spapastamkou** [comment]
@mariechristineb Merci pour ton service et bonne chance pour la suite. A bientôt!

**Comment by mariechristineb** [comment]
@spapastamkou Merci, Sofia! Ce fut un plaisir de collaborer avec l'équipe sur ce projet. À bientôt!

P.S. C'est ici que mon nom est mentionné: [Lesson Maintenance Workflow](https://github.com/programminghistorian/jekyll/wiki/Lesson-Maintenance-Workflow)

**Comment by acrymble** [comment]
@mariechristineb very best wishes for your next adventure!

**Comment by anisa-hawes** [comment]
> P.S. C'est ici que mon nom est mentionné: [Lesson Maintenance Workflow](https://github.com/programminghistorian/jekyll/wiki/Lesson-Maintenance-Workflow)

Thank you, @mariechristineb.

I have removed your name from the list of external assessors on the Lesson Maintenance Workflow wiki page.

**Comment by anisa-hawes** [comment]
Dear @spapastamkou. I'm not able to remove Marie-Christine from our organisation on GitHub – I think that only the owners of our repository are able to do this. Are you able to help @acrymble?

N.B. I am able to remove write access to outside collaborators, but I double checked and Marie-Christine is not listed as having any access permissions (neither on Jekyll nor ph-submissions)

Meanwhile, I have removed Marie-Christine's access to our Twitter account.

**Comment by spapastamkou** [comment]
Thanks @anisa-hawes !
Maybe I should ping @ZoeLeBlanc ro check this?

**Comment by ZoeLeBlanc** [comment]
I can do it! Just to confirm Marie-Christine's just on the French team correct? Once I remove her, then any forks or branches of her's will be deleted so just want to double check we are ready to remove her. Thanks!

**Comment by spapastamkou** [comment]
@ZoeLeBlanc Yes, I confirm MCB is only in the FR team and she was on sabbatical since some months, so nothing should be broken, if you remove her. Cheers!

**Comment by anisa-hawes** [comment]
Thank you, @ZoeLeBlanc. She is on the [Project Team](https://github.com/orgs/programminghistorian/teams/project-team/members?query=membership:child-team), and in the [French Team](https://github.com/orgs/programminghistorian/teams/french-team/members).

**Comment by ZoeLeBlanc** [comment]
Thanks @spapastamkou and @anisa-hawes ! Just removed her from both. Think final thing is to remove her from the org but wondering if we want to transfer to outside collaborator or not 🤔 ? Not sure that was an option before... thoughts @anisa-hawes ?

**Comment by anisa-hawes** [comment]
I plan to open a separate issue to document this work, but I've been doing some spring cleaning of ph-submissions recently, to remove outside collaborators who are neither actively authoring/translating or reviewing. 

Looking through the list, I found that we had many people who contributed 1, 2, 3, years ago yet still had write access. If Marie-Christine, or anyone else _needs_ write access to work on a lesson in the future, we can invite her as an outside collaborator when necessary. Does that sound reasonable?

**Comment by spapastamkou** [comment]
Thank you both @anisa-hawes and @ZoeLeBlanc. 
Anisa: I did some cleaning too some time ago and would perhaps be good to do this more systematically.

Sounds fine to invite people as outside collaborators when necessary (and not "stock" them as such for years).

**Comment by ZoeLeBlanc** [comment]
Thanks both!! I just removed Marie-Christine from the org as well so think that's it for her stepping down. Thanks for all your hard work 👏🏽

**Comment by mariechristineb** [comment]
Thanks everyone! It was a pleasure to collaborate on such a great project :heart:

**Comment by acrymble** [comment]
The last task will be covered by #2688
