### ISSUE TITLE
Setting up a semi-regular audit of branches and outside collaborators 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2677]
I have recently carried out some tidying across our two key repositories: /programminghistorian/jekyll/ and /programminghistorian/ph-submissions.

- [x] I have cleared all stale and merged branches (both repos).
- [x] I have removed write access from all outside collaborators who are not actively authoring/translating or reviewing (ph-submissions). I found that we had many people who contributed 1, 2, 3+ years ago yet still had write access.

This is about saving space across our repos as well as protecting the integrity of our work-in-progress.

I've set a reminder within my schedule to carry out this kind of basic audit on a quarterly basis going forwards. 

In the meantime I would like to encourage you to delete branches when you've merged them or no longer need them, and to grant write access for outside collaborators where necessary but limit that access to the period of time they are actively contributing.

**Comment by spapastamkou** [comment]
Thank you @anisa-hawes.
