### ISSUE TITLE
Adding author info for guest blog posts

### ISSUE THREAD

**Issue by tapar001** [programminghistorian/jekyll#268]
Just posted Liz Venditto's guest post and realized that since's she a guest contributor, the "About the author" field at the bottom of the post is blank. 

Possibilities as I see them: 

1) Remove "About the author" for guest posts? 
2) Create a brief bio for each guest author? 

Ideas? @wcaleb do you have any strong feelings about whether 1 or 2 above would be more appropriate, or maybe you have another idea? 

For now I added an editor's note at the bottom of the post saying who Liz is--but this doesn't feel like the best solution. (For what it's worth I first added that editor's note at the top of the post, but then that's what readers would see in the post preview on the main blog page. I'd rather people see Liz's words first, not mine.) 

I won't promote the post until we get this sorted. Thanks!

**Comment by wcaleb** [comment]
Second option preferable. Add her in the _data/authors.yml file with a brief bio. 

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by tapar001** [comment]
Got it, thanks @wcaleb!
