### ISSUE TITLE
Getting PH listed in resources databases

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2682]
Hi everyone @programminghistorian/project-team!

Today I started to identify DH resource databases and email them asking if they would like to list our awesome and incredibly resourceful website in their pages. The ones I already identified and contacted are [the MIT](https://libguides.mit.edu/digitalhumanities) and the [dhcenter](https://dhcenter-unil-epfl.ch/en/resources/).

Please let me know of other similar DH resource lists you are aware of, and I will nudge them as well.

**Comment by GeeAlmeida** [comment]
Already listed:
https://guides.lib.utexas.edu/digitalhumanities/resources
https://libguides.northwestern.edu/dh/resources
https://guides.loc.gov/digital-scholarship/resources


Added:
https://dhcenter-unil-epfl.ch/en/resources/

**Comment by GeeAlmeida** [comment]
Wrote to:
MIT
Bodleian (Oxford)

**Comment by acrymble** [comment]
@GeeAlmeida does this have an end goal for us to be able to close the ticket? It feels like there may not be an end to possible repositories

I think the reason you may not be getting suggestions is that most of us don't use these in our own work.

**Comment by GeeAlmeida** [comment]
> @GeeAlmeida does this have an end goal for us to be able to close the ticket? It feels like there may not be an end to possible repositories
> 
> I think the reason you may not be getting suggestions is that most of us don't use these in our own work.

Hi Adam
I intend to use this ticket to keep track of the repositories I identify and communicate with.

Is what you did this morning of looking through tickets something you do? I'd rather receive comments via email if that is ok?

**Comment by GeeAlmeida** [comment]
Hi Adam @acrymble 
I intend to use this ticket to keep track of the repositories I identify and communicate with.

**Comment by nivaca** [comment]
I have requested that the four editions of PH be added to https://oaji.net/.

**Comment by anisa-hawes** [comment]
Maybe this would be another resource list worth being on?: https://dighumlab.org/category/learning-resources/e-learning/

**Comment by anisa-hawes** [comment]
Another idea is to re-investigate https://open.umn.edu/opentextbooks/. 

Adam shared this resource link with me a few month's before you joined us, and I found that we don't (at the moment) meet one of their criteria: _Must be a complete textbook available as a complete portable file (e.g. PDF, EPUB)._

I know this is something that has been discussed within the Project Team in the past and decided against. But it is something I've been thinking about in relation to users’ needs, e.g., to be able to download and save our lessons to read offline. I wonder whether we could consider packaging the past ‘volumes’ of our journals as PDFs? (a volume = lessons published by each journal during one year)

**Comment by acrymble** [comment]
We've just had these recommended at work:

OpenStax
•Open Textbook Library
•Pressbooks Directory
•Directory of Open Access Books
•OER Commons

I haven't looked into them.

**Comment by GeeAlmeida** [comment]
I have now contacted openstax, asking if they would like to list our materials among their resources.
They replied, pointing me towards their partnership webpage: https://openstax.org/general/openstax-ally-technology-partner-program. 

The next application period will open again mid December through mid January.

**Comment by GeeAlmeida** [comment]
> Maybe this would be another resource list worth being on?: https://dighumlab.org/category/learning-resources/e-learning/

Definitely, plus they are an IPP! I have written to our contact at the Digital Humanities Lab Denmark.

**Comment by GeeAlmeida** [comment]
> I have requested that the four editions of PH be added to https://oaji.net/.

@nivaca did you get a reply?

**Comment by nivaca** [comment]
> @nivaca did you get a reply?
@GeeAlmeida, unfortunately not. But the request to include our four editions is still ongoing, so it seems.

**Comment by spapastamkou** [comment]
Antonio Rojas Castro and then I had registered PH ES and FR in OER commons (and perhaps EN as well or it was already there). Please check again however.

**Comment by spapastamkou** [comment]
after verification, it was actually [the global PH](https://www.oercommons.org/courses/the-programming-historian) I myself had registered on OER commons. So for [this registry](https://www.oercommons.org/), mentioned by Adam, the FR and PT editions are not in yet. @GeeAlmeida

**Comment by GeeAlmeida** [comment]
Thanks for this Sofia! @spapastamkou

**Comment by GeeAlmeida** [comment]
> H ES and FR in O

Spanish and English were listed in OER. French and Portuguese were not.

I submitted them to the OER today. Let's see if they will list this time.

**Comment by GeeAlmeida** [comment]
I've asked UCLA's digital humanities program today: https://dh.ucla.edu/

**Comment by GeeAlmeida** [comment]
> > H ES and FR in O
> 
> Spanish and English were listed in OER. French and Portuguese were not.
> 
> I submitted them to the OER today. Let's see if they will list this time.

I've received a confirmation that French is now listed. No word on the Portuguese though.

**Comment by GeeAlmeida** [comment]
Resource lists to try to get into:
https://guides.lib.udel.edu/c.php?g=85603&p=548857
Email: kabner@udel.edu

https://guides.lib.ku.edu/c.php?g=95126&p=616810
Email: brianlee@ku.edu

**Comment by spapastamkou** [comment]
thanks @GeeAlmeida !

**Comment by GeeAlmeida** [comment]
Requested insertion here:
https://ezb.uni-regensburg.de/db_prop.phtml?bibid=AAAAA&colors=7&lang=en

**Comment by GeeAlmeida** [comment]
Checked and we are in EBSCO (US database)

**Comment by DanielAlvesLABDH** [comment]
Hi @GeeAlmeida , do I need to do anything about this? https://zdb-katalog.de/list.xhtml?t=programming+historian&asc=false
And this? https://ezb.uni-regensburg.de/db_prop.phtml?bibid=AAAAA&colors=7&lang=en

**Comment by GeeAlmeida** [comment]
> Hi @GeeAlmeida , do I need to do anything about this? https://zdb-katalog.de/list.xhtml?t=programming+historian&asc=false And this? https://ezb.uni-regensburg.de/db_prop.phtml?bibid=AAAAA&colors=7&lang=en

Hi @DanielAlvesLABDH no, I don't think so. I have requested insertion to the second link. When I get a chance I will ask in the first link. Thank you!

**Comment by GeeAlmeida** [comment]
To investigate:

https://researchguides.njit.edu/oer/textbooks/repositories

**Comment by acrymble** [comment]
@GeeAlmeida you could productively use these opportunities to tell them about IPP. Most of these resources you're finding seem to be individual universities.

**Comment by anisa-hawes** [comment]
I came across Surf.nl last week, <https://www.surf.nl/en/education-it/digital-educational-resources> which I understand is the closest equivalent to Jisc in The Netherlands. Might be worth looking into too? 

Perhaps worth cross-referencing #2535 here in case they offer Subscription Management as well as resource listings?

**Comment by GeeAlmeida** [comment]
from issue #2535: 

- [X] EBSCO https://www.ebsco.com/academic-libraries (we are already there)
- [X] JSTOR https://www.jstor.org/ (English submitted via online form 07/12 - not yet online 23/12)
- [ ] Surf.nl https://www.surf.nl/en/education-it/digital-educational-resources (emailed 23/12, again 22/02)
- [ ] Arts & Humanities Citation Index / [Web of Science](https://clarivate.com/products/scientific-and-academic-research/research-discovery-and-workflow-solutions/web-of-science/core-collection/editorial-selection-process/)
- [ ] [Scopus](https://suggestor.step.scopus.com/suggestTitle/step1.cfm)
- [ ] [ERIH PLUS](https://kanalregister.hkdir.no/publiseringskanaler/erihplus/login.action)
- [ ] [Google Scholar](https://support.google.com/scholar/troubleshooter/23941?hl=en) - see comment below (23/12)
- [ ] [OpenStax](https://docs.google.com/forms/d/1ZJmYy3y-fv3GhiPdjyV96637sF72r72kGi19Iq2RWKk/viewform?edit_requested=true) - Registrations accepted through January 20th, 2023
- [x] [ProQuest](https://about.proquest.com/en/publishers/) - contacted 14/12 - received a reply 6/01 (they will review our content and if they find it suitable they will grab it from our website).
- [x] [DOAJ](https://doaj.org/) - we are here
- [x] [MIAR](https://miar.ub.edu/idioma/es ) - four languages added
- [x] [ROAD](https://road.issn.org/) - we are here
- [ ] [Latindex](https://latindex.org/latindex/postulacion/registroDirectorio) - Used [this link](https://latindex.org/latindex/editores/formEditores) to have the English journal included on 23/12. If this works, use it for the remaining 3 journals.
- [ ] [MERLOT](https://www.merlot.org/merlot/login.htm)


Resource lists to try to get into:
https://guides.lib.udel.edu/c.php?g=85603&p=548857
Email: [kabner@udel.edu](mailto:kabner@udel.edu)

https://guides.lib.ku.edu/c.php?g=95126&p=616810
Email: [brianlee@ku.edu](mailto:brianlee@ku.edu)

em Portugues needs to be added to:
https://zdb-katalog.de/list.xhtml?t=programming+historian&asc=false


Looked at:
- SPARC https://sparcopen.org/ (not for us, pro-open access NGO. Interesting list of supporting orgs though)
- Lyrasis https://www.lyrasis.org/Pages/Main.aspx (lots of paid options)
- CRL https://www.crl.edu/ (not pertinent)
- https://www.coalition-s.org/ (not pertinent)
- https://researchguides.njit.edu/oer/textbooks/repositories (already looked at the listed options)

**Comment by GeeAlmeida** [comment]
I have completed JStor's form today requesting that they include the English journal in their website. If this works I need to do the same with French, Portuguese and Spanish.

**Comment by GeeAlmeida** [comment]
• Arts & Humanities Citation Index ([Web of Science](https://clarivate.com/products/scientific-and-academic-research/research-discovery-and-workflow-solutions/web-of-science/core-collection/editorial-selection-process/)
• [Scopus](https://suggestor.step.scopus.com/suggestTitle/step1.cfm)
• Historical Abstracts
• ERIH PLUS

> 

Registrations accepted through January 20th, 2023
https://docs.google.com/forms/d/1ZJmYy3y-fv3GhiPdjyV96637sF72r72kGi19Iq2RWKk/viewform?edit_requested=true

**Comment by GeeAlmeida** [comment]
> Wrote to: MIT Bodleian (Oxford)

Nothink has come out of my attempts - checked today and they did not list PH.

**Comment by GeeAlmeida** [comment]
> > Maybe this would be another resource list worth being on?: https://dighumlab.org/category/learning-resources/e-learning/
> 
> Definitely, plus they are an IPP! I have written to our contact at the Digital Humanities Lab Denmark.

I have written to them today requesting insertion

**Comment by GeeAlmeida** [comment]
> Let's see if they will list this time.

No reply and no insertion either

**Comment by GeeAlmeida** [comment]
> > @nivaca did you get a reply?
> > @GeeAlmeida, unfortunately not. But the request to include our four editions is still ongoing, so it seems.

@nivaca Do you think it's time to reapply, or should I give them more time?

**Comment by GeeAlmeida** [comment]
> 

Are you familiar with OpenStax? They have an open call for applications, but I am not sure if [this](https://docs.google.com/forms/d/1ZJmYy3y-fv3GhiPdjyV96637sF72r72kGi19Iq2RWKk/viewform?edit_requested=true) is for us?

Here are some of the questions in their form that I don't know to answer: 
What are our goals over the next 18 months, What is our stance on OER and why are we interested in partnering with OpenStax? What is the greatest advantage a partnership with OpenStax could offer our business?

**Comment by GeeAlmeida** [comment]
There is something called [The Open Library of Humanities](https://www.openlibhums.org/), an initiative from Birkbeck (University of London). Two DH journals are listed: Digital Studies / Le champ numérique and Digital Medievalist. If PH wants to be included, the form needs to be filled out by the editors.

**Comment by GeeAlmeida** [comment]
A note on Google Scholar: I have been unable to use their [form](https://support.google.com/scholar/troubleshooter/23941?hl=en) to request inclusion in the GS index. Can someone with more technical knowledge give it a go and report back here? @programminghistorian/technical-team 

Here is their information on what we need to do:
https://scholar.google.co.uk/intl/en/scholar/inclusion.html

[This](https://www.ardaconference.com/blog/how-to-index-articles-in-google-scholar/) and [this](https://www.greenlanemarketing.com/resources/articles/the-current-state-of-google-scholar/) are the best resources I found about getting indexed by GS.

**Comment by GeeAlmeida** [comment]
> > H ES and FR in O
> 
> Spanish and English were listed in OER. French and Portuguese were not.
> 
> I submitted them to the OER today. Let's see if they will list this time.

04/01/23 An update: French is now included. No sign of Portuguese. Might need to ask for the inclusion of Portuguese again.

**Comment by GeeAlmeida** [comment]
I made a request to the Library of Congress (U.S.) and it looks like they will include our journals in their Electronic Resources Online Catalog. I'll update here with a link when I receive the confirmation.
