### ISSUE TITLE
Re-establishing access to our Patreon account 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2683]
I'm opening this issue to ensure that we can re-establish access to our Patreon account. 

In the course of conversation in #2625, we decided to turn off 2 Factor Authentication, but now neither @acrymble or myself can access the account.

**Comment by anisa-hawes** [comment]
Hello @drjwbaker. When you have a moment, could you check whether you're able to access our Patreon account?

I'm wondering if we might need to prompt a password re-set.

**Comment by drjwbaker** [comment]
I can't access it either.

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. You won't see this note until tomorrow, but when you have a chance could you check if you can still access Patreon? I'm really confused about what has happened here...

**Comment by anisa-hawes** [comment]
@GeeAlmeida has solved the mystery! Our Patreon account is now linked to community [@] programminghistorian.org. Password remains the same as before. Two Factor Authentication is OFF. I've updated [the Service Integrations page](https://github.com/programminghistorian/project-and-business-archive/blob/master/service-integrations/ProgHist-Service-Integrations.md#patreon).
