### ISSUE TITLE
Tech Team project team descriptions

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2684]
I've spoken to @ZoeLeBlanc and @hawc2 about the way we describe our 'tech team' on the project team page. This reflects an old way of working, and puts 'responsibility' for the website with the Tech Team members who are volunteers. We've also got some members of our wider team who have provide (or continue to provide) valuable tech support to our staff, for improving or fixing things on the website. I propose changing the team descriptions from:

```
Technical Lead: Coordinates and trains members of the technical team
Technical Team: Responsible for the technical features that bring the content and peer review to our community
```

to

```
Technical Lead: Has oversight over our publishing technical infrastructure and website
Infrastructure Support Team: Has provided valuable voluntary support, technical advice, or development of our website over an extended period
```

I think this better acknowledges publicly that we're grateful for that work, but removes the responsibility element. @ZoeLeBlanc can you let me know what you think?

**Comment by acrymble** [comment]
@ZoeLeBlanc can you let me know if you're happy with this?

**Comment by ZoeLeBlanc** [comment]
This looks great to me @acrymble! Hopefully with this change we can also start to plan for the RnD team as well! 

I can go ahead and do PR for this unless you want to Adam.
