### ISSUE TITLE
Workshop ADHO 2023

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2686]
Hi Alex, Zoe and Scott

I started this issue because I don't have all of your emails. Plus this gives an opportunity to everyone in the @programminghistorian/project-team who wants to collaborate a chance to join us at this early stage. So, for those of you who were not there, during our team meeting on Friday Alex suggested putting together an application for a workshop to be presented at the ADHO 2023 conference. The deadline for applications is in a month, 25 October.

I wonder if we can get together this week to talk about ideas and possibilities? Alex has placed the CFA into this [document](https://docs.google.com/document/d/19UGOEBRXVrmwAlHh0DCzTo89Bpth9CQbSoxbxCQq4UQ/edit) 
I created a [Doodle](https://doodle.com/meeting/participate/id/dyry0gne) to find a time that works for everyone.

**Comment by hawc2** [comment]
Here's the CFP online (took me a while to find it): https://dh2023.adho.org/?page_id=308

**Comment by GeeAlmeida** [comment]
This ticket can be closed, as a proposal has been submitted. Thanks to all involved!
