### ISSUE TITLE
Updating Register of Members

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2688]
This is an administrative thing we have to do at ProgHist from time to time to keep the register of members up to date. I've sent a draft to @drjwbaker to check over. I'll close this when we've confirmed it.

**Comment by drjwbaker** [comment]
@acrymble Apologies. This did get actioned. But yes, latest changes to the FR need to be taken into account for the November revision.

**Comment by acrymble** [comment]
Ok great, thanks. We only have to update every 6 months I believe, so I'll call this closed.
