### ISSUE TITLE
Twitter Bot

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2691]
I am looking at editing the Twitter bot. I want to add content and filter out some old content.

I wonder if anyone (@programminghistorian/project-team) can give me more information on how it works? I'll drop my main questions below:

- If I add or delete rows, how does that interfere with the bot's schedule of publications?
- I would like to move things that seem to be in the wrong tab (Portuguese in English tab), is it safe to just cut and paste?
- Is there any way I can have more control over what goes out when? Is there a logic/pattern the bot is following?
All help appreciated!

**Comment by spapastamkou** [comment]
You can check the instructions for the bot here: https://github.com/programminghistorian/proghistbot especially for the third point

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. Yes! I can help!

We use a Twitter Bot as a tool to initiate promotion of new lessons, and help activate lessons from our past catalogue.

You can add, edit, cut or paste rows of the Google Sheet. Our Bot promotes one lesson a week at random, which means that we don't have control over when it will select a specific row. 

Each row represents a pair of Tweets to be posted within one week. We create two related Tweets to communicate a message, and then reinforce it. Each pair of Tweets is complemented with a link, to a lesson or related page of our website.

“message_one” (column A) is posted early in a week
“message_two” (column B) is a short follow-up Tweet to be posted later in the same week
“link” (column C) a live link to a published lesson/or another page of our website.

You should leave column D blank and untouched – the Xs you will find in this field represent the Bot's log of its progress.

In particular, I think you can feel empowered to take ownership of the Communications tab!

**Comment by jenniferisasi** [comment]
Chiming in to add to @anisa-hawes, briefly, take ownership of the Comms tab 💯

**Comment by acrymble** [comment]
@GeeAlmeida are we able to close this ticket or do you need more information?

**Comment by GeeAlmeida** [comment]
> @GeeAlmeida are we able to close this ticket or do you need more information?

Still working on this. I'll close the ticket when I am done with the changes I want to make in the bot.

**Comment by nabsiddiqui** [comment]
@GeeAlmeida I was asked a while ago to post about this lesson on the Twitter Bot here: https://github.com/programminghistorian/ph-submissions/issues/343. 

Is it possible that when you figure this out that you add this tweet? I'm a little loss on where we are in the process of the Twitter Bot and am trying to get it off my todo list.

**Comment by hawc2** [comment]
@nabsiddiqui I didn't realize we hadn't done that for the computer vision lesson, but it's a part of the process that's supposed to happen right at the time of publication, so it's good for you to know how to do it for the next lesson you publish. You're just supposed to add a new line for the English tab at the top of the sheet with the twitter message as described in this thread and on the [proghistbot repo](https://github.com/programminghistorian/proghistbot). 

@GeeAlmeida to @acrymble's question, it seems like this ticket can be closed. Our guidelines might need to be updated to better guide people to these final steps, but that's separate from your original issue question

**Comment by hawc2** [comment]
FYI @nabsiddiqui the author of that lesson did a big twitter thread at the time that the PH Twitter account retweeted, so I'm not sure it's necessary at this point to add it to the bot retroactively

**Comment by jenniferisasi** [comment]
@hawc2 and @nabsiddiqui it is necessary to add two tweets about the lesson, regardless if the author tweets/-ed about it because the bot will cycle through the lessons and, eventually, tweet about that lesson again, and again, and again unless taken down if we retire the lesson. You could include a link to the author's thread on one of the tweets, however.

**Comment by hawc2** [comment]
oh ok good to know, thanks @jenniferisasi!

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. A quick note to say that if there are any Tweets you'd like to remove from the the Twitter Bot, you could follow the instructions [here](https://github.com/programminghistorian/jekyll/wiki/Retiring-a-Lesson-from-the-Twitter-Bot) to paste rows into the Deprecated tab of the sheet.

**Comment by ZoeLeBlanc** [comment]
Hi Everyone! I think for now we should freeze the bot until we figure out both where to move the bot (could move to Google Cloud https://developer.twitter.com/en/docs/tutorials/how-to-create-a-twitter-bot-with-twitter-api-v2 or potentially Netlify) and also whether we still want to use a bot to promote lessons or not (perhaps looking at the data we get from #2734 ). The @programminghistorian/technical-team will work on this at our next meeting in December 😊

**Comment by acrymble** [comment]
@ZoeLeBlanc I think @GeeAlmeida finds the bot quite frustrating because it is unpredictable and not always on message, so it would be good to discuss with her how it fits in communication plans moving forward before devoting dev time to it!

**Comment by hawc2** [comment]
yeah our discussion today was leaning towards the bot not being necessary...

**Comment by ZoeLeBlanc** [comment]
Ya there might be a middle ground we're we have more custom options with the bot so it's less unpredictable and easier to edit too. But we are definitely also considering how it fits within the broader communication strategy. @GeeAlmeida would you be able to join our next tech team meeting at 9am Central Time on December 8? If yes I can send you a zoom link! Alternatively we could chat on PH Slack, so lmk what works for you 😊

**Comment by spapastamkou** [comment]
Note to ourselves: if we are to move the bot, we should update the editors guidelines where the link towards the Gsheet is provided, if I am not mistaken, twice. 

And a question (for here or for your meeting): what do we do in a short term perspective? There are several lessons to be published in the coming weeks; in this case, should the editors prepare tweets for the bot (this or a future one)? Thanks!

**Comment by GeeAlmeida** [comment]
> Ya there might be a middle ground we're we have more custom options with the bot so it's less unpredictable and easier to edit too. But we are definitely also considering how it fits within the broader communication strategy. @GeeAlmeida would you be able to join our next tech team meeting at 9am Central Time on December 8? If yes I can send you a zoom link! Alternatively we could chat on PH Slack, so lmk what works for you 😊

Happy to be there! Send a Zoom link to community@programminghistorian.org please!

**Comment by anisa-hawes** [comment]
> Note to ourselves: if we are to move the bot, we should update the editors guidelines where the link towards the Gsheet is provided, if I am not mistaken, twice.
> 
> And a question (for here or for your meeting): what do we do in a short term perspective? There are several lessons to be published in the coming weeks; in this case, should the editors prepare tweets for the bot (this or a future one)? Thanks!

Thank you, @spapastamkou. In the short term, I think editors should continue to prepare x2 Tweets at the time of a lesson's publication and add it to the existing Google Sheet. Whatever decision is made about a new method or a new platform for communications, I think one of the considerations will be how we want to highlight/remind readers about new and old lessons.

**Comment by spapastamkou** [comment]
@anisa-hawes Great, thanks a lot. I think so as well, since it will frankly be difficult to catch afterwards something not done in its time.

**Comment by GeeAlmeida** [comment]
> hin the broader communication strate

Zoe do send me a link, I intend to be there tomorrow!
My email is community@programminghistorian.org

**Comment by anisa-hawes** [comment]
> 
> Zoe do send me a link, I intend to be there tomorrow! My email is [community@programminghistorian.org](mailto:community@programminghistorian.org)

- [x] I'm emailing you the meeting information now

**Comment by GeeAlmeida** [comment]
@programminghistorian/project-team 

The last bot tweet was on 29/11. Seems this process has been terminated!

I think it's fine to quiet it down during the festive season. But an alternative for the new year would be good. In the technical meeting Zoe suggested looking at a bot that publishes to Mastodon, and that then gets replicated in Twitter.
