### ISSUE TITLE
Events Calendar 2022-23

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2692]
We need to establish an events calendar for the coming year. This will be led by @GeeAlmeida.

I'm creating a ticket where she can plan and otherwise seek input from stakeholders.

| Month  | Date | Title | Language | Type |
| ------------- | ------------- |  ------------- | ------------- | ------------- |
|  November 2022 |  16/11 | Aprende a crear tutoriales para el Programming Historian | ES  | Interview |
|  December 2022 | 16/12  | Teaching with Programming Historian | EN  | Roundtable |
|  January 2023 | tbd  | tbd  | PT  | tbd  |
|  February 2023 | tbd   | tbd  | tbd  | tbd  |
|  March 2023 | tbd   | tbd  | tbd  | tbd  |
| April 2023 | tbd   | tbd  | tbd  | tbd  |
| May 2023  | tbd   | tbd  | tbd  | tbd  |
|  June 2023 | tbd   | tbd  | tbd  | tbd  |
| July 2023 | tbd   | tbd  | tbd  | tbd  |
| August 2023 | tbd   | tbd  | tbd  | tbd  |
| September 2023  | tbd   | tbd  | tbd  | tbd  |

**Comment by GeeAlmeida** [comment]
For Dec the idea is to invite 2-3 lecturers who use our tutorials with their students, to discuss how that goes, how helpful they are, etc.
Names of people you know use PH with students would be really helpful!
@programminghistorian/project-team

**Comment by anisa-hawes** [comment]
Dear @GeeAlmeida. Sending you an email about this, introducing you an educator I met in Denmark last week who uses PH in their teaching in particularly inspiring ways ✨

**Comment by GeeAlmeida** [comment]
For December our guests are:
Joana Vieira Paulino
Nicolas Vaughan
Jessica Parr

More details to follow soon!

**Comment by GeeAlmeida** [comment]
For January I am in conversation with the Portuguese team. The idea is to partner with a Brazilian university (FGV) and use the occasion to celebrate 30 lessons published in Portuguese. The date is tbc, either 18 or 20/01.

**Comment by GeeAlmeida** [comment]
I suggest that we create a tag "Events" and that should make it easy for people to follow each event's issue. This issue is basically duplicating content already inserted in the issues created for each event.

**Comment by anisa-hawes** [comment]
Yes, we can create a new 'Events' Label here on GitHub Issues.

Click Labels > Edit Labels > New Label > Label name > Description (optional) > [choose colour] > Create Label.


(You can edit the colour or the label name if you like 🙂 )

**Comment by GeeAlmeida** [comment]
Thanks @anisa-hawes for creating the new Events tag. Now people can follow the events through the tag. This means this issue can be closed.
