### ISSUE TITLE
adding to the research / investigacion / recherche / pesquisa pages

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2700]
Hi everyone

This is a new issue to collate research activities related to PH.

Have you got something to add? Put it in a comment below and it will appear on the website in the coming weeks!

**Comment by GeeAlmeida** [comment]
Japanese translation of William J. Turkel and Alan MacEachern, [The Programming Historian](http://niche-canada.org/programming-historian), 1st ed. NiCHE: Network in Canadian History & Environment (2007-11): https://sites.google.com/site/theprogramminghistorianja/

**Comment by acrymble** [comment]
I found this which I don't see on there: https://halshs.archives-ouvertes.fr/halshs-02277639/

**Comment by GeeAlmeida** [comment]
I'll make this update on Friday - if you have anything to add, do it before then!

**Comment by jenniferisasi** [comment]
Invited talk to a class: 
Isasi, Jennifer. "_Programming Historian_: A Collaborative Project to Put Programming Within the Reach of Humanists," Language Technologies for Digital Humanities, within the Global Digital Humanities degree, University of Mondragón, Spain (14 November 2022).

**Comment by spapastamkou** [comment]
Invited participation to a workshop: 
Sofia Papastamkou, Participation à l'atelier "Formation et compétences pour les différents types d’acteurs : pratiques pédagogiques et didactique", animé par Dorothée Benhamou-Suesser et Madeleine Géroudet. Cycle d'ateliers du projet ResPaDon. Paris, Bibliothèque nationale de France, 6 octobre 2022 https://respadon.hypotheses.org/1755

EN: 
Sofia Papastamkou, Participation to the workshop  "Formation et compétences pour les différents types d’acteurs : pratiques pédagogiques et didactique", coordinated by Dorothée Benhamou-Suesser and Madeleine Géroudet. The Workshops of the ResPaDon project. Paris, Bibliothèque nationale de France, 6 October 2022 https://respadon.hypotheses.org/1755

**Comment by rivaquiroga** [comment]
Roundtable discussion at a conference:

EN
Riva Quiroga. [“Open Review in Journals”](https://perma.cc/NC2A-6LL3). Roundtable discussion at XI International Conference BIREDIAL-ISTEC (7 October 2022). 

ES
Riva Quiroga. [“Evaluación abierta en revistas”](https://perma.cc/NC2A-6LL3). Mesa de discusión de la XI Conferencia Internacional BIREDIAL-ISTEC (7 de octubre de 2022).

**Comment by acrymble** [comment]
Daniel van Strien is hosting a workshop at the British Library on 17 November to do a guided tour of his lesson 'Computer Vision for the Humanities' as part of the 'Digital Scholarship Training Programme' at the library.

**Comment by GeeAlmeida** [comment]
including the added items to the website
