### ISSUE TITLE
PH calendar of events - November

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2701]
Hi everyone @programminghistorian/project-team 

Our first PH event is in the works. It will be in Spanish, and will be an interview with Riva (@rivaquiroga). 

Title: Aprende a crear tutoriales para el Programming Historian
Theme: creating PH tutorials and translations/localisation issues
Format: interview (Riva Quiroga)
Language: Spanish
Date: 16/11 
Time: 15:00 UTC
Zoom info: to be shared with participants ✨

**Comment by GeeAlmeida** [comment]
[[Registration page](tinyurl.com/chtutoria)](https://www.ticketsource.co.uk/null/t-jzxqmgm)
![Riva Quiroga](https://user-images.githubusercontent.com/109232661/197271948-1436ca86-1212-4661-93e5-0b7b06db2e30.png)
![Riva Quiroga 2](https://user-images.githubusercontent.com/109232661/197271978-43b4f586-1a93-4973-a413-c44421fd9a46.png)

**Comment by drjwbaker** [comment]
'Registration page' link above doesn't work.

**Comment by acrymble** [comment]
@drjwbaker I've updated it above. It was fine on Twitter. I'm not sure where else it's gone out but hopefully just an error here.

**Comment by anisa-hawes** [comment]
The Spanish Team are helping us to circulate and promote this event within our Spanish-speaking networks:

- [x] @mariajoafana is sharing it via the LatamHD mail list that is managed by the Red de HD <http://humanidadesdigitales.net/> in Mexico and will also circulate among PhD students at Universidad de los Andes.

--

We would be grateful if other Spanish-speakers in the @programminghistorian/project-team are able to help spread the word among networks at your universities, with Spanish-speaking PhD students/early career researchers in your departments:

The event will take place on **16th November at 15:00 UTC**. It is free to attend. A full description (in Spanish) is available here: <https://tinyurl.com/chtutoria> including a link for people to click and register. 

Gisele also prepared a Tweet in Spanish [here](https://twitter.com/ProgHist/status/1585343000804085760), which you may like to Retweet with your circles.

**Comment by jenniferisasi** [comment]
I will share it with a couple of contacts (Humanidades Digitales Hispánicas (Spain) and Asociación Argentina de HD). But is there a cap to attendance, I see in the registration link that there are only 14 passes available? Thanks!

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi! 

I'm sorry to say that I'm not sure about whether there is a limit to the number of attendees... 

Is this something you know, @rivaquiroga?

If not, I'll need to wait for Gisele to be able to confirm.

**Comment by rivaquiroga** [comment]
@anisa-hawes, I have no idea about how the event was created on that platform :broken_heart:. I don't believe we should limit the number of attendees.

**Comment by drjwbaker** [comment]
@anisa-hawes Thanks for looking into this. If we are going to use ticketsource, we'll need this added to our service integrations (which I'm sure you've thought about already!).

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker. That is a very good point. 🙂 

I'll organise a catch up with Gisele next week so that we can make sure our Service Integrations are up-to-date. It's key that more than one person in the team knows the what/why/how of any services we use. 

- [x] Gisele has shared the login credentials with me and I've saved them in my password manager
- [x] I've added this information to the Service Integrations page

**Comment by rivaquiroga** [comment]
Maybe we can keep using Eventbrite, as in previous events. It is available in different languages, so it is easier for non-English speakers to register.

**Comment by anisa-hawes** [comment]
Hello @rivaquiroga. On my browser (Chrome), there is an embedded Google Translate tool in the lower left corner of the Ticket Source page, where I can select a language to translate into. Does this display on your browser too? 
![Screenshot 2022-11-02 at 17 21 05](https://user-images.githubusercontent.com/87070441/199558451-634ad06e-ffa1-4f12-85bd-de958713ea50.png)

**Comment by rivaquiroga** [comment]
No. I'm also using Chrome. In the lower-left corner I have the cookie preferences menu. 
I know people can enable Google Translate on their browsers and that the translation might be good enough for them to be able to register. But it is not the same experience as having a localized platform that will also adjust things like timezone.

**Comment by anisa-hawes** [comment]
Thank you for letting us know @rivaquiroga. I agree, localisation features such as adjusting to the local timezone are important. 

@GeeAlmeida, can you double-check the settings and investigate? Maybe it is worth looking into using EventBrite for the future?

**Comment by rivaquiroga** [comment]
Hi @GeeAlmeida! I made some additional images to promote the event, so we don't repeat the same one over and over on Twitter. I thought it would be a good idea to make the title/topic the biggest thing. And to have one image with more details about the event in case someone wants to share it via email, Slack, or another platform.  

![evento-ph-3](https://user-images.githubusercontent.com/31421616/199562820-838128e2-cf0d-4d39-ab77-4c26c281af46.png)

![evento-ph-1](https://user-images.githubusercontent.com/31421616/199567493-8b2f1926-8858-45d5-82aa-d4ce8d0fd60c.png)


![evento-ph-2](https://user-images.githubusercontent.com/31421616/199562830-6635febe-79bd-45fd-bdb9-f2367b45cd83.png)

**Comment by GeeAlmeida** [comment]
> ed to wait for Gisele to be able to confirm.

Hi eveyone
The cap on atendees was increased to 25 following comments here. The initial idea was to keep numbers and expectation low, as this is a first event... In my opinion, 7 tickets sold of 16 looks good... 7 tickets sold of 25 not as good. That was the thinking behind the low number in the first place.

**Comment by GeeAlmeida** [comment]
> Hi @GeeAlmeida! I made some additional images to promote the event, so we don't repeat the same one over and over on Twitter. I thought it would be a good idea to make the title/topic the biggest thing. And to have one image with more details about the event in case someone wants to share it via email, Slack, or another platform.
> 
> ![evento-ph-3](https://user-images.githubusercontent.com/31421616/199562820-838128e2-cf0d-4d39-ab77-4c26c281af46.png)
> 
> ![evento-ph-1](https://user-images.githubusercontent.com/31421616/199567493-8b2f1926-8858-45d5-82aa-d4ce8d0fd60c.png)
> 
> ![evento-ph-2](https://user-images.githubusercontent.com/31421616/199562830-6635febe-79bd-45fd-bdb9-f2367b45cd83.png)

Thank you Riva!

**Comment by GeeAlmeida** [comment]
> Maybe we can keep using Eventbrite, as in previous events. It is available in different languages, so it is easier for non-English speakers to register.

Hi Riva

I didn't know there was an Eventbrite account. Do you know the login details for it? Can you share them with me via email?

I was under the impression EventBrite charged for its services even if the events were free. A colleague told me that and I did not question. Looking for more information, I now see that they are free if the event is free. So, yes, that would be a better option. If you have the details do share. Or let me know if I should create a new account!

**Comment by acrymble** [comment]
@GeeAlmeida I don't think there was a PH account for eventbrite. I have used my own in the past when running a PH event, and I suspect others have done the same.

**Comment by rivaquiroga** [comment]
@GeeAlmeida, as Adam said, we have used our own accounts. Maybe we should create one for PH. 
Eventbrite does not charge you if the event is free. Only if you charge participants they ask for a fee.

What do you think about adding a link for people to check at what time the event is taking place in their time zone? Something like:
"Puedes revisar a qué hora se realizará el evento en tu hora local a través de este enlace: https://everytimezone.com/s/5019417d"

**Comment by GeeAlmeida** [comment]
Riva I am confused about the time. 15 hs UTC = 15 hs GMT (UK time)?
I checked when I set up the event and 15 hs UTC translated as 16 hs in London. That is the time in ticketsource. That is different from the link you shared.

I think the confusion comes from the fact that a couple of weeks ago the UK changed from British Summer Time to GMT.

I have amended the ticketsource page and will inform the people who have registered of the correct time when I email them the Zoom link closer to the date.

**Comment by rivaquiroga** [comment]
We agreed on 15:00 UTC. When we agreed on the time and date of the event (early October), 15:00 UTC was 16:00 UK time. But on the day the event is going to take place (mid-November) 15:00 UTC is 15:00 UK time because you are not in BST anymore. 
In ticketsourse the event says 4pm, but it does not mention the timezone. But the image says 15:00 UTC, so that is probably what people are taking into account.

**Comment by GeeAlmeida** [comment]
I've added the sentence and link you suggested to the event page, thanks Riva!

**Comment by rivaquiroga** [comment]
> I have amended the ticketsource page and will inform the people who have registered of the correct time when I email them the Zoom link closer to the date.

Thanks :two_hearts:

**Comment by GeeAlmeida** [comment]
OK, this event has now passed. Thank you @rivaquiroga for being a great interviewee!

Here is the link to the YouTube video of the event:

https://youtu.be/QgSuaHM5ap0
