### ISSUE TITLE
Board of Trustees Meeting: Thursday 17th November 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2702]
Board of Trustees Meeting: Thursday 17th November 2022 at [14:00 UTC](https://www.google.com/url?q=https://www.timeanddate.com/worldclock/converter.html?iso%3D20221117T140000%26p1%3D1440&sa=D&source=calendar&ust=1666014872912734&usg=AOvVaw3Sj9nFab_xJA5T2GyhZyRA)
--

Date: 17th November 2022 Thank you for replying to my calendar invitation 
Time: [14:00 UTC](https://www.google.com/url?q=https://www.timeanddate.com/worldclock/converter.html?iso%3D20221117T140000%26p1%3D1440&sa=D&source=calendar&ust=1666014872912734&usg=AOvVaw3Sj9nFab_xJA5T2GyhZyRA)
Zoom link: https://zoom.us/j/5959205456 **Passcode required** (see email)
Chair: @acrymble
Secretary: @anisa-hawes 
Members: @amsichani @drjwbaker @rivaquiroga @spapastamkou @ZoeLeBlanc
Minutes of the last meeting: [BoT-14-07-2022.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/07-2022/BoT-14-07-2022.md)
Business Plan (updated Nov. 2022): [ProgHist Business Plan 2022-11.docx](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/ProgHist%20Business%20Plan%202022-11.docx)

---

Hello all,

**I'm creating this issue so that we can begin to draft our agenda for November's BoT meeting.**
Please feel free to edit this agenda, and add further Items for discussion below

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf),  I'd like to ask that new agenda Items are added **in advance of the meeting** so that all attendees have sufficient time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions.  

### Agenda

- 1. Apologies 
- 2. Approval of [Minutes from last meeting](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/07-2022/BoT-14-07-2022.md) & actions status.
- 3. ProgHist Directors administration (e.g., changes of address)
- 4. Vote to agree @JMParr's appointment to the Board
- 5. Finance Update (@drjwbaker) > [paper](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/2022-11_ProgHist-Ltd_finance-update.docx)
- 6. Family Leave Policies (@drjwbaker @amsichani)
- 7. Technical Needs Survey (@acrymble)
- 8. New MEs for all publications (@acrymble)
- 9. Possibilities of collaboration between PH and [Ranke.2](https://ranke2.uni.lu/) (@spapastamkou) [working document](https://demo.hedgedoc.org/s/oCkKvV41V)
- Any Other Business

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by anisa-hawes** [comment]
Hello all,

Ahead of our next Board of Trustees Meeting on Thursday 17th November, I'd like to share the file on our Project and Business repo where relevant paperwork will be collated: [/charity/Board-of-Trustees-Meetings/2022/11-2022](https://github.com/programminghistorian/project-and-business-archive/tree/master/charity/Board-of-Trustees-Meetings/2022/11-2022)

Please take the time to review our Business Plan (updated Nov. 2022): [ProgHist Business Plan 2022-11.docx](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/ProgHist%20Business%20Plan%202022-11.docx)

Thank you,
Anisa

**Comment by drjwbaker** [comment]
Just to add, the updated Business Plan is excellent.

**Comment by drjwbaker** [comment]
Finance paper added.

**Comment by anisa-hawes** [comment]
Visual update on our IPP Programme added: [ProgrammingHistorian-IPP-Update-Nov-2022.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/ProgrammingHistorian-IPP-Update-Nov-2022.pdf) (with thanks to @GeeAlmeida)

**Comment by anisa-hawes** [comment]
Dear all,

The Minutes of yesterday's BoT Meeting are available for your review: [BoT-17-11-2022.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/BoT-17-11-2022.md).

Please let me know if you'd like me to make any amendments/additions.

A.

**Comment by drjwbaker** [comment]
Perfect.
