### ISSUE TITLE
Error in R Basics with Tabular Data

### ISSUE THREAD

**Issue by eiamjw** [programminghistorian/jekyll#2703]
[R Basics with Tabular Data](https://programminghistorian.org/en/lessons/r-basics-with-tabular-data)

There is an error in the text. Where it says "This would give you the total number of passengers (in hundreds of thousands) who flew in January and February of 1949." this should be "This would give you the total number of passengers (in thousands) who flew in January and February of 1949."

Further error, or confusing statement in the text:
"The data could be used to find out which of these features made each type of car more or less safe for drivers over time." It's not clear why this statement is here or what it might mean. There is no other mention of safety data in the exercise.

The section headed 'Matrices' starts with the following text:
"Now that you have a better understanding of how some of the basic functions in R work, we can look at ways of using those functions on our own data." It is not clear to me, coming to this lesson for the first time, what "our data" means. (It looks like this lesson has been taken out of another context where the Old Bailey data has already been introduced and loaded.) The following exercises require the use of the Old Bailey data, but this is not available to the student of the lesson.

**Comment by anisa-hawes** [comment]
Thank you @eiamjw. I'll re-read the lesson, and check if any adjustments or clarifications are needed.

**Comment by anisa-hawes** [comment]
Hello @eiamjw. 

Thank you for connecting with us and sharing your experience of the lesson.

The expression, _in hundreds of thousands_ sounds reasonably clear to me. If I understand correctly, 230 in hundreds of thousands = two hundred and thirty thousand or 230,000. Indeed, later in the lesson we encounter the figure 1520 (the total number of passengers in 1949) written as 1,520,000. 

In the Matrices section, the authors are giving an example of how a reader could use R functions on their own data (data that a reader of the lesson has collected themselves). 

To create the example variables Theft and ViolentTheft, the authors have simply keyed in the values from the columns headed Theft and Violent Theft from the table in the image. The first four values from those two columns of data (2,30,38,13) and (7,20,36,3) are used to demonstrate various R functions in this section.

The exercises that follow are examples of how you could use functions (`cbind()`, `rbind()`, etc.) if you had keyed in your own data, which could be anything.

![Screenshot 2022-11-03 at 16 28 42](https://user-images.githubusercontent.com/87070441/199779885-b139caf2-1698-4c0e-82ba-c4babec35627.png)

I'm not knowledgable about cars but I gather that data from a sequence of Car Road Tests could support researchers who are interested in whether cars with specific features were safer than others? Again, this data is just for readers to practice with.

![Screenshot 2022-11-03 at 17 00 32](https://user-images.githubusercontent.com/87070441/199786472-9c404ae9-1324-45e8-a038-0d9e855b9f46.png)

I don't think any updates are needed here.
