### ISSUE TITLE
Events for Library partners

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2706]
We'd like to start hosting some workshops or events aimed at Librarians who have responsibilities for research skills / DH related skills training in some way within their organisation. This includes those who are IPP members.

We would like to speak to a librarian or two about what types of events would add the most value for them and their community, so that we can tailor our programme, which @GeeAlmeida is putting together. If anyone is willing to speak with us or if you can recommend someone, please let us know.

**Comment by acrymble** [comment]
I've made a few inquiries to find someone who might be able to sit down for a chat.

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. It would definitely be good to bring Argula Rublack (librarian from Senate House Library who we spoke to at the IHR Centenary Festival) into this conversation.

**Comment by GeeAlmeida** [comment]
Good idea, Anisa! I've written to Argula!

**Comment by rivaquiroga** [comment]
@acrymble, @silviaegt is a DH librarian.

**Comment by acrymble** [comment]
We've got one meeting set up. And a couple of other people to chat with. Thanks everyone.
