### ISSUE TITLE
Issues with "Scalable Reading of Structured Data"

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2707]
While translating "Scalable Reading of Structured Data" we found some issues related to the plots shown in the lesson. 

## Figure 1
- The number of tweets is hardcoded in the plot with `caption = "Total number of tweets: 2.413"`. The problem is that the plot included in the lesson says the number of tweets is 2435. This mismatch could be potentially confusing for readers, especially because if we add the actual number of tweets from column "n" of the dataframe shown in the lesson, we get 2432 tweets.

- The code suggests changing the axis breaks with `scale_y_continuous(breaks = seq(0, 400, by = 50))`, but the plot included was not created using the code provided in the lesson (there are no ticks or values on axis "y"):

![figure1-o](https://user-images.githubusercontent.com/31421616/196296618-8cb82a5d-d714-4c50-a02e-0aeed837a12b.png)

 
This could be potentially confusing for readers. 
(Actually, we decided to remove that line of code in the Spanish translation because if the number of tweets that the reader gets is different, you can end with a plot with a "y" axis like this one:

![figure1](https://user-images.githubusercontent.com/31421616/196292393-ff552e54-d69e-401e-82ff-1759607a379a.png)

 
## Figure 2

The plot says the number of tweets is 2435, but in the output shown in previous lines, the total number of tweets is 2432.

## Figure 3

The description above the plot says: _The visualisation looks a lot like the previous bar charts, but the difference here is `facet_wrap`, which creates three bar charts for each type of interaction._ The problem is that the image only shows one bar plot for one type of interaction. In this case, it is not a mismatch between code and plot. The reason is that in the dataframe `interaction` (the one used for creating the plot), the column “interaction” only has one value (the string "favorite_count"). It was intentionally created that way. That is why `facet_wrap` only creates one plot. 
 
This is the code used in the lesson for creating `interactions`

``` 
interactions <- sesamestreet_data %>%
  group_by(verified) %>%
  summarise(mean = mean(favorite_count)) %>%
  mutate(interaction = "favorite_count")
```

And this is the content of that object:

``` 
  # A tibble: 2 × 3
  verified    mean interaction  
  <lgl>      <dbl> <chr>        
1 FALSE      0.892 favorite_count
2 TRUE     114     favorite_count
```
 
It is not clear to us what the three bar charts were supposed to be depicting. To have three different plots using `facet_wrap`, the variable called within that function should have three different values. But the column “interaction” was intentionally created containing the same value in all rows: `mutate(interaction = "favorite_count")`.
That section ([Interaction with verified versus non-verified account](https://programminghistorian.org/en/lessons/scalable-reading-of-structured-data#interaction-with-verified-versus-non-verified-accounts)) starts getting a little confusing from this line: _In this next step, you add the result of the calculation above to a dataframe. Use a new column headed “interaction” to specify that it is “favorite_count”_. The result of the calculation is already a dataframe. The next step (`mutate(interaction = "favorite_count")`) just adds a column to that same dataframe. Is there a step missing?

**Comment by drjwbaker** [comment]
Thanks for raising these issues @rivaquiroga. On Figures 1 & 2, I recall the captions and images went through a few iterations, so they may have fallen out of step at some point. Is the solution here for us to make new figures (and captions) that match the code?

On Figure 3, I think we'd need to go back to the authors. Are you happy for me to tag the authors to look into this?

**Comment by drjwbaker** [comment]
(fyi, I'm aware that Anisa is on holiday, so I'm not tagging here in case she get a notification and feels duty bound the respond!)

**Comment by spapastamkou** [comment]
integrating here [the issue of review of of the FR translation](https://github.com/programminghistorian/ph-submissions/issues/482) - might need to exchange between us

**Comment by rivaquiroga** [comment]
@drjwbaker, yes, for figures 1 and 2, the solution is to update the images, so they match the data and the code. We recreated them to be able to translate titles and legends; I am attaching the updated versions here.
In the case of figure 3, I agree that the best option is to bring the authors.


![scalable-reading-of-structured-data-1](https://user-images.githubusercontent.com/31421616/196791788-1b46a58c-9238-4b8a-a949-d0e153425598.png)
![scalable-reading-of-structured-data-2](https://user-images.githubusercontent.com/31421616/196791791-083440f7-88c8-4f15-9687-e914e10dbf48.png)

**Comment by drjwbaker** [comment]
On the figures, thanks @rivaquiroga .

@maxodsbjerg During translation one of our editors has picked up an issue with this article that I think you are best placed to resolve. Could I ask that you take a look at this please, then we can create a timetable for resolving the apparent issue. See https://github.com/programminghistorian/jekyll/issues/2707#issue-1412322494 above, specifically: 

> ## Figure 3
> 
> The description above the plot says: _The visualisation looks a lot like the previous bar charts, but the difference here is `facet_wrap`, which creates three bar charts for each type of interaction._ The problem is that the image only shows one bar plot for one type of interaction. In this case, it is not a mismatch between code and plot. The reason is that in the dataframe `interaction` (the one used for creating the plot), the column “interaction” only has one value (the string "favorite_count"). It was intentionally created that way. That is why `facet_wrap` only creates one plot.
> 
> This is the code used in the lesson for creating `interactions`
> 
> ```
> interactions <- sesamestreet_data %>%
>   group_by(verified) %>%
>   summarise(mean = mean(favorite_count)) %>%
>   mutate(interaction = "favorite_count")
> ```
> 
> And this is the content of that object:
> 
> ```
>   # A tibble: 2 × 3
>   verified    mean interaction  
>   <lgl>      <dbl> <chr>        
> 1 FALSE      0.892 favorite_count
> 2 TRUE     114     favorite_count
> ```
> 
> It is not clear to us what the three bar charts were supposed to be depicting. To have three different plots using `facet_wrap`, the variable called within that function should have three different values. But the column “interaction” was intentionally created containing the same value in all rows: `mutate(interaction = "favorite_count")`. That section ([Interaction with verified versus non-verified account](https://programminghistorian.org/en/lessons/scalable-reading-of-structured-data#interaction-with-verified-versus-non-verified-accounts)) starts getting a little confusing from this line: _In this next step, you add the result of the calculation above to a dataframe. Use a new column headed “interaction” to specify that it is “favorite_count”_. The result of the calculation is already a dataframe. The next step (`mutate(interaction = "favorite_count")`) just adds a column to that same dataframe. Is there a step missing?

**Comment by anisa-hawes** [comment]
Thank you for reporting this Issue, @rivaquiroga ! 

I see the two new figure images [you have created here](https://github.com/programminghistorian/jekyll/issues/2707#issuecomment-1284509668) but I notice that strangely some of the lowercase letter 'i's are displayed as uppercase 'I' and this makes the titles and labels difficult to read.

Perhaps @maxodsbjerg and @VictorHarbo could help us by recreating the images? 

Also, to note the labels in Figure 1 are Dec (with capital D) in EN, while they are 'dic' in ES (with lowercase d).

When we have the new images, I can slot them into the lesson.

**Comment by VictorHarbo** [comment]
Hi @anisa-hawes 

I will try to recreate the images either later this evening or hopefully tomorrow!

**Comment by anisa-hawes** [comment]
Hello @VictorHarbo 👋🏻  

Thank you! Whenever you have time, there isn't a rush to complete this today – I know how busy you and your team are.

It was wonderful to meet you in Århus last week!

**Comment by VictorHarbo** [comment]
So, I looked at this this afternoon. Indeed there is some code and even text missing about figure 3, well spotted @rivaquiroga 

I have found the missing text, can I fork the lesson from the ph-submission repo and create a pull-request with the update directly @anisa-hawes ?

Furthermore I have created three new versions of the figures. Where and how do you want them?

**Comment by anisa-hawes** [comment]
Thank you so much, @VictorHarbo! Speedy work!

You can do it that way, but simpler would be to email me the changes (to admin [@] programminghistorian.org)  / or share the updated files on your repo? Then I can slot them in.

**Comment by VictorHarbo** [comment]
Hi again @anisa-hawes 

The text and images are here: https://github.com/maxodsbjerg/ScalableReadingOfStructuredData 
The images are prefixed with 20221027 and the text file itself is prefixed with 20221028.

**Comment by anisa-hawes** [comment]
Hello @VictorHarbo. I've just been taking a look at the files on your repo. – thank you for preparing these. 

Comparing the two text files, I notice that your updates haven't been applied to the latest version of the .md. (My hesitation to suggest that you fork our repo was that due to such frequent updates on our site, other users' forks almost always end up behind commits on our master branch. )

It seems like there are still a couple of very small issues to resolve with the images too. 

- [x] Figure 1 : ideally for EN, the subtitle here would be _Period: 4 December 2021 - 13 December 2021_ with uppercase Ds
- [x] Figure 3 : I notice that _Period:_ is duplicated in the subtitle here. 

I've [created a branch called Issue-2707-edits](https://github.com/programminghistorian/jekyll/tree/Issue-2707-edits) where I can stage the changes. The lesson .md file which we want to apply your edits + missing text to [is here on that branch](https://github.com/programminghistorian/jekyll/blob/Issue-2707-edits/en/lessons/scalable-reading-of-structured-data.md). 

Shall we connect by email to work together? You can reach me here: admin [@] programminghistorian.org.

**Comment by anisa-hawes** [comment]
In the process of preparing the updates to this lesson, I have been thinking again about a suggestion I made during the copyediting process. I expressed my preference to remove the hardcoded captions from within the images. This is for several reasons, including an important one: that makes it more difficult for me to make changes in the future if I need to. At the time, Tiago said his preference was to "keep the captions and titles in the figure itself if nothing else because it is always a helpful reminder of how to do it" and I do understand this.

> Q Throughout the lesson, I'd like to suggest we reconsider the Caption for your figures, which effectively repeat the caption/title as given within the screenshot image. I'd be interested to hear Tiago's thoughts on this, but I'm wondering if the caption/titles given within the screenshot images can be removed? So that the image/caption format is more consistent with our existing lessons. I would also like to advise that we add in alt text so that the bar graphs are accessible to screen reader users. The syntax to use is: {% include figure.html filename="file-name.png" alt="Visual description of figure image" caption="Caption text to display" %}

Tiago's thoughts: "I think this is a fair point -- personally, I'd keep the captions and titles in the figure itself if nothing else because it is always a helpful reminder of how to do it in the code (I know I'm constantly trying to figure out how to add these kinds of labels). What I'd suggest is that the alt field is used to include the same content as the figure itself, for accessibility, while the caption would have a more descriptive tone

Chatting with @rivaquiroga on Slack this morning, she agrees that it makes good sense to remove the hard-coded captions, so that we are in a stronger sustainability position. We have clear captions and we have alt-text too.

I've emailed @VictorHarbo today with a question re: a further update to replacement Figure 1, but I'm wondering if in fact we take this opportunity to replace all three figures.

Riva has the plots, so we could collaborate to slot them in. 

What do you think @hawc2?

- [x] I've received the updated figure and have uploaded this [to the branch I'm working on](https://github.com/programminghistorian/jekyll/tree/Issue-2707-edits).

**Comment by anisa-hawes** [comment]
Hello @hawc2,

I hope you're well?

I've been working with the authors and have prepared the updates requested above in PR #2731.

I wonder what your thoughts are on removing the hard-coded captions that are included in this lesson's images? [As explained above](https://github.com/programminghistorian/jekyll/issues/2707#issuecomment-1302121103), this is something Tiago and I discussed during copyediting, and something Riva and I have spoken about again in the course of resolving this Issue. My sense is that future updates to this lesson would be much simpler if the captions were not hard-coded. It would also make these images/captions more consistent with our other lessons.

Let me know what you think?

Everything is ready to go, if you are happy with things as they are.

**Comment by hawc2** [comment]
@anisa-hawes makes sense to me to avoid hard-coding the title into the plot, in keeing with our normal editorial standards and workflows. If there's anything important to this particular lesson that this practice strays from, it seems better to offer a brief disclaimer explaining why, although I doubt any reader would notice

**Comment by anisa-hawes** [comment]
Thank you, @hawc2. I've made [the following adjustments in the branch](https://github.com/programminghistorian/jekyll/pull/2731/files) I'm preparing:

- [x] Removed `title =` and `subtitle =` where they are hard-coded within `labs()` 
- [x] Revised l.179 to explain how titles and subtitles can be hard-coded alongside other descriptive text if a reader wants to add them
- [x] Added the Figure numbers into our captions (consistent with other lessons)

Next step:

- [x] Email the authors to ask for three replacement figures (minus titles)
- [x] Authors are also double-checking that the captions specify the correct number of Tweets at each stage of the lesson, just to make sure that the mis-matches @rivaquiroga  identified have all been resolved  🙂 I am looking over the Preview, and I am still a little confused... Q: Should l.168 and 171 also read that the total number of tweets is **2432**? At the moment, they say **2413**  **YES** Now corrected > https://github.com/programminghistorian/jekyll/pull/2731/files
