### ISSUE TITLE
PH calendar of events - December 

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2709]
Hi everyone @programminghistorian/project-team 

Our second PH event is in the works. It will be in English, and will be an interview with lecturers who use PH with their students. The date is to be announced.

I will update this ticket as the details are finalised.

Title: Teaching with Programming Historian
Theme: using PH tutorials with students
Format: roundtable discussion with Joana Vieira Paulino, Nicolas Vaughan and Jessica Parr
Language: English
Date: Friday, December 16th 
Time: 14-15:30 UTC - [click here](https://everytimezone.com/s/64174c0b) to check the time where you are
Zoom info: to be shared with participants ✨

**Comment by drjwbaker** [comment]
Just to check, are these meetings protected in some way (e.g. password). I wouldn't want posting public links to lead to us getting zoom-bombed (it does happen, sadly!)

**Comment by GeeAlmeida** [comment]
> Just to check, are these meetings protected in some way (e.g. password). I wouldn't want posting public links to lead to us getting zoom-bombed (it does happen, sadly!)

I don't think they are password protected. I have deleted the link. Thanks!

**Comment by drjwbaker** [comment]
Okay. I may be being over cautious!

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. I've adjusted the Zoom settings so that participants will need a Passcode to join our Meeting Room. 

- [x] I'll share this with you now  
- [x] (and I'll update the Service Integrations notes too)

I use the Waiting Room feature already, so new participants don't join our meetings automatically. You can see who they are, and admit them individually.

**Comment by GeeAlmeida** [comment]
Date to be confirmed, but likely to be December 16th

**Comment by GeeAlmeida** [comment]
For December our guests are:
Joana Vieira Paulino
Nicolas Vaughan
Jessica Parr

More details to follow soon!

**Comment by GeeAlmeida** [comment]
I have emailed Joana, Nicolas and Jessica to finalise the booking.

**Comment by GeeAlmeida** [comment]
There is a possibility that Adéla Sobotkova might join the roundtable. She is Associate Professor of History and Classical Studies at Aarhus University, and although she doesn't use PH in the classroom, she very often signposts her students to PH. Semmed like a good addition to the discussion. She is checking if free on the 16th and wil let me know.

**Comment by GeeAlmeida** [comment]
The Eventbrite link for this event is:
https://tinyurl.com/ph-16-12

**Comment by GeeAlmeida** [comment]
![Image 1](https://user-images.githubusercontent.com/109232661/202760563-ec124110-7c13-4c85-8bf2-dfd975d9797d.png)

**Comment by GeeAlmeida** [comment]
@programminghistorian/english-team 

Our second event will be in English. Please share it with your wider networks and contacts if you can!

**Comment by acrymble** [comment]
@GeeAlmeida who is the target audience?

**Comment by GeeAlmeida** [comment]
Lecturers looking to use PH in their teaching.

**Comment by GeeAlmeida** [comment]
Just an update to let you all know that we already have 26 bookings for this event. Yay!

**Comment by GeeAlmeida** [comment]
There's been amazing demand for this event - we are now at capacity, with 100 people registered to attend. 
I have increased capacity to 120, counting on 20% not turning up on the day.
There is now also a waiting list for this event.

**Comment by GeeAlmeida** [comment]
Here is the video for the event:
https://youtu.be/u5x5WlLD-Bo
