### ISSUE TITLE
Gwenaëlle Patat stepping down from the FR team

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2712]
@InesSalome  is stepping down for the FR team. Here is a list of what we have to do at the team level: 

- [x] Remove Google Groups access (@anisa-hawes)
- [x] Remove Google Analytics access (@acrymble) (Note of Sofia: is this applicable here?)
- [ ] ~~Remove Github Jekyll access (@ZoeLeBlanc)~~
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Remove Twitter access (@anisa-hawes)
- [x] Change team: true to team: false, and add team_end: YYYY to the  _data/ph_authors.yml file to remove the person from the Project Team page (@anisa-hawes) OR @spapastamkou 
- [x] Open issues assigned to GP: [translation editing on ph-submissions](https://github.com/programminghistorian/ph-submissions/issues/449) -  @spapastamkou (Note of Sofia: I will close this issue - I need to add a report for the current state of the lesson which is ready but not in bcz of more pressing tasks currently)
- [x] Review service integrations page to ensure that they do not have any associated integrations tied to their accounts (@anisa-hawes).

**Comment by spapastamkou** [comment]
Thank you for your service @InesSalome and good luck to your new job!

**Comment by InesSalome** [comment]
Thank you for having included me in the team @spapastamkou, it was a great experience to work with you and I wish all of you the best in the future !

**Comment by anisa-hawes** [comment]
Dear @InesSalome,

I have removed you from our Google Groups, and I have checked that you do not have Twitter access.
I can also confirm that you do not have any Service Integrations linked to your accounts.

Merci pour votre contribution et bonne chance pour vos prochains projets ! ✨ 

-- 

Dear @spapastamkou,

I've prepared a PR #2715 to remove Gwenaëlle from the Project Team page. I'll request your review when it's ready.

Very best,
Anisa

**Comment by spapastamkou** [comment]
Thanks @anisa-hawes, I merged the PR. 
Given #2688, I tick @drjwbaker task. Wait for @ZoeLeBlanc to remove access to GitHub and will close this issue.

**Comment by acrymble** [comment]
@spapastamkou I've had a look and I don't think she has Jekyll access on this site. Some of our newer members may not have needed it, so I think you can close this now.

**Comment by spapastamkou** [comment]
Thank you @acrymble and @anisa-hawes. Please not however that I still find InesSalome (which is GP's username) among the members I can assign tickets to on jekyll and on ph-submissions.

**Comment by acrymble** [comment]
You're right @spapastamkou she was on something called 'French Team' which I suspect got set up and maybe never used. I've removed her now.

**Comment by spapastamkou** [comment]
Thanks a lot, Adam! We use sometimes this collective alias to get the attention of the members without individually pinging them.
