### ISSUE TITLE
Give the reader the possibility to choose multiple topics or/and activities

### ISSUE THREAD

**Issue by matgille** [programminghistorian/jekyll#2714]
Hi, 

Sometimes there are several topics/activities in a lesson, but as I understand it, only the first one is used to filter the lessons. 

Would it help to allow the user to select multiple topics and activities ? 

I don't know if it's feasible, it's just an idea !

Best, 

Matthias

**Comment by anisa-hawes** [comment]
Hello @matgille. My understanding is that only one `activity` can be applied, but Authors may choose multiple `topics` if they wish. In the YAML, it might appear like this:

```
activity: analyzing  
topics: [python, data-manipulation]
```

or 

```
activity: transforming  
topics: [data-manipulation, data-management, distant-reading, r]
```

My experience is as you describe, that only one of these filters can applied productively to our Lessons Index. Users have the option to refine the Index by either activity _or_ topic, and then may choose to sort/order their results by date of publication or difficulty level. But they can't choose to filter twice, e.g., find lessons related to the activity `analyzing`, then find which _of those_ relate to the topic `R`. 

I agree that the opportunity to apply multiple filters could support readers to find lessons that meet their learning objectives. 

I'll add this to [a list I'm building of Issues that raise ideas](https://github.com/orgs/programminghistorian/projects/2/views/1) for enhancements to improve users' experience of our website and its contents. 

Thank you for this suggestion ✨

**Comment by matgille** [comment]
Hi @anisa-hawes, 

Thank you for your answer. I should have read better the editor guidelines !


Best, 


Matthias
