### ISSUE TITLE
Suggestion from a reader: community forum for peer-peer support

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2721]
We received a suggestion from a reader via Twitter today.

[The Tweet is here](https://twitter.com/EthanWatrall/status/1585698029478113280), and read: "_I'm surprised that @ProgHist doesn't have a community forum for peer to peer or author to learner  support on their tutorials....or am I missing something?_"

I wrote a brief reply to thank them for the suggestion and said that we could share this idea with our team. Feels like something very much within @GeeAlmeida's remit as community lead so I will assign her here!

What do the @programminghistorian/project-team think about this?

**Comment by anisa-hawes** [comment]
I see that @acrymble has contributed to say that we used to host a peer-to-peer forum when our site ran on Wordpress. But that this wasn't any longer possible with our new infrastructure.

I'll add this to [a list I'm building of Issues that raise ideas](https://github.com/orgs/programminghistorian/projects/2/views/1) for enhancements to improve users' experience of our website and its contents.

**Comment by rivaquiroga** [comment]
Hi! I think this is a great idea.
We do need to take into account that forums must be moderated. And someone has to do that job.

**Comment by ZoeLeBlanc** [comment]
Agree with the points raised about needing to think about time to moderate and who will enforce standards. One option on the infrastructure side is simply enabling discussions on this or the ph-submissions repo https://docs.github.com/en/discussions . Discussions are essentially forums and this blog post gives a nice overview of some of the features https://github.blog/2022-01-13-how-five-open-source-communities-are-using-github-discussions/. The benefit of using Github is that at least technically it wouldn't add overhead infrastructure and would make it easy for us to turn issues in the forum, into issues on the repo (and maybe vice versa).

Overall though like this idea and think it could be useful for us, especially as Twitter increasingly degrades and no longer gives us a space for more informal conversations.

**Comment by hawc2** [comment]
@ZoeLeBlanc that's a cool feature! I agree we should first try out options available within Github infrastructure before coding something into the website or using third-party platforms. 

The peer to peer and author to learner discussion board set up could increase engagement in some interesting ways, although it might present new challenges around moderation. Maybe it could also serve as a space for bug reports or feature requests which are currently sent through email or posted on github tickets. It would be great if we could foster a broader community (beyond our editorial team) invested in maintaining lessons too

**Comment by acrymble** [comment]
Can we park any actual development until we've had time to come up with a holistic approach to a publishing ecosystem that may or may not need this type of feature, rather than what we've had historically, which is adding things on to our existing infrastructure.

We're going to discuss this at our next board meeting #2702

**Comment by anisa-hawes** [comment]
Yesterday, an author sent me a correction for a lesson using a web annotation tool called Hypothesis [https://web.hypothes.is/](https://web.hypothes.is/) which I think looks super ✨ (screenshot below). 

A thought: perhaps something worth investigating as we begin to think about how a community forum for peer-peer support could work? An annotation tool like this one could prove helpful for pointing to specific elements of code. 

![Screenshot 2022-11-16 at 19 36 28](https://user-images.githubusercontent.com/87070441/202437576-bdffb8ef-ed34-4ff1-8a1c-35bfdd506ea4.png)

**Comment by acrymble** [comment]
There are a number of historic threads about that tool. https://github.com/programminghistorian/jekyll/issues?q=is%3Aissue+is%3Aclosed+hypothesis

**Comment by GeeAlmeida** [comment]
I've included this suggestion in https://github.com/orgs/programminghistorian/projects/2/views/1 and will now close this issue.

**Comment by anisa-hawes** [comment]
Hello @GeeAlmeida. I'd already added this to [the enhancements // user needs Project Board](https://github.com/orgs/programminghistorian/projects/2/views/1) 🙃. In this case, I wonder if it is worth keeping the Issue open to invite a little more discussion from the @programminghistorian/project-team? Which peer-to-peer forums do they contribute to elsewhere? Which ones work well (and why)? 

Maybe this idea of a PH peer-to-peer learning space is something that you'll be able to gauge interest in when you are speaking with participants at forthcoming events?

I think what Zoe and Alex are suggesting (above) is that we could use [GitHub discussions](https://docs.github.com/en/discussions) for this purpose, which wouldn't involve developing any new infrastructure. 

The discussion we need to have as a team is whether we would want to create a forum like this (there are already some positive responses!) and, if so, how we would manage and moderate it.

Perhaps those things are worth brainstorming here in the issue?

**Comment by GeeAlmeida** [comment]
OK, I've reopened the issue.
