### ISSUE TITLE
Editing https://programminghistorian.org/en/ipp

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2727]
The Institutional Partnership page needs to include the following sentence:
Gold partners are offered two exclusive bespoke workshops per year for their students and researchers on how to get started using digital humanities tools.

**Comment by acrymble** [comment]
@GeeAlmeida I don't remember this. Was this advertised somewhere?

**Comment by drjwbaker** [comment]
@acrymble Context. @GeeAlmeida suggested this as part of the IPP renewal email. I suggested it would be fine if Gisele believed that/we had capacity to deliver. I also suggested we'd need to update https://programminghistorian.org/en/ipp to reflect this change, were we to go ahead with it.

On reflection, and thinking back to our articles of association it occurs to me that membership rates and terms are really things that the Trustees should approve (or, formally approve that we delegate that responsibility to our community lead). My apologies for not flagging this sooner.

**Comment by acrymble** [comment]
@drjwbaker thanks. Can I ask you to liaise with @GeeAlmeida to put together some notes for us all on how this will be managed? I'm just thinking aloud, but what if someone wants a workshop in Chinese or French? Or if they think this is going to be in-person, or multi-day, or they want to roll it over to another year (etc, etc). We need to make sure we manage expectations because this is a contractual obligation of ours.

**Comment by anisa-hawes** [comment]
Would you like me to reverse the change made to the website in PR #2728 @acrymble? I'm happy to do this, and we can implement the new wording after a fuller discussion.

I've halted the Tweet for now too, so that we aren't sharing a link to a page of information that may be about to change.

**Comment by acrymble** [comment]
@anisa-hawes as long as @drjwbaker and @GeeAlmeida have a plan for how this will work then it's not a problem. I just hadn't heard about it.

**Comment by drjwbaker** [comment]
I have written to @GeeAlmeida
