### ISSUE TITLE
Update /es/pia, /fr/pi and /pt/ppi

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2729]
I am opening this Issue to follow PR #2728.

We are updating our /es/pia, /fr/pi and /pt/ppi pages to clarify that:

EN: _Gold Tier partners are offered two bespoke workshops per year to help their communities use digital humanities tools and methods._

ES: Se ofrecen dos talleres personalizados al año a las instituciones asociadas en Gold Tier para ayudar a sus comunidades a utilizar herramientas y métodos de humanidades digitales. 

FR: Les partenaires de niveau _Gold Tier_ ont droit à deux ateliers sur mesure par an afin de permettre à leurs communautés de bénéficier de l'apprentissage de méthodes et d'outis numériques.

PT: As instituições parceiras de nível ouro tem dois workshops personalizados por ano para ajudar suas comunidades a usar ferramentas e métodos de humanidades digitais.

I would be grateful if someone from the @programminghistorian/french-team, @programminghistorian/spanish-team and @programminghistorian/portuguese-team could help me with the translations of this sentence!

**Comment by anisa-hawes** [comment]
Gisele has created a digital graphic to celebrate our first Gold Tier partnership, and I'd like us to translate the text within the graphic so that we can share it across our language communities.

I've drafted the following, but let me know if corrections/adjustments are needed! Very likely! 🙂 

EN ::  PH is proud to announce that Digital Scholar is a Gold Tier supporter
ES :: PH se enorgullece de anunciar que Digital Scholar es un colaborador en nivel Gold
FR :: PH a la joie d'annoncer que Digital Scholar est maintenant un de nos soutiens de niveau Gold
PT :: PH orgulha-se de anunciar que Digital Scholar é um apoiante do nível de Ouro

**Comment by acrymble** [comment]
@anisa-hawes can you point me to where we had decided this bespoke workshop offering? I can't remember seeing it.

**Comment by anisa-hawes** [comment]
Thank you for following up, @acrymble. My understanding is that this is something @GeeAlmeida and @drjwbaker have agreed in their dialogue about IPPs.

**Comment by GeeAlmeida** [comment]
I'll make this update on Friday!

**Comment by GeeAlmeida** [comment]
> partenaires de niveau _Gold Tier_

Anisa do you want me to produce different versions of the image, one per language? Let me know what you have in mind for this!

**Comment by GeeAlmeida** [comment]
@anisa-hawes The image in the Spanish page (PIA) is not showing correctly. This is not something I know how to fix at the moment. The same happens in French.

**Comment by anisa-hawes** [comment]
Which image, @GeeAlmeida?  /es/pia looks good to me in the Netlify Preview:

 
![Screenshot 2022-11-11 at 15 12 35](https://user-images.githubusercontent.com/87070441/201369028-8bea02c4-4178-4cf8-a12e-1ef36a03f9df.png)

**Comment by GeeAlmeida** [comment]
That was the image I thought had issues. All good then!

**Comment by anisa-hawes** [comment]
> > partenaires de niveau _Gold Tier_
> 
> Anisa do you want me to produce different versions of the image, one per language? Let me know what you have in mind for this!

I thought it would be nice to promote Gold Tier in multiple languages! And also to have a graphic ready to go, incase a new Gold Tier partner joins us whose native language is ES, FR or PT 🙂

**Comment by drjwbaker** [comment]
@GeeAlmeida Before we make this live, do please send through (as elaborated via email) your thoughts on how we resource the gold tier, ideally in time for the Trustees to discuss it next Thursday https://github.com/programminghistorian/jekyll/issues/2702

**Comment by anisa-hawes** [comment]
Closed by #2745.
