### ISSUE TITLE
Show last modified date on lessons

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#273]
See if this can be automatically generated without a plug-in.

**Comment by wcaleb** [comment]
I've looked into this a little bit, and I'm not sure it will work for us. There is a Jekyll plug-in that provides "last modified" time, but it will only work when the site is compiled locally on a machine and then pushed to GitHub (in plain speak, that means that when edits are made on GitHub website itself, as a large number of our edits are ... and that's not even considering the problems that could arise from our manually generating the site instead of relying on GitHub Pages's automatic generation).

I'm also not sure anymore how essential this is. The link to "previous versions" in the footer of every page takes a viewer directly to a list of all previous commits, with the most recent one clearly dated at the top. If we want, we could make that link more prominent (by putting it at top rather than in footer, for example), but since we have it there, I'm not sure how much we want to reinvent the wheel just to have the date printed on the page. Willing to be persuaded otherwise, though, if someone sees an easier way.

**Comment by wcaleb** [comment]
Discuss at #291?

**Comment by wcaleb** [comment]
I can look into using the GitHub API to get the last modified date, perhaps with a Javascript.

**Comment by acrymble** [comment]
I know this is a bit old, but I do still think this would be a useful feature. I don't have any technical solutions though.

**Comment by wcaleb** [comment]
@fredgibbs Are you working on this as part of site redesign? If not, I have a little bit of time to work on it this week, but didn't want to duplicate efforts.

**Comment by fredgibbs** [comment]
@wcaleb yes! it's pretty straightforward through the GitHub API, and I have it working on my dev copy.

**Comment by fredgibbs** [comment]
fixed in new design work.
