### ISSUE TITLE
Update needed: `buildNode.js 12 actions are deprecated`

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2730]
After merging a PR yesterday, I noted [an alert message](https://github.com/programminghistorian/jekyll/actions/runs/3379954391) alongside the build check (which had passed successfully).

The alert read:

---

**Annotations**
1 warning
[build](https://github.com/programminghistorian/jekyll/actions/runs/3379954391/jobs/5612172068)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout

---

Do you have capacity to review this, @ZoeLeBlanc? I would be grateful for your advice about how best to proceed.

I read [these notes](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-nodejs-v16) to try and understand. I couldn't find `runs.using:` in our `build.yml`, although I did note `runs-on: ubuntu-latest`. Maybe I'm looking in the wrong place...

**Comment by acrymble** [comment]
Do we know what we use node.js for? Is it crucial?

**Comment by ZoeLeBlanc** [comment]
Thanks for catching this @anisa-hawes! I just pushed up a PR to fix it https://github.com/programminghistorian/jekyll/pull/2735 . Literally just involves updating one of the actions we call in the build.yml file, so not a big issue at all.

**Comment by anisa-hawes** [comment]
Thank you, @ZoeLeBlanc! This is much appreciated! 

I noted that PR #2733 stalled its build checks last Friday, so I'll rebase that when this is merged in 🙂

**Comment by anisa-hawes** [comment]
This Issue is closed by PR #2735.

**Comment by anisa-hawes** [comment]
This seems to be causing a problem again... 

Following [a recent merge](https://github.com/programminghistorian/jekyll/actions/runs/3603453490) (where all checks had passed successfully) I noted the following build errors:

build
`API rate limit exceeded for user ID 8355129.`

build
`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: peter-evans/repository-dispatch@v1`


After a re-running the job, my merge has been passed with a green tick ! But maybe something for us to keep an eye on.
