### ISSUE TITLE
Use of Twitter for communication

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2734]
All - due to the changes currently in progress as a result of Elon Musk being the new boss of Twitter, maybe we should prepare to examine possible alternatives for the future. I do not say that this should be done tomorrow, as we should probably wait and see what the changes will really be and how/if they have impact on the PH communications strategies and outreach to our audience. But there is no harm to think about alternative or complementary actions (create a Mastodon account, other...). 

Also, it would not harm to download and archive our account's Twitter data - but perhaps this is already part of the existing archiving activities?

**Comment by rivaquiroga** [comment]
I agree with Sofia. Exploring new platforms as a complementary outreach strategy is a good idea. Not only because part of our current audience might move to other places like Mastodon but mainly because there are potential readers that are not Twitter users. Maybe having an Instagram or a LinkedIn profile could help us reach new audiences.

**Comment by drjwbaker** [comment]
Just noting that if we do decide to go down a mailing list route as part of a comms rethink, as we are registered in a territory that observes GDPR https://gdpr-info.eu/ there are strict rules over how we look after that data, and that will take time/effort to do correctly/legally.

**Comment by GeeAlmeida** [comment]
Hey Sofia @spapastamkou 
What do you mean with downloading and archiving our account's Twitter data? This is not something I have done so far. I don't think this has been done yet.

**Comment by spapastamkou** [comment]
@GeeAlmeida Once connected to the Twitter account, use https://twitter.com/settings/account and then select `Download an archive of your data` . It may take some time but eventually the files arrive, if I remember correctly in form of sheets. Perhaps James has idea about archiving them? I would suggest to upload the downloaded folders on our repo on GitHub (see with Anisa/Adam in which repo?) and we could also prepare a file with the IDs of the tweets to deposit on Zenodo (to be compliant with current data policy of Twitter). If we agree on the latter option, I can help to prepare and deposit the file.   

![twitter-archive-data](https://user-images.githubusercontent.com/27706167/201054272-242790e0-8736-4a8a-b457-0d9738c46153.png)

**Comment by GeeAlmeida** [comment]
@drjwbaker You might be the best person to do what Sofia is suggests (download ProgHist's data from Twitter), as when I tried to do it Twitter sent a verification code to the gmail, and these codes tend to expire quite quickly!

**Comment by drjwbaker** [comment]
Okay @GeeAlmeida. I'll can do it. Can you please send me the password?

**Comment by rivaquiroga** [comment]
People [started asking](https://twitter.com/infovestigacion/status/1592912473732288513?) if we are on Mastodon :eyes:

**Comment by rivaquiroga** [comment]
Considering yesterday's events at Twitter headquarters it might be a good idea to create a Mastodon account in the next few days, right? Maybe nothing happens. Maybe the platform collapses. Who knows. 
fedihum.org could be a good instance to choose.
Quinn Dombrowski started a list of DH accounts on Mastodon. Once created, we can add ours there using this form: https://forms.gle/fDLWhuvsv82LEeKq8

**Comment by spapastamkou** [comment]
Just in case, there is also the [instance of Humanities Commons](https://team.hcommons.org/2022/11/07/humanities-commons-launches-mastodon-server-open-to-scholars/) - should be accessible soon.

**Comment by GeeAlmeida** [comment]
Brazilians seem to be heading in large numbers to [Koo](https://www.kooapp.com/). I don't know if this is happening in other countries.

**Comment by GeeAlmeida** [comment]
Hey everyone
I looked into setting up a Mastodon account. It is currently not possible to register using the main server [mastodon.social] so I investigated the HC that Sofia mentioned [hcommons.social]: 
<img width="344" alt="image" src="https://user-images.githubusercontent.com/109232661/203962719-0bbcb966-df1e-44b6-af04-474a6b7d6231.png">

Does it matter to us that HC has very few users? Should I go ahead and register using their server? If not this, then what?

**Comment by GeeAlmeida** [comment]
Just to update that I have created a Mastodon account. It is pending verification, but should soon be online!

**Comment by GeeAlmeida** [comment]
Mastodon allows users to have a verified account, like Twitter's blue tick. Here is how they explain how to do it:
"You can verify yourself as the owner of the links in your profile metadata. For that, the linked website must contain a link back to your hcommons.social profile. The link back must have a rel="me" attribute. The text content of the link does not matter. Here is an example:

`<a rel="me" href="https://hcommons.social/@proghist">Mastodon</a>`

Can we do this for PH? Where on the website? A blog post??

**Comment by GeeAlmeida** [comment]
@programminghistorian/project-team 

I just want to let you all know that we now have a Mastodon account:
[@proghist@hcommons.social](https://hcommons.social/@proghist)

If you are on Mastodon, please connect. I have followed all of the team members I found on Mastodon. :)

**Comment by GeeAlmeida** [comment]
@ZoeLeBlanc in light of tomorrow's meeting, I want to flesh out the developments and issues as I see them:
- we now have a Mastodon account as well as a Twitter. The two are integrated through something called ["Moa Party"](https://moaparty.com) whatever is published in one is replicated in the other platform. This seems to be working fine.
- I like the fact that the bot publishes links to published materials on our website. These rarely get interactions, but keep our profile populated and hopefully interesting
- What I don't like is that I cannot control the bot / don't know when the bot will tweet

**Comment by jenniferisasi** [comment]
Hi @GeeAlmeida! Adding a note to your last bullet point, as we know for sure (cos we tell it to do so) when the bot will tweet on a regular schedule:

- Monday - 9AM PST, 12PM EST, 4PM London time
- Thursday 6:30 AM PST, 9:30 AM EST, 1:30PM London

All this information can be found on our repo [proghistbot](https://github.com/programminghistorian/proghistbot) which I realize we might have not share with you accordingly, and I apologize for that. @anisa-hawes we should add a note about the repo on the Jekyll repo Wiki, right?

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. Sofia also [shared this link](https://github.com/programminghistorian/jekyll/issues/2691#issuecomment-1263634464) in the related thread #2691.  
I can add it to the Wiki now, and @GeeAlmeida can update as necessary when decisions about changes have been made 🙂 

- [x] Add the ProgHistBot repo link to our Wiki <https://github.com/programminghistorian/jekyll/wiki/Twitter-Bot>

**Comment by GeeAlmeida** [comment]
> Hi @GeeAlmeida! Adding a note to your last bullet point, as we know for sure (cos we tell it to do so) when the bot will tweet on a regular schedule:
> 
> * Monday - 9AM PST, 12PM EST, 4PM London time
> * Thursday 6:30 AM PST, 9:30 AM EST, 1:30PM London
> 
> All this information can be found on our repo [proghistbot](https://github.com/programminghistorian/proghistbot) which I realize we might have not share with you accordingly, and I apologize for that. @anisa-hawes we should add a note about the repo on the Jekyll repo Wiki, right?

Thank you for this!

**Comment by GeeAlmeida** [comment]
Tasks derived from this discussion:

- [x] Download and [archive our account's Twitter data](https://github.com/programminghistorian/project-and-business-archive/tree/master/project/Archive)
- [x] Create a Mastodon account [@proghist@hcommons.social](https://hcommons.social/@proghist)
- [x] Add our Mastodon account to a list of DH accounts <https://forms.gle/fDLWhuvsv82LEeKq8>
- [ ] Verify Mastodon account by adding a `rel="me"` attribute somewhere on our website (where?)
- [x] Set up cross-posting service Twitter >< Mastodon
- [x] Update Service Integrations page + share credentials with at least one other person

**Comment by anisa-hawes** [comment]
Did the addition of the `rel="me"` attribute work as you hoped, @GeeAlmeida? 

(I remember that you slotted it into your recent [2022 in review](https://programminghistorian.org/posts/2022-in-review) blogpost)
