### ISSUE TITLE
PH calendar of events - January

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2747]
Hi everyone @programminghistorian/project-team 

Our third event is in the works. Would January be a good time to host our first event in Portuguese @programminghistorian/portuguese-team ? I had discussed with @DanielAlvesLABDH the possibility of collaborating with a university in Brazil... Can we start thiking about this?

I will update this ticket as the details are finalised.

Working Title: Conheça o Programming Historian em português
Theme: getting to know PH
Format: roundtable discussion
Language: Portuguese
Date: either 25/01
Time: 14 hs UTC
Zoom info: to be shared with participants ✨

**Comment by GeeAlmeida** [comment]
![Riva's Templates](https://user-images.githubusercontent.com/109232661/206704364-800be324-44f3-4743-a40b-3cca0ce4f5e3.png)

**Comment by GeeAlmeida** [comment]
Conheça o Programming Historian em português 

A nossa revista de metodologia de história digital é um projeto pioneiro em humanidades digitais. Compareça no dia 25 de janeiro, quando discutiremos:
o nosso processo editorial
como publicar um tutorial
como contribuir para a revista
o nosso modelo de conteúdo aberto

com a presença dos editores Daniel Alves e Eric Brasil

**Comment by anisa-hawes** [comment]
Thank you, @GeeAlmeida. Shall we update Upcoming Events / Próximos eventos /  Manifestations à venir / Próximos Eventos?

**Comment by GeeAlmeida** [comment]
> Thank you, @GeeAlmeida. Shall we update Upcoming Events / Próximos eventos / Manifestations à venir / Próximos Eventos?

Yes, I am just waiting for comments from the speakers before I do that.

**Comment by DanielAlvesLABDH** [comment]
Olá Gisele, se puder altere "proceso" para "processo", por favor. Obrigado

**Comment by GeeAlmeida** [comment]
@DanielAlvesLABDH  aqui está a nova versao:

![Riva's Templates (5)](https://user-images.githubusercontent.com/109232661/207007476-a98dcec9-edcf-4033-bab4-269f384c49e2.png)

**Comment by GeeAlmeida** [comment]
Just to inform you that a couple of tweets will go out over the festive season reminding people to register for this event.

**Comment by GeeAlmeida** [comment]
39 people have signed up to this event so far (early Jan).

**Comment by GeeAlmeida** [comment]
Hey everyone.
This event was held on Wednesday. It was quite interesting!

We had 64 people registered to attend, I think wee had about 22-24 actually in the call.
Here is the link to the YouTube: https://youtu.be/5M1KX6AeLbQ

**Comment by DanielAlvesLABDH** [comment]
Thank you @GeeAlmeida. It was great!
