### ISSUE TITLE
Adding a new menu item events / eventos / manifestations / eventos 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2748]
I am opening this Issue to signal that I'm adding a new menu item to our website which provides a space for listing future and past _Programming Historian_ events.

I propose the following menu headings: en/events, es/eventos, fr/manifestations, pt/eventos
and that each page will have two sections: 

en/events/future
en/events/past

es/eventos/futuros
es/eventos/pasados

fr/manifestations/futur
fr/manifestations/passé

pt/eventos/futuros
pt/eventos/passados

- [x] I'm going to begin preparing the necessary changes in `menu.html` and `snippets.yml` alongside template versions of the four new pages in a branch so I can make sure everything works.

- [x] @GeeAlmeida and I will connect next Friday 18th November and work together to populate these pages with information about November and December's events. Gisele will maintain the pages going forwards. Our idea is to include links to EventBrite registration pages for future events, and YouTube/links to other documentation for past events.

In creating the templates, I've been thinking about how best to formulate/present the multi-lingual list. I think it's important to a) make it clear which language the event will be co-ordinated in, b) simplify maintenance/translation of the page upon each update. I very much welcome feedback on this.

- [ ] When we're happy with the formatting, we'll seek feedback on the vocabulary choices, and I will be happy to make adjustments to my (very rough) translations as needed!

**Comment by anisa-hawes** [comment]
Okay. The template pages are ready in [PR 2749](https://github.com/programminghistorian/jekyll/pull/2749), and @GeeAlmeida is happy with the layout and formatting (she has also made some tweaks to my Portuguese blurb 🙃 ).

--

Gisele expressed a preference for the word 'upcoming' in place of 'future', so I've replaced the section headings as follows:

en/events/upcoming
en/events/past

es/eventos/próximos-eventos
es/eventos/eventos-pasados

fr/manifestations/manifestations-à-venir
fr/manifestations/manifestations-passé

pt/eventos/próximos-eventos
pt/eventos/eventos-passados

--

I'd be grateful if someone from the @programminghistorian/spanish-team and @programminghistorian/french-team could take [a look at the ES](https://deploy-preview-2749--ph-preview.netlify.app/es/eventos) and [FR pages](https://deploy-preview-2749--ph-preview.netlify.app/fr/manifestations) to check you're happy with the vocabulary and phrases.

> https://deploy-preview-2749--ph-preview.netlify.app/es/eventos
> https://deploy-preview-2749--ph-preview.netlify.app/fr/manifestations

You'll notice that I've written a short blurb on each 'landing page' to say: _In 2022 we launched a programme of in-house, multilingual events to support educators, learners, and project partners. If you would like to contribute, collaborate or find out more please contact our Education & Community Lead Gisele Almeida._

I welcome feedback on this text, and any other aspects of the page!

**Comment by anisa-hawes** [comment]
Another (related) thought I had was whether I should collapse the Vacancies tab into the About drop-down menu, to avoid the bar becoming too cluttered... ?

I think I can see how that would be done.

**Comment by DanielAlvesLABDH** [comment]
Hi all. Just noticed that the menu item "Vagas" on the PH PT site redirects to the EN page. Also, it would be good to change a little the text on the Portuguese page: "Obrigado pelo seu interesse ao trabalhar com" to "Obrigado pelo seu interesse em trabalhar com"

**Comment by jenniferisasi** [comment]
The Spanish language page is fine, @anisa-hawes. Only thing is, @rivaquiroga did we ever decide to write only in "tú" or both tú and usted (not mixed in the same text, of course); can't remember.

**Comment by rivaquiroga** [comment]
If we follow our own Author Guidelines, we should use tuteo. I'll make the change.

**Comment by rivaquiroga** [comment]
Done!

**Comment by anisa-hawes** [comment]
> noticed that the menu item "Vagas" on the PH PT site redirects to the EN page. Also, it would be good to change a little the text on the Portuguese page: "Obrigado pelo seu interesse ao trabalhar com" to "Obrigado pelo seu interesse em trabalhar com"


Thank you, @DanielAlvesLABDH. I've integrated both of these corrections into #2749.
