### ISSUE TITLE
editor name on powershell

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#275]
https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/intro-to-powershell.md

No editor listed in reviewer list. @jerielizabeth this was you, no?

**Comment by jerielizabeth** [comment]
Indeed! :) I just added myself and added the review ticket information.

## 

Jeri E. Wieringa
Digital Publishing Production Lead, George Mason University Libraries
PhD Candidate, Department of History and Art History
George Mason University
www.jeriwieringa.com
