### ISSUE TITLE
Steps to put together a PH event

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2750]
Steps to put together PH events:

1) Create a new issue at ticket to discuss the event and identify its topic with the wider team

2) Identify possible speakers

3) In dialogue with the speakers, set the date and time

4) Create the event in Eventbrite (include a question to participants: are they OK with the event being recorded?)

5) Create a TinyURL for the event's Eventbrite link

6) Ideally at least 3 weeks in advance, start to communicate the event: 

 - if we are sharing images on social media containing information, add alt-text to give the details written in the image
 - ensure the web accessibility for the visuals
 - Use Riva's templates on Canva as the basis of images for future events. They should be adapted, to suit the colour of the relevant publication
 - The colours and fonts are available in the Brand Guidelines: https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines
 - PH's existing imagery can be found at: https://www.flickr.com/photos/britishlibrary/ or https://www.flickr.com/photos/e-codices or http://www.loc.gov/maps/collections.

---

**Where to communicate the event**

All languages: Patreon, Twitter/Mastodon and PH website (events section in four languages)

Language-specific:

**Spanish**: ask for the support of the Spanish team to spread the word among their contacts and students
Past events have been shared to: Humanidades Digitales Hispánicas (Spain) and Asociación Argentina de HD [Jenn]; LatamHD mailing list that is managed by the Red de HD http://humanidadesdigitales.net/ in Mexico [mariajoafana]; and tweeted by @HDHispanicas [Humanidades Digitales Hispánicas]

**English**: ask for the support of the English team to spread the word among their contacts and students; Royal Historical Society newsletter, H-net, H-Soz-Kult, Digital Humanities channel in Slack

Digital Humanities Summer Institute mailing list - email event to [institute@lists.uvic.ca](mailto:institute@lists.uvic.ca)

**Portuguese**: 

Laboratório de Humanidades Digitais: dhlab@fcsh.unl.pt [Daniel's group]
Associação das Humanidades Digitais: ahdig.portugues@gmail.com
História da Historiografia: historiadahistoriografia@hotmail.com
ANPUH: secretaria@anpuh.org 
Rede Brasileira de História Pública: rebrahip@gmail.com
Associação Brasileira de Humanidades Digitais / Jair Martins de Miranda: jairmm@unirio.br
Ana Isabel Ribeiro (Coimbra): aribeiro@fl.uc.pt [asked for a group email]
Sílvia Lima Gonçalves Araújo (Minho): saraujo@elach.uminho.pt [asked for a group email]
Thiago Lima Nicodemo (Centro de Humanidades Digitais / Unicamp): tnicodem@unicamp.br
Bruno Leal (UnB): bruno.leal@unb.br
Vanessa Martins do Monte (Grupo de Pesquisas Humanidades Digitais / USP): vmmonte@usp.br [asked for group email]

**French**: 

quanti@groupes.renater.fr
mate-shs@services.cnrs.fr
dh-request@groupes.renater.fr
accesouvert-request@groupes.renater.fr
Matthias Gille Levenson: matthias.gille-levenson@casadevelazquez.org
DHAfricaNetwork on Twitter

---

7) Send speakers a Google Calendar invite with the link to the Zoom call (10 minutes before the announced time) and the questions / points to be discussed during the event

**- On the day of the event:**

8) Send an email to those who have registered to attend the event with the Zoom link

9) Check video and audio settings on hosting computer and guest speakers. Ensure one more person is co-host

10) Edit the video and upload it to YouTube - edit out the Q&A at the end of the session

11) Close the event's particular issue with a comment containing the link to the session on YouTube

12) Communicate the YouTube link:
- send the link to registered attendants
- post it on Twitter / Mastodon
- post it on the website (under "past events")

**Comment by acrymble** [comment]
Good places to advertise English events would be: Twitter, Mastodon, Patreon, Royal Historical Society newsletter. Maybe H-net (do people still use that?).

**Comment by acrymble** [comment]
@GeeAlmeida thanks for opening this. Let's discuss it at our next group meeting. Once we've solidified this plan, it would be good to move it to a stable place where it can act as a reference for anyone else running events. Maybe the Wiki (if we keep using the Wiki).

**Comment by GeeAlmeida** [comment]
> Good places to advertise English events would be: Twitter, Mastodon, Patreon, Royal Historical Society newsletter. Maybe H-net (do people still use that?).

Thanks Adam!

Have we decided we are leaving Twitter and opening a Mastodon account?
I still receive H-net emails. I'll look for a DH-specific channel in there.

**Comment by acrymble** [comment]
@GeeAlmeida If you're still getting useful traction at Twitter I don't think you need to leave. But it's probably not as all-encompassing a solution as it once was.

I don't think there is a DH-specific H-net. But again, your audience isn't necessarily DH people, but humanities people. Especially for the upcoming event.

**Comment by GeeAlmeida** [comment]
@programminghistorian/english-team does anyone have further suggestions on where to advertise English events? So far I've got:
Royal Historical Society newsletter, H-net, H-Soz-Kult, Digital Humanities channel in Slack

**Comment by hawc2** [comment]
The DHSI listserv is very active. There's other associtation listserves with relevant communities, like Code4Lib. 

UCLA's DH newsletter is very popular and would probably include our event announcements if we asked. We could contact other DH orgs/departments like Yale's DH Lab and they can share events with their communities

**Comment by drjwbaker** [comment]
- https://sites.google.com/view/ai4lam
- Europeana Research Community (via Rebecca Kahn) https://pro.europeana.eu/page/europeana-research
- whatever we think of it, dh-humanist is still going https://dhhumanist.org/
- https://www.jiscmail.ac.uk/cgi-bin/webadmin?A0=DIGITALSCHOLARSHIP

**Comment by GeeAlmeida** [comment]
> The DHSI listserv is very active. There's other associtation listserves with relevant communities, like Code4Lib.
> 
> UCLA's DH newsletter is very popular and would probably include our event announcements if we asked. We could contact other DH orgs/departments like Yale's DH Lab and they can share events with their communities

Alex @hawc2 thank you for these suggestions. I have joined DHSI following this suggestion. I tried with Code4Lib but it wasn't clear to me how to send them events. Can you maybe point me to a website? Also great about the events, will try to reach out to some.

**Comment by hawc2** [comment]
Well, in searching for the Code4Lib listserv, I came across a List of Lists that Code4Lib put together: https://wiki.code4lib.org/List_of_Listservs

There may be a few useful resources there. 

Here's Code4Lib's wikipage on their listserv: https://wiki.code4lib.org/MailingList

**Comment by GeeAlmeida** [comment]
@programminghistorian/portuguese-team 
Hi Portuguese team
We will soon be communicating our first event in Portuguese. Can you let me know where I can post it so as many people as possible will find out about it? Thanks!

**Comment by DanielAlvesLABDH** [comment]
Hi @GeeAlmeida, I have published the news about the event here: https://ahdig.wordpress.com/2022/12/13/conheca-o-programming-historian-em-portugues/

**Comment by ericbrasiln** [comment]
@GeeAlmeida it might be a good idea to send an e-mail to the ANPUH (Associação Nacional de História do Brasil). They could post the event information on their website and social media.
secretaria@anpuh.org and informe@anpuh.org

**Comment by GeeAlmeida** [comment]
> [secretaria@anpuh.org](mailto:secretaria@anpuh.org) and [informe@anpuh.org](mailto:informe@anpuh.org)

Boa! Vou mandar pro pessoal da História da Historiografia tb, eles estao por comecar um newsletter.

**Comment by GeeAlmeida** [comment]
> Hi @GeeAlmeida, I have published the news about the event here: https://ahdig.wordpress.com/2022/12/13/conheca-o-programming-historian-em-portugues/

Daniel what is their email address, so I can send them future events?

**Comment by GeeAlmeida** [comment]
Next week I will close this issue and turn its contents into a Wiki guide. If anyone would like to add anything, you can either do it here in the coming days or in the Wiki afterwards.

**Comment by GeeAlmeida** [comment]
This issue is being closed. All of the details shared here have been included in the Wiki [Protocol for organising events](https://github.com/programminghistorian/jekyll/wiki/Protocol-for-organising-events)
