### ISSUE TITLE
Offer to Gold IPPs

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2751]
IPPs that sign up to the gold tier pay  £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD for their yearly membership. Our selling point for this tier is the offer of two workshops per year. This issue is to discuss what exactly we should be offering and to sketch a protocol for PH's relationship with gold tier supporters.

**What we offer**

The two workshops per year are aimed at students and researchers. Show them how to use PH, how to find relevant skills for their research, where to go next, etc. In a conversation with librarians, they welcomed the fact that two offering per year makes it more flexible and easier for students to sign up.

In the same conversation it was suggested that a more advanced workshop aimed at librarians and educators would also be helpful. It would show how to use PH with students and researchers. This would be a basic overview, not specialist training. To reduce the number of workshops, an idea is to offer this "advanced" workshop to all gold tier organisations at the same time.

**Wording of the offering for Gold Tier IPPs**

At the moment, our website states the following:

"Gold partners are offered two bespoke workshops per year to help their communities use digital humanities tools and methods."

This needs to be more focused, and clear - binding us to no more than what we can offer. For example, maybe it should mention that the two workshops need to be booked within the 12 months, if not they will not roll on to the next academic year.

**Protocol for Gold Tier IPPs**

1- James writes to thank them for their support

2- Gisele writes to make the offer of two workshops

3- A special tweet goes out celebrating gold tier support

4- tbc

**Comment by drjwbaker** [comment]
> The two workshops per year are aimed at students and researchers. Show them how to use PH, how to find relevant skills for their research, where to go next, etc. In a conversation with librarians, they welcomed the fact that two offering per year makes it more flexible and easier for students to sign up.

I suspect some librarians may wish to join as well as professional development

**Comment by drjwbaker** [comment]
Maybe something like: "Gold partners are offered the opportunity to suggest the topics/themes for two workshops per year to help their communities use digital humanities tools and methods. These workshops would have open registration, with places reserved for staff (and where applicable students) of Gold tier members."

This recognises that:
- not all IPPs are places with students
- gives IPPs something but doesn't mean we have to run closed workshops for them

**Comment by drjwbaker** [comment]
>  maybe it should mention that the two workshops need to be booked within the 12 months

Agreed.

**Comment by acrymble** [comment]
60 minutes? 90 minutes? Timezone limits?
On Zoom?

Can anyone else think like a lawyer here and think of things that may go wrong if not made very explicit?

**Comment by drjwbaker** [comment]
Indeed Adam. We need some wording to the effect of:

> the final decision as the composition, format, duration, and timing is all ProgHist Ltd workshops, events, and seminars delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd.

**Comment by acrymble** [comment]
Can we please turn this thread into a draft of the full email text we'll send so we can check it over and make sure we're covering ourselves and avoiding any confusion with the IPPs? @GeeAlmeida can you please draft that and we can tinker with it as needed? I think we can do English only for now, until we start to get Gold IPPs in other languages.

I'd also like to know how we will keep track that this is done within the time limits. Who is going to monitor that we don't have workshops outstanding? It would be embarrassing to forget.

**Comment by drjwbaker** [comment]
The relevant line in the email from last time:

> The current annual renewal rates are £1,000 GBP / $1,400 USD / €1,200 EUR / $1,700 CAD. Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners are offered two exclusive bespoke workshops per year for their students and researchers on how to get started using digital humanities tools. Please email Dr. James Baker (programminghistorian@gmail.com) to renew your membership.

Based on ongoing discussions, I propose we change to:

 > The current annual renewal rates are £1,000 GBP / $1,400 USD / €1,200 EUR / $1,700 CAD. Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners are offered the opportunity to suggest the topics or themes for two events per year to help their communities use digital humanities tools and methods.* Please email Dr. James Baker (programminghistorian@gmail.com) to renew your membership.

Then at the foot of the email:
> * Events will have open registration, with places reserved for Gold Tier members. Event suggestions and reserved places only apply during the period of Gold Tier membership. The final decision as the composition, format, duration, and timing of all ProgHist Ltd events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd.

**Comment by acrymble** [comment]
@drjwbaker I like the disclaimer. Very important. Also love the idea of opening them up to others.

I'm not sure we have the in house expertise to do custom events though, especially if they're technical. If the Gold member wants a workshop on network analysis, I don't think we can whip that up. Can we move to a simplified menu of choices of workshops we know we can deliver? Our library partners mentioned things like:

- Intro to PH for Librarian / Research Support staff (with the aim of helping others to use it)
- Students-oriented event on finding new skills on PH, maybe for your dissertation or a major research paper
- Early Career event for using PH in the classroom for the first time
- Mid/Late Career event for using PH in the classroom for the first time
- No thank you, we don't need any events, we just wanted to support your great work.

We need to be mindful that @GeeAlmeida will have to be comfortable with whatever the content is, so we have to avoid things that are too technically specialist.

**Comment by GeeAlmeida** [comment]
> full email text we'll send

Hi Adam
when you say "full email text we'll send" I think you have in mind the email to orgs that have already signed up as Gold IPPs?

At this moment in time I am more concerned with the information that goes out to orgs to become IPPs. I will do as you requested at a later stage if that is OK.

**Comment by GeeAlmeida** [comment]
On the types of events, I like the idea of bespoke / custom events. Maybe this is a better way to spend the money available for events?
Plus, more gold IPPs means there would be more money available. If they have a need that we can address (workshop / extensive network of individuals who can provide various workshops) I don't see why not.
@drjwbaker @acrymble

**Comment by GeeAlmeida** [comment]
James mentioned something different in this suggestion: "Events will have open registration, with places reserved for Gold Tier members." - is that a model we want to pursue? Open events with seats reserved to Gold IPPs?
I don't see this as feasible. Zoom is limited to 100 attendees. What would we offer? 20 places per Gold IPP?

**Comment by drjwbaker** [comment]
>  I don't see this as feasible. Zoom is limited to 100 attendees. What would we offer? 20 places per Gold IPP?

I don't think we need to worry about the technical implementation. But if we are, we could - for example - have two types of ticket to an event: one that is £0 and open (with say 80 places) and another that is £0 but for staff/students at Gold IPPs (with say 20 places). That would be reasonable in the fisrt instance, and could evolve if/as we get more Gold IPPs.

**Comment by drjwbaker** [comment]
> @drjwbaker I like the disclaimer. Very important. Also love the idea of opening them up to others.
> 
> I'm not sure we have the in house expertise to do custom events though, especially if they're technical. If the Gold member wants a workshop on network analysis, I don't think we can whip that up. Can we move to a simplified menu of choices of workshops we know we can deliver? Our library partners mentioned things like:
> 
>     * Intro to PH for Librarian / Research Support staff (with the aim of helping others to use it)
> 
>     * Students-oriented event on finding new skills on PH, maybe for your dissertation or a major research paper
> 
>     * Early Career event for using PH in the classroom for the first time
> 
>     * Mid/Late Career event for using PH in the classroom for the first time
> 
>     * No thank you, we don't need any events, we just wanted to support your great work.
> 
> 
> We need to be mindful that @GeeAlmeida will have to be comfortable with whatever the content is, so we have to avoid things that are too technically specialist.

Agree that we can't run anything (but as @GeeAlmeida says we do have £ for asking a trainer to lead something that is beyond what @GeeAlmeida can lead on). But I also think we don't need to be precise here: the disclaimer I propose does the work you want it to without overthinking possible things people may want.

For example, if a Gold IPP asked for a session on network analysis we may not have the expertise to run a training session on this lesson https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python, but we do have the capacity to faciliate a session where people run through the lesson together (so peer learning rather than instructional learning).

**Comment by drjwbaker** [comment]
> > full email text we'll send
> 
> Hi Adam when you say "full email text we'll send" I think you have in mind the email to orgs that have already signed up as Gold IPPs?
> 
> At this moment in time I am more concerned with the information that goes out to orgs to become IPPs. I will do as you requested at a later stage if that is OK.

Agreed. That is why I put the relevant line from your last IPP mailout in the thred here https://github.com/programminghistorian/jekyll/issues/2751#issuecomment-1330421283

**Comment by GeeAlmeida** [comment]
> Can we please turn this thread into a draft of the full email text we'll send so we can check it over and make sure we're covering ourselves and avoiding any confusion with the IPPs? @GeeAlmeida can you please draft that and we can tinker with it as needed? I think we can do English only for now, until we start to get Gold IPPs in other languages.
> 
> I'd also like to know how we will keep track that this is done within the time limits. Who is going to monitor that we don't have workshops outstanding? It would be embarrassing to forget.

@acrymble I will keep track of what is delivered to Gold IPPs. At this point I don't envisage that many of them.

On a similar topic, how has the work of keeping track of contacts with prospective IPPs been done previously?
I'll just do what you guys used to do. I have looked in the business archive but could not find anything related to this.

**Comment by GeeAlmeida** [comment]
New proposed draft (to be sent to prospective IPPs):


Gold partners are offered two workshops per year to help their communities use digital humanities tools and methods. The composition, format, duration, and timing of events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd.

**Comment by acrymble** [comment]
> 

We kept track on that google spreadsheet I shared with you a few months ago. That's probably not a good long term solution, but it's what we have at the moment.

**Comment by drjwbaker** [comment]
> New proposed draft (to be sent to prospective IPPs):
> 
> Gold partners are offered two workshops per year to help their communities use digital humanities tools and methods. The composition, format, duration, and timing of events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd.

Thanks @GeeAlmeida. As types of membership are set by the Trustees (according to our Articles of Association, that is that document that describes how the Ltd works), I propose that the Trustees have the final say on the wording here. As I see it, we have two options:

1. The current annual renewal rates are £1,000 GBP / $1,400 USD / €1,200 EUR / $1,700 CAD. Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners are offered two workshops per year to help their communities use digital humanities tools and methods. The composition, format, duration, and timing of events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd. Please email Dr. James Baker ([programminghistorian@gmail.com](mailto:programminghistorian@gmail.com)) to renew your membership.

2. The current annual renewal rates are £1,000 GBP / $1,400 USD / €1,200 EUR / $1,700 CAD. Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners are offered the opportunity to suggest the topics or themes for two events per year to help their communities use digital humanities tools and methods. The composition, format, duration, and timing of events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd. Please email Dr. James Baker ([programminghistorian@gmail.com](mailto:programminghistorian@gmail.com)) to renew your membership.

The Trustees are meeting [16 January](https://github.com/programminghistorian/jekyll/issues/2762) anyway, so I propose that we decide this then (and at the same time our membership rates, which are set in January each year). We can then get the next batch of IPP renweal notices out later that month.

@anisa-hawes: I know that @spapastamkou has set this as a single issue meeting, but I've added it to the calendar here https://github.com/programminghistorian/jekyll/issues/2762 and appended a note about spending a little time on this decision.

**Comment by GeeAlmeida** [comment]
@drjwbaker 
Option 1 does not eliminate the possibility of workshops being suggested by gold partners. Can I use that for now?

I have the goal of contacting 15 prospective IPPs by the end of the year. 

Or should I put this goal on hold until the wording is resolved?

**Comment by drjwbaker** [comment]
Until the Trustees have agreed a wording, I suggest we use something like..

> The current annual renewal rates are £1,000 GBP / $1,400 USD / €1,200 EUR / $1,700 CAD. Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners have access to workshops to help their communities use digital humanities tools and methods (full details TBC). The composition, format, duration, and timing of events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd. Please email Dr. James Baker ([programminghistorian@gmail.com](mailto:programminghistorian@gmail.com)) to renew your membership.

..as that is less of a commitment than we currently have.

**Comment by GeeAlmeida** [comment]
@drjwbaker I understand you will update me on this next week...? I'll leave this here as a reminder.

FYI, I spoke to a team from Leuven this week and they had a good suggestion, that Gold IPPs can ask for a workshop on a tutorial they use with their students. This to me sounds like a real useful add-on that will interest departments that use our website more heavily than others.

**Comment by drjwbaker** [comment]
@GeeAlmeida Yes, Trustees will have an agreed wording ready for next week. And what Leuven suggests would fit within the current draft wording.

**Comment by drjwbaker** [comment]
Okay, the agreed wording is as follows (with the paragraph beginning with an asterisk to appear in smaller lettering at the bottom on an email, slide, etc. As with our IPP rates, the Trustees will review this each January.

-----

Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners are offered the opportunity to work with us to develop events that help their communities use digital humanities tools and methods.*
 
*Programming Historian events have open registrations, with places reserved for Gold Tier members. Up to two events each year will be developed with Gold Tier members. Event development opportunities and reserved places only apply during the period of Gold Tier membership. The final decision as to the composition, format, duration, and timing of all ProgHist Ltd events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd.

----

**Comment by drjwbaker** [comment]
(note that this needs a PR to update on the site)

**Comment by GeeAlmeida** [comment]
@programminghistorian/project-team 

Team, can you please help translate the text below into Spanish, Portuguese and French? I will then update the "support us" page on our website.

---

Gold Tier Partnership rates are £3,000 GBP / $4,200 USD / €3,600 EUR / $5,100 CAD. Gold partners are offered the opportunity to work with us to develop events that help their communities use digital humanities tools and methods.*

*Programming Historian events have open registrations, with places reserved for Gold Tier members. Up to two events each year will be developed with Gold Tier members. Event development opportunities and reserved places only apply during the period of Gold Tier membership. The final decision as to the composition, format, duration, and timing of all ProgHist Ltd events delivered as part of the Gold Tier scheme is at the discretion of ProgHist Ltd.

**Comment by acrymble** [comment]
@GeeAlmeida are you able to write the Spanish one? I'm not sure your level of written Spanish but I know you speak it well.

**Comment by DanielAlvesLABDH** [comment]
I will write the Portuguese one in the afternoon

**Comment by marie-flesch** [comment]
I'll translate it into French by the week @GeeAlmeida

**Comment by anisa-hawes** [comment]
I've prepared the following drafts, if useful.

- [x] ES is confirmed (thank you, @jenniferisasi)

Las tarifas de nuestros colaboradores en nivel Gold son de £3.000 GBP, $4.200 USD, €3.600 EUR, $5.100 CAD. A nuestros seguidores Gold se les ofrece la oportunidad de trabajar con nosotros para desarrollar eventos que ayuden a sus comunidades a utilizar las herramientas y métodos de las humanidades digitales.

*Los eventos de Programming Historian tienen inscripciones abiertas, con plazas reservadas para nuestros seguidores Gold. Se desarrollarán hasta dos eventos al año con miembros de la categoría Gold. Las oportunidades de desarrollo de eventos y las plazas reservadas sólo se aplicarán durante el periodo de afiliación a la categoría Gold. La decisión final sobre la composición, el formato, la duración y el calendario de todos los eventos de ProgHist Ltd organizados como parte del programa Gold queda a discreción de ProgHist Ltd.

- [ ] FR: 

Les tarifs pour du partenariat niveau Gold sont de 3 600 EUR, 3 600 CHF, 5 100 CAD, 3 000 GBP, 4 200 USD. Nos soutiens de niveau Gold ont la possibilité de travailler avec nous pour développer des événements qui aident leurs communautés à utiliser les outils et les méthodes des humanités numériques.

*Les événements de Programmation Historienne sont ouverts à l'inscription, avec des places réservées à nos soutiens de niveau Gold. Jusqu'à deux événements par an seront développés avec des soutiens niveau Gold. Les opportunités de développement d'événements et les places réservées ne s'appliqueront que pendant la période d'adhésion au niveau Gold. La décision finale concernant la composition, le format, la durée et le calendrier de tous les événements ProgHist Ltd organisés dans le cadre du programme Gold est à la discrétion de ProgHist Ltd.

- [x] PT is confirmed (thank you, @DanielAlvesLABDH) 

As taxas de parceria ao nível Gold são €3.600 EUR, $21.000 BRA, £3.000 GBP, $4.200 USD, $5.100 CAD. Os nossos apoiadores do nível Gold têm a oportunidade de trabalhar connosco para desenvolver eventos que ajudem as suas comunidades a utilizar ferramentas e métodos de humanidades digitais.

*Os eventos de Programming Historian estão abertos para inscrição, com lugares reservados para os nossos apoiadores de nível Gold. Serão desenvolvidos até dois eventos por ano com apoiadores de nível Gold. Oportunidades de desenvolvimento de eventos e lugares reservados só se aplicarão durante o período de filiação de nível Gold. A decisão final sobre a composição, formato, duração e calendário de todos os eventos ProgHist Ltd. organizados no âmbito do programa Gold fica ao critério da ProgHist Ltd.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes, your Portuguese is perfect! Thanks for the help!

**Comment by GeeAlmeida** [comment]
> @GeeAlmeida are you able to write the Spanish one? I'm not sure your level of written Spanish but I know you speak it well.

Hi @acrymble yes, I think I probably have the Spanish for this - although it is always best to have a native look at my writing.

I didn't have much time on Wed afternoon. Glad to see we are almost there with the texts. I will wait until the website is updated before I send the first email to prospective IPPs and tweet about our first Gold supporter.

**Comment by rivaquiroga** [comment]
Here is the Spanish version:

Las tarifas para nuestros colaboradores en nivel Gold son de £3.000 GBP, $4.200 USD, €3.600 EUR, $5.100 CAD. Como parte de la membresía, se les ofrece la oportunidad de trabajar con nosotros en el desarrollo de eventos que ayuden a sus comunidades a utilizar herramientas y métodos de las humanidades digitales.

*Los eventos de Programming Historian tienen inscripciones abiertas, con plazas reservadas para nuestros colaboradores del nivel Gold. Se desarrollarán hasta dos eventos al año con los miembros de esta categoría. Las oportunidades de desarrollo de eventos y las plazas reservadas sólo se aplicarán durante el periodo de afiliación a la categoría Gold. La decisión final sobre la composición, el formato, la duración y el calendario de todos los eventos de ProgHist Ltd organizados como parte del programa Gold Tier queda a discreción de ProgHist Ltd.

**Comment by GeeAlmeida** [comment]
Gracias Riva!

**Comment by marie-flesch** [comment]
And here's the French text : 

Les tarifs de nos partenariats de niveau Gold sont de 3 600 EUR, 3 600 CHF, 5 100 CAD, 3 000 GBP, et 4 200 USD. Nos partenaires Gold peuvent travailler avec nous pour développer des évènements qui aident leurs communautés à utiliser les outils et les méthodes des humanités numériques.

*Les évènements du Programming Historian sont ouverts sur inscription, avec des places réservées à nos partenaires Gold. Nous organiserons jusqu’à deux évènements par an avec nos partenaires de niveau Gold. Il n’est possible d’organiser des évènements et de profiter de places réservées que pendant la période d’adhésion au niveau Gold. La décision finale concernant la composition, le format, la durée et la date de tous les évènements de ProgHist Ltd organisés dans le cadre du programme Gold est à la discrétion de ProgHist Ltd.

**Comment by GeeAlmeida** [comment]
Fab @marie-flesch, thank you so much!
