### ISSUE TITLE
Netlify Build Image needs to be updated

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2752]
I'm opening this Issue because I noted that [our Netlify Build Image needs to be updated](https://app.netlify.com/sites/ph-preview/deploys/6374ef927ca4bf0009cf7a43), so [all our ph-preview deploys are failing](https://github.com/programminghistorian/jekyll/pull/2731).

Clicking into the Deploy detail, I find the following:

![Screenshot 2022-11-16 at 14 28 19](https://user-images.githubusercontent.com/87070441/202207341-bc44abc0-eede-417d-a0c1-f3305184ad6d.png)

The text reads:

UNSUPPORTED BUILD IMAGE

  The build image for this site uses Ubuntu 16.04 Xenial Xerus, which is no longer supported.

  To enable builds for this site, select a later build image at the following link:
  https://app.netlify.com/sites/ph-preview/settings/deploys#build-image-selection

  For more details, visit the build migration guide:
  https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

I have scanned the Migration Guide, and note that there would have been a warning somewhere in our logs `DEPRECATION NOTICE: Builds using the Xenial build image will fail after November 15th, 2022` but I didn't encounter that...

Are you able to help @ZoeLeBlanc? 

(I can make the change if you let me know what's needed, but I don't have the Netlify login credentials.)

**Comment by ZoeLeBlanc** [comment]
Thanks for catching this @anisa-hawes! I just updated the netlify settings for our build image so hoping that does the trick 🤞🏽 😅

**Comment by anisa-hawes** [comment]
Super! Thank you, @ZoeLeBlanc! 🚀 That seems to have solved it.
