### ISSUE TITLE
Update screesnhot for Kaggle setup in computer vision lessons 

### ISSUE THREAD

**Issue by davanstrien** [programminghistorian/jekyll#2754]
The setup for the computer vision lessons https://programminghistorian.org/en/lessons/computer-vision-deep-learning-pt1#kaggle needs to be updated to reflect an update in the options for GPUs in Kaggle.

<img width="627" alt="Screenshot 2022-11-17 at 10 56 17" src="https://user-images.githubusercontent.com/8995957/202428279-1b68953c-e2ba-4906-99dc-fec857b24a87.png">

Kaggle offers different types of GPU, so it's clearer to specify which kind to users of the lesson. This will require an updated screenshot and a small modification to the text. 

 I will aim to do it this week or early next week.

**Comment by davanstrien** [comment]
Happy to also get assigned to this :)

**Comment by anisa-hawes** [comment]
Thank you, @davanstrien. If you could email me the updated image (admin [@] programminghistorian.org) then I can make this change. That is usually simpler than you forking our repo, as we make changes to our website so frequently.
