### ISSUE TITLE
Diacritical marks not covered by the theme font

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#276]
Hi all! 

I have a lesson about to be moved over with some diacritical marks that appear to be rendering in a different font. (http://programminghistorian.github.io/ph-submissions/lessons/editing-audio-with-audacity) Do we know if Lato supports Vietnamese characters?

**Comment by wcaleb** [comment]
Hmmm ... [this list](https://www.fontsquirrel.com/fonts/list/language/vietnamese) suggests it does. Maybe the character needs to be inputted a certain way? Using a Unicode number? I confess I'm a bit out of depth here.

**Comment by jerielizabeth** [comment]
I'll look into whether there is another way to enter them! Thanks!

**Comment by jerielizabeth** [comment]
it appears to be a weight problem -- Lato has the characters, but only at 400 weight.

**Comment by wcaleb** [comment]
It's not an ideal fix, because it will only cover some cases, but I made the "credits" box use the 400 weight in our stylesheet.
