### ISSUE TITLE
Build and deployment update needed? : `Input 'emit_telemetry' has been deprecated`

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2761]
I am opening this Issue to signal that our build and deployment may need to be updated. Daniel and I noted that recent PR #2759 did not successfully merge in.

[Clicking into the full error detail](https://github.com/programminghistorian/jekyll/actions/runs/3540348017/jobs/5943416350), there is the message: `Input 'emit_telemetry' has been deprecated`. 

In this case, I was able to [merge in the PR successfully by re-running the build but the warning remains](https://github.com/programminghistorian/jekyll/actions/runs/3540348017). So we may still need to review this, incase an update is needed. Hello @ZoeLeBlanc, might you have time to take a look at this? Not urgent, I don't think...

**Comment by anisa-hawes** [comment]
[Looks like it might be something lots of others on GitHub have experienced within the last 24 hours](https://github.com/community/community/discussions/39907)! An error on GitHub's side, and nothing to worry about 🙂

**Comment by anisa-hawes** [comment]
Noting here that the same error message `Warning: Input 'emit_telemetry' has been deprecated with message: Use of this input causes the action to do nothing. You should remove this build step from your workflow.` appears in the pages build and deployment section of [a recent merge](https://github.com/programminghistorian/jekyll/actions/runs/3593707188).

**Comment by ZoeLeBlanc** [comment]
Thanks for flagging this @anisa-hawes ! Let's plan to tackle this at our meeting next week unless it turns out to be more urgent.
