### ISSUE TITLE
Agreeing our meetings calendar: 2023

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2762]
Hello all,

I am opening this Issue to agree our meetings calendar in advance for 2023. 

We currently have four core meeting sequences:

1. Project Team Meetings
2. Board of Trustees Meetings
3. Managing Editors' Meetings
4. Annual General Meeting

I would like to propose that we meet as a whole Project Team (1.) on a bi-annual basis going forwards, in March and September.

Meanwhile Board of Trustees Meetings (2.), and Managing Editors' Meetings (3.) will continue once-per-quarter. Our Annual General Meeting (4.) is once per year, in May.

In each sequence I'm aiming to vary the day of the week, to increase the probability that everyone will be able to attend at least some of the meetings.  Remember, there is no expectation that everyone will be able to attend every meeting. I'll always share minutes internally, so that anyone unable to attend can still understand what was discussed.

Also, members of the Board of Trustees or Managing Editors may request a topic-specific meeting in addition to this schedule if they need to.

I've reviewed the list of holidays/religious days you collectively complied [here](https://github.com/programminghistorian/jekyll/issues/1739). I don't think this calendar presents obvious clashes for 2023, but please let me know if you feel one of the dates I've suggested feels unsuitable. 

Please let me know your thoughts @programminghistorian/french-team, @programminghistorian/portuguese-team, @programminghistorian/spanish-team,  @programminghistorian/english-team and I will begin to send out calendar invitations.

2023
---

**January**
Monday 16th: Special Board of Trustees Meeting [16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230116T160000&p1=64&p2=232&p3=1440&p4=136&p5=195). See #2778

**February**
~~Thursday 23rd: Board of Trustees Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230223T140000&p1=1440).~~

**March**
Thursday 2nd: Board of Trustees Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230302T140000&p1=1440)
~~Wednesday 8th: Project Team Meeting [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230308T150000&p1=1440)~~
Thursday 16th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230316T140000&p1=1440)

**April**
(no meetings)

**May**
Wednesday 24th: Board of Trustees Meeting [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230524T150000&p1=1440)
- [x] Calendar invites sent

**June**
Friday 16th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230616T140000&p1=1440)
- [x] Calendar invites sent

Wednesday 21st: Annual General Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230621T140000&p1=1440)
- [x] Calendar invites sent

**July**
Wednesday 12th: Board of Trustees Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230712T140000&p1=1440)
- [x] Calendar invites sent

**August**
(no meetings)

**September**
Friday 15th: Project Team Meeting [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230915T150000&p1=1440)
- [x] Calendar invites sent

Wednesday 20th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230920T140000&p1=1440)
- [x] Calendar invites sent

**October**
(no meetings)

**November**
Friday 10th: Board of Trustees Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20231110T140000&p1=1440)
- [x] Calendar invites sent

**December**
Friday 1st: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20231201T140000&p1=1440) 
- [x] Calendar invites sent

**Comment by rivaquiroga** [comment]
December 8 is a holiday in most Spanish-speaking countries :latin_cross:. We don't know yet who will be the Managing Editor of the Spanish team by then, but it might be a good idea to take that into account.

**Comment by anisa-hawes** [comment]
Thank you @rivaquiroga! I appreciate you sharing this information. In that case, I'd like to suggest we bring that meeting forward by one week to Friday 1st December. I've updated the calendar + the time zone converter link (above) .

**Comment by GeeAlmeida** [comment]
@anisa-hawes  Which meetings am I to attend? Project Team meetings and Annual General Meeting?

I've checked my calendar and there are no conflicts.

**Comment by anisa-hawes** [comment]
Thank you, @GeeAlmeida. Yes, if you are working on those days you can join those meetings.

**Comment by anisa-hawes** [comment]
Dear @spapastamkou. Thank you for suggesting the single issue BoT Meeting for January. Unfortunately, I cannot make it on Monday 16th, so I am suggesting Wednesday 18th as an alternative #2778.

**Comment by hawc2** [comment]
@anisa-hawes have we stopped having monthly project team meetings that I should be attending? I was used to going more regular to PH organizational meetings. Maybe I missed that we changed schedules going forward? 

I'm just trying to figure out which of these meetings I should put on my calendar (and figure out what role the ME plays for admin planning). If I won't be at these meetings to raise certain issues coming up on the English team, I can start posting them as issues on Github or another channel if you can suggest one

**Comment by anisa-hawes** [comment]
Hello @hawc2. I'm sorry to have missed this question. 

The Managing Editors' meetings are scheduled quarterly (next one on 16th March), so that will be an ideal forum for discussions about administration, workflows, and planning. 

I'm equally very happy for you to open Issues with specific ideas/questions.

**Comment by hawc2** [comment]
Thanks @anisa-hawes. 

Sorry for continued questions, but I'm a little confused, because if I remember correctly, when Sarah was ME, and I was Assistant ME, I attended monthly meetings where the Board of Trustees (Admin) were present. That seemed to be the schedule through the 2022 calendar year. 

It looks like from the calendar for 2023, there will be two meetings this year where MEs will be able to speak to PH Admin (the Annual meeting and the Project Team meeting in September). I don't mean to be annoying and make everyone attend more meetings, but my prior experience with PH led me to expect that when I was ME I would have a pretty regular channel of communication with the Admin team, and that there would be monthly or at least quarterly checkins where we could report on ongoing issues and challenges with each journal, as well as hear from admin about higher-up planning and discuss descisions as a group.

I don't think I realized before when you posted this ticket that the change was so drastic in terms of frequency of Project Team meetings where everyone would be included. I should've brought it up before, but I've still just been getting my bearings as ME for the English team. I just wanted to take this opportunity to note that, from my perspective, the lack of regular meetings with the Admin Team in 2023 has led me to feel more out of the loop and unsure of how to raise issues/concerns that aren't easy to discuss over Github. I will try to post more issues to Github relating to needs/tasks, but I also do think we should reassess this proposed schedule for 2023.

**Comment by drjwbaker** [comment]
@hawc2 Thanks for raising this. It has been noted that there are some uncertainty over what the Board of Trustees meetings (which Sarah used to attend as a Trustee) do and don't do. But the short version is that the Trustees aren't controlling the admin side of things: most of our business is financial (e.g. signing off annual accounts), legal (e.g. putting in place a parental leave policy for our employees), and strategic (e.g. oversight of the business plan). With @anisa-hawes changing role to become Publishing Manager, it should be clearer that she is empowered to work directly with MEs on decision making, and then bring proposals to the Trustees for *appropriate* sign off (e.g. if the MEs and Anisa decide a new employed role is needed, the signoff required from Trustees is restricted mostly to ensuring it is financially viable, meets our charitable purposes, and fits the business plan). So a refresh of meeting types can be part of that. Ideally, Trustees meetings should really be focused on financial, legal, and advisory functions. I hope that helps.

**Comment by drjwbaker** [comment]
Also, with @rivaquiroga and @spapastamkou stepping of as MEs, but remaining Trustees, the difference in roles should become clearer. As ever, growing fast as a publisher (as a employer, with IPPs, etc) has its associated growing pains.

**Comment by hawc2** [comment]
Thanks @drjwbaker. That makes sense. I guess I thought the meetings I had been attending last year we're different from the Board of Trustees meetings, more like general org meetings. I would be in favor of something like quarterly Project Team meetings for the core people involved with the language journals, the tech team, and the admin team, to help keep us all on the same page. It could be optional for the rest of the PH editors to attend if interested. But I'm also happy to wait and see how things develop with Anisa's new role serving to mediate. I can plan to coordinate with her for now about any questions I have about larger PH planning

**Comment by drjwbaker** [comment]
What you suggest feels about right to me @hawc2

**Comment by drjwbaker** [comment]
@anisa-hawes On the AGM in May, I know you have a lot on, so do please say if you need help pulling this together. I suspect we need to get the invites out soon, though I'm sure you have that in hand (I just remembered and - with luck! - I have a gap for this in my diary).

**Comment by spapastamkou** [comment]
@drjwbaker hey James, normally the date of 24 th May would be kept for the next BoT meeting and we should organize the AGM in June (second half). I formulated the request - I hope this does not perturbate a lot the agendas! - and more details should arrive soon.

**Comment by anisa-hawes** [comment]
Dear all, 

I have amended the calendar above to reflect two proposed changes:

**May**
Wednesday 24th: Board of Trustees Meeting [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230524T150000&p1=1440)

**June**
Wednesday 21st: Annual General Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230621T140000&p1=1440)

-- 
Further details to follow.

**Comment by drjwbaker** [comment]
Ta. @anisa-hawes: practical thing. Could we run this (in part/whole) from an outlook / goolge calendar, with all required attendees tagged to calendar invites that pop into our diaries? I really appreciate holds going into my diary as early as feasible, and I don't mind them moving around subsequently if needs be.

**Comment by anisa-hawes** [comment]
Yes, excellent idea @drjwbaker. I will send calendar invites for the forthcoming meetings.

A note to say that I am in the process of reviewing our meetings calendar in light of several recent conversations with Managing Editors and others about how I can better support cross-team dialogue, and also provide internal and external community-building opportunities. More to follow on this.
