### ISSUE TITLE
Managing Editors' Meeting: Thursday 15th December 2022

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2763]
Hello @DanielAlvesLABDH, @rivaquiroga, @hawc2, @spapastamkou and @marie-flesch.

I am opening this Issue to agree an agenda for the forthcoming meeting of MEs.

Date: Thursday 15th December
Time: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20221215T140000&p1=1440&p2=198&p3=232&p4=133&p5=195): 09:00 Philadelphia / 11:00 Santiago / 14:00 Lisbon / 15:00 Paris
Minutes of the last meeting: [09_2022_ManagingEditorsMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Managing-Editors-Meetings/09_2022_ManagingEditorsMeeting.md)
Zoom link: https://zoom.us/j/5959205456
Passcode: by email

December Managing Editors' Meeting
---

Please add items you'd like to put on the agenda for discussion:

- Welcome to @marie-flesch ✨ 

- Update on Actions from last meeting @anisa-hawes 

- Forward-planning for 2023: When will you next be recruiting new editors to the Project Team? (so I can support you through advertisement and recruitment, and also offer training for new colleagues)
  -  The FR team will be recruiting in January 

- Forward-planning for 2023: How can ProgHist best support your communities through our Education & Community programme?
  
- Suggestion to attribute translators more prominently on lessons @hawc2 [See also Issue 2771](https://github.com/programminghistorian/jekyll/issues/2771)

**Comment by hawc2** [comment]
Thanks Anisa. Like the French team, the English team is hoping to recruit in January, with a focus on bilingual editors who can help with translations

**Comment by DanielAlvesLABDH** [comment]
Thank you @anisa-hawes. We will have a meeting of the PT team December 9th. Then we will have news.

**Comment by rivaquiroga** [comment]
Hi! I just realized that this meeting is at the exact same time of [the December event](https://github.com/programminghistorian/jekyll/issues/2709). Is it possible that we move it to another time slot?

**Comment by anisa-hawes** [comment]
Dear @rivaquiroga,

Yes, I noted this a few weeks ago. I wasn't sure if it was a problem, but we can organise a different time. I am sending an email to you all now to see what's possible.

Going forwards, I would like to avoid clashes. Gisele will be able to keep an eye on [Issue 2762](https://github.com/programminghistorian/jekyll/issues/2762) to know which days I have organised meetings.

**Comment by spapastamkou** [comment]
@hawc2 @rivaquiroga @DanielAlvesLABDH @anisa-hawes goodbye to all of you from here as this was my last Managing Editors meeting. It was a real pleasure working with you all as ME of the FR and you learnt me a lot! I leave you in the good company of @marie-flesch - who is :fire:! - and hopefully I will bump into you on other issues:-)

**Comment by DanielAlvesLABDH** [comment]
Dear @spapastamkou thanks for your kind message and for your collaboration. It was a pleasure to know you and to work with you. Best wishes and also best wishes to Marie!

**Comment by anisa-hawes** [comment]
Minutes of this Managing Editors' Meeting are available on our private Project and Business repository [12_2022_ManagingEditorsMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2022/Managing-Editors-Meetings/12_2022_ManagingEditorsMeeting.md).
