### ISSUE TITLE
Attributing translators more prominently on lessons

### ISSUE THREAD

**Issue by hawc2** [programminghistorian/jekyll#2771]
As a potential feature enhancement, I was wondering what others thought about changing how we credit 'translators' on lessons in the publication information. 

Currently, only authors are listed prominently under the title, while 'translators' are in listed in the banner below, mixed in with Editors and Reviewers. 

![Screenshot 2022-11-30 174340](https://user-images.githubusercontent.com/15621648/204924218-7c588ba4-a446-4842-b9c9-b08b97cb3305.png)

![Screenshot 2022-11-18 at 16 39 31](https://user-images.githubusercontent.com/15621648/204923530-a07ad18b-2f9e-4ee5-b40f-4fea46f210e5.png)

To properly attribute translation as authorship, ideally, the lesson title would be followed by the name of original author(s) and then by the translator(s), all of which would appear before the lesson description. Then only the Editors and Reviewers would be listed in the banner below. 

What would that change require technically, and is it worth considering?

**Comment by anisa-hawes** [comment]
Hello @hawc2. Thank you for raising this idea. 

Zoe and Adam met earlier this week, and agreed that we would pause any further tweaks or development to the website, as we shape plans for our new technical infrastructure. 

I'll add this idea (and any others that come up) to the [enhancements // user needs](https://github.com/orgs/programminghistorian/projects/2) Project Board I created so we can keep a record of things to consider for implementation in the future.

**Comment by acrymble** [comment]
I'm interested what @programminghistorian/spanish-team @programminghistorian/french-team @programminghistorian/portuguese-team think, as they have more experience in this area.

**Comment by DanielAlvesLABDH** [comment]
Hi to all. Thanks to Alex for sharing the thoughts, although that as not being an issue that we have discussed in the PT team. I would be in favour of given more visibility to translators work, but they are already mentioned not only in the banner but also in the citation of the lesson. There is an intellectual job connected with the translation but personally I would prefer to keep the reference in the top only to the original authors. But again, this is a personal position, not discussed inside the team.

**Comment by josircg** [comment]
I agree with Daniel. The author's name should be the only highlights.

**Comment by spapastamkou** [comment]
Hey there. From random discussions we had now and then I think we tend to agree in the FR team that there is a co-construction of the contents by all the contributors. I don't think I can personally stress enough how true this is specifically for the translations. We have been receiving in FR (and I believe this should be the case in other teams as well) translations of very unequal quality: they could range from very good to mediocre or even sometimes not that good or even unfinished. Sometimes the translators do not fully participate to the process, after submitting the translation (for reasons that may vary). For the very good translations, the evaluations and a decent editorial work suffice to publish a translated lesson of good quality. For all the other categories, it is the work of the editor and the quality of the reviews that will make the difference. When the editorial work (or the reviews) is not done as it should, then this reflects on the result. So putting the name of the translator in evidence: some may worth it but in some cases this would be unjust for all the other contributors that guaranteed the decent result.

**Comment by anisa-hawes** [comment]
One option would be adding in an About the Translators section in lesson end-matter to follow About the Authors.

![Screenshot 2022-12-07 at 17 51 00](https://user-images.githubusercontent.com/87070441/206257576-4cdfa368-663e-4fc3-89ec-98d7ad140fb6.png)

Translators' names are already included in our Suggested Citations, which is great.

**Comment by DanielAlvesLABDH** [comment]
But for that we would have to include information about the translators in the same or similar place where we keep information on authors, right?

**Comment by anisa-hawes** [comment]
If I understand correctly (?), we already add translators' bios to `ph_authors.yml` but this information doesn't display at the moment.

Creating an About the Translators section, would involve creating a new .html page (called something like `translator-info.html`) to function in the same way that `author-info.html` does at the moment. We'd need to make an addition to `_layouts/lesson.html` so that it is included.

<https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/author-info.html>

**Comment by DanielAlvesLABDH** [comment]
Thank you Anisa. I don't remember to have included bios about the translators to ph_authors, at least for the PT team. And again, I think we already give the correct highlight to their collaboration.

**Comment by hawc2** [comment]
Just to clarify, my concern about the current banner at the top of each
lesson is primarily that we put the Translators mixed in with Editors and
Reviewers. I agree Translators shouldn't be as prominently listed as
Authors, but I do think of Authors/Translators as on one side of publishing
process, and Editors/Reviewers on the other side.

Separating Translators from Editors/Reviewers visually on the PH website
would hopefully make Translator credit stand out more clearly for readers
as a secondary, if derivative form of authorship, and it might make it more
obvious to readers who are skimming that they are reading a translation
rather than the original.

**Comment by acrymble** [comment]
@hawc2 that sounds reasonable to me. It's a technical development though, which we've agreed to pause while we evaluate our new infrastructure choices. Should we add this to the to-do list?

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. It's already on [the enhancements // user needs](https://github.com/orgs/programminghistorian/projects/2) to-do list.

**Comment by DanielAlvesLABDH** [comment]
Hi @hawc2 that seems a good idea, to introduce a more clear separation between editor/reviewers on on side and translators on the other side on the top banner. With that I could agree

**Comment by acrymble** [comment]
I think we can close this @anisa-hawes if we've captured the idea for future dev?

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. Yes, I have noted this in the [enhancements // user needs project board](https://github.com/orgs/programminghistorian/projects/2).
