### ISSUE TITLE
Board of Trustees Meeting: Monday 16th January 2023

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2778]
Board of Trustees Meeting: Monday 16th January 2023 at [16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230116T160000&p1=64&p2=232&p3=1440&p4=136&p5=195)
--

Date: 16th January 2023
Time: [16:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230116T160000&p1=64&p2=232&p3=1440&p4=136&p5=195)
Webex link: See email from @spapastamkou or [here](https://unilu.webex.com/unilu/j.php?MTID=ma3ed134a3af6be5c8c0aa929c46dbc3b) 
Chair: @acrymble
Secretary: @spapastamkou 
Members: @amsichani @drjwbaker @rivaquiroga @spapastamkou @ZoeLeBlanc @JMParr 
Minutes of the last meeting: [BoT-17-11-2022.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/BoT-17-11-2022.md)
Possible collaboration with Ranke.2: [working document](https://demo.hedgedoc.org/s/oCkKvV41V)

---

Hello all,

**I'm creating this issue on behalf of @spapastamkou who has requested a BoT meeting** to discuss an opportunity for PH to collaborate with [Ranke.2](https://ranke2.uni.lu/). We'll also take this opportunity to consider our [Offering to Gold IPPs](https://github.com/programminghistorian/jekyll/issues/2751)

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf),  I'd like to ask that new agenda Items are added **in advance of the meeting** so that all attendees have sufficient time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions.  

### Agenda

- 1. Apologies 
- 2. {attended by Andreas Fickers, Daniel Guido and Stefan Krebs} Opportunity to collaborate with [Ranke.2](https://ranke2.uni.lu/) (@spapastamkou) [working document](https://demo.hedgedoc.org/s/oCkKvV41V)
- 3. {Trustees only} Approval of [Minutes from last meeting](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2022/11-2022/BoT-17-11-2022.md) & actions status.
- 4. {Trustees only} ProgHist Directors administration (e.g., changes of address)
- 5. {Trustees only} 2023 IPP ratesl and offering to Gold IPPs (see Issue #2751) @drjwbaker 
- 6. Any Other Business

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by spapastamkou** [comment]
Thanks @anisa-hawes for opening the issue and for sending the invite. The date is however the 16th January. There is already a [webex link](https://unilu.webex.com/unilu/j.php?MTID=ma3ed134a3af6be5c8c0aa929c46dbc3b) and I just sent you an invite via mail.

**Comment by anisa-hawes** [comment]
Okay. Thank you for letting me know, @spapastamkou. I'm afraid I can't make it on that day to support the meeting by taking minutes.

**Comment by spapastamkou** [comment]
I am sorry you won't be there but I understand. I'll keep the notes for the minutes, no problem! For the record, Andreas Fickers, Daniel Guido and Stefan Krebs for the C²DH should attend as well.

**Comment by drjwbaker** [comment]
@anisa-hawes : I can note take on this one. What I also suggest is that we deal with the Ranke2 discussion first (as that is the purpose of this sepecial meeting), then move to normal business thereafter.

**Comment by drjwbaker** [comment]
(I've edited the agenda to reflect that)

**Comment by spapastamkou** [comment]
thanks @drjwbaker

**Comment by spapastamkou** [comment]
@anisa-hawes I know you don work today and so this is reminder that I will do some notetaking for the minutes of the meeting, (and probably JB as well).

**Comment by amsichani** [comment]
Apologies for missing this, I got confused - did a BoD meeting happened after the Ranke meeting? I 'd like to ask to send an email with date & link to all members of BoD well in advance so we can secure a BoD slot in our calendars. More than happy to read the minutes @spapastamkou once they are ready and apologies again.

**Comment by spapastamkou** [comment]
This was the Ranke meeting and the latest BoT to date:) We work on the
minutes and Anisa will send them when ready.

**Comment by anisa-hawes** [comment]
Minutes of this Board of Trustees Meeting are available on our private Project and Business repository [BoT-16-01-2023.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/BoT-16-01-2023.md). With thanks to @spapastamkou for preparing these.
