### ISSUE TITLE
Web / Document Accessibility training

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2779]
Since we do a lot of public-facing content creation, it's important that we know how to follow best practices for accessibility. This is especially important for @GeeAlmeida given her role. I'm opening this ticket to put together a list of training options around marketing / web accessibility.

I welcome ideas from @programminghistorian/project-team if anyone knows of training that might be appropriate. So far I have found:

- Web Accessibility for Product and Marketing Teams - six free 30-minute sessions: https://www.levelaccess.com/resources/web-accessibility-training-product-and-marketing/ which seems to cover lots of useful design ideas.

- Abilitynet.org has paid training (£99-149) on topics such as accessible social media, creating accessible documents and presentations, and how to begin your own accessibility testing. https://abilitynet.org.uk/training

I was also hoping to find one for hosting accessible webinars, but haven't yet found any.

Once we have a few more options, I'll speak to @GeeAlmeida about a training plan in this area, and we can then close the ticket. I hope to have this done by mid January 2023.

**Comment by hawc2** [comment]
@acrymble I'll ask around - it's a good question. This is a reliable and useful resource put together for the Digital Library Federation's conferences: https://wiki.diglib.org/Creating_Accessible_and_Interactive_Online_Presentations

**Comment by anisa-hawes** [comment]
The following might be useful: 

Accessible webinars – making online work for everyone: https://accessibility.jiscinvolve.org/wp/2016/09/12/webinars/
Accessibility, assistive technology and inclusive practice: https://accessibility.jiscinvolve.org/wp/

**Comment by acrymble** [comment]
I've come across some more useful guidance on accessible design:

A poster on how design decisions affect various disabilities: https://github.com/UKHomeOffice/posters/blob/master/accessibility/dos-donts/posters_en-UK/accessibility-posters-set.pdf 

Web Design for dyslexia, simple guidance: https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide

**Comment by GeeAlmeida** [comment]
Hey everyone, thank you for all the suggestions. I have started to make my way through these resources today.

**Comment by GeeAlmeida** [comment]
PRINT
levelaccess.com - started the watching the webinars (4/1) registered and started the courses (11/01)
abilitynet.org.uk - maybe attend Accessibility for Content Creators (?) - when not on a Thursday
https://github.com/UKHomeOffice/posters/blob/master/accessibility/dos-donts/posters_en-UK/accessibility-posters-set.pdf - comprehensive, though not really explaining much
https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide - seems interesting


HOSTING EVENTS
https://wiki.diglib.org/Creating_Accessible_and_Interactive_Online_Presentations - wealth of information
https://accessibility.jiscinvolve.org/wp/2016/09/12/webinars/ - interesting list of common issues during sessions
https://accessibility.jiscinvolve.org/wp/ - doesn't seem to be relevant

**Comment by hawc2** [comment]
I asked the listserv for Digital Accessibility at the Digital Library Federation, and people chimed in with lots of helpful resources on this topic. I've had to recopy all these links so it's a little messy, less detailed. 

Not all of these are free. Multiple people recommended courses on Library Juice Academy, including by Stephanie Rosen and [Carli Spina](https://libraryjuiceacademy.com/shop/course/162-web-accessibility-techniques-for-design-and-testing/):

https://www.oercommons.org/hubs/CAST
https://www.cast.org/products-services/resources
https://webaim.org/services/training/
https://webaim.org/projects/screenreadersurvey9/
https://webaim.org/techniques/screenreader/
https://www.deque.com/resources/
https://accessibilityinsights.io/ - a nice testing tool many people like, including those who are newer to web accessibility work.
https://www.accessible-social.com/ - a resource that goes into quite a bit of detail about making social media, and online content more broadly, accessible. 
https://alistapart.com/article/color-accessibility-work
flows/  - an basic introduction if color is an issue you are particularly working on, such as if your platform has color graphics or data visualizations (there are other more detailed resources on accessible data visualizations if that is an area of focus for your work).
https://journals.ala.org/index.php/ltr/issue/view/791
https://open.ubc.ca/oer-accessibility-toolkit/
[RGD_AccessAbility_Handbook1.pdf](https://github.com/programminghistorian/jekyll/files/10447153/RGD_AccessAbility_Handbook1.pdf)

**Comment by acrymble** [comment]
Thanks @hawc2.

@GeeAlmeida I think it would be useful for us to save a list of these resources for future reference. I'm sure we will need to refer to it in future. Would you and @anisa-hawes decide on a logic place to store this reference? Maybe the Wiki or maybe you have another idea.

Then you and I can talk about any training you'd value most in this area at our next meeting.

Once you have that reference list finish, I think we can close this issue with thanks to everyone's input.

**Comment by GeeAlmeida** [comment]
UCL has quite clear and concise information/guidelines on the accessibility of learning resources:

Ensure:

- Layout is clear, with good spacing, including text that isn’t cramped or dense. Navigation is consistent.
- Fonts are sans serif and large enough to read (minimum 11pt).
- Colour text has high contrast against backgrounds. Avoid red, green and pink text.
- Links are descriptive (avoiding 'click here') and open in the same window. Where there is heavy dependence on images, there is also a text description of the key points, for screen-reader users (e.g. [alongside the image, as a caption, or as ‘alternative text]

More info (use of colour, social media etc.):
https://www.ucl.ac.uk/isd/services/accessibility-disability-it/digital-accessibility-hub/digital-accessibility-resources-and-0

**Comment by anisa-hawes** [comment]
I've created a Wiki page [Achieving Accessibility: Training Options](https://github.com/programminghistorian/jekyll/wiki/Achieving-Accessibility:-Training-Options) which gathers these resources together. Please add new links to resources as you find them.

**Comment by jenniferisasi** [comment]
Fab, @anisa-hawes! Thanks for putting all these great resources in a Wiki for the entire team future reference.
