### ISSUE TITLE
Adding to the blog

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2784]
@anisa-hawes 

I'd like to ake a blog post containing the end-of-year information I've been sharing on Twitter.

I haven't yet used the blog - can you tell me how to do it?

**Comment by anisa-hawes** [comment]
Yes! Of course, I'd be happy to help @GeeAlmeida.

Start by creating a new branch (in the same way you do when you are staging any updates to the website) called `Issue-2784'.

New blog posts are prepared by creating a new .md file within [/gh-pages/_posts](https://github.com/programminghistorian/jekyll/tree/gh-pages/_posts).

At the upper right of that page, select Add file > Create new file.

Give your file a name, following this format exactly: `YYYY-MM-DD-title-of-your-blogpost.md`

Paste in the following YAML information as a header, including the `---` above and below. This provides the information needed for the post to display.

```
---
title: Title of Your Blogpost
authors: 
- Gisele Almeida
layout: post
categories: posts 
---
```

If you want to include an image in your post, upload the image as a .png to [/images/blog](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/blog).

We use .html syntax to instruct the file to display the image. You'll need to follow this template:

```
<p><figure><img src="/images/blog/your-image-file-name.png" alt="Visual description of image"/><figcaption>Image caption to display</figcaption> </figure></p> 
```

Finish by generating a Pull Request and reviewing the Netlify Preview to check everything looks as you want it to. When you're ready, tag me as a reviewer. 

But let me know if I can help with anything along the way!

**Comment by acrymble** [comment]
There is some (sparse) instruction for this on the Wiki: https://github.com/programminghistorian/jekyll/wiki/Creating-Blog-Posts

**Comment by GeeAlmeida** [comment]
@anisa-hawes I won't be able to finish today, but will come back to it next Wed!

Thanks for the instructions :)
