### ISSUE TITLE
Publish a call for application for new editors for the French team

### ISSUE THREAD

**Issue by marie-flesch** [programminghistorian/jekyll#2789]
I am preparing to publish an advertisement for a new French Editor on the Vacancies / Vacantes / Postes vacants / Vagas pages of our website. I'm updating the following pages: en/vacancies fr/postes-vacants es/vacantes pt/vagas pages

**Comment by anisa-hawes** [comment]
Thank you, @marie-flesch, @spapastamkou and @matgille for collaborating to prepare this call for applications!

Let's liaise with @GeeAlmeida next week to prepare some Tweets + Mastodon posts in French to be scheduled for posting during the festive break!
