### ISSUE TITLE
Make it easier for reviewers to reference particular lines

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#279]
See discussion here: https://github.com/programminghistorian/ph-submissions/issues/29#issuecomment-241490054

**Comment by wcaleb** [comment]
Over at the submissions site, I made [this change](https://github.com/programminghistorian/ph-submissions/commit/787953659df1a8c7f3ce2a041a06583b5e8b4791), which will display a grayish number to the left of each paragraph on the live previews for lessons. It's not perfect and doesn't display exactly right on lists, but it might do what we need it to. Discuss at #291?

**Comment by ianmilligan1** [comment]
From @sgsinclair over in the HTRC issue:

> Fancy numbering! Out of curiosity, is there a reason why headers don't get numbers? (I'm just thinking of how reviewers may want to refer to those as well.)

My sense is it's a technical limitation, but I thought @wcaleb would be best positioned to answer?

**Comment by wcaleb** [comment]
I think it could conceivably be done with some adjustment to the CSS, though I'm not sure that paragraphs and headers can be included in the same "counter." But since headers are usually short and have hyper-references, I would think it wouldn't be hard for reviewers to spell them out or link directly to them?
