### ISSUE TITLE
Fix broken link on our Supporters pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2798]
I am opening this Issue because a link that features across en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores has broken. 

The link in question is to the Fundação para a Ciência e Tecnologia, special programme Verão com Ciência 2021,
<https://www.fct.pt/apoios/veraocomciencia/index.phtml.pt>

We could replace the link with this one: <https://www.fct.pt/media/noticias/a-iniciativa-verao-com-ciencia-da-fct-financia-418-bolsas-de-iniciacao-a-investigacao/> which is a news item about the various fellowships funded through this initiative.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes you can use this one (https://www.uevora.pt/investigar/projetos?id=5261). Is the news from our research center

**Comment by anisa-hawes** [comment]
Perfect. Thank you, @DanielAlvesLABDH!
