### ISSUE TITLE
python 3 update

### ISSUE THREAD

**Issue by jjon** [programminghistorian/jekyll#2802]
@anisa-hawes, It only recently came to my attention that, thanks to your energy and industry, the tutorial that I authored long ago https://programminghistorian.org/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file was updated in Oct. of 2020 to be consistent with python 3. Many thanks for your attention to these details. The revisions were minimal and appropriate except in one particular case. In your commit message you point out that you
```
# lines 162-182
# replaced code block with script written in Python3. This script uses `numpy` and has been modified to reduce the return distance to the distance between two strings.
```
The function that you used to replace the one (python2.7) that I had originally used, is in many ways a better and more instructive example; however, there is no explanation or instruction in my text concerning what `NumPy` is, how to install it, or how to import it. Moreover, all that overhead is unnecessary. In your replacement function, the only thing that `NumPy` does is create a matrix of zeros. If I'm not mistaken, this could be done very simply with a list comprehension. Below, I have revised the function you used in order to obviate the need for `NumPy`:
```python
def lev_revised(seq1, seq2):
    """ The only reason `NumPy` is used in this function is to create the appropriate matrix of zeros.
    If you have `NumPy` and are accustomed to its use, well and good, but this is unlikely to be true of
    the reader of this lesson; moreover, there's really no need for it in this context. We can avoid the
    overhead of the install and import of that module by simply replacing this line:
    `distance = np.zeros((rows,cols),dtype = int)` with this line:
    `distance = [[0]*cols for x in range(rows)]`
    """
    # Initialize matrix of zeros
    rows = len(seq1)+1
    cols = len(seq2)+1
    distance = [[0]*cols for x in range(rows)] # numpy not needed for this

    # Populate matrix of zeros with the indices of each character of both strings
    for i in range(1, rows):
        for k in range(1,cols):
            distance[i][0] = i
            distance[0][k] = k

    # Iterate over the matrix to compute the cost of deletions,insertions and/or substitutions
    for col in range(1, cols):
        for row in range(1, rows):
            if seq1[row-1] == seq2[col-1]:
                cost = 0 # If the characters are the same in the two strings in a given position [i,j] then the cost is 0
            else:
                # In order to align the results with those of the Python Levenshtein package, if we choose to calculate the ratio
                # the cost of a substitution is 2. If we calculate just distance, then the cost of a substitution is 1.
                cost = 1
            distance[row][col] = min(distance[row-1][col] + 1,      # Cost of deletions
                                 distance[row][col-1] + 1,          # Cost of insertions
                                 distance[row-1][col-1] + cost)     # Cost of substitutions

    return distance[row][col]


print(lev_revised("numpy","NumPy")) # returns 2
```

A good deal has changed at PH and I'm quite out of the loop. With your guidance I suppose I could figure out how to update my fork and issue a pull request, or, if you think my suggestion worthwhile, perhaps you could change that single line yourself? (and perhaps also the trivial typo on line 246: doubled h in the URL).

Please let me know what you think at your convenience.

Jon Crump (@jjon)

**Comment by anisa-hawes** [comment]
Dear @jjon,

Thank you for getting in touch, and for these kind words! Although I committed those changes, I cannot take credit for writing this code: that was the work of a brilliant colleague Jairo Antonio Melo Flórez @jairomelo. 

I'm very happy to apply the update you suggest above, and to correct the small typing error you've identified in the English version of this lesson. Indeed, the simplest workflow is for me to make that change on your behalf. Forks of our repository inevitably fall many commits behind our master branch because we update our website so frequently.

I've initiated a Pull Request, and you can see [the changes I've made in the rich diff view](https://github.com/programminghistorian/jekyll/pull/2804/files).

Best,
Anisa
