### ISSUE TITLE
Designing a course for FSCI's FORCE11

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2803]
Hi @programminghistorian/project-team 

Scholarly Communication Institute (FSCI) has an open call for course proposals for its 2023 summer school, which will focus on "The Future of Research Communications and e-Scholarship." 

This is a good opportunity to collaborate! Would anyone be interested in putting a proposal together?

Submission Deadline: Monday, January 16, 2023

Summer school dates: Monday 31 July - Friday 04 August / Courses Span Tuesday 01 through Thursday 03 August

Course Specifications: 
Remote course conducted via Zoom Preferably team-taught
3-9 hours in duration, over 3 consecutive days
Can specify whether Morning or Afternoon (Pacific Time) time slot is preferred
Interactive, real-time components + asynchronous content
Provide students with reference materials
Courses on a wide range of Scholarly Communication topics will be considered.
For reference, list of the FSCI 2022 courses with abstracts:
https://force11.org/fsci/post/course-list-with-abstracts-2022/

Instructors will receive free FSCI 2023 registration.
![image](https://user-images.githubusercontent.com/109232661/209327029-202f477a-a7ca-4bc1-9d58-0243cc2d431d.png)

Thank you @JMParr for sending this in!

**Comment by GeeAlmeida** [comment]
@jenniferisasi I saw that you delivered a course in 2022. Would you mind to comment if you think this is worthwhile for PH? What was your experience like?

**Comment by jenniferisasi** [comment]
Certainly, @GeeAlmeida, this could be somewhat useful for PH with the right angle. Attendants are librarians, communication professionals, and instructors of Higher Ed. I really enjoyed chatting with folks outside my usual context as they were not only learning from what Gimena del Rio Riande and I were talking about, but sharing their own experiences.

**Comment by GeeAlmeida** [comment]
I am going to close this issue, as the deadline for this has passed.
