### ISSUE TITLE
Applying Perma.cc links to newly published ES lesson

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2806]
Happy New Year, @rivaquiroga!

Today is my first day back at work. I'm going to add perma.cc links into your newly published lesson: [Introducción al web scraping usando R](https://programminghistorian.org/es/lecciones/introduccion-al-web-scraping-usando-r) ✨

**Comment by rivaquiroga** [comment]
Hi, @anisa-hawes! Thanks! In this particular case, not all links should be archived. Perma links are not scrapable, so the ones that people need to scrape should remain as is. Tomorrow I can let you know which links are those.
