### ISSUE TITLE
accents in avatars

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#281]
I've added the avatars for the new Spanish team and put them on the project team page, but those with accents (Víctor Gayol) or hyphens (Maria José Afanador-Llach) have both failed to display. @wcaleb can you advise?

**Comment by acrymble** [comment]
Avatars are here: https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars

**Comment by wcaleb** [comment]
The problem is the accented characters, not the hyphens. Will have to 
think about a work-around for this, as our YAML directory is set up so 
that entries are "looked up" by name. In the meantime, I've hard-coded 
those sections in the Project Team while I think about a work-around or 
revamping of our system that can cover cases like this.

**Comment by vgayolrs** [comment]
Accented characters on PH web displays ok on my browser today. I don't know how do you fixed it. And I don't know exactly how do you create the website. But to solve further problems there are two options. 1) modify the css style sheet with the line: "meta http-equiv="Content-Type" content="text/html; charset=utf-8" before "head": 2) ask editors to send text in plain text with accents like: "V&iacutector" (Víctor). Both will display correctly.

**Comment by acrymble** [comment]
Thanks @vgayolrs, I think the problem is with the way github pages works. We're using utf-8 already, and I tried your HTML code solution, but it didn't work. You can take a look at the way the site is put together by looking at the code behind the project team page:

https://github.com/programminghistorian/jekyll/blob/gh-pages/project-team.md

It draws together the following:

https://github.com/programminghistorian/jekyll/tree/gh-pages/avatars
https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/authors.yml

**Comment by ianmilligan1** [comment]
@wcaleb I saw that the hard-coded sections in the [Project Team](http://programminghistorian.org/project-team) page had blown up the markdown code that followed. I switched it over to HTML in a94f80149f372a17ac1fc6e35c5648637a3f58c3 until the accent issue is all resolved.

**Comment by wcaleb** [comment]
@ianmilligan1 Thanks for catching that. The problem was just that I didn't close the `div` tags when inserting the HTML. Doing that in 7b3f1457852dd98b9036c91bf7a8006349304d5e appears to fix the problem.

**Comment by acrymble** [comment]
This is an old problem now, but hardcoding seems to suit given that it's a one-off issue. I'm closing this but re-open if needed.
