### ISSUE TITLE
Programme of events - a couple of ideas

### ISSUE THREAD

**Issue by GeeAlmeida** [programminghistorian/jekyll#2816]
I have two ideas to share here for events in the coming months. 

1) A very simple "How to use Programming Historian" session, which I could deliver in English, Spanish and Portuguese. This would be a trial run of the offer to IPPs.

Because the 'How to' is really very basic, I thought of starting off with a discussion on what is DH and some information on the different tools out there. This would be followed by a walkthough of the website.

2) An idea born out of exchanges with Jess is to offer Africa-based scholars a session within our calendar of events. This would be focused on increasing capacity in relation to DH and get people acquainted with PH.

**Comment by acrymble** [comment]
Love the 1 idea in particular. Is it aimed at end users (researchers) or supporters (librarians / teachers)?

Let's definitely develop this.

**Comment by GeeAlmeida** [comment]
@JMParr and I are in conversation with a scholar based in Uganda, with a view of putting together workshops for researchers based in Africa.
@programminghistorian/french-team @programminghistorian/english-team I wonder if anyone would be interested in joining the conversation at this early stage?

Of coure you can join in later on, but I just wonder who might have an interest in being part of this?

**Comment by GeeAlmeida** [comment]
Idea number one is also being developed. In conversation with Adam we have reached some questions that can be addressed in a session focused around the day-to-day work of humanities people, to help them think clearly about what digital methods can do for them:

- Why should I teach my history students about network analysis?
- Is stylometry the right method for the types of problems I'm trying to solve?
- As a museum professional, what are the 3 new technologies I could learn about to future proof my skillset?

**Comment by hawc2** [comment]
I'd be happy to join in. Thanks Gisele!

**Comment by GeeAlmeida** [comment]
I just want to inform everyone that Maria Jose (@mariajoafana) has secured funding to offer workshops in Spanish. The first one is next week (09 and 10/02).

This is the programme of events:

- Feb: Crear una exhibición digital mínima e interactiva con CollectionBuilder, Jeniffer Isasi 

- Febrero (?): Georeferenciación de mapas históricos con Map Warper, Miguel Cuadros y Anthony Picón 

- Marzo: Visualización de metadatos de colecciones de imágenes con ImagePlot, Joshua G. Ortiz 

- Abril: Introducción al marcado TEI, Nicolás Vaughan 


I will share the invitation materials and more details as the come in. @mariajoafana you might want to share the details and materials about the first event here, so the @programminghistorian/spanish-team can help promote it. @jenniferisasi I am not sure if Maria Jose will see this, but I think you will ;)

**Comment by jenniferisasi** [comment]
Hi @GeeAlmeida, of course I was going to read the message :) I don't have any of the promo materials yet either, but as soon as I get them I will send them to you. What I can share is that I am teaching at 12-1:30PM EST

**Comment by GeeAlmeida** [comment]
@jenniferisasi I will be concluding my working day soon and I am not back until Wed - the day of your first session. So my suggestion is that you share the materials here, with a call out to the Spanish team to help promote the workshop.

**Comment by jenniferisasi** [comment]
Will do @GeeAlmeida !

**Comment by acrymble** [comment]
Zotero is running events at supporting libraries to teach with Zotero. This is exactly what we need for ph https://www.zotero.org/support/webinars

**Comment by GeeAlmeida** [comment]
Hey everyone
Maria Jose has shared the details and promotion materials for the workshops she has organised. The first one is this Thursday. @programminghistorian/spanish-team can you all please help spread the word?
I have tweeted and posted on Mastodon. You can replicate those, or post your own version, as well as spread the information via email, word of mouth... 
The first workshop is Wed and Fri this week, at midday Bogotá time. The link for registrations is:
https://facartes.uniandes.edu.co/evento/taller-crear-una-exhibicion-digital-minima-e-interactiva-con-collectionbuilder/

I'll attach here an image you can use to promote the events:

 
![Talleres-PH-2023](https://user-images.githubusercontent.com/109232661/217193856-88429ee6-a130-4c4d-9287-aaac509599d7.png)

**Comment by GeeAlmeida** [comment]
@jenniferisasi FYI

**Comment by GeeAlmeida** [comment]
I want to share with you all that the first workshop in @mariajoafana Maria Jose's series had 260 people registered and @jenniferisasi  Jenn's first worshop on Wednesday had 138 people in attendance. Isn't that fabulous?

**Comment by GeeAlmeida** [comment]
I want to share with you all where things are headed with the second idea that started this thread - of a series of workshops  focused on increasing capacity among African DH researchers and students. This conversation is ongoing, @JMParr and @hawc2 are in conversation with colleagues in Edinburgh and Makerere University (Uganda). It looks as though the next step will be to launch a consultation with collagues in Africa to help shape the programme that will be offered.
The gist of what we have been discussing is available in [this document](https://docs.google.com/document/d/1-k63KqBdl9isMYvEVBCaJeAjCgqq7raa/edit?usp=sharing&ouid=112812042675572577011&rtpof=true&sd=true) - but do bear in mind that this is a work in process and as I said, a consultation will soon be carried out. This is just FYI.

**Comment by anisa-hawes** [comment]
Any events in planning by Gisele are now on hold while we find someone else who can organise those activities.

Noting here that I have written to those people who I know were involved in coordinating plans to arrange new support. 

Thank you.
