### ISSUE TITLE
Site - errors and inconsistencies between versions in different languages

### ISSUE THREAD

**Issue by ericbrasiln** [programminghistorian/jekyll#2834]
Errors found on [Editor guidelines](https://programminghistorian.org/en/editor-guidelines) page in all languages. There are inconsistencies between information and errors in internal links in markdown. I'll list the problems here and then fix them in a new branch (which will be linked to this issue).

- [x] In topic 5 of the Portuguese version "[Confirmar se todos os links e cabeçalhos YAML funcionam corretamente](https://programminghistorian.org/pt/directrizes-editor#5-confirmar-se-todos-os-links-e-cabe%C3%A7alhos-yaml-funcionam-corretamente)", there is an inconsistency with the English/Spanish/French version. In other languages, the information is that the “site will be automatically tested by Travis CI”. While in the Portuguese version, the information is that the site “will be automatically tested by GitHub Actions”. As we currently no longer use Travis CI in our workflow, I propose updating the information.
- [x] Still in this topic, there is an error that is present in the English version and is repeated in other languages: in the first unordered list of the topic, in the first item of the list, the link to “[You may skip the rest of this section.]( https://programminghistorian.org/en/guidelines-editor#11-thank-everyone-and-encourage-promotion)” is wrong. the correct one is: “[https://programminghistorian.org/en/editor-guidelines#6-inform-the-editor](https://programminghistorian.org/en/editor-guidelines#6-inform-the-editor)”.

**Comment by spapastamkou** [comment]
A good occasion to report a bug only for the EN version of the Author guidelines: the contents of the page in the beginning provide the following link (anchor): https://programminghistorian.org/en/author-guidelines#step-2-writing-a-new-lesson 
It does not work once we click on, as the good link is: https://programminghistorian.org/en/author-guidelines#step-2-writing-and-formatting-a-new-lesson 
There is no such problem on the FR page (+ ES and PT). If you open a PR I can replace it.

**Comment by ericbrasiln** [comment]
Thanks @spapastamkou 
I'll fix this link as well.

**Comment by spapastamkou** [comment]
thanx!
