### ISSUE TITLE
Installation issue on Windows: Building a static website with Jekyll and GitHub Pages

### ISSUE THREAD

**Issue by dlschwartz** [programminghistorian/jekyll#2837]
- Lesson: Building a static website with Jekyll and GitHub Pages
- Windows

Problem:
The instructions in the lesson under "[On Windows](https://programminghistorian.org/en/lessons/building-static-sites-with-jekyll-github-pages#on-windows-)" work fine up through 6. Several of the students I'm working with were unable to run 7. Instead they needed to follow these instructions from the [Jekyll website](https://jekyllrb.com/docs/installation/windows/).  After that they were able to return to the lesson and carry on.

Thanks for a great lesson! I've been using it for a few years and it's been a great skill to have for myself and teach to others.

**Comment by anisa-hawes** [comment]
Hello @dlschwartz. Thank you for getting in touch!

We will take a look, and make an adjustment if necessary.

Very best, 
Anisa

**Comment by anisa-hawes** [comment]
This is the same step reported as a problem in [#2462](https://github.com/programminghistorian/jekyll/issues/2462). I will therefore close this, and revisit that Issue to finalise a resolution.

Note to self: cross-referencing [#2836](https://github.com/programminghistorian/jekyll/issues/2836) which is a different problem but concerns the same lesson.
