### ISSUE TITLE
TF-IDF: deprecated code needs update

### ISSUE THREAD

**Issue by quinnanya** [programminghistorian/jekyll#2842]
In the final code block of [Analyzing Documents in TF-IDF](https://programminghistorian.org/en/lessons/analyzing-documents-with-tfidf), there's a line `tf_idf_tuples = list(zip(vectorizer.get_feature_names(), doc))`. 

I'm getting this warning and suggested fix for the deprecated function in scikit-learn:

`FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.`

Replacing `get_feature_names()` with `get_feature_names_out()` fixes the warning.

**Comment by anisa-hawes** [comment]
Many thanks, @quinnanya!

I really appreciate you identifying this, and taking the time to let us know. 

I've prepared the update to the EN original and FR translation in PR #2847.
