### ISSUE TITLE
It seems that the Twitter API will no longer have a free tier

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2848]
[It was announced today](https://twitter.com/TwitterDev/status/1621026986784337922
). Next week they’ll give the details. Not having a free tier affects the bot and some of the lessons we have published (and some translations that are currently in progress) :broken_heart: 

![Screenshot from 2023-02-02 12-15-14](https://user-images.githubusercontent.com/31421616/216365108-39494e5d-97e1-47b0-bb8b-9e294206fd85.png)

**Comment by rivaquiroga** [comment]
In the past they have changed their minds about some of their decisions. So let's hope this is the case :crossed_fingers:

**Comment by spapastamkou** [comment]
Thanks for opening the issue @rivaquiroga. Yes, Elon did it again, what a mess (this could be) :(

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. @jenniferisasi and I were just messaging each other about this on Slack! 

We think /en/lessons/beginners-guide-to-twitter-data _may_ still work, but we'd need to adjust [the second paragraph of the TweetSets section](https://programminghistorian.org/en/lessons/beginners-guide-to-twitter-data#tweetsets):

> You could, however, substitute any tool that gives you a set of dehydrated tweets. Because tweets can be correlated to so much data, it’s more efficient to distribute dehydrated data sets consisting of unique tweet IDs, and then allow users to “hydrate” the data, linking retweet counts, geolocation info, etc., to unique IDs. More importantly, [Twitter’s terms for providing downloaded content to third parties](https://developer.twitter.com/en/developer-terms/agreement-and-policy), as well as research ethics, are at play. Other common places to acquire dehydrated datasets include Stanford’s [SNAP](https://snap.stanford.edu/data/) collections, the [DocNow Project](https://www.docnow.io/catalog/) and data repositories, or the [Twitter Application Programming Interface (API)](https://developer.twitter.com/), directly. (If you wonder what an API is, please check this [lesson](https://programminghistorian.org/en/lessons/introduction-to-populating-a-website-with-api-data#what-is-application-programming-interface-api).) This latter option will require some coding, but Justin Littman, one of the creators of TweetSets, does a good job summarizing some of the higher-level ways of interacting with the API in this [post](https://gwu-libraries.github.io/sfm-ui/posts/2017-09-14-twitter-data).

**Comment by rivaquiroga** [comment]
I’m not sure it will still work. The dataset is downloadable, but it only includes the tweets’ IDs. People are expected to use the DocNow Hydrator to get the text of the tweet and other variables. And for that, the API is needed (check the second paragraph -after the image- in the [Hydrating section](https://programminghistorian.org/en/lessons/beginners-guide-to-twitter-data#hydrating )). :sob:

**Comment by anisa-hawes** [comment]
Oh dear... that's true, @rivaquiroga.

We can review this after the 9th (see what happens...). For now, I'm going to note down a list of the lessons I think will be affected. Please do add any others I may have missed.

- /en/lessons/beginners-guide-to-twitter-data

- /en/lessons/scalable-reading-of-structured-data
- /ph-submissions/issues/484 ES
- /ph-submissions/issues/534 PT
- /ph-submissions/issues/482 FR

- /en/lessons/json-and-jq

- /en/lessons/intro-to-twitterbots
- /fr/lecons/intro-aux-bots-twitter

- /en/lessons/creating-apis-with-python-and-flask

**Comment by spapastamkou** [comment]
When the going gets tough, the tough get going :-) I drop here a t[witter thread with alternatives](https://twitter.com/dfreelon/status/1622606612543291393), who knows, it might prove useful.

**Comment by anisa-hawes** [comment]
Catching up on the current status of access to Twitter's API, and I think our proposed organisational use will still be possible within the new Free Tier. There is a posting limit of 1,500 Tweets per month (~50 per day) but we do not post that frequently (no way near 😅). 

The notes which follow can be read on [this page](https://developer.twitter.com/en/products/twitter-api):   

**Free Tier**
For write-only use cases and testing the Twitter API

- Rate limited access to v2 tweet posting and media upload endpoints 
- 1,500 Tweets per month - posting limit at the app level
- 1 app ID
- Login with Twitter 
- Cost: Free

**Comment by anisa-hawes** [comment]
I understand this doesn't mean that [our lessons (listed above)](https://github.com/programminghistorian/jekyll/issues/2848#issuecomment-1415769340) are still operable.  

On that note, I'm less hopeful. [Shawn Graham posted on Mastodon recently](https://scholar.social/@electricarchaeo/110152012575008700) to say that Bots they built (which inspired the EN /en/lessons/intro-to-twitterbots and FR lesson /fr/lecons/intro-aux-bots-twitter) aren't working anymore... 

This case seems like a good candidate for a Lesson Maintenance project, to test all the lessons we think will be affected, and revise as many as possible, where possible.

**Comment by hawc2** [comment]
@anisa-hawes at this point it's probably fair to say Twitter won't be what it was, and at least a few of our lessons are gonna remain outdated. In the case of published English lessons on the Twitter API, at the very least we should add a note explaining API access has changed and elements of the lesson will no longer work. I don't know if we should Archive these lessons just yet, as they may still be useful for teaching related skills/questions. Happy to help make a case by case decision if you need my input

**Comment by anisa-hawes** [comment]
I've drafted text for an information/warning box to be applied to all the lessons [listed here](https://github.com/programminghistorian/jekyll/issues/2848#issuecomment-1415769340). 

I would be grateful for your views on this wording, and for your support to adjust my translations @jenniferisasi, @marie-flesch and @DanielAlvesLABDH. 

**EN**:
Access to Twitter’s API has recently changed. The Free Tier no longer allows users to search and download Twitter data. Unfortunately, this means that elements of this lesson will only work for those who are paying for an upgraded plan. At the moment, there are no special access plans for researchers or academics. 

**ES**:
El acceso a la API de Twitter ha cambiado recientemente. El nivel gratuito ya no permite a los usuarios buscar y descargar datos de Twitter. Lamentablemente, esto significa que algunos elementos de esta lección sólo funcionarán para quienes paguen por un plan mejorado. Por el momento, no existen planes de acceso especiales para investigadores o académicos.

**FR**:
L'accès à l'API de Twitter a récemment changé. Le niveau gratuit ne permet plus aux utilisateurs de rechercher et de télécharger des données Twitter. Malheureusement, cela signifie que les éléments de cette leçon ne fonctionneront que pour les personnes qui paient pour un plan amélioré. Pour l'instant, il n'existe pas de plan d'accès spécial pour les chercheurs ou les universitaires.

**PT**:
O acesso à API do Twitter foi alterado recentemente. O nível gratuito já não permite aos utilizadores pesquisar e transferir dados do Twitter. Infelizmente, isto significa que os elementos desta lição só funcionarão para quem estiver a pagar por um plano melhorado. De momento, não existem planos de acesso especiais para investigadores ou académicos.

-- 

Beyond this, I am putting together a proposal for a maintenance project in which someone is dedicated to working through each of these lessons to identify what still works / what doesn't / where the specific blockages / how detrimental the blockages are. I think this might be necessary to empower us to make case-by-case decisions on keeping lessons active (with fuller warning boxes or notes where needed) or (very sadly 😢 ) retiring them.

**Comment by DanielAlvesLABDH** [comment]
Dear @anisa-hawes the Portuguese version is fine. Thank you

**Comment by marie-flesch** [comment]
Hi Anisa, here it is! 

FR: 
L'accès à l'API de Twitter a récemment changé. Le niveau gratuit ne permet plus de rechercher et de télécharger les données de Twitter. Malheureusement, cela signifie que certains éléments de cette leçon ne fonctionneront que pour les personnes qui disposent d’un accès payant à l’API. Pour l'instant, il n'existe pas de plan d'accès spécial pour les chercheur·es ou les universitaires.

**Comment by jenniferisasi** [comment]
Thanks @anisa-hawes, I am only going to change a few words: 

ES:
El acceso a la API de Twitter ha cambiado recientemente. El nivel gratuito ya no permite a los usuarios buscar y descargar datos de Twitter. Lamentablemente, esto significa que algunos elementos de esta lección sólo funcionarán **para quienes paguen un plan de acceso a la API.**

**Comment by anisa-hawes** [comment]
PR #2985 applied warning box notes to the following lessons:

- /en/lessons/beginners-guide-to-twitter-data
- /en/lessons/scalable-reading-of-structured-data
- /en/lessons/json-and-jq
- /en/lessons/intro-to-twitterbots
- /fr/lecons/intro-aux-bots-twitter
- /en/lessons/creating-apis-with-python-and-flask

Meanwhile, I have applied equivalent notes to the following lessons in progress on ph-submissions:

- /es/borradores/traducciones/lectura-escalable-de-datos-estructurados <https://github.com/programminghistorian/ph-submissions/commit/8d9938cde3a754270936dec4cbe3e8e596b2a52d>
- /pt/esbocos/traducoes/leitura-escalavel-dados-estruturados <https://github.com/programminghistorian/ph-submissions/commit/e22e4f760adfecd7fd652f8a703e373e1adf667c>
- /fr/en-cours/traductions/lecture-multi-echelles-donnees-structurees <https://github.com/programminghistorian/ph-submissions/commit/4f4879996ece978b4c38afe305f088db7fd9715f>

**Comment by joanacvp** [comment]
Hello @anisa-hawes. The PT version according to the glossary: 

O acesso à API do Twitter foi alterado recentemente. O nível gratuito já não permite aos usuários pesquisar e transferir dados do Twitter. Infelizmente, isto significa que os elementos desta lição só funcionarão para quem estiver a pagar por um plano melhorado. De momento, não existem planos de acesso especiais para pesquisadores ou académicos.[2023]

**Comment by anisa-hawes** [comment]
Thank you, @joanacvp ! I've made these adjustments to /pt/esbocos/traducoes/leitura-escalavel-dados-estruturados https://github.com/programminghistorian/ph-submissions/commit/5d1e5cf27453fec636d8c9a6100b5e9b467d53bc
