### ISSUE TITLE
Query Strings Lesson - OBO site is broken

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#285]
Related to #284 the problem with the Query Strings lesson (http://programminghistorian.org/lessons/downloading-multiple-records-using-query-strings) is actually that the Old Bailey Online website crashed in August 2016 and as a result a number of URLs were changed temporarily and the advanced search features were disabled. While the Old Bailey Online team fix this, this lesson will not work properly.

I have temporarily put a warning at the top of the lesson and I'll contact the Old Bailey Online people to ask for an update.

**Comment by sharonhoward** [comment]
As you've already noted, the print.jsp links are broken and the advanced search is not available, but in addition the Calculate Total function is not working. I don't know right now when these things will be fixed, but I hope to have a better idea in the next week or so. 

NB: the Old Bailey API is also unavailable, which means that Vilja Hulden's 'Naive Bayesian' lesson won't be working either.

**Comment by acrymble** [comment]
Thanks @sharonhoward for the update and for the warning about the Naive Bayesian. Hopefully we can get a fix soon.

**Comment by acrymble** [comment]
I've added a warning also to the Hulden lesson. Thanks again @sharonhoward . Hopefully a fix soon. I will leave this ticket open until we're resolved.

**Comment by acrymble** [comment]
Just an update for the community: we're still keeping an eye on this, but from what we can tell the Old Bailey Website is still undergoing maintenance, so for the time being we must continue to wait.

Fingers crossed that they solve the problem soon.

**Comment by acrymble** [comment]
I think this should be fixable now as the Old Bailey site has returned (we hope permanently). I'll try to find some time to make any needed repairs.

**Comment by acrymble** [comment]
I've tried this but the advanced search still isn't available on the site. Wildcard (*) searching doesn't work, so the lesson still can't be used.

**Comment by acrymble** [comment]
It would be possible to re-write the lesson to use the Connected Histories website instead: http://www.connectedhistories.org/Search_results.aspx?dtf=1700-01-01&dtt=1750-12-31&kw=mulatto*+negro*&sr=ob

The core skills are the same, and so is the data. It just uses a different way in. I might try that instead, but I'll have to find a day to do it.

**Comment by acrymble** [comment]
I got an email today that this might now be working. I just need to try it out to see. Thanks @sharonhoward

**Comment by acrymble** [comment]
Note of changes required:

~~ln 132-158: the url on the new site is now https://www.oldbaileyonline.org/search.jsp?gen=1&form=searchHomePage&_divs_fulltext=mulatto*+negro*&kwparse=advanced&_divs_div0Type_div1Type=sessionsPaper_trialAccount&fromYear=1700&fromMonth=00&toYear=1750&toMonth=99&start=0&count=0 . This involves a https instead of http, and the foo=bar has been replaced with gen=1, which will affect other lines as well. %7C is also now just an underscore. It should be: https://www.oldbaileyonline.org/search.jsp?gen=1&form=searchHomePage&_divs_fulltext=mulatto*+negro*&kwparse=advanced&_divs_div0Type_div1Type=sessionsPaper_trialAccount&fromYear=1700&fromMonth=00&toYear=1750&toMonth=99&start=0&count=0 . This also affects lns 141-152, and 158 comment about foo=bar.~~

~~ln 246-248 - same as above. Just swap new URL.~~

~~ln 255-281 - same as above. Update for new URL.~~

~~ln 437-475 - same as above. Update for new URL.~~

~~ln 538-581 - same as above. Update for new URL.~~

~~ln 624-669 - same as above. Update for new URL.~~

ln 713 - this link no longer works. Works if search parameters are left off the end of the URL. Need to investigate. Think highlighting has been disabled, which might be the issue.

ln 716-728 - i'm not sure this is correct anymore because they've changed some of the bits of the URL. Need to get to this point with working code and check from there. There are code blocks further down that need revising due to URL issue noted above.

**Comment by acrymble** [comment]
This lesson has been fixed. Thanks @sharonhoward for alerting me to the updates on the Old Bailey site.
