### ISSUE TITLE
email address for contact?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#286]
I just noticed that @fredgibbs is still listed as the contact on the 'Feedback' page (http://programminghistorian.org/feedback). @ianmilligan1 has been the contact for a year, I believe. So we obviously missed this one. To solve this in future I'd like to suggest we set up a editors@programminghistorian.org email. This will involve contacting CHNM and routing it through Gmail I would imagine. I think it also looks more official and helps us keep our various lives (emails) separate.

Anyone object to this or to my suggested email address? I'll do it if not.

**Comment by ianmilligan1** [comment]
I dunno, I gotta admit - having a personalized contact probably lowers the barrier slightly. You're actually corresponding with Person X at Institution Y, rather than impersonal e-mail.

**Comment by acrymble** [comment]
If that's the concensus I'm ok with that. We're just talking about doubling the number of pages with these contact details though ( #280 ). So I thought this might be easier.

**Comment by ianmilligan1** [comment]
Next time I should just do a Find + Replace/All throughout, when @jerielizabeth takes over in Sept/Oct (Oct 1st?).

**Comment by wcaleb** [comment]
We talked about this on the last Skype call ... but can't remember what we decided. I think there was broad support for a generic email address, but willing to be corrected!

**Comment by ianmilligan1** [comment]
Ah I missed the last call as I was on vacation, so that may explain all. 😀

**Comment by acrymble** [comment]
If I put my honest hat on, I'm not so sure there was broad support. So we can leave this if that's the preference.

**Comment by fredgibbs** [comment]
Just wanted to make official my support for a personal email address rather than a generic one. I think it's more welcoming, which is very important. Also, having a custom email account gives us yet another thing to manage (and maybe someone else to manage as domain owner).
