### ISSUE TITLE
Remove remains of python-warning 

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#2866]
In PR #2861 the FR team bumped into remains of the python_warning (please see https://github.com/programminghistorian/jekyll/issues/520 for past context) in the yaml metadata. The relevant field was removed from the FR file, and also from the ES file in this occasion. Perhaps there are more sleeping beauties here and there - or could appear in the future as more lessons are translated - and overall it might be wiser to remove the cores of the warning (so it would be easier to catch yaml metadata in the lesson files since they would not work or I suppose so).

I think there are at least two files concerned: ` /_layouts/lesson.html` and `/_data/snippets.yml` and I copied the relevant lines for each in the attached doc. Please take note of this @ZoeLeBlanc and @jenniferisasi and check if there are more files concerned as you know better this part compared to me. I do not tag Anisa because she is away but she will surely be familiar with the issue after she returns. 

Fyi @marie-flesch and @matgille (to better understand what was going on).  

[python-warning-remains.txt](https://github.com/programminghistorian/jekyll/files/10787094/python-warning-remains.txt)

**Comment by spapastamkou** [comment]
(I did not assign myself as I am currently on sabbatical but I can lend a hand if necessary - just need to be tagged bcz otherwise my notifications are off).

**Comment by acrymble** [comment]
@spapastamkou I believe this is something Anisa would have the skills to do. She's improved her jekyll skills quite a lot in the past year.

**Comment by ZoeLeBlanc** [comment]
Thanks for flagging this @spapastamkou ! I'm a little confused about the issue though. Is it that the Python warning is showing up when it isn't supposed to? Or is something else going on? Happy to wait for Anisa's return but also happy to tackle this since it seems like maybe a small issue.

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou.

Within `/_layouts/lesson.html`, we can remove the following `if` statement:

```
  {% if page.python_warning %}
  <div class="alert alert-warning">
    {{ site.data.snippets.python-warning[page.lang] | markdownify }}
  </div>
  {% endif %}
```

Within `_data/snippets.yml` we can remove the following lines:

```
python-warning:
  en: |
    This lesson was written using Python v. 2.x. Code may not be compatible with newer versions of Python. "[Python Introduction and Installation](/lessons/introduction-and-installation)" provides instructions for how you can install Python 2.x alongside newer versions.
  es: |
    Esta lección ha sido escrita utilizando Python v. 2.x. Es posible que el código no sea compatible con nuevas versiones de Python. "[Introducción a Python e instalación](/es/lecciones/introduccion-e-instalacion)" contiene una panorámica sobre cómo instalar Python 2.x y versiones posteriores.
  fr: |
    Cette leçon a été écrite en utilisant Python v. 2.x. Le code peut ne pas être compatible avec les versions les plus récentes de Python. Merci de consulter la leçon "[Python Introduction and Installation](/en/lessons/introduction-and-installation)" (en anglais) qui fournit des instructions pour installer Python 2.x en plus des versions plus récentes.
  pt: |
     Esta lição foi escrita usando o Python v. 2.x. O código pode não ser compatível com as versões mais recentes do Python. "[Introdução ao Python e instalação](/pt/licoes/introdução-e-instalacao)" fornece instruções sobre como instalar o Python 2.x, tal como versões mais recentes.
```

Dear @ZoeLeBlanc,

This cropped up with a recent FR translation of an early Python lesson, and I had missed this when I checked the YAML. 
The translator copy-pasted the original lesson's YAML from ph-submissions rather than from the live version in Jekyll, so that field was erroneously included.

I'll prepare the PR now. It is a very simple fix.
