### ISSUE TITLE
Exploring and Analyzing Network Data with Python - new major code release

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#2867]
## If you are reporting a problem with a lesson, please try to provide us with the following information:  

- Exploring and Analyzing Network Data with Python by @jrladd and others.
- Using Mac & Python 3.x

The tutorial was published in 2017 and advised using Networkx version 2.4. The Networkx module's latest stable release is 3.0, and from my experience working with students in the classroom, they tend to install the latest version of software, not necessarily the version used in the tutorial.  In this case, that would cause an error because one of the functions used in the tutorial was deprecated in version 3.0.

` print(nx.info(G)) `

I've checked the Networkx notes and .info was deprecated in the move from networkx 2x to 3x. (“Remove deprecated function nx.info (#5759)”) - https://networkx.org/documentation/stable/release/release_3.0.html. I haven’t been able to find a replacement, nor details of why it was deprecated. Just that it was. This means the brief example following that line of code can’t be replicated if using 3.x or newer.

To future-proof this lesson, my recommendation is to advise downloading the latest version of networkx in the "Data Prep and NetworkX Installation" section (instead of specifying 2.4). This is in line with our sustainability practices.

Then simply removing the section: 

` Finally, you can get basic information about your newly-created network using the info function:

print(nx.info(G))

The info function gives five items as output: the name of your graph (which will be blank in our case), its type, the number of nodes, the number of edges, and the average degree[4](https://programminghistorian.org/en/lessons/exploring-and-analyzing-network-data-with-python#fn:averagedegree) in the network. The output should look like this:

Name:
Type: Graph
Number of nodes: 119
Number of edges: 174
Average degree:   2.9244 `

and the code line 

`print(nx.info(G)) # Print information about the Graph`

Everything else works fine. This is not a bug in the original tutorial, but a sustainability suggestion to move forward, and avoid confusion in users.

**Comment by jrladd** [comment]
Thanks @acrymble, I noticed the issue with `nx.info()` in my teaching with NetworkX too.

We specified 2.4 previously as a way of dealing with futureproofing problems.  Some of the original functions used in the tutorial were deprecated by a later release, and at the time the idea was to avoid having to constantly update things by setting a version number.

My concern about asking readers to download the latest version of NetworkX is that while there's only a problem with one function right now, NetworkX has not been shy about introducing breaking changes. There could very well be further updates that break more of the tutorial in the near future.

That said, I'm happy to do whatever is most consistent with PH's policy here.

**Comment by hawc2** [comment]
@jrladd I don't think we have a hard and fast rule, and this sounds like a complex case. At the very least, it would be good to add a note explaining why we're using an older version of NetworkX, and what potential problems may arise. 

I understand why it can be hard to go with the newest version, as that may require even more updates on your part with each new change, but we should explain the two options are available and the benefits of each. At some point we will probably need to update the version though, and if you are interested in updating the lesson for 3.0, it seems like a good time to do it. 

If we stick with the older version, a warning will help with a brief explainer/and or instructions for alternate implementations. If there's a relevant link you can provide on the NetworkX site to offload instructions to their docs, that might be helpful for sustainability too.

**Comment by jrladd** [comment]
To follow up on this, @hawc2, I'd be happy to update things for the 3.0 release. I should have time in June once my semester is finished. 

I also think we should stick with using a set version number at the installation step, so the user knows which version the tutorial is using and installs that version. That doesn't stop us from making more updates in the future, but it would help prevent problems if there are small changes between this and the next major release.

**Comment by anisa-hawes** [comment]
Many thanks, @jrladd! 

Please let me know how I can help to coordinate this update. I've set myself a reminder to contact you in June so that we can work together to stage the PR.

**Comment by spapastamkou** [comment]
Please note that this lesson is currently in the process of translation in French - pinging here @marie-flesch to keep an eye.

**Comment by jrladd** [comment]
Thanks for your patience, @anisa-hawes and @hawc2! Attached is a new version of the tutorial with a couple small tweaks to update to NetworkX 3.1. Let me know how we should handle the update from here: should I create a PR or is there another method?

[exploring-and-analyzing-network-data-with-python.md](https://github.com/programminghistorian/jekyll/files/12401962/exploring-and-analyzing-network-data-with-python.md)

**Comment by anisa-hawes** [comment]
With many thanks, @jrladd! I've prepared the PR 🙂 

My next step is to liaise with colleagues in the PT team, as these edits will need to be replicated in the translation: /pt/licoes/explorar-analisar-dados-rede-python.
