### ISSUE TITLE
List of Spanish reviewers and translators

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#287]
Hello, 

We are starting to collect names of Spanish reviewers, translators and collaborators. I have just seen that you have already a page for this: **https://github.com/programminghistorian/jekyll/tree/gh-pages/_data**

Should we add our names to yours or create our own page? 

Thanks!

**Comment by acrymble** [comment]
Good question. This list is people who have already acted as a reviewer on a lesson. Is that what you mean, or are you talking about potential reviewers? In that case, we don't have a list of that anywhere.

**Comment by arojascastro** [comment]
I see! I meant potential reviewers. In that case we can stick to our spreadsheet, right?

**Comment by acrymble** [comment]
If that works for you guys that's fine. We don't have any private spaces for storing information that we don't want public.

**Comment by acrymble** [comment]
I think your question has been answered so I will close this issue. Reopen it if you need to.
