### ISSUE TITLE
Update English editorial guidelines

### ISSUE THREAD

**Issue by hawc2** [programminghistorian/jekyll#2877]
This page has been outdated for a while now: https://programminghistorian.org/en/editor-guidelines#the-role-of-the-editor

@anisa-hawes is it possible to link the PDF you've created to replace these guidelines so there's a live web link where I can point Editors for information on the process? I know you're still working on updating these guidelines, but it's important we keep the live web link up to date. Can you post to this issue ticket as well the most up-to-date version to make sure we're on the same page?

Alternatively, if we don't want to include Editor Guidelines on the public facing website, that's fine by me too. It's just important we have a single place that I can point editors for up-to-date guidelines, even if it's a pdf we host internally in our google workspace.

**Comment by anisa-hawes** [comment]
See #2760.
