### ISSUE TITLE
DH Awards 2022 – Nomination and Voting Announcement

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2880]
Following #2794, I have received a notification that we have been nominated in the Best Digital Humanities Training Materials category of the 2022 [Digital Humanities Awards](http://dhawards.org/).

Congratulations to all the @programminghistorian/project-team 🎉 

Voting is now [OPEN](http://dhawards.org/dhawards2022/voting/)! 

Please show your support by visiting <http://dhawards.org/dhawards2022/voting/> to cast your vote before 2023-03-26. 

The voting announcement is also available in [French](http://dhawards.org/dhawards2022/voting-announcement/voting-announcement-french/), [Spanish](http://dhawards.org/dhawards2022/voting-announcement/voting-announcement-spanish/) and [Portuguese](http://dhawards.org/dhawards2022/voting-announcement/voting-announcement-portuguese/).

I'll circulate the announcement on our social media channels later this afternoon, and would be grateful for your support to share it widely.

**Comment by DanielAlvesLABDH** [comment]
Great news!

**Comment by anisa-hawes** [comment]
And also 🌟 @jenniferisasi and Gimena del Rio Riande's short paper _En qué lengua citamos cuando escribimos sobre Humanidades Digitales?_ has been nominated in the Best Short Publication category! <https://revistas.uned.es/index.php/RHD/article/view/36280>

Congratulations! 👏🏼

**Comment by marie-flesch** [comment]
That's awesome! Congrats!

**Comment by josircg** [comment]
@ericbrasiln "Ferramenta heurística para a Hemeroteca Digital Brasileira" has been nominated too! Congratulations!

**Comment by anisa-hawes** [comment]
Hooray! Congratulations @ericbrasiln! 🙌🏻 

I’m scheduling some Tweets/and Mastodon posts to circulate in the coming days to share the news / encourage people to vote for us. It would be 

EN:

@ProgHist has been nominated in the Best #DigitalHumanities Training Material category of the 2022 @DHAwards. 

Voting for the 2022 DH Awards is open until 2023-03-26 here: http://dhawards.org/dhawards2022/voting/ 

Support us!

--

ES: 
- [x] Checked by @jenniferisasi  

@ProgHist ha sido nominado en la categoría de Mejor Material de Formación en #HumanidadesDigitales de los @DHAwards 2022. 

La votación para los Premios DH 2022 está abierta hasta el 2023-03-26 aquí: http://dhawards.org/dhawards2022/voting/ 

¡Apóyanos!

--

FR:
- [x] Merci beaucoup, @marie-flesch

@ProgHist a été nominé dans la catégorie Meilleur support de formation en #HumanitésNumériques des @dhawards 2022.

Le vote pour les DH Awards 2022 est ouvert jusqu'au 26-03-2023 ici : http://dhawards.org/dhawards2022/voting/

Soutenez-nous !

-- 

PT:
- [x] Muito obrigado, @DanielAlvesLABDH!

@ProgHist foi nomeado na categoria de Melhor Material de Formação em #HumanidadesDigitais dos @DHAward 2022.

A votação para os Prémios DH 2022 está aberta até 2023-03-26 aqui: http://dhawards.org/dhawards2022/voting/

Apoie-nos!


--- 

I'll also prepare some posts to celebrate our two Project Team member's nominations via the PH channels! ✨

**Comment by marie-flesch** [comment]
@proghist a été nominé dans la catégorie Meilleur support de formation en #HumanitésNumériques des @dhawards 2022.

Le vote pour les DH Awards 2022 est ouvert jusqu'au 26-03-2023 ici : http://dhawards.org/dhawards2022/voting/

Soutenez-nous !

**Comment by marie-flesch** [comment]
Be careful @anisa-hawes, the deadline for the vote is **2023-03-26** and not **2022-03-26**

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. For the Portuguese text:

@proghist foi nomeado na categoria de Melhor Material de Formação em #HumanidadesDigitais dos @DHAward 2022.

A votação para os Prémios DH 2022 está aberta até 2023-03-26 aqui: http://dhawards.org/dhawards2022/voting/

Apoie-nos!

**Comment by anisa-hawes** [comment]
I've prepared Tweets in Spanish and Portuguese to celebrate + promote @jenniferisasi and @ericbrasiln via PH channels.

For Jenn in ES:

El trabajo corto de @jenniferisve y @gimenadelr ¿En qué lengua citamos cuando escribimos sobre Humanidades Digitales? ha sido nominado en la categoría de Mejor Publicación Corta de los @DHAwards

https://doi.org/10.5944/rhd.vol.7.2022.36280

¡Enhorabuena!

Vota aquí: http://dhawards.org/dhawards2022/voting/

#HumanidadesDigitales 


--

For Eric in PT:

@ericbrasiln's "Ferramenta heurística para a Hemeroteca Digital Brasileira" foi nomeada na categoria Melhor Ferramenta ou Conjunto de Ferramentas dos @DHAwards

https://ericbrasiln.github.io/pyHDB/

Parabéns!

Vote aqui: http://dhawards.org/dhawards2022/voting/

#HumanidadesDigitais

**Comment by anisa-hawes** [comment]
Note:

I've written to Jenn and Eric to confirm + check translations of the posts prepared above. 

I've set myself a reminder to circulate a final reminder to vote on 22 March (voting closes on 26 March).

> http://dhawards.org/dhawards2022/voting/
