### ISSUE TITLE
Spanish Managing Editor Handover

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2890]
We have a new Managing Editor: :sparkles: @jenniferisasi :sparkles: 
I'm working on updating the following:

- [x] the field `team_roles` in `ph_authors.yml`
- [x] our emails in `ph_authors.yml`
- [x] the field `managing_editor` in `snippets.yml`
- [x] the name provided on our Lesson Query forms
- [x] the Managing Editor's name across our Wikipedia entries **Done!**
- [x] the Managing Editors list on [our Wiki](https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover)
- [x] the Editorial Team on [our Wiki](https://github.com/programminghistorian/jekyll/wiki/Editorial-Team)

**Comment by anisa-hawes** [comment]
Thank you @rivaquiroga! I can take care of updating our Wikipedia entries.
