### ISSUE TITLE
Updating the Additional Supporters sections of our supporters / colaboradores / nos-soutiens / apoiadores pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2895]
Adding former (non-renewing) IPPs to the [Additional Supporters section](https://programminghistorian.org/en/supporters#additional-supporters) of our supporters / colaboradores / nos-soutiens / apoiadores pages.

Additional Supporters are defined as _organizations that have or continue to give support_. This enables us to acknowledge our thanks for the former support of:

- RStudio/Posit

as well as:

- Software Sustainability Institute
- CESTA (Stanford)

**Comment by anisa-hawes** [comment]
Hello @spapastamkou.

Apologies for leaving this Issue hanging. It originates from a conversation about how we acknowledge organisations who have previously supported us an an IPP but are not active members.

**Option 1**: We list all active and inactive IPPs on our Supporters page

**Option 2**: We remove inactive IPPs from our Supporters page

**Option 3**: We move inactive/non-renewing supporters to the [Additional Supporters](https://programminghistorian.org/en/supporters#additional-supporters)/[Soutien additionnel](https://programminghistorian.org/fr/nos-soutiens#soutien-additionnel). This section is defined as organisations _that have or continue to give_ support.

Some thoughts:

-  My sense is that our existing Supporters list helps us to grow our community.
-  I note that in the Additional Supporters section we include a date range in brackets to indicate the phase of active past support. So if we decide to move non-renewals there, I will need to tab back through the monthly cashflow documents to find out the start dates. That is not difficult, just one extra step.

**Comment by spapastamkou** [comment]
Should we consider separating those organisations that have given support but no longer do? As for members, have a sort of history of the supporting orgs. Thoughts about this?

**Comment by anisa-hawes** [comment]
Thank you for these thoughts, @spapastamkou. Yes, I think the Additional Supporters section does that job of providing a history of supporting organisations. This would also provide a visual distinction, helping me to ensure the IPP Information Pack diagram of logos is accurate and reflects current active partners only.

I'm currently liaising with a number of partners whose membership is due for renewal, so I'll close this Issue for now. I'll open a new Issue when I have an up-to-date list of any required changes (based on which organisations are renewing and which are non-renewing).

Going forwards, I'll move non-renewing organisations to the Additional Supporters section, providing the dates in brackets to indicate the year(s) of their active support.
