### ISSUE TITLE
Announcing our collective success in the DH Awards 

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2913]
### _Programming Historian_ [has WON the Best DH Training Materials category of the DH Awards](http://dhawards.org/dhawards2022/results/)! 

-----

I've prepared announcements to share via our social media channels, and would be grateful if a member from each @programminghistorian/spanish-team, @programminghistorian/french-team and @programminghistorian/portuguese-team could review my translations?

- [x] **EN:**

Overjoyed that @ProgHist have won the Best DH Training Materials category of the @dhawards!
Congratulations to the whole project team, and thank you to all who voted for us.
Three cheers for all other winners and nominees whose brilliant work is to be celebrated

\+ 

Special mention to @hwrts + the Mmmonk Workshop team and @EphemeralMedia – both runners up in the Best DH Training Materials category of the @dhawards 

--

- [x] **ES:**

Estamos encantados de que @ProgHist haya ganado la categoría de Mejor material de formación en DH de los @dhawards!
Enhorabuena a todo el equipo del proyecto y gracias a todos los que han votado por nosotros.
Muchas felicitaciones a todos los demás ganadores y nominados cuyo brillante trabajo merece ser celebrado.

\+

Mención especial para @hwrts + el equipo de Mmmonk Workshop y @EphemeralMedia - ambos finalistas en la categoría de Mejor Material de Formación en DH de los @dhawards

--

- [x] **FR:**

Nous sommes ravi·es que @ProgHist ait remporté la catégorie "Meilleur support de formation DH" des @dhawards !
Félicitations à toute l'équipe du projet et merci à tous ceux qui ont voté pour nous.
Félicitations également à tous les autres gagnant·es et nominé·es pour leur formidable travail.

\+

Mention spéciale à @hwrts et à l'équipe de Mmmonk Workshop et @EphemeralMedia - tous deux finalistes dans la catégorie "Meilleur support de formation en DH" des @dhawards.

--

- [x] **PT:**  

Estamos muito satisfeitos pelo @ProgHist ter ganho a categoria de Melhor Material de Formação de DH do @dhawards!
Parabéns a toda a equipe do projecto e obrigado a todos os que votaram em nós.
Três vivas a todos os outros vencedores e nomeados cujo brilhante trabalho será celebrado.

\+

Menção especial a @hwrts + a equipa da Oficina Mmmonk e @EphemeralMedia - ambos concorrentes na categoria de Melhor Material de Formação de DH do @dhawards

---

I am going to prepare a PR to update to the following sections on our website:

/en/about#awards
/es/acerca-de#premios 
/fr/apropos#récompenses
/pt/sobre#prémios

**Comment by nabsiddiqui** [comment]
Wonderful! Congratulations everyone!

**Comment by JoshuaGOB** [comment]
Congrats everyone! Below my suggestions for the Spanish version. 

Nos complace anunciar que @proghist recibió el premio de Mejor material de formación en DH de los @dhawards!
Enhorabuena a cada integrante del proyecto y gracias a quienes votaron por @proghist.
Igualmente, muchas felicitaciones a quienes ganaron o recibieron nominaciones por su excelente trabajo.

+

También queremos hacer una mención especial a @hwrts + integrantes de Mmmonk Workshop y @EphemeralMedia - finalistas en la categoría de Mejor Material de Formación en DH de los @dhawards

**Comment by anisa-hawes** [comment]
Thank you, @JoshuaGOB! I've made this adjustment 🙂

**Comment by marie-flesch** [comment]
Here are my edits for the French version: 

Nous sommes ravi·es que @proghist ait remporté la catégorie "Meilleur support de formation DH" des @dhawards !
Félicitations à toute l'équipe du projet et merci à tous ceux qui ont voté pour nous.
Félicitations également à tous les autres gagnant·es et nominé·es pour leur formidable travail. 

+

Mention spéciale à @hwrts et à l'équipe de Mmmonk Workshop et @EphemeralMedia - tous deux finalistes dans la catégorie "Meilleur support de formation en DH" des @dhawards.

**Comment by anisa-hawes** [comment]
Merci, @marie-flesch ✨

**Comment by DanielAlvesLABDH** [comment]
PT:
Estamos muito satisfeitos pelo @proghist ter ganho a categoria de Melhor Material de Formação de DH do @dhawards!
Parabéns a toda a equipe do projecto e obrigado a todos os que votaram em nós.
Três vivas a todos os outros vencedores e nomeados cujo brilhante trabalho será celebrado.

+

Menção especial a @hwrts + a equipa da Oficina Mmmonk e @EphemeralMedia - ambos concorrentes na categoria de Melhor Material de Formação de DH do @dhawards

**Comment by anisa-hawes** [comment]
Obrigado, @DanielAlvesLABDH.

I'll schedule an announcement in PT for later today, when the Brazilians will also be awake!
