### ISSUE TITLE
Using hashtags in blog titles

### ISSUE THREAD

**Issue by tapar001** [programminghistorian/jekyll#293]
One more blog question! 

I wanted to make the title of this blog post #TeachingWithDH: Distant Reading in the Undergraduate Classroom (in an attempt to get people to participate with blog posts on social media using that hashtag). But I had to cut everything before "Distant" because the post wouldn't load when I included the # and the : in the title. 

Any tips on how to include hashtags and colons in the title without breaking the post?

**Comment by amandavisconti** [comment]
Does putting the title inside quote marks help? 

title: "#TeachingWithDH: Distant Reading in the Undergraduate Classroom"

I did that on my most recent blog post and it worked (though I feel like I had tried it in the past and it didn't work for some reason?)

**Comment by tapar001** [comment]
This worked -- thank you!
