### ISSUE TITLE
Updates to our Events pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2932]
I am updating the following pages of our website to reflect new and forthcoming events:

/en/events
/es/eventos
/fr/manifestations
/pt/eventos

(I am aware that the layout of this page lacks interest, and will need some energy to activate. For now, it is the basic minimum).

**Comment by jenniferisasi** [comment]
Oh there are more than this :) 

@JimmyMedeiros82 is teaching "Aprendendo a analisar dados com R com base em lições do PH" on May 8th at 1PM (I think my time); looks like @rivaquiroga already included her Part 1 and 2 of web scraping? and then her, @mariajoafana and I are doing "Sobre Programming Historian en español y cómo contribuir a la publicación" on May 10th, 3PM, all as part of the [SemanaHD](https://semanahd.cuaieed.unam.mx/#/calendario) 

Anisa, I plan to make a few Tweets and toots about these, maybe I'll find some time to create a flyer?

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi! I'll add these in.

**Comment by rivaquiroga** [comment]
@anisa-hawes, I'm currently editing the PR with that info

**Comment by rivaquiroga** [comment]
BTW, the flyer for the web scraping events is ready. They requested an image when creating the event in the SemanaHD webpage, but not sure why, because they are not rendering the images. Here it is!


![taller-ph-webscraping](https://user-images.githubusercontent.com/31421616/235195077-ae192165-ee3b-48bd-90e3-68cd3abef2c1.png)

**Comment by jenniferisasi** [comment]
Wonderful! Hmm that is weird...

I am going to create a little image with the 4 events to publicize on Twitter and Mastodon all at once

**Comment by anisa-hawes** [comment]
Thank you @jenniferisasi and @rivaquiroga! 

Jenn, I'll send you links to our fonts and .svg logo files 🙂
