### ISSUE TITLE
Liz Fischer is stepping down from the EN team

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2934]
@lizfischer is stepping down for the EN team. 

The following is a list of actions that need to be taken:

- [x] Deassign any open issues assigned to Liz (@anisa-hawes) (@hawc2 to reassign)
- [x] Remove from our Github organisation + English Team on Jekyll (@ZoeLeBlanc)
- [x] Remove Write access to ph_submissions (@anisa-hawes)
- [x] Remove from ProgHist Ltd register of members (@drjwbaker)
- [x] Add to the Membership History list on the Project Team pages of our website (@anisa-hawes) #2935 
- [x] Remove Google Groups + social channels access (@anisa-hawes)
- [x] Review service integrations (@anisa-hawes)

Thank you for your contributions to _Programming Historian_. We wish you well, and hope you will keep in touch.

**Comment by spapastamkou** [comment]
Hey @ZoeLeBlanc, when you have a minute, could you take care of this please (= remove Liz Fischer from the repos and EN team)? I tried to do it myself but I do not seem to have credentials to remove team members from the repo. Thanks a lot in advance!

**Comment by ZoeLeBlanc** [comment]
Just removed Liz from PH and made her an outside collaborator. Thanks for pinging me @spapastamkou again. I was traveling last week and now have Covid so apologies for moving a bit slowly. Thanks for all your hard work and @anisa-hawes too!

**Comment by spapastamkou** [comment]
a huge thanks @ZoeLeBlanc ! And I hope you are better soon!
