### ISSUE TITLE
New topic: Creative coding

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#2947]
The ES team is [about to publish a lesson](https://github.com/programminghistorian/ph-submissions/issues/509) that doesn't fall under any of the topics or categories we have available at the moment, thus, we propose the creation of a new tag along the lines of "creative coding" (using [Wikipedia article](https://en.wikipedia.org/wiki/Creative_coding) as reference). 

 type: creative-coding
  displayname:
    en: "Creative coding"
    es: "Programación creativa"
    fr: "Code créatif"
    pt: "Código criativo"
  description:
    en: "Lessons for creating expressive rather than functional products with programming."
    es: "Lecciones para crear productos expresivos en vez de funcionales con programación."
    fr: "Leçons pour créer des produits expressifs plutôt que fonctionnels avec la programmation"
    pt: "Lições para criar produtos expressivos em vez de funcionais com a programação"

Do you like this definition? 

Reminder: Update _[Interactive Fiction in the Humanities Classroom](https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/interactive-text-games-using-twine.md)_ once this is ready.

**Comment by anisa-hawes** [comment]
**PT**: Lições para criar produtos expressivos em vez de funcionais com a programação

**FR**: Leçons pour créer des produits expressifs plutôt que fonctionnels avec la programmation
