### ISSUE TITLE
Organising our Annual General Meeting: 21st June 2023 at 14:00 UTC

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2954]
I am opening this Issue as a space to organise our AGM. These are the steps I think are needed. Please add in any steps/notes you feel I've missed.

--

- [x] Decide on a date **The event will take place on Wednesday 21st June at [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230621T140000&p1=1440)**

--

- [x] Prepare invitations 
- [x] Circulate invitations - send to IPPs, our Patreon community, and the Project Team
- - [x] direct emails to IPP representatives
- - [x] direct emails to Patreons
- - [x] via our Google Groups
- - [x] via our General Slack + Discord channels

--

- [x] Promote event:
- - [x] a Patreon post
 
--

- [x] Initial planning meeting to agree the AGM's shape and content @spapastamkou @rivaquiroga and @anisa-hawes
- [x] Finalise agenda @spapastamkou @rivaquiroga and @anisa-hawes 
- [x] Treasurer's Report @drjwbaker 
- [x] Prepare slide presentation @spapastamkou @rivaquiroga and @anisa-hawes

**Comment by drjwbaker** [comment]
@anisa-hawes Once you get to the agenda, please link to the Treasurers Report here https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2023/ProgHist-Ltd_Treasurers-Report-2023.pdf
