### ISSUE TITLE
Broken markdown asset link

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#296]
From Alissa M on twitter, the Pandoc/markdown lesson has a broken link to the following URL: http://programminghistorian.org/assets/sample.md

I suspect this is a problem with jekyll trying to render the markdown and getting confused.

The asset is in fact at that URL and can be accessed also via https://github.com/programminghistorian/jekyll/blob/gh-pages/assets/sample.md

Is there a simple fix for this?

**Comment by ianmilligan1** [comment]
I think we should use the raw link, as the authorial intent is to get people to work with the file. I'll change the link, but if anybody disagrees we can always revert.
