### ISSUE TITLE
Hypothesis integration

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#297]
1. Each lesson: add link to reload page with Hypothesis sidebar showing. Do we need to limit this to a Hypothesis group or PH tag for spam/moderation purposes?
2. Other editors are following up on the existing Hypothesis tickets, but I should set up a way to be notified of new annotations on PH lessons (that automatically works when new lessons are added to the site—does H allow such a feed yet?). I need a workflow for turning new annotations into tickets (when addressable) and completing these or finding another team member who feels able to address the issue (we decided _not_ to ping lesson authors to make these changes). Should always create a ticket per annotation (if it's at all something relevant): comment and close ticket if not going to address so we have a record; assign ticket if we should address the issue in the lesson; either add inline text or a footnote (GH Pages Jekyll now allows) depending on relevancy for majority of audience.
3. Further publicity/community encouragement of Hypothesis annotation of lessons? (reread existing reviews of PH site for ideas)
4. Home > Feedback page > add reference to Hypothesis as way to provide feedback
5. Update author info page to indicate editors may make these small changes and fixes (possible for authors to opt-in to notification? check status of lesson displaying latest update/version number)
6. Annotating All Knowledge involvement?

**Comment by mdlincoln** [comment]
I'm going to close this for now, as it sounds like no action is going to happen on this for the moment.
