### ISSUE TITLE
Annual General Meeting: 21st June 2023 at 14:00 UTC

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2970]
![AGM-2023](https://github.com/programminghistorian/jekyll/assets/87070441/5d2c5499-0566-4788-b5da-b04316c5ad15)

---

Date: 21 June 2023
Time: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230621T140000&p1=1440). [This link](https://www.timeanddate.com/worldclock/converter.html?iso=20230621T140000&p1=1440) enables guests to search for their home location and check the time in their zone.
Zoom details: see email
Chair of the Trustees: @spapastamkou 
Deputy Chair of the Trustees: @rivaquiroga  
Treasurer: @drjwbaker 
Secretary: @anisa-hawes 
Minutes of the last meeting: [2022_ProgHistLtd-AGM-minutes.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2022/2022_ProgHistLtd-AGM-minutes.pdf)
Treasurer's report: [ProgHist-Ltd_Treasurers-Report-2023.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2023/ProgHist-Ltd_Treasurers-Report-2023.pdf)

---

Dear all,

**I'm creating this Issue so that we can set our agenda for June's Annual General Meeting.**
Please feel free to add Items for discussion. 

### Agenda

- Welcome @anisa-hawes
- Apologies @anisa-hawes
- Programming Historian Annual report @spapastamkou, @rivaquiroga, @anisa-hawes & treasurers report  @drjwbaker
- Open Discussion about the coming year @spapastamkou
- Approve Minutes 2022 AGM (@spapastamkou)
- Any Other Business

**Comment by anisa-hawes** [comment]
Dear all,

I have now uploaded the minutes of Wednesday's meeting to our Project and Business Archive. 

Project Team Members can review them in Markdown format here: [2023_ProgHistLtd-AGM-minutes.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2023/2023_ProgHistLtd-AGM-minutes.md).

Please let me know if you'd like to suggest any revisions.

Thank you.

Very best,
Anisa

**Comment by anisa-hawes** [comment]
A PDF copy of our 2023 Annual General Meeting minutes [2023_ProgHistLtd-AGM-minutes.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2023/2023_ProgHistLtd-AGM-minutes.pdf) have been uploaded to our Project and Business Archive.

There, you can also find Sofia and Riva's Director's Report [PHDirectorsReportAGM2023.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2023/PHDirectorsReportAGM2023.pdf) and James's Treasurer's Report [ProgHist-Ltd_Treasurers-Report-2023.pdf](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/AGMs/2023/ProgHist-Ltd_Treasurers-Report-2023.pdf).

**Comment by drjwbaker** [comment]
[2023_ProgHistLtd-AGM-minutes.md](https://github.com/user-attachments/files/29328274/2023_ProgHistLtd-AGM-minutes.md)
