### ISSUE TITLE
Board of Trustees Meeting: Wednesday 19th July 2023 at 16:00 UTC

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#2988]
Date: 19th July 2023
Time: 16:00 UTC ([check your local time](https://everytimezone.com/s/59a9af23))
Zoom link + passcode: will be sent by email
Chair: @rivaquiroga 
Secretary: @anisa-hawes 

---
I am creating this issue for us to edit and add items to the agenda for our next meeting on July 19.

## Agenda 

1. Apologies 
2. Approval of minutes of the 24th May meeting: [BoT-24-05-2023.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/BoT-24-05-2023.md) + Actions Status
3. ProgHist Directors administration (e.g., changes of address)
4. Publishing Managers' Report including update on Digital Humanities Publishing Assistant appointment (@anisa-hawes)
5. Technical infrastructure update (@spapastamkou @anisa-hawes)
6. Potential new trustee(s)
7. Proposal for a workshop PH-C²DH and other stakeholders of multilingual publications (email sent by @spapastamkou )
8. [Call for proposals: Open Infrastructure Fund](https://investinopen.org/blog/open-infrastructure-fund-pilot-cfp/) (@rivaquiroga)
9.  Any other business

**Comment by spapastamkou** [comment]
I will add some items soon and send relevant information by email as not very likely to be able to participate.

**Comment by acrymble** [comment]
I’d like to add Technical infrastructure long term plan to the agenda please

**Comment by spapastamkou** [comment]
I confirm that I will not be able participate to this meeting, normally all information I had to share has been sent by email and Anisa and Riva have hopefully what they need on my behalf. Have a great meeting and a restful summer all!

**Comment by drjwbaker** [comment]
Who is chairing in the absence of the chair? This needs to be agreed before the meeting.

**Comment by anisa-hawes** [comment]
Thank you, @drjwbaker. @rivaquiroga is Chairing this meeting.

**Comment by drjwbaker** [comment]
Okay.

**Comment by drjwbaker** [comment]
(sorry, missed that in the header *face palm*)

> No! My fault completely. I updated the header just now, because your question made me realise my mistake. (@anisa-hawes)

**Comment by spapastamkou** [comment]
Dear fellow trustees, are there any (informal) notes of the meeting available? I know AH will send the minutes after her leave and I do not want to bother her before, so if someone has kept notes I would be grateful if you can give me access. Thanks!

**Comment by anisa-hawes** [comment]
Apologies for the delay. Minutes of this meeting have been uploaded to our private Project and Business repository: [BoT-19-07-2023.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/BoT-19-07-2023.md).
