### ISSUE TITLE
Update broken link across cleaning-data-with-openrefine, limpieza-de-datos-con-OpenRefine, nettoyer-ses-donnees-avec-openrefine, limpar-dados-openrefine

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#2999]
I am preparing to replace a broken link to the Powerhouse (museum in Sydney) which has recently updated its website address from http://www.powerhousemuseum.com/ [404] > **https://powerhouse.com.au/**.

It appears that this museum has changed its name several times during the past few years. It was previously known as the Powerhouse Museum, then Museum of Applied Arts and Science, now Powerhouse.

This link features in the following lessons:

/en/lessons/cleaning-data-with-openrefine
/es/lecciones/limpieza-de-datos-con-OpenRefine
/fr/lecons/nettoyer-ses-donnees-avec-openrefine
/pt/licoes/limpar-dados-openrefine

The dataset associated with these lessons was downloaded at the time the original lesson was written, and is hosted on our assets repository so I believe it is still possible for readers to follow the steps: https://programminghistorian.org/assets/phm-collection.tsv 

However, a short section of wording will need to be adjusted because the tab separated values (`.tsv` file) does not appear to be available from their website any longer:

> The Powerhouse has been very actively disclosing its collection online and making most of its data freely available. From the museum website, a tab-separated text file under the name phm-collection.tsv can be downloaded, which you can open as a spreadsheet. The unzipped file (58MB) contains basic metadata (17 fields) for 75,823 objects, released under a [Creative Commons Attribution Share Alike (CCASA) license](http://creativecommons.org/licenses/by-nc/2.5/au/). In this tutorial we will be using a copy of the data that we have archived for you to download (in a moment). This ensures that if the Powerhouse Museum updates the data, you will still be able to follow along with the Lesson.

**Comment by anisa-hawes** [comment]
Hmmm.... I am digging around on their website to see if the datasets _are still available_, but can't find them. I would be very surprised if a load of data which had been actively made available was now removed...

Also found this: https://data.nsw.gov.au/data/dataset/powerhouse-museum-collection-simplified-dataset

**Comment by rivaquiroga** [comment]
Mmm... this is not the first time we have to change the link to the dataset used in this lesson. As you said, we have the tsv file on our repository, so the lesson is still usable if we update the paragraph about the file.

**Comment by anisa-hawes** [comment]
It is a bit of a mess... I might also need to update the screenshots for Figure 1. across all four lessons 😞 

It seems crazy that a major museum would change its name! Twice!
