### ISSUE TITLE
Markdown reference links or inline links?

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#3]
@fredgibbs, as mentioned in #2, I'm thinking of using Pandoc to convert all the existing lessons to Markdown as a first stab at transition to the new site. 

Wondering if we might want to use Markdown "reference links" (which put all URLs at the bottom of the file) instead of inline links, as it would make the Markdown more readable on GitHub?

**Comment by asbjornu** [comment]
Just a note for others finding this issue through search; reference links in Markdown only support links. [Doing something like this](https://raw.githubusercontent.com/programminghistorian/jekyll/6faf2b725b0710b55172ce65d2f1552b555055dc/lessons/googlemaps-googleearth.md) won't work:

```markdown
![geo12][]\

…

[![geo23][]]: ../images/geo23.png
```

What will work, though, is this:

```markdown
[![Alt text][image-reference]][link-reference]

…

[image-reference]: ../images/geo23.png
[link-reference]: /some/link
```

The above is equivalent to the following inline link example:

```markdown
[![Alt text](../images/geo23.png)](/some/link)
```

Breaking this up, we have the image first, indicated by the `!` prefix on the link:

```markdown
![Alt text](../images/geo23.png)]
```

Then we wrap that in the following ordinary Markdown link:

```markdown
[…](/some/link)
```

Replace `…` with the image, change the inline links (`(…)`) with reference links (`[…]`) and you'll get the working example from above.
