### ISSUE TITLE
Investigating a small update to `build.yml`

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3001]
In the course of preparing a new EN lesson for publication which integrates a `.ipynb` file that we are hosting locally on GitHub, we note that our build check rules are preventing us linking to the URL we need to direct to: 

[https://github.com/programminghistorian/jekyll/blob/gh-pages] /assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb.

When I try formating this as a relative link (following our usual practice /assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb) the file displays as raw data.

When I use the full link, the build checks fail with the error message:

`It looks this page contains a full link to data in one of our GitHub repositories. Do not link to GitHub for data. Instead, please use a relative path starting with /`

I've been chatting with @rivaquiroga to better understand this, and she suggested that if we are going to host notebooks in this way, we will need to adapt our build check rules about how we link to internal assets. We need to stipulate an exception to the rules for any file ending in `.ipynb`. This will require a small change to our `build.yml` file.

**Comment by anisa-hawes** [comment]
Unexpectedly, I can see that the arguments at line 36 do state: ` --file-ignore "/assets/`

**Comment by rivaquiroga** [comment]
The problem with using a relative link is that it shows the raw content of the notebook on our website. And what we need is for people to access the notebook in the version hosted on GitHub, so they can download it or open it in Colab. 

![Captura de pantalla 2023-08-10 a la(s) 13 14 42](https://github.com/programminghistorian/jekyll/assets/31421616/7e21d50f-cc63-4927-8f67-12fc2e7f9080)

**Comment by anisa-hawes** [comment]
Maybe something like `--ignore="*.ipynb"` is what we need?

**Comment by anisa-hawes** [comment]
Hello @ZoeLeBlanc and @jrladd. I hope you're well? 

I'd like to ask if either of you might be able to advise me on this Issue. 

Does the option of an adjustment (exclusion) to our build check rule seem sensible to you in this case?

**Comment by ZoeLeBlanc** [comment]
I could take a look at this either later today or early tomorrow. Just skimming the issue so far and it would be helpful to see what lesson we're trying to do this in. Is it a current PR? I think the track you suggest sounds promising though @anisa-hawes so no worries if you resolve it before I can get to this 😊

**Comment by anisa-hawes** [comment]
Thank you, @ZoeLeBlanc. Not an urgent rush – most important is that we want to get this right. It will be something we encounter again and again as lessons integrate Python notebooks. 

Yes, we are working on this via PR #2987. Reviewing the asset within that branch, the notebook displays as we want it to: https://github.com/programminghistorian/jekyll/blob/Issue-2986/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb

I've started to test out an edit to our `build.yml` file, and I think I have something which builds https://github.com/programminghistorian/jekyll/pull/3002/commits/f40d13b6a52b6f7c0dacaa32096871d33fe32355 (aside from multiple broken links across the site which I can fix tomorrow 😅)

**Comment by ZoeLeBlanc** [comment]
Ok had a second to take a look. So this isn't an issue with our build workflow but actually a custom module that @mdlincoln  wrote that validates our yaml (exact link to the line of code is [here](https://github.com/programminghistorian/jekyll/blob/412c42b1d527dd3c37c976ef5ca7aa39c9f2297a/_plugins/validate_yaml.rb#L198 ).

So figuring out fixes could be in our `build.yaml` but probably it's best to either update the module or link to notebooks differently. 

If we want to update the module we would need to update our regex to:
`if Regexp.new("[\\(<]https?://github.com/programminghistorian/.+/blob(?!.*\.ipynb)") =~ p["content"]`
So that we don't throw an error for notebooks.

Alternatively we could use jupyter's nbviewer instead. So the link would be https://nbviewer.org/github/programminghistorian/jekyll/blob/Issue-2986/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb

Happy to discuss more but hopeful that either of those options should resolve the issue 😊

**Comment by rivaquiroga** [comment]
@anisa-hawes, I think nbviewer is the best solution for our user case. It offers different options to our readers: open in Colab, execute in Binder, see the file in GitHub, and a download button.

**Comment by anisa-hawes** [comment]
Thank you so much @ZoeLeBlanc and @rivaquiroga ! 

In the case of using nbviewer, am I right that the correct link (in the published lesson) would be:

<https://nbviewer.org/github/programminghistorian/jekyll/blob/gh-pages/assets/clustering-visualizing-word-embeddings/clustering-visualizing-word-embeddings.ipynb>

I'm aware that this link will fail (404) until _after_ publication, thereby blocking our build. One solution would be to prepare an additional PR which adds the `.ipynb` to assets ahead of preparing the PR to publish. Does this sound sensible? 

I'm reading the nbviewer FAQs and it seems that no account or log-in credentials are needed so we can start using it straight away 🙂

**Comment by anisa-hawes** [comment]
Success! Thank you both. I really appreciate this insight about nbviewer, @ZoeLeBlanc ✨ 

I'm preparing some notes to set out a workflow for how we handle notebook assets in a consistent and sustainable way.
