### ISSUE TITLE
call for interest: article on Programming Historian, Journal of Digital History

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#3005]
Dear team, the Journal of Digital History is interested in having an article on/related to Programming Historian in a special issue on teaching digital history. The call on this issue is accessible here: https://journalofdigitalhistory.org/en/cfp/teaching 

Please manifest yourselves if you have ideas and capacity in order to agree on an idea for and work on a collective article. I propose we keep this open until the first week of September included as many members are likely to be on vacation currently. Thank you.

**Comment by jenniferisasi** [comment]
Thanks @spapastamkou! Manifesting myself to say that I don't have capacity (nor much experience in the particulars of teaching digital history) but happy to brainstorm and/or read drafts :)

**Comment by DanielAlvesLABDH** [comment]
Dear @spapastamkou, many thanks for sharing this. Unfortunately, I will not have time to dedicate to this in the next months. I could help reading and commenting on draft but nothing more. Sorry. 
But probably @joanacvp and/or @ericbrasiln are interested?

**Comment by joanacvp** [comment]
Dear @spapastamkou. I will be happy to participate and collaborate with our experience in NOVA FCSH (Lisbon, Portugal) on the impact of using the PH when teaching digital history :)

**Comment by spapastamkou** [comment]
Thanks all of you until now ! Please note that it is utterly possible (even desirable) to adopt a larger Digital Humanities scope, of which digital history would be a part, in order to underline PH's hybrid character and include members/community/uses of PH that go beyond the discipline of history.

**Comment by jenniferisasi** [comment]
@spapastamkou since I don't teach classes, at all, do you think that a section on teaching workshops would fit? That I do regularly and I use lessons or create lesson from the workshops

**Comment by spapastamkou** [comment]
I think this would be a great contribution @jenniferisasi and I was hoping that you'd be interested. I believe @rivaquiroga @anisa-hawes have ideas from such a perspective that can fit as well. And it would be surely possible to ask for input by other members who may not have the possibility to invest themselves more.

**Comment by jenniferisasi** [comment]
@spapastamkou count me in!

**Comment by anisa-hawes** [comment]
One idea we could consider:

Submitting an edited roundtable discussion about how our lessons serve as self-learning tools as well as pedagogical tools. 

I'm particularly interested in reflecting on the unique value of lessons that are written text-on-paper/screen in the accessible tone of voice we might hear from a colleague or friend who is explaining their methodology and reflecting on their decisions. 

My sense is that our lessons are specifically written one-to-one, author-to-reader, for working through at-your-own-pace. I think that educators who use our lessons in their teaching are doing agile and adaptive work when they transform this form into a spoken-out-loud, one-to-many, classroom context.

**Comment by rivaquiroga** [comment]
Hi, everyone!
We created a channel on Slack to work on the article: #collaboration-article-jdh
If someone else has interest in participating, you can join us there 🤝

**Comment by spapastamkou** [comment]
thanks a lot for the initiative @rivaquiroga. I think however it is important to clarify that this does not mean the conversation no longer takes place here and moves entirely on Slack, at least at this early stage (as not everyone interested is/can be branched there for whatever reason). Cheers!

**Comment by acrymble** [comment]
I'm potentially interested. I'm not sure how a contribution really fits their model of narrative/hermeneutic/data layers. Is someone taking a lead on this initiative on our behalf?

**Comment by spapastamkou** [comment]
I started à Gdoc to note who is in and ideas. It is open but do not have
access to the link until later today. I can help shape the approach and
contribute but preferably without being corresponding author

Le jeu. 14 sept. 2023, 12:44, Adam Crymble ***@***.***> a
écrit :

**Comment by spapastamkou** [comment]
Some very basic notes in this [Gdoc](https://docs.google.com/document/d/15J-_dKK1a-jXttLuLbV7LwEE2w6vPS02EdjQR9usQUo/edit?usp=sharing). Please feel free to add ideas if interested.

**Comment by spapastamkou** [comment]
Small update: I have currently some pressing deadlines to honor (included two for PH) but I did not forget this issue and will write back to all who manifested themselves in some days from now and close the issue at that point. Thanks for understanding!

**Comment by rivaquiroga** [comment]
Another idea (I'll add it to the GDoc too): 

- What can we say about teaching digital (history/humanities) in the past 10 years by looking at the tutorials published at PH? 

- Have the topics/datasets/goals/methods/authors' background/etc. changed in this period? What has remained stable? 

We can complement this data with the input from workshops based on PH tutorials.

**Comment by spapastamkou** [comment]
Started sending emails to all of you who declared possible interest here - should be done by the end of the day - will close the issue then. Thanks for your patience!
