### ISSUE TITLE
Fix broken link in ES datos-tabulares-en-r + PT nocoes-basicas-R-dados-tabulares

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3009]
I am opening this issue to update a broken link in the following ES and PT lessons:

- **Datos tabulares en R**: /es/lecciones/datos-tabulares-en-r
- **Noções básicas de R com dados tabulares**: /pt/licoes/nocoes-basicas-R-dados-tabulares

--

ES: The problem link is at line 543: `En este caso, y dentro del paréntesis de esta la función [write.xlsx](https://www.rdocumentation.org/packages/xlsx/versions/0.6.1/topics/write.xlsx)`

PT: This link also appears in the PT translation /pt/licoes/nocoes-basicas-R-dados-tabulares at line 549: `Neste caso, e dentro do parêntese desta função [write.xlsx](https://www.rdocumentation.org/packages/xlsx/versions/0.6.1/topics/write.xlsx)`

Note: does not feature in the EN original /en/lessons/r-basics-with-tabular-data

--

**Comment by anisa-hawes** [comment]
Searching on https://www.rdocumentation.org/, I am not finding an equivalent page to replace this with... https://www.rdocumentation.org/search?q=write.xlsx

I have identified two options:

- https://www.rdocumentation.org/packages/xlsx/versions/0.6.5 
- https://docs.ropensci.org/writexl/

(What do you think might be best @rivaquiroga?)

**Comment by DanielAlvesLABDH** [comment]
Hi @anisa-hawes. Probably this (https://www.rdocumentation.org/packages/xlsx/versions/0.6.5) is best. Thanks
