### ISSUE TITLE
Collaborative article for: Special Issue of the Journal of Electronic Publishing (JEP)

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/jekyll#3013]
Hi, everyone!

There is a call for papers for a special issue on Multilingual Publishing & Scholarship of the Journal of Electronic Publishing (JEP). Seems like a good fit for a PH related article.

**The CfP**
https://journals.publishing.umich.edu/jep/news/71/

**The Deadlines**
Abstract submissions: September 15
Full papers of accepted abstracts: December 31st 2023. 

If you are interested and have the capacity to participate, we have created a channel on Slack to work together on a proposal: #collaboration-article-jep

**Comment by anisa-hawes** [comment]
An update: our abstract has been accepted! ✨ 

**Would you like to collaborate with us?**
---

- Please let us know if you're interested in contributing by 31st October. 
You can let us know here, or join us in the Slack channel: **#collaboration-article-jep** to participate.

- Our full paper is due on December 31st.

**Comment by anisa-hawes** [comment]
Draft successfully submitted. With thanks to @rivaquiroga, @amsichani and @charlottejmc for their collaboration 👐🏻
