### ISSUE TITLE
Replace broken link in /es/lecciones/reutilizando-colecciones-digitales-glam-labs

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3016]
I am opening this Issue to replace a broken link in the ES lesson [Reutilizar colecciones digitales: GLAM Labs](https://programminghistorian.org/es/lecciones/reutilizando-colecciones-digitales-glam-labs).

The problem link is <https://labs.loc.gov/lc-for-robots/>.

I think it could be suitably replaced with <https://labs.loc.gov/data-for-exploration>. This page offers a list of open datasets provided by the Library of Congress.

**Comment by jenniferisasi** [comment]
That seems like a good replacement to me too @anisa-hawes
