### ISSUE TITLE
Orientation for Charlotte Chevrie, our new Publishing Assistant

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3018]
### Welcome, Charlotte Chevrie (@charlottejmc)!

This is a checklist of tasks and conversations which [@anisa-hawes](https://github.com/anisa-hawes) is working through with our new Publishing Assistant, Charlotte Chevrie.

--- 

**Overview of the project:**
- [x] Introduce the About pages, including PH history 
- [x] Introduce the Project Team pages and organisational structure chart 
- [x] Introduce the Supporters' pages, explain our Institutional Partners Programme
- [x] Introduce the Research pages
- [x] Introduce the Lesson Index pages, including conversation about the ways users find and filter resources to meet their learning objectives

**Internal communications:**
- [x] Set up Gmail address (publishing.assistant [at] programminghistorian.org) 
- [x] Invite to our Google Groups 
- [x] Invite to Slack + Discord 
- [x] Organise welcome meetings with team members (over the coming weeks)

**Workflows + best practice:**

First steps:
- [x] Set up GitHub Account 
- [x] Invite Charlotte to join our organisation on GitHub
- [x] Introduce Jekyll Issues 
- [x] Introduce the Pull Request system 
- [x] Add Charlotte’s profile + portrait to the Project Team page #3022 
- [x] Publish a blog post to introduce Charlotte

**Focus area 1** :  Publications support
- [x] Introduce Active Lessons Project Board
- [x] Introduce ph-submissions Issues
- [x] Introduce the [editorial workflow](https://github.com/programminghistorian/ph-submissions/wiki/Overview-of-Editorial-workflow)
- [x] Introduce Publishing tasks at Phase 1 
- [x] Introduce Publishing tasks at Phase 6 
- [x] Conversation about lesson sustainability, including principles and challenges
- [x] Introduce Lesson Maintenance, including [workflow](https://github.com/programminghistorian/jekyll/wiki/Maintenance-Workflow) and [Project Board](https://github.com/orgs/programminghistorian/projects/6/views/1) 

**Focus area 2** : Documentation and record-keeping support
- [x] Introduce the Project and Business Archive
- [x] Introduce our meetings types and frequency
- [x] Conversation about minute-taking methods
- [x] Share templates for minute-taking

**Focus area 3** : Communications support
- [x] Introduce the PH Blog 
- [x] Initiate conversation about how we could re-activate our blog to improve engagement and reach our multi-lingual communities. Qs: Rethink the platform we use? Adjust the format/tone of voice/content themes/kind of messaging?
- [x] Share examples of other newsletter/blog formats, which could provide inspiration
- [x] Introduce our Twitter and Mastodon social media profiles

**Workspace + tools:**
- [x] Workspace assessment
- [x] Home office tech requirements
- [x] Set-up profile on Bitwarden Vault for shared passwords
- [x] Charlotte to work through Sarah Simpkin's lesson [Getting Started with Markdown](https://programminghistorian.org/en/lessons/getting-started-with-markdown) / [Débuter avec Markdown](https://programminghistorian.org/fr/lecons/debuter-avec-markdown)

**Comment by rivaquiroga** [comment]
Welcome, @charlottejmc! ✨️

**Comment by jenniferisasi** [comment]
¡Bienvenida, @charlottejmc! Happy to help with the onboarding in any way I can

**Comment by anisa-hawes** [comment]
I'm closing this Issue as we've now marked off the final few points on Charlotte's orientation checklist. 

Congratulations to @charlottejmc on a super first month! ✨
