### ISSUE TITLE
Question regarding Intro to Beautiful Soup 

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#302]
Question reported via email as to why the tutorial recommends a conversion to "str" at the end of the tutorial. I am looking into this (the tutorial may need updating). 

> I've been using the Programming Historian to teach some cognitive
> science students to code. I think the site is great.
> 
> I have a quick query about something in the Intro to Beautiful Soup
> lesson. In the final example the `str` is used to convert everything but
> the value of 'congress'. Is there a reason for that? I can't see why
> 'congress' needs to be different to the

**Comment by acrymble** [comment]
Unless the value is supposed to be a number, it looks like you've just forgotten to add str to the rest of it.

**Comment by jerielizabeth** [comment]
Ah, the value was indeed a number (i.e., 43 for the 43rd Congress). But for the sake of consistency, all of the values could be converted to strings. 

And actually, it appears that the HTML behind this lesson has changed, so using strings now makes more sense for the data.

**Comment by acrymble** [comment]
This isn't really a bug then. You could either add a short note to clarify, or just close this.
