### ISSUE TITLE
Project Team Meeting, 15 September 2023

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#3023]
## Project Team Meeting, 15 September 2023

Date: Friday 15 September 2023
Time: [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20230915T150000&p1=1440)
Zoom link: https://zoom.us/j/5959205456
Passcode: by email

Project Team Meeting
---

- Welcome to @charlottejmc, our new Publishing Assistant ✨ 

- Editorial Guidelines: working closely with the Managing Editors over recent months, we've introduced [a phased workflow](https://github.com/programminghistorian/ph-submissions/wiki#editorial-guidelines) which we are continuing to test and refine. This workflow sets out the sequence of tasks and clarifies who is responsible for which processes at each step. A key difference in this proposed workflow, is that the publishing team will take care of Phase 1 Submissions (where we process + upload new lesson materials, generate + check lesson previews) as well as Phase 6 Sustainability + Accessibility. This will include: coordinating copyediting (original lessons only), typesetting (all lessons), generation of perma.cc archival links, collection of copyright declaration forms + request of DOI. (@anisa-hawes)

- Ideas for a collaborative article for the Journal of Digital History #3005 (@spapastamkou)

- Thinking about readers' needs: prompted by [Adam's recent article](https://doi.org/10.1007/s42803-023-00066-x), we thought it would be useful to discuss how we seek to learn about which skills our communities want to learn, and how we could do this more effectively.

**Comment by spapastamkou** [comment]
Agenda soon to come!

**Comment by acrymble** [comment]
Is this meeting still happening?

**Comment by anisa-hawes** [comment]
Thank you, @acrymble. Yes, it is happening. Apologies for my delay in adding the agenda items.

**Comment by DanielAlvesLABDH** [comment]
Dear all, unfortunately due to a meeting of the Board of my institution I cannot attend today. Best

**Comment by mariajoafana** [comment]
Dear all, I won't be able to attend. I'm attending the MaratónHD, the Colombian DH conference in Medellín.

**Comment by rivaquiroga** [comment]
Hi, everyone! I'll only be able to attend the first half of the meeting (I'm attending conference out of town). Hope my internet connection is reliable enough 🤞

**Comment by spapastamkou** [comment]
@anisa-hawes Do we need something more here or we can close this issue now? Thanks in advance!

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou. Nothing further. 

The minutes are available in our private repository [09_2023_ProjectTeamMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2023/Project-Team-Meetings/09_2023_ProjectTeamMeeting.md).
