### ISSUE TITLE
Missing anchor link in French guidelines for author

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#3028]
In the [French guidelines for authors, part 3: submit a lesson](https://programminghistorian.org/fr/consignes-auteurs#%C3%A9tape-3-soumettre-une-nouvelle-le%C3%A7on) in point 2: préparer vos fichiers, there are brackets indicating the presence of a link but the link is missing. 
Here is the extract: 
Merci de vérifier que tous les fichiers images sont nommés de manière appropriée, en accord avec les [conventions de nommage spécifiées ci-dessus]. 
And this is the link that should normally be there: 
(#figures-et-images)

The relevant file is `consignes-auteurs.md` in the jekyll/fr folder.

**Comment by spapastamkou** [comment]
cc @marie-flesch @anisa-hawes

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou. Charlotte & I have spoken about this.

Charlotte, this is a template for creating a `[link that directs to a particular section on the same page](#figures-et-images)`.

**Comment by spapastamkou** [comment]
thanks a lot for taking care of this, @charlottejmc :-)
