### ISSUE TITLE
Project Team presentation - simplify?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#303]
I'd like to suggest that we simplify the Project Team page. There's too much text and I don't think it actually helps potential users to understand who to contact for what. It also asks people to contact Jeri Wieringa in the first instance, but she doesn't have an email address listed on the page.

I think the DH Commons masthead (equivalent to our project team) is more user-centric, and less about the editors.
![screen shot 2016-10-28 at 11 23 38](https://cloud.githubusercontent.com/assets/646647/19803562/572e0b5c-9d01-11e6-94a2-cca1af45a6c5.png)

We don't have to go that bare, but making it transparent who the editors are and how the project team comes together might be simpler for users. Categories such as:
- Commissioning Editor
- Editorial Team
- Spanish Language Team
- Community Development Team
- Technical Team

And to get your name on a respective list, you just have to be actively engaged in that aspect of the project?

The editor interests was a good idea, but I don't think it's translated into anything helpful for authors, and it's really just highlighted that we have narrow interests relative to the whole of digital humanities!

Thoughts?

**Comment by ianmilligan1** [comment]
Sounds like a great idea to me, Adam. I think a more minimalist approach would be nice (although there might be something humanizing about having our smiling/stoic/etc. faces there).

**Comment by fredgibbs** [comment]
assigning this to me, as per the general site CSS and layout update.

**Comment by arojascastro** [comment]
I had a look at my bio and it is already outdated -- I am not longer based in Barcelona. Who I should contact to update it? Thanks.

**Comment by acrymble** [comment]
@arojascastro you can update it yourself here: https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/authors.yml

You raise an interesting question though about our records. Don't we want the record of where people were when they contributed (wrote, reviewed, whatever) rather than where they end up? I suppose in that sense someone could have multiple yml entries. But maybe we don't want to worry about that right now?

**Comment by ianmilligan1** [comment]
I think that might make things overly complicated, having multiple yml entries. If we really want a static snapshot of where somebody was when they contributed a piece, it should perhaps just be hardcoded into the lesson?

**Comment by acrymble** [comment]
We're a bit off topic now for this thread, but @ianmilligan1 you raise a good point. Not sure why we haven't been going with hard-coding.

**Comment by acrymble** [comment]
I have been asked to make this easier (for work) to understand my contribution to this project. I suspect it would also help our readers and potential contributors. So I'd like to roll this out if we can. Anyone unhappy with these categories? I've tried to think who would be in which, so please don't be offended if you think I have it wrong (just add yourself).

1. Commissioning Editor

- Jeri Wieringa

2. Editorial Team

- Adam Crymble
- Fred Gibbs
- Ian Milligan
- Jeri Wieringa
- (anyone else feel they are actively editing?)

3. Spanish Language Team

- Maria José Afanador-Llach
- Antonio Rojas Castro
- Víctor Gayol

4. Community Development Team

- Adam Crymble
- (someone please join me on this! Maria, are you going to be the Spanish person on this front?)

5. Technical Team

- Fred Gibbs
- Caleb McDaniel
- Amanda Visconti
- (anyone else feel they contribute a lot to this?)

**Comment by wcaleb** [comment]
@acrymble I definitely see the benefit of making more specific what we do, but I wonder if this breakdown works at cross-purposes with the goal of simplifying the page. I think there's even more overlap and could be more with time. (For example, I have one lesson I'm editing and another submission being prepared; if others come on who do both technical and editorial work, then those lists will both expand and replicate each other.)

I wonder if a better way to do this would be with "categories" in our bio YAML, so that under each person's name on the Project Team, there could be a small list of "tags" specifying what that person does (e.g., "editing," "maintenance," "outreach"). This would also enable use to keep everyone together on the Project Team without creating divisions that might imply more hierarchy in our organization than there actually is.

**Comment by vgayolrs** [comment]
In any of the two proposals, could we maintain an alphabetical order by surname?
@acrymble : I clarify my comment: most of us are in alphabetical order of surnames, except Antonio, whose surname is Rojas Castro.

**Comment by acrymble** [comment]
There are separate user-experience and professional issues at stake here. Also specific styling (which @fredgibbs is doing as a separate aspect of this). 

The user-experience should take priority, I think. As such, I do think it's worth putting the managing editor (as well as the Ombudspersons) at the top, on their own. These are rotating positions and we can make that clear. I don't mind if the rest are together as @wcaleb suggests.

The professional matters are more about transparency than 'credit' or 'rank' because we all contribute differently and it comes together into a project that none of us could do on our own (and alphabetical is fine with me). We're just different than most projects humanists understand, and I think everyone could benefit from being able to say: I do these bits.

As far as tags go, maybe this is a better list?:

- Commissioning Editor
- Ombudsperson
- Editorial Team
- Spanish Language Team
- Community Development Team
- Technical Team
- Board Member (currently everyone)

**Comment by acrymble** [comment]
Using @wcaleb 's suggestion for tags. Maybe an entry might look like this? (not styled)

Adam Crymble is a lecturer of digital history at the University of Hertfordshire.
Project Roles: Editorial Team; Community Development Team; Board Member.

We could have a short blurb towards the bottom that explained each for anyone that cared.

**Comment by jerielizabeth** [comment]
I like the tags approach! One comment: I am not sure we need the "Commissioning Editor" title.

**Comment by acrymble** [comment]
Would you prefer something else? I'd prefer we think of them as 'roles' rather than 'titles'. I'm not trying to implement rank. Just make it clear how the project team comes together to produce the project. In that case, who ~~editors~~ authors should contact first.

**Comment by acrymble** [comment]
Just trying to tag everyone (in alphabetical order). Let me know if you want yours changed:

- Maria José Afanador-Llach works in the Fundación Histórica Neogranadina, a non-profit organization digitizing endangered colonial archives in Colombia and promoting digital humanities projects.
Current Teams: Spanish Team; Project Board Member

- Adam Crymble is a lecturer of digital history at the University of Hertfordshire.
Current Teams: Editorial Team; Community Development Team; Project Board Member

- Víctor Gayol is a researcher and professor at El Colegio de Michoacán, A.C. (CPI-CONACYT), México, with a PhD in History.
Current Teams: Spanish Team; Project Board Member

- Fred Gibbs is an assistant professor of history at the University of New Mexico.
Current Teams: Editorial; Technical; Board

- Caleb McDaniel is an associate professor of history at Rice University. 
Current Teams: Editorial; Technical; Board

- Ian Milligan is an assistant professor of history at the University of Waterloo.
Current Teams: Editorial; Board

- Antonio Rojas Castro is a researcher a the Cologne Center for eHumanities, with a PhD in Humanities (Spanish Literature).
Current Teams: Spanish; Board

- Amanda Visconti is Managing Director at the University of Virginia Scholars' Lab DH center, with a Ph.D. in Literature.
Current Teams: Technical; Ombuds; Board

- Jeri Wieringa is a doctoral candidate in history at George Mason University.
Current Teams: Editorial; Submissions; Board

--

Team descriptions:
---

- Community Development - responsible for project outreach.
- Editorial - responsible for editorial work resulting in the review and publication of lessons.
- Ombuds - a person that authors and reviewers can turn to if they have queries or concerns about any part of the peer review and publication process.
- Project Board Member - a fully fledged member of the project team, involved in directing the project's future.
- Spanish - responsible for the Spanish-language version of the project.
- Submissions - first point of contact for authors seeking feedback on lesson ideas.
- Technical - responsible for the technical features that bring the content and peer review to our community.

**Comment by vgayolrs** [comment]
@acrymble Happy to join the Community Development Team

**Comment by acrymble** [comment]
Sure, let's discuss ideas at the next editorial meeting

**Comment by wcaleb** [comment]
Would it be simpler to call these "Teams" instead of "Roles" and then try to find one word for each? Visually I think simpler would be better, and as long as there is a fuller key at the bottom, we don't lose anything by shorter tag names. 

Teams:
- Spanish
- Editorial
- Technical
- Submissions (or Contact)
- Outreach
- Ombuds
- Board


Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by acrymble** [comment]
Works for me

**Comment by arojascastro** [comment]
I like the new proposal. By the way in the current state I should go after Ian M. My family name is Rojas. If the organization chantes, then I need to go after @vgayolrs.

**Comment by acrymble** [comment]
updated above based on suggestions.

**Comment by acrymble** [comment]
@ianmilligan1 are you still an ombudsperson? Or is @amandavisconti the only one now? Just noticed you're both listed on Editorial Guidelines.

**Comment by ianmilligan1** [comment]
I think I'm still an ombudsperson.

**Comment by acrymble** [comment]
- Maria José Afanador-Llach works in the Fundación Histórica Neogranadina, a non-profit organization digitizing endangered colonial archives in Colombia and promoting digital humanities projects.
Current Teams: Spanish; Ombuds, Community, Board

- Adam Crymble is a lecturer of digital history at the University of Hertfordshire.
Current Teams: Editorial; Community; Board

- Víctor Gayol is a researcher and professor at El Colegio de Michoacán, A.C. (CPI-CONACYT), México, with a PhD in History.
Current Teams: Spanish; Ombuds, Community, Board

- Fred Gibbs is an assistant professor of history at the University of New Mexico.
Current Teams: Editorial; Technical; Board

- Matthew Lincoln is a data research specialist at the Getty Research Institute, and an art historian of early modern Europe. 
Current Teams: Editorial; Technical; Board

- Caleb McDaniel is an associate professor of history at Rice University. 
Current Teams: Editorial; Technical; Board

- Ian Milligan is an assistant professor of history at the University of Waterloo.
Current Teams: Editorial; Ombuds; Board

- Jessica Parr teaches at Simmons College (Boston) and works on PLACE Project at UNH Durham. She is a scholar of the early modern Atlantic.
Current Teams: Editorial; Board

- Antonio Rojas Castro is a researcher a the Cologne Center for eHumanities, with a PhD in Humanities (Spanish Literature).
Current Teams: Spanish; Submissions, Board

- Brandon Walsh is Head of Graduate Programs in the Scholars' Lab in the University of Virginia Library.
Current Teams: Editorial; Board

- Amanda Visconti is Managing Director at the University of Virginia Scholars' Lab DH center, with a Ph.D. in Literature.
Current Teams: Technical; Ombuds; Board

- Jeri Wieringa is a doctoral candidate in history at George Mason University.
Current Teams: Editorial; Submissions; Board

--

Team descriptions:
---

- Community Development - responsible for project outreach.
- Editorial - responsible for editorial work resulting in the review and publication of lessons.
- Ombuds - a person that authors and reviewers can turn to if they have queries or concerns about any part of the peer review and publication process.
- Project Board Member - a fully fledged member of the project team, involved in directing the project's future.
- Spanish - responsible for the Spanish-language version of the project.
- Submissions - first point of contact for authors seeking feedback on lesson ideas.
- Technical - responsible for the technical features that bring the content and peer review to our community.

**Comment by arojascastro** [comment]
Great work! I think I am in charge of the submissions too whereas María and Víctor are both our ombudspersons.

**Comment by mdlincoln** [comment]
With the closing of #379 , is this issue now outdated?

**Comment by acrymble** [comment]
No. #379 was about restricting who was involved in project decisions.

This is about making the Project Team page more informative and useful for readers (and a little less knights of the round).

**Comment by acrymble** [comment]
this can be done in future. We have team changes coming anyway, and it only affect one page

**Comment by acrymble** [comment]
@mdlincoln can we repurpose the lessons sorting features for this Project Team page?

**Comment by mdlincoln** [comment]
I don't see a compelling reason to do so. We don't have 60+ editors.

**Comment by acrymble** [comment]
As a way of seeing all the people involved in a given aspect of the project. Otherwise I can just hardcode it as a list of keywords.

**Comment by acrymble** [comment]
Updated listed (minus Fred and Caleb):

- [x] Maria José Afanador-Llach works in the Fundación Histórica Neogranadina, Colombia.
Current Teams: Spanish Team, Ombuds (Spanish); Board

- [x] Adam Crymble is a lecturer of digital history at the University of Hertfordshire, UK.
Current Teams: Editorial Team; Community Development Team; Board

- [x] Víctor Gayol is a professor at El Colegio de Michoacán, A.C. (CPI-CONACYT), México.
Current Teams: Spanish Team, Managing Editor (Spanish); Board

- [x] Matthew Lincoln is a data research specialist at the Getty Research Institute, USA.
Current Teams: Editorial; Technical; Board

- [x] Ian Milligan is an assistant professor of history at the University of Waterloo, Canada.
Current Teams: Editorial; Board; Ombuds

- [x] Jessica Parr teaches at Simmons College (Boston) and works on PLACE Project at UNH Durham, USA.
Current Teams: Editorial; Managing Editor (English); Board

- [x] Antonio Rojas Castro is a researcher a the Cologne Center for eHumanities, Germany.
Current Teams: Spanish; Managing Editor (Spanish); Board

- [x] Amanda Visconti is Managing Director at the University of Virginia Scholars' Lab DH center, USA.
Current Teams: Technical; Ombuds; Board

- [x] Brandon Walsh is Head of Graduate Programs in the Scholars' Lab in the University of Virginia Library, USA.
Current Teams: Editorial; Community; Board

- [x] Jeri Wieringa is a doctoral candidate in history at George Mason University, USA.
Current Teams: Editorial; Managing Editor (English); Board


--

Team descriptions:
---

- Community - responsible for project outreach & impact.
- Editorial - responsible for editorial work resulting in the review and publication of lessons.
- Ombuds - a person that authors and reviewers can turn to if they have queries or concerns about any part of the peer review and publication process.
- Project Board Member - a fully fledged member of the project team, involved in directing the project's future.
- Spanish - responsible for the Spanish-language version of the project.
- Managing Editor - first point of contact for authors seeking feedback on lesson ideas.
- Technical - responsible for the technical features that bring the content and peer review to our community.

**Comment by acrymble** [comment]
@wcaleb I've tried to make a dev version of this on the submissions site at /project-team but it won't let me visit the URL. Has this been disabled? And if so is there a workaround I can use?

**Comment by acrymble** [comment]
@mdlincoln as the snippets on the project team page are generated from the /authors.yml file, and as these are also used in lesson pages, can I add the tags listed above to this under a new yml thingermabob called 'subteams', and then change the /_includes/contact-info.html accordingly? I want to preserve what we've got but add this new detail.

**Comment by acrymble** [comment]
Not sure if that's clear. My entry would look like this:

- name: Adam Crymble
  github: acrymble
  email: adam.crymble@gmail.com
  twitter: Adam_Crymble
  url: "http://adamcrymble.org"
  team: true
  sortname: Crymble
  subteams: editorial, community, board
  bio:
    en: |
        Adam Crymble is a lecturer of digital history at the University of
        Hertfordshire.
    es: |
        Adam Crymble es profesor de historia digital en la Universidad de Hertfordshire.

**Comment by mdlincoln** [comment]
Sure, that would work fine. You'd want to code it like so (I think `team_roles` is more descriptive than `subteams` FWIW)

```
team_roles:
  - editorial
  - community
  - board
```

Once this is done, we'd need to 

1. Create a data file for these roles so that they can get both EN and ES terms and descriptions
2. Decide how to display the tags on the project team page

**Comment by acrymble** [comment]
I've added those as described. Will mockup a display proposal.

**Comment by acrymble** [comment]
mockup for comment. Also incorporates dates of activity as per #404. Everything from "Community Participants" and below on the existing page would just stay the same. 
![teammockup](https://user-images.githubusercontent.com/646647/28490234-c62023c2-6ecc-11e7-9b61-101b1dc7593c.png)

**Comment by mdlincoln** [comment]
Adam I think this looks great! If we decide to move ahead, this should be relatively simple to implement on the back end.

**Comment by acrymble** [comment]
I've half-done this. I've added the Project Team Membership History and Managing Editor bits, but not the simpified project team descriptions.

I've added an affiliation value for each active team member in preparation for the last phase.

[Update: I haven't touched the Spanish page yet]

**Comment by mdlincoln** [comment]
This is great Adam. Actually displaying the project team descriptions is something that I'd like to structure into the Jekyll layouts of the page (so it's easier to add/change teams AND keep translations in sync) so let me try some drafts of that this weekend?

**Comment by vgayolrs** [comment]
@acrymble : As soon as @mdlincoln  finishes his drafts, I can lend a hand with the Spanish version.

**Comment by mdlincoln** [comment]
Please see the preview available at #541 and add comments on the PR
