### ISSUE TITLE
Investigate a broken link in ES lesson introduccion-map-warper

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3030]
I am preparing to replace a broken link in the ES lesson [Introducción a Map Warper](https://programminghistorian.org/es/lecciones/introduccion-map-warper)
(This fix is not needed on the EN translation)

This is the broken link http://bibliotecanacional.gov.co/es-co/colecciones/biblioteca-digital/mapoteca

It appears that the whole Biblioteca Nacional website is down right now: see https://bibliotecanacional.gov.co/

I will check again tomorrow to determine further action.

**Comment by jenniferisasi** [comment]
Thank you @charlottejmc! I'll keep an eye on this as well. 

Let's as @mariajoafana in the meantime to see if she knows anything or if they have been notified about anything? ¡Gracias!

**Comment by charlottejmc** [comment]
The link for the Mapoteca page found here https://bibliotecanacional.gov.co/es-co/colecciones/biblioteca-digital/mapoteca# is now working again, so I will close this issue!
