### ISSUE TITLE
Board of Trustees Meeting: Friday 10th November 2023 at 14:00 UTC

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#3036]
Date: 10th November 2023
Time: 14:00 UTC ([check your local time](https://everytimezone.com/s/89b6e633))
Zoom link + passcode: already sent by email
Chair: @spapastamkou  
Secretary: @charlottejmc 

## Agenda 

1. Apologies 
2. Approval of [minutes of the 19th July meeting](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/BoT-19-07-2023.md) + Actions Status
3. ProgHist Directors administration (e.g., changes of address)
4. Trustees roles and responsibilities + organizational structure 
5. Publishing Managers' Report (+ Update on Business Plan)
6. Technical infrastructure update (@spapastamkou @anisa-hawes)
7. [New Languages Policy](https://docs.google.com/document/d/1aHsThDD6huy_VZiRKvrUpul2yIwDs-rsyaCHqauRcvc/edit?usp=sharing) (@spapastamkou)
8. 2022/23 Financial year end & Changes to employee pension benefits (@drjwbaker @amsichani )
9. Any other business

**Comment by drjwbaker** [comment]
Papers for Item 8 (2022/23 Financial year end) are at https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/2023-11-10_Item-8_year-end.md (which, in sum, is a short report on our spend last year and agreed changes for 2023/24).

**Comment by spapastamkou** [comment]
Important announcement: for any documents that you have not received prior to the meeting in a reasonable delay, especially the ones Anisa and I work on, please note that I am the guilty part of the affair and assume 100 % responsibility.

**Comment by amsichani** [comment]
hi @anisa-hawes @charlottejmc may I ask you to send me the Zoom link & password for this meeting to my email so I can join? cheers!

**Comment by anisa-hawes** [comment]
Sent by email! Apologies for the confusion!

**Comment by charlottejmc** [comment]
Hello all,

The Minutes of the recent BoT Meeting are available for your review: [2023-11-10_BoT.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/2023-11-10_BoT.md)

Please let me know if you'd like me to make any amendments/additions.

**Comment by charlottejmc** [comment]
Hello all,

The Minutes of the recent BoT Meeting are available for your review: [2023-11-10_BoT.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/2023-11-10_BoT.md)

Please let me know if you'd like me to make any amendments/additions.

**Comment by rivaquiroga** [comment]
Thanks, @charlottejmc!
