### ISSUE TITLE
Updating the Additional Supporters sections of our supporters / colaboradores / nos-soutiens / apoiadores pages

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3039]
Adding former (non-renewing) IPPs to the [Additional Supporters section](https://programminghistorian.org/en/supporters#additional-supporters) of our /en/supporters, /es/colaboradores, /fr/nos-soutiens, /pt/apoiadores pages.

Additional Supporters are defined as _organisations that have or continue to give support_. This enables us to acknowledge our thanks for the former support of:

- [Institute of Historical Research Wohl Library](https://www.history.ac.uk/library-digital), United Kingdom [2020].
- [Software Sustainability Institute](https://www.software.ac.uk/), United Kingdom [2021].
- [Center for Spatial and Textual Analysis (CESTA)](https://cesta.stanford.edu/), Stanford University, United States [2021].
- [Transkribus - READ COOP](https://readcoop.eu/), Austria [2022].
- [RStudio/Posit](https://posit.co/), United States [2022].

This update will also ensure that the headline list of IPPs is current and up-to-date.

**Comment by anisa-hawes** [comment]
Hello @spapastamkou and @rivaquiroga. I think we have discussed this before, but I would like to move forwards by listing the names of withdrawn supporters in the Additional Supporters section, so that the list headed Institutional Partners represents a live list of current IPP members.

(@drjwbaker and I spoke about this recently, and considered the term Alumni Supporters instead of Additional. On reflection, I think Additional still feels right because the University of Sussex Library's support with facilitation of our DOIs is ongoing).

**Comment by rivaquiroga** [comment]
Sounds good to me!

**Comment by anisa-hawes** [comment]
Thank you, @rivaquiroga. At the same time, I'm preparing to update the initial contact name + email address across /en/ipp, /es/pia, /fr/pi, and /pt/ppi as I will be handling all initial enquiries.

**Comment by spapastamkou** [comment]
Thanks for this work, Anisa. It is a detail and it could be done later if this is easier for you; but I think that it would be good in a given moment to move the past supporters in a sort of alumni style presentation, as you mentioned with JBaker. Can we consider create respectively an alumni at a title 3 lever both in IPPS and in Additional to have a clear view of who does what (IPP or additional) and who is still active? Or, if this seems complicated, think of any other way that would not drawn the Library of Sussex among past supporters as their support with DOIs is important for us to acknowledge.

**Comment by anisa-hawes** [comment]
Thank you for these thoughts, @spapastamkou. I've prepared a draft option in PR #3040:

- I've created and Alumni Partners sub-section which is distinct from Additional Supporters
- I've moved (non-renewing) IPPs to Alumni Partners
- I've sub-divided Additional Supporters into active and past

What do you think? (I will ask colleagues to check my translations when we're happy with the draft).

**Comment by spapastamkou** [comment]
Looks fine!
