### ISSUE TITLE
Counting Frequencies from Zotero Items broken link

### ISSUE THREAD

**Issue by twsh** [programminghistorian/jekyll#305]
The link to obo.py in the lesson Counting Frequencies from Zotero Items http://programminghistorian.org/lessons/counting-frequencies-from-zotero-items gives me a 404 error. I looked at http://programminghistorian.org/lessons/counting-frequencies and found a link http://programminghistorian.org/assets/python-lessons5.zip which gives me a zip file which I think has what I need. (Although the `stripTags` function in the version on obo.py in that archive isn't quite the same as in the instructions. And I think that `startLoc`, `endLoc`, and `pageContents` can be removed: currently the latter is being assigned itself.)

**Comment by acrymble** [comment]
Thanks I have updated the link to python-lessons5.zip
