### ISSUE TITLE
Intro to Bash - problem with link

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#307]
Hi everybody:

I'd just translated "Introduction to the Bash Command Line", by Ian Milligan & James Baker, and I noticed that the link to download the War and Peace text file from Gutenberg has changed slightly.

In lesson: http://www.gutenberg.org/cache/epub/2600/pg2600.txt

But the text is at: http://www.gutenberg.org/files/2600/2600-0.txt 

I can edit it in the original lesson in English, but I do not know the collective procedure (sorry, first time doing this).

All the best!

**Comment by ianmilligan1** [comment]
I don't think the link has changed, but rather Gutenberg is throwing up a welcome message the first time you see it. Both lead to the text file itself.  But I like the latter URL better so we can make the change and it might be more stable. 😄

**Comment by ianmilligan1** [comment]
Thanks @vgayolrs !
