### ISSUE TITLE
Single Issue BoT: Financial Year End + Forward Planning

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3071]
Single Issue Board of Trustees Meeting: Friday 1st December 2023 at [15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20231201T153000&p1=1440)
--

Date: Friday 1st December 2023
Time: [15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20231201T153000&p1=1440)
Zoom link + passcode: (see calendar invitation)
Chair: @spapastamkou 
Members: @acrymble @amsichani @drjwbaker @JMParr @rivaquiroga @ZoeLeBlanc
Publishing Manager: @anisa-hawes 
Minutes: @charlottejmc 

>**Document for review**: [Report on Financial Year End 2022/23](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/2023-11-15_Item-8_year-end_v2.md)

---

Hello all,

I'm opening this Issue on behalf of @drjwbaker to represent our forthcoming Single Issue BoT dedicated to Finance.

### Agenda

- 1. [Report on Financial Year End 2022/23](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/2023-11-15_Item-8_year-end_v2.md) 
- 2. Forward financial planning and budget adjustments for 2023/24

_The remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387)._

#### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk guidance on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) we'd like to highlight a few notes about procedures for the meeting:

- Our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- We vote, and in split decisions the chair has the casting vote (Article 10.1)
- We need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))

**Comment by spapastamkou** [comment]
We agreed with @anisa-hawes that she will chair today's meeting (I will be there though)!

**Comment by charlottejmc** [comment]
Dear all,

The Minutes of the recent BoT Meeting are available for your review: [2023-12-01_single-issue_BoT_Minutes.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2023/2023-12-01_single-issue_BoT_Minutes.md)

Please let me know if you'd like me to make any amendments/additions.
