### ISSUE TITLE
adopting standard icons for peer review/license

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#308]
I have come across the following a few times on other sites. I wonder if this is something we can adopt as part of the visual language of projects like ours?

![screen shot 2016-11-29 at 10 15 59](https://cloud.githubusercontent.com/assets/646647/20705966/fca883c6-b61c-11e6-9261-a53c3692a973.png)

The check mark for peer review, and the unlocked license icon in particular. @wcaleb is this an easy addition? Might tie in with @fredgibbs work on refining CSS?

**Comment by drjwbaker** [comment]
@acrymble: I believe it is part of the visual language of Ubiquity Press http://www.ubiquitypress.com/ See for example, any of the articles at http://olh.openlibhums.org/

**Comment by fredgibbs** [comment]
YES, this blends with the upcoming design refresh, as well as adding the last modified lesson time, (which is easy to do with the GitHub API).

**Comment by acrymble** [comment]
I don't think this is going to be in the new design exactly as per the latest work, which addresses the spirit in some other ways. Shall we close this ticket? @fredgibbs

**Comment by fredgibbs** [comment]
I agree: I don't think we need icons in this exact presentation, but I've tried to address the standardization issue, and this look inspired the new footer. So I'll close this and it will be fully implemented in impending style reboot.
