### ISSUE TITLE
Palladio's interface in "Creating Network Diagrams from Historical Sources"

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#309]
In translating and testing the lesson "Creating Network Diagrams from Historical Sources" I noticed an issue.  
Palladio's interface has changed slightly since the original lesson was published.  I've made snapshots of the Figures in the lesson (with the new interface) for the Spanish version. I  was wondering if is worth revising the original lesson and changing the snapshots for new ones with the new interface.
I would add that I was able to follow every step of the lesson without any problems so I don't think that keeping the old snapshots would affect our audience's capability to follow the lesson. Maybe it's only a matter of adding a note explaining that Palladio's interface has changed slightly. In any case, I'll be happy to provide new snapshots of the English version if you guys consider it is necessary to replace all Figures. 
I'm attaching a couple of images so you can compare and contrast some of the changes in the interface. 

![old_palladio](https://cloud.githubusercontent.com/assets/18707866/20775527/616bd63e-b729-11e6-801e-bb4e3e9e980c.png)
![new_palladio](https://cloud.githubusercontent.com/assets/18707866/20775528/61707d42-b729-11e6-85ba-64560e0c5fae.png)

**Comment by acrymble** [comment]
Are you sure it's not a Mac vs Windows thing?

I don't think there's any problem you updating the screenshots. That's part of ongoing maintenance and it's a good thing. But if it's just a matter of you using a different machine than the author then we should leave it.

**Comment by fredgibbs** [comment]
I think the best solution is to leave images or other small outdated things about lessons alone if they don't interfere with following the tutorial, as to preserve as much as the original author's work as possible. I think the best general solution and in this case, too, is the suggestion to have a disclaimer at the beginning that some screen shots may not match perfectly but won't affect anything. That's also true for many if not all the QGIS lessons at this point as well so it will be nice to have a generic solution.

**Comment by ianmilligan1** [comment]
Agreed with @fredgibbs - I think that's a good path forward!

**Comment by mariajoafana** [comment]
I'm not sure if it's a matter of Mac vs Window. Either way @fredgibbs idea sounds like the way to go
Thanks!

**Comment by acrymble** [comment]
closing this because it feels resolved. Reopen if needed.
