### ISSUE TITLE
BoT: Strategic vision + planning for growth

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3098]
Board of Trustees Meeting: Friday 12th January 2024 at [15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20231201T153000&p1=1440)
--

Date: Friday 12th January 2024
Time: [15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240112T153000&p1=1440)
Zoom link + passcode: (see calendar invitation)
Chair: @spapastamkou 
Members: @acrymble @amsichani @drjwbaker @JMParr @rivaquiroga @ZoeLeBlanc
Publishing Manager: @anisa-hawes 
Minutes: @charlottejmc 

>**Documents for review**: 
>- [draft-ph-business-plan-2023-24](https://docs.google.com/document/d/1fQq78otSa-_yltMognAJb9cS_ABjyp_OFQf-UkvoOFY/edit?usp=sharing)
>- [draft-new-publications-queries](https://docs.google.com/document/d/1aHsThDD6huy_VZiRKvrUpul2yIwDs-rsyaCHqauRcvc/edit)
---

Hello all,

I'm opening this Issue to represent our forthcoming BoT meeting dedicated to discussing strategic visions and ideas for growth.

### Agenda

- 1. [Review of draft Business Plan](https://docs.google.com/document/d/1fQq78otSa-_yltMognAJb9cS_ABjyp_OFQf-UkvoOFY/edit?usp=sharing) 
- 2. [Review of working document on handling queries about new publications](https://docs.google.com/document/d/1aHsThDD6huy_VZiRKvrUpul2yIwDs-rsyaCHqauRcvc/edit?usp=sharing)

_The remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387)._

#### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk guidance on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) we'd like to highlight a few notes about procedures for the meeting:

- Our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- We vote, and in split decisions the chair has the casting vote (Article 10.1)
- We need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))

**Comment by charlottejmc** [comment]
Dear all,

The Minutes of the recent BoT Meeting are available for your review: [2024_01_12_BoT.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_01_12_BoT.md).

Please let me know if you'd like me to make any amendments/additions.

**Comment by charlottejmc** [comment]
Dear all,

The Minutes of the recent BoT Meeting are available for your review: [2024_01_12_BoT.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_01_12_BoT.md).

Please let me know if you'd like me to make any amendments/additions.
