### ISSUE TITLE
Spelling mistake in /es/lecciones/analisis-redes-sociales-teatro-1

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#3106]
Found a spelling mistake on [Análisis de redes sociales de personajes teatrales (parte 1)](http://programminghistorian.org/es/lecciones/analisis-redes-sociales-teatro-1) so creating a PR to fix it quick.

**Comment by anisa-hawes** [comment]
Hola @jenniferisasi. What line is the spelling mistake on?
