### ISSUE TITLE
New metadata field for Translation reviewer

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#311]
As the Spanish translations start to come in we need a way to differentiate between lesson reviewers and translation reviewers.

This should be in the YAML block I presume.

**Comment by arojascastro** [comment]
What about "proofreader"? I know that editors and reviewers also check the spelling and language, but my work as a reviewer of the translations consisted in paying attention to style rather than ideas or content.

**Comment by acrymble** [comment]
You might ask the people doing it for you what they think would be appropriate. Proof reader might imply that person is responsible for any typos or formatting errors. Sometimes our formatting might break as we update the CSS, so I would be careful not to choose a name that implies that person is to blame.

**Comment by amandavisconti** [comment]
Separate but related issue—the new YAML I'll be pushing soon has a writing-language item so we can sort by lesson language.

**Comment by arojascastro** [comment]
Hello @vgayolrs and @mariajoafana -- any thoughts on this? Should we go with "translation reviewer" or "proofreader"?

**Comment by vgayolrs** [comment]
Hi everyone!

"Translation reviewer" is most appropriate if we think about what Jairo did
with the Python lessons. I agree with Adam that "Proof reader" may cause
misunderstandings about the responsibilities of who did the translation.

All the best!
Víctor

2017-02-13 2:49 GMT-06:00 Antonio Rojas Castro <notifications@github.com>:

**Comment by arojascastro** [comment]
ok -- but we need to reach a conclusion... :(

**Comment by vgayolrs** [comment]
"Translation reviewer"

2017-02-13 7:32 GMT-06:00 Antonio Rojas Castro <notifications@github.com>:

**Comment by mariajoafana** [comment]
I like "translation reviewers"

**Comment by acrymble** [comment]
This can be closed if you've already started implementing it. Just add a note to the Editorial Guidelines (http://programminghistorian.org/editor-guidelines) and let us know how to start using it.

**Comment by vgayolrs** [comment]
Ok, closing this.

**Comment by arojascastro** [comment]
Can we add a space and a comma after each of the translation reviewers? Se for instance: http://programminghistorian.org/es/lecciones/instalacion-mac

Also I think Adam should be given for being in charge of the reviewing process...

**Comment by arojascastro** [comment]
Sorry @wcaleb but now the Spanish reviewers are gone and the English reviewers are duplicated. Let me know if I can help you.

**Comment by wcaleb** [comment]
Just a small error. Should be fixed shortly.
