### ISSUE TITLE
Sofia stepping down from the FR team

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#3142]
I am stepping down from the FR team and I open this issue to update data and available information on the website.

**Comment by spapastamkou** [comment]
@programminghistorian/french-team La bise:-)

**Comment by marie-flesch** [comment]
Au revoir Sofia ! Et merci encore pour tout :)

**Comment by jenniferisasi** [comment]
Merci, merci pour tout ce que vous avez fait pour PH toutes ces années, @spapastamkou, à bientôt!

**Comment by matgille** [comment]
Merci pour tout Sofia !!! ça a été un plaisir de travailler avec toi. 

Matthias
