### ISSUE TITLE
Rumoured Github pages limit affect us?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#315]
Just came across this on Twitter about new limits on the free Github Pages service.

https://twitter.com/msb5014/status/811252318377230336/photo/1

1GB limit on site size.
100gb bandwidth limit per month
10 page builds per hour.

Do these new limits affect what we're doing in a way that requires us to make a change? I suspect no but I figured I'd raise it in case.

**Comment by wcaleb** [comment]
Not for a while anyway. Our repo is currently around half a gig, by my calculation.
