### ISSUE TITLE
From email: update to wget lesson

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#316]
Bug report submitted via email (and gently edited).

"The wget lesson includes the following:

"You will need to install the ‘Command Line Tools’ kit in XCode. Open up the ‘Preferences’ tab, click on ‘Downloads,’ and then click ‘Install’ next to Command Line Tools. We are now ready to install a package manager.”

i couldn’t get this to work, so had a root around the internet and found this

https://stackoverflow.com/questions/9329243/xcode-4-4-and-later-install-command-line-tools

which seems to suggest that this hasn’t worked for the last few years, the work around suggested in the response worked fine for me."

**Comment by ianmilligan1** [comment]
OK I can take a look!

**Comment by ianmilligan1** [comment]
Fantastic, I ran through the manual install and seems to work well. Mileage may vary as there are so many version of OS X out there, but if it's relatively up to date this should work. Can you please pass along my thanks to the bug reporter, @jerielizabeth?

**Comment by jerielizabeth** [comment]
Will do! Thanks @ianmilligan1
