### ISSUE TITLE
Agreeing our meeting calendar: 2024

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3161]
Hello all,

I am opening this Issue to agree our meetings calendar for the rest of 2024. 

We currently have four core meeting sequences:

1. Project Team Meetings – We agreed last year to meet as a whole Project Team on a bi-annual basis going forwards, in March and September. I've kept to this in the schedule I propose below.
2. Board of Trustees Meetings – These will continue once per quarter. We have had conversations about splitting them into two broad 'themes': 'Business', and 'Strategic Planning'. I've alternated them accordingly.
4. Managing Editors' Meetings – In the past, we have held these once per quarter as well. Following some members' suggestion, however, we could try implementing them every 2 months instead. I've proposed this in the schedule below.
5. Annual General Meeting – Our AGM is once per year, in May.

In each sequence I'm aiming to vary the day of the week, to increase the probability that everyone will be able to attend at least some of the meetings.  Remember, there is no expectation that everyone will be able to attend every meeting. I'll always share minutes internally, so that anyone unable to attend can still understand what was discussed.

Also, members of the Board of Trustees or Managing Editors may request a topic-specific 'Single Issue' meeting in addition to this schedule, if they need to.

I've reviewed the list of holidays/religious days you collectively complied [here](https://github.com/programminghistorian/jekyll/issues/1739). I don't think this calendar presents obvious clashes for 2024, but please let me know if you feel one of the dates I've suggested feels unsuitable. 

Please let me know your thoughts @programminghistorian/french-team, @programminghistorian/portuguese-team, @programminghistorian/spanish-team,  @programminghistorian/english-team and I will begin to send out calendar invitations.

2024
---

**January**
Friday 12th: Board of Trustees Meeting – Strategic Planning [15:30 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240112T153000&p1=1440)

**February**
(No meetings.)

**March**
(No meetings.)

**April**
Wednesday 17th: Managing Editors Meeting [13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240417T130000&p1=1440)
- [x] Calendar invites sent

Friday 19th: Board of Trustees Meeting - Business [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240419T140000&p1=1440)
- [x] Calendar invites sent

**May**
(No meetings.)

**June**
Wednesday 26th: Annual General Meeting [14:00-15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240626T140000&p1=1440)
- [x] Calendar invites sent

Tuesday 18th: Board of Trustees Meeting – Single Issue (Board roles + renewal of terms)
[14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240618T140000&p1=1440)
- [x] Calendar invites sent

**July**
Thursday 18th July: Managing Editors 
[14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240718T140000&p1=198&p2=222&p3=1440&p4=136&p5=195)
- [x] Calendar invites sent

Friday 12th July: Board of Trustees – Single Issue (Arrangements for renewal of Trustees' terms) [13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240712T130000&p1=1440)
- [x] Calendar invites sent

**August**
(No meetings.)

**September**
Friday 20th: Project Team Meeting [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240920T150000&p1=1440)
- [ ] Calendar invites sent

**October**
Friday 4th: Managing Editors Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241004T140000&p1=1440)
- [x] Calendar invites sent

Friday 11th: Board of Trustees Meeting - Business [15:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241011T150000&p1=1440)
- [ ] Calendar invites sent

**November**
(No meetings.)

**December**
Thursday 19th: Managing Editors' Meeting [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241219T140000&p1=1440) 
- [x] Calendar invites sent

**Comment by spapastamkou** [comment]
Is this planning still happening? Some dates are really close but do not seem to have been booked so they may need an update.

**Comment by anisa-hawes** [comment]
Thank you, @spapastamkou. Planning is underway 🙂

**Comment by spapastamkou** [comment]
thanks, @anisa-hawes!

**Comment by anisa-hawes** [comment]
Closing this Issue, to replace it with a new calendar planning the period Sept. 2024 - Aug. 2025
