### ISSUE TITLE
Updating our en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores page

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3162]
I am preparing to update the list of [Individual Supporters](https://programminghistorian.org/en/supporters#individual-supporters) on our en/supporters, es/colaboradores, fr/nos-soutiens, pt/apoiadores page, to reflect the changes in our Patreon supporters.

**Comment by anisa-hawes** [comment]
Closed by #3163
