### ISSUE TITLE
Editorial Meeting Agenda - 27/01/2017

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#317]
Please suggest issues to discuss at the next meeting. Some suggestions from me:

* Spanish Update and planned release timeframe (Maria, Victor, Antonio)
* Lessons page revamp (Amanda) #193 
* Redesign work briefing (Fred) #303, #308, #130, #273, etc. [Fred sends appologies!]
* Subject specialist editor (Adam)
* Outreach Officer (Adam)
* 10 year anniversary (2018) - how to mark?

**Comment by mariajoafana** [comment]
Hi all, I teach a class this afternoon, so I was wondering if today's meeting could start with the Spanish team updates. I'll need to leave the meeting at around 5:45pm (British time).

**Comment by acrymble** [comment]
No problem.

**Comment by acrymble** [comment]
Spanish
- python lessons done. 6 others in progress. (https://github.com/PH-espagnol/borradores/tree/master/lecciones/Python-lecciones-code)
- need a title for translation reviewers (translation-reviewer)?
- collaboration with MA in digital humanities in Colombia (I like this idea).
- when to launch? we'd like to soft launch asap. need to deal with #288 url to be /es... - action @wcaleb 
- Updates needed to Editorial Guidelines: http://programminghistorian.org/editor-guidelines
- main PH text also translated. Need to go live. - action @wcaleb 

Lessons page (Amanda)
- demo provided to team.
- concerns about activity categories. Should we adopt : http://tadirah.dariah.eu/vocab/index.php ?

CSS - fred sends apologies, so we'll discuss next time.

New people - Adam to circulate to team a draft call for new specialist editor & outreach persons

**Comment by vgayolrs** [comment]
Terribly sorry. I was late for the PH meeting because of another meeting
that went on too long.
I take note of the issues addressed for the Spanish site.

All the best

Victor

2017-01-27 11:15 GMT-06:00 Adam Crymble <notifications@github.com>:

**Comment by amandavisconti** [comment]
Spanish lessons = There's a Spanish-language channel on the [DH Slack](http://tinyurl.com/DHSlack) where we could share these.

I'd also be interested in hosting some kind of Slack hangouts for the 2018 anniversary (designate specific lessons where someone will be on the Slack one evening to help people work through the lesson)—I've been meaning to do this for a while anyway.

Explore removing "activity" from front matter and instead associating topics to activities (e.g. when you click on "presenting" on /lessons, you see a list of topics related to that research activity)

**Comment by acrymble** [comment]
closing this. if you need to move any of these conclusions to a ticket, please do so.
