### ISSUE TITLE
Replace 'Gold' with 'Diamond' on our /en/ipp, /es/pia, /fr/pi and /pt/ppi pages

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3175]
I've recently noticed that the text on our /en/ipp, /es/pia, and /fr/pi and pages mentions we publish 'gold open access scholarship' rather than 'diamond open access'. This is a very important distinction because Gold Open Access will usually incur costs to the authors, whereas we are entirely free for readers and authors alike.

I believe /pt/ppi does not specify whether we are gold or diamond open access, but I will take this opportunity to add it in nonetheless.

**Comment by anisa-hawes** [comment]
I'm also taking this opportunity to rephrase the description of our Gold Tier membership offer (making it a more general and open opportunity to collaborate, rather than a specific offer of workshops), and remove an accompanying footnote which isn't any longer needed.
