### ISSUE TITLE
Missing author/reviewer info for "OCR with Tesseract and ScanTailor" lesson

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#318]
Can anyone supply the author and reviewer info for the "[OCR with Tesseract and ScanTailor](http://programminghistorian.org/lessons/OCR-with-Tesseract-and-ScanTailor)" lesson? 

It's not appearing on the /lessons page, possibly because author/reviewer info is missing from _data/authors.yml and _data/reviewers.yml. (Note the lesson file itself says Mila Oiva is the author, but we don't have any other info about them.)

Because this lesson also doesn't seem to have an image for the /lessons page, maybe it wasn't supposed to be published? (I created an image for it to see if that would make the lesson appear on /lessons, but feel free to find something better as I didn't spend much time looking.)

**Comment by fredgibbs** [comment]
It is not supposed to be published. Mila Oiva was indeed the author and Alison was the editor (I handed it off to her early on in the process when I was swamped with other lessons). I don't know why it stalled. After re-reading the lesson, as much as I like the topic, I don't think it's particularly valuable and would need a lot of work to make it publishable (links, etc), and even then I don't see it making a significant contribution. Also, it's significantly tilted towards windows, so it would have be extended to cover Mac uses as well (which includes building from source(!)). I hate to leave work behind, but I think we should move on from this one.

**Comment by amandavisconti** [comment]
Lesson image removed and lesson moved to /deprecated in my new lesson code
