### ISSUE TITLE
Syncing front matter for lessons in various written languages

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#319]
The new /lessons page pulls in lessons using terms written in English like "lesson.difficulty", which will miss lessons for which the front matter is written in another language. How might we address that current and new lessons' front matter, as well as the looping on the new /lessons page, are written in English? How might we keep all languages on PH synced? (e.g. a same-lesson-as variable? a "this front matter item converts to that front matter item" _data file?)

**Comment by fredgibbs** [comment]
this will be handled in impending redesign work, mainly via translations in _snippets file.
