### ISSUE TITLE
How should lessons directory be organized?

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#32]
- alphabetically?
- by category?
- by level of difficulty? (perhaps with an icon to indicate level?)
- by "workflow path"? (that is, do this lesson, and then do this lesson that builds on it, etc.)

**Comment by acrymble** [comment]
This is almost a year old. Anyone want to engage in this discussion, or should we close?

**Comment by fredgibbs** [comment]
i'm closing this because i think we've settled on category--though seeing this thread reminds me that we've been meaning to add some indicator of difficulty level to the lessons. i think that could be a great summer fellow task. i think i'll add a new issue just to add a difficulty level indicator.
