### ISSUE TITLE
Add difficulty ratings for all lessons & reinstate related code

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#320]
Some lessons already have a difficulty rating (between 1-5) set in their front matter, but a number of lessons have "difficulty: 0" to indicate they need to be given a rating.

Once this is done, we can
1. add a sort-by-difficulty button to /lessons
2. restore the "Best for Beginners"/etc. info to the top of each lesson
(I'm willing to do these two follow-up tasks if I'm told the lessons have all been rated, but I don't know the remaining "difficulty: 0" lessons well enough to rate them myself).

**Comment by acrymble** [comment]
It should be between 1 and 3: http://programminghistorian.org/editor-guidelines#add-a-difficulty-indicator-to-the-yaml-file

**Comment by acrymble** [comment]
is there a way for us to see the 0 ones? We made a big list of this a few years ago so I might be able to fill them in.

**Comment by amandavisconti** [comment]
![screenshot_166](https://cloud.githubusercontent.com/assets/899033/22382917/ae6234e4-e495-11e6-81b9-eaa710a2864a.png)
Does this help? (ignore the "occurences found" stuff)

**Comment by acrymble** [comment]
geez I didn't realise we'd dropped the ball on that!

| Lesson | difficulty |
| --------- | --------- |
| code reuse and modularity | 2 |
| counting frequencies | 2 |
| creating an omeka exhibit | 1 |
| creating and viewing html files | 2 |
| extracting keywords | 2 |
| from html to list of words (lessons 1 and 2) | 2 | 
| getting started with markdown | 1 |
| installing omeka | not sure. |
| installing python modules pip | 1 |
| intro to augmented reality | not sure |
| introduction and installation | 1 |
| keywords in context | 2 |
| linux installanation | 1 |
| mac installation | 1 |
| manipulating strings in python | 2 |
| normalizing data | 2 |
| OCR with Tesseract | i dont think this is meant to be published |
| output data as html | 2 |
| output keywords in context | 2 |
| up and running with omeka | 1 |
| viewing html files | 2 |
| windows installation | 1 |
| working with text files | 2 |
| working with web pages | 2 |

related do you need me to find images for all of the python lessons?

**Comment by acrymble** [comment]
I'm basing that on @ianmilligan1 comment in #91 
"in my mind a Difficulty One is something that can be done as a completely self-contained lesson, whereas the others are more advanced or have dependencies"

**Comment by amandavisconti** [comment]
If you'd like them to have images, that would be great. Thanks for the difficulty ratings; I'll add these in.

[x] Add ratings above
Reinstate sort & filter by difficulty to /lessons => now in #193 
[ ] Restore the "Best for Beginners"/etc. info to the top of each lesson

**Comment by amandavisconti** [comment]
Added these locally, will push with #193 code changes

**Comment by amandavisconti** [comment]
Guessed difficulties of:
2 = installing omeka (terminology like SSH, VPS that is defined, but too quickly for an easier difficulty level)
2 = Introduction to Mobile Augmented Reality Development in Unity (lots of dependencies, new concepts)
2 = "From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources"

**Comment by amandavisconti** [comment]
Remaining work on this issue:
[ ] Restore the "Best for Beginners"/etc. info to the top of each lesson (see if @fredgibbs would like to style this in a particular way)

**Comment by fredgibbs** [comment]
the lesson headers are going to be COMPLETELY different--if everyone approves, anyway--so the difficulty level display is being reformatted as well. So I wouldn't add any more text to the top of the lessons. (although, if it's something as a place holder to be incorporated into the design, that's fine).

**Comment by amandavisconti** [comment]
Less work for me—in that case, I'll close this issue. Excited to see the new design work!
