### ISSUE TITLE
Restore previous/next lesson links

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#321]
Once new /lessons page (#193) is up, the previous/if next lesson info (for lessons in a sequence) can be restored. (I removed this as the templating that checked if this info should be displayed was breaking the site.) Should check with Fred first to make sure this works with his new design.

Use this to order lessons on the /lessons page, and fill if/then checks on individual lesson pages for if a lesson has a previous and/or next lesson.

Check whether switching to @wcaleb's new defaults variable setting from using _lessons as a collection solves the endless looping problem.

**Comment by mdlincoln** [comment]
@amandavisconti What is the status of issue?

**Comment by fredgibbs** [comment]
this is done in redesign work.
