### ISSUE TITLE
Managing Editors Meeting: Wednesday 17th April 2024

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3212]
Hello @marie-flesch, @jenniferisasi, @ericbrasiln and @hawc2.

I am opening this Issue to agree an agenda for the forthcoming meeting of MEs.

Date: Wednesday 17th April 2024 **Thank you for accepting my calendar invitation**.
Time: [13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240417T130000&p1=1440&p2=1288&p3=213&p4=198)
Minutes of the last meeting: [12_2023_ManagingEditorsMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2023/Managing-Editors-Meetings/12_2023_ManagingEditorsMeeting.md)
Zoom details: see email.

**April Managing Editors' Meeting**
---

Please add any other items you'd like to discuss:

- Development and launch of a new Reviewers' expression of interest form 
  - Ref: PH-EN-Peer-Reviewer-Form (shared by email)
- Creating plans and documentation for reuse with future Calls for Proposals 
- Updating our `Formulario.Consulta.Leccion.txt`, `Formulaire.Tutoriel.txt`, `formulario.proposta.licao.txt` based on [/forms/Lesson.Query.Form.txt](https://github.com/programminghistorian/jekyll/blob/gh-pages/assets/forms/Lesson.Query.Form.txt)
- Building a shared list of direct contacts and community mailing lists where we can circulate calls for contributions 
   - Ref: `ph-circulation-calls-opportunities.xlsx` (shared by email)
-
-

**Comment by jenniferisasi** [comment]
Thanks @anisa-hawes for organizing this meeting! 

All those items seem good to me, and plenty to talk about :)

**Comment by marie-flesch** [comment]
Yes thank you so much @anisa-hawes for organizing this!

**Comment by hawc2** [comment]
Thanks @anisa-hawes, looking forward to it!

**Comment by ericbrasiln** [comment]
Thanks, @anisa-hawes . It will be a pleasure to take part in my first managing editors meeting.

**Comment by charlottejmc** [comment]
Dear all,

The minutes of the recent Managing Editors Meeting are available for your review: [04_2024_ManagingEditorsMeeting.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/project/Meetings/2024/Managing-Editors-Meetings/04_2024_ManagingEditorsMeeting.md)

Please let me know if you'd like me to make any amendments/additions.
