### ISSUE TITLE
Board of Trustees Meeting: Friday 19th April 2024

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3219]
Board of Trustees Meeting: Friday 19th April 2024 at [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240419T140000&p1=1440)
--

Date: 19th April 2024
Time: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240419T140000&p1=1440)
Zoom link + passcode (see email)
Chair: @spapastamkou 
Members: @acrymble @amsichani @drjwbaker @JMParr @rivaquiroga @ZoeLeBlanc
Publishing Manager: @anisa-hawes 
Minutes: @charlottejmc 
Minutes of the last meeting: [2024_01_12_BoT.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_01_12_BoT.md)

---

Hello all,

**I'm creating this issue to agree the agenda for our next BoT meeting.**
Please feel free to edit or add Items for discussion below.

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf),  I'd like to ask that new agenda Items are added **in advance of the meeting** so that all attendees have sufficient time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions.  

### Agenda

- 1. Apologies 
- 2. Approval of [Minutes from last meeting](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_01_12_BoT.md) & actions status.
- 3. ProgHist Directors administration (e.g., changes of address)
- 4. Publishing Manager's Report @anisa-hawes 
- 5. Trustees' skills survey @spapastamkou 
- 6. Renewal of Trustees’ roles on the Board @spapastamkou 
- 7. Update on Tech Infrastructure Renewal plans @drjwbaker and @anisa-hawes
- 8. Supporting independent community translations under CC-BY @anisa-hawes 
- Any Other Business

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (click 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by charlottejmc** [comment]
Dear all, 

The minutes for this meeting are [available](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_04_19_BoT.md) for your review. Please let me know if you would like to make any comments or amendments.

Thank you!

**Comment by spapastamkou** [comment]
Thanks for your work on the minutes, @charlottejmc.
