### ISSUE TITLE
Add filtering by writing language to /lessons once Spanish lessons in repo

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/jekyll#322]
Once we have Spanish lessons live on the site/located in the main /jekyll repo, I will add sorting by [edit!] {{page.lang}} to the /lessons page

**Comment by wcaleb** [comment]
Right now the Spanish lessons don't have a writing-language field in the metadata. Do these need to be added? This may also relate to #324 (paging @mdlincoln). Right now in the `_layouts` I determine whether the page is in Spanish by checking to see if it is in the `/es/` subdirectory, but perhaps it would be better to make the logic work using a "writing-language" YAML field?

**Comment by mdlincoln** [comment]
It looks like this might be a good place to use Jekyll [_collections_](https://jekyllrb.com/docs/collections/)

You already have all the necessary content in `es` - what's needed is registering that directory _as_ a collection in `_config.yml` (I think that would require renaming the spanish directory to `_es` with a preceding underscore, though. That would create a `colleciton` variable for each of those pages, which could be checked when rendering any of the layouts.

**Comment by amandavisconti** [comment]
The new lessons page uses Jekyll collections (/_lessons), if an example would help: e.g. [the config form the lesson filtering demo site](https://github.com/amandavisconti/proghistdev/blob/master/_config.yml)

**Comment by amandavisconti** [comment]
Oh, and I did put a writing-language field in the new /_lessons front matter (anticipating other languages), but if there's a way to not manually type that into lesson front matter and instead ID it from what collection a lesson is in, that would be awesome.

**Comment by wcaleb** [comment]
Thanks for the tip! I've implemented the `collection` solution in c8ba6c0d6a357f00d6a9826e60f30db221834ce8. Still working out some kinks.

**Comment by wcaleb** [comment]
OK, the kinks are actually pretty serious. As you can see if you look at a page like [this one](http://programminghistorian.org/es/lecciones/contar-frecuencias), or any of the other lessons in the `_es` collection, on rendering the page it is inserting the whole page multiple times at weird points in the HTML. I though the culprit was the `next` and `previous` fields in the YAML, but I took those out of the lesson linked above and it didn't seem to fix the problem. @amandavisconti when I look at your setup, your test site doesn't seem to be having this problem, so I'm a bit stumped.

**Comment by wcaleb** [comment]
The behavior of the `_es` collection was so wonky that I decided to revert the change for now so we can do more localized testing (which I probably should have done from the beginning!). So disregard above comment.  Sorry to spam your inboxes!

**Comment by amandavisconti** [comment]
@wcaleb The next/previous were causing similar repeated loops on my lesson filter work, so I removed them and created an issue (#321) to look at reintroducing them later.

**Comment by wcaleb** [comment]
@amandavisconti With the refactoring I did in https://github.com/programminghistorian/jekyll/commit/6e12c50d43fcc0d3de546dccbeeb986d23bfb0f5, you should be able to access the language of the page with `{{ page.lang }}`. That variable is set by default in `_config.yml` based on the page's path.

**Comment by amandavisconti** [comment]
@wcaleb Awesome!

**Comment by mdlincoln** [comment]
@amandavisconti Given that spanish lessons are now exclusively shown on `es/lecciones.md`, can this issue be closed?

**Comment by fredgibbs** [comment]
while we might eventually want to change the strategy for lesson index display, the issues raised in this thread have been obviated by the way we've settled on storing translated lessons and creating a dedicated lessons index page for each language in the language root directory (the lessons template displays whatever lessons exist in the language's base directory (only / or /es now, obv).
