### ISSUE TITLE
Add lesson images for Python intro lessons

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#323]
As @amandavisconti is redoing the lessons page ( #193 ), the original python lessons really need images to represent them.

**Comment by acrymble** [comment]
Be good to get all in the same style: https://www.flickr.com/search/?text=Whims%20and%20Oddities%2C%20in%20prose%20and%20verse%3B%20with%20forty%20original%20designs

| Lesson | URL of proposed image |
| ----- | ----- |
| Python Introduction and Installation | https://www.flickr.com/photos/britishlibrary/11227236623/in/album-72157641858423503/ |
| Setting Up an Integrated Development Environment for Python for Mac, Linux, or Windows | https://www.flickr.com/photos/britishlibrary/11003025153/ |
| Understanding Web Pages and HTML| https://www.flickr.com/photos/britishlibrary/11002895506/ |
| Working with Text Files in Python | https://www.flickr.com/photos/britishlibrary/11002874005 OR https://www.flickr.com/photos/britishlibrary/11002886545 OR https://www.flickr.com/photos/britishlibrary/11002920616 |
| Code Reuse and Modularity in Python | https://www.flickr.com/photos/britishlibrary/11002923334/ |
| Downloading Web Pages with Python | |
| Manipulating Strings in Python | https://www.flickr.com/photos/britishlibrary/11002906876/ |
| From HTML to a List of Words (part 1) | https://www.flickr.com/photos/britishlibrary/11002759645/ OR https://www.flickr.com/photos/britishlibrary/11003052914 |
| From HTML to a List of Words (part 2) | https://www.flickr.com/photos/britishlibrary/11002818305/ OR https://www.flickr.com/photos/britishlibrary/11002993006 |
| Normalizing Textual Data with Python | https://www.flickr.com/photos/britishlibrary/11002893076/ OR https://www.flickr.com/photos/britishlibrary/11002986954 |
| Counting Word Frequency with Python | https://www.flickr.com/photos/britishlibrary/11002917216/ |
| Creating and Viewing HTML Files with Python | https://www.flickr.com/photos/britishlibrary/11002907123/ OR https://www.flickr.com/photos/britishlibrary/11003047374 |
| Output Data as an HTML File with Python | https://www.flickr.com/photos/britishlibrary/11002926846 |
| Keywords in Context (Using n-grams) with Python | https://www.flickr.com/photos/britishlibrary/11002965274/  OR https://www.flickr.com/photos/britishlibrary/11002990226/|
| Output Keywords in Context in an HTML File with Python | https://www.flickr.com/photos/britishlibrary/11002826505 |

**Comment by acrymble** [comment]
These have been added and appear to be working, but I did get a page build error email when I uploaded the files to github:

The page build failed with the following error:

> unable to build page. Please try again later.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

@wcaleb this was particularly when I uploaded the files to this folder: https://github.com/programminghistorian/jekyll/tree/gh-pages/gallery

I see Allison had already found icons for these (should have checked first), and so now there are .jpg and .png versions of each python lesson. Could that be causing the generic error message? It seems to be loading fine.

I can go in and delete the old icons from Allison, but @wcaleb can you advise before I do?

**Comment by amandavisconti** [comment]
@acrymble If we can use .png title images going forward, those will work with how the new lesson page is pulling in images (I already converted any existing lesson images & will include those in the demo).

**Comment by acrymble** [comment]
ok. I'll change them all. That is already in the editorial guidelines, and I missed it. Sorry.

**Comment by acrymble** [comment]
all converted, and jpg images removed.
