### ISSUE TITLE
HTML language tags for upcoming Spanish release

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#324]
A good-to-have for the upcoming Spanish translations (#280) would be adding language declarations in the top-level HTML tags, and/or in lower-level elements (if there are going to be pages with both languages present): https://www.w3.org/International/questions/qa-html-language-declarations

You'd want to add both `es` but also, of course, `en`, which doesn't seem to be present in the current, English edition of _PH_. This helps out a lot with accessibility, searchability, and discoverability by making it easier for search engines and browsers to understand that the content is in Spanish.

I'm happy to do a PR for this after the soft launch if that helps ease your workload a bit. Implementing it would depend on exactly how you choose to architect different languages within Jekyll's framework.

**Comment by acrymble** [comment]
I suppose this involves this header file? https://github.com/programminghistorian/jekyll/blob/gh-pages/_includes/header.html

**Comment by mdlincoln** [comment]
More likely it belongs in `_layouts`, where you would define whether the entire page is in `es`, or if just the body text is in `es`, depending on whether you're going to be completely translating the headers/footers as well. It'll be easier to figure out the exact implementation once the Spanish lessons are actually added to the repo.

**Comment by wcaleb** [comment]
@mdlincoln There is now a very rough prototype of the Spanish site contained in https://github.com/programminghistorian/jekyll/commit/96db94ff3685fe775ef9b68a3d68ec3b0c052b58. As you can see there, the basic logic will be that anything under the main `es` directory is a Spanish page. There is also an `es` subdirectory in `_includes` for translated includes. I've modified the `_layouts` with "if-then" statements that check to see if the page URL includes `/es/` and then uses the appropriate English or Spanish header or footer. Could we use similar "if-then" statements to put these language tags in the `_layouts`? What would be the best approach, do you think?

**Comment by mdlincoln** [comment]
Liquid if-then statements will work just fine. Given that it looks like @amandavisconti will be using jekyll Categories in the site redesign, the if-then statements should probably be able to reference the `category` tag rather than needing to do a regex on the URL. Once the layout redesign is merged in here, then it'd make sense to finish implementing those if-then statements in the layouts. I'd wait to do that, though, since it looks like @amandavisconti is going to be doing a fair amount of editing of the layout files?

On a related note, though, I looked through the current templates and they could be made quite a bit [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)-er by taking advantage of Jekyll's template inheritance. e.g., `blank.html` would contain the skeleton required by every single page - this would be the only place that you ought to have to include the language if-then statements. `default.html`, `directory.html`, and `post.html` would then all start with the following YAML header:

``` yml
---
layout: blank.html
---
```

That way, instead of having to hard-code the if-then statements, html headers, etc for every layout, you just do it for `blank.html`. The specialized layouts would include any specific markup chunks they need (e.g. author/reviewer lists for `default.html` that shouldn't show up in `directory.html`. All the contents of those nested layouts will just get inserted where  `{{content}}` shows up in `blank.html`

[I did a very rough rewrite (possibly with broken bits!) based on the current `gh-pages` branch, so you can see what this looks like.](https://github.com/mdlincoln/programminghistorian/commit/99a02724050e54b32ccdd8dcf94f3dfc7b87458d) Again, this would need to be re-done with whatever layout edits @amandavisconti is doing.
