### ISSUE TITLE
Investigate broken links in EN data-mining-the-internet-archive and ES mineria-de-datos-en-internet-archive

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3252]
I am opening this Issue to investigate a replacement for broken links in EN [Data Mining the Internet Archive Collection](https://programminghistorian.org/en/lessons/data-mining-the-internet-archive) and ES [Minería de datos en las colecciones del Internet Archive](https://programminghistorian.org/es/lecciones/mineria-de-datos-en-internet-archive)

The problem links relate to several pages from the Library of Congress's website about the marc bibliographic standard:

**data-mining-the-internet-archive**  
` [Library of Congress's MARC 21 Format for Bibliographic Data]: http://www.loc.gov/marc/bibliographic/`
` [rules specified for the 260 datafield]: http://www.loc.gov/marc/bibliographic/bd260.html`
 ` [MARC standards]: http://www.loc.gov/marc/`

**mineria-de-datos-en-internet-archive**  
`[formato MARC 21 de la Biblioteca del Congreso para datos bibliográficos]: http://www.loc.gov/marc/bibliographic/`
`[reglas específicas para el campo 260]: http://www.loc.gov/marc/bibliographic/bd260.html`
`[estándares MARC]: http://www.loc.gov/marc/`

**Comment by charlottejmc** [comment]
After some investigation, I note that all of the Library of Congress's webpages starting with `http://www.loc.gov/marc/` are 'Not Found': 'The requested URL /marc/ was not found on this server' (coupled with a 404 error).

It's unclear whether these pages will be back up anytime soon.

In the meantime, I suggest replacing these links with alternatives:

`http://www.loc.gov/marc/bibliographic/` 
        > `https://www.librarianshipstudies.com/2017/10/marc-21.html`
`http://www.loc.gov/marc/bibliographic/bd260.html`
        > `https://www.oclc.org/bibformats/en/2xx/260.html`
`http://www.loc.gov/marc/`
        > `https://en.wikipedia.org/wiki/MARC_standards`

**Comment by anisa-hawes** [comment]
All pages back online! ✨
