### ISSUE TITLE
Adding a warning box for all lessons using the Old Bailey Online website

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3254]
As agreed in Issue #3169, I am adding a warning box at the start of the lessons affected by the changes to the Old Bailey Online website, to let readers know that some parts of the lesson may not work as described.

- [x] In English:
The Old Bailey Online’s website has recently been updated. Unfortunately, due to the various [changes](https://www.oldbaileyonline.org/about/whats-new), many (if not all) elements of the example website used in this lesson will not work as described. The methodologies taught by this lesson remain relevant, however, and may be adapted by readers to a different example site. We are working on adapting the lesson to the new Old Bailey Online website, but we have no clear timeline on when the lesson will be updated. [April 2024]

- [x] In French:
Le site web Old Bailey Online a récemment été mis à jour. Malheureusement, à cause de ces [changements](https://www.oldbaileyonline.org/about/whats-new), certains éléments utilisés dans cette leçon (voire tous) ne fonctionneront plus comme ils sont décrits. Les méthodologies enseignées dans cette leçon restent tout de même pertinentes, et peuvent être adaptées à un autre site. Nous essayons actuellement d'adapter la leçon au nouveau site Old Bailey Online, mais nous ne pouvons pas encore déterminer quand la leçon sera prête. [Avril 2024]

- [x] In Spanish:
El sitio web de Old Bailey Online fue actualizado recientemente. Desafortunadamente, debido a diversos [cambios](https://www.oldbaileyonline.org/about/whats-new), muchos (si no todos) de los elementos del ejemplo utilizado en esta lección no funcionarán como se describe. Sin embargo, las metodologías que se enseñan en la lección siguen siendo relevantes y los lectores pueden adaptarlas para otros sitios web. Aunque estamos trabajando en adaptar la lección para la nueva Old Bailey Online, no tenemos un cronograma claro sobre cuándo actualizaremos la lección. [abril de 2024]

- [x] In Portuguese:
O site do Old Bailey Online foi recentemente atualizado. Infelizmente, devido às diversas [mudanças](https://www.oldbaileyonline.org/about/whats-new), muitos (se não todos) os elementos do site de exemplo usado nesta lição não funcionarão conforme descrito. No entanto, as metodologias ensinadas por esta lição permanecem relevantes e podem ser adaptadas pelos leitores para um site de exemplo diferente. Estamos trabalhando na adaptação da lição para o novo site do Old Bailey Online, mas ainda não temos cronograma preciso de quando a lição será atualizada.  [Abril de 2024]

**Comment by charlottejmc** [comment]
Hello @ericbrasiln and the rest of the @programminghistorian/portuguese-team,

Would any of you kindly be available to translate the warning message above? 

Thank you very much in advance for your time ✨

**Comment by ericbrasiln** [comment]
Hi @charlottejmc 

Here is the translation:

>O site do Old Bailey Online foi recentemente atualizado. Infelizmente, devido às diversas [mudanças](https://www.oldbaileyonline.org/about/whats-new), muitos (se não todos) os elementos do site de exemplo usado nesta lição não funcionarão conforme descrito. No entanto, as metodologias ensinadas por esta lição permanecem relevantes e podem ser adaptadas pelos leitores para um site de exemplo diferente. Estamos trabalhando na adaptação da lição para o novo site do Old Bailey Online, mas ainda não temos cronograma preciso de quando a lição será atualizada.  [Abril de 2024]
