### ISSUE TITLE
Output for gazetteers' lesson

### ISSUE THREAD

**Issue by Ape3** [programminghistorian/jekyll#326]
Still working with "Using Gazetteers to Extract Sets of Keywords from Free-Flowing Texts", Windows 10 and Python 3.6: The finished code produces a correct list on the screen, which I can integrate into the alumni-sheet by copy/paste - feasible but not a promising way, even with 'only' some six thousand entries - or an outputs.txt with a one line content, which I'm unable to convert into a correct column to be appended to the alumni-spreadsheet. 
Some hints for a beginner would be appreciated, thanks
  ##Andreas

**Comment by acrymble** [comment]
Hi @Ape3 

You'll need to provide more details. What operating system? What software are you using?

Please note that the tutorial says: "This tutorial assumes that you have already installed Python version 2 on your computer", so that may be part of your problem.

**Comment by Ape3** [comment]
My environment is Operating System = Windows 10 and Python 3.6 - that was the version I was proposed to download when recently being looking for python. Should I install an older version? Would Python 2.7.13 make a difference?

**Comment by acrymble** [comment]
I can't promise you any solutions because I don't have your computer in front of me. You might try a mac instead, as I suspect the windows operating system might be the problem rather than the python. If it works on a mac then that helps narrow down the issue.

**Comment by nabsiddiqui** [comment]
There are considerable differences between Python2 and Python3.  I do not know if that is a problem though.  It may be worth going through either way.  Here is a tutorial on how to install both on the same machine in Windows: https://www.youtube.com/watch?v=IX6mc9l6tY4

**Comment by acrymble** [comment]
Thanks @nabsiddiqui that sounds like a good first step, since the lesson is written for Python 2.
