### ISSUE TITLE
GitHub Topics

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#327]
https://github.com/blog/2309-introducing-topics Thought you might find this of interest.

**Comment by ianmilligan1** [comment]
Thanks! 

I went through and just added topics based on our lesson categories as they are:

api
data-management
data-manipulation
data-mining
exhibits
linked-open-data
mapping
network-analysis
pedagogy
programming-historian
python
scraping
text-analysis

Thoughts?

**Comment by jerielizabeth** [comment]
That is pretty cool! If you click on data-mining, PH shows up on an aggregated page with Gensim.

**Comment by ianmilligan1** [comment]
And how! Very cool!
