### ISSUE TITLE
Replace broken ImagePlot download link in introduccion-a-imageplot-y-la-visualizacion-de-metadatos

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3275]
- [x] I am replacing a broken link in the ES lesson [Introducción a ImagePlot y la visualización de metadatos de colecciones de imágenes](https://programminghistorian.org/es/lecciones/introduccion-a-imageplot-y-la-visualizacion-de-metadatos).
The problem link flagged as failed is <https://imagej.nih.gov/ij/?> which has been moved to <https://imagej.net/>.

- [x] Meanwhile, I noticed that links to the Software Studies Initiative <http://lab.softwarestudies.com/> are also failing, and we have replaced this with the new URL <http://lab.culturalanalytics.info/>

- [ ] The download link to ImagePlot is no longer available <http://lab.softwarestudies.com/p/imageplot.html#download>. There are no Releases available on the tool's GitHub https://github.com/culturevis/imageplot, so we are seeking insight into whether the software is still available, and still functional.

**Comment by rivaquiroga** [comment]
It seems that they moved to https://lab.culturalanalytics.info. 
They announced it here: https://web.archive.org/web/20231010083630/http://lab.softwarestudies.com/2016/11/please-use-our-new-wesbite.html

**Comment by charlottejmc** [comment]
Thank you for finding this link @rivaquiroga! Unfortunately it doesn't seem to work either on my side... 

Edit: <http://lab.culturalanalytics.info/> works (http instead of https)

I still need to find an alternative for downloading ImagePlot, since <http://lab.softwarestudies.com/p/imageplot.html#download> doesn't work either...
The new website still links to the old ImagePlot links, which don't work anymore.
The only potential alternative would be using the [GitHub repo](https://github.com/culturevis/imageplot), but I don't see any releases, or other ways of getting ImagePlot. If we were able to find a way, this would mean editing the lesson to include new instructions for users.

This poses the question of whether the lesson actually currently works at all...

Hello @JoshuaGOB – I hope you don't mind me tagging you here as author of the lesson. Do you have any indication of whether ImagePlot is still functional, and how we might let readers download it? Thank you!

**Comment by JoshuaGOB** [comment]
Hi all, This has been on my to do list for longer than I'd like to admit. I'm very sorry for that.

I'm of two minds about this lesson. The macros from ImagePlot are over a decade old and I haven't heard of any interest in continuing the work. If the lesson isn't receiving any attention from readers, would it make sense to retire it?

The other option is to update the language in the lesson to point to the best location for the files. 
- ImagePlot's Repo
- We could host the four files (80kb) 

I'm open to either. What do you think @jenniferisasi

**Comment by anisa-hawes** [comment]
Thank you for your note, @JoshuaGOB. May I ask where the four installation files you mention are available?

If @jenniferisasi feels that this lesson is still relevant and useful to the community, we can certainly investigate our options for hosting these. Are you in contact with the developers of/contributors to ImagePlot?

The key thing is that the lesson is still operable, and (of course!) to test that we need to be able to install the tool.

**Comment by JoshuaGOB** [comment]
Hi @anisa-hawes 
ImagePlot uses a group of macros that do the work behind ImageJ but don't require an actual install:
[ImagePlot.txt](https://github.com/culturevis/imageplot/blob/master/ImagePlot.txt)
[ImageShapes.txt](https://github.com/culturevis/imageplot/blob/master/extras/ImageShapes.txt)
[imageMeasure.txt](https://github.com/culturevis/imageplot/blob/master/extras/imageMeasure.txt)
[ImageSizeReport.txt](https://github.com/culturevis/imageplot/blob/master/extras/ImageSizeReport.txt)

**Comment by anisa-hawes** [comment]
Thank you for explaining, @JoshuaGOB. 

Let us know what you think when you have time, @jenniferisasi ☺️

**Comment by jenniferisasi** [comment]
Hi all, thanks for your patience as I get to this issue. I believe that if the solution @JoshuaGOB proposes works out, we should leave the lesson up for now. Shall we try hosting the files and then trying out the workflow to make sure they work? Thanks!

**Comment by anisa-hawes** [comment]
Thank you, @jenniferisasi. We'll experiment with hosting these four files, and work through the lesson to test it.

**Comment by charlottejmc** [comment]
Hi @JoshuaGOB and @jenniferisasi,

In the branch called `Issue-3275`, I've uploaded the four files to the /assets folder for introduccion-a-imageplot-y-la-visualizacion-de-metadatos. 

However, looking at the [lesson text](https://github.com/programminghistorian/jekyll/blob/Issue-3275/es/lecciones/introduccion-a-imageplot-y-la-visualizacion-de-metadatos.md), I think the section `## ImagePlot` will need to be adapted quite extensively. We can change the first sentence to say: "Los archivos necesarios para ImagePlot se pueden descargar desde [nuestro repositorio GitHub](https://github.com/programminghistorian/jekyll/tree/Issue-3275/assets/introduccion-a-imageplot-y-la-visualizacion-de-metadatos)." (or something like that!). After that, I think we'll need to make some more detailed changes to reflect the new workflow.

If I understand correctly, we won't be asking readers to go through the ImageJ interface anymore, so I imagine sentences like "Al hacer clic derecho en la pantalla de Results aparece un menú [...]" will need to be updated throughout the lesson.

I believe these types of changes are outside the scope of what @anisa-hawes and I might be able to provide (especially in Spanish!) – @JoshuaGOB, would you be comfortable trying some edits, directly within the branch `Issue-3275`? We'll of course assist with typesetting and other publication services when you feel you have it working. 

Do let me know your thoughts!

Thanks very much ✨

**Comment by charlottejmc** [comment]
Hello @JoshuaGOB and @jenniferisasi,

Just checking in with you about this issue – will you have capacity to take a shot at implementing some edits to adapt the lesson to the new ImagePlot files?

Thanks so much! @anisa-hawes and I are always on hand to assist with any queries you may have.

**Comment by anisa-hawes** [comment]
Hola Joshua @JoshuaGOB,

I hope you're well?

Do you still feel that you have capacity to help us update your lesson? 

Please let Charlotte and I know how we can help. We're keen to make it as simple as possible for you to contribute revisions. If you prefer to share suggested updates as comments here in the Issue, we can implement those changes on your behalf.

Charlotte has added the four files to our repo, so the assets will now be hosted locally. We just need your input to adapt the surrounding text, which will make the adapted workflow clear to readers. 

With thanks,
Anisa

**Comment by JoshuaGOB** [comment]
Hi @anisa-hawes I had forgotten to push the changes. I made a branch in the submissions repo and just need another pair of eyes to make sure I didn't miss anything.

**Comment by anisa-hawes** [comment]
Ah... Thank you, Joshua @JoshuaGOB. I can see you've made some edits to the branch Charlotte created here in Jekyll: https://github.com/programminghistorian/jekyll/commit/6988b14f5920477967a511e264a0712572821430, but now also some additional changes in ph-submissions: https://github.com/programminghistorian/ph-submissions/commit/b34d40894dbc8dc2faf5baa295b69326118c541b.

Could you help me consolidate all these changes into the Jekyll branch? (The ph-submission file doesn't need to be updated, as that doesn't represent our version of the published file).

One additional note is that all the existing metadata in the YAML will remain as it is. For example, please be assured that on the header, your middle initial displays with your name as: Joshua G. Ortiz Baco (which is how it is written in our `ph_authors` file). Two lines which we could add to reflect this update + test are:

```
tested_date: 2024-11-07
lesson-testers: Joshua G. Ortiz Baco
```
