### ISSUE TITLE
Adding a new Patron-level supporter to our list of Individual Supporters

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3277]
I am opening this Issue to add the name of our newest Patron-level supporter to [our list of Individual Supporters](https://programminghistorian.org/en/supporters#individual-supporters).

In addition to the significant time and thoughtful energy he already commits to our project, **James Baker** has made an additional and very generous pledge of support. 

On behalf of us all, sincere thanks @drjwbaker ✨

**Comment by jenniferisasi** [comment]
Thank you @drjwbaker !!
