### ISSUE TITLE
Single Issue BoT: Arrangements for renewal of Trustees' terms

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3292]
Single Issue Board of Trustees Meeting: 12 July 2024
--

Date: 12 July 2024 (thank you for indicating your availability via When2Meet)
Time: [13:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20240712T130000&p1=1440)
Zoom link + passcode: (see calendar invite)
Chair: @drjwbaker  
Members: @acrymble @amsichani @spapastamkou @JMParr @rivaquiroga @ZoeLeBlanc
Publishing Manager: @anisa-hawes 
Minutes: @charlottejmc

---

Hello all,

I'm opening this Issue on behalf of @drjwbaker to represent a forthcoming Single Issue BoT dedicated to arrangements for renewal or cessation of Trustees' terms.

### Agenda

- 1. Arrangements for renewal of Trustees' terms
- 2. AOB: how and in what form to discuss IPP rates
- 3. AOB Infrastructure update (Project Manager)

_The remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387)._

#### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (hit 'View PDF' link) and [gov.uk guidance on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) we'd like to highlight a few notes about procedures for the meeting:

- Our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- We vote, and in split decisions the chair has the casting vote (Article 10.1)
- We need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))

**Comment by drjwbaker** [comment]
Many thanks for arranging this @anisa-hawes. I have written to Trustees asking those whose terms are expiring to provide information on their future contributions (with a timeline that allows for collation and circulation of papers prior to the meeting).

**Comment by anisa-hawes** [comment]
Dear Trustees,

The Minutes of the recent Single Issue Meeting are available for your review: [2024_07_12-single-issue_BoT_Minutes.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_07_12-single-issue_BoT_Minutes.md)

Please let me know if you'd like me to make any amendments/additions.
