### ISSUE TITLE
Update analisis-redes-sociales-teatro-2

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3295]
An outside contributor has contacted us to point out some inconsistencies between Figure 5 and the text around it, in [Análisis de redes sociales de personajes teatrales (parte 2)](https://programminghistorian.org/es/lecciones/analisis-redes-sociales-teatro-2). He notes:

> The context surrounding Figura 5 indicates the necessity of showing a directed graph table of "Interacción lingüística". However, Figura 5 shows instead a non-directed graph table of "Coaparición en escena".
> 
> This confusion may stem from the section preceding Figura 5, which states, "Seleccionando la pestaña Aristas del Laboratorio de datos puedes introducir manualmente estas etiquetas, que describen el tipo de relación entre los personajes." It seems that there's a requirement for manual input to modify the relationships between characters, but the specifics of this process are not clearly outlined, leading to potential confusion regarding the content of Figura 5.
> 
> Could you please clarify the intended method for manually inputting these labels, and confirm whether Figura 5 should indeed illustrate a "Coaparición en escena" or an "Interacción lingüística" graph table?

The author of this lesson @dxvidmr has very kindly accepted to help us solve these two questions, coordinated by @jenniferisasi.

**Comment by charlottejmc** [comment]
Hi @dxvidmr,

Thanks again for helping us solve the small issues with this lesson! Do you think you might be able to take a look soon? Do let us know, and we'll be happy to collaborate on it. 

Muchas gracias ✨

**Comment by dxvidmr** [comment]
Hi @charlottejmc ! I apologize for my silence. It's been a hectic week, but I will fix the lesson problems by Sunday. Lo prometo! 😌

**Comment by dxvidmr** [comment]
Hi! Sorry for the wait!! 🫣 I think I've come up with a solution to address the issues brought up in the lesson.

I suggest that paragraph 91 be changed to these two paragraphs:

Gephi ha importado nuestra matriz y la ha transformado en una lista de aristas con un nodo de origen, otro de destino, un tipo de relación, un peso y un `id`. Además, ha creado 11 nodos utilizando como etiqueta el `id` numérico que les asignamos. 

En la nueva lista de aristas importada, que puedes ver en la pestaña **Aristas** del **Laboratorio de datos**, verás que nos faltan los atributos (‘Label’, etiqueta) que sí pudimos importar en en el grafo de coaparición en escena, pues venían ya en nuestro archivo CSV. Nos faltan las relaciones entre los personajes: amor correspondido, amistad, servidumbre, etc. Para poder visualizarlas en este grafo tendremos que introducirlas manualmente en la columna correspondiente (’Label’, etiqueta). Puedes coger esta información de la lista de aristas del grafo no dirigido, teniendo en cuenta que ahora las relaciones están duplicadas y también tendrás, por tanto, que duplicar las etiquetas. Es decir, etiqueta como `amor correspondido` la relación de Belisa (nodo 1) a Don Juan (nodo 6) y también un `amor correspondido` de Don Juan (nodo 6) a Belisa (nodo 1). Y una relación de `amistad` de Belisa (nodo 1) a Celia (nodo 3) y otra relación de `amistad` de Celia (nodo 3) a Belisa (nodo 1). Cuando termines, tu lista de aristas dirigidas debería verse así:

<img width="960" alt="figura5" src="https://github.com/user-attachments/assets/77002bf8-0b82-477d-8bdb-fb9e003065cd">

(New) Figura 5. (We can keep the same alt text and caption.)

And then change paragraph 95 to this new paragraph:

Con las aristas preparadas, ahora vamos a importar los datos referentes a los nodos de los dos grafos. Los pasos ahora son exactamente los mismos para los dos grafos, así que hazlo primero en un espacio de trabajo y luego en el otro:

[...]

And that's all. I explained more explicitly that relationship labels must be entered manually, and I changed the capture to the correct one. Now that I have installed a newer version of Gephi, the menu above looks different. Please let me know if this is a problem and I will try to reinstall the previous version to make the capture more consistent. I don't think it's a big problem, but let me know.

I hope this solves the problem. If not, please don't hesitate to contact me as many times as necessary! 

I don't know if this is a problem we're carrying over from Part 1. It might not be super clear that the relationships between the characters should be included in the edge list for the undirected graph. What do you think?

Sorry again for the delay!

**Comment by jenniferisasi** [comment]
¡Mil gracias @dxvidmr! Me parece que todo está más claro ahora. Tendré que echar un vistazo a la parte 1 a ver si hay que hacer alguna aclaración para los más principiantes. 

@charlottejmc let me know when you're available to incorporate these changes or if I shall do it myself.

**Comment by charlottejmc** [comment]
Thank you so much for providing a solution @dxvidmr! We really appreciate the time you've given to this. 

@jenniferisasi, I'll work on incorporating these changes today, and I'll request your review when it is ready. Do also let me know if you think parte 1 will require any more changes – we can make those in the same branch if needed, before merging.
