### ISSUE TITLE
Proofread Spanish versions of splash pages

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#330]
The Spanish versions of our splash pages (About, Project Team, Contribute, and Research) need to be proofread. There are some Markdown problems on some of them that are affecting the HTML display. Please check the box when each is fixed and if possible reference this issue in any commit message related to it.

- [x] [Acerca-de](http://programminghistorian.org/es/)
- [x] [Contribuciones](http://programminghistorian.org/es/contribuciones)
- [x] [Equipo de proyecto](http://programminghistorian.org/es/equipo-de-proyecto)
- [x] [Investigacion](http://programminghistorian.org/es/investigacion)

**Comment by vgayolrs** [comment]
Ok, I take that.

**Comment by wcaleb** [comment]
Some of the lessons also include links to pages using the `es.programminghistorian.org` form of URLs that we were considering, instead of `programminghistorian.org/es/`, so click through the links to make sure they are working.

**Comment by acrymble** [comment]
Just noticed that Jeri Weiringa is listed as the contact person on
programminghistorian.org/es/ . Is she able to field queries in Spanish?

On Fri, Feb 17, 2017 at 8:59 PM, W. Caleb McDaniel <notifications@github.com

**Comment by arojascastro** [comment]
thats definitely wrong. by the time we translated we hadnt decided yet who would be our contact person... ill change it soon. thanks.

**Comment by vgayolrs** [comment]
thanks @acrymble @arojascastro , working on it.

**Comment by vgayolrs** [comment]
@wcaleb I think I'm almost done. But I have a problem with the page "Equipo de proyecto". We have to translate the biographical data of the project members but we need to have the information in a different space from the original one in English (I suppose). If you guide me with this point I would appreciate it.
On the other hand, in the contributions page there is a first paragraph that we added about collaborating with translations ("Traduce una lección"). I do not know if this is the right place or if it's better to put at to the end. Any thoughts? Also, there is a link to illustrate this paragraph with "translator.png", but I can't find it ( @arojascastro , do you have it?).

**Comment by arojascastro** [comment]
@vgayolrs that image does not exist yet... I just faked the link to the image guessing that we would find an illustration of a translator. @acrymble where did you find those illustrations?

**Comment by acrymble** [comment]
The images are found in online collections. Instructions on finding an appropriate image are in our editorial guidelines: http://programminghistorian.org/editor-guidelines#7-find-an-image-to-represent-the-lesson

It usually involves quite a lot of browsing.

**Comment by mariajoafana** [comment]
I can be the contact person on the Spanish website

**Comment by jerielizabeth** [comment]
Thanks @mariajoafana for taking on the Spanish contact role! Happy to help in any way I can!

**Comment by vgayolrs** [comment]
@wcaleb : proofreading completed. There are another little things to do, but we can close this.
