### ISSUE TITLE
Add redirect_from to metadata of Spanish lessons

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#331]
I recommend that a redirect_from field be added to each of the translated lessons in the `es/lecciones` directory, where the value is the URL of the English version of the lesson, prepended by `/es/`. There's an example of what this would look like in https://github.com/programminghistorian/jekyll/commit/e6200ad1dd4600fd504453a5d6bc60746d381419.

This will make it easier for me to automate links on the English lessons to the Spanish translations, and vice versa. It will also fix the current problems with the Spanish version of the lesson directory, which links to English versions of the URL. (See what I mean by trying to click on any of the lesson links [here](http://programminghistorian.org/es/lecciones/) ... but then click on the link to the "Contar frecuencias de palabras con Python" and see how it redirects!

**Comment by vgayolrs** [comment]
Done. I'm closing this...
