### ISSUE TITLE
Update the Spanish lesson directory

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#332]
Right now all of the images on [the Spanish version of the lesson directory](http://programminghistorian.org/es/lecciones/) are broken because they point to the relative URL `../images/XXXX`, and because the page is inside a subdirectory (`/es/`), the relative URL doesn't work. I'm not sure whether it's worth going through and fixing all of these yet; depending on the outcome of #193 this page may need to be more fundamentally updated anyway. Thoughts @amandavisconti?

**Comment by vgayolrs** [comment]
@wcaleb When I translated this I left the URLs as they were in the English version. The easiest way is to change them by hand with the URLs of the correct pages in Spanish version. I can do it.

**Comment by wcaleb** [comment]
Hi Victor,

I wasn't referring to the URLs so much as the new directory design that Amanda is working on. If we implement the redirect_from metadata mentioned in another issue, then the URLs you have already will work.

**Comment by vgayolrs** [comment]
OK! Thanks!

**Comment by wcaleb** [comment]
Closing for now as I think it's ready enough for the soft launch.
