### ISSUE TITLE
Agreeing our meetings calendar: Sept. 2024 - Aug. 2025

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3325]
I'm opening this Issue to agree our meetings calendar from September 2024 - August 2025. 

There are four core meeting sequences:

**Board of Trustees Meetings** – once per quarter. 
**Project Team Meetings** – bi-annual.
**Managing Editors' Meetings** – once per quarter.
**Annual General Meeting** – once per year.

----

2024
--- 

### September
[no meetings]

### October
**Managing Editors Meeting**
Friday 4th: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241004T140000&p1=1440)
- [x] Calendar invites sent

**Project Team: Insights Gathering Workshops** with Amelia Wakeford
- [x] Invitations + links to sign-up sheet sent
1. Wednesday 16th October [14:00](https://www.timeanddate.com/worldclock/converter.html?iso=20241016T140000&p1=tz_cot&p2=198&p3=tz_clst&p4=213&p5=1440&p6=136&p7=195&p8=133)-15:00 UTC
2. Wednesday 16th October [15:30](https://www.timeanddate.com/worldclock/converter.html?iso=20241016T153000&p1=tz_cot&p2=198&p3=tz_clst&p4=213&p5=1440&p6=136&p7=195&p8=133)-16:30 UTC
3. Thursday 17th October [14:00](https://www.timeanddate.com/worldclock/converter.html?iso=20241017T140000&p1=tz_cot&p2=198&p3=tz_clst&p4=213&p5=1440&p6=136&p7=195&p8=133)-15:00 UTC
4. Thursday 17th October [15:30](https://www.timeanddate.com/worldclock/converter.html?iso=20241017T153000&p1=tz_cot&p2=198&p3=tz_clst&p4=213&p5=1440&p6=136&p7=195&p8=133)-16:30 UTC

### November
**Board of Trustees Meeting** 
Wednesday 27th November 2024 15:00 UTC
- [x] Calendar invites sent

### December
**Managing Editors Meeting** 
Thursday 19th: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241219T140000&p1=1440) 
- [x] Calendar invites sent

2025
---

### January
[no meetings]

### February
**Board of Trustees Meeting**
Friday 7th February 2025 15:00 UTC
- [x] Calendar invite sent

### March
**Managing Editors Meeting**
Week beginning 3rd (Th. 6th, Fri. 7th)
or
Week beginning 10th (Wed. 12th, Th. 13th, Fri. 14th) 
- [x] Poll shared

**Project Team Meeting**
TBA

### April
[no meetings]

### May
**Board of Trustees Meeting**
Friday 9th May 2025 15:00 UTC
- [x] Calendar invite sent

### June
**Annual General Meeting** 
Wednesday 25th
or 
Thursday 26th
- [x] Poll shared with Trustee group

### July
**Managing Editors Meeting**
Week beginning 30th June (Wed. 2nd, Th. 3rd, Fri. 4th)
or
Week beginning 7th (Wed. 9th, Th. 10th, Fri. 11th)
- [x] Poll shared

### August
[no meetings]

**Comment by drjwbaker** [comment]
fyi, we are also likely to need a Trustees meeting (or period of asynchronous discussion/resolution) in mid-Dec once the infrastructure recommendation lands for approval
