### ISSUE TITLE
User Feedback on new lesson directory

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#333]
This ties in with #193 and work by @amandavisconti.

Live demo is here:

https://amandavisconti.github.io/proghistdev/lessons/

--
Tester number 1 - academic in STEM:

Was positive about the attempt to improve usability, and liked the browsing/searching combination options. Specific feedback for improving usability:

1) too much information present on the individual lesson descriptions. Suggests only the title and blurb are needed. Author, date, reviewers are all not needed from a user perspective. Icons are pretty but could be shrunk considerably.

2) Liked the 'acquire, transform, analyze, present, sustain' labels. Thought that was a useful way in. Also liked the categories (except 'original programming historian' which is random and not user-centric). Wanted to be able to do faceted browsing like on British History Online site (http://www.british-history.ac.uk/search/subject/historical-geography/place/london).

3) Strongly opposed to listing all of the lessons at the bottom because that makes the scroll bar daunting. Wanted numerical indication of how many results you have after your browse/search (7 results, or 7 out of 56 lessons match your criteria).

4) Suggested revise text at top: "We invite you to browse around. If you can’t find a skill, technology, or tool covered here, please let us know!" to "We invite you to browse. If you can’t find a skill, technology, or tool covered here, [please let us know!](LINK)"

5) Suggested revised text in second sentence to "sustain my humanities data" instead of just "humanities data".

6) "Reset to see all lessons" should be a button.

7) Search results are too far below the fold. Need to put the content at the top in left margin to bring results up.

8) Order of results suggested by reverse chronological order of publication date.
--

**Comment by acrymble** [comment]
User Two: Digital Humanities Scholar

1. I like the design of the old page better (I think it’s the font type) - this is just a preference;

2. I didn’t see the lessons list when I’m seeing the “help me acquire, etc”. So the first time I clicked in one of the buttons, I didn’t see anything happening. Because the changes were occurring below. Then I figured it out, but maybe you want to give a sign to the user, for example if I click on analyse, then this button stays blue and the others grey (or any other sign that tell user things are changing), then maybe the user seeing a change would scroll down;

3. Overall, I prefer the new structure, because it organises the content better. I was wondering for some time, if it is possible to have a “path of all the lessons”. If someone would like to go through all the lessons, which should he do first, second, etc. I’m asking this because I was trying to learn from the website and I was using your post (http://adamcrymble.blogspot.pt/2014/08/learning-python-with-programming.html) where you recommend the order one should follow, but it doesn’t have all the lessons. Some of the lessons are not connected also, so I’m not sure if my suggestion makes sense. Maybe when you click on a subject (“Python” for example), they could appear ordered? In case of Python, installation is the 6th one.

**Comment by acrymble** [comment]
User Three: User of PH

1. The filter buttons need to be responsive, users with smaller screens won't notice the changing articles.
2. I very much like the goal-oriented categories, but mayhaps they shouldn't necessarily be in a sentence? What's more, on my 14' laptop, the sentence spills over to another line.
3. As a side note, I have no clue as to the demographics of the DH world, but from my experience with fellow students, the terminology might scare people off, as opposed to the old design, whose plain-text design is a bit more inclusive.
4. It's not entirely clear, intuitively, how the filters relate to the groups anchor links.
5. The lesson blocks look wonderful and inviting, and I'm glad you're keeping the etchings. Won't they be a bit more inviting if they fitted on a single page?
6. Perhaps a skill-based filter might be suitable? Lessons like the markdown intro, the QGiS primer and the RegEx one are much less intimidating ones whose titles a first timer can't even understand (JSON with jq, for instance)
7. I assume the googleFont issue is known, but having Verdana as a fallback seems a strange choice. San-serif looks much much better, and is closer to Lato.

**Comment by acrymble** [comment]
User Four: DH Scholar:

First of all, the idea to allow us to browse among lessons in a faceted way is be fantastic! (is a faceted search option, right?)

- I like the idea to add the possibility of navigating among the “action tags": acquire, transform, analyze.. But from my screen when I click to any of the categories nothing changes, so a user could feel that something is going wrong. Then, I scrolled down the page and I realized that something was happening, the tags were filters as  expected.
 

- Maybe the option to have a hue effect on the "action tags” buttons that let the users to select or deselect them would be a good complement to the option “Reset to see all lessons”, a good option to filter by a customized combination

- Why are the “topics tags” and the “action tags” so separated (speaking of design). Maybe you could use a similar design (buttons in different colors, for example, with a short title explaining the difference between them)

- I’d prefer to see the search bar in a common place, like upwards on the right, for example. But I don’t know if it’s something just for me or if it’s commonly accepted

- It would be super useful to have a menu on the up left part of the screen with the lessons structure to go straight to the exact content people are searching for (the subtitles from the lessons, for example)

- Another thing useful is having related articles linked in any of the lessons, specially if the lessons are speaking about new versions of the software or new ways to do the same thing, technologies are changing a lot these days and something may need an update, to have it linked from the original article would be awesome!

- I know that the infinite scrolling si fashion now, but I think that seeing the lessons as a grid (as you did in your former interface) with the main information (the description could be activated when the user drags the mouse on every lesson’s block) instead of seeing them as a list with a lot of scrolling would be nice.

**Comment by acrymble** [comment]
@amandavisconti can I invite you to respond to these, and get a sense of what's possible/desirable?

Summary of suggestions:

**Design Comments**

There were a number of comments related to the design of the top section in particular. Most if not all should be easily addressed:

- [x] List of results is too far down the screen
- [x] Too much scrolling needed - suggested getting rid of the full list at the bottom. Too daunting. Some numerical indicator of how many lessons would be good (7 of 56 match your criteria).
- [x] Facets/Buttons should change visibly (grey/blue) when activated/unactivated.
- [x] Thinks that DO something should be buttons (reset, the categories).
- [x] Search box in unusual spot - suggested top right (also note, what does this search? full text? just titles?)
- [x] Should make use of left margin for faceting.
- [x] Suggestions for tweaking language.
- [x] Suggested that there is too much info in the descriptions (authors/reviewers/date not pertinent for users; images too big)
- [x] Suggested change of font
- [x] One user expressed preference for grid-style rather than list-style.

**Structure Comments**
**AV: #321 will address these, and I'll switch to reverse chronological order in the meantime.**
- [x] Desire to know possible/suggested 'paths' through the lessons. Difficult to tell at present. => 
- [x] If a 'path' is an option, lessons should appear in the list in the suggested order (eg, intro to python before later lessons). Otherwise suggested as reverse chronological order by publication date, so newest material at top.

**Comment by amandavisconti** [comment]
@acrymble Thank you and the reviewers for all this! Very useful. I'll work on a response.

**Comment by amandavisconti** [comment]
_(Checked off items above as I included them here, or added comment above on other action.)_

@fredgibbs, the following user-testing suggestions seem like they might fall under your CSS/styling work—if any do not (or you otherwise don't want to work on them), let me know and I can add them to my task list!:
[ ] Suggested change of font
[ ] One user expressed preference for grid-style rather than list-style
[ ] Suggested that there is too much info in the descriptions (authors/reviewers/date not pertinent for users; images too big)
[ ] Search box in unusual spot - suggested top right (also note, what does this search? full text? just titles?)
[ ] Should make use of left margin for faceting
[ ] Suggestion to keep any link that does something as a button rather than a normal hyperlink
[ ] Facets/Buttons should change visibly (grey/blue) when activated/unactivated
[ ] List of results is too far down the screen

I moved the following to my plate over on #193:
- Suggestions for tweaking language.
- [alternative to reverse chronological ordering](https://github.com/programminghistorian/jekyll/issues/193#issuecomment-281208539)
- Search box: what does this search? full text? just titles? (way to indicate which?)
- Things that DO something should be buttons (reset, the categories).
- Too much scrolling needed - suggested getting rid of the full list at the bottom. Too daunting. - - Some numerical indicator of how many lessons would be good (7 of 56 match your criteria).

**Comment by fredgibbs** [comment]
yes! mostly, i am indeed working on these. i think that
[ ] List of results is too far down the screen
is similar to "too much scrolling needed" so i'm going to leave that to you, @amandavisconti, but the others will be handled in my ongoing work.

**Comment by fredgibbs** [comment]
actually, now that i've posted that, i see how i probably misunderstood the comment, so nevermind. they are all on my list!

**Comment by amandavisconti** [comment]
Closing this as it sounds like @fredgibbs and I both have our to-dos from this user-testing listed on other issues (mine are #193, #320, #322). Thanks again to @acrymble and all for exploring and suggesting!
