### ISSUE TITLE
Add warning box about PDF availability in /en/generating-an-ordered-data-set-from-an-OCR-text-file & /fr/generer-jeu-donnees-texte-ocr

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3332]
We've received feedback by a user of [en/generating-an-ordered-data-set-from-an-OCR-text-file](https://programminghistorian.org/en/lessons/generating-an-ordered-data-set-from-an-OCR-text-file) that the example document used in the lesson (indexed on WordCat as [Il Cartolare di Giovanni Scriba](https://search.worldcat.org/title/17591390)) is not open access, and difficult to locate even through an institutional library. 

This outside contributor was able to access a different edition of the text through their institutional library, and has made a `.txt` version of it available to us. 

We may want to:
- Find and host the original `.pdf` and `.txt` files used in the lesson, although this may prove to be impossible or restricted by copyright (@hawc2, for example, the text is available through Temple University according to the WorldCat entry – perhaps you might be able to check whether we could legally download it and host it on here?) 
- Add a warning box informing users that while we can't provide access to the exact document, they can use any other corpus and apply the same methods. This will increase the lesson's difficulty, which is already set to High.
- Link to the `.txt` file created by the outside contributor, accompanied by a warning box to inform readers that because the text is a different edition, small changes may be required. The contributor noted that 'small changes to the code were needed', and we could ask them for more details.

**Comment by charlottejmc** [comment]
I was able to locate a [PDF of the original text](https://notariorumitinera.eu/NI_vs_contenitore.aspx?Id_Scheda_Bibliografica_Padre=4421&Id_Progetto=6) used in the lesson, from the same edition. @anisa-hawes and I have decided to host the PDF on GitHub (in the lesson's assets folder) and link to it from the lesson body.

**Comment by charlottejmc** [comment]
Unfortunately, the PDF is much too large to be hosted on GitHub. While we can usually upload our larger assets to Zenodo, it does not make sense in this particular case, because Zenodo assigns a DOI (and thus authorship) to all files, yet we are not the creators of this particular asset.

Instead, we found a suitable solution to be creating a [Perma.cc link](https://perma.cc/AKY5-MMUQ) for the PDF and linking to it from within the lesson body.

**Comment by charlottejmc** [comment]
Just noting here that while perma.cc can capture the PDF, the file cannot be downloaded...
@anisa-hawes explains that there are other web archiving tools which _can_ capture PDFs so they are downloadable, perma.cc doesn't do this. 

For now, I'm exchanging the perma link for the standard link to the PDF.

**Comment by charlottejmc** [comment]
Dear @Lucia-Michielin, I'm tagging you here to let you know that we found a PDF of the text used in this lesson (in the same 1935 edition!). We've now updated the lesson to include a link to it, so that readers can easily download and manipulate it. 

Thank you very much for flagging this issue when you did. We really appreciate your contribution!

Charlotte and Anisa ✨

**Comment by Lucia-Michielin** [comment]
Dear Charlotte and Anisa,
This is a very good news!

Best Wishes,

Lucia

Il giorno gio 1 ago 2024 alle ore 17:39 charlottejmc <
***@***.***> ha scritto:
