### ISSUE TITLE
RSS feed too greedy?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#334]
I just noticed the following page appeared in our RSS feed:

http://programminghistorian.org/es/translation-list

I don't think we intended that to go out via RSS, so perhaps this needs some tweaking.

**Comment by vgayolrs** [comment]
Deleted from https://github.com/programminghistorian/jekyll/tree/gh-pages/es. This file is for internal control use only in https://github.com/PH-espagnol/borradores
Thank you for notice that @acrymble . I close the issue.
