### ISSUE TITLE
Board of Trustees Meeting: Wednesday 27th November 2024

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#3383]
Board of Trustees Meeting: Wednesday 27th November 2024 at [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241127T140000&p1=1440)
--

Date: 27th November 2024
Time: [14:00 UTC](https://www.timeanddate.com/worldclock/converter.html?iso=20241127T140000&p1=1440)
Zoom link + passcode (see email)
Chair: @drjwbaker
Members: @acrymble @amsichani  @JMParr @rivaquiroga @ZoeLeBlanc
Publishing Manager: @anisa-hawes 
Minutes: @charlottejmc 
Minutes of the last meeting: [2024_07_12-single-issue_BoT_Minutes.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_07_12-single-issue_BoT_Minutes.md)

--- 

Hello all,

In line with Trustees' duties, as summarised in [Section 2 of The Essential Trustee Guidance](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/866947/CC3_feb20.pdf), please add new agenda Items are added **in advance of the meeting** so that all attendees have sufficient time to prepare their thoughts ahead of our meeting. Thank you for committing energy to your role, and thank you in advance for actively participating in our discussions.  

### Agenda

1. Apologies [AH] {2 mins}
2. Approval of Minutes from last meeting & actions status [AH] {5 mins}
3. ProgHist Directors administration (e.g., changes of address) [JB] {2 mins}
4. Chair's report: recognising our differences and reaffirming [our responsibilities](https://www.gov.uk/government/publications/the-essential-trustee-what-you-need-to-know-cc3) [JB] {10 mins}
5. Trustee Tasks: updates and milestones {10 mins}
    a. Publishing Manager Line Management [AC]
    b. Editorial Guidelines [RQ]
    c. Charity Law, HR, and Vision [AMS]
6. Business Plan [JB/AH] {10 mins}
7. Publishing Manager's Report [AH] {10 mins}
8. Any Other Business {5 mins}
9. Date of next meeting {1 min}

Note, the remit of the Board of Directors is restricted to the terms of ProgHist Ltd, which - broadly speaking - supports the the financial and legal business of The Programming Historian and its Members (that is, the Editorial Board https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-538298387).

### Notes

Per our [Articles of Association](https://beta.companieshouse.gov.uk/company/12192946/filing-history) (click 'View PDF' link) and [gov.uk notes on running a company](https://www.gov.uk/running-a-limited-company/company-and-accounting-records) a few notes in terms of procedure for the meeting:

- our quorum is 3 (Article 9.1) and our max size 7 (Article 13)
- we vote, and in split decisions the chair has the casting vote (Article 10.1)
- we need to keep records of decisions (Article 12) and resolutions ([GovUK](https://www.gov.uk/running-a-limited-company/company-and-accounting-records))**

**Comment by anisa-hawes** [comment]
Dear Trustees,

The Minutes of the November BoT Meeting are available for your review: [2024_11_27_BoT.md](https://github.com/programminghistorian/project-and-business-archive/blob/master/charity/Board-of-Trustees-Meetings/2024/2024_11_27_BoT.md).

Apologies for the extended delay. Please let me know if you'd like me to make any amendments/additions - I can do that in the New Year.
