### ISSUE TITLE
Keeping track of proposed lessons

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#339]
Suggestion from @fredgibbs for keeping track of (and following up on) proposed lessons that come in, as a number of these fail to materialise. The suggestion is to create a ticket on the submission site (https://github.com/programminghistorian/ph-submissions) when a new proposal comes in, outlining the basics of what's been agreed, listing the name of the author, and giving a 3 month window to write, after which time they will be contacted by the managing editor to see if they plan to follow through. We hope this will help us keep track better and also to encourage greater completion rates.

Suggested text for those tickets:
---

The Programming Historian has received the following proposal for a lesson on 'PROVISIONAL LESSON TITLE' by AUTHOR(S) NAME(S). This purpose of the lesson is to:

* key learning outcome 1
* key learning outcome 2
* key learning outcome 3 (add as needed)

In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than [90 DAYS BY DEFAULT BY LONGER IF AGREED WITH EDITOR]. The author(s) agree to contact the editor in advance if they need to revise the deadline.

If the lesson is not submitted within the AGREED PERIOD, the editor will attempt to contact the authors. If they do not receive an update this ticket will be closed and the topic may be pursued by another author.

The main editorial contact for this lessons is [EDITOR USERNAME]. If there are any concerns from the authors they can contact the Ombudsperson [OMBUDSPERSON USERNAME].

---

Once we're happy with this (please revise as you see fit), we will have to update the Author and Editorial guidelines

http://programminghistorian.org/new-lesson-workflow
http://programminghistorian.org/editor-guidelines

I suppose we'd want to make it clear that you don't HAVE to pre-propose and wait 90 days. This is just for those people who reach out.

**Comment by fredgibbs** [comment]
this looks good to me! although i don't think we need to say that the topic could be pursued by another author, since the general topic could always be pursued by someone else as long as the learning outcomes were different. i vote to say the ticket will be closed and can be reopened if the author decides to take up the lesson again.

**Comment by jerielizabeth** [comment]
This sounds interesting to me as a way of keeping track of the proposed lessons.

I assume it would be the role of the primary corresponding editor (me currently) to create these?

**Comment by acrymble** [comment]
Whomever they approach I suppose. But yes, I guess it would mostly be you while you're in that role. Is that no good?

**Comment by jerielizabeth** [comment]
That is fine by me! Shall I give it a try with a few and see how it goes?

**Comment by acrymble** [comment]
Ok with me. You'll have to tell the authors that's the plan of course.

**Comment by jerielizabeth** [comment]
First test at https://github.com/programminghistorian/ph-submissions/issues/54

**Comment by acrymble** [comment]
should we put the template you used somewhere and close this ticket? Editor's guidelines?

**Comment by jerielizabeth** [comment]
Created new ticket for implementing this system.
