### ISSUE TITLE
Linear Regression tutorial

### ISSUE THREAD

**Issue by mlplace** [programminghistorian/jekyll#3403]
In the following code, it's unclear as least to me where the date_labels  parameter to the SelectKBest().fit_transform comes from.

from sklearn.feature_selection import SelectKBest, f_regression
Z_new = SelectKBest(f_regression, k=3500).fit_transform(Z, date_labels)

**Comment by mlplace** [comment]
Would this be correct?  date_labels = df_all['yearDecimal']

**Comment by anisa-hawes** [comment]
Thank you for getting in touch, @mlplace.

We appreciate you letting us know that you encountered a problem when working through the lesson [Regression Analysis with Scikit-Learn (part 1 - Linear)](https://programminghistorian.org/en/lessons/linear-regression).

I'd like to ask if you could share some details to help us understand the context:

- [ ] The system you are using (Mac, Linux, Windows)
- [ ] Version numbers of the relevant software you are using
- [ ] The exact steps you took that caused the problem

**Comment by anisa-hawes** [comment]
Hello @mlplace,

As we haven't heard from you, I'll close this Issue.
If you do want to share some further information [(as outlined in my comment above)](https://github.com/programminghistorian/jekyll/issues/3403#issuecomment-2473038785), we can reopen this report. We aren't able to provide personalised troubleshooting support, but if you think there is a general problem or error within the lesson's code we can investigate.

With thanks.
