### ISSUE TITLE
Replace 2x broken links in /en/lessons/introduction-to-populating-a-website-with-api-data + /en/lessons/json-and-jq

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/jekyll#3413]
I am opening this Issue to investigate broken links in the EN lesson [Introduction to Populating a Website with API Data](https://programminghistorian.org/en/lessons/introduction-to-populating-a-website-with-api-data) and [Reshaping JSON with jq](https://programminghistorian.org/en/lessons/json-and-jq).

Both are links to objects in the Rijksmuseum collection.

The problem links are: 
- https://www.rijksmuseum.nl/nl/collectie/RP-P-OB-84.508 
- https://www.rijksmuseum.nl/nl/collectie/SK-C-5

I can find the images via queries: 

- https://www.rijksmuseum.nl/nl/collectie/object/Aanval-van-een-Engels-schip-op-drie-Franse-schepen-bij-Sint-Eustatius-1758--01bf1416e7dbd101013da941d85042a7?query=RP-P-OB-84.508&collectionSearchContext=Art&page=1&sortingType=Popularity
- https://www.rijksmuseum.nl/en/collection/object/The-Night-Watch-Militia-Company-of-District-II-under-the-Command-of-Captain-Frans-Banninck-Cocq--3137deb45cd7765f9a76084a16c99544?query=SK-C-5&collectionSearchContext=Art&page=1&sortingType=Popularity&tab=data

But when I search by the object numbers, I find that even the provided persistent links do not work at the moment.:

- RP-P-OB-84.508 (persistent URL: https://id.rijksmuseum.nl/200523944)
- SK-C-5 (persistent URL: https://id.rijksmuseum.nl/200107928)

I therefore suspect this may be a temporary issue on the Rijksmuseum website, so will check back in within the coming days.

**Comment by charlottejmc** [comment]
The original links are working again and I was able to [run the build successfully](https://github.com/programminghistorian/jekyll/pull/3401), so I'll close this issue now. Thank you! ✨
