### ISSUE TITLE
Fix freeyourmetadata links in 7 files

### ISSUE THREAD

**Issue by charlottejmc** [programminghistorian/jekyll#3425]
The link http://freeyourmetadata.org/ is broken in en/intro-to-linked-data, es/introduccion-datos-abiertos-enlazados and pt/introducao-dados-abertos-conectados.

The site seems insecure: clicking on the link leads to "sub" URLs like http://ww16.freeyourmetadata.org/?sub1=20241211-1407-17ab-8d35-0be26e16d6f6, or alternatively https://ww25.freeyourmetadata.org/?subid1=20241211-1403-1976-8243-3dec620b88e1.

I will look more into this.

**Comment by charlottejmc** [comment]
Update: the build has passed upon re-running jobs, without editing the links.

**Comment by charlottejmc** [comment]
Reopening this issue because another freeyourmetadata.org link has broken a build.

However, just like above, the second build attempt ended up being successful...

**Comment by anisa-hawes** [comment]
Thank you, @charlottejmc. On my side, the homepage <http://freeyourmetadata.org/> generates a security risk warning, and Chrome doesn't open the page .... So I think we will need to remove this link from the lessons.

We could also contact the authors to ask if they'd like to share an alternative, but it doesn't appear to be critical (the authors share the citation to the book in the bullet above).

**Comment by charlottejmc** [comment]
I will temporarily remove the links from the following lessons:

- [x] en/cleaning-data-with-openrefine
- [x] en/intro-to-linked-data
- [x] es/introduccion-datos-abiertos-enlazados
- [x] es/limpieza-de-datos-con-OpenRefine
- [x] fr/nettoyer-ses-donnees-avec-openrefine
- [x] pt/introducao-dados-abertos-conectados
- [x] pt/limpar-dados-openrefine
