### ISSUE TITLE
implement nav bar with dropdowns 

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#346]
proposed nav structure (precise nav headers will be decided later, but here are the topics):

Home
About
--What and Why
--Research
--Project Team
Lessons
--(could have subpages that brought up a default view, like newest, most popular, whatever)
Contribute
--Provide Feedback
--Write
--Review  
--Edit
Blog

**Comment by acrymble** [comment]
Spanish too.
@arojascastro has also added a 'Translate' under 'Contribute'.
