### ISSUE TITLE
Translate Spanish versions of author bios

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#354]
As noted on #348 by @vgayolrs: right now "the authors bio data will be displayed in English, i.e.: "William J. Turkel is Professor of History at the University of Western Ontario", instead of "William J. Turkel es profesor de Historia en la Universidad de Western Ontario""

**Comment by wcaleb** [comment]
Everyone please note important change in this commit: the author bios in `authors.yml` are now broken into `en` and `es`.

@vgayolrs @arojascastro @mariajoafana Whenever you finish translating a lesson, you'll need to go in to `_data/authors.yml` and create an `es` version of the author's bio, as I have done already for William Turkel and Adam Crymble. Please note that the white spacing in this file is very important, so be sure to indent following the examples of Turkel and Crymble, and use spaces instead of tabs. I have also updated the Editor Guidelines to reflect this change.

**Comment by mariajoafana** [comment]
Thanks @wcaleb , we'll keep this in mind

**Comment by acrymble** [comment]
This seems to be causing a bug on the English page at the moment: http://programminghistorian.org/project-team
![screen shot 2017-03-02 at 15 15 25](https://cloud.githubusercontent.com/assets/646647/23513553/5b03b44e-ff5c-11e6-8561-e53f2ee17086.png)

**Comment by wcaleb** [comment]
Good catch. Fixed in 03e492082b3e15957b70b1358c2bd13834e38bbc.
