### ISSUE TITLE
Make date string on lessons language-independent

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#355]
As noted in #348 by @vgayolrs, right now our date string at the top of the lessons and in suggested citations contains the English words for months.

We could easily change the date format so that it only includes numbers (like 02-14-17), but would we then run into problems in differences between USA norm (MM-DD-YY) and international norm (DD-MM-YY)?

The only other way I can think to do this would be to hard-code a Spanish date into the YAML of each lesson. 

Thoughts?

**Comment by acrymble** [comment]
Could adopt YYYY-MM-DD.

**Comment by wcaleb** [comment]
Good idea @acrymble. Is there anywhere that wouldn't be recognizable? If not, then that might be the easiest thing to do. Thoughts @vgayolrs @arojascastro @mariajoafana ?

**Comment by arojascastro** [comment]
I am not really picky on this kind of issues. I am more concerned on language issues and translation quality - so its up to others.

**Comment by mariajoafana** [comment]
I think adopting YYYY-MM-DD is a good solution.
