### ISSUE TITLE
Spanish Wikipedia links?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#356]
Just noticed that the following lesson has a link to the English wikipedia page for UTF-8.

http://programminghistorian.org/es/lecciones/instalacion-windows

There appears to be a Spanish version of this page.

https://es.wikipedia.org/wiki/UTF-8

Has this been intentionally left with the English link? I just wanted to let you know in case that was a mistake.

**Comment by vgayolrs** [comment]
Thank you @acrymble
