### ISSUE TITLE
Spanish Lesson - zip asset not found

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#359]
The Zip file at the end of the following lesson leads to a 404 error:

http://programminghistorian.org/es/lecciones/trabajar-con-paginas-web 
http://programminghistorian.org/es/lecciones/manipular-cadenas-de-caracteres-en-python
(http://programminghistorian.org/es/assets/python-lessons1.zip)

http://programminghistorian.org/es/lecciones/de-html-a-lista-de-palabras-1 (
http://programminghistorian.org/es/assets/obo-t17800628-33.html) - though this is the same file in both languages so keeping only 1 version is ideal.

http://programminghistorian.org/es/lecciones/de-html-a-lista-de-palabras-1
http://programminghistorian.org/es/lecciones/de-html-a-lista-de-palabras-2
(http://programminghistorian.org/es/assets/python-lessons2.zip)

http://programminghistorian.org/es/lecciones/de-html-a-lista-de-palabras-2
http://programminghistorian.org/es/lecciones/normalizar-datos
(http://programminghistorian.org/es/assets/python-lessons3.zip)

http://programminghistorian.org/es/lecciones/normalizar-datos
http://programminghistorian.org/es/lecciones/contar-frecuencias
(http://programminghistorian.org/es/assets/python-lessons4.zip)

http://programminghistorian.org/es/lecciones/contar-frecuencias
http://programminghistorian.org/es/lecciones/crear-y-ver-archivos-html-con-python
(http://programminghistorian.org/es/assets/python-lessons5.zip)

http://programminghistorian.org/es/lecciones/crear-y-ver-archivos-html-con-python
(http://programminghistorian.org/es/assets/python-lessons6.zip)

http://programminghistorian.org/es/lecciones/palabras-clave-en-contexto-n-grams
(http://programminghistorian.org/es/assets/python-lessons8.zip)

http://programminghistorian.org/es/lecciones/salida-palabras-clave-contexto-ngrams
http://programminghistorian.org/es/assets/python-lessons9.zip

**Comment by acrymble** [comment]
it looks like this might not have been uploaded yet. Related to #366 since these files have to go in the same assets folder as the English code.

**Comment by vgayolrs** [comment]
@acrymble obo-t17800628-33.html is the same. 
Part of the zip assets are in https://github.com/PH-espagnol/borradores/tree/master/assets and I need to move them to the jekyll folder and complete them.
