### ISSUE TITLE
Spanish characters in code highlighting as if errors

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#360]
Noticed that when accented characters are used in code blocks in Spanish lessons, our codeblock syntax highlighter is flagging them in red highlighting, as if they're an error. This isn't great for users who might be easily confused as they learn.

Can this be addressed, or are we stuck with it?

http://programminghistorian.org/es/lecciones/trabajar-con-paginas-web
![screen shot 2017-03-04 at 10 00 11](https://cloud.githubusercontent.com/assets/646647/23577843/79c1895e-00c1-11e7-9f72-a66e1a2a68e9.png)

**Comment by vgayolrs** [comment]
Thanks @acrymble . Let me see what I can do to fix it.

**Comment by vgayolrs** [comment]
I corrected it with a little trick: changing the verb tense to avoid accents. Anyway I will look for a solution in case we have to include words with accents in the code.
