### ISSUE TITLE
Spanish Lesson - broken link (markdown error)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#363]
http://programminghistorian.org/es/lecciones/normalizar-datos

- [x] There is no URL for  "[página Web][]"

Also for:

http://programminghistorian.org/es/lecciones/salida-de-datos-como-archivo-html

- [x] "[archivo zip de las lecciones anteriores][]"
- [x] "[Contar frecuencias][]"
- [x] "python-lessons7.zip [zip sync][]"
- [x] "[Contar frecuencias][]: ../lecciones/contar-frecuencias [archivo zip de las lecciones anteriores]: ../assets/python-lessons6.zip [zip sync]: ../assets/python-lessons7.zip"

And:

http://programminghistorian.org/es/lecciones/palabras-clave-en-contexto-n-grams

- [x] "Si no tienes estos archivos de las lecciones anteriores, puedes descargar programming-historian-7, un [archivo zip de las lecciones anteriores][]"

And:

http://programminghistorian.org/es/lecciones/salida-palabras-clave-contexto-ngrams

- [x] "Si no tienes estos archivos de las lecciones anteriores, puedes descargar un [archivo zip de las lecciones anteriores][]."

**Comment by acrymble** [comment]
I've fixed the ones that were links. The remaining ones pertain to the .zip assets #359

**Comment by vgayolrs** [comment]
Thanks @acrymble . I think we can close this as there is #359 open with the same problem (.zip assets).

**Comment by vgayolrs** [comment]
Done. Please notice that the .zip files names changed to avoid conflicts in assets.
