### ISSUE TITLE
clarify Spanish translation workflow

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#369]
This is in response to conversation at #368 .

@arojascastro has requested a workflow diagram that shows what the roles of the authors, editors, and reviewers are in the translation process. (also in the regular submission process?)

@arojascastro and @vgayolrs also discussed whether the reviewing of Spanish-language material should happen on the main PH Jekyll (this) repository or the Spanish repository (https://github.com/PH-espagnol/borradores/issues). There were concerns about interoperability and testing/reviewing before publication.

Since anything on the main Jekyll repo is live and effectively published, I would suggest this work take place on the 'Submissions' repo instead (https://github.com/programminghistorian/ph-submissions). That means we only have to keep track of 2 repos instead of 3. I don't see a fundamental difference between the Spanish work and the Editorial work, because in both cases it's about quality control before publication, and a place to discuss.

The way we use that site is that each page/lesson gets a ticket where all conversations about that page/lesson are discussed. An editor takes primary responsibility for that page/lesson and when they are satisfied the file gets moved to the live site.

I suspect this will be less complicated when it is just lessons being translated rather than the main pages of the site.

**Comment by arojascastro** [comment]
Thanks @acrymble for your summary. Yes, the diagram should represent relationships, tasks and times of the regular submission process, because essentially the submission of the translations follows the same path. 

In respect of reviewing pages/lessons in your repository, I am open to discuss alternative views, I just thought that it would be less annoying for you. Also we have already opened issues on our repository but in any case we can continue in yours. We need to take a decision soon because in the guidelines I linked our spanish repository - so if we are using yours I should check some links.

Finally, I would like to highlight that some of the translations of pages still need to be reviewed and that the python lessos were only reviewed by one person (Jairo). My view is that myself and @mariajoafana we should proof read them because only one review is not enough.

**Comment by acrymble** [comment]
As per request, here is basically what our editorial workflow looks like (sorry it's just rough). This might be helpful for thinking about how the translation workflow is the same or different.

<img width="624" alt="editorialworkflow" src="https://cloud.githubusercontent.com/assets/646647/23589485/ece6cdae-01c5-11e7-9286-fba75322ceec.png">

**Comment by vgayolrs** [comment]
@acrymble I agree to work translations in https://github.com/programminghistorian/ph-submissions repo. We will be able to keep the discussion on the issues in one place and refer them correctly through the appropriate tickets.
@arojascastro It would be great to have that workflow diagram. Could you make a proposal?

**Comment by vgayolrs** [comment]
I certainly agree that translations should still be reviewed. The translation of the introduction to Python, in effect, was formally revised by Jairos; but it has been reviewed by other people in an external and informal way to know that everything works (there were missing zip files and other details but yesterday I fixed it), I can ask those people to integrate as formal reviewers to PH. Anyway, I will greatly appreciate the comments @arojascastro  and @mariajoafana  can make. Thank you.

**Comment by acrymble** [comment]
I guess the question is: do you want 2 formal outside reviewers? Or do you want 1 outside reviewer, and 1 member of the 'Spanish team' to do the checking?

**Comment by arojascastro** [comment]
I would like to review the Python lessons because since it is the first lesson translated it will shape future translations. I respect a lot Spanish different dialects but I am afraid that we have to discuss about terms that are not used in Spain and that I guess are used in Mexico. By this i don't mean that we should change them I am only saying that it is important that we have this conversation about how to translate some English tecnical words into Spanish (Mexican, Colombian or Iberian). We cannot overlook the fact that our audience is international. The problem with this is that it will take me some days.

**Comment by acrymble** [comment]
Suggested workflow for translation (please comment if this is not appropriate)
<img width="636" alt="translationworkflow" src="https://cloud.githubusercontent.com/assets/646647/23589546/e7d33658-01c6-11e7-85d2-a762f01b31a2.png">

**Comment by arojascastro** [comment]
Yes, I think we agreed that translations could be reviewed by one editor and one reviewer (which at the moment it must be the third member of the Spanish team since we have no reviewers). It works for me and I would love to stick to it. Many thanks @acrymble for doing it!

**Comment by acrymble** [comment]
@arojascastro I think your comments about internationalisation are great. We are definitely hoping to make this work across the Spanish-speaking world!

Also please note that we built up our reviewers by sending people unsolicited emails. Don't be afraid to do the same!

**Comment by acrymble** [comment]
@mariajoafana obviously please do share your views on this, as this is something that has to work for everyone. I'm happy to try to help this fit with how we do things with the rest of the project, but please don't feel I'm trying to take charge of your Spanish team initiative.

**Comment by acrymble** [comment]
also when we made changes to our submissions about a year ago, we only started using it for new lessons that came in. So if you're already half-way through a translation, don't feel compelled to change to the submission site just for the sake of it.

**Comment by vgayolrs** [comment]
@acrymble I think your translation workflow proposal is great! @arojascastro I agree with you both about internationalisation, which means a more or less standardization. But we have to be cautious with the extreme homogenization because in Spanish there is a great diversity that we must also respect. The case of the expression that we discussed a few days ago with @mariajoafana  ("to be part of") can be expressed as "hacer parte de" or "formar parte de". Both expressions are understood by all Spanish speakers, although to some it seems a humorous way of expressing the idea, by cultural context. In some countries, a computer is called "ordenador" and in others "computadora". As we expect PH to become an international collaborative tool (it already is), we must respect to a certain extent the regional ways of expression by authors and translators as long as they are understandable for all (not the same to be used by all). Failure to do so may lead to a potential feeling of harassment to their own form of cultural expression.

**Comment by arojascastro** [comment]
Of course, I am not trying to homogenize language, but I think we need to have a discussion that has not happened yet. I think it would be great to make a list of words or expressions so we can keep them in mind. When earlier I asked you about "ambiente" instead of "entorno" (translation of environment) I did not say that is wrong. I said in Spain we use "entorno". I accepted your explanation. My point is that I need to read your translations to find out what words I should learn as distinct or typical from Mexico/Colombia. I would also benefit from resources on Spanish in Mexico and Colombia because I always check terms in Spanish/Iberian dictionaries.

**Comment by arojascastro** [comment]
I also think that in case of doubt is good that a third person takes a decision. That is why its good to have a second reviewer.

**Comment by mariajoafana** [comment]
Thanks for the workflows @acrymble I also agree with working the translations on
 https://github.com/programminghistorian/ph-submissions

Lastly, I'm in the process of reading the Python lessons (I'm three lessons in) and so far I haven't find any typo or unclear language. I'll let you know when I'm done.

**Comment by acrymble** [comment]
Maybe it would help to have a template for your review tickets concerning new translations so that everyone knows what to expect and what to look for (as well as what not to look for?). We have one for the English lesson reviews:

---

The Programming Historian has received the following tutorial on '[Lesson Name]' by [USERNAME]. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/[URL]

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to [OMBUDSPERSON] if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ([OMBUDSPERSON] - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

---

Maybe something like this?:

The Programming Historian has received the following translation on '[LESSON]' by [USERNAME]. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/[URL]

I will act as editor for the review process. My role is to read through the translation and to seek one formal review from the community. I will also manage the discussions, which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a [NATIONAL DIALECT HERE] speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to [SPANISH OMBUDSPERSON] if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ([OMBUDSPERSON] - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

---
Please amend as needed.

I know this feels like a lot. But it took us years to work out the best way to do these open reviews and to manage everyone's expectations. So don't worry, we're here to help sort out these workflows with you.

**Comment by vgayolrs** [comment]
@acrymble I think it would be nice to have templates in both languages. I can translate them and can serve as a useful example for other languages that could be integrated into the project. On the other hand, it would be good to reach an agreement about the repositories. I insist it would be more manageable to use / ph-submissions. @mariajoafana  @arojascastro, any thoughts?

**Comment by arojascastro** [comment]
I think it is a great idea. We should use it every time we receive a submission and open an issue, right? I agree with @vgayolrs that we should translate it. There is a welcome message in the Guidelines for translators -- so it needs to be updates. I added the message in the issue on those guidelines in the our soon to be deleted repository.

**Comment by vgayolrs** [comment]
So if everyone agrees, these days I will propose a way to have all the Spanish translations of of the website pages and lessons that are not reviewed, as well as the new lessons to review, in the repository `/ ph-submissions`, by creating the appropriate folders. Thank you all!

**Comment by acrymble** [comment]
It sounds like everyone is happy with this workflow.

The next step would be to write up this conversation as a set of guidelines for translators / translation editors and post them on the website. Then we can close this ticket. This should probably be done in Spanish.

**Comment by vgayolrs** [comment]
@acrymble Thank you very much for helping the Spanish team. Before closing this ticket, I have a comment and a question.

The comment is about the Spanish workflow for translations and new lessons. I think both are realy well covered in the page [Instruciones para autores](http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones), translated and adapted by @arojascastro . It seems to me very clear and the text reflect exactly the English version. And if somebody surf to [Guía para revisores](http://programminghistorian.org/es/guia-para-revisores) (Reviewers guidelines) and [Guía para editores](https://github.com/PH-espagnol/borradores/blob/master/lecciones/guia-editor.md) (which is not yet in Jekyll, but I can take care of tuning and finishing it), the reader has the whole process clear. I only suggest changing the name of the page from [Instruciones para autores](http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones) (*Instructions for Authors*) -> to *Instrucciones para autores y traductores.*

The question for @acrymble  is: I'm translating the templates for translations review tickets (and eventually, new lessons reviews) so, where you suggest storing them to work here and allow the Spanish team to have access?

Thanks in advance.

**Comment by arojascastro** [comment]
Good idea! I also think that we should change the title of that page otherwise it would be misleading for translators.

**Comment by mariajoafana** [comment]
Yes, I agree.

**Comment by vgayolrs** [comment]
Thank you! So, we seem to agree, so I close this ticket. If someone thinks that something should be considered again, please, do not hesitate to reopen it.

**Comment by acrymble** [comment]
I would put your template for the review tickets in the Guidelines for Editors, since it's up to them to manage that.

The English page should have the equivalent documentation for editing translations, just so they are in sync as much as possible.

**Comment by vgayolrs** [comment]
Thanks @acrymble, working on it.
