### ISSUE TITLE
"Editor" in yaml instead of under 'Reviewer'

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#370]
As per #340 - @wcaleb has suggested converting all editors listed as reviewers to 'editor' instead. This ticket is to identify the offending lessons and start revising.

**Comment by acrymble** [comment]
The following files need the editor pulled out from amongst the reviewers:

- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/applied-archival-downloading-with-wget.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/automated-downloading-with-wget.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/building-static-sites-with-jekyll-github-pages.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/cleaning-data-with-openrefine.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/cleaning-ocrd-text-with-regular-expressions.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/code-reuse-and-modularity.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/corpus-analysis-with-antconc.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/counting-frequencies-from-zotero-items.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/counting-frequencies.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/creating-an-omeka-exhibit.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/creating-and-viewing-html-files-with-python.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/creating-network-diagrams-from-historical-sources.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/creating-new-items-in-zotero.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/data-mining-the-internet-archive.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/downloading-multiple-records-using-query-strings.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/extracting-keywords.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/from-html-to-list-of-words-1.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/from-html-to-list-of-words-2.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/generating-an-ordered-data-set-from-an-OCR-text-file.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/geocoding-qgis.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/georeferencing-qgis.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/getting-started-with-github-desktop.md
- [ ] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/getting-started-with-markdown.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/googlemaps-googleearth.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/graph-databases-and-SPARQL.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/installing-omeka.md
- [ ] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/installing-python-modules-pip.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/intro-to-bash.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/intro-to-beautiful-soup.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/intro-to-the-zotero-api.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/introduction-and-installation.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/json-and-jq.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/keywords-in-context-using-n-grams.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/linux-installation.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/mac-installation.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/manipulating-strings-in-python.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/naive-bayesian.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/normalizing-data.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/output-data-as-html-file.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/output-keywords-in-context-in-html-file.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/preserving-your-research-data.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/qgis-layers.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/research-data-with-unix.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/sonification.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/text-mining-with-extracted-features.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/topic-modeling-and-mallet.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/transforming-xml-with-xsl.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/transliterating.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/understanding-regular-expressions.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/up-and-running-with-omeka.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/vector-layers-qgis.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/viewing-html-files.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/windows-installation.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/working-with-text-files.md
- [x] https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/working-with-web-pages.md

**Comment by acrymble** [comment]
All updated except:
@ssimpkin lesson (who was editor on this please?)
https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/getting-started-with-markdown.md

And @fredgibbs which didn't really have an editor I don't think, because it was meant to make @jerielizabeth lesson on beautiful soup easier to use.
https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/installing-python-modules-pip.md

**Comment by wcaleb** [comment]
Thanks, Adam. I need to adjust the `_include` now so that the editor is printed.

**Comment by wcaleb** [comment]
I've tried to join the editors and reviewers together using the [concat](https://help.shopify.com/themes/liquid/filters/array-filters#concat) filter, but it doesn't seem to be working. Ideas @mdlincoln?

**Comment by wcaleb** [comment]
Ah, it looks like the `concat` Liquid filter [isn't available in Jekyll 3](http://stackoverflow.com/questions/40243421/concatenate-arrays-in-liquid). Will have to work around this some other way.

**Comment by mdlincoln** [comment]
I think I have a workaround using the `split` filter. Will push shortly.

**Comment by wcaleb** [comment]
You read my mind! I was thinking on that too, but will stop.
