### ISSUE TITLE
Footer in Spanish site redirects to English feedback

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#372]
Here is my first issue in this repository. 

I found out that "Deja una opinión" in the footer in the Spanish site links to the English Feedback link. Can we fix this? 

Besides this, "Deja una opión" seems to me a literal translation of "Leave an opinion". I don't know if in Latin America you say that but in Spain we don't - we usually say "Send your comments" (Envíanos tus comentarios). I do not mean to homogenize language just checking if it is an error. So please don't get crossed.

**Comment by vgayolrs** [comment]
Can you check the changes in a few minutes?

**Comment by arojascastro** [comment]
Great!
