### ISSUE TITLE
Temporary /es menu link?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#373]
Can we add a temporary /es menu link to let people find the Spanish site? (and vise versa for English).

I know we're planning on making changes to the menus in #346 but a temporary solution seems appropriate.

Any objections?

**Comment by vgayolrs** [comment]
I think it's great! (and the Spanish team will be proud and grateful!)

**Comment by mariajoafana** [comment]
Yes, that's a great idea. 
Also, the blog posts are up. I managed to do it :) Once you get more familiarized with Github it becomes less intimidating... 
Let me know if the posts look good and if you like the chosen image. 
I can make any change before we officially announce it on twitter.

**Comment by arojascastro** [comment]
Thanks @mariajoafana for choosing the image and writing the announcement. I like a lot!

**Comment by acrymble** [comment]
I have added this link to the menu. I recognise that it's temporary and that the changes to the navigation will change this, but we need a short-term way for people to find the project.
