### ISSUE TITLE
Improving submission of Spanish translations/lessons for review

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#374]
Hi everybody!

@acrymble @mariajoafana @arojascastro 

As discussed here #369, In order to improve the method for submit and review new lessons in Spanish as well as the Spanish translations of published PH lessons, I have opened the folder "programminghistorian/submissions/es" with two options: 1) [programminghistorian/submissions/es/traducciones](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/traducciones), in order to put there the translations, and 2) [programminghistorian/submissions/es/lessons](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/lecciones), in order to put there the new lessons originally written in Spanish.

This will improve the work flow of submit, review and editing the material, as we can have a better tracking with review tikers, edition, and so on.

Please do not hesitate to comment on this repository management option in order to improve it.

**Comment by arojascastro** [comment]
For clarification purposes, why not submissions/es/lecciones? I do not understand the question for @wcaleb. There is something that I am missing.

**Comment by vgayolrs** [comment]
@arojascastro Forget it, I found the first folder we made here with Caleb and Adam back in september/2017, but it no longer works.

**Comment by acrymble** [comment]
is this ready to be closed or is there an outstanding action?

**Comment by vgayolrs** [comment]
Ready to be closed. Just remind @mariajoafana  to take note of this and, if any change is needed, she can reopen it.

**Comment by mariajoafana** [comment]
Good, noted.
