### ISSUE TITLE
Changes made to improve Spanish site

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#376]
@mariajoafana @arojascastro @acrymble 

I toured the splash pages and secondary ones to get an idea if the site works properly. I fixed some links and make some changes and aditions to fit everything as discussed at #369 

1. The [Guía para editores](http://programminghistorian.org/es/guia-editor) (*Editor guidelines*) redirected error404, so I took the one [translated and adapted](https://github.com/PH-espagnol/borradores/blob/master/lecciones/guia-editor.md) by @arojascastro . Its a very good translation and reflects the contents of the original version plus adapted to the needs of the Spanish site. Only I tuned it a bit and put the necessary things we discussed at #374 about editing traduction's reviews [in this paragraph](http://programminghistorian.org/es/guia-editor#nota-sobre-la-revisi%C3%B3n-de-traducciones). Please, let me know if it's clear and if it's reflect the ideas we discussed.

2. The same item was added to the [Guía para revisores](http://programminghistorian.org/es/guia-para-revisores) (*reviewers guidelines*) as you can see [here](http://programminghistorian.org/es/guia-para-revisores). Same as above, please do not hesitate to comment if it is clear or can be improved.

3. [Instrucciones para autores](http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones) (*Instructions for authors*) was renamed to include translators as suggested at #369 

4. I noticed that Editor Templates for translations and new lessons was already translated by  @arojascastro at Guía de editores, from the original. But I notcied too that the link in the original page leads to [ISSUE_TEMPLATE](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/ISSUE_TEMPLATE.md), so I made two versions: one [PLANTILLA-TRADUCCION](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-TRADUCCION.md) and other [PLANTILLA-LECCIONES](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/PLANTILLA-LECCION.md), stored in `ph-submissions/es`. Please let me know if it's clear and works fine for you.

Thank you!

**Comment by arojascastro** [comment]
Great! Many thanks @vgayolrs. I like all changes that you made. The Guía para editores still need to be proofread becasue there are some Markdown syntax errors. Can we create a Review Ticket? (I know that we have created review tickets in the Spanish repository but maybe we can remove them and create issues here?).

**Comment by mariajoafana** [comment]
Excellent, the additions following our previous discussions look great. 
About your question, now that all the Spanish webpage materials are here in the Jekyll repo I'll say that is fine to create the ticket here. In this case you can call it something like "Fix Markdown on Guía de editores". In the future, we might want to use the Spanish repo to post review tickets only of translated lessons before publication.

**Comment by arojascastro** [comment]
Ok, I correct some typos in #6538ff1 (how can i link to a commit?)

**Comment by wcaleb** [comment]
@arojascastro If you paste the URL to the commit you want in a comment box here, GitHub will automatically convert it to a shorter link, like this: https://github.com/programminghistorian/jekyll/commit/6538ff173caee1c46c7d97b83cfd2e3be52e56dc.

On the [commits history](https://github.com/programminghistorian/jekyll/commits/gh-pages), there is also a handy "clipboard" icon next to the commit hash so that you can quickly copy the URL to that commit in order to paste it elsewhere.

**Comment by arojascastro** [comment]
Cool! Many thanks @wcaleb

**Comment by wcaleb** [comment]
@arojascastro Also, if you mention the issue number #376 with a hashtag in the "commit message" for your commit, it will automatically put a link on this ticket to that commit. See an example of what this looks like at the bottom of #311.

**Comment by vgayolrs** [comment]
Ok, if there's no more comments about this issue, I close it. Please don't hesitate on reopen it if you want to add something. Thank you.
