### ISSUE TITLE
Further Translations

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#378]
A discussion ticket to consider a French translation, as we've been contacted informally by at least 2 people seemingly interested in this.

I'm of course happy to see the project reach as many people as possible, and all content is CC-BY so anyone can translate whatever they want. If this involves incorporating more language content onto our site I think we'll have to consider our capacity (in terms of people's time and energy) to do so. Once we have the workflow completely sorted out for the Spanish material this might be more feasible for us.

But I did want to open a ticket so we could see if this is something the community & team wanted in the medium-term.

**Comment by acrymble** [comment]
We got a number of people retweeting this, but no one (including those who contacted us) have added any comments here. So I would suggest the appetite for this isn't sufficiently high at the moment.

**Comment by symac** [comment]
Hi @acrymble, 
I had noticed the issue and subscribed to it, but I was thinking the last sentence of your message for "the community & team" was referring to insiders of the community, requesting inputs regarding the best way to integrate translated contents into the main site and I had not understood you were willing us (people that had contacted you by email) to comment there to show the support.

So I can confirm, following my previous email, that I am still interested in translating the content to French. If people reading this issue are interested, just contact me ( sylvain@geobib.fr) and we'll see how we can start working on French translation before going further.

**Comment by acrymble** [comment]
Thanks @symac . Sorry I didn't mean the language to sound like we weren't after your input. By community I meant anyone who feels invested or interested in the project.

**Comment by acrymble** [comment]
I've renamed this to 'Further Translations' from 'French Translation' because we've now also been contacted by a Russian colleague interested in a Russian translation of the project.

**Comment by acrymble** [comment]
I'm going to close this, as we aren't actively pursuing it. But it's good to know that future translations may be viable in future.

**Comment by symac** [comment]
In case someone came across this ticket looking for a French translation, I hope to get something done in the next few weeks, I have [forked the repo](https://github.com/symac/jekyll) and started adding translations to configuration files (I still need to figure out how all of that communicates within Jekyll as I'm not an expert with the tool but I am for the moment recopying what is available in Spanish to French).

If you are willing to work on a French translation please contact me so that we don't duplicate the work!

**Comment by acrymble** [comment]
@symac perhaps you can contact us when you have a few things worked out. And let us know if there are specific Jekyll questions, as we've got lots of experts on the team who could offer advice.

I do think our experience with the Spanish translation has helped us work out some effective workflows for further translations. What we'd need to know is if there is sufficient energy and interest for this to be done for a French version. I'm sure @arojascastro @mariajoafana and @vgayolrs can attest to how much work it's been so far!

**Comment by symac** [comment]
Thanks @acrymble for the input. I hope that having some foundation will help gather more people, I will take some time to have a first draft of a French translation then will try to publicize this first version.
Will let you know as soon as there is more to be seen.

**Comment by acrymble** [comment]
it would be interesting to know which lesson you are going to do first.

**Comment by drjwbaker** [comment]
I am some French language DH contacts I can route this through when some draft work is ready to be shared. @ianmilligan1 - any Canadian colleagues who may find this of interest?

**Comment by ianmilligan1** [comment]
Yep, same here - I can share once draft work is ready to be shared!

**Comment by ettorerizza** [comment]
If needed, I'm ready to translate some lessons.

**Comment by symac** [comment]
Thanks for all the comments on this. To answer @acrymble 's question, I have started working on introduction lessons : 

- [introduction-and-installation](https://symac.github.io/jekyll/fr/lecons/introduction-et-installation) (**done**)
  - [mac-installation](https://symac.github.io/jekyll/fr/lecons/installation-python-mac) (partial)
- [viewing-html-files](https://symac.github.io/jekyll/fr/lecons/comprendre-les-pages-web) (**done**)
- [working-with-text-files](https://symac.github.io/jekyll/fr/lecons/travailler-avec-des-fichiers-texte) (**done**)

I have also started working on some other lessons, will continue doing some others during the next few days/weeks and will then update this issue, asking for reviewing/help.

**Comment by drjwbaker** [comment]
Thanks @ettorerizza!

**Comment by acrymble** [comment]
As all content on the _Programming Historian_ is licensed under a CC-BY license, anyone is free to translate and republish the material.

The _Programming Historian_ team is open in principle to additional official translations and non-English based teams working towards original content, which we would host as part of the main project.

Translation is not, however, purely a matter of converting lessons from English into another language. The _Programming Historian_ is a multi-lingual project involving a large team, and so translation requires extensive teamwork and coordination across our editorial team.

Anyone interested in joining the _Programming Historian_ as part of a new translation project should be prepared to fulfil the following requirements:

1) A team of at least 3 editors, from more than one country who are committed to the project for at least two years. At least one member should have substantial experience with translation. Please note that due to our editorial board diversity commitment, we may insist on a certain number of members from different countries, and of different genders. We advise getting in touch with us before attempting to put together any teams as we may know of other people considering a similar translation.
2) A willingness of the  team to engage productively with the existing multi-lingual editorial board, including contributing actively to monthly Skype meetings.
3) A commitment to our peer review system using Github and peer review for all translations and new lessons, using the workflows adopted by the rest of the team.
4) A commitment to translating and maintaining the translations of all non-lesson pages on the site as the project evolves and as policies change over time. This includes but is not limited to the following pages, which must be translated before any lessons can be hosted:

- the Front Page
- About Page
- Author Guidelines
- Contributor Guidelines
- Reviewer Guidelines
- Editor Guidelines
- Lesson Retirement Policy
- Project Team
- Research Outputs

Anyone interested in proposing a new translation initiative is invited to contact our Managing Editor (@jmparr) in the first instance to discuss the idea informally. We look forward to hearing from you.

**Comment by acrymble** [comment]
From our editorial call, we discussed the needs for more social content about the role of new editorial teams. Some rough ideas (which maybe sound a bit too harsh at the minute, but it's just a starting point):

The Programming Historian is controlled entirely by the Central Editorial Board, comprised of all active members of the project team. In order to ensure that the project continues to thrive, we expect all sub-teams involved in producing a linguistic version of the project (eg, English, Spanish, French, etc.) to adhere to the following principles:

1. The sub-team is required to adhere to the author, reviewer, editor, and technical guidelines at all times. These guidelines can only be amended by the Central Editorial Board.
2. The sub-team is required to adhere to the CC-BY license at all times.
3. The sub-team is required to participate actively in the Central Editorial Board.
4. The Central Editorial Board reserves the right to replace or amend the membership of a sub-team if it is becoming unsustainable or if it believes that the sub-team will not be able to continue the project to the level that we expect of The Programming Historian.

--

Thoughts?

The plan is to ultimately post this and the above technical expectations to the Wiki.

Please comment by 7 May, at which point I'll move the finished text over.

**Comment by walshbr** [comment]
This might be softened a bit by a sentence explaining the context for it. Something like this to be integrated into the first paragraph:

"While each linguistic version of the project needs the freedom to act autonomously, there are certain agreed upon workflows, technical protocols, and policies necessary to maintain seamless integration with the project as a whole."

**Comment by arojascastro** [comment]
It seems reasonable to me with @walshbr suggestion.

**Comment by drjwbaker** [comment]
So, in sum (to check I get this having missed the chat): everyone is in the Editorial Board, everyone is also part a language project (EN, ES, FR, er al), there are minimum requirements for each language project to ensure some consistency between them, but outside those minimum requirements each language project acts independently.

**Comment by acrymble** [comment]
@drjwbaker I suppose the key is yes, fairly independent, but at the pleasure of the Editorial Board which reserves the right to act should it feel the need to do so to ensure quality is maintained.

**Comment by arojascastro** [comment]
I think this [proposal](https://github.com/programminghistorian/jekyll/issues/378#issuecomment-369307840) is great. However, I do not undestand if that proposal has been replaced with [this](https://github.com/programminghistorian/jekyll/issues/378#issuecomment-383653376). If not, I do not understand how are they related structurally in the wiki/website. Can you clarify the place of each text in our website/wiki?

**Comment by acrymble** [comment]
@arojascastro the idea was to ammend the second one to the first.

We proposed putting it on the wiki just so it didn't need to be translated. 99.99% of our readers won't care about those issues, so I just figured why not keep it off the main site? If you think it should be live and translated, I guess that's fine by me.

**Comment by arojascastro** [comment]
I think there are some important details in the first proposal that maybe should be included in the second likewise the monthly skype meeting and the paratextual contents that need to be translated before the launch of a new version. I'm happy that this goes to the Wiki only as long as we make sure that potential new editors  read it - that means, that we point out to it in our conversations. I honestly should pay more attention to the wiki.

**Comment by acrymble** [comment]
Just for total clarity, here is the proposed final text:

The _Programming Historian_ is controlled entirely by the central Editorial Board, comprised of all active members of the project team. In order to ensure that the project continues to thrive, we expect all language sub-teams (English, Spanish, French, etc.) to adhere to the following principles:

1. The sub-team is required to adhere to the author, reviewer, editor, and technical guidelines at all times. These guidelines can only be amended by the central Editorial Board.
2. The sub-team is required to adhere to the CC-BY license at all times.
3. The sub-team is required to participate actively in the central Editorial Board.
4. The central Editorial Board reserves the right to replace or amend the membership of a sub-team if it is becoming unsustainable or if it believes that the sub-team will not be able to continue the project to the level that we expect of The Programming Historian.

Translation is not purely a matter of converting lessons from English into another language. The _Programming Historian_ is a multi-lingual project involving a large team, and so translation requires extensive teamwork and coordination across our editorial team. New language sub-teams joining the project to translate existing material and with an aim of producing original content should be prepared to adhere to the following additional principles/requirements:

* A team of at least 3 editors, from more than one country who are committed to the project for at least two years. At least one member should have substantial experience with translation. Please note that due to our editorial board diversity commitment, we may insist on a certain number of members from different countries, and of different genders. We advise getting in touch with us before attempting to put together any teams as we may know of other people considering a similar translation.
* A willingness of the team to engage productively with the existing multi-lingual editorial board, including contributing actively to monthly Skype meetings.
* A commitment to our peer review system using Github and peer review for all translations and new lessons, using the workflows adopted by the rest of the team.
* A commitment to translating and maintaining the translations of all non-lesson pages on the site as the project evolves and as policies change over time. This includes but is not limited to the following pages, which must be translated before any lessons can be hosted:

- the Front Page
- About Page
- Author Guidelines
- Contributor Guidelines
- Reviewer Guidelines
- Editor Guidelines
- Lesson Retirement Policy
- Project Team
- Research Outputs

Anyone interested in proposing a new translation initiative is invited to contact our Managing Editor (@JMParr) in the first instance to discuss the idea informally. We look forward to hearing from you.

**Comment by JMParr** [comment]
Sounds good, Adam.

**Comment by acrymble** [comment]
Thank you everyone for your input on this. This policy has now been moved to the Wiki:

https://github.com/programminghistorian/jekyll/wiki/Additional-Language-Sub-Teams-Policy
