### ISSUE TITLE
Testing Spanish workflow

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#383]
@mariajoafana @arojascastro 

I am opening this ticket to test the workflow of the Spanish team to submit, edit and review translations, as we discussed at #369 . We will be testing the process with finished translations sent to the [new repository for translation submissions](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/traducciones), as we agreed at #374 . Please let me know if I'm missing something. I'm including @acrymble  to help us monitoring the workflow, but I'm confident we can do it without disturbing him too much. So, here we go...

As I am acting as "the translator", I will upload the translated lessons into the repository, I will give them the latest retouching and then I will send you all an email (In a normal case the translator would send the email to @arojascastro ), notifying you about the submission including the information indicated in [Instrucciones para autores y traductores](http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones). Of course, we will save steps 1 and 2.

I think we could use this ticket to discuss the worflow in process to improve it. Anything else, please comment. Thank you!

**Comment by arojascastro** [comment]
Following Adam's email, who is acting like an editor?

**Comment by acrymble** [comment]
Maybe it's worth filling in your table of editors/translators now and then everyone knows? https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md

We normally have an editor chosen before authors start writing. The translations have been a bit different, but you could figure out now who will edit what (spreading the work between you) and then there is no confusion.

**Comment by arojascastro** [comment]
Yes, I agree we should fill in that table with editors. So please @vgayolrs @mariajoafana add your names. I will understand that the gaps are left for me.

**Comment by vgayolrs** [comment]
If I may suggest, I think the best way to start testing the workflow is to designate different editors. For example, @mariajoafana  could be the editor responsible for those translations that already began to review @arojascastro , so he could finish the translation review:

1. Preservar tus datos de investigación: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/preservar-datos-de-investigacion.md
2. Introducción a Markdown: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/introduccion-a-markdown.md
3. Escritura sostenible en texto plano usando Pandoc y Markdown: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/escritura-sostenible-usando-pandoc-y-markdown.md

Translations that have not been reviewed could be edited by @arojascastro and reviewed by @mariajoafana :

1. Instroducción a la línea de comandos en Bash: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/introduccion-a-bash.md
2. Instalar módulos Python con pip: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/instalar-modulos-python-pip.md

Perhaps it would be good to invite a second external reviewer in each case. @arojascastro  has received emails from people interested in participating, who may be asked to review.

Finally, I would also like to be an editor. There are two lessons translated:

1. De la hermeneútica a las redes de datos: Extracción de datos y visualización de redes en fuentes históricas, translated by @mariajoafana that rest in the old repository: https://github.com/PH-espagnol/borradores/blob/master/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas.md
2. Introducción al control de versiones con GitHub Desktop, translated by @arojascastro  that rest in the old repository to: https://github.com/PH-espagnol/borradores/blob/master/lecciones/introducci%C3%B3n-control-versiones-github-desktop.md

In these cases, I suggest that the authors submit these lessons to the programminghistorian/ph-submissions/es.., and drop me an email to start the process. 

Please let me know what do you think about this, to add the editor's names to the translation list as suggested. Remember that the issues-templates (both for translation and lessons) are at https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es

Thank you everybody!

**Comment by mariajoafana** [comment]
Perfect, lets try the workflow this way. I thinks that the process make sense, I just started creating the tickets for the translations in which I'll be acting as editor and filled the table assigning myself as editor. Also, as a translator I just submitted the "Creado diagramas de redes" to ph-submissions and sent Víctor an email in a sort of "mock" editorial process exercise. Where should be create the images folder?

**Comment by vgayolrs** [comment]
@mariajoafana : As editor of your translation I would be responsable of creating that folder. Let me do it and then I will post here the process.

**Comment by vgayolrs** [comment]
Switch to Spanish:
@mariajoafana : ya está lista la carpeta para las imágenes de la traducción en la siguiente dirección:
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/creando-diagramas-de-redes-desde-fuentes-historicas
Ahi puedes subir las imágenes de la lección.
En caso de que tú o @arojascastro , como editores, necesiten crear una carpeta, solamente hay que ir a `programminsghistorian/ph-submissions/images` y crear ahí la carpeta con el *slug* de la traducción y un archivo `placeholder.md` que indique algo así como "Carpeta para las imágenes de la traducción de lección de María José Afanador-Llach". Eso sería todo.
Saludos!

**Comment by vgayolrs** [comment]
Switch to Spanish:
@mariajoafana @arojascastro 
Para abrir los Tickets (o *Issues*) de revisión de traducciones sugiero cambiar el nombre que hemos estado usando (*Nueva traducción*: nombre-de-la-lección ) a *Ticket de revisión de traducción de*: nombre-de-la-lección. Esto para tener más claridad y poder abrir tickets cada vez que nos propongan nuevas traducciones pero aún no estén enviadas. De tal manera quedaría como aquí:
https://github.com/programminghistorian/ph-submissions/issues/58
En vez de como aquí:
https://github.com/programminghistorian/ph-submissions/issues/57
y
https://github.com/programminghistorian/ph-submissions/issues/56
¿Qué opinan?

**Comment by vgayolrs** [comment]
Cerramos este ticket en función de la reunión editorial #394 . Si es necesario discutir algo lo reabrimos.
