### ISSUE TITLE
Add to CONTRIBUTING.md?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#387]
[This document](https://github.com/programminghistorian/jekyll/blob/gh-pages/.github/CONTRIBUTING.md) can be amended with additional information anyone contributing to the technical development (rather than the content production) of the _Programming Historian_ website.

- [x] Distinguish between technical contributions (the focus of this doc) and content contributions (the focus of published webpages)
- [x] How to set up your system with Ruby and Bundler
- [x] How to fork, clone, and then use `bundle install` to create the proper development environment
- [x] Using `_config.yml` and `{{ site.baseurl }}` to properly render a dev branch on GH pages
- [x] Standards for documenting and justifying changes, then submitting those changes via pull request.

### My outstanding questions 

1. Who on the team will be responsible for reviewing technical PRs?
2. Do we need an _individual_ on the team who will coordinate other team members doing development work do final sign-off on merging contributions?

**Comment by fredgibbs** [comment]
very important questions that i think we should address on our next call.

**Comment by wcaleb** [comment]
Agree it would be worth discussing.

Re: the specific questions about CONTRIBUTING.md, I think in general in the past we have favored keeping general contributing documents aimed at a pretty wide audience. My only worry would be putting so much aimed at developers in this document that it might appear forbidding for people who are just looking into any ways to contribute (as author, reviewer, etc.).

Perhaps some of the documentation about Ruby development environment for Jekyll could be put in our repo wiki and linked from the CONTRIBUTING.md file. Also, @amandavisconti's [lesson on GitHub Pages](http://programminghistorian.org/lessons/building-static-sites-with-jekyll-github-pages) covers some of the information about Ruby and bundler, so maybe we could refer to that via link in this documentation.

**Comment by mdlincoln** [comment]
There isn't actually a CONTRIBUTING.md at the root of this repo. 

"content" contributions in the form of lessons and editorial work are documented in [/contribute.md](https://github.com/programminghistorian/jekyll/blob/gh-pages/contribute.md), which is published on the web page at <http://programminghistorian.org/contributing.html>) 

"technical" ones, whose guidelines are the ones that are linked to when you open an actual issue or PR on this repo, are stored at [/.github/CONTRIBUTING.md](https://github.com/programminghistorian/jekyll/blob/gh-pages/.github/CONTRIBUTING.md) Right now, that only includes the anti-harassment policy.

I agree it makes sense to keep the content contribution and technical contribution guidelines separated, but also to link between one another with clear signposts so people spend their time looking at the right one!

I think putting most of the technical contribution documentation in the wiki makes sense... but I'm also not 100% clear how current the wiki has been kept here? It looks like a few things have been deprecated and moved out to the published site. Definitely good to discuss next week.
