### ISSUE TITLE
Revise or remove Troubleshooting

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#388]
It looks like [this troubleshooting page](https://github.com/programminghistorian/jekyll/blob/gh-pages/troubleshooting.md) from the old site hasn't been touched for three years, and it's now pretty outdated, but it's [still being generated with our site](http://programminghistorian.org/troubleshooting). I don't think it's linked from anywhere currently. (I only noticed it because it generated a dead link error referenced in #385.) Should we revise it? Or just remove it?

**Comment by ianmilligan1** [comment]
These are good general principles, but yeah, it's pretty outdated now. I'd be happy to see it removed, but given @acrymble is one of the authors would also be happy to defer to his judgment on it.

**Comment by acrymble** [comment]
I'm generally against deleting things, in part because I've been doing internet history research lately and it drives me crazy when people do that. This hasn't really been integrated into the site. It could be updated and posted on the blog just so those ideas (many of which are still useful) don't go to waste.

**Comment by wcaleb** [comment]
I agree, Adam. I would favor revising/updating it, and then including 
a link to it somewhere, perhaps at the top of the lessons directory? Or 
at the beginning of the series on Python, where it seems like it may 
have appeared originally, as part of PH1?

**Comment by wcaleb** [comment]
Incidentally, here is the [old resources page](https://github.com/programminghistorian/jekyll/blob/gh-pages/_oldsite/modified_html/resources.html) that is linked to from the troubleshooting page. Perhaps, at least for the moment, I could include the list of links in that page at the bottom of `troubleshooting.md`? That would at least make one of the link errors in #390 go away.

**Comment by mdlincoln** [comment]
There are no incoming links to the "troubleshooting" page on the new site. I think it is just fine to leave the page published, in case someone happens to have the old link saved. I'm going to close for now - please reopen if we think there's more to discuss!
