### ISSUE TITLE
Lesson page lesson name different from actual lesson name

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#389]
Just pointed out via Twitter:

This lesson is named 'From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources' http://programminghistorian.org/lessons/creating-network-diagrams-from-historical-sources

But on the lessons page it is called 'Creating Network Diagrams from Historical Sources'.

This is potentially confusing for users. It may also not be the only lesson where this has been done. I suspect it's something that was done because it made the lessons page look prettier (given the long title). I suggest we standardise our practices of title length and short/long titles to prevent this confusion in future.

**Comment by acrymble** [comment]
#193 is an obviously linked issue. @amandavisconti can we address both in the redesign?

**Comment by amandavisconti** [comment]
@acrymble I think this is already fixed by virtue of the lessons page no longer being hardcoded—the titles appearing on the lessons page are just the text under "title" in a lesson's front matter.

**Comment by acrymble** [comment]
Ok let's call this future-fixed then.
