### ISSUE TITLE
Travis CI tests timing out

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#391]
Since commit 63d0486, we're seeing intermittent timeouts of the travis tests.

**Comment by wcaleb** [comment]
Do we somehow have to config Travis to handle unicode the same we had to locally?

**Comment by mdlincoln** [comment]
I don't think it's a travis issue - it's running on ubuntu, and that's only an OS X issue. It looks like the unicode file is actually causing some kind of hang in htmlproofer. I'm going to try running it locally and see what happens.

**Comment by mdlincoln** [comment]
I really don't think it's the unicode character filename causing any issue. I just removed it and am still having a timeout on Travis. Meanwhile, earlier builds finished (with the expected errors) _with_ those filenames: https://travis-ci.org/programminghistorian/jekyll/builds/212134767

**Comment by wcaleb** [comment]
There was a broken external link in `troubleshooting.md` that I found myself, and it looks like once I corrected it, Travis was able to run HTMLProofer easily. I wonder if it was somehow hanging on that broken link for some reason?

**Comment by wcaleb** [comment]
@mdlincoln Weirdly enough, https://github.com/programminghistorian/jekyll/commit/886feb77c24fce631753ee209814813673e8caf1 seems to have fixed this. Closing for now. I don't know if the lack of a response code from the incorrect URL was causing everything to crash?

**Comment by mdlincoln** [comment]
It's odd, other URLs also have a lack of a response code without timing out. It looks like the ability to set a timeout limit for htmlproofer may be forthcoming, so I'll keep an eye on the problem until then.
