### ISSUE TITLE
Mallet lesson needs updating for more recent version

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#393]
@jburnford noted in an e-mail to me:

>The Programming Historian Mallet lesson seems to cause a small problem if students download the newest version (.8), instead of the .7 version you’ve got linked on the lesson. The final _composition.txt file does not work right. It is confusing as everything else seems to work until they open the file in Excel and it does not have the topic-percentage pairs for each file. The easy solution is to just get them to download the older version of Mallet, but if you and Shawn have a bit of time at some point in the future, it would be good to update it and figure out which part of the command changed in the new version.

We've made explicit that we should use the old version, but we really should update it at some point to use the newest version.

**Comment by ianmilligan1** [comment]
I will do so when I have some spare cycles but might not be for a while.

**Comment by acrymble** [comment]
I don't think you need to feel compelled to update this. The lesson is still internally correct. But it's up to you.

**Comment by ianmilligan1** [comment]
Hah thanks Adam. We've had a fair number of questions about this - the version we use is no longer easy to find except through our lesson.

**Comment by fredgibbs** [comment]
This sort of thing might be an opportunity to generate additional community participation--to see if we can't encourage someone who has been thinking about contributing to PH but doesn't want to write a new lesson--updating an existing one and replacing a few screen shots isn't too intimidating and could be a good trial run.

**Comment by mdlincoln** [comment]
Flagging this for consideration re: #536

**Comment by ianmilligan1** [comment]
Why don't us authors talk and see if we can get this updated.

**Comment by mdlincoln** [comment]
https://github.com/programminghistorian/jekyll/issues/536#issuecomment-318408907
