### ISSUE TITLE
Store a copy of Powerhouse Museum TSV in assets 

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#395]
The `phm-collection.tsv` dataset used in the [Open Refine lesson](https://github.com/programminghistorian/jekyll/blob/gh-pages/lessons/cleaning-data-with-openrefine.md) appears to be missing. We have been saying that we have a copy available on our site, but we don't. So we need to download the collection or check to see if [the one mentioned](https://github.com/programminghistorian/jekyll/issues/390#issuecomment-289208161) by @acrymble in #390 is the one we need (renamed from `txt` to `tsv` perhaps?).

**Comment by wcaleb** [comment]
@acrymble I'm noticing now that an earlier paragraph in the lesson directs users to find the file [here at a FreeYourMetadata link](http://data.freeyourmetadata.org/powerhouse-museum/). It looks like the file in question is 56 MB---pretty large for us to store in our repo, but not impossible, I think. So should we just put a copy of the TSV file available on that page in our `assets` folder? Or are we reasonably confident that it will be reliably available from the FreeYourMetadata site?

**Comment by fredgibbs** [comment]
since this is a live issue, i would say that we should get in the habit of storing all dependent resources locally. ideally, we could use a portion of the this tsv file--easy to do if we're hosting it ourselves and can edit it--probably all 56 MB isn't necessary and could actually be slightly problematic for people with older machines.

**Comment by mdlincoln** [comment]
I agree that it's a good policy to try and host copies of lesson data here. The powerhouse data is on the large side of things, and it's a good idea in the future to tailor lesson data to be just the amount needed to be effective. But it's no issue to put a copy here (and that freeyourmetadata site has _very_ slow download speeds, so I'd feel much more comfortable having a copy here anyway)
