### ISSUE TITLE
how to keep static pages in sync across languages?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#396]
Our two new editors have added themselves to the Project Page, but not to the Spanish version.

What is the best way to ensure the two sets of pages stay in sync from a contact perspective? Can we set up an alert that automatically gets sent to @arojascastro perhaps when one of the static pages is updated, and he can respond accordingly? Or is there a better way?

**Comment by vgayolrs** [comment]
If someone updates the static pages, just send us a message to update the Spanish version, while defining an automatic alert or the best way. This reminds me that we still have to translate information from the `authors.yml` file.

**Comment by walshbr** [comment]
As for an automatic alert - I'm not as familiar with git hooks as I should be, but this seems like a use case for them - https://www.atlassian.com/git/tutorials/git-hooks. Could imagine a number of different options - one that looks to see if your commits change a set list of static files or and refuses them if the message does not ping one of the translators maybe? Then you'd just have to modify the commit message to ping one of the translators. I'd need to investigate more to make sure that's really viable though and stub out options.

**Comment by wcaleb** [comment]
Git Hooks would work if we were always committing locally, but often commits are made directly here on GitHub, and those wouldn't trigger hooks.

The easiest way, it seems to me, would be to include one of the Spanish team member's GitHub handle in the "longer" section of any commit message when you update a static page that needs some translation. That will ping the person whose handle you included. See https://github.com/programminghistorian/jekyll/commit/3a5b6acfa022690f9f3a7ffc1cb31656d25ad624 for an example of how I pinged @amandavisconti using a commit message.

**Comment by wcaleb** [comment]
We discussed on #394 and agreed that, as a general rule, when anyone makes a change to a static page, ping one of the Spanish team members so that they know new translation is needed.
