### ISSUE TITLE
update lessons page layout according to user testing from #333 

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#397]
[ ] Suggested change of font
[ ] One user expressed preference for grid-style rather than list-style
[ ] Suggested that there is too much info in the descriptions (authors/reviewers/date not pertinent for users; images too big)
[ ] Search box in unusual spot - suggested top right (also note, what does this search? full text? just titles?)
[ ] Should make use of left margin for faceting
[ ] Suggestion to keep any link that does something as a button rather than a normal hyperlink
[ ] Facets/Buttons should change visibly (grey/blue) when activated/unactivated
[ ] List of results is too far down the screen

**Comment by amandavisconti** [comment]
Re "list of results is too far down screen", my displaying the full list only once (instead of one full list that can be filtered down to partial display, followed by a full list sorted by topic) should help with this (but other display changes such as 3 lessons per line would help too!)
