### ISSUE TITLE
unicode filenames and git tracking

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#400]
The adjacent problem that @wcaleb and I ran in to during #381 is _not_ resolved.

On my local machine (OS X 10.11.6 w/ git 2.9.2) I see only one copy of `_posts/2017-03-05-lanzamiento-PH-español.md`. However, currently on the `gh-pages` [branch we've got two](https://github.com/programminghistorian/jekyll/tree/c7a33388b7e027b1f08d5218c3fb4b3f81d8f685/_posts), which means that there's duplicate posts appearing on the public site.

One of them looks like the one I had committed with `git config --global core.precomposeunicode false`, and I think that one is likely outdated, so I am going to try and remove it.

**Comment by mdlincoln** [comment]
*sigh* ok @wcaleb, when you have a moment can you try the following:

1. Make sure `git config --global core.precomposeunicode true` ([this is how it really ought to be set for any OS X contributors to this repo](https://git-scm.com/docs/git-config#git-config-coreprecomposeUnicode))
2. Pull and checkout the `temporary_post_removal`
3. If you can pull without errors, check the local copy of your `_posts` to see if you have just one version of this post, or multiples. If just one, then I think we're set.

**Comment by mdlincoln** [comment]
To clarify, 26c18d1 has removed the duplicate post, so we no longer have a double-post published live. We still just need to confirm that the re-committed file actually works correctly on everyone's local repos.

**Comment by mdlincoln** [comment]
@wcaleb were you able to test the `temporary_post_removal` branch on your system after setting `git config --global core.precomposeunicode true`?

**Comment by wcaleb** [comment]
@mdlincoln When I pull that branch and check it out, there is only one of the posts on that branch. And also only one of the posts on the `gh_pages` branch too FWIW.

**Comment by mdlincoln** [comment]
OK - then I think this issue ought to be resolved.
