### ISSUE TITLE
Whole Project citation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#404]
Raised in #394 - @fredgibbs raised concerns about the current project citation (as distinct from the lesson-level citations). I wanted to bring that discussion forward here since I am going to close the meeting ticket to which it was attached.

@fredgibbs noted:

i would like to make a VERY STRONG argument that we remove the suggested citation. there are a few main reasons:

+ anyone needing to cite PH will be publishing it somewhere that will have a citation style that must be followed. so people can figure out how it makes sense to cite PH given whatever paradigm they are using.
+ it's misleading. if i cite an article published from 2014, i should be citing the editors who produced that publication, not the current editors who maybe don't know anything about it.
+ i have not seen anywhere ever a convincing argument for why an entire project team should be all listed as editors, which has a fairly specific meaning for cited publications.
+ it's kind of meaningless: what is a second edition of a constantly changing website? we're not a published book that has discrete editorial interventions and printings. the date is also wrong, since we have an ongoing publication. it should be 2012 (or whatever) with an open-ended date (so 2012-).

--

@acrymble replied:

I have to say I'm surprised by this, and it might be a difference between the needs and pressures in different jurisdictions. Does it hurt anyone to leave it? Because I think it poses challenges for me in the UK research environment to say what this project is and to ensure it 'counts' in an appropriate way.

I can't say I was convincing, but I did put forth an argument for why project teams should be named in project citations:

http://www.digitalhumanities.org/dhq/vol/7/2/000164/000164.html

I found at the time that American colleagues were seemingly least interested in this, which again suggests to me there's just a different need for representing work in different countries.

I also use these types of citations to teach my students about collaboration and to teach them to distinguish between the content (eg a lesson) and the project. So I think dropping it would be a step in the wrong direction. I'd be much happier to revise it. We discussed project version numbers previously, which I think are more meaningful and maybe could be linked to cohorts of team members.

--

@amandavisconti offered a solution

Some compromise possibilities:

+ Replace the hardcoded author list in the citation with a call to the current editors (may need to add a field to data sheet to do this, which is yet another thing to remember to update...)
+ Replace "x edition" with "accessed on date" or "accessed on [pull in today's date]" (possibly with link to /jekyll repo for that date?)
+ If you're citing an individual lesson, the citation on that page should be hardcoded with the names of the editors at the time of its publication.
+ If you're citing the whole project (using the citation at the bottom of the home page), we could provide a dropdown menu of years updating the list of editors. This would be a little incorrect given we have changes within given years, and I'm also not sure many people would want to cite the whole site from a given point in the past, rather than when they're most currently accessing it. So alternatively, we could provide a small link under the citation: "Want to cite an older version of the project?" that connects to a page listing each year next to all the editors active in that year.

--

We talked about this briefly in the meeting, and @vgayolrs noted that it would be good to have a clear citation for each changing team over time, to preserve the history of the project.

We haven't resolved this yet, so I've opened this ticket to allow for further conversation. This feels related to the issues of internationalisation and credit in #403

**Comment by acrymble** [comment]
If we go with @vgayolrs idea, the first citation should be of William J. Turkel and Alan MacEachern, who published the first Programming Historian (2008).

**Comment by acrymble** [comment]
We could resolve this issue by adding a "project history" page under the new drop-down "about" menu which highlights some of the ways the project and team have changed over the years (and will continue to do so in future). I think it's useful to give these digital projects some historical context, and I've been writing a lot about DH and history lately. Would anyone object to that?

**Comment by acrymble** [comment]
@fredgibbs has suggested adding date ranges of activity to team members on the Project Team page. We already do this for emeritus members. I don't think we have a list of active members. Is this correct?:

Maria José: 2016
Adam: 2011
Victor: 2016
Fred: 2011
Matt: 2017
Caleb: 2014
Ian: 2014
Jess: 2017
Antonio: 2016
Amanda: 2016
Brandon: 2017
Jeri: 2015

**Comment by jerielizabeth** [comment]
2015 for me is correct.

**Comment by ianmilligan1** [comment]
I think 2014 is correct for me as well.

**Comment by acrymble** [comment]
@wcaleb can you confirm 2014?

**Comment by wcaleb** [comment]
Yes, 2014.

**Comment by acrymble** [comment]
This will be addressed by the changes from #303 .

We are removing the suggested citation for the whole project (not individual lessons necessarily) in exchange for giving readers more information about who was involved with the project at which times.
