### ISSUE TITLE
Project Title decision

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#405]
Since we've been working towards standardisation in many ways, I wondered if it wasn't time to decide once and for all what the title of the project is.

We use both 'The Programming Historian' and 'Programming Historian'. "The" is included in the original: http://ir.lib.uwo.ca/historydig/3/, but what do we want to use moving forward?

**Comment by fredgibbs** [comment]
I very much support standardization and NOT using "the" in the title. Speaking of standardisation, do we have an official language?

**Comment by ianmilligan1** [comment]
FWIW, I prefer just _Programming Historian_ as well.

**Comment by walshbr** [comment]
Also prefer dropping the "the" from the title.

**Comment by amandavisconti** [comment]
Ditto.

**Comment by jerielizabeth** [comment]
I am happy to drop the "the"!

**Comment by acrymble** [comment]
Ok. I suppose we need to go through and remove all 'the' instances from the site documentation.

**Comment by acrymble** [comment]
@fredgibbs I think we had this discussion about language a few years ago and decided not to choose a form of English because of the international nature of our project. The Spanish team have also been battling with that because of the differences between Iberian and Latin American Spanish. Is there a reason you're asking?

**Comment by wcaleb** [comment]
At the risk of unnecessary delay, since it seems like it has broad support, can I ask why dropping the "The" is preferable? While I think we do use both on the site, my rough impression is that "The Programming Historian" is more widespread, so standardizing in the direction of "Programming Historian" would likely be a more noticeable change. Just wondering ... I kinda like "The PH" but if I'm alone in this, I'm happy to defer to the group---and reasons for the change would probably easily persuade me.

**Comment by acrymble** [comment]
@wcaleb I am with you on the preference, but I wasn't going to go against the flow. I'm curious also.

**Comment by mdlincoln** [comment]
Echoing @wcaleb - I agree that the most prominent uses of "The" have been in both the old and new site titles... so it would seem that it makes more sense to standardize to "The Programming Historian" rather than "Programming Historian".

Whichever way this is decided, I'm glad to take point on actually carrying out the standardization across the site.

**Comment by arojascastro** [comment]
Reading this interesting conversation. We are using *The programming historian en español*... Why? Because in Spanish we need an article. However, we did not discuss this, it just came naturally, right? @mariajoafana @vgayolrs

**Comment by walshbr** [comment]
I've been thinking a lot about the question from @wcaleb over the last couple days, and I can't really come up with any real reason. And the more I think about it the more I think I'm ambivalent. Even though I said I preferred dropping it, when I wrote various constructions of both I think I'm more persuaded to standardize to keep "The."

- The Programming Historian released a new lesson.
- Programming Historian released a new lesson.

- There is a new lesson out from The Programming Historian.
- There is a new lesson out from Programming Historian.
 
- The Programming Historian's new lesson is great.
- Programming Historian's new lesson is great.

And if "The" is more widely used already and necessary in translation anyway - those seem like compelling arguments to me for keeping it.

**Comment by amandavisconti** [comment]
I'm fine with going either way. My leaning toward cutting "The" before was because I kept writing

- There is a new lesson out from the _Programming Historian_.

which now that I think about it is more awkward—I should use the "The" that's already there.

**Comment by jerielizabeth** [comment]
I can go either way.

**Comment by wcaleb** [comment]
We discussed this briefly on #412. The general consensus for those who were on the call was:

- Keep "The Programming Historian" in the masthead and formal citation for the site.
- Adopt a style standard about how to use the title in running text: I suggest (a) always italicize and capitalize *Programming Historian*, but (b) do not capitalize and italicize articles preceding that (e.g., "there is a new lesson out from the *Programming Historian*," "Find out how you can become a *Programming Historian* contributor," "Check out our new *Programming Historian* lesson on linked data")

This solution seems to be the one adopted by the *Journal of American History.* See [examples here](http://jah.oah.org/):

- They have *The Journal of American History* in the masthead.
- In running text, they refer to "the *Journal of American History*".
- They still sometimes drop the article to refer to *JAH* articles or in their Twitter handle (as we do), which is @JourAmHist.

If you support this solution, please "thumbs up" this comment---if you want to discuss further or suggest changes, please comment.

**Comment by acrymble** [comment]
@fredgibbs to implement the above decision re 'the'

**Comment by fredgibbs** [comment]
The short term solution to fix title page and masthead are complete, so i'm un-assigning myself but keeping ticket open for later content review.

**Comment by acrymble** [comment]
Pages this affects (english only)

- [x] /project-team
- [x] /about
- [x] /research
- [x] /contribute
- [x] /reviewer-guidelines
- [x] /author-guidelines
- [x] /index

**Comment by acrymble** [comment]
All english pages fixed as per @wcaleb suggestions above.
