### ISSUE TITLE
Broken link on "Escritura sostenible..."

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#409]
The link `https://github.com/nickbart1980` referenced in [Escritura sostenible en texto plano usando Pandoc y Markdown](http://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown) is not valid.

**Comment by mdlincoln** [comment]
It looks like the link on the en version of this lesson is <https://github.com/njbart>?

**Comment by mariajoafana** [comment]
thanks @mdlincoln 
Fixed
