### ISSUE TITLE
english slug in spanish lessons?

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#413]
When viewing a lesson translated into spanish, is there a way to get the corresponding english slug (whether set in YAML or derived automatically by jekyll)? With the new lessons page, this is necessary for pairing images with lessons; this may be also necessary for new tweet cards as well. This could be solved with a en-slug (or whatever) in the YAML but i'm not sure if there is some other way of doing this right now or a better strategy.

**Comment by wcaleb** [comment]
It can be gotten from the redirect_from value in the YAML of Spanish lessons. To get the slug you can use the remove_first filter to drop the "/en/"

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Magister
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by fredgibbs** [comment]
thanks for the quick reply @wcaleb! sorry for the dumb question.
