### ISSUE TITLE
Add translation date field to YAML for Spanish lessons

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#415]

**Comment by arojascastro** [comment]
Can I ask if this was implemented?

**Comment by acrymble** [comment]
Not that I'm aware of. I think it's largely a matter of deciding on a term and starting to use it.

**Comment by mdlincoln** [comment]
These were originally needed for the versions-of-record, and that discussion is still ongoing - so there is no rush.

Still, it would be good to have the metadata in the translated lessons no matter what. Please use:

```
translation_date: 2017-07-01
```

**Comment by arojascastro** [comment]
I added all dates except those for python here 4cf0ba5c6731f919d5c85fea070dc7aad88f8853 

I retrieved them from here https://github.com/programminghistorian/ph-submissions/issues?q=is%3Aissue+label%3Atranslation+is%3Aclosed

@vgayolrs where can I find the translation date for your python lessons?

**Comment by arojascastro** [comment]
@vgayolrs me puedes recordar la fecha de publicación de tus lecciones de Python, por favor?

**Comment by vgayolrs** [comment]
@arojascastro : todas se publicaron ya corregidas a lo largo de la primera quincena de marzo 2017 (se puede ver en los tickets de revisión). Si quieres ponle 15 de marzo, o te hago la lista de cada una con la fecha de cierre del ticket. Tú me dices.

**Comment by arojascastro** [comment]
Ok, @vgayolrs 15 de marzo va bien. Gracias.

**Comment by arojascastro** [comment]
added all translation dates f80cfcc923639068b01e6a3b72e8b2e178e740ac
