### ISSUE TITLE
Can we delete the master branch?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#420]
Since the entire site is built from gh-pages, can we remove the `master` branch and set `gh-pages` as the default branch? I keep accidentally checking out and committing to `master` on my local machine out of habit...

**Comment by wcaleb** [comment]
I think gh-pages is the default, at least on the remote. I think the master branch has some historical commits from the conversion to GitHub that we don't want to delete. The blog post we wrote about that transition links back to master branch to illustrate the process, IIRC. 

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Magister
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/

**Comment by mdlincoln** [comment]
Ah, fair enough!
