### ISSUE TITLE
Tidying the repo wiki

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#421]
It's been suggested that docs for technical contributions (re #387) might live in the repo wiki. I was surveying its current contents and had a few questions for more experienced team members, as the last edit to this wiki was back in September 2016. If we're going to put development guidelines here, I'd love to deprecate pages that are no longer used, and highlight those pages that _are_ still being actively maintained:

1. Wiki pages that listed editor&author guidelines for workflow are almost all now on public-facing pages on the PH site itself. I wouldn't _delete_ those wiki pages, because I don't want to break links. But I would want to finish the job of removing all content from them, and boldly marking each as **Deprecated** with a link to the appropriate contribution page on the published site, and probably remove them from the wiki sidebar as well. Any objections to this?
2. Other pages
    1. @acrymble You were the last person to update [People who use the Programming Historian](https://github.com/programminghistorian/jekyll/wiki/People-who-use-the-Programming-Historian). Are you still using this page? How does it relate to <http://programminghistorian.org/research>? Also, it looks like [Scholarly activities](https://github.com/programminghistorian/jekyll/wiki/Scholarly-activities) has already been deprecated, yes?
    1. @amandavisconti You were the last person to update [Editorial Roles](https://github.com/programminghistorian/jekyll/wiki/Editorial-Roles). Thoughts?
    1. @jerielizabeth What about [Lesson Pipeline](https://github.com/programminghistorian/jekyll/wiki/Lesson-Pipeline)?
    1. @amandavisconti [Website Usability Testing](https://github.com/programminghistorian/jekyll/wiki/Website-usability-testing) would absolutely fit within the genre of development guidelines, so I think it should stay for now.

Final note: the wiki is actually its own git repo, so any content we delete from it will remain within the change history and will always be recoverable

**Comment by jerielizabeth** [comment]
@mdlincoln the Lesson Pipeline page, I believe, is being replaced with the "proposals" issues in the ph-submissions repo.

**Comment by amandavisconti** [comment]
@mdlincoln I just updated my roles and Miriam's on the role page—not sure if others are still correct.

**Comment by acrymble** [comment]
@mdlincoln no, some of it needs to find a home on the main site still. Haven't figured out exactly where that is. Scholarly activities has been deprecated.
