### ISSUE TITLE
Additional step suggested for Windows users of "Building Static Sites with Jekyll"

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#422]
Comment from Ed Sperr received via email on an additional challenge for Windows users:

> Did want to note one potential edit however – the version of Ruby installed using the Windows instructions did not include the DevKit. Without the DevKit, Jekyll doesn’t seem to want to run properly. So, if this gets updated at some point, be sure to include a step where one installs the DevKit for Windows using the instructions at: https://github.com/oneclick/rubyinstaller/wiki/Development-Kit

@amandavisconti I am happy to put you in contact with Ed if more information is needed.

**Comment by amandavisconti** [comment]
Thanks, I'll address this and add Ed to the credits at the bottom of the lesson!
