### ISSUE TITLE
create translate section on english contribute page

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#427]
this was highlighted in #414 but now moving it into its own non-design issue.

**Comment by acrymble** [comment]
I propose the link go to the Spanish-language version because anyone doing translating will have to be Spanish-speaking anyway. But proposed text for 'contribute' page:

> 
> If you are fluent in both English and Spanish, you are invited to get in touch with us about translating one of our published _Programming Historian_ lessons into Spanish. This will help us to build a Spanish-language digital humanities community, and to build your language, method, and technological skills.
> 
> We are seeking rigorous and readable translations that take into account the Spanish-language research context and the resources available in our community. If you are interested in collaborating, consult our instructions for authors and translators.

**Comment by acrymble** [comment]
Fixed this will https://github.com/programminghistorian/jekyll/commit/2186637831bfaa878cb281201b264cf9c6abf618#diff-27455f84f02fccb1aba2862e3b34cb0e
