### ISSUE TITLE
review lesson topics (gray buttons in new design)

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#429]
This is another item mentioned in #414 and also an outgrowth of #193. We have centered on a few lesson categories according to stages in the research process, but the lesson topics have not been evaluated in some time (especially in light of many new and upcoming lessons). However, this should happen after the new design launches as to keep that change visible in the commit history.

**Comment by mdlincoln** [comment]
It sounds like we're going to see how these topics work for now - we may get feedback as solicited by Fred in the [blog post about the categories](https://programminghistorian.org/posts/new-lessons-page) and can reopen this if needed.
