### ISSUE TITLE
Rogue Javascript in the HTML

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#431]
A recent push to the site seems to have deposited some javascript in the page header. Flagging @mdlincoln.

![image](https://cloud.githubusercontent.com/assets/1447744/26122125/472c89f0-3a2b-11e7-858b-2dfddc42dbac.png)

**Comment by mdlincoln** [comment]
oh 💩 , I was trying to put that in the HTML header rather than the visible page header... fixing it now

**Comment by jerielizabeth** [comment]
I thought it might be something along those lines. Everytime I touch javascript i break something :)
