### ISSUE TITLE
Rendering problem - "Limpieza de datos con OpenRefine"

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#433]
We have recently published a new translation lesson: http://programminghistorian.org/es/lecciones/limpieza-de-datos-con-OpenRefine

The pipe character in two paragraphs is causing GitHub Pages to attempt to render a table. Does anyone know why this is happening? How can we fix it? 

The English version is working well.

**Comment by acrymble** [comment]
which lines?

**Comment by arojascastro** [comment]
In this file: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/limpieza-de-datos-con-OpenRefine.md

Three paragraphs: 

- L 87:  "Una vez eliminados los registros duplicados, podemos observar más de cerca el campo Categorías."
- L 99: "El método de agrupación por defecto no es demasiado complejo"
- L 107: "Ahora ingresa una segunda | después de la primera para obtener"

**Comment by mdlincoln** [comment]
@arojascastro There are two ways to stop pipe characters from turning in to a table:

1. Put a backslash before the pipe: `\|`
2. Wrap the pipe in back-ticks so that it is treated like code: `` `|` ``

I wrapped the pipes in backticks here.

**Comment by arojascastro** [comment]
@mdlincoln cool! Many thanks, I had no idea.

**Comment by mdlincoln** [comment]
👍  You would not _believe_ how hard it was to make back ticks appear inside backticks in that comment, though! 😂  

[Nested backticks in GitHub-flavored Markdown](https://gist.github.com/mcandre/8d76e076b2495fd8b36f439ec5033116)
