### ISSUE TITLE
Bios not displayed

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#434]
In this new translation: http://programminghistorian.org/es/lecciones/limpieza-de-datos-con-OpenRefine

Author's bio is not displayed at the bottom of the page  at all. 

Any idea how to fix this? Thanks.

**Comment by acrymble** [comment]
Did you create a bio here? https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/authors.yml

**Comment by mdlincoln** [comment]
In order to display a bio on an `/es` page, the authors need to have an `es` bio in `authors.yml`

**Comment by arojascastro** [comment]
Ops! True. Sorry...
