### ISSUE TITLE
"Recommended for Intermediate Users" is missing in Spanish translation

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#435]
Hi again, maybe I am missing something essential (again), but the level of difficulty (Recommended for Intermediate Users) is missing in our translation: http://programminghistorian.org/es/lecciones/limpieza-de-datos-con-OpenRefine

At the moment we have this: 
```
layout: default
redirect_from: /es/lessons/cleaning-data-with-openrefine
difficulty: 2
```
Is there any place where I should add the Spanish translation? Thanks.

**Comment by mdlincoln** [comment]
I do not think that lesson difficulty is displayed on the current site. However, it will be displayed on the new redesign (see for example http://fredgibbs.net/jekyll/lessons/r-basics-with-tabular-data)

**Comment by arojascastro** [comment]
It is in the English version, I checked. Well, I meant the blurb "Recommended...", not really  the level of difficulty.

**Comment by mdlincoln** [comment]
oh gosh, you're right, I missed it completely. We need to update the lesson difficulty logic so that it displays on spanish pages, too. I will add it to my to-do list.

**Comment by fredgibbs** [comment]
the lesson difficulty logic for spanish lessons will be implemented in the redesign code; but we'll need to provide translations for editor, reviewers, and similar category terms (beginner, intermediate, advanced) here: https://github.com/fredgibbs/jekyll/blob/gh-pages/_data/snippets.yml

**Comment by arojascastro** [comment]
Can we change 'Equipo de proyecto` to 'Equipo'. Maybe we should revise other terms. Is it now the right moment? I guess that if we change those terms we also need to change names of files and URL's. What do you think @vgayolrs and @majofana?

**Comment by mdlincoln** [comment]
@arojascastro I want to be careful about changing URLs that had already been published. 

If there's a strong reason to change it, then we need to remember to add the old one in the `redirect_from` YAML field, so anyone who links to the former URL will get routed to the right page.

**Comment by acrymble** [comment]
The 'Equipo de proyecto' concern should probably be in #414, since that's where changes are being discussed. It could simply be fixed by changing the menu item to 'proyecto' without changing the file name or page title.

**Comment by arojascastro** [comment]
True. I'll add my comments there after discussing changes with the Spanish team. I close this.
