### ISSUE TITLE
Blog post(s) on technical changes at PH

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#437]
With the forthcoming design overhaul from @fredgibbs and @amandavisconti, plus the link-rot checking and YAML validation that we're implementing with Travis, I think it might be nice to cap off these efforts with a blog post or two that sheds some light on all this work!

I'm obviously happy to take point on a post talking about 404 prevention and file validation in a big collaborative publication like this... any thoughts from others on infrastructure/process changes we'd like to highlight?

**Comment by amandavisconti** [comment]
I can write a few sentences on cleaning up the lesson front matter to make the filter/sort possible. A blog post is a great idea!

**Comment by mdlincoln** [comment]
For explaining the redesign, I thought maybe highlighting the key motivations would be nice. And we can always expose some of the... messy... process that happens with merging code 😉

**Comment by acrymble** [comment]
feel free to do more than 1. There's a lot that's been happening.
