### ISSUE TITLE
Automatic generation of TOCs

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#438]
Hi there, this might be basic too but I am wondering how to generate a TOC automatically in Markdown. The lesson on Sparql contains many sections with commas, brackets and capital letters...  https://github.com/programminghistorian/jekyll/blob/gh-pages/es/lecciones/sparql-datos-abiertos-enlazados.md 

I would like to avoid writing the links by hand. Any suggestions?

**Comment by mdlincoln** [comment]
Add the following code:

``` md
* TOC
{:toc}
```

And it should automatically produce a table of contents where you place it.

**Comment by arojascastro** [comment]
Cool! Here is your lesson translated into Spanish: http://programminghistorian.org/es/lecciones/sparql-datos-abiertos-enlazados

I still need to update the index of the main page.

**Comment by mdlincoln** [comment]
FYI this shortcut is powered by the kramdown rendering engine, which was not available for gh-pages when I originally wrote the SPARQL lesson. I think I may be able to add it to all lessons...

**Comment by arojascastro** [comment]
Sorry again, @mdlincoln... do you know why images are not displayed? The path to the images contains an additional / 

http://programminghistorian.org/images//sparql-lod-14.png

But I checked the path in the html code and it looks fine: 

http://programminghistorian.org/es/lecciones/sparql-datos-abiertos-enlazados

Thanks

**Comment by mdlincoln** [comment]
You need to include the YAML `redirect_from: /es/lessons/graph-databases-and-sparql`. The figure code relies on the `redirect_from` field to create the image path from `es` lessons.

**Comment by mdlincoln** [comment]
Once we finish implementing #426 then we'll be able to catch those problems!

**Comment by arojascastro** [comment]
True, I always forget that redirect amongst other things @mdlincoln it's good that you are implementing TRAVIS, I guess its working like a schema that validates a file

**Comment by mdlincoln** [comment]
@arojascastro copy and paste the code I included. It is `redirect_from`, not `redirect-from`

**Comment by mdlincoln** [comment]
@arojascastro I think I see the remaining problem with figure 1 & 2 - I can rename the source iamge files and push them.

**Comment by arojascastro** [comment]
Please @mdlincoln I do not see it...

**Comment by mdlincoln** [comment]
Yay, it passes now! 🎊 📯 🎆 

Two of the new image files `sparql-lod-01.PNG` and `sparql-lod-02.PNG` had capitalized `PNG` instead of lowercase `png`. I did not realize that this causes the image links to break 😵

**Comment by mdlincoln** [comment]
Thanks @arojascastro for guiding this translation through! I'm so glad to see it online 😄

**Comment by arojascastro** [comment]
Thank you @mdlincoln for you help. I enjoyed reviewing your lesson and working with Nuria. Glad to see it out there finally.
