### ISSUE TITLE
Spanish Twitter

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#440]
We have had a comment from someone complaining about Spanish tweets in our Twitter feed: https://twitter.com/Nothingunspoken/status/866050664757157888

Maybe we should think about a Spanish language account? It might also be a good way to measure uptake of a Spanish community?

**Comment by arojascastro** [comment]
Seriously? There is a Translate button on Twitter. 

I do not mind using a different account for Spanish tweets. I am in charge of the EADH social media and I have never experienced that reaction. It is true that we mainly tweet in English but sometimes we tweet in Spanish, French, Italian and German. I think it is good for English speakers. In that sense we have a pedagogical mission consisting in acknowledging the "other". 

I would just answer "you can translate using the Translate button". I do not think you are tweeting in Spanish very often so the risk of losing followers is very low.  

Anyway, you might disagree with me, I'm happy with any decision.

**Comment by ianmilligan1** [comment]
I'd ignore that tweet and just keep what we're doing.

**Comment by walshbr** [comment]
Yeah I'd ignore that tweet as well. The reply tweets to it suggest the feelings that I have. Small sample size, but they do seem like a validation of the current method at least as powerful as the criticism.

**Comment by acrymble** [comment]
Ok. We can reopen this in future if we decide we'd benefit from a separate Twitter account.

**Comment by mdlincoln** [comment]
Absolutely not. That complaint was preposterous. I'm in total agreement with @arojascastro

**Comment by mariajoafana** [comment]
I just read the tweet! I agree that we should keep one account, we live in a global world after all

**Comment by amandavisconti** [comment]
I support ignoring the tweet.
