### ISSUE TITLE
complete translations for special terms in new snippets.yml 

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#443]
if we want to do this ahead of time, perhaps the easiest thing is for a translator to replace the existing snippets.yml with the one from my fork (https://github.com/fredgibbs/jekyll/blob/gh-pages/_data/snippets.yml) and finish the translations in that file. nothing in the new snippets file will break the existing site. we can also do it immediately after the design work goes live.

**Comment by mdlincoln** [comment]
I'll copy over the snippets now, so then @vgayolrs @mariajoafana @arojascastro can take a look. Since it's backwards compatible, might as well do it now before launching the rest of the design.

**Comment by mariajoafana** [comment]
thanks @mdlincoln Should I translate the snippets from lines 91 on which are not translated in this yml?

**Comment by mdlincoln** [comment]
@mariajoafana Yes, please!

**Comment by vgayolrs** [comment]
I'll help you with this @mariajoafana

**Comment by arojascastro** [comment]
I translated this here: https://github.com/fredgibbs/jekyll/pull/10

**Comment by mdlincoln** [comment]
Merged with 222ed02f3a7153ebfbf1a62997459bdd7c450c36
