### ISSUE TITLE
implement change history link/icon 

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#446]
this used to be in the footer, but probably shouldn't be for each lesson. probably, the last modified label and date in the header should link to the change history for that lesson.

**Comment by mdlincoln** [comment]
@wcaleb suggests changing footer to read

"Site last updated {{date}}"

and

"See page history"

**Comment by wcaleb** [comment]
And link "site updated" to repo's general commit history, and link "page history" to the page's commit history.
