### ISSUE TITLE
Move _oldsite into a separate repository

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#449]
The `_oldsite` directory is not published to the website; it simply resides in this repository. Are there any objections to moving it out to its own repository within the [programminghistorian org](https://github.com/programminghistorian)? This will help declutter the main repo.

**Comment by ianmilligan1** [comment]
I think that's a great idea!

**Comment by mdlincoln** [comment]
I've copied the files (with their original commit history from 3 years ago) into https://github.com/programminghistorian/oldsite

(I have not yet removed the `_oldsite` directory in this repo - I want to make sure this migrated repo looks ok.)

**Comment by wcaleb** [comment]
Moving it to new repo looks great to me. (In README for that repo, you may want to also link to [this blog post](http://programminghistorian.org/posts/how-we-moved-to-github) explaining the conversion process.

As that post documents, much of the original HTML from the old site is also on the `master` branch of our main `jekyll` repository. I can't remember now (!) what the main differences between the `_oldsite` folder and that `master` branch are, if there are any. 

At any rate, I think what you've done looks great.

**Comment by wcaleb** [comment]
Actually,  it looks from [this commit](https://github.com/programminghistorian/jekyll/commit/b3cc5a9aa03e800ee85e2a18093af745db9c4d03) like all I did was move the old stuff that's on the master branch into a folder on the jekyll branch. So `oldsite` in a sense was already redundant: it just gathers together the old stuff that was broken into subfolders on the master branch. 

I still think we should leave the master branch there, but this makes me even more confident that you can just delete the oldsite folder.

**Comment by mdlincoln** [comment]
From my perspective, that means that the `master` branch was already redundant 😉  but I'm happy enough to keep it and just get rid of the `_oldsite` directory!

**Comment by wcaleb** [comment]
Haha! My only reason for keeping the master branch at this point is that the blog post on conversion contains links to it. If we wanted to go through the blog post and update those links to the `oldsite` repo, that would enable us to delete the master branch. If you think that's worth it, I'd be happy to do it.

**Comment by mdlincoln** [comment]
Ah, I hadn't realized that. I'm good :)
