### ISSUE TITLE
topics.yml needs to be translated for new spanish lesson index page

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#451]

**Comment by arojascastro** [comment]
Thank you for this @fredgibbs. I must admit I got lost a little. Can you remind me how to acces to the file containing those topics?

**Comment by mdlincoln** [comment]
@fredgibbs I think the data structure for lesson topics - both in topics.yml as well as the code to render different topics lesson index search - needs to be set up before translation work can begin?

**Comment by fredgibbs** [comment]
topics.yml and the es lessons index page should be ready on the redesign branch with 04665c2

**Comment by arojascastro** [comment]
@fredgibbs @mdlincoln done here: https://github.com/programminghistorian/jekyll/blob/redesign/_data/topics.yml

**Comment by mdlincoln** [comment]
🎉
