### ISSUE TITLE
translate new index page

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#452]

**Comment by fredgibbs** [comment]
@mdlincoln: you're right on #465. i've just replaced the old es index page with the new one, so it's ready to be translated in place. i'll close #465 since it's a non-issue now.

**Comment by fredgibbs** [comment]
on a related note, we need also to translate the new about page; since the new about page is a derivative of the original index page, it seems like this work will be done together with the new index page translation--hence appending the task to this ticket.

**Comment by arojascastro** [comment]
Great @fredgibbs. Can you remind me where are those files? Thanks.

**Comment by mdlincoln** [comment]
@arojascastro 

- Spanish main page: https://github.com/programminghistorian/jekyll/blob/redesign/es/index.md
- Spanish about page: https://github.com/programminghistorian/jekyll/blob/redesign/es/acerca-de.md

Please note that these files are on the `redesign` branch of this repo. If you are editing in the web interface, please make sure the branch is set to `redesign`:

<img width="287" alt="screen shot 2017-06-13 at 8 17 33 am" src="https://user-images.githubusercontent.com/4392604/27089992-d3d8bebe-5010-11e7-975a-0774b2ea0734.png">

If you're using GitHub desktop or the command line, make sure to switch to the branch there before editing.

**Comment by arojascastro** [comment]
Thank you @mdlincoln. I promise to work on all those pending tasks during this week.

**Comment by arojascastro** [comment]
@fredgibbs @mdlincoln I have translated both pages. Some internal links might be broken because I wasn't sure about the path. @vgayolrs and @mariajoafana may want to revise my translation though. However this revision should not prevent us from implementing the new design, I believe.

**Comment by mdlincoln** [comment]
Thanks! I'll look for broken links on these pages - there are quite a few that we need to clean up from the redesign, so I'll address those in their own ticket if needed.
