### ISSUE TITLE
Add Spanish translation to 404 page

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#455]
Unfortunately we cannot have a separate 404 page _only_ in Spanish. However, can we please add a translation of the English text on that page, so both can be seen?

**Comment by arojascastro** [comment]
Sure! @mdlincoln

**Comment by arojascastro** [comment]
Translation added in fece7b4a44bb114810c44d2cdd1f061e2edb48e0 @mdlincoln

**Comment by mdlincoln** [comment]
💯 💯 💯
