### ISSUE TITLE
Long links within lesson texts breaks the float on mobile

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#459]
![2017-05-26 09 55 56](https://cloud.githubusercontent.com/assets/1447744/26504471/966ab7b4-41f9-11e7-861a-e5eee570e3de.png)

![2017-05-26 09 55 51](https://cloud.githubusercontent.com/assets/1447744/26504472/966afb02-41f9-11e7-8bdd-7d3e44738462.png)

**Comment by fredgibbs** [comment]
text-overflow: ellipsis to the rescue!
