### ISSUE TITLE
Managing backlog of lesson proposals

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#461]
Facing challenge of an increasing number of proposals and a limited number of editors. 

Question for the team: 

- Do we need to set up some sort of "waitlist" of lessons proposals that are accepted but that are pending editorial availability? Can this be done informally (assign editor but let author know that there will be a delay in response from the editor in the proposal issue.)?

**Comment by JMParr** [comment]
Waitlist seems reasonable to me. I know I have 2 pending. What else do we have in the queue at the moment that are not yet assigned?

**Comment by acrymble** [comment]
I see we have 6 active English lessons in review at the moment: https://github.com/programminghistorian/ph-submissions/issues (two of which are very old and I would suggest we reject on that basis). So I dont' know that we're at capacity yet. But if we do get to that stage, a solution is important.

**Comment by acrymble** [comment]
We don't have stats yet, but I suspect a significant proportion of planned lessons won't come through. We can always shuffle people between editors if a proposed lesson turns into a submitted lesson.

**Comment by acrymble** [comment]
I don't think we need this open at the moment, given our latest call discussion about potential pitches not following through. Reopen if needed.
