### ISSUE TITLE
Engagement posts

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#473]
I'm finishing up working with an author on an engagement post. A question on workflow:

1. Shall I just add it to the repository myself as a pull request for others to take a look at? 
2. Just push it live myself w/o a PR? 
3. Have the author add it themselves through a PR?

Seems like a small thing to ask someone to learn GitHub for if they've never used it before, so I was going to do number one.

And I'm not seeing engagement posts advertised anywhere as a category of thing we do anywhere on the "Contribute" page, though I could be missing them somewhere. Do we want to include a description of them there as a potential way that people can be involved with the project? I'm not sure people are out there just waiting to do this sort of thing, so it might not be a big deal. But could be good to let people know of the possibility.

**Comment by acrymble** [comment]
I would say 2 to your main question. As long as it looks ok, no problemo

**Comment by ianmilligan1** [comment]
Great question.. I think I would also lean towards #2.

**Comment by walshbr** [comment]
10/4 - I'll just push myself without a PR. I've got the engagement post ready to go. I'll post it once the redesign work has been merged in and I pull down those changes. And if no one has overwhelming sentiment that engagement posts should be advertised more clearly I'll take that as an answer to the question and not worry about it. Will close for now, but can reopen later for discussion if need be.
