### ISSUE TITLE
Merge fred/jekyll onto a branch in this repository

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#474]
@fredgibbs as soon as you are satisfied with the status of the redesign in your own repo, I'd like to merge all of it into a test branch in this repository, where it will be easier to run travis checks and finish final edits and fixes there. Please let me know when you think you are ready for me to do that.

**Comment by fredgibbs** [comment]
let's try the merge into a test branch! everything is done on my fork apart from a few translation issues, that might be better handled on the test branch instead of my fork.

**Comment by mdlincoln** [comment]
Great - and yes, that way the Spanish editors _should_ be able to edit in this repo directly without having to do pull requests. I'll work on it tonight/tomorrow and post once I've done so.

**Comment by mdlincoln** [comment]
The redesigned code is now on the ["redesign"](https://github.com/programminghistorian/jekyll/tree/redesign) branch of this repository. All further changes before our final live merge should be made on that branch, or as pull requests based off that branch.

**Comment by acrymble** [comment]
is there a URL we can view it at?
