### ISSUE TITLE
Managing Editor role to fill

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#477]
We will need to fill the Managing Editor role for 2017-18 from the Editorial Board. As this role has unofficially been a 1 year post the last four years, I suggest we just solidify it as such. That lets people plan ahead.

**Comment by wcaleb** [comment]
See email to the list by @jerielizabeth about the role.

**Comment by acrymble** [comment]
This will be filled by @JMParr from September 1 2017 until August 31 2018.

@jerielizabeth, can you make sure she has the keys? We'll have to remember to update the website in various places as well.
