### ISSUE TITLE
Workflow for reporting an error or proposing a lesson edit

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#479]
When looking to report https://github.com/programminghistorian/jekyll/issues/478 it struck me that the workflow for me to report an error or propose a lesson edit was a little clunky:

- go to https://github.com/programminghistorian/jekyll via the footer
- to go issues
- cut and paste lesson URL

I'm wondering if it is worth changing your footer (and, depending on how much input you want to encourage, space under the header and sub-headings) to:

- have a 'Suggest an Edit with GitHub' button that links to https://github.com/programminghistorian/jekyll/issues/new. This seems more efficient that pointing people at http://programminghistorian.org/feedback.
- have a 'Make an Edit with GitHub' button to the page URL with 'edit' interspersed - for example
https://github.com/programminghistorian/jekyll/edit/gh-pages/lessons/graph-databases-and-SPARQL.md - so that those who do/can use GitHub can fork and PR without writing out an issue. Admittedly this by-passes the useful advice at http://programminghistorian.org/feedback, but for most who use GitHub http://programminghistorian.org/feedback is redundant anyway.
- have a 'Suggest or Make an Edit via email' button for those who can't/don't use GitHub

You may have had this discussion already and rejected the idea due to concerns over relying on GitHub too much, but I thought I'd put it out there to reduce the potential clicks between thinking of a change and suggesting/making a change! Given that you manage this whole awesome thing via GitHub, it seems a shame not to make the best of some shortcuts in the architecture.

**Comment by mdlincoln** [comment]
Thanks so much for this feedback! I believe one concern was not necessarily relying on GitHub per se, but rather that not everyone would know what was happening if they were suddenly dropped into a GitHub new issue form.

However, I recently discovered it's possible to set boilerplate issue text via URL attributes! Which would mean that anyone clicking on "submit feedback" on a given page would land on a pre-populated issue form that already includes the page title, page url, and perhaps a list of helpful advice.

Something worth thinking about.

**Comment by drjwbaker** [comment]
Even if they have no GitHub account? I totally get the concern, hence the suggestion of multiple routes, indeed making not GitHub default is probably best, but omitting the direct edit or direct issue route for those who do seems inefficient to me.
