### ISSUE TITLE
Text on Open Access should include some european references

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#481]
I just translated the new about page into Spanish: https://github.com/programminghistorian/jekyll/blob/redesign/es/acerca-de.md

While translating I noticed that the text is lacking some important references  to understand the development of open access in Europe. Is this intentional? The references that I suggest are:

- Berlin Declaration promoted by the Max Planck Institute: https://en.wikipedia.org/wiki/Berlin_Declaration_on_Open_Access_to_Knowledge_in_the_Sciences_and_Humanities (See also this page: http://www.berlin9.org/about/declaration/)
- European Commission policy: http://ec.europa.eu/research/openscience/index.cfm?pg=openaccess

The current text is linking to organizations relevant in the UK and Canada, I think. I would like to see more references to other national and international initiatives if possible.

**Comment by acrymble** [comment]
Should we just add a statement that it is also compliant with the Berlin Declaration on open access?

**Comment by arojascastro** [comment]
Yes, I think so. My point is that when I was translating the text I realized that did not know any of those organisms/policies whereas I was missing the Berlin Declaration. I think those references imply that the reader is English, American or Canadian -- but they do not tell anything to a Hispanic reader. I would like to know other people's views on this though.

**Comment by acrymble** [comment]
It doesn't have an American reference because as far as I know there is no
US policy that demands scholars publish open access but there is one in
Britain. So if you are British it matters what the open access policy is.
It's sort of like food packaged with a notice that it's suitable for
vegetarians. For most people it doesn't matter.

**Comment by acrymble** [comment]
I see that the Horizon 2020 grants require open acces: http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-pilot-guide_en.pdf. @arojascastro are there more formal requirements in Europe on the way that we could point to? Like a requirement that all publications must be open access after date XXXX? I'm not familiar with this research landscape.

**Comment by arojascastro** [comment]
@acrymble as far as I know Horizon2020 and its policy is the greatest research framework in Europe. In a lower level you only encounter national policies about research and open access. I think each country has its own policy but most of them are currently referring to Horizon 2020 -- at least that's the situation in Spain.

**Comment by acrymble** [comment]
If you think it's relevant and want to add a note, I don't mind.

**Comment by arojascastro** [comment]
Yes, I think it is relevant. But of course we cannot expect to cover all countries, languages, cultures, so maybe it is ok as it is.

**Comment by arojascastro** [comment]
Ok, I'll take care of this.
