### ISSUE TITLE
Remaining broken links in redesign

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#483]
- ./_site/author-guidelines.html
  - [x]  internally linking to /getting-started-with-markdown, which does not exist (line 195)
     `<a href="/getting-started-with-markdown">Getting Started with Markdown</a>`
- ./_site/blog.html
  - [x]  internally linking to /posts/lanzamiento-PH-español, which does not exist (line 217)
     `<a href="/posts/lanzamiento-PH-espa%C3%B1ol"><img src="/images/Launch-PH-Spanish/Launch-PH-Spanish.jpg" alt=""></a>`
- ./_site/es/acerca-de.html
  - [x]  internally linking to /flujo-de-trabajo-nuevas-lecciones, which does not exist (line 125)
     `<a href="/flujo-de-trabajo-nuevas-lecciones">flujo de trabajo</a>`
  - [x]  internally linking to /guia-para-revisores, which does not exist (line 125)
     `<a href="/guia-para-revisores">guía para revisores</a>`
- ./_site/es/guia-para-autores.html
  - [x]  internally linking to enviar-una-traducción-o-una-lección-nueva, which does not exist (line 131)
     `<a href="enviar-una-traducci%C3%B3n-o-una-lecci%C3%B3n-nueva">Enviar una traducción o lección nueva</a>`
  - [x]  internally linking to escribir-y-dar-formato, which does not exist (line 130)
     `<a href="escribir-y-dar-formato">Escribir y dar formato</a>`
  - [x]  internally linking to traducir-o-proponer-una-lección-nueva, which does not exist (line 129)
     `<a href="traducir-o-proponer-una-lecci%C3%B3n-nueva">Traducir o proponer una lección nueva</a>`
- ./_site/es/index.html
  - [x]  internally linking to es/lecciones/, which does not exist (line 133)
     `<a href="es/lecciones/">nuestras lecciones</a>`
  - [x]  internally linking to flujo-de-trabajo-nuevas-lecciones.html, which does not exist (line 147)
     `<a href="flujo-de-trabajo-nuevas-lecciones.html">Escribe una lección nueva</a>`
- ./_site/es/lecciones/index.html
  - [x]  internal image /gallery/.png does not exist (line 1310)
  - [x]  internal image /gallery//es/installing-python-modules-pip.png does not exist (line 799)
  - [x]  internally linking to /es/lessons/, which does not exist (line 1310)
     `<a href="/es/lessons/"><img class="rounded" src="/gallery/.png"></a>`
  - [x]  internally linking to /es/lessons/, which does not exist (line 1324)
     `<a href="/es/lessons/"><h2>Preservar tus datos de investigación</h2></a>`
  - [x]  internally linking to /es/lessons//es/installing-python-modules-pip, which does not exist (line 799)
     `<a href="/es/lessons//es/installing-python-modules-pip"><img class="rounded" src="/gallery//es/installing-python-modules-pip.png"></a>`
  - [x]  internally linking to /es/lessons//es/installing-python-modules-pip, which does not exist (line 813)
     `<a href="/es/lessons//es/installing-python-modules-pip"><h2>Instalar módulos de Python con pip</h2></a>`
- ./_site/es/lecciones/instalar-modulos-python-pip.html
  - [x]  internal image /gallery//es/installing-python-modules-pip.png does not exist (line 149)
  - [x]  internally linking to /lessons//es/installing-python-modules-pip, which does not exist (line 256)
     `<a href="/lessons//es/installing-python-modules-pip">el original</a>`
- ./_site/es/lecciones/preservar-datos-de-investigacion.html
  - [x]  internal image /gallery/.png does not exist (line 148)
- ./_site/lessons/building-static-sites-with-jekyll-github-pages.html
  - [x]  External link http://amandavisconti.github.io/JekyllDemo/2016/02/29/a-post-about-my-research.html failed: 404 No error
  - [x]  External link http://literaturegeek.com/2015-12-08-WhyJekyllGitHub failed: 404 No error
- ./_site/lessons/counting-frequencies-from-zotero-items.html
  - [x]  internally linking to ../assets/programming-historian3.zip, which does not exist (line 260)
     `<a href="../assets/programming-historian3.zip">zip</a>`
- ./_site/lessons/creating-an-omeka-exhibit.html
  - [x]  internally linking to link, which does not exist (line 245)
     `<a href="link">added items to your Omeka site</a>`
- ./_site/lessons/creating-network-diagrams-from-historical-sources.html
  - [x]  External link http://www.uk.sagepub.com/booksProdDesc.nav?prodId=Book237401 failed: 403 No error
- ./_site/lessons/data-mining-the-internet-archive.html
  - [x]  External link http://programminghistorian.github.io/lessons/cleaning-ocrd-text-with-regular-expressions failed: 404 No error
- ./_site/lessons/getting-started-with-github-desktop.html
  - [x]  internally linking to GitHub.com, which does not exist (line 340)
     `<a href="GitHub.com">GitHub</a>`
- ./_site/lessons/graph-databases-and-SPARQL.html
  - [x]  External link http://europeana.ontotext.com/sparql failed: 404 No error
- ./_site/lessons/intro-to-beautiful-soup.html
  - [x]  internal image /images/intro-to-beautiful-soup/ does not exist (line 319)
  - [x]  internally linking to /images/intro-to-beautiful-soup/, which does not exist (line 318)
     `<a href="/images/intro-to-beautiful-soup/">`
    `<img src="/images/intro-to-beautiful-soup/" alt="The power of sudo: 'Sandwich' by XKCD">`
	</a>
- ./_site/lessons/preserving-your-research-data.html
  - [x]  External link http://dspace.jorum.ac.uk/xmlui/handle/10949/14725 failed: 404 No error
- ./_site/lessons/r-basics-with-tabular-data.html
  - [x]  External link http://lincolnmullen.com/projects/dh-r failed: 404 No error
- ./_site/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown.html
  - [x]  External link https://github.com/nickbart1980 failed: 404 No error
- ./_site/posts/launch-PH-Spanish.html
  - [x]  internally linking to /posts/lanzamiento-PH-español, which does not exist (line 135)
     `<a href="/posts/lanzamiento-PH-espa%C3%B1ol"><img src="/images/Launch-PH-Spanish/Launch-PH-Spanish.jpg" alt=""></a>`

**Comment by walshbr** [comment]
@mdlincoln - clearly I'm easily guilted for the common good. Basic GitHub question - is it possible for me to check off items from the task list, or does that have to be done by you since they're technically markdown in a message you created? Google was coming up short…

Update: figured it out! Clicking on buttons with hope in your heart ftw.

**Comment by mdlincoln** [comment]
Great! I think we've eliminated all but a few external links
