### ISSUE TITLE
redesigned es lecciones page needs translation

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#485]
~https://github.com/programminghistorian/jekyll/blob/redesign/es/index.md~

https://github.com/programminghistorian/jekyll/blob/redesign/es/lecciones.md

**Comment by arojascastro** [comment]
I'm confused. I thought I had translated that page... ?

**Comment by mdlincoln** [comment]
Sorry, I linked to the wrong page! I meant this one: https://github.com/programminghistorian/jekyll/blob/redesign/es/lecciones.md

**Comment by arojascastro** [comment]
Done! Sorry for the delay @mdlincoln @fredgibbs

**Comment by mdlincoln** [comment]
💯
