### ISSUE TITLE
Spanish Twitter Translations

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#486]
Spanish Twitter bot is implemented, so pulling out these translation-related tasks into their own issue so they don't get lost.

- [ ]  Populate the second tab of the bot spreadsheet with Spanish tweets.
- [x]  Translate the addition to the editorial workflow that informs new authors about how to make additions to the tweet queue.

Let me know if you have any questions!

**Comment by mariajoafana** [comment]
Great, thanks @walshbr I'm working on the translation.

**Comment by mariajoafana** [comment]
Translation is done. I'll keep populating the Spanish tweets. Thanks

**Comment by arojascastro** [comment]
I have added some #humanidadesdigitales hashtag in those tweets that were not too long. I hope it is working but if not let me know and i will remove the hashtag.

**Comment by walshbr** [comment]
Looks like it's working to me! Hard to gauge, but I think they're getting about as many engagements as the English tweets, give or take depending on the timing. And I'll keep an eye out to make sure that they're working, but if you're checking the lengths of the tweets on Twitter they should be ok.

**Comment by walshbr** [comment]
Took a look - most of them are OK but there are a couple that are too long. If you're testing the tweet lengths, keep in mind that you'll need to measure the length by more than just the message column. A tweet is made from the spreadsheet by taking the message, adding a space to it, and then adding the link. Twitter shortens URL's to 23 characters, so that means each message will have 24 characters added to it. So the max length you can have for a tweet is 116 characters, if my early morning math is right.

I've got a very small Python script that I have been using for testing - I can post it to the bot repo if that's helpful. It just lifts to the surface those messages that are longer than 115 characters so that I don't have to check every one manually. These were the ones that came out as too long when you add the link.  
```
Extrae datos y visualízalos en forma de red utilizando Palladio con este tutorial de @martenduering #humanidadesdigitales http://programminghistorian.org/es/lecciones/introduccion-e-instalacion

 ¿Quieres colaborar en un proyecto? Esta lección de @vanstriendaniel sobre GitHub desktop te puede ayudar #humanidadesdigitales http://programminghistorian.org/es/lecciones/introduccion-e-instalacion

 .@sethvanhooland @RubenVerborgh y Max De Wilde te ensañan a usar OpenRefine para limpiar tus datos #humanidadesdigitales http://programminghistorian.org/es/lecciones/introduccion-e-instalacion

Comienza acá como un historiador programador con lecciones introductorias de Python por @adam_crymble y @williamjturkel - http://programminghistorian.org/es/lecciones/introduccion-e-instalacion
```

**Comment by arojascastro** [comment]
Thank you @walshbr. I'll have a look at those tweets and fix the issue.

**Comment by arojascastro** [comment]
Ok, I think I fixed them: https://docs.google.com/spreadsheets/d/1o-C-3WwfcEYWipIFb112tkuM-XOI8pVVpA9_sag9Ph8/edit#gid=904817529

Should I delete those X and XY?

**Comment by walshbr** [comment]
Looks good @arojascastro! Nah leave the X/XY as is. That column is used by the bot to track which things it has tweeted and what the most recent tweet was (so that it uses the same lesson twice a week). Not meant to be touched human hands unless you want to alter the queue. 

Looks like the remaining work is just to populate tweets for the other translated lessons when you get a chance.

**Comment by arojascastro** [comment]
Thank you @walshbr! Yes, so far we are covering all translations. I am hoping we are publishing new ones soon and we are adding more messages.

**Comment by walshbr** [comment]
Ah does that mean you have all the current tweets up there for all current translations? I thought we were a few short, but if we're up to date I can close the issue. Thanks @arojascastro

**Comment by arojascastro** [comment]
I think so if I'm not mistaken @mariajoafana

**Comment by arojascastro** [comment]
We can reopen later
