### ISSUE TITLE
Accessibility of external links

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#488]
I've just been contacted about the accessibility of some of the sites we link to in lessons, and whether we'd be willing to adopt strategies to ensure our lessons met the Web Content Accessibility Guidelines (https://www.w3.org/TR/WCAG20/).

I'll report back when I know more (this is not an area of strength for me), but I wanted to open a ticket to flag it up in the meantime.

**Comment by mdlincoln** [comment]
Will you be able to clarify/elaborate on this question for the next editorial meeting? #504

**Comment by acrymble** [comment]
I don't have a lot more detail. It might be a case of bringing in someone who can advise on high level strategies and policies we could adopt. This was particularly to do with people who use screen readers.

**Comment by mdlincoln** [comment]
But what was the issue with external links, specifically?

**Comment by acrymble** [comment]
It was the links to the W3 html tutorials, which are apparently (ironically) not screen-reader friendly. I haven't been able to look into this further.

**Comment by mdlincoln** [comment]
The external pages are not screen-reader friendly? In which case... we can't do anything about that?

**Comment by acrymble** [comment]
The spirit of the suggestion was that we consider the implications of the websites we refer people to.

**Comment by acrymble** [comment]
I haven't received any more information on this. I'm going to close because there's no capacity to action this at the moment.
