### ISSUE TITLE
Broken Link working-with-webpages

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#492]
reported via twitter by @ed_podesta. /working-with-webpages the following link no longer works:

https://www.oldbaileyonline.org/search.jsp?form=custom&_divs_fulltext=arsenic

This has been replaced by the following, presumably when they updated the security on their site:

https://www.oldbaileyonline.org/search.jsp?form=searchHomePage&_divs_fulltext=arsenic&kwparse=and&_persNames_surname=&_persNames_given=&_persNames_alias=&_offences_offenceCategory_offenceSubcategory=&_verdicts_verdictCategory_verdictSubcategory=&_punishments_punishmentCategory_punishmentSubcategory=&_divs_div0Type_div1Type=&fromMonth=&fromYear=&toMonth=&toYear=&ref=&submit.x=0&submit.y=0

**Comment by acrymble** [comment]
Fixed with https://github.com/programminghistorian/jekyll/commit/8004e8b899971b2c0e50856a9608608e1b961eda#diff-ea5ee3180a8c5734bab267c52b97f193

@mariajoafana @vgayolrs @arojascastro This should also probably be updated in line 59 of https://github.com/programminghistorian/jekyll/edit/gh-pages/es/lecciones/trabajar-con-paginas-web.md but I dont' want to touch that file without your permission.

**Comment by arojascastro** [comment]
Thank you @acrymble. I just replaced the link here ebc6088f95905b4d4b8fe3828efab8f8ad7c098b
