### ISSUE TITLE
Brighten color for header banner text?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#494]
The gray used for the header banner is dim to the point of being a little hard to see (at least in my eyes!) Could we change it to match the somewhat brighter footer text?

**Comment by wcaleb** [comment]
Or brighten the text.

**Comment by mdlincoln** [comment]
Yes, to clarify, I meant brighten the banner _text_

**Comment by fredgibbs** [comment]
fixed with fd18f0e

**Comment by mdlincoln** [comment]
This commit brightened text in the lesson subheader, but I was talking about the header that shows up on all pages. It's really low-contrast right now, even I have a hard time reading it.

<img width="435" alt="screen shot 2017-07-05 at 4 40 43 pm" src="https://user-images.githubusercontent.com/4392604/27889366-de3a2586-61a0-11e7-8c02-4ff1ac4d1545.png">

**Comment by fredgibbs** [comment]
ah. maybe with 6b6339c it looks better?

**Comment by mdlincoln** [comment]
Way better! Thanks, it's been too long since I've done CSS and I couldn't figure out which attributes were governing the header text...
