### ISSUE TITLE
School-Aged Funding Call $5-million (Canada)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#501]
This came in via Twitter from Bill Turkel:

https://www.canada.ca/en/innovation-science-economic-development/programs/science-technology-partnerships/cancode.html
https://www.canada.ca/en/innovation-science-economic-development/programs/science-technology-partnerships/cancode/funding-cancode.html

Up to $5 million to deliver technical training initiatives (including online) aimed at K-12 students in Canada. Particularly interested in working with native and northern groups, as well as under-targeted demographics including girls.

Would have to either be a partnership or through @ianmilligan1 (who is currently on sabbatical). Raised for discussion in case anyone is interested or has ideas.

**Comment by ianmilligan1** [comment]
Aye, I certainly wouldn't have a cycle to look into this seriously for a few months. But I think this would be a long shot. Apart from me, we don't really have a Canadian presence, nor any demonstrated capacity with working with large numbers of people below the university level.

We'd also have to meet the following criteria:
* Must be a not-for-profit organization incorporated in Canada; and
* Must have a minimum of three years' experience in the delivery of coding and digital education programs to K-12 youth and/or their teachers.

I'd be cautious about the former – there are some fees involved, and it adds a level of administrative work – and I don't think we can finagle the latter into shape. It is also for projects that need to be delivered by 31 March 2019, and I'm probably full up on large collaborative grant-funded projects until at least 2020.

Geez I feel like a downer here.

**Comment by acrymble** [comment]
Ok @ianmilligan1 thanks for responding. I think we'll have to pass this one up - at least in terms of taking any lead. If anyone is looking for partners, we'd be happy to hear from you!
