### ISSUE TITLE
sorting by difficulty too flat?

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#509]
While I like the difficulty sorting feature, having only 3 levels for many dozens of lessons (and having only a few advanced difficulty lessons), reduces its utility considerably. It might be worth revisiting if we should have finer grained (= more) levels, or maybe add an additional sorting field like time (= expected time to complete tutorial).

**Comment by acrymble** [comment]
Just tried this sort. There doesn't seem to be a visual indicator of the divisions, so from a usability standpoint it looks like a progression from easy to difficult, with each lesson getting harder.

If there was a numerical count like on the other types of category, that might help encourage people to fill in the gaps in provision (ie, to write more difficult lessons).

**Comment by mdlincoln** [comment]
@acrymble I think those could both be very good additions.

I'd hesitate to add a fourth level of difficulty, lest we need to parse the difference between slightly-less-than-medium and slightly-more-than-medium difficulty.

**Comment by mdlincoln** [comment]
Note to myself to try out some visual indicator (a colored badge, perhaps) marking lesson difficulty in the lesson index.

**Comment by mdlincoln** [comment]
Closing due to lack of urgency; will revisit if desired.
