### ISSUE TITLE
Abstracts for Spanish lessons

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#510]
Do we want them?

**Comment by arojascastro** [comment]
Yes, why not? @vgayolrs @mariajoafana

**Comment by mdlincoln** [comment]
OK - I'll leave it to you to add them when you have time!

**Comment by mariajoafana** [comment]
Yes

**Comment by mariajoafana** [comment]
Thanks @mdlincoln

**Comment by mariajoafana** [comment]
I can take care of adding/translating the abstracts @arojascastro @vgayolrs

**Comment by mariajoafana** [comment]
I just finished adding all the abstracts for the Spanish lessons.
