### ISSUE TITLE
redesign has reduced usability of submission site styling

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#513]
As noted by Shawn Graham:

line numbers missing, styling gone:

http://programminghistorian.github.io/ph-submissions/lessons/correspondence-analysis-in-R

**Comment by acrymble** [comment]
to clarify, I mean the preview of lessons in progress. Not the github site itself.

**Comment by wcaleb** [comment]
I can work on this.

**Comment by wcaleb** [comment]
See initial fixes at https://github.com/programminghistorian/ph-submissions/pull/96.

**Comment by wcaleb** [comment]
Initial adjustments done, so I'm closing this.
