### ISSUE TITLE
Twitter Bot and Deprecated Lessons

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#514]
A deprecated lesson came up this week on the Twitter Bot, I nabbed it from the Twitter stream once I noticed, but it had gotten an engagement or two already. I'm assuming that we don't want to be actively tweeting those lessons that we're not promoting as current, so the Twitter bot will need to be refactored slightly to account for the fact that lessons might get pulled eventually. We could add a column for deprecated true/false, but that seems like an unnecessary piece of logic to add. Easiest solution would be -

- [x] Remove ID column from spreadsheet - makes it difficult to remove tweets from the list as they mess up the sequential ordering. This column isn't used in the current iteration of the bot anyway, as it is pulling the ID numbers from the spreadsheets rows themselves.
- [x]  Remove deprecated tweets entirely from spreadsheet (unless someone feels compelling reasons to save them).
- [x] Add language reminding people to pull the twitter content from the spreadsheet once they're deprecated to the bot documentation and…somewhere else? Do we have instructions for how to deprecate lessons somewhere (though I recognize that the process is pretty straightforward).

**Comment by walshbr** [comment]
Refactored to remove the ID column. Moved the deprecated tweets to a third sheet in that same google spreadsheet called "Deprecated."

**Comment by walshbr** [comment]
@mdlincoln - is there somewhere for me to add language about removing things from the Twitter bot when lessons are deprecated? Might be missing it, but couldn't find a space to stick that. After we add language somewhere to that effect this can be closed.

**Comment by mdlincoln** [comment]
Hm, good point! I suppose our "Archiving" guidelines #536 will need to contain a section (or likely a sub-page) for the editorial workflow for moving a lesson from published to archived. I'll stick this in my bucket of stuff then :)

**Comment by mdlincoln** [comment]
Just adding a note that this will be closed once we can merge #612.

**Comment by mdlincoln** [comment]
Closed by #612
