### ISSUE TITLE
back button to lessons page forgets choices

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#519]
This may be impossible, but I just noticed that (Chrome) when using the filters on the lessons page and then going to a lesson, when you use the back button the filters are not remembered because the buttons don't get linked to the URL in any way.

Is this something we can add or is that a nightmare?

**Comment by fredgibbs** [comment]
should be working better with f8e05f410fb344f78b23ab50c8e4827a72063e5c.
