### ISSUE TITLE
Python warnings broken link

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#520]
@acrymble The warnings you've been adding to python lessons have a broken link. You need to use a leading `/` to create a valid url to the python introduction and installation lesson.

Also, consider saving that python warning in the `_includes` folder and then adding `{% include python_warning.html %}` to the necessary lessons, so that it's easier to change the source text in one place without manually fixing everywhere else.

**Comment by acrymble** [comment]
sorry. Fixed them. A separate issue, but do we want includes being used on lesson-specific stuff rather than footer/header type material? That could get messy, no?

**Comment by mdlincoln** [comment]
Given that you've right now put the python warning within the body of the lesson text, we have to use an include. 

I implemented a table of contents include precisely because, depending on the exact heading structure of that lesson, it may or may not make sense to stick it in a predefined location before the start of the lesson text.

**Comment by mdlincoln** [comment]
On the other hand, if you'd prefer the warning to just display at the top alongside the previous/next lesson banner, then that's easily implemented as a quick YAML flag `python_warning: true`
