### ISSUE TITLE
CSS for tables isn't rendering well/at all

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#523]
See e.g. https://programminghistorian.org/lessons/understanding-regular-expressions#lesson-goals

```
| | | | | |
|:--|:--|:--|:--|:--|
|Arizona.|Quarter ended June 30, 1907.|Deaths|diphtheria|   1|
|Arizona.|Quarter ended June 30, 1907.|Deaths|enteric fever|4|
|Arizona.|Quarter ended June 30, 1907.|Deaths|scarlet fever|11|
|Arizona.|Quarter ended June 30, 1907.|Deaths|smallpox|     2|
|Arizona.|Quarter ended June 30, 1907.|Deaths|tuberculosis| 49|
```

renders as

<img width="786" alt="screen shot 2017-07-20 at 1 05 26 pm" src="https://user-images.githubusercontent.com/4392604/28436559-295cf9c4-6d4c-11e7-8361-f3ab0798de90.png">

(This also needs fixing in ph-submissions for https://github.com/programminghistorian/ph-submissions/issues/78)

**Comment by amandavisconti** [comment]
Hi @mdlincoln,

The author I'm working with (@jeffblackadar) has a question about formatting tables in lessons—is this something that was addressed when you closed this issue?

Jeff says: "I think tables in Markdown just don't work for the reviewers. (I suspect Safari does not process them well). Is that true? If I can't use tables in Markdown, could I still use inline html? Not as nice, but putting things in a table seems to be a good way to organize some of the content."

Thank you!

**Comment by mdlincoln** [comment]
@amandavisconti hmm, I thought it had been fixed... but I will take a look in the next few days. https://programminghistorian.github.io/ph-submissions/lessons/getting-started-with-mysql-using-r definitely does not seem to be rendering as intended, and authors definitely _should_ be able to use the usual markdown syntax. Let me investigate a bit.
