### ISSUE TITLE
Python 2 lesson warning

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#525]
Can one of the Spanish team edit the [python-warning snippet](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/snippets.yml#L195) to be displayed on any lessons originally written for Python 2?

I've already set the warning to display on the english lessons that @acrymble originally marked, as well as all their Spanish translations.

**Comment by arojascastro** [comment]
translated here: https://github.com/programminghistorian/jekyll/blob/fc429f02bb53c8e1e2aff88bfdb09120ac69f7b8/_data/snippets.yml

Thanks
