### ISSUE TITLE
B&W project team photos?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#526]
Would anyone object to me swapping everyone's photo with a black and white equivalent for the /project-team page?

This will only affect @mdlincoln @ianmilligan1 @JMParr @arojascastro @walshbr 

I think the B&W ones look nice and consistent, but I don't want to squash anyone's personal identity expression!

**Comment by walshbr** [comment]
No objections at all! Also happy to swap out that photo for something without ice cream if you prefer something more professional if you prefer.

**Comment by ianmilligan1** [comment]
No objections for me!

(I'm on team ice cream btw, @walshbr) 😉

**Comment by JMParr** [comment]
No problem. Would you mind swapping out my headshot for the attached? I'd
meant to do it, but haven't had a chance. It's already black and white.

(I am also on team ice cream, @walshbr) :)

**Comment by acrymble** [comment]
can you email it to me @JMParr ?

**Comment by JMParr** [comment]
Done. Thank you!

**Comment by mdlincoln** [comment]
OK

**Comment by arojascastro** [comment]
Done! I tried to add my personal website but it is not working, I think. I tried "www.antoniorojascastro.com", "https://antoniorojascastro.com" and "antoniorojascastro.com"...

**Comment by acrymble** [comment]
Thanks everyone. @arojascastro I've fixed your URL.
