### ISSUE TITLE
Spanish Outreach strategy

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#528]
Opening this because it's on the editorial agenda #504.

We need a strategy for making Spanish-speakers aware of the resource so that all of the work the team have put in is used as widely as possible. I'm sure there are some things already being employed.

**Comment by acrymble** [comment]
@vgayolrs mentioned some plans to host some workshops. He'll let us know if he needs any support for those.

We recognise that there's no urgency at the moment as this project is still new.

**Comment by vgayolrs** [comment]
At this moment I am programming two types of activities. On one hand an inductive talk about the PH project, and on the other hand the realization of a three-day workshop with the most basic topics offered by PH: data management, data manipulation and an introduction to Python. At the moment these are the topics that have already begun to be translated into Spanish, and the idea is also to find more volunteers to translate (and eventually suggest new lessons). I'm going to start at COLMICH taking advantage of the fact that we have new students entering for the doctorates we offer, but the idea is to involve other Mexican and Central American institutions.

**Comment by acrymble** [comment]
This sounds like a good plan for now. I will close this ticket, but it can be reopened if needed.
