### ISSUE TITLE
Document technical integrations

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#529]
It'd be good for the contributing docs on the wiki to have a page documenting the non-github services we're using, who maintains those integrations, and who holds the keys (if applicable) to each of those.

- Travis CI
    - maintained by: @mdlincoln
    - keys: uses GitHub OAuth, no addt'l pw
- Netlify
    - maintained by: @mdlincoln
    - keys: uses GitHub OAuth, no addt'l pw
- Twitter bot
    - maintained by: @walshbr 
    - keys: ???
- Cloudflare
    - maintained by: @mdlincoln
    - keys: DNS currently associated to @mdlincoln Cloudflare account
- programminghistorian.org domain name
    - maintained by: webmaster@chnm.org
    - keys: N/A

**Comment by walshbr** [comment]
Twitter bot involves two keys - Twitter credentials and Google Spreadsheet credentials. The Twitter credentials are embedded in Heroku, but they're ultimately owned directly by our proghist twitter account at https://apps.twitter.com. The Heroku account is owned by me with @mdlincoln and @jerielizabeth as collaborators. 

Google Spreadsheet is a bit trickier b/c it wants a keychain file generated from the google app console to authorize. I've got it generated and living on my local machine, ignored by the github repo, but pushing directly to the heroku remote. Shouldn't be too hard to generate another in the future if we need to pass it off though. Let me know if you need more @mdlincoln

**Comment by acrymble** [comment]
We also have the Google Analytics account, which is tied to my Google account, but which everyone should have access to.

**Comment by mdlincoln** [comment]
I've posted these notes at https://github.com/programminghistorian/jekyll/wiki/Service-Integrations
