### ISSUE TITLE
Isn't the home image too big? 

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#530]
In my MacBook Air 11 inch I just noticed that the name of the website is not visible because the image is too big. 

Now it's 100%:
![100](https://user-images.githubusercontent.com/7340111/28492113-17de77b0-6efd-11e7-9154-5bef8a570fd2.png)

If we reduced it to 75% then we could read *The programming historian en español*:
![75](https://user-images.githubusercontent.com/7340111/28492116-28ea4bce-6efd-11e7-8c13-e49df72a6ac2.png)

50% could even be better. Of course this is subjective. If you have good reasons to not reduce the size just keep it as it is. Thanks.

**Comment by mdlincoln** [comment]
https://reduce-home-img-width--ph-dev.netlify.com/

How does this look @arojascastro? (disregard the different fonts on that preview version of the page - that's another issue I'm about to fix!)

**Comment by arojascastro** [comment]
Yes @mdlincoln nos it's fitting 💯
