### ISSUE TITLE
Alert-warning in spanish transations

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#539]
Hi everybody!
I think that this issue has to be seen directly with @mdlincoln . In the new [lessons's layout](https://github.com/programminghistorian/jekyll/blob/3ac5ba8c0133cba6d4e8c9eb557c82b6d307e2be/_layouts/lesson.html) there is an alert warning that provide a link to the original lessons in the spanish translations (line 115-ss).

```
 {% if page.redirect_from and page.lang == 'es' %}
      <div class="alert alert-warning">
        Esta lección fue publicada originalmente en Inglés. Es posible que desee consulte <a href="/lessons/{{slug}}">el original</a>.
      </div>
{% endif %}
```

To achieve a more correct form in Spanish, line 117 should read:

```
Esta lección fue publicada originalmente en Inglés. Es posible que desee consultar <a href="/lessons/{{slug}}">el original</a>.
```

*consultar* instead of *consulte* 

Sorry, I tried to fix by myself, but I noticed that is necessary to open a new branch to proposse changes, and as I'm not very skilled in Github, I prefer to leave the note here.

**Comment by mdlincoln** [comment]
Thanks @vgayolrs, I'll fix that.
