### ISSUE TITLE
Is it possible to replace "and" by "y" when there are two or more authors?

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#540]
For instance, in this lesson https://programminghistorian.org/es/lecciones/introduccion-a-bash we find `Ian Milligan and James Baker` and it should be `Ian Milligan y James Baker`.

A side note: the editor of the original and the editor of the translation is not displayed yet.

![captura de pantalla 2017-07-29 a las 17 32 21](https://user-images.githubusercontent.com/7340111/28745994-1b2f727a-7484-11e7-8126-157c09fd18ad.png)

**Comment by mdlincoln** [comment]
Yes, I can fix this.

**Comment by mdlincoln** [comment]
Also @arojascastro @mariajoafana @vgayolrs I am about to add the translation reviewer to the lesson layout, but the original `editors` still needs to be added to most of the lesson YAML in order to display correctly.
