### ISSUE TITLE
Spanish translations for editorial team roles

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#542]
For #541 we are now ready to get translations of the editorial sub-team roles and labels. The file is on the `editor_roles` branch and can be edited here:

https://github.com/programminghistorian/jekyll/blob/editor_roles/_data/teamroles.yml

**Comment by vgayolrs** [comment]
I'll take this, @mdlincoln .

**Comment by vgayolrs** [comment]
@mdlincoln : On the first block of translations I have no doubt, but on the second block I would like the meaning to be revised.
i.e.: Ombudsperson = Defensor
In many Spanish-speaking countries *Ombudsperson* is translated as "Defensor del Pueblo" , but many times the term used is the English one. @arojascastro , @mariajoafana , any suggestion?

**Comment by arojascastro** [comment]
What about "intermediario" o "mediador"? It is true that "defensor del pueblo" is widely used but in a legal context. In this context I am not sure. I would go with "ombudperson" (I never heard of that word before but now I got used to it) or "mediador" (de conflictos, se entiende). Anyway, a side note: I am going on holidays today! Back to work on 22 August 🥇

**Comment by vgayolrs** [comment]
Thanks @arojascastro , makes sense to me (hapy holidays!). @mariajoafana , any thoughts?

**Comment by mariajoafana** [comment]
The one that I've heard in the press "defensor del lector". I do like "mediador" and maybe we can keep "ombudperson" in parenthesis. Enjoy your holidays @arojascastro !

**Comment by vgayolrs** [comment]
So, lets keep "mediador" instead of ""defensor". Thanks @mariajoafana , @arojascastro !

**Comment by mdlincoln** [comment]
Thank you all for taking a look! If you are satisfied with the translations, @vgayolrs, you may close this issue.

**Comment by vgayolrs** [comment]
I'm closing this issue but, please, @arojascastro and @mariajoafana , if you think that any translation of roles or definitions could be improved, don't hesitate and re-open it. Thanks everybody!
