### ISSUE TITLE
introductory_state_example.csv is not accessible

### ISSUE THREAD

**Issue by pkiraly** [programminghistorian/jekyll#543]
- The full title of the lesson: Data Wrangling and Management in R
- URL of the lesson: https://programminghistorian.org/lessons/data_wrangling_and_management_in_R
- The system I am using: Linux

The 'Data Wrangling and Management in R' lesson is based on a CSV file which should be download from Dropbox: https://www.dropbox.com/s/8pvgnvg5g14ka59/introductory_state_example.csv?dl=0, but for me it is not accessible. I try to access it from Chrome and Firefox in logged in and logged out state (to my Dropbox account), none of the attempts are working. Without accessing the file, it is not possible to follow the lesson. The message I got from Dropbox:

That file isn’t here anymore 
Someone might’ve deleted the file or disabled the link.

Best,
Péter

**Comment by mdlincoln** [comment]
@ianmilligan1 Shouldn't this file be hosted on our repo anyway, and not in dropbox?

**Comment by ianmilligan1** [comment]
Yes. Let me fix it – thanks for flagging this.

**Comment by ianmilligan1** [comment]
Hazzah, fixed. Sorry about this @pkiraly but thank you so much for letting us know. It works now on my end.

**Comment by pkiraly** [comment]
You are extremely reactive! Thanks, it works for me as well.

**Comment by ianmilligan1** [comment]
A dumb mistake on my end, so am glad I could correct it quickly (and thanks for pinging this to me so quickly too @mdlincoln!).

**Comment by mdlincoln** [comment]
Hey, you caught me during my morning coffee, so it was no trouble :) Thanks @pkiraly for reporting the issue.
