### ISSUE TITLE
Error reported in "Data Wrangling and Management in R"

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#545]
Received via email from Erik Johnson:

> Nice tutorial. Here is the info.
> 
> https://programminghistorian.org/lessons/data_wrangling_and_management_in_R
> 
> Code chunk:
> 
> secular_colleges_after_1812<-early_colleges%>%
> filter(established < 1812)%>%
> mutate(is_secular=ifelse(sponsorship!="Secular", "no", "yes"))
> 
> ggplot(secular_colleges_after_1812) +
> geom_bar(aes(x=is_secular, fill=is_secular))+
> labs(x="Is the college secular?")
> 
> 
> Should be:
> 
> secular_colleges_after_1812<-early_colleges%>%
> filter(established > 1812)%>%

Thanks all!

**Comment by ianmilligan1** [comment]
Thanks @jerielizabeth – let me ping @nabsiddiqui as well (I will send him an e-mail). 

@nabsiddiqui - let me know, if you let me know the change I can make it for you.

**Comment by nabsiddiqui** [comment]
Hey @jerielizabeth.  Yes, you are correct.  I was using R markdown and copy and pasting from a script.  I must have copied incorrectly from my script.  I'll fix this.

**Comment by nabsiddiqui** [comment]
@ianmilligan1 I set up a pull request with the fixes.
