### ISSUE TITLE
Wiki guidelines on CI and Netlify checks

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#547]
I'm merging #425 now because it contains an image that I reference in #500 - but it needs further editing.

**Comment by mdlincoln** [comment]
I'm going to add to Ian's documentation on how to understand the PR checks by Ravis and Netlify, and how to properly submit a review.

**Comment by arojascastro** [comment]
Please! :)

**Comment by mdlincoln** [comment]
I've added sections on how to see the Netlify preview, and how to properly submit a pull request review.
