### ISSUE TITLE
Eng Managing Editor transition date?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#550]
I just noticed that the new project team page has Jess listed as the Managing Editor in the bios, but Jeri still at the top of the page, and on all the other pages where contact info is present.

Has there been an agreed date to the transition so we can update the website consistently?

**Comment by jerielizabeth** [comment]
We are making the switch at the end of August / beginning of September.

**Comment by acrymble** [comment]
Pages that have mention of Jeri as the managing editor that will need to be swapped:

- [x] /project-team 
- [x] /contribute (in three places)
- [x] /feedback
- [x] /author-guidelines
- [x] https://github.com/programminghistorian/jekyll read me file

Might be worth swapping that to 'Managing Editor' so we don't need to revise in future, but could use Jess's name if that's preferable.

**Comment by JMParr** [comment]
@jerielizabeth  and I are planning a call together to discuss the transition, but yes, we're making the switch in the end of August/early Sept. If it's not too much of a hassle, would it be okay to have my name? Am on the job market.

**Comment by jerielizabeth** [comment]
We will switch over on September 4. I'll push up the changes in a pull request at the end of the week so we can confirm that I caught all the references, and merge it in on the 4th.

I like having the name of the managing editor -- it is not hard to find/replace through the files and feels friendlier to me.

**Comment by jerielizabeth** [comment]
Managing editor switched over this morning! Thanks, all!
