### ISSUE TITLE
Cloudflare blocking OpenRefine access to asset file

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#554]
I am receiving an error with a new lesson we have in the pipeline. We are hosting an HTML file that users are supposed to pull into OpenRefine for parsing. I uploaded the file to the main site (https://programminghistorian.org/assets/fetch-and-parse-data-with-openrefine/pg1105.html) but when I execute the query in OpenRefine, I get the following error (please forgive the html): 

>The owner of this website (programminghistorian.org) has banned your access based on your browser's signature (389432035b7b2a07-ua21).</p> </div> </div> </div> <div class="cf-error-footer cf-wrapper"> <p> <span class="cf-footer-item">Cloudflare Ray ID: <strong>389432035b7b2a07</strong></span> 

Is there an option in Cloudflare to allow this sort of access without compromising security?

Adding @mdlincoln to the issue, as it's an infrastructure question.

**Comment by mdlincoln** [comment]
Gosh, I will look in to that right away. There are some additional settings I will look into right now.

**Comment by mdlincoln** [comment]
@jerielizabeth I tried modifying a setting that was supposed to block suspicious visitors (really, we can just turn this off, as we're only serving static files) Can you try this out again and let me know the results?

**Comment by jerielizabeth** [comment]
It is now working as expected! Thank you!

**Comment by jerielizabeth** [comment]
Closing the ticket since it looks good on my end!

**Comment by mdlincoln** [comment]
Oh good, I'm relieved that was an easy fix.
