### ISSUE TITLE
ISSN in footer

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#555]
Our ISSN is no longer present on the home page. This is strongly recommended by the ISSN guidelines (http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-for-electronic-media/). I suggest the most useful and least obtrusive place to put that is in the footer.

To avoid any design issues, I propose we just swap out the 'Hosted by Github' bit. I don't think we need to advertise for a private company.

**Comment by mdlincoln** [comment]
What is our ISSN number?

**Comment by acrymble** [comment]
2397-2068
