### ISSUE TITLE
Translation for Editorial Guidelines step 10) Confirm all links and YAML headers are functioning correctly

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#556]
I have updated the Editor Guidelines with a new section on how to check the results of our automated YAML and link testing - it is ready to be translated.

https://github.com/programminghistorian/jekyll/blob/gh-pages/editor-guidelines.md

**Comment by vgayolrs** [comment]
Thank you @mdlincoln  . I see that the translation is a bit outdated without counting your new aggregates (lacks the new steps 7, 9 y 10). I'll work on it these days if you agree, @mariajoafana  @arojascastro.

**Comment by vgayolrs** [comment]
@mdlincoln , working on it, first doubt:
On line 129 we read: "If you are not sure how to do that or have any questions, contact Caleb McDaniel for assistance." As Caleb is no longer with us I suppose that the one in charge of clearing the doubts will be you. True?

**Comment by mdlincoln** [comment]
Good catch @vgayolrs . I changed both names - also note that in fc5fb360d77a52e316ef28e58831f150fa4820ba I removed some text from the ph-submissions section of the page that was redundant.

**Comment by vgayolrs** [comment]
@mdlincoln , Line 296 = There is a small error in the internal link; Says: "\#\8-thank-everyone-and-encourage-promotion", should say: "\#\11-thank-everyone-and-encourage-promotion"

**Comment by vgayolrs** [comment]
@mdlincoln Finished translation. I think It's working OK on the website. You can close this issue, but I encourage @arojascastro & @mariajoafana to review the page and reopen this If they find any defect. Thank you!

**Comment by mdlincoln** [comment]
Thanks 🎊

**Comment by arojascastro** [comment]
Great! Reviewed!
