### ISSUE TITLE
TOC "errors in Generating an Ordered Data Set from a Text File"

### ISSUE THREAD

**Issue by jjon** [programminghistorian/jekyll#557]
Some recent (last month) change broke the TOC in the lesson "Generating an Ordered Data Set from a Text File". I've fast-forwarded my local repo to match the upstream repo, and I've pushed it to https://github.com/jjon/jekyll. I'll be happy to make the necessary changes and make a pull request, but I'm not certain what changes need making. My surmise is this:

The TOC directive: `{% include toc.html %}`

generated the following html:

```
<li><a href="#-a-couple-of-useful-functions-before-we-start" id="markdown-toc--a-couple-of-useful-functions-before-we-start"></a><a name="prelim" target="_blank"></a> A couple of useful functions before we start:
    <ul>
        <li><a href="#-levenshtein-distance" id="markdown-toc--levenshtein-distance"></a><a name="levenshtein-distance" target="_blank"></a> Levenshtein distance</li>
        <li><a href="#-roman-to-arabic-numerals" id="markdown-toc--roman-to-arabic-numerals"></a><a name="Roman-Numerals" target="_blank"></a> Roman to Arabic numerals</li>
    </ul>
</li>
... snip
```
This created hrefs with extraneous hyphens because the markdown has leading whitespace, like this:

```## <a name="prelim"></a> A couple of useful functions before we start:```

Could someone have a look and let me know if my surmise is correct? If so, I will remove the offending spaces, push the result to my github fork and issue a pull request.

NB: Git is not my native language, so I'm groping around here fairly gingerly.

Thanks,
Jon

**Comment by mdlincoln** [comment]
Thanks for the heads up @jjon - yes, we did a switchover to automatically generated markdown TOCs on all lessons in our redesign, and I didn't notice that this lesson had some custom formatted subheaders. If you would remove the spaces and create a pull request, I'd be very happy to merge it! Thanks.

**Comment by jjon** [comment]
Thanks for responding so quickly @mdlincoln - I'll get to it as soon as I can.

**Comment by jjon** [comment]
@mdlincoln - Done. Please also post here if I've screwed anything up.
