### ISSUE TITLE
How to import my existing unity project to android studio project

### ISSUE THREAD

**Issue by nubhokage1991** [programminghistorian/jekyll#559]
I am making a project about AR using unity and vuforia sdk. I just want to know if it is possible to run my existing unity project to a android studio project let's say in android studio I have a button, when I press that button my unity project (app) will run just like this one I found on youtube https://www.youtube.com/watch?v=665waHAeA1k&t=32s because I am planning on saving images in sqlite database or is it possible to save images in sqlite database in the unity engine.

I am developing a simple app and AR is its main function but also there is a function where you can choose a destination, in a school set-up (it's a small vicinity) instead of using gps location I'm planning on using images of the pathways to a certain location, in this way I can make my app independent to the internet.

Please help me, I know I'm asking too much (badly need it) but just a simple demonstration on how to do it.

**Comment by mdlincoln** [comment]
Hi @nubhokage1991 - unfortunately we aren't able to answer really specialized questions like this! However you may have better luck finding qualified AR practitioners on stackoverflow.com by searching for "augmented reality" or "virtual reality": https://stackoverflow.com/questions/tagged/augmented-reality
