### ISSUE TITLE
Managing Reviewer Requests

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#560]
Another issue for the editorial meeting: 

I received feedback asking about how we are managing reviewer requests, as this particular person received multiple review requests (each from a different editor) all within the span of a few weeks. 

In the interest of not over-burdening any particular community member with review requests, it appears that a system for communicating internally whom we are asking to review would be useful. Some ideas on how this could be managed include: through the submissions issues; through an internal spreadsheet; through email.

**Comment by ianmilligan1** [comment]
I think an internal spreadsheet would be good – I don't think we should make requests public, as it sort of puts people on the spot if they can't do it for whatever reason, and I think that'd be a lot of e-mail to keep track of.

**Comment by drjwbaker** [comment]
Spreadsheet.

**Comment by walshbr** [comment]
Yeah spreadsheet seems good to me.

**Comment by jerielizabeth** [comment]
Cool! I have a google spreadsheet already with people who have contacted us to express interest in reviewing. It makes sense to me to have this information in the same spreadsheet.
