### ISSUE TITLE
HTML-Proofer error from Project Gutenberg

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#561]
I have managed to break things in (not really) new and (not so) interesting ways. 

I am getting the following error message from Travis: 

> - ./_site/lessons/fetch-and-parse-data-with-openrefine.html
> *  External link http://www.gutenberg.org/ebooks/1105 failed: 403 No error
> htmlproofer 3.7.2 | Error:  HTML-Proofer found 1 failure!

Which is a link in the lesson I am working on pushing up. The trouble is, that link works just fine from a browser or via cURL. 

I see in the build.sh file that we are explicitly skipping another PG book link. Would the best way forward be to add this link to the url-ignore line? Is there a generalizable solution we can pursue?

**Comment by mdlincoln** [comment]
I modified the skip command into a regex, so that it'll skip any project gutenberg link. Unfortunately, their server sends bizarre HTTP response codes even though they load fine in browsers...
