### ISSUE TITLE
British Museum SPARQL endpoint failing again

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#569]
[Latest build is failing because the British Museum's SPARQL endpoint is returning HTTP 400 codes for my SPARQL lesson.](https://travis-ci.org/programminghistorian/jekyll/builds/266179298)

This is related to #290 though affects the lesson on a much larger scale, as it means all the British Museum links don't quite work anymore. I'm going to contact Dominic Oldman about this and see if it can't be resolved at the source, because really, this means one of their major online services - about to be relaunched to much fanfare - is not actually functioning.

That said, it's a good example of a hosted resource changing/breaking and fouling up a lesson, so has some bearing on #534.

**Comment by mdlincoln** [comment]
OK, BM endpoint is back up - but it looks like some tiny ontology namespace changes have broken some of the sample queries in this lesson. This is a very small fix - I need to make sure that `PREFIX`es are supplied for every query explicitly now. Will do that shortly.

It's also worth noting that the interface on their SPARQL endpoint has changed a bit, so the screenshots are now a little out of date. I think this is an entirely superficial change that shouldn't impact the lesson much, but I'm admittedly a biased user. @drjwbaker you've used this service a bit - any thoughts on whether we need to further update the lesson?

**Comment by mdlincoln** [comment]
Clarifying thought: I think this kind of superficial interface change is precisely the kind of thing that users should be able to work through without needing to re-screenshot everything. But it may be worth some note in the text that the interface has changed a bit, even if the core data model remains the same.

**Comment by mnscholz** [comment]
The BM endpoint seems to be down since quite some time (at least a few months now).
So I wonder whether there are plans to change this lesson to use another endpoint.

**Comment by mdlincoln** [comment]
This is quite frustrating given the British Museum's pretense to be a leader in the field of museum information.

I'll survey the possibility of swapping out the URLs here to the new, more stable ResearchSpace ones. However, if this is not possible, then I will regretfully recommend both this and the Spanish translation be retired. A new endpoint would mean a new lesson. I will try to report back by October 15th at the latest, if not sooner.

**Comment by mnscholz** [comment]
Thanks, Matthew!
I just realized that Palladio seems to have vanished, too(?). At least the link's domain is abandoned and I couldn't find a working one.

Edit: Palladio moved to http://hdlab.stanford.edu/palladio/

**Comment by acrymble** [comment]
Can you contact them about it @mdlincoln ?

**Comment by acrymble** [comment]
@svmelton it may not be obvious, but this is an English lesson, so this falls under your remit.

**Comment by svmelton** [comment]
Thanks, @mdlincoln—are there any updates on swapping the URLs, or should we plan to retire the lesson?

**Comment by mdlincoln** [comment]
Thank you for the reminder. After some research, there does appear to be a complex workaround for re-pointing to the British Museum via new URLs. However, I now have no faith whatsoever in this institution maintaining these resources. Nor, unfortunately, do I have the bandwidth right now to rewrite this lesson to point to a new resource. 

I will be doing a class on SPARQL next summer which may provide an opportunity to write a new lesson on this pointing at a more reliable endpoint, but I would treat that as an entirely new lesson to be reviewed again.

I'm sorry to say that the best option right now is to retire the lesson. I will compose a PR now that retires this as well as its Spanish translation.

**Comment by acrymble** [comment]
@mdlincoln are you happy for me to contact the British Museum to enquire about this before we  commit to retiring?

**Comment by mdlincoln** [comment]
No, we've waited long enough, and I have done my fair share of outreach.

**Comment by drjwbaker** [comment]
In September 2018 I attempted contact Dominic at the BM with some questions about https://public.researchspace.org/sparql. I heard nothing back. In the context of sweeping personnel changes at the BM in the last year and a bit, I'm not sure how active their endpoints are any more.

**Comment by acrymble** [comment]
Ok.  But let's keep retirement issues within the remit of managing editors, who should have full intellectual control of what's happening within their given publication. So you should be recommending retirement rather than doing it yourself.
