### ISSUE TITLE
Sort by API Counting Incorrectly

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#574]
Sorting by topic for API on the lessons page is counting the number of lessons on the page incorrectly. It lists 1 as the number of lessons for that topic, but selecting it produces 6 lessons in the sorting interface.

**Comment by mdlincoln** [comment]
I have no javascript-fu, and nothing sticks out in the lesson page HTML or in the lessonfilter.js that would seem to explain why this is happening. FWIW only one of the lessons there - Fetch and Parse Data with OpenRefine - actually has `api` as one of its topics. All the rest are `web-scraping`

@amandavisconti do you have any idea what could be happening here?

**Comment by walshbr** [comment]
Just took a look - should be fixed in PR #577. Was searching for topic by looking for a substring of a larger string instead of an item in an array.
