### ISSUE TITLE
community engagement on PH - brainstorming

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/jekyll#579]
possibly in line with discussions #576 and #304 

During our August meeting, I suggested that it might be helpful, along the lines of DH and general online coding communities, to have a crowdsourced area of PH. I brought up the idea of hosting a wiki (and now maybe a discussion board) that could serve as an engagement space for our users/readers. I think it's important for us to outline that lessons are valuable and should be recognized in accordance with the expectations of the humanities, but there are also expectations from the programming side of things to be communal in the way things are taught and learned. In that spirit, it could be fun to open up an area of the site for these forms of communication.

In terms of a wiki - initially I conceived of a devil's advocate position wherein we have our peer-reviewed articles and then we have a wiki, perhaps getting our users/readers to give insights in how to use certain tools that aren't at the level of a full-blown lesson, but still could be helpful for those getting started and could help support some of our lessons (getting into the nitty-gritty of sw, dependencies etc, which would be ok in this space, since we'd expect the crowdsourcing to serve as check on the content).

The flip side is a discussion area - in a way mirroring how many of the code discussion boards work, this area could give users/readers a space to ask questions about lessons _for other users_. Authors could feel free to contribute, but I don't think that should be expected. Also could be a space for users/readers to suggest lessons/features/etc for the publication.

I think others had some additional ideas for community engagement spaces for PH. Please add them here!

**Comment by acrymble** [comment]
we used to have comments on our lessons when we used wordpress. Would that be the same idea?

**Comment by alsalin** [comment]
@acrymble It could be? right now, I think everything is on the table for brainstorming.

**Comment by drjwbaker** [comment]
As discussed at the Editorial Meeting https://github.com/programminghistorian/jekyll/issues/596 we should decide how we want to **prioritise our modest resources** with regards to community engagement. So, do we want to..
- do a survey https://github.com/programminghistorian/jekyll/issues/576
- create a wiki (this issue)
- add in some sort of comment fucntionality
- encourage people to use https://web.hypothes.is/
- something else
- none of the above

**Comment by ianmilligan1** [comment]
My vote would be for comment functionality, encouraging hypothesis, and just trying to be friendly and approachable whenever possible.

**Comment by drjwbaker** [comment]
@ianmilligan1 In addition to or instead of some of the other things? Setting priorities for resource allocation is what - I think - we want to get out of this.

**Comment by ianmilligan1** [comment]
Instead of other things on your list above, I don’t think we should devote energy to another survey at this point or a wiki. But again I’ve been on leave so I am a bit out of the loop.

**Comment by drjwbaker** [comment]
Okay. Happy to go with whatever if we have quorum (slight OT: when was the last survey?)

**Comment by alsalin** [comment]
I think that there is some momentum being #576 survey (as per #596 call and ongoing discussion). I think the survey is a great idea and could be the initial stages of future changes to the ways in which we do community engagement. I also really like the idea of using hypothes.is.

**Comment by walshbr** [comment]
Closing this issue to consolidate discussion in the direction of #576.
