### ISSUE TITLE
directories for lessons?

### ISSUE THREAD

**Issue by fredgibbs** [programminghistorian/jekyll#58]
i wonder if it wouldn't be easier especially in the long term for moving lessons through the pipeline and maintaining them if we--instead of putting all lessons as files in the lessons directory, and putting images in the image directory, etc.--put all assets associated with a single lesson (and the lesson .md itself) in a single directory with the same name as the lesson under the main lessons directory. that way all assets (images, files, maybe screencasts or videos in the future) for each lesson stays with the lesson. this shouldn't change the main lesson URLs, though we'd need some scripting to change the image links in the existing lesson files. i think there are distinct advantages for editing and making new lessons with this approach. are there procedural reasons not to do this (other than the work involved to make the switch)?

**Comment by wcaleb** [comment]
Just a note that if we want to reconsider this, I've recently learned that you can activate a Jekyll gem that redirects old URLs to new ones. So if, for instance, we wanted to do the "each lesson has its own folder" approach suggested by @fredgibbs, we could have old URLs (which were to specific html files) redirect to new ones.
