### ISSUE TITLE
Antconc sample corpus 404

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#586]
It looks like the sample corpus for ["Corpus Analysis with Antconc"](https://programminghistorian.org/lessons/corpus-analysis-with-antconc#tutorial-downloads) was being hosted on Dropbox instead of on our site - and it's now a 404 link. 

I've pinged Heather to see if she has a copy of the data so I can commit it directly to our repo.

**Comment by mdlincoln** [comment]
Alternatively, if anyone _here_ happens to have that data downloaded, commit it or email it to me so I can add it.

**Comment by acrymble** [comment]
Do we have any other drop box links?

**Comment by mdlincoln** [comment]
@acrymble I'll check and post separate issues as needed

**Comment by mdlincoln** [comment]
Heather will send me a copy of the data in the coming week.
