### ISSUE TITLE
Translate new bios into Spanish

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#597]
The file `ph_authors.yml` needs to be updated with a few translations of bios into Spanish -- see entries after Anandi Silva Knuppel. This pending bios correspond to lessons that have not been translated yet.

**Comment by vgayolrs** [comment]
Me parece bien. Si no hay prisa, lo hago esta tarde.

**Comment by arojascastro** [comment]
Gracias @vgayolrs, como veas. Si te encargas tú, cuando termines puedo revisarlo y cerrar el tícket.

**Comment by vgayolrs** [comment]
Listas actualizaciones @arojascastro . Si quieres comprobar y cerrar el ticket. Slds!

**Comment by arojascastro** [comment]
Question: Can  you be `a PhD candidate in literature at Washington University in St. Louis` and `postdoctoral fellow` at the same time? Maybe he is a `predoctoral fellow`? @acrymble 

```John Ladd is a PhD candidate in literature at Washington University in St. Louis and postdoctoral fellow for Six Degrees of Francis Bacon at Carnegie Mellon.```

**Comment by acrymble** [comment]
It doesn't make sense but it is possible. It's a job title.

**Comment by arojascastro** [comment]
Ok, then I am closing this. Thanks!
