### ISSUE TITLE
Translate snippet into Spanish

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#599]
In the Spanish version of our [Team project](https://programminghistorian.org/es/equipo-de-proyecto), there is a snippet (`Project Team Roles`) in English that should be available in Spanish. 
![captura de pantalla 2017-09-11 a las 14 35 12](https://user-images.githubusercontent.com/7340111/30275005-0b51c76a-9700-11e7-838d-8ffafb7de4d3.png)

I cannot find where is this snippet @mdlincoln 

:)

**Comment by vgayolrs** [comment]
As far as I understand, the head of the list is here:
https://github.com/programminghistorian/jekyll/blob/6b6aa7699238dec6515f001de2c67a42c2897034/_includes/project-team-loop.html
But I do not know how to do the modification so that the automatic translation is done as with the rest of the list.

**Comment by mdlincoln** [comment]
Good catch @arojascastro. I've edited the page so that header is now a snippet that can be translated here: https://github.com/programminghistorian/jekyll/blob/1f9493499f3a9cf20c241e3c3bb0e526071137d9/_data/snippets.yml#L215-L218

**Comment by vgayolrs** [comment]
Thank you very much @mdlincoln ! @arojascastro, @mariajoafana  :  I'm proposing to translate "roles" as "papel" (aunque podría ser "función en el equipo del proyecto"), para no usar el anglicismo, salvo mejor opinión vuestra.

Aprovecho para indicar que también hay que traducir varios segmentos que cambiaron:

> Please direct correspondence in the first instance to:
> Jessica Parr (English)
> Victor Gayol (Spanish)
>  Antonio Rojas Castro (Spanish)

> You can follow the Programming Historian on Twitter: @proghist. 

Yo me encargo ahora y cuando creas, @arojascastro , cierras el ticket.

**Comment by arojascastro** [comment]
Gracias @vgayolrs, me parece bien. Si quieres que traduzca algo dímelo, otherwise cerraré el ticket cuando me lo digas.

**Comment by arojascastro** [comment]
I am closing this.
