### ISSUE TITLE
Add data to tracking reviewers spreadsheet

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#600]
We should start tracking reviewers to this [spreadsheet](https://docs.google.com/spreadsheets/d/1EMQyVpIYnWjNr4hEQDDilkUl28gGPA2gSLjp61_AFgM/edit#gid=1063152009). Some information is already recorded here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md

**Comment by vgayolrs** [comment]
Perdón, querido @arojascastro , ¿por qué no lo dejamos en público en el registro que ya tenemos en github? Requisitar todo en la hoja de cálculo quizá nos cause doble trabajo e inconsistencias entre una y otra lista que, por cierto, deberíamos hacer más pública invitando a posibles traductores. ¿Qué piensas @mariajoafana ?

**Comment by vgayolrs** [comment]
Por ejemplo, de la lista en git: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md, ya quité una traducción que tenía yo pendiente de una lección que se ha quitado del sitio, y así también deberíamos quitar dos perspectivas de traducciones que han sido retiradas (deprecated): 1) https://programminghistorian.org/lessons/deprecated/creating-new-items-in-zotero , 2) https://programminghistorian.org/lessons/deprecated/counting-frequencies-from-zotero-items. Pero díganme ustedes qué les parece mejor.

**Comment by arojascastro** [comment]
Estoy de acuerdo en que no hay que duplicar, pero en la lista de traducciones no hay datos sobre cuándo contactamos al traductor o al revisor, y otra información importante. Con todo, para mí me es más cómodo no utilizar la hoja de cálculo (fue sugerencia del equipo inglés). También coincido en que debemos quitar las lecciones descartadas (no sé si queda alguna más).

**Comment by arojascastro** [comment]
Por otra parte, las lecciones ya entregadas se deben eliminar de la de lista; por ejemplo, creo que ya  hay ticket de revisión para tu intro a shell... de esa manera veremos las que están pendients solamente, ¿no? Hay alguna sin fecha de entrega o que ya han pasado la fecha de entrega.

**Comment by arojascastro** [comment]
Maybe the new editors @jenniferisasi and @jamotilla can give us their opinion about this?

**Comment by jenniferisasi** [comment]
@arojascastro upon checking the English team's tracking, I can really see the use of having our own tracking of reviewers. 
One use I can think of right now is to have a record of positive or negative responses and the time each reviewer takes to review. Also, as you point out, there's no record of reviewers on the [/lista-de-traducciones.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md) and a list will avoid asking someone who is working on one or two reviews at the moment to review another tutorial.

**Comment by arojascastro** [comment]
Good! 

For the old tutorials: Anyone would like to start adding the names of our reviewers, their github username, the date they finished their contribution, the lesson and editor? (maybe also their email) Who is willing to take care of it? That person should just go to the website and browse all the translations and take note of the information. @vgayolrs @mariajoafana @jenniferisasi @jamotilla 


For the on going translations, I guess each editor should add that information.

**Comment by jamotilla** [comment]
I can do it @arojascastro

**Comment by arojascastro** [comment]
Any progress on this @jamotilla? Please let us know when you are done so we can extend your work and close finally this issue.

**Comment by jamotilla** [comment]
@arojascastro it´s almost done

**Comment by arojascastro** [comment]
Cómas vas con esto @jamotilla ?

**Comment by jamotilla** [comment]
Ahora lo reviso @arojascastro, hoy mismo queda

**Comment by arojascastro** [comment]
I think we can close this issue, right? @jamotilla ?

**Comment by jamotilla** [comment]
Let me check this today @arojascastro , i let you know later

**Comment by jamotilla** [comment]
It´s done @arojascastro, you can close the issue.

**Comment by arojascastro** [comment]
Gracias! @jamotilla
