### ISSUE TITLE
Update list with new translations

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#601]
I am not sure this [list](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md) contains the recent lessons, so we should check. Also, we should decided if we keep this list to track translators or if we want to add a tab to the spreadsheet shared with the English team. What do you think?

After updating the document, we should contact some translators and ask for further information -- and of course send reminders to list in order to get more people involved in the translations of pending lessons.

**Comment by arojascastro** [comment]
Our list is structured using the old classification system (such as Data Management, Data Manipulation, etc.). I think we should update the list taking into account the new categories employed after redesigning the website (obtain, analyze, etc.) and remove the lessons that have been already published. 

I had a look at the list and we should contact the following translators:
- construccion-de-sitios-estaticos-usando-jeyll-github-pages (Gloria Cortés)
- editing-audio-with-audacity (jamotilla)
- intro-to-linked-data (maría jesús colmenero)
- intro-googlemaps-googleearth (andrés gattinoni)
- georreferenciar-qgis (mariajoseafana) ;))
- creating-an-omeka-exhibit (mpgarcia10)

Let's try to review and publish six new lessons before 2018!

**Comment by acrymble** [comment]
I see one of the API lessons is assigned to @vgayolrs. Remember, those were deprecated.

**Comment by vgayolrs** [comment]
Yes @acrymble , I've noticed that, thanks. @arojascastro, I think we have to update that list and keep it public, but we can also add a tab to the spreadsheet.

**Comment by arojascastro** [comment]
Ok, let's keep it public. But how about make two sections only and make it simpler? 

### Traducciones pendientes
- título en inglés y enlace a la versión inglesa

### Traducciones en proceso
- título en inglés y enlace a la versión inglesa

We can record further details in the private spreadsheet. What do you think? Or only *Traducciones pendientes*?

**Comment by arojascastro** [comment]
Por cierto, enviaré un email jamotilla y a maría jesús colmenero, preguntando. ¿Queréis que me ponga en contacto con el resto? Creo que de los otros no soy editor o no me puse en contacto yo, por lo que es posible que no tenga el email.... ya me decís :)

**Comment by arojascastro** [comment]
Done in commit (Submissions) 2c9860f4ab50ae2a7bab9120380b6b32ca65780d

While updating our list, I realized that the lesson on data management in R uses undercores in the name of the file: https://programminghistorian.org/lessons/data_wrangling_and_management_in_R

Is there a reason for that @ianmilligan1 ? Thanks.
