### ISSUE TITLE
Example missing in Introduction to the Principles of Linked Open Data

### ISSUE THREAD

**Issue by drodz11** [programminghistorian/jekyll#605]
Hello,

Using Chrome browser version 60.0.3112.113 on Mac OSX Yosemite 10.10.5.

Link to lesson: https://programminghistorian.org/lessons/intro-to-linked-data

In the RDF/XML section, there appears to be an example missing after the second paragraph ending in "with the prefixes declared inside the XML snippet, this is:" I have included a sceenshot below.

Thank you to Jonathan Blaney and everyone on the PH team. This is such an incredible resource!  

![screen shot 2017-09-13 at 3 44 42 pm](https://user-images.githubusercontent.com/25777161/30397472-0966a4ec-989b-11e7-8612-d87e8c58fbad.png)

**Comment by mdlincoln** [comment]
Thanks @drodz11 for the report! We'll look in to updating this to fix.
