### ISSUE TITLE
adding translation editors to YAML metadata

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#611]
I have been reviewing some tutorials and I found out that our metatada information is not very consistent. 

### tutorial without original reviewers
![sin_revisores_originales](https://user-images.githubusercontent.com/7340111/31013913-97e1864a-a518-11e7-8ab9-0bc7c1c672e1.png)

### tutorial without translation editor
![sin_editor](https://user-images.githubusercontent.com/7340111/31013925-a545a816-a518-11e7-8974-eff854c613e1.png)

### tutorial with translation editor
![traduccion_con_editor](https://user-images.githubusercontent.com/7340111/31013935-ad66e7b2-a518-11e7-85bc-85bf77e3adae.png)

In my opinion, only the last tutorial contains the necessary metadata information.

I am wondering whether is possible to use any validation system for this (Travis?) @mdlincoln @acrymble ?

**Comment by arojascastro** [comment]
By the way the snippet *traducción editado por* should be *traducción editada por* (in femenine).

**Comment by acrymble** [comment]
Some of the early lessons involving Fred Gibbs didn't have reviewers. That's not inconsistent with what happened. He did the reviewing himself, acting as an editor.

**Comment by arojascastro** [comment]
Ok, but can we validate the metadata about translations? I just want a list of tutorials that do not contain that info... of course I can check out myself but it is time consuming. If we cant do it automatically please let me know and I will.

**Comment by mdlincoln** [comment]
We do check metadata @arojascastro (#426) however right now `translation_editor` is not validated, because only one lesson actually had a `translation-editor` in it. I'll add that field to the checklist now, and then you'll see all the errors for lessons that are missing it.

**Comment by mdlincoln** [comment]
~You can find the list of lessons with missing `translation-editor` here: https://travis-ci.org/programminghistorian/jekyll~

**Comment by arojascastro** [comment]
Super! @mdlincoln

**Comment by mdlincoln** [comment]
Apologies, the specific build listing the missing YAML is here: https://travis-ci.org/programminghistorian/jekyll/builds/281347660

**Comment by arojascastro** [comment]
@mdlincoln  🔝  💯

**Comment by mdlincoln** [comment]
@arojascastro Is it possible to add these editors soon? Without having the editor metadata in place, we will keep receiving build errors and it makes other development work difficult.

**Comment by arojascastro** [comment]
@mdlincoln sorry, I can't work on this until Sunday... you may turn it off? Now I know that basically all lessons need that feld. Maybe @vgayolrs and @mariajoafana can help me?

**Comment by arojascastro** [comment]
I am sorry @mdlincoln but I must postpone this tak for some more days.

**Comment by mdlincoln** [comment]
Hi @arojascastro @vgayolrs what is the current status of this ticket?

**Comment by arojascastro** [comment]
Sorry for the super delay @mdlincoln - this pull request should solve the problem: https://github.com/programminghistorian/jekyll/pull/666

Please let me know if there is any lesson missing that field yet.

**Comment by arojascastro** [comment]
Thanks @vgayolrs for approving my request. Can @mdlincoln check that Travis validation is good?
