### ISSUE TITLE
Broken documentation links on "Exploring and Analyzing Network Data"

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#613]
It looks like the python networkx package just moved its documentation, and may have done so in ways that aren't easily find-and-replaceable. @walshbr would you perhaps reach out to the authors and ask if they could take a look? If not, we can Wayback all the links... but that'd be unfortunate for such a major package.

**Comment by mdlincoln** [comment]
The new home for their docs: https://networkx.github.io/documentation/stable/index.html (they didn't make any redirects!)

**Comment by walshbr** [comment]
Wow. Sure! I'll get in touch with John. And just to clarify @mdlincoln, as with the Audacity tutorial, we're only doing this for the production version of the lesson in the jekyll repo, right? Not touching the archived pre-publication version on ph-submissions.

**Comment by mdlincoln** [comment]
those never get touched again. Does it say somewhere that they need to be updated?

**Comment by walshbr** [comment]
Nah I'm likely just paranoid. I'll ping John.

**Comment by jrladd** [comment]
Thanks for bringing this to my attention. I'd noticed that NetworkX finally updated to a stable v2.0, but I hadn't thought about the documentation links. I'll fork the repo on Monday and make a few changes. They've also changed a couple small syntax things (nx.set_node_attributes, I think) that may have to be updated too.

**Comment by jrladd** [comment]
Okay, I went ahead and forked the repo, made changes, and opened at pull request at #614. That should fix all the links and update a little bit of the NetworkX syntax. Let me know if there's more I can do!
