### ISSUE TITLE
Editorial board diversity suggestion

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#619]
I think we've done a lot to try to diversify ourselves and our intended audiences in the past couple of years. I wanted to raise the idea of adopting a 50%+1 policy for our editorial board members, so that the board never becomes more than 50%+1 person from the same gender / nationality.

Hopefully we'll have some stability in our board for a few years, but I wanted to raise this for comment. We can do it at the editorial board if folks prefer, and can adopt Chatham House Rule if that makes the conversation easier.

At the moment, we wouldn't contravene this policy if we were to adopt it.

**Comment by walshbr** [comment]
Sounds good to me - my only comment @acrymble would be that you had a lot of good thoughts when we were last looking for new board members about other kinds of diversity that we might consider in addition to race, gender, and nationality - Academic/GLAM, senior/junior, academic background/current affiliation. Gender/nationality are certainly the biggest and probably the ones worth explicitly binding to a numerical policy like that. But it might be good to supplement that policy with some language acknowledging that we will try to honor those other myriad forms as well. Your ideas were good ones, and I'd like to keep them in the mix.

**Comment by acrymble** [comment]
me to draft some text for comment...

suggestion to integrate into the about pages.

**Comment by acrymble** [comment]
Draft text. Based on the premise of a section on the /about page, perhaps under the Gold Open Access section?

The Programming Historian is committed to diversity, and we insist on a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. Our commitment to diversity extends to our Editorial Board, which has adopted a diversity policy to ensure that members from any one gender or any one nation do not comprise more than 50% + 1 of the members on the board. This is to ensure that the project continues to benefit from diverse viewpoints.

--

Please comment and amend.

**Comment by drjwbaker** [comment]
Small addition.

> The Programming Historian is committed to diversity, and we insist on a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. Our commitment to diversity extends to our Editorial Board, which has adopted a diversity policy to ensure that members from any one gender or any one nation do not comprise more than 50% + 1 of the members on the board. This is to ensure that the project continues to benefit from diverse viewpoints. This policy is under perpetual review and we welcome [suggestions](https://programminghistorian.org/feedback) on it from the community.

**Comment by arojascastro** [comment]
I like!

**Comment by acrymble** [comment]
If anyone else has views on this, can you please add them (or thumbs up James' post)? Otherwise we'll take this as agreed.

**Comment by mdlincoln** [comment]
Thanks for drafting this up @acrymble. When you're ready, can you try adding it in as a pull request? Then the translations can go in to the same branch.

**Comment by acrymble** [comment]
Minor tweak to reflect difference between where someone lives and what nationality they identify with:

The Programming Historian is committed to diversity, and we insist on a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. Our commitment to diversity extends to our Editorial Board, which has adopted a diversity policy to ensure that members from any one gender or any one nationality do not comprise more than 50% + 1 of the members on the board. This is to ensure that the project continues to benefit from diverse viewpoints. This policy is under perpetual review and we welcome suggestions on it from the community.

--
Can we get this translated @arojascastro so that we can push it out?

**Comment by acrymble** [comment]
(please)

**Comment by arojascastro** [comment]
En *The Programming Historian* estamos comprometidos con la diversidad y defendemos la necesidad de mantener un espacio de trabajo sin ningún tipo de acoso u hostigamiento basado en el  género, identidad, orientación sexual, capacidades, físico, peso, etnia, edad, religión o nivel de conocimiento técnico de los participantes y colaboradores. Asimismo, nuestro compromiso con la diversidad se extiende a la composición del Consejo Editorial garantizando que los miembros de un mismo género o nacionalidad no alcanzan una ratio superior al 50% +1 del total. Con esto pretendemos que el proyecto se siga beneficiando de puntos de vista distintos. La medida está sujeta a revisiones futuras, por lo que aceptamos el envío de sugerencias de los miembros de la comunidad.

It was hard to translate some words because in Spanish they do not sound ok, so I rephrased and hopefully the meaning will be equivalent. Maybe @jenniferisasi or @jamotilla or @vgayolrs or @mariajoafana can review my proposal?

**Comment by acrymble** [comment]
I just realized that we're in violation of this rule on gender balance.

**Comment by drjwbaker** [comment]
Add @jenniferisasi here https://programminghistorian.org/project-team and we are fine, no?

**Comment by jenniferisasi** [comment]
Hi everyone,

I was working on my bio yesterday but GitHub desktop kept crashing. I'll try again today after I teach. 

Best,

Jennifer Isasi, PhD
Dept. Of Modern Languages
Thomas Hall 215
University of Nebraska at Kearney

**Comment by arojascastro** [comment]
I recommend sourcetree: https://www.sourcetreeapp.com/

**Comment by drjwbaker** [comment]
@acrymble Can you clarify of what you mean by 50% + 1 please (I'm being thick). We are 14. We are split 8/6 on gender now. That is 50% + 1, correct?

**Comment by acrymble** [comment]
I guess you're right in that regard. I had in mind that there'd never be more than 1 more than the other. But this seems fine to me.

**Comment by drjwbaker** [comment]
That would mean we'd always have to be an odd number.

**Comment by acrymble** [comment]
I just realised this is already posted live. Closing issue.
