### ISSUE TITLE
Suggested Workflow for updating translations

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/jekyll#620]
In order to keep updated the Spanish translations, I propose that we adopt a transparent mechanism that allows the Spanish team to be aware at the same time English lessons are being updating.

I suggest that, every time someone makes a change in a lesson, give us notice to any of the members of the Spanish team through the same commit window.

If you think there may be another more efficient mechanism, please discuss it here.

**Comment by acrymble** [comment]
This is related to #630 and a suggestion that we use pull requests for making contributions.

**Comment by walshbr** [comment]
Closing as we're doing pull requests for all changes and adding spanish team members as reviewers to facilitate the translation.
