### ISSUE TITLE
Updating Data Mining the Internet Archive Collection to include IA Configure

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#621]
Annie Swafford wrote in to note that a recent update to the [Internet Archive Python library](http://internetarchive.readthedocs.io/en/latest/quickstart.html) now requires archive.org credentials to run in @wcaleb's ["Data Mining the Internet Archive Collection"](https://programminghistorian.org/lessons/data-mining-the-internet-archive). E-mail below:

>Dear Jessica,
>I have a question about the Programming Historian lesson on "Data Mining the Internet Archive Collection" (https://programminghistorian.org/lessons/data-mining-the-internet-archive).  
>
>When I got the error message "raise AuthenticationError('No access_key or secret_key set! Have you run 'ia configure'",  I realized that the internetarchive python library requires an access/authorization key to run (http://internetarchive.readthedocs.io/en/latest/quickstart.html), which isn't mentioned in the tutorial. 
>
>Do you think the tutorial could be updated to reflect this? (It looks the library was updated at the end of September, which is probably why the tutorial leaves out needing a key.)
>
>Thanks,
>Annie

@wcaleb do you want to update this, or I can if you're swamped. I think it's just a matter of the user being told to:

a) create an account on archive.org;
b) run `ia configure` before any other commands after installing the library to provide it with credentials?

**Comment by arojascastro** [comment]
I think this is also relevant for @vgayolrs  since he is the editor of the Spanish translation - currently under review. Right?

**Comment by vgayolrs** [comment]
Thanks @arojascastro : it is, indeed.

**Comment by wcaleb** [comment]
Looking into it ...
