### ISSUE TITLE
HTRC Solr proxy no longer offered

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#622]
[Text Mining in Python through the HTRC Feature Reader](https://programminghistorian.org/lessons/text-mining-with-extracted-features#whats-in-a-volume) mentions a Solr API in passing at the end of the "What's in a Volume?" section. Our dead link checker flagged a 404 on the wiki it links to... and after brief investigation it looks like that API is [no longer supported by HTRC](https://wiki.htrc.illinois.edu/display/COM/HTRC+Technical+FAQs#HTRCTechnicalFAQs-Q4:WhathappenedtotheHTRCSolrProxyAPI?).

This isn't a huge issue for the lesson, but it might be worth adding a note that this paragraph mentions a resource that no longer works? Or just removing the reference entirely - it is not integral to the lesson.

@ianmilligan1 I'm just paging you as editor of this lesson

**Comment by ianmilligan1** [comment]
Thanks for the heads up @mdlincoln.

I'm in turn going to ping the lead author @organisciak - thoughts Peter, re: removing reference entirely or noting that the API is dead?

**Comment by ianmilligan1** [comment]
FWIW after thinking on this, my vote would be to just remove the paragraph.

**Comment by organisciak** [comment]
Quick catch Matt! I'm looking into this with the HTRC people. There's an alternative Solr close to a public release (most of the attention is on the front end, the API has been stable for a bit), so I'm looking into whether it's better to update or remove the references.

**Comment by mdlincoln** [comment]
@organisciak Did you manage to do any research on this? If you haven't had the time, I quite understand. However, I'll plan on removing this paragraph within the next week if I don't hear from you. We're always glad to re-open the issue and accept new changes if you find a happier solution!

**Comment by organisciak** [comment]
Thanks for the followup, this task fell off my radar. Yes, remove the
mention.
