### ISSUE TITLE
slow page loads in India

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#624]
Google Analytics has changed and they start now warning you of issues with your various audiences. They've highlighted that people in India are experiencing very slow load times on our site. This is actually our second largest user base. Does anyone know of anything we can do to support that or otherwise improve performance for these people?

<img width="311" alt="screen shot 2017-10-15 at 17 31 21" src="https://user-images.githubusercontent.com/646647/31586936-53c8a212-b1d0-11e7-8211-66f08e827d2b.png">

**Comment by mdlincoln** [comment]
The actual serving of pages is nothing we have control over, I'm afraid.

**Comment by acrymble** [comment]
I was thinking more along the lines of making sure our files (eg screenshots) weren't overly large. I know we dont' control the servers directly.

**Comment by drjwbaker** [comment]
Work of the DH Minimal Computing group is relevant here http://go-dh.github.io/mincomp/ I think we are pretty good on this front. My understanding is the fewer interactives and large image files the better.
