### ISSUE TITLE
Sustainability question for lesson with a hosted Virtuoso server

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/jekyll#628]
Hi all,

We have a lesson under development (http://programminghistorian.github.io/ph-submissions/lessons/making-a-small-rdf-database) that uses a hosted Virtuoso server to demonstrate some SPARQL queries. Currently that server is hosted by the author (http://whanley.history.fsu.edu:8890/sparql), which he is willing to continue to do indefinitely. However, that is a rather large external dependency, and given our efforts for sustainability, I wanted to reach out to the group to hear if there are other suggestions on how we might incorporate the hosted server. I am also open to the idea that we not include the hosted server as part of the lesson, if it is too much of a complication for sustainability. 

Pinging @mdlincoln on this as I know you've worked with SPARQL and @alsalin for sustainability.

Thanks!

**Comment by alsalin** [comment]
I would recommend leaving it out as it doesn't seem to be critical to the lesson - seems like there's an option for users familiar with SPARQL to download a file hosted at PH. We could also put in a note that takes users to some documentation on how to setup their own environment for testing.

**Comment by mdlincoln** [comment]
Remove the dependency on an individually-hosted server at all costs. Even pointing to institutionally-hosted ones like Europeana has proven... less than perfect 😬

**Comment by jerielizabeth** [comment]
Thanks @alsalin and @mdlincoln! I'll work with the author to remove it and rely instead on the reader having their own running server.
