### ISSUE TITLE
Update documentation to require large datasets to be put on Zenodo

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#63]

**Comment by wcaleb** [comment]
Just read that GitHub is about to offer [better support for large files](https://github.com/blog/1986-announcing-git-large-file-storage-lfs). Do we need more than 1 GB? If not, would this be an option to consider alongside or instead of Zenodo? @williamjturkel @acrymble @fredgibbs

**Comment by acrymble** [comment]
Current plan is to use this instead of Zenodo for the time being.
