### ISSUE TITLE
Project Team Membership History should be translated?

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#631]
I just realized that this [section](https://programminghistorian.org/project-team#project-team-membership-history) is not translated in the Spanish edition: https://programminghistorian.org/es/equipo-de-proyecto 

Should we translate it? @vgayolrs @mariajoafana

**Comment by vgayolrs** [comment]
En algún ticket puse el dedo en ese renglón y otros de la misma página. Yo me encargo.

**Comment by vgayolrs** [comment]
hecho. cierro, siquieren revisar la página por algún error abrimos el ticket,
