### ISSUE TITLE
Document Workflow for Branches

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#634]
As we move to editing via Pull Requests vs. direct commits (#630), we need documentation for editors on how to (a) open branches; (b) edit on the branch; (c) open up a pull request to bring back to master. This can go in the [Wiki page here](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions).

#617

**Comment by ianmilligan1** [comment]
This is in progress and is accessible here <https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions>. Any comments/suggestions/etc. can go here. Thanks all!

**Comment by drjwbaker** [comment]
As @acrymble is the person who seems to know this workflow least well (no criticism!), I'd be keen to hear what he thinks.

**Comment by acrymble** [comment]
looks fine to me. Will have to test it to know if I get it right.

**Comment by drjwbaker** [comment]
Sure. I think this one will only bed in once we've started doing it.

**Comment by mdlincoln** [comment]
Closing for now. If questions present themselves regarding these docs, let's open up new issues as needed.
