### ISSUE TITLE
Annual Zenodo deposit (2017) - report / documentation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#640]
Linked to #595 I propose adding some documentation on what happened during the calendar year, to accompany the Zenodo deposit of the project. This will make it possible for people to get a sense of what's changing, what's new, etc.

I've suggested the CHNM annual report as a model, (https://rrchnm.org/news/annual-report-2016-2017/) but it doesn't need to be nearly so thorough or pretty. I just think some human-focused documentation about what's been deposited and what happened this year is a good idea.

**Comment by mdlincoln** [comment]
(I posted this comment in #595 but it is more specific to this proposal)

@acrymble This "annual report" just sounds like the yearly blog post you write - which would itself be preserved in the Zenodo archive. Can we just use that instead? Why the added work?

**Comment by acrymble** [comment]
Same reason people put effort into anything they package up and distribute.

A 'dump' of files in a zip or tar ball, devoid of presentation and documentation, is of extreme limited use. To assume someone is going to unzip that, spend several minutes at least figuring out the file structure, and locate a markdown file in a folder called /blog that might contain some details about what happened in the last year, isn't very user friendly.

**Comment by ianmilligan1** [comment]
But why not just use the yearly blog post you write as this descriptive narrative, rather than creating a separate document? (I don't think @mdlincoln was suggesting just leaving it in the `/blog` folder - that would indeed require too much sleuthing) 😄

**Comment by mdlincoln** [comment]
FWIW, Zenodo zips up the repository _as is_, so I'm not sure there is some space for appending other reports to a tagged release? (Though perhaps the GitHub release notes themselves could work @drjwbaker?)

I'd also note that anyone downloading this dump from Zenodo is going to get... well, a pile of directories and files to dig through. If you want to archive the _presentation_ of the site, then we should just be pointing to an Internet Archive cache of the site, and not bother trying to create something with Zenodo that preserves the repository itself.

I'm now actually unsure if @acrymble and @drjwbaker actually have the same purpose in mind when they are thinking of creating archived dumps of the site...?

**Comment by acrymble** [comment]
I suspect we're not far off in our purposes. All I'm asking is that this take longer than 3 minutes, and doesn't have the title 'PH Dump 2017'. It needs a decent description of what the deposit is, contains, and ideally a human-readable change log that tells readers how it's different from the previously deposit from the year before.

Effectively, this should be deposited with the care that you'd expect of a librarian or archivist.

**Comment by drjwbaker** [comment]
> Effectively, this should be deposited with the care that you'd expect of a librarian or archivist.

Yes. It will be. Once I get the mechanism going we'll have a dummy deposit. It will have nice wording, promise :)

> I'd also note that anyone downloading this dump from Zenodo is going to get... well, a pile of directories and files to dig through. If you want to archive the presentation of the site, then we should just be pointing to an Internet Archive cache of the site, and not bother trying to create something with Zenodo that preserves the repository itself.

Reusing the deposit in that way isn't the point. The point is to create a snapshot of the project (that isn't meant to be useable) in a scholarly manner, with a DOI, in a place we can trust.

**Comment by acrymble** [comment]
I think we've agreed on this. I'm closing the ticket.
