### ISSUE TITLE
Geoparsing Text with the Edinburgh Geoparser

### ISSUE THREAD

**Issue by fortinma** [programminghistorian/jekyll#648]
I think there is just a tiny bit of an explanation that may be using the wrong file name in the following area of this wonderful tutorial:

In the section called: "Extracting Geo-Resolution Output to TSV", I believe the command is ok, but in the explanation of the command, the wrong filename is maybe referenced:

This the command:
"./bin/sys-i386-snow-leopard/lxprintf -e "ent[@type='location']" "%s\t%s\t%s\t%s\t%s\n" "normalize-space(parts/part)" "@gazref" "@in-country" "@lat" "@long" < ./out/172172.out.xml> ./out/172172.out.tsv"

But the explanation then says:
"In the example above, the XML input file (containing the location entities) is ./out/burtons.out.xml, and the TSV file is ./out/172172.out.tsv."

I think the file "burtons.out.xml" should probably be listed as "172172.out.xml".

If I am missing something and and I am wrong, I do apologize for the trouble.

**Comment by ianmilligan1** [comment]
Thanks @fortinma! Let me check with the author and look closer on Monday, we’ll be in touch soon. Appreciate the feedback on this.

**Comment by bea-alex** [comment]
Yes, you're right.  Thanks for spotting that.

**Comment by fortinma** [comment]
No worries. Thanks for the great tutorial!
