### ISSUE TITLE
Creating New Items in Zotero - code problem

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#66]
This lesson tells you to import an 'obo' library, but no such library exists (and it is not needed for the lesson).

import obo
from libZotero import zotero
import urllib2
import datetime

---
It would also be incredibly helpful for users if they were given a list of all the things they could add to their item using the API. What are the names of all the metadata fields that they can use?

**Comment by wcaleb** [comment]
Probably the `obo` refers to the Old Bailey Online library that is used for ProgHist v.1?

**Comment by ianmilligan1** [comment]
Just looked into this too. `obo` is referring to the `obo.py` module, which is used extensively in the next lesson: http://programminghistorian.org/lessons/counting-frequencies-from-zotero-items (complete with download). To make the "Creating New Items in Zotero" lesson work as a standalone, my vote would be to remove that item from the code block.

**Comment by acrymble** [comment]
yeah we used the obo.py in the introductory python lessons and as this
Zotero series was created shortly after that, we hadn't yet quite detatched
ourselves and built towards standalones.

**Comment by wcaleb** [comment]
I removed the `obo` call and also added a paragraph on how to see the fields available for modification. We might want to check with author to make sure she's okay with the paragraph I included; I just stuck it there for now.
