### ISSUE TITLE
Navigation to next lesson is broken

### ISSUE THREAD

**Issue by gobsmacked** [programminghistorian/jekyll#671]
At the end of each lesson the links to advance seem to point to the previous lesson instead.
"Great! Now you're ready to move on to the next lesson ."
So this text at the end of lesson 2 points back to lesson 1 instead of pointing to lesson 3

All the chapters seem to be like this.
These are the lessons on Python that should begin at:
https://programminghistorian.org/lessons/introduction-and-installation
You will also see that this first lesson has no way to get to the second lesson.

**Comment by ianmilligan1** [comment]
Thanks @gobsmacked, thanks for letting us know.

**Comment by ianmilligan1** [comment]
... and should be fixed now, thanks again @gobsmacked and do let us know if you run into any other issues or things that might seem askew.
