### ISSUE TITLE
Markdown Display bug - pip lesson

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#676]
The URLs at the very end of the Pip lesson (https://programminghistorian.org/lessons/installing-python-modules-pip) are displaying as markdown rather than HTML

![screen shot 2018-01-15 at 13 45 21](https://user-images.githubusercontent.com/646647/34945202-63b7a46c-f9fa-11e7-8771-f8993b97fd66.png)

**Comment by mdlincoln** [comment]
Closed with #677
