### ISSUE TITLE
Question about the LaTex style file example

### ISSUE THREAD

**Issue by dylan-k** [programminghistorian/jekyll#68]
I have a question about one of the examples on the page [Sustainable Authorship in Plain Text using Pandoc and Markdown](http://programminghistorian.org/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown).

It was easy to follow along with this article thanks to the clear examples and explanations, and I'd like to say thanks for that! But there's one thing that confused me.

> With time, you will be able to fine tune the formatting of PDF documents by specifying a LaTeX style file (saved to the same directory), and running something like:

> ``$ pandoc -H format.sty -o project.pdf --number-sections --toc project.tex``

This looks like it might be exactly what I'm trying to do, actually, but up until this example the work had been done with markdown files. In this example, it looks like the PDF is created from a TEX file. From where I'm starting, I have a markdown file and a LaTeX style file that I would like to use.

Is it possible to create a PDF, starting from a markdown file?

**Comment by wcaleb** [comment]
Assuming you have a LaTeX engine (`pdflatex`, `xelatex`, etc.) on your system, it is possible to use Pandoc to go straight form Markdown to PDF. Behind the scenes, Pandoc will first convert the Markdown to a LaTeX file using its default LaTeX template, and will then invoke a LaTeX engine (`pdflatex` by default) to produce a PDF. 

You don't have to mess with LaTeX at all *unless* you want to fine tune the styling of the output PDF (which at some point you probably will). In that case you'll have to learn enough LaTeX either to modify the default template that Pandoc uses, or to write some LaTeX commands to be included in the header of the behind-the-scenes LaTeX file as in the example you quote.

Hope that helps!

**Comment by dylan-k** [comment]
Where is the default template that Pandoc uses?
