### ISSUE TITLE
Making Technical Contributions to main site

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#680]
Having just tried @ianmilligan1 's new instructions on making a pull request (https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions), I think I was able to do it. I also think it would be FAR more useful to have this on the main website under "Contribute" rather than on the project Wiki. I almost couldn't find it.

This would of course mean translation...

**Comment by ianmilligan1** [comment]
Woohoo! Let’s chat on call. I’m happy to port the English version over.

**Comment by acrymble** [comment]
I think we discussed this at a meeting and suggested leaving it on the Wiki for now. Can reopen later if we forget where it is.
