### ISSUE TITLE
Copy editing

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#681]
I'd like to discuss the possibility of getting copy editing for submissions. This is incredibly difficult work that is very time consuming for editors. I'm also quite sure that we aren't all consistent across lessons. I think we should have a conversation about whether or not we could find a way to pay for this final flourish of quality before publication. It may not be feasible, but it would make my life easier, and I imagine others too.

**Comment by ianmilligan1** [comment]
Let's chat about it, for sure. My own sense as somebody who's hired copy editors in the past is that they're quite expensive (as it's such a skill).

**Comment by drjwbaker** [comment]
Second @ianmilligan1: good copy editors are expensive. But I'd love to find a way here.

**Comment by mdlincoln** [comment]
Do we think there's an action item for this ticket at the moment? I know it's something to bear in mind in the future but until the bigger funding question is sorted out, perhaps we can close this out?

**Comment by drjwbaker** [comment]
Note that ticket on 'the bigger funding question' is #724.
