### ISSUE TITLE
Bio: José Antonio

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#683]
Welcome to the _Programming Historian_ team, @jamotilla! It's great to have you on board.

We want to add you to our public Editorial Team page, so we need you to add your information to our ph_authors.yml file. Take a look at the format for adding your information here:

https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml#L491-L507

You can add your data at the bottom of this file, making sure it matches the format that you can see in that example biography for editorial team members. 

Note: In addition to my biography text, I also have fields for my twitter, github, and personal website (url) - but these are optional, and you only need to include ones that you want to share on the public website. 

If you're not familiar with editing files on GitHub yet, take a look at the guide in our wiki: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions Let me know if you have any questions 😄

**Comment by jamotilla** [comment]
Thanks @mdlincoln! It´s done :)
