### ISSUE TITLE
Bio: Jennifer Isasi

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#684]
Welcome to the Programming Historian team, @jenniferisasi! It's great to have you on board.

We want to add you to our public Editorial Team page, so we need you to add your information to our ph_authors.yml file. Take a look at the format for adding your information here:

https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml#L491-L507

You can add your data at the bottom of this file, making sure it matches the format that you can see in that example biography for editorial team members.

Note: In addition to my biography text, I also have fields for my twitter, github, and personal website (url) - but these are optional, and you only need to include ones that you want to share on the public website.

If you're not familiar with editing files on GitHub yet, take a look at the guide in our wiki: https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions Let me know if you have any questions 😄

**Comment by acrymble** [comment]
just a note for when Jennifer adds her avatar, the project-team.md page needs to have new members added manually to the Project Team Membership History section.

**Comment by arojascastro** [comment]
True @acrymble at the moment in the spanish version we can only find English speaking collaborators... we should add the reviewers and translators of the Spanish edition. However, should we keep them separated? I mean, do you want them to add them to the English edition? Should we remove the English collaborators in the Spanish version of PH? What do you all think?

**Comment by arojascastro** [comment]
To clarify my point I meant the people metioned as "community participants"
