### ISSUE TITLE
Call for Lesson in Spanish

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#685]
At the January editorial call - #678 -  it was suggested that we put out a call for a lesson this year to be written in Spanish first, then translated to English. Such a thing would continue the goals of fostering our Spanish community, and it would also teach the rest of the board a lot about internationalization and translation. Assigning @arojascastro to lead discussion here on this with the rest of the Spanish group to make sure that this is something you all have the bandwidth to take on. 

Related to #579 and #636.

**Comment by acrymble** [comment]
This would perhaps be worth talking to people about in Mexico City when everyone is together, as a way of finding out what types of lessons the Spanish-speaking DH community thinks it needs that aren't available.

**Comment by arojascastro** [comment]
@jenniferisasi and @jamotilla will draft a call and will publish it here so we can all review it.

**Comment by arojascastro** [comment]
How is this going @jenniferisasi and @jamotilla ? Any progress? Do you need help?

**Comment by jamotilla** [comment]
Hi @arojascastro, @jenniferisasi already sent me a draft, and i´m working on it. I think i´ll have it today. Thanks

**Comment by arojascastro** [comment]
Great, just keep us updated...

**Comment by jenniferisasi** [comment]
Here is our draft for the CFP. We have included text from the website and are not sure if it is needed as part of the CFP or if you think it would be better to have a link to the guide(s)? 

Call for Papers para lecciones originales en español

Programming Historian 

The Programming Historian en español ha establecido una comunidad diversa en la que publicamos tutoriales revisados por pares dirigidos a humanistas que quieran aprender a utilizar herramientas digitales para sus propósitos de investigación y/o enseñanza. Hasta hoy, el equipo en español se ha centrado en la traducción de lecciones escritas en inglés, adaptándolas en la medida de lo posible a su uso en español. 

El creciente trabajo en el mundo hispanohablante en el campo de las humanidades digitales, el uso que nuestras comunidades han hecho de este tipo de recursos, y la pluralidad de especialistas en diversos campos de las ciencias sociales y humanidades que han adoptado y desarrollado recursos computacionales para sus investigaciones, nos han motivado a abrir un convocatoria para la recepción de propuestas de tutoriales de contenidos originales en español, los cuales, una vez aprobados y publicados, pueden ser traducidos al inglés para su amplia difusión en el mundo no hispanohablante.

Uno de nuestros nuevos propósitos es publicar material original en español. Es decir, nos gustaría comenzar a contribuir a la comunidad de PH con lecciones pensadas desde el ámbito de la investigación de todo lo referido a las humanidades en español. Si utilizas alguna herramienta o método digital para tu investigación, y crees que sería de utilidad para el resto de la comunidad, ésta convocatoria es para ti.

Así, The Programming Historian, por medio de su equipo de contenidos en español, convoca a presentar propuestas de lecciones o tutoriales en español, pensadas desde el ámbito de la investigación de todo lo referido a las humanidades en español. 

¿Qué tipo de lección queremos? The Programming Historian en español no tiene un modelo de lección estándar. Recibimos lecciones sobre cualquier tema siempre y cuando ayuden a los humanistas (usualmente historiadores, pero no siempre) en cualquier fase del proceso de investigación y publicación. Aceptamos lecciones dirigidas a todos los públicos, desde las que requieren habilidades y experiencia avanzadas, hasta las que tienen naturaleza introductoria para principiantes. Las lecciones pueden tener una extensión breve y tratar de manera directa una tarea concreta; o bien, pueden ser lecciones largas que requieren un mayor número de explicaciones en detalle. 

Para presentar una propuesta de lección, es necesario enviar un resumen o abtract de no más de 500 palabra, en el cual expongas tu propuesta y expliques el alcance o impacto que tu lección puede tener en el ámbito de las humanidades digitales. Es importante que previo a tu propuesta, revises las lecciones disponibles tanto en español como en inglés, para evitar la duplicidad de contenidos. 

Las propuestas y las lecciones serán revisadas de acuerdo a los lineamientos que The Programming Historian en Español utiliza para las traducciones:  

Revisión por pares
Todos los tutoriales serán revisados de manera rigurosa bajo la supervisión de uno de nuestros editores. Cuando recibimos una propuesta de lección nueva o de traducción, uno de nuestros editores se encarga de que el texto cumpla con los objetivos marcados y de que todos los conceptos sean claros para cualquier usuario y estén bien explicados. Todo este proceso se lleva a cabo antes de enviar el texto a nuestros revisores externos.

Nuestro proceso de revisión es un poco distinto al tradicional: no solicitamos una valoración sobre la calidad del texto, es decir, si merece ser publicado o no, sino que pedimos a nuestros revisores que participen de manera activa para mejorar el tutorial, de tal modo que todas las partes implicadas aprendan. Al hacernos cargo de un tutorial nuevo o bien de una traducción, seguimos un flujo de trabajo específico con el objetivo de que la lección se publique en un período de tiempo razonable. Puedes consultar nuestra guía para revisores si deseas más información.

Código abierto
En The Programming Historian en español estamos comprometidos con el uso de herramientas y lenguajes accesibles para todo el mundo. Todas nuestras lecciones utilizan lenguajes y programas gratuitos. Creemos que cualquier persona debería poder hacer uso de nuestros tutoriales con independencia de la financiación disponible para llevar a cabo su proyecto de investigación. Desde 2016, se ha depositado una versión citable del proyecto Programming Historian en [Zenodo] (https://zenodo.org/). El depósito de 2017 está disponible en doi.org/10.5281/zenodo.1046738.

Acceso abierto Gold
Todas las contribuciones a The Programming Historian en español son publicadas con una licencia Creative Commons BY. Esto cumple con un modelo de publicación de acceso abierto Gold, en conformidad con la Declaración de Berlín sobre Acceso Abierto al conocimiento en Ciencias Sociales y Humanidades, con los requisitos de financiamiento RCUK y de publicación académica HEFCE en el Reino Unido, así como con la Canadian Tri-Agency Open Access Policy. Acceso abierto Gold significa que la versión de los documentos está disponible de manera libre, sin tarifas de suscripción o restricciones de acceso. A los autores se les permite republicar sus tutoriales en cualquier sitio. Asimismo, cualquiera puede hacerlo siempre y cuando cite al autor original y respete sus derechos morales.

No aplicamos cargos por procesamiento de artículos (APCs), o suscripción bibliotecaria.
The Programming Historian en español está indexado en el Directorio de Revistas de Acceso Abierto DOAJ.

Política de diversidad
En The Programming Historian estamos comprometidos con la diversidad y defendemos la necesidad de mantener un espacio de trabajo sin ningún tipo de acoso u hostigamiento basado en el género, identidad, orientación sexual, capacidades, físico, peso, etnia, edad, religión o nivel de conocimiento técnico de los participantes y colaboradores. Asimismo, nuestro compromiso con la diversidad se extiende a la composición del Consejo Editorial garantizando que los miembros de un mismo género o nacionalidad no alcanzan una ratio superior al 50% +1 del total. Con esto pretendemos que el proyecto se siga beneficiando de puntos de vista distintos. La medida está sujeta a revisiones futuras, por lo que aceptamos el envío de sugerencias de los miembros de la comunidad.

Financiamiento y propiedad
The Programming Historian es una iniciativa dirigida por voluntarios, controlada en su totalidad por el Consejo Editorial de The Programming Historian con la ayuda de contribuyentes de la comunidad. No es una persona jurídica y, actualmente, no recibe financiación directa de ninguna organizacin o entidad.

El proyecto agradece el apoyo anterior recibido de la Network in Canadian History & Environment (NiCHE), y por el apoyo en el alojamiento del Roy Rosenzweig Centre for New Media (RRCHNM).

**Comment by arojascastro** [comment]
¡Muchas gracias @jenniferisasi y @jamotilla! Me parece excelentemente explicado. 

Creo que podría ser un poco más breve, es decir, no hace falta poner lo que sigue a partir de "Las propuestas y las lecciones serán revisadas de acuerdo a los lineamientos que The Programming Historian en Español utiliza para las traducciones" sino enlazar a las guías y políticas.

Creo que también se podría mencionar de manera explícita lo siguiente:
- que no hay plazo para enviar propuestas (¿lo hay?, no lo hemos debatido...) sino que la recepción de originales permanece abierta durante todo el año (o algo así, en otras palabras). 
- que hay que enviar la propuesta a una persona en concreto (hasta ahora era yo, pero lo podemos revisar). Lo mismo para las dudas y aclaraciones. 

Quizás también hace falta aclarar que el formato de la lección es Markdown (para que no escriban en Word), aunque el resumen puede ser Word (¿no? ¿o lo pedimos todo en Markdown?) y que la revisión por pares se hace en abierto en Github. Esto último es importante porque necesitamos el nombre de usuario de Github lo antes posible y si no tienen usuario aún retrasa todo el proceso un poco. Todo esto está en las guías pero aunque las enlacemos nadie se las lee enteras.

En fin, no sé, a ver qué opinan @mariajoafana y @vgayolrs. En general, como digo, me parece muy claro y muy bien explicado.

**Comment by jenniferisasi** [comment]
¡Gracias @arojascastro! Es fácil acortarlo y añadir los links. Tomo nota de los cambios/añadidos que propones mientras espero la respuesta de los otros compañeros sobre Markdown y la persona a quien se deben enviar las propuestas.

**Comment by mariajoafana** [comment]
My paper on PH en español was accepted for DH2018 in Mexico and my talk would be a good moment to make the call and assess with the audience the types of tutorials that people want to find in PH en español and what kinds of tutorials people in the Spanish-speaking world can and want to write. Or maybe is worth it to plan an informal meeting during the conference to talk about the call and encourage those interested to send their abstracts.

Jennifer, me parece excelente. De acuerdo con Antonio puede ser más corto el texto. Creo que el llamado no debe tener plazo. Tal vez valga le pena pedir a quienes envíen el abstract que lo hagan en Markdown junto con su nombre de usuario de GitHub.

**Comment by acrymble** [comment]
Congratulations, I'm really pleased to hear your talk was accepted!

**Comment by arojascastro** [comment]
Congrats!  It would be great to use that platform to get some feedback from Hispanic users. However, I thought that the call would be published as soon as we have a final version... why should we wait until June?

**Comment by jenniferisasi** [comment]
Aquí va el CFP revisado. He quitado lo que dijimos y algo más, pues releyendo me parecía repetitivo para un llamado a recepción de lecciones. @arojascastro he puesto tu contacto para la recepción de abstracts por estar tu nombre en la web. Creo que aquí deberíamos aceptar Word u otros formatos más comunes porque no se suben a Github, ¿no? Creo que pedir Markdown de primeras podría echar para atrás algunas propuestas. 

Como @arojascastro creo que si tenemos la propuesta lista antes, no deberíamos esperar a DH2018 pero sí hacer mucha promoción durante el evento, claro. 

--
Call for Papers para lecciones originales en español

Programming Historian 

The Programming Historian en español ha establecido una comunidad diversa en la que publicamos tutoriales revisados por pares dirigidos a humanistas que quieran aprender a utilizar herramientas digitales para sus propósitos de investigación y/o enseñanza. Hasta hoy, el equipo en español se ha centrado en la traducción de lecciones escritas en inglés, adaptándolas en la medida de lo posible a su uso en español. 

El creciente trabajo en el mundo hispanohablante en el campo de las humanidades digitales, el uso que nuestras comunidades han hecho de este tipo de recursos, y la pluralidad de especialistas en diversos campos de las ciencias sociales y humanidades que han adoptado y desarrollado recursos computacionales para sus investigaciones, nos han motivado a abrir un convocatoria para la recepción de propuestas de tutoriales de contenidos originales en español, los cuales, una vez aprobados y publicados, pueden ser traducidos al inglés para su amplia difusión en el mundo no hispanohablante. Si utilizas alguna herramienta o método digital para tu investigación, y crees que sería de utilidad para el resto de la comunidad, esta convocatoria es para ti.

Así, The Programming Historian, por medio de su equipo de contenidos en español, convoca a presentar propuestas de lecciones o tutoriales en español, pensadas desde el ámbito de la investigación de todo lo referido a las humanidades en español. 

¿Qué tipo de lección queremos? The Programming Historian en español no tiene un modelo de lección estándar. Recibimos lecciones sobre cualquier tema siempre y cuando ayuden a los humanistas en cualquier fase del proceso de investigación y publicación, desde las que  tienen naturaleza introductoria para principiantes hasta las que requieren habilidades y experiencia avanzadas. 

Para presentar una propuesta de lección, es necesario enviar un resumen de no más de 500 palabras, en el cual expongas tu propuesta y expliques el alcance o impacto que tu lección puede tener en el ámbito de las humanidades digitales a [Antonio Rojas Castro](rojas.castro.antonio@gmail.com). Es importante que previo a tu propuesta, revises las lecciones disponibles tanto en español como en inglés, para evitar la duplicidad de contenidos. No existe plazo para el envío y recepción de propuestas.

Las lecciones enviadas deberán seguir los lineamientos que The Programming Historian utiliza para la recepción de [lecciones originales o traducciones](https://programminghistorian.org/es/guia-para-autores), incluyendo el uso del formato Markdown y una cuenta de usuario en Github. A su vez, la publicación de las lecciones seguirá nuestras [políticas de publicación](https://programminghistorian.org/es/acerca-de).

**Comment by drjwbaker** [comment]
Publish now, highlight call at DH? (I'll be there as well)

**Comment by jenniferisasi** [comment]
We are going to publish the CFP on a blog post, then distribute it on email lists and social media. I am going to work on the post these days.

**Comment by mariajoafana** [comment]
Perfect, let me know if you need any help with posting the CFP in the webpage. One the post is ready I'll sent the info to Spanish-speaking DH organizations. I'll ask each one of us to circulate it among colleagues and friends, and in social media.

**Comment by jenniferisasi** [comment]
I'm finalizing the Markdown file. Do I have to just upload it to the jekyll/_posts folder? @mariajoafana maybe you can help me with this? ¡Gracias!

**Comment by mdlincoln** [comment]
@jenniferisasi yes! Make sure that you put the date as a prefix in the filename, so that it looks like the other files already inside `_posts`

**Comment by jenniferisasi** [comment]
Thanks for your help @mdlincoln!

**Comment by acrymble** [comment]
This is live, so I'm closing.
