### ISSUE TITLE
Plans for 2018

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#686]
@drjwbaker suggested at the January call that we consider our plans for 2018 and spend some time on this during the February editorial call. Collect such topics and conversation starters for that call here, though it might be worth keeping the descriptions brief and/or opening an adjoining ticket to collect discussion for any particular topic of interest. 

Primary interest during the call seemed to be, in various ways, in the direction of community engagement: #579 and #685.

**Comment by acrymble** [comment]
I'll be more professionally tactical in a way that's very UK-centric and say I think we should focus on articulating the ways that the Project is having "Impact" in various stake-holder communities. That is - changing the way people think and act. We have a lot more Impact than we have evidence of it.

**Comment by drjwbaker** [comment]
Agree: community engagement, India, splash around the Spanish panel at DH (on which, any appetite to make ES stickers for DH? @arojascastro et al)

**Comment by arojascastro** [comment]
I like stickers :)

We should flag / pin (?) @mariajoafana and @vgayolrs because they will be in DH2018 Mexico.

**Comment by acrymble** [comment]
Is this an actionable ticket? In other words: what needs to happen to close it?

**Comment by acrymble** [comment]
reopen if needed. I think this is covered by other tickets now.

**Comment by drjwbaker** [comment]
To add, I think we have a clear 2018 set of plans so I agree to the ticket closure:

- community survey
- India blog and follow up
- internationalastion
- big ES outward push / splash :)
