### ISSUE TITLE
India Community Outreach

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#687]
India continues to be a particularly strong part of our user community. There was interest during the January call in exploring our connections to this community more fully to determine their interests, needs, and uses of the Programming Historian. Assigned people here had a number of ideas that included:

* Exploring our own contacts at ADHO
* Reaching out to folks on twitter (though I'd do this in a last resort, if the others don't pan out).
* Potential Programming Historian meetup at DH focused on this community or others

**Comment by acrymble** [comment]
We can start by highlighting what we already know in a blog post, which can act as a line in the sand from which we can move forward. I'll see if I can find some time to mock something up.

**Comment by drjwbaker** [comment]
@acrymble Ping me if you want support/input/coauthor on that.

**Comment by acrymble** [comment]
@drjwbaker I'd love some help with that so we're singing from the same hymn sheet moving forward.

Here's some data that I'll plunk here for the minute:

Country | Visitor Increase | Percentage Increase
-- | -- | --
Peru | 2,426 | 1,193
Ecuador | 1,821 | 1,090
Colombia | 5,682 | 1,073
Chile | 4,373 | 946
Mexico | 9,868 | 714
Argentina | 3,699 | 551
Spain | 11,468 | 402
TOTAL | 39,337 | 508
Top Five by Traffic |  
United States | 100,853 | 219
India | 43,906 | 276
Great Britain | 24,688 | 252
Canada | 11,575 | 215
Germany | 11,645 | 225

Top Ten Cities | Traffic Volume 2017 |  
Bengaluru, India | 18,222 |  
London, UK | 13,113 |  
New York, USA | 12,102 |  
Chennai, India | 7,387 |  
Hyderabad, India | 5,997 |  
Toronto, Canada | 4,796 |  
Sydney, Australia | 4,447 |  
Pune, India | 4,297 |  
Chicago, USA | 4,006 |

**Comment by drjwbaker** [comment]
@acrymble Okay. Well if you are happy to throw together a sketchy v1, I can take v2.

**Comment by acrymble** [comment]
The Images from Tashrih al-aqvam on the BL flickr would be great for an accompanying image (I think): https://www.flickr.com/photos/britishlibrary/12459181963/in/album-72157640831988343/

**Comment by acrymble** [comment]
---
title: The Programming Historian and India
layout: post
categories: posts 
---

When the _Programming Historian_ launched its open access tutorials in 2012, historians were the target audience. By 2014 our audience statistics had already presented a surprise: India had emerged as the second largest source of _Programming Historian_ readers - a title it still holds in 2018.

Country | Visitors 2017 | Per cent Increase from 2016 |  
-- | -- | --
United States | 100,853 | 219 |
India | 43,906 | 276 |
Great Britain | 24,688 | 252 |
Canada | 11,575 | 215 |
Germany | 11,645 | 225 |

While India is home to many talented historians, we suspect the project may have attracted a very welcome but unintended audience. The traffic is concentrated in four cities, topped by Bengaluru, India's equivalent of Silicon Valley. In fact, four of the top ten cities in the world for _Programming Historian_ traffic, are all in India:

Top Ten Cities | Traffic Volume 2017
-- | -- 
Bengaluru, India | 18,222
London, UK | 13,113
New York, USA | 12,102  
Chennai, India | 7,387 
Hyderabad, India | 5,997
Toronto, Canada | 4,796  
Sydney, Australia | 4,447
Pune, India | 4,297
Chicago, USA | 4,006

(Maybe a map?)

Interest seems to be focused on the tutorials that provide Python programming skills (/counting-frequencies, /working-with-text-files, and creating-and-viewing-html-files top the list, with a lot of interest also in /intro-to-augmented-reality-with-unity and /building-static-sites-with-jekyll-github-pages).

This interest has both excited our project team, but also wanting to know more about how people in India are using the project, and how we can better serve the needs of this group....

**Comment by acrymble** [comment]
@drjwbaker anything you'd add to the above?

**Comment by drjwbaker** [comment]
@acrymble Sorry. Fell down the list. Some potential words.

> Interest seems to be focused on the tutorials that provide Python programming skills (/counting-frequencies, /working-with-text-files, and creating-and-viewing-html-files top the list, with a lot of interest also in /intro-to-augmented-reality-with-unity and /building-static-sites-with-jekyll-github-pages). This suggests two things: first, that a cohort of individuals in or around the Indian "tech industry" are using our lessons to develop their programming skills; and second, that open access Python tutorials fill a gap in the market.

> Of course, these figures are modest: 18,222 readers per month from Bengaluru doesn't make the *Programming Historian* the hottest ticket in town. But the continued way the longitudinal data suggests a sustained use of our lessons by this demographic has both excited our project team and energised us to go beyond the stats, to know more about *why* and *how* people in India are using the project, and how we can better serve the needs of this group.

> With that in mind, we'd love to hear from our readers in India about why and how they use the *Programming Historian*, from academics in India or scholars working on contemporary India (anthropologists, researchers in development studies) with ideas about what might be happening, and from comparable projects - such as our friends at [*Software Carpentry*](https://software-carpentry.org/) - with comparable stories to tell.

**Comment by acrymble** [comment]
I came across an article today that outlines Indian Universities that teach DH: https://www.hindustantimes.com/education/new-bytes-digital-humanities-courses-are-becoming-a-hit-among-students/story-0h0IjdLYhDcskSk7scNHpK.html

It's in the Hindustan times, and outlines the following programmes:

Bengaluru's Srishti Institute of Art, Design and Technology (MDes programme)
Jadavpur University, Kolkata (PG diploma)
Pune University (certificate course)
Koti Women's College, Hyderabad (BA in computer applications-digital humanities).

As well as the following instructors:

Padmini Ray Murray (Srishti)
Amlan Dasgupta (Jadavpur University)

These would be good leads if we wanted to re-open an Indian outreach initiative.

**Comment by drjwbaker** [comment]
Good spot Adam. I contacted Padmini in the past re PH and India but I didn't receive a reply. Amlan I don't know.
