### ISSUE TITLE
Missing image for @jamotilla 

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/jekyll#689]
#688 was just merged and while it has the bio statement, it's linking to an image that doesn't exist. 

@jamotilla could you upload a headshot or avatar? 

On the build it is looking for:

```
  *  internal image /avatars/Jose-Antonio-Motilla.png does not exist (line 1203)
```

But if you prefer you can also just upload it to this issue (dragging and dropping) or e-mail it to me (ianmilligan1@gmail.com) and I am happy to put it into the system too. 😄

**Comment by jamotilla** [comment]
Thanks @ianmilligan1 
![jamotilla](https://user-images.githubusercontent.com/26726739/35283455-f3d2aeb0-001d-11e8-8de8-50ba01bb4183.jpg)

**Comment by ianmilligan1** [comment]
Thanks! I will add when I have a chance shortly

**Comment by acrymble** [comment]
[image: Inline image 1]
