### ISSUE TITLE
gem install jekyll does not work with Ruby 2.5.0, problem for the static webpages with Jekyll and GitHub page

### ISSUE THREAD

**Issue by smoothstatistics** [programminghistorian/jekyll#691]
The problem occurs in "Building a static website with Jekyll and GitHub Pages", when using a Windows computer. Running 'choco install ruby' automatically installs Ruby 2.5.0, which has an issue with ffi, which then leads to not being able to install Jekyll. See here, for example: https://github.com/ffi/ffi/issues/598
I solved it by running 'gem install ffi -f' as suggested in that link, but anticipate issues down the line.
It might be better to have users install version 2.4 of Ruby instead, if possible. Thanks!

**Comment by smoothstatistics** [comment]
I have proceeded further in the tutorial and indeed it does not work - 'jekyll new JekyllDemo' leads to "Bundler: ffi-1.9.18-x64-mingw32 requires ruby version < 2.5, >= 2.0, which is
  Bundler: incompatible with the current version, ruby 2.5.0p0"
and proceeding with 'bundle exec jekyll serve --watch' then errors out because gem minima is not found.

**Comment by amandavisconti** [comment]
Thanks for reporting this, @smoothstatistics! I'll see if I can troubleshoot this, this week.

**Comment by monsij** [comment]
*Hello there,I've successfully installed jekyll with Ruby 2.4.3.It's perfectly running*.Thanks @smoothstatistics 
@amandavisconti

**Comment by smoothstatistics** [comment]
Thanks Amanda!
Monsij, how did you install Ruby 2.4.3 and make sure that your computer looked there when looking for Ruby? I have installed Ruby 2.4 manually but my computer still looks for Ruby 2.5 and then errors.

**Comment by monsij** [comment]
Have you tried 'bundle install' too after the manual re-install of Ruby?

**Comment by amandavisconti** [comment]
@smoothstatistics I'm wondering if using `choco install ruby --version 2.4.3.1` instead of `choco install ruby` would help? I'll see if I can get access to a Window computer to test this. Thanks again for alerting me to this!

**Comment by mdlincoln** [comment]
I'm closing this as there's been no updates for a few months. Please reopen if needed.
