### ISSUE TITLE
"Last updated" header showing nonsensical number

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#697]
The latest update to the [Sentiment Analysis lesson](https://programminghistorian.org/lessons/sentiment-analysis) (#692) is causing our "last modified" header to show the nonsensical date `2018-00-25`

I need to look in to what part of the jekyll/js code may be causing this.

**Comment by mdlincoln** [comment]
I feel like there's probably a more robust way in javascript to format a date as `YYYY-MM-DD` than what Fred did here:

https://github.com/programminghistorian/jekyll/blob/gh-pages/_layouts/lesson.html#L172

Thoughts @amandavisconti @walshbr ?

**Comment by walshbr** [comment]
Looks like the function Fred is calling counts from 0, not 1. So every lesson was actually just off by one for the month counter. The PR I just pushed should correct this by adding one to the date. And you're right - the more robust way for working with this would be https://momentjs.com/, which @zoeleblanc suggested to me just now. I left it the way it is for now, but we can refactor later if we with.
