### ISSUE TITLE
Directory of Open Access Journals XSD

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#698]
Our content is part of the Directory of Open Access Journals (DOAJ), which makes it easier for libraries to add it to their catalogue. This was set up in Issue #180 a couple of years ago. Lesson metadata can either be added manually (very cumbersome), or semi-automatically by uploading a pre-formated XML document that meets their criteria.
![screen shot 2018-01-25 at 18 13 34](https://user-images.githubusercontent.com/646647/35404620-83f31bc2-01fb-11e8-886b-82d79c6732dd.png)

I can't upload the xsd to this ticket, but I can supply the template. Is this something we could automatically generate so that we could keep our content synced with the DOAJ? @mdlincoln

**Comment by mdlincoln** [comment]
please post a link where the org describes exactly the specification of the file, but also where it goes - a separate path on the site? header info in the lesson page itself?

**Comment by acrymble** [comment]
https://doaj.org/publishers Under "7) How to get your journal content / article metadata indexed in DOAJ. Uploading content."

**Comment by mdlincoln** [comment]
OK, this looks like it requires us to actively send updates to their API every time we have a new article - it's not a passive harvesting system. I will need to think about this a bit.

**Comment by acrymble** [comment]
There is an option for uploading the file periodically (Upload DOAJ XML to us via the 'Upload Article XML' tab. You can either upload the file manually by selecting it from a location on your computer OR you can enter the URL where the DOAJ site should go to look for the file.)

This would be a big step in the right direction, and I suspect easier than the API option. It would mean I could just upload the full file once a year to keep us up to date, rather than the current setup, which involves inputting each article's metadata, one field at a time.

**Comment by mdlincoln** [comment]
Maybe this is something that we could pin to the annual Zenodo archive activity @drjwbaker ?

**Comment by drjwbaker** [comment]
Just to check I understand what is going on, do we need to generate DOAJ XML for every article and manually upload it or can be bulk upload a DOAJ XML file with multiple new articles in it?

**Comment by acrymble** [comment]
It's my understanding (and hope) that it's the latter.

**Comment by drjwbaker** [comment]
If so, we can roll that into the Zenodo activity if you want. Maybe by keeping a fresh DOAJ XML up to date each time we publish a new article, then uploading it periodically (though I'm speculating as I know next to nothing about the process here).

**Comment by acrymble** [comment]
I think uploading it once a year is fine. What would really make the
process easy is if the XML was auto-generated from site metadata.

**Comment by mdlincoln** [comment]
I don't _think_ it'd be hard at all to create a jekyll template that keeps a current DOAJ XML file generated. If we want to go in that direction, I can try my hand at building it up.

**Comment by mdlincoln** [comment]
Alright, here's a try at formatting this: https://5a738f8cdf995304f18d3bca--ph-dev.netlify.com/doaj_xml/doaj.xml

It passes the DOAJ xml validation fine. One issue with their schema is that it doesn't offer fine-grained creator roles, so I'm only pulling in our lesson authors, and will not include editors, reviewers, translators, or translation editors. I don't think DOAJ gives much leeway on this, but I did want to note it.

**Comment by mdlincoln** [comment]
Also, once we do a PR for this, then all someone would need to do once per year is pass the URL https://programminghistorian.org/doaj_xml/doaj.xml and their upload service should retrieve it.

**Comment by drjwbaker** [comment]
@mdlincoln Thanks for making a start. I've not forgotten this. Will take a look tomorrow.

**Comment by mdlincoln** [comment]
Thanks @drjwbaker - i've push a few edits in the meantime, so make sure to consult the latest at https://github.com/programminghistorian/jekyll/tree/oaj_xml

**Comment by drjwbaker** [comment]
Okay. I'm being thick today. Link https://github.com/programminghistorian/jekyll/issues/698#issuecomment-362426665 doesn't work for me and I don't know what you mean by 'pass the URL [..] upload service should retrieve it'. I also don't know how and for what purpose https://github.com/programminghistorian/jekyll/tree/oaj_xml differs from https://github.com/programminghistorian/jekyll (the to pages look basically the same) or how you might have used it to make https://5a738f8cdf995304f18d3bca--ph-dev.netlify.com/doaj_xml/doaj.xml. Also, I'd need our username/password for https://doaj.org/publisher/uploadfile to upload the latest, which I don't have.

Once I get all that, happy to do the upload and roll an annual update into the annual archiving process ready for next year.

**Comment by mdlincoln** [comment]
hah, let's get James a big cup of coffee ☕️ 

1. The branch I added the xml template to is `oaj_xml` so https://github.com/programminghistorian/jekyll/tree/oaj_xml is the URL where you can view the branch.
2. The netlify url was a branch preview - but to make things a bit easier to follow, I just opened a PR. As usual, you can click on the "Details" link next to the Netlify process to pull up a live preview of the PR to look at the built version of the XML: https://deploy-preview-711--ph-dev.netlify.com/doaj_xml/doaj.xml
3. According to https://doaj.org/publishers#upload:
    >You can either upload the file manually by selecting it from a location on your computer OR you can enter the URL where the DOAJ site should go to look for the file.

**Comment by mdlincoln** [comment]
As for the login credentials, that's on @acrymble

**Comment by drjwbaker** [comment]
1. Get it. Branching to make small changes confuses me every time.
2. Don't know what you mean by 'As usual, you can click on the "Details" link next to the Netlify process to pull up a live preview'. I don't know what Netlify is so there is no 'as usual' for me. Not that it seems my comprehension here matters :)
3. Get it.

**Comment by drjwbaker** [comment]
Reopening until I get login credentials from @acrymble

**Comment by acrymble** [comment]
I have transferred ownership of the DOAJ account to @drjwbaker

**Comment by drjwbaker** [comment]
Got it. I'll work on this when I get a minute (hopefully the strikes break meaning sooner rather than later..) then setup something in the service integrations re doing this regularly.

- [x] Update journal articles at [DOAJ](https://doaj.org/publisher/)
- [x] Document workflow (including regularity of updates) at https://github.com/programminghistorian/jekyll/wiki/Service-Integrations

**Comment by drjwbaker** [comment]
Done for March (found it easier to do manually in the end). Shall repeat every six months. Reminder set.

**Comment by mdlincoln** [comment]
@drjwbaker ...did the xml not work?

**Comment by drjwbaker** [comment]
I'm sure it would. I just figured there weren't that many to add and I'd have to cut/paste the data into the xml template anyway, so I just did it manually. I took the 'non-geek' route https://maxhemingway.files.wordpress.com/2015/05/geeks-vs-nongeeks-repetitive-tasks.png to save time :)

**Comment by mdlincoln** [comment]
Did the Spanish lessons make in in there? Because I can't find them [in our listing](https://doaj.org/toc/2397-2068) but maybe I missed it somewhere.

**Comment by drjwbaker** [comment]
No. I have it on my list to discuss this at the next editorial meeting (that is, how we want to handle it).

**Comment by drjwbaker** [comment]
- [ ] Add to DOAJ all the ES lessons. Use translation date in lesson metadata for publication date.

**Comment by drjwbaker** [comment]
Okay. In relation to adding ES translations to DOAJ, I want to discuss briefly the following fields that [DOAJ](https://doaj.org/) use.

> Author(s)

DOAJ doesn't distinguish types of author so at present our DOAJ entries only include the author (so not the editor, for example). Do we want to include the author-translator in our `Traducido` field as an extra author for the ES publications? Eg, for [this](https://programminghistorian.org/es/lecciones/introduccion-a-bash) ES lesson, @vgayolrs would be listed as an author.

> Publication Date

As I *think* we agreed at #729, do we agree to use the `Traducido` date rather than the `Publicado` date as the 'Publication Date' for ES listings on DOAJ? Eg, for [this](https://programminghistorian.org/es/lecciones/introduccion-a-bash) ES lesson `2017-29-07` instead of `2014-09-20`.

> Journal ISSN

Okay. This one seems to empty a can of worms :) At present we use the same ISSN for the EN and ES versions of PH. It strikes me that if we have different volume numbers of EN and ES publications (as proposed at #767), this doesn't work with the ISSN framework (ISSNs are for individual publications, if we start *issuing* different volume numbers for our EN and ES lessons then we have two different publications both in spirit in and formal metadata). Looking at #147, it seems like the application for an ISSN was made by @acrymble  on the assumption that we run one publication. Since then ES has appeared and we are starting (I feel) to work on the assumption that we run two publications (if two publications that are *very* closely aligned). So do we need to apply for a second ISSN to make this and #767 work properly? I suspect this point might need a proper think through and a separate issue..

**Comment by amsichani** [comment]
I believe EN and ES should be treated as different publications: they have different metadata (title, date, author/translator, volume numbers) and that's the rule for creating distinct information objects. So different volume numbers for sure and different ISSNs as well. 

The ISSN service is free  but we need to find out what exactly we need to <a href="http://www.bl.uk/aboutus/legaldeposit/websites/faq/ukmaterial/index.html">deposit to the BL</a>, as PH is getting UK ISSN. Also we need to set up a workflow/registry for ISSN assignment and having also a back up of ISSNs for future lessons. I can see there the need to feel/show that there are two closely aligned publications but there are not identical ones - so  the <a href="http://www.issn.org/understanding-the-issn/assignment-rules/the-issn-l-for-publications-on-multiple-media/">ISSN-L</a> option for multiple media is not applicable to this case (Information Science can be a bit cruel some times). So, in my view, two different ISSNs is the way to go. We can then include the ISSN to the end of the suggested citation as proposed in #771: 

Dennis Tenen y Grant Wythoff, "Escritura sostenible en texto plano usando Pandoc y Markdown," traducido por Víctor Gayol, The Programming Historian en español, vol. 2 (2017), ISSN 1748-7188 https://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.

**Comment by acrymble** [comment]
I'm glad you raised this. I was thinking the same thing. I got our first ISSN #147. It is free as you say, and makes more sense if our volume numbers don't align. There are no deposit requirements that I'm aware of. If there are, we've been ignoring them.

**Comment by amsichani** [comment]
Fab @acrymble  - " Ongoing integrating resources” is our flag. 
As for legal deposit, I think our current publication status can easily skip the requirements of <a href="http://www.bl.uk/aboutus/legaldeposit/websites/faq/ukmaterial/index.html">"the Legal Deposit Libraries (Non-Print Works) Regulations 2013"</a>. Thoughts?

**Comment by drjwbaker** [comment]
Do we need quorum for this decision? It may be technical, but it has potentially profound ramifications long term: even if we stay two integrated publications for now and believe we will *forever* creating a technical infrastructure that lists us as publishing two (or, if we get a FR version, more) separate publications creates the conditions for divergence in the future (eg: separate editorial boards, laying of management structure, divergence of content)

**Comment by drjwbaker** [comment]
(I should add that I shan't be at #777 so if we discuss there someone else will have to take it on, explain the situation to the team)

**Comment by acrymble** [comment]
I'm going to move the matter of additional ISSNs to a new ticket, because it's tangential to this one.

**Comment by drjwbaker** [comment]
We have an ISSN https://github.com/programminghistorian/jekyll/issues/788#issuecomment-395426637

So, to confirm from https://github.com/programminghistorian/jekyll/issues/698#issuecomment-379298822 for the DOAJ listing of ES publication we will:

- List in the 'author' field both original authors and translators.
- Use the `Traducido` date rather than the `Publicado` date as the 'Publication Date'.
- List one issue per year
- List 2017 translations as Volume 1, 2018 translations as Volume 2, et cetera.

Happy? (especially @arojascastro et al)

**Comment by arojascastro** [comment]
Very happy and grateful!

**Comment by drjwbaker** [comment]
Closing this as specific tasks moved to new issue for ES publication https://github.com/programminghistorian/jekyll/issues/897
