### ISSUE TITLE
Política de retirada de lecciones

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#706]
I have translated this [policy](https://deploy-preview-612--ph-dev.netlify.com/lesson-retirement-policy). Please @jenniferisasi @mariajoafana @vgayolrs @jamotilla review and comment.

Some observations:
- In case we have not translated a retired lesson, we decide not to translate it... right? So I modified the original to make room for this possiblity. The modification is in the first paragraph. Just for the record, we have not translated any retired lesson so far.
- If the lesson was translated, should we store it in our own directory *retiradas* or not? What do you think @mdlincoln @acrymble? If so, we should create a directory in `jekyll/es`. 
- I still do not see where this file about the retirement policy goes, because the English version hasn't been merged yet. Maybe @mdlincoln can tell me. 
- For the record: we still have to translate the paragraphs about the topic in our author and editors guidelines. 

## Política de retirada de lecciones

Los editores de *The Programming Historian* hacemos todo lo posible para mantener el funcionamiento de las lecciones a medida que surgen problemas menores. Sin embargo, con el paso del tiempo, los cambios en las tecnologías subyacentes o los principios utilizados por una lección determinada pueden llegar a ser tan sustanciales que los usuarios ya no podrán completar la lección con éxito. Ante estas situaciones, el equipo editorial del *The Programming Historian en español* puede decidir no traducir una lección o bien, si ya ha sido traducida, "retirarla", es decir, mantener la página publicada, pero eliminándola de nuestro directorio de lecciones activas tras añadir una advertencia en la parte superior de la página señalando que no todos los elementos de la lección funcionan como se pretendía originalmente. Esta última medida también se llevaría a cabo con las lecciones originales en español.

No retiramos las lecciones a la ligera. Si el equipo editorial comienza a recibir mensajes sobre problemas con una lección, investigaremos el problema y tomaremos medidas para resolverlo. A menudo, no será necesario retirar la lección:

- **No** retiraremos la lección cuando las correcciones son fáciles de hacer (por ejemplo, corregir el formato de una lección o cambiar una o dos URLs rotas).
- **No** retiraremos la lección cuando han surgido nuevos métodos para una tarea preferibles a los métodos expuestos en una lección, pero la tecnología original para una lección todavía funciona y está disponible. La lección aún puede resultar una herramienta de aprendizaje útil y proporcionar una instantánea de las técnicas disponibles cuando se publicó.

Sin embargo, si está claro que los cambios en el texto, código y/o figuras son necesarios de manera sistemática y que tales cambios son de una escala que requeriría rehacer la lección por completo, entonces abriremos un debate público para discutir entre todos los miembros del equipo editorial la posibilidad de retirar la lección.

En los casos en que los miembros del equipo editorial, o miembros de la comunidad en general, estén dispuestos y sean capaces de ofrecer voluntariamente su experiencia, podemos crear una lección actualizada derivada del original. De acuerdo con nuestra licencia CC-BY, este derivado será atribuido de manera visible al creador de la lección original y a todos los colaboradores que contribuyeron en la producción de la nueva lección.

Con independencia de que se cree o no un nuevo derivado, si el tutorial ya ha sido publicado, llevaremos a cabo los siguientes pasos:

- La lección será trasladada de https://programminghistorian.org/es/lecciones/TITULO-LECCION a https://programminghistorian.org/lesson/retired/TITULO-LECCION. Se establecerá una redirección, por lo que cualquier enlace a la URL original indicará al usuario la nueva URL.

- Una vez retirada, la lección dejará de aparecer en el directorio de lecciones y se eliminará del flujo de anuncios de Twitter.

- El siguiente anuncio será añadido a la parte superior de la lección retirada:

>Los editores de *The Programming Historian* hacen todo lo posible para mantener las lecciones cuando aparecen problemas menores. Sin embargo, desde el momento de la publicación, los cambios en las tecnologías subyacentes o los principios utilizados en esta lección han sido sustanciales, hasta el punto de que los editores han decidido no actualizarla más. Es posible que la lección siga siendo una herramienta de aprendizaje útil y una instantánea de las técnicas de la historia digital cuando se publicó, pero no podemos garantizar que todos los elementos sigan funcionando como estaba previsto.

## Lecciones retiradas

OCR with Tesseract and ScanTailor

Counting Frequencies from Zotero Items

Creating New Items in Zotero

Intro to the Zotero API

**Comment by mdlincoln** [comment]
@arojascastro Because of technical issues, it would be best to store retired translated lessons into the same `/retired` folder as the English lessons - I hope this is acceptable? Editors would still add `redirect_from` to the retired lesson YAML so that e.g. `/es/lecciones/introduccion-e-instalacion` redirected to `lessons/retired/introduccion-e-instalacion`

The new file `/lesson-retirement-policy.md` is in the top-level path, so the new page you create should go in `/es`

A reminder about translating PRs: once the team is satisfied with the translation, **please do NOT open a separate PR**. Rather, you should add the commits to the `archiving-policy` branch. This will ensure that all the necessary changes stay in the same pull request and can be reviewed and tested together.

**Comment by arojascastro** [comment]
Oki doki, I'll modify the translation. Thanks @mdlincoln

**Comment by jenniferisasi** [comment]
I've read the translation and I don't see any issues with it @arojascastro

**Comment by jamotilla** [comment]
I´ve read the translation too, i think its very good

**Comment by mdlincoln** [comment]
@arojascastro it looks like everyone likes this - can you please add it as a PR? I'd like to get this finished for our next conference call so we can get it off the agenda.

**Comment by arojascastro** [comment]
Uploaded translation in committ  3a5f44d

**Comment by mdlincoln** [comment]
Closed by #612
