### ISSUE TITLE
Links broken (Exploring and Analyzing Network Data with Python)

### ISSUE THREAD

**Issue by rodrigovaldes** [programminghistorian/jekyll#718]
Hello,

I found that the links to the datasets (quakers_nodelist.csv, quakers_edgelist.csv) in the lesson Exploring and Analyzing Network Data with Python are broken. I hope those files are still available.

Btw, great project.

**Comment by mdlincoln** [comment]
I don't see any problem with either https://programminghistorian.org/assets/exploring-and-analyzing-network-data-with-python/quakers_nodelist.csv or https://programminghistorian.org/assets/exploring-and-analyzing-network-data-with-python/quakers_edgelist.csv

Please report back with more detail if you're still having problems.

**Comment by rodrigovaldes** [comment]
I am looking at this page,

http://programminghistorian.github.io/ph-submissions/lessons/published/exploring-and-analyzing-network-data-with-python#fnref:averagedegree

The links there are slightly different:

http://programminghistorian.github.io/assets/exploring-and-analyzing-network-data-with-python/quakers_nodelist.csv
http://programminghistorian.github.io/assets/exploring-and-analyzing-network-data-with-python/quakers_edgelist.csv

(instead of ".org", there is ".github.io")

The links above are nor working. I hope that helps

**Comment by mdlincoln** [comment]
http://programminghistorian.github.io/ph-submissions is the lesson submission and review site, so those lessons are old drafts and not the finished versions. The published site is https://programminghistorian.org, and the network analysis lesson you should use is https://programminghistorian.org/lessons/exploring-and-analyzing-network-data-with-python
