### ISSUE TITLE
Sponsorship of the Programming Historian

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#724]
The Programming Historian is a volunteer-driven project. In order for it to grow, improve, and be sustained, the Editorial Board of the Programming Historian are considering accepting sponsorship (judged on a case-by-case basis using a mechanism that has yet to be decided). This would enable us to:

- Pay for professional publishing services that would enhance the quality of our publication (e.g., copy editing)
- Improve our community outreach and internationalisation.
- Protect the Programming Historian from changes to service agreements of those ‘free’ services upon which we rely.

We should add that we remain committed to open source values and our content will not disappear behind a paywall. And so in that spirit of openness, we open this ticket and we invite our community of authors, reviewers, and readers to share their views and advice on this idea.

**Comment by antimony27** [comment]
Hey James (and PH in general),

 I understand the need for some funding down the road, but I also think a wide call for editors would be helpful (perhaps you've done this before, I'm not sure). I've been running PH meetups at the University of Guelph for about 6 months, and I would volunteer time to copy-edit some lessons. I wasn't sure about how to make suggestions, etc, but now I see that this can all be done in github. 

I also wonder if having 'edit-a-thons' like those that happen for Wikipedia, would be a good idea. I can see those doing two things: 1. making small copy-edit changes and 2. making updates to code/links in the lessons. I could propose a test event with my group at Guelph if you all think this is a good idea. It would also serve as a good intro to github.

Looking forward to following this convo.

**Comment by drjwbaker** [comment]
@antimony27 Some interesting suggestions (and enthusiasm!), but I'm not sure they quite fit our editorial workflow as it stands: a workflow that would be challenging and time-consuming to unpick.

With respect to how lessons get from ideas to articles, this is very much like a standard publication: the idea is submitted, it goes through peer review, a decision is made based on that whether or not to proceed, if we proceed it is published https://programminghistorian.org/editor-guidelines Where we differ is in the long term management of lessons to keep them current or - in some cases - to remove them from the live site https://programminghistorian.org/lesson-retirement-policy

We have identified that copy editing is big time sink for our editors and not a service we are comfortable asking people to do voluntarily as it undercuts a profession. Hence the idea to consider accepting sponsorship to cover paying for professional copy editing of new lessons. And whilst meetup edits could work, the issue with our present workflow is timing: copy editing for a publication should to take place before publication (and note, copy editing for English lessons would also need to be extended to other languages we support - currently only Spanish https://programminghistorian.org/es/, perhaps soon French https://github.com/programminghistorian/jekyll/issues/378 - before those translations are published) and we are at present keen - mindful that we want authors to get credit for their lessons - that in some respects we stick to what looks like a publication model.

On the idea of 'edit-a-thons' this also clashes with how we currently think of lessons as publications: although we do fix bugs and revise lessons that break, our lessons are authored by our authors and so - for me - having a team of people editing their work without them knowing doesn't feel quite right.

But you've got me thinking. Seen as this discussion is more about process, added value, and community engagement than sponsorship, it may be worth moving to a fresh issue because I can see some ideas in here that my fellow editors might want to pursue.

**Comment by antimony27** [comment]
Right - sorry if this didn't fit within what you are thinking or with the ideas of the PH team/workflow. Just thoughts, wasn't trying to undermine any of the important work done by the team or by copy-editors. Feel free to shift the convo elsewhere.

**Comment by drjwbaker** [comment]
@antimony27 I love the ideas. I've opened a specific issue to discuss further: https://github.com/programminghistorian/jekyll/issues/725

**Comment by peterwebster** [comment]
Hi @drjwbaker : I quite see the need, and I don't imagine many folk would have any principled objection as such. I guess much depends on the mechanism: what sort of size of sponsorship do you need/want? Lots of grateful former or current users, dropping in £20/year by Paypal, or two or three big organisations? What can you offer a sponsor (assuming that it isn't done purely for the warm feeling of fostering scholarship)?

**Comment by drjwbaker** [comment]
Thanks @peterwebster. These are useful questions. I'd imagined seeking funding from orgs rather than individuals, and that they would get back a masted brand recognition thing - 'powered by X' or similar. My fellow editors might have different ideas, but this is precisely why we opened this ticket.

**Comment by SMDreller** [comment]
Hi, @drjwbaker.

I am a copy editor, so I'd like to start by thanking you and your colleagues at the Programming Historian for insisting that professionals like me be paid appropriately for the editing services we provide.

I am also a historian and from my perspective there is nothing inherently wrong with a project like yours developing a thoughtful sponsorship program. Nothing at all. Everything costs something, and right now it sounds like you have an opportunity cost problem---i.e. volunteers spending more time on editing means they're spending less time on producing new lessons or whatever else engages their particular skills most effectively. If you really feel that you can demonstrably secure/improve your project's work by shifting some of the burden to paid professionals, everyone wins. And that includes your readers. Perhaps especially your readers.

You know this but I'm going to say it anyway: what would definitely bother me is if there appears to be some connection between the sponsor and the author and/or lesson. The obvious situation would be if the developer of a particular DH tool sponsors a lesson about their tool, but there are other similarly unpalatable permutations of this idea. I can imagine some ways to try to avoid this problem, but I doubt I could add anything new to the conversations you are already having internally about this.

I'd like to offer two examples from my own field, architectural history, of online resources with sponsorship programs that I respect tremendously and use routinely. One is Places Journal: https://placesjournal.org/  Theirs is more of a series of partnerships they've worked out with academic institutions, but I do like the elegantly unapologetic way the partnerships are presented. The other is Pioneering Women of American Architecture, which is a project of the Beverly Willis Architecture Foundation: https://pioneeringwomen.bwaf.org/ In this case, the site uses the word "sponsor" and unobtrusively indicates who the sponsor is for each of the architects' profiles. They accept sponsorship from individuals, not departments like Place Journal or organizations as you have proposed, but I think you could get some good ideas from this example nonetheless. Notably, the sponsor names on each of the profiles are not clickable, making them less like a paid-for ad and more like a meaningful sponsor/patron. And so on.

I'm going to finish here the way I started, which is as an editor. By now you've probably already reached out to a copy editor about how much her/his services might actually cost as a way to inform your ideas about the scope of your sponsorship needs. But if you haven't done this yet, you are welcome to contact me. I have some projects winding down soon, which means I could end up being available when the Programming Historian has the funds to hire a copy editor. I don't want to take a job away from a fellow editor, though, so please only be in touch if you haven't already organized with someone else.

I hope some of this helps.

**Comment by drjwbaker** [comment]
@SMDreller Super helpful. Thank you. On ..

> what would definitely bother me is if there appears to be some connection between the sponsor and the author and/or lesson

.. I concur. We have author https://programminghistorian.org/author-guidelines#write-sustainably and reviewer https://programminghistorian.org/reviewer-guidelines#sustainability guidelines on creating sustainable lessons which I would not like to see compromised by sponsorship, which probably rules our lesson sponsorship (which wasn't an option I'd considered). These guidelines are there to help us in cases - for example - where projects propose lessons based on tools they have created, so they could be usefully reapplied were we to have whole project sponsors (which was the model I had in my head).

On editing, thank you. I've worked with freelance copy editors in the past and have a sense of their rates. Were we to hire copy editors it would be after the peer review of each lesson (so last step before publication). I guess we'd need to think carefully around our mechanism for lining up copy editors and giving them reasonable lead time.

**Comment by mhbeals** [comment]
I would suggest we take a page from the response to the Ad-pocalypse on YouTube. There are three trends developing there that I think would work for PH.

1) Affiliate status of relevant retailers rather than sponsor-directed ads. For example, there are many YouTubers who work with Audible, Amazon and other platforms. They recommend books, and the like, based on their own professional perception of useful works (essentially a further reading section) and then link to them on these platforms and earn royalties from sales. It is very little work for the authors and I think keeps them independent from the "sponsor"

2) Patreon.  Why not go to the people who actually use the resource and ask for their totally voluntary support.  I give $5 a month/$1 a video to various programming channels because I think they are helpful and want to help them keep going. This is my preference because it is totally independent and can be supplemented with Paypal Donations / targeted referrals

3) Merchandise.  I know it seems silly, but dang if I wouldn't proudly drink from a PH mug or cuddle up to a PH pillow in my "office-hour" chair. These are essentially drop-sellers and easy to set up.

All this is to say that I'm not really a fan of 20th-century style advertising and think its time has largely passed.

**Comment by acrymble** [comment]
@mhbeals thanks for the suggestions. I've heard of Patreon, but never used it. That's a bit like the scholarly society model of paying $20 per year and they put out a journal (without looking like that's what it is).

**Comment by drjwbaker** [comment]
1. I know little about. 3. I understand from @acrymble raises very little £. On 2., I like the idea of Patreon - eg https://www.patreon.com/bePatron?c=1246580&rid=2088750 - and am curiously what experiences of others are with it. But @mhbeals I also think there is a 4. option we'd be wise to consider: direct monetary or in-kind support from organizations who want to associate themselves with us and we want to be associated with.

**Comment by arojascastro** [comment]
I like number 2 as well. Patreon or Paypall are good options -- Wikipedia accepts donations as well. Maybe we should find out about the legal conditions that we should meet in order to get money.

**Comment by acrymble** [comment]
We'll need to remember that this is meant to be a time saver, so any solution has to benefit that aim rather than take too much effort to administer and encourage.

**Comment by acrymble** [comment]
I've emailed my finance team to see what it would cost to host any money and administer its expenditure via my university (though open to it being elsewhere). I'll let you know when I hear back if this is possible.

**Comment by drjwbaker** [comment]
I've had the same discussions with folks at Sussex. I'll report back when I hear more.

**Comment by acrymble** [comment]
@drjwbaker I'm not getting far with this. I don't know if you've had more luck.

**Comment by drjwbaker** [comment]
@acrymble I'd like to keep it open. Slow progress. Perhaps worth a chat offline.

**Comment by acrymble** [comment]
I've tested out a Patron page. Looks easy enough. They take 5% as a fee, and 1% fee if you use paypal for the money handling. I think we should give it a go, but we'd need a specific use for the money that we could tell patrons about.

This would also have to go to a university or charity, otherwise there are income tax implications.

**Comment by drjwbaker** [comment]
> This would also have to go to a university or charity, otherwise there are income tax implications.

That is part of what I can working on. So thanks for taking a look at this. We could just float a Patreon on the site.

**Comment by acrymble** [comment]
I think we're now onto a new issue here. We're agreed that we're going to try to get an income to cover our costs. Our current issue is how are we going to do that in practice. Should we start a new issue about getting a budget line, and close this one?

**Comment by drjwbaker** [comment]
You do love closed issues @acrymble :)

**Comment by drjwbaker** [comment]
This https://mashable.com/2018/06/03/microsoft-github-acquistion exactly the kind of thing I meant re 'Protect the Programming Historian from changes to service agreements of those ‘free’ services upon which we rely.'

**Comment by walshbr** [comment]
We'll have to watch that closely I think

**Comment by mdlincoln** [comment]
Copying in what I sent over the listserv since it bears repeating here. tl;dr: don't foster FUD where none is needed

>1. There's absolutely _nothing_ to suggest that the services we rely on for PH are going to be impacted by this - if anything, it removes FUD because Microsoft actually is a financially viable company, whereas Github did not run a profit. It would be shocking if Microsoft began to close up features of GitHub that used to be open - and if they did, there would be systematic warning about it anyway.
>2. That said, it's is good to understand alternatives... I've already tested out what it'd be like to migrate our repository over to GitLab, and it's just about seamless, copying over our entire backlog of issues (save for some issues with a few pull request comments, though I believe those are being ironed out). GitLab offers the same kind of page publishing capabilities and integration with CI services so that we can do our 404 link checking etc. We'd need to re-point the domain name, but none of our links would break. James would need to figure out some other way to send snapshots of the site to Zenodo, but all the old ones would work fine. The biggest hurdle would be that team and community members would need to create accounts on GitLab and get used to using the GitLab interface. The underlying patterns of issues and merge requests are identical to GitHub, but of course buttons and menus look different on GitLabl. But that'd be the case with any more to any new platform.
>
>So, no reason at all to move now, and virtually no reason to move in the future. But the ability to move is there if we need it, and while it would require some rewiring, the site itself would not need to change one bit.
