### ISSUE TITLE
Using edit-a-thons and meet-up editing to added value and enhance community engagement

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#725]
Further to the suggestion by @antimony27 at https://github.com/programminghistorian/jekyll/issues/724#issuecomment-367411931 opening this thread to discuss adding value and generating community engagement through edit-a-thons (fix-a-thons?) and meet-up edits of PH materials, and how we might square this with our current editorial workflows.

**Comment by mdlincoln** [comment]
see also #182

**Comment by acrymble** [comment]
This also links to #498 and concerns expressed (mostly by me) about revising lessons and the ethics of 'authorship' being attributed to a derivative work. This is something that has to be handled very carefully if we pursue it.

**Comment by antimony27** [comment]
Hi @mdlincoln @acrymble @drjwbaker Thanks for the feedback. Am taking it all in and learning about your process and previous thoughts is very interesting. Thank you for being so open.

I wanted to quickly state that I was not thinking about editing the content of the lessons as one would a wikipedia article - I think my reference there just the idea more than the amount of editing that takes place in Wiki Editathons.

 I would never want to take away from the hard work done to create one of these lessons, and I agree with Adam that if I published a lesson I wouldn't want people to have free access to change it, particularly as they are currently published. I was thinking more about small edits, spelling and grammar errors, and simple things like numbering that would smooth the process of using these (fabulous) lessons. 

I like the idea of the annotations for suggestions, but again understand the issues in #182 

Will keep thinking.

**Comment by acrymble** [comment]
@antimony27 I really like the idea of getting people together to make contributions for the greater good. I wonder what the most productive such activity would be?

**Comment by acrymble** [comment]
If anyone would like to continue this discussion please reopen the ticket. Closing as we haven't had any activity for a few months.
