### ISSUE TITLE
Discussion on DH and Institutional Credit

### ISSUE THREAD

**Issue by JMParr** [programminghistorian/jekyll#730]
The Programming Historian relies on the generosity of authors and reviewers to produce our tutorials. Our contributors come from a range of institutions in different countries. We have decided to open a discussion to help the editorial team better understand how our contributors's institutions view DH work, and how our contributors receive credit for their work with us - whether it's for faculty tenure and promotion, annual review, or other mechanism.  We would also like to understand if there are obstacles to receiving credit. Our goal is to see if there are things we can do to better support our contributors.

**Comment by sdfb** [comment]
One thought, for those of us who submit publications as part of dossiers for review, might be to support nicely formatted downloadable PDFs.  The look and feel of more traditional journal articles could help make PH lessons more legible as scholarly contributions.

**Comment by walshbr** [comment]
Thanks @sdfb. I wonder if we might be able to address some of those concerns by being a little more deliberate with our styling for printing. Right now printing a PH lesson looks like you've printed a webpage, which is a mixed bag at best. But we can control the look and feel of a page for printing via CSS. We could make it a bit more legible and formatted as a scholarly contribution when printed, which could then be added to a review dossier by going to print and then saving the page as a PDF (would probably need instructions for how to do that). Not exactly what you're suggesting, but perhaps a step in that direction?

**Comment by drjwbaker** [comment]
I suspect .md to .pdf translators than can be tweaked to give a more scholarly look and feel exist. I know @acrymble did *a lot* of manual work for the PH Print Edition, but on an article by article basis this might work https://pandoc-scholar.github.io/ I'm going to https://www.software.ac.uk/cw18 so might be able to sneak work around this topic (though not PH specific) into the hackday agenda...

**Comment by acrymble** [comment]
Thanks @sdfb. Just by way of making links to older conversations around this idea, these threads are pertinent:

- #417 PDF version-of-record
- #410 Propose "Version of Record" + amendment of lessons
- #65 Write a script to produce ebook and pdf

**Comment by taylor-arnold** [comment]
This is an important issue for me. While tenure and promotion at my institution emphasizes research output, demonstrating excellence and innovation in teaching is also taken seriously. Peer-reviewed articles published in pedagogical or tutorial oriented journals is an established way of doing this (in fact, it is even explicitly written into my department's career profile). 

Personally, I do not feel that there is a need to produce PDF versions of the articles (I'm not against it; I just do not feel that is the primary concern). There are plenty of research journals now that are digital-first or digital-only (in DH alone I can think of: DHQ, Cultural Analytics, Digital Studies / Le champ numérique). Instead, I believe the issue with PH at the moment is that the current tutorials are missing several important signifiers that typically distinguish peer-reviewed content from blogs and other materials:

- Volume/Issue numbering
- Suggested citation information (this was previously included but seems to have been removed)
- DOIs (note: this is not a replacement of the prior two items)

I believe that all of these have been suggested in various threads, but I'm not sure where those discussions have fallen. Implementation of the first two in particular would lend a great amount of credibility to these tutorial as publications with seemingly minimal work or noise added to the process.

As an example, take the Journal of Open Source Software (JOSS). Here is [an example article](https://joss.theoj.org/papers/2f5fa0cbfc075383d7764d271889b6ea). Each article is its own issue and volumes are changed over, I believe, quarterly.

**Comment by drjwbaker** [comment]
Thanks @statsmaths! I certainly think we should have 2) and don't know why we dont (I think this is a long debate..). 3) - as I understand it - costs money we don't have at the moment. 1) could be retrofitted (one volume a year, one issue every six months), though I'm curious that it is important at all given that so many articles these days are published a year or more before they get assigned volume/issue data.

**Comment by acrymble** [comment]
Thanks @statsmath. You're right, we've had some earlier conversations about these ideas.

On DOIs & Volumes see #64 
On Suggested Citations see #82 #130 #404

They've fallen in the past due to differing ideas on the team about what type of publication we were.

@drjwbaker I think the advantage of volume numbers is purely as a signifier to the everyday working historian that this falls into a category of work that they've seen before and understand. One volume a year retrofitted would be easy enough to implement. We might need to add an issue-by-issue listing in addition to the current 'lessons' page. But that wouldn't be difficult.

**Comment by nolauren** [comment]
Thanks for adding these issues to the next Editorial Meeting Agenda. I just want to echo the importance of demonstrating that these are peer reviewed "articles".  Adding a number and volume issue would not only help make this more legible to our institutions but also help users know new lessons are available. Organizing some of these issues around a particular topic/ method might also help build out certain areas that are sparse or needed.

**Comment by JMParr** [comment]
Thank you, Lauren!

**Comment by acrymble** [comment]
We are moving forward with volume numbers as per #767 to address this issue, as well as suggested citations that conform to scholarly practices in journals. We welcome further suggestions, but I will close this issue for now. Reopen if someone wants to continue the discussion.
