### ISSUE TITLE
Rattle snake image for "Python"

### ISSUE THREAD

**Issue by maximromanov** [programminghistorian/jekyll#732]
- https://programminghistorian.org/lessons/introduction-and-installation

The image of a rattle snake* for "python" is a bit weird. All the lessons are really great, so this thing looks a bit silly... 

* https://programminghistorian.org/gallery/introduction-and-installation.png

**Comment by acrymble** [comment]
You're absolutely right that it's not a Python. None of our icons are really exact representations of the lesson topic. We do try to come up with an image that loosely fits some of the themes of a lesson, but we're drawing from what's available online in open collections, so sometimes we have to get creative.
