### ISSUE TITLE
new translation: google maps?

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#735]
Hi @mariajoafana I noticed you created [a new branch with a translation of the Google Maps lesson](https://github.com/programminghistorian/jekyll/tree/mariajoafana-patch-1) a few days but you never submitted a pull request for it. 

Is this ready to be reviewed and merged onto the site, or are you still working on it?

re: https://github.com/programminghistorian/ph-submissions/issues/130

**Comment by mariajoafana** [comment]
Hi @mdlincoln , yes, I just created the pull request. The lesson is ready now, I've having some problems uploading the images, my GitHub desktop is acting funny. I'll try again tomorrow in my office's computer

**Comment by acrymble** [comment]
This was approved and is live, no?
