### ISSUE TITLE
missing data files in qgis tutorial

### ISSUE THREAD

**Issue by matthewljones** [programminghistorian/jekyll#74]
In
http://programminghistorian.org/lessons/qgis-layers
the links to the two non-PEI gov't data files 404 on dropbox.

https://www.dropbox.com/s/mgrb90vcpggnw8c/PEI_highway.zip
https://www.dropbox.com/s/fev9116zfr31ogb/PEI_placenames.zip

tarballs same thing.

**Comment by acrymble** [comment]
Thanks Matthew, I've forwarded that on to the author for comment.

**Comment by acrymble** [comment]
I've passed the missing file on to @wcaleb who will host it on our github account instead.

**Comment by wcaleb** [comment]
@acrymble I noticed while fixing this that the TAR files hosted on Dropbox are also missing. For now, I just removed the links to the alternate TAR files, but if you want to get those from the authors and put them in assets too, we can.
