### ISSUE TITLE
Normalize communication instance EN / ES

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#748]
I just noticed that in the English Team page, there are two contacts for the Spanish team: https://programminghistorian.org/project-team

![captura de pantalla 2018-03-20 a las 10 33 32](https://user-images.githubusercontent.com/7340111/37646714-a8ee5bfe-2c2a-11e8-8003-ab4323a27744.png)

Whereas in the Spanish Team page, there is only one - myself: https://programminghistorian.org/es/equipo-de-proyecto

Is this intentional or an error?

**Comment by acrymble** [comment]
Ya that's a mistake. You can change it.

**Comment by ianmilligan1** [comment]
Closed with #749
