### ISSUE TITLE
Published lessons in English that may not be translated into Spanish

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#756]
Yesterday, I intended to update our list of [pending translations](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md).

As you may know, we decided not to translate lessons that the English team has already archived because of sustainability problems. In addition, we decided not to translate those lessons that are very language independent - such as the lesson "Geoparsing text with Edinburgh". The list of *not amenable to translation* lessons is [here](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md).

I am wondering if there are anymore lessons that we should not translate. I checked out most of them, but I cannot read them in detail. My first impression is that the lesson on [Sentiment analysis...](https://programminghistorian.org/lessons/sentiment-analysis) should not be translated because it relies on [NLT](https://programminghistorian.org/lessons/sentiment-analysis#using-python-with-the-natural-language-toolkit-nltk), which is very language dependent. 

I have doubts also with [Fetching and Parsing Data from the Web with OpenRefine](https://programminghistorian.org/lessons/fetch-and-parse-data-with-openrefine) because there is a [section](https://programminghistorian.org/lessons/fetch-and-parse-data-with-openrefine#post-request) that relies on NLT as well. 

Maybe the editors of both lessons @acrymble and @jerielizabeth can give us their opinion? 

I suggest that the Spanish editors look at the English version of PH again, browse lessons and help me to update the list of pending translations and the list of lessons that are not going to be translated because they are not working in Spanish. 

Is that ok? @vgayolrs @jenniferisasi @mariajoafana @jamotilla

**Comment by acrymble** [comment]
The lesson on sentiment analysis would need to be written using a Spanish language sentiment analysis tool, since this is obviously based on English words. It's appropriate to leave this out of the translation.

**Comment by arojascastro** [comment]
Thanks for your confirmation @acrymble !

**Comment by ianmilligan1** [comment]
Any chance we could use different phrasing than “rejected”? Maybe something like “not amenable to translation”?

**Comment by arojascastro** [comment]
Sure, changed and sorry!

**Comment by mariajoafana** [comment]
I'll take a look at the lessons and see if there are other lessons not amenable to translation.

**Comment by jerielizabeth** [comment]
Greetings, @arojascastro! I agree that the Sentiment Analysis section of the Open Refine lesson relies on external, and English-language, APIs, making it hard to translate it. 

I could talk to the author about another version of that section that relies on geocoding, say, which is less language specific and still shows how to make api calls with OpenRefine. Just a thought, if it's a lesson that you are interested in including.

**Comment by arojascastro** [comment]
I think it is fine not to translate it @jerielizabeth - it is a very tecnical lesson that should be adapted in depth and that requires a Spanish speaker expert able to make those changes. So I would just leave it as it is unless someone else disagrees.

**Comment by arojascastro** [comment]
I think we can close this for the moment and reopen later.
