### ISSUE TITLE
Files not in assets directory

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#758]
I am currently translating this tutorial on [XML and XSL](https://programminghistorian.org/lessons/transforming-xml-with-xsl). The necessary files to complete the tutorial are stored in the author's github repository. I was wondering if we should store them in ours instead. See this section: https://programminghistorian.org/lessons/transforming-xml-with-xsl#choosing-and-preparing-xml-data

On the other hand, I have a language doubt: the author writes *aggrevation* in the introduction:

> In all three of these situations, a basic understanding of XML, and its sister-language XSL, could have saved you time and aggrevation. This tutorial will provide you with the ability to convert or transform historical data from an XML database (whether a single file or several linked documents) into a variety of different presentations—condensed tables, exhaustive lists or paragraphed narratives—and file formats. Whether filtering a large database or adding formatting such as headings and pagination, XSL offers historians the ability to reshape databases to support their changing research or publication needs.

Is it correct? Or it should be *aggravation*? I looked for that word in the dictionary and found nothing.

**Comment by ianmilligan1** [comment]
It should probably be "aggravation." I'll submit a PR to fix that typo.

**Comment by ianmilligan1** [comment]
@acrymble edited this lesson - what do you think Adam?

**Comment by acrymble** [comment]
yes that's clearly a typo. Sorry.

As for storing the data on our servers, this would be a good idea for sustainability reasons. @mhbeals is that ok, since you created these files?

**Comment by arojascastro** [comment]
I have one more question. I do not understand what "the module tutor" means, I do not know how to translate that.

[Context](https://programminghistorian.org/lessons/transforming-xml-with-xsl#choosing-and-preparing-xml-data): 

>For example, the module tutor in our introduction or a researcher who wants a simple table of the dates, publications and page numbers of humorous articles within the database. Both can be quickly created using XSL.

**Comment by arojascastro** [comment]
Uhmm I think I solved it. Forget.

**Comment by acrymble** [comment]
it just means teacher or lecturer. Very British expression.

**Comment by mhbeals** [comment]
I am happy to have the files transferred.

-MHB
________________________________

**Comment by arojascastro** [comment]
Hello all, 

I am wondering if I would have the author's permission to translate the names of the xml file into Spanish -- as well as the XSLT intructions. This is an extra work, but maybe it is worth the effort. What do you think?


### XSLT 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs" version="2.0">


  <xsl:template match="@* | node()">
    <xsl:copy>
      <xsl:apply-templates select="@*, node()"/>
    </xsl:copy>
  </xsl:template>


  <xsl:template match="root">
    <xsl:element name="raíz">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="record">
    <xsl:element name="registro">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="id">
    <xsl:element name="identificador">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="title">
    <xsl:element name="título">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="city">
    <xsl:element name="ciudad">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="province">
    <xsl:element name="provincia">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="country">
    <xsl:element name="país">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="date">
    <xsl:element name="fecha">
      <xsl:attribute name="cuándo"><xsl:value-of select="@when"/></xsl:attribute>
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="year">
    <xsl:element name="año">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="month">
    <xsl:element name="mes">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="day">
    <xsl:element name="dia">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="keywords">
    <xsl:element name="seccionPalabrasClave">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="keyword">
    <xsl:element name="palabraClave">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="headline">
    <xsl:element name="titular">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>
 

  <xsl:template match="text">
    <xsl:element name="texto">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>
  
  <xsl:template match="p">
    <xsl:element name="p">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

</xsl:stylesheet>
```

### output

```xml
 <registro>
      <identificador>15</identificador>
      <título>Glasgow Advertiser</título>
      <ciudad>Glasgow</ciudad>
      <provincia>Scotland</provincia>
      <país>United Kingdom</país>
      <fecha cuándo="1789-08-03">
         <año>1789</año>
         <mes>08</mes>
         <mes>03</mes>
      </fecha>
      <seccionPalabrasClave>
         <palabraClave>international trade</palabraClave>
         <palabraClave>prices</palabraClave>
      </seccionPalabrasClave>
      <titular/>
      <texto>
         <p>From Quebec, June 10, we are informed, Canada is at present greatly distressed; provisions extremely dear ; beef, if good for any thing, 5per pound ; mutton, 7–d. butter, 15d. The parishes in the upper country, about Niagara and Montreal, have been without bread for four months.</p>
         <p>There are orders now in town for as many goods for Quebec as will load ten ships; the trade being so exceedingly brisk, and the people giving the preference to European goods.</p>
      </texto>
   </registro>
```

In that case I would generate a `SAPsimple_es.xml` file that we could store in our github repository. But is there any legal problem?

**Comment by mhbeals** [comment]
Of course. Thank you!

MHB
________________________________

**Comment by arojascastro** [comment]
Just for the record, if we store the input in our github repository, I think the tutorial needs to be modified because there about two paragraphs explaining  how to download a zip from the author's repository... maybe this does not need to be removed though. Maybe it just need a link saying something like "You can also dowload the input files clicking here". What do you think @acrymble?

**Comment by ianmilligan1** [comment]
I've opened up a branch and will stage the file - I can put some sample language but @acrymble can edit it. 😄

**Comment by mdlincoln** [comment]
FWIW I'd favor simplicity - give the user one way to download the file, and don't unnecessarily confuse them
