### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#760]
Seen as one of our roles are editors is to promote PH at various events and fora, can I suggest that we add some info on our stickers to https://github.com/programminghistorian/jekyll/wiki/Service-Integrations so the process of getting swag is clear. I'm thinking:

- link to the template/logo
- service from which we have ordered / can order
- ~cost

@acrymble: you appear to know the most about this so input appreciated.

**Comment by ianmilligan1** [comment]
My research team ordered stickers from StickerMule, which we were really happy about. I can't remember how much they cost but it was under $100CAD for 75 or 100, and great customer service. If folks are curious I can pull the invoice from our system.

![20180319_115533](https://user-images.githubusercontent.com/3834704/37972371-345180ba-31a6-11e8-94ab-5e5086d8ff23.jpg)

**Comment by amsichani** [comment]
I am regularly using <a href="https://www.moo.com/uk/products/stickers-range.html">MOO</a> for business cards and stickers - really happy about the creative aspect of the service (fully customised,  inspirational templates) as well as the customer service. An estimated cost using their<a href="https://www.moo.com/uk/help/faq/cost-calculator.html"> online calculator</a>): for 200 round stickers, £75.24 incl tax / for 500 rectangular stickers , £164.10 incl tax, all 5 days delivery within the UK.

**Comment by acrymble** [comment]
In the past I used StickerYou, which is based in Canada but pretends to be American as all good Canadian companies do...

They were about 50 cents per sticker and you buy them in sheets on 20. I have some here in London and I could mail you some if you wanted @drjwbaker. If you're planning on ordering them through a university, keep in mind you'll need to use a supplier or set them up as one.

**Comment by JMParr** [comment]
I have used StickerMule with great results. Would love to get in on some stickers if we have some, or are planning to order some.

**Comment by acrymble** [comment]
@mariajoafana and I have a small sticker budget for our workshop we'll be hosting in Colombia in the summer.

**Comment by mariajoafana** [comment]
Perfect

**Comment by acrymble** [comment]
Does anyone want to design a new sticker, or are we happy with the existing one?

https://github.com/programminghistorian/jekyll/blob/gh-pages/_promo/programmingHistorianSticker-promo.png

**Comment by ianmilligan1** [comment]
Looks good to me!

**Comment by JMParr** [comment]
Looks good to me, unless we want to consider a brighter color to stand out
against laptop colors?

**Comment by acrymble** [comment]
not a lot of colour on our website. But we do have this blue on the front page.

![programminghistorian-blue](https://user-images.githubusercontent.com/646647/38309189-4348a988-3811-11e8-90f7-06fd3a7d9c0d.png)

**Comment by JMParr** [comment]
I like that. The other one was fine. And you're right that we don't have
much color on our website. I just see a lot of students with black and dark
gray laptops. The sticker might not have stood out very much.

**Comment by drjwbaker** [comment]
I like the design. No harm in having some PH stickers designs in some different color schemas though.

**Comment by acrymble** [comment]
Can I get a sense of who wants stickers, and how many?

**Comment by JMParr** [comment]
I would like stickers. Maybe 50? I could send you money.

**Comment by drjwbaker** [comment]
Ditto.

**Comment by acrymble** [comment]
Does this trope make sense for the Spanish stickers? Or is it just lame?
![programminghistorianred](https://user-images.githubusercontent.com/646647/38465981-073b2d10-3b1a-11e8-9eea-141645e07ec8.png)

**Comment by acrymble** [comment]
Costings for 2" square(ish) stickers:

Allwag (my university's official supplier)
500 - £75
1000 - £130

Sticker Mule
500 - $127 USD free shipping
1000 - $188 USD free shipping

MOO (rectangular stickers - they don't do square)
500 - £130 GBP + shipping
1000 - £260 GBP + shipping

StickerYou
500 - $174.75 + shipping
1000 - $299.50 + shipping

If we had 750 that would be 50 each. I can mail them out to everyone through the university post, so no extra shipping costs to us. If we each got 50 would everyone make sure they disappeared into the world?

**Comment by drjwbaker** [comment]
Awesome. Thanks for coordinating Adam. You need some £$€?

**Comment by acrymble** [comment]
Ideally #724 sponsorship, rather than out of pocket. I'd like to move away from covering costs ourselves.

**Comment by drjwbaker** [comment]
To clarify, do we need sponsorship now to buy stickers or is there budget around the Columbia work to cover this?

**Comment by acrymble** [comment]
I won't know that for a couple of months yet. We have to see how costs fall (but maybe, if we can wait)

**Comment by drjwbaker** [comment]
Okay. #765 isn't until late June, so we have some time.

**Comment by acrymble** [comment]
Just a note on this that only 2 people have actually expressed an interest in stickers. I'm not sure there's enough interest in this to coordinate something.

**Comment by arojascastro** [comment]
I think it's cool to have stickers. I would like to have the Spanish version though. I am not sure if we should coordinate this together or if the Spanish team should get stickers on their own. In any case, it would be good to have the logo with the tilde that you uploaded on Twitter some days ago. Maybe @mariajoafana and @vgayolrs want to have stickers for DH2018.

**Comment by JMParr** [comment]
I'd be happy to have stickers in both English and Spanish versions. I teach
in an area that has a sizable Spanish-speaking population. If there aren't
enough people to do orders as a group, perhaps editors could order their
own, as they see fit?

**Comment by jenniferisasi** [comment]
Sorry for the late reply @acrymble, I would like to have stickers too! Like @JMParr, I'd be happy to have both versions, as I will be in a mixed environment starting at the end of July. Would that be possible? As @arojascastro said, I don't know if you want to coordinate both languages separately?

**Comment by acrymble** [comment]
Thanks. We will definitely be getting Spanish stickers. I'm waiting to see our travel budget before we decide on English ones.

**Comment by alsalin** [comment]
I'd like 50 (25 english + 25 spanish). a bunch for me and some for ECDS :D

**Comment by amsichani** [comment]
I d like 50 EN stickers.

**Comment by walshbr** [comment]
I'd also like 50 EN stickers. If we have them by June I can take them to HILT and pass them out, but no worries if they're not in the mix by then.  There will always be other opportunities to give them away!

**Comment by ianmilligan1** [comment]
I'm on my way out I know but I can always make sure stickers find happy homes at events. Plus I have a few laptops I'd adorn them with (and my colleagues Nick Ruest and Ryan Deschamps have done yeomans work for the site so I'd give them some too).

**Comment by acrymble** [comment]
I'm not sure I'm going to be able to do this in time to send people stickers to Mexico. We're just needing to make sure our budget is ok before we make this order. So if someone has a pressing need, it might be worth making an individual order in the short term.

I'll still try, but don't rely on me!

**Comment by drjwbaker** [comment]
Thanks for the update @acrymble. So, those of us going to DH #765 I'm happy to make an order and bring them with me for distribution: say 100 EN and 100 ES?

**Comment by acrymble** [comment]
I've just managed to put this order in @drjwbaker . For 500 Spanish only. No promises when they will arrive.

**Comment by drjwbaker** [comment]
Huh. As it happened, I ordered 100 ES stickers from Stickermule yesterday as well. I've just tried to share the reorder code with our email list (which might not work..)

**Comment by drjwbaker** [comment]
(mine will be with me by 29 May)

**Comment by acrymble** [comment]
Can I close this then?

**Comment by drjwbaker** [comment]
@acrymble: I opened this because I wanted to document how we go about ordering stickers so it is clear for new members that we: a) have sticker templates b) do it ad-hob and c) mostly pay for it ourselves (at present). Where can we document this? https://github.com/programminghistorian/jekyll/wiki/Service-Integrations?

**Comment by acrymble** [comment]
Oh ok. Maybe we need a new page on the wiki for things we pay for that we need to find a budget for?

**Comment by drjwbaker** [comment]
Done. Edit as you see fit https://github.com/programminghistorian/jekyll/wiki/Things-we-pay-for-%28and-need-budget-for%29
