### ISSUE TITLE
Adding new editors bio & details at the project team page

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#762]
I am going to add my bio & details at the project team page. As I am waiting for some (hopefully!) good job developments within the coming weeks, I m probably going to update it soon ;)

_NOTE: This is part of a test issue / PR sequence for AM to support her onboarding on the PH workflow_

**Comment by amsichani** [comment]
once my PR is merged, it 'd be great if we can have a Spanish translation of my short bio - @arojascastro et al. muchas gracias!

**Comment by arojascastro** [comment]
Done in a3e0783708a26174b86c081eecc4db0d4de79ac1

**Comment by amsichani** [comment]
thanks @arojascastro !  I forgot to put my surname at the short bio- I ve updated the page in <a href="https://github.com/programminghistorian/jekyll/blob/%23762/_data/ph_authors.yml">0ba4d20</a>
