### ISSUE TITLE
DH2018

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#765]
A bunch of us are going to [DH2018](https://dh2018.adho.org/en/). This issue will be a central hub for:

- [x] Who is going (like this comment if you are going)
- [x] Things we plan to do there that are PH related.
- [x] Sticker/swag planning and distribution.
- [x] General meetup chatter (Tuesday during reception)

Please add info here.

**Comment by drjwbaker** [comment]
So who else will be at DH besides me and @mariajoafana? (I lost track, sorry!)

**Comment by walshbr** [comment]
I'll be there

**Comment by jamotilla** [comment]
i´ll be there @drjwbaker!

**Comment by vgayolrs** [comment]
Me too

**Comment by mdlincoln** [comment]
me!

**Comment by acrymble** [comment]
would be great if you could all take a photo of those of you there, so we can put it on the site!

**Comment by drjwbaker** [comment]
@acrymble Good call. I presume you will be taking some snaps in Bogota as well. If possible, let's keep these organised as promo shots.

**Comment by drjwbaker** [comment]
DH is next week! A couple of things:

- @mariajoafana is presenting on PH ES at a Thursday 4pm session (before the Fiesta!) https://www.conftool.pro/dh2018/index.php?page=browseSessions&form_session=317&presentations=show I hope we can all make it.
- I will have ~180 ES stickers with me.
- when do we want to aim to get together to chat + share stickers? One option is to meet Monday after the workshops (5pm), though this depends on us all being there on Monday. Alternatively, we could find each other at the reception? (Tuesday, 6pm)
- Do we want to shamelessly invade the DH hashtag with notes about PH ES? If so, who is up for sending some strategy, scheduled tweets.

**Comment by walshbr** [comment]
I could aim for the Tuesday reception. We're doing one of the excursions, but theoretically we should be back by then. Monday after the workshops might be a bit more difficult for me.

I think we should absolutely invade the DH hashtag. I'm happy to tweet in English, but I think it'd be better if we had someone tweet in Spanish given that the stickers are specifically about PH ES.

I'll try to make the Thursday talk!

**Comment by drjwbaker** [comment]
@walshbr You are going on a Tuesday excursion?

**Comment by walshbr** [comment]
Yeah a couple of us who weren't doing the Tuesday workshops found that was the only time we were free.

**Comment by drjwbaker** [comment]
Okay. Well in that case, let's endeavour to meet up during the reception (rather than right at the beginning), which should give you some time.

Do we want a group chat (WhatsApp?) to co-ordinate, say hi, during DH?

**Comment by mariajoafana** [comment]
The whatsapp group is a good idea. (My number +3123513693) I can meet on Tuesday during the reception. 
I'm working on my presentation, it's short, 10 minutes.  I will deliver in Spanish but will have bilingual slides. Or should I present in English? I have mixed feeling about this, since more people will understand the talk if I deliver it in English, but is paradoxical since we are talking about language diversity in DH...Three other papers in my panel are in Spanish and the other two in English.

I'm also revising our Google Analytics and working on an outline for the presentation. In the original proposal I focused on three main things: 1) the strategies to spread PH in the Spanish-speaking world (here I'll mention our upcoming workshop, and our outreach strategies via mailing lists, social media, and using PH tutorials in classes). 2) Analysis of the user's traffic of our PH en español since it was launched until today. 3) The challenges that the Spanish team has encountered in the process of translating tutorials, getting people involved in the Spanish-speaking world, in tandem with the need to understand the limits and possibilities of DH in Hispanic institutional, historical, economic, and cultural contexts. 

If there is any idea that anyone will like to contribute, particularly @arojascastro @vgayolrs @jamotilla and @jenniferisasi , please let me know.

**Comment by mdlincoln** [comment]
I've got the PH session on my calendar! 

And do add me on whatsapp: +1 570 854 9695

**Comment by walshbr** [comment]
@mariajoafana speaking as someone who will only understand glances of your talk in Spanish, I think presenting in Spanish with bilingual slides sounds great and makes a lot of sense. I think there are really strong reasons for presenting in Spanish like you say, and if you have a couple main points in English on slides I think people will understand and appreciate the presentation even if they're not Spanish speakers. But you're all the experts on this - I'm sure it will be great!

Will download and figure out whatsapp and report back!

**Comment by drjwbaker** [comment]
Note, we can take chat to WhatsApp now. I'll close this after the event (we may have some more actions we'd like to add to this)

**Comment by acrymble** [comment]
@drjwbaker if you want more Spanish stickers and will be in London next week, let me know.

**Comment by drjwbaker** [comment]
@acrymble We shall be in Mexico next week! :)

**Comment by acrymble** [comment]
Woops, right. Nevermind :)

**Comment by vgayolrs** [comment]
Hi
@drjwbaker, please, add me on WhatsApp: +1 52 351 127 9521
I'll there on Tuesday. ... and ready to invade the DH hashtag in Spanish with PH ES

**Comment by drjwbaker** [comment]
@vgayolrs Do you have a WhatsApp account? I've added you as a phone contact but can't find you in the app.

**Comment by vgayolrs** [comment]
Hi @drjwbaker , yes, I just join the WhatsApp group with the link you sent by email... and sorry, I just woke up and dyslexia is worse ... wrong number. The right one: +52 1 351 127 9521

**Comment by mpuren** [comment]
Hi @drjwbaker, I'm in Mexico, and I can meet you during the reception on Tuesday. I have a WhatsApp account and I just join the group. Here my number +33 6 36 70 50 96.

**Comment by acrymble** [comment]
Can someone make sure that we get a great blog post out of this and that any papers are added to /research if they presented (even loosely) on PH activity?

**Comment by drjwbaker** [comment]
@mariajoafana Perhaps we could write something that takes the highlights from your slides in terms of a) what ES has done b) impact of ES c) challenges and next steps?

**Comment by drjwbaker** [comment]
(plus, of course, a little on the conference itself: team meeting up, nomination of @mariajoafana's paper, ~200 stickers circulated)

**Comment by mariajoafana** [comment]
Yes, I agree. Should we write the post in English and then translate it into Spanish?

**Comment by drjwbaker** [comment]
If that works for you, yes. Perhaps you could start by cutting/pasting some relevant bits from your talk into a draft post at https://github.com/programminghistorian/jekyll/tree/gh-pages/_posts and I can then try to weave it all together! Plan?

**Comment by mariajoafana** [comment]
Yes, plan!

**Comment by drjwbaker** [comment]
Drafting here https://github.com/programminghistorian/jekyll/pull/932#issuecomment-403715143
