### ISSUE TITLE
Volume & Issue numbers

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#767]
- [x] How do we want to split into volumes/issues? Volume by year, and that's it?
- [ ] Generate these from published date metadata (we should _not_ be manually typing these volume numbers into these metadata)
- [x] Display suggested citation on lesson page

**Comment by acrymble** [comment]
I would vote for 1 volume per calendar year, to keep life simple for us. I don't know that issues make sense. Will that be important for our authors?

**Comment by drjwbaker** [comment]
We could for the sake of appearances have two issues per year, one for all articles published Jan-Jun, one for all articles published Jul-Dec. OLH do that for the sake of appearances. The question is whether we care *that* much about appearances and/or whether it helps some of our authors to have issues numbers.

**Comment by mdlincoln** [comment]
Plenty of smaller journals I cite in art history, for one, only have one number, and don't subdivide. In my personal experience, I think just numbering by year would be fine... open to opposing, real-life examples though.

**Comment by drjwbaker** [comment]
If we have precedent, do that.

**Comment by acrymble** [comment]
To make this conform to journal practices, can we add a second display to the /lessons page so that /lessons becomes 'Browse by topic' and a second page just shows a static volume-by-volume display in reverse publication order? I'd envisage this as a 'Browse by volume' page, making 'Lessons' a drop-down menu on the menu bar. Thoughts?

**Comment by amsichani** [comment]
What I think is important (and I am not sure there is available somewhere - please point it out if there is one), is a (suggested) standard citation mechanism for our lessons. With the volumes now in hand, this 'd look like a proper journal article citation.

**Comment by acrymble** [comment]
another question: are we going to treat the various language versions as part of the same 'publication', or will each language get its own volume numbering and be listed independently? If we have a /es/lessons/volumes page will it only list the Spanish lessons? I'd say yes. That then raises questions as to whether or not /es is a separate publication entity.

**Comment by mdlincoln** [comment]
I don't see need for a "volumes" page, since the stated need for this is just so that we can have a nice suggested citation that feels more like a print journal. The only delimiter for these volumes is the year published, there is no other special mechanism; we don't have "special issues" that need highlighting in that way.

That said, the volume numbering could be different between spanish and english lessons. Volume 1 for _The Programming Historian_ starts in 2012 by my count; whereas Volume 1 for _The Programming Historian en español_ starts in 2016. Thoughts?

**Comment by arojascastro** [comment]
Yes, I agree with @mdlincoln: 1 volume per year / separate En and Esp - after all the title is different thus it is a different publication

A side thought: now that we have *volumes* we could open calls on specific topics to fill in some gaps. For instance, in my opinion we have lots of tutorials on text anaylisis and data mining but very few on publication and website design. Also as I said here https://github.com/programminghistorian/jekyll/issues/768 we could use calls to find tutorials that use multilingual resources or that focus on transnational issues or topics.

**Comment by mdlincoln** [comment]
@arojascastro I think the idea of focused clusters of lessons would be great, but that is explicitly NOT what these volume numbers are doing. They are simply mirrors of the year a lesson was published, and add no additional semantic meaning. Any additional subdivision would mean adding new categories into lesson metadata. This is fine, but it'd be a separate task than generating volumes numbers.

**Comment by arojascastro** [comment]
I know you are not trying to do that, I am just jumping with an idea that it was related anyway.

**Comment by drjwbaker** [comment]
@acrymble Why was this closed? I can't see that volume numbers for each year have been implemented on the site.

**Comment by acrymble** [comment]
Because #771 took its place I believe.

**Comment by drjwbaker** [comment]
Ta. Ignore my Friday afternoon madness :)
