### ISSUE TITLE
Internationalisation of our author, review, and editorial guidelines

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#768]
Agreed at #729 we will look at working on internationalising our author, review, and editorial guidelines this year. This piece of work will take into account the call for a Spanish lesson, DH2018, and the potential addition of a French team. I am happy to work on this.

**Comment by acrymble** [comment]
This would make a great workshop for DH people more broadly. Maybe something we could host in London if we could get together money. I'd love to learn these skills so I can be a better contributor to the community. But that's an aside.

**Comment by arojascastro** [comment]
I am interested as well. I know this is a broader issue, but a straightforward measure would be to implement the guidelines that I authored (with additions and modifications of course) in https://github.com/programminghistorian/jekyll/issues/651. In respect of authors, editors and reviewers, we need to expand our pool of collaborators and search actively for them - perhaps by opening a specific call on a specific issue and stating that we are looking for tutorials on multilingual resources or questions that focus on transnational historical problems. Also we can use Twitter to recruit people and open a discussion about the topic.

**Comment by arojascastro** [comment]
Just for the record, I found these EdX [Guidelines for Writing Global English](http://draft-edx-style-guide.readthedocs.io/en/latest/global_English.html) useful.

**Comment by acrymble** [comment]
is this still an active task?

**Comment by drjwbaker** [comment]
I *think* #651 was a big step in this direction. I expect Bogota, DH2018, and FR will all demand we return to these issues, but I'm happy to close with a note that we haven't addressed this in our [Reviewer Guidelines](https://programminghistorian.org/en/reviewer-guidelines#openness-and-inclusivity) yet.
