### ISSUE TITLE
Tutorial Lengths & Translations

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#779]
@arojascastro has pointed out that longer tutorials take more work to translate #751 . If we move to paid copy editing, longer lessons will also incur a greater cost (£).

@drjwbaker noted there wasn't a clear pedagogical reason for restricting tutorial lengths, but the above reasons may be good enough for encouraging a maximum word length. In particular, our current translations have (understandably) focused on the shorter tutorials:

![translated-length](https://user-images.githubusercontent.com/646647/38369051-c0f79a7e-38de-11e8-8be0-e4edf224d44e.png)

Over time, our lessons have become considerably longer, and not necessarily at the benefit of increased traffic (not that traffic is the only measure of success worth noting):

![traffic-length](https://user-images.githubusercontent.com/646647/38369097-da89a0cc-38de-11e8-997b-bf69ed2ea68b.png)

Y axis is word length; x asis is year published; size is traffic past 12 months.

It seems that there may be good colleagial and financial reasons for capping submissions to less than 8,000 words? This is still quite long, and in line with many other journals in history.

**Comment by ianmilligan1** [comment]
Capping at 8,000 words sounds sensible to me.

**Comment by acrymble** [comment]
related to #681

**Comment by acrymble** [comment]
I would like to add this to our current documentation so that authors can begin to follow it. If you would like to raise any concerns, please do so by 7 May 2018, at which point I"m going to add a pull request.

**Comment by walshbr** [comment]
As I mentioned on the call, I think this is a good suggestion. Particularly since it covers most tutorials that we have already, I think it's a fine approach that would cover us from extreme cases. I'd just want to make sure that the language for this indicates that while 8000 words is the upper limit we encourage and frequently publish shorter lessons.

**Comment by arojascastro** [comment]
I like it as long as it is clear that it is an approximation (do you say that in English?), upper limit as @walshbr points to, and that we are happy to create a series of tutorials on a topic that needs more length (like the tutorials on Python and on Geospatial analysis).

**Comment by acrymble** [comment]
This involves changing the same files as being amended in #651 so I will adjust that once the first ticket has been closed.

**Comment by acrymble** [comment]
This has been closed via #830 pull request.
