### ISSUE TITLE
Additional ISSNs for each language?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#788]
Raised by @amsichani in #698.

Do we want an additional ISSN number for each language version of the project?

This probably makes the most sense given our recent decision to use volume numbers #767 that are differently numbered in English and Spanish. It implies that the two publications are distinct, and as @drjwbaker noted, it may lead to greater independence of future versions of the project in other languages. That may or may not be desirable.

**Comment by drjwbaker** [comment]
Re #789 this needs quorum because to quote me from #698:

> It may be technical, but it has potentially profound ramifications long term: even if we stay two integrated publications for now and believe we will forever creating a technical infrastructure that lists us as publishing two (or, if we get a FR version, more) separate publications creates the conditions for divergence in the future (eg: separate editorial boards, laying of management structure, divergence of content)

**Comment by arojascastro** [comment]
Yes, I think having more than one ISSN is a good idea and it is coherent with the volume numbers. We need more feedback from @jenniferisasi @vgayolrs @mariajoafana @jamotilla etc.

**Comment by amsichani** [comment]
Given the importance of the issue in the long-term and as a number of people are not going to join at #777, I think we need to have quorum on this one (I 'd say, also enough people representing the ES team). 

Assigning distinct ISSN for each of the PH publication series, also as part of their DOAJ entries, and overall information management.
As for now, we are producing two separate scholarly publication series, (its useful, I guess,  to think of those as two separate journal titles), EN and ES. For each language, we ll have a separate ISSN and each ISSN will have its own volume numbering for their indexing - we should be aware that volume numbers of these publications won't align. If we get a FR PH version, we are going to add a third publication (ISSN& volume numbering) on our publications list. These should be seen as closely aligned publications but not identical ones, from an Information Science/bibliographic point of view.

From a technical - operational point of view:
- obtain one more UK ISSNs from [BL](http://www.bl.uk/bibliographic/issn.html), for our ES publication series. Once we know the procedure, I guess it 'd be easy to ask for another one (eg FR) in the near future, if needed .

What is needed for an ISSN:

> ISSN numbers can be issued in advance* of publication via the [application form](http://forms.bl.uk/bibliographic/index.aspx) which can be completed and sent online, or printed out and faxed / posted to us. The form is also available in PDF format 109KB which can be emailed to you. It is not possible to assign ISSN over the telephone. The basic information required is:
> 
> Proposed title (working titles / project titles are not sufficient);
> Frequency of publication;
> Proposed start date (month / year);
> Publisher name and address.
> The Centre will also need to receive a copy of the first issue on publication in order to validate our records. This copy will be passed through to the Legal Deposit Office and subsequent issues can be sent directly to them.
> 

*we need to ask if the ISSN can be also obtained _after_ the launch of an online publication, as we are already having a couple of ES lessons, waiting for their ISSN.

- once obtained, add the adequate ISSN to the DOAJ for each ES publication/ lesson as discussed #698.

- create volume numbers for each ISSN publication and add full citation by the end of each lesson #767.

Given that the ISSN assignment could also mark in a more eloquent way the conditions for divergence within the PH management structure in the future, I think its wise to start discussing or reflecting on how we are planning to deal with eg. Main editorial board & separate editorial teams,  quorum, uniformity on guidelines, divergence of content etc. This is something important we need to decide, as the PH team is getting bigger and more diverse.

**Comment by acrymble** [comment]
This plan would really mean we have a federated system, with a central editorial board responsible for policy / consistency, and separate publications operating largely atonomously. I kind of feel like we do that already, so maybe it isn't a big jump. But it might feel like one.

**Comment by amsichani** [comment]
I agree - this is how we are normally operating as for now. I just wanted to have it written down, just to make sure we are all on the same page. Should we ask BL for another ISSN for the ES publication?

**Comment by drjwbaker** [comment]
@amsichani It seems to me that if we are to agree to do this https://github.com/programminghistorian/jekyll/issues/378#issuecomment-383892254 then yes we need an ISSN for each language project.

And on..

> we need to ask if the ISSN can be also obtained after the launch of an online publication, as we are already having a couple of ES lessons, waiting for their ISSN.

.. the ISSN for the EN lessons was obtained after publication began.

**Comment by amsichani** [comment]
great- thanks for the update @drjwbaker . Let's wait until 7th May to see how consensus on #378 goes.

**Comment by drjwbaker** [comment]
@JMParr to get ES ISSN. Update me when you have it so I can action #698.

- [x] apply for ISSN at [http://forms.bl.uk/bibliographic/index.aspx](http://forms.bl.uk/bibliographic/index.aspx)

**Comment by JMParr** [comment]
I have applied and requested an ES ISSN. Confirmation, etc, will go to @acrymble because I used the same information he used to apply for the EN ISSN.

**Comment by acrymble** [comment]
Can we close this issue then?

**Comment by drjwbaker** [comment]
When our application for an ISSN for the ES site is successful, yes.

**Comment by acrymble** [comment]
Dear Dr Crymble,

INTERNATIONAL STANDARD SERIAL NUMBER (ISSN)

Thank you for your recent enquiry.  We have assigned the following ISSN:

The programming historian en español    ISSN 2517-5769

We would be grateful if the ISSN could be printed in all issues of the serial, preferably on the top right-hand corner of the front cover or title screen in the form given above, i.e. preceded by the letters ISSN with a hyphen separating the two halves of the number.  If the serial is available in more than one physical format, a separate number is assigned to each version and all the ISSN should be quoted on each version available, with an appropriate qualifier in brackets, eg:

ISSN 0000-0000 (Print)
ISSN 0000-0000 (Online)
ISSN 0000-0000 (CD-ROM)

The same ISSN is printed on successive issues of the serial, providing the title does not change.  Please notify us in advance of any change in title, however slight, as this may necessitate the assigning of a new number. The ISSN should also be quoted in all promotional and descriptive material concerning the serial.

The ISSN UK Centre requires only the first issue of a publication. For details of the current and future arrangements for legal deposit of websites and electronic publications, please see the information provided at: http://www.bl.uk/aboutus/legaldeposit/websites/index.html

Thank you for your interest and co-operation.

Yours sincerely

ISSN UK Centre                                                  Ref. 7  Electronic                                           

NB.  Please consider this email official notification of your ISSN as no further letter will be sent.

**Comment by drjwbaker** [comment]
Thanks @acrymble. Close and add getting an ISSN to the FR setup workflow?

**Comment by acrymble** [comment]
I don't think we need an issn for French until we have French content. Maybe we can revisit it once we have a launch date?
