### ISSUE TITLE
Header hover anchor links

### ISSUE THREAD

**Issue by todrobbins** [programminghistorian/jekyll#79]
Let's try to implement something similar to http://ben.balter.com/2014/03/13/pages-anchor-links/ for header anchors and the ability to link to specific sections on pages. See #78 for discussion of this.

**Comment by wcaleb** [comment]
I think I've got the hover icons working, but haven't tested in multiple browsers. Let me know if it seems to work for you. @todrobbins @miriamposner

**Comment by todrobbins** [comment]
It's working for me on multiple browsers! Great work @wcaleb!

**Comment by fredgibbs** [comment]
@wcaleb @todrobbins this is great! thanks to you both for proposing and working through this so quickly!

**Comment by wcaleb** [comment]
I've moved the icon so that it hovers just inside the right edge of the 
browser window, because putting it in front of header was messing up 
center spacing a little. Let me know if you think the new way breaks 
functionality.
