### ISSUE TITLE
Change 'Editorial Team' and 'Spanish Team' tags

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#802]
On the /project-team page we have an 'Editorial Team' (which basically means Editorial Team (English)) and 'Spanish Team' (which basically means Editorial Team (Spanish)).

I think it implies a hierarchy that we don't want to communicate.

Propose changing this to:

* Editorial Team (English)
* Editorial Team (Spanish)

This also allows additional 'teams' to be added.

I don't think this is controversial, so once I have 7 people express consent, I will do a pull request. Any concerns, please raise them.

**Comment by ianmilligan1** [comment]
👍

**Comment by arojascastro** [comment]
Good idea!

**Comment by acrymble** [comment]
Thanks, we have 8 approvals. I'm going to make this change.
