### ISSUE TITLE
Error on R-Basics With Tabular Data

### ISSUE THREAD

**Issue by JMParr** [programminghistorian/jekyll#805]
User Jeniffer Lilliam Mendoza Espinosa reports a potential bug in the coding at the following juncture:

>Crime(apply,1,mean) 
[1] ......
>Crime(apply, 2,mean)

**Comment by mdlincoln** [comment]
I see - not a bug per se, just a typo in the code in the lesson. I'll make a PR.

**Comment by JMParr** [comment]
Excllent. Thank you!
