### ISSUE TITLE
Editor Guidelines out of sync

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#809]
The editor guidelines are a bit behind current policy. Suggest a few tweaks to the 'Editorial Checklist' (having just used them).

2) Create an Author Bio
 - the example doesn't have 'team: false;' in it.

4) Add reviewers and editors to the YAML file
 - i~~sn't there also a listing of 'reviewers' you have to add them too as well? I couldn't find this. And I know we've had trouble in the past of editors forgetting to do it. Maybe we can just have this parsed from the combined metadata automatically somehow?~~

8) Other lesson YAML finalization
 - the example given doesn't include all fields required in recently published lessons. It is missing the 'editors:' and 'review-ticket:' fields.

all minor things, but wanted to raise them.

**Comment by mdlincoln** [comment]
Reviewers no longer need to be added to any combined list; I updated it to generate from metadata a few months back.
