### ISSUE TITLE
Gold Open Access

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#81]
Our project is 'Gold' Open Access compliant and charges no Article Processing Fee (APC). That's increasingly important for some people. Where should we put that info?

**Comment by drjwbaker** [comment]
Could PH align itself with http://doaj.org/ guidelines on this? (if not apply to be DOAJ listed as PH isn't a journal, right?)

**Comment by acrymble** [comment]
Not sure if we'd qualify, as we're not a legal entity. But we could try.

**Comment by drjwbaker** [comment]
Aligning to the principles might then be a start. OAPEN have some guidelines PH could usefully align with http://www.oapen.org/peerreview?page=intro (if not join formally)

**Comment by acrymble** [comment]
Thanks James. Do you think we fall short of that at the moment?

**Comment by drjwbaker** [comment]
PH has excellent peer review standards as far as I can tell. Clear guidance on citation (which I note is coming) and how PH complies with OA best practice for book-like works (I've always described, perhaps erroneously, PH as 'an open, iterative, collaborative book') would I imagine help authors comply with mandates/their conscience and justify writing for you.

**Comment by acrymble** [comment]
I've incorporated this information onto the about page. Thanks @drjwbaker .

**Comment by drjwbaker** [comment]
Nice summary.
