### ISSUE TITLE
Suggested citations

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#82]
I think we need to add suggested citations for our lessons and for the project. This should be possible via the YAML files, no?

**Comment by wcaleb** [comment]
Yes, should be. If you let me know how citation should be formatted I can add to layout.

**Comment by acrymble** [comment]
That's quite a philosphical question. I'm always a Chicago person. But is everyone happy with that? I suppose date would be the date the lesson was published? And now, do we need a 'version number' for the project? We might need to think about our metadata.

**Comment by wcaleb** [comment]
I think an "accessed on" phrase could solve the version problem. Though 
theoretically I may be able to insert the actual git hash number.

**Comment by acrymble** [comment]
I'm not a big fan of the 'accessed on', but I do like the hash number, in theory. If I were citing a lesson, I think I'd do it like this:

Ian Milligan and James Baker, 'Introduction to the Bash Command Line', *The Programming Historian* (20 September 2014) <http://programminghistorian.org/lessons/intro-to-bash>.

I think what I'd like to be able to do is to give the reader some indication of which version of the lesson I had used. But we don't really make that clear anywhere.

**Comment by nabsiddiqui** [comment]
Honestly, I think including the hash number would be a bit difficult for people to use.  It would require users to understand the backend of the system that they may not be familiar with.  It may be easier just to do 'accessed on' since this is something that all the major citation styles have formats for .  There is no reason the citations have to be one style.  We could have different suggested citations for MLA, Chicago, etc.

**Comment by acrymble** [comment]
You're probably right about the hash number. We needn't throw it down someone's throat what back end we're using for our site. They won't care. Shouldn't care.

Most people can convert MLA to Chicago and vise versa. Since the site is fairly static, @wcaleb I presume it's easiest for us to offer one suggested citation and let users decide what to do with it?

**Comment by wcaleb** [comment]
Yes, I think a suggested citation would work best. I will work on this later this week. Thanks!

**Comment by acrymble** [comment]
If you're going to be mucking about anyway, can we expose the data in a way that will make lessons automatically Zoteroable via the little icon in the URL bar? https://www.zotero.org/support/dev/exposing_metadata

**Comment by wcaleb** [comment]
I think we already have that. Have you tried it and it didn't work?

**Comment by acrymble** [comment]
sorry, you're right. ignore me.

**Comment by drjwbaker** [comment]
Small thought: it defaults to 'web page' as an item type. This might require a bigger discussion in terms of how PH sees itself, but I - from a semi-outside perspective - have always seen PH as a book project so 'Book Section' feels the appropriate item type here for me. Either way, neither 'Web Page' nor 'Book Section' allow for DOI fields in Zoteroland. Perhaps looking ahead those item types that have DOI fields should be considered?

**Comment by fredgibbs** [comment]
i feel strongly that the zotero item type should be journal article; i think we’re much more like an online journal than any of the other standard zotero item types.


-- 

frederick w gibbs | assistant professor of history | univ. of new mexico


fredgibbs.net | @fredgibbs

**Comment by wcaleb** [comment]
I think @mdlincoln is the one who implemented the Zotero metadata detection for us. Is it easy to switch the item type, Matthew?

**Comment by acrymble** [comment]
If fred feels strongly, I don't feel strongly enough to disagree.

On Mon, Apr 27, 2015 at 2:38 PM, W. Caleb McDaniel <notifications@github.com

**Comment by nabsiddiqui** [comment]
Just chiming in to say I agree with fred.  I think the rhetoric of the "contribution" page also seems to suggest that Programming Historian views itself as an online journal rather than a website.  Things like reviewers, editors, etc. further contribute to this idea.

**Comment by mdlincoln** [comment]
Yes, I can switch the item type to 'article' easily enough.

**Comment by mdlincoln** [comment]
On a related note, at the moment lesson I've coded reviewers as "contributors" in the COinS tags. It is also possible to code them as "editors". Depending on your CSL, "editors" can get higher priority than "contributors". For example, Chicago citations list editors, but not contributors.

**Comment by acrymble** [comment]
The 'contributor' thing is throwing off aggregator sites. Google Scholar has found the PH, but it doesn't know what to do with the metadata: http://scholar.google.co.uk/citations?view_op=view_citation&hl=en&user=-l26ZlEAAAAJ&citation_for_view=-l26ZlEAAAAJ:Zph67rFs4hoC

**Comment by mdlincoln** [comment]
Hmm I see. Browsing the [Zotero documentation](https://www.zotero.org/support/dev/exposing_metadata), it looks like `<meta>` tags using DC terms may be a better solution for both Zotero and Google Scholar than COinS. I'll look into it further.

**Comment by mdlincoln** [comment]
Switching over to `<meta>` tags and/or classifying the lessons as journal articles rather than websites (either using COinS or `<meta>` tags) means ditching the ability to list reviewers as "contributors" in the metadata.

My two cents: switch to the `<meta>` tags. 

- It's easy to classify the lessons as journal articles with them
- they're easier to update with future info (like DOIs for lessons if ever implemented)
- Zotero and Google Scholar can both import them
- Even if Zotero does capture reviewers as "Contributors" using COinS, none of the main citation styles ever include "Contributors", anyway.

If this sounds fine, I can do a pull request for the `<meta>` tags. I'm also happy to write up code for the suggested citations while I'm at it.

**Comment by wcaleb** [comment]
That sounds good to me, @mdlincoln. If you do want to do the citation code, too, I'd separate it out so it can be reviewed as a separate PR.

**Comment by mdlincoln** [comment]
:+1:
