### ISSUE TITLE
editorial instructions - review ticket

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#820]
@mdlincoln wants the full URL rather than the review ticket number in the 'review-ticket' yaml field.

The instructions in /editor-guidelines currently say:

> 6) Add the review ticket number to the YAML file
> 
> In order to promote transparency around the review process, create a review-ticket key in the YAML file and provide the ticket number for the corresponding review ticket in the ph-submissions repository. This information will be used to provide a link back to the review ticket for the lesson.

Needs to be updated in both languages, as well as the example YAML in the same files.

**Comment by arojascastro** [comment]
Ok, I can translate.

**Comment by arojascastro** [comment]
Done in committ https://github.com/programminghistorian/jekyll/commit/6745800c23cb3dee5387603b0c00f058b6f4714e

**Comment by acrymble** [comment]
Merged. Closing.
