### ISSUE TITLE
Workflow for translating from Spanish to English

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#835]
As we now accept Spanish-language lessons, we need to consider how we will manage the translation of lessons from Spanish into English.

Our workshop in Bogota in August may result in a number of Spanish lessons, so we should be prepared for this workflow for whenever we need to implement it. Please share thoughts on how best to manage this new task.

**Comment by drjwbaker** [comment]
Perhaps we need a list of all the relevant translation that editors can do and then figure out who is responsible for what. Thus far relevant translations are:

- EN > ES
- ES > EN
- EN > FR
- FR > EN
- ES > FR
- FR > ES

I guess then each team (EN, ES, FR) needs a person responsible for editing incoming translations that have already been edited (I should add, that of course I trust my ES colleagues to translate to EN!)

**Comment by acrymble** [comment]
I think the best solution for this is to recruit someone specifically to take on this task. That is, unless someone on the team wants to devote their energy to it. I don't think we need to worry about French just yet.

**Comment by drjwbaker** [comment]
And/or reshuffle existing translation resource so that people are allocated to specific types of translation. Agreed that FR > EN is not an issue right now.

**Comment by acrymble** [comment]
Fine, if someone is interested. Does anyone on the Spanish team want to be the Spanish-to-English person? @mariajoafana @arojascastro @jenniferisasi @vgayolrs @jamotilla ?

**Comment by arojascastro** [comment]
I think I cannot be that person at the moment (since I want to go on a leave for some months). Maybe in the future... sorry.

**Comment by jenniferisasi** [comment]
To clarify, what would be the main tasks you envision for this role? a) translator, b) editor of translation, c) both a & b?

**Comment by acrymble** [comment]
b.

**Comment by acrymble** [comment]
I mean, c if that's what the person wants. But given the volume it might entail, I think B is more realistic.

**Comment by acrymble** [comment]
We discussed this in the August 2018 call. I'm going to close this because we don't need this person for at least 6 months, so it's premature to take up energy on it at this time. This can be reopened when it becomes more urgent.
