### ISSUE TITLE
Language change icons (header)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#837]
Our header currently only really supports space for 1 additional language.

<img width="1345" alt="screen shot 2018-05-13 at 17 24 17" src="https://user-images.githubusercontent.com/646647/39969339-3c816b28-56d2-11e8-85e1-97c975a54de3.png">

We will need to alter the design a little to allow for choice between 3 languages. Perhaps a "Language" drop down icon? https://thenounproject.com/search/?q=language

**Comment by drjwbaker** [comment]
In the first instance, can't we just list them (whilst making it clear that ES / FR / EN are language options)? We have the space between the title and the options.

**Comment by acrymble** [comment]
Ok, that sounds reasonable.
