### ISSUE TITLE
Typo on lesson "R Basics with Tabular Data"

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#838]
Hi @acrymble, 

While reviewing my translating of this lesson ([#164](https://github.com/programminghistorian/ph-submissions/issues/164)), we found a typo on "[R Basics with Tabular Data](https://programminghistorian.org/lessons/r-basics-with-tabular-data)" regarding the code to upload data into R
- The Ós on **read.csv(file=Ófile-name.csvÓ,header=TRUE,sep=Ó,Ó)** should be quotes and read: **read.csv(file="file-name.csv",header=TRUE,sep=",")** 

Thanks!

**Comment by acrymble** [comment]
Thanks, I will fix this after finishing #826 because it involves fixing the same files.
