### ISSUE TITLE
Review of Antconc

### ISSUE THREAD

**Issue by nabsiddiqui** [programminghistorian/jekyll#84]
This was a very interesting tutorial, and I really enjoyed working through it.  Antconc seems to be an extremely powerful tool, and I didn’t know it existed before this.  I definitely think it will be helpful for historians as they look at more data analysis related issues.  My concerns with the review are largely small and deal with organization, formatting, and some grammatical error.  In regards to the lesson itself, it seems that there is a little bit of a breakdown near the end on clarity and there is also a few other  places where I think the lesson could be a little clearer.

## General Points

1. I would have liked to see a “Downloads for this project” somewhere near the top.  By scattering it through the text, it can sometimes be problematic as you work through the tutorial.

2. Some of the “see also” stuff seems misplaced in the tutorial.  I think it would be better served near the end of the tutorial in a Further Resources section.

3. Similar to point two, I would like to see a shortened copy of the Introductory Bibliography on the author’s site in the actual lesson itself, perhaps included in the Further Resources section.  Preferably one that is annotated so that people know where to start and what they are looking at.

4. The “levels” need to be explained and articulated.  It is confusing as to what Level 1 “1L” means and Level 2 “2R” are.  Make sure that all the correct choices are marked in the screen shots also.

5. The zip file contains a file that consists of “all reviews” but seems to be replicated when you load in the positive reviews and the negative reviews.  I would delete the “all reviews” folder and just keep the positive and negative review folders to save file size. I don’t remember the “all reviews” folder being used.

6. Stopwords should be removed in my opinion.  The author mentions that she prefers them, but I did not really find a reason why.  In fact, I think the tutorial could be expanded to include how to get rid of them.

## Specific Points

>There are other concordance software packages available, but it is freely available across platforms and very well maintained. See the concordance bibliography for other resources

Should say

>There are other concordance software packages available, but **this** is freely available across platforms and very well maintained. See the concordance bibliography for other resources

In general I would recommend getting rid of the above line altogether.  It seems a little off topic.

> Another version of this tutorial, considers more specific ways to use these methods to produce and answer specific research questions.

Remove or put in new “Further Resources” section.

>By text clean-up, I mean removing extratextual information such as “boilerplate” which appears regularly throughout. If you keep this information, it’s going to throw your data off; text analysis software will address these words in word counts, statistical analyses, and lexical relationships. For example, you might want to remove standard headers and footers which will appear on every page.

Seems to be unnecessary to include this information.  Perhaps a link to the “Cleaning Data with OpenRefine” and “Cleaning OCR’d text with Regular Expressions” tutorial on Programming Historian.

>For more on these topics, see “Representativeness in Corpus Design,” Literary and Linguistic Computing, 8 (4): 243-257; Developing Linguistic Corpora: a Guide to Good Practice. Remember, each file you want to use in your corpus must be a plain text file for Antconc to use it. It is customary to name files with the .txt suffix so that you know what kind of file it is.

Remove or put in new “Further Resources” section.

>Download the zip file of movie reviews, and move it to your desktop ~~or somewhere else easily accessible~~. If the zip file did not automatically unzip when you saved it, unzip it yourself (as your operating system requires). You should see a folder labled “movie reviews from nltk” on your desktop.

Rest of the tutorial always references desktop.  Remove striked out text for consistency.

>In the search box at the bottom, type the and click “start”. The Concordance view will show you every time the word the appears in our corpus of movie reviews, and some context for it. This is called a “Key Words in Context” viewer.

“The” should be put in quotes.  I would not recommend using a stop word though.  It seems a strange choice for a tutorial like this.  Replace with different word.

>Try a similar search for “a”. do we get the same kinds of patterns?

Same problem as “the.”  Would prefer a different word.  Also, I would remove the rhetorical question and just explain what pattern is being displayed.  

>What do you see? I understand this can be a difficult to read way of identifiying patterns. Try pressing the yellow “sort” button. What happens now?

Same as above.  Describe what happens rather than be rhetorical.

>The * operator (which finds zero or more characters) can help, for instance, find both the singular and the plural forms of nouns.

Would like this explained a little more.  What does “zero or more characters” mean?  It only makes sense when you do the rest of the tutorial.

>First, sort each search in a meaningful way (eg. by search term then 1L then 2L)
Second, File > Save output to text file (& append with .txt.)

Change formatting.  Would be better as a list.

>~~HINT~~TIP: During the course of exploring in your research, you may generate many such files for reference; it’s helpful to use descriptive filenames that describe what’s in them (so, not “antconc_results.txt”).

“TIP” makes more sense.  Also, it would make more sense if the author gives an example of a good filename rather than what not to use.  

>Do this for each of the two searches and then look at the two text files side by side. What do you notice?

Rhetorical question should be removed.  Describe what is important about the text file.  Also, some people may be confused by the output the text file.  Make sure to mention that they need to maximize/expand the window.

>Try generating collocates for she.

Should not be tabbed over.

>Screenshot of collocates

Screenshot seems to have a collocate for “she” at the beginning which mine did not produce.  I am using OS X.  The first word is “s”.  Another problem is that the From and To Sections have to be changed and the sort by frequency has to be selected.  This should be explicit in the text and explained.  What is 1L, 2R, etc.?

>Task: Generate collocates for m?n and wom?n. Now sort them by frequency to 1L.

Explain why we need to change to 1L.  Also, the 1L is in the “To” section.  What should be in the “For” section.  What do these settings do?

>Some people might want to remove these small words by using a stopword list; this is a common step in topic modelling. Personally I don’t encourage this practice because addressing highly-frequent words is where computers shine! As readers we tend not to notice them very much. Computers, especially software like Antconc, can show us where these words do and do not appear and that can be quite interesting, especially in very large collections of text.

Stopwords are usually removed for a reason.  They are largely noise.  I don’t understand the benefits of keeping them, and I think the tutorial would be better served by having a section on removing stop words.

>Settings > Tool preferences > Keyword List
Under ‘Reference Corpus’ make sure “Use raw files” is checked
Add Directory > open the folder containing the files that make up the reference corpus
Ensure you have a whole list of files

Should be formatted as a list.  Also in the final line, it should say what the reference corpus folder is called for clarity(i.e. “Spielberg reviews”)

>Screen shot about swapping ref/main files

Minor detail but my button says “Swap with target files.” Again, on Mac OS X.

> Keyness: this is the frequency of a word in the text when compared with its frequency in a reference corpus, “such that the statistical probability as computed by an appropriate procedure is smaller than or equal to a p value specified by the user.” – taken from here.)

Keep the part on keyness but remove the “taken from here” and put near the bottom in the Further Resources section.

>Hit Load (& wait …) then once the ‘Loaded’ box is checked, hit Apply.
>You can also opt to swap reference corpus & main files (SWAP REF/MAIN FILES) and it is worth >looking at what both results show.

>In Keyword List, just hit Start (with nothing typed in the search box). We see a list of Keywords that >have words that are much more “unusual” – more statistically unexpected – in the corpus we are >looking at when compared to the reference corpus.

Tutorial needs to be clarified here.  The image that is later shown takes the swapping of the target files to be a given.  In order to do this, you have to make sure that you load the original files again by hitting the load button(something I didn’t originally do or understand was necessary).  You also need to regenerate the word list before you can get the keyword list.  That is really important as you move through the tutorial since otherwise it will not generate.  This section needs the most work for clarity.  

>For those interested in the statistical details, see the section on keyness on p7 of Laurence Anthony’s readme file ().

Remove.

**Comment by fredgibbs** [comment]
review incorporated into final version 9e2ebce..c4285f9
