### ISSUE TITLE
Membership History

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/jekyll#843]
Realized with Jeri leaving that our membership history is out of date. I can take care of this pretty easily, but not sure when to do so. Should I go ahead and fix, or do we want to wait until they've phased out of editing their final lessons (and thus properly and completely out)?

<img width="597" alt="screen shot 2018-05-15 at 5 28 55 pm" src="https://user-images.githubusercontent.com/2334220/40084551-7b5f0f32-5865-11e8-8ce9-fc63ba5fbb0e.png">

The people to modify:

- [x] Ian
- [x] Jeri
- [x] Anna-Maria

**Comment by acrymble** [comment]
Can you wait until I have managed to close #826 which involves moving almost all English pages? That's currently waiting on #830 pull request which is awaiting a review.

**Comment by walshbr** [comment]
Yep!

**Comment by acrymble** [comment]
Amanda is still part of the team. She is our ombudsperson.

**Comment by walshbr** [comment]
Modified accordingly in the to do's above

**Comment by acrymble** [comment]
You can do this now. That pull request is closed.

**Comment by acrymble** [comment]
@amsichani maybe you'd like to update this?

**Comment by walshbr** [comment]
Good point! Given the good news from @amsichani circulating on Twitter I've added her to the list.

**Comment by walshbr** [comment]
Closed in #861
