### ISSUE TITLE
Make Tech Install Instructions More Visible

### ISSUE THREAD

**Issue by M0nica** [programminghistorian/jekyll#847]
I attempted to add instructions to running site locally with this PR [https://github.com/programminghistorian/jekyll/pull/844](https://github.com/programminghistorian/jekyll/pull/844) since technical instructions weren't explicitly provided in the README. However, I now see that there is a guide in the Wiki on making technical contributions [https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions](https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions).

Can I update the README to link to the current guide to making technical contributions and/or update the [contribute page](https://programminghistorian.org/contribute) to include a description and link to the wiki article on making technical contributions? Currently, the contribute page seems to focus on editorial contributions and reporting issues and the README doesn't link to the Wiki.

Goal: Update the site and/or readme to make the current wiki on getting started with technical instructions more visible for first-time contributors.

**Comment by acrymble** [comment]
Hi @M0nica thanks for opening this. At the minute we put things on the Wiki that are ONLY in English. All other material is subject to translation. Maybe the easiest solution is adding a "Technical Contributions" link to the /Contribute menu, and then continue to add to it on the Wiki?

I definitely agree with you that the README should be updated to make the Wiki content more visible.

**Comment by M0nica** [comment]
@acrymble So are you saying that it's okay for the contribute menu _only_ on the English version of the site to have a link to the technical contributions wiki?  <img width="1351" alt="screen shot 2018-05-17 at 9 28 18 pm" src="https://user-images.githubusercontent.com/6998954/40211554-45c76cb0-5a19-11e8-97df-10ca90ce209b.png">

**Comment by acrymble** [comment]
We have an editorial call in a few days. I've added this to our agenda in case anyone on the team wants to comment before we make changes. I think you've rightly pointed out that our Wiki and the information on it could be much more visible.

**Comment by acrymble** [comment]
As a start I've updated the Wiki to make its purpose and contents clearer.

@mdlincoln there are a number of pages I've put in a "up for Deprecation" list on the wiki front page. https://github.com/programminghistorian/jekyll/wiki

A few of them are marked "deprecated". But can we just delete them?

**Comment by acrymble** [comment]
Ok, for our call, to make this super clear:

1) Are we happy to add "Technical Contributions" to our /contribute page and menu (I see no reason not to)
2) However, since it is on the Wiki and only available in English, is the Spanish / French team happy with the link pointing to the English wiki page. And if so, should the link say (English only) on the menu?
3) if the answer to 1 is yes, and 2 is no, are our other teams willing to translate that page?

**Comment by arojascastro** [comment]
We can translate them, it is not a big problem :)

**Comment by acrymble** [comment]
Ok maybe this is easier than I thought then. @mdlincoln is the Technical Contributions page complete and up to date and viable for translation, or should we revisit it first?

**Comment by arojascastro** [comment]
Let us know when you have a final version and one of us can start translating.

**Comment by acrymble** [comment]
Ok, since I've been assigned this task, I hereby declare this a "Policy" issue and request that all team members edit this English page on the Wiki https://github.com/programminghistorian/jekyll/wiki/Making-Technical-Contributions by no later than 10 June 2018, at which time I will make it a page on the website and request translation.

@jenniferisasi you've been doing pull requests lately and said you needed to practice. Can you please try the instructions out and help us identify any areas that need more detail?

**Comment by drjwbaker** [comment]
Checked and happy. If someone else has a qualm with the first person language I'm happy to support that change, but disinclined to edit without a wider sense that it needs it :)

**Comment by jenniferisasi** [comment]
Hi @acrymble and all, 
I read the instructions and I think they are pretty clear, can't see any issue with them.

**Comment by mdlincoln** [comment]
Decided on 2018-05-31 that we don't need to translate & publish this wiki page. However, we strongly encourage our editors to please look at it and try it out, so that we can edit and add more things as needed!

**Comment by acrymble** [comment]
@mdlincoln I thought we still intended to put a link on the "Contribute" menu for this?

**Comment by mdlincoln** [comment]
@acrymble ah you're right - sorry, I thought that'd been done already. I'll do a PR
