### ISSUE TITLE
Deleting branches

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#848]
This is not urgent neither important, but I think we should try to delete some Github branches that are not longer needed in both repositories and try to re-use others for recurring tasks.

Here are some screenshots:

![branches_2](https://user-images.githubusercontent.com/7340111/40170587-1173c922-59c9-11e8-99b3-81276c299330.png)
![branches_1](https://user-images.githubusercontent.com/7340111/40170650-41af2c1c-59c9-11e8-985e-c25da23ae9e4.png)

(This is  my OCD talking).

**Comment by mdlincoln** [comment]
Yes, we should be deleting branches once they've been merged from PRs. Note, though, that branches aren't meant to be re-used. 

Make one, do the PR, and then delete it.

What would also help is if people make informative branch names, commit messages, and PR descriptions.

**Comment by arojascastro** [comment]
Ah, good to know, I thought it was a good practice, but yes, it makes sense to delete after accepting the PR and not reusing it anymore. 

I also agree with the informative names of the branches. I added this to the agenda so we can discuss in our meeting and maybe clarify in the wiki (it it is not already there).

**Comment by acrymble** [comment]
Is this just a matter of deleting old branches? If they were mistakenly left open I would think you could just delete them? I have a couple related to active pull requests or tickets.

**Comment by mdlincoln** [comment]
I've cleaned out the stale ones, and emphasized in the wiki that merged branches should be deleted. The instructions already state that it's important to put informative commit messages, but I will reinforce this during the call.
