### ISSUE TITLE
French sticker logo

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#850]
for comment. I tried a cedilla accent but it didn't work. Looked hindi.
![programminghistorianfrgreen](https://user-images.githubusercontent.com/646647/40268331-57064a32-5b63-11e8-95bc-e4f5035c57dc.jpg)

**Comment by drjwbaker** [comment]
Does an acute accent or circumflex work? (in the same way you have the tilde on the ES sticker)

**Comment by acrymble** [comment]
attempt with all 5 accents.
![programminghistorianfrgreen2](https://user-images.githubusercontent.com/646647/40268751-6db8af92-5b6b-11e8-8d71-10cfe39364cc.jpg)

**Comment by drjwbaker** [comment]
I kinda like it.

**Comment by drjwbaker** [comment]
Though I guess our FR team should have a say :)

**Comment by grandjeanmartin** [comment]
Hi! @drjwbaker is referring to the ES logo, is it available somewhere for comparison? Not sure putting an accent will be understandable for the French speakers (as there's no accent in "l'historien programmeur"). Same for the "le", btw, if the abbreviation/name stays in english?

**Comment by acrymble** [comment]
@grandjeanmartin the Spanish one is here: https://github.com/programminghistorian/jekyll/blob/gh-pages/_promo/programmingHistorianESBlue.png

**Comment by drjwbaker** [comment]
@grandjeanmartin Thanks for joining in! I'm guessing the ~ above ES on the Spanish sticker is intended to a) be playful and b) signal something Spanish language. Something similar for the French sticker is what we'd be looking for (so it may be linguistically inaccurate, but it shouldn't be incongruous)

**Comment by PonteIneptique** [comment]
Hi there !

While I am not bought by the accent (though it mimics the Spanish logo and it makes sense to copy it), I find the "LE PH" much more problematic, as it is not gender neutral, and the only way to make it would be to use "LES" which is also Spanish if my basics serve me well ?

**Comment by acrymble** [comment]
Ok. Some clear resistance to this idea. Which is fine. We're looking for a solution that doesn't equate "French" with "France". So if anyone has symbolic suggestions that would be great!

**Comment by inactinique** [comment]
Hi all. And why not keeping [PH] and under it writing "francophone". The word francophone would take the same width as [PH] which means a smaller font size.
It's not symbolic but may work.
Best, 
Frédéric

**Comment by drjwbaker** [comment]
@inactinique I like that.

**Comment by acrymble** [comment]
![programminghistorianfrgreen3](https://user-images.githubusercontent.com/646647/40539398-8f2350f6-600c-11e8-90c3-20d9bbce8e5b.jpg)

**Comment by spapastamkou** [comment]
1) I like this last "francophone" version. 2) Another idea was to maybe add something like "#jesuis" (not gendered, contemporary, easily understood). But "PH francophone" is definitely better in my view.

**Comment by inactinique** [comment]
Another solution would be to use the french guillemets instead of the brackets.

**Comment by spapastamkou** [comment]
That would be certainly exact but more subtle. "Francophone" tells it like it is, no thing to search or risk to confuse. And fits graphically as well.

**Comment by acrymble** [comment]
![programminghistorianfrgreen4](https://user-images.githubusercontent.com/646647/40540347-bf42822c-600f-11e8-8c9d-bdfc95de10cc.jpg)

**Comment by amsichani** [comment]
I like more the francophone one. Its clear and it works graphically. Just wondering if we could find something that is a bit more 'playful' and less eloquent/formal, as we 've managed well to do with the ES logo, IMHO

**Comment by arojascastro** [comment]
If I am allowed to say my opinion, I think *francophone* works better, because in Spanish we also use *french* quotation marks... although we call them *latin*...

**Comment by inactinique** [comment]
Thanks for the remark Antonio, that reminds us also that French tend to be culturally imperialistic in the latin world ;) I think the Francophone logo works very well, though not really fun.

**Comment by grandjeanmartin** [comment]
The "francophone" version looks good to me.

**Comment by acrymble** [comment]
just one thought, if we go with the "francophone" logo then people will probably call that version of the project "Programming Historian francophone".

**Comment by inactinique** [comment]
That might not be a problem, as we still don't know how to call it in a gender balanced way.

**Comment by acrymble** [comment]
I think I would go with the latin quotation marks personally, since virgulilla is not exclusive to Spanish either, but is a clever cultural hint. But it looks like francophone is the most popular option, so I'll put that in our /_promo folder for safe storage. We aren't planning on ordering any stickers at the minute (unless someone wants to donate some money - £140 or so) so we can always revisit this in future if someone has a new idea.

**Comment by aurelberra** [comment]
Sorry to be late to the party… First of all, it's absolutely great to see that a francophone PH is getting off the ground!

In case this discussion is re-opened at some point, I'd like to say that the idea of a single symbol to distinguish language-based versions is really nice. In my opinion, adding a whole word, "francophone", breaks the unity with the Spanish version, makes for a heavier logo and looks a bit redundant as the URL already contains "fr".

I feel the circumflex accent on its own could meaningfully play the same role for French as the tilde for Spanish. (Unless, maybe, you are planning to introduce tutorials in Romanian soon.) It would be especially elegant with a serif font for the diacritic.

My two *centimes*, with the accompanying proofs of concept (not quite the same font, but same colours).

![screen shot 2018-05-29 at 22 38 35](https://user-images.githubusercontent.com/1230441/40684209-175eccf2-6391-11e8-9357-0e820d82cb78.png)

![screen shot 2018-05-29 at 22 26 15](https://user-images.githubusercontent.com/1230441/40684210-17766768-6391-11e8-8b9b-435e56a4e42f.png)

**Comment by spapastamkou** [comment]
thank you Aurélien! More details to come soon:)

**Comment by acrymble** [comment]
At the request of @spapastamkou and on @aurelberra 's suggestion, here's also the circumflex option. The font name is "Crete Round" and is downloadable for free if anyone wants to try others. This was mentioned in #879 
![programminghistorianfrgreen5](https://user-images.githubusercontent.com/646647/40855639-f4d4bcbc-65cc-11e8-9084-14455824a956.jpg)

**Comment by mdlincoln** [comment]
FYI, I have standardized URL and non-URL versions of the logos as SVG files and moved them to `/images/logos` so that they can be referenced across the site.
