### ISSUE TITLE
Internal links should use relative paths only

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#854]
I'd like to update our guidelines to make it clear that internal links (aka pointing from one lesson to another on PH) should use relative links only. For example, instead of:

```
https://programminghistorian.org/en/lessons/creating-apis-with-python-and-flask
```
we should instead use
```
/en/lessons/creating-apis-with-python-and-flask
```

This makes any future site changes and page movements much simpler.

I was going to include this in the editor guidelines - do we think it should be in the author guide as well, or is that adding too much for authors?

**Comment by drjwbaker** [comment]
Editors.

**Comment by acrymble** [comment]
Can travis flag that at the pull request stage?

**Comment by mdlincoln** [comment]
I'm still looking for a solution to that @acrymble. There are a handful of occurrences across the site we _do_ in fact want to have full links, such as in suggested citations, markdown examples, etc. If I can figure out a way to exclude errors from those examples, I will certainly add it.

Either way, we'll still want to make sure that the editor guidelines are updated so they would know why Travis is throwing errors for it.
