### ISSUE TITLE
Language-independent landing page

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#855]
Now that all English pages are under the `/en` path except the current `index.html`, we still need to settle on what our lading page at <https://programminghistorian.org> should look like.

One possibility could be showing this intro paragraph in each language on the front page, maybe running as three columns across the screen.

![screenshot-2018-5-20 the programming historian programming historian](https://user-images.githubusercontent.com/4392604/40284130-07ef85da-5c3f-11e8-8188-e4e8ef75ff9d.png)

**Comment by drjwbaker** [comment]
I fear columns would render terribly on mobile.
Rather than repeat three times, is there anyway to randomise which translation of the blurb visitors land on? We can then just put 'English', 'French', & 'Spanish' under the text.

**Comment by acrymble** [comment]
Default to English page unless your language settings are set to EN or FR?

Default to English seems to be quite common for multilingual journals out of Canada: https://www.acadiensis.ca/
https://www.utpjournals.press/loi/cjh

Alternatively we could take this opportunity to re-think what is presented on our homepage. We've had a request to make the site look more like a traditional academic journal to help with cultures of credit. We could open that discussion given this opportunity.

**Comment by drjwbaker** [comment]
Added policy tag because I think this is important. I suggest - per our new guidelines at https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance - a formal deadline for feedback of 1 June.

**Comment by arojascastro** [comment]
I agree with Adam that we should "re-think what is presented on our homepage". 

I am happy with the English page as a default, but in that case it would be good that it is mentioned that is a multilingual project and that visitors may want to access to the Spanish or French version. 

In other words, the landing page should do two functions:

- introduce the english version to the english reader 
- help the spanish or french reader to get access to those versions

My 5 cents.

**Comment by walshbr** [comment]
In that vein, what about defaulting to English, with translated text just below that also directs visitors as to how to navigate to the appropriate translation appropriate for them?

**Comment by mdlincoln** [comment]
From 2018-05-31 call, we're generally agreed upon the idea that we want to have the front page show the brief english description of what readers will find in the site, and also make sure alternate language sides of the Programming Historian are prominently shown in the body of the page (aka user won't have to scroll or open a sidebar to see the links on the front page alone)

I'll mock up a possible design so that we have a concrete thing for feedback.

**Comment by mdlincoln** [comment]
(Fyi I'm removing the policy tag now because we seem generally agreed on the goals of the front page. I'll keep this ticket open for further comments on the implementation of that goal)

**Comment by drjwbaker** [comment]
> (Fyi I'm removing the policy tag now because we seem generally agreed on the goals of the front page. I'll keep this ticket open for further comments on the implementation of that goal)

In response to this very sensible action, I've updated https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance to say we remove the policy tag once we have consensus.

**Comment by mdlincoln** [comment]
Note that we explored one possibility here: https://github.com/programminghistorian/jekyll/pull/914

**Comment by mdlincoln** [comment]
This has been launched.
