### ISSUE TITLE
Wikipedia article

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#857]
Just a note to say that I've added a Wikipedia article for the project, which is currently under review: https://en.wikipedia.org/wiki/Draft:Programming_Historian

I just copied and pasted another journal and changed the info.

**Comment by drjwbaker** [comment]
If we fail to pass the notability threshold, we can chuck the stats at them :)

**Comment by acrymble** [comment]
I'm pretty sure you can update it to make it more notable if you've got ideas.

**Comment by drjwbaker** [comment]
Okay, well keep us posted on whether the article is published.

**Comment by acrymble** [comment]
I don't think there's an explicit action with this ticket. I just wanted to record that I'd done it.

I will close this now and let everyone know when it has been approved or rejected.

**Comment by acrymble** [comment]
My attempt at getting us a Wikipedia article keeps getting rejected for lack of "reliable" sources.

https://en.wikipedia.org/wiki/Draft:Programming_Historian

Could I ask that a few people try to add a couple of sentences and good references so that we can get this accepted? I note that we've already got a fuller entry than some of the really quite substantial journals in the field, but the bar has been set high for us for some reason.

**Comment by mariajoafana** [comment]
I just added one reference

**Comment by walshbr** [comment]
Are there any Spanish language sources or any reviews of the Spanish PH that we could incorporate?

**Comment by acrymble** [comment]
@walshbr no there aren't any reviews in Spanish yet, but I think we should solicit one. I will make a ticket

**Comment by acrymble** [comment]
Thanks @mariajoafana it has now been accepted:

https://en.wikipedia.org/wiki/Programming_Historian
