### ISSUE TITLE
Update or remove "News" page?

### ISSUE THREAD

**Issue by nabsiddiqui** [programminghistorian/jekyll#86]
The "News" page hasn't been updated in a while and doesn't reflect the changes on the website.  For a while, before agreeing to help contribute, I did not know the site was still active because I only checked the news page.  

It would be beneficial to update it when new lessons are posted and perhaps provide an RSS feed?

**Comment by acrymble** [comment]
Good to know. Does anyone want to devise a workflow for keeping this fresh?

**Comment by williamjturkel** [comment]
During one of our recent Skype calls, it was suggested that we might also update the News more frequently with posts about pedagogy or about how to use the site: "So You Want to Get Started With Visualization". First work through this, then try that, then you might do X, ...

**Comment by wcaleb** [comment]
I wonder if the name of the page is misleading. Should we instead call it "Blog"?

**Comment by nabsiddiqui** [comment]
I think calling it "blog" makes more sense.  There currently isn't a way to figure out when new lessons are posted though.

**Comment by acrymble** [comment]
I think @miriamposner was behind the name change to News, so perhaps worth conferring with her.

**Comment by miriamposner** [comment]
Was I? "Blog" seems fine to me.

**Comment by wcaleb** [comment]
Thanks for the feedback. Add RSS feed and changed title to blog.
