### ISSUE TITLE
Layout issue - 'Uses of the Programming Historian' blogpost

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#862]
I think there is a layout issue / broken link at Cheryl LaGuardia's ref on https://programminghistorian.org/posts/Uses-Of-The-Programming-Historian related to #852 - probably @acrymble you might want to have a look on it! Fab resource for PH visibility / impact!

**Comment by acrymble** [comment]
Thanks, you're right. If you're happy to fix it, that would be great.

**Comment by amsichani** [comment]
done #863
