### ISSUE TITLE
Language sub-team communication channels

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#871]
This was raised in an email exchange with the editors and is related to #849 - "Reduce bus factor for service integrations".

Do the various sub-teams have methods of communicating that do not involve all members of the PH Editorial Board? If so, can we please document these on the Wiki under "Service Integrations" so we know what they are should we need to pass them on to another administrator in future?

The English team does not have any at the moment. We use the Google Group email address, Skype meetings, and Github only.

Spanish Team?
French Team?

**Comment by acrymble** [comment]
@arojascastro says the Spanish team does not have any such channels.

@spapastamkou can you please list the French ones if there are any?

**Comment by spapastamkou** [comment]
We created this list as working group list: proghist-fr@groupes.renater.fr
I suggest that we add it in the wiki only if it proves to be sustainable and in this case also add at least one member of the global DH as admin. 
If ok, then set a span of time to decide whether sustainable/useful.

**Comment by acrymble** [comment]
Is there anything you feel you can't use github for? One disadvantage of using a different email list is that we can't help you because the rest of us don't know what conversations you are having.

**Comment by mariajoafana** [comment]
The Spanish team communicates via email every once in a while. We don't use a group list, but we  send email among all members of the tram us to discuss some issues before the Skype meetings. If we need support from the rest of the team we bring the issue to GitHub
