### ISSUE TITLE
"Escritura sostenible" is not displaying review ticket but it is in the yaml block

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#874]
I just noticed [this](https://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown):
![escritura](https://user-images.githubusercontent.com/7340111/40628008-a4e29524-62c2-11e8-8bb0-e692dee5e7bf.png)

But the metadata block seems ok to me: https://github.com/programminghistorian/jekyll/blob/gh-pages/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown.md

Any idea what is going on? @mdlincoln

**Comment by mdlincoln** [comment]
Ah, it's because this lesson has no reviewers, but it does have translation reviewers. I can fix this.
