### ISSUE TITLE
Expectation of email notifications for @ messages (editorial board)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#877]
I'd like to suggest that we strongly request that all members of the editorial team set up their github so that they receive any tickets in which their name has be @ to their email, and that they acknowledge those emails in a reasonable timeframe.

I suspect we've got a few people who have this turned off, and it makes it difficult to close certain issues.

**Comment by acrymble** [comment]
Check off your name if you are receiving emails when someone @ mentions you in a post please.

- [x] @acrymble 
- [x] @alsalin 
- [x] @amsichani 
- [x] @drjwbaker 
- [x] @JMParr 
- [x] @jenniferisasi 
- [x] @jamotilla 
- [x] @mariajoafana 
- [x] @arojascastro 
- [x] @vgayolrs 
- [x] @mdlincoln  
- [x] @walshbr 
- [x] @spapastamkou 
- [x] @mpuren

**Comment by mdlincoln** [comment]
Related to this - I'm never quite sure to ping specific members of the Spanish teacm when we need a review of a translation (I've noticed @arojascastro has been taking on the brunt of this work and it feels rather uenven)

GitHub allows us to establish sub-teams so that if you want to ping the whole team, you can now call @programminghistorian/spanish-team . I will set up parallel ones for the english and french team (such as it is right now) just to help out with this kind of notification system.

**Comment by mdlincoln** [comment]
For what it's worth, these team pages also have a discussion functionality that could replace needing to use google groups - personally I'd _love_ to only monitor github and not have to look for emails too... but I think I'm probably an outlier as far as working habits of this group goes.

**Comment by acrymble** [comment]
I think we need to find out why @vgayolrs @mariajoafana and @jamotilla have turned off their notifications. I'm sure they have good reasons why this system isn't working for them, but we'll need to find a workaround so that we can communicate with everyone effectively

**Comment by arojascastro** [comment]
I think they should simply turn them on. Victor was or is on sabbatical though.

**Comment by vgayolrs** [comment]
Hi, I am receiving all emails. I'm back starting this weekend.

**Comment by mariajoafana** [comment]
Actually, my notifications are on but they are sent to my old utexas email to which I don't have access now. I have tried a few times to change my email in Github but it when I try to verify the new one I never get the email to do so. Keeping up with the tickets in Github is difficult without getting the notifications.

**Comment by mariajoafana** [comment]
I just found a way around it, and I'm good now to receive the notifications

**Comment by acrymble** [comment]
Can someone on the Spanish team reach out and ask @jamotilla? I see him contribute to the editorial process all the time, but I'm not sure he's set up to receive these messages.

**Comment by jamotilla** [comment]
Hi Adam, i’ll check the settings of my email account.

**Comment by jamotilla** [comment]
it´s done @acrymble , i´m receiving the notifications

**Comment by acrymble** [comment]
Thanks @jamotilla.

I've also added @mpuren to the list. Can you please confirm if you're receiving messages to your email inbox before I close this ticket?

**Comment by acrymble** [comment]
@mpuren can you please let us know if your github is set up to receive emails when someone messages you like this? If I don't hear from you, I'll assume not and get in touch via email so we can help you do so.

**Comment by acrymble** [comment]
I've emailed @mpuren to see if she needs help with her settings on this. Then I can close.

**Comment by mpuren** [comment]
@acrymble I confirme that I receive the Github notifications
