### ISSUE TITLE
Getting a budget line for PH

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#878]
We need a budget line somewhere so that we can manage money we received (eg, from individual sponsors via Patreon or other mechanisms we might look into per #724).

**Comment by drjwbaker** [comment]
This is coming along. Hoping to update mid-August.

**Comment by drjwbaker** [comment]
Belated update: I have a meeting next week (TBC) to discuss implementation.

**Comment by drjwbaker** [comment]
No update since team email 22 October.

**Comment by acrymble** [comment]
If it will help things along if I show up wearing a suit, let me know. We can plan a day.

**Comment by drjwbaker** [comment]
Thanks Adam. We now have an added complication in that the librarian I've been working with on this (who has been working super hard on our behalf!) is leaving and I need to establish who'll she'll be handing this over to to keep pressing. More soon.

**Comment by acrymble** [comment]
Do we need to start exploring other options?

**Comment by drjwbaker** [comment]
Maybe..

**Comment by acrymble** [comment]
Ok. I'll start asking around. I feel like conceptually this is going to make the most sense to American universities and their already existing channels for receiving and processing donations. That's not quite as embedded in British culture. Are any of our American-based team members thinking this might be something your institution could provide (infrastructure) for us?

**Comment by drjwbaker** [comment]
:cough: Scholar's Lab :cough: :smile:

**Comment by acrymble** [comment]
The Digital Pedagogy Lab in the US operates on donations only. Does anyone know any of them and can find out who manages their donations? Is it a university? http://www.digitalpedagogylab.com/support/

**Comment by drjwbaker** [comment]
Looks like they have a setup exactly like the one I was exploring: running donations through a university alumni office as alumni offices are the parts of universities best setup to handle the logistics and legalities of donations.

**Comment by acrymble** [comment]
Thanks for checking @drjwbaker. This is really an area that Americans are better at. But I wonder if the IHR or some other DH centre in the UK would be willing to "host" our relationship with an alumni office at their university? Should I ask around?

**Comment by drjwbaker** [comment]
It doesn't have to be in the UK (though depending on how *things* pan out, it could still be where I am). And perhaps - looping into discussions of getting institutional credit for our work - we should start with our own institutions?

**Comment by mdlincoln** [comment]
I'll ping folks at my institution and see if there's a way to do this.

**Comment by acrymble** [comment]
I spoke to a colleague who used a crowdfunding site for a project, and she reports that the money went directly into her bank account and was used to pay for things directly.

**Comment by drjwbaker** [comment]
Okay, but there are tax and money laundering implications of doing this. If this person is UK-based, I hope they are doing the relevant paperwork..

**Comment by acrymble** [comment]
Maybe it's time we look into setting up as a charity to avoid the tax problems? https://www.gov.uk/setting-up-charity

**Comment by drjwbaker** [comment]
I was thinking the same recently. I'm willing to go through the eligibility check process and report back.

**Comment by acrymble** [comment]
As we're exploring a charity option instead, should we close this avenue, which is university-focused?

**Comment by drjwbaker** [comment]
Agreed.

**Comment by drjwbaker** [comment]
Closed as superseded by https://github.com/programminghistorian/jekyll/issues/1301
