### ISSUE TITLE
Title for the FR version 

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#879]
@spapastamkou proposed two (2) alternatives for the title of the French version . 

1. the Programming Historian francophone
3. the Programming Historian en français

please note that the title shouldn't dictate the logo  of the site and vice versa.

**Comment by acrymble** [comment]
I prefer 2 personally. It's in line with the Spanish version.

**Comment by spapastamkou** [comment]
I prefer The PH en français for the same reasons and bcz it could be in lines with future editions in other languages.
But in this case, the sticker « PH francophone » could perhaps create confusion as for the title. In this case prefer a sticker with a symbol instead of text?

**Comment by mariajoafana** [comment]
I agree with @acrymble

**Comment by mpuren** [comment]
I prefer the option 2 for the title : "the PH en français", because it's in line with the Spanish version, and with potential future editions in other languages.

**Comment by acrymble** [comment]
Looks like we're agreed?

I've updated this on the Wiki on a new "brand guidelines" page (how very corporate of me).

https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines

**Comment by mdlincoln** [comment]
I'll use "The Programming Historian en français" in the mockup for our new title page, which is coming soon!
