### ISSUE TITLE
Solicit an academic review of Spanish PH

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#884]
Suggested by @walshbr. We have 2 reviews of the English project, listed on the /research page. Since we've now got over 30 Spanish lessons, it seems like a good time to approach a Spanish journal to do a review. Can anyone suggest an appropriate publication(s) to approach? I approached 4 last time and we ended up with 2 reviews, so many suggestions welcome.

**Comment by arojascastro** [comment]
This could work for the whole project: https://dhcommons.org/

Some Spanish journals:

- Revista Caracteres: http://revistacaracteres.net/
- Revista de Humanidades Digitales: http://revistas.uned.es/index.php/RHD/index

I'll keep thinking.

**Comment by acrymble** [comment]
what are the "history" journals in Spanish?

**Comment by arojascastro** [comment]
- Culture and History (it's a Spanish journal despite its title): http://cultureandhistory.revistas.csic.es/index.php/cultureandhistory
- Revista de Historiografía: https://e-revistas.uc3m.es/index.php/REVHISTO/index

I have peer reviewed some articles about digital history for both of them, so I think they would welcome reviews.

**Comment by acrymble** [comment]
My Spanish is not good, but it looks like only Revista de Historiografía does reviews.

**Comment by mariajoafana** [comment]
In Colombia I can recommend Fronteras de la Historia, which is the journal of the Colombian Institute of Anthropology and History, they receive reviews: http://www.icanh.gov.co/?idcategoria=1252

In Mexico there is Estudios de Historias NovoHispana: http://www.historicas.unam.mx/publicaciones/revistas/novohispana/novohispana.html I guess that @vgayolrs and @jamotilla can give us a better sense of what journals to approach there.

**Comment by jamotilla** [comment]
In mexico we have Relaciones Estudios de Historia y Sociedad which is a very prestigious journal and @vgayolrs is the editor. We also have Historia Mexicana from El Colegio de México. There are another journals like Revista del Colegio de San Luis

**Comment by vgayolrs** [comment]
let me think about that

**Comment by vgayolrs** [comment]
### Spanish
En Humanidades hay cerca de 406 revistas académicas digitales en español y portugués en línea que utilizan recursos digitales para su publicación. Habría que descartar muchas para llegar a las que se dedican a historia. Pero, generalmente en nuestro medio, las cuestiones digitales están todavía más en el ámbito de las Humanidades Digitales que en el de la Historia Digital (que es muy distinto). Además, habría que buscar revistas que se interesen en publicar cosas sobre historia digital.

En una búsqueda en este universo, topé con 523 resultados de artículos que tratan sobre historia digital. Otra vez, es cuestión de hacer una criba.

Sin embargo, mientras eso sucede, podríamos por lo menos pensar en alguien que pudiese interesarse en escribir una reseña sobre PH-es y mientras tanto se vería dónde publicarla. Hoy he contactado a Isabel Galina, presidenta de la [Red de Humanidades Digitales](http://www.humanidadesdigitales.net/) en cuyo blog han aparecido varias cosas sobre PH-es, para proponerle escribir una reseña. Además, es una de las organizadoras de DH2018... Espero que acepte.

Por otro lado, como saben algunos, soy editor de [REHS](http://www.revistarelaciones.com/index.php/relaciones), que es una revista de historia y antropología. Apenas hace poco publiqué un ensayo crítico de @jairomelo sobre [nuestro tema](http://www.revistarelaciones.com/index.php/relaciones/article/view/251) y en este número que empieza a publicarse mañana un texto de Isabel Galina (coincidente con DH2018). Todo para decir que se vería muy mal que pidiera una reseña para publicar de un proyecto del que formo parte como miembro del equipo editorial (nuestro código de ética). Pero sí, alguna opción creo que tendremos.

---

### English
In Humanities there are about 406 digital academic journals in Spanish and Portuguese online that use digital resources for publication. It would be necessary to discard many to reach those dedicated to history. But, generally in our environment, digital issues are still more in the Digital Humanities field than in Digital History (which is very different). In addition, we should look for journals that are interested in publishing things about digital history.

In a search of this universe, I came across 523 results of articles that deal with digital history. Again, it's a matter of discarting.

However, while that happens, we could at least think of someone who might be interested in writing a review about PH-es and, in the meantime, we can find where to publish it. Today I contacted Isabel Galina, president of the [Digital Humanities Network](http://www.humanidadesdigitales.net/) in whose blog several things about PH have appeared, to propose to write a review. Also, she is one of the organizers of DH2018 ... I hope she accepts.

On the other hand, as some of you know, I am the editor of [REHS](http://www.revistarelaciones.com/index.php/relaciones), which is a History and Anthropology journal. Just recently I published a critical essay by @jairomelo about [our subject](http://www.revistarelaciones.com/index.php/relaciones/article/view/251) and, in this issue that begins to be published tomorrow, a text of Isabel Galina (coincident with DH2018). All to say that it would be very wrong to ask for a review to publish a project of which I am a member of the editorial team (our code of ethics). But yes, some option I think we will have.

**Comment by acrymble** [comment]
It really needs to be a journal that does "Book Reviews", because they'll need someone in charge of organizing these. We should contact the book review editor, not potential reviewers.

**Comment by vgayolrs** [comment]
Ok @acrymble . I'm going to contact Ernesto Priani and Gimena del Río who are the editors of [Revista de Humanidades Digitales](http://revistas.uned.es/index.php/RHD/index). They have a call of papers that include reviews. They do not look for the reviewers but they call freely (it is the common practice in the world of academic journals in Spanish, most of them do not have "book review editors" as in English academic journals). I can also contact Laurette Godinas or César Manrique, editors of a new journal, [Bibliographica](https://bibliographica.iib.unam.mx/index.php/RB/about/submissions#authorGuidelines). In the case of reviews, it is the same as in the previous one. Both journals are interested in HD issues.
On the other hand, I do not think that [Estudios de Historia Novohispana](www.historicas.unam.mx/publicaciones/revistas/novohispana/novohispana.html), which @mariajoafana  mentioned, are interested in reviewing PH, but I'll speak today with the editor who is my close friend.
Give me this week to contact more editors. But I still think that we have to contact also potential reviewers, for what I say before.

**Comment by acrymble** [comment]
Ok thanks, I didn't realize it was different in Spanish journals.

**Comment by acrymble** [comment]
@vgayolrs did you want to do this still, or should we close this issue? I didn't realise this was unusual in Spanish scholarship.

**Comment by acrymble** [comment]
I'm going to close this for now. We can reopen in future if someone has time to pursue it.
