### ISSUE TITLE
June Editorial Meeting Agenda - TBC

### ISSUE THREAD

**Issue by amsichani** [programminghistorian/jekyll#886]
Time is 5PM British, 12PM Eastern US, 9AM Pacific US.

Working agenda follows. Please add by commenting or editing this comment directly.

- [ ] #721 Current Research Projects or Submissions Pending about the Programming Historian.
- [ ] #849 Reduce bus factor for service integrations.

**Comment by acrymble** [comment]
I believe this meeting has been postponed until July
