### ISSUE TITLE
Minor suggestions in the lesson about plain text using Pandoc and Markdown

### ISSUE THREAD

**Issue by ivanhercaz** [programminghistorian/jekyll#889]
Hi everyone,
I read "Escritura sostenible en texto plano usando Pandoc y Markdown", translated by @vgayolrs, and I would like to give you some minor suggestions:

  - Gitit link is broken, so there are two options:
    1. Change by its [last snapshot](https://web.archive.org/web/20171020184351/http://gitit.net:80/) in the Internet Archive.
    2. Or change by [its GitHub repository url](https://github.com/jgm/gitit). I prefer this option because the first is like a mirror site of the [John MacFarlane website](http://johnmacfarlane.net/).
  - In the section "Trabajar con bibliografías" there is a "`# Bibliography` al final del documento". I think this "Bibliography" may be change by "Bibliografía", because there isn't a special rule that specify the necessity to be in English.

If I find something more, I will report it!

I take the opportunity to thank you the work you do with this awesome project! I'm looking forward to contributing some lesson.

Regards,
Iván

**Comment by arojascastro** [comment]
¡Muchas gracias! Estudiaremos los cambios que propones.

**Comment by ivanhercaz** [comment]
De nada, @arojascastro. Ya me pondré en contacto contigo para proponerte alguna de las lecciones que tengo en mente. De momento me mantengo a la espera.

**Comment by mariajoafana** [comment]
Muchas gracias Ivan. 
@vgayolrs Nos llegan estas sugerencias para corregir en este tutorial que traduciste. ¿Cómo las ves?

**Comment by vgayolrs** [comment]
@ivanhercaz , ¡mil gracias por las observaciones! @arojascastro , si no tienes inconveniente me dedico a ello el finde (que ahora estoy liado)

**Comment by arojascastro** [comment]
Gracias @ivanhercaz. Ojalá nos envíes una propuesta. 

Me parece bien arreglar el enlace y traducir `Bibliographie`. Ahora bien, revisando la lección me pregunto si no se podría además traducir los metadatos:

```
 @article{fyfe_digital_2011,
        title = {Digital Pedagogy Unplugged},
        volume = {5},
        url = {http://digitalhumanities.org/dhq/vol/5/3/000106/000106.html},
        number = {3},
        urldate = {2013-09-28},
        author = {Fyfe, Paul},
        year = {2011},
        file = {fyfe_digital_pedagogy_unplugged_2011.pdf}
    }
```

```
---
title: Flujo de trabajo en texto plano
author: Gabriel García
date: 20 de enero de 2014
bibliography: proyecto.bib
csl: mla.csl
---
```

(Hay otros casos)

Es decir, en lugar de `title` poner `título`, en lugar de `author` poner `autor`, etc.

**Comment by ivanhercaz** [comment]
@vgayolrs, de nada :smile: Cualquier otro detalle lo comunicaré. Gracias a ti por traducir el artículo.

> Me parece bien arreglar el enlace y traducir `Bibliographie`. Ahora bien, revisando la lección me pregunto si no se podría además traducir los metadatos:

Traducir los metadatos no es posible, o al menos hasta donde yo tengo conocimiento. Para ello habría que modificar la plantilla latex encargada de la transformación del texto markdown a documento PDF, cambiando los campos `title` por `título`, y así con cada uno de ellos.

Lo que sí se puede hacer es añadir la variable `lang`en los metadatos, con la clave `es`, de manera que si hay un `abstract`, este se traducirá por `resumen`. Y así sucedería también con otros datos.

**Comment by arojascastro** [comment]
Ok, gracias por la aclaración. Quizás podríamos añadir esta información en forma de destacado o nota del traductor o incluso en un paréntesis.

**Comment by ivanhercaz** [comment]
@arojascastro, y leyendo más sobre las [variables de idiomas](http://pandoc.org/MANUAL.html#language-variables), sigo creyendo que ninguna puede hacer que se entiendan los metadatos en otro idioma que no sea el inglés, sino que para ello habría que adaptar una plantilla latex.

> Quizás podríamos añadir esta información en forma de destacado o nota del traductor.

No es mala idea la verdad.

**Comment by ivanhercaz** [comment]
> Gracias @ivanhercaz. Ojalá nos envíes una propuesta.

De nada @arojascastro, me apasiona el conocimiento colaborativo, así que es un placer. Entre las ideas que tengo de propuestas que quiero enviar, una tiene que ver con Pandoc y Markdown. A ver si le doy forma y, si la veo viable, contactaré contigo.

**Comment by ivanhercaz** [comment]
> Lo que sí se puede hacer es añadir la variable `lang` en los metadatos, con la clave `es`, de manera que si hay un `abstract`, este se traducirá por resumen. Y así sucedería también con otros datos.

Se me olvidaba, otra forma para que los metadatos salgan traducidos (aquellos que contengan texto o un formato diferente en otro idioma) es utilizar `\usepackage[spanish]{babel}` en la variable `header-includes`. Algo así:

```
---
header-includes: |
  \usepackage[spanish]{babel}
---
```
Además, se puede hacer incluso que se añada un bloque de metadatos yaml por defecto. Si quien escribe el artículo lo suele hacer siempre en inglés, puede especificar ese idioma en un `header-includes` de otro archivo y luego ejecutar un comando similar a este:

`pandoc -S ../default.yaml -o salida.pdf --filter pandoc-citeproc entrada.md`

Una de mis ideas de propuesta va por este camino, algunos detalles para favorecer un mejor entorno de escritura en markdown para científicos.

**Comment by vgayolrs** [comment]
@mdlincoln I found the Gitit link problem also in the original lesson, so we should make a decision between the two teams and edit the original lesson and the translation simultaneously.

**Comment by arojascastro** [comment]
Gracias a todos. El cambio ya ha sido realizado.
