### ISSUE TITLE
Missing bio for Cleaning Data lesson authors

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#89]
We don't have bios in the `_data/authors.yml` file for the authors of this lesson:

http://programminghistorian.org/lessons/cleaning-data-with-openrefine

@acrymble

**Comment by acrymble** [comment]
I've alerted them.

**Comment by acrymble** [comment]
Max De Wilde is a PhD student at the Information and Communication Science department of the Université libre de Bruxelles.
Ruben Verborgh is a post-doc researcher at the Multimedia Lab of the Universtiteit Gent.
Seth van Hooland is an associate professor at at the Information and Communication Science department of the Université libre de Bruxelles.

will add to yaml asap.

**Comment by wcaleb** [comment]
Done, @acrymble.
