### ISSUE TITLE
SVG versions of logos

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/jekyll#899]
@acrymble are you able to produce SVG versions of the logos? It will be useful to have that format if we want to experiment with integrating them into the site homepage.

Please email them to me for the moment - I want to experiment a bit more first before committing them into the repo.

**Comment by acrymble** [comment]
I've attempted to do this on a couple of websites and it's turning the background colour black. Does anyone have experience with this?

**Comment by mdlincoln** [comment]
What software did you originally use to make the images?

**Comment by acrymble** [comment]
I did them in GIMP

**Comment by mdlincoln** [comment]
Mind just emailing me the gimp files and I'll look at them?

**Comment by acrymble** [comment]
I'm afraid I haven't kept the gimp files. The versions I've got are the ones on the PH site.

**Comment by acrymble** [comment]
I can remake them if you need. I kept the details on our wiki: https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines

It's just a font on a coloured background, so easy to replicate.

**Comment by acrymble** [comment]
Sorry @mdlincoln I saw you made a mockup. Does that mean we can close this?

**Comment by drjwbaker** [comment]
Where have the non-svg versions of the logos gone? I can only find https://github.com/programminghistorian/jekyll/tree/gh-pages/images/logos (also, note that link to logos at https://github.com/programminghistorian/jekyll/wiki/Brand-Guidelines is broken, note sure where it is intended to go: the svg folder?)

**Comment by drjwbaker** [comment]
Second thoughts, let's just keep svg. And I've fixed the broken wiki link.
