### ISSUE TITLE
Europeana SPARQL endpoint?

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#904]
I'm revising all lessons in order to get data about the resources employed and I bumped into @mdlincoln's beautiful lesson on lod. There is a note here about the Europeana endpoint: https://programminghistorian.org/en/lessons/graph-databases-and-SPARQL#linking-multiple-sparql-endpoints

I think the Endpoint now is available here: http://sparql.europeana.eu/

More info: https://pro.europeana.eu/post/europeana-sparql-endpoint

**Comment by mdlincoln** [comment]
😬 thanks for noting this - I can check if the queries still work (maybe they changed their ontologies 🤢) and update the lesson appropriately. I'll ping the Spanish team to review for the translated version once I'm done.

**Comment by arojascastro** [comment]
I hope they did not. Thank you for pinging us.

**Comment by mdlincoln** [comment]
Problem number 1: they no longer allow remote queries of RDF data aka no `SERVICE` statements... which directly undercuts the whole point of that section. I'm reaching out to them for comment, since the [link they provide for details about that decision is dead](http://sparql.europeana.eu/sparql?help=enable_sponge)

**Comment by mdlincoln** [comment]
I'm also not expecting them to be forthcoming - despite a few waves of interest, Europeana hasn't really committed to LOD like it seemed they had in 2015...

If I don't hear anything back in a week, I'll reword the warning on the lesson to note that their SPARQL endpoint is available but no longer supports the exact query we show in the lesson.

**Comment by arojascastro** [comment]
I think it's a pity. But maybe you can just remove that section about connecting different endpoints.

Note to myself: we did not update the lesson with the alert / warning in the Spanish translation: https://programminghistorian.org/es/lecciones/sparql-datos-abiertos-enlazados#enlazando-m%C3%BAltiples-puntos-de-entrada-sparql
