### ISSUE TITLE
neutral Political Views policy

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#905]
In the past we've had a policy that meant that the Programming Historian remained neutral in all contemporary political matters. Particularly with regards to expressing opinions (from the project, or implying with the support of the project) on elections, electoral candidates, and contemporary international politics. This extends to content appearing in lessons that might be viewed as partisan.

This broadly fits with our international agenda to welcome readers and authors from around the world without judging their cultural values.

I'd like to formalise this on our wiki as a matter of policy so that there is no confusion in future, especially as we continue to internationalise the project. My proposed text is:

The _Programming Historian_ is an international publication and welcomes readers and contributors with a wide range of political, cultural, and religious views. While the members of our editorial board are undoubtedly passionate about a range of issues, the _Programming Historian_ and the Editorial Board remain a-political with regards to party politics, elections, referendums, and matters of international relations.

--

I suppose there are times when we may want to express opinions with regards to ethics of technology, education, or publishing. But I do think we need to agree to leave our own party politics at the door, and especially when speaking or purporting to speak on behalf of the project.

Can I ask for comments on this by the end of July? (I know we have no meeting this month).

**Comment by drjwbaker** [comment]
Out of curiosity, is this motivated by anything in particular or are you seeking to formalise something that was once informally agreed (among previous editors)?

**Comment by acrymble** [comment]
Not anything anyone has done recently. We just observed that in the past
and I thought it would be useful to formalize it now that we have a way to
do so and have lots of new members

**Comment by arojascastro** [comment]
As long as that statement doesn't impede us to discuss about "ethics of technology, education, or publishing", I'm happy if people are happy.

**Comment by amsichani** [comment]
this is indeed an important addition to our internationalisation/diversity policy and thanks @acrymble  for raising it. In line with @arojascastro 's comment, lets make sure we are still able to discuss PH within the OA agenda (having a distinct socio-economical approach).

**Comment by acrymble** [comment]
Proposed by @walshbr that we also add a link to the editorial guidelines in this blurb, to highlight the areas in which we are political (open access) and not (jokes). This avoids needed to update any of the live site pages.

If you have any further views on this please post them here by August 15 2018 at which point I'll move it to the Wiki if I hear nothing more.

**Comment by walshbr** [comment]
And regarding my comment in the call about adding a clause to reflect that this is something we're expecting authors to abide by as well as editors - I think it's probably fine as is. Upon rereading I think the fact that you refer to the PH as a unit as well as the board conveys that. This looks good to me.

**Comment by acrymble** [comment]
Thank you for your feedback everyone. This has been moved to https://github.com/programminghistorian/jekyll/wiki/Neutral-Political-Policy

It did not affect any live pages. Only the Wiki.
