### ISSUE TITLE
Spanish DH Jargon

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/jekyll#908]
Adam and I discussed today the importance of having a list of approved DH terms in Spanish that can help us ease the translation and revision processes, and for sure the writing of original tutorials in Spanish. This could also be useful for the Spanish-speaking DH community.  

We can start to compile some terms here and then ¿create a section in the webpage? or circulate them internally. I think it'll more useful to make this an open access resource.

**Comment by mdlincoln** [comment]
This sounds like it might be a good wiki page, since it is mostly for reference for our internal processes and will need to be frequently updated. It'd still be publicly viewable if its on the wiki - you could do a blog post pointing out the wiki page to make sure prospective authors know about it?

**Comment by jenniferisasi** [comment]
These are great ideas! We would benefit greatly from a vocabulary list on a wiki page - we could also link said terms to their Wikipedia entries?  
Another idea (that will make it more difficult but I think it's needed): We need to check with people from several countries and/or varieties of Spanish to make sure we reach consensus to call it "approved DH terms in Spanish."  

I have a few terms that I have had to change in one of my translations this week: 
"marco de datos" > "conjunto de datos" 
"palabras estructurales" > "palabras de función"
"de alta escala "> "de gran escala"
plot > "diagrama" > "gráfico"
"high-level patterns" > "patrones a nivel general"

**Comment by arojascastro** [comment]
I think it is a good idea. Professional translators usually use *Translation memories*, which are basically chunks of texts that have been previously translated: https://en.wikipedia.org/wiki/Translation_memory

I am currently experimenting with a translation tool that helps you to create memories. The tool is open source - OMEGA: http://omegat.org/

I do not know yet for sure but, after uploading the source text, you can generate a list of terms and then reuse that list in future translations. Maybe we can explore that method and share the list of terms with our collaborators.

**Comment by arojascastro** [comment]
On the other hand, it would be good to have a similar list of terms in English.

**Comment by acrymble** [comment]
I'd suggest publishing this as a more formal initiative. This could help set an agenda for DH in Spanish.

**Comment by amsichani** [comment]
this is a great idea that could help a number of non-English DH initiatives, in languages with no standard DH terminology yet, and it will also boost our internationalisation agenda. I can see here a useful case-study for an edit-a-thon too, prob for the Bogota workshop? "creating a Spanish DH dictionary/glossary" -have a look on a [ similar attempt](https://folgerpedia.folger.edu/Glossary_of_digital_humanities_terms)

**Comment by mariajoafana** [comment]
We can plan an activity on the last day of the workshop in Bogotá to work on this Spanish DH glossary. After the participants had spent some hours writings their own tutorials I guess we will have some terms to discuss. What do you think @acrymble ? Maybe be can get some of the participants to engage on the initiative

**Comment by acrymble** [comment]
@jamotilla you found a Spanish version of TaDiRAH's taxonomy. The participants in Bogotá thought that was a good starting point for a vocabulary. Maybe you can suggest how we take that forward?

**Comment by arojascastro** [comment]
we are already using TADIRAH's research activities: http://tadirah.dariah.eu/vocab/index.php?tema=6

**Comment by jenniferisasi** [comment]
I've just been sent this document regarding vocabulary in the archive. I think it could be very useful for us: [GLOSARIO de Preservación Archivística Digital Versión 4.0](http://www.mecd.gob.es/planes-nacionales/dam/jcr:f20a4ba1-0ed2-445d-9be9-b8b0382562ea/mex-glosario-interpares-total0112.pdf)

**Comment by acrymble** [comment]
It looks like we don't need to do this work from scratch then. Maybe we just need to include links to the above resources on our Spanish author guidelines page? @jenniferisasi what do you think?

**Comment by jenniferisasi** [comment]
I agree with you @acrymble. I've looked for other vocabularies but nothing comes as complete as the document I shared. I don't see the TADIRAH version in Spanish, though? I see the option of changing languages but it changes a bit of the page, not the content. 
If someone else agrees, @mariajoafana @vgayolrs @jamotilla , I'll work on adding the resource myself.

**Comment by mariajoafana** [comment]
Yes, @jenniferisasi the glossary that you shared is very complete. The Spanish version of TAdiRAH is found here:
http://vocabularios.caicyt.gov.ar/portal/index.php?task=fetchLast&v=42

We can add both resources I guess, and also encourage Spanish-language authors and translator to propose new terms to add to TadiraH

**Comment by jenniferisasi** [comment]
Gracias @mariajoafana, ahora sí veo los términos en español. ¡Está muy bien! 
I'll take note to work on this as soon as I can.

**Comment by jenniferisasi** [comment]
Working on this. I don't want to take the definite decision as to where to include the links; rereading the
guidelines, I think the best place (and easiest edit) for these references is under [Traduce una lección](https://programminghistorian.org/es/contribuciones#traduce-una-lección) on the contribute page. Now, inside the different guidelines it could go on "[Escribir para una audiencia global](https://programminghistorian.org/es/guia-para-autores#escribir-para-una-audiencia-global)" and/or on **Guía para revisores** under "[Traducciones](https://programminghistorian.org/es/guia-para-revisores#traducciones)", what do you think?

**Comment by mariajoafana** [comment]
Si, me parece que los lugares que señalas está bien, aunque cree que lo dejaría únicamente en Traduce una lección y en la Guía para revisores
