### ISSUE TITLE
Applied Archival Downloading with Wget

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#909]
- Mac
- GNU Wget 1.19.1 built on darwin16.6.0.
- Python 3.6.3 :: Anaconda, Inc.
- The [The National Archives of Australia](https://programminghistorian.org/en/lessons/applied-archival-downloading-with-wget#a-second-example-the-national-archives-of-australia) section appears to no longer work. View doesn't allow for `right click -> view image` bit of the lesson. Script downloads html files. Wget calls seem to be not finding what they should (see below).

`--2018-06-14 16:31:29--  http://www.nla.gov.au/apps/cdview/?pi=nla.ms-ms5393-1-s1-v.jpg`
`Resolving www.nla.gov.au... 192.102.239.53`
`Connecting to www.nla.gov.au|192.102.239.53|:80... connected.`
`HTTP request sent, awaiting response... 302 Moved Temporarily`
`Location: http://nla.gov.au/nla.ms-ms5393-1-s1-v.jpg [following]`
`--2018-06-14 16:31:32--  http://nla.gov.au/nla.ms-ms5393-1-s1-v.jpg`
`Resolving nla.gov.au... 192.102.239.32`
`Connecting to nla.gov.au|192.102.239.32|:80... connected.`
`HTTP request sent, awaiting response... 200 OK`
`Length: unspecified [text/html]`
`Saving to: ‘index.html?pi=nla.ms-ms5393-1-s1-v.jpg.2’`
` `
`index.html?pi=nla.ms-ms5     [ <=>                            ]  11.81K  --.-KB/s    in 0.001s  `
` `
`2018-06-14 16:31:34 (11.6 MB/s) - ‘index.html?pi=nla.ms-ms5393-1-s1-v.jpg.2’ saved [12090]`
` `
`--2018-06-14 16:31:36--  http://www.nla.gov.au/apps/cdview/?pi=nla.ms-ms5393-1-s2-v.jpg`
`Reusing existing connection to www.nla.gov.au:80.`
`HTTP request sent, awaiting response... 302 Moved Temporarily`
`Location: http://nla.gov.au/nla.ms-ms5393-1-s2-v.jpg [following]`

**Comment by acrymble** [comment]
@ianmilligan1 this WGET stuff is outside of my area of expertise. Do you by chance have a moment to suggest a solution?

**Comment by ianmilligan1** [comment]
I think it'd have to be reworked as I'd assume that the National Archives of Australia site itself has changed. The author could have the opportunity to do maybe?

**Comment by mdlincoln** [comment]
So the URLs that it suggests to follow lead to 404s... as far as I can tell this is a change made by NAA.

If the rest of the lesson is still working, I suggest we add a `{% include alert.html %}` to that section with a note that it no longer works for that reason, but that we're leaving the text there for reference.

Any objections?
