### ISSUE TITLE
English Managing Editor & Call Coordinator (2018/19)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#911]
@JMParr and @walshbr have done a fantastic job taking on the roles of English Managing Editor and Skype Call Coordinator this year. We had originally said this would be an annual September-August role, following on from previous people holding those roles.

Does anyone on the editorial board want to step forward for either of these positions next year? I think it's a really great way for a new person to learn the system in depth, so I would recommend it (I've done both in past).

**Comment by amsichani** [comment]
This title/role of Skype Call Coordinator looks so tempting to me - happy to give it a try. Thanks so much @JMParr and @walshbr for the fantastic job!

**Comment by alsalin** [comment]
I'd also be interested in in the Skype call coordinator. Not sure if we could split duties?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amsichani** [comment]
yes - this is absolutely fine by me ! we can have 6months each, perhaps? how that sounds @alsalin ? any objection ?

**Comment by alsalin** [comment]
@amsichani that sounds good to me!

**Comment by acrymble** [comment]
It's not a really big role, and might be awkward rather than helpful to split it. Are either of you interested in the managing editor role?

**Comment by walshbr** [comment]
Just to underscore @acrymble's point - the call coordinator (and I imagine the ME as well) will get easier the longer you do it. So for efficiency's sake it probably makes sense to keep it in year rotations. That way you have time to get comfortable and it becomes less of an ask.

**Comment by alsalin** [comment]
@walshbr @acrymble I do see your points here - if the position won't begin until September, then I think I would like to do the ME position (I should have a dissertation draft by September, so that will release me to be able to take on regular responsibilities - that was my only hesitation honestly).

**Comment by amsichani** [comment]
thanks for the input @acrymble @walshbr . I was hesitant to propose myself for the ME at this point, as I 'd like to spend more time and familiarize myself with the editorial & overall workflow- happy to take the Skype call coordinator role then . @alsalin #girlspower

**Comment by walshbr** [comment]
For what it's worth @amsichani, @JMParr and I had only been on the board for about five or six months before we took over those roles. I'd definitely want you to feel comfortable with whatever you decide to take on, but you'll have about as much experience as we did! So I guess I'm just saying - feel confident that you'd have our support in whatever you decide you're comfortable with. And we can help you get up and running.

**Comment by JMParr** [comment]
The workload for the ME role fluctuates. There tend to be more emails
during semester breaks and up through early September, when many campuses
start their fail term (which probably won't surprise you). I think when we
transitioned the role from Jeri to me, we wound up switching over in the
2nd week of Sept.

**Comment by JMParr** [comment]
And yes, I think it's been fine to be in the ME role as a relatively new
editor. It does mean that you may have to ask the rest of the board more
questions, but I have found it helpful as a learning experience.

**Comment by acrymble** [comment]
Thanks for volunteering. I haven't heard any other voices here. Are we happy to go ahead with @amsichani as Call Coordinator and @alsalin as Managing Editor for next year?

I'm sure they'll do a great job.

**Comment by JMParr** [comment]
Okay with me. Amandi can just let me know when she'd like to transition in
to ME.

**Comment by alsalin** [comment]
Sounds like fun everyone! @JMParr shall we chat on email to figure out a transition schedule?

**Comment by walshbr** [comment]
Sounds good - I'll continue doing the Skype calls for July and August and then hand off to @amsichani, assuming that transition schedule works for her. Sorry, everyone - two more months of me!

**Comment by amsichani** [comment]
@walshbr sounds great ! both our transition schedule and the two more months of you!

**Comment by acrymble** [comment]
Thanks everyone. Closing this, as I thinkw e're agreed.
