### ISSUE TITLE
Sponsorship/donations wording.

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#915]
Building on #724, we need some wording that states what we do with sponsorship/donations. Suggest as a starter:

---

The Programming Historian is a volunteer-driven project. In order for it to grow, improve, and sustain our work since FIXME 2018 the Editorial Board of the Programming Historian have accepted sponsorship and donations. This enables us to:

- Pay for professional publishing services that enhance the quality of our publication (e.g., copy editing)
- Improve our community outreach and internationalisation.
- Protect the Programming Historian from changes to service agreements of those ‘free’ services upon which we rely.

To find out how to sponsor or donate to the Programming Historian, please visit our FIXME PAGE. For a list of our current sponsors and named donors see FIXME PAGE.

Sponsorship and donations are managed by FIXME (probably me). Money donate to the Programming Historian is held at FIXME on behalf of the Programming Historian. We thank FIXME for this generous in-kind contribution.

We remain committed to open source values and our content will not disappear behind a paywall. 

---

Note, with translation in mind, we should try to keep this brief.

Note, FIXME PAGE could be lower down the same page.

**Comment by drjwbaker** [comment]
(note: FIXME PAGE could be lower down the same page)

**Comment by drjwbaker** [comment]
Sub-tasks of this on types of sponsorship at https://github.com/programminghistorian/jekyll/issues/918

**Comment by drjwbaker** [comment]
Okay this is my first draft of a proposed new 'Support Us' page, which I guess should be a child of 'Contribute' header but might also be flagged elsewhere in our page design. Anyhow, try to keep this issue for wording, and we'll open new tickets for process and design issues.

@amsichani: perhaps we can discuss this offline - I'm in the office Friday 27th, Monday 30th, and Wednesday 1st if you are around.

--------

The Programming Historian is a volunteer-driven project. We are committed to open source values and our content will not disappear behind a paywall. However, in order for it to grow, improve, and sustain our work, since 2018 the [Editorial Board of The Programming Historian](https://programminghistorian.org/en/project-team) have accepted sponsorship and donations. This enables us to:

- Pay for professional publishing services that enhance the quality of our publication (e.g., copy editing).
- Improve our community outreach and internationalisation.
- Protect The Programming Historian from changes to service agreements of those ‘free’ services upon which we rely.

## Donate to Us

You can donate to The Programming Historian in two ways:

- First, use our [Patreon](FIXME html) page to donate a monthly amount to us (minimum $1 per month). You will be named on our site for your generous contribution to our work. And depending on your level of contribution, you will receive small gift from us. Note that if for any reason you'd prefer your name not be listed on our site, please email programminghistorian@gmail.com and we will ensure it is not displayed.
- Second, for one-off donations, post a cheque payable to 'The Programming Historian' and a cover letter to the following address: Dr James Baker, School of History, Art History and Philosophy, University of Sussex, Falmer, Brighton, BN1 9RH, United Kingdom. Note that if for any reason you'd prefer your name not be listed, please state that in your cover letter.

All donors (excluding those who asked to remain anonymous) are listed below. 

## Sponsor Us

If you represent an organisation or group who are interested in sponsoring The Programming Historian, please contact James Baker to discuss. Sponsorship can be financial, in-kind, or a combination of both. Sponsorship length and value are negotiable and can take a variety of forms:

- Site Sponsorship. Your logo in the header and/or footer of each page of The Programming Historian.
- Activity Sponsorship. This might be of copy-editing (your logo on each lesson page copy-edited with your sponsorship) or of a language initiative (your logo on each page of our English, Spanish, French, or future language edition).

If you have an alternative sponsorship idea that you'd like to discuss with us, please get in touch.

All sponsorship is subject to [agreement](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance) by the [Editorial Board](https://programminghis) of The Programming Historian. In order to avoid perceived conflicts of interest, safeguard our peer review process, and ensure our academic integrity, the Editorial Board have agreed **not to accept** the following forms of sponsorship

- Headline Sponsorship. For example, 'The Programming Historian in association with..' or 'The Programming Historian powered by..'.
- Individual or Selective Lesson Sponsorship. For example, your logo on a single lesson page or lessons pages about a single tool or set of approaches.

All sponsors (past and present) and the nature of that sponsorship (excluding the financial value of that sponsorship) are listed below. 

## Haven't got any money?

The Programming Historian runs on the far-from-endless energy of volunteers, and we want to hear from anyone who shares our interest in teaching digital methods, forging new processes of peer review, and building diversity in the digital humanities community. So if you are unwilling or unable to donate to The Programming Historian, but want to contribute in some way, please see our '[Contribute to The Programming Historian](https://programminghistorian.org/en/contribute)' page where we’ve outlined common ways to contribute.

## Management of Donations and Sponsorship

Donations and sponsorship are managed by James Baker on behalf of the [Editorial Board of The Programming Historian](https://programminghistorian.org/en/project-team). Financial sums arising from donations to and sponsorship of The Programming Historian are held at FIXME on behalf of The Programming Historian.

--------

**Comment by amsichani** [comment]
@drjwbaker 1st August, I ll be around, having a 1-4 meeting. Meet up before this? I ll have a look and add comments on the draft beforehand.

**Comment by amsichani** [comment]
@drjwbaker  this looks great to me- many thanks for drafting this. Minor comment/idea:
- how about try and keep [this](https://github.com/programminghistorian/jekyll/wiki/Things-we-pay-for-(and-need-budget-for)) updated so we can also point here for current/ongoing needs? I think it helps to have them all listed in one place and also keep track on past& future tasks/needs.

Btw, where are we planning to place this Statement? I think it fits nice at the Contribute drop down menu.

**Comment by drjwbaker** [comment]
I agree that we should keep that wiki page updated. Though as it is more for us than readers, perhaps keeping it updated should be the responsibility of the treasurer https://github.com/programminghistorian/jekyll/issues/948? (see as they will see payments/claims come in/out)

On where the text should go, I agree that is should be a child of the Contribute menu.

**Comment by drjwbaker** [comment]
If you are happy with the wording @amsichani, I will move to make this a policy issue to be agreed by set deadline (probably after our September call given that we are both away for the August call).

**Comment by drjwbaker** [comment]
@amsichani & I have discussed, and we move that the 'Support Us' page wording at https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041 is a policy issue.

Per https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance we give this a deadline of 1 October (so that it falls after our September meeting)

**Comment by drjwbaker** [comment]
Note: this wording may change due to decision on "sponsorship types we do not accept" policy issue (deadline 7 Sept) https://github.com/programminghistorian/jekyll/issues/918#issuecomment-408109200

**Comment by arojascastro** [comment]
Thank you for writing this! It sounds all very good. I have some doubts or questions:

- small gift fro us. --> small gift from us.
- what is FIXME?
- Are we sure Patreon and the bank account are accepting money from all countries and currencies? Sometimes there are payment problems. 

Thanks again.

**Comment by drjwbaker** [comment]
@arojascastro:

- [x] small gift fro us. --> small gift from us. *Typo. Fixed now*
- [x] what is FIXME? *this indicates that there is something for me to fix. It is just my preferred placeholder for text that I cannot confirm yet*
- [x] Are we sure Patreon and the bank account are accepting money from all countries and currencies? Sometimes there are payment problems. *Good point. I don't know. I'll add to https://github.com/programminghistorian/jekyll/issues/916 Happy for people to suggest other ways of donating*

**Comment by walshbr** [comment]
"Your logo in the header and/or footer of each page of The Programming Historian." - do we really want to offer up the header as well? My sense was that the footer was more common for something like this. But I can also imagine this getting to be pretty onerous if, say, we had more than a handful of sponsors of this kind. I might offer up the footer for now, leave header off, and consider creating a page that collects all of these sorts of sponsors in one spot. But the proliferation of logos might just be a future problem not necessary to worry about at the moment.

Other than that it looks great to me.

**Comment by drjwbaker** [comment]
A few notes re header:

- I envisage footer being more common and header costing a fair few £ more.
- How often do you see our page footer? 😄 
- I didn't envisage having more than one active logo in header at one time (that is, a sponsorships are fixed period and for defined real estate)
- We have the header space
- You write: "consider creating a page that collects all of these sorts of sponsors in one spot". We wrote: "All sponsors (past and present) and the nature of that sponsorship (excluding the financial value of that sponsorship) are listed below." Are you suggesting an additional page?

**Comment by walshbr** [comment]
Fair enough - one active logo at a time addresses some of that. To the last point, I think I was suggesting collecting in one place instead of proliferating markers of sponsorship on multiple pages on the site. But you're the one working and thinking on this, so I'm happy to defer to you. 

I think I was also not 100% clear on whether this language is going on the main site or the wiki, but now as I read more I think it seems clear this is on the main site. If we're collecting all sponsors in one space somewhere other than the wiki then I don't think we need another page.

**Comment by drjwbaker** [comment]
I'm thinking there might be some in one place, some proliferated. But each case will - I suspect - be unique, and all will require approval from the team.

Main site but per https://github.com/programminghistorian/jekyll/issues/946 it may initially go on the wiki.

**Comment by walshbr** [comment]
@drjwbaker (sorry to tag you in three different places!). we talked about this in #949. The thoughts on the call were that it might make sense to wait until we have a firmer sense of #878 before discussing this or #915 further. Partially because a budget line might have particular stipulations, but also because we can't actually accept any funding until that issue is closed. Maybe this can be discussed internally but not posted as a public-facing policy until we're ready to actually act upon it?

**Comment by drjwbaker** [comment]
Agreed. Thanks to the team for their input. Leave open for now?

**Comment by mdlincoln** [comment]
@drjwbaker would you be able to make a PR for this soon, adding the base text to the about page? Then we can get ES and FR translations, and then I can move on to adding particular sponsors to the `french-staging` branch.

**Comment by drjwbaker** [comment]
@mdlincoln I'm afraid there has been a hold up, so the financial mechanism behind this text won't be going live for a bit. I'm guessing we need some wording - however - in recognition of the support we are getting through you for the FR work.

So what about this slimmed down text (below) that we used as a placeholder - and translate - until the financial mechanism is in place?

----

The Programming Historian is a volunteer-driven project. We are committed to open source values and our content will not disappear behind a paywall. However, in order for it to grow, improve, and sustain our work, in 2018 the [Editorial Board of The Programming Historian](https://programminghistorian.org/en/project-team) started to put in place financial and policy-based mechanisms for accepting sponsorship and donations. This enables us to:

- Maintain our infrastructure.
- Bring in professional services that enhance the quality of our publications.
- Improve our community outreach and internationalisation.
- Protect The Programming Historian from changes to service agreements of those ‘free’ services upon which we rely.

## Supporters

The project is grateful for the following support:

- Web development is supported by the [dSHARP lab at Carnegie Mellon University](http://dsharp.library.cmu.edu/) and the [Andrew W. Mellon Foundation](https://mellon.org/) [2018-Present]
- Ongoing hosting support from the Roy Rosenzweig Center for New Media ([RRCHNM](http://chnm.gmu.edu/)) [2011-Present].
- Funding for a writing workshop in Bogota, Colombia, supported by the [British Academy](https://www.britac.ac.uk/) [2018].
- Seed funding and project management support from the Network in Canadian History & Environment ([NiCHE](http://niche-canada.org/)) [2011-2013].

## Donate to Us

We hope to have a donation mechanism in place by mid-2019.

## Sponsor Us

If you represent an organisation or group who are interested in sponsoring The Programming Historian, please contact [James Baker](drjwbaker) to discuss. Sponsorship can be financial, in-kind, or a combination of both. Sponsorship length and value are negotiable.

All sponsorship is subject to [agreement](https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance) by the [Editorial Board](https://programminghis) of The Programming Historian. In order to avoid perceived conflicts of interest, safeguard our peer review process, and ensure our academic integrity, the Editorial Board have agreed **not to accept** the following forms of sponsorship

- Headline Sponsorship. For example, 'The Programming Historian in association with..' or 'The Programming Historian powered by..'.
- Individual or Selective Lesson Sponsorship. For example, your logo on a single lesson page or lessons pages about a single tool or set of approaches.

## Haven't got any money?

The Programming Historian runs on the far-from-endless energy of volunteers, and we want to hear from anyone who shares our interest in teaching digital methods, forging new processes of peer review, and building diversity in the digital humanities community. So if you are unwilling or unable to donate to The Programming Historian, but want to contribute in some way, please see our '[Contribute to The Programming Historian](https://programminghistorian.org/en/contribute)' page where we’ve outlined common ways to contribute.

## Management of Donations and Sponsorship

Donations and sponsorship are managed by [James Baker](drjwbaker) on behalf of the [Editorial Board of The Programming Historian](https://programminghistorian.org/en/project-team).

----

**Comment by mdlincoln** [comment]
Oh dear, ok - thank you for the update! Yes, I hope we can still go ahead with the sponsor page and then add in direct donation info when that's available - seems like a reasonable compromise.

Any objection to moving "current sponsors" to a more prominent position further up this list, say before the "Donate to us" or before the "sponsor us" subheads?

Also, I'm realizing now this looks quite expansive, and our about page is already quite full - I'd vote for this to be a new page if i'm being honest. Thoughts?

**Comment by drjwbaker** [comment]
Re new page, my bad. We agreed above https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041 that this would be a new 'Support Us' page. The one remaining question is how this interacts with the 'Funding and Ownership' part of the existing About page https://programminghistorian.org/en/about#funding--ownership @mariajoafana @acrymble Given you are the most recent team members to have research funding for PH, what are your thoughts on the matter?

On the wording. Agreed. Fixed above. Better?

**Comment by acrymble** [comment]
Our lessons are being individually sponsored. The outputs of the British Academy Bogota workshop were sponsored. Anyone who produces a lesson as part of a research grant will be sponsored. It's standard practice in publications for funding to be acknowledge, so we need to keep that option available.

I'm less ideologically driven by the need to justify why we would want money. I don't think we need to explain ourselves. It's just standard practice that projects list sponsorship and funding received in the past in a list-like way. I remain unclear why we can't just do the same.

**Comment by drjwbaker** [comment]
Because we agreed that: a) if we plan to ask for money via donations, we should tell people why they might want to support us; b) if we plan to accept sponsorship, we should tell readers that sponsorship doesn't fundamentally change what we do, our values, that we can be 'bought' (e.g. just because CMU are now involved, doesn't now make this a CMU project that does what CMU wants); c) this is a good opportunity to explain the risks the project faces by being entirely volunteer driven.

That said, I take you point. But I feel this is a bit like that neutral political views policy discussion https://github.com/programminghistorian/jekyll/issues/905: there we agreed that although logically everything is political, that we were defining political in this context as party political and that our neutrality on party politics needed explaining. Here although logically all our work is sponsored, I have proposed (and we have agreed for the most part) that we define particular types of sponsorship as different, and our interactions with those types of sponsorship as something that needs explaining.

On the 'Support Us' page wording, what about the 'Supporters' section bringing across the language from the About Page https://github.com/programminghistorian/jekyll/issues/915#issuecomment-447926291. I propose we then edit the 'Funding & Ownership' part of the About page https://programminghistorian.org/en/about#funding--ownership to point to the new 'Support Us' page first followed by the 'The Programming Historian is a volunteer-driven..' paragraph.

**Comment by drjwbaker** [comment]
Agreed at https://github.com/programminghistorian/jekyll/issues/1103#issuecomment-449141377 to launch 'Sponsor Us' page with FR initiative.

**Comment by drjwbaker** [comment]
@mdlincoln Given that we agreed to launch this with the FR initiative, do you want to me make the changes (edit 'about.md', add 'sponsor-us.md', request ES/FR translations) to the French staging branch?

**Comment by mdlincoln** [comment]
yes

**Comment by drjwbaker** [comment]
Done: https://github.com/programminghistorian/jekyll/pull/1070/commits/162e871ddf836643269c907669733297b1b2e96b & https://github.com/programminghistorian/jekyll/pull/1070/commits/65c5ab14e89c928a8b6c83beb215e017b59f0d3b (though if you didn't want me to commit straight to branch, **sorry**.....)

**Comment by acrymble** [comment]
Is this resolved now @drjwbaker ?

**Comment by drjwbaker** [comment]
@acrymble It has been committed to the FR staging branch, but isn't on the live site. So if that is enough to close, then we can close.

**Comment by acrymble** [comment]
Ok let's close it, since it's been taken care of.
