### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#916]
Issue on [Patreon](https://www.patreon.com/) as a mechanism for accepting donations of #915.

- [x] Test [Patreon]
- [x] Add Patreon widget/button to site design. Info https://www.patreon.com/brand/guidelines. @walshbr working on this.
- [x] Agree donation tier(s)
- [x] Agree goal(s)
- [x] Agree text on page
- [x] Add to [Service Integrations](https://github.com/programminghistorian/jekyll/wiki/Service-Integrations)
- [x] Add bank/checkout details

**Comment by drjwbaker** [comment]
Patreon's model is about monthly donations. Patreon runs a 'Rewards' system whereby patrons get things in exchange for the £$€ level at which they donate (see https://www.patreon.com/timsherratt for an eg).

I suggest we have :

- a minimum tier (£$€1 or more) where we thank people by name on the site
- a second tier (£$€5 or more) where we thank people by name on the site and send them some stickers
- a higher tier (?) where we thank people by name on the site and do something super nice for them (ideas?)

Given that Patreon does not support one-time donations (unless the patron donates then cancels subsequent monthly donations), I shall also explore PayPal as an option.

**Comment by acrymble** [comment]
I reserved us the most logical page on this by the way. "Programming Historian".

**Comment by drjwbaker** [comment]
Oops, I've just done that as well..

**Comment by drjwbaker** [comment]
(at 'The Programming Historian')

**Comment by drjwbaker** [comment]
Patreon has a goal based system:

> Earnings-based goals
> Your goals are based on how much you earn on Patreon.
> "When I reach $500 per month, I’ll start a special podcast series where I interview 1 patron every month."

I suggest we have one for copy-editing, based on [Society for Editors and Proofreaders](https://www.sfep.org.uk/resources/suggested-minimum-rates/) minimum costs, and a (conservative) estimate of 3 hours to copy edit each lesson, and ~2 new lessons each month (which I know is more than we get), one goal can be:

> $300 Alongside improving our community outreach and internationalisation and protecting the Programming Historian from changes to service agreements of those ‘free’ services upon which we rely, if we reach this goal we can ensure that all new lessons are copy-edited.

We may also choose to have a second goal for copy-editing all new translations, though given volume of translation this may need some thinking through.

Note: we can change these goals as we please (that is, they aren't binding)

**Comment by drjwbaker** [comment]
Page mockup (preview before submitting for review with Patreon)

![screen shot 2018-06-18 at 13 26 30](https://user-images.githubusercontent.com/4965300/41535728-51f57ed2-72fb-11e8-8ff7-82275c466bdf.png)

**Comment by drjwbaker** [comment]
Once submitted for review, we get a chance to add bank details. Given that this is not confirmed, we are in no hurry. Thanks!

**Comment by acrymble** [comment]
I'm sure you saw Tim Sherratt's page: https://www.patreon.com/timsherratt

**Comment by drjwbaker** [comment]
@acrymble Yes. Drew some ideas from it.

**Comment by acrymble** [comment]
Just looked into the Patreon cut, and it's 2.9% + $0.35 per transaction. I'd raise the minimum number to at least $3 in that case, otherwise there won't be any money coming in at all.

**Comment by drjwbaker** [comment]
I think this didn't happen https://blog.patreon.com/updating-patreons-fee-structure/

**Comment by drjwbaker** [comment]
https://patreon.zendesk.com/hc/en-us/articles/204606125-How-do-you-calculate-fees-

**Comment by drjwbaker** [comment]
From page today.

![screen shot 2018-06-18 at 14 06 32](https://user-images.githubusercontent.com/4965300/41537590-dd653e80-7300-11e8-9d0e-05b7b649a486.png)

**Comment by drjwbaker** [comment]
Comment from @arojascastro at https://github.com/programminghistorian/jekyll/issues/915#issuecomment-409913275

> 'Are we sure Patreon and the bank account are accepting money from all countries and currencies? Sometimes there are payment problems.'

To be investigated.

**Comment by acrymble** [comment]
Can we close this while we rethink our strategy for a budget line? @drjwbaker ?

**Comment by drjwbaker** [comment]
Closed whilst we have a rethink. Note, @drjwbaker has an interim Patreon account with programminghistorian@gmail.com login. Ask him for password.

**Comment by acrymble** [comment]
I've had another look at the proposed text, and I've attached my suggestions for an approach that is more emotional, has giveaways that don't cost us money and promotes the giving process more  widely, and that has a layer for institutional sized donatinons. Please give feedback before I implement anything.

---

## What are you creating?

a world where everyone is empowered to master technology

## About your Patreon page
--

**_Programming Historian_ is an international volunteer-driven project administered by ProgHist Limited, a not-for-profit company limited by guarantee registered in England (12192946). Our publications are published by the Editorial Board of the Programming Historian.**

We seek to change the world through high quality open access learning.

We believe that everyone should have access to free education and the tools they need to master technology. We are a leading open access not-for-profit publisher specializing in beginner-friendly technology tutorials that allow learners to build skills at their own pace. We publish in English, Spanish, and French, and each year reach more than 1-million people around the world.

Your contribution enables us to maintain and update published lessons, to devote extra time to work with our authors so they produce clear and accessible instructions, and to expand our multi-lingual and culturally sensitive approach to learning and teaching.

Thank you for supporting our project.


## Tiers

For getting us off the ground, the first person to join a tier will be recognized on our sponsorship page. We really appreciate you.

### Subscriber

$1 or more per month

Thank you! We will thank you as a new subscriber to our thousands of Twitter followers.

### Sponsor

*$5 or more per month* 

Thank you! All of the above benefits plus we will add a thank you in our quarterly newsletter and the chance to suggest a lesson topic (within the scope of our publications) on our website to prospective authors.

### Patron

*$15 or more per month*

Thank you! All of the above benefits plus listing your name on our website as a valued sponsor.

### Lasting Legacy Member

*$200 or more per month*

Thank you! All of the above benefits plus a hand-written thank you from our team and prominent listing of your name or organization on our sponsorship pages for the duration of your support.



## Goals

$500 a month will enable one of our editors to update and maintain our 130+ published lessons, and to work more closely with our authors to make sure every new lesson is written clearly and accessibly. $1,000 per month will allow us to support the translation of every lesson into English, Spanish, and French.


## Thanks

Thank you for joining our efforts to make technology learning accessible and free to all.

**Comment by drjwbaker** [comment]
Much more inspiring. Thanks for your creative input @acrymble.

**Comment by drjwbaker** [comment]
Have you managed to connect this with our PayPal? If not, I can look at it Monday.

**Comment by acrymble** [comment]
I haven't touched patreon or Paypal. I just took the headings and wrote the text.

**Comment by drjwbaker** [comment]
Okay. I'll look at plugging them together tomorrow.

**Comment by acrymble** [comment]
It's also possible to have a certain number of spots on a given tier. So we could launch with a foundational sponsor category, for example. People we agree to commemorate as the group that helped get us started. If we think that would be helpful.

**Comment by drjwbaker** [comment]
@acrymble As I suggest at https://github.com/programminghistorian/jekyll/issues/1405#issuecomment-541578202 can we pull this into a full 'policy' suggestion (per https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance)?

**Comment by drjwbaker** [comment]
> Okay. I'll look at plugging them together tomorrow.

I can't add the payout info until we send the Paypal page for review. Once a tier is up, we can't change the tier without cancelling the Patrons, so we have to get this right. So we can't send for review until we are happy (as an Editorial Board) with the tiers.

**Comment by drjwbaker** [comment]
There is a Patreon button:

`<a href="https://www.patreon.com/bePatron?u=11816614" data-patreon-widget-type="become-patron-button">Become a Patron!</a><script async src="https://c6.patreon.com/becomePatronButton.bundle.js"></script>`

I'm going to test it on our site today (like I did for paypal at #917).

**Comment by drjwbaker** [comment]
From https://github.com/programminghistorian/jekyll/pull/1502:

> I think this isn't displaying properly on the preview because the Patreon account isn't live. Catch-22 et cetera :)

**Comment by svmelton** [comment]
Has PH ever produced any merchandise or swag? (Buttons, shirts, stickers, etc.) I've often seen items like those in Patreon rewards, and it could make donating more enticing.

**Comment by drjwbaker** [comment]
We have EN https://github.com/programminghistorian/jekyll/blob/gh-pages/images/programmingHistorianSticker-promo.png ES https://github.com/programminghistorian/jekyll/pull/796/commits/b70801e8f120ee0ad193d95459874004ec22433d#diff-ec72e4e733db87314958095af3a34b9c and FR stickers (though I can't find them all in our repo right now..). We certainly can send some out if we have the right details (and it doesn't cost us too much!)

**Comment by drjwbaker** [comment]
Agreed at https://github.com/programminghistorian/jekyll/issues/1483 to implement these tiers. On @svmelton's point, we can always lightly edit the text for the tiers to send folks swag if we want :)

**Comment by drjwbaker** [comment]
We now have a live Patreon page https://www.patreon.com/theprogramminghistorian/

I'll work on the financial checkout mechanisms now.

**Comment by drjwbaker** [comment]
Finances in place. We are go people.

**Comment by drjwbaker** [comment]
@jenniferisasi: further to https://github.com/programminghistorian/jekyll/issues/1503#issuecomment-545911156 can I leave you to figure out how to best promote this via our social media channels?

Note also at https://github.com/programminghistorian/jekyll/issues/916#issuecomment-541396704 we've agreed to thank people on Twitter and via our newsletter. In the first instance, I happy to do a weekly thank you tweet via our Twitter, and pass you a list of names for the newsletter.

**Comment by jenniferisasi** [comment]
I take note of this task on my list. 

Also, and I'm sorry I didn't raise the question before, how can we make this available in other languages for our non-English speaking audience?

**Comment by drjwbaker** [comment]
Do you mean multi-lingual Patreon? Good point. That is poorly supported. We can certainly try putting translations in all the boxes you can see at https://www.patreon.com/theprogramminghistorian. What do you think?

**Comment by jenniferisasi** [comment]
Yes, after posting the question and browsing through Patreon and google, that seems to be the only viable option. The good news is, I think, that the membership levels are mostly cognates in Spanish-English-French. 
Shall we translate then @programminghistorian/spanish-team and @programminghistorian/french-team?

**Comment by acrymble** [comment]
What about separate pages? Then none of them need to look lesser than the others.

**Comment by drjwbaker** [comment]
So multiple language campaigns. Certainly possible.

**Comment by drjwbaker** [comment]
Though we might need muiltple accounts. I'd need to check.

**Comment by drjwbaker** [comment]
Multiple language campaigns would require multiple account, each with a separate email address, each with separate Paypal checkout, et cetera https://support.patreon.com/hc/en-us/articles/360028555212-Can-I-have-multiple-accounts- I feel that is a bit too much for us to manage right now. We could start by changing the tier names, so from 'Subscriber' to 'Subscriber / ES / FR'.

**Comment by acrymble** [comment]
Multilingual videos?

**Comment by acrymble** [comment]
I think this issue is now complete, no? The question of best approach to multilingual support seems like a new issue to me, @drjwbaker ?

**Comment by drjwbaker** [comment]
Agreed.
