### ISSUE TITLE
PayPal

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#917]
Issue on PayPal as a mechanism for accepting donations of #915. Purpose: Patreon #916 is setup to accept monthly donations rather than one-off payments.

**Comment by acrymble** [comment]
You should check with your university. UofL wouldn't let us use this a few years ago for British History Online.

**Comment by drjwbaker** [comment]
We can't setup on the [not-for-profit or charity route](https://www.paypal.com/uk/webapps/mpp/not-for-profit) as we aren't either of these things (that is, we don't have the requisite paperwork).

**Comment by drjwbaker** [comment]
Yes @acrymble. This seems more fraught with problems. I think we'll have to await confirmation of how the setup will work before looking at this further.

**Comment by acrymble** [comment]
Can we close this while we rethink our strategy for a budget line? @drjwbaker ?

**Comment by drjwbaker** [comment]
closed whilst we have a rethink

**Comment by drjwbaker** [comment]
@programminghistorian/technical-team PayPal has a mechanism for generating buttons (for example, to ask for donations). These result in some html code. Do you have some capacity to test whether one of these PayPal generated button would render correctly with our install? If so, I can an example to this ticket.

**Comment by acrymble** [comment]
you can preview it in a pull request.

**Comment by drjwbaker** [comment]
Any suggestions which part of the website to add it to for testing?

**Comment by drjwbaker** [comment]
- [x] Add PayPal details to service integrations

**Comment by drjwbaker** [comment]
Code for test button below (note, lots of tweaking we can do):

`<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">`
`<input type="hidden" name="cmd" value="_s-xclick" />`
`<input type="hidden" name="hosted_button_id" value="7BGHUZRVS4LYL" />`
`<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_donate_LG.gif" border="0" name="submit" title="PayPal - The safer, easier way to pay online!" alt="Donate with PayPal button" />`
`<img alt="" border="0" src="https://www.paypal.com/en_GB/i/scr/pixel.gif" width="1" height="1" />`
`</form>`

**Comment by drjwbaker** [comment]
@programminghistorian/technical-team Re https://github.com/programminghistorian/jekyll/pull/1500 I'd like a view from you on how to best place a PayPal donate button. I've currently got it in the footer between the ProgHist Ltd text and the columns with ISSN details et cetera, but I'm open to ideas. For example, I'd like to see what it looks like in the header, but feel less confident about editing (even for testing purposes!) `header.html`.

**Comment by acrymble** [comment]
What about just on the /support-us  page under the section that says we're hoping to have a mechanism soon? Then you don't have to fiddle with more complicated design elements in the short term?

**Comment by drjwbaker** [comment]
Adam. I know it works because I've put it in the footer in the fake PR. I now just want to know how it looks elsewhere in the site template, where my html foobar is less strong.

**Comment by walshbr** [comment]
I'd keep it in the footer or in the /support-us stage as @acrymble suggests.

**Comment by drjwbaker** [comment]
So it looks roughly okay in the footer then?

**Comment by acrymble** [comment]
Sorry @drjwbaker I'm not totally clear what you're trying to achieve. I personally think the donate button is fairly ugly. I don't think it will get us any money in the footer, because not many people will see it.

But is this a matter of seeing if the actual  paypal payments reach our bank account (that's what I thought you wanted to do), or are you trying to move into integrating income streams into our web design?

I thought we were just using paypal as a service to manage the money we raise via Patreon, and that Patreon would be the public-facing donation mechanism that we advertise.

**Comment by drjwbaker** [comment]
In which case we are at cross-purposes. I was assuming that we are looking at having a Patreon button/link for ongoing donations and Paypal button/link for one-off donations. I think whatever we choose to have that these need to be on every page (so, eg, in a footer) so in https://github.com/programminghistorian/jekyll/pull/1500 was a) testing that this button would work and b) interested in where else we could put it without breaking our look/feel/tech.

**Comment by drjwbaker** [comment]
Update:

- paypal works.
- the html 'donate' button works on our site should we want to use it.
- details added to service integrations. 

Lets use https://github.com/programminghistorian/jekyll/issues/1457 to discuss integration onto the site. So closing for now.
