### ISSUE TITLE
Recognition of sponsorship/donations/support

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#918]
Building on #724, we need to agree how best to recognise sponsorship and donations on the site.  At present this is buried on https://programminghistorian.org/en/about. I propose:

**For donations**

A list of all individuals (if you want to be named) who have contributed money to the project and a link to the Patreon page where current patrons are listed. Perhaps an extension of https://programminghistorian.org/en/project-team#community-participants

**For sponsorship**

We have a Sponsorship Coordinator role to whom potential sponsors are directed (and who actively seeks sponsorship). This individual is empowered to come up with a model that fits the  potential sponsor and at the same time is suitably visible given the £$€ and/or in-kind contribution.

Suggested models we might put on the site:

1. Site sponsor (logo/name in footer)
2. Monthly or short period fixed-term sponsor (logo/name in header)
3. Event sponsor (logo/name with event details, on specific pages). This can also work for research funding.
4. Activity sponsor (e.g., sponsor of copy-editing for Spanish language lessons with logo/name alongside each translation copy-edited with these funds)

Suggested models we might agree to not accept:

1. Headline sponsor ('The Programming Historian in association with..' or 'The Programming Historian powered by..'
2. Lesson sponsorship. I agree with the concerns on this here https://github.com/programminghistorian/jekyll/issues/724#issuecomment-369678930 that this might be seen as compromising peer-review

**Comment by acrymble** [comment]
There's a lot in this. Can we put this on the July agenda?

**Comment by drjwbaker** [comment]
Sure (cc @amsichani for when you pull the agenda together). I should add that I'm aware there is a lot here and that we'll need to split into separate issues / workstreams. This is just my initial overview of what recognition for donors/sponsors might look like.

**Comment by acrymble** [comment]
I'd suggest a small team of 3 people (or so) could probably put together a strong proposal to bring to the group on this. That might mean we get further faster. But just a suggestion.

**Comment by drjwbaker** [comment]
Sure. Hadn't planned to take all of this myself.

Who wants to work on proposal? And what parts of the above (site design, models, process) are you interested in leading on?

**Comment by walshbr** [comment]
Added this to the agenda for July - #919.

**Comment by acrymble** [comment]
If we have someone on the team in the US who is in a role where they are eligible for applying for grants, it would be good to get them involved so that we can make sure American culture is represented by this approach we take.

**Comment by walshbr** [comment]
There are some bureaucratic reasons that staff w/o faculty status at our institution have difficulty applying for grants, but it's something we're actively trying to work against and around. So I can weigh in if it's helpful.

**Comment by drjwbaker** [comment]
To be clear, I had thus far seen the sponsorship/donation activity as distinct from grant capture. Though in terms of recognising all these activities on our site, there is overlap.

**Comment by drjwbaker** [comment]
@amsichani Agreed to support this work.

**Comment by drjwbaker** [comment]
https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041 notes proposed types of sponsorship we will not accept. These are:

- Headline Sponsorship. For example, 'The Programming Historian in association with..' or 'The Programming Historian powered by..'.
- Individual or Selective Lesson Sponsorship. For example, your logo on a single lesson page or lessons pages about a single tool or set of approaches.

I move that this is a policy issue. Per https://github.com/programminghistorian/jekyll/wiki/Programming-Historian-Governance I give this a deadline of 7 September (both after the next call and taking in account that many of us have holiday)

**Comment by acrymble** [comment]
This needs a new 'Treasurer' role on the Project Team. Which is fine and easy. But it definitely needs to be done.

**Comment by drjwbaker** [comment]
@acrymble The next task on my to-do list is: "open a ticket about Treasurer role" 😃

**Comment by arojascastro** [comment]
I am trying to follow up this discussion. I do not have much to say but thank you for working on it.

**Comment by drjwbaker** [comment]
@arojascastro I appreciate your thanks 😄

**Comment by acrymble** [comment]
Having through about this, I'm struggling to come up with an example where the traditional methods of acknowledging support on academic websites wouldn't be sufficient. Some examples:

Migration Observatory, University of Oxford:

<img width="1470" alt="screen shot 2018-08-16 at 12 00 08" src="https://user-images.githubusercontent.com/646647/44204945-9689cd80-a14c-11e8-88c8-174da374b5b6.png">

Old Bailey Online:

<img width="753" alt="screen shot 2018-08-16 at 12 05 09" src="https://user-images.githubusercontent.com/646647/44204960-a86b7080-a14c-11e8-92a4-6963bf37930f.png">

Where individuals have been sponsored/funded to create a lesson, then the normal convention is to include an acknowledgement in the acknowledgement section of the paper (which we don't usually have but certainly can in future because it's in line with academic convention).

With event or activity sponsorship (eg, Bogotá workshop), then we can acknowledge funding on event branding, and in the list of past supporters.

I would see this all fitting very well on the Project-Team page.

**Comment by acrymble** [comment]
If we're thinking of this as people contributing to a general fund that's used to cover ongoing costs, then I think (until we get someone really rich offer us a lot of money), we don't need to let them put conditions on how that money is spent. So maybe it's just a matter of saying that donations are spent in the way the Editorial Board feel could make the biggest impact for the project. Anyone interested in donating towards a specific activity are invited to contact the Treasurer to discuss the idea further.

**Comment by drjwbaker** [comment]
Adam. Thanks for this. I agree that existing models work, but there is no reason to just do what has been done - having viable options on the table for potential sponsors gives us a starting point for conversations.

On https://github.com/programminghistorian/jekyll/issues/918#issuecomment-413509109 this really refers to https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041. All we say here is a selection of things we are looking to use donations/sponsorship money on, but you are correct to say we will always reserve the right to change our priorities.

**Comment by acrymble** [comment]
Is there a difference between what we're calling "Sponsorship" and "Advertising"? I don't think we want to spend the time running advertising. That's why I favour the list of sponsors approach, not unlike the way museum exhibits engrave a wall with the names of benefactors.

**Comment by drjwbaker** [comment]
I agree. But the list of exhibit benefactors in a museum is much more visible than our footer or a list of things tucked at the bottom of an about page. Let's say I'm exploring options. This isn't about brash advertising space. Just a way of making this work for us *and* recognising generous contributions.

**Comment by acrymble** [comment]
Continuing to think on this. I'm not sure what you have in mind in terms of sponsorship, but in order to get a logo on our site in some prominent space (your examples 1 and 2 above), I'd think we'd want some pretty major money - like enough to hire someone full time for a year at 100% full economic costing. I'm not sure that's realistic as we start out. I know the head of a department at a major UK history dept isn't allowed to go out for lunch with an alumnus unless he's confident he can get at least £2,000 in donation money because anything less isn't worth his time. We need to keep that in mind here too.

I think we should discourage restricted gifts that require us to spend the money in certain ways (your example 4) unless they're tied to grants or linked directly to something we definitely want to do already and have the flexibility to do it our own way. We don't want to start working for sponsors.

If you've got sponsors lined up or have hypotheticals in mind, then I think that would help me understand why we need a sponsorship policy. I don't mean to sound negative, but I'm struggling to *get* this.

**Comment by drjwbaker** [comment]
@acrymble Thanks for your frankness (I expect nothing less). This issue was designed to create a conversation after all. I've noticed my **BIG** error at https://github.com/programminghistorian/jekyll/issues/918#issuecomment-408109200. It said we should move to not accept:
- Site Sponsorship. Your logo in the header and/or footer of each page of The Programming Historian.
- Activity Sponsorship. This might be of copy-editing (your logo on each lesson page copy-edited with your sponsorship) or of a language initiative (your logo on each page of our English, Spanish, French, or future language edition).

..when it should have said..

- Headline Sponsorship. For example, 'The Programming Historian in association with..' or 'The Programming Historian powered by..'.
- Individual or Selective Lesson Sponsorship. For example, your logo on a single lesson page or lessons pages about a single tool or set of approaches.

This is now fixed.

**Comment by drjwbaker** [comment]
On the rest (which more correctly address ticket https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041):

> Continuing to think on this. I'm not sure what you have in mind in terms of sponsorship, but in order to get a logo on our site in some prominent space (your examples 1 and 2 above), I'd think we'd want some pretty major money - like enough to hire someone full time for a year at 100% full economic costing. I'm not sure that's realistic as we start out. I know the head of a department at a major UK history dept isn't allowed to go out for lunch with an alumnus unless he's confident he can get at least £2,000 in donation money because anything less isn't worth his time. We need to keep that in mind here too.

Perhaps. But we are testing the waters here and we won't know if we are selling ourselves short until we have. So if someone wants to offer some money for their logo in a prominent place for short period of time and there are no reputational risks to us attached (we like them, they are good people) what do we have to lose? 

> I think we should discourage restricted gifts that require us to spend the money in certain ways (your example 4) unless they're tied to grants or linked directly to something we definitely want to do already and have the flexibility to do it our own way. We don't want to start working for sponsors.

Does "All sponsorship is subject to agreement by the Editorial Board of The Programming Historian" not cover this?

> If you've got sponsors lined up or have hypotheticals in mind, then I think that would help me understand why we need a sponsorship policy. I don't mean to sound negative, but I'm struggling to get this.

Apart from our potential bank account, I don't. We decided we needed some text that gave potential sponsors a starting point for discussion about what we could offer in return for sponsorship (in-kind or financial), something to point them to, to show that we've thought about the implications, what we want, what we don't want, et cetera. The text at https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041 is the product of that. I happen to think it will prove useful. But as it is a policy issue we may as a group think otherwise. Deadline for comment on the 'Support Us' page wording is 1 October https://github.com/programminghistorian/jekyll/issues/915#issuecomment-409829679. Not having a sponsorship policy on the page is a viable outcome of this.

**Comment by arojascastro** [comment]
I think I understand both parts. However, in my opinion, this initiative deserves a try. We can change the policy later or redo it or even remove it after learning about the experience. I have in mind some European infraestructures that may be want to sponsor us: CLARIN and DARIAH. They do a lot of things about teaching and they even create themselves tutorials. I think after approving this policy we could approach them. On the other hand, in Spain, I only imagine a potential sponsor, and it would be big bank. I do not like banks though. I think it will be easier to find sponsors for the English team in any case. So it is up to the English team in my opinion how to deal with it.

**Comment by acrymble** [comment]
We also have to be wary of transacting services and the legal implications of something goes wrong. If the sponsor doesn't think we've done what they said, who gets sued?

**Comment by walshbr** [comment]
@drjwbaker we talked about this in #949. The thoughts on the call were that it might make sense to wait until we have a firmer sense of #878 before discussing this or #915 further. Partially because a budget line might have particular stipulations, but also because we can't actually accept any funding until that issue is closed. Maybe this can be discussed internally but not posted as a public-facing policy until we're ready to actually act upon it?

**Comment by drjwbaker** [comment]
Agreed. Thanks to the team for their input. Leave open for now?

**Comment by drjwbaker** [comment]
Due to TBA developments, reviving this separate from #878. Two points to consider.

1. I suggest in the first instance that we tweak https://programminghistorian.org/en/about#funding--ownership so that we separate current, legacy, and project based support.
2. I suggest that open a discussion about whether or not we want to add sponsor logos to our footer.

@mdlincoln Does this fit your needs?

**Comment by acrymble** [comment]
Logo use has to be approved by the organisation who owns it. There are often branding rules about blank space, etc as well. Further, I think will look messy. So I don't think we should include logos in the footer.

**Comment by JMParr** [comment]
Agree to what @acrymble said. A list of acknowledgements, thanking sponsors ought to be enough.

**Comment by walshbr** [comment]
From a technical standpoint, given that logos are all unique and consist of different line heights, shapes, branding requirements, we should do this in a way that minimizes our need to re-CSS things with each new sponsor. I've done a footer design for sponsors in the past, and it required a fair amount of work to get the fairly different logos all playing aesthetically. And looking at the project now, they've added three _more_ sponsors. So the work put into the four-logo look was moot more or less and needs to be rebuilt.

We might just have to have logos, and that's totally fine and understandable. But I think we'll be more limited in our ability to design for the future if we're trying to fit logos into our footer. I'd rather come up with a simple list that we can just add to on a separate page than worry about the design/accessibility effects of how each new logo will effect a global feature like the footer, which is already operating under design constraints.

**Comment by mdlincoln** [comment]
For the future, sure, maybe we'll need them - but for the immediate needs, if they even want logos, all it would need to be is images on the sponsorship page. So I wouldn't panic about footer logos quite yet.

**Comment by drjwbaker** [comment]
Okay. 2. is out. Are we happy with what I suggest for 1.?

**Comment by acrymble** [comment]
@drjwbaker it looks like the support us page is up and running. Is this ticket resolved then?
