### ISSUE TITLE
correction to first python lesson?

### ISSUE THREAD

**Issue by mavelezserna** [programminghistorian/jekyll#92]
Hi - I've never used github before so apologies if I'm doing it wrong,
I've started teaching myself python following the first lesson and found a possible error:
at:
"Make a “Run Python” Command in Komodo Edit
    In Komodo Edit, click the gear icon under Toolbox and select New Command.
    In the top field type “Run Python File“
    In the Command field, type: `%(python) %f` Then hit the OK button at the bottom of the Add Command window."
The Command should be `%(python) %F`
(capital F) as that is the shortcut for file path, rather than base name.
It worked for me at least (I'm only at the 'hello world' stage...)

**Comment by mavelezserna** [comment]
Also under instructions for launching a python shell -
it would be useful to add that you have to open a terminal and type `python`
I know this is really basic but... I had to google it.

**Comment by acrymble** [comment]
Hi Maria, I've had groups of students successfully set up Komodo Edit recently using this lesson. Are you using a particularly obscure setup, or has there been a change to Komodo Edit?

**Comment by mavelezserna** [comment]
I don't know, sorry... I think I followed the instructions, though I downloaded Python from the website rather than through apt-get.
When I try to run the original command `%(python) %f` with my hello-world file I get this:
`/usr/local/bin/python: can't open file 'hello-world.py': [Errno 2] No such file or directory`
Whereas if I change the `%f` to `%F` it works.
Maybe my setup *is* particularly obscure - am on a five-year-old laptop running Linux Mint 16 - but I did not purposely customise anything during the install. Again apologies if I'm muddling the issue, figured it is in the spirit of the Programming Historian to document this kind of oddity.

**Comment by duhaime** [comment]
Hi all, either works in windows 8.1 with git and mingw shells installed.

**Comment by ianmilligan1** [comment]
Just like Doug, either works in OS X too. Some Googling around finds that a few Linux distributions seem to distinguish between %f and %F. Maybe we could change it to upper case for the Linux-Installation page?

Also, Maria found a great catch that we committed the initial 'Python' command. I can go in and add a line of code there.

**Comment by ianmilligan1** [comment]
Just a note that I put a quick line of code in there directing people to enter the Python shell first before being able to `print('hello world')`

**Comment by acrymble** [comment]
Any Linux users can clarify this? If we change it to upper case F for linux instructions will that work in all cases?

**Comment by ianmilligan1** [comment]
Just returning to this.

As doesn't look like anybody has handy access to a Linux box, my vote is that since both work let's change %f to %F. @acrymble does that sound good - if so, I can make change.

**Comment by acrymble** [comment]
yep that's fine.
