### ISSUE TITLE
Pending changes in "Procesamiento básico de textos con R"

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#929]
As pointed out here https://github.com/programminghistorian/jekyll/pull/922, in that lesson there was a internatl link that I removed in order to pass Travis. The link should be added in footnote 2 once the translation is published:

> Taryn Dewar, “Datos tabulares en R”, Programming Historian. Trad. de Jennifer Isasi de 10 de abril de 2018.,

**Comment by arojascastro** [comment]
Also fix the markdown in the abstract - by removing it? (it is not displayed correctly): 

`(*high-level patterns*) `

In:

> Aprende a utilizar R para analizar patrones a nivel general (*high-level patterns*) en textos, para aplicar métodos de estilometría a lo largo del tiempo y entre autores y para aprender metodologías de resumen con las que describir objetos de un corpus.

**Comment by arojascastro** [comment]
Also I think this block of code is not displayed ok:


>#A tibble: 1,457 x 4
   word     count language frequency
   <chr>    <dbl> <chr>        <dbl>
 1 america    28. en          0.0232
 2 people     27. en          0.0817
 3 just       25. en          0.0787
 4 world      23. en          0.0734
 5 american   22. en          0.0387
 6 work       22. en          0.0713
 7 make       20. en          0.0689
 8 want       19. en          0.0440
 9 change     18. en          0.0358
10 years      18. en          0.0574
>#... with 1,447 more rows

and the following

**Comment by jenniferisasi** [comment]
@arojascastro en cuanto terminemos de publicar la traducción de datos tabulares hago los cambios que señalas aquí.

**Comment by arojascastro** [comment]
Ok, pero ya empecé los cambios en esta "branch": https://github.com/programminghistorian/jekyll/tree/issue-929

Ya me queda poco, si acaso cuando haga el pull request, contrólalos, te pongo como revisora.

**Comment by arojascastro** [comment]
Done in https://github.com/programminghistorian/jekyll/commit/bef961edb3097485885e7a5951f9f3b10c61fa41
