### ISSUE TITLE
post to blog, I think I did it wrong

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#93]
I tried posting a new entry to the blog, but I've obviously done it wrong. Entry is 'edinburgh-workshop-2015' in the 'blog' directory. Do I have to do something specific to have that pop up on the blog page and RSS feed? @wcaleb

**Comment by wcaleb** [comment]
The post has to be named in a certain way. See the section on naming conventions for posts: 

https://github.com/programminghistorian/jekyll/wiki/Creating-Blog-Posts

**Comment by acrymble** [comment]
Great. Thanks.
