### ISSUE TITLE
Data Wrangling format issues.

### ISSUE THREAD

**Issue by bmschmidt** [programminghistorian/jekyll#930]
The data wrangling article doesn't display well in a way that makes it difficult to understand.. Consider the following:

https://programminghistorian.org/en/lessons/data_wrangling_and_management_in_R

```{R}

# Make sure you have installed the historydata package and loaded it before this

data(early_colleges)
early_colleges

## # A tibble: 65 x 6
##                   college         original_name          city state
##                     <chr>                 <chr>         <chr> <chr>
##  1                Harvard                  <NA>     Cambridge    MA
##  2       William and Mary                  <NA>  Williamsburg    VA
##  3                   Yale                  <NA>     New Haven    CT
##  4 Pennsylvania, Univ. of                  <NA>  Philadelphia    PA
##  5              Princeton College of New Jersey     Princeton    NJ
##  6               Columbia        King's College      New York    NY
##  7                  Brown                  <NA>    Providence    RI
##  8                Rutgers       Queen's College New Brunswick    NJ
##  9              Dartmouth                  <NA>       Hanover    NH
## 10   Charleston, Coll. Of                  <NA>    Charleston    SC
## # ... with 55 more rows, and 2 more variables: established <int>,
## #   sponsorship <chr>
```

> As you can observe, this dataset contains the name of the college, its original name, the city and state it was founded, when the college was established, and its sponsorship. 

You can't observe it, because the columns the text refers to are being truncated.

**Comment by acrymble** [comment]
Thanks @bmschmidt for pointing this out. @nabsiddiqui this was your article originally. Can you suggest a solution to this query so we can make a quick update?

**Comment by nabsiddiqui** [comment]
@acrymble Yes, I will try to come up with a solution and have it for you guys sometime next week.

**Comment by nabsiddiqui** [comment]
Thank you everyone for the feedback and help, especially @nolauren.  @acrymble This can be closed now.
