### ISSUE TITLE
Tag by technology

### ISSUE THREAD

**Issue by magdmartin** [programminghistorian/jekyll#931]
It will be useful to filter [lessons available](https://programminghistorian.org/en/lessons/ ) by technology or language (python, OpenRefine, MySQL, R ...)

**Comment by acrymble** [comment]
Thanks for the suggestion. We've also got the option of adopting the TaDiRAH taxonomy, which @jamotilla pointed out is also available in Spanish. Maybe that would be a better long-terms olution for us to consider? Any views anyone?

http://tadirah.dariah.eu/vocab/index.php

**Comment by mdlincoln** [comment]
I'm hesitant to enforce yet another level of labeling on our lessons - and this need would actually be fulfilled by full-text search #1018
