### ISSUE TITLE
Standarization of new proposals?

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#936]
Hi,

You know I love standarizing things. I actually that's my main work and resarch field. So... despite of risking your patience, I would like to suggest to standarize the submission of new proposals (originals, mainly).

From my experience (and maybe @JMParr agrees) as "managing editor" for the ES edition (which is very small because we only got two proposals), we always have to exchange a lot of emails in order to get a proposal that we can share with the rest of the team. Basically, the main problem is that authors do not provide enough information in order to assess their proposal. 

I was thinking that maybe we could implement a form with some required fields - instead of using email as a communication mean.

Some fields:

- Author's name
- Affiliation (optional?)
- Email
- Title of the lesson
- Summary in English or Spanish (if the original is Spanish I think the author should provide a summary in English because otherwise the managing editor has to translate it)
- Main objectives
- Activity 
- Topic / Technologies  
- Main resource / dataset / case study 
- Target Audience
- Expected submission date

And then some free questions like:

- Originality: How is your proposal complementing already existing lessons?
- Sustainability and global scope: How are you planning ot meet our guidelines on sustainability and global audience?

Example:

- Antonio Rojas 
- Universität zu Köln
- pepito@gmail.com
- Introduction to XQuery for Humanities Scholars
- Summary in English or Spanish (if the original is Spanish I think the author should provide a summary in English because otherwise the managing editor has to translate it): blablabla
- Main objectives: 1. Explain what is XQuery and differences with related technologies 2. Introduction to the dataset: Metadata of medieval manuscritps 3. Instructions etc.
- Transform
- XQuery
- Metadata of medieval manuscripts
- Begginner 
- 2018-10-25
 
- Originality: the PHes has no lesson on this technology, however, the lesson on XSLT and others may be a model for mine
- Sustainability and global scope: I will  host the XML file in the PH server and illustrate my tutorial with descriptions of French, Italian and Spanish manuscripts

**Comment by mdlincoln** [comment]
I think this is a really great idea!

**Comment by walshbr** [comment]
Ditto! Think this is a great idea. I think having an intake form that sends a notification to the managing editor would help streamline things.

**Comment by alsalin** [comment]
I love standardization and as the incoming ME, i double vote for this :P

**Comment by JMParr** [comment]
Add me to the supporters.

**Comment by arojascastro** [comment]
Thank you! Very cool :)

Do you have any preference about how we should create the form? A Google form is ok? Do we have a PH gmail account where we can create the form and store the answers in a spreadsheet? 

On the other hand, should we create three forms in English, Spanish and French? Or a unique single form that contains the fields in those languages? For instance: `title / título / titre`?

**Comment by drjwbaker** [comment]
A simple template potential authors can cut/paste should suffice.

**Comment by amsichani** [comment]
@arojascastro you are our standardisation hero!

**Comment by acrymble** [comment]
Love the idea. Should simplify life. A few comments on your proposed fields:

- Author's name
- Affiliation (optional?) **[I don't think this is relevant]**
- Email
- Title of the lesson
- Summary in English or Spanish (if the original is Spanish I think the author should provide a summary in English because otherwise the managing editor has to translate it) **[The Spanish team has editorial independence from the English version, so we don't need to see it unless you want us to]**
- Main objectives **[I think the language we use here is "Learning Outcomes"]**
- Activity **[what does this mean?]**
- Topic / Technologies
- Main resource / dataset / case study
- Target Audience
- Expected submission date

I might suggest asking them to tell us what category it fits into:
<img width="588" alt="screen shot 2018-07-13 at 10 19 56" src="https://user-images.githubusercontent.com/646647/42683901-886e3e92-8686-11e8-967d-0cf75bc48ba3.png">

As I said, love the idea. And yes we do have a PH gmail account that it could go to.

**Comment by JMParr** [comment]
A query - I do think, in theory, people could just cut and paste the
required sections, but I wonder if we're more likely to get cooperation if
there's a Google form or something.

**Comment by arojascastro** [comment]
Hi all, 

@acrymble the "Activity" field is what you called "Categories" e.g. "acquire", "transform", etc. 

Yes, "learning outcomes" is better than "objectives", I agree.

I think the English and future French team should have an opinion on the Spanish submissions if we are all committed to translation. I am not sure how "independent" are we ones from each others and actually in the past we have shared our opinion about English submissions from a global perspective.

*Affilitiation* can be dropped yes but it is useful in order to know the context of production: is the proposal coming from Mexico, Spain, UK, Canada? But I guess we can find out by googling the author. 

The form would allow us to perform some statistical analysis after storing the data in a spreadsheet and maybe keep the track of the submission by adding more private fields - plus what Jessica just mentioned. But I am happy with a template that peopole can copy and paste in an email.

**Comment by mdlincoln** [comment]
Definitely do a form - I agree with @JMParr it's easier for users and much more professional than asking them to cut/paste.

**Comment by spapastamkou** [comment]
I also find the idea excellent. I believe a summary in English in case of a Spanish or French submission would be useful because it is good to have knowledge of what is going on in the linguistic areas covered by each team.

**Comment by arojascastro** [comment]
Hello everybody, I am on holidays until next Monday. I'll re-read the messages and try to sum up some conclusions before acting -- sharing a newer proposal. Help is welcomed!

**Comment by acrymble** [comment]
@arojascastro thanks so much for your work on this and suggestion. By way of trying to help, I suggest the following categories (based on your original idea):

- Your name (text box - short)
- Email address (text box - short)
- Submission language (dropdown box, English, French, Spanish)
- Proposed lesson title (text box - short)
- Abstract (text box - multiline)
- Case study description (text box - multiline)
- Learning outcomes (3 text boxes - short)
- Originality (text box - multiline)
- Global Reach (text box - multiline)
- Sustainability (text box - multiline)
- Research Phase (dropdown box - acquire, transform, analyze, present, sustain)
- Research Area (dropdown box - apis, python, data management, data manipulation, distant reading, set up, linked open data, mapping, network analysis, web straping, digital publishing, other)
- Estimated submission date (date field)
- Lesson will use open technology and data without cost to the reader (check box)
- Anything else you would like to tell the editor at this stage (text box, multiline)

**Comment by arojascastro** [comment]
I think it is good and I thank you for taking the lead - I'm back from holidays but still not fully working on *PH* until September. Did we agree on a form in the end?

**Comment by acrymble** [comment]
Yes a form. Do we have a preferred form provider?

**Comment by drjwbaker** [comment]
Can we not just use a template? https://github.com/programminghistorian/jekyll/issues/936#issuecomment-404513043 No need to force potential authors to give data to a provider for no real benefit.

**Comment by acrymble** [comment]
Sorry I didn't predict @drjwbaker 's comment when I was working, but I put together a test Google Drive form just to try it out in form format: https://docs.google.com/forms/d/e/1FAIpQLSeqtbftJnltGiWU0d_u5bDm6BvlWjo1zJsLIjcpt4-Xzw-5Zw/viewform?usp=sf_link

Would be good for someone to try it and let us know if it takes too long, is confusing, otherwise needs revision.

My own preference is a form because I think it's cleaner from a user perspective. You also HAVE to follow it, which meets @arojascastro 's goal of standardisation. But we can debate the best approach.

**Comment by drjwbaker** [comment]
Okay, but if we go with a Google Form I'd argue that we **need** to offer an alternative ("Alternatively, if you'd rather not use a Google Form please fill in this template and email to EDITOR NAME"). We'd be failing to reflect our own values (e.g. internalization guidelines) were we to assume that every potential author is happy to give their data to a US Google.

**Comment by acrymble** [comment]
At the moment their alternative is to email Jess on her gmail account. So I'm not sure our alternative is any less Google. Is this coming out of something you've encountered? I've never heard anyone unwilling to use a form on a website for security reasons. Just trying to understand your concern here so we can find a solution that's easy for us and for users.

**Comment by drjwbaker** [comment]
Yes, so all we need to say is that the alternative is to email Jess and please use our template when doing so.

And yes, it is coming out of people not wanting to fill out a Google Forms / unnecessarily use Google services, which I've encountered in Library Carpentry, teaching, and friendship circle contexts.

**Comment by acrymble** [comment]
Can we particularly get feedback on this from @mariajoafana and @alsalin who will be the primary users of whatever solution we come up with in their roles as Managing Editor? What would be your preference on a system for receiving submission pitches?

**Comment by alsalin** [comment]
I'm ok with google forms, but could we add in a submission page using GitHub? It could then send the forms to the PH google account? I'm not sure that fixes anything but just another idea.

**Comment by drjwbaker** [comment]
(can I just add, I'm not being willfully awkward here I'm just trying to encourage us not default to a Google service in a situation where I'm not sure we necessarily need it, even though I can see the advantages of it)

**Comment by acrymble** [comment]
Is there a Github powered option?

**Comment by acrymble** [comment]
Can someone try the Google Form with some fake data just to get a sense of how onerous it is for a potential author? I'm a bit worried it's too long to do.

**Comment by arojascastro** [comment]
I just submitted a fake proposal. It is long, true, but doable. I think it is good to collect as much as data as possible and it will really help us to take control. If someone really wants to write a lesson, it will fill in the form for sure - shouldn't be a problem to spend 10 minutes. Right? Otherwise, we could reduce the three questions on originality, global reach and sustainability into one. Or maybe delete them? But I think it is doable after all.

**Comment by acrymble** [comment]
Thanks @arojascastro . I didn't get alerted in my email, which I assumed I would. So I guess we'd have to make sure it was set up properly. I'm inclined to agree that we could cut those three questions, and leave that for the editor to encourage during the review stage. I don't know how much they help us come to a decision at that early stage.

**Comment by arojascastro** [comment]
Yes, or maybe just leave at the end a free input about originality, sustainability and global reach 

Any other comments to the editor --> Comments on originality, sustainability and global reach to the editor

But not required.

Or keep those questions but make them unrequired.

**Comment by arojascastro** [comment]
Also, maybe in the header of the form we could add the link to the guidelines for authors or copy and paste the text 

> We welcome tutorials relevant for the humanities, pitched at any level of technical aptitude and experience that focus on one problem or process, can be sustainable in the long term, and are addressed to a global audience. The scope and length of the tutorial should be appropriate to the complexity of the task being taught. Tutorials should not exceed 8,000 words (including code) without the explicit permission of the editor, which will be granted only in exceptional circumstances. We expect that most lessons will be between 4,000 and 6,000 words. Longer lessons may need to be split into multiple tutorials. 

Or is it too much information?

**Comment by JMParr** [comment]
I would say "tutorials should not exceed 8,000 words (including code). Most
lessons will be between 4,000 and 6,000 words, etc.

I understand the desire to be direct, but I think "without the explicit
permission of the editor, etc" might rub potential authors the wrong way.

**Comment by alsalin** [comment]
@acrymble

**Comment by alsalin** [comment]
ack sorry for the button mashing - @acrymble in a quick search, i found some code snippets for creating forms in GitHub - but I'm not GH expert.

**Comment by acrymble** [comment]
@alsalin can you send some links?

@JMParr that text is just pasted from our Author guidelines. If you think it needs changing maybe you can suggest an alternative?

**Comment by alsalin** [comment]
@acrymble https://medium.com/@asjas/using-formspree-io-on-your-github-pages-a60c290d1ee was one that I saw and in the comments are listed a few other options that I've seen. Again - not a GH master, so not sure how well this could work.

**Comment by JMParr** [comment]
I'll take another look, Adam. Maybe I'm overthinking this.

**Comment by mariajoafana** [comment]
If a form in GitHub is doable that'll be fine, moreover if we can get alerts. If not Google forms is fine. This form will be particularly useful for the new incoming original Spanish lessons. If we have approved it I'll like to translate it and ask our Bogotá's workshop participants to pitch their lesson filling the form first.

**Comment by acrymble** [comment]
Nobody has found a form solution, so I'm going to suggest a simple markdown file that we ask people to download and email us.

**Comment by JMParr** [comment]
Seems fine to me.

**Comment by acrymble** [comment]
This requires changes to the authors-guidelines.md file, which is currently awaiting a review on a pull request: https://github.com/programminghistorian/jekyll/pull/998

I don't want to complicate things by changing this file in two different locations, so this will have to wait until that pull request is approved.

The form is here: 
[Lesson Query Form.txt](https://github.com/programminghistorian/jekyll/files/2407560/Lesson.Query.Form.txt)

**Comment by mariajoafana** [comment]
I'm uploading here the lesson template in Spanish for review by Spanish language team . Once approved @jenniferisasi will create the pull request to add this and other modifications to the Spanish language author guidelines according to the English-language page 
[Formulario.Consulta.Lección.txt](https://github.com/programminghistorian/jekyll/files/2420046/Formulario.Consulta.Leccion.txt)

**Comment by jenniferisasi** [comment]
Thanks @mariajoafana. I made two little changes to the wording, but it's good to go. However, @acrymble do we want to include the French managing editor info? We are asking about the submission language so, though not online yet, I thought the addition will save us a later edit/commit. 

As I understand, I will wait to #998 to be closed to work on including this form on the guidelines, together with the changes you've made there.

**Comment by acrymble** [comment]
@jenniferisasi we don't have a French managing editor yet, I don't think.

**Comment by jenniferisasi** [comment]
Hi @acrymble, have you added the Lesson Query Form.txt anywhere in the guidelines? I made the changes for submission (with the markdown guide) but I can't find the lesson proposal form - just wanna make sure I'm keep track to implement all changes

**Comment by acrymble** [comment]
@jenniferisasi no I haven't. You could add both of them in one pull request and then we could close this. They just need to be put at an appropriate spot in the Author Guidelines files.

**Comment by acrymble** [comment]
@mpuren @spapastamkou can you give us an estimate on publishing the French pages? We could then do this at the same time so that the pages in different languages stay syncronised.

Then we can close this issue.

**Comment by spapastamkou** [comment]
I upload the file with the template in FR so that @mpuren has access to take a look. We can update the relevant page while we review our branch with @mdlincoln. Does that help, @acrymble ?
[Formulaire.Tutoriel.txt](https://github.com/programminghistorian/jekyll/files/2551006/Formulaire.Tutoriel.txt)
