### ISSUE TITLE
dropdown menus for 'Contribute'?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#94]
I just came across the updated reviewer guidelines (great, love em). But I didn't see them on the site. What are thoughts on having an expandable 'Contribute' menu that makes it clearer the various pages related to submissions, authorship, and reviewing?

* Contribute.md
* Submissions.md
* Reviewer Guidelines.md

If these had links in the main navigation along the following lines, they would be more visible for visitors and editors:

* Get Involved
* Instructions for Authors
* Instructions for Reviewers

Does that sound desireable, and worthwhile?

**Comment by ianmilligan1** [comment]
I think that's a great idea - both desirable and worthwhile to me.

**Comment by drjwbaker** [comment]
Seconded. I'm sure prospective first time PH authors would be grateful to you for making transparent the process their work will go through. Perhaps you could get the opinions of the Summer Fellows? (given that I assume they are all first time authors)

**Comment by wcaleb** [comment]
Instead of adding javascript for a drop-down menu, would a streamlined "Get Involved" page that links more clearly at the top to Instructions for Reviewers and Instructions for Authors satisfy the same goals?

**Comment by acrymble** [comment]
That is fine, but may require some thinking about design. Is it a matter of
no javascript desired? Alternatively, maybe we think about expanding the
menu?

On Mon, May 18, 2015 at 2:31 PM, W. Caleb McDaniel <notifications@github.com

**Comment by wcaleb** [comment]
It's not that Javascript or CSS would be impossible, but it will create more complexities (for example, to make everything operable in multiple browsers, as well as on mobile devices). I think the text on all of these pages could be streamlined, and if level-1 and level-2 headers were used more sparingly and tied clearly to structure, then it may be possible even to combine all three pages into `contribute.md`, and then use a table of contents at the top to "jump" to specific sections on instructions of authors, reviews, etc. Here's a [quick mock-up](http://programminghistorian.org/new-contribute).

**Comment by acrymble** [comment]
If that were punctuated by some of the images Allison has been finding to
separate the sections visually, I think that could work well.

On Mon, May 18, 2015 at 4:38 PM, W. Caleb McDaniel <notifications@github.com

**Comment by ianmilligan1** [comment]
Agreed: I think that would work really well.

**Comment by acrymble** [comment]
I'd like to continue this as #114
