### ISSUE TITLE
Elementary documentation on translation of FR infrastructure file names and basic terms

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#940]
_(Update 27 July 2018: this ticket was originally created to document the process of translation of the FR infrastructure files. Its creation was also part of the tasks of #864. The ticket has proved to be ill-conceived as various issues arise for which distinct tickets are needed. This ticket has been renamed in order to reflect exactly its current content and will soon be closed. Part of its content could be found on the Wiki as part of larger documentation of the FR translation issues. Please see also #947, #951. Thnx to @acrymble and @walshbr for remarks and suggestions)_

This ticket has been created in order to provide basic documentation / info on french translations (to share with @mpuren); host questions towards the rest of the PH team as they arise during the translation process. It is complementary to #836 that deals with technical questions of the fr translations of the infra pages. 

To whom might be concerned, below are provided the file names of the fr directory preceded by their equivalents in the en directory.

about => apropos
author-guidelines => consignes-auteurs 
contribute => contribuer
editor-guidelines => consignes-redacteurs
feedback => feedback 
index => index
lesson-retirement-policy => politique-retrait-lecons
lessons => lecons
project-team => equipe-projet
research => recherche
reviewer-guidelines => consignes-evaluateurs

**Comment by spapastamkou** [comment]
##Contributors: basic terms choices  

This part refers to following terms: author, reviewer, editor and, in general, to terms in relation with the organisation of a scientific journal.  
Main reference text: Guide pour les revues numériques de l'ENSSIB (Ecole nationale supérieure des sciences de l'information et des bibliothèques), 2001, http://revues.enssib.fr/titre/1ed/4organisation/1comites.htm  

EN => FR
author => auteur
reviewer => évaluateur
editor => rédacteur

- auteur: rien de particulier à signaler   
- évaluateur (pour reviewer): le terme a été préféré aux termes "lecteur" (lié au "comité de lecture") ou encore "expert" pour s'aligner à la traduction française de "open peer review": évaluation ouverte par les pairs. Toutefois, les autres termes, notamment le terme "expert" peuvent se rencontrer au fil des textes notamment par souci d'éviter les répétitions du seul terme "évaluateur".   
- rédacteur (pour editor):
En français, éditeur = 
1) l'équivalent de publisher en anglais (sens principal du mot); 
2) le responsable de la direction d'un ouvrage collectif ou d'une revue (anglicisme) 
(cf. http://revues.enssib.fr/titre/1ed/1editeur/1definition.htm ).   
  
L'équivalent de "editor" en français dans le cadre d'une revue est "rédacteur".   
 
Texte de référence: _Guide pour les revues numériques de l'Ecole nationale supérieure des sciences de l'information et des bibliothèques_, 2001, notamment "Organisation du travail éditorial" : http://revues.enssib.fr/titre/1ed/4organisation/1comites.htm 
et "Editeur" http://revues.enssib.fr/titre/1ed/1editeur/1definition.htm   


##Gendered common names and inclusive writing  
If we take the example of the roles attached to contributors, the problem in French is that these terms are gendered.  
In small contexts, such as the menu, I used the male form (auteurs, évaluateurs etc) as inclusive for all (according to the rule of the Académie française) and mainly bcz a Menu provides limited space.  

Wherever the context of a phrase allowed it, I used both genders in parataxis or opposition: for example, to translate editor, I used "le rédacteur ou la rédactrice". For a concise presentation in the context of the team roles, I used "rédacteur/rédactrice" (but I avoid to do so in the flow of a phrase). 
Where the context did not allow for, I used the male as inclusive for all: "Nous tenons à créer une communauté diversifiée et inclusive de rédacteurs, d'auteurs et de lecteurs". In this case, using two French words for each English term would give one much too long and not really elegant phrase.    

J'ai évité l'écriture inclusive avec utilisation du point milieu (les électeur·rice·s ou les citoyen·ne·s) ou du point (tou.te.s) car elle n'est pas très esthétique, pas vraiment généralisée et n'est pas une norme (je privilégie à la place quand cela est possible l'utilisation des deux termes en juxtaposition, cf. plus haut) .    

Pour l'accord de genre entre nom et adjectif, quand il existe plusieurs noms de genre différent, j'ai suivi les règles classiques.   

Pour les "basic terms" (ceux du menu "Contribuer"), il est à noter la question qui se pose pour "auteur" et "auteure". "Auteure" n'est pas un mot officiellement établi en France ni reconnu par l'Académie française, bien qu'utilisé. Cependant, le terme est établi et couramment utilisé en français du Québec. Il me semble donc que nous pouvons utiliser ce terme (et d'autres dans le même registre) de manière légitime.   

Where possible, I use(d) gender neutral terms (lectorat for readers, for example). 

cc @mpuren (on en discute si besoin:)) Sorry to all for this being half English half French, this comes from notes taken during translation.

**Comment by spapastamkou** [comment]
of interest to @programminghistorian/spanish-team : I think @drjwbaker 's bio in ph_authors.yml needs a little update in Spanish

Qs for all @programminghistorian/project-team on about.md file (for elements of the About page common to all editions) : 
- link to RCUK's website has changed. Redirection works (15 secs). Do we keep the same link or replace with new one? 
- link to HEFCE web site: works but the web site is "historical and no longer maintained" bcz HEFCE closed in March 2018. 
- how about adding a bit of European context (Guidelines to the Rules on Open Access to Scientific Publications and Open Access to Research Data in Horizon 2020)? 
<http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-pilot-guide_en.pdf>

**Comment by acrymble** [comment]
@spapastamkou it might be worth documenting some of these decisions you want to remember (like what form of terms to use) on the Wiki. Tickets like this one tend to get forgotten once they are closed. The Wiki is a place where we keep things relevant to the Project Team which we might need to refer to more regularly: https://github.com/programminghistorian/jekyll/wiki

**Comment by acrymble** [comment]
@spapastamkou Thanks for pointing out the link issues on the /index page. The HEFCE and RCUK links were mentioned because they have policy implications for any UK-based authors. Essentially, your work will only 'count' in future if it is open access. This statement merely notes that we are compliant. If we need to highlight compliance for other regions then I agree it's worth adding more notes/links. But we should stay focused on that compliance message rather than advocating widely for open access policies around the world (which is important but probably belongs somewhere else)

**Comment by mpuren** [comment]
@spapastamkou 
##Gendered common names and inclusive writing: I was thinking about how translating gendered terms in French, and I propose to open a dedicated ticket on this subject (if you agree, I'll open it). Because this is a current and important debate in the French-speaking community (especially in France) and we should be totally clear on this subject and make decisions that we'll be able to follow in the future. For instance, I know that the "écriture inclusive" is not widely used for now - and it is still a "weird" way to write gendered terms for French people (and surely for French-speaking people in general), but I'm wondering whether we shouldn't adopt it if we think that the inclusive writing will become the norm in the future. So if you agree, I'll open a new ticket to give the possibility to other French-speaking people to give their opinion on the subject. 

##Wiki: We should document our decisions in the wiki, so we'll be able to retrieve them easily. But @acrymble I'm not sure in which section of the wiki we can document our choices.

**Comment by mpuren** [comment]
@spapastamkou Dernière chose : doit-on employer la nouvelle orthographe qui rentre en vigueur en septembre? En ce qui me concerne, je ne suis pas particulièrement pour, mais cela se discute évidemment.

**Comment by spapastamkou** [comment]
@mpuren about inclusive writing I provide further context: I think that the decision can be safely done by the editors because there are the theoretical foundations (= rules set by the Office québécois de la langue française:
- Formation de noms féminins http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?Th=1&Th_id=358&niveau=
 - Principes généraux de la rédaction épicène http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?Th=2&t1=&id=3912
- some elements about the debate in the Québec where the issues have been discussed (and resolved) http://andreracicot.ca/ecriture/ 

I tried to apply the basic elements except for the use of the "point médian".  If we are to be strict on this point, then according to the Office québécois de la langue française, " l’utilisation des doublets abrégés (formes tronquées) n’est pas recommandée. Toutefois, étant donné que la rédaction épicène s’avère trop souvent mise de côté au profit du masculin générique par manque de place, l’Office juge que l’emploi des doublets abrégés peut alors devenir une option dans les contextes où l’espace est restreint (par exemple, les tableaux, les formulaires, les publications dans des plateformes de microblogage) ainsi que dans les écrits de style télégraphique".
==> in this case, for example, one of the phrases I have translated could take this form: "Nous tenons à créer une communauté diversifiée et inclusive de rédacteurs et rédactrices, d'auteur(e)s et de lecteurs et lectrices". 

If you 'd rather that we formalize and follow systematically, I propose to follow these rules that also inspire the ones proposed in France on the matter as well (see here https://www.ecriture-inclusive.fr/)
What do you think?

**Comment by mpuren** [comment]
Thank you @spapastamkou for these precisions, that's clearer for me. And I agree: we can follow the rules proposed by the Office québécois de la langue française.

**Comment by arojascastro** [comment]
This is very interesting for the Spanish team as well! We did not think about *inclusive language* in gender terms yet. I think we use *masculine* as *universal*, but at the moment there is a lot of debate about the need of using feminine terms as well in Spain (I do not know about other countries like Mexico or Colombia).  

The English version does not have this issue, it is a translation problem e.g. "reader" or "usuario" has no gender in English while in Spanish could be "lector" and "lectora" or "usuario" and "usuaria". 

I think it is worth revising. What do you think @vgayolrs @mariajoafana @jamotilla @jenniferisasi ?

**Comment by acrymble** [comment]
As we discussed in the Skype call, this ticket does not contain a single issue that can be completed and closed. That means the ticket will always remain open.

@spapastamkou can you please identify any discrete issues in this thread and open new tickets for them? This will help us keep organised as a group.

If you think there is one discrete issue here, you could change the name of the ticket to reflect that.

**Comment by arojascastro** [comment]
Sure! Yes, that's more convenient. I'll open a new for the Spanish case and discuss there when I am back from holidays (unless someone else can open it earlier).

**Comment by spapastamkou** [comment]
I will do this, @acrymble , the soonest I can work on it is tonight.

**Comment by mpuren** [comment]
@spapastamkou I opened a new ticket concerning the translation of gendered terms in French. Do you think we need to open a ticket on "les nouvelles règles orthographiques" for French?

**Comment by amsichani** [comment]
Just a minor note : as for the FR translation of file names, once finished it could/will live also [here](https://programminghistorian.org/translation-concordance), alongside the translated ES filenames.

**Comment by spapastamkou** [comment]
Thanks a lot for the useful note @amsichani. 
For the new orthography rules, @mpuren, I do not personally see any issues raised but if you think a ticket would be useful in relation with the PH, it is really up to you to decide.
