### ISSUE TITLE
DH2018 papers to /research please

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#942]
If you gave a paper about PH at DH2018, please add it to /research

@mariajoafana I know you gave one. I don't know if anyone else did.

**Comment by jamotilla** [comment]
@acrymble i think only @mariajoafana talked about PH, in my case i mentioned the project and talked about the possibilities that our tutorials give to scholars that work with historical data sets.

**Comment by mariajoafana** [comment]
I've uploaded my paper. I think no one else presented on PH so I'm closing this issue
