### ISSUE TITLE
Accidental commit on main branch

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#943]
So I managed to make an accidental commit on the main branch https://github.com/programminghistorian/jekyll/commit/601f10c08ea37d056750e55d6184eec34e68302d#diff-0c23acdb6f8128d6724d9e248b32888e I didn't think this was possible?

(note this also needs very minor Spanish translation)

**Comment by mdlincoln** [comment]
Currently, team administrators have the ability to push to the protected `gh-pages` branch. I kept this as an option in case of emergency fixing needed without needing to go through the PR/review process.

Just be careful in the future!

**Comment by drjwbaker** [comment]
Sorry!

**Comment by mdlincoln** [comment]
And congrats on your promotion @drjwbaker !!! 🍾

**Comment by drjwbaker** [comment]
@arojascastro One word here needs a translation 😄
