### ISSUE TITLE
keeping unpublished french pages in sync

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#946]
I just realised (because James updated his bio) that we're in the habit of requesting updates to Spanish pages when we update an English one. But because the French pages are all being developed offline and are currently unpublished, those changes will not necessarily be noticed and incorporated into the French site.

We either need to start publishing (and not advertising) French pages so that the team can get used to asking for French translation updates. Or we need another mechanism for making sure that the French pages aren't out of date as soon as they are published.

**Comment by drjwbaker** [comment]
We could moratorium changes core non-lesson pages until the FR team are ready? The mechanism for this would be to stage pull requests but not action them until FR are ready. Downside is that it might put unrealistic time pressures on the FR team to complete translations.

**Comment by mdlincoln** [comment]
This is an important challenge @acrymble. 

I agree with @drjwbaker that probably the most tenable solution is a moratorium on changing the core pages like editor guides etc., while maybe saving for last some more mutable files like the `ph-authors.yml`. I can make sure to periodically merge new changes in the english/spanish pages over to the french translations branch, to ensure that they are working with the most up-to-date content for `ph-authors.yml` in particular.

This would mean pausing any _merging_ of #951 #915 #905 #918 unless they can be done _before_ the French team translates the impacted pages.

**Comment by drjwbaker** [comment]
I can live with a hiatus on #951 #915 #905 #918 *if* we have clear timescales for the FR work to happen (without, that is, creating unrealistic expectations)

**Comment by mpuren** [comment]
Can we give you clear timescales by the end of the week? I want to be sure we have realistic expectations with @spapastamkou.

**Comment by acrymble** [comment]
#905 - Npov policy should be possible on the Wiki only.

The tickets about sponsorship can also be put on the Wiki to begin with, so we don't need to hold those up.

**Comment by acrymble** [comment]
Are there any French pages we can start publishing soon? I don't think we need them all to go live in one pull request, do we? As long as it's not linked in the menu and there is a holding page on the /lessons page, then I think it's ok to publish, no?

**Comment by spapastamkou** [comment]
The file related to #955 and the one corresponding to the page mentionned in #951 are translated and committed in the FR branch actually. Updates can be done quickly if needed. What could soon be published in FR are the index and about pages, the 404 page, the parts of the yml files. Translation of the editors guidelines is also in progress but needs some time. If a modest start is not a problem to start publishing, then we can. In any case, bios can be updated with no problem, but please confirm whether it is all right to do it in the files that are currently in the FR branch.

**Comment by acrymble** [comment]
Thanks @spapastamkou this sounds great. It looks like you are nearly finished translating these core pages! You can definitely do the updates on the French branch. As long as you make a note of it on any relevant tickets (eg, #955 - Update Jennifer's bio) so that we know it's been done.

**Comment by acrymble** [comment]
we seem to be doing ok on this as long as editors send messages to @spapastamkou and @mpuren when they do pull requests. So hopefully we can continue as is. Closing this because I think we've solved this through common sense.
