### ISSUE TITLE
Treasurer & Sponsorship Coordinator

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/jekyll#948]
We need a two new roles to handle the obligations that arise from accepting donations and sponsorship as listed in the draft statement at https://github.com/programminghistorian/jekyll/issues/915#issuecomment-408108041

These are:
- Treasurer. Looks after the money (in and out) from donations and sponsorship, sorts out reimbursements/payment when money is spent.
- Sponsorship Coordinator. Point of contact for potential and existing sponsors, monitors Patreon, negotiates sponsorship.

The first person needs to be at the place where the money will likely be held (see private discussion). The second can be anyone. They can in the first instance be the same person. Thoughts?

**Comment by acrymble** [comment]
I'd say same person until we know how much work it is. We'll need a reporting mechanism to make sure it all stays above board.

**Comment by drjwbaker** [comment]
Okay. And agreed. These are on my todo list :)

**Comment by walshbr** [comment]
@drjwbaker We discussed this and the other funding-related issues in the call. This one, in particular, we had strong feelings about. The consensus and received wisdom based on experiences at Bogotá was that we should probably have one person do these two jobs. And that this one person should be the person who is at whatever institution is able to offer a budget line for PH. The idea being that the financial office at Person A's institution is only going to want to talk to Person A about the budget issues and will be unlikely to give time of day to someone from another institution. Does that make sense as a way of proceeding? So I think the recommendation was that this might be on hold and then quickly resolved once we get clarity about #878.

**Comment by drjwbaker** [comment]
Agreed. Thanks to the team for their input. Leave open for now?

**Comment by acrymble** [comment]
Can we close this on the assumption that this has to be @drjwbaker in the first instance? Or is that a false assumption?

**Comment by drjwbaker** [comment]
Okay. Shall I add the roles to my profile?

**Comment by drjwbaker** [comment]
https://github.com/programminghistorian/jekyll/pull/1035 closes this.
