### ISSUE TITLE
Link issues on the /about page

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#951]
The issues are relevant to the [Gold Open Access part of the page](https://programminghistorian.org/en/about#gold-open-access) and were first raised in #940. 

I copy/paste exactly from there: 
- link to RCUK's website has changed. Redirection works (15 secs). Do we keep the same link or replace with new one?
- link to HEFCE web site: works but the web site is "historical and no longer maintained" bcz HEFCE closed in March 2018.
- how about adding a bit of European context (Guidelines to the Rules on Open Access to Scientific Publications and Open Access to Research Data in Horizon 2020)?
http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-pilot-guide_en.pdf  

And @acrymble 's comment: "The HEFCE and RCUK links were mentioned because they have policy implications for any UK-based authors. Essentially, your work will only 'count' in future if it is open access. This statement merely notes that we are compliant. If we need to highlight compliance for other regions then I agree it's worth adding more notes/links. But we should stay focused on that compliance message rather than advocating widely for open access policies around the world (which is important but probably belongs somewhere else)"

I share this point of view as well, give emphasis mainly to the message and be able to provide more links (European and Latin American context maybe?). 

My question is: are we willing to correspondingly modify this part of the page? If so, how do we organise this work?

**Comment by acrymble** [comment]
The first question should be: which countries/regions have mandated open access publishing requirements?

**Comment by spapastamkou** [comment]
I did not forget this and I have worked on it but I am on a lot of things currently. Sorry for the delay, I will come back very shortly.

**Comment by acrymble** [comment]
@spapastamkou can you provide us an update on this? Is this something we're still going forward with? Or should we close this issue?

**Comment by spapastamkou** [comment]
Well, here is a much delayed update: Once I started work on the national policies in Europe, things started moving as a result of some countries adopting the S plan (of which France). So I waited till it's more stable. I can complete the PH part in a general way on the basis of info provided [here](https://www.coalition-s.org/about/) if you think it's worth it.

**Comment by spapastamkou** [comment]
I propose following formulation for [this part](https://programminghistorian.org/en/about#gold-open-access); if ok, I make a PR for EN and FR pages and ask for an ES translation. If a more pertinent EN formulation can be proposed, please edit directly and insert in the text below.  
 
"All submissions to the Programming Historian are published under a Creative Commons ‘CC-BY’ license. This adheres to a ‘Gold’ open access model of publishing, which is fully compliant with the Berlin Declaration on Open Access to Knowledge in the Sciences and Humanities, RCUK funding and HEFCE publishing requirements for scholars in the UK, as well as the Canadian Tri-Agency Open Access Policy, **and the European Commission/European Research Council supported Plan S**. ‘Gold’ open access means that the version of record is made freely available without subscription fee or restrictions on access. Authors are permitted to republish their tutorials anywhere".

**Comment by acrymble** [comment]
Thanks @spapastamkou.

Do you think it is still necessary to be explicit about these policies? We could for example simply have:

"All submissions to the Programming Historian are published under a Creative Commons ‘CC-BY’ license."

Or:

All submissions to the Programming Historian are published under a Creative Commons ‘CC-BY’ license. This adheres to a ‘Gold’ open access model of publishing. The version of record is made freely available without subscription fee or restrictions on access. Authors are permitted to republish their tutorials anywhere."

**Comment by spapastamkou** [comment]
Yes, it is better to be more brief compared to the current formulation. Option 2 is clear enough. I make a PR asap and ask for your review, @acrymble, then I will (at last:)) close this ticket.
