### ISSUE TITLE
Update Jennifer's bio 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/jekyll#955]
I am going to update my bio both in English and Spanish.

**Comment by drjwbaker** [comment]
We also need to think about FR https://github.com/programminghistorian/jekyll/issues/946

**Comment by spapastamkou** [comment]
I can update the bio in FR as well, the file has already been committed in our branch since some time actually. I will check with @mdlincoln how we'd best do

**Comment by jenniferisasi** [comment]
Sorry, I totally overlooked that talk about the FR team updates on #946.

**Comment by acrymble** [comment]
I think this has been updated, no? Can we close?

**Comment by spapastamkou** [comment]
updated in FR

**Comment by jenniferisasi** [comment]
Perfect, thanks!
