### ISSUE TITLE
Geocoding Historical Data using QGIS - truncated data file

### ISSUE THREAD

**Issue by sharonhoward** [programminghistorian/jekyll#957]
The AlumniCounties.csv file attached to this lesson appears to have got truncated somewhere during the publication pipeline. It ends at Merionethshire. I compared it to the version in ph-submissions/assets/ and that file looks complete (it has a further 24 rows of data).

**Comment by acrymble** [comment]
Thanks @sharonhoward I will check it out when I can.

**Comment by acrymble** [comment]
this has been fixed. Thanks @sharonhoward
