### ISSUE TITLE
Lenguaje inclusivo en PH es?

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#958]
Hola, 

A raíz de lo que está haciendo el equipo francés aquí https://github.com/programminghistorian/jekyll/issues/940#issuecomment-408056054 en relación con el lenguaje inclusivo (básicamente, desdoblar el masculino y el fememino, entre otras estrategias), he pensado que podríamos debatir si queremos reflexionar al respecto y/o hacer cambios o decir algo en nuestras guías para autores. 

Un ejemplo muy simple: 

"The Programming Historian en español publica tutoriales revisados por pares dirigidos a humanistas que quieran aprender una amplia gama de herramientas digitales, técnicas computacionales y flujos de trabajo útiles para investigar y enseñar. Estamos comprometidos en la promoción de una comunidad diversa de editores, autores y lectores."

Aquí creo que solo se podría desdoblar "comprometidos": "Estamos comprometidos y comprometidas en la promoción...".

Se podría hacer algo semejante con términos como: "revisor", "lector", "autor", etc. O no. Como preferáis, simplente creo que deberíamos posicionarnos.

¿Qué pensáis? ¿Podemos debatir pros y contras? @vgayolrs @mariajoafana @jamotilla @jenniferisasi

**Comment by vgayolrs** [comment]
Hola equipo!
Me parece  que el uso del lenguaje inclusivo en PH-es iría de acuerdo con una serie de políticas que tiene el proyecto en general y que se han discutido en diversos momentos (equidad de género, inclusión de la diversidad). De adoptarlo, concuerdo con @arojascastro en desdoblar los géneros cuando sea posible y no implique demasiadas repeticiones que pueden llegar a ser exageradas o cansar en la lectura. También se puede recurrir a formas como "las y los editores". Creo que el único problema que deberíamos evitar es forzar demasiado el lenguaje. Explico volviendo al ejemplo puesto por Antonio, me parece que ya sería demasiado: "Estamos comprometidas y comprometidos en la promoción de una comunidad diversa de editoras y editores, de autoras y autores y de lectoras y lectores..."
Y claro, por nada del mundo utilizar esos neologismos inclusivos como "bienvenides"...
¿Cómo la ven?

**Comment by arojascastro** [comment]
Mucho mejor lo que propones @vgayolrs - "las y los editores" etc. Supongo que hay varias estrategias. ¿A alguien le apetecería leer/investigar sobre el tema y proponer una lista de alternativas/estrategias?

**Comment by arojascastro** [comment]
También se podrían adoptar distintas estrategias en función del lugar: paratextos editoriales (en donde tenemos control) Vs tutoriales (en donde tenemos menos control) etc.

**Comment by jamotilla** [comment]
De acuerdo con lo que plantean @arojascastro y @vgayolrs, es necesario tener claridad en la materia.

**Comment by jenniferisasi** [comment]
Concuerdo en que debemos tomar una decisión. Una estrategia que evita la pesadez a la que alude @vgayolrs es el uso del colectivo, la actividad (?), el grupo, o lo abstracto: "El equipo editorial se compromete a promocionar la diversidad en la comunidad editorial, de autoría y de lectura" (queda algo forzado en este caso pero para hacernos una idea). Otra opción es el plural "nos comprometemos" 

@arojascastro creo que, de llegar a un acuerdo sobre los paratextos editoriales, deberíamos incluir un apunte en las guías para autores para que lo tengan en cuenta, de la misma forma que pedimos tener una audiencia global en mente?

**Comment by vgayolrs** [comment]
Hola de nuevo!
Creo que con lo vertido hasta aquí podríamos redactar unos breves lineamientos para la adopción del lenguaje inclusivo tanto para ir editando las páginas de PH-es que lo requieran así como para proponerle a las y los traductores y autores su utilización. Si les parece, puedo trabajar en ello en estos días.

**Comment by mariajoafana** [comment]
De acuerdo con los comentarios, quedamos pendientes de los lineamientos para continuar la discusión a partir de estos

**Comment by vgayolrs** [comment]
hola @arojascastro  @jenniferisasi @mariajoafana y @jamotilla !

Después de revisar varios manuales sobre lenguaje inclusivo (acá le dicen incluyente) que han estado publicando en varias dependencias de gobierno (acá es un tema muy sensible, pero cada manual es más aburrido que el anterior), encontré uno publicado por [INMUJERES](http://cedoc.inmujeres.gob.mx/documentos_download/101265.pdf) que no está tan mal y tiene 7 puntos a considerar para el lenguaje hablado o escrito.
Estos puntos son:

* *Emplear únicamente el sustantivo común*
* *Desdoblamiento en femenino y masculino*
* *Agregar la palabra persona o personal*
* *Sustituir el masculino genérico por un sustantivo que denomine a la institución o a la profesión o al colectivo de personas o al lugar sin una carga de género*
* *Hacer cambios en la redacción*
* *Parafrasear la idea original*
* *Nombrar en femenino cuando el referente es una mujer*

Pego abajo el texto con los ejemplos (habría que cambiarlos, por supuesto), pero creo que podríamos partir de estas siete propuestas para trabajar los lineamientos. ¿Me dicen qué les parece, falta o sobra algo? ¡¡¡Bienvenidas todas las ideas que se les ocurran!!!


> **Recursos para evitar el uso androcéntrico y sexista**
> 
> Una práctica muy común son las expresiones sexistas y androcéntricas en las profesiones, cargos y oficios en todos los ámbitos. Aún es posible encontrarnos con títulos profesionales de las mujeres en masculino o nombramientos laborales de éstas, también en masculino, por mencionar algunos casos. Por ello, lo que encontrarán adelante son algunos recursos para ser incluyentes a partir de ejemplos muy prácticos.
> 
> Veamos a continuación algunos de los recursos y ejemplos disponibles para evitar el uso androcéntrico y sexista en las profesiones, cargos y oficios.
> 
> *Emplear únicamente el sustantivo común*
> 
> Este tipo de palabras nos permiten ser incluyentes mediante la elección de la profesión, cargo u oficio, sin incluir algún artículo o adjetivo, como en los ejemplos siguientes:
> 
> Ejemplo:
> Serán 8 los marchistas mexicanos que asistirán en mayo a la Copa del Mundo de la disciplina en China [...]
> (La Afición, 9 de marzo de 2014:12)
> 
> Forma incluyente:
> Serán 8 marchistas mexicanos quienes asistirán en mayo a la Copa del Mundo de la disciplina en China [...]
> 
> *Desdoblamiento en femenino y masculino*
> 
> Ejemplos:
> Somos la cara amable del gobierno, del servidor público que te contesta y te resuelve lo que necesites. 
> (La Jornada, 28 de febrero de 2014:39)
> 
> Forma incluyente:
> Somos la cara amable del gobierno, del servidor y servidora pública que te contesta y te resuelve lo que necesites.
> 
> o
> 
> Somos  la  cara  amable  del  gobierno,  del  servicio  públicoque te contesta y te resuelve lo que necesites.
> 
> 
> La Secretaría de Educación Pública convoca a los diversos actores involucrados en la educación normal del país: maestros, padres de familia, alumnos, legisladores, investigadores y estudiosos de la educación, autoridades educativas locales, organizaciones de la sociedad civil y a todo interesado en aportar propuestas, [...]
> (El Financiero, 28 de febrero de 2014:39)
> 
> Forma incluyente:
> La Secretaría de Educación Pública convoca a los diversos actores involucrados en la educación normal del país: maestros, maestras, padres y madres de familia, alumnado, legisladoras y legisladores, investigadoras e investigadores y personas estudiosas de la educación, autoridades educativas locales, organizaciones de la sociedad civil y a toda persona interesada en aportar propuestas, [...]
> 
> *Agregar la palabra persona o personal*
> 
> Ejemplos:
> Con el propósito de coadyuvar a la profesionalización de los servidores públicos, así como de sus hijos, el gobierno del Estado, a través del Instituto de Innovación y Calidad Gubernamental,  suscribió  un  convenio  de  colaboración con la Universidad [...]
> (El Imparcial, 2 de abril de 2007)
> 
> Forma incluyente:
> Con el propósito de coadyuvar a la profesionalización del personal del servicio público, así como de sus hijos e hijas, el gobierno del Estado, a través del Instituto de Innovación y Calidad Gubernamental, suscribió un convenio de colaboración con la Universidad [...]
> 
> En este caso, el denunciante no está obligado a presentar pruebas de la falta ni se le pedirán sus datos personales. (Portal del consumidor. Profeco, 19 de marzo de 2014a)
> 
> Forma incluyente:
> En este caso, la persona denunciante no está obligada a presentar  pruebas  de  la  falta  ni  se  le  pedirán  sus  datos  personales. 
> 
> Los usuarios de este servicio tienen en su mayoría entre 21 y 40 años de edad, 60 por ciento son mujeres.
> (La Jornada, 28 de febrero de 2014)
> 
> Forma incluyente:
> Las personas usuarias de este servicio tienen en su mayoría entre 21 y 40 años de edad, 60 por ciento son mujeres.
> 
> *Sustituir el masculino genérico por un sustantivo que denomine a la institución o a la profesión o al colectivo de personas o al lugar sin una carga de género*
> 
> [...] ocho grandes arquitectos de la actualidad abrieron las puertas de sus casas como parte de la exposición “Donde los arquitectos viven” [...] 
> (Excélsior, 19 de marzo de 2014)
> 
> Forma incluyente:
> [...]  ocho  grandes de  la  arquitectura de la actualidad abrieron las puertas de sus casas como parte de la exposición “Donde los arquitectos y las arquitectas viven” [...] 
> 
> Ejemplos:
> Zuzul. Paraíso de los chinantecos. 
> (El Imparcial, 12 de abril de 2007)
> 
> Forma incluyente:
> Zuzul. Paraíso de la Chinantla.
> 
> El procedimiento abarca desde la presentación de tu queja, hasta el acuerdo entre tú y elproveedor, y serás acompañado durante todo el proceso por un abogado conciliador de Profeco.
> (Portal del consumidor. Profeco, 19 de marzo de 2014a)
> 
> Forma incluyente:
> El procedimiento abarca desde la presentación de tu queja, hasta el acuerdo entre tú y la empresa proveedora, y te acompañará durante todo el proceso una abogada o un abogado conciliador de Profeco.
> 
> Recuerda Price que en el devenir histórico de las empresas coloniales primero llega la infantería, siguen los ingenieros mineros y los agrónomos, después los misioneros y, por último, los antropólogos. 
> (La Jornada, 28 de febrero de 2014:21)
> 
> Forma incluyente:
> Recuerda Price que en el devenir histórico de las empresas coloniales primero llega la infantería, siguen la ingeniería minera y la agronomía, después los misioneros y, por último, la antropología.
> 
> Se trata de ingresos que el agricultor latinoamericano dejará de recibir por un producto que no podrá vender.
> (La Jornada, 28 de febrero de 2014:31)
> 
> Forma incluyente:
> Se trata de ingresos que el sector agricultor latinoamericano dejará de recibir por un producto que no podrá vender.
> 
> Locatel cuenta con 276 operadores telefónicos, entre ellos 45 psicólogos, 14 médicos y 17 abogados, quienes son capacitados constantemente. 
> (La Jornada, 28 de febrero de 2014:39)
> 
> Forma incluyente:
> Locatel cuenta con 276 personas operadoras, entre éstas 45 profesionistas en psicología, 14 en medicina y 17 en derecho, quienes son capacitadas constantemente.
> 
> *Hacer cambios en la redacción*
> 
> Ejemplos:
> Los  nadadores Mariana  Alvarado,  Amauri  Rodríguez, Mariana  Guerrero,  César  Uribe,  Susana  Escobar  y  Luis  González, destacaron en la primera jornada de la Olimpiada Nacional 2007. 
> (Noticias, voz e imagen de Oaxaca, miércoles 18 de abril de 2007)
> 
> Forma incluyente:
> Mariana Alvarado, Amauri Rodríguez, Mariana Guerrero, César Uribe, Susana Escobar y Luis González, destacaron en la primera jornada de natación de la Olimpiada Nacional 2007.
> 
> En este caso, el denunciante no está obligado a presentar pruebas de la falta ni se le pedirán sus datos personales.
> (Portal del consumidor. Profeco, 19 de marzo de 2014)
> 
> Forma incluyente:
> En este caso, tú no tienes la obligación de presentar pruebas de la falta ni se te pedirán tus datos personales.
> 
> Para  contrarrestar  la  creciente  incidencia  del  cáncer  de  mama, investigadores del Cinvestav del Instituto Politécnico  Nacional  (IPN)  desarrollaron  una  terapia  que,  dijeron, recuerda al caballo de Troya [...] Por estos hallazgos,  Daniel  Martínez  Fong  y  Rosa  Angélica  Castillo Rodríguez fueron galardonados [...]
> (La Jornada, 28 de febrero de 2014)
> 
> Forma incluyente:
> Para  contrarrestar  la  creciente  incidencia  del  cáncer de mama, el Cinvestav del Instituto Politécnico Nacional (IPN) desarrolla una terapia que, dijeron, recuerda al caballo de Troya [...] Por estos hallazgos, Daniel Martínez Fong y Rosa Angélica Castillo Rodríguez recibieron un galardón [...]
> 
> *Parafrasear la idea original*
> 
> Ejemplos:
> Francia tendrá su primer presidente nacido después de la Segunda Guerra Mundial, ya que Royal tiene 53 años y Sarkozy 52. 
> (El Imparcial, 23 de abril de 2007)
> 
> Forma incluyente:
> Francia recibirá  por  primera  vezen  su  presidencia  a  alguien que nació después de la Segunda Guerra Mundial. Royal tiene 53 años y Sarkozy 52.
> 
> Los  científicos lo  explican  diciendo  que  el  cerebro  tiene dos partes, y que cada una gobierna los músculos del lado contrario del cuerpo... 
> (Noticias, 9 de febrero de 2007)
> 
> Forma incluyente:
> Las  investigaciones  científicas  lo  explican  diciendo  que  el cerebro tiene dos partes, y que cada una gobierna los músculos del lado contrario del cuerpo... 
> 
> 
> El Código de Nuremberg insistía en que los científicos trabajando con seres humanos, tanto en la guerra como en la paz, debían obtener de ellos su autorización informada, [...] 
> (La Jornada, 28 de febrero de 2014:21)
> 
> Forma incluyente
> El Código de Nuremberg insistía en que la investigación científica  que  trabajara con  seres  humanos,  tanto  en  la guerra como en la paz, debía obtener su autorización informada, [...]
> 
> 
> Realizarán taller dirigido a empresarios, abogados, contadores, estudiantes de derecho, contaduría y a todos aquellos inmersos en la actividad económica y privada. 
> (Síntesis, 3 de marzo de 2014:14)
> 
> Forma incluyente:
> Realizarán taller dirigido a personas del ámbito empresa-rial, derecho, contaduría y a todas aquellas inmersas en la actividad económica y privada
> 
> *Nombrar en femenino cuando el referente es una mujer*
> 
> Ejemplos:
> La síndico segundo municipal 
> 
> Forma incluyente:
> La síndica segunda municipal
> 
> Cirujano oftalmólogo, Dra. Carmen Hernández Pérez
> 
> Forma incluyente:
> Cirujana oftalmóloga, Dra. Carmen Hernández Pérez
> 
> Noemí Coria García, Director de Administración y Finanzas 
> (El Financiero, 28 de febrero de 2014:15)
> 
> Forma incluyente:
> Noemí Coria García, Directora de Administración y Finanzas
> 
> L.A.F. Guillermina Sánchez Ruiz, Contralor 
> (El Financiero, 28 de febrero de 2014:11)
> 
> Forma incluyente:
> L.A.F. Guillermina Sánchez Ruiz, Contralora
> 
> Georgina Patricia Olavarría Cabrer, Presidente del Consejo de Administración 
> (El Financiero, 28 de febrero de 2014:13)
> 
> Forma incluyente:
> Georgina Patricia Olavarría Cabrer, Presidenta del Consejo de Administración
> 
> Secretario del Consejo Directivo, Lic. María Elsa Ramírez Martínez 
> (El Financiero, 28 de febrero de 2014:22)
> 
> Forma incluyente:
> Secretaria del Consejo Directivo, Lic. María Elsa Ramírez Martínez
> 
> A partir de esta revisión, debemos tener presente siempre que:
> •   Cuando nuestro referente sea una persona, deberemos aludirla de acuerdo con su sexo. Atender siempre de quién estamos hablando y cómo la denominamos. 
> 
> •   Las  reglas  revisadas  son  aplicables  sólo  a  aquellos  términos  con  los  que  aludamos  a  las  personas,  no  son aplicables a los animales ni a cualquier otro referente, a menos que éstos se personifiquen.
> 
> •   Al escribir o hablar, cuando el nombre de una profesión  o  cargo  está  formado  por  un  sustantivo  y  un  adjetivo,  ambos  deben  concordar,  es  decir,  en  masculino o femenino según el sexo del referente (la primera ministra, una ingeniera comprometida, una detective privada, etc.; mas no la primera ministro ni una ingeniero comprometido ni una detective privado, etc.).

**Comment by arojascastro** [comment]
¡Genial! Muchas gracias Víctor. Los siete puntos me parecen suficientes, aunque, como dices, podríamos añadir o sustituir algunos ejemplos de "cosecha propia". Además, tenemos que pensar dónde queremos añadir la sección (¿en qué guía?) y cómo implementamos las medidas en las guías y otros textos de soporte (si es necesario; yo creo que sí porque hay que predicar con el ejemplo).

(Este manual editado por el gobierno chileno también me pareció bien: https://www.mineduc.cl/wp-content/uploads/sites/19/2017/09/Manual-Lenguaje-Inclusivo-No-Sexista.pdf)

**Comment by vgayolrs** [comment]
De acuerdo @arojascastro , miraré también el manual que propones. Espero (uf, los pendientes!) en la semana tener una redacción más acorde a algo que tiene que ser sencillo.

**Comment by mariajoafana** [comment]
Buenísimo @vgayolrs 
Sobre lo que preguntas @arojascastro Se me ocurre que nos dividamos los textos de guías y otros entre todos y cada cual haga el ejercicio de implementar esto. Por otro lado creo que en todas las guía (revisores, autores y traductores, editores) deberíamos añadir la sección Lenguaje inclusivo.

**Comment by mariajoafana** [comment]
Una propuesta sobre el lenguaje inclusivo: https://sostenibilidad.semana.com/amp/carolina-sanin-una-propuesta-gramatical/35571?__twitter_impression=true

**Comment by acrymble** [comment]
This has been open and inactive for quite some time. Do we need to do anything so that we can close this issue? It strikes me as important.

**Comment by arojascastro** [comment]
We should write a section or a paragraph with some recommendations about inclusive language in our guidelines.

**Comment by mariajoafana** [comment]
I'm charge of writing the paragraph, will do this soon

**Comment by arojascastro** [comment]
¿Alguna novedad al respecto?

**Comment by acrymble** [comment]
This is a very old conversation. Is there some support the rest of the team can offer to help implement these ideas? @mariajoafana is about to go on sabbatical. Can anyone take over for her?

**Comment by mariajoafana** [comment]
Hola, disculpen la demora y desaparición con las cosas de PH, he tenido un mes complicado. 
Estuve trabajando en unas recomendaciones que podemos incluir en la guía para autores a partir del manual que compartió @vgayolrs y de la propuesta del artículo que les compartí de Carolina Sanín. 
No es tan fácil encontrar ejemplos para todos 7 puntos, pero esto son algunos que pueden ir ampliándose conforme encontremos más casos. Como verán no soy fan de "los historiadores y las historiadores", siguiendo el argumento de Sanín, pero obviamente esto está abierto a discusión.  

**Recomendaciones sobre lenguaje inclusivo **
En *Programming Historian* estamos comprometidos con publicar tutoriales que no reproduzcan lenguaje sexista y discriminador. Aunque reconocemos que hay varios debates alrededor del asunto y no hay un acuerdo al respecto, le pedimos a nuestros lectores que tengan en cuenta las siguientes recomendaciones: 

1. Al nombrar profesiones ambos géneros gramaticales se pueden incluir mutuamente.
	Ejemplo: 
En este sentido, es bastante frecuente que **las historiadoras** tengan que modelar eventos o procesos históricos como redes dinámicas. 
En este sentido, es bastante frecuente que **los historiadores** tengan que modelar eventos o procesos históricos como redes dinámicas. 

2. Emplear únicamente el sustantivo común. 
	Ejemplo: 
Los autores sostienen que para nosotros **los historiadores** sería mejor considerar estas categorías como discursos.
        Inclusivo:
Los autores sostienen que para nosotros **como historiadores** sería mejor considerar estas categorías como discursos.
		
3. Sustituir el masculino genérico por un sustantivo que denomine a la institución o a la profesión o al colectivo de personas o al lugar sin una carga de género
	Ejemplo: 
Es cierto que la idea clave aquí es la de control de autoridades, que es central para **los bibliotecómonos.** 
       Inclusivo:
Es cierto que la idea clave aquí es la de control de autoridades, que es central **en 		biblioteconomía.**

**Comment by acrymble** [comment]
I'm going to close this on 1 October 2019 unless someone says otherwise.

**Comment by rivaquiroga** [comment]
@acrymble, I'm closing this one. The result of this discussion will be part of https://github.com/programminghistorian/jekyll/issues/1424
