### ISSUE TITLE
Preferred endnote style

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#959]
We are currently in our Bogota writing workshop and someone has asked about our citation format. Newer lessons are increasingly using academic citations. Do we have a preferred style?

@mariajoafana @jamotilla and I are currently there advising writers.

**Comment by drjwbaker** [comment]
To be clear, is this about how to cite our lessons or how to write citations in our lessons?

**Comment by jamotilla** [comment]
@drjwbaker its about how to write citations in our lessons

**Comment by drjwbaker** [comment]
It is a good point. We don't have a style guide for that.

**Comment by arojascastro** [comment]
Well, we don't have pages, so we need to use endnotes. I think so far we have encouraged the use of highlighted blocks to add extra information. This is cool because translators make extensive use of footnotes. If both authors and translators use endnotes, then we have to distinguish them with "Nota del traductor" or similar. In any case, it would be good to be clearer in our author guidelines.

**Comment by acrymble** [comment]
What are our options for endnotes? I've grown up with Chicago Manual of Style. But I think they're locking down their guide increasingly behind a paywall. Are there any universal open standards that work well for history/humanities?

**Comment by drjwbaker** [comment]
Can we point authors at https://zbib.org/ to make a citation?

**Comment by acrymble** [comment]
For Chicago you mean?

**Comment by drjwbaker** [comment]
Yes. Unless someone is passionate about us using an alternative.

**Comment by arojascastro** [comment]
I am happy with Chicago. I am not sure which style we are already using in different sections though - e.g. the footer with the suggested citation or the research section. Maybe we should choose one style and apply it everywhere.

**Comment by acrymble** [comment]
Ok, I don't think we probably need a massive discussion on this, so I'll update the English guidelines with a brief note on this, and submit it for translation.
