### ISSUE TITLE
collate all scholarly activities

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#96]
Can members of the editorial team who have held an event, presented a poster, or published something scholarly-like about the project please help me compile a list here:

1) Adam Crymble, 'The Programming Historian 2', Digital Humanities 2012, Hamburg (July 2012).

2) Adam Crymble, 'Python Programming for Humanists', Day of Digital Ideas, University of Edinburgh (26 May 2015).

**Comment by wcaleb** [comment]
Since this is likely to be an ongoing list, could you create a Wiki Page to compile it? Leaving it as an open issue suggests that it's something that needs to be closed/fixed.
