### ISSUE TITLE
internal section links - instructions to author guidelines

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#963]
Another suggestion or query from Bogotá.

One of our workshop participants said she would like to be able to internally link to a section within another tutorial, since it provides a useful overview for her own tutorial and she wants to avoid duplicating instructions.

If it is not already possible, is there scope to make each markdown section linkable with a unique URL? Maybe heading levels 1-2 would be enough?

**Comment by acrymble** [comment]
An example of what I mean from Wikipedia: https://en.wikipedia.org/wiki/Digital_humanities#Textual_mining,_analysis,_and_visualization

The bit after the # is the section title.

**Comment by drjwbaker** [comment]
We do do this in some lessons. E.g. https://programminghistorian.org/en/lessons/visualizing-with-bokeh#categorical-data-and-bar-charts-munitions-dropped-by-country

**Comment by acrymble** [comment]
oh does it just work out of the box?

**Comment by drjwbaker** [comment]
Yeah. See https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#lists Basically if you do something like..

`______`
`# My first section`

`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`

`______`
`# My second section`

`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.`

.. with appropriate line breaks between sections, then the section links should appear. Most text editors that support markdown (e.g. TextWrangler) recognise headers like this, giving you extra functionality when writing/editing.

**Comment by acrymble** [comment]
Even better, I've just been told that if you hover over the title on a published lesson you get a little "link" icon that you can click to save that section's url to your clipboard.

<img width="836" alt="screen shot 2018-08-03 at 14 10 00" src="https://user-images.githubusercontent.com/646647/43661225-177118ac-9727-11e8-8946-b20c0db233bf.png">


It's been suggested by one of our Bogota workshop participants that this would be useful knowledge to have in the author guidelines.

**Comment by drjwbaker** [comment]
Correct. Re adding this to the author guidelines, what would be the purpose: to make it clear to authors to why we use this heading convention, to alert authors to the fact that they can link to sections of previously published PH lessons, or something else?

**Comment by acrymble** [comment]
Just to alert them that they can use this feature.

**Comment by drjwbaker** [comment]
We write at https://programminghistorian.org/en/author-guidelines#use-informative-section-headings:

![screen shot 2018-08-16 at 11 16 01](https://user-images.githubusercontent.com/4965300/44203084-d26d6480-a145-11e8-9404-524aa18df6c8.png)

We could add at the end: "Using this convention has the added advantage of creating a URL for each section of your lesson. For example, if you hover over the title of this section a link appears that points to the URL `https://programminghistorian.org/en/author-guidelines#use-informative-section-headings`. These links can then be used to readers to refer to specific parts of your lesson."

**Comment by acrymble** [comment]
I am going to close this on the advice of @mdlincoln that we stop tinkering so much with our guidelines! Thanks @drjwbaker for pointing out this solution.
