### ISSUE TITLE
Correct typo in Spanish translation of tutorial about AntConc

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#965]
I was alerted on Twitter about a typo here: https://programminghistorian.org/es/lecciones/analisis-de-corpus-con-antconc#operador--o

I think 

*Tarea: busca _she*

should be changed to 

*Tarea: busca she|he*

Because the original looks like 

*Task: Search on she|he.*

**Comment by acrymble** [comment]
this has been fixed.
