### ISSUE TITLE
Weird visualization in English tutorial on Antconc

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#966]
I'm revising a typo in the Spanish translation and I found out something weird in the original: https://programminghistorian.org/en/lessons/corpus-analysis-with-antconc#the--operator-or

This paragraph is visualized weirdly, right? It seems it's kinf of splitted into two columns:

![captura de pantalla 2018-08-04 a las 12 07 17](https://user-images.githubusercontent.com/7340111/43675121-42c9c4aa-97df-11e8-8efa-a38c534b7536.png)

**Comment by drjwbaker** [comment]
Good spot. I think the pipe between 'the she' and 'he search' has caused the text to format into two columns.

**Comment by acrymble** [comment]
tried to fix. Someone please review the pull request.
