### ISSUE TITLE
Problem with preview in Spanish original

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#967]
We have received our first original proposal in Spanish. The file is here: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/lecciones

We divided the contents in two directories:

- lecciones (original)
- traducciones (translations)

I believe the preview of the lesson only works if the file is in `traducciones`,  right? @mdlincoln 

At the moment we have these:

- (not working) http://programminghistorian.github.io/ph-submissions/es/lecciones/fichas-lectura-cod-imagenes

- (working) https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/fichas-lectura-cod-imagenes.md

**Comment by vgayolrs** [comment]
Me asigno también para darle seguimiento.

**Comment by mdlincoln** [comment]
Hmm, I can't say off the top of my head, but I suspect that the `ph-submissions` site was set up assuming all Spanish lessons are translations. I did a lot of work on _this_ repository to get it to be language agnostic but didn't migrate all of it over to `ph-submissions` yet. We definitely should make the submissions language agnostic - I'll open a ticket over there and look at how hard it would be to get it set up.

**Comment by arojascastro** [comment]
Thank you @mdlincoln - take it easy, you must be moving away if I am not wrong and that it takes a lot of time and effort

**Comment by mdlincoln** [comment]
I've updated the includes so that the figures ought to now show up for all lessons. You will noticed that I removed most of the metadata displays from the preview pages because they are extremely intricate and didn't make sense to try and maintain for these previews, which just focus on lesson content display and line numbering.

**Comment by arojascastro** [comment]
Many thanks @mdlincoln
