### ISSUE TITLE
Labels on Submissions repository

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#968]
Hi, 

I would like to discuss about the labels used in the submission repository: 

![captura de pantalla 2018-08-06 a las 17 51 22](https://user-images.githubusercontent.com/7340111/43727224-a954731e-99a1-11e8-9284-0849cc40b809.png)

Should we have labels for submissions and translations in each language (e.g. `spanish translation`, `english submission`, `spanish submission`) or use a combination of language label  (`spanish`, `english`) plus submission (`submission`) or translation label (`translation`)?  

Can we reflect on this in the following days? There might be other options, feel free to add different suggestions.

**Comment by walshbr** [comment]
That's a good point. I think your proposal to have a language label separate from a submission proposal makes a lot of sense.

**Comment by vgayolrs** [comment]
Agree w/ @walshbr . The second option is more practical. If not, we will be full of specific labels.

**Comment by jamotilla** [comment]
It´s a good idea, i think the second option (submission + language label) is better

**Comment by mdlincoln** [comment]
I also vote for second option.

**Comment by acrymble** [comment]
Just a quick note that I think I changed some of these in the past and it screwed things up. So @mdlincoln would have to check that isn't going to be the case again. I can't remember what the problem was, but it is in the back of my mind that it did cause an issue.

**Comment by arojascastro** [comment]
Just to be clear you prefer:

- spanish + submission
- spanish + translation

rather than 

- spanish submission
- spanish translation 

Right?

**Comment by arojascastro** [comment]
done here! https://github.com/programminghistorian/ph-submissions/labels

you can check the colors if you want or add descriptions for clarification - i'm closing!
