### ISSUE TITLE
Move large assets to Git Large Storage file tracking

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#97]
We have this enabled on our account now. Here are the instructions I got from GitHub by email:

---

It's time to start versioning large files on GitHub.com! Support for Git LFS is
now enabled for your organization: programminghistorian.

## Getting started

1. Download and install the Git command line extension. You only have to set up
   Git LFS once, but make sure you've got the latest release (v0.5.1) installed.

     Mac - https://github.com/github/git-lfs/releases/download/v0.5.1/git-lfs-darwin-amd64-0.5.1.tar.gz
     Windows - https://github.com/github/git-lfs/releases/download/v0.5.1/git-lfs-windows-amd64-0.5.1.zip
     Linux - https://github.com/github/git-lfs/releases/download/v0.5.1/git-lfs-linux-amd64-0.5.1.tar.gz
     Full list of pre-built binaries - https://github.com/github/git-lfs/releases/latest

2. Select the file types you'd like Git LFS to manage (or directly edit your
   .gitattributes). You can configure additional file extensions at anytime.

    git lfs track "*.psd"

3. Commit and push to GitHub.

    git add file.psd
    git commit -m "Add design file"
    git push origin master

### Storage and bandwidth

Your account includes 1GB of storage and 1GB/month of bandwidth for no
additional charge. If you need more data, you can upgrade your plan at any time:

https://github.com/organizations/programminghistorian/settings/billing

### Technical support

If you need help with any technical or billing-related issues, please check out
our documentation:

https://help.github.com/articles/versioning-large-files/

You can also email us at: git-lfs@github.com.

Thanks,

The Git LFS Team

**Comment by wcaleb** [comment]
By the way, are there current assets that we are hoping to upload using this? Trying to get a sense of how urgent this is, and whether anyone is waiting on it currently.

**Comment by acrymble** [comment]
The only one I know of is in the OpenRefine lesson. The second link doesn't
work:

The data files are available on our FreeYourMetadata website
<http://data.freeyourmetadata.org/powerhouse-museum/>, which will be used
throughout this tutorial. Please download the *phm-collection.tsv* file
before continuing (also archived on the Programming Historian site: as
phm-collection <http://programminghistorian.org/images/phm-collection.tsv>).

**Comment by fredgibbs** [comment]
i don't know of any other big data files we need to move. i think it was
more for future development than an urgent fix (adam's issue aside).

On Mon, Jun 1, 2015 at 10:52 AM, Adam Crymble <notifications@github.com>
wrote:

> The only one I know of is in the OpenRefine lesson. The second link doesn't
> work:
>
> The data files are available on our FreeYourMetadata website
> <http://data.freeyourmetadata.org/powerhouse-museum/>, which will be used
> throughout this tutorial. Please download the *phm-collection.tsv* file
> before continuing (also archived on the Programming Historian site: as
> phm-collection <http://programminghistorian.org/images/phm-collection.tsv
> >).
>
> On Mon, Jun 1, 2015 at 5:48 PM, W. Caleb McDaniel <
> notifications@github.com>
> wrote:
>
> > By the way, are there current assets that we are hoping to upload using
> > this? Trying to get a sense of how urgent this is, and whether anyone is
> > waiting on it currently.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/programminghistorian/jekyll/issues/97#issuecomment-107633202
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/programminghistorian/jekyll/issues/97#issuecomment-107635234>
> .
>



-- 
frederick w gibbs | assistant professor of history | univ. of new mexico
fredgibbs.net | @fredgibbs
<http://www.twitter.com/fredgibbs>

**Comment by acrymble** [comment]
It seems we've covered this migration. Reopen if you need to.
