### ISSUE TITLE
Update metadata block examples in Spanish guidelines for authors

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/jekyll#972]
I think both examples are outdated: https://programminghistorian.org/es/guia-para-autores#a%C3%B1ade-un-bloque-de-metadatos

**Comment by acrymble** [comment]
this is also out of date for English:

<img width="724" alt="screen shot 2018-08-21 at 08 48 30" src="https://user-images.githubusercontent.com/646647/44388068-11713080-a51f-11e8-84ea-7ed5740ae8fe.png">

**Comment by acrymble** [comment]
This is a blank version of what we have on the English site. Could we use this? I've added in translation yaml categories.

```
title: ["YOUR TITLE HERE"]
collection: lessons
layout: lesson
slug: [the file name, without the .md on the end]
date: [LEAVE BLANK]
translation_date: [LEAVE BLANK]
authors:
- [FORENAME SURNAME 1]
- [FORENAME SURNAME 2, etc]
reviewers:
- [LEAVE BLANK]
editors:
- [LEAVE BLANK]
translator:
- [FORENAME SURNAME 1]
translation-editor:
- [LEAVE BLANK]
translation-reviewer:
- [LEAVE BLANK]
review-ticket: [LEAVE BLANK]
difficulty: [LEAVE BLANK]
activity: [LEAVE BLANK]
topics: [LEAVE BLANK]
abstract: [LEAVE BLANK]
```
