### ISSUE TITLE
Dinner in London?

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#977]
@amsichani and I wondered if there might be interest for some of us to get together and have dinner in London, maybe in September/October? I know not everyone would be able to make it, but we had so much fun in Colombia getting to know each other, that I thought it might be a good way to team build, and maybe even spend a day working on some issues that would be easier to tackle by a team in the same room?

I'll just open this to see if there's any interest from those of you sort-of-nearby.

**Comment by amsichani** [comment]
count me in. I can help with the logistics, aka offering my living room for the occasion ;-)

**Comment by drjwbaker** [comment]
Love to. Great idea.

**Comment by acrymble** [comment]
Great. Is this viable for any of our European friends? @spapastamkou @mpuren or @arojascastro ?

**Comment by arojascastro** [comment]
I'd love to!

**Comment by amsichani** [comment]
I can also offer a spare room, if needed ! +my culinary skills

**Comment by mariajoafana** [comment]
I wish I could join you guys!

**Comment by spapastamkou** [comment]
this is a great idea, thanks for this @acrymble. I am afraid though that September is utterly impossible for me. If in October, do you think this dinner/work session could be combined with one in Lille, if members of the PH come for the workshop?

**Comment by acrymble** [comment]
Thanks @spapastamkou, good idea. That Lille Workshop is 15-17 October (Monday-Wednesday). Is the acceptance of your workshop already confirmed? Or is it pending acceptance?

We could do a London event any time really. October, November. Whatever.

**Comment by acrymble** [comment]
I'll do a doodle poll in september for this (probably to hold in October/November)

**Comment by acrymble** [comment]
Doodle poll has been sent via email. Will close this now.
