### ISSUE TITLE
revision of contribute (overview)/contribuciones/contribuer page

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/jekyll#979]
This is for all. 
The "Translate a lesson" section of the Contribute page https://programminghistorian.org/en/contribute#translate-a-lesson takes into account only the EN and ES versions of the PH. 
Would someone be able to work with me on a new formulation that would be more adapted to the existence of a FR version?

**Comment by spapastamkou** [comment]
I prepared a draft that follows exactly the existing formulation with addition of FR parts. I am not very happy about it but we could perhaps start work on this basis? 

"If you are fluent in both English and Spanish or in English and French, you are invited to get in touch with us about translating one of our published Programming Historian lessons into Spanish or French. This will help us to build Spanish-language and French-language digital humanities communities, and to build your language, method, and technological skills.

We are seeking rigorous and readable translations that take into account the Spanish-language and the French-language research contexts and the resources available in our respective communities. If you are interested in collaborating, consult our instructions for authors and translators in Spanish and in French".

**Comment by acrymble** [comment]
It should be language neutral because we don't want to privilege English.

If you are fluent in more than one of our supported languages (French, English, Spanish)...

**Comment by spapastamkou** [comment]
I take care of that this week as I am at the point of finishing 2 translations (of which one is the relevant page)

**Comment by spapastamkou** [comment]
New proposal: 

"If you are fluent in more than one of our supported languages (French, English, Spanish), you are invited to get in touch with us about translating one of our published Programming Historian lessons from one language to another. This will help us to assist building Spanish-language and French-language digital humanities communities, and to build your language, method, and technological skills.

We are seeking rigorous and readable translations that take into account the Spanish-language and the French-language research contexts and the resources available in our respective communities. If you are interested in collaborating, consult our instructions for authors and translators in Spanish and in French".

**Comment by acrymble** [comment]
Thanks @spapastamkou this looks good. I think in future we will want to encourage the translation of Spanish and French materials into English, but maybe we don't need that yet.

**Comment by amsichani** [comment]
Hey @spapastamkou, as far as I can see you ve proposed a new version of the text on the "translate a lesson" section of Contribute page & you ve got positive feedback on this. We haven't really discussed this during #1011 as the procedure is pretty much straightforward , I guess.
Next steps are 1)to secure a ES and a FR translation of this text, before 2)submitting a PR for all the languages' pages adequately. Hope that helps!

**Comment by jenniferisasi** [comment]
That text looks great! 
I will do the translation/edit in the Spanish version. Shall we wait till the French version launches? That's the only thing that kept me from doing the changes already.

**Comment by spapastamkou** [comment]
Cool, thank you both, I preferred to be sure:) I propose that you do not
wait for the launch of the FR web site to do the translation. I have
already used this version of the text in the FR file, so once published the
FR web site will be in lines with the rest.

**Comment by acrymble** [comment]
@spapastamkou if you close this ticket right now, nothing will be changed. You first have to make the changes in a pull request. Only close the ticket once the change is finished. otherwise it disappears and everyone forgets about it.

**Comment by spapastamkou** [comment]
Oops, sorry, let's keep it open then.

**Comment by spapastamkou** [comment]
Hey @programminghistorian/spanish-team, could someone please translate in Spanish in the `french-staging` branch? (I also pin shamelessly @jenniferisasi :-))

Small reminder: 
- it is about modifying (partly) this part https://programminghistorian.org/es/contribuciones#traduce-una-lecci%C3%B3n 

- the text to insert is the following:
"If you are fluent in more than one of our supported languages (French, English, Spanish), you are invited to get in touch with us about translating one of our published Programming Historian lessons from one language to another. This will help us to assist building Spanish-language and French-language digital humanities communities, and to build your language, method, and technological skills.

We are seeking rigorous and readable translations that take into account the Spanish-language and the French-language research contexts and the resources available in our respective communities. If you are interested in collaborating, consult our instructions for authors and translators in Spanish and in French".

Thanks in advance, I will then be able to close the ticket.

**Comment by jenniferisasi** [comment]
I have update our contributions file with the new text (sorry I had forgotten about it), using the `french-staging` branch but no pull-request is showing...

**Comment by mdlincoln** [comment]
@jenniferisasi that is normal - if you look now on the pull request, you'll see that your commit has been added to the total changes in that PR

![](https://screenshotscdn.firefoxusercontent.com/images/138f6803-0088-4cc7-adc3-0172ffb113c5.png)

**Comment by spapastamkou** [comment]
thank you very much @jenniferisasi :)
