### ISSUE TITLE
Update Ombudsperson list

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#982]
https://programminghistorian.org/en/reviewer-guidelines
https://programminghistorian.org/en/editor-guidelines

Ian Milligan is still listed on here. He needs to be removed from here and anywhere else he's listed as an ombudsperson.

---

It also looks like the Spanish version of the site lists 3 people, but only @mariajoafana is listed on the project team as an ombudsperson.

https://programminghistorian.org/es/guia-para-revisores

**Comment by acrymble** [comment]
This has been amended.

**Comment by arojascastro** [comment]
Thanks! Yes, she was the only one I think.
