### ISSUE TITLE
Managing Editor transition (ES/EN)

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#983]
On 1 September 2018, the managing editor roles will shift to the following people

* @mariajoafana (Spanish)
* @alsalin (English)

The technical changes required of the handover are listed on the wiki: https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover

The pages listed at that link will need to be updated at that time.

Since @mariajoafana is also the Spanish ombudsperson, I suggest that she should pass on that role (and update any relevant templates or pages to reflect that) See #982 - Update Ombudsperson List.

If there are any other steps required to hand over these roles, can @JMParr or @arojascastro remind us? I believe there might be a Google Gmail account?

**Comment by JMParr** [comment]
No Google or Gmail account.

**Comment by alsalin** [comment]
will the incoming folks make these changes? if so, when should we plan on making them?

**Comment by acrymble** [comment]
Why don't you do it on 1 September? Or as close as possible?

If you need help just let us know

**Comment by JMParr** [comment]
We've already agreed on Sept 1st as the switch.

**Comment by acrymble** [comment]
On a related topic, I think it would improve the consistency of our publishing and promotion if the managing editor did all actual lesson publishing (eg, the final pull requests). Is this something you'd feel comfortable with @alsalin and @mariajoafana ?

**Comment by alsalin** [comment]
@acrymble to make the edits listed in the link above? i'd be happy to!

**Comment by acrymble** [comment]
No, I meant that when a lesson has been peer reviewed and is ready to publish, would you be willing and able to actually do that? Note it's a fiddly process and because most people only do 1-2 a year it can be really frustrating (see @JMParr right now struggling with one). I just thought maybe if that was part of someone's role it would be easier because they'd have more experience with it.

Just an idea for reducing general stress!

**Comment by alsalin** [comment]
@acrymble ah! thanks for the clarification. I'd be ok with that as long as I could ask a thousand questions for the first attempt or so.

**Comment by acrymble** [comment]
Of course. That's what we're all here for. Maybe we can try it the first time something is ready and we can decide from there.

**Comment by acrymble** [comment]
What I'm proposing would mean the Managing Editor would do the following steps for each lesson being published (as written in the Editor's guidelines):

1 -  Move the Files

11 -  Confirm all links and YAML headers are functioning correctly

We'd just have to extract those two steps to a "Managing Editor Responsibility" section, and add in a note at the bottom of the current text that says "Inform the managing editor of all the files involved in the lesson so she can publish them...".

The advantages of this are that the Managing Editor gets good at using Github pull requests and no one else really has to (I know from talking to other editors that many people hate this with a passion). It also means that the Managing Editor has intellectual insight over the whole project's content, and is a fresh set of eyes that can help us maintain standards and consistency when publishing.

**Comment by JMParr** [comment]
I would endorse this as the outgoing ME. I wish I were much better at
Github.

**Comment by acrymble** [comment]
I've added @alsalin the Managing Editor as listed on Wikipedia. You'll just have to change the contact info on the pages listed here to complete this changeover: https://github.com/programminghistorian/jekyll/wiki/Managing-Editor-Handover

**Comment by acrymble** [comment]
We're ready for this switch now @alsalin. did you want me to update the files, or would you like to practice the pull requesting?

**Comment by alsalin** [comment]
@acrymble great timing! i'm just adding my changes now and hopefully not breaking everything.

**Comment by alsalin** [comment]
@acrymble also, should the GH readme get added to the list for editing as well?

**Comment by acrymble** [comment]
yes I suppose so.

**Comment by alsalin** [comment]
@acrymble many thanks for double checking all this!

**Comment by acrymble** [comment]
@alsalin great work.
@mariajoafana you'll have to update the files as well, with your own contact details. Let me know if you need help.

Then we can close this ticket.
