### ISSUE TITLE
Author of Counting Frequencies needs a bio

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/jekyll#99]
We don't have him listed in `_data/authors.yml`, so nothing shows up under "About the author."

**Comment by wcaleb** [comment]
Connected to #83; perhaps we need someone to do a review to see which authors we are still missing bios for, while at the same time adding info for email, twitter, github, website, etc. to authors directory (as much as each author wants to provide).

**Comment by ianmilligan1** [comment]
I can send Spencer a quick note and doublecheck a potential bio statement. Perhaps:

Spencer Roberts is Research Assistant and former Digital History Research Fellow at the Roy Rosenzweig Center for History and New Media, and a Ph.D. graduate student at George Mason University in the Department of History.
