### ISSUE TITLE
Shorten Editorial Guidelines

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#992]
Pending the outcome of the following tickets: 

#991 - New Lesson Template
#972 - Update Metadata example in Auhor Guidelines

We could reduce the number of steps in the Editorial Gudelines, which are becoming dauntingly long, and a number of editors have found it difficult or have missed steps when trying to publish lessons. In particular, the "Acceptance and Publication" checklist, which currently has 12 items:

```
    1) Move the Files
    2) Create an Author Bio
    3) Add a table of contents to the lesson
    4) Add reviewers and editors to the YAML file
    5) Add a difficulty indicator to the YAML file
    6) Add the review ticket URL to the YAML file
    7) Update the date field in the YAML file
    8) Other lesson YAML finalization
    9) Find an Image to represent the lesson
    10) Incorporate your lesson into our Twitter bot
    11) Confirm all links and YAML headers are functioning correctly
    12) Thank Everyone and Encourage Promotion
```

---

Propose Following Changes to those sections:

| Section | Solution |
|:---:|:---:|
| 1) Move the Files | Move to "Managing Editor" checklist - see #983 - Managing Editor transition. This would become the "Managing Editor's" responsibility |
| 2) Create an Author Bio | no change |
| 3) Add a table of contents to the lesson | Add table of contents to the lesson - see #991 - added to new lesson template and included by authors from the start.|
| 4) Add reviewers and editors to the YAML file | condense with 4, 5, 6, 7, 8, into "verify YAML data" step to make it look less daunting|
| 5) Add a difficulty indicator to the YAML file | condense with 4, 5, 6, 7, 8, into "verify YAML data" step to make it look less daunting |
| 6) Add the review ticket URL to the YAML file | condense with 4, 5, 6, 7, 8, into "verify YAML data" step to make it look less daunting |
| 7) Update the date field in the YAML file | condense with 4, 5, 6, 7, 8, into "verify YAML data" step to make it look less daunting|
| 8) Other lesson YAML finalization | condense with 4, 5, 6, 7, 8, into "verify YAML data" step to make it look less daunting|
| 9) Find an Image to represent the lesson | no change |
| 10) Incorporate your lesson into our Twitter bot | no change |
| 11) Confirm all links and YAML headers are functioning correctly | Move to "Managing Editor" checklist - see #983 - Managing Editor transition. This would become the "Managing Editor's" responsibility  |
| 12) Thank Everyone and Encourage Promotion | no change. |

---

```
So the new section would be:

    1) Create an Author Bio
    2) Verify YAML data
    3) Find an Image to represent the lesson
    4) Incorporate your lesson into our Twitter bot
    5) Ask the Managing Editor to verify and publish the lesson
    6) Thank Everyone and Encourage Promotion
```

and the Managing Editor Section would be:

```
   1) Look over the preview for any obvious errors.
   2) Move the Files
   3) Confirm all links and YAML headers are functioning correctly
   4) Inform lesson editor that the lesson is published.
```

**Comment by arojascastro** [comment]
I like it, it would make everything simpler for most of editors, but this means that the managing editor has to invest more time and effort. I guess the upcoming managing editors should be aware of this. Otherwise, lessons will be stuck in the pipeline.
