### ISSUE TITLE
Page of lessons we'd like to see

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/jekyll#995]
Suggestion coming out of our community survey #576:

- maybe list lessons you would like filled so that less confident authors might feel inclined to write one or collaborate with someone else

We have this on our blog from time to time, but I think this is a good suggestion. To make it easier to keep in sync, I suggest 1 page for all 3 languages, listed by "Requests from X Team".

**Comment by acrymble** [comment]
I propose linking to this on the contribute menu and in the author's guidelines.

Going back through our blog posts, we already have a number of requests out there, but they may be easy to miss.

## English Project - Requested Lessons
The English-language editorial team is interested in hearing from prospective authors for the following lessons:

1) What can you conclude from topic models?

We requested this back in early 2017, but no one has yet written it, so we’re putting out the plea again: we’ve got a great lesson on how to conduct a topic model using MALLET. It’s been extraordinarily popular over the years. But we’re still not seeing enough historians (and humanists) actually publishing topic-model-based research results. If you’ve done so, please write us a tutorial on how others can do so too. This is a great opportunity to share the HOW of your article (all the bits the peer reviewers told you to take out so you could focus on the WHAT).

2) How do you conduct spatial clustering of geographic data?

Another re-request from our wish-list in 2017. We’ve got a great set of introductory mapping lessons, and while they are great for teaching how to make nice visualisations, we’ve not yet branched deeply enough into more advanced analysis skills. One of the most useful is the application of clustering algorithms, which identify logical groups of individual points in geographic space. Useful for forming conclusions on anything from trade to migration. But like with all analyses, it’s a space (no pun intended) fraught with pitfalls for the uninitiated. We’re looking for a great introduction that highlights both the strengths and the challenges of this form of analysis.

3) When do you know your network analysis is meaningful?

Again, one that we asked for previously, but haven’t yet seen. Ok, so we’ve built a great network diagram. How do we move to the next step and form meaningful conclusions? This is about starting with a graph and shifting into analysis mode. If you can help our readers take that step, we want to hear from you.

4) TF-IDF to Historical Research

And the last of our unfulfilled requests: let’s talk about meaningful words. Term Frequency - Inverse Document Frequency is a well known means of identifying words that appear more often than we might expect in a given document. It’s one of the ways we know what a document is about. Let’s take this to the next step and teach readers how this fairly simple statistic about meaningful words can turn into meaningful research outputs. If you’ve published on historical lingustics (as in #1 above), we’d love to hear from you on the HOW TO of your wonderful paper.

5) Space Syntax of Historical Data

After having seen a great workshop by Katrina Navickas on Space Syntax we’d like to learn more about it and how historians can apply this geographical approach in their research.

6) How to Publish Digital Scholarly Editions using a Native XML Database

Digital scholarly editions are often modelled as XML documents. Although there are some publication tools such available, the options can be bewildering and the solutions may not fit a user’s particular needs. Keeping with our open ethos, we’d like to see someone take readers through an open source solution that gives them a sustainable and flexible way to publish their digital edition.

7) How to Analyse Audio Artefacts We have one lesson on how to use Audacity to edit audio files and another on how to transform you transform your data into audio to better understand it. But you can do much more! How are you using tools to get quantifiable data about your audio artefacts? Or, how can you use machine learning techniques to produce new understandings of an audio collection?

## proyecto español-lecciones solicitadas
El equipo editorial de habla español está interesado en escuchar a los posibles autores para las siguientes lecciones:

...

**Comment by acrymble** [comment]
I will publish this soon. Can someone from the Spanish team add 1 or 2 requests so it looks balanced? @vgayolrs @mariajoafana @jenniferisasi @jamotilla

**Comment by acrymble** [comment]
Ok, I'm going to publish this without Spanish suggestions at this time. We can update this if and when the Spanish team decides to suggest topics.

**Comment by jenniferisasi** [comment]
Thank you Adam. Yes, please go ahead without suggestions in Spanish, as we have some of the firts originals in the making for now.
